// The Blood Debt: an ancient crime was never paid for, and the curse rides the bloodlines that descend from it.
export default {
  id: "blood_debt",
  name: "The Blood Debt",
  kind: "history",
  family: "world",
  pitch: "The founders of the great houses committed a massacre that was never paid for. Their descendants carry a curse, and through bastards and marriages it is spreading to everyone.",
  slots: ["bloodline", "history-secret"],
  tone: ["grim", "melancholy"],
  era: ["bronze", "medieval", "renaissance", "industrial"],
  scale: "regional",
  genres: ["fantasy", "grimdark", "flintlock", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "ward_walls", w: 2.5 }, { id: "gods_twilight", w: 2 }, { id: "unquiet_gate", w: 2 }, { id: "body_of_the_world", w: 1.2 }],

  cast: [
    { role: "investigator", n: "a sworn genealogist of the guild that keeps the true family trees", home: "capital", stance: "Wants to know whose blood the mark came from, and is starting to read the pages the guild burned." },
    { role: "official", n: "the royal chronicler, keeper of the founders' history", home: "capital", stance: "Holds that the founders won the land in honest war, and that the realm needs that to be true." },
    { role: "believer", n: "a hill claimant descended from the slaughtered hosts", home: "mountain", stance: "Wants the land, the names and the apology, and believes the curse will end when they are given." },
    { role: "survivor", n: "a marked commoner whose village was burned by the Purge", home: "remote", stance: "Never barred a door on anyone, and wants to know why their children paid." },
  ],

  truths: [
    { id: "original_sin", n: "The debt is owed to the wronged", d: "The founders of the great houses came to the hills as refugees and were taken in by the hill people. At the midwinter feast they barred the doors, burned their hosts alive and took the land. The curse in their blood is the victims' vengeance, and it ends only with restitution: the land, the names and the apology the founders refused. So far every heir has chosen to die young instead.", tags: ["truth:debt_restitution"],
      known: [
        "Every great house holds a feast on the same midwinter night and bars its doors at midnight. The royal chronicle says the founders won the land in honest war against hill tribes who attacked them first.",
        "Hill folk leave salt and bread on a cairn at a high pass, and their lament asks for the burners to kneel. The cairn names fourteen families; {investigator} matched them to the fourteen great houses of today.",
        "A burnt hall in the hills was barred from the outside, with 412 bodies under its floor and a carving inside the doors: the hosts fed the founders, gave them beds, and were burned for it.",
        "Confirmed: the founders burned the people who sheltered them and took their land. The curse is the victims' vengeance, and it ends with restitution: the land, the names and an apology at the hall. No king has paid.",
      ] },
    { id: "bargain", n: "The curse is the interest", d: "The founders bought their strength, luck and long rule from an ancient power, and signed for it with the later years of every heir. That is why the marked are strong and die before forty. The debt has compounded for centuries and is almost due in full, and each new heir still signs.", tags: ["truth:debt_bargain"],
      known: [
        "The marked are stronger, luckier and quicker than other people, and they die before forty, on days a physician could almost predict. The temples call it the gods' sorrow for the weight of rule.",
        "In a great house's gallery, the ancestors' portraits have aged since they were painted, and the oldest have no faces left. The founding-year accounts of all fourteen houses record the same payment: 'one generation'.",
        "{investigator} found a contract behind the founder's portrait, written in red-brown ink and signed by every heir, each name beside a figure in years. The figures grow with each signature.",
        "Confirmed: the founders bought strength, luck and rule from an old power with their heirs' later years. Each marked heir pays in life, the debt is nearly due in full, and the houses are still signing.",
      ] },
    { id: "shield", n: "The curse is a ward", d: "The curse is not a punishment. It is a seal on a pit where a creature is locked, and the marked bloodlines are the lock. Every marked line that is burned or cured weakens the seal, and the Purge has been burning marked villages for decades to make the realm clean.", tags: ["truth:debt_ward"],
      known: [
        "The Purge burns marked commoners for the good of the realm and leaves marked nobles alone. A marsh-healer who lifts the mark warns that it has to sit on someone, and it reappears in the next village.",
        "At a stone in a ring of thorn, the marked pray for release. The words on it are a binding, with a list of what is bound, and there is knocking from a sealed pit beneath it.",
        "A Purge inquisitor told {investigator} that the knocking in the pit grew louder with every village burned, thirty in six years. The bishop's answer was to burn faster, and to keep the nobles' marked lines off the lists.",
        "Confirmed: the mark is a lock. The founders bound a creature in the pit and tied the binding to their own blood. Every marked line burned or cured weakens the seal, and the Purge is breaking it village by village.",
      ] },
  ],

  tags: ["blood_curse"],

  subthemes: [
    { id: "heir_marked", n: "The Marked Heir", d: "The heir has come of age and the mark has appeared: a red seam along the palm, and dreams of a burning hall. The court has bought a lot of gloves.", w: 1.4, req: "monarchy", mods: [["origin:old_dynasty", 3], ["hierarchical", 1.5]], tags: ["theme:heir_marked"] },
    { id: "common_spread", n: "The Spreading Mark", d: "The mark is showing up in villages that have no noble blood at all, or think they have none. The genealogists have a great deal of explaining to do.", w: 1.1, mods: [["poor", 1.3], ["unstable", 1.3]], truthLink: "shield", tags: ["theme:common_spread"] },
    { id: "curse_marriage", n: "The Poisoned Match", d: "An alliance marriage has been arranged by genealogists to dilute the curse, or to concentrate it. The bride's family do not know which.", w: 1, req: { any: ["dynastic", "monarchy"] }, tags: ["theme:curse_marriage"] },
    { id: "victim_heir", n: "The Claimant from the Hills", d: "A hill-woman claims descent from the slaughtered people and a right to the throne. The curse marks fade in her presence.", w: 0.9, req: { any: ["monarchy", "mountain", "hills"] }, truthLink: "original_sin", tags: ["theme:victim_heir"] },
    { id: "purge_inquisition", n: "The Purge", d: "Inquisitors hunt marked commoners, burning them for the good of the realm. The marked nobles are not touched.", w: 1.1, req: { any: ["zealous", "harsh_law", "theocratic", "militant"] }, truthLink: "shield", tags: ["theme:purge_inquisition"], mark: { kind: "zone", n: "Burned villages", color: "#5a3a2a", size: [1, 2], where: "any" } },
    { id: "years_for_power", n: "The Short-Lived Strong", d: "The marked are stronger, luckier and quicker than other folk, and they die before forty. Armies love them.", w: 1, req: { any: ["martial", "warrior_code", "standing_army"] }, truthLink: "bargain", tags: ["theme:years_for_power"] },
    { id: "crime_restaged", n: "The Feast Restaged", d: "Someone is re-enacting the old crime: a feast, a betrayal, a hall set burning, each year at another great house.", w: 0.7, req: "monarchy", truthLink: "original_sin", tags: ["theme:crime_restaged"] },
    { id: "cure_rumour", n: "The Rumoured Cure", d: "A hedge-healer in the marshes is said to lift the mark. The people she cures recover. Soon after, the mark appears in the villages around them.", w: 0.9, truthLink: "shield", tags: ["theme:cure_rumour"] },
    { id: "empty_tomb", n: "The Empty Mausoleum", d: "A great house opened its family tomb for a funeral and found every coffin empty, back to the founder.", w: 0.8, req: { any: ["ancestor_bound", "origin:old_dynasty", "faith:ancestors"] }, truthLink: "bargain", tags: ["theme:empty_tomb"] },
    { id: "blighted_seat", n: "The Blighted Seat", d: "The fields around a cursed house's seat yield nothing but thistles and rain falls there every day of the year.", w: 1, mods: [["origin:old_dynasty", 2], ["hierarchical", 1.3]], tags: ["theme:blighted_seat"], mark: { kind: "zone", n: "The rain-blight", color: "#4a5a4a", size: [1, 2], where: "capital" } },
    { id: "genealogists", n: "The Genealogists", d: "A sworn guild keeps the true family trees: who is marked, who is not, and who is a secret branch. They are feared more than the tax collectors.", w: 1.2, req: { any: ["hierarchical", "scholarly", "monarchy"] }, tags: ["theme:genealogists"] },
  ],

  sites: [
    { id: "desecrated_temple", n: "The Burnt Hall of $", kind: "ruin", where: "remote", truthLink: "original_sin", d: "The ruined hall where the founders slaughtered their hosts.",
      layers: {
        surface: { n: "Black with fire", text: "A roofless hall stands in the hills above {place}, its stones black with old fire. Nothing nests in it, not even crows. Shepherds go a day's walk out of their way to pass it, and say their dogs will not cross the threshold." },
        study: { n: "Barred from outside", text: "The great doors were barred from the outside; {investigator} found the iron brackets bent inward by pressure from within. The guest tables still stand in twelve rows, set for a feast, with the bowls in place." },
        dig: { n: "The banner shroud", points: "site:victims_tomb", text: "Under the floor lie 412 bodies. Among them is the founders' own banner, used as a shroud by someone who came later to bury the dead. Stitched on its hem in hill script is a name, the same name carved on the cairn at {lead}." },
        revelation: { n: "Founded on a feast", text: "The founders came to these hills as refugees, and the hill people fed them and gave them beds. At the midwinter feast the founders barred the doors, burned their hosts alive, and took the land. Every great house descends from the men who held the bars. Every great house still holds a midwinter feast." },
      } },
    { id: "genealogy_vault", n: "The Vault of Lines at $", kind: "dig", where: "capital", d: "The genealogists' vault, with whole pages burned out of the family trees.",
      layers: {
        surface: { n: "Guarded day and night", text: "A locked archive lies under the genealogists' guild house in {place}, guarded day and night by six sworn men. It holds the true family trees: who is marked, who is not, who is a secret branch. Nobles pay fifty crowns to see their own page." },
        study: { n: "The burned generation", text: "{investigator} compared every great house's tree. In each one the same generation has been burned away, the third from the founders, as cleanly as with a hot iron. The guild's own index says only 'damaged by damp'." },
        dig: { n: "The copy in the wall", points: "archive", text: "A surviving copy, hidden in a wall cavity, shows the burned generation: every heir married to a bride or groom 'of the hills', all fourteen weddings on one day. The guild's marriage register for that day should be in {lead}." },
        revelation: { n: "One wedding day", text: "Three generations after the founding, by royal order, every great house married into the surviving hill families on one day, to end the hill claims by law. The guild burned the page so the houses could call their blood unmixed. Every marked shepherd in the hills is cousin to a duke, and the guild has the list." },
      } },
    { id: "changing_gallery", n: "The Portrait Gallery of $", kind: "anomaly", where: "capital", truthLink: "bargain", d: "A gallery of ancestral portraits whose faces change.",
      layers: {
        surface: { n: "Dust sheets", text: "A long gallery of ancestors in the great house at {place} is kept under dust sheets. The servants uncover it once a year, for the heir's birthday. Thirty-one portraits hang there, from the founder down to the heir's mother." },
        study: { n: "Faces that age", text: "Each face has aged since it was painted; {investigator} checked them against the painters' sketches in the house accounts. The oldest have no faces left, only canvas the colour of skin. The heir's mother aged five years last winter." },
        dig: { n: "The red-ink contract", points: "archive", text: "Behind the founder's portrait is a contract in red-brown ink, with a column of signatures down the years, one per heir. The latest signature is still tacky. The house steward filed a copy of the contract's terms in {lead}." },
        revelation: { n: "Paid in years", text: "The founders bought strength, luck and long rule from an old power, and every heir since has signed away their later years to pay for it. That is why the marked die before forty. The contract's last clause says the debt is nearly settled, and that the final payment is the whole of the next heir's life." },
      } },
    { id: "curse_shrine", n: "The Speaking Stone of $", kind: "shrine", where: "remote", truthLink: "shield", d: "The shrine where the curse was first spoken.",
      layers: {
        surface: { n: "The ring of thorn", text: "A worn stone stands in a ring of thorn on a hill near {place}. The marked come here to pray for release and tie red ribbons on the thorns. On one feast day {survivor} counted six hundred ribbons." },
        study: { n: "A binding, not a curse", text: "The words on the stone are not a curse but a binding, with a list of what is bound: tooth, claw, hunger, voice. {investigator} took a rubbing. The script is the genealogists' guild's own oldest hand." },
        dig: { n: "The knocking", points: "archive", text: "Below the stone is a sealed pit with an iron lid. When the marked kneel at the stone, there is knocking from inside, three blows at a time. The Purge's own records of the knocking are kept in {lead}." },
        revelation: { n: "The lock", text: "The mark is a seal. The founders bound a creature in this pit and tied the binding to their own blood, so that while marked families live it stays shut. Every marked village the Purge burns weakens the lock. The knocking has grown louder in each year the inquisitors have worked." },
      } },
    { id: "victims_tomb", n: "The Tomb of the Hosts at $", kind: "shrine", where: "mountain", truthLink: "original_sin", d: "A hill tomb where the slaughtered people's last queen is buried.",
      layers: {
        surface: { n: "Salt and bread", text: "A cairn on a high pass above {place} marks a grave. Hill folk leave salt and bread on it every day, in all weathers. A palace courier once left a gold coin there, and came back the next day to take it away again." },
        study: { n: "Names on the cairn", text: "The cairn's carvings name the slaughtered people's last queen and list, by name, every family that betrayed her: fourteen in all. {investigator} matched all fourteen to great houses of the realm today." },
        dig: { n: "The scale", points: "cast:believer", text: "Among the queen's grave goods is a bronze scale. One pan is empty. The other is heaped with the founders' house-rings, taken from the dead after the feast. The hill claimant, {lead}, says the empty pan is for what is owed." },
        revelation: { n: "A debt with a balance", text: "The curse is the slaughtered hosts' vengeance, carried in the blood of the families on the cairn, and it has a balance. It ends when the houses return the hill land, restore the old names and kneel at the burnt hall. Three kings have read this cairn. None has paid." },
      } },
  ],

  beings: [
    { id: "curse_hound", n: "Debt-hound", kind: "predator", d: "A black, red-eyed hound seen near marked people shortly before they die. No one has ever seen it eat.", danger: 2, biomes: ["tempforest", "grass", "boreal", "swamp"], look: { size: 1.1, group: [1, 1], move: "solo", speed: 14, col: "#1a1010", col2: "#a02020", body: "quad", active: "night", visible: false } },
    { id: "debt_ash_crow", n: "Ash-crow", kind: "bird", d: "Grey crows that gather over cursed seats in great numbers and are said to remember every face.", danger: 0, biomes: ["grass", "tempforest", "swamp", "coldsteppe"], look: { size: 0.5, group: [10, 100], move: "flock", speed: 40, col: "#6a6a6a", col2: "#2a2a2a", body: "bird", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "bd_line_ledgers", n: "Line ledgers", field: "writing", level: 1, d: "Sworn genealogies that track who carries the mark, and who might." },
    { id: "bd_mark_salves", n: "Mark salves", field: "medicine", level: 2, d: "Ointments and gloves that hide the red seam, and draughts that dull the dreams." },
    { id: "bd_blood_reading", n: "Blood-reading", field: "medicine", level: 3, d: "A physician's test that shows the mark in the blood before it shows on the skin." },
    { id: "bd_ward_rites", n: "Ward rites", field: "arcana", level: 4, d: "Rites that move the curse from one bearer to another, or spread it thin across many." },
  ],

  units: [
    { id: "bd_marked_guard", n: "Marked guard", role: "infantry", wpn: "sword", kit: "plate", ranks: 3, gap: 1.3, size: 60, w: 0.5, mods: [["theme:years_for_power", 8], ["warrior_code", 2]] },
    { id: "bd_inquisitors", n: "Purge inquisitors", role: "infantry", wpn: "sword", kit: "mail", ranks: 3, gap: 1.2, size: 70, w: 0.4, mods: [["theme:purge_inquisition", 8], ["militant", 2]] },
  ],

  faiths: [
    { id: "debt_reckoners", n: "The Reckoning", d: "Every crime is a debt, every debt is owed, and the gods are the creditors. Pay, or your children will.", tags: ["faith:reckoning"], w: 0.5, names: ["The Reckoning of $", "The Ledger of the Gods", "The Faith of the Scales"], mods: [["theme:victim_heir", 4], ["just", 2], ["ancestor_bound", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Cursed fiefs", color: "#6a4040", size: [1, 2], count: [1, 3], where: "inner", d: "Estates around the seats of the cursed houses: barren, rain-soaked and full of crows." },
  ],

  storylines: [
    { id: "bd_heir_mark", n: "The Hand of the Heir", scale: "realm", anchor: "realm", w: 1.5, req: ["blood_curse", "monarchy"],
      stages: {
        start: { h: "The mark appears on the heir of {realm}", b: "At the coming-of-age feast, the heir of {realm} took off a glove, and the court saw the red seam across the palm.", wait: [2, 6], fx: { stability: -4 }, next: [{ to: "hidden", w: 1.5 }, { to: "cure_sought", w: 1 }] },
        hidden: { h: "{realm} hides the heir's mark", b: "The heir now wears gloves day and night, and the physicians who saw the mark have retired to distant estates. {investigator}, a genealogist, has been summoned.", wait: [3, 8], next: [{ to: "found_out", w: 1, mods: [["spy_network", 2], ["unstable", 1.5]] }, { to: "early_death", w: 1 }] },
        cure_sought: { h: "{person} rides for the marsh-healer", b: "{ruler} has sent {person} with a sack of gold to the healer in the marshes who is said to lift the mark.", wait: [2, 6], next: [{ to: "cured", w: 1 }, { to: "early_death", w: 1 }] },
        found_out: { h: "The heir's mark is common knowledge", b: "A maid sold the story to a pamphleteer. {capital} is full of talk that the line of {realm} is accursed and must end.", fx: { stability: -15, unrest: 15 }, end: true },
        early_death: { h: "The heir of {realm} dies young", b: "The marked heir died at twenty-six, strong to the last day. A black hound was seen at the gates the night before.", fx: { heir: true, stability: -8 }, end: true },
        cured: { h: "The heir of {realm} is cured", b: "The mark has faded from the heir's hand. In the marsh villages around the healer's hut, children have begun to wake with red seams on their palms.", fx: { stability: 5, unrest: 10, flag: "curse_moved" }, end: true },
      } },
    { id: "bd_restitution", n: "The Debt of {realm}", scale: "realm", anchor: "realm", w: 1, req: ["blood_curse", { any: ["monarchy", "pious", "mountain", "hills"] }],
      stages: {
        start: { h: "A claimant comes down from the hills of {realm}", b: "{believer}, a hill-woman, has come to {capital} with a crowd of followers. {believer} claims descent from the people the founders slaughtered, and demands what the founders' heirs owe that people.", wait: [2, 6], fx: { unrest: 10 }, next: [{ to: "audience", w: 1, mods: [["ruler:just", 3], ["pious", 1.5]] }, { to: "arrested", w: 1.5, mods: [["harsh_law", 2], ["autocracy", 1.5]] }] },
        audience: { h: "{ruler} hears the claim of {believer}", b: "Before the whole court, {believer} named the families of the burnt hall one by one. Every marked noble in the room felt their palm burn.", wait: [2, 5], next: [{ to: "debt_paid", w: 1, mods: [["ruler:just", 2]] }, { to: "refused", w: 1 }] },
        arrested: { h: "{believer} is thrown in the tower", b: "The claimant was seized at the palace gates. That night, every marked noble in {capital} woke screaming.", wait: [1, 4], fx: { stability: -6 }, next: [{ to: "refused", w: 1 }, { to: "debt_paid", w: 0.5, mods: [["unstable", 2]] }] },
        debt_paid: { h: "{realm} pays the old debt", b: "{ruler} returned the hill lands, restored the old names to the maps and knelt at the burnt hall. In the great houses, the red seams are fading.", fx: { stability: 10, prestige: 10, treasury: -60, monument: { tier: 1, name: "The Stone of Restitution" } }, end: true },
        refused: { h: "{realm} refuses the debt", b: "{believer} was sent back to the hills with nothing. Within a year the mark appeared in a dozen new families, and the crows came to {capital}.", fx: { stability: -10, plague: true }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "{official}, royal chronicler", text: "From the Noble Genealogy of {realm}, preface by {official}, royal chronicler, {year}: 'The fourteen great houses of {realm} descend in unbroken honour from the founders, who won the land by the sword from a lawless and savage people. No house has ever been tainted by foreign blood. The short lives of the high born are the price of their service.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "{investigator}, genealogist", points: "site:victims_tomb", text: "A counting-out rhyme of {place}, written down by {investigator} in {year}: 'Red in the palm, black at the door, the lord pays now what the lord owed before.' Whoever the rhyme lands on plays the lord, and has to kneel. Asked where they learned it, they said from the old women who leave bread on the cairn at {lead}, every day, for the last 300 years." },
    { depth: "lore", about: "truth", source: "person", bias: "true", reliable: "partial", who: "A marked noble of the fourth house", text: "Diary of a marked noble of the fourth house, {year}, on the night of the thirtieth birthday: 'I dream of a hall on fire every night. I know the faces at the tables; I could draw them. I have never seen them in my life. The red seam on my palm is a finger longer this year. Father died at 37. I have ordered gloves and a will.'" },
    { depth: "core", about: "truth:original_sin", source: "ruin", bias: "true", reliable: true, plain: true, who: "The hosts, carved inside the burnt hall", text: "Carved inside the barred doors of the burnt hall in hill script, translated by {investigator} in {year}: 'We fed them. We gave them our beds. On the feast night they barred the doors and burned us, 412, and took our land. Let their blood remember what their mouths forget, until they give back the land, our names and their knees.' The cuts are shallow, made with a spoon, from the inside." },
    { depth: "core", about: "truth:original_sin", source: "oral", bias: "true", reliable: "partial", who: "{believer}, hill claimant", points: "site:desecrated_temple", text: "A hill lament sung at the cairn on the pass by {believer}, who claims descent from the slaughtered hosts, {year}: 'Salt on the cairn and bread on the stone, till the burners kneel and our names come home.' The claimant's family has sung it daily for 300 years. The second verse names the hall where the burning was, which stands at {lead}." },
    { depth: "core", about: "truth:original_sin", source: "heretic", bias: "heretic", reliable: "partial", who: "A broadside pasted up in {place}", points: "site:genealogy_vault", text: "Broadside pasted up in {place}, {year}: 'Ask why all fourteen great houses hold a feast on the same midwinter night and bar their doors at midnight. Ask what they are afraid will come in. Then ask the genealogists why the third generation of every family tree is burned away. Their vault is at {lead}.'" },
    { depth: "core", about: "truth:original_sin", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, marked commoner", text: "Letter of {survivor}, a marked commoner, to the claimant {believer}, {year}: 'I am no lord. My mother's grandmother was a lord's bastard, the genealogists say. For that my palm is red, and the Purge burned my village, thirty houses, with my two boys in one of them. I never barred a door on anybody. If kneeling at that hall would end it, I would walk there on my knees. Tell me where to sign.'" },
    { depth: "core", about: "truth:original_sin", source: "archive", bias: "official", reliable: false, who: "{official}, royal chronicler", text: "Royal chronicle of {realm}, the founding year, as recopied by {official} in {year}: 'The hill tribes were subdued in honest war after they treacherously attacked the founders' camp at midwinter. Their dead numbered some hundreds. The founders, in mercy, let the survivors go up into the mountains, and the land passed lawfully to the fourteen houses.'" },
    { depth: "core", about: "truth:bargain", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, genealogist", text: "The contract behind the founder's portrait, copied by {investigator} in {year}: 'For strength in arm, luck in war and crowns on our heads, we give the latter years of every heir. Interest compounds.' Below are 31 signatures in red-brown ink, one per heir, each beside a figure: years paid. The genealogist's note: 'The figures grow with every heir. The founders sold their children's old age, and by my sum the account closes with the next signature.'" },
    { depth: "core", about: "truth:bargain", source: "person", bias: "true", reliable: "partial", who: "A physician to the great houses", text: "Case book of a physician to the great houses of {realm}, {year}: 'They do not die of disease. They simply run out, like a candle cut short, on a day you could almost predict: 38, 36, 35, 33, in the last four heirs of one house. Each was the strongest rider of the season until the week before. I have asked to be excused from the fifth.'" },
    { depth: "core", about: "truth:bargain", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, genealogist", points: "archive", text: "Household accounts of the first great house for the founding year, as found by {investigator}: 'Paid to [name removed], for services: one generation. Balance outstanding: [figure removed].' The same entry appears in the accounts of the other thirteen houses, on the same day, with the same erasures. The unredacted ledger was sent for safekeeping to {lead}." },
    { depth: "core", about: "truth:bargain", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, heir of a great house", text: "Letter of {person}, heir of a great house, to a younger sibling, {year}: 'I signed the paper behind the founder's picture this morning. Father showed me how, with the red ink. The steward says my share is 22 years. I am 19. I will be the best swordsman in {realm} until I am 35, and then I will stop. Do not let them show you the paper. Run.'" },
    { depth: "core", about: "truth:bargain", source: "temple", bias: "official", reliable: false, who: "Sermon at the high temple of {realm}", text: "Sermon preached at the high temple of {realm} on the funeral of a marked heir, {year}: 'The short lives of the high houses are the gods' sorrow for the weight of rule, and no sign of any bargain. This heir gave 34 years to the realm. Talk of contracts and payments is heresy, and the temple will hear no more of it.'" },
    { depth: "core", about: "truth:shield", source: "ruin", bias: "true", reliable: true, plain: true, who: "The speaking stone, copied by {investigator}", text: "Words on the speaking stone, copied by {investigator} in {year}: 'Bound in the blood, bound in the line. While one line lasts, it lies. When the last line breaks, it rises.' Under the verse is a list of nine bound things: tooth, claw, hunger, voice, and five more in an older script. The genealogist's note: 'This is a binding, not a curse. The lines it names are the fourteen houses. The marked are the lock, and the Purge is burning it.'" },
    { depth: "core", about: "truth:shield", source: "person", bias: "true", reliable: "partial", cost: true, who: "A Purge inquisitor, to {investigator}", text: "Confession of a Purge inquisitor to {investigator}, {year}: 'Every village we burned, the knocking under the shrine got louder. Thirty villages in six years. I told the bishop. The bishop said to burn faster. I burned the village of {survivor} myself, children and all. The knocking that night was so loud the horses broke their tethers.'" },
    { depth: "core", about: "truth:shield", source: "oral", bias: "garbled", reliable: "partial", who: "The marsh-healer, as a patient wrote it", points: "site:curse_shrine", text: "The marsh-healer's warning to those who come to be cured, as one patient wrote it down in {year}: 'I can lift it off you. I can't make it go away. It has to sit on someone. Last year I lifted nine, and nine children in the next village woke marked. Pay me in bread, not gold. Better still, go and pray at the stone at {lead}, and leave it where it is.'" },
    { depth: "core", about: "truth:shield", source: "library", bias: "propaganda", reliable: false, who: "Tract of the Purge", text: "Tract of the Purge, printed in {place}, {year}: 'The mark is a corruption of the blood and must be burned out of the realm. Every marked line purged is a step toward a clean people. Thirty villages have been cleansed. Noble houses are exempt by royal warrant, their blood being already in the care of the genealogists.'" },
    { depth: "sub", about: "sub:genealogists", source: "archive", bias: "official", reliable: "partial", who: "{investigator}, genealogist", points: "site:genealogy_vault", text: "From the guild's sworn tree, kept by {investigator}, {year}: 'Line of the fourth house: marked. Branch in the eastern villages: marked, unacknowledged, forty persons. Branch in the royal line: [sealed by order].' A guild clerk has added in the margin: 'Seal broken twice this year. Not by us.' The tree is kept in {lead}." },
    { depth: "sub", about: "sub:years_for_power", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A drover at the ford of {place}", text: "A drover's account of the fight at the ford of {place}, {year}: 'The marked captain killed nine men at the ford and laughed doing it, wet to the waist. Thirty-eight years old. They buried the captain a month later with the sword, and no wound on the body. The regiment asked for another marked officer the same week.'" },
    { depth: "sub", about: "sub:empty_tomb", source: "person", bias: "true", reliable: true, who: "The sexton of {place}", text: "Report of the sexton of {place} to the great house, {year}: 'Opened the family tomb for the old lord's funeral, as ordered. Every coffin empty, thirty of them, back to the founder. Every lid nailed down from the inside. I have nailed the old lord's lid down from the outside, twice, and enclose my bill for the extra nails.'" },
    { depth: "sub", about: "sub:curse_marriage", source: "person", bias: "true", reliable: "partial", who: "A bride in the great house of {place}", points: "site:genealogy_vault", text: "A bride's letter home from the great house of {place}, {year}: 'The genealogist measured my hand before the wedding with a brass rule, palm and fingers, and wrote three numbers in a book that goes back to {lead}. He looked pleased. Mother, what did he see? Nobody here will say whether I was chosen to thin the mark or to thicken it.'" },
    { depth: "sub", about: "sub:common_spread", source: "oral", bias: "true", reliable: "partial", who: "The reeve of {place}", points: "cast:investigator", text: "Talk at the well in {place}, {year}, as the reeve noted it for the genealogists: 'The miller's boy has the red seam, seven years old. The miller swears no lord ever passed through. The miller's wife says nothing at all. That is the fourth marked child here this year, and not one family is on the guild's tree. Sent to the genealogist, {lead}.'" },
    { depth: "sub", about: "sub:crime_restaged", source: "archive", bias: "redacted", reliable: "partial", who: "The watch of {place}", points: "cast:official", text: "Report of the watch of {place}, {year}: 'Fire at the great house during the midwinter feast. Doors barred from outside; twelve guests dead. This is the third house in three years, always at midwinter, always the bars. The royal chronicler has asked that all papers be sent to {lead}, and that the word feast be left out of them.'" },
    { depth: "sub", about: "sub:heir_marked", source: "person", bias: "true", reliable: true, who: "A glover of {place}", text: "Order book of a glover of {place}, {year}: 'For the palace: forty pairs, kid leather, lined, long in the cuff. Same order as last month. Same as the month before. The steward asks that the left palms be cut a little wider. I have not asked why. I have bought a second house.'" },
    { depth: "site", about: "site:changing_gallery", source: "person", bias: "true", reliable: "partial", who: "A housemaid of the great house at {place}", text: "A housemaid of the great house at {place}, to the steward, {year}: 'The old lord's picture smiled when the young lord took sick. I'll swear it on any book you like. I have dusted that gallery twelve years, and they have all got older since I started, every one of the 31. I want my wages and a place in another house.'" },
    { depth: "site", about: "site:victims_tomb", source: "traveller", bias: "true", reliable: true, who: "A traveller on the high pass", points: "cast:believer", text: "A traveller's letter from the high pass above {place}, {year}: 'On the cairn someone keeps a scale of bronze. One pan is empty. The other is piled with fourteen signet rings, and nobody steals them, though one would buy a farm. A hill woman sat by it all day asking passers-by whether they were of the fourteen houses. Ask for {lead}, they told me.'" },
  ],
};
