// The Body of the World: the land is the body of a primordial giant; dead, sleeping, or carrying us somewhere.
export default {
  id: "body_of_the_world",
  name: "The Body of the World",
  kind: "shape",
  family: "world",
  pitch: "The land is the body of a giant from before the world: the mountains are its bones and the rivers its veins. Miners dig ore from it, and nobody is sure it is dead.",
  slots: ["world-shape", "history-secret"],
  tone: ["mythic", "grim"],
  era: ["bronze", "medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "mythic", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "gods_twilight", w: 3 }, { id: "walking_mountains", w: 2.5 }, { id: "downward_throat", w: 2 }, { id: "rim", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a listener who keeps the pulse-logs of the heart-mountain", home: "mountain", stance: "Counts what the land does, and has started to fear the count." },
    { role: "official", n: "the surveyor-general of the Marrow Guild, which mines bone-ore and ichor", home: "capital", stance: "Holds that the land is rock and ore, and that the guild's shafts harm nothing." },
    { role: "believer", n: "a Mourner preacher who calls the land a murdered father", home: "border", stance: "Wants every shaft closed and the old crime named aloud." },
    { role: "survivor", n: "a miner's widow from the bone-ore shafts", home: "inner", stance: "Wants the guild to dig out a body and admit what the rock felt like." },
  ],

  truths: [
    { id: "carcass", n: "The giant was murdered", d: "The first gods killed the primordial giant in its sleep and built the world from its corpse: its bones are the hills, its blood the seas. Its parts still hold its power, which is why bone-ore and ichor are worth so much. Its blood-kin, the giants, remember the murder and want it paid for, and the church that mines the body calls the mining a sacrament.", tags: ["truth:giant_murdered"],
      known: [
        "The creation hymn says the hills are a giant's bones and the seas its blood. The schools call this a figure of speech, though bone-ore has marrow-channels and ichor runs red from the shafts.",
        "The giant-kin have come down to reclaim a bone-range they call 'our father's arm'. They say six came with spears while their father slept. The church says the chaos before the world was tamed without blood.",
        "{investigator} found six gods with red hands painted under a temple's plaster, over a giant lying with open eyes, and a red canyon that grows wider every century with a black spear-shard on its floor.",
        "Confirmed: the first gods murdered the primordial giant in its sleep and built the world from the body. Its kin want the murder paid for, and the church that plastered over the paintings mines the body as a sacrament.",
      ] },
    { id: "sleeper", n: "The giant is only asleep", d: "The primordial is not dead but asleep under the land. Earthquakes are its dreams and volcanoes its fevers. The Marrow Guild's deep shafts wound it, and since they were sunk its heart has doubled its beat: it is beginning to wake, and the guild is paid by the ton.", tags: ["truth:giant_sleeps"],
      known: [
        "Earthquakes come more often near the Marrow Guild's deep shafts, and miners say the deep rock is warm and flinches when struck. The guild says the deep strata are settling and the shafts have no bearing on it.",
        "The heart-mountain beat once a day for four centuries. Its temple has stopped announcing the count, and a pilgrim cave of bone arches carries the same slow beat under its floor.",
        "{investigator}'s pulse-logs show the beat at one and a half since the guild's first deep shaft and two since the third, with an earthquake following each new shaft within the season.",
        "Confirmed: the primordial is asleep under the land, not dead. The guild's shafts are wounding it, its heart has doubled its beat, and it is waking. The guild is still paid by the ton.",
      ] },
    { id: "bearer", n: "The giant is carrying us", d: "The world rides on the back of a living colossus swimming through an endless sea, and its route, its hunger and its age decide the fate of everyone on top. The academies have had its course in their star tables for three centuries and filed it as an error. The creature is old and has begun to dive: the shell coast harbour marks stand forty feet lower than in the oldest charts, and the academy has stopped printing them.", tags: ["truth:giant_bearer"],
      known: [
        "Star-readers say the sky has shifted a hand's breadth in a lifetime. The academy says their old instruments were faulty, and has replaced the instruments at its own expense.",
        "Shell-coast sailors say there is no other shore and that the land leaves a wake behind it. The shell-folk pray facing down over their cliffs, asking something below to swim gently and not dive.",
        "{investigator} dropped floats from the horn cliffs of the shell city; all thirty drifted the same way, against the wind. A tunnel through the horn reached warm flesh and a vessel as wide as a road.",
        "Confirmed: the land rides on a living colossus swimming through an endless sea. The academies filed its course as an error for three centuries. It is old and has begun to dive: the shell coast sits forty feet lower than in the oldest harbour marks.",
      ] },
  ],

  tags: ["world_body"],

  subthemes: [
    { id: "heart_pulse", n: "The Heart-Mountain", d: "A mountain in the realm beats, very slowly, once a day. The beat has quickened this year, and the priests have stopped announcing the count.", w: 1.2, req: { any: ["mountain", "hills"] }, truthLink: "sleeper", tags: ["theme:heart_pulse"], mark: { kind: "zone", n: "The beating mountain", color: "#8a3a3a", size: [1, 2], where: "mountain" } },
    { id: "marrow_guild", n: "The Marrow Guild", d: "Miners who dig bone-ore and draw ichor, the giant's blood, from deep shafts. Their profits are vast and their workers have strange dreams.", w: 1.4, req: { any: ["mountain", "artisans", "guilds"] }, mods: [["mercantile", 1.5]], tags: ["theme:marrow_guild"] },
    { id: "vein_flood", n: "The Opened Vein", d: "A mine broke through the rock into soft, warm flesh. The valley below flooded with warm red water that does not clot and will not drain.", w: 0.9, req: { any: ["mountain", "river"] }, truthLink: "sleeper", tags: ["theme:vein_flood"], mark: { kind: "zone", n: "The red valley", color: "#7a2020", size: [1, 2], where: "any" } },
    { id: "giant_kin_march", n: "The Giant-Kin March", d: "The giant-kin of the high ranges have come down to reclaim a bone-range they call 'our father's arm'. They do not want land; they want the miners out.", w: 1.1, req: { any: ["mountain", "cold", "near:titan"] }, truthLink: "carcass", tags: ["theme:giant_kin_march"] },
    { id: "fever_plague", n: "The Fever of the Land", d: "A plague that physicians cannot trace. A heretic says it is the land's own fever, and that we are the infection.", w: 0.8, truthLink: "sleeper", tags: ["theme:fever_plague"] },
    { id: "bearer_turning", n: "The Turning Stars", d: "The star-readers say the sky has shifted a hand's breadth in a lifetime, as if the whole land were moving across the sea.", w: 0.9, req: { any: ["coastal", "faith:stars", "seers", "scholarly"] }, truthLink: "bearer", tags: ["theme:bearer_turning"] },
    { id: "shell_coast", n: "The Shell Coast", d: "Fisherfolk on the far coast live on cliffs of horn and barnacle. Once a generation, an eye the size of a lake opens in the sea below them.", w: 0.8, req: "coastal", truthLink: "bearer", tags: ["theme:shell_coast"], mark: { kind: "zone", n: "Horn cliffs", color: "#9a8a6a", size: [1, 3], where: "coast" } },
    { id: "ichor_city", n: "The Ichor City", d: "A city grown rich on ichor trade. Its folk live long, sleep little and have begun to dream the same dream.", w: 0.9, req: { any: ["mercantile", "has:city"] }, tags: ["theme:ichor_city"] },
    { id: "twin_lakes", n: "The Eye-Lakes", d: "Two round lakes lie side by side in the uplands. Shepherds swear that on still nights the reflection in them blinks.", w: 0.8, req: { any: ["river", "hills", "mountain"] }, truthLink: "sleeper", tags: ["theme:twin_lakes"] },
    { id: "murder_weapon", n: "The First Spear", d: "Diggers uncovered a spearhead of black metal the size of a ship. The temple claims it as holy; the giant-kin call it evidence.", w: 0.7, req: { any: ["near:ruins", "pious", "scholarly"] }, truthLink: "carcass", tags: ["theme:murder_weapon"] },
    { id: "butchers_church", n: "The Butchers' Heirs", d: "The great church teaches that the first gods were right to slay the chaos-giant, and that mining its bones is a sacrament.", w: 1.2, req: { any: ["pious", "organised", "faith:pantheon"] }, tags: ["theme:butchers_church"] },
  ],

  sites: [
    { id: "rib_cave", n: "The White Arches of $", kind: "wonder", where: "mountain", d: "A cave of vast curved white arches, unmistakably ribs.",
      layers: {
        surface: { n: "Polished arches", text: "A pilgrim cave in the mountains near {place} is roofed with pale curved arches, polished by centuries of hands. Pilgrims pay a copper at the door and touch the arches for luck. About three thousand come each summer." },
        study: { n: "Bone, not stone", text: "{investigator} drilled a core from one arch: it is bone, not stone, with marrow-channels as wide as a wrist. The arches curve around a hollow the size of a cathedral. There are 24 of them, twelve a side." },
        dig: { n: "The drum through the wall", points: "sub:heart_pulse", text: "In the hollow is a chamber of dark, dry tissue. With an ear to the floor there is a slow sound like a drum heard through a wall: one beat, then a long silence. The pulse-logs of the heart-mountain, which beats on the same count, are kept in {lead}." },
        revelation: { n: "Still beating", text: "The cave is the giant's chest, and its heart is still beating, once a day. The Marrow Guild, which took over the cave and its door-copper ninety years ago, has known all along. It charges double on the days the beat is loudest." },
      } },
    { id: "red_wound", n: "The Unhealed Canyon of $", kind: "anomaly", where: "any", truthLink: "carcass", d: "A red-earthed canyon that never scars over, where the first gods are said to have struck.",
      layers: {
        surface: { n: "Warm red soil", text: "A canyon near {place} has red soil, warm underfoot, where nothing but thornbush grows. Herders bring sick sheep to lie on it in winter. Rain that falls here runs off red and stains the river for a mile." },
        study: { n: "Wider each century", text: "{investigator} compared the survey stones set by three generations of surveyors. The canyon is nine feet wider than when the first stone was set, 300 years ago, and its edges are soft and raised, like the lips of a cut." },
        dig: { n: "The shard", points: "site:defaced_carving", text: "On the canyon floor lies a shard of black metal as long as a cart, and around it soil that shrinks away from a hand. The shard's edge matches the spearheads painted in the gods' red hands on the frieze at {lead}." },
        revelation: { n: "The first cut", text: "The first gods struck the sleeping giant here and cut the world out of its body. The wound has never healed, because the body was never allowed to heal. The church has a chapel on the rim and sells the red soil, by the thimble, as a relic of the gods' victory." },
      } },
    { id: "tooth_quarry", n: "The Tooth Quarry of $", kind: "dig", where: "mountain", d: "A quarry whose stones are still sharp, and still growing.",
      layers: {
        surface: { n: "White stone", text: "A quarry in the mountains near {place} cuts white, glassy stone prized for millstones; one stone sells for forty silver. The quarrymen work in pairs, and never leave a block half-cut overnight." },
        study: { n: "Growing back", text: "Worked faces left alone grow back a finger's width a year. {investigator} scored a cut face with chisel lines and came back a year later. The lines had healed over, and the new stone was smoother than the old." },
        dig: { n: "Enamel", points: "archive", text: "Deep down the stone turns to enamel, and the quarry wall curves like a jaw. A second, older tunnel runs below it, sealed with a Marrow Guild stamp. The guild's survey map of the jaw is in {lead}." },
        revelation: { n: "The jaw", text: "The quarry is cut into the giant's jaw, and its teeth are still growing. The Marrow Guild has known for a century: its millstones are teeth, sold to every mill in the realm. The guild's price list calls them 'self-dressing', and charges extra for it." },
      } },
    { id: "defaced_carving", n: "The Defaced Frieze of $", kind: "ruin", where: "remote", truthLink: "carcass", d: "A temple frieze of the first gods, their hands chiselled away.",
      layers: {
        surface: { n: "The hill temple", text: "An abandoned temple of the old pantheon stands on a lonely hill near {place}. The roof has fallen, but a frieze of the first gods still runs round the inner wall. The goatherd who shelters there charges visitors nothing, and tells them to look at the hands." },
        study: { n: "The missing hands", text: "Every god's hands have been hacked off the frieze, carefully, by someone who knew which ones to choose: six gods, twelve hands. {investigator} found the chips swept into a corner and stacked, not thrown away." },
        dig: { n: "Red to the elbow", points: "archive", text: "Under a later coat of plaster, the original paint shows the hands red to the elbow, gripping spears, over a giant lying on its back with open eyes. The temple's repair accounts, naming who paid for the plaster, are in {lead}." },
        revelation: { n: "Plastered over", text: "The first gods made the world by butchering a sleeping giant, and their own temple painted it. When the great church came to power, its bishops paid masons to hack off the red hands and plaster over the body. The repair accounts list the cost as 'restoration'." },
      } },
    { id: "barnacle_city", n: "The Barnacle Steps of $", kind: "wonder", where: "coast", truthLink: "bearer", d: "Where land meets the sea in a sheer cliff of horn, a city of barnacle-shells clings to the brink.",
      layers: {
        surface: { n: "The shell city", text: "A rope-and-shell city of some two thousand people clings to a cliff of something like horn near {place}, above a sea that is always moving. Its people fish with lines a mile long, and pray facing down." },
        study: { n: "Plates and currents", text: "The cliff is plated, each plate as big as a house, and the plates are scored by currents running one way. {investigator} dropped painted floats from the top: all thirty drifted the same way, against the wind." },
        dig: { n: "The vessel", points: "library", text: "A tunnel through the horn reaches warm, damp flesh and a vessel as wide as a road, pulsing slowly. A sample of the flesh was sent to the academy, which kept it quiet. Its report is shelved in {lead}." },
        revelation: { n: "Riding on it", text: "The land is the back of a living creature swimming through an endless sea. The academies have had star tables showing its course for three centuries and called the drift an error. The creature is old, and the shell-folk's prayers ask it, every evening, not to dive." },
      } },
  ],

  beings: [
    { id: "giant_kin", n: "Giant-kin", kind: "beast", d: "Grey-skinned folk twice a man's height who live in the high ranges and call the mountains their grandfather's bones.", danger: 2, biomes: ["peaks", "alpine", "tundra", "boreal"], look: { size: 4, group: [2, 8], move: "herd", speed: 7, col: "#8a8a80", col2: "#4a3a30", body: "biped", active: "day", visible: true } },
    { id: "warden_beast", n: "Warden-beast", kind: "predator", d: "Pale, eyeless hunters that come out of deep mines and kill the diggers, then go back down. Physicians think they defend the land against the mines, the way a body fights a wound.", danger: 3, biomes: ["peaks", "alpine", "badlands", "colddesert"], look: { size: 2, group: [3, 12], move: "pack", speed: 11, col: "#e8e0d8", col2: "#b0a090", body: "spider", active: "night", visible: false } },
    { id: "hair_grass_grazer", n: "Lousebuck", kind: "grazer", d: "A flat, armoured grazer that roams the swaying hair-grass plains in vast herds. Scholars note uneasily that it is shaped like a louse.", danger: 0, biomes: ["grass", "coldsteppe", "savanna"], look: { size: 1.2, group: [20, 150], move: "herd", speed: 8, col: "#6a5a40", col2: "#3a3020", body: "insect", active: "day", visible: true } },
  ],

  techs: [
    { id: "bw_bone_ore", n: "Bone-ore smelting", field: "metallurgy", level: 2, d: "White ore from the bone-ranges is smelted into a pale, springy steel that never rusts." },
    { id: "bw_pulse_logs", n: "Pulse logs", field: "natural_philosophy", level: 2, d: "Listeners record the heart-mountain's beat, year on year, in endless careful ledgers." },
    { id: "bw_ichor_draughts", n: "Ichor draughts", field: "medicine", level: 3, d: "Distilled ichor that heals any wound and lengthens life, at a price no physician will name." },
    { id: "bw_anatomy_maps", n: "Land anatomy", field: "writing", level: 4, d: "Maps that chart the realm as a body: which valley is a vein, which ridge a tendon, where never to dig." },
    { id: "bw_heart_drum", n: "The heart-drum", field: "arcana", level: 5, d: "A drum that beats with the heart-mountain and can, it is said, soothe it, or wake it." },
  ],

  units: [
    { id: "bw_giant_kin", n: "Giant-kin warband", role: "beast", wpn: "axe", kit: "hide", ranks: 2, gap: 4, size: 30, w: 0.4, mods: [["theme:giant_kin_march", 10], ["mountain_folk", 2]] },
  ],

  faiths: [
    { id: "mourners_flesh", n: "Mourners of the Flesh", d: "The land is our murdered father; every mine is a desecration and every quake a sob.", tags: ["faith:mourners"], w: 0.5, names: ["The Mourners of $", "The Grieving Body", "The Bone Vigil"], mods: [["ancestor_bound", 2], ["theme:giant_kin_march", 4]] },
  ],

  mapMarks: [
    { kind: "zone", n: "The rib-ranges", color: "#d0c8b8", size: [3, 6], count: [1, 2], where: "mountain", d: "Parallel white ranges that, from high enough, are plainly ribs." },
    { kind: "zone", n: "Hair-grass plains", color: "#9a8a50", size: [2, 5], count: [0, 1], where: "remote", d: "Plains of fine grass that sways in one direction with no wind at all." },
  ],

  storylines: [
    { id: "bw_deep_mine", n: "The Deep Shaft of {place}", scale: "local", anchor: "town", w: 1.5, req: "world_body",
      stages: {
        start: { h: "The Marrow Guild sinks a deep shaft at {place}", b: "The richest bone-ore ever found lies under {place}, and the guild means to have it. {person}, the overseer, has hired every pick in the province.", wait: [3, 8], fx: { treasury: 30 }, next: [{ to: "strike_vein", w: 1.5 }, { to: "white_come", w: 1 }] },
        strike_vein: { h: "The shaft at {place} strikes a vein", b: "The miners broke through the rock into soft, warm flesh. Red water is filling the lower galleries, and the ground hums.", wait: [1, 4], fx: { unrest: 8 }, next: [{ to: "valley_floods", w: 1.5 }, { to: "shaft_sealed", w: 1, mods: [["pious", 2], ["theme:butchers_church", 0.5]] }] },
        white_come: { h: "Pale hunters come up the shaft at {place}", b: "Eyeless white hunters came up the shaft at night and killed eleven miners, then went back down. {investigator}, a listener who records the land's heartbeat, says the land has noticed the digging.", wait: [2, 5], fx: { pop: 0.95, stability: -4 }, next: [{ to: "shaft_sealed", w: 1 }, { to: "dig_deeper", w: 1, mods: [["ruler:greedy", 2], ["theme:marrow_guild", 2]] }] },
        valley_floods: { h: "The red flood drowns {place}", b: "The vein will not close. {place} is under warm red water, and its people are on the hills.", fx: { abandon_town: true, pop: 0.9 }, end: true },
        shaft_sealed: { h: "The shaft at {place} is sealed with prayers", b: "The shaft was filled with salt and stone, and the priests sang over it for nine days. The hum has stopped. The miners have not gone back.", fx: { stability: 4, treasury: -20 }, end: true },
        dig_deeper: { h: "The guild digs on beneath {place}", b: "Guarded by soldiers, the guild dug on. The earthquakes started that winter, and the heart-mountain's beat doubled.", fx: { treasury: 60, stability: -10, flag: "waking" }, end: true },
      } },
    { id: "bw_eye_opens", n: "The Eye Beneath {realm}", scale: "realm", anchor: "realm", w: 1, req: ["world_body", { any: ["coastal", "learned", "seers", "faith:stars"] }],
      stages: {
        start: { h: "Listeners of {realm} report the land is moving", b: "{investigator}, keeper of the pulse-logs, has gone before {ruler}: the stars have shifted, the tides have changed, and the heart beats twice where it beat once.", wait: [3, 8], next: [{ to: "believed", w: 1, mods: [["learned", 2], ["ruler:just", 1.5]] }, { to: "mocked", w: 1.5 }] },
        believed: { h: "{realm} funds the listeners", b: "Towers of brass ear-trumpets rise on the coasts and mountains of {realm}. The listeners write down everything the land does.", wait: [6, 14], fx: { science: { natural_philosophy: 1 } }, next: [{ to: "song_heard", w: 1 }, { to: "it_wakes", w: 0.6, mods: [["flag:waking", 4]] }] },
        mocked: { h: "{ruler} laughs the listeners out of court", b: "{investigator} was dismissed as a crank. The pulse-logs were sold for kindling in the market of {capital}.", wait: [6, 18], next: [{ to: "it_wakes", w: 0.5, mods: [["flag:waking", 4]] }, { to: "quiet_again", w: 1.5 }] },
        song_heard: { h: "The land sings off the coast of {realm}", b: "The listeners' trumpets caught a sound beneath the sea: a long low song, and far away, an answer. {investigator} wept on hearing it.", fx: { discovery: "natural_philosophy", prestige: 10 }, end: true },
        it_wakes: { h: "The land stirs beneath {realm}", b: "For a day the whole of {realm} rose and fell like a sleeper's chest. Towers fell in {capital}; the sea drew back and returned.", fx: { pop: 0.85, stability: -15, titan: true }, end: true },
        quiet_again: { h: "The heartbeat slows again", b: "Whatever troubled the land has passed. The heart-mountain beats once a day once more, and nobody in {capital} remembers the listeners.", fx: { stability: 2 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", who: "Cantor of the temple of {place}", text: "The creation hymn as sung at the spring festival in the temple of {place}, {year}, with the cantor's note: 'Of its bones the hills, of its blood the seas, of its skull the sky, of its hair the forests, and of its last breath, the wind.' The cantor adds that the third line is now sung softly, by order, since the Mourners began singing it louder outside." },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "A Geography for Young Nobles", text: "From A Geography for Young Nobles, chapter one, {year} edition: 'The giant of the old songs is a figure of speech, by which the ancients expressed their wonder at the land. Bone-ore is a mineral like any other; ichor is a red spring-water. Our six great ranges merely resemble ribs.' A pupil has written beneath: 'Then why do they have marrow?'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A mountaineer of {realm}", text: "A mountaineer's letter after climbing the highest peak in {realm}, {year}: 'From the top, the ranges lie parallel as ribs, twelve of them, and between them like a spine runs the great ridge. I could see where the shoulders begin. I came down and did not sleep for a week. My guide refuses to go up again for any money.'" },
    { depth: "core", about: "truth:carcass", source: "oral", bias: "true", reliable: true, plain: true, who: "A giant-kin elder, through an interpreter", text: "A giant-kin elder, speaking to {investigator} through an interpreter at the edge of the bone-range, {year}: 'Our father lay down to rest. Six came with spears while our father slept. They cut our father into the world and called it a gift. The hills are our father's bones; you mine them and sell them by the cart. We are the kin, and we remember the night. We do not want your land. We want you out of our father's arm.'" },
    { depth: "core", about: "truth:carcass", source: "ruin", bias: "true", reliable: "partial", who: "{investigator}, pulse-log keeper", points: "site:defaced_carving", text: "Survey notes of {investigator} on the old frieze, {year}: 'Under the plaster: six figures with red hands, twelve hands in all, and below them a vast giant lying on its back with its eyes still open. The spearheads are painted black. A black metal spearhead the size of a ship was dug up last year, and the temple has claimed it. The frieze is at {lead}.'" },
    { depth: "core", about: "truth:carcass", source: "heretic", bias: "heretic", reliable: "partial", who: "{believer}, Mourner preacher", points: "site:red_wound", text: "Pamphlet of {believer}, a Mourner preacher, {year}: 'Every altar of the pantheon is a butcher's block. Every coin of bone-ore is a piece of our father sold, at three silver the pound. Go to the red canyon at {lead}, where they struck the first blow, and put your hand on the soil. It is warm. Dead earth is not warm.'" },
    { depth: "core", about: "truth:carcass", source: "archive", bias: "true", reliable: "partial", cost: true, who: "A Marrow Guild captain", text: "Report of a Marrow Guild captain to the guild, {year}: 'The giant-kin came down the bone-range at dawn and took back the shaft at {place}. They did not kill the miners. They carried them out, sixty of them, set them on the road and broke every pick. The overseer, {person}, would not leave the shaft. The giant-kin buried {person} in it with the ore, and sang over the grave.'" },
    { depth: "core", about: "truth:carcass", source: "temple", bias: "official", reliable: false, who: "Ruling of the great church of {realm}", text: "Ruling of the great church of {realm}, read in every parish, {year}: 'The chaos that came before the world was not slain but tamed, freely and without blood, by the mercy of {deity}. Paintings showing otherwise are forgeries of the Mourners. The church will pay twenty silver for each one reported, and will see to its restoration.'" },
    { depth: "core", about: "truth:sleeper", source: "archive", bias: "true", reliable: true, plain: true, who: "{investigator}, pulse-log keeper", text: "Pulse-log of the heart-mountain, summary page, signed by {investigator}, keeper of the logs, {year}: 'One beat per day for 400 years. One and a half since the guild sank its first deep shaft. Two since the third. The giant under us is not dead. It is asleep, the shafts are wounding it, and it is waking. Every earthquake on our list follows a new shaft within the season.'" },
    { depth: "core", about: "truth:sleeper", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, miner's widow", text: "Statement of {survivor}, a miner's widow, to the guild's compensation clerk, {year}: 'My husband said the rock down there is warm, and it flinches when you strike it. All the men felt it. The pay was four silver a shift, so back down we sent him. The foreman says the shaft closed like a hand. The guild offers thirty silver. I want the body, and the guild will not dig for it.'" },
    { depth: "core", about: "truth:sleeper", source: "oral", bias: "garbled", reliable: "partial", who: "A hill farmer of {place}", points: "cast:investigator", text: "A hill farmer of {place}, asked about the earthquakes, {year}: 'When the ground shakes we say: hush, it dreams. Then we put a bowl of milk at the door. My father did, and his father. There were three shakes a year when I was a boy. There were eleven last year, and we have run short of milk. Ask {lead}, who keeps the count.'" },
    { depth: "core", about: "truth:sleeper", source: "library", bias: "official", reliable: false, who: "{official}, surveyor-general of the Marrow Guild", text: "Report of {official}, surveyor-general of the Marrow Guild, to the crown, {year}: 'Earthquakes arise from the settling of the deep strata and are not increasing in frequency. The guild's forty deep shafts have no bearing on them. Reports of warm or moving rock are the fancies of tired men, and the guild has raised wages to cure them.'" },
    { depth: "core", about: "truth:bearer", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A sailor of the shell coast", points: "library", text: "A sailor of the shell coast, telling the harbour tavern at {place} about a voyage, {year}: 'There is no other shore. We sailed forty days straight out and the sea went on, and when we looked back the whole land was moving, low and slow, leaving a wake like a ship's. The captain logged it. The academy took the log, and it sits in {lead}.'" },
    { depth: "core", about: "truth:bearer", source: "archive", bias: "true", reliable: true, plain: true, who: "An academy star-reader", points: "library", text: "Note by an academy star-reader on the star tables of {realm}, compared across three centuries, {year}: 'Every star has shifted in the same direction by the same amount, a hand's breadth in a lifetime. The sky is not moving. We are. The land rides on something that swims, and it has held one course for 300 years. The academy filed my note as an instrument error; it lies in {lead}.'" },
    { depth: "core", about: "truth:bearer", source: "temple", bias: "pious", reliable: "partial", who: "{investigator}, pulse-log keeper", text: "The shell-folk's evening prayer, sung facing down over the cliff edge near {place}, as written down by {investigator} in {year}: 'Swim gently, old mother; we are small on your back. Do not dive this year.' The shell-folk say the eye beneath them last opened in their grandparents' time, and will open again within ten years. They are building boats." },
    { depth: "core", about: "truth:bearer", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a fisher of the shell coast", text: "Letter of {person}, a fisher of the shell coast, to the harbour reeve, {year}: 'The eye opened under us last night, as wide as the bay, and looked up for an hour. The sea dropped thirty feet when it blinked. My boat and my brother were on the water. The boat came back. Please write my brother's death down as drowning. Nobody will believe the other thing.'" },
    { depth: "core", about: "truth:bearer", source: "library", bias: "official", reliable: false, who: "Natural History of the Coasts", text: "From the academy's Natural History of the Coasts, {year} edition: 'The so-called eye of the shell coast is a whirlpool of the tides, and has been observed by no reputable witness in 200 years. The star-shift reported by certain readers is an error of their instruments, which the academy has replaced at its own expense.'" },
    { depth: "sub", about: "sub:marrow_guild", source: "archive", bias: "redacted", reliable: "partial", who: "A Marrow Guild survey map", points: "archive", text: "A Marrow Guild survey map of the bone-range, {year}, with a margin note in red ink: 'Do not dig at the sites marked, seven in all. Do not record why. [signature removed].' Each site is marked with a small drawn heart. The map turned up in the papers of {official}, surveyor-general. The guild's full survey is at {lead}." },
    { depth: "sub", about: "sub:ichor_city", source: "person", bias: "true", reliable: "partial", who: "A physician of the ichor city", points: "library", text: "Case notes of a physician of the ichor city of {place}, {year}: 'My patients are all past a hundred, and none of them dream of their own lives any more. Forty-eight patients, one dream: they are very big and very cold, lying on their backs in the dark, and something is cutting. Ichor sells at ten silver the vial. I have stopped drinking mine. My notes have gone to {lead}.'" },
    { depth: "sub", about: "sub:fever_plague", source: "heretic", bias: "heretic", reliable: "partial", who: "{believer}, Mourner preacher", points: "archive", text: "Placard of {believer}, a Mourner preacher, nailed up in {place} during the fever, {year}: 'The fever is the land's fever. The land is burning us out of its blood, the way your body burns out a splinter. Nine hundred dead this summer. Stop digging and it will stop burning. The guild's shafts are all listed in {lead}. Go and count them.'" },
    { depth: "sub", about: "sub:butchers_church", source: "temple", bias: "propaganda", reliable: false, who: "Sermon at a new shaft, {place}", text: "Sermon at the consecration of a new shaft at {place}, {year}: 'To dig the bone of the world is to share in the gods' first victory. Blessed be the pick. The church takes one cart in ten from this shaft as its tithe, for the glory of {deity} and the upkeep of three chapels.'" },
    { depth: "sub", about: "sub:twin_lakes", source: "oral", bias: "garbled", reliable: "partial", who: "An upland innkeeper of {place}", text: "Notice painted on a board by the door of an upland inn at {place}, {year}: 'Do not fish in the left lake at full moon. That is when it looks up. Right lake fine any time. Boat hire two coppers. No refunds if the lake blinks. Guests who see it blink are asked not to tell the other guests.'" },
    { depth: "sub", about: "sub:shell_coast", source: "traveller", bias: "true", reliable: "partial", who: "A pedlar on the shell coast", points: "site:barnacle_city", text: "A pedlar's notes on the shell coast, {year}: 'The cliffs here are horn, plated like a beetle's back, and the city hangs on them by ropes. Two thousand people. Every family keeps a boat ready on a winch. They told me that once a generation an eye the size of a lake opens in the sea below. The steps down to the water are at {lead}.'" },
    { depth: "sub", about: "sub:heart_pulse", source: "temple", bias: "official", reliable: "partial", who: "Temple under the heart-mountain", text: "Notice of the temple of {place}, under the heart-mountain, {year}: 'The temple will no longer announce the mountain's daily beat-count. Last year's count of one and a half was a clerical error. The faithful are asked not to lie on the mountain's flanks with their ears to the ground, which is unseemly and frightens the goats.'" },
    { depth: "site", about: "site:rib_cave", source: "traveller", bias: "true", reliable: true, who: "A pilgrim at the white arches", points: "cast:investigator", text: "A pilgrim's letter from the white arches near {place}, {year}: 'I paid my copper and touched the arches for luck, like everyone. Then I lay down with my ear to the floor, from one dawn to the next, on a blanket I rented for four coppers. One beat at first light, then nothing all day and night, then one more. The guild man at the door said not to tell anyone. The heart-mountain's keeper, {lead}, keeps the same count.'" },
    { depth: "site", about: "site:tooth_quarry", source: "person", bias: "true", reliable: "partial", who: "The quarrymaster of {place}", text: "The quarrymaster of {place}, to a buyer's agent, {year}: 'We cut the same block four times in my life. It grew back each time, a finger a year. I've stopped telling the buyers. It wears itself smooth again in the mill, which is why our millstones never need dressing. Forty silver each, and I don't take returns.'" },
  ],
};
