// The Broken Writ: the world's sacred law was a single object, and it was shattered; demigods hold the shards.
export default {
  id: "broken_writ",
  name: "The Broken Writ",
  family: "world",
  kind: "cosmic",
  pitch: "The world's law was a single golden object, the Writ. It was shattered, and the demigods who seized its pieces are at war over the land.",
  slots: ["divine-order", "history-secret"],
  tone: ["mythic", "grim"],
  era: ["bronze", "medieval"],
  scale: "world",
  genres: ["fantasy", "mythic", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "great_root", w: 3 }, { id: "gods_twilight", w: 1.5 }, { id: "unquiet_gate", w: 2 }, { id: "elder_lattice", w: 1.5 }, { id: "balanced_circle", w: 1.2 }],

  cast: [
    { role: "investigator", n: "the keeper of the old archive, who has read the queen's letters", home: "capital", stance: "Wants the Shattering told as it happened, and suspects the court's history was written first." },
    { role: "official", n: "a herald of the Old Order Loyalists, the knights sworn to restore the Writ", home: "inner", stance: "Holds that the Writ must be made whole exactly as it was, whatever burns on the way." },
    { role: "believer", n: "a whisperer of the consort's cult", home: "border", stance: "Keeps the erased consort's name and believes the consort tried to save the Writ." },
    { role: "survivor", n: "a gravedigger of the Unended catacombs", home: "remote", stance: "Has buried the twitching dead for twenty years and wants them let go." },
  ],

  truths: [
    { id: "imposed", n: "The Writ was a cage", d: "A power from beyond the sky set the Writ on the world like a lid, to hold down the world's own order: death, change and wild growth. Under it the dead could not rest. Breaking it was a rebellion, not a crime, and death and decay are coming back, while the loyalist knights burn rot-villages to keep the lid on.", tags: ["truth:imposed_writ"],
      known: [
        "Since the Shattering, some of the dead do not finish dying, and the catacombs are full of the twitching. The loyalists teach that death and decay are wounds in the world's nature that only a mended Writ can heal.",
        "A few of the dead have begun to die properly again, with peaceful faces. A rot-cult in the marshes says decay is the world breathing again, and that the Writ itself was the sickness.",
        "{investigator} found a buried city whose gate names a law 'from beyond the sky, laid on us like a lid'. Its tombs hold the only peaceful dead left, and the roots binding the unended dead run toward the broken Writ.",
        "Confirmed: a power from beyond the sky laid the Writ over the world to hold down death, change and growth. Breaking it was a rebellion. Death is returning, and the loyalists burning rot-villages are fighting to keep the lid on.",
      ] },
    { id: "self_broken", n: "The queen broke it herself", d: "The queen who swore to keep the Writ shattered it herself, with a hammer, because its law bound her too. She erased her consort's name the day before, because he knew and tried to stop her, and then blamed him. Her 'murdered' consort, her 'traitor' children and the whole war were cover for one woman's escape, and her children are still fighting it.", tags: ["truth:queen_broke_writ"],
      known: [
        "The court's history says the consort broke the Writ and the queen died defending it. Statues of the consort stand faceless in every old square, and a cult whispers the consort's name at midnight.",
        "Letters in the queen's hand from the night before the Shattering speak of being 'free of it, whatever it costs them'. Eleven of the twelve letters are missing from the archive.",
        "{investigator} found that the golden pillar was broken from inside, with one pair of sandal prints in its core, and that the consort's name was chiselled off the day before the war began, not after.",
        "Confirmed: the queen broke the Writ herself because its law bound her, and blamed her husband, who had tried to stop her. The demigods fighting over the shards are her children, still fighting the war she staged.",
      ] },
    { id: "many_writs", n: "Any law will do", d: "The Writ was only one possible order among many: a law written once, on a golden page, in a tower with no door. Whoever gathers enough shards does not restore the old law but writes the next one. Every demigod knows it, and every one of them preaches restoration in public.", tags: ["truth:many_writs"],
      known: [
        "Every demigod who holds a shard says the Writ must be restored exactly as it was. Yet each shard-domain already lives under a different law: endless harvest, endless war, stars that set the hour of every death.",
        "Minutes of one shard-court's war council say plainly that four shards would not restore the old law, and that restoration is to be spoken of only in public.",
        "{investigator} read a gold page in a doorless tower: 'An order is chosen, not found.' The lectern beneath it has a socket shaped for a splinter, and three demigods have sent climbers.",
        "Confirmed: the Writ was one law among many, written once on a golden page. Whoever gathers enough shards writes the next law of the world. Every demigod knows it, and every one preaches restoration.",
      ] },
  ],

  tags: ["writ"],

  subthemes: [
    { id: "shard_court", n: "The Shard-Court", d: "A demigod rules here holding one shard of the Writ, and the land bends to that one law: endless harvest, endless war, or endless night.", w: 1.6, req: { any: ["monarchy", "autocracy", "gov:empire", "realm:large", "realm:vast"] }, tags: ["theme:shard_court"], mark: { kind: "zone", n: "The Shard-Lands", color: "#b08a3a", size: [2, 5], where: "capital" } },
    { id: "rotting_domain", n: "The Rotting Domain", d: "A demigod's shard has turned against its holder. Crimson rot blooms in the fields and in the demigod's own flesh, and the court pretends not to notice.", w: 1, req: { any: ["marsh", "jungle", "hot", "river"] }, truthLink: "imposed", tags: ["theme:writ_rot"], mark: { kind: "zone", n: "The Bloom-Rot", color: "#9a3a4a", size: [2, 4], where: "remote" } },
    { id: "graceless", n: "The Graceless Exiles", d: "Folk cast out from the Writ's grace generations ago are being called back by guiding lights only they can see. Each arrives convinced they are the one meant to mend it.", w: 1.3, tags: ["theme:graceless"] },
    { id: "deathless", n: "The Catacombs of the Unended", d: "Since the Shattering, some of the dead do not finish dying. The catacombs are stuffed with the twitching, and gravediggers are paid like soldiers.", w: 1.1, req: { any: ["ancestor_bound", "faith:ancestors", "near:ruins", "pious"] }, truthLink: "imposed", tags: ["theme:unended_dead"] },
    { id: "star_sorcerer", n: "The Star-Reader's Rebellion", d: "A demigod of the observatories wants to throw down the Writ's fate and replace it with a law in which the stars decide every birth and death.", w: 0.8, req: { any: ["faith:stars", "scholarly", "seers", "cold"] }, truthLink: "many_writs", tags: ["theme:star_order"] },
    { id: "furnace_seal", n: "The Giants' Furnace", d: "On a mountain the last giants keep a fire that must never go out. They will not say what it is burning, only that it was burning before the Writ.", w: 0.8, req: { any: ["mountain", "mountain_folk", "cold"] }, truthLink: "imposed", tags: ["theme:giant_furnace"] },
    { id: "grafted_heir", n: "The Grafted Heir", d: "A child demigod is being made mightier by the grafting of limbs taken from the slain. The court calls it devotion; the servants call it butchery.", w: 0.7, req: { any: ["autocracy", "harsh_law", "gov:absolute"] }, tags: ["theme:grafted_heir"] },
    { id: "peasant_shard", n: "The Peasant's Shard", d: "A splinter of the Writ has fallen into a farmer's hands. Her village now obeys a law of its own, and three demigods have sent riders.", w: 0.9, req: { any: ["egalitarian", "realm:tiny", "realm:small", "tribal"] }, truthLink: "many_writs", tags: ["theme:peasant_shard"] },
    { id: "loyalists", n: "The Old Order Loyalists", d: "Knights who swear the Writ can be restored exactly as it was. Their cause is noble; their methods are brutal.", w: 1.2, req: { any: ["pious", "zealous", "hierarchical", "militant"] }, tags: ["theme:writ_loyalists"] },
    { id: "nameless_statue", n: "The Chiselled Consort", d: "Statues of the queen's consort stand in every old square with his name cut away. A cult has begun to whisper it again.", w: 0.8, req: { any: ["urbane", "has:city", "spy_network"] }, truthLink: "self_broken", tags: ["theme:erased_consort"] },
    { id: "queens_letters", n: "The Queen's Letters", d: "Letters in the queen's own hand have surfaced in an archive, written the night before the Shattering. They do not read like a victim's.", w: 0.6, req: { any: ["scholarly", "academies", "learned"] }, truthLink: "self_broken", tags: ["theme:queens_letters"] },
  ],

  sites: [
    { id: "broken_monolith", n: "The Shattered Seat of $", kind: "wonder", where: "capital", d: "The great golden monolith where the Writ was kept, cracked through and hollow.",
      layers: {
        surface: { n: "The split pillar", text: "A pillar of gold-veined stone, ninety feet high, stands in {place}, split from crown to root and ringed with a wall of thorns. Pilgrims push coins through the thorns. The keepers rake them out each dawn and count them for the loyalists." },
        study: { n: "From inside", text: "{investigator} measured the breaks. They are clean and run outward, as if made by one blow from inside the pillar, not by an assault from without. Every chronicle of the Shattering describes an army at the gates." },
        dig: { n: "The hollow core", points: "site:consort_statue", text: "In the hollow core are the marks of a hammer's claw and, in the dust, one pair of small sandal prints, going in and coming out. The same sandal is carved on the queen's foot at the base of the faceless statue at {lead}." },
        revelation: { n: "Closest to it", text: "The Writ was not stolen by an enemy. It was broken from inside, by someone who could walk into its core: the keeper who stood closest to it. The army at the gates arrived the next morning. Every chronicle of the Shattering begins with the army." },
      } },
    { id: "false_sky_city", n: "The Buried City under $", kind: "ruin", where: "remote", truthLink: "imposed", d: "An eternal city sunk beneath the earth, lit by a painted sky.",
      layers: {
        surface: { n: "Cold air", text: "A sinkhole near {place} blows cold air day and night, and lights are seen far below after dark. The village lowers no buckets into it. A boy who climbed 200 feet down on a rope in {year} came back up and would only say the sky was painted." },
        study: { n: "The first enemies", text: "{investigator} read the loyalist chronicles: the city's people were the Writ's first enemies, buried alive under a vault painted with their own false stars. The chronicles put their number at forty thousand and call them the Rot-Folk." },
        dig: { n: "Whole and peaceful", points: "site:deathless_catacomb", text: "Their tombs hold the dead whole and peaceful, laid in rows with calm faces and no roots on them. They are the only true deaths left in the world. Compare the twitching dead in the catacombs at {lead}." },
        revelation: { n: "The world's own order", text: "The buried people's law was natural death and natural change. A power from beyond the sky laid the Writ over the world like a lid and took death away; this city refused it and was buried for it. Its tombs are the last place where the dead rest. The loyalists hold the sinkhole's rim." },
      } },
    { id: "deathless_catacomb", n: "The Unended Vaults of $", kind: "dig", where: "any", truthLink: "imposed", d: "Catacombs where the dead lie twitching, wound in roots, unable to finish dying.",
      layers: {
        surface: { n: "Wax and prayers", text: "Bone-pits under {place} are sealed with wax and prayers, and smell of old honey. The gravediggers here are paid like soldiers, six silver a week. {survivor} has worked the pits for twenty years and wears cotton in both ears." },
        study: { n: "Roots to the capital", text: "The twitching dead are wound in thin roots. {investigator} followed one root three miles through the catacomb walls. It runs toward the capital, where the broken Writ stands, and draws the dead slowly that way." },
        dig: { n: "The one at rest", points: "archive", text: "At the bottom lay a dead man with a splinter of the Writ in his heart. He was the only one at rest, his face slack and peaceful, no roots on him. The loyalists took the splinter; their receipt for it is filed in {lead}." },
        revelation: { n: "Death returns", text: "The Writ held death back from the world. Where it is broken, death returns, and with it peace: the splinter in the dead man's heart had broken the Writ's hold on him. The loyalists are gathering every splinter to mend the Writ, which would keep these dead twitching for ever." },
      } },
    { id: "doorless_tower", n: "The Doorless Tower of $", kind: "anomaly", where: "mountain", truthLink: "many_writs", d: "A tower whose top floor has no stair and no door.",
      layers: {
        surface: { n: "The top room", text: "A slender tower stands on a crag above {place}. The windows of its top room glow on some nights, nine times last year by the shepherds' count. There is no stair to that room, and no door into it." },
        study: { n: "Before it is spoken", text: "The tower's founder left a journal, which {investigator} has read. It speaks of 'a room where a law may be written before it is spoken', and of writing in that room, once, long ago, a law for the whole world." },
        dig: { n: "The golden page", points: "library", text: "Climbers who broke in through a window found a lectern, a blank page of gold, and a splinter-shaped socket in the lectern's edge. Faint lines on the page could still be read by lamplight. The founder's journal is kept at {lead}." },
        revelation: { n: "Written once", text: "The Writ was a law written once, on this page, and only one choice among many. With enough shards in the socket it can be written again, differently, by whoever holds the pen. Three demigods have sent climbers to the tower. All three preach restoration." },
      } },
    { id: "consort_statue", n: "The Faceless Consort of $", kind: "shrine", where: "inner", truthLink: "self_broken", d: "A huge statue of a god whose name and face have been chiselled off.",
      layers: {
        surface: { n: "The faceless god", text: "A towering stone figure of the queen's consort stands near {place}, faceless, its plinth scarred where letters were cut away. The queen is carved small at its feet. Cult members leave a single lit candle there each midnight." },
        study: { n: "A day older", text: "{investigator} found the mason's docket in the palace accounts: 'Remove the consort's name and face from the great statue, by the queen's order. Paid, 4 silver.' It is dated the day before the Shattering, while the consort was still at the queen's table. The name came off before the crime it was blamed for." },
        dig: { n: "Inside the plinth", points: "cast:believer", text: "Inside the plinth is a sealed lead box holding the consort's own testimony, written the night before the Shattering. It names the queen and her hammer. The consort's cult keeps a copy; ask {lead}." },
        revelation: { n: "Erased first", text: "The queen erased her husband's name the day before the war, because he knew she meant to break the Writ and had tried to stop her. She broke it the next morning and called him the traitor. Their children have fought over the shards ever since, each sure the traitor's poison is in the other's blood." },
      } },
    { id: "furnace_peak", n: "The Giants' Hearth at $", kind: "ruin", where: "mountain", d: "A furnace the size of a hall on a frozen peak, still burning, tended by the last giants.",
      layers: {
        surface: { n: "Footprints in snow", text: "Smoke rises from a frozen peak above {place} where nothing lives. In the snow are footprints three times a man's length. Herders who go up after lost goats come back with singed beards, and without the goats." },
        study: { n: "Whole valleys", text: "The last giants feed the furnace with the timber of whole valleys; {investigator} counted forty felled slopes in sight of the peak. A giant at the hearth would say only that it was burning before the Writ, and must not go out." },
        dig: { n: "The wing", points: "temple", text: "In the coals lie the twisted remains of a wing, larger than a ship's sail and not of any bird. The bones still move, very slightly. A temple drawing of the same wing, labelled 'the first beast', is kept at {lead}." },
        revelation: { n: "Kept burning", text: "The giants are burning the body of the first creature the Writ was made to hold down, and have been since before the Shattering. With the Writ broken, only the fire keeps it down. The demigods are felling the giants' forests for their siege engines." },
      } },
  ],

  beings: [
    { id: "demigod_knight", n: "Shard-sworn knight", kind: "beast", d: "Warriors changed by a demigod's shard, grown huge and hollow-eyed. They no longer eat or sleep, only guard.", danger: 3, biomes: ["grass", "tempforest", "badlands", "alpine"], look: { size: 2.6, group: [1, 3], move: "solo", speed: 7, col: "#b09040", col2: "#3a3a3a", body: "biped", active: "any", visible: true } },
    { id: "rot_bloom_hound", n: "Bloom-hound", kind: "predator", d: "Dogs swollen with crimson rot flowers, the rot's carriers. Their bite blooms within a week.", danger: 2, biomes: ["swamp", "rainforest", "temprain", "mangrove"], look: { size: 1.2, group: [3, 7], move: "pack", speed: 11, col: "#7a2a3a", col2: "#d08a6a", body: "quad", active: "dusk", visible: true } },
    { id: "grace_moth", n: "Grace-moth", kind: "insect", d: "Pale golden moths that gather around anyone the Writ once favoured. Exiles follow them like lanterns.", danger: 0, biomes: ["grass", "tempforest", "boreal", "dryforest"], look: { size: 0.06, group: [10, 60], move: "swarm", speed: 6, col: "#e8d080", col2: "#ffffff", body: "insect", active: "night", visible: true } },
    { id: "fallen_giant", n: "Hearth-giant", kind: "beast", d: "The last of the giants who served the Writ and were betrayed by it, ash-grey and soot-eyed.", danger: 2, biomes: ["alpine", "peaks", "glacier"], look: { size: 6, group: [1, 2], move: "solo", speed: 4, col: "#6a6a6a", col2: "#c84a1a", body: "biped", active: "day", visible: true } },
  ],

  techs: [
    { id: "bw_writ_law", n: "Writ jurisprudence", field: "writing", level: 1, d: "The study of the Writ's surviving words as law, argued by scholars in every shard-court." },
    { id: "bw_grace_lights", n: "Grace-beacons", field: "navigation", level: 2, d: "Lamps tuned to the guiding lights only the graceless see, used to lead exiles across the broken land." },
    { id: "bw_grafting", n: "Grafting of limbs", field: "medicine", level: 3, d: "The stitching of a slain warrior's limbs onto the living, to borrow their strength. Never entirely successful." },
    { id: "bw_shard_smithing", n: "Shard-smithing", field: "arcana", level: 4, d: "Splinters of the Writ set into blades and crowns, giving a small piece of its law to the bearer." },
    { id: "bw_thorn_walls", n: "Thorn walls", field: "architecture", level: 2, d: "Living hedges of iron-hard thorn grown as walls around holy places and capitals." },
    { id: "bw_new_writ", n: "The writing of law", field: "arcana", level: 5, d: "The art of shaping a new order from gathered shards. Each scholar who claims to know it describes a different world." },
  ],

  units: [
    { id: "bw_shard_knights", n: "Shard-sworn knights", role: "cavalry", mounted: 1, wpn: "lance", kit: "plate", ranks: 2, gap: 3, size: 40, w: 1, mods: [["theme:shard_court", 6], ["theme:writ_loyalists", 3]] },
    { id: "bw_graceless", n: "Graceless wanderers", role: "infantry", wpn: "sword", kit: "light", ranks: 3, gap: 1.6, size: 60, w: 0.6, mods: [["theme:graceless", 8]] },
  ],

  govs: [
    { id: "bw_shard_court", n: "Shard-court", d: "A demigod rules by right of the shard they hold; their law is literally the law of the land.", tags: ["gov:shard_court", "monarchy", "autocracy"], w: 1, forms: ["Shard-Court of $", "Domain of $", "The $ Dominion"], ruler: "Demigod", mods: [["theme:shard_court", 8], ["hierarchical", 1.5]] },
  ],

  faiths: [
    { id: "bw_golden_writ", n: "The Golden Writ", d: "The faith of the shattered law: the Writ will be made whole, and the dead will go back to their graves.", tags: ["faith:bw_golden_writ", "organised"], w: 2, mods: [["hierarchical", 1.5], ["pious", 1.5]], names: ["The Writ of $", "The Golden Law", "The Order of the Whole"] },
  ],

  mapMarks: [
    { kind: "zone", n: "The Shattering-Scar", color: "#6a5a3a", size: [2, 4], count: [1, 2], where: "border", d: "Battle-churned no-man's land between the demigods' domains, where nothing has grown since the war." },
  ],

  storylines: [
    { id: "bw_shard_falls", n: "The Splinter of {place}", scale: "local", anchor: "town", w: 1.5, req: "writ",
      stages: {
        start: { h: "A splinter of the Writ falls near {place}", b: "A shepherd, {person}, found a sliver of gold that hums in the hand. Since then no one in {place} has been able to tell a lie aloud.", wait: [2, 5], fx: { flag: "splinter" }, next: [{ to: "riders", w: 2 }, { to: "village_law", w: 1, mods: [["egalitarian", 2], ["realm:tiny", 2]] }] },
        riders: { h: "Demigod riders come for the splinter of {place}", b: "Shard-sworn knights rode in at dawn demanding the sliver for their lord. {person} has fled into the hills with it.", wait: [2, 6], fx: { unrest: 10 }, next: [{ to: "taken", w: 1.5 }, { to: "swallowed", w: 1 }] },
        village_law: { h: "{place} lives by its own law", b: "With the splinter on the shrine, {place} has become a place of perfect honesty. Merchants avoid it; pilgrims flock there.", fx: { stability: 4, prestige: 3, monument: { tier: 1, name: "The Truthful Shrine of {place}" } }, end: true },
        taken: { h: "The splinter of {place} is taken", b: "The knights caught {person} at the river ford. The sliver is in a demigod's crown now, and {place} burns.", fx: { abandon_town: true, unrest: 12 }, end: true },
        swallowed: { h: "{person} swallows the splinter", b: "Cornered, {person} swallowed the sliver. The knights fell to their knees before a shepherd who now cannot die, and who cannot let them lie.", fx: { flag: "shepherd_demigod", prestige: 5 }, end: true },
      } },
    { id: "bw_reassembly", n: "The Mending of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["writ", { any: ["autocracy", "big", "theme:shard_court", "theme:writ_loyalists"] }],
      stages: {
        start: { h: "{ruler} vows to make the Writ whole", b: "The court of {realm} has declared a holy war to gather the shards. The loyalist knights rally to {capital}.", wait: [4, 10], fx: { prestige: 5 }, next: [{ to: "shard_war", w: 2 }, { to: "scholar_doubt", w: 1, mods: [["learned", 2], ["scholarly", 2]] }] },
        shard_war: { h: "{realm} goes to war for a shard", b: "The armies of {realm} march against the nearest demigod. Rivers ran gold where the shard-sworn fell.", wait: [6, 14], fx: { war: "rival", pop: 0.95 }, next: [{ to: "shard_won", w: 1, mods: [["winning", 2]] }, { to: "shard_lost", w: 1, mods: [["losing", 2]] }] },
        scholar_doubt: { h: "A scholar warns {ruler} against the Mending", b: "{investigator}, keeper of the old archive, has read the queen's letters. 'The Writ was not broken by its enemies,' the scholar writes. 'Ask why.'", wait: [3, 8], next: [{ to: "shard_war", w: 1 }, { to: "new_law", w: 1, mods: [["ruler:ambitious", 3], ["learned", 1.5]] }] },
        shard_won: { h: "{realm} holds two shards", b: "With a second shard in {capital}, the realm's law has changed in a night: wounds close, but the old no longer die.", fx: { prestige: 12, stability: -4, flag: "two_shards" }, end: true },
        shard_lost: { h: "The holy war of {realm} fails", b: "The demigod's knights broke the host on the field. {ruler}'s crusade is over, and the loyalists blame the court.", fx: { prestige: -10, stability: -8 }, end: true },
        new_law: { h: "{ruler} means to write a new Writ", b: "{ruler} has stopped speaking of restoration. The scribes of {capital} have been set to draft a new law for the world, with {ruler} at its centre.", fx: { flag: "new_writ", stability: -6, unrest: 10, science: { arcana: 0.6 } }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", who: "The Golden Writ catechism", text: "From the Golden Writ catechism, taught to every child of {realm} at seven, {year} text: 'The Writ was the world's law, made into one golden object. When it was whole, the harvest never failed, no child died before its mother, and the dead went quietly. It was broken into shards. Make it whole and all will be so again.' Question 14 asks who broke it. The answer has been changed twice in the margin." },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "A boy of {place}, to a travelling scribe", text: "A boy of {place}, to a travelling scribe collecting tales, {year}: 'My granny said the Writ was a ring, my uncle says it was a tree, and the priest says it was a word. They all agree it broke, about 200 years back, and that nothing has gone right since. The priest says the pieces are with the demigods. Granny said good riddance, and the priest stopped coming to dinner.'" },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "Court History of the Shattering", text: "From the official History of the Shattering, by the court of {realm}, {year} edition, approved by {official}: 'The Writ was shattered by the traitor-consort and his allies among the giants. The queen died defending it, and her children war only because the traitor's poison is in their blood. The consort's name is not to be printed in this or any book.'" },
    { depth: "core", about: "truth:imposed", source: "ruin", bias: "true", reliable: true, plain: true, who: "The buried city's gate, translated by {investigator}", text: "Carved over the gate of the buried city, translated by {investigator} in {year}: 'They brought a law from beyond the sky and laid it on us like a lid. Before it, our dead went to rest and our fields grew wild. After it, the dead could not finish dying. We refused it, and they buried us under painted stars. Remember that we were the world's own order.' Forty thousand names follow." },
    { depth: "core", about: "truth:imposed", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, gravedigger", text: "Diary of {survivor}, gravedigger of the Unended catacombs, {year}: 'Since the Shattering a few of them die properly again, three this month. The priests call it a curse. I have never seen faces so peaceful. My own mother has twitched in pit nine for eleven years, wound in roots. I asked the loyalists to leave my mother be when they come for the splinters. They said no.'" },
    { depth: "core", about: "truth:imposed", source: "oral", bias: "exaggerated", reliable: "partial", who: "A herder who carries wood to the giants", points: "site:furnace_peak", text: "A herder of {place} who carries wood up to the giants, to {investigator}, {year}: 'The giants say they guarded the Writ for its makers, that the makers were not gods of this world, and that they will never do it again. One told me the makers came down three times, and the third time stayed. They pay me five iron bars a load. The hearth is at {lead}.'" },
    { depth: "core", about: "truth:imposed", source: "heretic", bias: "heretic", reliable: "partial", who: "A rot-cult preacher, copied by a spy", points: "site:false_sky_city", text: "Sermon of a rot-cult preacher in the bloom-rot marshes near {place}, {year}, copied by a loyalist spy: 'Decay is the world breathing again. The bloom is not a sickness. The Writ was the sickness. Three hundred of us live in the rot, and none of us has the twitching death. Go and see the buried city at {lead}, where they put the last people who said so.'" },
    { depth: "core", about: "truth:imposed", source: "temple", bias: "official", reliable: false, who: "{official}, herald of the Loyalists", text: "Sermon of {official}, herald of the Old Order Loyalists, {year}: 'The Writ is the world's own nature made visible. Death and decay are not its enemies but its wounds, and every rot in the land proves how badly the world needs it mended. Twelve rot-villages were cleansed this year, and their splinters taken for the Mending.'" },
    { depth: "core", about: "truth:self_broken", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, keeper of the old archive", points: "archive", text: "A letter in the queen's hand, found in the old archive by {investigator}, dated the night before the Shattering: 'Tomorrow I am free of it, whatever it costs them. My husband knows. He must not be [the rest is cut away].' The catalogue lists twelve such letters. Eleven are missing, and the borrowing slip names {lead}." },
    { depth: "core", about: "truth:self_broken", source: "ruin", bias: "true", reliable: true, plain: true, who: "The queen, scratched inside the pillar", text: "Scratched on the inner face of the golden pillar with a hammer's claw, found by {investigator} in {year}: 'I was its keeper and its prisoner. Now I am neither. I broke it myself, and tomorrow I will tell them my husband did it.' The letters match the queen's hand in the archive letters, stroke for stroke, down to a crossed seven." },
    { depth: "core", about: "truth:self_broken", source: "person", bias: "garbled", reliable: "partial", who: "An old palace servant, dying", text: "An old palace servant of {place}, dying, to the priest, {year}: 'The queen came out of the hall alone, with a hammer, and she was smiling. They told us it was the consort. We knew better, all thirty of us, and we said nothing. The steward who saw it first was hanged that week. That is the whole of what I have to confess.'" },
    { depth: "core", about: "truth:self_broken", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "{believer}, of the consort's cult", points: "site:consort_statue", text: "Midnight handbill of the consort's cult, signed by {believer}, {year}: 'The consort tried to stop the queen. My family has kept the consort's name for 200 years, one keeper in each generation. My father whispered it in the square of {place}, and the loyalists cut out my father's tongue for it. The proof is sealed in the plinth at {lead}, and nobody will open it.'" },
    { depth: "core", about: "truth:self_broken", source: "library", bias: "propaganda", reliable: false, who: "Court pamphlet on the consort", text: "Court pamphlet of {realm} on the faceless statues, {year}: 'The consort's face was removed by the grieving queen herself, after his treason. To speak his name is to share his guilt. Any person heard whispering it will lose the tongue that spoke it. Forty such sentences were carried out last year.'" },
    { depth: "core", about: "truth:many_writs", source: "ruin", bias: "true", reliable: true, plain: true, who: "The gold page, read by {investigator}", text: "Faint writing on the golden page in the doorless tower, read by {investigator} by lamplight, {year}: 'An order is chosen, not found. Gather the pieces and choose again.' Beneath it, in the founder's hand: 'I wrote the first. Let whoever holds the shards write the next.' The archivist's note: the Writ was one law among many, written on this page. Whoever mends it will not restore it. They will rewrite it, with the pen on this lectern." },
    { depth: "core", about: "truth:many_writs", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A cloth merchant of {place}", points: "sub:star_sorcerer", text: "A cloth merchant back from the star-demigod's land, to the guild at {place}, {year}: 'The law is different there. Nobody dies before the stars say, and nobody lives a day past it; my wife's cousin was told the day of her own death at nine. I sold forty bales and left. Each shard-holder is already writing a world of their own. Ask at {lead} what the star-demigod's charter says.'" },
    { depth: "core", about: "truth:many_writs", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, keeper of the old archive", points: "archive", text: "Minutes of a shard-court's war council, {year}, obtained by {investigator}: 'If we hold four shards we do not restore the old law. We [struck through]. Speak of restoration in public.' Present: the demigod, six generals, one scribe. The scribe was dismissed the next day. The full minutes are kept in {lead}." },
    { depth: "core", about: "truth:many_writs", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, the farmer with the splinter", text: "Statement of {person}, the farmer who found a splinter of the Writ, to a magistrate, {year}: 'I put the splinter on our shrine and wished nobody in the village could steal. It worked. Then riders came from three demigods, and each lord wanted it for a different law. They burned my barn to make me choose one. I chose none. They took my daughter instead, to hold until I do.'" },
    { depth: "core", about: "truth:many_writs", source: "temple", bias: "official", reliable: false, who: "{official}, herald of the Loyalists", text: "Reply of {official}, herald of the Old Order Loyalists, to a scholar who asked whether the Writ could be rewritten, {year}: 'There is one Writ and one Order. Gather the seven shards and it can only be made what it was. Every demigod who holds a shard has sworn to us in writing that they want only restoration. We keep the oaths on file, all seven, and we believe them. Your question has been noted.'" },
    { depth: "sub", about: "sub:shard_court", source: "traveller", bias: "true", reliable: "partial", who: "A wool trader in the grain-demigod's land", text: "A wool trader's letter from the domain of the grain-demigod, {year}: 'Here the wheat never stops ripening; they reap four times a year. Neither do the levies stop: every man over fourteen is a soldier, and the harvest feeds the war. I sold my wool to the army at a fine price, and was very nearly enlisted at the city gate.'" },
    { depth: "sub", about: "sub:rotting_domain", source: "person", bias: "true", reliable: true, who: "A court physician of the bloom-rot", text: "Case notes of a court physician to the demigod of the bloom-rot, {year}: 'The crimson flowers are in her lungs now; three blooms came up at the last bleeding. She asks for the windows open, because she says she can smell them blooming. The court has been told it is a cold. The shard on her brow has turned the colour of rust.'" },
    { depth: "sub", about: "sub:graceless", source: "oral", bias: "exaggerated", reliable: "partial", who: "The landlord of the inn at {place}", text: "The landlord of the inn at {place}, to a magistrate, {year}: 'The exile walked in following a light none of us could see, and said she had come to mend the world. She was the fourth this year. They are graceless folk, cast out of the Writ's favour generations back, and every one swears to be the one. The fourth paid her bill, which the other three did not.'" },
    { depth: "sub", about: "sub:deathless", source: "library", bias: "official", reliable: "partial", who: "Ordinance of the court of {realm}", points: "site:deathless_catacomb", text: "Ordinance of the court of {realm}, {year}: 'The unended dead are to be bound, entombed and prayed over until the Writ is made whole. They are not to be burned. Gravediggers are to be paid six silver a week, as soldiers are. Any gravedigger who lets one of the dead go to rest by other means will hang. The catacombs at {lead} are under the crown's seal.'" },
    { depth: "sub", about: "sub:peasant_shard", source: "oral", bias: "garbled", reliable: "partial", who: "A pedlar at {place}", text: "A pedlar's tale at the market of {place}, {year}: 'In the farmer's village nobody can steal. I tried, to see. My hand would not close on the purse, though it lay right there on the stall. Three demigods have sent riders, and the village has posted a boy on the road to count them. He has counted 60.'" },
    { depth: "sub", about: "sub:loyalists", source: "temple", bias: "propaganda", reliable: false, who: "{official}, herald of the Loyalists", points: "archive", text: "Proclamation of the knights of the Whole, read at the market cross of {place} by {official}, {year}: 'The Old Order Loyalists, knights of the Whole, have never put a village to the torch. The twelve villages that burned this year were already lost to the rot. Their splinters have been taken into safekeeping for the Mending, and are listed in {lead}.'" },
    { depth: "sub", about: "sub:queens_letters", source: "archive", bias: "true", reliable: "partial", who: "{investigator}, keeper of the old archive", points: "site:broken_monolith", text: "Note of {investigator}, keeper of the old archive, {year}: 'The queen's letters were written the night before the Shattering. They do not read like a victim's. The queen writes of freedom, of a hammer, of the hour the guard changes. I have compared the queen's hand with the scratching inside the split pillar at {lead}. I will not put the result in writing yet.'" },
    { depth: "sub", about: "sub:star_sorcerer", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A hired climber", points: "site:doorless_tower", text: "A climber's statement to the court of {realm}, {year}: 'The star-demigod hired nine of us to break into the top room of a tower with no stair. We got in through a window. There was a lectern, a gold page with writing too faint to read, and a hole the shape of a splinter. Our master wants the page. The tower is at {lead}. Two of us fell.'" },
    { depth: "site", about: "site:furnace_peak", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A goatherd above {place}", text: "A goatherd's account of the giants' hearth above {place}, {year}: 'The giant at the furnace would not let me near. I asked what it was burning. It said: if it goes out, it gets up. I asked what does. It threw another tree on. I have moved my goats to the low pastures, three days further on, and I do not mind the walk.'" },
  ],
};
