// The Downward Throat: a bottomless chasm of layered wonders; going down is easy, and climbing back up costs you.
export default {
  id: "downward_throat",
  name: "The Downward Throat",
  kind: "shape",
  family: "world",
  pitch: "A round chasm with no known bottom lies at the centre of the land. Its ledges hold relics worth fortunes, but climbing back up makes people sick, and deep enough, it changes them.",
  slots: ["economy-resource", "monster-source", "augmentation"],
  tone: ["wonder", "horror"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "regional",
  genres: ["fantasy", "shonen", "grimdark", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "inner_sun", w: 3 }, { id: "body_of_the_world", w: 2 }, { id: "elder_lattice", w: 2 }],

  cast: [
    { role: "investigator", n: "a physician of the rim infirmary who has measured the climbing sickness in 212 delvers", home: "inner", stance: "Wants the sickness named and measured; believes it is a physical force, not a curse." },
    { role: "official", n: "the rim authority's warden of descents, who issues tokens and opens and closes ledges", home: "capital", stance: "Wants the relic tithe steady and the rim calm; denies anything that would frighten the cartels." },
    { role: "believer", n: "a Descender preacher who leads pilgrims over the rim", home: "inner", stance: "Believes the bottom is calling and the climb back up is the only sin." },
    { role: "survivor", n: "a black-token delver who came up from the fifth ledge with half a face changed", home: "remote", stance: "Wants the orphans kept off the ropes; will say what the ledges cost, but not what is below them." },
  ],

  truths: [
    { id: "field", n: "The deep keeps what it gives", d: "A force fills the throat and holds on to everything that goes down; the climbing sickness is that force pulling back. Ladder-fibre and slow methods shield a climber from it. The rim authority has known since the deep camp's trials on orphans, sells fibre shrouds to cartel delvers, and still sends the orphans up bare.", tags: ["truth:throat_field"],
      known: [
        "Delvers come up sick, and sicker the higher they climb in one day. {investigator} at the rim infirmary thinks the sickness behaves like a weight, not a disease. The rim temple calls it the gods' judgement on greed.",
        "Letters from black-token delvers describe a grip that loosens if a climber goes slowly and carries nothing. A ladder below the deepest mapped ledge seems to let climbers come up clean. Nobody has explained how.",
        "A deep camp on the fifth ledge tested fibre shrouds on orphans. One child climbed clean in a shroud; the child beside it, without one, did not come back. The pages after that test are cut out of the log.",
        "Confirmed: a force in the throat holds everything that goes down, and the sickness is its pull. Ladder-fibre shields a climber from it. The rim authority knows, sells shrouds to the cartels at 2,000 crowns, and sends the orphans up without them.",
      ] },
    { id: "wound", n: "The throat is a wound", d: "The land is living flesh and the chasm is a wound in it. The sickness is the land's defence against the people climbing in and out, and every relic hauled up tears the healing open again. The rim authority has drilled and hauled for 300 years because the relic tithe pays for the crown, and the wound is wider now than when it started.", tags: ["truth:throat_wound"],
      known: [
        "A red seep on the second layer heals small cuts, and the upside-down forest rises toward the rim every year. The assay office calls the seep an iron spring, and a crane-hand who preached otherwise was barred from the cranes.",
        "{investigator} found that the seep thickens when relics are hauled up and thins when the cranes stop. The rope-village folk call every relic a stitch pulled out, and will not drink the water.",
        "Behind the seep is a pulsing grey-pink mass growing over an old authority drill hole. Murals in the hanging city show a spear driven into a sleeping beast, and a city falling into the hole.",
        "Confirmed: the land is alive and the throat is a wound in it. The sickness is its defence, and every relic hauled up keeps the wound open. The rim authority has known for generations and keeps drilling, because the relic tithe pays for the crown.",
      ] },
    { id: "invitation", n: "The throat is an invitation", d: "The chasm was cut as a road by a people who went down first, and a power at the bottom calls others after them. The sickness changes climbers' bodies, and only those changed enough can reach the bottom. The black-token delvers the guild mourns as dead went on down, and the rim authority burns the letters they send back.", tags: ["truth:throat_invitation"],
      known: [
        "A black token belonging to a delver missing for 30 years came up in a relic basket, scratched with the words 'come down'. The rim authority says there is no bottom and no voice, and seizes letters from below.",
        "The statues in the downward temple kneel toward the dark, and a stair under its altar is cut for six-toed feet. Hollowed delvers who come over the rim draw a door with people waiting beside it.",
        "{survivor} has had the temple lintel read: the road down was cut by those who went first, and it is kept for those who have changed. Eleven delvers took the stair in one year; four of their tokens have come back up.",
        "Confirmed: the throat is a road, and a power at the bottom calls people down. The sickness changes climbers until they can reach it. The black-token delvers the guild mourns are not dead. They went on, and some of them write back.",
      ] },
  ],

  tags: ["abyss"],

  subthemes: [
    { id: "delvers_guild", n: "The Delvers' Guild", d: "Delvers are ranked by coloured tokens, from pale apprentices to black-token legends who went down and never came up. The guild hall is a shrine to its missing.", w: 1.5, mods: [["guilds", 2], ["urbane", 1.5]], tags: ["theme:delvers_guild"] },
    { id: "rim_orphanage", n: "The Rim Orphanage", d: "The rim authority runs an orphanage that turns out cheap child-delvers. Its charity is famous; its graduation rates are not published.", w: 1.2, mods: [["hierarchical", 1.5], ["poor", 1.5]], tags: ["theme:rim_orphanage"] },
    { id: "token_message", n: "The Token from Below", d: "A black token belonging to a legendary delver came up in a relic basket, with a note scratched into it: 'come down'.", w: 1, truthLink: "invitation", tags: ["theme:token_message"] },
    { id: "immune_child", n: "The Child Who Climbs", d: "An orphan apprentice came up from the fourth ledge without a nosebleed. The guild wants her trained; the scholars want her opened.", w: 0.8, truthLink: "invitation", tags: ["theme:immune_child"] },
    { id: "rising_layer", n: "The Rising Layer", d: "The upside-down forest of the second layer is closer to the surface every year. Its trees are now visible from the rim.", w: 0.9, truthLink: "wound", tags: ["theme:rising_layer"] },
    { id: "relic_cartels", n: "The Relic Cartels", d: "Distant banking houses fund expeditions and own the delvers who make them. A good relic can buy a duchy; a bad one can empty one.", w: 1.3, req: { any: ["mercantile", "has:port", "gov:merchant"] }, mods: [["rich", 1.5]], tags: ["theme:relic_cartels"] },
    { id: "deep_camp", n: "The Deep Camp", d: "A scholar has built a camp on the fifth ledge and pays well for children. The guild pretends not to know.", w: 0.7, req: { any: ["scholarly", "academies", "autocracy"] }, truthLink: "field", tags: ["theme:deep_camp"] },
    { id: "rope_trade", n: "The Basket Rope", d: "A village of changed folk on the third ledge trades with the rim by basket and rope. They send up wonders; they ask for salt, string and news.", w: 1, tags: ["theme:rope_trade"] },
    { id: "cloud_colour", n: "The Cloud Column", d: "The pillar of cloud above the throat is seen across the continent. This year it has turned the colour of a bruise, and the farmers downwind are uneasy.", w: 0.9, truthLink: "wound", tags: ["theme:cloud_colour"], mark: { kind: "zone", n: "Under the column", color: "#7a6a8a", size: [2, 4], where: "inner" } },
    { id: "descenders", n: "The Descenders", d: "A creed that holds the bottom is paradise and the climb back is the only sin. Its faithful go down singing and do not come back.", w: 1, req: { any: ["pious", "mystic", "zealous"] }, truthLink: "invitation", tags: ["theme:descenders"] },
    { id: "second_throat", n: "The Second Throat", d: "A smaller chasm has opened in a distant province, and the same cloud is rising from it.", w: 0.6, req: { any: ["realm:large", "realm:vast", "near:rift"] }, tags: ["theme:second_throat"], mark: { kind: "zone", n: "The new pit", color: "#3a2a3a", size: [1, 1], where: "remote" } },
  ],

  sites: [
    { id: "fourth_ledge", n: "The Downward Temple of $", kind: "shrine", where: "inner", truthLink: "invitation", d: "A temple on the fourth ledge whose statues all face down into the dark.",
      layers: {
        surface: { n: "Tokens at the door", text: "Delvers who reach the fourth ledge leave a token at the temple door for luck. The guild counted 1,400 there in {year}, most of them pale. Nobody sleeps inside. {survivor} slept there once and says every dream was of walking down a stair." },
        study: { n: "The kneeling statues", text: "Thirty-two statues kneel along the nave, all facing the far wall, where the floor drops into the dark. Their carved hands are cupped open, as if to receive a gift from below. The faces are worn smooth. The feet have six toes." },
        dig: { n: "The stair under the altar", text: "Under the altar slab a stair goes down, its steps too wide and shallow for human feet. Guild chalk on the first landing tallies eleven delvers who took it in {year}. The guild's descent register for that year is kept in {lead}.", points: "archive" },
        revelation: { n: "A waystation", text: "The temple was a waystation on a road. Its builders went down on purpose and let the sickness change them so they could go further. The guild has read the lintel since {year} and still sends pale-token orphans past the door. Eleven took the stair. Four of their tokens have come back up, scratched 'come down'." },
      } },
    { id: "upside_city", n: "The Hanging City of $", kind: "ruin", where: "inner", d: "A city built upside-down on the wall of the shaft, its towers pointing into the void.",
      layers: {
        surface: { n: "Spires from the rim", text: "On clear days, spires can be seen from the rim of {place}, hanging from the shaft wall like icicles about 900 yards down. Rim children count them for luck. There are thirty, and the guild charges a crown to look through its glass." },
        study: { n: "A different down", text: "Inside, everything obeys its own down. Stairs, wells and graves all point toward the centre of the shaft, not its bottom. {investigator} set a lead ball on the floor of the main square and watched it roll sideways off the edge." },
        dig: { n: "The painted archive", text: "The city archive holds murals of a people who lived on flat ground before the throat opened. The last panel shows them waking with their world turned on its side. A rubbing of all 40 panels was sent up and filed in {lead}.", points: "library" },
        revelation: { n: "The city that stayed", text: "The throat was not always here. It opened under a living city of thirty towers about 600 years ago, and its people chose to stay, living sideways for four generations. The few who climbed out founded the rim towns. The crane families still carry the thirty towers on their crests, drawn upright." },
      } },
    { id: "endless_ladder", n: "The Ladder over $", kind: "anomaly", where: "remote", truthLink: "field", d: "A ladder of unknown fibre hanging in the dark below the deepest mapped ledge.",
      layers: {
        surface: { n: "A ladder in the letters", text: "Five black-token letters, written years apart, mention a ladder below the deepest mapped ledge that 'hangs from nothing'. {survivor} kept all five in a tin box and believed them long before the guild did." },
        study: { n: "Fibre that will not burn", text: "A three-foot length of the ladder's fibre came up in {year}. It will not burn in a forge, and no surface blade will cut it. The guild's smith broke twelve chisels on it and sent the bill to the warden." },
        dig: { n: "The bleeding test", text: "Two delvers climbed side by side from the sixth ledge, one on the ladder and one on the rock beside it. The one on the ladder came up clean. The other lost two teeth and an eye. {investigator}'s notes on the test went to {lead}.", points: "cast:investigator" },
        revelation: { n: "A road around the grip", text: "The grip of the deep can be cheated. Someone who understood the force built this ladder to climb against it. The rim authority has held a length of its fibre since {year}; {official} sells shrouds woven from it to cartel delvers at 2,000 crowns each. The orphans still climb bare." },
      } },
    { id: "deep_relic_cache", n: "The Relic Shelf at $", kind: "dig", where: "any", d: "A cache of relics that only work at the depth they were found.",
      layers: {
        surface: { n: "A warehouse of dead relics", text: "A merchant of {place} bought 212 'dead' relics at a bankrupt's sale for 30 crowns. They sit in crates in a riverside warehouse. The merchant uses the largest, a brass bowl, as the cat's dish." },
        study: { n: "The depth tags", text: "Every relic carries a tag naming the ledge and depth where it was found. {investigator} tested the delvers' claim that each works only within a few yards of its depth. It held for all nine relics taken back down." },
        dig: { n: "Needles pointing down", text: "Taken back to their depths, the relics hum awake and swing to point straight down, like compass needles. All nine point at one spot below the deepest ledge. The bearings were plotted on a chart now kept in {lead}.", points: "archive" },
        revelation: { n: "Parts of one thing", text: "The relics were never meant to leave. They are parts of one larger thing at the bottom, and each pulls toward it. The cartels have sold over 40,000 of them to the courts of the world as curiosities. In every vault from here to the coast, they are all pointing the same way." },
      } },
    { id: "wound_canyon", n: "The Red Seep of $", kind: "anomaly", where: "any", truthLink: "wound", d: "A side-cleft on the second layer where the rock bleeds warm red water.",
      layers: {
        surface: { n: "The healing flasks", text: "Delvers fill flasks at a red seep on the second layer. The warm water closes small cuts overnight, and rim apothecaries pay 3 crowns a flask. The rope-village folk will not drink it, and spit when they pass the cleft." },
        study: { n: "The crane count", text: "{investigator} logged the seep's flow beside the crane station's tally for two years. It thickens in the weeks when relics are hauled up and thins when they are lowered back. In the one winter the cranes stopped, it nearly dried." },
        dig: { n: "Behind the rock face", text: "Behind a foot of rock is a grey-pink mass that pulses about once a minute. Pale threads are growing over an old drill hole, closing it. The bit still stuck in the hole bears the rim authority's stamp; the drilling order is filed in {lead}.", points: "archive" },
        revelation: { n: "The wound", text: "The land is living flesh and the throat is a wound in it. Every relic hauled up tears the healing open again. The rim authority has drilled and hauled for 300 years because the relic tithe pays for the crown. The threads close a drill hole in a month. The authority cuts a new one in a week." },
      } },
  ],

  beings: [
    { id: "hush_hunter", n: "Hush-hunter", kind: "predator", d: "A long-limbed ledge predator that hunts by sound and mimics the cries of its prey. Delvers work in silence for fear of it.", danger: 3, biomes: ["peaks", "alpine", "temprain"], look: { size: 3, group: [1, 2], move: "solo", speed: 15, col: "#3a3a4a", col2: "#c8c0a0", body: "quad", active: "any", visible: false } },
    { id: "lantern_drifter", n: "Lantern drifter", kind: "small", d: "A floating jelly that drifts up the updraft at dusk, glowing gold. Harmless, unless touched.", danger: 1, biomes: ["peaks", "alpine", "temprain", "rainforest"], look: { size: 0.6, group: [10, 80], move: "swarm", speed: 2, col: "#e8c060", col2: "#a06030", body: "insect", active: "dusk", visible: true } },
    { id: "throat_hollowed", n: "The Hollowed", kind: "beast", d: "Delvers who climbed too far and changed: furred, long-eyed, gentle or terrible. Some still remember their names.", danger: 2, biomes: ["peaks", "alpine", "temprain"], look: { size: 1.2, group: [1, 6], move: "pack", speed: 6, col: "#8a7a6a", col2: "#e0d0b0", body: "biped", active: "night", visible: true } },
  ],

  techs: [
    { id: "dt_depth_tokens", n: "Depth tokens", field: "writing", level: 1, d: "Rank tokens and depth charts that tell a delver how deep they may go, and how sick they will be coming up." },
    { id: "dt_ascent_rest", n: "Slow ascent", field: "medicine", level: 2, d: "Resting stations every few hundred yards, where climbers wait out the sickness before going on." },
    { id: "dt_rim_cranes", n: "Rim cranes", field: "engineering", level: 2, d: "Great timber cranes and basket lifts that bring relics up without bringing people with them." },
    { id: "dt_depth_relics", n: "Relic grading", field: "natural_philosophy", level: 3, d: "Relics catalogued by depth and tier, from curiosities to world-breakers." },
    { id: "dt_field_shield", n: "Field shrouds", field: "arcana", level: 4, d: "Cloaks woven with ladder-fibre that dull the climbing sickness. Each costs a black-token's fortune." },
  ],

  units: [
    { id: "dt_delvers", n: "Delver company", role: "infantry", wpn: "spear", kit: "light", ranks: 2, gap: 2.5, size: 40, w: 0.8, mods: [["theme:delvers_guild", 6], ["theme:relic_cartels", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "The Throat", color: "#1e1a24", size: [1, 2], count: [1, 1], where: "inner", d: "A round chasm with no known bottom, ringed by tiered rim-towns, a pillar of cloud standing over it." },
    { kind: "zone", n: "Relic country", color: "#8a7a5a", size: [3, 6], count: [1, 1], where: "inner", d: "Crowded lands around the rim, rich on relics and the expeditions that chase them." },
  ],

  storylines: [
    { id: "dt_come_down", n: "The Token from Below", scale: "local", anchor: "town", w: 1.5, req: "abyss",
      stages: {
        start: { h: "A legend's token surfaces in {place}", b: "In a basket of relics hauled up near {place} lay the black token of a delver missing for thirty years. Scratched on the back: 'come down'.", wait: [1, 4], next: [{ to: "expedition", w: 2 }, { to: "ignored", w: 1, mods: [["stable", 1.5]] }] },
        expedition: { h: "{person} goes down after the token", b: "{person}, an apprentice raised by the missing delver, has slipped past the rim guard with a pack and a rope. A friend, {person2}, went too.", wait: [4, 12], next: [{ to: "letter_up", w: 1.5 }, { to: "returns_changed", w: 1 }, { to: "lost", w: 1 }] },
        ignored: { h: "The token of {place} is sold at auction", b: "The guild called it a forgery. A cartel bought it for a fortune, and nobody has gone down after the name.", fx: { treasury: 20 }, end: true },
        letter_up: { h: "A letter comes up the rope to {place}", b: "A sealed letter came up in a relic basket in {person}'s hand: the legend is alive, very far down, and the bottom 'is not what they told us'.", wait: [3, 8], fx: { science: { natural_philosophy: 0.6 } }, next: [{ to: "pilgrimage", w: 1, mods: [["theme:descenders", 3], ["pious", 1.5]] }, { to: "sealed_letter", w: 1 }] },
        returns_changed: { h: "{person2} climbs out of the throat, changed", b: "{person2} came over the rim at dawn: furred, long-eyed and gentle, unable to speak but able to draw. The drawings show a door.", fx: { unrest: 6, flag: "door" }, end: true },
        lost: { h: "No word from below", b: "The ropes came up cut. In {place} they have added two names to the wall of the missing.", fx: { stability: -2 }, end: true },
        pilgrimage: { h: "Hundreds go down the throat after the letter", b: "The Descenders read the letter as scripture. Three hundred of the faithful went over the rim of {place} in one week, singing.", fx: { pop: 0.9, unrest: 10 }, end: true },
        sealed_letter: { h: "The guild seals the letter from below", b: "The Delvers' Guild locked the letter in its vault. The black-token delvers have been quietly buying rope ever since.", fx: { stability: 2 }, end: true },
      } },
    { id: "dt_world_breaker", n: "The Relic of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["abyss", { any: ["rich", "big", "autocracy", "atwar"] }],
      stages: {
        start: { h: "A world-breaker relic comes up from the deep", b: "Delvers in the pay of {realm} have hauled up a relic of the highest tier. It killed the crane crew, and is now in a lead box in {capital}.", wait: [3, 8], fx: { prestige: 8 }, next: [{ to: "weaponised", w: 1, mods: [["atwar", 3], ["ruler:ambitious", 2]] }, { to: "studied", w: 1.5 }] },
        weaponised: { h: "{realm} turns the deep relic on its enemies", b: "Carried before the army of {realm}, the relic flattened a fortress in a moment. The cloud column over the throat has turned black.", wait: [4, 10], fx: { prestige: 15, discovery: "warfare" }, next: [{ to: "throat_answers", w: 1.5 }, { to: "relic_war", w: 1, req: "has:rival" }] },
        studied: { h: "Scholars of {realm} study the deep relic", b: "{investigator}, the rim physician who has measured the climbing sickness for years, has been given the box and a tower. Lights burn there every night.", wait: [4, 10], fx: { science: { natural_philosophy: 0.8 } }, next: [{ to: "returned_down", w: 1, mods: [["pious", 1.5], ["ruler:just", 2]] }, { to: "throat_answers", w: 1 }] },
        throat_answers: { h: "The throat convulses", b: "The ground around the throat heaved, and the rim-towns slid into the dark. Delvers say the deep took back what it was owed.", fx: { pop: 0.85, stability: -15, abandon_town: true }, end: true },
        relic_war: { h: "{rival} marches to seize the deep relic", b: "Unwilling to live in the shadow of the relic, {rival} has declared war on {realm}.", fx: { war: "rival" }, end: true },
        returned_down: { h: "{realm} lowers the relic back into the deep", b: "On the advice of {investigator}, the relic was lowered back on a thousand-yard chain. The cloud column paled again within a month.", fx: { stability: 6, prestige: 3 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: true, who: "Delvers' Guild primer", text: "Delvers' Guild primer, page one, issued to every apprentice at {place}: 'Down is free. Up is paid for. At the first ledge, a headache; at the third, blood from the nose; at the sixth, your shape. The token on your cord, pale, red, blue or black, tells the rim warden how far you may go. Below the sixth ledge we have no chart, because nobody has climbed back to draw one.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a relic merchant's sale catalogue", text: "Sale catalogue of a relic merchant at {place}, spring auction of {year}: 'Item 44. A pewter cup that fills itself with clean water every hour. Found on the seventh ledge by a black-token delver. Previous owners: three, all deceased, none of them because of the cup. Reserve price 900 crowns. The house makes no claim about the seventh ledge, and advises buyers not to ask.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "{investigator}, rim physician", text: "Skipping rhyme of the rim children of {place}, written down by {investigator}, physician, who heard it under the infirmary window in {year}: 'Pale, then red, then blue, then black; you can go down but you can't come back.' The children take one step at each colour. At black, one child jumps off the low wall, and the others must pretend for the rest of the game that the child is gone." },
    { depth: "core", about: "truth:field", source: "person", bias: "true", reliable: true, plain: true, who: "{survivor}, black-token delver", text: "Letter from {survivor}, black-token delver, sent up by basket from the fifth ledge in {year}: 'It is not a curse and it is not a disease. It is a grip. Everything down here is held, and the hold tightens the faster you pull against it. Climb slow, carry nothing, rest at every station, and it loosens. I came up 400 yards that way with no blood. Tell the orphans. The warden never will.'" },
    { depth: "core", about: "truth:field", source: "library", bias: "official", reliable: "partial", points: "archive", who: "{investigator}, rim physician", text: "Paper read to the guild by {investigator}, physician of the rim infirmary, {year}: 'I have examined 212 delvers on their way up. The sickness follows the height climbed in a day, not the time spent below. A delver who lives a month on the second ledge suffers less than one who climbs from the fourth in an afternoon. It behaves less like a disease than a weight. I asked for the deep camp's records and was refused. A copy is held in {lead}.'" },
    { depth: "core", about: "truth:field", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "the deep camp's log", text: "Log of the deep camp on the fifth ledge, day 31, in the camp scholar's hand: 'Subject seven, aged eleven, wore the fibre shroud and climbed to the fourth ledge with no bleeding. Subject eight, {person}, aged eleven, climbed on the next rope without it. At the fourth ledge eight could not see. At the third...' The next four pages are cut out with a knife. The register lists {person} as 'returned to the orphanage'. The orphanage has no record of a return." },
    { depth: "core", about: "truth:field", source: "temple", bias: "official", reliable: false, who: "the rim temple", text: "Sermon of the rim temple at {place}, read on the feast of tokens in {year}: 'The sickness of the climb is the gods' judgement on greed. It falls on those who take more than their share. The delver who brings up one relic and tithes a tenth of its price climbs in comfort. The delver who hides a second relic in a boot bleeds. Honest delvers have nothing to fear. The tithe box stands at the rim gate.'" },
    { depth: "core", about: "truth:wound", source: "ruin", bias: "true", reliable: true, plain: true, who: "inscription in the hanging city", text: "Inscription under the great mural of the hanging city, copied by {investigator} in {year} and read aloud, for a sack of salt, by a rope-village elder who still speaks the old tongue: 'The land lay asleep, and it was alive. Our kings drove an iron spear into its side for the red stone. The land opened, and we fell into the wound with our city. The wound is still trying to close. Take nothing more from it, or it will never heal.' The mural above shows the spear, thirty towers, and the city falling." },
    { depth: "core", about: "truth:wound", source: "oral", bias: "true", reliable: "partial", points: "site:wound_canyon", who: "a rope-village elder", text: "Said by a rope-village elder on the third ledge to {investigator}, who wrote it down at the basket station in {year}: 'Every relic you take up is a stitch pulled out. We have watched these walls for six generations. When your cranes run double shifts, the red water runs. When they stop for winter, the rock grows over the old drill holes a finger's width a month. Go and look at the seep at {lead} if you doubt me.' The elder would not say whose stitches." },
    { depth: "core", about: "truth:wound", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "a rim warden's arrest record", text: "Arrest record of the rim warden at {place}, {year}: '{person}, crane-hand, preached at the rim gate for three days that the cloud above the throat is breath, the red water is blood and the quakes are pain. Quoted: we are maggots in a wound and we call it a mine. The crowd reached 300. {person} is fined 20 crowns and barred from the cranes for life. The family has been moved off rim land.'" },
    { depth: "core", about: "truth:wound", source: "library", bias: "official", reliable: false, who: "{official}, warden of descents", text: "Survey of the second layer by the rim authority's assay office, {year}, signed by {official}, warden of descents: 'The red seeps of the second layer are iron-rich springs. Assays of 14 flasks show iron, salt and nothing else. They are of no more significance than the red rivers of the south. Reports that the seeps thicken when relics are hauled up come from delvers paid by the barrel, and are to be disregarded.'" },
    { depth: "core", about: "truth:invitation", source: "ruin", bias: "true", reliable: true, plain: true, who: "{survivor}, black-token delver", text: "Lintel of the downward temple on the fourth ledge, copied by {survivor}, black-token delver, in {year}, with a note: 'The guild translator read it for me for six crowns. You who are no longer what you were, come on down. The door at the bottom is kept for you. The road was cut by those who went first. The stair under the altar starts here. I have read it twice. It means exactly what it says.'" },
    { depth: "core", about: "truth:invitation", source: "person", bias: "true", reliable: "partial", cost: true, who: "a rim guard's report", text: "Report of a rim guard at {place}, night watch, {year}: 'At the second bell a hollowed one came over the rim. Furred, eyes as long as a hand. It wore the red token of {person}, lost on the fourth ledge eleven years ago. It sat by my brazier and drew in the dirt with one finger: a stair, a door, and many people with their arms open. Then it pointed at me, and down. {person}'s mother came at dawn. It did not know her.'" },
    { depth: "core", about: "truth:invitation", source: "temple", bias: "pious", reliable: "partial", points: "temple", who: "{believer}, Descender preacher", text: "Hymn of the Descenders, as taught by {believer} to pilgrims at the rim of {place} in {year}, and sung on the last 40 steps before the first ledge: 'Lose your face, lose your name, lose your way home; the bottom loves only what it has made its own.' {believer} tells pilgrims to leave their boots at the rim, since nobody who goes down properly needs them again. The temple at {lead} keeps the boots, 600 pairs so far." },
    { depth: "core", about: "truth:invitation", source: "archive", bias: "propaganda", reliable: false, who: "{official}, warden of descents", text: "Notice of the rim authority, posted at every basket station by order of {official}, warden of descents, {year}: 'There is no bottom to the throat and no voice within it. Delvers who claim to hear one, or who carry up writing from below, are to be held for examination for depth-madness at 2 crowns a day, at their own cost. Letters from below are guild property and must be handed in unopened.'" },
    { depth: "sub", about: "sub:rim_orphanage", source: "person", bias: "true", reliable: true, who: "an orphan of the rim house", text: "Letter from an orphan of the rim orphanage at {place} to an older sister in service, {year}: 'They gave me a pale token and a rope today. I am twelve, so I am a delver now. Matron cried. She never cries for the ones who graduate, only for the ones who come back early. There are 40 in my year. The board by the door says 31 went down last year. It has no number for how many came up.'" },
    { depth: "sub", about: "sub:relic_cartels", source: "archive", bias: "official", reliable: "partial", points: "sub:rim_orphanage", who: "a banking house ledger", text: "Ledger of a banking house of {place}, entry for {year}, in a clerk's hand: 'Expedition 31. Six delvers hired at 15 crowns a head. Four lost on the third ledge; wages unpaid by reason of death. One relic of the third tier recovered, a brass lamp that burns without oil, sold for 4,000 crowns. Return on capital: excellent. Recommend expedition 32 at once, crewed from the orphan house at {lead} at the lower rate.'" },
    { depth: "sub", about: "sub:rope_trade", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a rim-town innkeeper", text: "A rim-town innkeeper of {place}, telling travellers about the rope village in {year}: 'Every month a basket comes up from the third ledge. Fruit that glows, a knife that will not dull, once a fish that sang. And a list: salt, string, two lamps, and any newspaper. Any newspaper at all. Last time they wanted to know who was king. I sent down three years of papers, and they sent up a pearl the size of an egg.'" },
    { depth: "sub", about: "sub:immune_child", source: "oral", bias: "garbled", reliable: "partial", points: "sub:deep_camp", who: "tavern talk, noted by {investigator}", text: "Talk in the delvers' tavern at {place}, noted by {investigator} in {year}: 'The child who climbs, everyone calls her. Came up from the fourth ledge on a pale token without one drop of blood. When she walks the rim the throat hums, the way a dog whines at a door. The guild wants her trained. The deep camp has offered 300 crowns to borrow her for a season, and its agent lodges at {lead}.'" },
    { depth: "sub", about: "sub:rising_layer", source: "person", bias: "true", reliable: true, points: "site:wound_canyon", who: "a rim surveyor", text: "Rim surveyor's entry in the authority's depth book at {place}, {year}: 'Inverted trees of the second layer now visible at 120 fathoms with the glass. The entry 60 years before mine, in this same book, puts them at 300. That is a rise of three fathoms a year, faster since the cranes went to double shifts. I measured twice. The seep at {lead} has run heavier in the same years.'" },
    { depth: "sub", about: "sub:token_message", source: "person", bias: "true", reliable: "partial", points: "site:fourth_ledge", who: "a crane foreman's statement", text: "Statement of a crane foreman at {place} to the guild, {year}: 'Basket 1,117 came up with the usual relics and one black token. The stamp is {person}'s, who went down 30 years ago and is on the wall of the missing. Scratched on the back, in a careful hand: come down. Under that, a small drawing of a temple with its statues facing the dark. The older delvers say it is the temple at {lead}.'" },
    { depth: "site", about: "site:upside_city", source: "traveller", bias: "garbled", reliable: "partial", points: "library", who: "a pilgrim at the rim inn", text: "A pilgrim who went down to the hanging city with a guided party in {year}, telling it at the rim inn: 'I walked through its gate and my flask poured sideways. I was standing on a wall that was a floor, and up was the dark. The graves all face the middle of the shaft. Our guide charged 8 crowns extra for the painted archive, and said copies of the paintings hang in {lead}.'" },
    { depth: "site", about: "site:endless_ladder", source: "person", bias: "true", reliable: "partial", points: "cast:investigator", who: "{survivor}, black-token delver", text: "Letter of {survivor}, black-token delver, from below the deepest mapped ledge, {year}: 'Found the ladder the old letters talk about. It hangs from nothing I can see, and its fibre would not burn in my lamp. I climbed a mile up it with no blood from my nose. I climbed one yard beside it, on the rock, and lost two teeth. Someone built this to beat the grip. Send this to the physician at {lead}.'" },
    { depth: "site", about: "site:deep_relic_cache", source: "archive", bias: "official", reliable: "partial", who: "a cartel inventory", text: "Inventory of a warehouse at {place}, bought at a bankrupt's sale in {year} by a cartel factor: '212 relics, all dead. Each tagged with the ledge and depth where found. Paid 30 crowns for the lot.' Added a year later in {investigator}'s hand: 'Lowered nine to their tagged depths. All nine hummed and swung to point straight down, like compass needles. The other 203 are still in the warehouse. One is the cat's dish.'" },
  ],
};
