// The Drowned Crown: an endless, rising sea over the greatest kingdom that ever lived, and the reason it sank.
export default {
  id: "drowned_crown",
  name: "The Drowned Crown",
  kind: "shape",
  family: "world",
  pitch: "The sea has no far shore, and it is still rising. Under it lies the greatest kingdom that ever existed, and its records of why it drowned are still down there.",
  slots: ["world-shape", "history-secret"],
  tone: ["wonder", "melancholy"],
  era: ["bronze", "medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "shonen", "mythic", "flintlock"],
  w: 1,
  excludes: [],
  pairs: [{ id: "strewn_sky", w: 3 }, { id: "elder_lattice", w: 2 }, { id: "sleeper", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a ruin-reader who dives for pre-flood tablets and reads the old script in secret", home: "coast", stance: "Wants the erased century read aloud in every port; believes the past belongs to whoever can read it." },
    { role: "official", n: "an admiralty censor of the Wave-Throne, keeper of the charts and the burn lists", home: "capital", stance: "Wants one history and one chart; believes order is worth more than any tablet." },
    { role: "believer", n: "a Flood Church preacher of a bell town, who nails doors shut on storm nights", home: "coast", stance: "Believes the flood was just and that diving for the past is robbing the dead." },
    { role: "survivor", n: "a pearl-diver who went down the dry stair of a sea tower and came back three days later", home: "remote", stance: "Wants to go back down; will not say who sweeps the stairs." },
  ],

  truths: [
    { id: "divine_flood", n: "The gods sealed it under the sea", d: "The gods drowned the kingdom on purpose, to bury a thing its last king had made: a weapon, or perhaps a new god. The sea is the lock on it. Every relic lifted out weakens the seal and the sea rises to hold it down, so the harbour towns pay for each relic with their lowest street.", tags: ["truth:flood_seal"],
      known: [
        "The sea is rising a hand's breadth a decade, and harbours are rebuilt one tier higher. The admiralty calls it a natural tide of centuries. A whirlpool over the old capital has been widening on the charts.",
        "Harbour ledgers show the sea rising faster in the years after big relic hauls, and the admiralty has ordered the two kept in separate books. The Flood Church teaches that the old king made a thing the gods could not abide.",
        "A diving bell has found a dome under the whirl, carved with the seals of every god. Its inscription calls the waters a lock. The whirl turns one way and then the other on fixed days, like a key.",
        "Confirmed: the gods drowned the kingdom to bury what its last king made, and the sea is the lock. Every relic lifted out weakens the seal, and the sea rises to hold it. The harbour towns pay for each haul with their lowest streets.",
      ] },
    { id: "chose_to_sink", n: "The kingdom chose to sink", d: "The drowned kingdom went down willingly and lives on beneath the waves, changed into the gilled deep-folk. Its crown still claims every island under the old charter, and some of its heirs live on land among us. The people who walk into the sea when the bell rings are being called home; their families are not asked.", tags: ["truth:crown_beneath"],
      known: [
        "In storms a bell rings under the sea, and someone in the harbour town walks into the water. Pearl-divers report lit windows in a palace on the sea floor. The Flood Church says the deep-folk are seals and sea-cows.",
        "An admiralty patrol saw sixty lights below the surface moving in formation toward the old capital; the captain's remarks were cut from the report. An island off the coast moves two leagues a year in the same direction.",
        "Deep-folk envoys have come ashore under a white flag, speaking the old royal tongue and asking to read the empire's charter. {survivor} went down the dry stair of a sea tower and came back after three days.",
        "Confirmed: the drowned kingdom went down willingly and lives under the sea, changed. Its crown still claims every island. The bell-walkers are being called home, and the deep-folk say they go gladly. Their families on shore are never asked.",
      ] },
    { id: "erased_century", n: "The century was erased", d: "The maritime empire that rose after the flood burned every record of the century before it, because that century records what its founders did: seven admirals of the outer isles opened the old kingdom's sea-gates at midnight and drowned it to take its trade. The ruins still say so, and the admiralty still burns the islands of anyone who reads them.", tags: ["truth:erased_century"],
      known: [
        "The imperial library lists forty shelves of history for the century before the Wave-Throne as burned by order, reason left blank. The official history calls the old kingdom a poet's invention.",
        "Fishermen dredge up carved tablets in a dead script, and the admiralty buys and breaks every one it hears of. Ruin-readers who dive for them are hunted, and their islands burned with their students on them.",
        "{investigator} has matched 63 tablets into one chronicle. The last tablet names seven admirals who opened the sea-gates and the islands each was given. The same seven names head the empire's founding charter.",
        "Confirmed: the founders of the Wave-Throne opened the sea-gates and drowned the old kingdom to take its trade, then burned a century of records to hide it. Their descendants sit on the admiralty board and still burn the readers.",
      ] },
  ],

  tags: ["drowned_world"],

  subthemes: [
    { id: "rising_step", n: "The Rising Step", d: "The sea rose a hand's breadth this decade. Harbours are being rebuilt one tier higher, and the lowest island has become a reef.", w: 1.3, req: "coastal", truthLink: "divine_flood", tags: ["theme:rising_step"], mark: { kind: "zone", n: "The drowning shore", color: "#4a7a8a", size: [1, 3], where: "coast" } },
    { id: "ruin_readers", n: "The Ruin-Readers", d: "Scholars who dive for pre-flood tablets and decipher them in secret. The empire burns their islands when it finds them.", w: 1.2, req: { any: ["scholarly", "academies", "faith:philosophy"] }, truthLink: "erased_century", tags: ["theme:ruin_readers"] },
    { id: "lit_palace", n: "The Lit Palace", d: "Pearl-divers have found a palace on the sea floor with lights burning in its windows.", w: 0.8, req: "coastal", truthLink: "chose_to_sink", tags: ["theme:lit_palace"] },
    { id: "drowned_key", n: "The Drowned King's Key", d: "A key of sea-green metal turned up in a fish's belly at market. Every captain on the sea wants to know what it opens.", w: 1, req: { any: ["has:port", "mercantile"] }, tags: ["theme:drowned_key"] },
    { id: "calm_belt", n: "The Calm Belt", d: "A belt of dead-calm sea, full of monsters, divides the known waters. The only safe crossing is by oar, and the oarsmen are paid like princes.", w: 1.1, req: { any: ["seafaring", "navy", "has:port"] }, tags: ["theme:calm_belt"], mark: { kind: "zone", n: "The calm belt", color: "#2a5a6a", size: [2, 4], where: "coast" } },
    { id: "odd_climate", n: "The Island Out of Season", d: "An island where it is always winter, beside one where it always rains upward. Sailors swear the weather is a memory of what stood there before.", w: 0.9, req: "island", tags: ["theme:odd_climate"] },
    { id: "deep_embassy", n: "The Embassy of the Deep", d: "Sea-folk have come ashore under a white flag, speaking an old royal tongue, and asking to see the charter of the empire.", w: 0.7, req: { any: ["coastal", "has:port"] }, truthLink: "chose_to_sink", tags: ["theme:deep_embassy"] },
    { id: "final_island", n: "The Final Island", d: "Pirates hunt the last island at the end of the needle-stone chain, where the drowned king is said to have left his treasure.", w: 1.1, req: { any: ["seafaring", "mercenaries", "unstable"] }, tags: ["theme:final_island"] },
    { id: "storm_bell", n: "The Storm Bell", d: "In storms a great bell rings from under the sea. Every time it rings, someone in the harbour town walks into the water.", w: 0.8, req: "coastal", truthLink: "chose_to_sink", tags: ["theme:storm_bell"] },
    { id: "thalassocracy", n: "The Wave-Throne", d: "The great maritime empire owns the charts, the needle-stones and the history. Its admirals decide which islands may remember.", w: 1.3, req: { any: ["navy", "gov:empire", "autocracy"] }, truthLink: "erased_century", tags: ["theme:thalassocracy"] },
    { id: "flood_church", n: "The Flood Church", d: "A church teaching that the flood was just, and that to dive for the past is to dig up the dead.", w: 1, req: { any: ["pious", "organised", "faith:sea"] }, tags: ["theme:flood_church"] },
  ],

  sites: [
    { id: "sea_towers", n: "The Towers of $", kind: "ruin", where: "coast", d: "Stone towers standing out of the open sea, the tops of a drowned city.",
      layers: {
        surface: { n: "Gull towers", text: "Seven stone spires stand out of the open sea off {place}, crusted with gulls and weed. Fishermen tie up to them in calm weather and sell the eggs. The tallest has a window sixty feet up, still glazed." },
        study: { n: "Corners of one building", text: "{investigator} took bearings on all seven towers from a rowing boat. They are not separate towers. They line up as the corners and gateposts of a single building nearly a mile across, standing on the sea floor." },
        dig: { n: "The dry stair", text: "Inside the tallest tower a stair goes down. The first forty steps are dry, as if the sea were held back by a door that is not there. On the fortieth step stands a broom of new straw. {survivor}'s account of going lower is told in {lead}.", points: "cast:survivor" },
        revelation: { n: "Swept stairs", text: "Parts of the old city are still dry, and someone keeps them. Whoever lives below holds the sea back from these halls, sweeps the stairs and burns incense. The admiralty's first diving survey found the broom in {year} and logged the towers as empty rock. The broom is replaced every year." },
      } },
    { id: "whirl_capital", n: "The Whirl over $", kind: "anomaly", where: "remote", truthLink: "divine_flood", d: "A great whirlpool over the drowned capital that never stops turning.",
      layers: {
        surface: { n: "The red circle", text: "A whirlpool the width of a town turns over the drowned capital. Every chart since {year} marks a circle around it in red. Insurers will not cover a ship that crosses the line, and the line has been redrawn wider twice." },
        study: { n: "Like a lock", text: "{investigator} kept a log of the whirl for nine years. It turns one way for 182 days and the other way for 183, changing on the same morning each year, like a key worked back and forth in a lock." },
        dig: { n: "The dome of seals", text: "A weighted line dropped at the whirl's heart struck stone at 400 fathoms. A diving bell found a dome, carved with the seals of every god in the Flood Church calendar. A rubbing of the seals was sent to {lead}.", points: "temple" },
        revelation: { n: "The lock", text: "The gods drowned the kingdom to bury what its last king made, and laid the sea over the dome as a lock. Every relic the admiralty and the readers lift weakens it, and the sea rises to hold it down. Since the diving bells came, the whirl has widened by a quarter mile." },
      } },
    { id: "erased_tablets", n: "The Tablet Reef of $", kind: "dig", where: "coast", truthLink: "erased_century", d: "A reef of carved stone tablets from the erased century.",
      layers: {
        surface: { n: "Writing stones", text: "Fishermen of {place} snag carved stone tablets in their nets and sell them as writing stones for 2 coppers each. Most end up as doorsteps. The admiralty buys any it hears of at ten times the price, and breaks them." },
        study: { n: "One chronicle", text: "{investigator} matched 63 tablets by their broken edges. They are one chronicle, a year to a tablet, in the pre-flood script. The last forty are cut with deeper, faster strokes, as if the carver was running out of time." },
        dig: { n: "The last tablet", text: "Decoded, the last tablet names seven admirals of the outer isles who opened the sea-gates, and lists the island each received as a reward. The same seven names head the founding charter of the Wave-Throne, whose only copy is kept in {lead}.", points: "archive" },
        revelation: { n: "The founders' work", text: "Seven admirals opened the old kingdom's sea-gates at midnight and drowned it to take its trade. Then they founded the Wave-Throne and burned a century of records to hide it. Their great-grandchildren sit on the admiralty board today, and still buy up the doorsteps." },
      } },
    { id: "ship_bar", n: "The Ship Graveyard at $", kind: "ruin", where: "coast", d: "A sandbar where hundreds of wrecks lie piled, all of them facing the same way.",
      layers: {
        surface: { n: "Hulks on the bar", text: "Hundreds of wrecks lie heaped on a shifting sandbar off {place}, from reed boats to three-masted galleons. Every one lies bow to the west. Salvagers have stripped the newer ones, but none of them will sleep on the bar." },
        study: { n: "Thirty-seven charts", text: "{investigator} recovered 37 charts from the wrecks' chart-boxes. Each shows a route to a final island at the end of the needle-stone chain. No two routes agree, and every one of them ends at this bar." },
        dig: { n: "The royal letter", text: "In the oldest wreck, a cedar box held a royal seal and a letter of passage, signed by a king no history names and dated to the erased century. The pirates who hunt the final island trade copies of it in {lead}.", points: "sub:final_island" },
        revelation: { n: "The king's charts", text: "For four hundred years the drowned king has sent charts up from below and left them where captains will find them. Ships follow them here, some to bring tribute and most to steal it. The pirates still hunting the final island carry the newest chart, and pay well for it." },
      } },
    { id: "moving_island", n: "The Wandering Isle of $", kind: "wonder", where: "remote", truthLink: "chose_to_sink", d: "An island that moves, a little, every night.",
      layers: {
        surface: { n: "Never where charted", text: "An island off {place} is never quite where the charts put it. The admiralty corrects its position every year by notice. Fishermen who stake nets on its beach find them in the morning a hundred yards from the water." },
        study: { n: "Against the current", text: "{investigator} sank marker posts on its reef and timed them for a season. It is not drifting. It moves two leagues a year against the current, in a straight line toward the old capital under the whirl." },
        dig: { n: "The barnacled door", text: "Under the beach sand lies the back of a great shell, ridged like a turtle's. In its side is a door the height of two men, barnacled shut, with a royal crest on its knocker. A drawing of the crest went to {lead}.", points: "library" },
        revelation: { n: "The road home", text: "The drowned people are alive, and they travel under the sea on beasts like this one. The island is a carriage going home to the capital, slowly, with passengers, some of them bell-walkers. The admiralty has corrected the charts for 90 years and never once sent a boat to knock." },
      } },
  ],

  beings: [
    { id: "sea_king", n: "Sea-king", kind: "marine", d: "A colossal serpent-fish of the calm belts that can swallow a galley. The sea-folk are said to ride them.", danger: 3, biomes: ["open", "abyss"], look: { size: 120, group: [1, 1], move: "solo", speed: 12, col: "#2a4a5a", col2: "#c0a060", body: "serpent", active: "any", visible: true } },
    { id: "drowned_folk", n: "Deep-folk", kind: "marine", d: "Pale, gilled people in old court jewellery who watch ships from the swell. They speak, when they speak, a royal tongue.", danger: 1, biomes: ["shelf", "reef", "kelp", "abyss"], look: { size: 1.7, group: [2, 10], move: "pod", speed: 9, col: "#8ab0b0", col2: "#d0c080", body: "fish", active: "night", visible: false } },
    { id: "bell_crab", n: "Bell-crab", kind: "marine", d: "A crab the size of a cart that wears drowned church bells as shells. In storms you can hear them walk.", danger: 1, biomes: ["shelf", "reef", "estuary"], look: { size: 2, group: [1, 4], move: "solo", speed: 3, col: "#6a5a3a", col2: "#b08040", body: "crab", active: "night", visible: true } },
  ],

  techs: [
    { id: "dc_needle_stones", n: "Needle-stones", field: "navigation", level: 1, d: "Lodestones that lock onto the next island in the chain, the only way to cross the open sea." },
    { id: "dc_tier_harbours", n: "Tier harbours", field: "architecture", level: 2, d: "Harbours built in steps so that each generation can move up one as the sea rises." },
    { id: "dc_diving_bells", n: "Diving bells", field: "engineering", level: 3, d: "Bells of bronze and glass that carry readers down to the ruins and back." },
    { id: "dc_tablet_cipher", n: "The tablet cipher", field: "writing", level: 4, d: "The key to the pre-flood script. Every copy is burned on sight by the empire." },
    { id: "dc_sea_glass", n: "Sea-glass relics", field: "arcana", level: 4, d: "Glass from the drowned kingdom that calms the water around a ship, and draws the deep-folk." },
  ],

  units: [
    { id: "dc_wave_marines", n: "Wave-throne marines", role: "infantry", wpn: "sword", kit: "mail", ranks: 3, gap: 1.3, size: 100, w: 0.8, mods: [["theme:thalassocracy", 6], ["navy", 2]] },
  ],

  govs: [
    { id: "dc_thalassocracy", n: "Thalassocracy", d: "A sea-empire that owns the routes, the charts and the past; its admirals are its lords.", tags: ["gov:thalassocracy", "autocracy"], w: 0.4, req: "has:port", forms: ["Wave-Throne of $", "Sea-Empire of $", "Admiralty of $"], ruler: "Wave-Sovereign", mods: [["navy", 4], ["realm:large", 2], ["theme:thalassocracy", 5]] },
  ],

  faiths: [
    { id: "flood_church", n: "The Flood Church", d: "The flood was the gods' justice. The dead lie where they deserve, and must not be disturbed.", tags: ["faith:flood"], w: 0.6, names: ["The Church of the Flood", "The Just Waters", "The Tide-Law of $"], mods: [["seafaring", 2], ["theme:flood_church", 5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Sunken shelf", color: "#5a8aa0", size: [2, 5], count: [1, 3], where: "coast", d: "Shallows where the lost continent's coast shows through the water, and towers break the surface." },
  ],

  storylines: [
    { id: "dc_bell", n: "The Bell Beneath {place}", scale: "local", anchor: "coast", w: 1.3, req: "drowned_world",
      stages: {
        start: { h: "A bell rings under the sea off {place}", b: "In last night's storm a deep bell rang under the water off {place}. In the morning, {person} was gone from bed, and a line of footprints led into the sea.", wait: [1, 4], fx: { unrest: 8 }, next: [{ to: "more_walk", w: 1.5 }, { to: "bell_hunt", w: 1, mods: [["seafaring", 2]] }] },
        more_walk: { h: "More of {place} walk into the sea", b: "Every storm, the bell rings, and someone from {place} walks into the water smiling. The priests of the Flood Church are nailing doors shut.", wait: [3, 8], fx: { pop: 0.95, stability: -5 }, next: [{ to: "town_empties", w: 1 }, { to: "bell_hunt", w: 1 }] },
        bell_hunt: { h: "{person2} dives for the bell of {place}", b: "{person2}, the best diver on the coast, has gone down with a weighted line to find the bell before the next storm.", wait: [2, 6], next: [{ to: "bell_silenced", w: 1 }, { to: "met_drowned", w: 1 }] },
        town_empties: { h: "{place} is abandoned to the bell", b: "The last families have left {place} for the hills. On stormy nights travellers still hear the bell, and see lamps moving under the water.", fx: { abandon_town: true }, end: true },
        bell_silenced: { h: "The bell of {place} is cut loose", b: "{person2} found the bell in a drowned belfry and cut its rope. It fell into the deep, and the storms off {place} are only storms again.", fx: { stability: 5, prestige: 3 }, end: true },
        met_drowned: { h: "{person2} returns with a message from the deep", b: "{person2} came up three days later, alive, and said the walkers are well, and that the king below sends his greetings to {ruler}.", fx: { flag: "deep_contact", science: { navigation: 0.5 } }, end: true },
      } },
    { id: "dc_tablets", n: "The Tablets of the Lost Century", scale: "realm", anchor: "realm", w: 1.2, req: ["drowned_world", { any: ["learned", "scholarly", "academies", "coastal"] }],
      stages: {
        start: { h: "Ruin-readers of {realm} crack the tablet cipher", b: "{investigator}, a ruin-reader hiding in {realm}, has decoded the first full tablet of the erased century. Copies are already circulating.", wait: [3, 8], fx: { science: { writing: 0.8 } }, next: [{ to: "empire_demands", w: 1.5 }, { to: "published", w: 1, mods: [["tolerant", 2], ["isolation", 2]] }] },
        empire_demands: { h: "The Wave-Throne demands the ruin-readers", b: "Warships stand off {capital}. The admiralty demands {investigator} and every tablet, or it will burn the harbour.", wait: [1, 4], fx: { stability: -6 }, next: [{ to: "handed_over", w: 1, mods: [["small", 2], ["unstable", 1.5]] }, { to: "defiance", w: 1, mods: [["martial", 2], ["ruler:brave", 3]] }] },
        published: { h: "The lost century is printed in {realm}", b: "The decoded tablets have been printed in {capital}. They name the empire's founders as the ones who opened the sea-gates.", fx: { discovery: "writing", prestige: 10, unrest: 8 }, end: true },
        handed_over: { h: "{realm} hands over the ruin-readers", b: "{investigator} was taken aboard the flagship in irons. The tablets were sunk in the bay, and {realm} has been praised for its loyalty.", fx: { stability: 3, prestige: -8 }, end: true },
        defiance: { h: "{realm} defies the Wave-Throne", b: "{ruler} refused. The admiralty shelled the harbour, and the tablets' story is now told in every port that hates the empire.", fx: { stability: -8, unrest: 10, prestige: 8 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "{official}, admiralty censor", text: "Imperial history of the Wave-Throne, volume one, as revised in {year} under the seal of {official}, admiralty censor: 'Before the Wave-Throne there was only the sea and a few savage islands, with no writing and no law. The great kingdom of the old songs is a poet's invention. Any tablet claiming otherwise is a forgery, and is to be surrendered to the admiralty for a reward of 20 silver.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "a capstan shanty, noted by {investigator}", text: "Capstan shanty of the crews of {place}, written down by {investigator} in a harbour tavern in {year}: 'The king went down with his crown on his head, and the sea took his land for a bed; and when the tide is high and the moon is red, he sings to the ones he left.' The crews sing the last line twice. The bosun said a ship that sings it only once loses a man before port." },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:sea_towers", who: "{survivor}, pearl-diver", text: "Told by {survivor}, pearl-diver of {place}, to a crowd at the fish market in {year}: 'There are streets down there. Real streets, paved, with carts still in them and oxen bones in the traces. I swam 200 yards down one on a single breath. Then a door opened by itself, and there was lamplight inside.' Nobody believed a word. {survivor} went back down the next spring, by the dry stair at {lead}." },
    { depth: "core", about: "truth:divine_flood", source: "ruin", bias: "true", reliable: true, plain: true, who: "inscription on the dome under the whirl", text: "Inscription on the dome under the whirl, read by {investigator} by lamplight through the window of a diving bell at 400 fathoms, {year}: 'We, the gods of the shore and the sky, drowned this land to bury what its king made. What is here must not wake. The waters are the lock. Each thing you lift from here turns the key. Let no one lift them.' Around the words are carved seals, one for every god in the calendar." },
    { depth: "core", about: "truth:divine_flood", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, Flood Church preacher", text: "Flood Church catechism, as {believer} teaches it to the children of {place} every seventh day, {year}: 'Why did the waters come? Because the old king made a thing the gods could not abide. Where is it now? Under the waters, where it belongs. What must we do? Leave the dead and their goods alone.' The children answer together. {believer} gives a dried fig for each right answer, and none for questions." },
    { depth: "core", about: "truth:divine_flood", source: "heretic", bias: "heretic", reliable: "partial", who: "a ruin-reader's tide notebook", text: "Tide notebook of a ruin-reader, found in a burned house at {place} in {year}: 'Twelve years of marks on the harbour wall. In every year after a big haul of relics from the whirl, the sea rises a hair more than the year before. In the two years the admiralty stopped diving, it hardly rose at all. The sea is not rising. It is being raised, to hold something down.' The last page lists the relics the writer had sold." },
    { depth: "core", about: "truth:divine_flood", source: "person", bias: "true", reliable: "partial", cost: true, who: "a fisherman's petition", text: "Petition to the governor of {place} from {person}, fisherman of the lowest tier, {year}: 'My house, my net-shed and my mother's grave went under this spring. The whole third tier was lost in one season. That same season the admiralty lifted 300 relics from the whirl. I am told the two are not connected. I ask 40 silver for a new roof and a boat to move the grave.' Marked by the clerk: refused, no connection." },
    { depth: "core", about: "truth:divine_flood", source: "library", bias: "official", reliable: false, points: "archive", who: "{official}, admiralty censor", text: "Admiralty circular to all harbour masters, signed by {official}, {year}: 'The rising of the sea is a natural tide of centuries, about a hand's breadth a decade, and is unconnected with relics, gods or any so-called seal. Harbour masters will stop recording relic hauls and tide marks in the same ledger, as the practice has caused confusion. The old ledgers, all 31 volumes, are to be sent to {lead} for safekeeping.'" },
    { depth: "core", about: "truth:chose_to_sink", source: "person", bias: "true", reliable: true, plain: true, who: "minutes of a harbour council", text: "Minutes of the harbour council of {place}, {year}, recording a deep-folk envoy who came ashore under a white flag and spoke through an interpreter: 'We did not drown. We went home, all of us, on purpose, 400 years ago, and we changed so we could live there. The charter you sail under was written on our land, and the land is still ours. We have come to read it.' The envoy left a gold ring as a pledge and walked back into the sea." },
    { depth: "core", about: "truth:chose_to_sink", source: "oral", bias: "true", reliable: "partial", who: "bell-town grandmothers, heard by {investigator}", text: "The grandmothers of the bell town of {place}, as {investigator} heard them at a wake in {year} for a fisher who walked into the sea: 'The ones who walk out when the bell rings are not dead, only called. Don't set their place, don't sell the boat. On a calm day you can see them wave from under the water, off the second tower.' Three of them swore to it. The fisher's widow sold the boat anyway, for 60 silver." },
    { depth: "core", about: "truth:chose_to_sink", source: "temple", bias: "pious", reliable: "partial", cost: true, who: "{believer}, Flood Church preacher", text: "Parish register of {place}, kept by {believer}, Flood Church preacher, after the storm of {year}: 'The bell rang under the sea from midnight to the third hour. At dawn {person}, aged nine, was missing from bed. The footprints went straight down the beach and into the water, walking, not running. The child's mother has been given poppy to sleep. That makes fourteen from this parish since the bell began. I have nailed the doors of the lower street shut.'" },
    { depth: "core", about: "truth:chose_to_sink", source: "archive", bias: "redacted", reliable: "partial", points: "site:moving_island", who: "an admiralty patrol report", text: "Report to the admiralty from the captain of the patrol galley at {place}, night of {year}: 'At the second watch, lights observed twenty fathoms below the surface, about sixty in number, in formation, moving east toward the old capital at a walking pace. They passed under the isle at {lead} and did not come out the other side. Crew sworn to silence and paid a double ration.' The captain's remarks have been cut from the page." },
    { depth: "core", about: "truth:chose_to_sink", source: "temple", bias: "official", reliable: false, who: "the Flood Church synod", text: "Ruling of the Flood Church synod at {place}, {year}, read from every pulpit: 'The drowned kingdom perished to the last soul, as the gods intended. The so-called deep-folk are seals and sea-cows, seen by drunk sailors in bad light. Anyone who goes to the water when the storm bell rings does so of their own free will, and shall be buried without rites. No net is to be set within 300 yards of the towers.'" },
    { depth: "core", about: "truth:erased_century", source: "ruin", bias: "true", reliable: true, plain: true, points: "archive", who: "the last tablet, decoded by {investigator}", text: "The last tablet of the reef chronicle, decoded by {investigator} in {year} after nine years' work: 'In this year the seven admirals of the outer isles opened the sea-gates of the kingdom at midnight, for a promise of its trade. By morning they were the only kingdom left. We who carve this stand on the last high ground. We write so the lie they will tell has a witness.' Below are the seven names. They also head the founding charter in {lead}." },
    { depth: "core", about: "truth:erased_century", source: "archive", bias: "redacted", reliable: "partial", points: "library", who: "an imperial library catalogue", text: "Shelf catalogue of the imperial library at {place}, page 112, copied by a junior clerk in {year}: 'Shelves 1 to 40: the century before the founding. Status: burned, by order. Reason: [blank]. Authority: [blank].' In the margin, in pencil, the clerk has written: 'Shelf 41 survived. It was misfiled with the tide tables.' The tide tables for that year are kept in {lead}." },
    { depth: "core", about: "truth:erased_century", source: "heretic", bias: "exaggerated", reliable: "partial", cost: true, who: "a tavern wall and an admiralty notice", text: "Painted on the wall of a harbour tavern at {place} in red lead, {year}: THE WAVE-THRONE IS BUILT ON A DROWNED MAN'S FACE. Pasted beneath it, the admiralty's notice: 'The painter, {person}, has been taken. Seven tablets were found in the painter's cellar. The cellar has been filled with sand and the tavern's licence revoked. Anyone who repaints these words will join the painter.' The words were repainted the following week." },
    { depth: "core", about: "truth:erased_century", source: "library", bias: "propaganda", reliable: false, who: "a Wave-Throne school primer", text: "School primer of the Wave-Throne, lesson three, printed by the admiralty press in {year}: 'The seven founders of the Wave-Throne gathered the scattered survivors of a natural calamity and gave them order, law and charts. Each founder was given an island in thanks, by vote of a grateful people. A child must name all seven founders before going to sea.' In one copy, a reader has pencilled beside the names: same as the tablet." },
    { depth: "sub", about: "sub:ruin_readers", source: "person", bias: "true", reliable: true, points: "site:erased_tablets", who: "a ruin-reader's last letter", text: "Last letter of {investigator}'s teacher, a ruin-reader, smuggled out in a fish barrel in {year}: 'They burned the island, and my nine students with it. I have the cipher in my head and nowhere else, and the admiralty knows whose head. My notes are wrapped in oilcloth under the reef at {lead}. Read them aloud to as many people as you can. That is the only safe copy.'" },
    { depth: "sub", about: "sub:calm_belt", source: "traveller", bias: "exaggerated", reliable: "partial", who: "an oarsman of the calm belt", text: "Told by an oarsman of the calm belt at the hiring hall of {place}, {year}: 'Forty days rowing the calm with no wind and the sea-kings circling. On the thirtieth day one came up beside us, an eye as big as the hatch, and looked in at the oarsmen like a cook looking at hens. It took the cook. We were paid 90 silver each at the far side, and the cook's share was split eleven ways.'" },
    { depth: "sub", about: "sub:drowned_key", source: "oral", bias: "garbled", reliable: "partial", points: "sub:final_island", who: "a customs clerk", text: "Market gossip at {place}, written down by a customs clerk in {year}: 'The fishwife who found the green key in a cod has been offered 300 silver by one captain, 500 by another, and a knife by a third. One swears it opens the drowned king's treasury, one his tomb, and the third, after a drink, the sea itself. The third captain sails out of {lead}. The fishwife has hidden the key and doubled the price of cod.'" },
    { depth: "sub", about: "sub:rising_step", source: "person", bias: "true", reliable: true, points: "site:whirl_capital", who: "the harbour engineer", text: "Report of the harbour engineer of {place} to the town council, {year}: 'The third tier was built 60 years ago by my master's master. I am building the fifth, for 1,200 silver, a man's height above the fourth. My apprentice will build the sixth, if there is a sixth. The council asks why the sea rises faster in the years the admiralty dives at the whirl. I am an engineer. Ask the divers at {lead}.'" },
    { depth: "sub", about: "sub:odd_climate", source: "traveller", bias: "garbled", reliable: "partial", who: "a ship's cook", text: "Diary of a ship's cook, putting in at the winter island near {place} in {year}: 'Snow in midsummer, as promised. In the square there is a frozen fountain carved with sea-horses, and children skate round it. Nobody here built the square or knows who did. Forty yards off, on the next island, the rain falls upward. The captain bought three barrels of snow to chill the officers' wine.'" },
    { depth: "site", about: "site:sea_towers", source: "person", bias: "true", reliable: "partial", who: "{survivor}, pearl-diver", text: "Statement of {survivor}, pearl-diver, to the harbour master of {place}, {year}, after three days missing: 'Forty steps down inside the tallest tower, and still dry. On the forty-first the air smelled of incense, and somebody had swept. There was a broom against the wall, new straw. I sat on the step for what I thought was an hour. When I came up, my family had already paid for the funeral.'" },
    { depth: "site", about: "site:moving_island", source: "archive", bias: "official", reliable: "partial", points: "archive", who: "{official}, admiralty censor", text: "Chart correction notice of the admiralty, number 214, signed by {official}, {year}: 'The isle of {place} is to be marked two leagues further east. Previous correction, last year: two leagues east. The year before: two leagues east. Captains are reminded that the charts are correct and the island is at fault. Earlier notices on this isle are filed in {lead}.'" },
    { depth: "site", about: "site:ship_bar", source: "person", bias: "true", reliable: "partial", who: "a salvager's log", text: "Salvage log of a crew working the wreck bar off {place}, {year}: 'Day 12. Stripped the galleon at the east end: four cannon, a bell, 31 silver. In its chart-box, a chart to the final island, drawn in a hand I have seen before. It is the same hand as the chart in the reed boat at the west end, which is three hundred years older. Every wreck here points west. I have told the crew to stop reading the charts.'" },
  ],
};
