// The Elder Lattice: a vanished people once ruled the world through a network of gates; the gates are sealed, and the reason waits.
export default {
  id: "elder_lattice",
  name: "The Elder Lattice",
  kind: "history",
  family: "world",
  pitch: "A vanished people once ruled the whole world through a network of gates. Their roads and stone rings are everywhere. Every gate is sealed, and nobody knows what is on the other side.",
  slots: ["history-secret"],
  tone: ["wonder", "melancholy"],
  era: ["bronze", "medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "mythic", "flintlock", "grimdark"],
  w: 1.1,
  excludes: [],
  pairs: [{ id: "balanced_circle", w: 2.5 }, { id: "nursery_sea", w: 2.5 }, { id: "downward_throat", w: 2 }, { id: "strewn_sky", w: 1.5 }, { id: "drowned_crown", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a glyph-reader of the Lattice Collegium who maps the precursor nodes", home: "mountain", stance: "Wants the ring-word read correctly before anyone opens anything; believes the Elder builders were people, not gods." },
    { role: "official", n: "the crown's keeper of the relic lamp, who answers for the realm's ruins", home: "capital", stance: "Wants the lamp lit and the rings quiet; will say whatever keeps the dynasty's claim intact." },
    { role: "believer", n: "a gate-cult prophet who leads the faithful up the rings at night", home: "border", stance: "Believes the rings are the doors of the gods, and that they open for the worthy." },
    { role: "survivor", n: "a hill shepherd who lost a flock and two fingers to the grey at a warm ring", home: "remote", stance: "Wants the rings buried and the cultists off the hill; trusts nobody who wants a door opened." },
  ],

  truths: [
    { id: "sealed_enemy", n: "The gates hold something out", d: "The precursors sealed their gates to lock out a devouring force: a grey swarm that unmakes anything it touches and learns from what it eats. They died at the rings holding them shut, and the seals answer only to the blood of their last keepers. Every gate reopened by a cult, a crown or a curious scholar can let the swarm back in.", tags: ["truth:gate_enemy"],
      known: [
        "Gate-rings across the world are sealed, and their stone is warmer on the inside face. The crown says black stone holds the sun's heat. A shepherd found a sheep by one with half its face smoothly gone.",
        "{investigator} has read the glyphs on a sealed ring: a warning, repeated forty times, that what lies beyond eats what it touches and learns what it eats. The Sealers' oath says blood on the stone keeps the grey away.",
        "Behind one ring lie rows of precursor bodies, each with a hand pressed toward the gate. Another ring opened for an hour and showed a dead grey world with a dark shape moving. The Sealers are down to one old woman.",
        "Confirmed: the precursors sealed the gates against a grey swarm that unmakes what it touches, and died holding them shut. The seals answer only to the last keepers' blood. Every ring the cults or crowns open can let the swarm back in.",
      ] },
    { id: "departure", n: "The precursors left", d: "The precursors were not destroyed. They left through the gates for somewhere better and sealed the way behind them, meaning to come back for what they left in 'the cradle', their word for this world. Some of them would like their world back, and the black glass keys the courts are fighting over will open the door for them.", tags: ["truth:gate_departure"],
      known: [
        "The Collegium holds that the Elder people died in one catastrophe. An expelled reader points out that no precursor bodies have been found anywhere but at the rings. Gate-cults say the door was closed from the other side.",
        "The glass library's last plates are farewells, each ending with a phrase the Collegium reads as 'we will come back for it'. One plate listed what was left behind. It was sold to a court agent before anyone read it.",
        "Black glass keys have turned up in three realms, and each court is buying or stealing the others'. The plates call this world the cradle, and say the way was sealed for safety, not for ever.",
        "Confirmed: the precursors left through the gates and sealed them behind them. They are still out there, and some want their world back. The keys the courts are collecting are theirs, and will open the door from this side.",
      ] },
    { id: "we_are_them", n: "We are their caretakers", d: "The present peoples are the bred descendants of the precursors' servants, made to tend the world while the masters slept in glass. The gates are not doors but alarms: opening one wakes the masters. The relic crowns that rule in their name are stewards who forgot they were stewards, and the sleepers are due to wake.", tags: ["truth:caretakers"],
      known: [
        "A metal construct has walked out of a ruin, asking every village for its household. A ruin-tribe's story says the tall ones made people to sweep their floors. The crown says we owe nothing to any vanished race.",
        "A landslide opened a hall of 140 tall sleepers in glass, breathing once a day. The construct called {investigator} by a word the glass plates use for a tool, then asked where the master was.",
        "Murals in the sleepers' hall show the sleepers giving orders to smaller people with brooms and hoes, who have our faces. The caption says the keepers were made from the servants' line, and that the masters wake when a door opens.",
        "Confirmed: today's peoples are the bred descendants of the precursors' servants, left to keep the world while the masters slept. The gates are alarms. The relic crowns are stewards who forgot it, and one sleeper has already opened its eyes.",
      ] },
  ],

  tags: ["precursors"],

  subthemes: [
    { id: "gate_flickers", n: "The Waking Gate", d: "A gate-ring on a mountaintop has begun to glow at night. Shepherds report a hum, and their sheep will not graze near it.", w: 1.2, req: { any: ["mountain", "near:ruins", "near:ley"] }, tags: ["theme:gate_flickers"], mark: { kind: "zone", n: "The lit ring", color: "#6ab0c0", size: [1, 1], where: "mountain" } },
    { id: "collegium", n: "The Lattice Collegium", d: "Scholars mapping the precursor nodes and decoding their script. They have one word right so far, and they are fighting over what it means.", w: 1.3, req: { any: ["scholarly", "academies", "learned", "near:ruins"] }, tags: ["theme:collegium"] },
    { id: "relic_crown", n: "The Relic Crown", d: "The realm's power rests on a single working precursor relic: a lamp, a well, a throne that heals. It has begun to flicker.", w: 1.2, req: { any: ["monarchy", "autocracy", "origin:ruin_heirs"] }, tags: ["theme:relic_crown"] },
    { id: "construct_wakes", n: "The Wandering Construct", d: "A metal servant has walked out of a ruin and is searching the land for its masters. It is polite, tireless and growing impatient.", w: 0.9, req: { any: ["near:ruins", "origin:ruin_heirs"] }, truthLink: "we_are_them", tags: ["theme:construct_wakes"] },
    { id: "ruin_tribe", n: "The Ruin-Dwellers", d: "A tribe lives inside a precursor structure, drinking from its fountains and sleeping in its warm halls. They kill outsiders who touch the walls.", w: 1, req: { any: ["tribal", "insular", "near:ruins"] }, tags: ["theme:ruin_tribe"] },
    { id: "ley_shift", n: "The Shifting Lines", d: "The straight lines that join the ruins have moved. The weather along them has gone mad: snow in summer, warm rain in winter.", w: 0.9, req: { any: ["near:ley", "magic:high", "arcane"] }, truthLink: "sealed_enemy", tags: ["theme:ley_shift"] },
    { id: "dead_world_gate", n: "The Gate onto Ash", d: "A gate opened for an hour and showed a grey world with nothing alive in it, and a dark shape moving in the distance. Then it shut. The stone is still warm.", w: 0.7, truthLink: "sealed_enemy", tags: ["theme:dead_world_gate"] },
    { id: "last_sealer", n: "The Last Sealer", d: "The hereditary order that keeps the seals has dwindled to one old woman. She has no heir, and the seals answer only to her blood.", w: 0.9, req: { any: ["pious", "ancestor_bound", "faith:ancestors"] }, truthLink: "sealed_enemy", tags: ["theme:last_sealer"] },
    { id: "key_race", n: "The Race for the Keys", d: "Precursor keys, rods of black glass, have turned up in three realms. Each realm wants all of them, and nobody knows what they open.", w: 1.1, mods: [["has:rival", 2], ["autocracy", 1.5], ["spy_network", 2]], truthLink: "departure", tags: ["theme:key_race"] },
    { id: "sleeper_vault", n: "The Sleepers' Vault", d: "Diggers found a vault of people asleep in glass, tall and fine-boned, breathing once a day. One has opened its eyes.", w: 0.7, req: { any: ["near:ruins", "scholarly"] }, truthLink: "we_are_them", tags: ["theme:sleeper_vault"] },
    { id: "gate_cult", n: "The Gate-Cults", d: "Worshippers who believe the gates are the doors of the gods and pray for them to open. They leave offerings in the rings and climb them at night.", w: 1, req: { any: ["pious", "mystic", "zealous", "faith:ley"] }, truthLink: "departure", tags: ["theme:gate_cult"] },
  ],

  sites: [
    { id: "node_city", n: "The Node City of $", kind: "ruin", where: "remote", d: "The vast precursor city at the centre of the lattice, off-limits by every law.",
      layers: {
        surface: { n: "Towers no road reaches", text: "White towers stand on the horizon beyond {place}, and no road leads to them. Every realm forbids its people to go near, on pain of fifty lashes. Shepherds graze right up to the border stones and no further." },
        study: { n: "Where the roads point", text: "{investigator} plotted 118 precursor roads on one sheet. Every straight road in the world, followed far enough, points at the white towers. The Collegium called it a coincidence of surveying and declined to print the sheet." },
        dig: { n: "The chamber of rings", text: "At the city's heart is a round chamber holding 64 sealed gate-rings, and a floor map of the world with every gate marked by a glass bead. All the beads are cold but one. It marks the ring near {lead}.", points: "sub:gate_flickers" },
        revelation: { n: "One machine", text: "All the gates are parts of one machine, and this chamber works it. The Elder builders closed every ring from here at once. The crowns have forbidden the city for 400 years, not from fear, but so that no rival court could reach the controls first." },
      } },
    { id: "crystal_library", n: "The Glass Library of $", kind: "dig", where: "mountain", truthLink: "departure", d: "A precursor library of crystal plates that sing when touched.",
      layers: {
        surface: { n: "Glass shelves", text: "A cave in the mountains near {place} is lined with glassy shelves. Centuries of treasure hunters have broken most of the plates for jewellers, who pay 4 silver a pound for the shards and ask no questions." },
        study: { n: "Plates that speak", text: "Each surviving plate holds a voice that speaks when warmed in the hand. {investigator} has catalogued 311 of them: store lists, work rotas, a child's spelling lesson, and one plate that only laughs." },
        dig: { n: "The farewells", text: "The last forty plates are farewells: a name, then one phrase over and over, which the Collegium reads as 'we will come back for it'. One plate lists what was left behind. It was sold to a court agent at {lead} before anyone read it.", points: "sub:key_race" },
        revelation: { n: "Coming back", text: "The precursors left on purpose, through the gates, and sealed them for safety. They mean to return for what they left in the cradle, their word for this world. The keys the courts are buying are theirs, and every court collecting them is building the precursors a door." },
      } },
    { id: "sealed_ring", n: "The Sealed Ring of $", kind: "anomaly", where: "any", truthLink: "sealed_enemy", d: "A gate-ring of black stone, sealed with glyphs, warm to the touch.",
      layers: {
        surface: { n: "Offerings on the hill", text: "A ring of black stone stands on a bare hill near {place}, with offerings heaped beneath it: bread, ribbons, a child's shoe. Gate-cultists climb it at night. {survivor} lost thirty sheep beside it in one evening." },
        study: { n: "Warm on the inside", text: "The glyphs on the seal repeat one warning forty times around the rim. {investigator} measured the stone with a thermometer: the inside face is warmer than the outside by the heat of a hand, even in snow." },
        dig: { n: "The grave behind the ring", text: "Behind the ring lies a grave of precursor bodies, laid in rows of twelve, each with one hand pressed flat toward the gate. The Sealers' order kept a register of such graves; it is now held in {lead}.", points: "temple" },
        revelation: { n: "Holding the door", text: "The precursors died holding the gates shut against a grey swarm that eats whatever it touches. The seals still answer to the blood of their last keepers, and the Sealers' order is down to one old woman. The crown cut the order's funding in {year}. The gate-cults pray nightly for the door to open." },
      } },
    { id: "sea_causeway", n: "The Drowned Road of $", kind: "wonder", where: "coast", d: "A precursor causeway that runs straight into the sea.",
      layers: {
        surface: { n: "A road into the surf", text: "A perfect stone road runs from the hills above {place} into the surf and out of sight. Carters use the dry end, and it has never needed mending. Fishermen have worked the water over it for 200 years without snagging a net." },
        study: { n: "Toward an offshore node", text: "At the lowest tide of the year, {investigator} followed the road on foot for six miles, dead straight, toward a node far offshore, until the water reached the chest. The stones were clean of weed the whole way." },
        dig: { n: "The badge on the waystones", text: "The waystones along the road bear a badge: a ring inside an open hand. It is the same badge carved over the door of the hall of glass sleepers at {lead}.", points: "site:sleeper_hall" },
        revelation: { n: "More than any map shows", text: "The lattice runs under the sea as well. The roads, rings and halls on land are perhaps a third of it. The undersea stones are clean of weed, so somebody still keeps that road. The Collegium maps, sold to every crown for 300 silver, show only the dry part." },
      } },
    { id: "sleeper_hall", n: "The Hall of Glass Sleepers at $", kind: "dig", where: "inner", truthLink: "we_are_them", d: "A vault of tall people asleep in glass.",
      layers: {
        surface: { n: "A door in the hillside", text: "A landslide above {place} in {year} opened a sealed door in the hillside. The village sent two children in with a lamp. They came out an hour later and said the people inside were breathing." },
        study: { n: "One breath a day", text: "Inside are 140 glass coffins in rows, each holding a tall, fine-boned sleeper. {investigator} sat by one for a full day and counted a single breath, at noon. Their fingernails have grown since the door was opened." },
        dig: { n: "The murals", text: "The wall murals show the sleepers giving orders to smaller people with brooms and hoes, who look exactly like us. The last panel shows a ring lighting and the sleepers rising from the glass. A full copy was carried to {lead}.", points: "library" },
        revelation: { n: "The stewards", text: "Our ancestors were bred to keep the world while these people slept, and the gates are alarms: opening one wakes them. The relic crowns are stewards who forgot they were stewards. The gate-cults are trying to open a ring, and one sleeper has already opened its eyes." },
      } },
  ],

  beings: [
    { id: "lattice_construct", n: "Lattice construct", kind: "beast", d: "A tall metal servant of the precursors, still keeping its ancient rounds. Most ignore people; some do not.", danger: 2, biomes: ["badlands", "desert", "alpine", "grass", "tempforest"], look: { size: 3, group: [1, 3], move: "solo", speed: 5, col: "#a0a8b0", col2: "#40c0d0", body: "biped", active: "any", visible: true } },
    { id: "grey_mite", n: "Grey mite", kind: "insect", d: "Tiny grey specks that leak from warm gate-rings and eat stone, wood and flesh alike. A handful is a curiosity; a cloud is a catastrophe.", danger: 3, biomes: ["badlands", "alpine", "grass", "colddesert"], look: { size: 0.01, group: [500, 5000], move: "swarm", speed: 2, col: "#8a8a8a", col2: "#4a4a4a", body: "insect", active: "any", visible: false } },
    { id: "gate_hound", n: "Gate-hound", kind: "predator", d: "Sleek glass-eyed hounds bred by the precursors to guard the rings. Their bloodlines run wild in the ruins.", danger: 2, biomes: ["grass", "tempforest", "badlands", "dryforest"], look: { size: 1.3, group: [2, 6], move: "pack", speed: 16, col: "#2a3a4a", col2: "#80d0e0", body: "quad", active: "night", visible: true } },
  ],

  techs: [
    { id: "el_ruin_mapping", n: "Line-mapping", field: "astronomy", level: 1, d: "Surveyors learn that the ruins lie on straight lines, and use the lines as roads and landmarks." },
    { id: "el_glyph_reading", n: "Glyph-reading", field: "writing", level: 2, d: "A partial grammar of the precursor script: enough to read warnings, not enough to heed them." },
    { id: "el_relic_repair", n: "Relic repair", field: "engineering", level: 3, d: "Reviving dead precursor lamps, wells and pumps with salvaged parts and a great deal of luck." },
    { id: "el_construct_command", n: "Construct commands", field: "arcana", level: 4, d: "The words that make a precursor construct obey, or at least pause." },
    { id: "el_gate_keys", n: "Gate keys", field: "arcana", level: 5, d: "The use of the black glass rods that open the gates. Nobody has yet learned to close one." },
  ],

  units: [
    { id: "el_constructs", n: "Bound constructs", role: "beast", wpn: "axe", kit: "plate", ranks: 2, gap: 3, size: 12, w: 0.3, mods: [["theme:construct_wakes", 8], ["theme:relic_crown", 4]] },
    { id: "el_sealers", n: "Sealer guard", role: "magic", wpn: "staff", kit: "robe", ranks: 2, gap: 3, size: 20, w: 0.4, mods: [["theme:last_sealer", 8], ["theme:gate_flickers", 3]] },
  ],

  govs: [
    { id: "el_relic_crown", n: "Relic crown", d: "Whoever holds the precursor relic holds the throne; the court is its priesthood and its guard.", tags: ["gov:relic_crown", "monarchy", "autocracy"], w: 0.5, forms: ["Relic-Throne of $", "Lamp-Kingdom of $", "Heirs of $"], ruler: "Lamp-Bearer", mods: [["theme:relic_crown", 6], ["origin:ruin_heirs", 3]] },
  ],

  faiths: [
    { id: "gate_cult", n: "Gate worship", d: "The gates are the doors of the gods; the faithful pray for the day they open.", tags: ["faith:gates"], w: 0.6, names: ["The Open Door", "The Ring-Faith of $", "Children of the Gate"], mods: [["theme:gate_cult", 6], ["near:ruins", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Precursor ruins", color: "#7aa0b0", size: [1, 3], count: [2, 4], where: "any", d: "White ruins of the vanished people, laid out on dead-straight lines across the land." },
    { kind: "zone", n: "Gate country", color: "#304a5a", size: [1, 2], count: [1, 2], where: "remote", d: "The land around a sealed gate-ring, where the weather is wrong and nothing grazes." },
  ],

  storylines: [
    { id: "el_gate_wakes", n: "The Gate of {place}", scale: "realm", anchor: "realm", w: 1.5, req: "precursors",
      stages: {
        start: { h: "A gate-ring wakes near {place}", b: "The black ring on the hill above {place} glows at night, and the air around it hums. {investigator}, a Collegium glyph-reader, has ridden out with notebooks.", wait: [2, 6], next: [{ to: "studied", w: 1.5 }, { to: "cult_gathers", w: 1, mods: [["theme:gate_cult", 3], ["pious", 1.5]] }] },
        studied: { h: "{investigator} reads the glyphs of the {place} gate", b: "The glyphs on the ring are a warning, {investigator} reports, and also a set of instructions. The court of {realm} wants to know which to follow.", wait: [3, 8], fx: { science: { writing: 0.6 } }, next: [{ to: "opened", w: 1, mods: [["ruler:ambitious", 2.5], ["ruler:greedy", 2]] }, { to: "resealed", w: 1.5 }] },
        cult_gathers: { h: "Gate-cultists gather at {place}", b: "Hundreds of the faithful are camped around the ring, singing to it. Their prophet, {believer}, says the door will open at midsummer.", wait: [2, 6], fx: { unrest: 8 }, next: [{ to: "opened", w: 1 }, { to: "dispersed", w: 1, mods: [["harsh_law", 2], ["martial", 1.5]] }] },
        opened: { h: "The gate of {place} opens", b: "The ring split with a sound like a bell and showed a grey world beyond. Then the grey began to come through.", wait: [1, 3], fx: { unrest: 15, stability: -8 }, next: [{ to: "swarm", w: 1.5 }, { to: "visitors", w: 1 }] },
        resealed: { h: "The gate of {place} is sealed again", b: "Following the glyphs, {investigator} sang the ring closed. It cooled by morning. {investigator} has not spoken since.", fx: { stability: 4, discovery: "arcana" }, end: true },
        dispersed: { h: "Soldiers scatter the gate-cult at {place}", b: "The soldiers of {realm} broke up the camp and pulled down the offerings. The ring went dark a week later.", fx: { stability: 2, unrest: 5 }, end: true },
        swarm: { h: "Grey swarm spreads from {place}", b: "A grey cloud poured out of the ring and ate {place}: houses, fields and people, down to bare rock. It stopped at the river, for now.", fx: { abandon_town: true, pop: 0.85, plague: true }, end: true },
        visitors: { h: "Tall strangers walk out of the gate", b: "Three tall, fine-boned strangers walked out of the ring and looked about them with pity. They have asked to see whoever is 'minding the house'.", fx: { flag: "precursors_return", prestige: 5, unrest: 10 }, end: true },
      } },
    { id: "el_relic_fails", n: "The Dimming of the {realm} Lamp", scale: "realm", anchor: "realm", w: 1, req: ["precursors", { any: ["monarchy", "autocracy", "theme:relic_crown"] }],
      stages: {
        start: { h: "The relic of {realm} begins to fail", b: "The precursor relic that has blessed the rulers of {realm} for centuries is dimming. The court is keeping it secret, badly.", wait: [3, 8], fx: { stability: -5 }, next: [{ to: "repair_quest", w: 1.5 }, { to: "rival_hears", w: 1, mods: [["has:rival", 2], ["spy_network", 1.5]] }] },
        repair_quest: { h: "{ruler} sends seekers for precursor parts", b: "{person} and a band of relic-hunters have been sent to strip the old ruins for anything that might mend the relic.", wait: [4, 12], fx: { treasury: -40 }, next: [{ to: "mended", w: 1 }, { to: "dies", w: 1 }] },
        rival_hears: { h: "Rumours of {realm}'s failing relic spread abroad", b: "Spies have carried the news across every border. Envoys arrive in {capital} with polite questions and armies at their backs.", wait: [2, 6], fx: { prestige: -6 }, next: [{ to: "dies", w: 1 }, { to: "repair_quest", w: 1 }] },
        mended: { h: "The relic of {realm} burns bright again", b: "With a part torn from a ruin far beyond the border, {person} mended the relic. It burns brighter than ever, and a construct has followed {person} home asking for its part back.", fx: { prestige: 10, flag: "construct_follows", science: { engineering: 0.8 } }, end: true },
        dies: { h: "The relic of {realm} goes dark", b: "The relic is dead. Without it, the claim of {ruler} is only a claim, and the great houses of {realm} are already counting swords.", fx: { stability: -20, revolt: true }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: false, who: "{believer}, gate-cult prophet", text: "Sermon of {believer}, gate-cult prophet, preached under the ring at {place} on midsummer eve, {year}: 'The white ruins are the houses of the gods, who lived among us in the first age, and the rings are their doors. When we are worthy, they will open. Bring bread and a ribbon. Bring your children, for the gods love children. Last year we were 200 on this hill. This year be 1,000, and the door cannot refuse us.'" },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "Lattice Collegium primer", text: "Lattice Collegium primer for first-year students, chapter one, {year}: 'The Elder builders were mortal, not divine; their works are machines, not miracles. The lattice is the network of those works: straight roads joining nodes, and every node holding a ring, a gate of black stone some 20 feet across. Every ring found so far is sealed. Students will not touch a ring, climb a ring or leave food in one, whatever the local priest says.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:sealed_ring", who: "a relic-hunter in a tavern", text: "A relic-hunter's boast in a tavern at {place}, {year}, taken down by a Collegium student for the price of a round: 'I walked a white road for 40 days and never once climbed a hill. It went straight through them, in tunnels lit by lamps nobody fills. At the end was the black ring at {lead}, with a heap of bones in front of it, all facing the stone. I took the rings off their fingers and sold them.'" },
    { depth: "core", about: "truth:sealed_enemy", source: "ruin", bias: "true", reliable: true, plain: true, who: "glyphs on a sealed ring, read by {investigator}", text: "Glyphs on the seal of the black ring at {place}, decoded by {investigator} in {year} and read in full for the first time: 'Beyond this door is the grey. It eats what it touches. It learns what it eats. It has eaten our other world. We have closed the doors and we stay at them to hold them. Do not open them. We are sorry.' The warning is repeated forty times around the rim, word for word." },
    { depth: "core", about: "truth:sealed_enemy", source: "oral", bias: "true", reliable: "partial", points: "temple", who: "the last sealer, to {investigator}", text: "The Sealers' oath, sung by the last sealer of the order for {investigator} at {place} in {year}, with a knife in one hand and a bowl in the other: 'Hand on the stone, and the grey stays gone; blood on the stone, and the stone holds on.' The sealer cut a thumb and pressed it to the ring, and the stone was cool by morning. 'Forty rings,' the sealer said. 'One of me. Do the sums.' The order's register is kept at {lead}." },
    { depth: "core", about: "truth:sealed_enemy", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, shepherd", text: "Statement of {survivor}, shepherd, to the reeve of {place}, {year}: 'Found a ewe by the warm ring with half its face gone. Not bitten. Gone, smooth, like a slate rubbed clean. The next evening there was a grey haze by the stone, like dust in sunlight. I lost 30 sheep, and two fingers of my left hand getting the dog out. The dog is gone too. I want the ring buried, and the cultists off my hill.'" },
    { depth: "core", about: "truth:sealed_enemy", source: "library", bias: "official", reliable: false, who: "{official}, keeper of the lamp", text: "Report of {official}, keeper of the relic lamp, to the council of {realm} on the warm rings, {year}: 'The warmth of the gate-rings is a property of the black stone, which holds the sun's heat as a hearthstone does. Six rings were dug around; nothing lies beyond them but more hillside. The shepherd's sheep died of a known rot. Funding for the Sealers' order ends this year, since it guards nothing.'" },
    { depth: "core", about: "truth:departure", source: "ruin", bias: "true", reliable: true, plain: true, who: "glass plate 296, read by {investigator}", text: "Glass plate 296 of the library at {place}, warmed in the hand by {investigator} in {year}; a calm voice, translated: 'This is the last of us leaving. We go ahead through the doors to the better place. The way is sealed for safety, not for ever. We will come back for what we left in the cradle. Keep the keys together.' Then the phrase that means come back, 22 times, until the plate went cold." },
    { depth: "core", about: "truth:departure", source: "temple", bias: "pious", reliable: "partial", points: "sub:gate_flickers", who: "{believer}'s congregation", text: "Hymn of the gate-cults, sung by {believer}'s congregation as they climb the ring at {place}, {year}: 'They went through the door and they closed it behind, but they left us a key and they left us a sign.' The congregation takes the key to be one of the black glass rods. {believer} has offered 1,000 silver to anyone who brings one to the glowing ring near {lead}." },
    { depth: "core", about: "truth:departure", source: "heretic", bias: "heretic", reliable: "partial", cost: true, points: "heretic", who: "{person}, expelled Collegium reader", text: "Pamphlet by {person}, a Collegium reader expelled in {year} for printing it: 'They did not die. In 40 years of digging we have found precursor bodies only at the rings, never in their towns or houses. A people does not vanish without leaving its dead, unless it took them along.' The Collegium burned 400 copies and struck {person}'s name from its rolls and from eleven papers. One copy survives at {lead}." },
    { depth: "core", about: "truth:departure", source: "archive", bias: "official", reliable: false, who: "Collegium senior readers", text: "Collegium consensus, voted by the senior readers at {place} in {year}, 31 for and 2 against: 'The Elder people perished in a single catastrophe, as the scorched nodes prove. There is no question of their return. Members who teach otherwise lose their stipend.' Appended by order of {official}: 'The crown thanks the Collegium for its finding, and will go on buying black glass rods from any seller.'" },
    { depth: "core", about: "truth:we_are_them", source: "ruin", bias: "true", reliable: true, plain: true, points: "library", who: "mural caption in the sleepers' hall", text: "Mural and caption in the hall of glass sleepers at {place}, copied by {investigator} in {year}. Tall figures lie down in glass, and small figures with brooms and hoes bow over them. The caption, decoded: 'We have made the keepers from our servants' line, to tend the house while we sleep. When a door opens, we wake.' The small figures have our faces, down to the ears. The full copy is in {lead}." },
    { depth: "core", about: "truth:we_are_them", source: "person", bias: "true", reliable: "partial", points: "site:sleeper_hall", who: "{investigator}, Collegium glyph-reader", text: "Letter of {investigator}, Collegium glyph-reader, to a colleague, {year}: 'The construct that walked out of the ruin found me on the road at {place}. It called me by a word the glass plates use for a tool, a hoe or a broom, never for a person. Then it asked, politely, where my master was, and whether the house had been kept. I said yes. It wrote on a plate and walked on toward {lead}.'" },
    { depth: "core", about: "truth:we_are_them", source: "oral", bias: "garbled", reliable: "partial", who: "the ruin-dwellers, to {investigator}", text: "Creation story of the ruin-dwellers, told to {investigator} through an interpreter in {year}, in exchange for three lamps: 'The tall ones made us from their shadows to sweep their floors, then lay down to sleep. Sweep well, or they will wake angry.' Asked why they kill outsiders who touch the walls, the elder said the tall ones count the fingerprints, and every print is a mark against the sweepers." },
    { depth: "core", about: "truth:we_are_them", source: "person", bias: "true", reliable: "partial", cost: true, who: "a village physician", text: "Case notes of the physician at {place}, {year}: '{person}, aged 14, one of the two children sent into the sleepers' hall with a lamp. Since that day {person} wakes at noon and sweeps the house, the yard and the road, without speaking, for exactly one hour. The other child does the same. Both now call their parents by a word nobody here knows. The construct has visited twice and seemed pleased.'" },
    { depth: "core", about: "truth:we_are_them", source: "library", bias: "propaganda", reliable: false, who: "{official}, keeper of the lamp", text: "Royal proclamation of {realm}, read in every market by order of {official}, keeper of the lamp, {year}: 'The peoples of {realm} descend from their own heroic ancestors and owe nothing to any vanished race. The so-called murals of the sleepers' hall are a forgery. The hall is closed and its door walled up with 300 bricks. The two children who entered it are in the crown's care.'" },
    { depth: "sub", about: "sub:collegium", source: "library", bias: "garbled", reliable: "partial", points: "library", who: "the Collegium's index of papers", text: "Index of papers of the Lattice Collegium, {year}, under the heading 'The ring-word': seventeen papers. Paper 4 reads it as door. Paper 9 as warning. Paper 12, by {investigator}, as cradle. Paper 17 argues it means all three, and has caused two senior readers to stop speaking. Paper 18 has been commissioned at 60 silver. The original rubbings are kept at {lead}." },
    { depth: "sub", about: "sub:last_sealer", source: "person", bias: "true", reliable: true, who: "the last sealer", text: "Said by the last sealer of the order, aged 81, to the council of {place} in {year}, asking for an apprentice: 'My mother sealed the rings. Her mother before her. I have no daughter and no niece. The seals answer to our blood and to nothing else; I have tried four others, and the stone stayed warm. When I die, ask the rings who keeps them.' The council sent the request to a committee." },
    { depth: "sub", about: "sub:construct_wakes", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:node_city", who: "an innkeeper's letter", text: "An innkeeper of {place}, writing to a cousin in {year}: 'The metal man walked into the inn at noon, bowed to the room and asked whether anyone had seen its household. Nobody had. It waited by the door for three days without eating, which was a mercy, and dusted the shelves twice. On the fourth day it set off toward the white towers at {lead}, and took the broom.'" },
    { depth: "sub", about: "sub:key_race", source: "archive", bias: "redacted", reliable: "partial", points: "site:crystal_library", who: "a spymaster's dispatch", text: "Dispatch of a spymaster of {realm} to the crown, {year}, cipher removed: 'The rival court holds two keys. We hold one. The fourth is reported in [name removed], owned by a widow who uses it as a rolling pin. Recommend acquisition by any means, up to 5,000 silver. Note that a plate in the glass library lists four keys among what was left behind. That library is at {lead}.'" },
    { depth: "sub", about: "sub:relic_crown", source: "library", bias: "propaganda", reliable: false, who: "the lamp-plinth inscription", text: "Inscription on the lamp-plinth in the throne hall of {realm}, recut in {year} by order of {official}: 'The holy lamp was gifted by the gods to the founding king, and will burn as long as the dynasty endures.' It was recut because the Collegium had begun to read the old inscription beneath, in the precursor script. The first two words, according to {investigator}, were: steward's lamp, number 9." },
    { depth: "site", about: "site:node_city", source: "traveller", bias: "garbled", reliable: "partial", who: "a survey chainman's diary", text: "Diary of a chainman with the crown survey, kept on the forbidden border near {place}, {year}: 'Saw the white towers from the ridge. Walked toward them all day, 30 miles by my pace-count. At dusk they were exactly as far off as at dawn. Day two, the same. On day three I found my own campfire from day one, and the pace-count said 90 miles. I am going home, and I am billing the crown for 90.'" },
    { depth: "site", about: "site:sea_causeway", source: "oral", bias: "garbled", reliable: "partial", who: "a fisherman, to {investigator}", text: "A fisherman of {place} to {investigator}, at the net sheds in {year}: 'At the lowest tide of the year you can walk the drowned road out four miles before it gets deep. My uncle went on past that with a rope round his waist. He came back blue, and said there's a white door out there standing up in the sea on its own, and he knocked. The rope was 300 yards. He swore it went slack, as if someone took up the other end.'" },
  ],
};
