// The Falling Hour: the world has a fixed last day; some live it over and over, some places have stopped, and something in the sky is coming down.
export default {
  id: "falling_hour",
  name: "The Falling Hour",
  family: "world",
  kind: "cycle",
  pitch: "The world has a last day, and everyone can see it coming: a second moon grows larger in the sky each night, while a few people wake each morning remembering a world that already ended.",
  slots: ["apocalypse", "time"],
  tone: ["melancholy", "horror"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "grimdark", "flintlock"],
  w: 0.9,
  excludes: ["wheel_of_suns"],
  pairs: [{ id: "unremembering", w: 2.5 }, { id: "elder_lattice", w: 1.5 }, { id: "strewn_sky", w: 1.5 }, { id: "sleeper", w: 1.2 }],

  cast: [
    { role: "investigator", n: "an astronomer of the Moon-Watch who measures the falling moon every clear night", home: "mountain", stance: "Wants the tables right to the fourth place; has begun to suspect the tables were written before." },
    { role: "official", n: "the court's Keeper of the Count, who posts the moon's width at the palace gate", home: "capital", stance: "Wants order kept until the Last Day; believes panic kills more people than moons do." },
    { role: "believer", n: "a Welcomer singer who waits at the mark of impact", home: "remote", stance: "Believes the moon is a bride coming home, and the end is a wedding." },
    { role: "survivor", n: "a small-town mask-maker who wakes each turn remembering the last", home: "any", stance: "Wants one person saved this time; trusts nobody who has not lost a world." },
  ],

  truths: [
    { id: "the_loop", n: "The world repeats", d: "The world has already ended many times. A relic called the Hourglass of Mercy, taken from the old queen's chamber into the crown treasury, turns time back to a fixed morning each time the falling moon strikes, and only a handful of people carry their memories across. Each turn is a few days shorter than the last, and the court that holds the hourglass has never told anyone it turns.", tags: ["truth:time_loop"],
      known: [
        "A few people in many towns predict events to the hour, and one merchant house never loses a bet. The court calls them lucky frauds. Chalk notes on a town wall are dated next year, and some have come true.",
        "{investigator} found more than 400 tally marks under the plaster of the writing wall, and a chalk note that says turn four hundred and six. Rememberers leave each other messages in places that never change.",
        "A crown treasury inventory lists one hourglass of gold sand from the old queen's chamber, which turns itself; its location is blotted out. {survivor} says the world goes back to the same morning each time the moon strikes.",
        "Confirmed: the world has ended many times. The Hourglass of Mercy turns time back to a fixed morning at each impact, and only a handful remember. Each turn is shorter than the last, and the court that holds the hourglass has never said so.",
      ] },
    { id: "stopped_clock", n: "The moment was stopped", d: "The world should have ended long ago. At the last instant a sorcerer-queen stopped the moment of impact over the capital with her own life, and the frozen hour is all that holds the moon in the sky. The freeze is weakening; the Clockwardens who guard her have watched the last grain move and told the court the clock is fine.", tags: ["truth:stopped_clock"],
      known: [
        "The hour-tower's clock has one hand that has not moved in living memory, and in the still city rain hangs in the air. The court calls the city a quarantine zone. Lately the raindrops have started to fall, one a day.",
        "The Clockwardens swear never to wind another clock and never to enter the cellar. {investigator} saw inside the clock case: the gears turn, but nothing connects them to the hand.",
        "In the tower cellar a woman in a crown sits before a great hourglass, utterly still, one grain hanging in its neck. Words scratched on the cellar door say she is holding the moon, and when she lets go, it lands.",
        "Confirmed: the old queen stopped the moment of impact over the capital with her own life, and the frozen hour holds the moon up. The freeze is weakening. The Clockwardens have seen the grain move and told the court nothing.",
      ] },
    { id: "falling_thing", n: "The moon is a vessel", d: "The second moon is not stone. It is a sky-city, falling because the ones who steered it are dying aboard; one pilot already died at the lever of a shard trying to turn it away from us. Someone aboard is still alive and can be reached, and the court's astronomers have called its signal lights reflections for forty years.", tags: ["truth:sky_vessel"],
      known: [
        "The markings on the falling moon have changed: priests see a face, children a door. An astronomer's sketch shows straight lines far too long for nature, and the lamps along its dark edge are fewer every winter.",
        "A shard that fell a century ago is worked metal, ribbed like a hull and riveted, with writing on its inner face. The court's library calls it natural iron with a gas bubble inside, and has closed the crater.",
        "Inside the shard is a seat, and a dried body in scaled cloth with one hand on a lever pulled hard to one side. When the mirrors on the peaks struck the moon, a light on its face flashed back.",
        "Confirmed: the moon is a sky-city, falling because its crew is dying aboard. One pilot died in the shard trying to turn it. Someone aboard is still alive and signalling, and the court's astronomers have called the lights reflections for forty years.",
      ] },
  ],

  tags: ["falling_hour"],

  subthemes: [
    { id: "countdown_court", n: "The Countdown Court", d: "Astronomers post the moon's width at the palace gate every evening. The court has made the count a ceremony, and the ceremony a way to rule.", w: 1.3, req: { any: ["monarchy", "autocracy", "has:city"] }, mods: [["faith:stars", 2], ["scholarly", 1.5]], tags: ["theme:countdown"] },
    { id: "loopers", n: "The Rememberers", d: "A secret circle of people who wake each cycle remembering the last. They leave each other messages in places that do not change.", w: 1.2, req: { any: ["seers", "mystic", "urbane", "scholarly"] }, truthLink: "the_loop", tags: ["theme:loopers"] },
    { id: "loop_merchants", n: "The Foreknowing Houses", d: "A merchant house that never loses a bet, never misses a harvest price, never sails into a storm. Its founder is said to remember tomorrow.", w: 1, req: { any: ["mercantile", "gov:merchant", "has:port"] }, truthLink: "the_loop", tags: ["theme:foreknowing"] },
    { id: "frozen_city", n: "The City in the Hour", d: "A city where time stopped: a market caught mid-shout, a bird a hand above a roof, rain hanging in the air. Lately the raindrops have started to fall, one at a time.", w: 0.9, req: { any: ["realm:large", "realm:vast", "has:city", "near:ruins"] }, truthLink: "stopped_clock", tags: ["theme:frozen_city"], mark: { kind: "zone", n: "The Still Hour", color: "#c8b88a", size: [1, 2], where: "inner" } },
    { id: "clockwardens", n: "The Clockwardens", d: "An order that tends the great clock in the capital and forbids anyone to wind any other. They say the clock holds the hour. They do not say how.", w: 1, req: { any: ["organised", "gov:theocracy", "hierarchical", "artisans"] }, truthLink: "stopped_clock", tags: ["theme:clockwardens"] },
    { id: "last_day_festival", n: "The Festival of the Last Day", d: "The towns hold a feast on the day the moon is due to fall: masks, debts forgiven, marriages made. Some towns have held it before, and do not know how they know.", w: 1.2, mods: [["pious", 1.3], ["urbane", 1.5]], tags: ["theme:last_festival"] },
    { id: "impact_cult", n: "The Welcomers", d: "A cult that waits at the predicted point of impact, singing to the moon to come faster.", w: 0.8, req: { any: ["zealous", "faith:void", "mystic", "unstable"] }, tags: ["theme:welcomers"], mark: { kind: "zone", n: "The Mark", color: "#8a3a3a", size: [1, 1], where: "remote" } },
    { id: "deflectors", n: "The Deflectors", d: "Engineers and mages building towers, ropes and great mirrors to push the moon aside. Their works are vast, expensive and absolutely certain.", w: 0.9, req: { any: ["scholarly", "arcane", "academies", "artisans"] }, truthLink: "falling_thing", tags: ["theme:deflectors"] },
    { id: "moon_face", n: "The Changing Face", d: "The markings on the falling moon have changed. Some say they look like a face. Some say like a door.", w: 1, req: { any: ["seers", "faith:stars", "learned"] }, truthLink: "falling_thing", tags: ["theme:moon_face"] },
    { id: "shortening", n: "The Shortening", d: "The rememberers have noticed that each cycle is a few days shorter than the last. Their messages have grown urgent.", w: 0.6, req: { any: ["seers", "scholarly"] }, truthLink: "the_loop", tags: ["theme:shortening"] },
    { id: "tide_ruin", n: "The Pulled Tides", d: "The falling moon's pull has driven the tides far up the coast. Harbours are dry at noon and drowned at midnight.", w: 1.1, req: { any: ["coastal", "has:port", "island", "seafaring"] }, tags: ["theme:pulled_tides"] },
  ],

  sites: [
    { id: "clock_tower", n: "The Hour-Tower of $", kind: "wonder", where: "capital", truthLink: "stopped_clock", d: "A great clock tower whose clock has one hand, and that hand has not moved in living memory.",
      layers: {
        surface: { n: "One hand", text: "The great clock of the hour-tower in {place} has one hand, pointing a hair's width short of the top. It has not moved in living memory. Couples marry under it, because it is the one thing in the city that never changes." },
        study: { n: "Nothing connects", text: "The Clockwardens oil the gears every morning, forty of them in shifts. {investigator} was allowed one look inside the case in {year}. The gears turn, but no shaft runs from them to the hand. The hand is held by nothing." },
        dig: { n: "The cellar", text: "In the cellar a woman in a crown sits before a great hourglass, utterly still. A single grain of sand hangs in the neck of the glass. The Clockwardens' roster for the cellar watch, with every name since the first, is kept at {lead}.", points: "archive" },
        revelation: { n: "The queen's hour", text: "The old queen stopped the moment of impact over the capital and paid with her own life, which is still running out one grain at a time. The Clockwardens saw the grain slip a hair's width in {year} and told the court nothing. When it falls, the hour finishes and the moon lands." },
      } },
    { id: "graffiti_wall", n: "The Writing Wall of $", kind: "anomaly", where: "any", truthLink: "the_loop", d: "A wall where chalk messages appear that no one remembers writing.",
      layers: {
        surface: { n: "Chalk on whitewash", text: "A whitewashed wall in {place} is covered in chalk notes: warnings, prices, names, a recipe for barley soup. The town repaints it every month for 12 silver, and within a week it is covered again. Nobody admits to writing on it." },
        study: { n: "Same hand, next year", text: "{investigator} copied 300 notes and compared the hands. Many are in one steady hand. Some are dated next year, and four of those have already come true: a fire, a wedding, a fallen bridge, the price of salt." },
        dig: { n: "Tally marks", text: "Under the plaster the stone is scratched with tally marks in rows that fill the wall, more than 400 of them. At the end of the last row is a small hourglass, and a note: the rest of us meet at {lead}.", points: "sub:loopers" },
        revelation: { n: "Four hundred turns", text: "Each tally is one turn of the world. The hourglass in the crown treasury sends time back to the same morning each time the moon strikes, and a few people remember. One of them has scratched a mark here every turn for 406 turns. The rows get tighter: each turn is shorter than the last." },
      } },
    { id: "observatory", n: "The Moon-Watch at $", kind: "ruin", where: "mountain", d: "An observatory that has tracked the falling moon for three hundred years.",
      layers: {
        surface: { n: "The dome on the peak", text: "A domed tower of brass instruments stands on a high peak above {place}. It has measured the falling moon on every clear night for 300 years. The astronomers are paid by the crown and fed by goatherds, who think them harmless." },
        study: { n: "Slowing and starting", text: "The tables show the moon growing more slowly than it should. Three times it has nearly stopped, and three times started again. {investigator} has checked 300 years of arithmetic and found no error in it." },
        dig: { n: "The sealed table", text: "In a sealed room are older tables in {investigator}'s own hand, with tonight's numbers already in them, to the fourth place. They end in a single drawn circle. The seal on the door is the court's, signed by the Keeper of the Count at {lead}.", points: "cast:official" },
        revelation: { n: "Observed before", text: "This has all been observed before. The sealed tables were written by the same astronomer in an earlier turn of the world, and the court sealed them rather than read them. For a generation the court has known that tomorrow's numbers already exist, and has gone on posting them as news." },
      } },
    { id: "fallen_shard", n: "The Shard of $", kind: "dig", where: "remote", truthLink: "falling_thing", d: "A fragment that fell from the moon a century ago, still warm.",
      layers: {
        surface: { n: "A slab in a crater", text: "A crater a quarter-mile wide lies near {place}, the ground still warm a century after the fall. At its centre is a black slab, too regular to be a rock. Goats sleep against it in winter for the heat." },
        study: { n: "Ribbed like a hull", text: "The slab is worked metal, ribbed like a ship's hull and riveted. {investigator} found writing on its inner face in rows, with twelve repeated signs that look like numbers. A blacksmith from the village says the rivets are better than any he could make." },
        dig: { n: "The seat and the lever", text: "Inside is a cramped chamber with a single seat. A dried body in a suit of scaled cloth sits in it, one hand still on a lever pulled hard to the left. The body was taken to {lead} for study and has not been seen since.", points: "library" },
        revelation: { n: "Someone steering", text: "The moon is a vessel, and it is crewed. This shard was a steering room, and its pilot died pulling the lever to turn the moon away from us. The court's astronomers have called the lights on the moon reflections for forty years. Some of those lights are still answering." },
      } },
    { id: "festival_town", n: "The Masked Town of $", kind: "shrine", where: "any", d: "A town that keeps a festival mask for every person who has ever lived there, and some who never have.",
      layers: {
        surface: { n: "The mask hall", text: "A hall in {place} holds a carved festival mask for every person who has lived in the town, over 3,000 of them, each with a name on the brow. Townsfolk wear their own once a year, at the Festival of the Last Day." },
        study: { n: "Masks for the unborn", text: "Some masks carry the names of children not yet born. {investigator} took down nine such names in {year}. Within two years four children of those names had been born in the town, to the families whose crests the masks bear." },
        dig: { n: "Worn from use", text: "The oldest masks are worn smooth on the inside from many wearings, though the hall's records say they were carved for festivals that never came. The mask-maker keeps a book of orders at {lead}.", points: "cast:survivor" },
        revelation: { n: "Held before", text: "The town has held the last festival many times over. The worn masks prove it, though the people remember nothing. {survivor} remembers, and carves the next turn's masks in advance. The council pays for them from the festival fund and has never once asked how the maker knows the names." },
      } },
  ],

  beings: [
    { id: "frozen_folk", n: "The Stilled", kind: "beast", d: "People caught in a stopped hour at the edge of a frozen zone. When the hour slips they lurch a step, then freeze again, and they do not like to be touched.", danger: 1, biomes: ["grass", "tempforest", "dryforest", "badlands"], look: { size: 1.7, group: [3, 20], move: "herd", speed: 0.5, col: "#c8b88a", col2: "#7a6a4a", body: "biped", active: "any", visible: true } },
    { id: "moon_moth", n: "Moonfall moth", kind: "insect", d: "Pale moths that fly straight up at night towards the falling moon, in columns so thick they hide the stars.", danger: 0, biomes: ["grass", "tempforest", "savanna", "alpine", "boreal"], look: { size: 0.08, group: [200, 3000], move: "swarm", speed: 6, col: "#e8e4d8", col2: "#a89a7a", body: "insect", active: "night", visible: true } },
    { id: "hour_hound", n: "Hour-hound", kind: "predator", d: "A lean grey hound seen at the edges of stopped places. It moves when nothing else does, and it hunts people who remember.", danger: 3, biomes: ["grass", "tempforest", "boreal", "coldsteppe", "badlands"], look: { size: 1.3, group: [1, 3], move: "pack", speed: 30, col: "#6a6a70", col2: "#c8c0a0", body: "quad", active: "night", visible: false } },
  ],

  techs: [
    { id: "fh_moon_tables", n: "Moon tables", field: "astronomy", level: 1, d: "The width of the falling moon is measured nightly, and its day of arrival reckoned from the tables." },
    { id: "fh_tide_walls", n: "Tide walls", field: "engineering", level: 2, d: "Great sea walls and lock-harbours built against the moon-drawn tides." },
    { id: "fh_clockwork", n: "Fine clockwork", field: "engineering", level: 3, d: "Clocks with springs and escapements, each one licensed and sealed by the Clockwardens." },
    { id: "fh_message_cipher", n: "Rememberers' cipher", field: "writing", level: 3, d: "A code written into the things that never change between turns, so a message can outlive the world." },
    { id: "fh_great_mirrors", n: "The great mirrors", field: "natural_philosophy", level: 4, d: "Vast burning-mirrors on the peaks, meant to push the moon aside with gathered sunlight." },
    { id: "fh_hour_theory", n: "The theory of the hour", field: "arcana", level: 5, d: "Time is understood as a thing that can be stopped, held and spent, and its cost reckoned." },
  ],

  units: [
    { id: "fh_clockwardens", n: "Clockwarden halberdiers", role: "infantry", wpn: "pike", kit: "plate", ranks: 4, gap: 1.1, size: 80, w: 0.8, mods: [["theme:clockwardens", 8]] },
  ],

  faiths: [
    { id: "fh_welcome", n: "The Welcome", d: "The moon is a bride descending; the end is a wedding, and the faithful prepare to meet it in their finest clothes.", tags: ["faith:fh_welcome", "sinister"], w: 0.6, mods: [["theme:welcomers", 6], ["mystic", 2], ["seers", 1.5]], names: ["The Bride of $", "The Welcome", "The Descending Moon"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Moonfall scar", color: "#6a5a5a", size: [1, 3], count: [0, 2], where: "remote", d: "Craters left by fragments that fell from the second moon, the ground around them still warm." },
  ],

  storylines: [
    { id: "fh_looper", n: "The One Who Remembers in {place}", scale: "local", anchor: "town", w: 1.5, req: "falling_hour",
      stages: {
        start: { h: "{person} of {place} predicts a fire", b: "{person}, a lamp-maker of {place}, warned the street of a fire three days before it started, down to the hour. Now people are asking what else the lamp-maker knows.", wait: [2, 5], next: [{ to: "followers", w: 1, mods: [["seers", 2], ["mystic", 2]] }, { to: "merchants_buy", w: 1, mods: [["mercantile", 2], ["has:port", 1.5]] }, { to: "hunted", w: 1, mods: [["zealous", 2], ["harsh_law", 2]] }] },
        followers: { h: "{person} gathers listeners in {place}", b: "Every evening {person} tells a crowd what tomorrow brings. {person} is never wrong, and looks very tired.", wait: [4, 10], next: [{ to: "tries_to_save", w: 2 }, { to: "hunted", w: 1 }] },
        merchants_buy: { h: "A merchant house buys {person}'s silence", b: "{person2}, of a great merchant house, has taken {person} into the household. The house has not lost a bet since.", wait: [4, 10], fx: { treasury: 40 }, next: [{ to: "tries_to_save", w: 1 }, { to: "house_empire", w: 1, mods: [["gov:merchant", 2]] }] },
        hunted: { h: "{person} is hunted in {place}", b: "The priests call it witchcraft and the court calls it treason. {person} has gone into hiding, leaving chalk messages on the walls.", wait: [3, 8], fx: { unrest: 6 }, next: [{ to: "tries_to_save", w: 1 }, { to: "taken", w: 1 }] },
        tries_to_save: { h: "{person} tries to save one life", b: "Turn after turn, {person} says, they have watched {person2} die on the last day. This time {person} means to change it.", wait: [4, 10], next: [{ to: "saved", w: 1 }, { to: "loop_closes", w: 1 }] },
        saved: { h: "A death is prevented in {place}", b: "{person2} lived past the day {person} said they always died. {person} wept in the square, and for the first time could not say what tomorrow would bring.", fx: { stability: 5, flag: "loop_broken" }, end: true },
        loop_closes: { h: "{person} of {place} wakes again", b: "{person2} died on the last day, as before. On the first morning {person} was found writing a new tally on the wall, one more among thousands.", fx: { unrest: 5 }, end: true },
        house_empire: { h: "The foreknowing house rules {place}", b: "With {person} at its table, {person2}'s house now owns half the harbour and a seat on every council. No one has seen {person} smile in a year.", fx: { treasury: 60, stability: -3 }, end: true },
        taken: { h: "{person} vanishes from {place}", b: "The chalk messages stopped. A grey hound was seen at the end of the lamp-maker's street the night before.", fx: { stability: 2 }, end: true },
      } },
    { id: "fh_deflection", n: "The Mirrors of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["falling_hour", { any: ["scholarly", "learned", "academies", "rich", "arcane"] }],
      stages: {
        start: { h: "{realm} resolves to turn the moon aside", b: "{ruler} has funded the great work: vast mirrors on the peaks of {realm} to push the falling moon away with gathered sunlight. {investigator}, the Moon-Watch astronomer, leads the engineers.", wait: [6, 14], fx: { treasury: -60, science: { natural_philosophy: 0.6 } }, next: [{ to: "mirrors_lit", w: 2 }, { to: "money_runs_out", w: 1, mods: [["poor", 2], ["atwar", 2]] }] },
        mirrors_lit: { h: "The mirrors of {realm} are lit", b: "For one noon the peaks of {realm} blazed like a second sun, and a beam struck the falling moon. A light on its face flashed in answer.", wait: [3, 8], next: [{ to: "moon_answers", w: 1, mods: [["learned", 2]] }, { to: "nothing_changes", w: 2 }, { to: "rival_fears", w: 1, mods: [["has:rival", 2]] }] },
        money_runs_out: { h: "The mirror-works of {realm} stand idle", b: "Half-built frames rust on the peaks. The treasury of {capital} is empty, and the moon is no smaller.", fx: { stability: -8, prestige: -5 }, end: true },
        moon_answers: { h: "Lights on the moon answer {realm}", b: "Night after night, lights on the falling moon flash back at the mirrors in a pattern. {investigator} believes it is a language, and that the moon is asking for help.", fx: { discovery: "astronomy", prestige: 15, flag: "moon_contact" }, end: true },
        nothing_changes: { h: "The moon falls on regardless", b: "The beams struck true and the tables did not change. {investigator} has gone up to the peaks alone and does not answer letters.", fx: { stability: -5 }, end: true },
        rival_fears: { h: "{rival} calls the mirrors a weapon", b: "A beam that can strike the moon can strike a city. {rival} has demanded the mirrors be torn down, and is mustering.", fx: { relation: { rival: -25 }, war: "rival" }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", points: "archive", who: "{official}, Keeper of the Count", text: "Almanac of the Court, page one, issued by {official}, Keeper of the Count: 'The second moon descends at a measured rate, now a thumb's width a month. By the tables, the Last Day falls in the year {year}. Citizens are reminded that taxes remain due until then, and that the Festival of the Last Day is not a holiday for debt. The full tables may be seen at {lead} for one copper.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "the schoolmistress of {place}", text: "The schoolmistress of {place}, answering {investigator} at the school gate in {year}: 'Yes, all 26 of my pupils skip to it on new year's morning. Moon come down and moon come round, wake up early, safe and sound. I did not teach it, and their mothers say they did not either. I asked three of the children what happens after the moon comes down. All three said the same thing: you wake up.'" },
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", who: "a temple sermon", text: "Sermon at the temple of {deity} in {place}, preached on the night the moon filled a third of the sky, {year}: 'The moon is the eye of {deity}, stooping low to judge us. Be found doing good on the Last Day. Pay your tithe before then, for the temple cannot accept it after. There are 400 days left by the court's tables. Use them well.'" },
    { depth: "core", about: "truth:the_loop", source: "ruin", bias: "true", reliable: true, plain: true, who: "chalk on the writing wall", text: "Chalk on the writing wall at {place}, in a steady hand, found on the first morning of {year}: 'If you are reading this and do not remember writing it: you did. This is turn four hundred and six. When the moon strikes, the hourglass in the treasury turns time back to this morning, and you will forget again. Do not go to the harbour on the last day. Find the others. We are fewer each turn.'" },
    { depth: "core", about: "truth:the_loop", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, mask-maker", text: "Letter of {survivor}, mask-maker, never sent, found in a drawer at {place} in {year}: 'I have married {person} eleven times. {person} has never once known me on the first morning. I walk into the bakery, say good morning, and watch {person} decide whether I am worth a second look. Twice the answer was no. I am so tired of introducing myself, and this turn I have 31 days left.'" },
    { depth: "core", about: "truth:the_loop", source: "heretic", bias: "heretic", reliable: "partial", who: "a watch report", text: "Report of the watch at {place}, {year}, on a street-preacher arrested in the fish market: 'Shouted that the world is a song the god keeps singing from the start, because the god cannot bear the last verse. Claimed to have heard the song 30 times. Claimed the last verse is a moon on the harbour.' Fined 5 silver. On the last day the preacher was seen standing on the harbour wall, waiting." },
    { depth: "core", about: "truth:the_loop", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "a crown treasury inventory", text: "Crown treasury inventory of {year}, page 9, an item struck through by a later hand: 'One hourglass, sand of gold, from the old queen's chamber, eighteen inches high. Turns itself. Location: ...' The rest is blotted. A clerk's note in the margin: 'Moved by order. See the warrant book at {lead}.' The warrant book for that year is missing one page." },
    { depth: "core", about: "truth:the_loop", source: "library", bias: "official", reliable: false, who: "{official}, Keeper of the Count", text: "Ruling of the court's examiners at {place}, {year}, signed by {official}, Keeper of the Count: 'The so-called rememberers are lucky guessers and frauds who hide their failures. Of 40 examined, all made wrong predictions, which they now deny making. Time runs one way, as every licensed clock in {realm} attests. Persons claiming to remember tomorrow will be fined, and their chalk confiscated.'" },
    { depth: "core", about: "truth:stopped_clock", source: "temple", bias: "pious", reliable: "partial", points: "site:clock_tower", who: "the Clockwardens' vow", text: "Vow of the Clockwardens, taken by each novice at the age of 16, kneeling on the bare stair of the hour-tower at {lead}: 'I will tend the hour and not ask what it holds. I will wind no clock but the one. I will not go into the cellar. If I hear sand fall, I will tell the Warden and no one else.' The order has forty sworn members. It has never had more." },
    { depth: "core", about: "truth:stopped_clock", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a carter at an inn", text: "A carter who took the wrong road into the still city near {place}, telling it at an inn in {year}: 'There's rain hanging in the air there, every drop. Walk into one and it's cold and hard as a glass bead; I have the bruise to show you. A bird a hand above a roof. A market woman with her mouth open. And mark this: the drops are falling now. One a day. I watched one hit the cobbles. It was the only sound in the street.'" },
    { depth: "core", about: "truth:stopped_clock", source: "ruin", bias: "true", reliable: true, plain: true, who: "the hour-tower's cellar door", text: "Scratched into the hour-tower's cellar door with a nail, in letters an inch high, found by {investigator} in {year}: 'She is holding it. The queen stopped the moon over the capital with her own life, and that hour is all that holds it up. Do not wake her. Do not touch the glass. When she lets go, it lands.' Under it is the Clockwardens' mark and a date ninety years old." },
    { depth: "core", about: "truth:stopped_clock", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "a Clockwarden disciplinary record", text: "Disciplinary record of the Clockwardens, {year}: 'Novice {person}, aged 19, went into the cellar on the night watch against the third vow. Found at dawn on the cellar stair, aged as if by sixty years, hair white and teeth gone. {person} said only: the grain moved, I saw it move. {person} died before noon. The family has been paid 50 silver and told it was a fever.'" },
    { depth: "core", about: "truth:stopped_clock", source: "archive", bias: "official", reliable: false, who: "{official}, Keeper of the Count", text: "Order of the court, renewed in {year} under the seal of {official}: 'The still city is a quarantine zone for a sleeping-sickness of the old reign. The cordon of 200 soldiers remains in place. Reports of suspended rain are the fancies of trespassers. Trespassers will be held for 40 days in case of contagion, and charged for their board.'" },
    { depth: "core", about: "truth:falling_thing", source: "library", bias: "true", reliable: "partial", points: "site:fallen_shard", who: "{investigator}, Moon-Watch astronomer", text: "Night book of {investigator}, astronomer of the Moon-Watch, entry for {year}, beside a sketch of the moon's face: 'New markings in the south quarter. Straight lines crossing at right angles, the longest perhaps 80 miles. Nature does not draw straight lines that long. The shard that fell at {lead} a century ago had the same lines on its plates. I have asked the court for leave to go and look.'" },
    { depth: "core", about: "truth:falling_thing", source: "person", bias: "true", reliable: true, plain: true, points: "archive", who: "the mirror-master's report", text: "Report of the mirror-master of the peaks to the court, {year}: 'For 30 nights the lights on the moon have flashed back at our mirrors in one pattern. Read with the coast navy's signal book, it says: WE ARE FALLING. PILOTS DEAD. FOUR LEFT. HELP US STEER. The moon is a ship, and somebody aboard is alive. Our night logs, every flash, are lodged at {lead}. I ask for orders.'" },
    { depth: "core", about: "truth:falling_thing", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, mirror-hand", text: "Letter from {person}, a hand on the third mirror-frame of the peaks, to family, {year}: 'We lit the mirrors at noon. The beam struck the moon and a light flashed straight back down it. I was looking. I cannot see now, with either eye. The engineer says it was worth it, because the moon answered. I am paid off with 30 silver. Please come for me at the foot of the peaks.'" },
    { depth: "core", about: "truth:falling_thing", source: "heretic", bias: "exaggerated", reliable: "partial", who: "a soldier of the cordon", text: "Chant of the Welcomers, sung by {believer} and 70 followers at the mark of impact, written down by a soldier of the cordon in {year}: 'Our sisters ride the moon, and they are coming home!' {believer} told the soldier the moon is a bride, and the lights on it are the wedding guests, fewer every year because they are dressing. That night {believer} led the singing until dawn, in white." },
    { depth: "core", about: "truth:falling_thing", source: "library", bias: "official", reliable: false, who: "{official}, Keeper of the Count", text: "Finding of the court library on the shard near {place}, {year}, approved by {official}: 'The black slab of the shard-crater is a natural iron mass. The so-called chamber within is a gas bubble formed as the iron cooled. The so-called body is a goatherd who crawled inside to die. The rivets are not rivets. The crater is closed to visitors from this year, by a fence of 400 posts.'" },
    { depth: "sub", about: "sub:countdown_court", source: "archive", bias: "propaganda", reliable: false, who: "{official}, Keeper of the Count", text: "Proclamation posted at the palace gate by {official}, Keeper of the Count, on the evening the moon measured 41 thumbs, {year}: 'The Crown's astronomers report that the moon's descent has slowed, thanks to the prayers of our Sovereign. Remain calm. Remain at work. The evening count will now be read by a herald, and the astronomers' own figures will no longer be posted, to spare the public the arithmetic.'" },
    { depth: "sub", about: "sub:loopers", source: "person", bias: "true", reliable: "partial", points: "site:graffiti_wall", who: "a note under a cobble", text: "Note found pinned under a loose cobble in {place} in {year}, folded small, in a cipher the watch could not read; decoded later by {investigator}: 'Same place next turn. Bring the numbers. Trust no grey dog. Turn 406 is eleven days shorter than 405. If you are new, go to the wall at {lead} and count the marks. Then you will believe us.'" },
    { depth: "sub", about: "sub:loop_merchants", source: "traveller", bias: "exaggerated", reliable: "partial", points: "archive", who: "a rival shipowner", text: "A rival shipowner of {place}, complaining to the insurers' guild in {year}: 'The House never insures a ship that sinks. Never. Not once in 40 years and 212 voyages. It sold its grain the week before the price fell, and bought salt the day before the tide wall broke. The other houses have stopped bidding against it. Its ledgers are lodged with the guild at {lead}. I ask the guild to read them.'" },
    { depth: "sub", about: "sub:last_day_festival", source: "oral", bias: "garbled", reliable: true, points: "site:festival_town", who: "{survivor}, mask-maker", text: "Overheard in the workshop of {survivor}, mask-maker of the masked town at {lead}, by a customer in {year}: 'I always know which masks will be wanted. Last year I carved fourteen for babies, and fourteen were born. I'm only good at guessing.' The customer noticed a mask on the shelf with the customer's own name carved on the brow, worn soft on the inside, marked for next spring." },
    { depth: "sub", about: "sub:tide_ruin", source: "person", bias: "true", reliable: true, who: "a harbourmaster's log", text: "Harbourmaster's log, {place}, {year}: 'Low water at noon: the whole bay dry to the outer rocks, and children picking crabs off the mooring chains. High water at midnight: three streets under, and the chandler's stock gone. Fourth time this month. The tide wall cost 2,000 silver and has held for six weeks. I have asked the council for a boat for the harbourmaster's office.'" },
    { depth: "sub", about: "sub:moon_face", source: "temple", bias: "pious", reliable: "partial", who: "a temple notice", text: "Notice on the door of the temple of {deity} at {place}, {year}: 'The new markings on the moon are the face of {deity}, opening its eyes. Sermons on this subject will be held every evening for 3 coppers. The temple asks parents to stop their children saying the markings look like a door opening, as it upsets the congregation.'" },
    { depth: "site", about: "site:observatory", source: "archive", bias: "redacted", reliable: "partial", points: "cast:official", who: "{investigator}, Moon-Watch astronomer", text: "Night book of {investigator}, the Moon-Watch, {year}: 'Tonight's figure matches the sealed table exactly, to the fourth place. So did last night's, and the thirty before. The sealed table is in my own hand. I do not remember writing it. The seal on that room belongs to the Keeper of the Count, and the Keeper's office at {lead} will not answer my letters.'" },
  ],
};
