// The Great Root: an immeasurable tree binds the heavens, the lands and the deeps, and it is sick.
export default {
  id: "great_root",
  name: "The Great Root",
  family: "world",
  kind: "cosmic",
  pitch: "A single tree, too big to measure, holds the sky realms, the mortal lands and the deeps together. It is sick, and the blight is spreading down every branch.",
  slots: ["cosmology", "ecology"],
  tone: ["mythic", "melancholy"],
  era: ["stone", "bronze", "medieval"],
  scale: "world",
  genres: ["fantasy", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "broken_writ", w: 2.5 }, { id: "gods_twilight", w: 2.5 }, { id: "unquiet_gate", w: 2 }, { id: "wheel_of_suns", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a ring-reader who counts the growth-rings of fallen boughs to read the tree's history", home: "forest", stance: "Wants the rings read honestly; believes the tree is old, not sick, and is afraid of what that means." },
    { role: "official", n: "the registrar of the Sap Clergy, who keeps the sap-yield books and seals the clergy's decrees", home: "capital", stance: "Wants the sap flowing and the kings anointed; believes the Mother must never be doubted in public." },
    { role: "believer", n: "a speaker of the Fellers who preaches that the tree drinks the dead", home: "border", stance: "Believes the world will only be free when the tree falls, and that the first king's axe can fell it." },
    { role: "survivor", n: "a Root Watch sergeant who has held deep post four for eleven years", home: "mountain", stance: "Wants the deep posts reinforced; has heard what is down there and does not care what the clergy call it." },
  ],

  truths: [
    { id: "gnawing", n: "Something gnaws the roots", d: "A great wyrm lies coiled among the roots below the world and has been eating them for ages. The blight spreads from its bites; the old shrine-keepers fed it blight-wood to slow it, and it ate faster. When it chews through the last root the realms will come apart, and the Sap Clergy have forbidden anyone to say so since the Root Watch first reported the chewing.", tags: ["truth:root_gnawing"],
      known: [
        "A root-ridge has turned grey, its rivers thick with sap. The Sap Clergy call it a passing sickness of the bark and forbid tales of a beast below. Pale serpents as long as boats have begun climbing out of the root-caves.",
        "The Root Watch logs chewing at deep post four, and a new hollow the size of a barn in a braced root-wall. The weavers' tallies at the well of threads show the water falling for a thousand years, and faster lately.",
        "Below the well of threads the root-wall carries fresh tooth marks a man could lie in. A shrine under the hills records that its keepers fed the beast blight-wood to slow it, and it ate faster.",
        "Confirmed: a great wyrm coils among the roots and has been eating them for ages, and the blight spreads from its bites. When the last root goes, the realms come apart. The clergy took the Root Watch's logs and forbade anyone to say so.",
      ] },
    { id: "parasite", n: "The tree is feeding", d: "The tree does not hold the world up; it grew into it and drinks it. The dead do not rest: they walk down into the roots, and the tree feeds on them to keep its crown green. The Sap Clergy have recorded sap yields trebling in every plague year and war, and keep the yield books apart from the death-rolls so that nobody sets them side by side.", tags: ["truth:root_parasite"],
      known: [
        "On still nights the dead are seen walking down the root-paths with lanterns. The clergy say the dead rest in the Mother's roots like a child in its mother's arms. The Fellers ask why the crown grows greener after every war.",
        "A miner who broke into the underroots met a dead mother sweeping a step in a grey town, roots running through every house. A clergy register notes sap yield trebling in a plague year, and orders it kept apart from the death-rolls.",
        "In the desert stands the burned stump of a second world-tree, its root-hollows packed with millions of bones. Its burners carved an apology: they set it alight so the dead could go where the dead should go.",
        "Confirmed: the tree does not hold the world up. It grew into it and drinks it, and the dead walk down into the roots to feed it. The Sap Clergy hold the yield books that prove it, and keep them in a different room from the death-rolls.",
      ] },
    { id: "seed", n: "The last seed", d: "The tree is not dying of sickness but of age, and it is putting all its strength into one final seed growing in its hollowed heartwood. The world is only the shell around that seed, and it will be cracked and thrown away when the seed falls. The first peoples knew and left their trunk city in one season; the clergy have since forbidden the ring-readers to publish.", tags: ["truth:root_seed"],
      known: [
        "The ring-readers find a thousand good years in the fallen boughs, then three hundred lean ones, each ring narrower. The clergy call it rest. The great leaf-fall came early this generation, and the leaves are spotted brown.",
        "{investigator} notes that old orchard trees narrow their rings the same way in their last fruiting. A seed fell from the crown and sprouted far away, and everything for a league around it is withering.",
        "Pilgrims who climbed into a crack in the trunk say the heartwood is gone, and a huge warm round thing fills the hollow and moves when they sing. The walls of the old trunk city are pushed outward from inside.",
        "Confirmed: the tree is dying of age and putting all its strength into one last seed. The world is the shell around it, and will be cracked and thrown away when the seed falls. The first peoples knew, and left; the clergy have silenced the ring-readers.",
      ] },
  ],

  tags: ["world_tree"],

  subthemes: [
    { id: "blighted_ridge", n: "The Blighted Ridge", d: "A root-ridge has turned grey. Its rivers run thick with sap, its trees drop their leaves in summer, and the blight crawls a little further down the valleys every year.", w: 1.4, truthLink: "gnawing", tags: ["theme:blight"], mark: { kind: "zone", n: "The grey ridge", color: "#7a7468", size: [2, 4], where: "mountain" } },
    { id: "fallen_bough", n: "The Fallen Bough", d: "A canopy-realm fell when its branch broke. Its survivors came down as refugees with wings they cannot use in heavy air, and nobody wants them.", w: 1, req: { any: ["mountain", "forest", "realm:large", "has:city"] }, tags: ["theme:fallen_bough"] },
    { id: "bitter_well", n: "The Bitter Well", d: "The well of fate among the roots has turned bitter. The weavers who drink it to see the future now see only one future, and it ends soon.", w: 0.9, req: { any: ["seers", "mystic", "faith:spirits"] }, truthLink: "gnawing", tags: ["theme:bitter_well"] },
    { id: "wyrmspawn", n: "The Climbing Spawn", d: "Pale serpents as long as boats have begun coming up out of the root-caves. The miners of the deep valleys have sealed their shafts with stone and prayer.", w: 1.1, req: { any: ["mountain", "hills", "mountain_folk", "near:ruins"] }, truthLink: "gnawing", tags: ["theme:wyrmspawn"] },
    { id: "fellers", n: "The Fellers", d: "A brotherhood of woodsmen who believe the tree is a tyrant and the world will only be free when it falls. They are searching for an axe that was buried with the first king.", w: 1, req: { any: ["egalitarian", "forest_folk", "tribal", "faith:philosophy"] }, truthLink: "parasite", tags: ["theme:fellers"] },
    { id: "sap_heirs", n: "The Sap-Blood Heirs", d: "The royal line claims descent from the tree itself, and proves it by bleeding amber. Two heirs bleed amber; one bleeds red, and is the eldest.", w: 1.3, req: { any: ["monarchy", "divine_right", "dynastic", "origin:old_dynasty"] }, tags: ["theme:sap_heirs"] },
    { id: "descending_dead", n: "The Descending Dead", d: "On still nights the dead are seen walking down the root-paths into the earth, single file, lanterns in hand. Families follow them as far as they dare.", w: 1, req: { any: ["ancestor_bound", "faith:ancestors", "pious"] }, truthLink: "parasite", tags: ["theme:descending_dead"] },
    { id: "far_sprout", n: "The Far Sprout", d: "A seed fell from the crown and sprouted in a distant land. The sapling grows a hand's width a day, and everything for a league around it is withering.", w: 0.8, truthLink: "seed", tags: ["theme:far_sprout"], mark: { kind: "zone", n: "The withering round", color: "#a89a5a", size: [1, 3], where: "remote" } },
    { id: "lying_runner", n: "The Lying Runner", d: "The bark-skitters that run messages up and down the trunk have started carrying lies. Two realms are at the brink of war over an insult neither ever sent.", w: 0.9, req: { any: ["has:rival", "monarchy", "spy_network", "dynastic"] }, tags: ["theme:lying_runner"] },
    { id: "hollow_pilgrims", n: "The Hollow Pilgrims", d: "Pilgrims who climbed into a crack in the trunk came back saying the tree is hollow, and that a huge round thing is growing inside it.", w: 0.8, req: { any: ["pilgrims", "pious", "scholarly"] }, truthLink: "seed", tags: ["theme:hollow_trunk"] },
    { id: "leaf_fall", n: "The Great Leaf-Fall", d: "Once in a generation the crown sheds, and leaves the size of sails bury the forests. This shedding came early, and the leaves are spotted brown.", w: 1.1, req: { any: ["forest", "forest_folk", "jungle", "river"] }, truthLink: "seed", tags: ["theme:leaf_fall"] },
    { id: "root_springs", n: "The Root-Springs", d: "Where the deep roots run hot, geysers break through the valleys and the sick come to bathe. The springs have begun to smell sweet, like sap.", w: 0.8, req: { any: ["mountain", "hills", "cold"] }, tags: ["theme:root_springs"] },
  ],

  sites: [
    { id: "well_of_threads", n: "The Well of Threads at $", kind: "shrine", where: "mountain", truthLink: "gnawing", d: "A spring among the deepest roots where the weavers of fate have drawn water since the first age.",
      layers: {
        surface: { n: "Three weavers", text: "A cold pool lies in a cavern of roots under the mountains near {place}, tended by three silent weavers of fate. Pilgrims pay 2 silver to ask a question and receive a knotted thread in answer. Most cannot read the knots." },
        study: { n: "The falling water", text: "The weavers' tallies are cut into the root-wall, one notch a year. {investigator} read a thousand of them. The water has fallen slowly and steadily the whole time, about a finger a decade, and twice as fast in the last fifty years." },
        dig: { n: "Tooth marks", text: "Below the pool, the root-wall is scored with tooth marks a man could lie down in. The edges are fresh and smell of sap. The Root Watch log for the deep post below this stretch is kept by its sergeant at {lead}.", points: "cast:survivor" },
        revelation: { n: "Another drinker", text: "The well is not drying up. The wyrm that left the tooth marks drinks the same water, and every year it comes closer. The weavers have seen it. The clergy have known since the Root Watch's first report in {year}, and still send pilgrims down at 2 silver a question." },
      } },
    { id: "trunk_city", n: "The Carved Halls of $", kind: "ruin", where: "remote", truthLink: "seed", d: "A city carved into the living trunk by the first peoples, abandoned in a single season.",
      layers: {
        surface: { n: "Windows in the bark", text: "Stairways and windows are cut into the bark a mile up the trunk above {place}, long empty. From below they look like woodworm holes. Climbers who reach them report 400 rooms, the furniture still in place." },
        study: { n: "Walls pushed out", text: "The city's inner walls bulge outward and the doorframes are cracked, as if the wood swelled from within. {investigator} counted the rings in a split beam: the swelling began the same year the boughs began to narrow." },
        dig: { n: "The hollow", text: "In the deepest hall the heartwood is gone. In its place is a smooth, vast hollow, warm to the hand, which pulses faintly when anyone sings. The hollow pilgrims who went further left a journal, now kept at {lead}.", points: "sub:hollow_pilgrims" },
        revelation: { n: "Making room", text: "The first peoples left their city in one season because the tree needed the room. The seed is growing in the heartwood, and the world is only its shell. The Sap Clergy still draw anointing sap from this trunk, and every bucket they take is taken from the seed." },
      } },
    { id: "sister_stump", n: "The Burned Stump of $", kind: "ruin", where: "desert", truthLink: "parasite", d: "The charred stump of a second world-tree, wide as a city, in the middle of a dead land.",
      layers: {
        surface: { n: "A black ring", text: "A ring of black wood, wide as a city, stands in a desert near {place} where nothing has grown in living memory. Caravans steer three days around it. Their camels will not cross the old root-line." },
        study: { n: "The shape of roots", text: "The desert is not natural. {investigator} walked its edge for forty days: it is the exact shape of a vanished root-spread, branching like a hand, and it is lifeless down to the bedrock." },
        dig: { n: "Bones like seeds", text: "Inside the root-hollows are bones, millions of them, packed like seeds in a pod. None is newer than the fire. A hearthstone carved by the people who burned the tree was carried away to {lead}.", points: "library" },
        revelation: { n: "Forgive us the desert", text: "Long ago a people burned a world-tree to free the dead it held. Their land became desert and they died of thirst in it, but they did it on purpose. The Sap Clergy teach this stump as a warning against the Fellers, and leave out what it was burned for." },
      } },
    { id: "underroots", n: "The Underroots of $", kind: "dig", where: "any", d: "Mine-shafts that broke into the root-system and found it runs through another country entirely.",
      layers: {
        surface: { n: "A forbidden mine", text: "A worked-out silver mine near {place} has its deep shafts bricked shut by order of the clergy. The miners' guild still pays a pension to 31 families from the last shift that went below the fifth level." },
        study: { n: "Cathedral roots", text: "The lowest gallery opens onto roots like cathedral pillars, with a grey light below them. {investigator} lowered a lamp on 300 feet of chain. It came back up cold, and the flame had turned grey." },
        dig: { n: "Grey towns", text: "Between the roots lie grey fields and quiet towns, and people who do not answer when spoken to. One miner came back up and named the people seen there. Every name matches the burial rolls at {lead}.", points: "archive" },
        revelation: { n: "Through the dead", text: "The roots pass through the land of the dead. Whatever else the tree is, it has been drawing on the dead since the first funeral. The 31 miners of the last shift are down there too, sweeping steps, and the guild has not stopped paying their pensions." },
      } },
    { id: "fallen_branch", n: "The Branch of $", kind: "wonder", where: "coast", d: "A coast whose long headland is, on close inspection, a fallen branch of the tree turned to stone.",
      layers: {
        surface: { n: "Ringed rock", text: "A grey headland runs forty miles out from the coast near {place}. Its rock is strange and ringed, and the fishermen use it as a wharf. Children dig grubs out of it that taste of honey." },
        study: { n: "Growth rings", text: "{investigator} counted the rings: they are growth-rings, and the bark pattern runs the whole forty miles. The outermost ring is narrow and dark. The bough fell in a lean year, about 600 years ago." },
        dig: { n: "The nests", text: "Inside the stone are petrified nests the size of houses, and the bones of winged people from a canopy realm, some still holding cups. Their pottery matches the shards carried by the refugees at {lead}.", points: "sub:fallen_bough" },
        revelation: { n: "Forgotten in a generation", text: "Branches have fallen before. A whole sky-realm came down here and died, and the coast forgot it in a generation. The refugees of the latest fallen bough are being turned away from these harbours by the great-grandchildren of the people who built a wharf on the last one." },
      } },
  ],

  beings: [
    { id: "bark_skitter", n: "Bark-skitter", kind: "small", d: "A long-tailed messenger-beast that runs the trunk between realms carrying news, and, increasingly, slanders of its own invention.", danger: 0, biomes: ["tempforest", "boreal", "rainforest", "temprain"], look: { size: 0.5, group: [1, 3], move: "solo", speed: 30, col: "#8a5a2a", col2: "#c89a5a", body: "quad", active: "day", visible: true } },
    { id: "root_wyrm", n: "Root-wyrm", kind: "predator", d: "A pale blind serpent spawned among the roots, as long as a fishing boat, that climbs out of caves to swallow sheep and miners.", danger: 3, biomes: ["alpine", "peaks", "boreal", "tempforest", "swamp"], look: { size: 9, group: [1, 1], move: "solo", speed: 5, col: "#d8d0c0", col2: "#8a7a6a", body: "serpent", active: "night", visible: true } },
    { id: "crown_stag", n: "Crown-stag", kind: "grazer", d: "A great white stag of the canopy that browses the tree's young leaves. Where herds of them come down to earth, people say the crown above is failing.", danger: 1, biomes: ["tempforest", "boreal", "alpine", "grass"], look: { size: 2.2, group: [3, 12], move: "herd", speed: 18, col: "#e8e4d8", col2: "#7a8a5a", body: "quad", active: "dusk", visible: true } },
    { id: "blight_moth", n: "Blight-moth", kind: "insect", d: "A grey moth that rises in clouds from blighted bark. Wherever its dust settles, leaves spot brown within a week.", danger: 1, biomes: ["tempforest", "boreal", "swamp", "temprain", "dryforest"], look: { size: 0.1, group: [50, 400], move: "swarm", speed: 8, col: "#8a8478", col2: "#5a544a", body: "insect", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "gr_sap_tapping", n: "Sap-tapping", field: "medicine", level: 1, d: "The tree's amber sap, drawn in thimblefuls, closes wounds and breaks fevers. Drawn in buckets, it makes kings." },
    { id: "gr_canopy_ways", n: "Canopy ways", field: "architecture", level: 2, d: "Rope-bridges, hanging towns and lift-baskets that link the high branches to the earth." },
    { id: "gr_heartwood_forging", n: "Heartwood forging", field: "metallurgy", level: 3, d: "Weapons of fallen heartwood cured in root-springs, harder than bronze and deadly to root-wyrms." },
    { id: "gr_ring_reading", n: "Ring-reading", field: "natural_philosophy", level: 3, d: "Counting the growth-rings of fallen branches to read the history of the world, year by year, and its sicknesses." },
    { id: "gr_blight_grafting", n: "Blight grafting", field: "agriculture", level: 4, d: "Cutting away blighted wood and grafting healthy shoots, learned on orchards and tried, desperately, on the tree itself." },
    { id: "gr_seed_lore", n: "The lore of the seed", field: "arcana", level: 5, d: "The knowledge of what the tree is growing in its heart, and what will be left of the world when it is done." },
  ],

  units: [
    { id: "gr_root_watch", n: "Root Watch", role: "infantry", wpn: "spear", kit: "hide", ranks: 3, gap: 1.4, size: 80, w: 1.2, mods: [["theme:wyrmspawn", 6], ["theme:blight", 3], ["mountain_folk", 1.5]] },
    { id: "gr_heartwood_bows", n: "Heartwood bowmen", role: "ranged", wpn: "bow", kit: "light", ranks: 3, gap: 1.4, size: 100, w: 1, mods: [["forest_folk", 3], ["theme:leaf_fall", 2]] },
  ],

  faiths: [
    { id: "gr_sap_clergy", n: "The Sap Clergy", d: "The tree is mother and pillar; its sap is grace, and its priests tend the trunk and anoint the kings.", tags: ["faith:world_tree", "organised"], w: 1.5, names: ["The Clergy of the Root", "The Green Pillar of $", "The Mother-Tree"], mods: [["forest_folk", 2], ["theme:sap_heirs", 3], ["pious", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Root-blight", color: "#6a6658", size: [2, 5], count: [1, 2], where: "mountain", d: "Grey valleys along a sick root-ridge where the leaves fall in summer and the rivers run sweet and thick." },
  ],

  storylines: [
    { id: "gr_blight_spreads", n: "The Grey of {place}", scale: "local", anchor: "town", w: 1.5, req: "world_tree",
      stages: {
        start: { h: "The orchards of {place} turn grey", b: "In a single week every tree around {place} dropped its leaves. The bark is soft and smells of old sap, and the grey moths are everywhere.", wait: [2, 5], fx: { growth: -0.002 }, next: [{ to: "graft", w: 1, mods: [["learned", 2], ["artisans", 1.5]] }, { to: "burn", w: 1, mods: [["harsh_law", 2], ["martial", 1.5]] }, { to: "spreads", w: 1 }] },
        graft: { h: "{person} tries to graft the grey trees of {place}", b: "An old orchard-keeper is cutting out the grey wood branch by branch and grafting on shoots from the high valleys. The clergy watch and do not help.", wait: [4, 10], next: [{ to: "saved", w: 1, mods: [["learned", 1.5]] }, { to: "spreads", w: 1 }] },
        burn: { h: "{place} burns its own orchards", b: "On the reeve's order, every grey tree in {place} has been fired. The moths rose from the smoke in a cloud that blotted out the sun.", wait: [2, 6], fx: { unrest: 10, growth: -0.003 }, next: [{ to: "spreads", w: 1 }, { to: "saved", w: 1, mods: [["chance:low", 1]] }] },
        spreads: { h: "The grey reaches the root under {place}", b: "The blight has gone down into the earth. Wells around {place} taste sweet, and at night farmers feel a large body moving beneath the fields.", wait: [3, 8], fx: { stability: -5, flag: "deep_blight" }, next: [{ to: "abandoned", w: 2 }, { to: "wyrm_slain", w: 1, mods: [["martial", 2], ["theme:wyrmspawn", 3]] }] },
        saved: { h: "Green shoots in {place}", b: "The grafts have taken. {person}'s orchard is green again, and pilgrims are walking from the far valleys to beg cuttings.", fx: { growth: 0.003, science: { agriculture: 0.6 }, monument: { tier: 1, name: "The Grafted Orchard" } }, end: true },
        abandoned: { h: "{place} is left to the grey", b: "The last families have loaded their carts and gone. The roofs of {place} are already furred with moth-dust.", fx: { abandon_town: true, stability: -4 }, end: true },
        wyrm_slain: { h: "A root-wyrm slain beneath {place}", b: "Miners and soldiers went down into the old shafts and came back with the head of a blind white serpent. The wells ran clear the next morning.", fx: { prestige: 6, stability: 4 }, end: true },
      } },
    { id: "gr_fellers_axe", n: "The Axe of the First King", scale: "realm", anchor: "realm", w: 1.2, req: ["world_tree", { any: ["forest_folk", "egalitarian", "faith:world_tree", "pious"] }],
      stages: {
        start: { h: "Fellers break into a royal tomb of {realm}", b: "The barrow of the first king of {realm} has been opened in the night. The grave-goods are untouched; only the old bronze axe is gone.", wait: [2, 5], fx: { unrest: 6 }, next: [{ to: "hunt", w: 2 }, { to: "preaching", w: 1, mods: [["egalitarian", 2], ["poor", 1.5]] }] },
        hunt: { h: "{ruler} hunts the Fellers through the forests", b: "Riders under {person} are burning woodsmen's camps across {realm}. The clergy of {faith} have declared the Fellers enemies of the world itself.", wait: [3, 8], fx: { stability: -3, unrest: 8 }, next: [{ to: "axe_recovered", w: 2, mods: [["martial", 1.5]] }, { to: "first_cut", w: 1 }] },
        preaching: { h: "Fellers preach openly in {realm}", b: "{believer}, the Fellers' speaker, tells crowds that the tree drinks their dead, and that their grandmothers are down in the roots, waiting to be freed.", wait: [3, 8], fx: { unrest: 12 }, next: [{ to: "first_cut", w: 2 }, { to: "hunt", w: 1 }] },
        first_cut: { h: "The first king's axe bites the trunk", b: "The Fellers reached the trunk and struck it once. Amber sap poured out like a river, and the whole of {realm} felt the ground shudder.", wait: [1, 3], fx: { stability: -10, flag: "cut" }, next: [{ to: "dead_freed", w: 1, mods: [["faith:ancestors", 2]] }, { to: "crown_cracks", w: 1 }] },
        axe_recovered: { h: "The first king's axe returns to its barrow", b: "{person} brought the axe home and the Fellers' leaders to the gallows. The clergy have sealed the barrow with iron.", fx: { stability: 6, prestige: 4 }, end: true },
        dead_freed: { h: "The dead come up out of the cut", b: "From the wound in the trunk, grey figures climbed out by the thousand and walked away into the hills. The old say they looked relieved.", fx: { unrest: 20, discovery: "natural_philosophy" }, end: true },
        crown_cracks: { h: "A branch falls on {realm}", b: "Days after the cut, a bough of the canopy gave way and came down across the north of {realm}. Whole valleys lie buried under leaves and splintered wood.", fx: { pop: 0.85, stability: -15, abandon_town: true }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", points: "library", who: "the Sap Clergy's order of service", text: "Hymn of the Sap Clergy, sung at every anointing in {realm}, as printed in the order of service for {year}: 'The Mother holds the sky on her shoulders and the deep in her fists. Her sap is our blood; her shade is our roof. Give thanks, and do not dig.' The last line was added 200 years ago, the year the Root Watch was founded. The older hymnals kept at {lead} end at roof." },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "a counting game, noted by {investigator}", text: "Counting game of the children of {place}, noted by {investigator} at a harvest fair in {year}: 'Leaf, branch, trunk, root; root, trunk, branch, leaf; down goes Granny, up goes grief.' On 'down goes Granny', the child who is it must crouch and walk in a slow circle with eyes shut. Asked why, the children said that is how the dead walk, and laughed." },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", points: "cast:investigator", who: "{investigator}, ring-reader", text: "Chronicle of the Ring-Readers, summary table, published by {investigator} at {lead} in {year}: the growth-rings of 14 fallen boughs record a thousand good years, then three hundred lean ones, each ring narrower than the last. A gloss for new readers: a ring is one year's growth of the wood, laid down like a page. The last 300 pages are getting thinner." },
    { depth: "core", about: "truth:gnawing", source: "archive", bias: "true", reliable: true, plain: true, who: "{survivor}, Root Watch sergeant", text: "Log of the Root Watch, deep post four, kept by {survivor}, sergeant, night of {year}: 'Heard it again at the turn of the watch. Chewing, slow and patient, a mile below us. There is a wyrm down there coiled round the roots, and it is eating them; the grey on the ridge spreads from where it bites. The root-wall we braced last spring has a new hollow the size of a barn. Requesting 20 more men, and a priest who will listen.'" },
    { depth: "core", about: "truth:gnawing", source: "oral", bias: "garbled", reliable: "partial", who: "a miner's wife, to {investigator}", text: "A miner's wife of {place}, explaining the chewing to {investigator} in {year}: 'The Hungry One was put down there by the first gods to guard the roots. It grew bored, and then it got peckish. That's what my mother told me, and her mother before, and they all lived up on the ridge before the grey came. We moved down in the spring, 40 households, and left the graves.'" },
    { depth: "core", about: "truth:gnawing", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, weaver of the well", text: "Statement of {person}, a weaver of the well, given to {investigator} in {year}; the first words {person} had spoken in 40 years: 'The thread of the world is short now. I have seen what holds the shears. It has no eyes, and it is very large, and it is close.' The weavers' rule is silence for life. {person} was put out of the well that same night and walked down the mountain alone, aged 71." },
    { depth: "core", about: "truth:gnawing", source: "ruin", bias: "true", reliable: true, points: "site:well_of_threads", who: "a shrine carving, found by sappers", text: "Carved in an old shrine deep under the hills near {place}, beside a drawing of a coiled serpent, found by Root Watch sappers in {year}: 'We fed it the blight-wood to slow it. It ate faster. We fed it our sick. It ate faster. We have bricked the door. Whoever opens it, run.' The sappers had opened it. They report a round tunnel nine feet wide, going down toward {lead}." },
    { depth: "core", about: "truth:gnawing", source: "temple", bias: "official", reliable: false, who: "{official}, registrar of the Sap Clergy", text: "Decree of the Sap Clergy, sealed by {official}, registrar, {year}: 'The root-blight is a passing sickness of the bark, cured by prayer and the burning of grey wood. Tales of a beast below the world are forbidden as despair. The Root Watch will report to the clergy, not to the court, and its logs will be kept in the registrar's office. The request for 20 more men is refused.'" },
    { depth: "core", about: "truth:parasite", source: "heretic", bias: "heretic", reliable: "partial", points: "archive", who: "{believer}, speaker of the Fellers", text: "Tract of {believer}, speaker of the Fellers, nailed up in the market of {place}, {year}: 'Why does the crown grow greener after every war? Count the dead. Then count the new leaves. After the river war, 4,000 dead, and the canopy over {realm} so thick it shut out the noon sun. The clergy's own sap-books say so, if you can get at them; they are kept at {lead}.'" },
    { depth: "core", about: "truth:parasite", source: "traveller", bias: "exaggerated", reliable: "partial", cost: true, points: "site:underroots", who: "{person}, miner", text: "{person}, a miner, telling it at the pithead of {place} in {year}: 'There was a grey town down there, and my mother was in it, sweeping a step. Dead six years. My mother told me to go home. The roots ran through every house like veins, and the walls moved, very slowly, like a throat drinking.' {person} went back down the shaft at {lead} the next week to fetch the mother home, and did not come up." },
    { depth: "core", about: "truth:parasite", source: "ruin", bias: "true", reliable: true, plain: true, points: "site:sister_stump", who: "the burned stump's inscription", text: "Inscribed on the burned stump in the desert at {lead}, read by {investigator} in {year} with the help of a desert guide: 'The tree drank our dead. Every funeral fed it, and the dead could not leave. We set it alight so that our dead could go where the dead should go. Forgive us the desert.' Beneath are the burners' names, 212 of them, with their ages." },
    { depth: "core", about: "truth:parasite", source: "archive", bias: "redacted", reliable: "partial", who: "a clergy register", text: "Clergy register of {place}, plague year, page 30, in the hand of a former registrar: 'Sap yield this season: thrice the usual. The Archpriest directs that this not be ... [struck through] ... with the death-rolls.' {investigator}, who found the page in {year}, adds a note: the death-rolls for the same season list 1,900 burials, also thrice the usual." },
    { depth: "core", about: "truth:parasite", source: "library", bias: "official", reliable: false, who: "{official}, registrar of the Sap Clergy", text: "Pastoral letter of the Sap Clergy, read at every funeral in {realm} by order of {official}, {year}: 'The dead are laid in the earth and rest in the Mother's roots, as a child rests in its mother's arms. To speak of feeding is heresy and an insult to every grieving house. Families are asked not to follow the dead down the root-paths, and to pay the burial fee of 3 silver in advance.'" },
    { depth: "core", about: "truth:seed", source: "person", bias: "true", reliable: "partial", points: "site:trunk_city", who: "a hollow pilgrim's journal", text: "Journal of a hollow pilgrim, entry for {year}: 'Climbed in at the crack above the carved halls at {lead}, twelve of us with ropes. The heart of the trunk is gone. A round thing fills it, bigger than a cathedral, and it was warm to the hand. We sang a hymn to keep our courage, and I swear it moved when we sang. Three of us would not come out again.'" },
    { depth: "core", about: "truth:seed", source: "library", bias: "true", reliable: true, plain: true, who: "{investigator}, ring-reader", text: "Note of {investigator}, ring-reader, added to the chronicle in {year}: 'The narrowing rings are not sickness. Every old tree in my orchard does the same in its last years, when it fruits for the final time; it starves its own wood to feed one crop. The Mother is old, and she is making one last seed in her heart. The world is what the seed grows in. When it falls, the shell is thrown away.'" },
    { depth: "core", about: "truth:seed", source: "oral", bias: "garbled", reliable: "partial", points: "site:fallen_branch", who: "a port clerk", text: "Lullaby of the canopy folk, sung by a refugee of the fallen bough in the harbour camp on the stone headland at {lead}, written down by a port clerk in {year}: 'When the Mother bears her child, the cradle will be cracked and thrown away. We are the cradle, my love. We are the cradle.' The clerk asked what it meant. The singer said: the Mother is old and is making one last seed, and nobody keeps the husk once the seed is out." },
    { depth: "core", about: "truth:seed", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, farmer by the far sprout", text: "Petition of {person}, a farmer near the far sprout, to the court of {realm}, {year}: 'The sapling that fell from the crown grows a hand a day. Everything for a league round it is withered: my barley, my orchard of 60 trees, my well, and last week my youngest, who took a fever playing in its shade and did not wake. The clergy call it a blessing and will not let us cut it down.'" },
    { depth: "core", about: "truth:seed", source: "temple", bias: "propaganda", reliable: false, who: "{official}, registrar of the Sap Clergy", text: "Proclamation of the Sap Clergy, sealed by {official}, registrar, {year}: 'The Mother is eternal, and her leaf-fall is only rest. Those who speak of a last fruiting are spreading fear for the Fellers, and will answer for it. The ring-reader {investigator} is forbidden to publish further, and the chronicle's last table is withdrawn from every library in {realm}.'" },
    { depth: "sub", about: "sub:sap_heirs", source: "person", bias: "true", reliable: "partial", who: "a court physician", text: "A court physician of {realm}, writing privately to a colleague in {year}: 'The princes bleed amber because they have drunk sap since the cradle, a thimble a day, nothing more. The eldest refused it at six, spat it at the priest, and has bled red ever since. That is the whole of the scandal. The clergy's registrar has offered me 200 silver to say otherwise in public.'" },
    { depth: "sub", about: "sub:fellers", source: "heretic", bias: "heretic", reliable: "partial", who: "a clergy informer", text: "Cut into a woodsman's door at {place}, as reported by a clergy informer in {year}: ONE TREE, ONE MASTER. ONE AXE, NO MASTERS. The informer adds: 'Above it, an axe-head drawn in charcoal, the shape of the first king's bronze axe. The woodsman has gone. The neighbours say a speaker of the Fellers lodged there three nights.' Informer's fee paid: 4 silver." },
    { depth: "sub", about: "sub:lying_runner", source: "archive", bias: "official", reliable: false, who: "the royal chancery", text: "Finding of the royal chancery of {realm}, {year}: 'The message carried by the skitter was examined and found genuine, by its seal, its ink and its insolence. The court of {realm} cannot accept such an insult unanswered. Three regiments are recalled from the harvest.' A note on the archive copy, in a later hand: the rival court denies sending it, and so did the skitter's handler, before the hanging." },
    { depth: "sub", about: "sub:descending_dead", source: "oral", bias: "true", reliable: true, points: "site:underroots", who: "a farmer, to {investigator}", text: "Said by a farmer of {place} to {investigator} at the yard gate, {year}: 'My father walked past this gate three nights after we buried him, going down the hill with a lantern, single file with eleven others from the parish. He did not look at the house. He never was one for goodbyes. I followed as far as the old mine road to {lead}, and then the lantern went under the ground.'" },
    { depth: "sub", about: "sub:blighted_ridge", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a drover at a cattle fair", text: "A drover's tale of the grey ridge above {place}, told at a cattle fair in {year}: 'The rivers off the ridge run so thick with sap that the fish swim slowly, and you can lift them out by hand. The bears come down to lick the rocks. I lost 30 head that drank from it; they stood still for a day and then lay down. Nobody buys ridge beef now.'" },
    { depth: "site", about: "site:well_of_threads", source: "temple", bias: "pious", reliable: "partial", who: "a novice of the well", text: "The rule of the well, as recited to pilgrims at the pool by a novice of {place}, {year}: 'Three drink from the well and three see the threads. The first sees what was, the second what is, and the third will not say.' The novice adds that the third weaver has not spoken in 40 years, and that a question put to the third weaver costs double, 4 silver, for the silence." },
  ],
};
