// The Hush Below: a silent, timeless sea of souls and feeling lies under every surface of the world, and the
// things that dwell in it trade gifts to mortals. Merges the cosmic "soul-sea and its patron" with the emotion-ocean
// otherworld that leaks power (as its cosmic form).
export default {
  id: "hush_below",
  name: "The Hush Below",
  family: "world",
  kind: "cosmic",
  pitch: "Under the world lies a silent sea, the Hush, made of every soul and feeling that ever existed. A being there gives powers to chosen mortals, and realms light their streets with oil from its whales without asking what the oil is made of.",
  slots: ["cosmology", "monster-source"],
  tone: ["grim", "melancholy"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "grimdark", "flintlock"],
  w: 1,
  excludes: ["sleeper"],
  pairs: [{ id: "unquiet_gate", w: 2.5 }, { id: "thinning", w: 2 }, { id: "drowned_crown", w: 1.5 }, { id: "elder_lattice", w: 1.5 }, { id: "unremembering", w: 1.2 }],

  cast: [
    { role: "investigator", n: "a deep-pilot of the pilots' guild who logs every storm in the Hush", home: "coast", stance: "Wants the storms charted and explained; has begun lining them up against the news." },
    { role: "official", n: "an abbot-inquisitor of the Abbey of Stillness, who wears wax in the ears and runs the silence-engines", home: "capital", stance: "Wants every voice from below silenced; believes even true words from the Hush are bait." },
    { role: "believer", n: "a keeper of the Covenant of the First Rite, who writes down the patron's every word", home: "remote", stance: "Believes the patron is a liberator who has earned its rest, and that a second must be given." },
    { role: "survivor", n: "one of the marked, who escaped an Abbey pyre through a shadow and still hears the patron", home: "border", stance: "Wants the patron let go and the Covenant stopped; trusts the voice more than the Abbey, and fears both." },
  ],

  truths: [
    { id: "made_patron", n: "The patron was one of us", d: "The being who speaks from the Hush was once a mortal youth, cut open on a headland stone by the Covenant of the First Rite, which wanted a voice in the deep. It has been a god for four thousand years and is very tired. It can be freed, replaced or unmade, and the Covenant, which kept the body so the rite could be repeated, has already chosen a new youth for the knife.", tags: ["truth:hush_patron"],
      known: [
        "Now and then someone wakes with a black sign burned into the back of the hand, and gains gifts from a voice in the Hush. The Abbey of Stillness calls the voice a devil of the abyss, uncreated and eternal.",
        "The marked report that the voice talks like a youth who has read every book, and asks what bread tastes like. An Abbey file records a marked one who was told the voice's mortal name. The name is struck out.",
        "Under a black altar on a headland lies a skeleton no older than twenty, ribs opened, bones carved with the Covenant's prayers and instructions for a second rite. The Covenant has bought every field around it.",
        "Confirmed: the patron was a mortal youth, made into a god on the headland stone by the Covenant of the First Rite four thousand years ago. It is tired, and it can be freed or unmade. The Covenant has already chosen the next youth.",
      ] },
    { id: "passions", n: "Feeling makes the gods", d: "The powers of the Hush are born from mortal passion: every war feeds the one of rage, every plague the one of despair, every revel the one of hunger. They have grown large enough to arrange history so that it keeps feeding them; a whole city once paid itself into the Hush to buy their help. The storms in the Hush now fall on the same hours as the battles.", tags: ["truth:hush_passions"],
      known: [
        "Passion-cults worship single feelings as gods and believe their gods are growing. The royal academy calls the passion-gods an allegory of the temperaments. A court diarist notes that every royal mood seems to bring its own disaster.",
        "{investigator}'s log matches all fourteen great storms in the Hush this decade to battles fought at the same hour. A burned cult book says the Red One has learned to keep the wars going.",
        "A grey island of torn-off moments has surfaced off the coast: coronations, weddings and 31 battles, looping without sound. An empty city's last ledger records a bargain with the Hush whose price was all of us.",
        "Confirmed: the powers of the Hush are born from mortal feeling, and have grown large enough to arrange history so it keeps feeding them. Every war feeds the one of rage, and the storms in the Hush now fall on the hours of battle.",
      ] },
    { id: "sea_of_dead", n: "The Hush is where the dead go", d: "The silent sea is the afterlife. Every gift drawn from it, every rune and charm and lamp of whale-oil, is a little of a dead soul spent; the soul-whales are full of the dead, and the rendering yards boil 300 of them a year. The dead have begun to notice what is being taken from them, and they are asking for it back in the wells.", tags: ["truth:hush_dead"],
      known: [
        "The streets of the realm burn blue whale-oil, and the rendering yards are the richest places in it. In some country the dead are heard in still wells at night, asking for things back. The temples say the Hush is empty.",
        "Bonecarvers say every charm they cut speaks with somebody's voice, and the luck in it is somebody's luck. At the whalebone strand, every rib hums with a different crowd of voices.",
        "Inside the largest whale skull on the strand is a chamber of rings, combs and coins that nobody buried there. One ring carries a name from a parish burial roll. Lamplighters report the blue lamps whispering.",
        "Confirmed: the Hush is where the dead go. The soul-whales are full of them, and every charm and lamp spends a little of a dead soul. The yards boil 300 whales a year, and the dead have started asking for their things back.",
      ] },
  ],

  tags: ["hush"],

  subthemes: [
    { id: "lamp_oil", n: "The Lamp-Oil Trade", d: "The realm's streets, engines and lighthouses burn oil rendered from the great soul-whales of the outer sea. The oil burns blue and silent, and the rendering yards are the richest places in the realm.", w: 1.5, req: { any: ["has:port", "seafaring", "mercantile"] }, mods: [["navy", 1.5], ["gov:merchant", 2]], truthLink: "sea_of_dead", tags: ["theme:lamp_oil"], mark: { kind: "zone", n: "The Rendering Coast", color: "#3c5a78", size: [1, 3], where: "coast" } },
    { id: "the_marked", n: "The Marked", d: "Now and then the patron chooses someone and burns a sign into the back of their hand. The marked can step through shadows and stop a heart from across a room, and almost none of them die in bed.", w: 1.4, truthLink: "made_patron", tags: ["theme:marked"] },
    { id: "abbey_stillness", n: "The Abbey of Stillness", d: "An inquisitorial order that hunts the marked, the witches and the heretics, carrying humming engines that drown out the Hush in a ring around them. Its abbots wear wax in their ears and do not take it out.", w: 1.3, req: { any: ["zealous", "organised", "gov:theocracy", "militant"] }, tags: ["theme:abbey"] },
    { id: "bonecharms", n: "The Bonecharm Market", d: "Carved trinkets of whale-bone, each humming faintly with a borrowed knack: a lucky hand, a quiet step, a few more years. Bonecarving witches sell them in back rooms; the Abbey burns them in the square.", w: 1.2, req: { any: ["urbane", "mercantile", "has:city", "faith:spirits"] }, truthLink: "sea_of_dead", tags: ["theme:bonecharms"] },
    { id: "silent_wing", n: "The Silent Wing", d: "A cathedral wing where no sound carries: a dropped bell makes no noise, and prayers spoken there are answered in a voice no one else hears. The bishop has bricked up the doors twice.", w: 0.9, req: { any: ["pious", "organised", "lavish"] }, truthLink: "made_patron", tags: ["theme:silent_wing"] },
    { id: "passion_cults", n: "The Passion-Cults", d: "Secret fellowships that worship a single feeling as a god, feeding it with riots, duels or ecstasies. Each cult believes its god is growing. Each is correct.", w: 1.1, req: { any: ["urbane", "unstable", "faith:void", "mystic"] }, truthLink: "passions", tags: ["theme:passion_cults"] },
    { id: "lamp_throne", n: "The Lamp-Throne", d: "An ancient ruler, kept half-alive on a throne of brass and pipes, whose mind shines like a beacon in the Hush. The pilots who steer ships through the Hush navigate by it, and they have noticed it dimming.", w: 0.6, req: { any: ["gov:empire", "autocracy", "realm:vast", "realm:large"] }, truthLink: "passions", tags: ["theme:lamp_throne"] },
    { id: "deep_storms", n: "The Deep-Storms", d: "Tempests in the Hush that cut a province off from its dreams and its prayers. Inside one, nobody can sleep, no charm works, and anyone who prays hears a voice praying back.", w: 0.8, truthLink: "passions", tags: ["theme:deep_storms"], mark: { kind: "zone", n: "A deep-storm", color: "#4a3a5a", size: [2, 4], where: "remote" } },
    { id: "null_born", n: "The Null-Born", d: "Children the Hush cannot touch: charms die in their hands and the marked cannot see them. The Abbey buys them from their parents; the cults pay more.", w: 0.8, tags: ["theme:null_born"] },
    { id: "vanished_traders", n: "The People Who Bargained", d: "A whole people, remembered in old maps and border-stones, emptied out in a single night. Their last ledgers record a bargain with the Hush, and the price was 'all of us'.", w: 0.8, req: { any: ["near:ruins", "scholarly", "ancestor_bound"] }, truthLink: "passions", tags: ["theme:vanished_traders"] },
    { id: "first_rite", n: "The Covenant of the First Rite", d: "The cult that made the patron never died out. It keeps the old altar, records the patron's every word, and has been choosing a new youth for the knife.", w: 0.9, req: { any: ["sacrifice", "faith:void", "insular", "seers"] }, truthLink: "made_patron", tags: ["theme:first_rite"] },
    { id: "dead_speak", n: "Voices in Still Water", d: "In this country, the dead are heard in still ponds and wells at night, asking for things back: a name, a ring, a year. People cover their wells and leave the lids weighted.", w: 1, req: { any: ["ancestor_bound", "faith:ancestors", "river", "marsh"] }, truthLink: "sea_of_dead", tags: ["theme:dead_speak"] },
  ],

  sites: [
    { id: "rite_altar", n: "The Altar of $", kind: "shrine", where: "remote", truthLink: "made_patron", d: "A flat stone on a headland, stained black, where nothing makes a sound.",
      layers: {
        surface: { n: "Where the wind stops", text: "A flat stone on a headland near {place} is stained black, and nothing near it makes a sound. Shepherds will not graze their flocks there; the wind stops at its edge. The Covenant has bought every field around it in the last three years." },
        study: { n: "The carvings", text: "Its carvings show a youth laid on the stone inside a ring of thirteen hooded figures, and above them the same sign the marked bear burned on their hands. {investigator} took a rubbing, and the paper came away cold." },
        dig: { n: "The opened skeleton", text: "Under the altar lies a skeleton no older than twenty, ribs opened, every bone carved with prayers in the Covenant's hand. The prayers end with instructions for a second rite. The Covenant's own copy is kept by its keeper at {lead}.", points: "cast:believer" },
        revelation: { n: "Made from a person", text: "The patron was made here from a youth of this country, and the body was kept so the rite could be repeated. The Covenant of the First Rite has kept the stone for four thousand years. It has chosen the next youth, and bought the fields so that nobody will hear." },
      } },
    { id: "whale_graveyard", n: "The Whalebone Strand at $", kind: "anomaly", where: "coast", truthLink: "sea_of_dead", d: "A beach where the soul-whales come to die, piled with ribs the size of chapels.",
      layers: {
        surface: { n: "Chapel ribs", text: "A shore near {place} is piled with soul-whale bones, ribs the size of chapels. Bonecarvers have scavenged it for centuries and pay the lord of the strand a silver a cartload. Gulls will not land on the bones." },
        study: { n: "Many voices", text: "The bones hum when touched, and each whale's hum is different, like voices in a crowd. {investigator} pressed an ear to twenty ribs in a row and counted the voices in each. The larger whales held more." },
        dig: { n: "The grave-goods", text: "Inside the largest skull is a chamber packed with small grave-goods, rings, combs and coins, though nobody has ever buried anything there. One ring is engraved with a name that appears in the burial rolls at {lead}.", points: "archive" },
        revelation: { n: "Full of the dead", text: "The whales swim in the Hush as much as in the sea, and what fills them is not oil but the dead. The trinkets are what the dead were holding. The rendering yards boil 300 whales a year, and every blue lamp in the capital burns somebody's parent." },
      } },
    { id: "silent_cathedral", n: "The Silent Wing of $", kind: "anomaly", where: "capital", d: "A walled-off wing of a great cathedral where sound simply stops.",
      layers: {
        surface: { n: "Closed for repairs", text: "A wing of the great cathedral of {place} has been closed for repairs for 150 years. The repair fund still collects a copper from every worshipper on feast days. Nobody has ever seen a mason go in." },
        study: { n: "Sound stops", text: "Inside, sound dies a pace from its source. A bell that {investigator} dropped on the flagstones made no noise at all. The floor is still and cold as deep water, and the candles burn without a flicker." },
        dig: { n: "Water under the crypt", text: "Under the flagstones the crypt opens not onto earth but onto dark, motionless water that no lamp can light. A bishop's bench stands at the edge, worn smooth by kneeling. The bishops' private letters are kept at {lead}.", points: "temple" },
        revelation: { n: "Built over the breach", text: "The cathedral was built over a breach on purpose, so the bishops could hear the patron's answers to their prayers. Six bishops prayed here and took its advice, and two of them bricked it up. The Abbey of Stillness holds the key, and its abbots come here alone at night." },
      } },
    { id: "drift_isle", n: "The Drifting Isle of $", kind: "anomaly", where: "remote", truthLink: "passions", d: "An island seen in dreams for generations, which has now been sighted from the shore.",
      layers: {
        surface: { n: "The dreamed island", text: "Everyone along the coast near {place} has dreamed of the same grey island. Last spring fishermen sighted it from the shore, three miles out, and the harbour master logged it. Nobody has rowed out to it twice." },
        study: { n: "Torn places", text: "The isle is a heap of places torn from elsewhere: a stair, a market, half a palace, a burning street, all silent. {investigator} mapped forty of them and matched twelve to scenes in the history books." },
        dig: { n: "Moments that loop", text: "Each fragment is a moment of great feeling, preserved: a coronation, a massacre, a wedding, a hanging, each looping without sound. The massacre is the one at {place}, which the court chronicle in {lead} calls a victory.", points: "library" },
        revelation: { n: "The storehouse", text: "The powers of the Hush collect the moments of strong feeling that fed them, and the isle is their storehouse. It has grown so full that it has surfaced. Of the forty moments on it, 31 are battles, and nine of those were fought in the last ten years." },
      } },
    { id: "last_gate", n: "The Last Gate of $", kind: "ruin", where: "mountain", truthLink: "passions", d: "A great arch in an empty city, its far side opening onto dark water.",
      layers: {
        surface: { n: "Tables still set", text: "An empty city stands in the hills near {place}, its houses furnished and its tables set, the bread long turned to dust. Looters take the silver and leave the rest. None of them stays the night." },
        study: { n: "The ledgers", text: "The city's ledgers record debts to a creditor never named, rising each year, paid in years of life: a decade from an old man, a year from a child. {investigator} added the columns. The debt grew faster than any city could pay." },
        dig: { n: "All of us", text: "At the city's heart an arch of black stone stands over dark water. The last ledger lies at its foot: one entry, 'all of us', and a signature for every citizen, 6,212 names. The passion-cults at {lead} pay well for copies.", points: "sub:passion_cults" },
        revelation: { n: "Still being delivered", text: "The vanished people did not die. They paid themselves into the Hush for the power to win one war, and the powers took the whole city as the price. The war they paid to win has never quite stopped, and the passion-cults sell copies of their ledger as scripture." },
      } },
  ],

  beings: [
    { id: "soul_whale", n: "Hush-whale", kind: "marine", d: "A vast pale whale that swims half in the sea and half in the silence below it. Its song can be heard through a ship's hull; sailors who hear it weep without knowing why.", danger: 1, biomes: ["open", "abyss", "polar"], look: { size: 34, group: [1, 4], move: "pod", speed: 9, col: "#c8d0d8", col2: "#3a4a6a", body: "whale", active: "any", visible: true } },
    { id: "passion_spawn", n: "Passion-spawn", kind: "beast", d: "A creature that rises where one feeling has run high for too long: a rage-thing on old battlefields, a grief-thing in plague towns. It wears the shape of what was felt there.", danger: 3, biomes: ["grass", "tempforest", "badlands", "swamp", "dryforest"], look: { size: 2.4, group: [1, 2], move: "solo", speed: 10, col: "#6a2a3a", col2: "#2a1a2a", body: "biped", active: "night", visible: true } },
    { id: "still_hound", n: "Still-hound", kind: "predator", d: "A grey hound from the Hush that hunts by silence: birds stop singing where the pack is near. It follows the marked as crows follow an army.", danger: 2, biomes: ["tempforest", "boreal", "coldsteppe", "temprain", "grass"], look: { size: 1.3, group: [3, 7], move: "pack", speed: 13, col: "#7a7a80", col2: "#2a2a32", body: "quad", active: "night", visible: true } },
    { id: "drowned_choir", n: "Well-voices", kind: "beast", d: "The dead, heard in still water, rising as faint shapes on windless nights to ask for what was taken. They are rarely dangerous, unless someone has their ring.", danger: 1, biomes: ["swamp", "temprain", "tempforest", "river"], look: { size: 1.7, group: [1, 6], move: "solo", speed: 2, col: "#a8b8c0", col2: "#5a6a7a", body: "biped", active: "night", visible: false } },
  ],

  techs: [
    { id: "hb_bonecarving", n: "Bonecarving", field: "arcana", level: 1, d: "Charms carved from soul-whale bone, each holding a small borrowed knack." },
    { id: "hb_rendering", n: "Whale-oil rendering", field: "alchemy", level: 2, d: "Soul-whale blubber boiled into a blue oil that burns silent and twice as long as tallow." },
    { id: "hb_deep_charts", n: "Deep-charts", field: "navigation", level: 3, d: "Charts of the currents of the Hush, steered by trance-pilots who follow a beacon of thought." },
    { id: "hb_null_wards", n: "Null-wards", field: "arcana", level: 3, d: "Rings and collars made from the blood of the null-born, which nothing from the Hush can cross." },
    { id: "hb_silence_engine", n: "The silence-engine", field: "engineering", level: 4, d: "A humming brass device, powered by whale-oil, that drowns out the Hush in a ring around it and strips the marked of their gifts." },
    { id: "hb_lamp_throne", n: "The lamp-throne", field: "arcana", level: 5, d: "A throne of pipes that keeps a dying mind burning in the Hush for centuries, so the realm's pilots can find their way home." },
  ],

  units: [
    { id: "hb_abbey_guard", n: "Abbey silencers", role: "infantry", wpn: "sword", kit: "mail", ranks: 3, gap: 1.6, size: 60, w: 0.5, mods: [["theme:abbey", 8], ["gov:theocracy", 2]] },
    { id: "hb_marked_blades", n: "Marked assassins", role: "magic", wpn: "sword", kit: "light", ranks: 1, gap: 4, size: 10, w: 0.2, mods: [["theme:marked", 12]] },
  ],

  faiths: [
    { id: "hb_abbey", n: "The Abbey Faith", d: "A stern church that teaches that the silence below is the abyss of the damned and that every voice from it is a lie. Its engines hum in every chapel.", tags: ["faith:hb_abbey", "organised"], w: 0.5, mods: [["zealous", 2], ["hierarchical", 1.5]],
      names: ["The Abbey of Stillness", "The Holy Silence of $", "The Sealed Ear"] },
    { id: "hb_patron", n: "The Patron's Covenant", d: "A hidden faith that honours the voice in the Hush as a liberator and keeps its marked as saints.", tags: ["faith:hb_patron", "sinister"], w: 0.3, mods: [["seers", 2], ["mystic", 2], ["sacrifice", 2]],
      names: ["The Covenant of the First Rite", "The Marked of $", "The Quiet Choir"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Still waters", color: "#5a6a80", size: [1, 2], count: [1, 3], where: "any", d: "Breach-lands where the Hush lies close: windless, soundless, the lakes like black glass." },
  ],

  storylines: [
    { id: "hb_marked_one", n: "The Mark of {person}", scale: "local", anchor: "town", w: 1.5, req: "hush",
      stages: {
        start: { h: "A servant of {place} wakes with a burned hand", b: "{person}, a scullion in a merchant's house in {place}, woke with a black sign seared into the back of the hand and the sound of the sea in the ears.", wait: [1, 4], next: [{ to: "gifts", w: 2 }, { to: "abbey_comes", w: 1, mods: [["theme:abbey", 3], ["zealous", 2]] }] },
        gifts: { h: "Strange deaths among the masters of {place}", b: "A cruel magistrate, a bailiff and a moneylender of {place} have died behind locked doors. {person} is seen in the market, calm, unafraid, unhurried.", wait: [3, 8], fx: { unrest: 10, flag: "marked" }, next: [{ to: "abbey_comes", w: 1.5 }, { to: "uprising", w: 1, mods: [["poor", 2], ["unstable", 2]] }, { to: "patron_speaks", w: 0.8, mods: [["seers", 2], ["mystic", 2]] }] },
        abbey_comes: { h: "The Abbey of Stillness arrives in {place}", b: "Silencers have set up their humming engine in the square of {place} and are inspecting every hand. {person} has not been seen since.", wait: [2, 5], fx: { stability: 2, unrest: 6 }, next: [{ to: "burned", w: 1.5 }, { to: "escapes", w: 1 }] },
        burned: { h: "The marked of {place} burned in the square", b: "{person} was found in a cellar and burned beside the engine. The silencers say the patron did not come to save its chosen. They are right; it never does.", fx: { unrest: 8, stability: -2 }, end: true },
        escapes: { h: "{person} vanishes through a shadow", b: "With the engine humming not twenty paces away, {person} stepped into the shade of a well and was gone. The abbots have doubled the bounty.", fx: { unrest: 5 }, end: true },
        uprising: { h: "{place} rises behind the marked", b: "The poor of {place} have barricaded the streets in the name of {person}, who they say cannot be killed. The garrison has withdrawn to the keep.", fx: { revolt: true, unrest: 20, stability: -8 }, end: true },
        patron_speaks: { h: "{person} returns from the silence with a message", b: "{person} has told the people of {place} what the patron said in the dark: that it was once a child of this country, and that it would like, very much, to die.", fx: { stability: -4, flag: "patron_message" }, end: true },
      } },
    { id: "hb_oil_boom", n: "The Blue Lamps of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["hush", { any: ["has:port", "seafaring", "mercantile"] }],
      stages: {
        start: { h: "{realm} lights its streets with whale-oil", b: "The rendering yards of {realm} cannot boil the soul-whales fast enough. Blue lamps burn silent in {capital}, and the whalers are richer than lords.", wait: [4, 10], fx: { treasury: 60, growth: 0.002 }, next: [{ to: "voices", w: 2 }, { to: "whales_vanish", w: 1 }] },
        voices: { h: "The lamps of {capital} begin to whisper", b: "Lamplighters of {capital} report that the blue lamps murmur in the small hours. {person}, a lamplighter's widow, swears one of them spoke in the dead husband's voice.", wait: [3, 8], fx: { unrest: 8 }, next: [{ to: "lamps_banned", w: 1, mods: [["pious", 2], ["ruler:pious", 3]] }, { to: "kept_burning", w: 1.5 }, { to: "dead_rise", w: 0.7, mods: [["theme:dead_speak", 3]] }] },
        whales_vanish: { h: "The soul-whales leave the coasts of {realm}", b: "The whaling fleets of {realm} have come home empty for two seasons. The great whales have gone into deeper water, and the lamps of {capital} are going out one by one.", fx: { treasury: -60, stability: -5 }, end: true },
        lamps_banned: { h: "{ruler} snuffs the blue lamps", b: "By decree, every whale-oil lamp in {realm} is to be put out and the rendering yards closed. The whalers are ruined; the city is dark and, for the first time in years, quiet.", fx: { treasury: -40, stability: 4, unrest: 6 }, end: true },
        kept_burning: { h: "{realm} burns on regardless", b: "The council of {realm} has ruled the whispers a nervous fancy. The yards work day and night, and {person} has been confined to an asylum, for the widow's own good.", fx: { treasury: 30, unrest: 5, flag: "oil_kept" }, end: true },
        dead_rise: { h: "The dead walk out of the lamps of {capital}", b: "On the longest night, the blue flames of {capital} guttered and pale shapes stood up in every lit room, asking for their names. The city emptied before morning.", fx: { pop: 0.9, unrest: 25, stability: -12 }, end: true },
      } },
    { id: "hb_second_rite", n: "The Second Rite", scale: "realm", anchor: "realm", w: 0.8, req: ["hush", { any: ["theme:first_rite", "seers", "sacrifice", "faith:hb_patron", "insular"] }],
      stages: {
        start: { h: "Hooded pilgrims gather in {realm}", b: "Members of an old covenant are buying up land around a stone on a headland in {realm}. {person}, a young novice, has been chosen for an honour no one will name.", wait: [3, 8], next: [{ to: "rite_done", w: 1.5 }, { to: "novice_flees", w: 1 }, { to: "abbey_raid", w: 1, mods: [["theme:abbey", 3], ["zealous", 2]] }] },
        novice_flees: { h: "The chosen of {realm} flees the covenant", b: "{person} ran from the headland the night before the rite and has asked {ruler} for protection, bringing the covenant's books and their account of how a god is made.", fx: { science: { arcana: 0.5 }, prestige: 3 }, end: true },
        abbey_raid: { h: "The Abbey breaks the covenant of {realm}", b: "Silencers stormed the headland before the rite. The cultists were taken and the altar broken in three, though the pieces still make no sound.", fx: { stability: 3, unrest: 4 }, end: true },
        rite_done: { h: "A second voice speaks from the silence", b: "The rite was done. Now two voices answer from the Hush, and the marked of {realm} report that the old one has fallen silent, or is listening.", wait: [6, 14], fx: { flag: "second_patron", unrest: 6 }, next: [{ to: "new_patron", w: 1 }, { to: "old_patron_freed", w: 1 }] },
        new_patron: { h: "The new patron chooses its first marked", b: "Twelve people across {realm} woke with burned hands on the same night. The new voice is young, eager, and has opinions about who should rule.", fx: { unrest: 15, stability: -6 }, end: true },
        old_patron_freed: { h: "The old patron is gone", b: "The marked of {realm} feel their gifts fading. The old voice has gone, and those who dreamed of it last describe a child walking, at last, down to a grey shore.", fx: { stability: 2, flag: "patron_freed" }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "a natural history primer", text: "Natural history primer for the schools of {realm}, chapter 9, {year}: 'The silence felt in certain lakes and forests is an effect of still air and soft ground. Superstitious folk call it the Hush, and say a sea of souls lies under every surface of the world. Pupils should note that a bell rung in such places is merely quieter, not silent. Pupils should not test this.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "a well-digger, to an apprentice", text: "A well-digger of {place}, to an apprentice, {year}: 'Past sixty feet the bucket comes up empty and cold as a cellar. {person} lay at the shaft mouth one night to listen. By morning {person} was chatting to a brother eleven years drowned. We capped that well and weighted the lid. Nobody puts an ear to a well in this valley. That's the whole of the trade.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "{investigator}, deep-pilot", text: "{investigator}, deep-pilot, in a dockside inn at {place}, {year}, to a ship's boy on a first voyage: 'You don't sail the Hush. You hold your breath and fall through it, and you steer by the one light in all that dark, the lamp-throne, and you pray it's still lit. Six days through and six back. Bring wax for your ears, and don't answer anyone who calls your name.'" },
    { depth: "core", about: "truth:made_patron", source: "ruin", bias: "true", reliable: true, plain: true, who: "the altar's underside, read by {investigator}", text: "Carved on the altar's underside in the Covenant's old tongue, read by {investigator} by lantern in {year}: 'Here we cut open our child so the deep might have a mouth. We gave it our child so that it would love us. It speaks now, and will speak for as long as the sea is silent. When it tires, we will give it a second.' Beside the words is the sign the marked bear on their hands." },
    { depth: "core", about: "truth:made_patron", source: "person", bias: "true", reliable: "partial", points: "archive", who: "{survivor}, one of the marked", text: "Testimony of {survivor}, one of the marked, before the Abbey's court at {place}, {year}, as recorded by the court clerk: 'It talks like a youth who has read every book. It asked me what bread tastes like now. It asked me twice. It said it was born in a fishing village on this coast, and that it is very tired.' The prisoner left through a shadow that evening. The full transcript is kept at {lead}." },
    { depth: "core", about: "truth:made_patron", source: "heretic", bias: "heretic", reliable: "partial", points: "site:rite_altar", who: "a shepherd in the gorse", text: "Hymn of the Covenant of the First Rite, sung by {believer} and twelve others at the headland of {lead} on the longest night of {year}, overheard by a shepherd hiding in the gorse: 'The first was made; the first grows weary; the first shall be unmade, and a second given.' The shepherd says the singers then read out a name and a village, and the village was the shepherd's own." },
    { depth: "core", about: "truth:made_patron", source: "temple", bias: "official", reliable: false, who: "{official}, abbot-inquisitor", text: "Ruling of the Abbey of Stillness, sealed by {official}, abbot-inquisitor, {year}: 'The so-called patron is a devil of the abyss, eternal and uncreated, and no mortal hand had any part in its making. To suggest otherwise is heresy, punishable by the engine. Bones found under any altar are to be reburied without examination, at the Abbey's expense of 4 silver.'" },
    { depth: "core", about: "truth:made_patron", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "an Abbey case file", text: "Abbey case file, {place}, {year}, in the hand of {official}: 'Subject {person}, marked, claims the voice gave its mortal name and the name of its village. Name recorded as [struck out]. Subject to be silenced. Name not to be repeated in chapel.' A second note, a week later: 'Subject {person} silenced. The engine was run for nine hours. Subject no longer speaks at all.'" },
    { depth: "core", about: "truth:passions", source: "heretic", bias: "true", reliable: true, plain: true, points: "temple", who: "a burned book of the Passion-Cults", text: "Page saved from a burned book of the Passion-Cults, found in the Abbey's evidence room at {lead} and copied by {investigator} in {year}: 'Every war waters the Red One. Every plague waters the Grey. They grew from what we felt, and now they are big enough to choose what we feel next. The Red One has learned which kings to whisper to, so that the wars never quite end.'" },
    { depth: "core", about: "truth:passions", source: "archive", bias: "garbled", reliable: "partial", points: "archive", who: "{investigator}, deep-pilot", text: "Log of {investigator}, deep-pilot, {year}: 'Storm in the Hush, worst in thirty years. Lost the beacon for nine hours. Three days after, news came of the battle at {place}. Same hour. I have checked my logs back ten years. Same hour as every great storm this decade, all 14 of them. The guild's storm book is kept at {lead}. Somebody should read it beside a chronicle.'" },
    { depth: "core", about: "truth:passions", source: "person", bias: "exaggerated", reliable: "partial", points: "archive", who: "a court diarist", text: "Private diary of a court diarist of {realm}, {year}, now held at {lead}: 'The old queen grieved for nine years and the plague came twice. The new king rages at breakfast, and by supper we are at war again. When the king laughed at the midsummer revel, the city held a riot of dancing that killed 14. I begin to think we are being fed upon, and the court is the trough.'" },
    { depth: "core", about: "truth:passions", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, pikeman", text: "Letter of {person}, a pikeman, to family, written the night after the battle at {place}, {year}: 'Nobody could stop. The captain ordered the halt three times. We kept killing after the trumpets, and none of us can say why; it was like being drunk on someone else's wine. I killed a boy with his hands up. They are hanging eleven of us for the prisoners tomorrow, and I am one.'" },
    { depth: "core", about: "truth:passions", source: "library", bias: "official", reliable: false, points: "library", who: "the royal academy", text: "Lecture of the royal academy of {realm}, {year}, as printed: 'The so-called passion-gods are a crude allegory of the four temperaments, popular with poets and players, and have no existence outside the stage.' Printed note: the academy regrets that its lecture hall at {lead} was wrecked during the reading by a crowd of 200, which it is confident was a coincidence." },
    { depth: "core", about: "truth:sea_of_dead", source: "oral", bias: "garbled", reliable: "partial", who: "a lamplighter's child, to {investigator}", text: "A lamplighter's child of {place}, telling {investigator} at a wake in {year} why no blue lamp was lit: 'Grandfather said when he died he'd go down to the quiet sea, and we must never burn a blue lamp at his wake, or we'd be burning him. So we've got tallow, five candles at a copper each. It smokes. Grandfather would have laughed at the smoke.'" },
    { depth: "core", about: "truth:sea_of_dead", source: "person", bias: "true", reliable: true, plain: true, who: "{person}, bonecarver", text: "Confession of {person}, bonecarver of {place}, to an Abbey priest, {year}, taken down word for word: 'Every charm I cut, I hear someone. Old men, children. The whales are full of the dead. The Hush is where everybody goes, and we boil them for lamp-oil. The luck in a charm is somebody's luck, and they want it back. Thirty years I've cut charms. I want to stop.'" },
    { depth: "core", about: "truth:sea_of_dead", source: "temple", bias: "official", reliable: false, who: "the high temple of {deity}", text: "Sermon set for every parish by the high temple of {deity}, {year}: 'The souls of the faithful ascend to {deity} on the day of their death. The silence beneath the world is empty, and nothing that dwells there was ever human. Whispering from lamps is a fault of the wick. The parish lamp-oil subsidy of 2 silver a household continues.'" },
    { depth: "core", about: "truth:sea_of_dead", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:whale_graveyard", who: "a bone-carter", text: "A carter who hauls bone off the whalebone strand at {lead}, telling it at the carvers' yard gate in {year}: 'I put my ear to a rib and heard a crowd, all speaking at once, all asking for things they had lost: a ring, a comb, a dog's name. One asked for a bowl of plums. I bought a bowl of plums in the village for 3 coppers and left it on the sand. In the morning that rib was quiet.'" },
    { depth: "core", about: "truth:sea_of_dead", source: "person", bias: "true", reliable: "partial", cost: true, who: "an asylum register", text: "Register of the asylum at {place}, {year}: '{person}, spouse of a lamplighter, admitted by order of the council. Claims the blue lamp in the kitchen speaks in the dead lamplighter's voice and asks for the wedding ring back. The ring was buried with the deceased. Patient refuses to light any lamp and sits in the dark. Fee paid by the rendering yard, 30 silver a year.'" },
    { depth: "sub", about: "sub:lamp_oil", source: "library", bias: "propaganda", reliable: false, who: "the Rendering Guild", text: "Pamphlet of the Rendering Guild of {realm}, {year}, given free at every lamp-shop: 'The whale-oil trade is the light and life of {realm}. The great whales are inexhaustible, insensible to pain and given to us by providence. Last year the yards rendered 300 whales and lit 40,000 lamps. Ignore the whispering; it is the wick.'" },
    { depth: "sub", about: "sub:abbey_stillness", source: "temple", bias: "pious", reliable: "partial", points: "cast:official", who: "{official}, abbot-inquisitor", text: "Rule of the Abbey of Stillness, chapter one, as taught by {official} to novices at the mother house of {lead}: 'Stop the ear. Mind the engine. Anything that speaks from below speaks to deceive, even when it tells the truth; especially then.' Novices are given two plugs of beeswax on the first day and told to replace them every seven days. The rule says nothing about removing them." },
    { depth: "sub", about: "sub:the_marked", source: "person", bias: "true", reliable: "partial", who: "a cell wall", text: "Scratched on the wall of cell 4 of the Abbey prison at {place}, {year}, signed with the sign of the marked: 'It gave me a gift and asked for nothing. That was how I knew to be afraid. I have stopped three hearts with it. All three deserved it. I am waiting for the price.' The cell was empty when the guards opened it, and the door was still locked." },
    { depth: "sub", about: "sub:null_born", source: "oral", bias: "garbled", reliable: "partial", points: "temple", who: "a midwife, reported to the Abbey", text: "Advice given by a village midwife of {place} to a new mother, as reported to the Abbey in {year}: 'If the baby makes the charms go cold, sell it to the Abbey house at {lead} and buy a new roof; they pay 20 silver. If the cultists come with more, sell it to them and move far away. Don't keep it. The marked can't see it, and neither can anything else down there.'" },
    { depth: "sub", about: "sub:lamp_throne", source: "archive", bias: "redacted", reliable: true, who: "pilots' guild minutes", text: "Minutes of the pilots' guild of {place}, {year}: 'The beacon is fainter again this year, by a sixth. The court physicians [...]. Motion to begin preparing a successor for the lamp-throne: carried, eleven to two. Motion to ask the successor first: defeated, eleven to two.' The minutes record that {investigator} voted with the two both times." },
    { depth: "sub", about: "sub:vanished_traders", source: "ruin", bias: "true", reliable: true, points: "site:last_gate", who: "the last ledger, copied by {investigator}", text: "The last line of the last ledger of the empty city, as copied by {investigator} in {year}: 'Price agreed: all of us. Delivery: on the first still night.' Above it are 6,212 signatures, each in a different hand, including children's marks. The ledger lies at the foot of the black arch at {lead}, and nobody has dared to move it." },
    { depth: "site", about: "site:silent_cathedral", source: "archive", bias: "redacted", reliable: "partial", who: "a bishop's private letter", text: "Private letter of a bishop of {place} to a brother bishop, {year}: 'I prayed in the closed wing again. It answered again, in a young voice. It knew my mother's name, and the name of the dog we had when I was six. It advised me on the vote in council, and it was right. Brick it up. Do not let me back in.'" },
    { depth: "site", about: "site:drift_isle", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a fisherman, to the harbour master", text: "A fisherman of {place}, who rowed out to the grey island in {year}, telling it to the harbour master: 'I walked through a wedding, a beheading and a fire, one after another, and not one of them made a sound. The beheading was the one at the old castle, in my great-uncle's time; I knew the headsman's hood. I counted 40 such places. I won't be rowing out twice.'" },
  ],
};
