// The Last Kindling: every good thing in the world is warmed by a first flame that is guttering out. It can be fed with
// great souls, or allowed to die. Merges the dying-flame cycle with the "kindled age" (an imposed order that locked death out).
export default {
  id: "last_kindling",
  name: "The Last Kindling",
  family: "world",
  kind: "cosmic",
  pitch: "All warmth in the world comes from a first flame, and it is going out. Each age a great person is burned to rekindle it, each rekindling lasts less long, and some of the dead have started coming back.",
  slots: ["cosmology", "apocalypse", "time"],
  tone: ["melancholy", "grim"],
  era: ["bronze", "medieval", "renaissance"],
  scale: "world",
  genres: ["fantasy", "grimdark", "mythic"],
  w: 1,
  excludes: ["pale_visitor"],
  pairs: [{ id: "unquiet_gate", w: 3 }, { id: "long_dark", w: 2.5 }, { id: "wheel_of_suns", w: 2 }, { id: "gods_twilight", w: 1.5 }, { id: "elder_lattice", w: 1.2 }],

  truths: [
    { id: "gods_age", n: "The fire is the gods' age, not ours", d: "The flame is not the natural order of the world. The fire-lords lit it to make an age for themselves, and every linking (burning a soul to feed the flame) makes their age last a little longer. The dark the keepers fear is only the age of mortals, waiting to begin, and every hero burned postpones it.", tags: ["truth:kindling_gods_age"],
      known: [
        "A canyon in the mountains shows nine cities stacked one on another, each greyer than the last. The lowest has no hearths at all. Nobody has explained how people lived there without the flame.",
        "{investigator} has copied a carving from the lowest city: people living under a grey sky, and tall figures carrying a torch up a hill. The Night Patient say the torch-bearers were the fire-lords. The keepers say the carving is a forgery.",
        "The founder's tomb holds a clay effigy and no body, and its inscription was recut. Several sources now say the fire-lords lit the flame for themselves, and that people were warm enough before it.",
        "Confirmed: there was an age before the fire. The fire-lords lit the flame to make an age of their own, and each linking burns a person to keep it going. The dark is only the age of mortals, and every linking postpones it.",
      ] },
    { id: "real_dark", n: "The dark is truly the end", d: "When the flame dies, nothing follows: no age of mortals, no rest, only cold. Each linking buys fewer years than the last, four hundred, then two hundred and ten, then ninety. The keepers ran out of great souls long ago and now burn prisoners and debtors by the hundred, and the arithmetic says the next linking will need a town.", tags: ["truth:kindling_real_dark"],
      known: [
        "The sun is weaker every decade. The court astronomers blame high dust; the keepers say each linking renews the flame in full. Border shrines on the ember roads have gone dark, and nobody official will say why.",
        "The dark border shrines went out one by one, moving inward toward the Kiln. {official}'s order to 'move the shrine in another mile' suggests the keepers know the warm lands are shrinking.",
        "A keeper's tally gives the years bought by each linking: 400, 210, 90. A later order lets the Kiln accept common souls 'in number'. A debtors' prison has sent 196 people to the Kiln.",
        "Confirmed: the flame is dying whatever is burned, and beyond it there is only cold. The keepers have known for centuries. They now burn the poor by the hundred to buy a few decades at a time.",
      ] },
    { id: "death_sealed", n: "Death was locked out of the flame", d: "The first keeper bound death outside the fire's law so that she and her children would never end. The ash-marked, who come back from death with less memory each time, are death trying to get back in. Every return strains the seal, and the flame is cracking under it.", tags: ["truth:kindling_death_sealed"],
      known: [
        "Some who die come back with a ring of grey ash over the heart, and lose memory with each return. The keepers call it a punishment for neglecting the hearth. The marked keep coming back regardless of piety.",
        "At the black fire on the ember road, the marked lose their ash-rings and stay dead the next time they die. Under its fire-bowl is an urn of cold grey dust with the hearth's seal on it.",
        "The Kiln's oldest door says death was shut out 'by her hand'. A letter from one of the first keeper's children says the marked are 'a knock on that door'. The keepers' relic inventory lists the urn as lost.",
        "Confirmed: the first keeper locked death out of the world so that she and her children would never end. The marked are death trying to return, and each return cracks the seal a little more.",
      ] },
  ],

  tags: ["kindling"],

  subthemes: [
    { id: "undying_mark", n: "The Ash-Marked", d: "Some who die come back, with a ring of grey ash burned into the skin over the heart. Each return takes a little of their memory; families hide their marked in attics until there is nothing left to hide.", w: 1.5, truthLink: "death_sealed", tags: ["theme:ash_marked"] },
    { id: "ember_roads", n: "The Ember Roads", d: "Pilgrim roads radiate toward the Kiln, lined with little shrine-fires where the faithful rest and the marked revive. The roads are safe, crowded and taxed.", w: 1.3, req: { any: ["pilgrims", "pious", "open_roads", "great_roads"] }, tags: ["theme:ember_roads"] },
    { id: "keepers_hunt", n: "The Keepers' Choosing", d: "The priesthood of the hearth is searching for the next soul to burn. They want someone great: a hero, a saint, a king. Great people in this realm have started to fail on purpose.", w: 1.2, req: { any: ["organised", "gov:theocracy", "pious", "faith:lk_hearth"] }, truthLink: "real_dark", tags: ["theme:keepers_hunt"] },
    { id: "night_patient", n: "The Night Patient", d: "A soft-spoken heresy that preaches the coming dark as a release. Its members put out their hearths one night a month and sit together, waiting, unafraid.", w: 1, req: { any: ["mystic", "faith:philosophy", "egalitarian", "unstable", "faith:lk_dark"] }, truthLink: "gods_age", tags: ["theme:night_patient"] },
    { id: "dimming_sun", n: "The Dimming", d: "The sun has been weaker every decade within living memory. Harvests come later; the north is cold in midsummer; ash falls like snow in the spring.", w: 1.2, req: { any: ["cold", "tundra", "mountain", "steppe"] }, mods: [["realm:large", 1.3]], truthLink: "real_dark", tags: ["theme:dimming"], mark: { kind: "zone", n: "The Ash-Fields", color: "#9a958e", size: [2, 4], where: "remote" } },
    { id: "stacked_valley", n: "The Valley of Stacked Cities", d: "A landslide opened a valley wall and showed a city beneath this one, and another beneath that, each built on the ashes of the age before. The bottom city's carvings show a world without fire.", w: 1, req: { any: ["near:ruins", "mountain", "hills", "scholarly"] }, truthLink: "gods_age", tags: ["theme:stacked_cities"] },
    { id: "empty_throne", n: "The Empty Throne of Cinders", d: "A great lord who burned in the last linking left a throne no one may sit on. Pretenders race to claim his ash, believing his soul still lies in it.", w: 0.9, req: { any: ["monarchy", "dynastic", "hierarchical"] }, tags: ["theme:empty_throne"] },
    { id: "hollow_market", n: "The Hollow Market", d: "A town whose people have died and returned so often that none of them remember why they trade. The stalls open every morning; the coins change hands; nobody eats.", w: 0.8, req: { any: ["mercantile", "urbane", "has:city"] }, truthLink: "death_sealed", tags: ["theme:hollow_market"], mark: { kind: "zone", n: "The Hollow Towns", color: "#6a6058", size: [1, 2], where: "inner" } },
    { id: "painted_refuge", n: "The Painted Refuge", d: "A great canvas in a forgotten chapel opens onto a cold painted country, where outcasts, the marked and those the keepers wanted have hidden for generations.", w: 0.6, req: { any: ["artisans", "lavish", "mystic"] }, tags: ["theme:painted_refuge"] },
    { id: "grey_wyrm", n: "The Last Grey Wyrm", d: "One of the stone-scaled wyrms that ruled before the fire still lives in the high places, ancient and patient. It remembers what the fire-lords did, and it would very much like the flame to go out.", w: 0.8, req: { any: ["mountain", "near:beasts", "peaks", "hills"] }, truthLink: "gods_age", tags: ["theme:grey_wyrm"] },
    { id: "soul_coin", n: "The Soul-Coin", d: "Here the currency of last resort is a glowing ember-coin struck from the souls of the slain. Mercenaries are paid in them, and the marked spend them to keep their minds.", w: 1, req: { any: ["mercantile", "mercenaries", "martial", "atwar"] }, truthLink: "real_dark", tags: ["theme:soul_coin"] },
    { id: "deathless_deep", n: "The Deathless Below", d: "A sealed river-cavern beneath the realm where the oldest dead are kept. They are still moving after a thousand years, and the cavern seals are warm.", w: 0.8, req: { any: ["ancestor_bound", "faith:ancestors", "near:ruins"] }, truthLink: "death_sealed", tags: ["theme:deathless_deep"] },
  ],

  sites: [
    { id: "the_kiln", n: "The Kiln of $", kind: "wonder", where: "remote", d: "A vast stone furnace at the end of the ember roads, where the first flame burns low behind iron doors.",
      layers: {
        surface: { n: "The iron doors", text: "Pilgrims reach the Kiln after forty days on the ember roads. They leave offerings at its black iron doors and feel the heat on their faces from thirty paces. The keepers sell a clay token stamped with a flame for two coppers, and most pilgrims buy three." },
        study: { n: "The courtyard of crowns", text: "The courtyard is heaped with armour, crowns and swords, rusted into one mound: the gear of every soul burned in every linking. {investigator} counted 61 crowns and stopped counting swords at 900. The newest layer, on top, is mostly prisoners' leg-irons." },
        dig: { n: "Behind the doors", text: "Behind the doors the flame stands no taller than a man. The ash around it is ankle-deep and still warm. A brass rule hangs on a nail inside the door, notched with the flame's height at each linking. The keepers' copy of those notches is kept in {lead}.", points: "archive" },
        revelation: { n: "The shrinking flame", text: "The keepers' notches put the flame at thirty feet after the ninth linking, fourteen after the tenth and seven after the eleventh. Each layer of ash is thinner. The keepers of the hearth have known for four hundred years that the flame is dying whatever they burn. Their answer, minuted the same year: raise the road tolls." },
      } },
    { id: "stacked_canyon", n: "The Nine Floors of $", kind: "dig", where: "mountain", truthLink: "gods_age", d: "A canyon whose walls show city upon city, each a kingdom of a former age.",
      layers: {
        surface: { n: "The Ladder of Kings", text: "A landslide in {year} opened the canyon wall and showed windows, row on row, for three hundred feet. The shepherds call it the Ladder of Kings and charge visitors a copper to look. A child found a bronze cup in the scree and sold it to {investigator}." },
        study: { n: "Nine floors", text: "The survey party counted nine cities, one on top of another. Each is smaller and greyer than the city below, and each has a bigger hearth-temple. In the fourth city a temple wall lists 14 names under the words 'given to the flame'." },
        dig: { n: "The lowest city", text: "The lowest city has no hearths at all: not one chimney in 400 houses. Its people carved themselves smiling under a grey sky, among trees of stone. Over its gate, tall figures carry a torch up a hill. A rubbing of the gate is kept by the scholar {lead}.", points: "cast:investigator" },
        revelation: { n: "Before the fire", text: "There was an age before the fire, and its people lived well enough. Then the fire-lords carried their torch up the hill, lit the flame for an age of their own, and built each new city on the ashes of the last. Nine cities, nine linkings. The shepherds live in the tenth." },
      } },
    { id: "black_bonfire", n: "The Black Fire at $", kind: "anomaly", where: "any", truthLink: "death_sealed", d: "A shrine-fire on the ember road that burns black and gives no heat.",
      layers: {
        surface: { n: "The cursed fire", text: "A shrine-fire on the ember road burns black and gives no heat. Pilgrims stopped resting here thirty years ago, and the keepers took the signpost down. A tin cup still hangs on the hook by the fire-bowl, where the last keeper boiled water." },
        study: { n: "Graves with headstones", text: "The marked who sleep beside the black fire wake without the ash-ring over their hearts. The roadside graves bear it out: 17 marked folk rested here, and all 17 later died and stayed dead. Their families paid for headstones, which the marked do not usually need." },
        dig: { n: "The urn", text: "Under the fire-bowl is a sealed clay urn of cold grey dust that dims any lamp held near it. The wax seal on the urn is the hearth's own, and the urn's number appears in the keepers' inventory of relics, kept in {lead}.", points: "temple" },
        revelation: { n: "A piece of death", text: "The dust is a piece of death, smuggled back past the flame. The first keeper locked death out so that she and her children would never end. Three centuries ago a keeper of this shrine opened the door a crack, on purpose. The hearth's inventory lists the urn as 'mislaid'." },
      } },
    { id: "first_lord_grave", n: "The Tomb of the First Lord at $", kind: "ruin", where: "capital", truthLink: "gods_age", d: "The tomb of the founder of the hearth, venerated for an age.",
      layers: {
        surface: { n: "The gilded tomb", text: "The founder's tomb stands in the cathedral of the hearth. Every sovereign of {realm} has knelt at it on coronation day, 23 of them so far. The gilding is renewed every ten years from the cathedral's gold, and the bill is pinned up in the vestry." },
        study: { n: "The recut letters", text: "The inscription calls the first lord the one who 'gave the world its fire'. Under a raking lamp, older letters show beneath it, chiselled flat. The older text had eleven words. {investigator} could read the first two: 'took from'." },
        dig: { n: "The clay body", text: "The coffin holds a clay effigy, finely made and fired hard like a pot, and no body. A mason's mark on its heel matches the marks in the cathedral's repair records, which are kept in {lead}.", points: "archive" },
        revelation: { n: "The lord who never burned", text: "The first lord never burned. He lit the flame for his own age and fed it with other people, starting with the forty men of his household guard. The effigy was made because there was no body to bury. The hearth's calendar still counts the years from his sacrifice." },
      } },
    { id: "unlit_ring", n: "The Unlit Ring of $", kind: "shrine", where: "border", truthLink: "real_dark", d: "A ring of shrine-fires on the edge of the warm lands, all of them dark.",
      layers: {
        surface: { n: "The dark shrines", text: "Old shrines line the border road, all of them dark. Locals say they went out in the plague years. Each still has a stone bench for pilgrims and a bronze bell on a post. Nobody has rung one of the bells in living memory." },
        study: { n: "One by one", text: "The shrines did not go out together. The dates scratched on their lintels run 12 to 30 years apart and move inward, toward the Kiln. The outermost went dark 410 years ago. The newest dark shrine is sixty miles from a market town." },
        dig: { n: "The keepers' rings", text: "In each shrine's ashes lies a keeper's iron ring, left when the keeper walked out into the cold. There are nine rings, with nine names engraved inside. The keepers' roll of the dead, which should list them, is kept by the road-keeper {lead}.", points: "cast:official" },
        revelation: { n: "The shrinking warmth", text: "The warmth is shrinking toward the Kiln, and the keepers have known for four centuries. Each time a shrine froze, the order moved the border shrines a mile inward, renamed the road and told no one. Nine keepers walked into the cold rather than lie to pilgrims. The roll lists them as 'retired'." },
      } },
  ],

  beings: [
    { id: "the_hollowed", n: "The hollowed", kind: "beast", d: "Marked folk who died and returned once too often: grey-skinned, empty-eyed, still wearing the clothes and habits of their lives, and violent when woken from them.", danger: 2, biomes: ["grass", "tempforest", "badlands", "boreal", "coldsteppe", "dryforest"], look: { size: 1.7, group: [2, 12], move: "herd", speed: 4, col: "#8a8278", col2: "#4a443e", body: "biped", active: "any", visible: true } },
    { id: "grey_wyrm", n: "Grey wyrm", kind: "predator", d: "A stone-scaled wyrm of the age before the fire, slow, vast and immune to flame. Few remain; each knows the others by name.", danger: 3, biomes: ["peaks", "alpine", "badlands", "glacier"], look: { size: 22, group: [1, 1], move: "solo", speed: 14, col: "#7a7a72", col2: "#b8b0a0", body: "reptile", active: "day", visible: true } },
    { id: "ember_moth", n: "Ember-moth", kind: "insect", d: "Moths with glowing bellies that swarm around shrine-fires and fade when the fire does. Pilgrims count them as omens.", danger: 0, biomes: ["grass", "tempforest", "dryforest", "savanna", "boreal"], look: { size: 0.06, group: [30, 300], move: "swarm", speed: 5, col: "#e08a3a", col2: "#5a3a2a", body: "insect", active: "night", visible: true } },
    { id: "cinder_hound", n: "Cinder-hound", kind: "predator", d: "A lean grey dog that feeds on ash and the sick, and follows the cold as it advances. Its eyes glow like coals that are going out.", danger: 2, biomes: ["badlands", "coldsteppe", "tundra", "grass"], look: { size: 1.2, group: [3, 8], move: "pack", speed: 12, col: "#5a5550", col2: "#c06030", body: "quad", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "lk_shrine_fires", n: "Shrine-fires", field: "architecture", level: 1, d: "Roadside hearths kindled from the Kiln, where travellers rest and the marked revive." },
    { id: "lk_ash_farming", n: "Ash-tilling", field: "agriculture", level: 2, d: "Grains bred to ripen under a weak sun in fields dressed with ash from the shrine-fires." },
    { id: "lk_soul_coin", n: "Soul-coin", field: "alchemy", level: 3, d: "Embers struck into coins from the souls of the slain, used to pay soldiers and to restore the minds of the marked." },
    { id: "lk_ashsteel", n: "Ash-steel", field: "metallurgy", level: 3, d: "Steel quenched in Kiln-ash that holds an edge against the stone hides of the old wyrms." },
    { id: "lk_keeper_vows", n: "The keeper vows", field: "arcana", level: 2, d: "Rites by which a shrine-keeper binds herself to a fire, so that it burns on her strength when fuel runs out." },
    { id: "lk_linking", n: "The linking", field: "arcana", level: 5, d: "The great rite by which a soul is fed to the first flame to rekindle the age. Each time it works for a shorter while." },
  ],

  units: [
    { id: "lk_ember_knights", n: "Ember knights", role: "cavalry", mounted: 1, wpn: "lance", kit: "plate", ranks: 2, gap: 2.8, size: 40, w: 0.5, mods: [["theme:keepers_hunt", 4], ["theme:ember_roads", 3], ["faith:lk_hearth", 3]] },
    { id: "lk_marked_host", n: "Ash-marked host", role: "infantry", wpn: "sword", kit: "mail", ranks: 5, gap: 1.2, size: 120, w: 0.4, mods: [["theme:ash_marked", 6], ["theme:soul_coin", 3]] },
  ],

  faiths: [
    { id: "lk_hearth", n: "The Hearth", d: "The keepers of the first flame, who teach that the fire is the world's life and that to be chosen for burning is the highest honour.", tags: ["faith:lk_hearth", "organised"], w: 0.8, mods: [["pious", 1.5], ["cold", 1.5], ["pilgrims", 2]],
      names: ["The Keepers of the Hearth", "The First Flame of $", "The Ember Church"] },
    { id: "lk_dark", n: "The Night Patient", d: "A quiet heresy that welcomes the end of the fire as the beginning of the age of mortals.", tags: ["faith:lk_dark", "sinister"], w: 0.2, mods: [["mystic", 2], ["egalitarian", 1.5]],
      names: ["The Night Patient", "The Patient Dark of $", "The Unkindled"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Grey reaches", color: "#7d7a76", size: [2, 5], count: [1, 2], where: "remote", d: "Lands the flame's warmth no longer reaches: grey, cold, quiet and haunted by the hollowed." },
  ],

  storylines: [
    { id: "lk_the_choosing", n: "The Choosing of {ruler}", scale: "realm", anchor: "realm", w: 1.5, req: ["kindling", { any: ["monarchy", "pious", "faith:lk_hearth", "organised"] }],
      stages: {
        start: { h: "The keepers of the hearth come to {capital}", b: "A procession of keepers has arrived in {capital} bearing an iron crown. They say the flame has chosen {ruler} for the next linking, and that it is the greatest honour in the world.", wait: [2, 5], fx: { unrest: 6 }, next: [{ to: "accepts", w: 1, mods: [["ruler:pious", 3], ["pious", 1.5]] }, { to: "refuses", w: 1.5 }, { to: "substitute", w: 1, mods: [["ruler:cruel", 3], ["ruler:paranoid", 2]] }] },
        accepts: { h: "{ruler} walks the ember road", b: "{ruler} has set out for the Kiln on foot, as the old rite demands. {heir} rules in the meantime, and the people line the roads to see their sovereign pass for the last time.", wait: [3, 8], fx: { prestige: 10, stability: 4 }, next: [{ to: "linked", w: 2 }, { to: "turns_back", w: 1 }] },
        linked: { h: "{ruler} burns, and the sun brightens", b: "Word has come from the Kiln: {ruler} has been given to the flame. For a season the sun stands brighter over {realm}, and the harvest is the best in years.", fx: { ruler_dies: true, prestige: 15, growth: 0.003, monument: { tier: 2, name: "The Ember Gate of {ruler}" } }, end: true },
        turns_back: { h: "{ruler} returns from the Kiln", b: "{ruler} reached the Kiln, looked into the fire and came home, saying only that it was smaller than they had been told. The keepers call it apostasy.", fx: { stability: -6, unrest: 10, flag: "saw_kiln" }, end: true },
        refuses: { h: "{ruler} turns the keepers away", b: "{ruler} has sent the iron crown back with a curt letter. The keepers have withdrawn, saying the sun will remember the slight.", wait: [4, 10], fx: { stability: -4 }, next: [{ to: "cold_years", w: 2 }, { to: "keepers_war", w: 1, mods: [["zealous", 2.5], ["theme:keepers_hunt", 3]] }] },
        cold_years: { h: "A cold summer settles on {realm}", b: "The crops of {realm} failed under a pale sun, and the keepers' preachers say whose fault it is. Ash fell in {capital} in midsummer.", fx: { pop: 0.92, unrest: 15, stability: -6 }, end: true },
        keepers_war: { h: "The ember knights march on {capital}", b: "The keepers have proclaimed {ruler} an enemy of the flame. Their knights are on the road to {capital} to collect what is owed.", fx: { revolt: true, stability: -10 }, end: true },
        substitute: { h: "{ruler} sends a thousand in their place", b: "{ruler} has struck a bargain with the keepers: not one great soul, but a thousand lesser ones, gathered from the prisons and the poor quarters. The carts left {capital} at dawn.", fx: { pop: 0.95, unrest: 20, prestige: -5, ruler_trait: "cruel" }, end: true },
      } },
    { id: "lk_marked_child", n: "The Ash-Marked of {place}", scale: "local", anchor: "town", w: 1.5, req: "kindling",
      stages: {
        start: { h: "A drowned child of {place} wakes on the bier", b: "{person}, a fisher's child pulled from the river at {place}, sat up on the bier the next night with a ring of grey ash over the heart.", wait: [1, 3], fx: { unrest: 4 }, next: [{ to: "hidden", w: 2 }, { to: "given_to_keepers", w: 1, mods: [["faith:lk_hearth", 3], ["pious", 1.5]] }] },
        hidden: { h: "The family of {person} keep to themselves", b: "The fisher's family of {place} have stopped coming to market. Neighbours say they hear a child singing in the loft, the same verse over and over.", wait: [6, 18], next: [{ to: "forgets", w: 2 }, { to: "to_the_kiln", w: 1 }, { to: "black_fire", w: 0.6, mods: [["mystic", 2], ["theme:night_patient", 3]] }] },
        given_to_keepers: { h: "{person} taken by the keepers", b: "The keepers have come for the marked child of {place} and taken the child to a shrine-fire on the ember road, where they say it will be useful. The child's mother followed them for three days.", fx: { unrest: 6, stability: 2 }, end: true },
        forgets: { h: "{person} no longer knows their own mother", b: "The marked child of {place} has died and returned twice more. The child is polite to the family now, as to strangers, and goes on singing.", fx: { unrest: 3 }, end: true },
        to_the_kiln: { h: "{person} sets out for the Kiln", b: "{person}, still a child, walked out of {place} one morning toward the Kiln, saying the fire was calling their name. {person2}, a pilgrim, went along.", fx: { flag: "pilgrim_child" }, end: true },
        black_fire: { h: "{person} sleeps by the black fire", b: "The family carried their marked child to the black fire on the old road. The child woke without the ash-ring. That winter the child fell sick and died, and stayed dead, and the family buried the body with relief.", fx: { stability: 1, flag: "death_returned" }, end: true },
      } },
    { id: "lk_bottom_city", n: "The City Under {place}", scale: "local", anchor: "town", w: 1, req: ["kindling", { any: ["mountain", "hills", "near:ruins", "scholarly", "learned"] }],
      stages: {
        start: { h: "A landslide opens the hillside at {place}", b: "The rains brought the hillside down above {place}, and the cliff behind it is full of windows. {investigator}, the hearth college scholar, has come to see.", wait: [2, 6], next: [{ to: "nine_cities", w: 2 }, { to: "sealed_again", w: 1, mods: [["faith:lk_hearth", 2.5], ["zealous", 2]] }] },
        nine_cities: { h: "Nine cities found beneath {place}", b: "{investigator} has counted nine cities stacked in the hillside, each smaller and greyer than the one below. The lowest city had no hearths, and its carvings show people smiling under a grey sky.", wait: [3, 8], fx: { science: { writing: 0.5 } }, next: [{ to: "published", w: 1.5 }, { to: "scholar_vanishes", w: 1 }] },
        sealed_again: { h: "The keepers seal the hillside at {place}", b: "Keepers arrived before the scholars could and walled the windows up with stone and prayer. {investigator} was sent home with a warning.", fx: { stability: 2 }, end: true },
        published: { h: "{investigator} publishes the bottom city", b: "Copies of {investigator}'s drawings of the hearthless city are passing hand to hand across {realm}. The Night Patient preach from them openly now.", fx: { discovery: "writing", unrest: 10, stability: -4 }, end: true },
        scholar_vanishes: { h: "{investigator} does not return from the dig", b: "The scholar went down to the lowest city alone with a lamp. The lamp was found at the bottom, still lit, and beside it a scrap of a sentence: 'it was ours'.", fx: { unrest: 4 }, end: true },
      } },
  ],

  cast: [
    { role: "investigator", n: "a scholar of the hearth college who measures shrine-fires and digs old cities", home: "mountain", stance: "Believes the keepers' own records will explain the dimming sun, and is finding out they do." },
    { role: "official", n: "a road-keeper of the hearth who keeps the linking tallies and the roll of the dead", home: "remote", stance: "Wants the flame fed and the pilgrims calm; knows the numbers and keeps them locked up." },
    { role: "believer", n: "a preacher of the Night Patient, the heresy that welcomes the dark", home: "border", stance: "Lost a sister to the last linking and preaches that the dark is only the end of the fire-lords." },
    { role: "survivor", n: "an ash-marked ferryman who has died and returned five times", home: "inner", stance: "Wants to remember the names of the family; would accept staying dead if it came to that." },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", who: "a parish keeper of {place}", points: "cast:official", text: "Hearth catechism as taught at {place} in {year}, with the parish keeper's margin note: 'What is the world? The warmth of the first flame, which burns in the Kiln. What is the dark? Its absence. What is your life? Fuel, given gladly.' Margin: 'The linking, in which a chosen soul is burned to renew the flame, is lesson two. Eleven children recited this year, down from thirty. Parents say the third answer frightens them. I have written to the road-keeper, {lead}, asking to soften it.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "a ferry-woman of {place}", text: "A ferry-woman of {place}, banking the brazier at dusk for her passengers, {year}: 'Bank the fire before you sleep. Every hearth is a spark of the big one at the Kiln, and if they all go out at once, the sun goes with them.' The ferry's brazier has not gone out in 61 years. The fare includes a copper for its coal, and nobody on the river complains about that copper." },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "the court astronomer of {realm}", text: "Report of the court astronomer of {realm} to the crown, {year}: 'The recent dimness of the sun is a passing veil of high dust, as in the reign of the third king, and will clear within a generation. My brass light-gauge reads a tenth weaker than my predecessor's figure, but his gauge was old and he drank. There is no cause for alarm, and the crown need not consult the keepers on the matter.'" },

    { depth: "core", about: "truth:gods_age", source: "ruin", bias: "true", reliable: true, plain: true, who: "carved in the lowest of the nine cities", points: "site:stacked_canyon", text: "Carved over a doorway in the lowest of the nine cities, copied by {investigator} in {year}: 'In our grandparents' time the lords came up the hill with a torch and lit their fire on the summit. They say the sky is theirs now and the age is theirs. We were nine hundred in this town and warm enough together. We do not need their fire.' The copy is filed with the canyon survey at {lead}." },
    { depth: "core", about: "truth:gods_age", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "{believer}, preacher of the Night Patient", text: "Sermon of {believer}, preacher of the Night Patient, at a cold hearth in {place}, {year}: 'My sister was chosen at the last linking. She walked to the Kiln with forty others, and the keepers say the forty bought us ninety years. Ninety years of whose age? They tell you the dark is death. The dark is only the end of the fire-lords. I keep her shoes by my unlit hearth, and I am waiting.'" },
    { depth: "core", about: "truth:gods_age", source: "oral", bias: "garbled", reliable: "partial", who: "a squire, at an inn in {place}", points: "sub:grey_wyrm", text: "Told at the inn at {place} by the squire who carried the lamp, {year}: 'Three days we climbed to the wyrm's cave. My knight raised a shield painted with the flame. The wyrm laughed and said: your masters lit a candle in my house and called it the sun. Then it let us go, which is more than the keepers ever did for anyone.' The squire's sworn account is filed at {lead}, and the squire still owes for the shield." },
    { depth: "core", about: "truth:gods_age", source: "temple", bias: "official", reliable: false, who: "the Hearth Creed, article one", text: "Article one of the Hearth Creed, read aloud at every coronation in {realm}, most recently in {year}: 'Before the flame there was nothing: no light, no life, no people. All that lives owes its being to the fire and to the lords who tended it.' The keepers require the new sovereign to repeat it with one hand on the iron crown. Two sovereigns who declined were not crowned." },

    { depth: "core", about: "truth:real_dark", source: "archive", bias: "true", reliable: true, plain: true, who: "{official}, road-keeper of the hearth", text: "Private tally of {official}, road-keeper of the hearth, kept in a locked ledger at the Kiln, {year}: 'Linking of the ninth age: four hundred years bought. Tenth: two hundred and ten. Eleventh: ninety. This one: we will be lucky to see forty. When it goes out, nothing comes after. I have walked the grey reaches. There is no new age waiting out there, only frost on dead birds.'" },
    { depth: "core", about: "truth:real_dark", source: "person", bias: "true", reliable: "partial", who: "a border-shrine keeper", points: "site:unlit_ring", text: "Diary of the keeper of the last shrine on the border road, {year}: 'Moved the shrine in another mile today, by order of {official}. Carried the fire-bowl on a handcart; it took six of us. The old site is frost at noon. We are not to speak of it to the pilgrims. The old shrines behind us, at {lead}, are all dark now, and I can see the nearest from my door.'" },
    { depth: "core", about: "truth:real_dark", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a pedlar of {place}", points: "ruin", text: "A pedlar of {place}, testifying to the town council in {year}: 'I walked twelve days into the grey reaches, as far as I dared. There was no monster there, no war, nobody. Only cold, and quiet, and birds lying where they fell, hundreds of them. My mule froze on the ninth night.' The pedlar's map of the route shows a ruined town at the far edge, marked {lead}." },
    { depth: "core", about: "truth:real_dark", source: "temple", bias: "official", reliable: false, who: "a proclamation of the keepers", text: "Proclamation of the keepers of the hearth, nailed to every shrine door on the ember roads in {year}: 'The flame is eternal. Each linking renews it in full, as on the first day, and so it shall be for as long as the faithful give gladly. Rumours of shrinking warmth are spread by the Night Patient. The toll for the roads is raised by two coppers, for upkeep.'" },
    { depth: "core", about: "truth:real_dark", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "an order of the keepers, countersigned by {official}", text: "Order of the keepers, countersigned by {official}, {year}: 'Great souls being scarce, the Kiln will accept the lesser in number. Ratio: one hero to [struck out] of the common sort.' Attached: a list of 196 sent from the debtors' prison of {place}. Name nine on the list is {person}, a cooper, for a debt of nine shillings. Beside it someone has written the sum, paid in full, and the date: three days late." },

    { depth: "core", about: "truth:death_sealed", source: "ruin", bias: "true", reliable: true, plain: true, who: "the oldest door of the Kiln", text: "Inscribed on the oldest of the Kiln's seven doors, copied by {investigator} in {year}: 'Here is death shut out, by her hand, that the age of the flame shall have no end and her children no grave.' Below it, in the same hand, a smaller line: 'The lock is the fire. While the fire stands, the door stands.' The keepers have hung a tapestry over the lower line." },
    { depth: "core", about: "truth:death_sealed", source: "person", bias: "true", reliable: "partial", who: "a child of the first keeper, to a sister", points: "temple", text: "A letter from one of the first keeper's children to a sister, preserved in the hearth's sealed collection at {lead}, dated in the 300th year of the flame: 'Mother did not light the world. She locked a door in it, so that none of us would end. Every one of the marked is a knock on that door. This year there were forty knocks. I can hear them from my room.'" },
    { depth: "core", about: "truth:death_sealed", source: "heretic", bias: "garbled", reliable: "partial", who: "a wall at the black fire", points: "site:black_bonfire", text: "Chalked on the shrine wall at the black fire, copied by {investigator} on a visit in {year}: 'IT IS NOT A CURSE. IT IS A KEY THAT DOES NOT FIT YET.' Under it, thirty-one marks in a column, one for each marked person who slept here and stayed dead. The newest mark is fresh. The fire stands at {lead}, and the keepers no longer sign the road to it." },
    { depth: "core", about: "truth:death_sealed", source: "library", bias: "official", reliable: false, who: "the keepers' primer on the ash-mark", text: "From the keepers' primer on the ash-mark, sixth edition, issued to parish keepers in {year}: 'The ash-mark is a punishment for impiety, borne by those who neglected their hearth. It is cured by pilgrimage and the grace of the keepers. A marked person who walks the ember roads and pays the tolls in full will be restored within three returns.' No restored person is named in the primer." },
    { depth: "core", about: "truth:death_sealed", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, ash-marked ferryman", points: "sub:undying_mark", text: "Statement of {survivor}, ash-marked ferryman, to a keepers' clerk in {year}: 'This is my fifth return, and each time I come back with less. I have lost my wife's name and my daughter's face. I keep both names on a slate in the ferry hut. Each time I die I stand at a shut door, and I can feel the fire's heat holding it. Let it open. The keepers' register of the marked at {lead} lists others who have lost more.'" },

    { depth: "sub", about: "sub:undying_mark", source: "person", bias: "true", reliable: true, who: "a mother of {place}", text: "A letter from a mother of {place} to her sister, {year}: 'He came back again last night, his fourth time, with the grey ring over his heart. He knew the dog's name but not mine. I have written my name on the wall over his bed in charcoal, in letters a hand high. The keepers want him sent to a shrine-fire. I have told them he is sleeping and barred the door.'" },
    { depth: "sub", about: "sub:keepers_hunt", source: "oral", bias: "exaggerated", reliable: "partial", who: "a fencing master of {place}", points: "cast:official", text: "Advice of a fencing master of {place} to the pupils, {year}: 'Never win a tourney. Never heal a plague. Never be loved by the people. The keepers are counting, and the fire wants the best.' The master lost a final on purpose years ago and has kept a trophy-shaped hole on the mantel since. The keepers' list of candidates is kept by the road-keeper {lead}." },
    { depth: "sub", about: "sub:soul_coin", source: "traveller", bias: "true", reliable: "partial", who: "a quartermaster on the border", text: "Accounts of a quartermaster on the border, {year}: 'Paid the company in ember-coins, 300 of them, struck from the slain at the last battle. They are warm to hold and hum on a still night, like someone singing in the next room. The marked in the company spend theirs to keep their memories. One sergeant spent forty in a week and still could not say what town she came from.'" },
    { depth: "sub", about: "sub:ember_roads", source: "library", bias: "propaganda", reliable: false, who: "a keepers' notice on the ember roads", text: "Notice posted at every toll-house on the ember roads, {year}: 'The ember roads are maintained at the keepers' expense for the comfort of pilgrims. The toll of four coppers is a voluntary offering. Pilgrims who decline to offer may use the verge.' The verge is posted with a second notice, smaller, forbidding pilgrims to rest at the shrine-fires without a toll token." },
    { depth: "sub", about: "sub:painted_refuge", source: "person", bias: "garbled", reliable: "partial", who: "a runaway from {place}", points: "sub:painted_refuge", text: "Tale of a runaway from {place}, told to a magistrate in {year}: 'You step into the big picture in the chapel and it is snowing. Everyone there is someone the keepers wanted: a healer, a champion, two princes. Eighty of us, perhaps. They paint new houses when there is room. I came out for medicine and could not find the frame again.' The magistrate's record of the tale is filed at {lead}." },
    { depth: "sub", about: "sub:hollow_market", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a grain factor travelling through {place}", points: "sub:deathless_deep", text: "Letter of a grain factor travelling through {place}, {year}: 'In the hollow town I bought a loaf. The baker took my coin, gave me the bread and said good morning, three times. Nobody there has eaten in years. The town's oldest families were moved to a sealed cavern, the baker said, because they no longer stop moving; the order for it is at {lead}. I left the loaf on the counter and the baker sold it again.'" },
    { depth: "sub", about: "sub:dimming_sun", source: "archive", bias: "true", reliable: true, who: "the reeve of {place}, harvest roll", text: "Harvest roll of the manor of {place}, kept by the reeve, {year}: 'Barley in on the ninth of the month of leaves, nineteen days later than the roll of sixty years ago for the same field. Yield four sacks to the acre; then it was seven. Ash on the snow in spring, two fingers deep. The keepers' answer to the petition was a sermon on gratitude. I have planted rye on the north strip and sold the plough-ox.'" },
    { depth: "sub", about: "sub:empty_throne", source: "archive", bias: "official", reliable: "partial", who: "a clerk of the court of claims", text: "Minutes of the court of claims of {realm}, sitting on the Throne of Cinders, {year}: 'Claimant the eleventh presents a snuffbox of ash said to be the late lord's left hand. Claimant the twelfth presents a larger box. The court notes that the ash so far presented would make four lords. Both claims are adjourned. The court reminds claimants that the throne itself may not be sat on, and that the bench beside it is for the clerk.'" },
    { depth: "site", about: "site:first_lord_grave", source: "archive", bias: "redacted", reliable: "partial", who: "a cathedral master mason", points: "archive", text: "Report of the master mason of the cathedral of the hearth, {year}: 'On opening the founder's coffin to repair the hinge we found [struck out]. The bishop has ordered the lid sealed with lead and our wages doubled for the month. Four of us signed.' A later hand has added: 'Mason's mark on the [struck out] matches the repair book of the first century, held at {lead}.'" },
    { depth: "site", about: "site:the_kiln", source: "person", bias: "true", reliable: true, who: "a pilgrim at the Kiln", text: "Letter of a pilgrim from {place}, sent home from the end of the ember road, {year}: 'Forty days walking and four coppers a day in tolls, and I have seen it. I thought it would be a sun. It is a campfire, no taller than your father, in a room of warm ash. The keepers would not let me measure it. Someone should tell them at home how small it is.'" },
  ],
};
