// The Long Dark: a winter of years, a dimming sun or a sky of ash returns every few generations, and this time it may stay.
export default {
  id: "long_dark",
  name: "The Long Dark",
  family: "world",
  kind: "cycle",
  pitch: "Every few generations a winter comes that lasts for years, under a sun that turns red. The last one was so long ago that the southern courts call it a nursery tale.",
  slots: ["apocalypse", "ecology"],
  tone: ["grim", "melancholy"],
  era: ["bronze", "medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "grimdark", "mythic", "flintlock"],
  w: 1,
  excludes: [],
  pairs: [{ id: "ward_walls", w: 3 }, { id: "gods_twilight", w: 2 }, { id: "last_kindling", w: 2 }, { id: "wheel_of_suns", w: 1.5 }, { id: "unquiet_gate", w: 1.5 }],

  truths: [
    { id: "cold_masters", n: "The cold has masters", d: "The winter is not weather. The Rime Court, a people of the cold, gave the first southern kings the summer lands for one promise, and the kings broke it and sealed them beyond the ice. Each Long Dark is the Rime Court coming to collect. Their grievance is just, and the clause that proves it was cut out of the crown's own charter.", tags: ["truth:cold_masters"],
      known: [
        "The Watch reports cold-walkers coming south behind the snow. The crown's library says they are frostbitten deserters. The Watch has 111 watchmen, and nobody in the south checks their reports.",
        "The oldest stretch of the northern wall has its hinges on the northern face. Under it is a stone in two scripts, one of them made of frost-shapes. Watchmen say the cold-walkers look sad rather than angry.",
        "The crown's founding charter has a clause cut out with a knife. The gate stone quotes the same words: 'in return for which the Crown swears'. {survivor} has copied the frost-script half.",
        "Confirmed: the cold folk gave the south its summer lands under a treaty, and the first kings broke it. Each Long Dark is the Rime Court collecting what is owed. The crown has hidden the clause for centuries.",
      ] },
    { id: "moved_sun", n: "The sun was moved", d: "A god-king of the old south dragged the sun nearer to end a famine; four thousand slaves died hauling it. The sun has been slipping back ever since. Each Long Dark is the sun falling further away, each return of warmth is shorter, and the fire-temples still sing about it as a gift.", tags: ["truth:moved_sun"],
      known: [
        "The sun looks redder than in old paintings. The temples blame the dust of distant fires. {investigator}, an astronomer, has measured it every solstice and has not published the results.",
        "Solstice tables two centuries apart show the sun's width shrinking by a twentieth. The fire-hymn says 'our father pulled the sun to us with a rope'. Most people take the hymn as a figure of speech.",
        "A painted cave shows the sun twice as large, with slaves hauling ropes toward it and a tally of four thousand. The size matches the tables for the god-king's reign.",
        "Confirmed: the god-king pulled the sun closer and it has been sliding back ever since. Each Long Dark is the slide. The temples call it a gift, and the court has sealed the tables.",
      ] },
    { id: "broken_seasons", n: "The seasons are broken", d: "An ancient calamity cracked the world's tilt, and the seasons swing wider every cycle. The old north built bronze engines to steady them, and the Watch turned them by hand each solstice. The last Ice-Warden took the key north and never came back; one engine still runs, and it can still be woken.", tags: ["truth:broken_seasons"],
      known: [
        "A valley in the mountains stays green all winter with no hot springs to explain it. The crown's survey calls the 'machinery' there natural rock. Herders say the ground hums.",
        "{investigator}'s notes show each cold cycle lasting longer than the last by a fixed ratio, like something winding down. A bronze plate in the north gives orders to 'turn the vanes at each solstice'.",
        "Watch records say the last Long Dark ended when the Ice-Warden went north with fire-glass and a key. The Ice-Warden and the key never came back. Bronze vanes turn under the green valley.",
        "Confirmed: the seasons are steadied by bronze engines the Watch once tended by hand. Without the key they are failing one by one. One engine still runs, and it can be woken.",
      ] },
  ],

  tags: ["long_dark"],

  subthemes: [
    { id: "long_autumn", n: "The Three-Year Autumn", d: "The harvest has failed to ripen three years running. Granaries are counted in the capital each month, and the numbers are no longer published.", w: 1.5, mods: [["cold", 2], ["river_folk", 1.3]], tags: ["theme:long_autumn"] },
    { id: "watch_on_ice", n: "The Watch on the Ice", d: "A sworn order guards the northern border against the cold-walkers, an enemy the south no longer believes in. It is starved of men, and filled with convicts.", w: 1.4, req: { any: ["cold", "mountain", "frontier", "frontier_forts"] }, mods: [["martial", 1.5]], truthLink: "cold_masters", tags: ["theme:ice_watch"], mark: { kind: "zone", n: "The Ice March", color: "#c8d8e8", size: [2, 4], where: "border" } },
    { id: "risen_snow_dead", n: "The Risen in the Snow", d: "Those who freeze in the drifts do not stay down. Villages burn their winter dead now, and argue about whose grandmother it is walking in the trees.", w: 1, req: { any: ["cold", "forest", "tundra"] }, truthLink: "cold_masters", tags: ["theme:snow_dead"] },
    { id: "southern_quarrels", n: "The Southern Quarrels", d: "The warm courts of the south are at war over a crown while the cold walks down the map. Every levy sent south is a levy not sent north.", w: 1.2, req: { any: ["monarchy", "dynastic", "warm", "hot"] }, tags: ["theme:southern_war"] },
    { id: "ice_refugees", n: "The People from Beyond", d: "Whole clans have come over the ice with their herds, fleeing something behind them. They are not welcome, and they are not going back.", w: 1, req: { any: ["cold", "steppe", "nomadic", "frontier"] }, tags: ["theme:ice_refugees"] },
    { id: "false_dawn", n: "The False Dawn", d: "A fire-priest has crowned a boy who 'brings the sun back'. The cold has not noticed.", w: 0.8, req: { any: ["pious", "zealous", "faith:sun"] }, truthLink: "moved_sun", tags: ["theme:false_dawn"] },
    { id: "red_sun", n: "The Red Sun", d: "The sun is redder at noon than old paintings show it, and ash falls grey on clear days. Astronomers measure its width each solstice and the measurements are shrinking.", w: 1, req: { any: ["scholarly", "learned", "faith:stars", "seers"] }, truthLink: "moved_sun", tags: ["theme:red_sun"] },
    { id: "hot_valleys", n: "The Steaming Valleys", d: "Valleys warmed by hot springs stay green through the worst of the cold. Every lord wants one, and every one is already held.", w: 1, req: { any: ["mountain", "hills", "near:ley"] }, tags: ["theme:hot_valleys"], mark: { kind: "zone", n: "Steam valley", color: "#7aa07a", size: [1, 2], where: "mountain" } },
    { id: "under_cities", n: "The Cities Below", d: "Towns are digging down: cellars joined to cellars, streets roofed over, whole quarters living by lamplight to save the heat.", w: 0.8, req: { any: ["urbane", "has:city", "artisans", "mountain_folk"] }, tags: ["theme:under_cities"] },
    { id: "old_north_weapon", n: "The Weapon in the Old North", d: "Watch archives speak of something buried in the abandoned northern cities that ended the last Long Dark. The archives disagree on what.", w: 0.8, req: { any: ["near:ruins", "cold", "scholarly"] }, truthLink: "broken_seasons", tags: ["theme:north_weapon"] },
    { id: "cold_truce", n: "The Talk with the Cold", d: "A border lord has met the cold folk under a flag of truce and come back alive. The court calls it treason; the lord calls it the only war he can win.", w: 0.6, req: { any: ["hospitable", "tolerant", "egalitarian", "frontier"] }, truthLink: "cold_masters", tags: ["theme:cold_truce"] },
  ],

  sites: [
    { id: "oldest_wall", n: "The Sealed Gate of $", kind: "ruin", where: "border", truthLink: "cold_masters", d: "The oldest section of the northern ice-wall, with doors that open only from the far side.",
      layers: {
        surface: { n: "The black wall", text: "The oldest stretch of the northern wall is black stone, older than the Watch that guards it. Its three doors are iced shut. The Watch roll lists four watchmen posted here, and a brazier that burns a cartload of wood a week." },
        study: { n: "Hinges on the wrong side", text: "The bars and hinges are on the northern face. These doors were built to be opened from beyond the wall, not from the south. {survivor} checked all three with a lamp and an axe-head, and asked for a transfer the same week." },
        dig: { n: "The treaty stone", text: "Under the gatehouse floor lies a carved stone in two scripts. One is the old crown script; the other is made of frost-shapes. The crown script breaks off at 'in return for which the Crown swears'. The charter it quotes is held at {lead}.", points: "archive" },
        revelation: { n: "The first breach", text: "The wall was not built to keep the cold out. It marked a treaty border: the Rime Court gave the south its summer lands, and the first southern kings swore something in return. The kings broke the oath, barred the doors from their side and cut the clause from their charter. The Rime Court collects each Long Dark." },
      } },
    { id: "kneeling_city", n: "The Kneeling City of $", kind: "ruin", where: "remote", d: "A frozen city whose people died kneeling in the squares, all facing the same way.",
      layers: {
        surface: { n: "Under the ice", text: "A city lies under clear ice in the far north, its people visible beneath like fish in a frozen pond. The Watch maps mark it with a cross and the word 'avoid'. A wooden sledge left by an earlier visitor still sits above the main square." },
        study: { n: "Summer clothes", text: "Every figure kneels facing north, about three thousand of them. None is dressed for winter: they wear linen and sandals, and one market stall still holds summer plums. Whatever happened here happened on a single warm day." },
        dig: { n: "The king's crown", text: "In the palace the king kneels too, and his crown has been set on the floor in front of him. Beside it lies a scroll case, open and empty. The Watch's record of the last Long Dark mentions this city, and is kept at {lead}.", points: "archive" },
        revelation: { n: "Terms refused", text: "They were not praying. The king laid down his crown and his people knelt to surrender to the cold before it reached them, in their summer clothes. The scroll case held the terms they offered. Whoever they surrendered to did not accept, and froze the city as it knelt." },
      } },
    { id: "warm_valley", n: "The Green Hollow of $", kind: "anomaly", where: "mountain", truthLink: "broken_seasons", d: "A valley that stays summer-warm in the deepest cold, with no hot springs to explain it.",
      layers: {
        surface: { n: "Flowers in the ice", text: "A valley ringed by glaciers stays green through the deepest cold. Goats graze it in midwinter, and the herders pay the lord one goat a year for the right. There are no hot springs, and the stream runs cold to the hand." },
        study: { n: "Lines of heat", text: "The warmth rises from the stone in straight lines a hundred paces apart, like heat from a buried hearth. Snow melts along the lines first. {investigator} drove copper stakes along one line and followed it to a shaft at the valley's head." },
        dig: { n: "The vanes", text: "Down the shaft turn great bronze vanes, slowly, frosted on one face and hot on the other. One of the eight has stopped. A bronze plate names the Watch as keeper of the turning key. A watchman, {lead}, has seen the key-roll.", points: "cast:survivor" },
        revelation: { n: "The engine left running", text: "The old north built these engines to steady the world's tilt after an ancient calamity cracked it. The Watch turned them by hand each solstice until the last Ice-Warden took the key north and never returned. This engine has run alone for three centuries. Seven of its eight vanes still turn." },
      } },
    { id: "star_chart_cave", n: "The Painted Sky of $", kind: "shrine", where: "any", truthLink: "moved_sun", d: "A cave whose ceiling is painted with a sky that does not match the one above.",
      layers: {
        surface: { n: "The painted ceiling", text: "An old shrine in a cave has a ceiling painted with stars. Pilgrims leave candle-stubs on the ledge, about a hundred a year, and the soot has darkened the paint near the entrance. The keeper charges nothing and sells hot cider." },
        study: { n: "The wrong sun", text: "The stars are right, every one checked against the sky. The sun is wrong: drawn twice as large as it looks now, and higher. {investigator} measured it against the painted stars and got the width the old tables give for the god-king's reign." },
        dig: { n: "The rope-haulers", text: "Behind the altar, a carved line of slaves hauls ropes upward toward the painted sun. Under them is a tally of four thousand marks. The fire-temple keeps the hymn that tells this story, and its oldest copy is at {lead}.", points: "temple" },
        revelation: { n: "Borrowed warmth", text: "The god-king of the old south pulled the sun closer to end a famine, and four thousand slaves died on the ropes. It held for two centuries. The sun has been sliding back ever since, and each Long Dark is one step of the slide. The fire-temples sing about it as a gift." },
      } },
    { id: "glassfire_mine", n: "The Fire-Glass Pits of $", kind: "dig", where: "mountain", d: "Old mines of a black volcanic glass that the cold-walkers cannot abide.",
      layers: {
        surface: { n: "Black shards", text: "Abandoned pits in the mountains are full of black, glittering volcanic glass. Children pick shards from the spoil heaps and sell them at market as charms, a copper a handful. The pits flood each spring and freeze each autumn." },
        study: { n: "Standard issue", text: "Watch archives from three centuries ago list fire-glass as standard issue: one spearhead and twelve arrowheads per watchman. The current issue list has no glass on it. The quartermaster who struck it off saved the Watch forty crowns a year." },
        dig: { n: "The deep galleries", text: "The deepest galleries are lined with frozen cold-walkers, tall and thin, shattered where glass struck them. Among them lies a watchman with a glass dagger in each hand. The watchman who found them, {lead}, still has the report.", points: "cast:survivor" },
        revelation: { n: "The war the crown forgot", text: "The last Long Dark was fought and won with what lies in these pits. The Watch dug the glass, armed every watchman and broke the cold-walkers at the passes. Then the winters ended, and the crown closed the mines to save money. The Watch now has 111 watchmen and no glass." },
      } },
  ],

  beings: [
    { id: "cold_walker", n: "Cold-walker", kind: "predator", d: "A tall, gaunt figure of ice and old bone that walks before the winter. Everything it passes is coated in frost.", danger: 3, biomes: ["glacier", "tundra", "boreal", "coldsteppe"], look: { size: 2.3, group: [1, 6], move: "pack", speed: 7, col: "#c8d8e8", col2: "#5a7a9a", body: "biped", active: "night", visible: true } },
    { id: "snow_wight", n: "Snow-wight", kind: "beast", d: "One who froze in the drifts and got up again. Slow, silent and always walking home.", danger: 2, biomes: ["tundra", "boreal", "tempforest", "coldsteppe"], look: { size: 1.7, group: [1, 8], move: "swarm", speed: 3, col: "#a8b0b8", col2: "#3a4048", body: "biped", active: "night", visible: true } },
    { id: "frost_bear", n: "Rime bear", kind: "predator", d: "A white bear grown huge in the cold years, its fur crusted with ice that turns arrows.", danger: 2, biomes: ["glacier", "tundra", "boreal"], look: { size: 3, group: [1, 1], move: "solo", speed: 25, col: "#e8eef2", col2: "#9aa8b0", body: "quad", active: "any", visible: true } },
    { id: "ash_moth", n: "Ash moth", kind: "insect", d: "Grey moths that hatch in their millions when ash falls, and eat stored wool and grain.", danger: 0, biomes: ["grass", "tempforest", "coldsteppe", "boreal", "savanna"], look: { size: 0.05, group: [100, 2000], move: "swarm", speed: 4, col: "#8a8680", col2: "#5a5650", body: "insect", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "ld_long_stores", n: "Long stores", field: "agriculture", level: 1, d: "Grain kept dry in sealed pits for seven years, and the habit of never eating the last of it." },
    { id: "ld_glass_houses", n: "Heated glass-houses", field: "architecture", level: 2, d: "Gardens roofed in glass and warmed by flues, growing greens through a winter of years." },
    { id: "ld_fireglass", n: "Fire-glass arms", field: "warfare", level: 2, d: "Blades and arrowheads knapped from black volcanic glass, which shatters what the cold has made." },
    { id: "ld_under_streets", n: "Roofed streets", field: "engineering", level: 3, d: "Whole quarters dug down and roofed over, heated by one great furnace and lit by lamps." },
    { id: "ld_sun_measure", n: "Measuring the sun", field: "astronomy", level: 4, d: "The width and colour of the sun are measured each solstice, and the tables show it shrinking, which no one wants to hear." },
    { id: "ld_season_engine", n: "The season engine", field: "natural_philosophy", level: 5, d: "Scholars learn how the buried northern vanes once held the world's tilt, and how they might again." },
  ],

  units: [
    { id: "ld_ice_watch", n: "Watchmen of the Ice", role: "infantry", wpn: "spear", kit: "hide", ranks: 3, gap: 1.4, size: 80, w: 1, mods: [["theme:ice_watch", 8], ["cold", 2]] },
    { id: "ld_glass_archers", n: "Fire-glass archers", role: "ranged", wpn: "bow", kit: "hide", ranks: 3, gap: 1.6, size: 60, w: 0.6, mods: [["theme:north_weapon", 6], ["theme:ice_watch", 3]] },
  ],

  govs: [
    { id: "ld_watch_march", n: "Watch-march", d: "The sworn order of the northern wall has become the government of the north; its Ice-Warden rules from the gatehouse.", tags: ["gov:ld_watch", "autocracy"], w: 0.4, req: { any: ["cold", "frontier"] }, forms: ["March of $", "Watch of $", "Iceguard of $"], ruler: "Ice-Warden", mods: [["theme:ice_watch", 8], ["martial", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Ice line", color: "#dfe8f0", size: [2, 5], count: [1, 2], where: "remote", d: "Lands already lost to the advancing ice, their towns abandoned and their roads drifted over." },
  ],

  storylines: [
    { id: "ld_three_winters", n: "The Winters of {realm}", scale: "realm", anchor: "realm", w: 1.5, req: ["long_dark", { any: ["cold", "mountain", "frontier", "steppe"] }],
      stages: {
        start: { h: "Summer does not come to {realm}", b: "Snow lies in the fields of {realm} at midsummer for the second year. In {capital} the granary-wardens have stopped answering questions.", wait: [3, 8], fx: { growth: -0.002, unrest: 8 }, next: [{ to: "watch_warns", w: 2 }, { to: "hoarding", w: 1, mods: [["hierarchical", 2], ["poor", 2]] }] },
        watch_warns: { h: "The Watch sends word to {capital}", b: "{survivor}, a watchman of the northern Watch, rode three horses to death to reach {capital}. Creatures are walking south behind the snow, the watchman says.", wait: [2, 6], next: [{ to: "march_north", w: 1, mods: [["martial", 2], ["ruler:brave", 3]] }, { to: "ignored", w: 2 }, { to: "truce", w: 0.6, mods: [["tolerant", 2], ["hospitable", 2]] }] },
        hoarding: { h: "Granaries of {realm} under guard", b: "The lords of {realm} have locked the grain stores. Bread riots have broken out in {place}.", wait: [2, 6], fx: { unrest: 15, stability: -5 }, next: [{ to: "ignored", w: 1 }, { to: "famine_revolt", w: 1, mods: [["poor", 2], ["unstable", 2]] }] },
        march_north: { h: "{ruler} leads the host of {realm} north", b: "With fire-glass from the old pits, the army of {realm} has marched to meet the cold. They sing the old songs, half-remembered.", wait: [4, 10], fx: { treasury: -40 }, next: [{ to: "cold_broken", w: 1 }, { to: "host_lost", w: 1 }] },
        ignored: { h: "{capital} dismisses the warnings from the north", b: "The court of {realm} has more pressing matters. {survivor}'s report has been filed with the nursery tales.", wait: [6, 12], next: [{ to: "north_lost", w: 2 }, { to: "famine_revolt", w: 1 }] },
        truce: { h: "{survivor} parleys with the cold", b: "Under a white flag on the ice, {survivor} of the Watch has spoken with the cold folk and come back alive, with terms.", fx: { stability: -5, prestige: 5, flag: "cold_truce" }, end: true },
        cold_broken: { h: "The cold is driven back from {realm}", b: "Fire-glass and fire: the host of {realm} broke the cold-walkers at the passes. Spring came late, but it came.", fx: { prestige: 15, stability: 8 }, end: true },
        host_lost: { h: "The host of {realm} does not return", b: "No word from the army for a season. Then the snow-wights came down the north road, wearing the colours of {realm}.", fx: { pop: 0.85, stability: -15 }, end: true },
        north_lost: { h: "The north of {realm} is abandoned", b: "The ice took the northern provinces one village at a time. Their people fill the roads south, carrying their doors on their backs.", fx: { pop: 0.85, abandon_town: true, unrest: 10 }, end: true },
        famine_revolt: { h: "Hunger brings {realm} down", b: "The starving of {place} broke the granary doors and then the palace gates. The cold did not have to fight at all.", fx: { revolt: true, stability: -20 }, end: true },
      } },
    { id: "ld_buried_engine", n: "The Vanes under {place}", scale: "local", anchor: "town", w: 1, req: ["long_dark", { any: ["mountain", "hills", "cold", "near:ruins", "scholarly"] }],
      stages: {
        start: { h: "A warm wind from a hole near {place}", b: "Miners near {place} broke into a shaft that breathes warm air in the dead of winter. {person}, an old engineer, went down with a lamp.", wait: [2, 6], next: [{ to: "vanes_found", w: 2 }, { to: "shaft_sealed", w: 1, mods: [["pious", 2], ["zealous", 2]] }] },
        vanes_found: { h: "Turning bronze found beneath {place}", b: "{person} has come back with drawings of great bronze vanes, turning slowly in the dark, frost on one face and heat on the other.", wait: [4, 10], fx: { science: { natural_philosophy: 0.8 } }, next: [{ to: "engine_woken", w: 1, mods: [["learned", 2], ["scholarly", 2]] }, { to: "engine_broken", w: 1 }, { to: "lord_seizes", w: 1, mods: [["autocracy", 2]] }] },
        shaft_sealed: { h: "The priests seal the shaft at {place}", b: "The priests say the warm air is the breath of a sleeping evil that must not be woken. The shaft is filled with rubble and salt.", fx: { stability: 2 }, end: true },
        engine_woken: { h: "The valley at {place} turns green", b: "{person} and the miners freed the great vanes, and they turn faster now. For three leagues around {place}, the snow is melting in midwinter.", fx: { discovery: "natural_philosophy", growth: 0.002, prestige: 10, monument: { tier: 1, name: "The Vanes of {place}" } }, end: true },
        engine_broken: { h: "The vanes break beneath {place}", b: "A shriek of metal from the shaft, and the warm wind stopped. The cold that night was worse than any in living memory.", fx: { pop: 0.9, unrest: 10 }, end: true },
        lord_seizes: { h: "The lord of {place} claims the warm shaft", b: "The engine's warmth is now a lordly privilege: the lord's gardens bloom, and the town outside the wall freezes.", fx: { unrest: 15, treasury: 20 }, end: true },
      } },
  ],

  cast: [
    { role: "investigator", n: "a court astronomer who measures the sun's width at each solstice", home: "mountain", stance: "Knows the sun is shrinking and wants to be wrong; publishes nothing and keeps measuring." },
    { role: "official", n: "a granary-warden of the crown who keeps the grain counts and the charter rolls", home: "capital", stance: "Believes panic kills more people than cold, and keeps the figures out of sight." },
    { role: "believer", n: "a fire-priest who teaches that the god-king's fire holds the sun in place", home: "inner", stance: "Wants every hearth fed and the boy-king crowned; sure the sun will come back if the fire is kept." },
    { role: "survivor", n: "a watchman, once a bread-thief, who has seen the cold-walkers up close and lived", home: "border", stance: "Wants the south to believe the Watch before the wall is empty." },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "the royal chronicle of {realm}", text: "From the royal chronicle of {realm}, preface to the {year} edition: 'The so-called Long Dark, said in the north to be a winter of years under a red sun, is a nursery tale. The great winters of record were ordinary hard seasons, exaggerated by frightened chroniclers. The present edition removes the eleven pages devoted to them in the last, to save paper and prevent alarm.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "children of {place}, recorded by {investigator}", text: "Skipping rhyme sung by the children of {place}, written down by {investigator} in {year}: 'When the sun goes red and the swallows stay, bake bread for seven years and pray.' The astronomer's note: 'The last Long Dark lasted seven years by the Watch rolls. The children are better informed than the court. The swallows here did not leave this autumn.'" },
    { depth: "lore", about: "truth", source: "archive", bias: "true", reliable: true, who: "the muster roll of the Watch", points: "site:oldest_wall", text: "Muster roll of the Watch on the ice, compared with the roll of three centuries ago, {year}: 'Then: two thousand sworn watchmen on the wall. Now: one hundred and eleven, of whom sixty are convicted thieves, among them {survivor}. Four watchmen to hold the old gate at {lead}. Fire-glass on hand: none. Blankets: seventy.' Signed by the Ice-Warden, who has asked for more blankets." },

    { depth: "core", about: "truth:cold_masters", source: "ruin", bias: "true", reliable: true, plain: true, who: "the treaty stone under the old gate", text: "Reading of the treaty stone under the old gate, made in {year} by {survivor} and a herder from beyond the ice who knows the frost-script: 'The Rime Court gives the crown the summer lands south of this stone, for one promise kept.' Below, cut later and in frost-shapes only: 'Broken. We will collect each time the year turns.' The herder says that line was added in the first Long Dark, and that every child beyond the ice knows what the promise was." },
    { depth: "core", about: "truth:cold_masters", source: "oral", bias: "garbled", reliable: "partial", who: "a herder from beyond the ice", points: "sub:ice_refugees", text: "Testimony of a herder who crossed the ice with 200 reindeer, through a Watch interpreter, {year}: 'The winter has a queen. She is not cruel, only owed. Your kings took the warm grass and gave her a word, and the word was a lie. We are not running from her. We are getting out of the way.' The Watch's report on the clan, camped by the wall and refusing to move on, is at {lead}." },
    { depth: "core", about: "truth:cold_masters", source: "person", bias: "exaggerated", reliable: "partial", cost: true, who: "{survivor}, watchman, to family", text: "Letter of {survivor}, watchman, to family in {place}, {year}: 'They do not attack. They walk, and we die of the cold they carry. {person} died standing at the post beside me, the spear still upright, eyes open. One of them looked at me afterwards. It looked sad, Mother. It looked like it was waiting for an apology. I have 40 days left to serve.'" },
    { depth: "core", about: "truth:cold_masters", source: "archive", bias: "redacted", reliable: "partial", who: "{official}, keeper of the charter rolls", points: "archive", text: "Inventory note of {official}, keeper of the charter rolls, {year}: 'Item 1: the founding charter of the first southern crown, vellum, one sheet. One clause cut out with a knife, about four lines. The remaining text reads: in return for which the Crown swears... The missing piece is not in the roll-chest. The older charter copy at {lead} has not been checked, by order.'" },
    { depth: "core", about: "truth:cold_masters", source: "library", bias: "official", reliable: false, who: "the crown's office of the north", text: "Circular of the crown's office of the north to all magistrates, {year}: 'There is no people beyond the ice. The cold-walkers described in old Watch reports are frostbitten deserters, seen through snow-blindness. Watch reports of tall grey figures are to be filed, not forwarded. Magistrates who forward them will bear the cost of the courier, currently three crowns.'" },

    { depth: "core", about: "truth:moved_sun", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, fire-priest", text: "The fire-hymn, as {believer} has it sung at the fire-temple of {place}, with a sermon note, {year}: 'Our father pulled the sun to us with a rope of a thousand hands. Feed the fire, that it does not slip.' The note: 'The rope is a figure for prayer. Every household is to bring one log to the temple fire each week. Nine hundred logs came last week.'" },
    { depth: "core", about: "truth:moved_sun", source: "library", bias: "true", reliable: true, plain: true, who: "{investigator}, court astronomer", text: "Unpublished memorandum of {investigator}, court astronomer, {year}: 'The sun is moving away from us. The solstice tables of this observatory, two centuries apart, show its width shrunk by a twentieth part. The oldest tables, from the god-king's reign, show it far larger. It was pulled close once, by force, and it is sliding back. The second table is marked not for copying. I have copied it.'" },
    { depth: "core", about: "truth:moved_sun", source: "heretic", bias: "heretic", reliable: "partial", who: "an unsigned pamphlet", points: "site:star_chart_cave", text: "Unsigned pamphlet found in the market at {place}, {year}, printed on one side: 'The god-king did not save us. He borrowed the sun on our grandchildren's credit, and the debt is being called. Four thousand slaves hauled it. Go and count them yourself on the cave wall at {lead}. Then ask the fire-priests why they sing about it.'" },
    { depth: "core", about: "truth:moved_sun", source: "temple", bias: "official", reliable: false, who: "the fire-temple's council", text: "Ruling of the council of the fire-temple, {year}, read at every altar: 'The redness of the sun is the dust of distant fires and will pass. The sun was set in its place on the first day and has never moved. The hymn of the rope is not to be read as history. Astronomers who say otherwise are to be refused the sacrament until they recant.'" },
    { depth: "core", about: "truth:moved_sun", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a farmer of {place}", text: "Petition of {person}, a farmer of {place}, to the crown, {year}: 'Three summers of snow. My youngest died in the second. {believer} says the sun will come back if the fire is fed, so I have burned my barn, my cart and my plough at the temple, one log a week. The sun is still red. I ask the crown for seed, and for someone who can tell me the truth.'" },

    { depth: "core", about: "truth:broken_seasons", source: "ruin", bias: "true", reliable: true, plain: true, who: "a bronze plate in the old north", points: "site:warm_valley", text: "Bronze plate on the shaft wall under the green valley, copied by {investigator} in {year}: 'The year swings because the world is cracked. These vanes hold it steady. Turn the vanes at each solstice with the key. If the vanes stop, the year will swing like a broken door, wider each time.' The plate lists eight sister engines. The shaft is at {lead}." },
    { depth: "core", about: "truth:broken_seasons", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a tinker passing through the north", points: "site:warm_valley", text: "A tinker's account of the northern road, sold as a pamphlet in {year}: 'There is a valley up there where it is summer forever and the ground hums. I slept one night in the grass and dreamt of turning wheels. The goats there are fat in midwinter. The herders charged me one silver to sleep there and would not take a second.' The valley lies near {lead}." },
    { depth: "core", about: "truth:broken_seasons", source: "library", bias: "garbled", reliable: "partial", who: "{investigator}, court astronomer", text: "Working notes of {investigator}, court astronomer, {year}: 'Each cold cycle in the Watch rolls is longer than the one before by a fixed ratio: four years, then five, then seven. The weather is winding down, not raging. A storm does not keep time. A clock running out does.' The notes break off with a sum that comes to eleven years." },
    { depth: "core", about: "truth:broken_seasons", source: "archive", bias: "official", reliable: false, who: "{official}, for the crown survey", text: "Report of the crown survey of the north to the crown, {year}, countersigned by {official}: 'The warm valleys of the north are of volcanic origin only. The machinery reported there is natural columnar rock, which forms in regular shapes. The survey recommends the valleys be leased for grazing at two crowns a year. No further survey is needed.'" },
    { depth: "core", about: "truth:broken_seasons", source: "archive", bias: "true", reliable: "partial", cost: true, who: "{person}, last Ice-Warden of the Watch", text: "Last order of {person}, Ice-Warden of the Watch, nailed up at the old gate at the end of the last Long Dark: 'I take the turning key and forty watchmen north to the eight engines. If the vanes turn, spring will follow. Do not send after us.' Spring followed within the year. None of the forty came back, and the key has not been seen since." },

    { depth: "sub", about: "sub:long_autumn", source: "archive", bias: "redacted", reliable: "partial", who: "{official}, granary-warden", points: "cast:official", text: "Granary count of {realm}, month eleven of {year}, signed by the crown's granary-warden: 'Stores of wheat, barley and rye in the 14 crown granaries: sufficient for [figure inked over].' A clerk's note in the margin: 'Figure removed by order of the warden. The full count goes only to the warden, {lead}. Bread price in {place} up a third since spring.'" },
    { depth: "sub", about: "sub:watch_on_ice", source: "person", bias: "true", reliable: true, who: "{survivor}, watchman", text: "Diary of {survivor}, watchman, first winter on the wall, {year}: 'They told me at the court in {place} that I was serving the realm instead of hanging. I am serving a wall nobody visits, against an enemy nobody believes in, beside 60 men who stole bread. I stole bread. The brazier ration is one log an hour. I have started to believe in the enemy.'" },
    { depth: "sub", about: "sub:risen_snow_dead", source: "oral", bias: "garbled", reliable: "partial", who: "the headman of {place}", text: "Order of the headman of {place}, posted on the chapel door after the first snow of {year}: 'If your father comes home after the first snow, do not let him in. He will be cold, and he will want to be warm, and he will take yours. Burn the winter dead before the third day. Wood for the burning is to be taken from the common store, two cords a body.'" },
    { depth: "sub", about: "sub:southern_quarrels", source: "library", bias: "propaganda", reliable: false, who: "a proclamation of the regent of {realm}", text: "Proclamation of the regent of {realm}, {year}: 'The war of succession is the gravest danger to the realm. Every levy is needed in the south until the pretender is defeated, which will be by spring. Rumours of northern troubles are spread by the pretender's agents. The Watch's request for 500 men is refused as untimely.'" },
    { depth: "sub", about: "sub:red_sun", source: "person", bias: "true", reliable: "partial", who: "{investigator}, to a colleague", points: "library", text: "Letter of {investigator}, court astronomer, to a colleague at {lead}, {year}: 'I have measured it eleven times, with the brass ring and with the smoked glass. The sun is smaller than in my teacher's tables. I will not publish. I have two children and I would like them to keep sleeping. If you measure it yourself, do it at noon and do it alone.'" },
    { depth: "sub", about: "sub:old_north_weapon", source: "archive", bias: "garbled", reliable: "partial", who: "the Watch records of the last Long Dark", points: "site:glassfire_mine", text: "Watch records of the last Long Dark, seventh year, copied by a clerk who misread half of it: 'The Ice-Warden went north with the black glass and the key. The cold broke at the passes. The Ice-Warden did not return; neither did the key.' A later hand adds: 'The glass came from the pits at {lead}. Pits closed by the crown, to save forty crowns a year.'" },
    { depth: "site", about: "site:kneeling_city", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a fur trader", text: "Account of a fur trader who crossed the ice-city at noon in {year}: 'I walked over them for an hour, about three thousand under the ice, all kneeling. They were all facing north, every one, in summer linen. I lay down over the palace and looked at the king. I swear the king's eyes moved. I sold the sledge to the Watch and walked home.'" },
  ],
};
