// The Pale Visitor: a silent orb hangs over the last great city; it gave a golden age, then something followed it here.
export default {
  id: "pale_visitor",
  name: "The Pale Visitor",
  family: "world",
  kind: "cosmic",
  pitch: "A huge white orb hangs low over the last great city. It brought a golden age long ago, and a dark power followed it here and still circles the world.",
  slots: ["divine-order", "apocalypse"],
  tone: ["wonder", "melancholy"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "mythic", "flintlock"],
  w: 1,
  excludes: ["last_kindling", "sleeper"],
  pairs: [{ id: "elder_lattice", w: 3 }, { id: "ward_walls", w: 2.5 }, { id: "leavings", w: 2 }, { id: "unremembering", w: 1.5 }],

  // the hidden truth: a world picks one
  truths: [
    { id: "refugee", n: "The Lantern is hiding", d: "The orb did not come to give. It fled an enemy across the space between stars and hid here, choosing the city with the highest walls. Every gift it granted was payment for protection: the Lit are not its knights but its shield, and they die so it does not have to. The founders agreed to this on behalf of their children.", tags: ["truth:visitor_refugee"],
      known: [
        "The Church teaches that the Lantern came freely to raise a worthy people. The only surviving line of the arrival record says it 'came down in fear', and the rest was burned with its translator.",
        "A dying Lit captain called the Lit the orb's 'shutters', not its knights. A golden-age wall far from the city says the orb fled past and 'chose the city with the higher walls'.",
        "The sealed chamber at the city's heart held twelve cradles, and its floor is scratched 'It asked us to hide it'. The Lit are guttering out, and the Church has hidden the count.",
        "Confirmed: the orb is a fugitive. The founders took its gifts in exchange for a promise that their children would stand between it and the dark. The Lit are that promise, and they are being spent.",
      ] },
    { id: "gardener", n: "The world is soil", d: "The orb is a sower of worlds, and the golden age was a planting; the city and the halo fields are test plots, replanted to the same spiral after every harvest. The Follower is a rival that cuts back whatever the orb grows. Neither sees the people of the world as anything more than a crop, and the yields are being written down.", tags: ["truth:visitor_gardener"],
      known: [
        "Land inside the halo is worth ten times land outside it. The Royal Survey credits the Lantern's warmth. An agronomist says the halo fields are replanted to one spiral pattern after every harvest, by no visible hand.",
        "Where the Follower passed, golden-age roads and orchards crumbled and the native scrub was untouched. A caravan-master called it weeding. A round orchard in the desert follows the same spiral as the halo.",
        "A seed-vault inscription reads 'Fourth planting. Mark the yield; the pruner will come.' The peak colonists bless strangers with 'may you be a good harvest'. A climber who stayed with them has not come back.",
        "Confirmed: the orb plants worlds, and the Follower prunes them. The city is a test plot. The people in it are counted as yield, by both of them, and the vault keeps the tally.",
      ] },
    { id: "one_being", n: "Light and shadow are one", d: "The Lantern and the Follower are two halves of one being, split long ago: one gives, the other tests. The Follower was here first, buried in the ice four thousand years before the orb came, waiting with carvings of its other half. In this world the halves will either rejoin or destroy each other, and the Lit are dying in the quarrel.", tags: ["truth:visitor_one_being"],
      known: [
        "The Church says the Follower is a mindless hunger that cannot speak. Shadow-Hearers say it offers tests instead of gifts. Scouts who reach the black slab in the waste come back calm and never pray again.",
        "A Lit deserter says the dark spoke in the Lantern's own voice. A child in a poor quarter says the orb is 'ashamed' and 'left without saying goodbye'. The Church took the child away.",
        "A black spire in the northern ice is four thousand years older than the orb's arrival. Its walls are covered in carvings of the orb and the word 'return', and the Shadow-Hearers go there to listen.",
        "Confirmed: the Lantern and the Follower are halves of one being. The Follower came first and waited. Their reunion or their war will be fought over the city, and the Lit are its casualties.",
      ] },
  ],

  tags: ["visitor"],

  subthemes: [
    { id: "lantern_stirs", n: "The Lantern Stirs", d: "For the first time in centuries the orb has moved: a slow turn, a wash of light over the city. The Church calls it a blessing. The old Lit are afraid.", w: 1.4, req: { any: ["pious", "has:city", "faith:sun", "organised"] }, tags: ["theme:lantern_stirs"] },
    { id: "guttering_lit", n: "The Guttering Lit", d: "One by one, the orb's chosen warriors are losing their light. Some wake ordinary; some never wake. The Order hides the count.", w: 1.3, req: { any: ["martial", "standing_army", "gov:theocracy", "militant"] }, truthLink: "refugee", tags: ["theme:guttering_lit"] },
    { id: "black_vessel", n: "A Black Vessel in the Waste", d: "A smooth black slab, too regular to be natural stone, has come down in the far wastes. Every scout sent to it returns unhurt and calm, and none of them pray any more.", w: 1, req: { any: ["desert", "cold", "badlands", "steppe"] }, truthLink: "one_being", tags: ["theme:black_vessel"], mark: { kind: "zone", n: "The Black Landing", color: "#2a2a35", size: [1, 3], where: "remote" } },
    { id: "unlit_hills", n: "The Unlit Hills", d: "Hill clans who never took the orb's gifts and never fled to its city. They have survived three sieges of the dark on their own, and the Church cannot forgive them for it.", w: 1.1, req: { any: ["tribal", "egalitarian", "mountain", "hills", "insular"] }, tags: ["theme:unlit"], mark: { kind: "zone", n: "Unlit hills", color: "#6a6a52", size: [2, 4], where: "mountain" } },
    { id: "fallen_shard", n: "The Fallen Shard", d: "A splinter of the orb fell in the night and came down beyond the border. It is still warm. Three realms have sent armies to fetch it.", w: 0.9, req: { any: ["frontier_forts", "martial", "realm:large", "realm:mid"] }, tags: ["theme:fallen_shard"] },
    { id: "hearing_child", n: "The Child Who Hears It", d: "A child in a poor quarter says the orb speaks to her in dreams, and she repeats words in a language nobody living knows. The Church wants her silent; the Archive wants her fed and watched.", w: 0.8, req: { any: ["seers", "mystic", "faith:stars"] }, truthLink: "one_being", tags: ["theme:hearing_child"] },
    { id: "mountain_colony", n: "The Colony on the Peak", d: "Climbers found a golden-age settlement on a high peak, still lit, still farming, its people centuries old and very polite. They say they are waiting for 'the sower' to return.", w: 0.7, req: { any: ["mountain", "cold", "mountain_folk"] }, truthLink: "gardener", tags: ["theme:peak_colony"] },
    { id: "burned_translation", n: "The Burned Translation", d: "An archivist translated the record of the orb's arrival. The Church burned it and her with it, but copies are moving through the universities.", w: 1, req: { any: ["scholarly", "academies", "zealous", "gov:theocracy"] }, truthLink: "refugee", tags: ["theme:arrival_record"] },
    { id: "halo_harvests", n: "The Halo Harvests", d: "Close to the orb, wheat ripens twice a year and nobody falls sick. Further out, the fields are thin and the winters long. The line between is guarded, and land inside it is worth a duchy.", w: 1.2, req: { any: ["river", "warm", "grass", "has:city"] }, truthLink: "gardener", tags: ["theme:halo_lands"], mark: { kind: "zone", n: "The halo fields", color: "#c8d68a", size: [2, 5], where: "capital" } },
    { id: "shadow_hearers", n: "The Shadow-Hearers", d: "Cults that listen to the Follower. It offers no gifts, only struggle, and promises that those who survive its tests will need no god at all.", w: 0.9, req: { any: ["faith:void", "sacrifice", "harsh_law", "warrior_code"] }, truthLink: "one_being", tags: ["theme:shadow_hearers"] },
    { id: "pruned_lands", n: "The Pruned Lands", d: "Where the Follower passed, every golden-age thing withered at once: orchards, roads, even the stones of old towers. The native scrub came back untouched.", w: 0.8, req: { any: ["desert", "badlands", "dryforest", "savanna"] }, truthLink: "gardener", tags: ["theme:pruned_lands"] },
    { id: "lit_quarrel", n: "The Quarrel of the Lit", d: "The orb's warriors are split: half say the Lantern deserves their deaths, half say it has never once answered a question. Both halves are armed.", w: 0.8, req: { any: ["monarchy", "autocracy", "realm:large", "realm:vast"] }, truthLink: "refugee", tags: ["theme:lit_quarrel"] },
  ],

  sites: [
    { id: "shadow_line", n: "The Shadow-Line of $", kind: "anomaly", where: "any", d: "A strip of glassy earth where the orb's shadow falls at the same hour every day.",
      layers: {
        surface: { n: "The glass road", text: "A narrow road of fused earth, glassy and green-black, runs out from the city. Pilgrims walk it barefoot at noon, when the orb's shadow lies along it. The sacred stretch is thirty miles long, and the Church sells a pair of linen foot-wraps at the start." },
        study: { n: "Dead straight", text: "It is not a shadow's path, since a shadow would swing with the seasons. The glass runs dead straight toward one spot on the horizon, summer and winter. {investigator} sighted along it with a brass level and found it true to a hand's width over ten miles." },
        dig: { n: "The causeway", text: "Beneath the glass lies a causeway of golden-age stone, older than the city, running the same way. Its kerbstones are numbered, counting down; the lowest number found is 112. The archivist {lead} keeps the unfinished map of the causeway.", points: "cast:investigator" },
        revelation: { n: "The gaze", text: "Since the day it arrived, the orb has kept its face toward one place beyond the horizon. The golden-age builders paved its gaze as a road and numbered the stones down toward whatever it watches. The Church has never let anyone walk the road past mile thirty." },
      } },
    { id: "warm_shard", n: "The Warm Stone of $", kind: "dig", where: "border", d: "A fallen shard of the orb, still warm after a hundred years.",
      layers: {
        surface: { n: "The crater", text: "A pale stone sits in a crater beyond the border, ringed by offerings and soldiers. It has been warm for a hundred years, and snow never lies within ten paces of it. The guard is changed every six days, for a reason the duty roster does not give." },
        study: { n: "Numb hands", text: "A brief touch heals wounds. A long touch leaves the hand numb to cold, and the person stops feeling fear. The six-day limit was set after a whole guard company, 80 strong, walked out into the waste one morning, singing." },
        dig: { n: "The hollow", text: "Under the stone the earth is hollowed in the exact shape of a curled human body, knees to chest. In the hollow lies one grey hair, longer than a person is tall. The duty log of the first guard company is kept at {lead}.", points: "archive" },
        revelation: { n: "Old skin", text: "The shard did not break off. The orb shed it, the way a snake sheds a skin it has outgrown, and whatever lay curled inside has gone. The Church has guarded an empty shell for a century. It has cost one company of eighty, and six fearless days from every soldier posted since." },
      } },
    { id: "ice_vessel", n: "The Frozen Spire of $", kind: "dig", where: "remote", truthLink: "one_being", d: "A black spire locked in ice that has not melted for longer than the orb has been in the sky.",
      layers: {
        surface: { n: "The Tooth", text: "A dark peak stands out of a glacier in the far north. Hunters call it the Tooth and camp in its lee, because the wind breaks on it. Their fire-rings go back generations, and one is lined with the skulls of seals." },
        study: { n: "Older than the orb", text: "{investigator} counted the ice layers in a crevasse beside it, one band per winter. The black spire was buried about four thousand winters before the orb appeared in the sky. Its sides are smooth as glass and faintly warm." },
        dig: { n: "Portraits", text: "Inside, the walls are covered in careful, affectionate carvings of the orb, hundreds of them, like portraits of a missing relative. One shows the orb and the spire side by side, touching. A Shadow-Hearer, {lead}, carried a rubbing of it back from the ice.", points: "cast:believer" },
        revelation: { n: "It came first", text: "The Follower did not follow the orb here. It arrived four thousand years earlier and waited in the ice for its other half. The two were one being once, split into a giver and a tester. The Church was built on one side of their quarrel, and the Lit have died for that side." },
      } },
    { id: "desert_garden", n: "The Round Garden of $", kind: "wonder", where: "desert", truthLink: "gardener", d: "A perfect circle of orchard in the middle of the desert, the exact shape and size of the orb.",
      layers: {
        surface: { n: "The mercy", text: "A perfect circle of orchard, fig and pomegranate a mile across, stands in a waterless waste. Desert folk call it a mercy and take only fruit that has fallen. A clay jar at the edge holds coins left by caravans, and nobody steals from it." },
        study: { n: "One planting", text: "Every tree is the same age, and every row follows a spiral that matches the halo fields around the city. {investigator} counted 1,440 trees. The circle is the exact width of the orb as measured from the city walls." },
        dig: { n: "The seed-vault", text: "The roots go down to a buried seed-vault of golden-age make, still tending the trees with water from no visible source. Its door carries the same inscription as a vault in the ruins at {lead}.", points: "ruin" },
        revelation: { n: "The test plot", text: "The orb plants worlds the way farmers plant fields. This garden is a test plot, and so is the city. The vault keeps a tally of yields by season, and the city is on it beside the figs. The city's column is longer, and it has a mark beside it for the pruning." },
      } },
    { id: "first_touch", n: "The Chamber of First Touch in $", kind: "shrine", where: "capital", truthLink: "refugee", d: "The sealed room at the heart of the city where the orb first touched the ground.",
      layers: {
        surface: { n: "The sealed shrine", text: "At the heart of the city stands a shrine no layperson has entered in four hundred years. Its bronze doors are sealed with lead, renewed by the Church every year at a cost of sixty crowns. Pilgrims press their ears to the doors and say they hear breathing." },
        study: { n: "Records that stop", text: "The Church's records of the chamber stop on the day the Follower first appeared in the sky. The last entry is a list of supplies: oil, bread, twelve blankets. {official} keeps the record book and will not say who ordered the chamber closed." },
        dig: { n: "The scratches", text: "Scratched into the floor in golden-age script, over and over, are the words 'It asked us to hide it'. There are three hundred repetitions, in at least nine hands. The founders' charter, which should explain them, is kept at {lead}.", points: "archive" },
        revelation: { n: "The bargain", text: "The founders did not receive a god. They sheltered a fugitive, and for long life and full barns they promised that their children would fight and die to protect it. The twelve cradles held the first Lit. The Church renews the promise every year, for children not yet born." },
      } },
  ],

  beings: [
    { id: "lit_mote", n: "Lantern-mote", kind: "small", d: "A tiny drifting light that attends the Lit, chiming softly. Unattended motes wander the halo fields at dusk like lost bees.", danger: 0, biomes: ["grass", "tempforest", "savanna", "dryforest"], look: { size: 0.2, group: [1, 6], move: "swarm", speed: 6, col: "#f4f0d8", col2: "#d8c87a", body: "insect", active: "dusk", visible: true } },
    { id: "glassback", n: "Glassback", kind: "beast", d: "A grazer of the waste whose hide has turned to dark glass where the Follower passed. It is calm, unafraid and almost impossible to kill.", danger: 2, biomes: ["desert", "badlands", "colddesert", "coldsteppe"], look: { size: 2.4, group: [1, 3], move: "solo", speed: 5, col: "#1e1e28", col2: "#5a5a7a", body: "quad", active: "any", visible: true } },
    { id: "shade_hound", n: "Shade-hound", kind: "predator", d: "A wolf touched by the Follower: grey-black, silent, and tireless. It hunts the Lit above all other prey.", danger: 3, biomes: ["boreal", "tempforest", "coldsteppe", "tundra", "badlands"], look: { size: 1.6, group: [3, 7], move: "pack", speed: 13, col: "#2a2a30", col2: "#4a4a5a", body: "quad", active: "night", visible: true } },
    { id: "gilded_tender", n: "Gilded tender", kind: "beast", d: "A golden-age construct of brass and pale stone that still walks the old terraces, pruning trees nobody planted in a thousand years.", danger: 1, biomes: ["alpine", "grass", "tempforest", "dryforest"], look: { size: 2, group: [1, 2], move: "solo", speed: 3, col: "#b89a5a", col2: "#e8e0c8", body: "biped", active: "day", visible: true } },
  ],

  techs: [
    { id: "pv_halo_tilling", n: "Halo tilling", field: "agriculture", level: 1, d: "Fields laid in spirals around the orb's light, doubling the harvest inside the halo." },
    { id: "pv_arrival_reckoning", n: "The Arrival Reckoning", field: "astronomy", level: 2, d: "A calendar that counts from the day the orb arrived, and tracks the slow drift of its shadow." },
    { id: "pv_shard_lamps", n: "Shard-lamps", field: "arcana", level: 2, d: "Slivers of fallen orb set in glass, giving light without fire and warding off the shade-hounds." },
    { id: "pv_glass_walls", n: "Glass-earth walls", field: "architecture", level: 3, d: "Walls fired from the fused earth of the shadow-line, which the Follower's beasts will not cross." },
    { id: "pv_second_rising", n: "The second rising", field: "medicine", level: 4, d: "The orb's own art of raising the fallen Lit, learned in part. Each time someone is raised, they come back with less of their memory." },
    { id: "pv_shadow_lens", n: "The shadow-lens", field: "natural_philosophy", level: 5, d: "A lens that shows where the Follower is, as the Lantern sees it. People who use it for long stop fearing the dark, which alarms everyone around them." },
  ],

  units: [
    { id: "pv_lit", n: "The Lit", role: "magic", wpn: "sword", kit: "plate", ranks: 2, gap: 2.5, size: 30, w: 1.5, mods: [["theme:guttering_lit", 4], ["theme:lit_quarrel", 3], ["gov:theocracy", 2]] },
    { id: "pv_shadow_hearers", n: "Shadow-hearer band", role: "infantry", wpn: "axe", kit: "hide", ranks: 3, gap: 1.6, size: 80, w: 0.5, mods: [["theme:shadow_hearers", 8]] },
  ],

  faiths: [
    { id: "pv_still_lantern", n: "The Still Lantern", d: "The orb is god, its silence is wisdom, and to ask it questions is pride.", tags: ["faith:still_lantern", "organised"], w: 1.2, names: ["The Church of the Still Lantern", "The Light over $", "The Silent Gift"], mods: [["pious", 2], ["theme:lantern_stirs", 3], ["theme:halo_lands", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Black glass plains", color: "#22222c", size: [2, 4], count: [1, 2], where: "desert", d: "Plains fused to black glass where the Follower's vessels came down during the Fall." },
    { kind: "zone", n: "Golden-age terraces", color: "#d4b870", size: [1, 3], count: [0, 2], where: "mountain", d: "Overgrown terraces and roads of the golden age, too perfect to have been built by hand." },
  ],

  storylines: [
    { id: "pv_lantern_wakes", n: "The Light over {capital}", scale: "realm", anchor: "realm", w: 1.5, req: ["visitor", { any: ["pious", "has:city", "organised"] }],
      stages: {
        start: { h: "The orb turns above {capital}", b: "For the first time in living memory the white orb has moved. Light pours over {capital}, and the bells of {faith} ring for three days.", wait: [2, 5], fx: { stability: 3 }, next: [{ to: "gifts_return", w: 2 }, { to: "follower_answers", w: 1, mods: [["frontier_forts", 1.5], ["theme:black_vessel", 3]] }] },
        gifts_return: { h: "Miracles in the streets of {capital}", b: "The sick are rising from their beds and the old Lit feel their light return. {person}, a baker's apprentice, woke this morning glowing like a lamp.", wait: [3, 8], fx: { prestige: 6, growth: 0.003, flag: "gifts" }, next: [{ to: "called_to_arms", w: 2 }, { to: "question_asked", w: 1, mods: [["scholarly", 2], ["academies", 2], ["theme:arrival_record", 3]] }] },
        follower_answers: { h: "The dark gathers beyond the borders of {realm}", b: "Scouts report the shade-hounds massing in their thousands at the edge of the waste. The orb's light, it seems, can be seen from very far away.", wait: [2, 6], fx: { unrest: 10 }, next: [{ to: "called_to_arms", w: 2 }, { to: "truce_offered", w: 1, mods: [["theme:shadow_hearers", 3], ["theme:hearing_child", 2]] }] },
        called_to_arms: { h: "{ruler} raises the Lit for a new siege", b: "Every new-lit youth of {realm} has been summoned to the walls. {person} is among them; the Church says it is an honour, and mothers are hiding their glowing children in cellars.", wait: [4, 10], fx: { unrest: 12, flag: "siege" }, next: [{ to: "siege_held", w: 2, mods: [["martial", 1.5], ["standing_army", 1.5]] }, { to: "siege_broken", w: 1, mods: [["unstable", 2], ["poor", 1.5]] }] },
        question_asked: { h: "A scholar of {capital} asks the orb a question", b: "Against the Church's law, {investigator}, an archivist, climbed the highest tower in {capital} and asked the orb aloud why it came. That night the orb dimmed, and has not brightened since.", wait: [3, 8], fx: { stability: -6 }, next: [{ to: "answer_given", w: 1, mods: [["learned", 2]] }, { to: "called_to_arms", w: 1 }] },
        truce_offered: { h: "The Follower sends an envoy to {realm}", b: "A figure of grey glass walked unharmed to the gates of {capital} and offered peace: the orb for the realm. {ruler} has not yet answered.", wait: [2, 6], next: [{ to: "orb_betrayed", w: 1, mods: [["ruler:cruel", 2], ["ruler:paranoid", 2], ["theme:shadow_hearers", 2]] }, { to: "called_to_arms", w: 2 }] },
        siege_held: { h: "The walls of {capital} hold against the dark", b: "The Lit held the walls through the long nights, and the dark withdrew. Half of them did not wake on the last morning. {person} is to be honoured with a statue.", fx: { prestige: 10, pop: 0.9, monument: { tier: 1, name: "The Statue of {person}" } }, end: true },
        siege_broken: { h: "The dark breaks into the halo of {realm}", b: "The shade-hounds came over the wall at the third gate. The halo fields around {capital} are ash, and the orb has drawn itself higher into the sky.", fx: { stability: -20, pop: 0.75, abandon_town: true }, end: true },
        answer_given: { h: "{investigator} comes down from the tower", b: "The archivist has written down what the orb said, and refuses to tell anyone but the archive. The Church calls for a burning; the students of {capital} are guarding the archive doors.", fx: { discovery: "astronomy", unrest: 15 }, end: true },
        orb_betrayed: { h: "{ruler} accepts the Follower's peace", b: "The Lit have been ordered to lay down their light. The dark has kept its word so far: no hound has crossed the border since. Some say the orb is weeping.", fx: { stability: -10, prestige: -10, flag: "betrayed" }, end: true },
      } },
    { id: "pv_shard_race", n: "The Warm Stone of {place}", scale: "realm", anchor: "frontier", w: 1.2, req: ["visitor"],
      stages: {
        start: { h: "A piece of the orb falls near {place}", b: "A streak of white fire came down beyond {place} last night. Shepherds say the stone it left is warm and sings when the wind blows.", wait: [1, 3], next: [{ to: "race", w: 2 }, { to: "pilgrims", w: 1, mods: [["pious", 2], ["pilgrims", 3]] }] },
        race: { h: "Armies march on the warm stone at {place}", b: "{realm} has sent riders under {person} to claim the shard before anyone else can. Banners of other realms have been seen on the far ridge.", wait: [2, 6], fx: { unrest: 5 }, next: [{ to: "claimed", w: 2, mods: [["martial", 1.5]] }, { to: "border_war", w: 1, req: "has:rival", mods: [["has:rival", 2]] }, { to: "hounds_first", w: 1 }] },
        pilgrims: { h: "Pilgrims crowd the crater at {place}", b: "Thousands have come to touch the stone, and the lame walk away straight. {person}, a hermit, has taken charge of the crater as its keeper.", wait: [3, 8], fx: { stability: 4 }, next: [{ to: "race", w: 1 }, { to: "shrine_raised", w: 1, mods: [["pious", 2]] }] },
        claimed: { h: "The warm stone is carried into {capital}", b: "{person} brought the shard home in a lead-lined cart. It has been set in the cathedral, and the halo fields around {capital} have spread a mile.", fx: { prestige: 8, growth: 0.003 }, end: true },
        border_war: { h: "Blood spilled over the stone at {place}", b: "Riders of {realm} and {rival} met at the crater. Neither side will retreat, and both claim the stone is theirs by the gods' will.", fx: { war: "rival", relation: { rival: -25 } }, end: true },
        hounds_first: { h: "The shade-hounds reach the stone first", b: "The riders found the crater empty, the earth around it scorched black. Tracks of a great pack lead back toward the waste.", fx: { stability: -5, prestige: -4 }, end: true },
        shrine_raised: { h: "A shrine rises over the stone at {place}", b: "The hermit {person} and the pilgrims have walled the crater and named it holy ground. The crown has decided, for now, to let them be.", fx: { monument: { tier: 1, name: "The Shrine of the Warm Stone" }, stability: 3 }, end: true },
      } },
  ],

  cast: [
    { role: "investigator", n: "an archivist of the city Archive who reads golden-age script", home: "capital", stance: "Wants the arrival record translated again, and knows what happened to the last translator." },
    { role: "official", n: "a deacon of the Church who keeps the roll of the Lit", home: "inner", stance: "Believes the city stands only while people trust the Lantern, and hides every count that might shake it." },
    { role: "believer", n: "a Shadow-Hearer who walks the waste and listens to the Follower", home: "remote", stance: "Holds that the dark's tests make people free of gods, and wants the Lit to lay down their light." },
    { role: "survivor", n: "a Lit soldier of the walls whose light has guttered out", home: "border", stance: "Gave a youth to the Lantern and got no answer; wants to know what it was all for." },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "a child's primer of {realm}", text: "From a child's primer of {realm}, lesson one, {year} edition: 'The Lantern is the great white orb over our city. It came in the year of plenty and gave us long life and full barns. Then the dark came after it, which we call the Follower, and the Lantern lit our bravest children to fight it. These are the Lit. Count the Lit you know; most children know three.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "reapers of {place}, recorded by {investigator}", text: "Harvest rhyme sung by the reapers of {place} at the last sheaf, written down by {investigator} in {year}: 'Under the light the wheat grows twice; beyond the light, you pay the price; and what is in the light's own eye, the light itself won't say, nor why.' The archivist notes that the last line is sung quietly, and that the reapers stop if a deacon is in the field." },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a wool trader, writing home", points: "sub:unlit_hills", text: "Letter of a wool trader from the Unlit hills, {year}, kept at {lead}: 'Up here they spit when the orb is named, three times, into the fire. Their headwoman told me a god who gives and never speaks is not a god but a debtor, and that the bill always comes. They have held off the dark three times without one Lit among them. The wool is good and cheap.'" },

    { depth: "core", about: "truth:refugee", source: "archive", bias: "redacted", reliable: "partial", who: "the arrival record, one surviving line", points: "cast:investigator", text: "The only surviving line of the arrival record, on a scorched leaf of vellum two fingers wide: '...and it came down in fear, and the elders of the city... [burned] ...in exchange for the gifts, the bodies of our...' The rest burned with its translator in {year}. The archivist {lead} keeps the leaf and has asked twice for leave to translate it again." },
    { depth: "core", about: "truth:refugee", source: "person", bias: "true", reliable: true, plain: true, who: "a Lit captain, to a confessor", text: "Last confession of a Lit captain, taken down by the chaplain of the third gate, {year}: 'We are not its knights. We are its shutters. The Lantern fled something across the dark between stars and hid here, and it made us so there would be something between it and that. I held the gate for 31 years. It never once looked down. Put that in your book.'" },
    { depth: "core", about: "truth:refugee", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "a broadside nailed up in {place}", text: "Broadside nailed to the church door of {place}, {year}, signed only 'a parent': 'My child {person} was lit at nine and died at fourteen on the third gate, with 200 others, in one night. Why does the Lantern never leave the city? Why has it never once fought? Ask yourselves what a god is doing hiding behind children. I have stopped asking it.'" },
    { depth: "core", about: "truth:refugee", source: "ruin", bias: "true", reliable: true, who: "scratched on a golden-age wall", points: "site:first_touch", text: "Scratched on a golden-age wall 400 miles from the city, copied by {investigator} in {year}: 'It was bright when it fled past us. We begged it to stay and offered our town. It looked at us, and chose the city with the higher walls.' The archivist notes that the city's first chamber, at {lead}, was sealed in the same century." },
    { depth: "core", about: "truth:refugee", source: "temple", bias: "official", reliable: false, who: "the Church's creed", text: "From the creed of the Church of the Still Lantern, recited at every lighting of a child, {year}: 'The Lantern came freely, of its own grace, to raise a people worthy of it. That it was pursued is a slander of the Shadow-Hearers. The Lantern fears nothing.' This year 46 children were lit. The creed is said over each one." },

    { depth: "core", about: "truth:gardener", source: "library", bias: "true", reliable: "partial", who: "an agronomist of {realm}", points: "site:desert_garden", text: "Notebook of an agronomist of {realm}, {year}: 'The halo fields are not blessed. They are managed. Each spiral is replanted to the same pattern after every harvest, by no hand I can find. I marked 40 stalks with red thread; the new shoots came up in the same places, threads and all. The round orchard at {lead} is planted on the same spiral.'" },
    { depth: "core", about: "truth:gardener", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a caravan-master", points: "sub:pruned_lands", text: "A caravan-master, writing up the route for the guild in {year}: 'Where the dark passed, the old golden-age roads crumbled like bread, and the stone towers fell in a week. The thornbush beside them did not lose a leaf. Whatever it is, it was weeding. Avoid the pruned country; there is nothing left to water a camel. The guild's map of it is at {lead}.'" },
    { depth: "core", about: "truth:gardener", source: "ruin", bias: "true", reliable: true, plain: true, who: "an inscription above a seed-vault", text: "Golden-age inscription over a seed-vault door, copied by {investigator} in {year}: 'This world is the fourth field we have sown. Fourth planting: the stock is hardier this time. The city is the test plot. Mark the yield; the pruner will come.' Below it is a table of numbers in nine columns. The archivist believes the last column counts people." },
    { depth: "core", about: "truth:gardener", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "a mountain guide", text: "Report of a mountain guide to the magistrate of {place}, {year}: 'The peak colony greets you with: may you be a good harvest. They seemed to mean it kindly. My client {person} stayed the night at their invitation. In the morning they said {person} had been gathered in, and showed me a young tree in the orchard. I came down alone. The fee was never paid.'" },
    { depth: "core", about: "truth:gardener", source: "archive", bias: "official", reliable: false, who: "the Royal Survey of {realm}", text: "Report of the Royal Survey of {realm} on the halo lands, {year}: 'The fertility of the halo lands, two harvests a year, is owed to the warmth of the Lantern's light and the diligence of the faithful. Talk of pruning is a peasant fancy. Rents within the line are to rise by a tenth, in recognition of the blessing.'" },

    { depth: "core", about: "truth:one_being", source: "heretic", bias: "heretic", reliable: "partial", who: "{believer}, Shadow-Hearer", text: "Catechism of the Shadow-Hearers, as {believer} teaches it to new listeners in the waste, {year}: 'The light gives without asking. The dark asks without giving. Neither is whole; neither ever was. Pass three of its tests and you will need no god.' New listeners keep a knotted cord, one knot for each test passed. {believer}'s cord has seven." },
    { depth: "core", about: "truth:one_being", source: "ruin", bias: "true", reliable: true, plain: true, who: "carved inside the black spire", points: "site:ice_vessel", text: "Carved inside the black spire in the ice at {lead}, copied by {investigator} in {year}: a picture of the orb, ringed by one word repeated forty times. Every scholar who has read it agrees it means 'return'. Beside it, a second picture shows the orb and the spire joined into one round thing. Under that, plainly: 'We were one. I came first. I will wait.'" },
    { depth: "core", about: "truth:one_being", source: "person", bias: "true", reliable: "partial", cost: true, who: "{investigator}, archivist", text: "Case notes of {investigator}, archivist, on {person}, the dream-child of {place}, {year}: 'Day 9. The child repeats golden-age words while asleep, about 300 a night. Translated: it is not afraid of the dark; it is ashamed; it left without saying goodbye. Day 10. {official} came with two deacons and took the child. The Church says {person} is resting. The family has had no letter.'" },
    { depth: "core", about: "truth:one_being", source: "traveller", bias: "garbled", reliable: "partial", who: "{survivor}, guttered Lit", points: "sub:black_vessel", text: "Statement of {survivor}, a Lit who deserted into the waste and came back, {year}: 'I walked eleven days to the black slab. The dark spoke to me there in the Lantern's voice: the same voice I heard when I was lit at twelve. I cannot unhear it. My light went out on the walk home.' The border command's file on the slab, with this statement in it, is at {lead}." },
    { depth: "core", about: "truth:one_being", source: "temple", bias: "propaganda", reliable: false, who: "a sermon of the Church", text: "Sermon preached in all 40 churches of the city on the feast of the Lantern, {year}: 'The Follower is the Lantern's enemy and nothing else: a hunger without mind, which can neither speak nor bargain. Whoever claims to have heard it has heard only their own sin. Deserters who speak of voices in the waste are to be confined until they recant.'" },

    { depth: "sub", about: "sub:guttering_lit", source: "archive", bias: "redacted", reliable: true, who: "the roll of the Lit, kept by {official}", text: "Roll of the Lit for {year}, kept by {official}: four hundred and twelve names. Beside ninety of them, in a different ink, a small black circle. The roll of ten years ago had 640 names and no circles. Name 211 is {survivor}, with a circle. No circle is explained anywhere in the book, and the ink of the circles is still fresh." },
    { depth: "sub", about: "sub:unlit_hills", source: "oral", bias: "true", reliable: true, who: "a hill-clan mother, to her son", text: "A mother of the hill clans, teaching her son to string a bow before the dark came in {year}: 'We have no light, so we learned the dark. It has teeth, but it can be counted. Forty came over the ridge last time, and we counted every one. Anything that can be counted can be beaten.' Recorded by a deacon, who was told to leave." },
    { depth: "sub", about: "sub:halo_harvests", source: "person", bias: "exaggerated", reliable: "partial", who: "a tenant farmer of {place}", text: "A tenant farmer of {place}, to a travelling clerk, {year}: 'A furrow inside the halo line is worth ten outside it. Two harvests a year inside, one thin one outside. My brother was hanged for moving a boundary stone three paces. The stone is still where he put it, because the lord liked the new line better.'" },
    { depth: "sub", about: "sub:burned_translation", source: "library", bias: "propaganda", reliable: false, who: "an index of the Church", text: "Entry 14 in the Church's index of forbidden books, {year}: 'The so-called arrival translation is a forgery by a disordered mind. Its author recanted before the fire. The faithful are forbidden to read it, copy it or discuss it. Copies found in the universities are to be surrendered to the deacons, for a reward of one crown each.'" },
    { depth: "sub", about: "sub:black_vessel", source: "traveller", bias: "true", reliable: "partial", who: "an army scout master", text: "Report of a scout master to the border command, {year}: 'Sent 12 scouts to the black slab. All 12 came back unhurt. They eat, sleep and drill as before. They have stopped praying. One told me, quite gently, that there was nothing left to pray to, and asked whether I had ever wondered why the light needs us.'" },
    { depth: "site", about: "site:shadow_line", source: "temple", bias: "pious", reliable: "partial", who: "a pilgrim's guidebook", points: "site:ice_vessel", text: "From a pilgrim's guidebook sold at the city gate, {year}: 'Walk the line at noon and you walk the Lantern's gaze. Pilgrims who reach mile 30 receive a blessing and a brass token. Those who go further are said to see what the Lantern sees. None has ever described it.' A hunter's note in one copy says the line points at {lead}." },
    { depth: "site", about: "site:first_touch", source: "archive", bias: "redacted", reliable: "partial", who: "the inventory of the sealed chamber", points: "archive", text: "Inventory of the sealed chamber, year of the founding: 'One altar. Twelve cradles, occupied. Oil, bread, twelve blankets. The doors to be closed and not opened while the light endures.' The page is signed by nine elders. A note pinned to the copy at {lead} asks who took the twelve children out, and when." },
    { depth: "site", about: "site:warm_shard", source: "archive", bias: "true", reliable: "partial", who: "{survivor}, crater guard", text: "Duty log of the crater guard at the warm stone, kept by {survivor}, {year}: 'Day 5. Touched the stone to warm my hands, as everyone does. Day 6. I am not afraid of anything. I could walk into the waste right now. Day 7. Relieved, by the rule. The fear came back on the road home, all at once. I wept for an hour, and I was glad of it.'" },
  ],
};
