// The Sleeper: an alien god sleeps beneath the sea; learning of it changes the learner, and its dreams leak into the waking world.
// Merges the "unlidded eye" (knowledge that transforms) and the "dreamer beneath" (a god whose dreams spread like plague).
export default {
  id: "sleeper",
  name: "The Sleeper",
  family: "world",
  kind: "cosmic",
  pitch: "A huge, ancient creature sleeps under the sea. People who study it too closely start to change, and its dreams leak into the minds of sleepers everywhere.",
  slots: ["cosmology", "divine-order", "apocalypse"],
  tone: ["horror", "grim"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "grimdark", "flintlock"],
  w: 1,
  excludes: ["pale_visitor"],
  pairs: [{ id: "drowned_crown", w: 3 }, { id: "unremembering", w: 2 }, { id: "leavings", w: 2 }, { id: "thinning", w: 1.5 }, { id: "balanced_circle", w: 1.5 }],

  // the hidden truth: a world picks one
  truths: [
    { id: "indifferent", n: "It does not know we are here", d: "The Sleeper is not angry, hungry or watching. It is simply too large to notice us: when it shifts in its sleep a coast sinks, and that is all. A person who understands even part of what it is comes away changed in mind, and often in body, which is why the college's best scholars come back from the lower galleries serene and no longer able to work.", tags: ["truth:sleeper_indifferent"],
      known: [
        "Coasts sink overnight with no storm. The temple says the deep god watches over every sailor. Scholars who study the old ruins under the college come back calm and stop publishing.",
        "A carving in the lowest gallery says an older people sang to the Sleeper for a thousand years, and it never heard. A quarry has uncovered a creature larger than the quarry, curled up asleep.",
        "A scholar's last letter says the Sleeper does not know we exist. {investigator} has examined a scholar who went down to the lowest gallery and came back unable to remember why work mattered.",
        "Confirmed: the Sleeper is too large to notice us, and its slightest movement sinks coasts. Understanding it changes the person who understands. Indifference is the whole of its relation to us.",
      ] },
    { id: "heirs", n: "It is raising heirs", d: "The Sleeper spread its blood through the world so that some living thing would grow to be like it. People who learn too much are its candidates, and the changed beasts are its failures. The Church heals with a sweet draught drawn from a relic under its altar, which is the Sleeper's blood; it is raising the Sleeper's heirs without knowing it, and its hunters kill the failures.", tags: ["truth:sleeper_heirs"],
      known: [
        "The Church of the Draught heals the sick with a sweet communion. Years later some of the healed change into things that are not human, and the Shutter Night kills them. The Church says the draught is the blood of the saints.",
        "A hunter has found a christening ring on a changed thing, and a priest asked whether it had spoken. A Church inventory lists forty stone cradles and records of children 'never to be copied'.",
        "{survivor}, a sworn hunter, has checked the changed against the parish registers. Every one of them took the draught as a child. A channel under the college runs from a black vat toward the cathedral.",
        "Confirmed: the draught is the Sleeper's blood. The Church has been raising its heirs for centuries and hunting the failures. The relic is still under the altar, and the draught is still given on Sundays.",
      ] },
    { id: "world_dream", n: "We are what it dreams", d: "The world exists because the Sleeper dreams it, and it dreams through sleeping people. Where many people dream the same nightmare, that nightmare becomes real. If the Sleeper ever wakes, the world ends, and the clockmakers' guild that measured how fast it is waking voted not to tell anyone.", tags: ["truth:sleeper_dream"],
      known: [
        "In some districts many people share the same dream, night after night. The crown's physicians blame crowding and poor diet. A whole valley fell asleep one night and has not woken, and those who go in to fetch the sleepers lie down beside them.",
        "{investigator}'s ward of sleepers speaks the same words at the same hour, and the floor under the empty beds has sunk. The Wakeful sect forbids deep sleep and has kept watch in shifts for six hundred years.",
        "A stone bed is carved with a warning: when ten thousand dream the same dream, the Sleeper dreams through them and it becomes real. A field of petrified sleepers lies layer on layer, all mid-breath.",
        "Confirmed: the world is the Sleeper's dream, and shared nightmares come true. A guild measured the Sleeper waking, found the count falling by a fifth each decade, and voted to keep it quiet.",
      ] },
  ],

  tags: ["sleeper"],

  subthemes: [
    { id: "sweet_draught", n: "The Sweet Draught", d: "A church heals the sick with a dark, sweet communion drawn from a relic it keeps under the altar. The healed are grateful and strong. Years later, some of them begin to turn into something that is not human.", w: 1.5, mods: [["pious", 2], ["organised", 2], ["faith:one_god", 1.5], ["faith:sl_draught", 4]], truthLink: "heirs", tags: ["theme:sweet_draught"] },
    { id: "empty_cradles", n: "The Parishes Without Children", d: "Fishing villages where no child has been born in a generation, and the adults share wide, unblinking eyes. They are polite to strangers and sing to the sea at night.", w: 1.2, req: { any: ["coastal", "island", "seafaring"] }, truthLink: "heirs", tags: ["theme:empty_cradles"], mark: { kind: "zone", n: "The Hollow Parishes", color: "#3e5a63", size: [1, 3], where: "coast" } },
    { id: "night_hunt", n: "The Shutter Night", d: "Once a year the city gates are barred, the bells ring, and sworn hunters go house to house after the changed. The townsfolk call it a festival and stay behind their shutters.", w: 1.2, req: { any: ["has:city", "urbane", "harsh_law"] }, tags: ["theme:night_hunt"] },
    { id: "blinking_star", n: "The Star That Blinks", d: "The court astronomers have logged a new star low in the southern sky. Through a good lens it is a disc, not a point, and on some nights it goes dark like a closing eye.", w: 1, req: { any: ["scholarly", "faith:stars", "seers", "academies"] }, truthLink: "world_dream", tags: ["theme:blinking_star"] },
    { id: "slumber_vale", n: "The Slumbering Vale", d: "An entire valley fell asleep one night and has not woken. The sleepers breathe, age and murmur the same words at the same moment, and those who go in to fetch them lie down beside them.", w: 0.9, truthLink: "world_dream", tags: ["theme:slumber_vale"], mark: { kind: "zone", n: "The Slumbering Vale", color: "#6b5e8a", size: [1, 2], where: "inner" } },
    { id: "tall_house", n: "The Tall House", d: "One noble line has grown taller with each generation, and quieter. Its heirs no longer speak above a whisper and do not seem to need to.", w: 0.7, req: { any: ["monarchy", "hierarchical", "dynastic"] }, truthLink: "heirs", tags: ["theme:tall_house"] },
    { id: "lidwardens", n: "The Lidwardens", d: "A secret office buys up books, closes observatories and makes curious scholars disappear. Its agents insist they are saving the realm, and they may be right.", w: 1, req: { any: ["autocracy", "spy_network", "harsh_law", "gov:theocracy"] }, tags: ["theme:lidwardens"] },
    { id: "dream_leavings", n: "Things Brought Back From Sleep", d: "People wake holding objects they dreamed of: a key to no door, a flower of no known kind, a coin stamped with a face that has too many eyes. Pawnbrokers trade in them quietly.", w: 1, req: { any: ["seers", "mystic", "magic:high", "near:rift"] }, truthLink: "world_dream", tags: ["theme:dream_leavings"] },
    { id: "the_wakeful", n: "The Wakeful", d: "A stern sect that forbids deep sleep, keeping its members awake on bitter tea and the rattle of night-bells. They are gaunt, short-tempered and very rarely mad.", w: 0.9, req: { any: ["zealous", "ascetic", "mystic"] }, truthLink: "world_dream", tags: ["theme:wakeful"] },
    { id: "uncharted_reef", n: "The Reef Not on the Charts", d: "Ships blown off course report a reef of black, regular stone where the charts show open water. The crews that return have stopped dreaming, or will not say what they dream.", w: 1, req: { any: ["has:port", "seafaring", "navy"] }, truthLink: "indifferent", tags: ["theme:uncharted_reef"] },
    { id: "same_drawing", n: "The Children's Drawing", d: "Children who have never met draw the same shape in the dirt: a ring with something folded inside it. Parents beat it out of them; teachers collect the drawings in a locked drawer.", w: 0.8, tags: ["theme:same_drawing"] },
    { id: "scholarium", n: "The Scholarium Below", d: "A college built over old ruins has been digging downward for a century. Its finest minds go down to the lowest galleries and come back serene and unable to explain why.", w: 1, req: { any: ["scholarly", "near:ruins", "academies"] }, truthLink: "indifferent", tags: ["theme:scholarium"] },
  ],

  sites: [
    { id: "risen_spire", n: "The Drowned Spire of $", kind: "ruin", where: "coast", d: "A tower of black stone that rises from the sea on the lowest tides of the year.",
      layers: {
        surface: { n: "The black church", text: "A rock off the headland rises from the sea on the lowest tides of the year. The fishermen will not row near it and call it the black church. The harbour keeps one rowing boat chained up with a sign: not for hire on low tides." },
        study: { n: "Uncountable sides", text: "It is a carved spire, not a rock. Crown surveyors have measured it nine times and never agreed how many sides it has: seven, eight, eleven. {investigator} tied a knotted cord round it at the waterline and counted twice. The counts differed." },
        dig: { n: "The open door", text: "At the lowest tide a door at its foot stands open onto stairs that go down further than the sea is deep. Warm air comes up them. A fisher's boot sits on the third step. The harbour's book of tides and door-openings is kept at {lead}.", points: "archive" },
        revelation: { n: "The tip of it", text: "The spire is the tip of a structure buried under the sea floor, larger than the bay. Its doors open and close with the tides, and the air inside is warm because the Sleeper's breath moves through it. The harbour has set its tide tables by the door for two hundred years and never asked why." },
      } },
    { id: "many_eyed_fossil", n: "The Watcher in the Stone at $", kind: "dig", where: "mountain", truthLink: "indifferent", d: "A fossil in a quarry face, too large to see whole, with rows of hollow eye-sockets.",
      layers: {
        surface: { n: "The honeycomb", text: "Quarrymen found a pattern of round hollows in a cliff face and called it the honeycomb. The stone sells well for fireplaces, and three hundred cartloads have gone to the city. The foreman keeps one hollow uncut for luck." },
        study: { n: "Eye-sockets", text: "The hollows are eye-sockets, hundreds of them, ringed around a single creature larger than the quarry. {investigator} counted 580 on the exposed face alone. Each socket is the width of a cartwheel, and all of them are closed." },
        dig: { n: "Curled asleep", text: "Deeper cuts show the creature's skin was laid down in sediment older than any other fossil, and it was curled up as if asleep. The quarry's cut-book, which records each face opened and who bought the stone, is kept at {lead}.", points: "library" },
        revelation: { n: "The shed skin", text: "It is a shed skin, not a corpse. The creature that grew out of it is alive and asleep under the sea, and it shed this skin without waking or noticing. The quarry has sold three hundred cartloads of it for fireplaces. Nobody in those houses has slept well since." },
      } },
    { id: "deep_galleries", n: "The Lower Galleries of $", kind: "dig", where: "capital", truthLink: "heirs", d: "Excavations beneath a college, where each level down is older and stranger than the one above.",
      layers: {
        surface: { n: "The cellars", text: "Below the college are cellars used for storage and for punishing first-year students, who are locked in overnight with one candle. Students scratch their names on the door; the oldest name is four hundred years old." },
        study: { n: "Older vaults", text: "Below the cellars are older vaults, and below those, walls of a stone nobody in the realm has quarried, black and faintly warm. {investigator} took a chip of it to the assayers. They returned the fee and the chip the same day." },
        dig: { n: "The cradles", text: "The deepest gallery holds forty small stone cradles in rows and a vat stained black. A channel cut into the floor carries what the vat held upward, toward the city. The channel ends under {lead}.", points: "temple" },
        revelation: { n: "The nursery", text: "The Church raised children down here on the Sleeper's blood, drawn from the relic it calls the Mother's vessel. A few grew into what the Sleeper wanted. Most were failures, and the Shutter Night was founded to kill them. The channel still runs to the cathedral, and the draught is still given on Sundays." },
      } },
    { id: "sleeping_field", n: "The Field of Sleepers near $", kind: "anomaly", where: "remote", truthLink: "world_dream", d: "A meadow of stone figures lying on their backs, every face turned up.",
      layers: {
        surface: { n: "The stone village", text: "A meadow far from any town holds stone figures lying on their backs, every face turned up. Locals say a village was turned to stone for a sin. Goats graze between them, and the shepherd counts 112 figures every evening." },
        study: { n: "Mid-breath", text: "The figures are not carved. They are people, petrified mid-breath, with their clothes and buttons, and their lips are all parted on the same syllable. {investigator} pressed an ear to one stone chest and heard nothing, then one heartbeat." },
        dig: { n: "Layer on layer", text: "Under the field lie older sleepers, and older below them, layer on layer, as if the field has been falling asleep for ten thousand years. The deepest layer wears bronze. A Wakeful elder, {lead}, keeps a record of this field.", points: "cast:believer" },
        revelation: { n: "Closest to waking", text: "When enough people dream the same dream, it becomes real and pulls the dreamers in. This field is where the dream is thinnest. The 112 on top fell asleep in one night eighty years ago, during a midsummer festival where the whole village slept out in the meadow. The festival is still held." },
      } },
    { id: "counting_tower", n: "The Counting Tower of $", kind: "wonder", where: "inner", d: "A clock tower whose mechanism counts down rather than up, built by a guild that no longer exists.",
      layers: {
        surface: { n: "The one-handed clock", text: "A town clock with one hand stands in the square, admired by visitors and ignored by the townsfolk. The guild that built it no longer exists. The town pays a keeper four silver a year to oil it, and one family has held the post for six generations." },
        study: { n: "Backwards", text: "The hand moves backwards, a hair's width each year, toward a mark carved as an open eye. {investigator} compared it with an engraving made 150 years ago. The hand has covered two-thirds of the distance since then." },
        dig: { n: "The ledgers", text: "In the works lie the guild's ledgers: star tables, tide tables and the dreams of a thousand sleepers, all reduced to one diminishing number. The last ledger mentions a fair copy sent to {lead}.", points: "archive" },
        revelation: { n: "The remainder", text: "The guild did not predict the waking. It measured how fast the Sleeper is coming awake, from dreams recorded across the realm, and the number has fallen by a fifth each decade. The guild voted not to tell the town and then dissolved itself. There is less time left than they hoped." },
      } },
  ],

  beings: [
    { id: "draught_wretch", n: "Draught-wretch", kind: "beast", d: "Someone healed by the sweet draught who kept changing after the healing stopped: long-limbed, furred in patches, still wearing the rags of good clothes.", danger: 3, biomes: ["tempforest", "temprain", "swamp", "boreal", "grass"], look: { size: 2.1, group: [1, 3], move: "solo", speed: 12, col: "#4a4038", col2: "#8a7a62", body: "biped", active: "night", visible: true } },
    { id: "hollow_fisher", n: "Hollow-eyed fisherfolk", kind: "beast", d: "Villagers of the childless parishes gone further: grey-skinned, wet-mouthed, wading out at dusk and not always wading back.", danger: 2, biomes: ["coast", "swamp", "mangrove"], look: { size: 1.8, group: [3, 10], move: "herd", speed: 5, col: "#5a6e70", col2: "#a8b8b0", body: "biped", active: "dusk", visible: true } },
    { id: "dream_moth", n: "Dreamwing moth", kind: "insect", d: "Pale moths that gather on the shutters of sleepers. A house they cover is a house where someone will not wake.", danger: 1, biomes: ["tempforest", "temprain", "swamp", "grass", "boreal"], look: { size: 0.08, group: [50, 400], move: "swarm", speed: 6, col: "#d8d0e0", col2: "#6a5a8a", body: "insect", active: "night", visible: true } },
    { id: "tide_coil", n: "Tide-coil", kind: "marine", d: "A long, pale thing glimpsed beneath ships on the lowest tides, many-eyed along its whole length. It has never attacked a ship. Ships near it sometimes simply stop.", danger: 3, biomes: ["abyss", "open", "shelf"], look: { size: 40, group: [1, 1], move: "solo", speed: 8, col: "#c8c8b8", col2: "#3a2a4a", body: "serpent", active: "night", visible: false } },
  ],

  techs: [
    { id: "sl_wakeful_tea", n: "Wakeful tea", field: "medicine", level: 1, d: "A bitter brew that keeps sleep light, so the shared dreams cannot take hold." },
    { id: "sl_dream_ledgers", n: "Dream ledgers", field: "writing", level: 2, d: "Dreams written down each morning and compared across towns; the shared ones are marked in red." },
    { id: "sl_sweet_draught", n: "The sweet draught", field: "medicine", level: 2, d: "A communion that closes wounds and breaks fevers overnight. Its source is not discussed." },
    { id: "sl_folding_steel", n: "Hunters' hooks", field: "metallurgy", level: 3, d: "Long iron hooks and short heavy blades, forged for close work in barred lanes on Shutter Night." },
    { id: "sl_deep_lenses", n: "Deep lenses", field: "astronomy", level: 4, d: "Ground lenses fine enough to see that the new star has an iris. Several observatories have since been closed." },
    { id: "sl_lid_rites", n: "The lid-rites", field: "arcana", level: 5, d: "Rites that close a mind against what it has seen, at the cost of everything else it knew that year." },
  ],

  units: [
    { id: "sl_hunters", n: "Night-hunters", role: "infantry", wpn: "axe", kit: "light", ranks: 2, gap: 2.2, size: 40, w: 0.8, mods: [["theme:night_hunt", 8], ["theme:sweet_draught", 3]] },
    { id: "sl_tallguard", n: "Tall guard", role: "infantry", wpn: "pike", kit: "plate", ranks: 4, gap: 1.6, size: 60, w: 0.3, mods: [["theme:tall_house", 12]] },
  ],

  faiths: [
    { id: "sl_draught", n: "Church of the Draught", d: "A healing church whose communion is a dark, sweet blood kept beneath the altar. Its priests are kind and its sick get well.", tags: ["faith:sl_draught"], w: 0.6, mods: [["pious", 1.5], ["organised", 1.5], ["near:ruins", 1.5]],
      names: ["The Church of the Sweet Draught", "The Healing Communion of $", "The Communion of the Cup"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Fog-shallows", color: "#7a8a90", size: [1, 3], count: [1, 2], where: "coast", d: "Coastal waters where the fog never lifts and the tide runs out further than it should." },
  ],

  storylines: [
    { id: "sl_empty_cradles", n: "The Empty Cradles of {place}", scale: "local", anchor: "town", w: 1.5, req: ["sleeper", "coastal"],
      stages: {
        start: { h: "No child born in {place} for nine years", b: "The midwife of {place} has packed her bag and gone inland. {investigator}, a physician from the capital, has come to find out why the cradles stay empty.", wait: [2, 5], next: [{ to: "the_singing", w: 2 }, { to: "driven_out", w: 1, mods: [["insular", 2.5]] }] },
        driven_out: { h: "The physician of {place} driven out", b: "The villagers of {place} were polite, then cold, then armed. {investigator} left on the mail cart and swore never to speak of what was kept in the boathouse.", fx: { unrest: 3 }, end: true },
        the_singing: { h: "Singing heard from the shore at {place}", b: "{investigator} has watched the whole village walk to the waterline at midnight and sing to the sea. The tune was the one from the children's drawings.", wait: [2, 6], fx: { flag: "singing" }, next: [{ to: "wedding", w: 2 }, { to: "physician_changes", w: 1, mods: [["seers", 2], ["mystic", 1.5]] }, { to: "burned", w: 1, mods: [["zealous", 2.5], ["harsh_law", 2], ["theme:lidwardens", 3]] }] },
        wedding: { h: "{place} walks into the sea", b: "On the year's lowest tide the people of {place} went out to the black rock in their best clothes and did not come back. The tide came in over empty streets.", fx: { abandon_town: true, unrest: 8 }, end: true },
        physician_changes: { h: "{investigator} stays on in {place}", b: "The physician's letters home have grown short and calm, then stopped. A traveller says {investigator} now sings with the others, and has the same wide eyes.", fx: { unrest: 4 }, end: true },
        burned: { h: "{place} burned by order of the crown", b: "Men without badges came by night and burned the boathouses and the chapel of {place}. Nobody in the capital will say who sent them, or what was found.", fx: { stability: -4, unrest: 12, pop: 0.95 }, end: true },
      } },
    { id: "sl_blinking_star", n: "The Eye above {capital}", scale: "realm", anchor: "realm", w: 1.2, req: ["sleeper", { any: ["scholarly", "learned", "faith:stars", "seers", "academies"] }],
      stages: {
        start: { h: "A new star is logged over {capital}", b: "{person}, chief astronomer of {realm}, has recorded a star where none was before. On the third night it went dark for an hour, then returned.", wait: [3, 8], fx: { science: { astronomy: 0.4 } }, next: [{ to: "lenses", w: 2 }, { to: "observatory_shut", w: 1, mods: [["theme:lidwardens", 4], ["autocracy", 1.5]] }] },
        lenses: { h: "The astronomers of {realm} grind a deeper lens", b: "A lens three spans across has been raised on the observatory tower. {person} has stopped sleeping and fills notebooks with one shape, over and over.", wait: [4, 10], fx: { flag: "lens" }, next: [{ to: "sleeping_city", w: 1.5 }, { to: "great_discovery", w: 1, mods: [["learned", 2], ["stable", 1.5]] }, { to: "observatory_shut", w: 0.8 }] },
        observatory_shut: { h: "The observatory of {capital} is closed", b: "By order of {ruler}, the great observatory is sealed and its notebooks burned. {person} was escorted to a quiet house in the hills and is said to be resting.", fx: { stability: 2, prestige: -3 }, end: true },
        sleeping_city: { h: "Half of {capital} does not wake", b: "On the morning after the star closed for a whole night, a third of {capital} would not wake. They murmur the same words together in their beds, and the physicians are helpless.", fx: { pop: 0.85, unrest: 20, stability: -10 }, end: true },
        great_discovery: { h: "{person} publishes the star tables", b: "The tables of {person} predict exactly when the new star will close. The scholars of every court have them now, and several of the readers have already begun to dream the same dream.", fx: { discovery: "astronomy", prestige: 6, unrest: 6 }, end: true },
      } },
    { id: "sl_sweet_blessing", n: "The Blessing of {place}", scale: "local", anchor: "town", w: 1.3, req: ["sleeper", { any: ["pious", "organised", "faith:sl_draught", "faith:one_god", "theme:sweet_draught"] }],
      stages: {
        start: { h: "A fever breaks in {place} overnight", b: "The fever ward of {place} emptied in a single night after the priests brought the sweet draught. {person}, the vicar, is hailed as a saint.", wait: [3, 8], fx: { stability: 4, pop: 1.03 }, next: [{ to: "the_changing", w: 2 }, { to: "quiet_years", w: 1, mods: [["stable", 1.5]] }] },
        quiet_years: { h: "{place} enjoys a run of good health", b: "Nobody in {place} has died of sickness in three years. The draught is given now to newborns and the old alike.", wait: [6, 18], next: [{ to: "the_changing", w: 2 }] },
        the_changing: { h: "Something walks the lanes of {place} at night", b: "Dogs have been found torn apart and a family has vanished. {survivor}, a sworn hunter from the city, has arrived with a hooked pike and asked to see the parish register.", wait: [2, 5], fx: { unrest: 10, flag: "changing" }, next: [{ to: "the_hunt", w: 2 }, { to: "church_cover", w: 1, mods: [["faith:sl_draught", 3], ["organised", 2]] }] },
        the_hunt: { h: "Shutter Night comes to {place}", b: "The gates of {place} were barred at sunset and {survivor}'s hunters went house to house. Among the things they killed was {person}, the vicar.", fx: { pop: 0.9, unrest: 8, stability: -3 }, end: true },
        church_cover: { h: "The Church closes ranks in {place}", b: "Priests from the cathedral have taken charge of {place}. The hunter {survivor} was arrested for heresy, and the draught is given twice as often now.", fx: { stability: -2, flag: "covered" }, end: true },
      } },
  ],

  cast: [
    { role: "investigator", n: "a physician of the capital who runs the long ward for the dream-sick", home: "capital", stance: "Measures everything and believes nothing yet; wants the dream sickness named before it is cured." },
    { role: "official", n: "a canon of the Church of the Draught who keeps the reliquary and the parish registers", home: "inner", stance: "Believes the draught is the greatest mercy the Church has ever given, and that doubt would kill more than it saves." },
    { role: "believer", n: "an elder of the Wakeful, who keep the night-bells", home: "mountain", stance: "Has slept sitting up for forty years and holds that a shallow sleeper is a closed door." },
    { role: "survivor", n: "a sworn hunter of the Shutter Night, healed by the draught as a child", home: "coast", stance: "Has killed the changed for twenty years and has started checking their names against the parish registers." },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "fishers' wives of {place}, recorded by {investigator}", text: "Song of the fishers' wives of {place}, sung over the nets at dusk, written down by {investigator} in {year}: 'Sleep, little one, sleep light and sleep shallow; the one under the water sleeps deep for us all.' The physician's note: 'The one under the water is the Sleeper, the great creature the coast believes lies under the sea. Not one of the 30 women I asked would sing the second verse indoors.'" },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "the Royal Almanac of {realm}", text: "From the Royal Almanac of {realm} for {year}, the page on health: 'The so-called dream sickness is a fever of damp lowlands, cured by drainage, fresh air and a firm bedtime. Families should not hang bells on beds, which disturbs rest. Shared dreams are a known effect of shared rooms. Cases this year: 40, a fall of a tenth.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a wine merchant on the road", points: "cast:believer", text: "Letter of a wine merchant on the road through {place}, {year}: 'Here they hang bells on their beds so that nobody sleeps too soundly. I laughed. The next night I dreamed of a door under the sea, and stairs, and warm air. I bought a bell for six coppers from the Wakeful elder {lead}. I have not dreamed since. I have not slept much either.'" },

    { depth: "core", about: "truth:indifferent", source: "person", bias: "true", reliable: true, plain: true, who: "a scholar of the college, last letter", text: "Last letter of a scholar of the college to {investigator}, {year}, written after a year in the lowest gallery: 'It is not angry with us. It does not know we exist. It is too large to know. Each time it shifts in its sleep, a coast sinks, and that is all. I understand this now, and understanding it has used me up. Please give my lens to a student.'" },
    { depth: "core", about: "truth:indifferent", source: "ruin", bias: "true", reliable: "partial", who: "cut in the lowest gallery", points: "sub:scholarium", text: "Cut into the wall of the lowest gallery under the college, in a script older than the realm, translated by two scholars in {year}, whose report is at {lead}: 'We sang to it for a thousand years. It did not hear. We stopped singing. It did not notice that either.' Beneath, a tally of 52 marks. Both translators asked for leave afterward and did not come back to the college." },
    { depth: "core", about: "truth:indifferent", source: "heretic", bias: "heretic", reliable: "partial", who: "a burned tract", points: "site:risen_spire", text: "From a tract burned by order of the Church in {year}, one page saved: 'The priests say the deep god judges. It does not judge. It turns over in its sleep, and a coast falls into the sea; three villages last spring, with 400 people in them. Go and look at the black spire at {lead} on the low tide, and tell me it is watching anyone.'" },
    { depth: "core", about: "truth:indifferent", source: "temple", bias: "official", reliable: false, who: "a pastoral letter of the temple", text: "Pastoral letter of the temple of {realm} after the sinking of the south coast, {year}: 'The faithful need fear nothing under the sea. {deity} set the waters in their place and watches over every soul that sails them. The villages lost were lost for their sins. A collection for the 400 will be taken on the next feast day.'" },
    { depth: "core", about: "truth:indifferent", source: "person", bias: "true", reliable: "partial", cost: true, who: "{investigator}, physician", text: "Case notes of {investigator}, physician, {year}: '{person}, scholar of the college, aged 34, brought up from the lowest gallery after nine days. Eats, sleeps, smiles. Cannot be made to care about anything: not the college, not the family, not the lens that took twelve years to grind. Says only: it does not know we are here, and once you know that, nothing is urgent. Discharged to the family.'" },

    { depth: "core", about: "truth:heirs", source: "archive", bias: "redacted", reliable: "partial", who: "a Church inventory", points: "site:deep_galleries", text: "Church inventory of {year}, much scored out, signed by {official}: 'Item, one reliquary vessel, the Mother's. Item, forty cradles, stone. Item, records of the [scored out] children, to be kept below and never copied. Item, one vat, black.' A later clerk has added: 'All items below the college, at {lead}. Not to be inventoried again.'" },
    { depth: "core", about: "truth:heirs", source: "person", bias: "true", reliable: true, plain: true, who: "{survivor}, sworn hunter", text: "Journal of {survivor}, sworn hunter, after the Shutter Night, {year}: 'The thing I killed tonight wore a christening ring. I checked the parish register. Fourteen changed ones this year, and every one took the sweet draught as a child. The draught is not the saints' blood. It is the Sleeper's, and the Church is breeding them. I took it myself, at six.'" },
    { depth: "core", about: "truth:heirs", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "a mother of the shore parishes", text: "A mother of the shore parish of {place}, speaking to {investigator} in {year}: 'The drowned ones are not drowned. They are going home. My {person} took the draught at four for the fever, and was the strongest child in the parish. At sixteen {person} walked into the sea in a Sunday coat, singing. One day they will come back for the rest of us.'" },
    { depth: "core", about: "truth:heirs", source: "temple", bias: "official", reliable: false, who: "{official}, canon of the Church of the Draught", text: "Homily of {official}, canon of the Church of the Draught, preached at the cathedral on the feast of healing, {year}: 'The communion is the blood of the saints, freely given. It heals the body and asks nothing in return. This year it has healed 1,100 of the sick of this city. Those who whisper otherwise would rather see your children die of fever.'" },
    { depth: "core", about: "truth:heirs", source: "heretic", bias: "exaggerated", reliable: "partial", who: "a hospital wall, copied by {investigator}", points: "temple", text: "Scrawled in red on the wall of the fever ward at {place}, copied by {investigator} in {year} before it was whitewashed: 'THEY ARE NOT CURING YOU. THEY ARE RAISING YOU.' Below, smaller: 'Ask what is under the altar at {lead}.' The ward had 60 beds. All 60 patients had been given the draught that week." },

    { depth: "core", about: "truth:world_dream", source: "ruin", bias: "true", reliable: true, plain: true, who: "carved on a stone bed", points: "site:sleeping_field", text: "Carved around the rim of a stone bed at the edge of the field of sleepers at {lead}, copied by {investigator} in {year}: 'This world is its dream. It dreams through those who sleep. Do not dream together. When ten thousand people dream the same dream, the Sleeper dreams through them, and what it dreams becomes real.' The bed is long enough for two." },
    { depth: "core", about: "truth:world_dream", source: "person", bias: "garbled", reliable: "partial", cost: true, who: "{investigator}, physician to the long ward", text: "Case notes of {investigator}, physician to the long ward, day 40: '212 sleepers, none awake since spring. At the second bell all of them spoke at once for an hour, the same words in every bed: the walls are thin; the walls are its eyelids. Afterwards the three empty beds had sunk a hand's width into the floor. {person}, the night nurse, lay down in one of them at dawn and has not woken.'" },
    { depth: "core", about: "truth:world_dream", source: "library", bias: "official", reliable: false, who: "the college of physicians", text: "Opinion of the college of physicians of {realm}, {year}: 'The shared dreams reported in some districts are a known effect of crowding and poor diet. Physicians agree there is nothing in them beyond imagination. The long ward in the capital is to close for want of funds; its 212 patients will be sent home to their families.'" },
    { depth: "core", about: "truth:world_dream", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a pilgrim among the Wakeful", points: "sub:the_wakeful", text: "A pilgrim's account of the Wakeful of the hill country, {year}, filed at {lead}: 'They swear that if everyone in the world slept on the same night, the world would stop. So they take turns to stay awake, three hundred of them in shifts, and they have done it for six hundred years. Their elder showed me the watch-roll. Not one night is blank.'" },

    { depth: "sub", about: "sub:sweet_draught", source: "person", bias: "true", reliable: "partial", who: "a nun of the Draught", points: "cast:official", text: "Diary of a nun of the Church of the Draught, {year}: 'It tastes of honey and iron. After the first cup I saw the colours of the chapel as I never had. After the tenth I could hear the sea from the hills, eighty miles off. I asked the canon, {lead}, for an eleventh. The canon gave it gladly. The next morning a deacon came to measure my height, and wrote it down.'" },
    { depth: "sub", about: "sub:night_hunt", source: "library", bias: "propaganda", reliable: false, who: "a notice of the city council", text: "Notice of the city council of {place}, posted on every door before the Shutter Night, {year}: 'The Hunt is an ancient civic festival commemorating the clearing of wolves from the city's forests. Gates close at sunset. Citizens are reminded to remain indoors for their own comfort. Last year's hunt cleared 31 wolves.'" },
    { depth: "sub", about: "sub:lidwardens", source: "archive", bias: "redacted", reliable: true, who: "a Lidwarden warrant", points: "cast:investigator", text: "Warrant of the office of Lidwardens, the crown's secret office that closes observatories, {year}: 'The bearer is authorised to remove all books, lenses and persons from the house of the physician {lead}. No receipt is to be given. Nothing removed is to be read.' Endorsed on the back: 'Books, 214. Lenses, 3. Persons: the physician was out.'" },
    { depth: "sub", about: "sub:uncharted_reef", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a ship's mate in a port tavern", text: "A ship's mate in a port tavern at {place}, {year}, three days off the boat: 'Square stones, black, the size of churches, a fathom under the keel, where the chart shows forty fathoms. The captain made all 22 of us swear on the ship's bell. I haven't dreamed a single night since, and I used to dream every night of my life.'" },
    { depth: "sub", about: "sub:empty_cradles", source: "oral", bias: "garbled", reliable: "partial", who: "a matchmaker of {place}", text: "Advice of a matchmaker at the inland market of {place} to a client's family, {year}: 'Do not take a bride from the shore parishes. Not because she is wicked. Because the sea will want the children, and she will let it have them. No child has been born on that coast in nine years. My fee is the same either way.'" },
    { depth: "sub", about: "sub:the_wakeful", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, Wakeful elder", text: "The rule of the Wakeful, as {believer} has it painted over the door of the watch-house, {year}: 'Sleep sitting. Sleep cold. Wake at every bell. A shallow sleeper is a closed door.' The bells ring every hour, twenty-four times a night. The elder has slept sitting up for forty years and has a temper to show for it." },
    { depth: "site", about: "site:counting_tower", source: "archive", bias: "true", reliable: true, who: "minutes of the clockmakers' guild", text: "Minutes of the clockmakers' guild of {place}, {year}: 'Revised count presented, from star tables, tide tables and the dream-registers of 40 parishes. The remainder is smaller than last decade's by a fifth. Motion to tell the town: defeated, eleven to two. Motion to dissolve the guild: carried. The hand on the tower to be left running.'" },
    { depth: "site", about: "site:risen_spire", source: "oral", bias: "garbled", reliable: "partial", who: "the harbour-master of {place}", text: "Notice of the harbour-master of {place}, chalked on the slipway board each spring, {year}: 'Never row out to the black church on the low tide. The door will be open, and you will want to go down the stairs. Two boats went out last year. One came back, rowed by a boy who will not say where the other six are.'" },
    { depth: "site", about: "site:many_eyed_fossil", source: "person", bias: "true", reliable: "partial", who: "a quarry foreman", text: "Report of the quarry foreman at {place} to the stone-buyers' guild, {year}: 'We have opened the honeycomb face another forty feet. The round hollows go on. My men say they are eyes, all shut, and will not work the face after dark. 300 cartloads sold. I have kept one hollow uncut for luck, and I sleep in the village now, not at the quarry.'" },
  ],
};
