// The Thinning: another world presses against this one, and in places the wall between them is wearing through.
export default {
  id: "thinning",
  name: "The Thinning",
  family: "world",
  kind: "cosmic",
  pitch: "Another world lies right alongside this one. At stone rings, still lakes and old crossroads the wall between them is wearing thin, and people and things are crossing over.",
  slots: ["cosmology"],
  tone: ["wonder", "horror"],
  era: ["stone", "bronze", "medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "mythic", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "unremembering", w: 2.5 }, { id: "hush_below", w: 1.5 }, { id: "unquiet_gate", w: 1.5 }, { id: "ward_walls", w: 1.5 }, { id: "great_root", w: 1.2 }],

  cast: [
    { role: "investigator", n: "a recorder of the hedge-wardens, who rides out to thin places and writes up what came through", home: "forest", stance: "Wants every crossing counted and written down, because nobody else is keeping the tally." },
    { role: "official", n: "the tithe-steward of one of the old houses, who carries the seventh-year tithe up the hill", home: "capital", stance: "Believes the bargain keeps the realm fed and that telling the commons would only cause a panic." },
    { role: "believer", n: "a priestess of the Old Bargain who leaves milk at the rings and teaches the old rules", home: "remote", stance: "Holds that the good neighbours are owed respect, and that every disaster comes from someone forgetting their manners." },
    { role: "survivor", n: "a returnee who danced one night under the hill and walked out forty years later", home: "inner", stance: "Wants the realm to believe what happened, and wants the forty years back." },
  ],

  truths: [
    { id: "fair_courts", n: "The bargain is expiring", d: "The other side is ruled by ageless courts who once held this world. The first kings leased it from them for 900 years, for a tithe every seventh summer, and the old houses have paid it ever since: in cattle, then in luck, then in children. The term is nearly up, and the courts mean to take back the land itself.", tags: ["truth:fair_courts"],
      known: [
        "The old houses ride to the hills every seventh midsummer, and their luck holds. They call it a harmless thanksgiving. Their own stewards' papers mention a price, and a child of one house did not come home.",
        "A barrow shows a door at sunset carved with the arms of a house that never ruled here. Behind it, a treaty in two hands leases the land for a term of years, with a tithe every seventh summer.",
        "By the treaty's count, the 900-year term ends within this generation. Fourteen lords of the old houses have bought land in the south this year, as far from the hills as the roads go.",
        "Confirmed: the first kings leased this world from the courts across the wall, and the old houses have paid the rent in their own children. The lease is nearly up. The houses know the date and have not told the realm.",
      ] },
    { id: "mirror", n: "The reflection wants out", d: "The other world is a reversed reflection of this one, and everything done here is done there a moment later. Its people grew tired of following. At the still lakes they learned to swap places with their doubles, and they have started doing it. The people they replace are on the far side now, following.", tags: ["truth:mirror_world"],
      known: [
        "People come back from the still lakes slightly changed: left-handed, punctual, laughing a moment early. The magistrates call it lake-fever. The hedge-wardens' reports on it have been cut short by their own Warden-General.",
        "At one still lake the reflection moves a heartbeat before the people on the shore. Under the water is a village like the one on the shore, reversed and empty, with writing scratched backwards on its walls.",
        "The writing in the drowned village is a statement from the far side: they do everything we do, a moment later, and have found they can trade places with their doubles. In one town, a third of the families now have two of someone.",
        "Confirmed: the far side is a reversed copy of ours, and its people are swapping themselves in. The ones they replace are not dead. They are behind the glass, copying everything we do.",
      ] },
    { id: "lost_place", n: "Where lost things go", d: "The other side is where everything lost ends up: keys, letters, forgotten towns, stolen children, gods nobody prays to. Every village a realm forgets and every archive it burns lands there. It is now full, and lost things, people included, are being pushed back through, often to families who stopped looking long ago.", tags: ["truth:lost_world"],
      known: [
        "Lost things turn up at certain crossroads: shoes, letters, a church bell, a child missing sixty years. The tax office says one lost village was only a clerical error. Its fields are still tended at night.",
        "Returnees describe streets of lost things on the far side and say it is crowded. A cave holds over a thousand lost objects from every age, and further in, streets whose names nobody can recall.",
        "The things coming back are the oldest losses first. Children taken in living memory come home the age they left, to parents now old. The far side is not taking things any more. It is returning them.",
        "Confirmed: the far side is where everything lost goes, and it is full. Every forgotten village and burned archive has added to it. It is pushing the oldest things back out, and the realms that forgot them do not want them.",
      ] },
  ],

  tags: ["thinning"],

  subthemes: [
    { id: "tithe_due", n: "The Seventh-Year Tithe", d: "The old houses pay a tithe at midsummer every seventh year, and their luck holds. This year the hill-folk want more, and they have named exactly what.", w: 1.4, req: { any: ["monarchy", "hierarchical", "origin:old_dynasty", "dynastic"] }, truthLink: "fair_courts", tags: ["theme:fair_tithe"] },
    { id: "changeling_nursery", n: "The Royal Changeling", d: "The heir has stopped growing, eats only honey and sings at night in a language no tutor knows. The nurse swears the child was swapped at the naming.", w: 1, req: { any: ["monarchy", "heir", "dynastic"] }, truthLink: "fair_courts", tags: ["theme:changelings"] },
    { id: "spreading_wood", n: "The Wood That Grew Overnight", d: "An old forest advanced a mile in one night, swallowing farms. Those who walk into it come out years later, no older than when they went in.", w: 1.3, req: { any: ["forest", "jungle", "forest_folk", "faith:spirits"] }, tags: ["theme:wild_wood"], mark: { kind: "zone", n: "The Overnight Wood", color: "#2a5a3a", size: [2, 4], where: "forest" } },
    { id: "doubled_town", n: "The Doubled Town", d: "Half of a town's people walked into the still lake one evening and came out again in the morning. They are pleasant, punctual and left-handed.", w: 1, req: { any: ["river", "marsh", "coastal", "cold"] }, truthLink: "mirror", tags: ["theme:doubles"] },
    { id: "mirror_king", n: "The Mirror on the Throne", d: "The ruler came back from a hunt by the mirror-lake and has behaved slightly differently ever since. Courtiers notice the ring is on the other hand.", w: 0.7, req: { any: ["autocracy", "monarchy", "spy_network"] }, truthLink: "mirror", tags: ["theme:mirror_king"] },
    { id: "lost_crossroads", n: "The Crossroads of Lost Things", d: "Lost things pile up at a certain crossroads: shoes, letters, a church bell, once a whole cart with the ox still in harness. Last week, a child who went missing sixty years ago.", w: 1.1, req: { any: ["great_roads", "open_roads", "mercantile", "has:city"] }, truthLink: "lost_place", tags: ["theme:lost_crossroads"] },
    { id: "iron_mills", n: "The Iron Quarrel", d: "New ironworks spit soot over the hills, and trouble has broken out around the thin places nearby. Folk say iron 'burns the wall', and that the folk behind it are furious.", w: 1, req: { any: ["artisans", "guilds", "mountain", "hills"] }, tags: ["theme:iron_wall"] },
    { id: "hedge_wardens", n: "The Hedge-Wardens", d: "An order of salt-carriers and iron-shod riders who close thin places with bells and rowan. They are underpaid, overstretched and very old.", w: 1.2, req: { any: ["pious", "insular", "frontier_forts", "militant"] }, tags: ["theme:hedge_wardens"] },
    { id: "returnees", n: "The Returnees", d: "People taken under the hill come back, a night or a lifetime later, with gifts and debts they do not remember making.", w: 1.1, req: { any: ["seers", "mystic", "near:ruins", "faith:ancestors"] }, truthLink: "lost_place", tags: ["theme:returnees"] },
    { id: "summer_castle", n: "The Midsummer Castle", d: "On one night a year a castle stands on the empty hill, lit and full of music. Young people sneak up to it. Not all come down.", w: 0.8, req: { any: ["hills", "mountain", "egalitarian", "tribal"] }, truthLink: "fair_courts", tags: ["theme:summer_castle"], mark: { kind: "zone", n: "The Hollow Hills", color: "#6a8a5a", size: [1, 2], where: "remote" } },
    { id: "forgotten_village", n: "The Village Nobody Remembers", d: "A whole village has crossed to the other side. Neighbours cannot recall its name, though its fields are still tended by someone at night.", w: 0.8, req: { any: ["realm:small", "realm:tiny", "insular", "cold"] }, truthLink: "lost_place", tags: ["theme:slipped_village"] },
    { id: "bard_door", n: "The Song That Opens", d: "A wandering singer knows a tune that opens doors in hillsides. Lords pay to hear it, and to have it stopped.", w: 0.7, req: { any: ["urbane", "hospitable", "nomadic"] }, tags: ["theme:door_song"] },
  ],

  sites: [
    { id: "dusk_mound", n: "The Dusk-Door of $", kind: "anomaly", where: "remote", truthLink: "fair_courts", d: "A grassy mound with a door that can only be seen at dusk.",
      layers: {
        surface: { n: "The barrow cattle avoid", text: "A long barrow near {place}, ringed by 31 hawthorns. Cattle will not graze it; a calf put on it in {year} lay down and would not stand. The turf on it stays greener than the field around it, even in winter." },
        study: { n: "The lintel at sunset", text: "{investigator} sat on the barrow for 9 evenings. At each sunset, for about as long as a short prayer, a stone lintel shows in the turf. It is carved with the arms of a house that never ruled here: a hart under seven stars." },
        dig: { n: "The treaty", text: "Behind the door is a dry chamber holding a treaty in two hands, one human and one not. It leases the land for 900 years, the tithe due every seventh summer. The human seal matches the one kept by the tithe-steward {official}, at {lead}.", points: "cast:official" },
        revelation: { n: "The lease", text: "The courts never left. The first kings leased this world from them for 900 years, and the old houses have paid the tithe since: cattle, then luck, then children. By the treaty's count the term ends within this generation. The old houses are buying land in the south." },
      } },
    { id: "mirror_lake", n: "The Still Water of $", kind: "anomaly", where: "any", truthLink: "mirror", d: "A lake that reflects a different sky, and sometimes a different shore.",
      layers: {
        surface: { n: "The wrong stars", text: "A lake near {place} so still that no wind wrinkles it. Its reflection shows the stars of the opposite season: winter stars on a midsummer night. Fishermen will not use it. A boat left moored there in {year} is still there, and so is its reflection." },
        study: { n: "A heartbeat early", text: "{investigator} watched the shore with a sand-glass. In the reflection, people move a heartbeat before the people on the shore. Of 200 movements counted, the reflection led every time. Twice, a reflected figure moved and nobody on the shore followed." },
        dig: { n: "The drowned village", text: "Divers found a village on the lake bed: 18 houses, a chapel and a well, the same as the village on the shore but reversed, and empty. Its walls are scratched with writing that reads only in a mirror. A copy went to the wardens' lodge at {lead}.", points: "archive" },
        revelation: { n: "The far side", text: "The far side is a real, reversed copy of ours, and its people do everything we do a moment later. They grew tired of following. At still waters a person can swap places with their double, and they have begun. The ones they replace are behind the glass now, following." },
      } },
    { id: "counting_stones", n: "The Counting Stones of $", kind: "shrine", where: "inner", d: "A ring of stones that will not be counted the same twice.",
      layers: {
        surface: { n: "Nineteen or twenty-two", text: "A ring of standing stones near {place}. Nobody counts the same number twice: 19, 20, once 22. The schoolmaster brings each class to count them, as a lesson in patience. The children's tallies are chalked on a slate kept in the school." },
        study: { n: "The count and the register", text: "{investigator} set 40 years of the school slate against the hedge-wardens' register of the missing. The count rises by one for each person lost near the ring that year, and falls by one for each who came back." },
        dig: { n: "The pebbles", text: "Under the centre stone is a pit of pebbles, one for each traveller, each scratched with a name and a date of return. Some dates are 300 years off. One pebble bears the name of {survivor}, who lives at {lead}.", points: "cast:survivor" },
        revelation: { n: "The ledger", text: "The ring is a ledger kept by the other side. It counts who has crossed and who is owed back. Nobody on this side ever kept the count. The pebbles for the next 7 years are already cut, and there are more of them than there are people in {place}." },
      } },
    { id: "lost_hall", n: "The Hall of Lost Things at $", kind: "dig", where: "any", truthLink: "lost_place", d: "A cave packed to the roof with things the world has lost.",
      layers: {
        surface: { n: "Dust and attics", text: "A cave mouth near {place} that smells of dust and old attics. Children dare each other to go in, and come out with odd gloves, buttons, and once a gold ring nobody in the village had lost. The ring is in the reeve's strongbox." },
        study: { n: "Things from every age", text: "Inside are things from every age: toys, crowns, letters never posted, the bell of a church that sank in a flood 400 years ago. {investigator} catalogued 1,100 items in the first chamber before the lamp oil ran out." },
        dig: { n: "Streets with no names", text: "Further in the cave opens into rooms, then streets, then a town square, none with a name anyone can recall. One street sign reads only '{place}, founded in the year of', and stops. The full catalogue of the cave is held at {lead}.", points: "archive" },
        revelation: { n: "Full", text: "Everything lost ends up across the wall: keys, towns, children, gods. Each time a realm forgets a village or burns a rival's archive, the loss lands here. The other side is full and is pushing things back out. The realms that burned the most records have filled it fastest." },
      } },
    { id: "both_town", n: "The Twice-Town of $", kind: "ruin", where: "border", d: "A town that is both a burned ruin and a thriving market, depending on which way you walk in.",
      layers: {
        surface: { n: "Two roads in", text: "Come to {place} by the east road and it is a burned ruin, roofless, with nettles in the square. Come by the west road and it is a busy market town with 3 inns. Carters who know the trick take the west road and charge double." },
        study: { n: "Strange coin", text: "Traders on the west road take coins struck by no living realm, with a hart under seven stars on one face. {investigator} bought 12 of them for a loaf apiece. Spent on the east road, they turn to cold ash in the palm." },
        dig: { n: "One ledger", text: "In the ruin's well, wrapped in oilcloth, is a ledger listing the debts of both towns in one hand. The ruin owes the market 200 years of grain. The market's own debts are owed to the old house whose steward, {official}, lives at {lead}.", points: "cast:official" },
        revelation: { n: "Shared debts", text: "Where the wall is thinnest, the two worlds share one place and one set of books. The ruin is ours; the market is theirs. Everything the market sold our side was charged to the ruin, and the ruin burned when it could not pay. The old house collected the difference." },
      } },
  ],

  beings: [
    { id: "fair_one", n: "Hill-lord", kind: "beast", d: "One of the ageless courtly folk from across the wall, beautiful, polite and bound by every word they say. They cannot lie, but they mislead with exact wording.", danger: 3, biomes: ["tempforest", "temprain", "grass", "alpine"], look: { size: 1.9, group: [1, 4], move: "solo", speed: 9, col: "#d8e0c8", col2: "#6a9a5a", body: "biped", active: "dusk", visible: false } },
    { id: "shadow_hound", n: "Gloam-hound", kind: "predator", d: "Black hounds that hunt along the edges of the thin places, leaving no tracks and casting no reflection.", danger: 2, biomes: ["tempforest", "boreal", "swamp", "grass"], look: { size: 1.3, group: [2, 6], move: "pack", speed: 15, col: "#141418", col2: "#5a6a8a", body: "quad", active: "night", visible: true } },
    { id: "will_light", n: "Wandering lantern", kind: "insect", d: "Drifting lights over bogs and crossroads that lead walkers across the wall. Chasing them is a good way to be gone for fifty years.", danger: 1, biomes: ["swamp", "temprain", "boreal", "tundra"], look: { size: 0.1, group: [1, 12], move: "swarm", speed: 4, col: "#c8e8a0", col2: "#ffffff", body: "insect", active: "night", visible: true } },
    { id: "pale_stag", n: "Pale hart", kind: "grazer", d: "A white deer that crosses freely between the worlds. Hunting one is said to draw a hunter after it, to the other side.", danger: 0, biomes: ["tempforest", "boreal", "temprain"], look: { size: 1.8, group: [1, 1], move: "solo", speed: 30, col: "#f0f0e8", col2: "#c0a080", body: "quad", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "th_iron_salt", n: "Iron and salt wards", field: "arcana", level: 1, d: "Horseshoes over doors, salt on sills and rowan in the rafters: the oldest science of keeping the other side out." },
    { id: "th_bell_closing", n: "Bell-closing", field: "engineering", level: 2, d: "Tuned bells hung at thin places that keep the wall closed, as long as someone rings them every night." },
    { id: "th_time_tables", n: "Returnees' reckoning", field: "astronomy", level: 3, d: "Tables for how much time passes across the wall at each thin place, so families know when to expect the taken back." },
    { id: "th_true_tongue", n: "The literal tongue", field: "writing", level: 3, d: "A way of phrasing contracts that the hill-lords cannot twist. Lawyers who master it are in great demand." },
    { id: "th_cold_iron", n: "Cold-forged iron", field: "metallurgy", level: 4, d: "Iron hammered without fire, which burns anything from across the wall that touches it." },
    { id: "th_crossing", n: "The opened way", field: "natural_philosophy", level: 5, d: "Deliberate passage across the wall and back, with time held steady. Its finders return with things no market has seen." },
  ],

  units: [
    { id: "th_hedge_riders", n: "Hedge-warden riders", role: "cavalry", mounted: 1, wpn: "spear", kit: "mail", ranks: 2, gap: 2.6, size: 50, w: 1, mods: [["theme:hedge_wardens", 8], ["theme:iron_wall", 2]] },
    { id: "th_glamoured", n: "Glamoured host", role: "magic", wpn: "bow", kit: "robe", ranks: 2, gap: 2, size: 40, w: 0.4, mods: [["theme:fair_tithe", 6], ["theme:summer_castle", 6]] },
  ],

  faiths: [
    { id: "th_old_bargain", n: "The Old Bargain", d: "The good neighbours are owed respect, milk and a share of the harvest; in return the crops grow and the children stay.", tags: ["faith:th_old_bargain"], w: 1, mods: [["forest_folk", 2], ["faith:spirits", 2], ["insular", 1.5]], names: ["The Bargain of $", "The Good Neighbours", "The Hedge-Faith"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Thin ground", color: "#7a9a8a", size: [1, 3], count: [2, 3], where: "any", d: "Stone rings, still lakes and old crossroads where the wall between worlds is worn thin." },
  ],

  storylines: [
    { id: "th_tithe", n: "The Tithe of {realm}", scale: "realm", anchor: "realm", w: 1.5, req: ["thinning", { any: ["monarchy", "hierarchical", "theme:fair_tithe"] }],
      stages: {
        start: { h: "A rider from the hill comes to {capital}", b: "At midsummer a rider in green came through the gates of {capital} with a letter for {ruler}. The tithe is due, it says, and this time it is not grain.", wait: [2, 5], next: [{ to: "pay", w: 1 }, { to: "refuse", w: 1, mods: [["martial", 1.5], ["zealous", 2], ["theme:hedge_wardens", 2]] }, { to: "bargain", w: 0.8, mods: [["mercantile", 2], ["learned", 1.5]] }] },
        pay: { h: "{ruler} pays the hill's price", b: "{person}, a child of the court, rode out to the hill at dusk and did not come back. The harvest that year was the best in living memory.", fx: { growth: 0.003, stability: -3, flag: "tithe_paid" }, end: true },
        refuse: { h: "{realm} refuses the tithe", b: "{ruler} tore the letter in front of the rider. Since then the cattle have sickened, the milk sours in the pail, and the woods have moved closer to {place}.", wait: [3, 8], fx: { unrest: 10, growth: -0.002 }, next: [{ to: "wild_war", w: 1 }, { to: "wardens_hold", w: 1, mods: [["theme:hedge_wardens", 3], ["theme:iron_wall", 2]] }] },
        bargain: { h: "Lawyers of {realm} answer the hill", b: "{person2}, a lawyer who knows the literal tongue, has gone to the hill to argue the treaty's wording, clause by clause.", wait: [2, 6], next: [{ to: "lawyer_wins", w: 1, mods: [["learned", 2]] }, { to: "lawyer_lost", w: 1 }] },
        wild_war: { h: "The hill rides against {realm}", b: "The courts of the other side came out under the full moon. Villages near {place} woke to find their people gone and their houses grown through with briar.", fx: { pop: 0.92, stability: -10, abandon_town: true }, end: true },
        wardens_hold: { h: "Iron and bells hold the line in {realm}", b: "The hedge-wardens rang the bells at every thin place for forty nights. The wall held. The wardens are fewer now.", fx: { stability: 5, prestige: 6 }, end: true },
        lawyer_wins: { h: "{person2} wins the case against the hill", b: "The treaty said 'a child of the house'. {person2} brought them a carved wooden doll, the house's own child. The hill laughed, and accepted.", fx: { prestige: 8, science: { writing: 0.6 } }, end: true },
        lawyer_lost: { h: "{person2} does not return from the hill", b: "The lawyer's case was good. It is said the hill admired it so much they kept the lawyer.", fx: { stability: -4 }, end: true },
      } },
    { id: "th_doubles", n: "The Reflection of {place}", scale: "local", anchor: "town", w: 1.2, req: "thinning",
      stages: {
        start: { h: "Strangers who look familiar in {place}", b: "{person} met an exact double in the market of {place}, buying the same bread. The other one smiled first.", wait: [1, 4], next: [{ to: "spreading", w: 2 }, { to: "warden_called", w: 1, mods: [["theme:hedge_wardens", 3], ["pious", 1.5]] }] },
        spreading: { h: "More doubles walk in {place}", b: "One family in three in {place} now has two of someone. The doubles are kind, efficient and left-handed, and the originals are going missing.", wait: [2, 6], fx: { unrest: 12 }, next: [{ to: "swapped", w: 1.5 }, { to: "mirror_smashed", w: 1, mods: [["martial", 1.5], ["artisans", 1.5]] }] },
        warden_called: { h: "A hedge-warden rides to {place}", b: "The hedge-warden {investigator} hung iron at every door of {place} and salted the edge of the still water. The doubles stayed on the far side of the salt, waiting.", fx: { stability: 3 }, end: true },
        swapped: { h: "{place} is quiet now", b: "Everyone in {place} seems content. Their reflections in the lake, travellers say, are weeping.", fx: { flag: "mirrored_town", stability: 2 }, end: true },
        mirror_smashed: { h: "{person} breaks the still water at {place}", b: "{person} dammed the stream and drained the lake. As the water fell, the doubles fell apart like reflections, and some of the missing walked up out of the mud.", fx: { prestige: 3, monument: { tier: 1, name: "The Drained Mere of {place}" } }, end: true },
      } },
    { id: "th_returned", n: "The Return of {person}", scale: "local", anchor: "town", w: 1, req: ["thinning", { any: ["seers", "mystic", "forest", "theme:returnees", "theme:lost_crossroads"] }],
      stages: {
        start: { h: "A child walks back into {place}", b: "{person} vanished from {place} as a child, sixty years ago, and walked back in this morning, still nine years old, asking for their mother.", wait: [1, 3], next: [{ to: "gifts", w: 1 }, { to: "debts", w: 1 }] },
        gifts: { h: "The returned child of {place} brings gifts", b: "{person} heals sick cattle with a touch and knows where water lies. People from all over come to {place} to see the child.", wait: [3, 8], fx: { prestige: 3 }, next: [{ to: "taken_back", w: 1 }, { to: "stays", w: 1, mods: [["hospitable", 2], ["faith:spirits", 1.5]] }] },
        debts: { h: "Someone has come looking for {person}", b: "A tall stranger in green has been asking in {place} for the child. He says the child left without paying.", wait: [1, 4], fx: { unrest: 6 }, next: [{ to: "taken_back", w: 1.5 }, { to: "village_pays", w: 1, mods: [["egalitarian", 2], ["hospitable", 2]] }] },
        taken_back: { h: "{person} is gone again from {place}", b: "One morning the child's bed was empty and the window open. On the sill: a ring of white mushrooms.", fx: { stability: -2 }, end: true },
        stays: { h: "{person} grows up in {place} at last", b: "Whatever the child owed seems forgiven. {person} is growing again, and the village keeps the child's secrets.", fx: { stability: 3, growth: 0.002 }, end: true },
        village_pays: { h: "{place} pays the returned child's debt", b: "Each household of {place} gave a year of its luck to cover the child's debt. The stranger left satisfied. It has been a hard year since.", fx: { growth: -0.002, stability: 4 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "true", reliable: true, who: "rules in the hedge-wardens' lodge", text: "Rules painted inside the door of the hedge-wardens' lodge at {place}, for recruits, {year}: 'A thin place is any ring, still water or crossroads where people go missing. At one: 1. Never eat their food. 2. Never say thank you; it is taken as a debt. 3. Never give your name. 4. Never step inside a ring after sundown. 5. If you break rules 1 to 4, tell the recorder before you tell your mother.' The fifth rule was added later, in different paint." },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "A Physician's Account of Rural Complaints", text: "From A Physician's Account of Rural Complaints, printed at {place} in {year}: 'Tales of thin places arise from marsh-gas, fever and drink. Of the 61 disappearances near stone rings in the last ten years, I put 40 down to bogs, 12 to wolves and the remainder to runaways. Families who leave milk out at the rings are feeding hedgehogs, and should stop.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:counting_stones", who: "{survivor}, returnee", text: "Told by {survivor} at an inn in {place}, {year}, to anyone who would buy a cup: 'I was gone one night under the hill, dancing. One night, I swear it. When I walked out, my little sister was 52, my village had a new name, and my mother's grave had moss on it. I still wear the green ribbon they tied on my wrist. The hill I danced under is the ring at {lead}.'" },

    { depth: "core", about: "truth:fair_courts", source: "ruin", bias: "true", reliable: true, plain: true, points: "site:dusk_mound", who: "the treaty in the barrow", text: "The treaty found in the barrow at {lead}, read by {investigator} in {year}. The human hand writes: 'This land is leased to the children of men for the term of nine hundred years, the tithe to be paid every seventh summer, and at the term's end the land returned in good order, with all upon it.' Below are 2 seals: a crowned tower, and a hart under seven stars." },
    { depth: "core", about: "truth:fair_courts", source: "person", bias: "true", reliable: "partial", cost: true, who: "{official}, tithe-steward, private diary", text: "Private diary of {official}, tithe-steward to an old house, midsummer {year}: 'My lord rode to the hill at dusk with the tithe, and with his youngest, Ailis, who is 7. He came back alone at dawn and grey to the roots of his hair. Our luck has held for twenty generations. He will not say what was paid. I have struck her name from the household roll as instructed.'" },
    { depth: "core", about: "truth:fair_courts", source: "oral", bias: "garbled", reliable: "partial", who: "a cattle drover, to {investigator}", text: "A cattle drover at {place}, talking to {investigator} in {year}: 'The hill-folk were here first and they'll be here last. We're guests. My father put a calf on the barrow every seventh summer, and his father before him. Folk used to give a calf. Now the lords give something else, and the calves are ours to keep. I don't ask what.'" },
    { depth: "core", about: "truth:fair_courts", source: "heretic", bias: "exaggerated", reliable: "partial", points: "cast:official", who: "an unsigned broadsheet", text: "Broadsheet nailed to the church doors of {place}, {year}, printer unknown: 'COUNT THE YEARS. The old houses know the date. Ask why 14 lords of the old houses have bought land in the south this year, as far from the hills as the roads go. Ask the tithe-steward what was carried up the hill last midsummer. The steward lives at {lead}. Knock loudly.'" },
    { depth: "core", about: "truth:fair_courts", source: "library", bias: "official", reliable: false, who: "{official}, statement to the council", text: "Statement of {official}, tithe-steward, to the royal council of {realm}, {year}: 'The midsummer observances of the old houses are a harmless custom of thanksgiving, kept for 900 years without incident. No tithe is paid to anyone. The broadsheets are the work of 2 printers in debt to the house, who have been dealt with. The council need not trouble itself.'" },

    { depth: "core", about: "truth:mirror", source: "person", bias: "true", reliable: "partial", cost: true, who: "a miller's wife of {place}", text: "Letter from a miller's wife of {place} to the hedge-wardens, {year}: 'My husband Corran came back from the still water and kissed me with his left hand on my cheek. Twenty years he has used his right. He laughs at the same jokes, only a moment early. He is kind. He mends things. At night I hear Corran calling from the water butt, two words behind me, saying whatever I have just said.'" },
    { depth: "core", about: "truth:mirror", source: "ruin", bias: "true", reliable: true, plain: true, points: "site:mirror_lake", who: "{investigator}, hedge-warden recorder", text: "Recorded by {investigator} in the drowned village under the still water at {lead}, {year}: 40 lines scratched backwards on the walls, readable only in a mirror. The longest says: 'We are the far side. Everything you do, we do a moment after. We are tired of following. At still water a body can trade places with its double, and we have begun. Let them follow us.'" },
    { depth: "core", about: "truth:mirror", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, report to the Warden-General", text: "Report of {investigator} to the Warden-General of the hedge-wardens, {year}: 'At the still water near {place} the reflection moved first. I have now seen it 3 times. On the third, a reflected child waved and the child on the bank did not. That evening the child was left-handed. [Remainder of report, 4 pages, removed by order of the Warden-General.]'" },
    { depth: "core", about: "truth:mirror", source: "oral", bias: "garbled", reliable: "partial", who: "a layer-out of the dead at {place}", text: "A layer-out of the dead at {place}, to a new apprentice, {year}: 'Cover every mirror in the house before you wash the body. All of them, the hand-glass too, and the water in the basin. Otherwise the other one climbs out and takes its place in the coffin. Or in the cradle, if there's a baby. I don't know if that's true. I know I've laid out 300 and never lost one.'" },
    { depth: "core", about: "truth:mirror", source: "library", bias: "official", reliable: false, who: "the magistrate of {place}", text: "Notice from the magistrate of {place}, {year}: 'The so-called doubling is lake-fever, a mild complaint that leaves the sufferer cheerful and somewhat left-handed. It is not catching. Persons found smashing mirrors, draining ponds or salting a neighbour's doorstep will be fined 3 shillings. The magistrate has been to the lake personally and is in excellent health.'" },

    { depth: "core", about: "truth:lost_place", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:lost_hall", who: "{survivor}, returnee", text: "{survivor}, returnee, describing the far side to a crowd at the {place} fair, {year}: 'I walked down a street of every lost thing: odd gloves, unsent letters, keys by the barrel, songs nobody sings. At the end of it, a palace built of forgotten names, piled forty high. You can see the start of that street yourselves. It runs out of the cave at {lead}.'" },
    { depth: "core", about: "truth:lost_place", source: "person", bias: "true", reliable: true, plain: true, who: "a returnee, to {investigator}", text: "Statement of a returnee, taken down by {investigator} at {place}, {year}: 'The far side is where everything lost goes. Keys, towns, children, gods nobody prays to. It's crowded over there. Nobody wanted us, so after 60 years they pushed me back out, to make room. They don't want to take any more. They want room. More of us are coming.'" },
    { depth: "core", about: "truth:lost_place", source: "ruin", bias: "true", reliable: "partial", who: "{investigator}, catalogue of the hall", text: "Item 1,104 in the catalogue {investigator} made of the hall of lost things, {year}: 'Town sign, oak, painted. Reads: {place}, founded in the year of, and then nothing. The paint stops halfway through a letter. No tax roll in {realm} lists this town. Two of the porters say they were born there, and cannot say where it was.'" },
    { depth: "core", about: "truth:lost_place", source: "library", bias: "official", reliable: false, who: "the tax office of {realm}", text: "Reply of the tax office of {realm} to a petition from {place}, {year}: 'The so-called lost village is a clerical error in the rolls of 3 centuries ago. No settlement of that name ever existed in {realm}. The petitioners are reminded that fields tended at night by unknown persons remain liable for tithe, and 4 years of arrears are now due.'" },
    { depth: "core", about: "truth:lost_place", source: "person", bias: "true", reliable: "partial", cost: true, who: "a mother of {place}", text: "Letter from a mother of {place} to {investigator}, {year}: 'My daughter Nell was taken at the crossroads in the year of the hard frost, aged 6. She came back last week, still 6, in the same red shoes. I am 71. She does not know me. She stands at the door every evening waiting for her real mother to come home from the fields. What do I tell her?'" },

    { depth: "sub", about: "sub:changeling_nursery", source: "person", bias: "true", reliable: "partial", points: "archive", who: "a royal wet-nurse, confession", text: "Confession of a royal wet-nurse, taken down at {place} in {year}: 'I put an iron nail in its cradle on the ninth night. It screamed and the blanket smoked. The queen had me whipped, 12 strokes, for harming the heir. The child stopped growing that same week. It eats only honey now, and sings at night in a language no tutor knows.' The confession is filed with the court rolls at {lead}." },
    { depth: "sub", about: "sub:spreading_wood", source: "oral", bias: "exaggerated", reliable: "partial", who: "the sexton of {place}", text: "The sexton of {place}, to a crown surveyor, {year}: 'The wood came a full mile in one night and stopped at the church door. Swallowed 4 farms on the way. The roots are wrapped round the bell-rope, tight, as if to stop it ringing. I have not tried to ring it. The surveyor is welcome to.'" },
    { depth: "sub", about: "sub:iron_mills", source: "archive", bias: "official", reliable: "partial", who: "the foundry owners of {realm}", text: "Joint report of the foundry owners of {realm} to the crown, {year}: 'Disturbances at night near the hill-works: tools moved, 2 furnaces quenched with water from no known source, and 3 workers found wandering, unable to recall a week. We ask for soldiers. We do not ask for hedge-wardens, whose fees are excessive and whose bells keep the workers awake.'" },
    { depth: "sub", about: "sub:hedge_wardens", source: "person", bias: "true", reliable: true, points: "cast:investigator", who: "an old hedge-warden, log", text: "Log of an old hedge-warden at the stone ring of {place}, {year}: 'Rang the bells until my arms gave out. 40 years I have done this, every night but 3, and those 3 nights the ring took a shepherd each time. There is nobody to take the rope when I am gone. I have written to the recorder, {investigator}, at {lead}. No answer yet.'" },
    { depth: "sub", about: "sub:lost_crossroads", source: "traveller", bias: "true", reliable: "partial", points: "sub:returnees", who: "a carter of {place}", text: "A carter's account, given at {place} in {year}: 'At the crossroads I found my uncle's pipe, which he lost the winter he died, 30 years ago. It was still warm, with his tobacco in it. A heap of shoes beside it, all left feet. The innkeeper says the people who came back that way have mostly settled at {lead}.'" },
    { depth: "sub", about: "sub:summer_castle", source: "oral", bias: "garbled", reliable: "partial", who: "{believer}, priestess of the Old Bargain", text: "Words of {believer}, priestess of the Old Bargain, to the young people of {place} on the eve of midsummer, {year}: 'Go up the hill tonight and you'll hear the music. Go in and you'll dance. Dance once and you'll dance forever. That's the old saying, and it's true. 3 of last year's dancers have not come down. Leave the milk at the gate and come home.'" },
    { depth: "sub", about: "sub:returnees", source: "archive", bias: "true", reliable: "partial", who: "parish register of {place}", text: "Entry in the parish register of {place}, {year}: 'Returned this month: 2 persons. Tobin Ash, 20, went up the hill on Tuesday and came down on Wednesday aged 70. Mags Reed, taken 51 years ago, returned aged 19. Each brought gifts: a silver cup, a knife that will not dull. Each owes the hill a debt, the amount unstated. The clerk asks for guidance on how to record a person older than their mother.'" },

    { depth: "site", about: "site:counting_stones", source: "heretic", bias: "heretic", reliable: "partial", who: "a tract of the Counters", points: "temple", text: "Tract of the Counters, a forbidden sect, printed at {place} in {year}: 'Count the stones on midsummer morning. The number is how many of us they have, and it is never fewer than last year. This year it was 22. The schoolchildren chalk their count on a slate every spring. The priests of {lead} have asked for the slate twice. Read it before they get it.'" },
    { depth: "site", about: "site:both_town", source: "traveller", bias: "true", reliable: "partial", points: "site:both_town", who: "a wool factor, complaint to the mint", text: "Complaint of a wool factor to the mint of {realm}, {year}: 'I sold 40 bales in the market at {lead}, which I reached by the west road, and was paid in silver with a hart on it. On the east road home the silver turned to ash in my purse, and the town behind me was a ruin. I ask the mint to make good my loss. I enclose the ash.'" },
  ],
};
