// The Unquiet Gate: the way to the land of the dead is broken, and the dead no longer leave.
export default {
  id: "unquiet_gate",
  name: "The Unquiet Gate",
  family: "world",
  kind: "cycle",
  pitch: "The road to the land of the dead is broken, and for generations nobody who dies has left. The dead fill the streets as cold mist, crowd the houses and keep their seats at table, and soon they will outnumber the living.",
  slots: ["afterlife", "apocalypse"],
  tone: ["horror", "melancholy"],
  era: ["bronze", "medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "grimdark", "mythic"],
  w: 1,
  excludes: ["wardens_gaol"],
  pairs: [{ id: "last_kindling", w: 3 }, { id: "hush_below", w: 2 }, { id: "great_root", w: 2 }, { id: "wheel_of_suns", w: 1.5 }, { id: "ward_walls", w: 1.5 }, { id: "unremembering", w: 1.2 }],

  // the hidden truth: a world picks one
  cast: [
    { role: "investigator", n: "a registrar of the grave census, who counts and interviews the dead for the crown", home: "inner", stance: "Believes the dead can be counted like anyone else, and that the numbers will say where they are meant to go." },
    { role: "official", n: "a chamberlain of the Veiled Tower who speaks and signs for the Founder", home: "capital", stance: "Holds that the realm's order depends on the Founder, and that nobody needs to know more than the proclamations say." },
    { role: "believer", n: "a senior bell-ringer of the Toll", home: "remote", stance: "Is certain the next peal will find the gate, and has rung for 30 years to prove it." },
    { role: "survivor", n: "a gate-seeker who came back alive from the cliff, without the company that went with them", home: "coast", stance: "Wants the realm to hear what the dead in the queue said, and wants the company's names read out." },
  ],

  truths: [
    { id: "dead_ferryman", n: "The Ferryman is dead", d: "A keeper once rowed each soul across the dark water to the land of the dead, for one bronze coin. The first river-king wanted the ford and its fares, and had soldiers spear the keeper at the crossing. With no one to row them, the dead cannot find the way, so they walk back to the places they loved. The crown still stamps the river-king's tower on its coins.", tags: ["truth:dead_ferryman"],
      known: [
        "The Toll's oldest hymn calls on 'the Rower' to take the dead home. The ringers no longer know who the Rower was, and the temple calls it a figure for time. Bronze coins stamped with a faceless rower turn up in old graves.",
        "A riverbank shrine says soldiers of the river-king waited for the Rower at the ford. The dead who will talk say they went to the water and found nobody at the oars.",
        "A black boat lies on a dried riverbed. Under it is a faceless body in a rower's cloak, pinned to the mud by 7 iron spears marked with the old river-kings' tower. The boat's bench is worn hollow.",
        "Confirmed: the first river-king had the keeper of the dead killed for the ford and its fares. The dead have walked home ever since, and the crown still mints the tower mark.",
      ] },
    { id: "full_house", n: "The house of the dead is full", d: "The land of the dead was never endless. It has filled rank on rank since the first burial, and the wars and plagues of the last few centuries filled its last rooms. Now each new soul that arrives pushes an old one back out into the world, through the nearest grave. Every war a realm starts sends a crowd of strangers into its own kitchens.", tags: ["truth:full_house"],
      known: [
        "Ghosts appear who speak no living tongue and wear the dress of forgotten empires. They are frightened, and they say they were pushed. The temple says only the wicked are refused entry to the halls of the dead.",
        "A town crypt fills with old bones every year though nobody has been buried there in 80 years. Many of the skulls are not quite those of living peoples. The oldest dead are coming back first.",
        "A gate-seeker who came back from the cliff says the dead in the queue all tell the same story: the house had only so many rooms. When a child dies, a stranger appears in that house the next night.",
        "Confirmed: the land of the dead is full. Each new death pushes an old soul out, and crypts fill fastest in years of war. The realms that fight most are filling their own streets.",
      ] },
    { id: "sealed_gate", n: "A king shut the door", d: "The realm's first king, afraid to die, had the gate of the dead walled up with 4,000 cartloads of black stone and cut away death's own face so it could not take him. He is still alive, withered and pulseless, in a tower in the capital. Every restless ghost in the world is the price of his life, and his chamberlains still sign his orders.", tags: ["truth:sealed_gate"],
      known: [
        "The Founder of the realm has ruled from behind a veil for 400 years. The crown says the veil is worn by his descendants out of reverence. The rings on the hands under it have never changed.",
        "A builder's contract from the founding year orders 4,000 cartloads of black stone laid at the sea-cliff, and every mason's mark destroyed afterward. Between the black pillars on that cliff, the door of the dead was dragged shut from this side.",
        "A palace physician wrote that the Founder has no pulse and asks every morning whether the door still holds. The Veiled Tower was built in the same year the parish rolls record the last departure of the dead.",
        "Confirmed: the first king sealed the gate of the dead and cut away death's face so he would never die. He sits in the Veiled Tower still. Every ghost in the world is waiting on him.",
      ] },
  ],

  tags: ["restless_dead"],

  subthemes: [
    { id: "ancestor_veto", n: "The Council of Grandfathers", d: "The city's dead sit in the council hall and vote. They outnumber the living councillors nine to one, and nothing has changed in two hundred years.", w: 1.4, req: { any: ["ancestor_bound", "faith:ancestors", "hierarchical", "origin:old_dynasty"] }, mods: [["has:city", 1.5], ["republic", 1.5]], tags: ["theme:ancestor_veto"] },
    { id: "bone_legions", n: "The Bone Legions", d: "A necromancer house raises the war dead of every old battle and hires them out by the thousand. They do not eat, desert or ask for pay.", w: 1.2, req: { any: ["martial", "arcane", "gov:magocracy", "autocracy", "near:ruins"] }, mods: [["atwar", 2], ["standing_army", 1.5]], tags: ["theme:bone_legions"], mark: { kind: "zone", n: "The Marching Fields", color: "#6e6a5c", size: [1, 3], where: "border" } },
    { id: "dead_heirs", n: "The Inheritance of the Dead", d: "The dead still own their land, and their courts still hear their suits. Grandsons wait sixty years for a house their grandmother will not give up.", w: 1.2, req: { any: ["monarchy", "mercantile", "dynastic", "hierarchical"] }, tags: ["theme:dead_heirs"] },
    { id: "bell_ringers", n: "The Bell-Ringers", d: "Priests who guide ghosts with chimes and toll them, one by one, towards a gate nobody has seen. The bells are cracking and the foundry that cast them is gone.", w: 1.3, req: { any: ["pious", "organised", "gov:theocracy", "faith:one_god", "faith:pantheon"] }, truthLink: "dead_ferryman", tags: ["theme:bell_ringers"] },
    { id: "pressed_back", n: "The Returned Ancients", d: "Ghosts appear who speak no living tongue and wear the dress of empires nobody remembers. They are frightened, and they say they were pushed.", w: 1, req: { any: ["near:ruins", "scholarly", "ancestor_bound"] }, truthLink: "full_house", tags: ["theme:pressed_back"] },
    { id: "possession_plague", n: "The Wearing Sickness", d: "In crowded quarters, ghosts with nowhere else to go have begun to slip into the sleeping living. The possessed wake speaking in a dead man's voice and will not give the body back.", w: 1.1, req: { any: ["has:city", "urbane", "poor", "realm:large", "realm:vast"] }, truthLink: "full_house", tags: ["theme:possession"] },
    { id: "deathless_court", n: "The Deathless Court", d: "The founder of the realm has ruled for four hundred years from behind a veil. His heralds say he is merely old. His physicians are never seen to leave.", w: 0.7, req: { any: ["autocracy", "gov:absolute", "gov:empire", "origin:old_dynasty"] }, truthLink: "sealed_gate", tags: ["theme:deathless_court"], mark: { kind: "zone", n: "The Veiled Demesne", color: "#3e3550", size: [1, 2], where: "capital" } },
    { id: "massacre_ghosts", n: "The Unburied Village", d: "The ghosts of a massacre stand in the road where they fell, every night, and wait for justice. The grandsons of the soldiers who did it still sit in the provincial court.", w: 1, req: { any: ["harsh_law", "atwar", "frontier", "martial"] }, tags: ["theme:massacre_ghosts"] },
    { id: "hidden_child", n: "The Child in the Attic", d: "Families hide their returned dead, especially children, from the priests who would bell them away. Every street has a window that is never opened.", w: 0.9, req: { any: ["egalitarian", "forest_folk", "river_folk", "insular"] }, tags: ["theme:hidden_dead"] },
    { id: "salt_towns", n: "The Salt-Walled Towns", d: "Towns ringed with salt and iron, their gates hung with bells, where the living still keep the dead out. Salt costs more than silver, and salt merchants are princes.", w: 1.1, req: { any: ["coastal", "desert", "mercantile", "has:port"] }, mods: [["desert", 1.5]], tags: ["theme:salt_towns"] },
    { id: "gate_seekers", n: "The Gate-Seekers", d: "Pilgrims who walk towards the old gate of the dead, meaning to open it again with their hands. None has come back alive, though a few have returned as ghosts.", w: 1, req: { any: ["pilgrims", "mystic", "seers", "ascetic"] }, truthLink: "sealed_gate", tags: ["theme:gate_seekers"] },
    { id: "keeper_relics", n: "The Ferryman's Coins", d: "Bronze coins stamped with a faceless rower turn up in graves older than any mint. Laid on a ghost's eyes, they make it go still and quiet, for a while.", w: 0.9, req: { any: ["river", "river_folk", "seafaring", "near:ruins"] }, truthLink: "dead_ferryman", tags: ["theme:ferry_coins"] },
  ],

  sites: [
    { id: "broken_gate", n: "The Broken Gate of $", kind: "ruin", where: "remote", d: "Twin pillars on a sea-cliff with nothing between them but cold air, where the dead gather in their thousands and wait.",
      layers: {
        surface: { n: "The pillars", text: "Two black pillars stand on a sea-cliff near {place}, 60 feet high, with nothing between them but cold air. The mist there is thick enough to lose a hand in, and faces show in it. Fishing boats will not come within sight of the cliff." },
        study: { n: "The procession", text: "{investigator} took rubbings of the carvings on 30 sheets of paper. They show the dead walking out to sea in a line, led by a figure with no face carrying an oar. The last panels have been chiselled off, centuries after the rest were cut." },
        dig: { n: "The hinges", text: "Under 9 feet of ash between the pillars lie bronze hinges as long as a man. The door they held was not broken. It was dragged shut and wedged with black stone, and every wedge is driven in from our side. The quarry that cut that stone is recorded at {lead}.", points: "archive" },
        revelation: { n: "The queue", text: "The way to the dead was never lost. The door is wedged shut, and the dead have queued at it ever since. {investigator} counts 2 million in sight of the cliff on a clear night. Every one of them faces the door. None of them faces us." },
      } },
    { id: "beached_ferry", n: "The Dry Keel of $", kind: "anomaly", where: "any", truthLink: "dead_ferryman", d: "A long black boat lies on the bed of a river that dried up the year the dead stopped leaving.",
      layers: {
        surface: { n: "The black boat", text: "A boat of black wood lies on the bed of a river near {place} that dried up the year the dead stopped leaving. It has not rotted. No ghost will go within 40 paces of it, and the village dogs will not either." },
        study: { n: "Oar and bench", text: "Its single oar is snapped clean through. Its single bench is worn into a hollow by passengers beyond counting. Under the bench {investigator} found 2,000 small bronze coins, each stamped with a faceless rower." },
        dig: { n: "Seven spears", text: "Under the hull lies a huge faceless body in a rower's cloak, pinned to the riverbed by 7 iron spears. Each spear carries the tower mark of the old river-kings. The royal armoury's issue rolls for that year are kept at {lead}.", points: "archive" },
        revelation: { n: "The murder at the ford", text: "The keeper of the dead was murdered on its own river. The first river-king wanted the ford and its fares, and sent soldiers to wait for the Rower. With no one to row them, the dead walk home. The crown of {realm} still stamps the tower on its coins." },
      } },
    { id: "quiet_cemetery", n: "The Quiet Yard of $", kind: "shrine", where: "inner", d: "A graveyard where no ghost has ever risen, though the town around it is thick with them.",
      layers: {
        surface: { n: "Untroubled graves", text: "In the middle of haunted {place} is an old yard where no ghost has ever risen. Mourners carry their dead here from 3 weeks away and pay the sexton in salt. The waiting list for a plot is 11 years long." },
        study: { n: "Face down", text: "{investigator} opened 12 graves with the sexton's leave. Every grave is shallow, and every body lies face down with hands flat, as if reaching for something under the yard. The oldest headstones say only: 'Down, not back.'" },
        dig: { n: "The bronze door", text: "A stair under the oldest tomb goes down to a small round door of bronze, warm to the touch and open by a finger's width. Cold air flows through it, inward. The bell-ringer {believer} wants to toll it wider, and lives at {lead}.", points: "cast:believer" },
        revelation: { n: "The crack", text: "This is a crack in the way to the dead, the only one anyone has found. The dead buried here slip through, about one a week. It could be widened. The Toll has known for a century and has kept the plots for its own priests and the families who can pay." },
      } },
    { id: "packed_crypt", n: "The Overflowing Crypt of $", kind: "dig", where: "any", truthLink: "full_house", d: "A crypt whose lowest chambers fill again with bones every year, though no one is buried there.",
      layers: {
        surface: { n: "The sexton's spring", text: "A town crypt under {place}. The sexton swears the bottom vault is cleared every spring, and has the carters' receipts: 14 carts of bones last year. Nobody has been buried in that vault for 80 years." },
        study: { n: "Old new bones", text: "The new bones are old: stained brown, brittle, and some not quite the bones of people. {investigator} sorted 300 skulls; 40 have a heavy ridge above the eyes that no living people have. The crypt is filling with the oldest dead first." },
        dig: { n: "The pressed floor", text: "The vault floor is a sheet of grey stone polished smooth by pressure from below, and it is cracking upward in a star. A ghost in bronze-age dress was found standing on it. The scholar who questioned it sent the notes to {lead}.", points: "library" },
        revelation: { n: "Pushed out", text: "The house of the dead is full. The wars and plagues of the last centuries filled its last rooms, and each new soul now pushes an old one out through the nearest grave. The crypt under {place} fills fastest in the years {realm} is at war." },
      } },
    { id: "veiled_tower", n: "The Veiled Tower of $", kind: "ruin", where: "capital", truthLink: "sealed_gate", d: "A tower in the old capital whose top room holds a death-mask of no human face.",
      layers: {
        surface: { n: "The lit window", text: "A sealed tower in {place} with one lit window. The guard changes every hour and never speaks. Pedlars sell lamp-oil at its foot, because the tower buys 3 barrels a month and has done for centuries." },
        study: { n: "The founding year", text: "The building rolls show the first king raised the tower in the same year the parish rolls record the last departure of the dead. The masons' marks on every stone are chiselled off. The tower's oil orders are signed by the chamberlain {official}." },
        dig: { n: "The top room", text: "In the top room is a mask of grey wax shaped like no face at all, and a chair holding a withered man with no pulse who answers to the Founder's name. His physicians' daybooks, 400 years of them, are kept at {lead}.", points: "archive" },
        revelation: { n: "Death's face", text: "The first king walled up the gate of the dead and cut away death's own face so death could not take him. Every ghost in the world is the price of his life. His chamberlains still sign his orders, and he still asks each morning whether the door holds." },
      } },
  ],

  beings: [
    { id: "lingerer", n: "Lingerer", kind: "beast", d: "A ghost that has forgotten its name and wanders the old roads in a cold drifting cloud, drawn to warmth and candlelight. One alone is harmless; a crowd of them can chill a person to death.", danger: 1, biomes: ["tempforest", "grass", "swamp", "boreal", "temprain", "coast"], look: { size: 1.7, group: [3, 20], move: "swarm", speed: 2, col: "#b8bcc4", col2: "#7a8090", body: "biped", active: "night", visible: true } },
    { id: "grave_wraith", n: "Grave-wraith", kind: "predator", d: "A ghost so starved for warmth that little of it is left. It drains heat from sleepers and leaves them cold and grey by morning.", danger: 3, biomes: ["swamp", "tundra", "boreal", "badlands", "colddesert"], look: { size: 2.1, group: [1, 2], move: "solo", speed: 10, col: "#4a4e5a", col2: "#9fe0d8", body: "biped", active: "night", visible: false } },
    { id: "mourning_crow", n: "Mourning crow", kind: "bird", d: "A grey-headed crow that follows the dead and sits on the roofs they haunt. Bell-ringers keep them to find ghosts.", danger: 0, biomes: ["grass", "tempforest", "boreal", "coast", "badlands"], look: { size: 0.5, group: [4, 30], move: "flock", speed: 40, col: "#3a3a40", col2: "#a0a0a8", body: "bird", active: "dusk", visible: true } },
    { id: "barrow_hound", n: "Barrow-hound", kind: "predator", d: "The dead hounds of dead hunters, still running their masters' old courses across the moors. They tear at anything that smells alive.", danger: 2, biomes: ["grass", "coldsteppe", "tundra", "alpine"], look: { size: 1.2, group: [3, 7], move: "pack", speed: 22, col: "#5a5a52", col2: "#c8d0c8", body: "quad", active: "night", visible: true } },
  ],

  techs: [
    { id: "ug_salt_iron", n: "Salt-iron wards", field: "metallurgy", level: 1, d: "Iron folded with sea salt makes lintels, nails and blades that the dead will not cross or touch." },
    { id: "ug_tolling", n: "The science of tolling", field: "arcana", level: 2, d: "Bells cast to exact tones that calm, gather or drive the dead. Each ringer learns a hundred peals by heart." },
    { id: "ug_grave_census", n: "The grave census", field: "writing", level: 2, d: "Registers of the dead: their names, their claims, their haunts. Some realms tax them." },
    { id: "ug_quiet_burial", n: "Downward burial", field: "architecture", level: 3, d: "Tombs built deep and facing down, with lead seals, so the dead stay in their graves a little longer." },
    { id: "ug_raising", n: "The grave levy", field: "warfare", level: 4, d: "Rites that bind the war dead to a standard, so that every lost battle adds to the army." },
    { id: "ug_death_mask", n: "The masking of death", field: "arcana", level: 5, d: "The forbidden rite that lets a living person strip away their own death, so they never die. Only one has ever finished it." },
  ],

  units: [
    { id: "ug_bone_legion", n: "Bone legion", role: "infantry", wpn: "spear", kit: "light", ranks: 8, gap: 1, size: 200, w: 0.6, mods: [["theme:bone_legions", 12], ["gov:magocracy", 2]] },
    { id: "ug_bell_wardens", n: "Bell wardens", role: "magic", wpn: "staff", kit: "robe", ranks: 2, gap: 3, size: 30, w: 0.8, mods: [["theme:bell_ringers", 8], ["gov:theocracy", 2]] },
  ],

  faiths: [
    { id: "ug_bells", n: "The Toll", d: "A priesthood of bell and lantern that guides the dead towards a gate it cannot find, and promises that the next peal will be the one.", tags: ["faith:ug_bells", "organised"], w: 1, mods: [["pious", 1.5], ["ancestor_bound", 1.5]], names: ["The Toll of $", "The Bell-House", "The Lantern Road"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Ghost-mist", color: "#9aa3ad", size: [2, 5], count: [1, 3], where: "any", d: "Low grey fog over old battlefields and dead cities, thick with the wandering dead." },
    { kind: "zone", n: "Necropolis", color: "#5c5866", size: [1, 2], count: [0, 2], where: "inner", d: "A city of the dead larger than any city of the living, still keeping its markets." },
  ],

  storylines: [
    { id: "ug_grandmother", n: "The Will of {person}", scale: "local", anchor: "town", w: 2, req: "restless_dead",
      stages: {
        start: { h: "The dead head of a family in {place} refuses to leave", b: "{person} died last winter, and still sits at the head of the family table in {place}. {person} will not hand the mill to a grandchild, {person2}, and the town court has agreed to hear the case.", wait: [2, 6], next: [{ to: "court_rules", w: 2 }, { to: "belled", w: 1, mods: [["pious", 2], ["theme:bell_ringers", 3]] }] },
        court_rules: { h: "A court in {place} rules for the dead", b: "The magistrates of {place} have found that a dead owner keeps their property. Every heir in {realm} is reading the judgment with dread.", wait: [3, 9], fx: { unrest: 10, flag: "dead_law" }, next: [{ to: "heirs_rise", w: 1, mods: [["poor", 2], ["egalitarian", 2]] }, { to: "law_of_dead", w: 2, mods: [["ancestor_bound", 2], ["hierarchical", 1.5]] }] },
        belled: { h: "Bell-ringers come for {person} of {place}", b: "The priests tolled {person} out of the chair and down the lane. The ghost went quietly. The next night it was back, and angry.", wait: [1, 4], fx: { unrest: 5 }, next: [{ to: "possession", w: 2 }, { to: "laid_rest", w: 1, mods: [["theme:ferry_coins", 4]] }] },
        heirs_rise: { h: "The living heirs of {place} take up torches", b: "{person2} and the disinherited young of {place} burned the court records and salted the old houses. The dead stand outside in the rain.", fx: { revolt: true, stability: -8 }, end: true },
        law_of_dead: { h: "{realm} recognises the rights of the dead", b: "The law of {realm} now holds that the dead may own, vote and inherit. The living young of {place} are leaving for the frontier.", fx: { stability: 4, growth: -0.1, unrest: 8 }, end: true },
        possession: { h: "{person} takes a grandchild's body", b: "{person2} woke speaking in the dead grandparent's voice. The mill belongs to the dead again, and no one in {place} dares to say whose hands are working it.", fx: { unrest: 12, flag: "possessed" }, end: true },
        laid_rest: { h: "An old coin quiets the dead of {place}", b: "A pedlar's bronze coin, laid on the eyes of {person}, put the ghost to rest at last. {person2} has the mill, and the coin has been stolen twice since.", fx: { stability: 3 }, end: true },
      } },
    { id: "ug_gate_march", n: "The Road to the Gate", scale: "realm", anchor: "realm", w: 1.5, req: ["restless_dead", { any: ["pious", "pilgrims", "unstable", "big", "learned"] }],
      stages: {
        start: { h: "{realm} sends an expedition to the gate of the dead", b: "With the living now fewer than the dead in some provinces, {ruler} has sent {person} and a company of bell-wardens to find the old gate and open it.", wait: [4, 10], next: [{ to: "finds_ferry", w: 1, mods: [["learned", 2]] }, { to: "finds_tower", w: 1, mods: [["autocracy", 1.5], ["theme:deathless_court", 4]] }, { to: "lost", w: 1 }] },
        finds_ferry: { h: "The expedition finds a dead rower", b: "{person} writes from a dry riverbed: the keeper of the dead lies there, speared, its boat empty. Someone killed death's ferryman, and the spears carry an old crown's mark.", wait: [3, 8], fx: { discovery: "arcana", flag: "ferryman" }, next: [{ to: "new_ferryman", w: 1, mods: [["pious", 2]] }, { to: "crown_blamed", w: 1 }] },
        finds_tower: { h: "The trail leads back to {capital}", b: "Every road to the gate ends in the old tower in {capital}. {person} has sent word that the realm's founder may never have died at all.", wait: [2, 6], fx: { unrest: 15 }, next: [{ to: "mask_broken", w: 1, mods: [["unstable", 2], ["theme:gate_seekers", 3]] }, { to: "silenced", w: 1, mods: [["autocracy", 2], ["harsh_law", 2]] }] },
        lost: { h: "No word from the expedition", b: "The last letter from {person} came from the cliffs, and spoke of a door and a great crowd. A year later, {person} was seen in the mist outside {capital}, dead and smiling.", fx: { stability: -4 }, end: true },
        new_ferryman: { h: "{person} takes up the broken oar", b: "Rather than come home, {person} took the dead rower's place. The ghosts of {realm} are thinning, slowly, and a lantern moves on the dry river every night.", fx: { stability: 10, prestige: 10, monument: { tier: 1, name: "The Rower's Shrine" } }, end: true },
        crown_blamed: { h: "{realm} learns who killed the ferryman", b: "The spears bear the mark of the realm's own first kings. Pamphlets in {capital} call the crown a house of murderers, and the dead are said to be listening.", fx: { stability: -15, revolt: true }, end: true },
        mask_broken: { h: "The tower in {capital} falls", b: "A mob of the living and the dead broke the tower and tore the grey mask from a withered thing in a chair. That night the mist rolled out to sea, and in the morning half the ghosts were gone.", fx: { ruler_dies: true, stability: -10, prestige: 10, pop: 1.02 }, end: true },
        silenced: { h: "{person} is executed for treason", b: "The crown hanged {person} at the city gate. The next morning the ghost was standing beneath the gallows, still talking.", fx: { unrest: 20, stability: -6 }, end: true },
      } },
    { id: "ug_dead_army", n: "The Grave Levy of {realm}", scale: "realm", anchor: "war", w: 1.2, req: ["restless_dead", { any: ["atwar", "martial", "arcane", "autocracy"] }],
      stages: {
        start: { h: "{realm} raises its war dead", b: "With the war going badly, {ruler} has let the necromancers of {realm} bind the fallen of old battles to the standards. Grey columns march towards {rival}.", wait: [2, 6], fx: { flag: "grave_levy" }, next: [{ to: "dead_win", w: 2 }, { to: "dead_turn", w: 1, mods: [["unstable", 2], ["chance:low", 1.5]] }] },
        dead_win: { h: "The dead of {realm} break the enemy line", b: "Spears do nothing to a man already dead. The army of {rival} broke and fled, and the fallen on both sides got up and joined the grey column.", wait: [3, 8], fx: { prestige: 12, relation: { rival: -30 } }, next: [{ to: "endless_war", w: 1 }, { to: "peace_dead", w: 1, mods: [["pious", 2], ["ruler:just", 2]] }] },
        dead_turn: { h: "The bound dead of {realm} turn on their masters", b: "The binding failed at dawn. The dead legion of {realm} remembered who had sent them to die the first time, and marched on {capital}.", fx: { stability: -20, revolt: true, pop: 0.9 }, end: true },
        endless_war: { h: "The war that cannot end", b: "Every battle raises more than it kills. The fields between {realm} and {rival} are now a country of the marching dead, and no one can call them home.", fx: { war: "rival", unrest: 15 }, end: true },
        peace_dead: { h: "{ruler} releases the grave levy", b: "Bell-wardens walked the lines for a month, tolling the dead loose. The war is over; the fields where they stood are still cold.", fx: { peace: true, stability: 6 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "an old net-maker of {place}, to {investigator}", text: "An old net-maker of {place}, answering {investigator} for the grave census, {year}: 'My grandmother said that once the dead went down to the water and were rowed away, and you only saw them again at the autumn feast. Now they don't go anywhere. Now they just stay. I have 6 of them in this house. Put them down in your book, they like being counted.'" },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: false, who: "{official}, chamberlain of the Veiled Tower", text: "Proclamation of the Veiled Tower, read in every market of {realm} by {official}, chamberlain, {year}: 'The present increase in apparitions is a natural fluctuation, recorded in 3 earlier centuries. It will subside, as it always has, with proper tolling and civic order. Householders are reminded that the salt tax rises by a penny a pound at midsummer.'" },
    { depth: "lore", about: "truth", source: "archive", bias: "true", reliable: true, points: "cast:investigator", who: "parish clerk of {place}", text: "Parish rolls of {place}, {year}, in the clerk's hand: 'Births, 212. Burials, 304. Departures of the dead, none.' The last column has been empty for so long that the clerk has stopped ruling it. A note pinned to the page says a copy goes each year to the census registrar, {investigator}, at {lead}, and that nobody has ever written back." },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a wine-buyer passing through {place}", text: "A wine-buyer's letter from {place}, {year}: 'In the old capital there are more chairs in the taverns than drinkers who can lift a cup. The landlord of the Blue Gate keeps a bell on the bar and rings it when the cold gets too thick to see the tap. Every regular is counted twice on the tax roll: once living, once not. Ale is 4 pennies.'" },

    { depth: "core", about: "truth:dead_ferryman", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, bell-ringer of the Toll", text: "Note by {believer}, bell-ringer of the Toll, in the margin of the oldest hymn-book at {place}, {year}: the hymn reads 'Ring, and the Rower hears; ring, and the oar dips; ring, and the water takes them home.' {believer} writes: 'I have rung it 30 years. Nobody in the Toll can tell me who the Rower was, or why the old books show an oar on the bell.'" },
    { depth: "core", about: "truth:dead_ferryman", source: "ruin", bias: "true", reliable: true, plain: true, points: "site:beached_ferry", who: "the last priest of a riverbank shrine", text: "Cut into a riverbank shrine near the dry ford at {lead}, under a carving of a boat, by the shrine's last priest: 'The Rower took one coin from each of the dead and asked nothing more. The river-king wanted the ford and the fares. His soldiers waited at the crossing with 7 spears. I saw the Rower fall. Nobody rows the dead now, and they cannot find the way.'" },
    { depth: "core", about: "truth:dead_ferryman", source: "oral", bias: "garbled", reliable: "partial", points: "sub:keeper_relics", who: "boatmen of {place}", text: "A boatmen's song from {place}, taken down by {investigator} in {year}, with the singer's comment: 'There was a boatman older than the river, and the king's men killed him for the fare.' The singer added: 'That's the whole song. Nobody knows more. If you want the boatman's coins, there's a pedlar sells them at {lead}, 2 shillings each, and they work.'" },
    { depth: "core", about: "truth:dead_ferryman", source: "person", bias: "true", reliable: "partial", cost: true, who: "the ghost of Ysolt Marr, to {investigator}", text: "Testimony of a ghost, taken down by {investigator} at {place}, {year}: 'My name is Ysolt Marr. I drowned at the mill-race at 19. I went down to the water like they told us. There was no one at the oars. I waited till the boat went grey with frost, and then I came home. My mother has been dead 40 years now and she is waiting in the kitchen. Wouldn't you go home?'" },
    { depth: "core", about: "truth:dead_ferryman", source: "library", bias: "official", reliable: false, who: "Commentary on the Hymns of the Toll", text: "From the official Commentary on the Hymns of the Toll, chapter 12, approved by the crown in {year}: 'The Rower of the old hymns is a poetic figure for the passage of time. There was never any ferry. The faithful are cautioned against looking for one, against buying so-called rower coins, and against digging in dry riverbeds, which are crown property.'" },

    { depth: "core", about: "truth:full_house", source: "heretic", bias: "heretic", reliable: true, plain: true, who: "{survivor}, gate-seeker", text: "Tract of {survivor}, the only gate-seeker of a company of 20 to come back alive from the cliff, {year}: 'I stood at the black pillars for 3 nights and talked to the dead in the queue. They all told the same story. The house of the dead had only so many rooms, and we filled them. Every child who dies now shoves a stranger out of bed and into your kitchen.'" },
    { depth: "core", about: "truth:full_house", source: "person", bias: "true", reliable: "partial", points: "site:packed_crypt", who: "a scholar's notes on a ghost", text: "Notes of a scholar on a ghost found in the crypt at {lead}, {year}: 'Woman, about 30, in bronze-age dress, with a copper pin through the cloak. Speaks no living tongue; by signs and 40 words of the old grave-script, she says it was crowded. So crowded she could not breathe. Then something pushed, and she was here. She keeps pointing down.'" },
    { depth: "core", about: "truth:full_house", source: "ruin", bias: "true", reliable: "partial", points: "ruin", who: "{investigator}, census registrar", text: "Report of {investigator} on a painted tomb ceiling near {place}, {year}: 'A vast hall filled shoulder to shoulder with the dead, perhaps 600 figures. At the edges, tiny figures fall out of the hall into a world of trees and houses. The painter added fresh figures in a later paint, more each time. A second tomb by the same painter is at {lead}.'" },
    { depth: "core", about: "truth:full_house", source: "temple", bias: "official", reliable: false, who: "the Toll's catechism", text: "From the catechism of the Toll, question 9, as taught to children in {place}, {year}: 'Q. Are the halls of the dead without end? A. They are without end, and the faithful dead rest in them forever. Those who linger here are the wicked, who are refused entry. Q. What of my uncle, who lingers? A. Ask your priest.'" },
    { depth: "core", about: "truth:full_house", source: "person", bias: "true", reliable: "partial", cost: true, who: "a weaver of {place}", text: "Letter from a weaver of {place} to the bell-house, {year}: 'My boy Pell died of the cough at 5. The next night a man in bronze armour was sitting in Pell's bed, weeping, in no language we know. The priests say Pell went in and the soldier came out. I want my son's bed back. I would settle for knowing where my son went.'" },

    { depth: "core", about: "truth:sealed_gate", source: "archive", bias: "redacted", reliable: "partial", points: "site:broken_gate", who: "a builder's contract of the founding year", text: "Builder's contract from the founding year of {realm}, found in the archive in {year}, partly burned: '...4,000 cartloads of black stone, to be laid at the cliff at {lead} by the king's order, between the pillars, and the mason's mark of every man to be destroyed after... [12 lines burned] ...the masons to be paid in full at the tower, and not before.'" },
    { depth: "core", about: "truth:sealed_gate", source: "heretic", bias: "exaggerated", reliable: "partial", cost: true, points: "site:veiled_tower", who: "Dunny Carr, mason", text: "Chalked on the wall of the tower at {lead} in {year}, and signed 'Dunny Carr, mason': 'HE NEVER DIED. HE SHUT THE DOOR SO HE WOULD NEVER HAVE TO WALK THROUGH IT. MY GUILD CUT THE STONE AND 40 OF US WERE HANGED FOR IT. EVERY GHOST IS HIS.' Under it, a constable's note: Carr taken into the tower for questioning, 3rd of the month. Not seen since." },
    { depth: "core", about: "truth:sealed_gate", source: "person", bias: "true", reliable: true, plain: true, points: "cast:official", who: "a palace physician, last letter", text: "Last letter of a palace physician to a sister, {year}: 'I have tended him for 30 years. The Founder has no pulse. He does not eat. He is the first king; he walled up the gate of the dead so he would never have to go through it. Every morning he asks whether the door still holds. My notebooks are with the chamberlain {official} at {lead}. Burn this.'" },
    { depth: "core", about: "truth:sealed_gate", source: "library", bias: "propaganda", reliable: false, who: "Annals of the Crown", text: "From the Annals of the Crown of {realm}, printed in {year}: 'The Founder departed this life in the year of the great flood, aged 71, and was entombed with full honours. The veil is worn today by the Founder's descendants out of reverence. The tower purchases lamp-oil for the perpetual flame, at 3 barrels a month.'" },

    { depth: "sub", about: "sub:ancestor_veto", source: "archive", bias: "official", reliable: true, points: "archive", who: "council minutes of {place}", text: "Minutes of the council of {place}, {year}: 'Motion to repair the north bridge. For: 4 living members. Against: 31 deceased members. The motion fails, as in each of the last 90 years. Councillor Abbet (deceased) asks that the minutes record the bridge was perfectly sound in his day.' The full run of minutes is kept at {lead}." },
    { depth: "sub", about: "sub:bone_legions", source: "person", bias: "true", reliable: "partial", who: "a sergeant of the grave levy, diary", text: "Diary of a sergeant of {realm}, campaign of {year}: 'We buried Hab Tiller on the field at the ford, with his pipe and 3 coins. On the third day he was back in the line, in our own grey column, and he didn't know me. He marched 20 miles without a rest and never once complained. The captain says he is the best soldier in the company now.'" },
    { depth: "sub", about: "sub:bell_ringers", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, handbook for ringers", text: "From the ringers' handbook compiled by {believer}, {year} edition: 'Toll 7 for the newly dead, 3 for the old, and 1, long, for those who will not go. Then walk away. Never look back to see if they followed.' A note on the flyleaf: 'Of the 12 great bells cast for the Toll, 5 are cracked. The foundry is gone. Do not ring the cracked ones in frost.'" },
    { depth: "sub", about: "sub:possession_plague", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a travelling apothecary", text: "Notebook of a travelling apothecary, poor quarter of {place}, {year}: 'They sleep with iron nails in their mouths here; I sold 300. A woman told me her husband went to bed and someone else woke up, and that someone wanted his breakfast, his tools and his wife. The new man is a better carpenter. She has not decided whether to complain.'" },
    { depth: "sub", about: "sub:deathless_court", source: "oral", bias: "garbled", reliable: "partial", who: "a washerwoman of {place}", text: "A washerwoman of {place}, talking at the river in {year}: 'My mother saw the Founder's procession when she was a girl, and I saw it at 10, and my daughter saw it last spring. Same veil, same slow walk, same 3 rings on the left hand. The coins say it's someone else now. The rings don't.'" },
    { depth: "sub", about: "sub:salt_towns", source: "traveller", bias: "true", reliable: true, who: "a salt merchant's factor", text: "Report of a salt merchant's factor at {place}, {year}: 'They pay the gate toll in salt here, a pound a head, and the walls are white with it. Salt fetches more than silver by weight. Outside the walls, in the evening mist, I counted 412 faces. The town has 380 people. My employer wishes to buy the road.'" },

    { depth: "site", about: "site:quiet_cemetery", source: "oral", bias: "true", reliable: "partial", who: "the sexton of {place}", text: "The sexton of the old yard at {place}, to a family haggling over a plot, {year}: 'Bury them face down here and they don't come back. Nobody knows why. 11 years' wait, 20 pounds of salt, no exceptions. My father kept this yard before me. He used to say they're going somewhere. He said it like he envied them.'" },
    { depth: "site", about: "site:broken_gate", source: "traveller", bias: "exaggerated", reliable: "partial", who: "{survivor}, gate-seeker", text: "{survivor}, the gate-seeker, describing the cliff to a crowd in {place}, {year}: 'We were 20 when we reached the black pillars at dusk. The mist parted and I saw them, row on row, down the cliff and out over the water, all facing the same way. In the morning I was 1. I have the company's names written on my arm. I will read them to anyone who asks.'" },
  ],
};
