// Codex prose fragments: short reusable sentences, picked by tags and stitched into sections of a
// realm's, culture's or faith's codex entry.
// Format: a fragment is a plain string, or { t: "text", req: <condition>, w: <weight> }.
//   req uses the core/rules.js condition format: "tag", "!tag", [all of], { any: [...] }, { not: cond }.
//   Slots in {braces} are filled by the app: {realm} {short} {ruler} {title} {capital} {people} {faith}
//   {deity} {land} {good} {good2} {rival} {ally} {founded} {era} {river} {range} {sea} {currency}
//   {fallen} {holy} {festival}, and the power words {power} {user} {users} {node} (magic/mage/mages/the ley
//   lines by default, or the active power premise's). A fragment whose slot has no value is dropped, so only use
//   {rival}/{ally}/{river}/{range}/{sea}/{fallen} in fragments that carry a req.
// Rules: 1-2 sentences, 12-40 words, no proper names except through slots, vary the openings.

/* =========================================================================================
   REALMS
   ========================================================================================= */
export const REALM_SECTIONS = {
  overview: [
    "{realm} is a land of long memories and short tempers, ruled from {capital} by {ruler}.",
    "Few realms of {land} are spoken of as often, or as warily, as {realm}.",
    "From the walls of {capital}, {ruler} governs a realm that outsiders underestimate and rarely understand.",
    "Travellers describe {realm} as a patchwork: proud towns, stubborn villages and a court that tries to hold them all together.",
    "The {people} call their country simply {short}, and speak the name with a mixture of pride and weary affection.",
    "Ask ten travellers about {realm} and you will hear ten stories, most of them about {good} and the people who sell it.",
    { t: "{realm} is a small country with a large opinion of itself, and it has survived by being too awkward to swallow.", req: { any: ["realm:tiny", "realm:small"] } },
    { t: "Tiny as it is, {realm} punches well above its size, mostly through wit, walls and well-placed friends.", req: "realm:tiny" },
    { t: "{realm} sprawls across so much of {land} that its provinces have little in common but taxes and a distant crown.", req: "realm:vast" },
    { t: "Vast and old, {realm} changes slowly; a new law can take a generation to reach the far provinces.", req: "realm:vast" },
    { t: "{realm} is one of the great powers of {land}, and its neighbours arrange their lives around its moods.", req: { any: ["realm:large", "realm:vast"] } },
    { t: "Sea-salt and tar hang over every harbour of {realm}, a realm that faces the water and turns its back on the hills.", req: "coastal" },
    { t: "An island realm, {realm} has always trusted its sea more than any ally.", req: "island" },
    { t: "{realm} is a realm of grass and sky, where towns are few and horizons endless.", req: "steppe" },
    { t: "Sand, wells and sun define {realm}; everything else is a luxury carried in on camel-back.", req: "desert" },
    { t: "{realm} lies under the eaves of deep forest, and its roads are narrow tunnels of green.", req: { any: ["forest", "jungle"] } },
    { t: "Built on terraces and passes, {realm} is a mountain realm whose valleys each think themselves a little kingdom.", req: "mountain" },
    { t: "Everything in {realm} flows from the {river}: its grain, its trade, its floods and its politics.", req: "river" },
    { t: "Long winters shape {realm}; its people are patient, thrifty and suspicious of anyone who complains about the cold.", req: "cold" },
    { t: "Reed-beds, causeways and fog make {realm} hard to conquer and harder to map.", req: "marsh" },
    { t: "A titan walks the land near {realm}, and every town keeps a lookout posted to track where it goes.", req: "near:titan" },
    { t: "The rift glows on the horizon of {realm} every night, and travellers say the people who live in its light look and act a little differently.", req: "near:rift" },
    { t: "Beasts prowl the edges of {realm}, and its people have learned to fight, fear or tame them.", req: "near:beasts" },
    { t: "Old ruins lie under every field of {realm}, and ploughmen turn up coins older than any living dynasty.", req: "near:ruins" },
    { t: "{realm} sits on the edge of the known world, a march of watchtowers facing the wild.", req: "frontier" },
    { t: "Just now {realm} is at war, and every road to {capital} is crowded with carts, recruits and rumours.", req: "atwar" },
    { t: "At peace for now, {realm} is busy with the quieter wars of trade, marriage and gossip.", req: "peace" },
    { t: "Priests outnumber soldiers in {capital}, and {realm} measures its greatness in temples raised to {faith}.", req: { any: ["pious", "gov:theocracy"] } },
    { t: "{power} is ordinary in {realm}: lamps that never gutter, wells that never fail, and {users} who never let you forget it.", req: { any: ["magic:high", "arcane"] } },
    { t: "Counting-houses line the streets of {capital}, and {realm} is said to run on {good} and credit.", req: { any: ["mercantile", "gov:merchant"] } },
    { t: "Wandering camps rather than towns make up most of {realm}, and its capital moves when the herds do.", req: "nomadic" },
  ],

  government: [
    "Power in {realm} flows from {capital}, though it tends to thin out the further one rides from the court.",
    "The court of {ruler} is crowded with petitioners, favourites and the quiet clerks who actually run things.",
    "Everyone agrees who rules {realm}; far fewer agree on who governs it.",
    // feudal
    { t: "Great lords hold their lands in fief from {ruler}, owing swords in war and grudging counsel in peace.", req: "gov:feudal" },
    { t: "Every duke of {realm} keeps a court that apes the royal one, and some of them are grander.", req: "gov:feudal" },
    { t: "Oaths bind the realm together: knight to baron, baron to count, count to crown, each promise renewed at every coronation.", req: "gov:feudal" },
    // absolute
    { t: "The word of {ruler} is law, and ministers rise or vanish on a single frown from the throne.", req: "gov:absolute" },
    { t: "An army of chamberlains stands between {ruler} and the world; to reach the throne one must bribe a dozen doors.", req: "gov:absolute" },
    { t: "The old nobility was broken long ago, and now lives in gilded idleness at court where the crown can watch it.", req: "gov:absolute" },
    // elective
    { t: "When a monarch dies, the great houses of {realm} gather to elect the next, and the bribes flow like wine.", req: "gov:elective" },
    { t: "{ruler} was chosen by a diet of electors and must bargain with them for every tax and every war.", req: "gov:elective" },
    { t: "The electors of {realm} guard their privilege jealously, and no crown here has ever passed quietly from parent to child.", req: "gov:elective" },
    // empire
    { t: "Governors appointed from {capital} run the provinces, rotated every few years so none grows roots.", req: "gov:empire" },
    { t: "Imperial scribes keep tax rolls on every village, and a census clerk is feared more than any bandit.", req: "gov:empire" },
    { t: "The {title} sits at the peak of a pyramid of ministries, examinations and seals that no single person fully understands.", req: "gov:empire" },
    // theocracy
    { t: "Priests of {faith} govern {realm}; the temple and the treasury share the same doors.", req: "gov:theocracy" },
    { t: "{ruler} speaks for {deity}, and a law that displeases the priesthood is simply declared a heresy.", req: "gov:theocracy" },
    { t: "Every village has a shrine-warden who also collects taxes, settles disputes and reports to the synod.", req: "gov:theocracy" },
    // merchant
    { t: "A council of the richest trading houses rules {realm}, and a seat on it costs more than most castles.", req: "gov:merchant" },
    { t: "The {title} presides over the council but may not trade, marry abroad or leave {capital} without permission.", req: "gov:merchant" },
    { t: "Policy in {realm} is written in ledgers: a war is declared only when someone has shown it will pay.", req: "gov:merchant" },
    // noble republic
    { t: "An assembly of landholders rules {realm}, and any single member may block a law by shouting a word.", req: "gov:noble_republic" },
    { t: "The {title} holds office at the assembly's pleasure and is watched by a dozen jealous families.", req: "gov:noble_republic" },
    { t: "Every noble in {realm}, however poor, is equal in the assembly, and many own nothing but a sword and a vote.", req: "gov:noble_republic" },
    // city state
    { t: "The citizens of {capital} elect their magistrates each spring, and the losers sulk until the next vote.", req: "gov:city_state" },
    { t: "{realm} is really one city and its fields; the council meets in a hall within earshot of the fish market.", req: "gov:city_state" },
    { t: "Guild-masters, old families and popular tribunes share power in {capital} in an arrangement nobody would design on purpose.", req: "gov:city_state" },
    // tribal
    { t: "Clan elders meet in a great moot each year, and the {title} is first among equals, not a master.", req: "gov:tribal" },
    { t: "No chief of {realm} can command a clan against its will; they persuade, gift and marry instead.", req: "gov:tribal" },
    { t: "Laws are remembered, not written, and recited by the elders whenever the clans gather.", req: "gov:tribal" },
    // khaganate
    { t: "The {title} rules from a great tent, and those who fail to ride when summoned lose their pastures.", req: "gov:khaganate" },
    { t: "Power in {realm} is counted in horsemen; each noyan commands a thousand riders and answers to {ruler} alone.", req: "gov:khaganate" },
    { t: "Conquered cities keep their own governors, as long as the tribute arrives on time and the gates stay open.", req: "gov:khaganate" },
    // magocracy
    { t: "Only the gifted may hold office in {realm}; the mundane majority pays taxes and keeps quiet.", req: "gov:magocracy" },
    { t: "The {title} is chosen by trial of power, and the losers rarely remain in {capital} long afterward.", req: "gov:magocracy" },
    { t: "A conclave of {users} meets in a tower above {capital}, debating laws in a tongue ordinary folk cannot follow.", req: "gov:magocracy" },
    // stratocracy
    { t: "Generals govern the provinces of {realm}, and every official wears a uniform and a rank.", req: "gov:stratocracy" },
    { t: "The {title} commands from a war-room rather than a throne room, and civil law is written as general orders.", req: "gov:stratocracy" },
    { t: "In {realm} a citizen is a veteran; those who never served cannot vote, own land or hold office.", req: "gov:stratocracy" },
    // commune
    { t: "Village assemblies send delegates to {capital}, where the {title} chairs debates that can last for days.", req: "gov:commune" },
    { t: "There are no lords in {realm}; the land belongs to those who work it, and they never let anyone forget it.", req: "gov:commune" },
    { t: "Offices in {realm} rotate by lot, and a cobbler may find himself treasurer for a year.", req: "gov:commune" },
    // beast
    { t: "Whoever commands the greatest beast commands {realm}, and {ruler} rides a monster that no rival has matched.", req: "gov:beast" },
    { t: "Chieftains of {realm} are ranked by the beasts they have tamed, and a lost mount can mean a lost seat.", req: "gov:beast" },
    { t: "The throne of {realm} is a nest, a pen and a court at once, and petitioners keep one eye on the teeth.", req: "gov:beast" },
    // misc
    { t: "Spies of the crown sit in every tavern, and even {ruler} is said to be watched by someone.", req: "spy_network" },
    { t: "{users} of the arcane council advise {ruler}, and some say they do more than advise.", req: "arcane_council" },
    { t: "Guild charters set the rules in every town, and the crown taxes the guilds rather than the people.", req: "guilds" },
  ],

  law: [
    "Justice in {realm} is slow, expensive and occasionally fair, and most folk would rather settle a quarrel privately.",
    "Most quarrels in {realm} are settled by village elders before any magistrate hears of them.",
    "The law codes of {realm} are old and much amended, and lawyers make fortunes finding the contradictions.",
    "Thieves in {realm} fear the pillory more than the gallows, for shame lasts longer than a rope.",
    "Local custom often trumps royal law, and a judge must know both to keep his post.",
    { t: "Punishments are public and severe: branding, flogging, and heads above the gates of {capital}.", req: "harsh_law" },
    { t: "The law of {realm} forgives nothing; even debtors are sold into labour until the last coin is repaid.", req: "harsh_law" },
    { t: "Nobles and commoners face different courts, and a lord can only be tried by his peers.", req: "hierarchical" },
    { t: "Anyone may speak at the village moot, and a judgement stands only if most agree it is fair.", req: "egalitarian" },
    { t: "Temple courts judge crimes against {faith}, and their sentences cannot be appealed to any earthly ruler.", req: { any: ["gov:theocracy", "pious", "zealous"] } },
    { t: "Blood feuds are settled by wergild, a price in {currency} for every life, limb and insult.", req: { any: ["tribal", "martial"] } },
    { t: "Trial by combat is still lawful, and many a dispute over land ends in a ring of spectators.", req: { any: ["warrior_code", "martial"] } },
    { t: "Contracts are sacred in {realm}; a broken bargain is punished more harshly than a broken head.", req: "mercantile" },
    { t: "Guests are protected by law; harming one under your roof is treated as murder.", req: "hospitable" },
    { t: "Foreigners must carry papers at all times, and those found without them are expelled or worse.", req: { any: ["isolation", "insular"] } },
    { t: "Military tribunals handle every crime, and a sentence is carried out before the drums stop.", req: "gov:stratocracy" },
    { t: "Truth-workings are used in the high courts, though the rich hire {users} to cloud them.", req: { any: ["arcane", "gov:magocracy", "magic:high"] } },
    { t: "Oaths are sworn over the bones of ancestors, and perjury curses a family for seven generations.", req: "ancestor_bound" },
    { t: "Travellers on the roads are under the crown's protection, and robbing them is a hanging offence.", req: { any: ["open_roads", "great_roads"] } },
    { t: "Imperial magistrates follow a written code in hundreds of volumes, and every verdict must cite chapter and line.", req: "gov:empire" },
    { t: "Harming a tamed beast is counted as harming its rider, and the penalty is the same.", req: "beast_tamers" },
  ],

  succession: [
    "Every succession in {realm} has been disputed by someone; the peaceful ones are merely the short disputes.",
    "When a ruler of {realm} falls ill, the court holds its breath and the pretenders polish their claims.",
    { t: "The crown passes to the eldest child, and younger siblings are sent to temples, armies or distant marriages.", req: ["monarchy", "!gov:elective"] },
    { t: "An heir must be acclaimed by the great lords before being crowned, and the acclamation is always negotiated.", req: "gov:feudal" },
    { t: "The ruler names an heir from among the royal kin, and the choice is kept secret until the funeral.", req: "gov:absolute" },
    { t: "Rival heirs are traditionally confined to a palace wing, and not all of them leave it alive.", req: "autocracy", w: 0.6 },
    { t: "The electors meet behind locked doors and are fed less each day until they agree.", req: "gov:elective" },
    { t: "Any adult of noble blood may stand for the crown, though only the rich can afford to.", req: "gov:elective" },
    { t: "The imperial heir is adopted, not born: the {title} chooses the most capable official as a son or daughter.", req: "gov:empire" },
    { t: "The dynasty that founded {realm} still rules it, and its family tree is painted on the throne-room wall.", req: { any: ["origin:old_dynasty", "dynastic"] } },
    { t: "A new leader is chosen when the old one dies, by signs read in the temple and approved by the synod.", req: "gov:theocracy" },
    { t: "Councillors serve fixed terms, and the chief magistrate is elected by a lottery of balls and urns.", req: "republic" },
    { t: "The {title} is elected for life by the council, which usually chooses someone old enough not to last.", req: "gov:merchant" },
    { t: "At a chief's death the clans gather, and the one who wins the most oaths becomes the next {title}.", req: "tribal" },
    { t: "Each son of the {title} rides for the throne, and the realm holds its breath until one of them wins.", req: "gov:khaganate" },
    { t: "The next archmage is decided by a duel of power before the assembled conclave.", req: "gov:magocracy" },
    { t: "Command passes to the most senior general, unless the army decides otherwise.", req: "gov:stratocracy" },
    { t: "Whoever tames the great beast after the ruler's death takes the throne, and many die trying.", req: "gov:beast" },
    { t: "A child of the royal line must survive a night alone in the wilds before being named heir.", req: ["monarchy", { any: ["martial", "warrior_code"] }], w: 0.5 },
    { t: "The heir must be recognised by the ancestors, a ritual performed at the tombs with incense and silence.", req: "ancestor_bound" },
    { t: "Seers watch the birth of every royal child, and the omens can disinherit an eldest son.", req: "seers" },
    { t: "Offices are never inherited; the assembly elects its speaker each year and forbids anyone to serve twice.", req: "gov:commune" },
  ],

  military: [
    "The army of {realm} is larger on paper than in the field, as armies generally are.",
    "Soldiers of {realm} march under the banners of {capital}, and each regiment keeps a proud and exaggerated history.",
    "Veterans in {realm} are honoured in speeches and forgotten in budgets.",
    { t: "In time of war, every village sends its young men with spears, and the harvest suffers for it.", req: "levies" },
    { t: "Peasant levies make up most of the host, armed with bills, bows and whatever their lords can spare.", req: "levies" },
    { t: "The standing army drills year-round in {capital}, uniformed, paid and fiercely loyal to its paymasters.", req: "standing_army" },
    { t: "Professional regiments garrison every province, and their officers are trained in a war college near {capital}.", req: "standing_army" },
    { t: "Wars are fought with hired companies, and the treasury is the true general of {realm}.", req: "mercenaries" },
    { t: "Mercenary captains are wooed with {currency} and watched closely, for they have changed sides before.", req: "mercenaries" },
    { t: "The fleet is the pride of {realm}; its admirals rank above generals and its ships are named for saints and victories.", req: "navy" },
    { t: "Warships crowd the harbour of {capital}, and every boy in the port dreams of a berth on one.", req: "navy" },
    { t: "Nobles must prove themselves in battle before they may inherit, and cowardice is a stain no fortune can wash out.", req: "warrior_code" },
    { t: "Tamed monsters march in the ranks of {realm}, and their handlers are the most feared soldiers on {land}.", req: "beast_cavalry" },
    { t: "War-mages ride with every army, and a battle against {realm} is fought against fire as well as steel.", req: "arcane_council" },
    { t: "A chain of forts guards every border, each within signal-fire range of the next.", req: "frontier_forts" },
    { t: "Paved military roads let the legions of {realm} march across the realm in days rather than weeks.", req: "great_roads" },
    { t: "The horsemen of {realm} are the terror of {land}, able to ride all day and shoot from the saddle.", req: "horse_lords" },
    { t: "Every child of {realm} learns the spear, and the whole people can become an army within a week.", req: "martial" },
    { t: "Mountain holds and narrow passes make {realm} easy to defend and almost impossible to invade.", req: "mountain_folk" },
    { t: "Archers and scouts of {realm} fight from the trees, and no army has marched through its forests unbled.", req: "forest_folk" },
    { t: "The {people} fight at sea as naturally as on land, boarding enemy ships with axe and hook.", req: "seafaring" },
    { t: "Warrior-monks of {faith} fight in the front rank, singing hymns as they kill.", req: "militant" },
    { t: "The whole realm is on a war footing: forges ring through the night and the roads are thick with supply wagons.", req: "atwar" },
    { t: "Recruiting sergeants tour every market in {realm}, and each week brings new lists of the fallen from the front against {rival}.", req: "atwar" },
    { t: "The war against {rival} has emptied the villages of young men and filled the temples with widows.", req: "atwar" },
    { t: "Garrisons in {realm} have grown lazy in peacetime, and their officers spend more time at cards than drill.", req: "peace" },
    { t: "The army of {realm} rides as one great horde, divided into tens, hundreds and thousands.", req: "gov:khaganate" },
    { t: "Every official is an officer and every citizen a reservist; {realm} is an army that happens to have a country.", req: "gov:stratocracy" },
    { t: "Hunters of {realm} are trained to bring down titanic beasts, and their harpoons and siege-bows are a marvel.", req: { any: ["near:titan", "origin:titan_slayers"] } },
    { t: "The soldiers of {realm} fight from causeways and flat-bottomed boats, and invaders drown in its bogs.", req: "marsh" },
    { t: "Victory is celebrated with trophies hung in the temples, and defeat with long, grim fasts.", req: "pious" },
  ],

  economy: [
    "{good} is the lifeblood of {realm}, and {good2} follows close behind.",
    "Merchants of {realm} deal chiefly in {good}, which is carried to markets across {land}.",
    "The coin of {realm} is reckoned in {currency}, and forgers are boiled in oil, or at least threatened with it.",
    "Most folk of {realm} farm, and the rhythm of sowing and harvest rules the calendar more than any king.",
    "Taxes fall heaviest on the peasants and lightest on those who write the tax laws.",
    "Tolls on bridges and gates bring more {currency} into the treasury than any mine.",
    "Market days fill the towns of {realm} with {good2}, livestock, gossip and pickpockets.",
    { t: "Harbours of {realm} bustle with ships loading {good} and unloading goods from every coast of {sea}.", req: "has:port" },
    { t: "Fishing fleets feed the realm, and salted fish is traded inland for grain and timber.", req: "coastal" },
    { t: "River barges carry {good} down the {river}, and every bend has a toll-house.", req: "river" },
    { t: "The {river} floods each year and leaves black silt behind, making the valley the breadbasket of {land}.", req: "river" },
    { t: "Wealth in {realm} is counted in horses and herds, and silver is merely what foreigners want.", req: { any: ["horse_lords", "nomadic"] } },
    { t: "Caravans cross the dunes carrying {good} and salt, guided by stars and the knowledge of every well.", req: "desert" },
    { t: "Timber, furs and honey come out of the forests, and woodcutters pay a tithe to the spirits before each felling.", req: "forest" },
    { t: "Mines honeycomb the {range}, yielding iron, silver and the odd gem that starts a family feud.", req: "mountain" },
    { t: "Guilds control every craft, set every price and train every apprentice; outsiders need a licence even to sell bread.", req: "guilds" },
    { t: "Low tolls and open markets draw traders from all of {land}, and {currency} of every mint jingle in the stalls.", req: "free_trade" },
    { t: "Trading houses of {realm} lend to kings and bishops, and they know how to call in a debt.", req: "mercantile" },
    { t: "The workshops of {realm} produce {good2} of such quality that a mark of origin doubles its price.", req: "artisans" },
    { t: "Paved roads and post-houses carry trade across the realm, and road-tolls fund half the treasury.", req: "great_roads" },
    { t: "Foreign goods are taxed ruinously, and smuggling is the most profitable trade in {realm}.", req: "isolation" },
    { t: "Temples own a third of the land and lend grain to farmers at interest that no one dares call usury.", req: { any: ["gov:theocracy", "pious"] } },
    { t: "Tribute from conquered peoples fills the treasury, and the {title} redistributes it to keep the clans loyal.", req: { any: ["gov:khaganate", "origin:horde"] } },
    { t: "Relics dug from the ruins are sold to scholars and collectors, and the treasury takes its cut.", req: "near:ruins" },
    { t: "Titan-shed scales, bone and hair are harvested in its wake and fetch fortunes in foreign markets.", req: "near:titan" },
    { t: "Enchanted goods are an everyday export: lamps, locks and charms bound with small, reliable workings of {power}.", req: { any: ["arcane", "magic:high"] } },
    { t: "War has driven up the price of bread and iron, and profiteers grow fat while the poor go hungry.", req: "atwar" },
    { t: "Pilgrims bring more {currency} to {realm} than any trade, and inns crowd every road to {holy}.", req: "pilgrims" },
    { t: "The terraced fields of {realm} grow rice, tea and fruit, watered by channels older than any dynasty.", req: { any: ["hot", "warm", "jungle"] } },
    { t: "Short summers mean every harvest is a race, and famine years are remembered by name.", req: "cold" },
    { t: "Beast-handlers sell tamed monsters to foreign armies, and a trained war-beast costs more than a castle.", req: "beast_tamers" },
  ],

  daily_life: [
    "Ordinary folk of {realm} rise with the sun, work until dusk and complain about the tax collector in between.",
    "The village well is the heart of every hamlet in {realm}, where news, courtship and quarrels begin.",
    "Children of {realm} grow up on stories of old heroes and warnings about the dark.",
    "Taverns are the parliaments of the poor in {realm}, and nothing is secret for long after the second jug.",
    "Most people in {realm} will never travel more than a day's walk from where they were born.",
    "Weddings in {realm} last three days and bankrupt the bride's family for three years.",
    "Life in {capital} is crowded, loud and exciting; life in the villages is none of those things, and the villagers prefer it.",
    "Every household keeps a small shrine by the hearth, tended by the eldest woman of the family.",
    { t: "Streets of {capital} are packed from dawn to midnight with hawkers, beggars, students and sharp-eyed thieves.", req: { any: ["urbane", "has:city"] } },
    { t: "Families live on boats and stilt-houses along the waterfront, and children swim before they walk.", req: { any: ["seafaring", "river_folk"] } },
    { t: "Life follows the herds: camps are struck at dawn, and a family's home fits on the back of two horses.", req: "nomadic" },
    { t: "In the high valleys, whole villages share one great hall through the winter, living and sleeping by the fire.", req: "mountain_folk" },
    { t: "Siesta empties the streets at noon, and the towns come alive only after sunset, under lantern light.", req: "hot" },
    { t: "Winter shuts every road for months, and families pass the dark season with carving, brewing and long stories.", req: "cold" },
    { t: "Houses are built on stilts above the mud, and people move between them by punt and plank.", req: "marsh" },
    { t: "Peasants of {realm} owe their lord three days of labour a week and their priest a tenth of everything.", req: "gov:feudal" },
    { t: "Everyone in {realm} knows their rank to a hair, and bows are measured in degrees.", req: "hierarchical" },
    { t: "Farmers and lords sit at the same assemblies here, and nobody bows to anybody without a good reason.", req: "egalitarian" },
    { t: "Temple bells mark the hours, and the whole realm stops work for prayer three times a day.", req: "pious" },
    { t: "Every village has a {user} who mends pots, blesses cattle and charges too much for both.", req: { any: ["arcane", "magic:high"] } },
    { t: "People plan their days around the titan's movements, and a distant tremor sends everyone to the cellars.", req: "near:titan" },
    { t: "Doors are barred at dusk and charms hung at every window, for the wilds come close at night.", req: { any: ["near:beasts", "frontier"] } },
    { t: "Lights from the rift keep people awake, and children often wake up describing the same strange dream.", req: "near:rift" },
    { t: "Families visit the tombs each week to report their news to the dead.", req: "ancestor_bound" },
    { t: "Guests are fed first and best, and even a poor family will kill its last goat to honour a stranger.", req: "hospitable" },
    { t: "Strangers are watched from behind shutters, and a new face in the village is the talk of the season.", req: "insular" },
    { t: "Every young man spends two years in the army, and every old man tells stories of those years forever after.", req: { any: ["martial", "standing_army", "gov:stratocracy"] } },
    { t: "Wartime rationing has made bread dear and tempers short, and every family has someone at the front.", req: "atwar" },
    { t: "Market squares ring with haggling from dawn, and even children learn to count coin before letters.", req: "mercantile" },
    { t: "Schools stand in every town, and literacy here is common enough that graffiti is a local art.", req: { any: ["scholarly", "academies"] } },
    { t: "People consult omens before every journey, and a black bird on the roof can cancel a wedding.", req: "seers" },
  ],

  history: [
    "{realm} was founded in the year {founded} {era}, though its people claim a history far older.",
    "The chronicles of {realm} begin in {founded} {era}, with a battle, a vow and a very convenient miracle.",
    "Since {founded} {era}, {realm} has weathered plague, famine and war, and remembers each in song.",
    "Every schoolchild in {realm} knows the founding tale, and every historian knows it is mostly invented.",
    "Old borders of {realm} have swelled and shrunk many times, and maps in {capital} are redrawn every generation.",
    // old dynasty
    { t: "The same bloodline has ruled {realm} since {founded} {era}, and its portraits fill an entire gallery.", req: "origin:old_dynasty" },
    { t: "Few families on {land} are older than the ruling house of {realm}, and none are prouder of it.", req: "origin:old_dynasty" },
    { t: "Centuries of unbroken rule have made the dynasty of {realm} seem part of the landscape, like the rivers and hills.", req: "origin:old_dynasty" },
    // successor
    { t: "When {fallen} fell, {realm} rose from its ruins, and still claims to be its rightful heir.", req: "origin:successor" },
    { t: "Imperial eagles of {fallen} still hang in {capital}, and the rulers of {realm} still use its titles.", req: "origin:successor" },
    { t: "{realm} was once a province of {fallen}; its governors declared themselves kings as the empire crumbled.", req: "origin:successor" },
    // horde
    { t: "Riders from the far grasslands conquered this land in {founded} {era} and never went home.", req: "origin:horde" },
    { t: "The ancestors of the ruling clans came as a horde, burning and taking, and settled as lords of the conquered.", req: "origin:horde" },
    { t: "Conquerors and conquered have mingled for generations, but the old horde families still keep their horses and their pride.", req: "origin:horde" },
    // merchant charter
    { t: "A trading company founded {realm} in {founded} {era}, and its original charter still hangs in the council hall.", req: "origin:merchant_charter" },
    { t: "{realm} began as a trading post, a warehouse and a quay; everything else grew around the profits.", req: "origin:merchant_charter" },
    { t: "The founders of {realm} were shareholders, not warriors, and they bought more land than they ever conquered.", req: "origin:merchant_charter" },
    // holy mandate
    { t: "A prophet of {faith} founded {realm} in {founded} {era}, and the faith still names its rulers.", req: "origin:holy_mandate" },
    { t: "The founder of {realm} had a vision at {holy}, and pilgrims still walk the path the prophet trod.", req: "origin:holy_mandate" },
    { t: "Holy scripture tells how {deity} gave this land to the faithful, and the faithful have held it by sword since.", req: "origin:holy_mandate" },
    // exiles
    { t: "Refugees from across {sea} landed here in {founded} {era} and took the coast by the sword.", req: "origin:exiles" },
    { t: "The first settlers of {realm} were exiles, and their descendants still keep the customs of a homeland none have seen.", req: "origin:exiles" },
    { t: "Burned ships on the shore are the emblem of {realm}, for the exiles who founded it could never go back.", req: "origin:exiles" },
    // rebellion
    { t: "Peasants and burghers rose against their masters in {founded} {era}, and {realm} was born in fire.", req: "origin:rebellion" },
    { t: "The old lords' castles in {realm} are now granaries and schools, their owners long hanged or fled.", req: "origin:rebellion" },
    { t: "Veterans of the great revolt are still honoured in {capital}, and their banners hang in the assembly hall.", req: "origin:rebellion" },
    // union
    { t: "{realm} was born when several old crowns were joined by a marriage that neither side has forgiven.", req: "origin:union" },
    { t: "The union of crowns in {founded} {era} made {realm} great, and made its provinces quarrel ever since.", req: "origin:union" },
    { t: "Each old kingdom within {realm} keeps its own laws, its own nobles and its own grudges against the others.", req: "origin:union" },
    // titan slayers
    { t: "The founder of {realm} brought down a titan, and its bones now form the palace roof in {capital}.", req: "origin:titan_slayers" },
    { t: "Titan-slayers founded {realm} in {founded} {era}, and every ruler since has sworn to finish the work.", req: "origin:titan_slayers" },
    { t: "A great spear hangs above the throne of {realm}, the weapon that felled a titan and made a kingdom.", req: "origin:titan_slayers" },
    // titan heralds
    { t: "The titan chose the founders of {realm}, or so they say, and the realm has followed its path ever since.", req: "origin:titan_heralds" },
    { t: "In {founded} {era}, the titan paused where {capital} now stands, and its heralds took this as a command to build.", req: "origin:titan_heralds" },
    { t: "{realm} was founded by the titan's first priests, and its borders shift with the titan's wanderings.", req: "origin:titan_heralds" },
    // rift touched
    { t: "A creature came through the rift and gave the first rulers of {realm} their power; the court records never say what it asked in return.", req: "origin:rift_touched" },
    { t: "{realm} was founded in {founded} {era}, the year the rift opened and strange lights fell over the land.", req: "origin:rift_touched" },
    { t: "The founders of {realm} returned from the rift changed, and their descendants still have eyes that shine in the dark.", req: "origin:rift_touched" },
    // beast bond
    { t: "The founders of {realm} tamed the monsters of the wilds instead of fleeing them, and made a kingdom on their backs.", req: "origin:beast_bond" },
    { t: "Legend says the first ruler of {realm} shared a cave with a great beast for a winter and emerged its master.", req: "origin:beast_bond" },
    { t: "{realm} began as a camp of beast-riders, and its oldest families still claim kinship with their mounts.", req: "origin:beast_bond" },
    // ruin heirs
    { t: "{realm} was built atop an ancient city, and its people still dig up that city's secrets.", req: "origin:ruin_heirs" },
    { t: "The walls of {capital} rest on foundations laid by forgotten hands, and scholars argue about who built them.", req: "origin:ruin_heirs" },
    { t: "Settlers found ruins here in {founded} {era} and moved in, and the old stones have shaped the realm ever since.", req: "origin:ruin_heirs" },
    // frontier march
    { t: "{realm} began as a border fort against the wild, and it is still armed to the teeth.", req: "origin:frontier_march" },
    { t: "The first lords of {realm} were wardens of a frontier, and their castles still face outward.", req: "origin:frontier_march" },
    { t: "Founded as a march in {founded} {era}, {realm} grew from a line of watchtowers into a realm of its own.", req: "origin:frontier_march" },
    // mountain hold
    { t: "{realm} is a fortress-kingdom carved into the {range}, and no enemy has ever taken its gates.", req: "origin:mountain_hold" },
    { t: "The halls of {realm} were delved deep into the mountains, and its people still live more beneath the rock than upon it.", req: "origin:mountain_hold" },
    { t: "Since {founded} {era}, sieges have broken against the walls of {realm}, and its people boast of every one.", req: "origin:mountain_hold" },
  ],

  foreign: [
    "{realm} keeps envoys in most courts of {land}, and trusts almost none of them.",
    "Diplomats from {capital} are known for long speeches and short memories of past promises.",
    "Neighbours regard {realm} with the wariness one reserves for a large dog that has not yet bitten.",
    { t: "{rival} is the old enemy of {realm}, and each side blames the other for every war in living memory.", req: "atwar" },
    { t: "Relations with {rival} have soured beyond repair, and border raids are now an annual tradition.", req: "frontier" },
    { t: "{realm} and {rival} have fought so often that their histories read like two halves of one long quarrel.", req: { any: ["martial", "atwar"] } },
    { t: "An alliance with {ally} is the cornerstone of {realm}'s foreign policy, sealed by marriages and oaths.", req: "dynastic" },
    { t: "Royal brides pass between {realm} and {ally} every generation, binding their houses into a single tangled family.", req: "dynastic" },
    { t: "{ally} is {realm}'s oldest friend, though friendship between crowns is always a matter of interest.", req: "monarchy" },
    { t: "Trade with {ally} makes both realms richer, and their merchants have agents in each other's ports.", req: "mercantile" },
    { t: "{realm} trusts no foreign court, and its envoys are chosen for their silence rather than their charm.", req: { any: ["insular", "isolation"] } },
    { t: "The spymasters of {realm} have ears in {rival}'s court, and {rival} suspects it.", req: "spy_network" },
    { t: "Priests of {realm} preach against the heretics of {rival}, and the pulpits call for a holy war.", req: "zealous" },
    { t: "Pilgrims from every land are welcome in {realm}, and its roads are safe for foreigners of any faith.", req: { any: ["tolerant", "open_roads"] } },
    { t: "Tribute flows to {realm} from lesser neighbours, who have learned it is cheaper to pay than to fight.", req: { any: ["gov:khaganate", "gov:empire"] } },
    { t: "{realm} is too small to matter alone, so it plays the great powers against each other with remarkable skill.", req: { any: ["realm:tiny", "realm:small"] } },
    { t: "Neighbouring realms fear the titan more than {realm}, and {realm} happily reminds them of it.", req: "near:titan" },
    { t: "Other realms look on the rites of {realm} with horror, and few envoys stay long in {capital}.", req: "sinister" },
    { t: "{realm} claims lands held by {rival}, citing treaties, maps and ancestors in equal measure.", req: { any: ["origin:successor", "origin:union"] } },
    { t: "The war with {rival} has made strange friends of old enemies, and {ally} now sends arms and gold.", req: "atwar" },
    { t: "Merchants of {realm} fly their flags in every harbour of {sea}, and its consuls sit in a dozen foreign ports.", req: "has:port" },
  ],

  troubles: [
    "Bandits have grown bold on the roads of {realm}, and merchants now travel only in armed convoys.",
    "A bad harvest has left the granaries half empty, and the price of bread is rising by the week.",
    "Rumours of plague in the south of {realm} have emptied the markets and filled the temples.",
    "The treasury is nearly empty, though no one at court seems to have noticed.",
    "Taxes have risen three times in as many years, and the villages are growing restless.",
    { t: "The heir of {ruler} is sickly, and the court is already choosing sides for the succession.", req: "monarchy" },
    { t: "Great lords of {realm} grow restless, and several have stopped paying their dues to the crown.", req: { any: ["gov:feudal", "gov:elective"] } },
    { t: "Distant provinces talk of independence, and the governors sent to calm them have stopped sending reports.", req: { any: ["gov:empire", "realm:vast"] } },
    { t: "Council factions are deadlocked, and no law has passed in {capital} for over a year.", req: "republic" },
    { t: "Two clans are feuding over grazing rights, and the {title} cannot stop them without taking a side.", req: "tribal" },
    { t: "The mundane majority grumble against the {users} who rule them, and anti-magic pamphlets circulate in secret.", req: "gov:magocracy" },
    { t: "Reformers within the priesthood whisper against the synod, and the temples are dividing.", req: "gov:theocracy" },
    { t: "The war against {rival} is going badly, and deserters roam the countryside in armed bands.", req: "atwar" },
    { t: "Wounded veterans crowd the streets of {capital}, and the war has made the crown many enemies at home.", req: "atwar" },
    { t: "Beasts from the wilds have raided outlying farms, and whole villages have been abandoned.", req: "near:beasts" },
    { t: "The titan has turned toward {realm}, and a great exodus has begun from the lands in its path.", req: "near:titan" },
    { t: "Creatures crawl out of the rift at night, and the wardens posted to watch it have stopped sending reports.", req: "near:rift" },
    { t: "Diggers in the ruins broke open a sealed vault, and a sickness has spread through the nearby villages ever since.", req: "near:ruins" },
    { t: "Pirates prey on the shipping lanes of {sea}, and insurance rates in {capital} have tripled.", req: "has:port" },
    { t: "Flooding on the {river} has ruined the harvest and driven thousands into the towns.", req: "river" },
    { t: "Heretics are being burned in the squares of {capital}, and the fires grow more frequent each season.", req: "zealous" },
    { t: "Mercenary companies unpaid since the last war are demanding their wages, and they are camped close to {capital}.", req: "mercenaries" },
    { t: "Peasants chafe under the lords' labour-dues, and a preacher of equality draws crowds in the market towns.", req: { any: ["gov:feudal", "hierarchical"] } },
    { t: "Wild {power} has flared across the realm; crops wither, milk sours and wells glow at midnight.", req: ["default:power", { any: ["near:ley", "magic:high"] }] },
    { t: "The guilds and the crown quarrel over who may tax the markets, and shops close in protest.", req: "guilds" },
    { t: "Old families still loyal to the fallen dynasty plot quietly in their country houses.", req: { any: ["origin:rebellion", "origin:successor"] } },
    { t: "Border forts report more raids each month, and the garrisons are stretched thin.", req: { any: ["frontier", "frontier_forts"] } },
  ],
};

/* =========================================================================================
   CULTURES
   ========================================================================================= */
export const CULTURE_SECTIONS = {
  customs: [
    "Among the {people}, a promise is sealed by sharing bread and salt, and breaking one shames the whole family.",
    "The {people} greet one another with a touch to the brow and a question about the other's parents.",
    "Every {people} child receives a secret name at birth, known only to the mother and the gods.",
    "Coming of age among the {people} is marked by a journey alone, and a gift brought home to prove it.",
    { t: "The {people} launch every new boat with a libation of wine and a song to the sea.", req: "seafaring" },
    { t: "No {people} sailor whistles aboard ship, for whistling calls up storms and drowned men.", req: "seafaring" },
    { t: "A {people} child is set on a horse before it can walk, and a rider's first fall is celebrated with a feast.", req: "horse_lords" },
    { t: "Horses are exchanged at every wedding among the {people}, and a poor dowry of horses shames the bride's clan.", req: "horse_lords" },
    { t: "The {people} carve the name of every family into the rock above their door, deeper with each generation.", req: "mountain_folk" },
    { t: "Before felling a tree, the {people} ask its permission and leave a gift at its roots.", req: "forest_folk" },
    { t: "Water is never wasted among the {people}; spilling it is an insult to the host and the gods alike.", req: "desert_wanderers" },
    { t: "The {people} float lamps downstream to honour the dead, one light for each soul lost that year.", req: "river_folk" },
    { t: "Camps of the {people} are always pitched in a circle, with the elders' tents facing the dawn.", req: "nomadic" },
    { t: "Among the {people}, a gossip salon is a school, a market and a battlefield all at once.", req: "urbane" },
    { t: "Young {people} earn their adult names in battle, and scars are displayed with pride at feasts.", req: "martial" },
    { t: "A handshake among the {people} is a binding contract, and many deals are witnessed by a notary anyway.", req: "mercantile" },
    { t: "The {people} settle disputes by formal debate, and the loser buys the winner's wine.", req: "scholarly" },
    { t: "No {people} meal begins without a prayer, and no journey without a visit to the shrine.", req: "pious" },
    { t: "A {people} apprentice serves seven years before being allowed to sign their own work.", req: "artisans" },
    { t: "The {people} rarely marry outsiders, and those who do are quietly left out of family gatherings.", req: "insular" },
    { t: "Among the {people}, a guest may stay three days without explaining themselves, and must be fed the best in the house.", req: "hospitable" },
    { t: "{people} address their betters with long honorifics, and forgetting one is an insult that can start a feud.", req: "hierarchical" },
    { t: "The {people} bow to no one; even chiefs are addressed by first name and expected to fetch their own water.", req: "egalitarian" },
    { t: "The {people} set a place at every feast for the ancestors, and no one may sit there.", req: "ancestor_bound" },
    { t: "A {people} child is given a beast-cub to raise, and the two grow up as siblings.", req: "beast_tamers" },
    { t: "The {people} measure time by the titan's movements, and its passing is marked by days of silence.", req: "titan_touched" },
    { t: "Gifted {people} children are sent to the {users} at seven, and their families are honoured for it.", req: "arcane" },
    { t: "No {people} decision is made without consulting dreams, and the dream-teller sits beside the chief.", req: "seers" },
    { t: "The long dark winter is when the {people} tell their oldest tales, one each night until the thaw.", req: "cold" },
    { t: "The {people} bathe together in steaming springs, and much of their politics happens in the water.", req: { any: ["mountain", "cold"] } },
  ],

  food: [
    "The {people} table is simple: bread, onions, cheese and whatever the season allows.",
    "A {people} feast is judged by the number of dishes, and a stingy host is never forgiven.",
    "The {people} brew a strong, cloudy beer that foreigners compare, unkindly, to river water.",
    "Stews simmer for days in {people} kitchens, and each family guards the secret of its pot.",
    { t: "Salted fish, seaweed and hard biscuit are the staples of the {people}, washed down with sour wine.", req: { any: ["seafaring", "coastal"] } },
    { t: "Island {people} feast on shellfish, roasted over driftwood and eaten with the fingers.", req: "island" },
    { t: "Mare's milk, fermented and fizzy, is the favourite drink of the {people}, served at every gathering.", req: "horse_lords" },
    { t: "Dried meat and curds keep the {people} alive on the long rides between pastures.", req: { any: ["nomadic", "steppe"] } },
    { t: "Hard cheeses aged in caves are the pride of the {people}, and a wheel can be worth a sheep.", req: "mountain_folk" },
    { t: "The {people} forage mushrooms, berries and roots, and their bread is dark with nut flour.", req: "forest_folk" },
    { t: "Dates, flatbread and bitter coffee sustain the {people}, and hospitality begins with three cups.", req: "desert_wanderers" },
    { t: "Rice and river fish, spiced with pepper and wrapped in leaves, are eaten at every {people} meal.", req: "river_folk" },
    { t: "The {people} fill their markets with street food: pastries, skewers, fried dough and sugared nuts.", req: "urbane" },
    { t: "Spices from distant lands make {people} cooking famous, and a well-stocked pantry is a mark of wealth.", req: "mercantile" },
    { t: "Pious {people} fast one day in seven, and break the fast with honey cakes shared among neighbours.", req: "pious" },
    { t: "Venison and boar are reserved for nobles, and commoners caught poaching lose a hand.", req: "hierarchical" },
    { t: "The {people} cook fiery curries of lentils and peppers, eaten with flatbread and cooled with yogurt.", req: "hot" },
    { t: "Smoked meat, pickled roots and strong spirits get the {people} through the winter.", req: "cold" },
    { t: "Eel pie, frog legs and reed-root bread are the humble fare of the {people} of the marshes.", req: "marsh" },
    { t: "Tropical fruit, cassava and roasted grubs are staples of the {people}, served on banana leaves.", req: "jungle" },
    { t: "Guests of the {people} are served first and eat until they refuse three times.", req: "hospitable" },
    { t: "Meat from the titan's wake is prized by the {people}, though foreigners find it strange and gamey.", req: "titan_touched" },
    { t: "The {people} leave the first portion of every meal on the ancestral altar before anyone eats.", req: "ancestor_bound" },
    { t: "Soldiers' rations of hardtack and salted pork are eaten proudly by the {people}, even at home.", req: "martial" },
    { t: "Wine is a {people} passion, and every hillside is terraced with vines.", req: { any: ["warm", "hills"] } },
  ],

  dress: [
    "{people} clothing is practical: wool in winter, linen in summer, and a good cloak for everything else.",
    "The {people} wear bright sashes to show their clan, village or trade.",
    "Jewellery among the {people} is worn as savings, and a woman's bracelets are her family's bank.",
    { t: "The {people} wear tight-fitting tunics, oiled leather and knitted caps against the sea wind.", req: "seafaring" },
    { t: "Long riding coats, felt boots and fur hats are the dress of the {people}, cut for life in the saddle.", req: { any: ["horse_lords", "steppe"] } },
    { t: "Heavy furs and fleece-lined boots keep the {people} warm through the bitter mountain winters.", req: { any: ["mountain_folk", "cold"] } },
    { t: "The {people} dress in greens and browns, dyed with bark and moss, blending into the trees.", req: "forest_folk" },
    { t: "Flowing robes and veils protect the {people} from the sun and the sand.", req: { any: ["desert_wanderers", "desert"] } },
    { t: "Light, loose cotton and wide straw hats are the everyday dress of the {people}.", req: { any: ["hot", "river_folk"] } },
    { t: "Fashion changes every season among the city {people}, and last year's sleeves are a social death.", req: "urbane" },
    { t: "Every {people} adult carries a blade at the belt, and going unarmed is considered indecent.", req: "martial" },
    { t: "Dress among the {people} is regulated by law: only nobles may wear purple, silk or fur.", req: "hierarchical" },
    { t: "The {people} dress plainly, and showing off wealth in public is thought vulgar.", req: { any: ["egalitarian", "pious"] } },
    { t: "Fine embroidery marks {people} clothing, each stitch a pattern passed down through generations of craftswomen.", req: "artisans" },
    { t: "Scholars among the {people} wear ink-stained gowns and caps that show their degree.", req: "scholarly" },
    { t: "The {people} wear charms and amulets sewn into their clothes, each against a particular misfortune.", req: { any: ["seers", "pious"] } },
    { t: "Beast-hide armour and trophies of teeth and claws adorn the {people}, marking every beast they have tamed.", req: "beast_tamers" },
    { t: "Titan-scale armour and bone jewellery are prized by the {people}, gathered from the titan's wake.", req: "titan_touched" },
    { t: "Glowing sigils woven into {people} robes mark the wearer's magical rank.", req: "arcane" },
    { t: "Masks carved with ancestral faces are worn by the {people} at every solemn occasion.", req: "ancestor_bound" },
  ],

  arts: [
    "The {people} love long ballads of doomed lovers and foolish kings, sung in taverns until dawn.",
    "Storytellers are welcome in every {people} home, paid in bread and a place by the fire.",
    "{people} music is played on drums and pipes, and every village has its own tune for every occasion.",
    "The {people} tell their history in woven tapestries, each thread a battle, a marriage or a famine.",
    { t: "Sea shanties and sagas of voyages are the great art of the {people}, sung at every harbour.", req: "seafaring" },
    { t: "Epic poems of great rides and raids are chanted by {people} bards over the campfire.", req: { any: ["horse_lords", "nomadic"] } },
    { t: "Carved stone and wrought iron are the {people}'s art, and their halls are thick with carvings.", req: "mountain_folk" },
    { t: "Woodcarving is the {people} art, from totem poles to delicate figures of spirits and beasts.", req: "forest_folk" },
    { t: "The {people} are masters of poetry, reciting verses of love, loss and the stars under the open sky.", req: "desert_wanderers" },
    { t: "Painted river barges and boat races are the pride of the {people}, and each family boat is a masterpiece.", req: "river_folk" },
    { t: "Theatres and opera houses fill the {people} cities, and actors are celebrities who dine with nobles.", req: "urbane" },
    { t: "War dances and martial displays are the favourite art of the {people}, performed at every festival.", req: "martial" },
    { t: "Libraries are the pride of the {people}, and illuminated manuscripts are traded like jewels.", req: "scholarly" },
    { t: "Great temples with painted ceilings and gilded altars are the finest works of {people} art.", req: "pious" },
    { t: "Master craftsmen of the {people} produce glass, porcelain and metalwork famous across {land}.", req: "artisans" },
    { t: "The {people} paint portraits of the dead, and every home has a wall of ancestral faces.", req: "ancestor_bound" },
    { t: "Performances with tamed beasts are the great spectacle of the {people}, drawing crowds from far away.", req: "beast_tamers" },
    { t: "The {people} carve the titan into everything: walls, cups, cradles and gravestones.", req: "titan_touched" },
    { t: "Illusions woven by mages are the high art of the {people}, and a great illusionist is honoured like a king.", req: "arcane" },
    { t: "Prophetic poems and dream-songs are the art of the {people}, recited in trance by chosen seers.", req: "seers" },
    { t: "The {people} are famed for their gardens, laid out with water channels, fruit trees and shaded paths.", req: { any: ["hot", "warm"] } },
    { t: "Wandering {people} minstrels carry news and songs from camp to camp, welcome everywhere.", req: "hospitable" },
    { t: "Epic cycles about heroes and their deeds are recited over many nights at the {people} courts.", req: "hierarchical" },
    { t: "Carved masks and fireside puppet plays enliven the long {people} winters.", req: "cold" },
    { t: "The {people} write satire, and no ruler, priest or merchant escapes their mockery.", req: { any: ["egalitarian", "urbane"] } },
  ],

  names: [
    "The {people} name children after grandparents, so the same few names echo through every family.",
    "A {people} name has three parts: a given name, a father's name, and the name of the home village.",
    "The {people} change their names at great moments of life: marriage, war, or a brush with death.",
    { t: "{people} sailors take a sea-name on their first voyage, often a joke that sticks for life.", req: "seafaring" },
    { t: "Many {people} are named for horses, and a child with a great horse's name is expected to live up to it.", req: "horse_lords" },
    { t: "{people} names are long lists of ancestors, recited in full on formal occasions.", req: "ancestor_bound" },
    { t: "Nobles among the {people} carry long strings of titles and lands in their names; commoners have one name each.", req: "hierarchical" },
    { t: "{people} children are named by the seer, who reads the omens at the birth.", req: "seers" },
    { t: "The {people} name their children for virtues and gods, hoping the name will shape the child.", req: "pious" },
    { t: "Among the {people}, a person's name is shared with their tamed beast, and the two answer to it together.", req: "beast_tamers" },
    { t: "Many {people} are named after trees, rivers and birds, and each name comes with its own small story.", req: { any: ["forest_folk", "river_folk"] } },
  ],

  values: [
    "The {people} value loyalty above all, and a traitor's family is shamed for generations.",
    "Hard work and patience are the {people}'s virtues; flashiness and haste are suspect.",
    "The {people} prize cleverness, and a good trick is admired even by its victim.",
    "Family comes first among the {people}, then the village, and only then the crown.",
    { t: "Courage at sea is the highest virtue for the {people}, and a coward on board is left on the next rock.", req: "seafaring" },
    { t: "Freedom of the open steppe is sacred to the {people}; walls and cities are prisons.", req: { any: ["horse_lords", "nomadic"] } },
    { t: "Stubbornness is a virtue among the {people}, and they boast that they have never given up anything.", req: "mountain_folk" },
    { t: "The {people} value harmony with the forest; taking more than one needs is a sin.", req: "forest_folk" },
    { t: "Endurance is the first virtue of the {people}, who can walk for days on a mouthful of water.", req: "desert_wanderers" },
    { t: "The {people} believe that like the river, a good life flows around obstacles rather than through them.", req: "river_folk" },
    { t: "Wit, style and taste are the {people}'s values, and a boring person is the worst kind of sinner.", req: "urbane" },
    { t: "Honour in battle is everything to the {people}, and a peaceful death is thought almost shameful.", req: "martial" },
    { t: "Profit is no sin among the {people}; a person who dies rich is thought to have lived wisely.", req: "mercantile" },
    { t: "Knowledge is the {people}'s treasure, and a book is a better gift than gold.", req: "scholarly" },
    { t: "The {people} value devotion, and a person's worth is measured by their piety.", req: "pious" },
    { t: "Craftsmanship is a moral duty for the {people}; shoddy work is a lie told in wood or metal.", req: "artisans" },
    { t: "The {people} value self-reliance and privacy, and asking for help is a last resort.", req: "insular" },
    { t: "Generosity to strangers is the first virtue of the {people}, and a closed door is a disgrace.", req: "hospitable" },
    { t: "Order and duty are the {people}'s values; everyone has a place, and chaos comes when they leave it.", req: "hierarchical" },
    { t: "Equality is sacred among the {people}, and anyone who puts on airs is soon mocked back into line.", req: "egalitarian" },
    { t: "The {people} live to honour their ancestors, and every deed is weighed by what the dead would think.", req: "ancestor_bound" },
    { t: "Mastery of beasts is the {people}'s highest ideal; courage without it is only foolishness.", req: "beast_tamers" },
    { t: "The {people} value humility, for they live beside a titan and know how small they are.", req: "titan_touched" },
    { t: "Talent in magic is revered among the {people}, and the gifted are expected to serve their communities.", req: "arcane" },
    { t: "The {people} believe fate can be read but not escaped, and they meet misfortune with calm acceptance.", req: "seers" },
  ],
};

/* =========================================================================================
   FAITHS
   ========================================================================================= */
export const FAITH_SECTIONS = {
  beliefs: [
    "{faith} teaches that the world was made with purpose, and that every soul has a part to play in it.",
    "The faithful of {faith} believe that {deity} watches over them, rewarding the righteous and punishing the proud.",
    "At the heart of {faith} lies the belief that suffering has meaning, and that the patient will be repaid.",
    // pantheon
    { t: "{faith} honours many gods, each ruling a part of the world, and none may be neglected without consequence.", req: "faith:pantheon" },
    { t: "Worshippers of {faith} believe that {deity} is the eldest of the gods, though the younger ones quarrel over who rules the heavens.", req: "faith:pantheon" },
    { t: "The gods of {faith} are proud and quarrelsome, and mortals must balance their offerings to avoid jealousy.", req: "faith:pantheon" },
    // one god
    { t: "{faith} teaches that there is one god, {deity}, and that all other gods are false or fallen.", req: "faith:one_god" },
    { t: "Believers of {faith} hold that {deity} created the world in seven days and will unmake it at the end of time.", req: "faith:one_god" },
    { t: "The church of {faith} teaches that salvation comes through obedience, and that doubt is the first step to damnation.", req: "faith:one_god" },
    // dualism
    { t: "{faith} teaches that light and darkness are locked in eternal struggle, and every soul must choose a side.", req: "faith:dualism" },
    { t: "Believers of {faith} hold that the world was made by a good god and marred by an evil one.", req: "faith:dualism" },
    { t: "In {faith}, every good deed strengthens the light, and every sin feeds the dark.", req: "faith:dualism" },
    // ancestors
    { t: "{faith} teaches that the dead do not leave; they watch over their descendants and demand to be honoured.", req: "faith:ancestors" },
    { t: "Followers of {faith} believe the ancestors can bless or curse the living, depending on how they are remembered.", req: "faith:ancestors" },
    // spirits
    { t: "{faith} holds that every river, stone, tree and beast has a spirit, and they must be bargained with.", req: "faith:spirits" },
    { t: "The spirits of {faith} are neither good nor evil, only hungry, proud and easily offended.", req: "faith:spirits" },
    // sun
    { t: "{faith} teaches that {deity} is the sun, and the ruler is the sun's child on earth.", req: "faith:sun" },
    { t: "Believers of {faith} hold that the sun dies each night and is reborn each dawn through their prayers.", req: "faith:sun" },
    // sea
    { t: "{faith} teaches that {deity} rules the depths, giving fish and taking sailors as her due.", req: "faith:sea" },
    { t: "The faithful of {faith} believe that the sea is the mother of all life, and all life will one day return to her.", req: "faith:sea" },
    // titan
    { t: "{faith} teaches that the titan is a living god, and its footsteps are scripture written on the land.", req: "faith:titan" },
    { t: "Followers of {faith} believe the titan will one day wake fully and remake the world in its image.", req: "faith:titan" },
    // void
    { t: "{faith} teaches that the rift is a door to a greater world, and that those who serve it will be changed into something better.", req: "faith:void" },
    { t: "Believers of {faith} hold that a hungry power lies beneath the world, and that feeding it offerings is safer than being eaten by it.", req: "faith:void" },
    // ley
    { t: "{faith} teaches that the ley lines are the veins of the world, and magic is the divine flowing through them.", req: "faith:ley" },
    { t: "In {faith}, the gods are not persons but patterns in the flow of power, and priests are mages who read them.", req: "faith:ley" },
    // philosophy
    { t: "{faith} teaches that there are no gods, only reason, virtue and the long work of understanding the world.", req: "faith:philosophy" },
    { t: "Followers of {faith} hold that a good life is one lived with reason, moderation and kindness.", req: "faith:philosophy" },
    // stars
    { t: "{faith} teaches that fate is written in the stars, and the wise can read it if they study long enough.", req: "faith:stars" },
    { t: "Believers of {faith} hold that each soul is born under a star, and that star rules its fortune.", req: "faith:stars" },
    // doctrines
    { t: "{faith} teaches that unbelievers must be converted or driven out, for their error pollutes the land.", req: "zealous" },
    { t: "{faith} holds that other faiths are welcome to their errors, and truth needs no sword to defend it.", req: "tolerant" },
    { t: "{faith} teaches that bloodshed stains the soul, and even a soldier must do penance after battle.", req: "pacifist" },
    { t: "{faith} holds that wealth is a trap, and the holy must live in poverty to see clearly.", req: "ascetic" },
    { t: "{faith} teaches that the gods are fed by sacrifice, and a hungry god is a dangerous one.", req: "sacrifice" },
    { t: "In {faith}, visions and trances matter more than scripture, and the mystic outranks the scholar.", req: "mystic" },
  ],

  rites: [
    "The faithful of {faith} pray at dawn and dusk, facing {holy} wherever they are.",
    "Weddings under {faith} are sealed with a shared cup and a blessing from the eldest priest present.",
    "Newborns are presented at the temple of {faith} on their seventh day, and named before the altar.",
    "Worshippers of {faith} light candles for the sick, the absent and the dead.",
    { t: "Every temple of {faith} holds a feast for each god in turn, and the calendar is crowded with holy days.", req: "faith:pantheon" },
    { t: "Worshippers of {faith} leave offerings at many shrines, choosing which god to honour by their need.", req: "faith:pantheon" },
    { t: "The church of {faith} holds services every seventh day, and attendance is taken by the priests.", req: "faith:one_god" },
    { t: "Confession before a priest of {faith} is required once a year, and forgiveness costs a tithe.", req: ["faith:one_god", "organised"] },
    { t: "Believers of {faith} keep two fires in their homes, one lit and one dark, and tend both.", req: "faith:dualism" },
    { t: "Families of {faith} gather at the tombs on holy days, feeding the dead and asking their advice.", req: "faith:ancestors" },
    { t: "Worshippers of {faith} keep the bones of their ancestors in a household shrine, washed and oiled each year.", req: "faith:ancestors" },
    { t: "Shamans of {faith} dance and drum to call the spirits, bargaining for rain, game and health.", req: "faith:spirits" },
    { t: "Before hunting, fishing or felling, followers of {faith} ask the spirits' leave and leave a gift.", req: "faith:spirits" },
    { t: "The faithful of {faith} greet the dawn with song, and the sun's rising is the holiest moment of each day.", req: "faith:sun" },
    { t: "Sailors of {faith} pour wine into the sea before each voyage, and throw a coin overboard for each safe return.", req: "faith:sea" },
    { t: "Followers of {faith} walk in the titan's footsteps, and a pilgrimage along its path cleanses all sin.", req: "faith:titan" },
    { t: "Rites of {faith} are held at night on the edge of the rift, where the faithful throw their offerings into it.", req: "faith:void" },
    { t: "Priests of {faith} channel the ley lines in their rites, and the altars glow with gathered power.", req: "faith:ley" },
    { t: "Followers of {faith} meet to debate, read and reflect, and a good argument is their only ritual.", req: "faith:philosophy" },
    { t: "The faithful of {faith} consult the stars before every major decision, and astrologers cast charts for every birth.", req: "faith:stars" },
    { t: "Every believer of {faith} must walk to {holy} once in their life, and many die along the way.", req: "pilgrims" },
    { t: "Gold, incense and processions mark the rites of {faith}; the gods like a show.", req: "lavish" },
    { t: "Rites of {faith} are simple and silent, held in bare halls with no decoration but a single lamp.", req: "ascetic" },
    { t: "Beasts are sacrificed on the altars of {faith}, their blood poured to feed the gods.", req: "sacrifice" },
    { t: "Rumour says that in the secret rites of {faith}, some of the offerings are people, not animals.", req: ["sacrifice", "sinister"] },
    { t: "Worshippers of {faith} seek visions through fasting, dancing and smoke, and share what they see.", req: "mystic" },
    { t: "Warrior-monks of {faith} consecrate their weapons at dawn and swear to use them only in the faith's defence.", req: "militant" },
    { t: "Converts to {faith} are baptised in public before cheering crowds, and apostates are punished in the same squares.", req: "zealous" },
    { t: "Temples of {faith} open their doors to worshippers of any faith, and foreign pilgrims are welcomed as guests.", req: "tolerant" },
    { t: "Believers of {faith} beg forgiveness from any creature they harm, even an insect crushed by accident.", req: "pacifist" },
  ],

  clergy: [
    "Priests of {faith} are trained from childhood in temple schools, learning scripture, song and a little medicine.",
    "The clergy of {faith} are respected in public and gossiped about in private, as clergy always are.",
    "A priest of {faith} must be unmarried, though the rule is kept better in the capital than the countryside.",
    { t: "Each god of {faith} has its own priesthood, and they compete fiercely for worshippers and offerings.", req: "faith:pantheon" },
    { t: "A strict hierarchy of priests, bishops and a high pontiff governs {faith} from the great temple at {holy}.", req: "organised" },
    { t: "The church of {faith} owns great estates, and its bishops are as powerful as any lord.", req: ["organised", "!ascetic"] },
    { t: "Priests of {faith} wear white on one side and black on the other, symbolising the eternal struggle.", req: "faith:dualism" },
    { t: "{faith} has no priests; the eldest of each family leads the rites for their own ancestors.", req: "faith:ancestors" },
    { t: "Shamans of {faith} are chosen by the spirits through illness, dreams or strange marks at birth.", req: "faith:spirits" },
    { t: "Sun-priests of {faith} shave their heads and wear gold, and the high priest is the ruler's own sibling.", req: "faith:sun" },
    { t: "Priests of {faith} are drowned and revived as part of their ordination, and a few never fully recover.", req: "faith:sea" },
    { t: "Titan-priests of {faith} follow the titan in great caravans, reading omens in its tracks.", req: "faith:titan" },
    { t: "The priesthood of {faith} is a secret society, whose members bear marks the rift left on their skin.", req: "faith:void" },
    { t: "Priests of {faith} are all mages, and ordination requires proof of power as well as faith.", req: "faith:ley" },
    { t: "{faith} has teachers rather than priests, and anyone who can argue well may lead a school.", req: "faith:philosophy" },
    { t: "Astrologers of {faith} outrank priests, and their towers dominate the skyline of every city.", req: "faith:stars" },
    { t: "Warrior-monks of {faith} guard temples and pilgrims, and their orders have fortresses across {land}.", req: "militant" },
    { t: "Inquisitors of {faith} hunt heretics, and their arrival in a town empties the taverns.", req: "zealous" },
    { t: "Priests of {faith} own nothing but a robe and a bowl, and they beg for their daily bread.", req: "ascetic" },
    { t: "High priests of {faith} dress in cloth of gold and ride in gilded litters.", req: "lavish" },
    { t: "Mystics of {faith} live in caves and on mountaintops, and people climb for days to hear their visions.", req: "mystic" },
    { t: "Priests of {faith} are forbidden to carry weapons, and even their staffs are of soft wood.", req: "pacifist" },
    { t: "The clergy of {faith} are loosely organised, and each village priest interprets the teachings freely.", req: "!organised" },
    { t: "Temple guides of {faith} escort pilgrims along the roads to {holy}, for a fee.", req: "pilgrims" },
    { t: "Sacrificial priests of {faith} wear red and carry the ritual knife as their badge of office.", req: "sacrifice" },
  ],

  afterlife: [
    "{faith} teaches that the soul travels a long road after death, judged by what it did in life.",
    "Believers of {faith} are buried with coins for the journey, and a lamp to light the way.",
    "The dead of {faith} are said to rest in a quiet land beyond the horizon, awaiting their descendants.",
    { t: "The souls of the righteous in {faith} feast in the halls of the gods, while the wicked wander forever.", req: "faith:pantheon" },
    { t: "{faith} teaches that {deity} judges every soul, sending the righteous to paradise and the wicked to torment.", req: "faith:one_god" },
    { t: "In {faith}, souls that served the light rise to join it, while those of the dark are devoured.", req: "faith:dualism" },
    { t: "The dead in {faith} become ancestors, who live on as long as they are remembered and fade when forgotten.", req: "faith:ancestors" },
    { t: "{faith} teaches that the dead become spirits of the land, dwelling in trees, stones and streams.", req: "faith:spirits" },
    { t: "The righteous dead of {faith} rise with the sun each dawn and shine forever in its light.", req: "faith:sun" },
    { t: "{faith} teaches that the drowned are blessed, and the dead are given to the sea in weighted shrouds.", req: "faith:sea" },
    { t: "The dead of {faith} are laid in the titan's path, for it is believed to carry their souls onward.", req: "faith:titan" },
    { t: "{faith} teaches that the dead pass through the rift and become part of what lies beyond.", req: "faith:void" },
    { t: "In {faith}, souls dissolve into the ley lines at death, joining the great current of power.", req: "faith:ley" },
    { t: "{faith} teaches nothing certain about death; a wise person lives well and leaves the rest to reason.", req: "faith:philosophy" },
    { t: "The dead of {faith} become new stars, and the brightest are the greatest souls.", req: "faith:stars" },
    { t: "Martyrs of {faith} go straight to paradise, and many believers seek a holy death.", req: { any: ["zealous", "militant"] } },
    { t: "Souls of {faith} are reborn many times, until they are pure enough to escape the wheel of life.", req: { any: ["ascetic", "mystic"] } },
    { t: "{faith} teaches that the dead may return in dreams, bearing warnings and blessings.", req: "mystic" },
    { t: "The wicked dead of {faith} are said to wander the world as hungry ghosts, and offerings are left to appease them.", req: { any: ["faith:ancestors", "faith:spirits"] } },
    { t: "Believers of {faith} are buried in great tombs, filled with treasure and servants' effigies.", req: "lavish" },
  ],

  symbols: [
    "The symbol of {faith} is a circle within a circle, carved above every temple door.",
    "Believers of {faith} wear a small token of {deity} around their necks, blessed at their naming.",
    "The holy colour of {faith} is white, and priests wear nothing else on feast days.",
    { t: "Each god of {faith} has its own symbol, and temples are decorated with dozens of them.", req: "faith:pantheon" },
    { t: "The single eye of {deity} is the emblem of {faith}, watching from every altar and banner.", req: "faith:one_god" },
    { t: "A flame half white and half black is the symbol of {faith}, marking the eternal struggle.", req: "faith:dualism" },
    { t: "A family tree carved into wood or stone is the sacred symbol of {faith}, kept in every home.", req: "faith:ancestors" },
    { t: "Feathers, bones and painted stones are the sacred symbols of {faith}, each tied to a particular spirit.", req: "faith:spirits" },
    { t: "A golden disc with rays is the emblem of {faith}, blazing above every altar.", req: "faith:sun" },
    { t: "A shell or a trident is the symbol of {faith}, carved on the prows of every ship.", req: "faith:sea" },
    { t: "A great footprint is the symbol of {faith}, marking every shrine along the titan's path.", req: "faith:titan" },
    { t: "An open eye within a black circle is the symbol of {faith}, painted in secret on doorways.", req: "faith:void" },
    { t: "A web of glowing lines is the symbol of {faith}, mapping the ley currents of the world.", req: "faith:ley" },
    { t: "An open book is the emblem of {faith}, for knowledge is its only holy thing.", req: "faith:philosophy" },
    { t: "A seven-pointed star is the symbol of {faith}, and each point stands for a heavenly sphere.", req: "faith:stars" },
    { t: "A sword crossed with a holy symbol is the emblem of {faith}'s warrior orders.", req: "militant" },
    { t: "A pilgrim's staff and shell are the symbols of {faith}, carried by every believer who has walked to {holy}.", req: "pilgrims" },
    { t: "A simple bowl is the symbol of {faith}, reminding the faithful that they need little.", req: "ascetic" },
    { t: "A bloodied knife is the sacred symbol of {faith}, carried by its priests in ceremony.", req: "sacrifice" },
    { t: "A white dove or an unstrung bow is the symbol of {faith}, marking its devotion to peace.", req: "pacifist" },
  ],

  holy_days: [
    "The {festival} is the greatest holy day of {faith}, celebrated with feasting, processions and prayer.",
    "Believers of {faith} observe the {festival} with a day of fasting, followed by a great feast at dusk.",
    "Each spring, the faithful of {faith} celebrate the {festival}, lighting fires to welcome the new season.",
    "The {festival} marks the end of the harvest, when the faithful give thanks to {deity} for the year's bounty.",
    { t: "At the {festival}, pilgrims crowd the roads to {holy}, and the city's population doubles overnight.", req: "pilgrims" },
    { t: "Midsummer is the holiest day of {faith}, when the sun stands highest and its priests perform the great rite.", req: "faith:sun" },
    { t: "On the {festival}, the faithful of {faith} visit the tombs of their ancestors and feast among the dead.", req: "faith:ancestors" },
    { t: "The {festival} is the day the fleet is blessed, and no ship of {faith} sails before it.", req: "faith:sea" },
    { t: "The night the rift burns brightest is the holiest time of {faith}, and the faithful gather to watch.", req: "faith:void" },
    { t: "When the titan stirs, the faithful of {faith} drop everything to celebrate, whatever the season.", req: "faith:titan" },
    { t: "The {festival} is timed by the astrologers of {faith}, and falls on a different day each year.", req: "faith:stars" },
    { t: "On the {festival}, the gods of {faith} are carried through the streets on gilded litters, amid music and incense.", req: ["lavish", "faith:pantheon"] },
    { t: "The {festival} is a day of silence and fasting for {faith}, when no fire is lit and no word spoken.", req: "ascetic" },
  ],
};

/* =========================================================================================
   CURRENCY & TITLES
   ========================================================================================= */
// forms: "$" = metal, "{unit}" = unit name
export const CURRENCY = {
  metals: ["silver", "gold", "copper", "bronze", "electrum"],
  units: [
    { n: "mark", w: 2 },
    { n: "crown", req: "monarchy", w: 2 },
    { n: "sovereign", req: "monarchy" },
    { n: "florin", req: "republic", w: 2 },
    { n: "ducat", req: { any: ["gov:merchant", "mercantile"] }, w: 2 },
    { n: "noble", req: "hierarchical" },
    { n: "penny", w: 1.5 },
    { n: "shilling" },
    { n: "talent", req: { any: ["gov:empire", "scholarly"] } },
    { n: "denar", req: "gov:empire" },
    { n: "dinar", req: { any: ["desert", "hot"] }, w: 2 },
    { n: "dirham", req: "desert" },
    { n: "tael", req: { any: ["river", "urbane"] } },
    { n: "shell-money", req: ["island", "tribal"], w: 3 },
    { n: "cowrie", req: { any: ["island", "jungle"] } },
    { n: "ring", req: { any: ["tribal", "cold"] } },
    { n: "hack-bar", req: { any: ["tribal", "nomadic"] } },
    { n: "yastuk", req: { any: ["gov:khaganate", "horse_lords"] } },
    { n: "sun", req: "faith:sun", w: 2 },
    { n: "shield", req: { any: ["martial", "gov:stratocracy"] } },
    { n: "anchor", req: "seafaring" },
    { n: "pound" },
    { n: "thaler", req: "mountain" },
    { n: "obol", req: { any: ["pious", "faith:pantheon"] } },
    { n: "sigil", req: { any: ["gov:magocracy", "arcane"] } },
    { n: "fang", req: "beast_tamers" },
    { n: "scale", req: "near:titan" },
  ],
  forms: ["$ {unit}s", "{unit}s", "$ {unit}s", "{unit}s of $"],
};

export const TITLES = {
  nobles: [
    "Duke", "Duchess", "Count", "Countess", "Baron", "Baroness", "Margrave", "Viscount", "Earl", "Thane",
    "Palatine", "Voivode", "Boyar", "Emir", "Satrap", "Jarl", "Castellan", "Seneschal", "Banneret", "Landgrave",
    "Noyan", "Archon",
  ],
  offices: [
    "Keeper of the Seal", "Lord Chancellor", "Master of Coin", "Marshal of the Realm", "High Admiral", "Lord Chamberlain",
    "Master of Whispers", "Grand Vizier", "Keeper of the Rolls", "Master of Horse", "Warden of the Marches", "Lord Steward",
    "Master of the Mint", "High Justiciar", "Keeper of the Keys", "Master of Ceremonies", "Royal Astrologer", "Court Archivist",
    "Lord of the Granaries", "Captain of the Guard", "Keeper of the Beasts", "Warden of the Roads",
  ],
};
