// News feed templates: the history simulation emits events month by month, and each event becomes a
// news item by picking one template of its kind and filling the slots.
// Format: NEWS = { <kind>: [ { h: "headline", b: "body", req?: <condition>, w?: weight }, ... ] }
//   req uses the core/rules.js condition format ("tag", "!tag", [all of], { any: [...] }, { not: cond })
//   and is tested against the ACTING realm's tags. w defaults to 1.
//   Slots: {realm} {realm2} {short} {short2} {ruler} {ruler2} {heir} {person} {title} {place} {place2} {war}
//   {tactic} {tactic2} {commander} {commander2} {casualties} {invention} {field} {project} {faith} {people}
//   {good} {gov} {gov2} {count} {titan} {site} {year} {epithet}, and the power words {power} {user} {users}
//   {node} (magic/mage/mages by default, or the active power premise's). A template with an empty slot is dropped.
// Rules: headlines 4-10 words, bodies 12-35 words, no proper names except through slots, vary the openings,
//   and keep at least four templates per kind without req.

export const NEWS = {
  /* ---------------- war and battle ---------------- */
  war_declared: [
    { h: "{short} declares war on {short2}", b: "Heralds rode out from the court of {ruler} today, carrying word that {realm} is at war with {realm2}. Levies are already gathering." },
    { h: "War! {realm} marches against {realm2}", b: "After months of insults and border quarrels, {ruler} has drawn the sword. Merchants are fleeing the roads toward {place}." },
    { h: "Banners raised as {war} begins", b: "The drums have sounded in {realm}. What began as a quarrel with {realm2} is now open war, and the people brace for a long season." },
    { h: "{ruler} throws down the gauntlet", b: "Before the assembled court, {ruler} named {realm2} an enemy of the realm. Few in {place} expect the fighting to end before winter." },
    { h: "Peace ends between {short} and {short2}", b: "The border is closed and the watchfires lit. Envoys of {realm2} were sent home without an answer, and the armies of {short} are moving." },
    { h: "Holy war proclaimed against {short2}", b: "Priests of {faith} declared from every pulpit that the war on {realm2} is sacred. Volunteers crowd the temple steps to take up arms.", req: { any: ["zealous", "militant", "theocratic"] }, w: 2 },
    { h: "The horde rides for {short2}", b: "Riders by the thousand have left the summer pastures. {ruler} has pointed the host at {realm2}, and the grasslands shake beneath them.", req: { any: ["gov:khaganate", "horse_lords"] }, w: 2 },
    { h: "Council votes for war with {short2}", b: "After a stormy session, the council of {realm} voted to take up arms against {realm2}. Bankers are already pricing the loans.", req: "republic", w: 1.5 },
    { h: "{short} sharpens its blades for glory", b: "Young nobles of {realm} cheered in the streets as war on {realm2} was proclaimed. Here, a war is an opportunity, not a misfortune.", req: { any: ["martial", "warrior_code"] }, w: 1.5 },
  ],
  battle_won: [
    { h: "Victory at {place}!", b: "The army of {realm} has routed the forces of {realm2} near {place}. {casualties} dead lie on the field, and the bells have not stopped ringing." },
    { h: "{commander} breaks the enemy with {tactic}", b: "Outnumbered near {place}, {commander} held the line with {tactic} until the host of {realm2} broke and fled. Songs are already being written." },
    { h: "{short2} routed in the field", b: "Word arrives from the front: the soldiers of {short} have carried the day at {place}. The enemy left {casualties} dead behind them." },
    { h: "Triumph for {short} in {war}", b: "Crowds gathered in the streets as couriers confirmed a great victory at {place}. {ruler} has ordered a day of thanksgiving." },
    { h: "Enemy scattered near {place}", b: "By nightfall the field belonged to {realm}. Captured banners of {realm2} will be paraded before {ruler} within the week." },
    { h: "{commander} outwits {commander2}", b: "By {tactic}, {commander} lured {commander2} into a trap at {place}. The survivors of {realm2} are fleeing toward their own border." },
    { h: "Riders of {short} sweep the field", b: "Horse archers circled the army of {realm2} at {place} until it simply fell apart. The plain is littered with {casualties} fallen.", req: { any: ["horse_lords", "gov:khaganate"] }, w: 2 },
    { h: "Fleet of {short} triumphs off {place}", b: "Burning hulls of {realm2} drift on the tide tonight. The sailors of {realm} have proven again that the sea belongs to them.", req: { any: ["seafaring", "navy"] }, w: 1.5 },
    { h: "Beasts of war crush {short2}", b: "The tamed monsters of {realm} tore through the enemy ranks at {place}. Those who survived speak only of the roaring.", req: { any: ["beast_cavalry", "beast_tamers"] }, w: 2 },
    { h: "{users} turn the tide at {place}", b: "Fire fell from a clear sky on the army of {realm2}. The {users} of {realm} are the talk of every tavern tonight.", req: { any: ["arcane_council", "gov:magocracy"] }, w: 2 },
  ],
  battle_draw: [
    { h: "Bloody stalemate at {place}", b: "Neither {realm} nor {realm2} could claim the field at {place}. Both armies withdrew at dusk, leaving {casualties} dead in the mud." },
    { h: "No victor in the clash near {place}", b: "A long day of killing gained neither side any ground. The armies of {short} and {short2} watch each other across a field of the fallen." },
    { h: "Both hosts bleed, neither yields", b: "Against {tactic}, {commander} answered with {tactic2}, and the battle at {place} ground to a halt. The war drags on." },
    { h: "Battle of {place} ends in exhaustion", b: "Rain, mud and stubbornness decided nothing today. Both {short} and {short2} claim victory; the crows are the only true winners." },
    { h: "{commander} and {commander2} fight to a standstill", b: "Two able commanders met at {place} and neither found the other's weakness. Each side counts {casualties} fallen and little gain." },
    { h: "A grim draw in {war}", b: "The heralds of {realm} speak of a hard-fought day, which everyone understands to mean a draw. The field at {place} remains empty." },
    { h: "Priests pray over a divided field", b: "After the indecisive clash at {place}, the priests of {faith} walked among the dead of both sides, blessing friend and foe alike.", req: "pious" },
  ],
  siege_started: [
    { h: "{place} under siege", b: "The army of {realm} has encircled {place} and dug in. The defenders of {realm2} have shut the gates and are rationing their grain." },
    { h: "Siege lines drawn around {place}", b: "Trenches, palisades and siege towers now ring {place}. Those inside can only wait, and hope that {realm2} sends relief." },
    { h: "{short} invests the walls of {place}", b: "Smoke rises from the camps outside {place}. {commander} has vowed not to leave until the town opens its gates." },
    { h: "Gates closed, {place} awaits the storm", b: "Refugees crowded into {place} just before the besiegers arrived. Now the walls are all that stand between them and {realm}." },
    { h: "Engines creak before {place}", b: "Carpenters of {realm} have built catapults within sight of the walls. The garrison of {place} answers with arrows and defiance." },
    { h: "Blockade tightens around {place}", b: "Ships of {realm} now choke the harbour of {place}. No grain, no news and no hope gets in by sea.", req: { any: ["seafaring", "navy"] } },
    { h: "Sappers dig beneath {place}", b: "The miners of {realm} have begun tunnelling toward the walls of {place}. Defenders press their ears to the stones at night.", req: "mountain_folk" },
  ],
  siege_fallen: [
    { h: "{place} falls to {short}", b: "After a long siege, the walls of {place} were breached at dawn. The banners of {realm} now fly over the town." },
    { h: "Gates of {place} thrown open", b: "Starved and exhausted, the garrison of {place} surrendered to {commander}. The citizens await their new masters in silence." },
    { h: "Storm of {place} succeeds", b: "Ladders went up at midnight and by morning {place} belonged to {realm}. {realm2} has lost a jewel of its crown." },
    { h: "{place} taken after bitter siege", b: "The defenders of {realm2} held out as long as they could. Today the keys of {place} were handed to {ruler}." },
    { h: "Walls breached, {place} surrenders", b: "A mine collapsed the eastern tower and the besiegers poured through. {place} is now held by {realm}." },
    { h: "{place} sacked by the victors", b: "Fires burned for three days after {place} fell. The soldiers of {realm} took everything they could carry.", req: { any: ["tribal", "gov:khaganate", "martial"] } },
    { h: "Mercy shown at {place}", b: "To general surprise, {ruler} forbade any looting when {place} fell. The townsfolk kneel, grateful and wary.", req: { any: ["pacifist", "tolerant", "hospitable"] } },
  ],
  siege_lifted: [
    { h: "Siege of {place} broken", b: "The besiegers have packed their tents and gone. {place} celebrates, though its granaries are empty and its walls scarred." },
    { h: "Relief army reaches {place}", b: "The host of {realm} arrived just in time. The enemy camp outside {place} was abandoned before the first charge." },
    { h: "{place} holds! Besiegers withdraw", b: "Months of hunger and fear ended this week when the enemy lines melted away. The garrison of {place} is hailed as heroes." },
    { h: "Enemy abandons siege lines", b: "Disease and desertion did what swords could not. The army before {place} has retreated, leaving its siege engines to burn." },
    { h: "Bells ring in {place} once more", b: "For the first time since the siege began, the bells of {place} rang for joy. {commander} rode through the open gates to cheers." },
    { h: "Gods spare {place}, say the priests", b: "The lifting of the siege is being hailed as a miracle of {faith}. Thanksgiving processions fill every street of {place}.", req: "pious" },
  ],

  /* ---------------- peace and diplomacy ---------------- */
  peace_signed: [
    { h: "Peace between {short} and {short2}", b: "Envoys signed a treaty today ending {war}. Soldiers are coming home, and the roads to {place} are open again." },
    { h: "{war} is over", b: "After much bloodshed, {ruler} and {ruler2} have agreed terms. Few are happy with them, but everyone is happy to stop dying." },
    { h: "Treaty sealed, swords sheathed", b: "Ink and wax have ended what steel could not. {realm} and {realm2} are at peace, at least until the next quarrel." },
    { h: "Ink dries on the peace of {place}", b: "In a tent outside {place}, envoys of both realms signed the peace. Church bells in {short} rang long into the night." },
    { h: "Armies go home as peace returns", b: "Farmers are trading pikes for ploughs as {realm} makes peace with {realm2}. Widows in every village wonder what it was for." },
    { h: "Priests bless the peace with {short2}", b: "The treaty with {realm2} was signed before the altar of {faith}, and the priests called down blessings on all who keep it.", req: "pious", w: 1.5 },
    { h: "Merchants cheer the end of {war}", b: "Traders of {realm} toasted the peace with {realm2} before the ink was dry. Caravans loaded with {good} are already on the road.", req: "mercantile", w: 1.5 },
  ],
  province_ceded: [
    { h: "{place} handed to {short}", b: "By the terms of the peace, {realm2} has surrendered {place} to {realm}. New tax collectors are expected before the harvest." },
    { h: "{short2} yields {place}", b: "The treaty is signed and {place} changes hands. Its people wake up as subjects of {ruler}, whether they like it or not." },
    { h: "Border redrawn at {place}", b: "Surveyors of {realm} are planting new boundary stones around {place}, ceded by {realm2} as the price of peace." },
    { h: "{place} changes masters", b: "A new flag rises over {place} as {realm} takes possession. Some families are packing their carts to leave." },
    { h: "Spoils of {war}: {place}", b: "{ruler} returns from the peace talks with {place} in hand. {realm2} will not soon forget the humiliation." },
    { h: "Oaths sworn anew in {place}", b: "The notables of {place} knelt before the envoys of {realm} and swore fealty. Their old lords watched from across the new border.", req: "monarchy" },
  ],
  white_peace: [
    { h: "{war} ends with nothing gained", b: "{realm} and {realm2} have made peace on the old borders. Years of fighting have changed no map, only the graveyards." },
    { h: "Exhausted realms agree a truce", b: "Neither {short} nor {short2} could win. The peace signed today returns everything to how it was, minus the dead." },
    { h: "Status quo restored", b: "Envoys agreed that every town shall return to its former master. {ruler} calls it an honourable peace; the soldiers call it a waste." },
    { h: "Peace without victory", b: "No land, no gold, no glory: {war} ends as it began. Both courts are already blaming their commanders." },
    { h: "Old borders, new graves", b: "The treaty with {realm2} leaves every boundary untouched. In {place}, mothers ask what their sons died for." },
    { h: "Ancestors displeased by empty peace", b: "Elders of {realm} say the spirits of the fallen are restless, for {war} ended without a single field won.", req: "ancestor_bound" },
  ],
  alliance_formed: [
    { h: "{short} and {short2} join hands", b: "A pact of mutual defence was signed today between {realm} and {realm2}. Their enemies will think twice now." },
    { h: "New alliance shakes the balance", b: "{ruler} and {ruler2} have sworn to stand together in war. Envoys from neighbouring courts are hurrying home with the news." },
    { h: "Pact of friendship with {short2}", b: "Gifts were exchanged and oaths spoken as {realm} entered an alliance with {realm2}. Toasts were drunk late into the night." },
    { h: "Two realms, one shield", b: "From today, an attack on {realm2} is an attack on {realm}. The treaty was sealed with the exchange of hostages and wine." },
    { h: "Envoys seal alliance at {place}", b: "In the great hall of {place}, diplomats of {short} and {short2} signed a lasting alliance. Neighbouring courts are watching closely." },
    { h: "Blood-oath binds {short} and {short2}", b: "The chiefs mixed their blood in a cup and drank. By the old custom, {realm} and {realm2} are now kin.", req: "tribal", w: 1.5 },
    { h: "Allied under one faith", b: "The priests of {faith} presided as {realm} and {realm2} swore alliance, calling it the will of heaven.", req: "pious" },
  ],
  alliance_broken: [
    { h: "Alliance with {short2} is dead", b: "{ruler} has torn up the treaty with {realm2}. Old friends are now wary strangers along the border." },
    { h: "{short} breaks faith with {short2}", b: "Envoys of {realm2} were sent home today. The alliance that held for years has ended in bitter words." },
    { h: "Pact dissolved amid recriminations", b: "Each side accuses the other of betrayal. Whatever the truth, {realm} and {realm2} no longer stand together." },
    { h: "Old friends part ways", b: "The alliance between {short} and {short2} quietly expired, unrenewed. Courtiers whisper about what comes next." },
    { h: "Betrayal! Treaty torn in two", b: "Before the whole court, {ruler} ripped the treaty with {realm2} and cast it into the fire. The envoys left without bowing." },
    { h: "Council ends alliance by vote", b: "The council of {realm} voted narrowly to end its alliance with {realm2}, citing costs and broken promises.", req: "republic" },
  ],
  rivalry_declared: [
    { h: "{short} names {short2} its rival", b: "{ruler} has declared openly that {realm2} is the greatest threat to the realm. Every policy will now be measured against it." },
    { h: "Bad blood between {short} and {short2}", b: "Insults at a feast have turned into a formal rivalry. Neither court will receive the other's envoys." },
    { h: "A new rivalry is born", b: "{realm} and {realm2} have become sworn rivals. Merchants, spies and soldiers on both sides prepare accordingly." },
    { h: "{ruler} vows to humble {short2}", b: "In a fiery speech at {place}, {ruler} swore that {realm2} would one day kneel. The crowd roared its approval." },
    { h: "Cold war on the border", b: "Troops are massing, tolls are doubling and tempers are rising. {realm} now regards {realm2} as its chief enemy." },
    { h: "Warriors of {short} demand a reckoning", b: "The martial houses of {realm} have pressed {ruler} to name {realm2} a rival. Old defeats, they say, must be repaid.", req: "martial" },
  ],
  trade_deal: [
    { h: "Trade pact signed with {short2}", b: "Tolls are lowered and roads opened between {realm} and {realm2}. Wagons of {good} are expected in {place} within the month." },
    { h: "Markets open to {short2}", b: "{realm} and {realm2} have agreed to trade freely. Shopkeepers in {place} are already stocking foreign {good}." },
    { h: "Caravans roll as {short} and {short2} deal", b: "A new trade agreement has been sealed with handshakes and silver. Both treasuries expect a fatter year." },
    { h: "{good} to flow into {short2}", b: "Under a new treaty, {realm} will ship {good} to {realm2} in exchange for favoured access to its markets." },
    { h: "Handshake in {place} opens new routes", b: "Merchants of both realms met in {place} to seal a trade deal. Innkeepers along the road are rubbing their hands." },
    { h: "Merchant houses toast new trade", b: "The great trading families of {realm} have won the deal they wanted with {realm2}. Profits, they promise, will trickle down.", req: "mercantile", w: 2 },
    { h: "Free trade treaty hailed", b: "Consistent with its creed of open markets, {realm} has struck another bargain, this time with {realm2}. Tariffs fall on {good}.", req: "free_trade", w: 1.5 },
    { h: "Fleets to carry {good} abroad", b: "The harbours of {realm} will send ships laden with {good} to {realm2} under a new agreement. Shipwrights are hiring.", req: "seafaring" },
  ],
  embargo: [
    { h: "{short} bans trade with {short2}", b: "By order of {ruler}, no goods may pass to {realm2}. Merchants with cargo already on the road face ruin." },
    { h: "Embargo declared on {short2}", b: "Border posts have been told to turn back every wagon from {realm2}. The price of {good} is expected to soar." },
    { h: "Markets closed to {short2}", b: "Traders from {realm2} were escorted out of {place} today. {realm} will buy nothing from them until further notice." },
    { h: "Ports shut, roads barred", b: "{realm} has cut all commerce with {realm2}. Smugglers are said to be delighted." },
    { h: "Price of {good} leaps after embargo", b: "The ban on trade with {realm2} has emptied the stalls of {place}. Housewives grumble, smugglers grin." },
    { h: "Merchants protest the embargo", b: "The guilds of {realm} are furious at the ban on trade with {realm2}. Some openly call it ruinous folly.", req: { any: ["mercantile", "guilds"] } },
  ],
  diplomat_mission: [
    { h: "Envoys of {short} arrive in {short2}", b: "A delegation from {realm} was received at the court of {ruler2} today, bearing gifts and polite, carefully worded proposals." },
    { h: "{person} sent to the court of {short2}", b: "{ruler} has dispatched {person} to {realm2} to smooth relations. The envoy is said to be charming and very patient." },
    { h: "Diplomats seek friendship with {short2}", b: "An embassy from {realm} has reached {place}. Its purpose is officially courtesy; unofficially, everyone guesses otherwise." },
    { h: "Gifts and speeches in {short2}", b: "The ambassadors of {realm} presented {ruler2} with fine {good} and fine words. Relations between the realms are warming." },
    { h: "Embassy sets out for {short2}", b: "Wagons of gifts and a long train of clerks left for {realm2} this week. The court of {short} hopes for friendship, or at least fewer quarrels." },
    { h: "Guest-right honoured at foreign court", b: "Envoys of {realm}, famed for their own hospitality, were feasted for three days in {realm2}. Both sides parted with warm words.", req: "hospitable" },
  ],

  /* ---------------- rulers and courts ---------------- */
  royal_marriage: [
    { h: "Royal wedding unites {short} and {short2}", b: "The houses of {ruler} and {ruler2} are joined by marriage. Feasting has gone on for a week in {place}." },
    { h: "Bells ring for a royal marriage", b: "{person} of {realm} has wed into the ruling house of {realm2}. Diplomats call it a masterstroke; lovers call it a pity." },
    { h: "{heir} weds the house of {ruler2}", b: "The heir of {realm} was married today to a scion of {realm2}. The match promises peace and, some whisper, a future claim." },
    { h: "A match made in the council chamber", b: "Negotiated over many months, the marriage between the houses of {short} and {short2} was celebrated today amid great pomp." },
    { h: "Crowds cheer the royal couple", b: "Flower petals rained on the streets of {place} as the newlyweds of {realm} and {realm2} passed by in an open carriage." },
    { h: "Another crown secured at the altar", b: "True to its tradition, {realm} gains an ally through marriage rather than war. The court of {realm2} rejoices with it.", req: "dynastic", w: 2 },
    { h: "Temple blesses a royal union", b: "The high priests of {faith} married {person} to the house of {ruler2} beneath the great dome, before thousands.", req: { any: ["pious", "lavish"] } },
  ],
  ruler_died: [
    { h: "{ruler} is dead", b: "Black banners hang from every tower in {realm}. {ruler} passed away in {place}, and the realm holds its breath." },
    { h: "The realm mourns {ruler}", b: "After a reign remembered for good and ill, {ruler} has died. Crowds line the road for the funeral procession." },
    { h: "Death comes for {ruler} {epithet}", b: "The court physicians could do nothing more. {ruler} {epithet} died at dawn, surrounded by family and anxious courtiers." },
    { h: "Bells toll across {short}", b: "Word spread from {place} this morning: {ruler} is no more. Markets closed and people wept in the streets." },
    { h: "{title} {ruler} laid to rest", b: "A long reign has ended. The nobles of {realm} gathered to bury {ruler} and to size one another up." },
    { h: "{ruler} joins the ancestors", b: "The elders say {ruler} now sits among the honoured dead, watching over {realm}. Offerings pile up at the tomb.", req: { any: ["ancestor_bound", "faith:ancestors"] }, w: 2 },
    { h: "Pyres burn for a fallen chief", b: "The clans of {realm} gathered to send {ruler} to the sky on a great pyre. Horses were sacrificed and songs sung all night.", req: "tribal", w: 1.5 },
  ],
  ruler_abdicated: [
    { h: "{ruler} steps down", b: "In a surprise announcement, {ruler} has renounced the throne of {realm}. Courtiers scramble to learn what comes next." },
    { h: "Abdication shocks {short}", b: "Weary of rule, {ruler} laid the crown aside today at {place}. {heir} is expected to take up the burden." },
    { h: "{ruler} retires from public life", b: "Citing age and poor health, {ruler} has left the throne. Many suspect other reasons, but none say so aloud." },
    { h: "Crown set down in {place}", b: "Before the assembled court, {ruler} removed the crown and walked out. The hall stood in stunned silence." },
    { h: "{ruler} leaves the throne for the cloister", b: "Seeking peace in prayer, {ruler} has abdicated and entered a monastery of {faith}. The court is left to squabble.", req: "pious", w: 1.5 },
    { h: "Forced out, say the whispers", b: "Officially {ruler} chose to abdicate. Unofficially, the great houses of {realm} gave no choice at all.", req: { any: ["hierarchical", "gov:feudal"] } },
  ],
  succession: [
    { h: "{heir} inherits the throne of {short}", b: "The crown of {realm} passes peacefully to {heir}. The nobles have sworn their oaths, at least for now." },
    { h: "A new reign begins in {short}", b: "{heir} has taken up the rule of {realm}. Hopes are high, as they always are at the start." },
    { h: "The crown passes to {heir}", b: "With the old ruler gone, {heir} now sits on the throne. The first decrees are awaited with interest." },
    { h: "{heir} takes the reins of power", b: "Ministers and generals filed past {heir} today to pledge their service. The realm of {realm} has a new master." },
    { h: "Long live {heir}!", b: "Criers in {place} proclaimed {heir} the new ruler of {realm}. The taverns were full well past midnight." },
    { h: "Blood of the old line endures", b: "Once again the ancient dynasty holds {realm}. {heir} continues a line that has ruled for centuries.", req: "origin:old_dynasty", w: 2 },
  ],
  election: [
    { h: "{person} elected to lead {short}", b: "After days of debate and nights of bargaining, the council of {realm} has chosen {person} as its new {title}." },
    { h: "Votes counted, {person} prevails", b: "The electors of {realm} have spoken. {person} will serve as {title}, to cheers from some and grumbles from others." },
    { h: "New {title} chosen in {place}", b: "White smoke rose over {place} today: {person} has been elected to lead {realm}." },
    { h: "{short} picks {person}", b: "A narrow vote has made {person} the new {title} of {realm}. The losing faction has already begun plotting." },
    { h: "Council hall erupts at election result", b: "Few expected {person} to win, but the votes were cast and counted. {realm} has a new {title}." },
    { h: "Merchant houses crown their candidate", b: "The richest families of {realm} have made {person} their {title}. Few were surprised; fewer were consulted.", req: "gov:merchant", w: 2 },
    { h: "Great houses elect a new king", b: "The nobles of {realm} gathered to elect a monarch for life, and chose {person} after a week of feasting and bribery.", req: "gov:elective", w: 2 },
    { h: "Clans raise {person} on a shield", b: "By the ancient custom, the clan chiefs of {realm} lifted {person} on a shield and proclaimed a new {title}.", req: "tribal", w: 2 },
  ],
  succession_crisis: [
    { h: "No clear heir in {short}", b: "With {ruler} gone and no undisputed heir, the great houses of {realm} are raising their banners. Civil strife looms." },
    { h: "Rival claimants split {short}", b: "Two claimants now demand the crown of {realm}. The nobles are choosing sides and sharpening swords." },
    { h: "Throne of {short} stands empty", b: "Weeks have passed without a new ruler in {realm}. Factions meet in secret and the capital grows tense." },
    { h: "Succession thrown into chaos", b: "The will of the late ruler has been declared a forgery. {person} and {heir} both claim the throne of {realm}." },
    { h: "Crisis as lords refuse their oaths", b: "Half the nobility of {realm} will not kneel to {heir}. The realm teeters on the edge of civil war." },
    { h: "Omens muddle the succession", b: "The seers of {realm} cannot agree which claimant the signs favour, and each faction quotes a different prophecy.", req: { any: ["seers", "faith:stars"] }, w: 1.5 },
  ],
  coronation: [
    { h: "{ruler} crowned in splendour", b: "Before the great and the good of {realm}, {ruler} was crowned today in {place}. Coins were thrown to the crowds." },
    { h: "Coronation day in {place}", b: "Trumpets sounded as the crown was set on the head of {ruler}. The people of {realm} have a new sovereign." },
    { h: "Long live {title} {ruler}!", b: "The coronation of {ruler} was the grandest spectacle {place} has seen in a generation. Feasting continues." },
    { h: "{ruler} anointed and enthroned", b: "Oil, oaths and a very heavy crown: {ruler} is formally the ruler of {realm}. The first acts of the reign are awaited." },
    { h: "Crowds flock to see {ruler} crowned", b: "Pilgrims, peasants and princes packed the streets of {place} for the coronation. Pickpockets had their finest day in years." },
    { h: "Heavens bless the new ruler", b: "The priests of {faith} declared {ruler} chosen by the gods as the crown was set in place. The crowds fell to their knees.", req: { any: ["divine_right", "pious"] }, w: 2 },
    { h: "Gold and incense for {ruler}", b: "No expense was spared as {ruler} was crowned amid processions, choirs and clouds of incense. The treasury will feel it.", req: "lavish", w: 1.5 },
  ],
  new_ruler_trait: [
    { h: "{ruler} now called {epithet}", b: "Across {realm}, the people have begun calling their ruler {ruler} {epithet}. The name seems likely to stick." },
    { h: "A ruler earns a name", b: "Tavern talk in {place} has given {ruler} a new title: {epithet}. Historians will doubtless argue whether it was deserved." },
    { h: "They call {ruler} {epithet} now", b: "What began as a jest at court has spread to every market in {realm}. {ruler} {epithet} is how the chroniclers now write it." },
    { h: "The legend of {ruler} {epithet} grows", b: "Stories of the ruler's deeds travel far beyond {realm}. Foreign courts now speak of {ruler} {epithet} with interest." },
    { h: "{epithet}: the people have spoken", b: "No decree made it official, but the whole of {realm} agrees. From now on, {ruler} is {ruler} {epithet}." },
    { h: "Bards sing of {ruler} {epithet}", b: "The minstrels of {realm} have made new songs of their ruler, and in every one {ruler} is called {epithet}.", req: { any: ["martial", "artisans"] } },
  ],

  /* ---------------- unrest and upheaval ---------------- */
  revolt: [
    { h: "Revolt erupts in {place}", b: "Angry crowds have seized {place} and driven out the officials of {realm}. The rebels demand lower taxes and the heads of the collectors." },
    { h: "Peasants take up arms", b: "Pitchforks and scythes are raised across the countryside around {place}. {ruler} has sent soldiers to restore order." },
    { h: "Rebellion spreads in {short}", b: "Rebels have declared {place} free of the crown. {count} villages are said to have joined them." },
    { h: "{place} rises against {ruler}", b: "Barricades went up in the streets of {place} overnight. The garrison fled, and the rebel banner flies from the town hall." },
    { h: "Unrest boils over into revolt", b: "Long months of grievance ended in fire. The people of {place} have risen, and {realm} faces open rebellion." },
    { h: "Burghers defy the crown", b: "The guilds of {place} have locked their gates against the collectors of {realm} and armed their apprentices.", req: { any: ["urbane", "guilds"] } },
    { h: "Clans break from the confederacy", b: "Several clans near {place} have renounced their oaths to {ruler} and ridden off with their herds and spears.", req: "tribal" },
  ],
  revolution: [
    { h: "Revolution! {gov} overthrown", b: "In a single tumultuous season, {realm} has cast off its {gov}. A {gov2} now governs in its place." },
    { h: "The old order falls in {short}", b: "The {gov} of {realm} is no more. New leaders speak of freedom, justice and, above all, a {gov2}." },
    { h: "{short} remade as {gov2}", b: "Crowds tore down the old symbols of power in {place}. {realm} will henceforth be a {gov2}." },
    { h: "Palace stormed, power seized", b: "The rule of {ruler} is over. The victors in {place} have proclaimed a {gov2} and begun rewriting the laws." },
    { h: "A new government for {short}", b: "After months of turmoil, {realm} has abandoned its {gov}. Whether the new {gov2} will last is anyone's guess." },
    { h: "Generals seize control of {short}", b: "The army has marched on {place} and taken the reins of state. Soldiers now guard every ministry.", req: "gov:stratocracy", w: 2 },
    { h: "Free commune proclaimed", b: "No more lords, no more kings: the people of {realm} have declared themselves free and equal under the new {gov2}.", req: "gov:commune", w: 2 },
    { h: "Priests take the throne", b: "The temples of {faith} now rule {realm} directly. The old {gov} has been swept away in the name of heaven.", req: "gov:theocracy", w: 2 },
  ],
  rebels_crushed: [
    { h: "Rebellion crushed at {place}", b: "The soldiers of {realm} have retaken {place}. The rebel leaders are in chains, and the gibbets are busy." },
    { h: "Order restored in {place}", b: "After weeks of fighting, the revolt around {place} is over. {ruler} promises justice; the survivors fear it." },
    { h: "{commander} scatters the rebels", b: "Using {tactic}, {commander} broke the rebel army outside {place}. {casualties} are said to have fallen." },
    { h: "Revolt ends in blood", b: "The rebellion in {realm} has been put down. Heads now decorate the gates of {place}, a warning to others." },
    { h: "Rebels surrender, pardons offered", b: "The last holdouts at {place} laid down their arms. {ruler} has offered pardons to all but the ringleaders." },
    { h: "Harsh punishment for rebels", b: "Under the stern laws of {realm}, every captured rebel from {place} will face the executioner. The streets are silent.", req: { any: ["harsh_law", "autocracy"] }, w: 1.5 },
  ],
  independence: [
    { h: "{place} declares independence", b: "No longer a province of {realm2}, {place} is now the free realm of {realm}. Its people celebrate in the streets." },
    { h: "A new realm is born: {realm}", b: "After a long struggle, {realm} has broken free of {realm2}. Its founders speak proudly of liberty and self-rule." },
    { h: "{short} breaks free of {short2}", b: "The banners of {realm2} have been hauled down across {place}. {realm} now stands on its own." },
    { h: "Freedom for {short}!", b: "Crowds sang in {place} as the independence of {realm} was proclaimed. The court of {realm2} has yet to respond." },
    { h: "Map redrawn as {short} secedes", b: "Cartographers have a new line to draw: {realm} has left {realm2} for good, and made {place} its capital." },
    { h: "{people} win their own realm", b: "For generations the {people} lived under foreign rule. Now, with the birth of {realm}, they govern themselves." },
  ],
  unrest_rising: [
    { h: "Discontent grows in {place}", b: "Grumbling in the markets of {place} has turned to shouting. Officials of {realm} report posters mocking {ruler} on every wall." },
    { h: "Tensions rise across {short}", b: "Taxes, hunger and rumour are stirring the people of {realm}. Soldiers have been doubled at the gates of {place}." },
    { h: "Mobs gather in {place}", b: "Crowds clashed with the watch in {place} last night. Several were hurt, and the mood remains ugly." },
    { h: "Whispers of rebellion in {short}", b: "Secret meetings, burnt tax rolls and missing officials: the signs of unrest are everywhere in {realm}." },
    { h: "Taxes spark anger in {place}", b: "The latest levy has pushed the people of {place} too far. Collectors now travel with armed escorts." },
    { h: "Preachers rail against the court", b: "Wandering priests of {faith} are condemning the luxury of {ruler}'s court, and the crowds in {place} are listening.", req: { any: ["pious", "ascetic"] } },
  ],
  assassination: [
    { h: "{person} assassinated!", b: "{person} was struck down in {place} by a hidden blade. The killer escaped, and every court in the land is asking who paid." },
    { h: "Murder at the court of {short}", b: "Poison in a cup of wine has claimed the life of {person}. Guards and cooks alike are being questioned in {realm}." },
    { h: "Dagger in the dark claims {person}", b: "The body of {person} was found at dawn in {place}. Suspicion falls on agents of {realm2}, though nothing is proven." },
    { h: "Shock as {person} is slain", b: "An assassin reached {person} in broad daylight in {place}. {realm} is in uproar and the borders are closed." },
    { h: "Killer strikes in {place}", b: "{person} is dead, felled by an assassin's bolt. {ruler} has sworn to find the killer, however long it takes." },
    { h: "Spymasters suspected in {person}'s death", b: "The web of informants that {realm} maintains abroad is suddenly very quiet about the death of {person}.", req: "spy_network", w: 1.5 },
  ],
  spy_caught: [
    { h: "Spy of {short2} unmasked", b: "A servant in the palace of {realm} has been revealed as an agent of {realm2}. The court is in uproar." },
    { h: "Foreign agent seized in {place}", b: "Guards arrested a spy working for {realm2} in {place}. Coded letters were found sewn into the lining of a cloak." },
    { h: "{short} catches {short2} spying", b: "Envoys of {realm2} have been summoned to explain the agent caught in {realm}. They deny everything, as spies' masters do." },
    { h: "Treachery exposed at court", b: "A trusted clerk has confessed to selling secrets to {realm2}. {ruler} is said to be furious." },
    { h: "Informer's net snares a spy", b: "An agent of {realm2} was taken in {place} before any harm was done. Relations between the realms have cooled sharply." },
    { h: "Spymasters of {short} strike again", b: "The famed intelligencers of {realm} caught an agent of {realm2} within a week of arrival. They are rarely surprised.", req: "spy_network", w: 2 },
  ],
  tech_stolen: [
    { h: "Secrets of {invention} stolen", b: "Agents of {realm} have smuggled the secret of {invention} out of {realm2}. Its scholars are said to be livid." },
    { h: "{short} steals a march on {short2}", b: "Plans, notes and one kidnapped craftsman have brought the knowledge of {invention} from {realm2} to {realm}." },
    { h: "Stolen knowledge reaches {place}", b: "Workshops in {place} are suddenly producing wonders once known only in {realm2}. Nobody asks how." },
    { h: "Spies bring home {invention}", b: "What {realm2} guarded for years, {realm} now possesses. The theft of {invention} has shaken its rival's court." },
    { h: "Craft secret smuggled out of {short2}", b: "A guild of {realm2} has lost its most prized secret to spies from {realm}. The guildmasters are demanding revenge." },
    { h: "Scholars decipher stolen texts", b: "The learned of {realm} have translated manuscripts taken from {realm2} and mastered {invention} in a single season.", req: "scholarly" },
  ],
  treasury_crisis: [
    { h: "Treasury of {short} runs dry", b: "Clerks report that the coffers of {realm} are empty. Soldiers go unpaid and creditors circle the palace." },
    { h: "{ruler} cannot pay the bills", b: "The crown of {realm} has defaulted on its debts. Bankers in {place} are refusing any further loans." },
    { h: "Crown jewels pawned in {place}", b: "In a desperate bid to pay its armies, the court of {realm} has pawned its treasures. The people are scandalised." },
    { h: "Coin debased, prices soar", b: "The mint of {realm} is cutting copper into the silver. Merchants have noticed, and bread now costs double." },
    { h: "Financial ruin threatens {short}", b: "Debts, wars and extravagance have emptied the treasury of {realm}. New taxes are expected, and so is anger." },
    { h: "Mercenaries mutiny over pay", b: "The hired companies of {realm} have gone unpaid for months and now occupy {place} until they see gold.", req: "mercenaries", w: 2 },
    { h: "Merchant houses refuse new loans", b: "The great trading families who run {realm} have closed their purses. Even they, it seems, have limits.", req: "gov:merchant", w: 1.5 },
  ],

  /* ---------------- learning and building ---------------- */
  discovery: [
    { h: "{invention} discovered in {short}", b: "Scholars of {realm} have mastered {invention}. Craftsmen are already asking how it can be put to use." },
    { h: "Breakthrough in {field}", b: "Word from the workshops of {place}: {invention} is now within the reach of {realm}. The learned are jubilant." },
    { h: "{short} masters {invention}", b: "Years of patient work in {field} have borne fruit. {realm} now knows the secret of {invention}." },
    { h: "New learning spreads from {place}", b: "The discovery of {invention} in {place} is the talk of {realm}. Some call it a marvel; others call it trouble." },
    { h: "{person} unveils {invention}", b: "Before an astonished crowd in {place}, {person} demonstrated {invention}. Envoys of other realms took careful notes." },
    { h: "Academies celebrate {invention}", b: "The state-paid scholars of {realm} have justified their stipends at last: {invention} is theirs.", req: { any: ["academies", "scholarly"] }, w: 1.5 },
    { h: "Guild craftsmen perfect {invention}", b: "The master artisans of {realm} have brought {invention} from theory to practice. Their guilds will guard the secret closely.", req: { any: ["artisans", "guilds"] }, w: 1.5 },
    { h: "{users} unlock {invention}", b: "The {users} of {realm} have found a new use for their gifts in {invention}. Ordinary craftsmen fear for their trades.", req: { any: ["arcane", "gov:magocracy"] } },
  ],
  institution_founded: [
    { h: "{project} founded in {place}", b: "{ruler} has established {project} in {place}. It is hoped that it will serve {realm} for generations." },
    { h: "New institution opens its doors", b: "With great ceremony, {project} was founded today in {place}. The first members were sworn in before the court." },
    { h: "{short} establishes {project}", b: "By royal charter, {realm} has created {project}. Critics call it expensive; supporters call it overdue." },
    { h: "Charter signed for {project}", b: "Seals were pressed and speeches made in {place} as {project} came into being. Its founders dream of great things." },
    { h: "A new pillar for {short}", b: "The founding of {project} marks a turning point for {realm}, say its patrons. Doubters will be watching closely." },
    { h: "Learned body founded in {place}", b: "The scholars of {realm} now have a new home: {project}, founded in {place} and generously endowed.", req: "scholarly", w: 1.5 },
  ],
  project_started: [
    { h: "Work begins on {project}", b: "Masons and labourers have gathered at {place} to begin {project}. The work is expected to take years." },
    { h: "{ruler} lays the first stone", b: "With a silver trowel and much ceremony, {ruler} launched the building of {project} in {place}." },
    { h: "Great works planned in {place}", b: "{realm} has committed vast sums to {project}. Quarries and forests are being stripped to supply it." },
    { h: "Ground broken for {project}", b: "The first trenches have been dug at {place}. If all goes well, {project} will be the pride of {realm}." },
    { h: "{short} dreams big with {project}", b: "Architects of {realm} unveiled their plans for {project} today. Taxpayers were notably less excited." },
    { h: "Guilds win contracts for {project}", b: "The craft guilds of {realm} will build {project}, and have already set the prices to their liking.", req: "guilds" },
  ],
  project_completed: [
    { h: "{project} completed at last", b: "After years of toil, {project} stands finished in {place}. {ruler} opened it before cheering crowds." },
    { h: "{short} finishes {project}", b: "The final stone has been set. {project} now serves the people of {realm}, and its builders are finally paid." },
    { h: "Crowds admire the new {project}", b: "People came from all over {realm} to see {project}, finished this month in {place}." },
    { h: "Work done on {project}", b: "Scaffolding came down in {place} today, revealing {project} in all its glory. {realm} is justly proud." },
    { h: "{place} unveils {project}", b: "Banners, bands and a long speech by {ruler} marked the opening of {project}. The labourers were given a feast." },
    { h: "Craftsmen's masterpiece complete", b: "The master artisans of {realm} have finished {project}, and visitors say the detail of the work is breathtaking.", req: "artisans", w: 1.5 },
  ],
  monument_completed: [
    { h: "New monument rises in {place}", b: "{project} has been completed in {place}, a lasting testament to the glory of {realm}." },
    { h: "{project} unveiled to wonder", b: "The veil fell and the crowd gasped. {project} now stands over {place} for all ages to see." },
    { h: "{ruler} dedicates {project}", b: "Before the whole court, {ruler} dedicated {project} to the memory of the realm's great deeds." },
    { h: "Stone and glory in {place}", b: "{realm} has a new landmark. {project} towers over {place}, and pilgrims are already arriving." },
    { h: "A monument for the ages", b: "Travellers say {project} can be seen for miles around {place}. {realm} intends that it be remembered." },
    { h: "Temple of {faith} consecrated", b: "Priests sang for a day and a night as {project} was consecrated in {place}, the holiest work of {realm} in a generation.", req: "pious", w: 1.5 },
  ],
  wonder_completed: [
    { h: "A wonder of the world: {project}", b: "{realm} has completed {project} at {place}. Nothing like it has ever been built, and the whole world talks of it." },
    { h: "{project} stuns the known world", b: "Envoys from every court have come to gaze at {project}. {ruler} receives them with barely concealed pride." },
    { h: "Marvel completed in {place}", b: "After a generation of labour, {project} is finished. Poets of {realm} say it will outlast every kingdom." },
    { h: "{short} crowns its age with {project}", b: "The completion of {project} marks the high point of {realm}. Scholars already speak of this as a golden age." },
    { h: "Pilgrims flock to {project}", b: "Roads to {place} are crowded with travellers eager to see {project}, the greatest work of {realm}." },
    { h: "Golden age declared as {project} rises", b: "Gold leaf, marble and ten thousand lamps: {project} in {place} is as extravagant as it is magnificent.", req: "lavish" },
  ],
  great_scholar: [
    { h: "{person} dazzles the learned world", b: "A brilliant mind has risen in {realm}. {person}, a master of {field}, is sought after by every court." },
    { h: "Genius of {field} emerges in {place}", b: "Scholars in {place} speak with awe of {person}, whose ideas in {field} are overturning old certainties." },
    { h: "{person} hailed as the wonder of {short}", b: "Few have ever grasped {field} as {person} does. {ruler} has granted a generous stipend and a tower." },
    { h: "New star of learning in {short}", b: "Students travel from far realms to hear {person} lecture on {field}. The lecture halls of {place} overflow." },
    { h: "{person} rewrites the books on {field}", b: "A treatise by {person} has sent the scholars of {realm} into furious debate. Most agree it is a masterpiece." },
    { h: "Philosophers crown a new master", b: "The schools of {realm} have acknowledged {person} as the foremost thinker in {field} of this age.", req: { any: ["faith:philosophy", "scholarly"] }, w: 1.5 },
  ],
  great_commander: [
    { h: "{commander} wins renown", b: "Soldiers of {realm} speak the name of {commander} with reverence. Enemies speak it with fear." },
    { h: "The legend of {commander} grows", b: "Another victory, another song. {commander} has become the most celebrated soldier in {realm}." },
    { h: "{commander}, master of {tactic}", b: "Famous for {tactic}, {commander} is now studied by officers across the land. {ruler} showers the general with honours." },
    { h: "A hero rises in {short}", b: "Crowds follow {commander} through the streets of {place}. Some whisper the general would make a fine ruler." },
    { h: "{commander} feared on every border", b: "Enemy captains of {realm2} reportedly refuse battle whenever {commander} takes the field." },
    { h: "Warrior houses honour {commander}", b: "By the martial code of {realm}, {commander} has been granted the highest honours a soldier can earn.", req: { any: ["martial", "warrior_code"] }, w: 1.5 },
  ],
  road_built: [
    { h: "New road links {place} and {place2}", b: "Workers of {realm} have finished a road between {place} and {place2}. Merchants rejoice at shorter journeys." },
    { h: "Highway opens to {place2}", b: "A paved road now runs from {place} to {place2}. Couriers of {realm} can make the trip in half the time." },
    { h: "Road to {place} completed", b: "Stones laid, bridges built: the new road to {place} opens for travellers, traders and, of course, tax collectors." },
    { h: "Carts roll on the new road", b: "The first caravans have taken the new road between {place} and {place2}. Innkeepers along the way are hiring." },
    { h: "{short} paves the way to {place2}", b: "After two seasons of work, {realm} has opened a highway to {place2}. Soldiers and merchants alike will use it." },
    { h: "Milestones mark a new imperial road", b: "Engineers of {realm} have added another paved road to their network, complete with post-houses and milestones.", req: { any: ["great_roads", "gov:empire"] }, w: 2 },
  ],

  /* ---------------- towns ---------------- */
  town_grew: [
    { h: "{place} is booming", b: "New houses climb the hills around {place} as people pour in from the countryside. It is now counted among the larger towns of {realm}." },
    { h: "{place} grows into a {title}", b: "With new walls and a bustling market, {place} has become a proper {title}. Its citizens are very proud." },
    { h: "Crowds and commerce swell {place}", b: "Markets overflow and rents soar in {place}. The town has grown beyond anything its founders imagined." },
    { h: "{place} earns a new charter", b: "{ruler} has granted {place} the rights of a larger town. Bells rang and the burghers drank to their good fortune." },
    { h: "New walls for growing {place}", b: "The old walls of {place} can no longer hold its people. Masons are already marking out a wider circuit." },
    { h: "Trade makes {place} rich", b: "The merchants of {place} have grown so wealthy on {good} that the town now rivals the capital of {realm}.", req: "mercantile", w: 1.5 },
  ],
  town_declined: [
    { h: "Hard times in {place}", b: "Empty houses and shuttered shops line the streets of {place}. The town has lost much of its people and standing." },
    { h: "{place} fades", b: "Once proud, {place} is shrinking. Young people leave for other towns and the market shrinks each year." },
    { h: "{place} loses its charter", b: "Too small to justify its old rights, {place} has been demoted by the officials of {realm}. The townsfolk are bitter." },
    { h: "Grass grows in the streets of {place}", b: "War, hunger and hard luck have emptied {place}. Travellers remark on how quiet it has become." },
    { h: "Decline of {place} continues", b: "Another family packs its cart and leaves {place}. The town council of {realm} wonders what can be done." },
    { h: "Ancestral homes left behind", b: "Families of {place} weep at the tombs before departing. The elders say the ancestors will grieve for the dwindling town.", req: "ancestor_bound" },
  ],
  town_abandoned: [
    { h: "{place} abandoned", b: "The last inhabitants of {place} have left. Only crows and wind remain in what was once a living town of {realm}." },
    { h: "Ghost town: {place}", b: "Where once markets bustled, {place} now stands empty. Its people have scattered across {realm}." },
    { h: "{place} is no more", b: "The town of {place} has been deserted. Doors hang open and weeds creep across the square." },
    { h: "Last lamp goes out in {place}", b: "The final family left {place} this month. Travellers who pass through say the empty streets make them uneasy." },
    { h: "{place} lost to the wilds", b: "Forest and field are reclaiming {place}. Chroniclers of {realm} add another name to the list of lost towns." },
    { h: "Spirits of {place} left alone", b: "Before leaving, the people of {place} made offerings to the spirits of the land, begging forgiveness for going.", req: { any: ["faith:spirits", "forest_folk"] } },
  ],
  town_founded: [
    { h: "New town founded at {place}", b: "Settlers of {realm} have raised the first houses at {place}. A well has been dug and a market cross set up." },
    { h: "{place} rises from the wilderness", b: "Pioneers have cleared land and built homes at {place}. {ruler} has granted the new settlement a charter." },
    { h: "Settlers stake a claim at {place}", b: "A band of hopeful families from {realm} has founded {place}. Hard winters lie ahead, but spirits are high." },
    { h: "A town is born: {place}", b: "The newest settlement of {realm}, {place}, celebrated its founding with a feast and the blessing of the fields." },
    { h: "Pioneers build at {place}", b: "Timber walls and a small chapel now stand where wilderness was. {place} is the latest town of {realm}." },
    { h: "Harbour town founded at {place}", b: "Fishermen and traders of {realm} have founded {place} on a sheltered bay. Its first boats are already at sea.", req: "seafaring" },
    { h: "Border fort grows into {place}", b: "What began as a frontier fort of {realm} has become a proper town. Its walls remain, and so does its watchfulness.", req: { any: ["frontier_forts", "frontier"] } },
  ],

  /* ---------------- disasters ---------------- */
  plague: [
    { h: "Plague strikes {place}", b: "A terrible sickness has broken out in {place}. {count} are dead and the gates are shut to all travellers." },
    { h: "Pestilence spreads across {short}", b: "Fever and black boils are spreading through {realm}. Physicians are helpless and the graveyards are full." },
    { h: "Death stalks the streets of {place}", b: "Carts collect the dead each morning in {place}. Those who can flee are fleeing, carrying the sickness with them." },
    { h: "Sickness grips {short}", b: "A wasting plague has taken hold in {realm}. {ruler} has ordered the ports closed and the sick quarantined." },
    { h: "Black bells toll in {place}", b: "The plague has come to {place}. Doors are marked with chalk, and whole families lie silent inside." },
    { h: "Priests blame sin for the plague", b: "The clergy of {faith} call the pestilence in {place} a punishment from heaven and lead penitent processions through the streets.", req: "pious", w: 1.5 },
    { h: "Physicians fight plague in {place}", b: "The scholars of {realm} have set up hospitals and quarantines in {place}, and the death toll is lower than feared.", req: "scholarly" },
  ],
  famine: [
    { h: "Famine grips {short}", b: "The harvest has failed across {realm}. Bread is scarce, and the poor of {place} are eating grass and bark." },
    { h: "Hunger stalks {place}", b: "Granaries in {place} are empty. {ruler} has promised relief, but carts of grain are slow to come." },
    { h: "Harvest fails, hunger follows", b: "Blight and drought have ruined the crops of {realm}. The price of bread has tripled and riots are feared." },
    { h: "Starvation in the countryside", b: "Villages around {place} have been abandoned as families search for food. The chroniclers call this the hungry year." },
    { h: "Bread riots in {place}", b: "Starving crowds stormed the granaries of {place}. The guards did not stop them; they were hungry too." },
    { h: "Herds perish on the steppe", b: "A harsh winter has killed the herds of {realm}. The clans face hunger unlike any in living memory.", req: { any: ["nomadic", "horse_lords"] }, w: 2 },
    { h: "Merchants import grain to {place}", b: "The trading houses of {realm} have shipped grain from abroad, at a price, to feed starving {place}.", req: "mercantile" },
  ],
  earthquake: [
    { h: "Earthquake shakes {place}", b: "The ground heaved beneath {place} before dawn. Houses collapsed and {count} are feared dead." },
    { h: "Disaster in {place}: the earth moves", b: "A mighty tremor has struck {realm}. Towers fell in {place} and the survivors are digging with bare hands." },
    { h: "{place} in ruins after quake", b: "Few buildings stand in {place} after the earthquake. {ruler} has sent soldiers and supplies." },
    { h: "Ground splits near {place}", b: "A great crack has opened in the land near {place}. Wells ran dry and temples cracked in the tremor." },
    { h: "The earth trembles across {short}", b: "From {place} to the borders, people felt the shaking. The damage is still being counted." },
    { h: "Mountain holds shaken by quake", b: "Tunnels collapsed and halls cracked as an earthquake rolled through the mountains of {realm}. Miners are still trapped.", req: "mountain_folk" },
    { h: "Seers had warned of the quake", b: "Oracles of {realm} foretold the tremor that shattered {place}. Now everyone wants to know what else they have seen.", req: "seers" },
  ],

  /* ---------------- faith and the uncanny ---------------- */
  heresy: [
    { h: "New sect spreads in {place}", b: "Preachers of a strange new doctrine are drawing crowds in {place}. The priests of {realm} call it heresy." },
    { h: "Heresy troubles {short}", b: "The followers of {faith} are multiplying across {realm}. Traditional clergy demand that {ruler} act." },
    { h: "{faith} gains converts in {place}", b: "Whole villages around {place} have embraced {faith}. Old shrines are being quietly abandoned." },
    { h: "Preachers of {faith} arrive", b: "Wandering missionaries of {faith} have reached {realm}. Many people listen; some listen very closely indeed." },
    { h: "Schism splits the faithful", b: "A new sect has broken from the old faith in {realm}. Brothers argue at table and neighbours stop speaking." },
    { h: "Zealots burn heretic texts", b: "Enraged by the spread of {faith}, the zealous clergy of {realm} have lit bonfires of forbidden books in {place}.", req: "zealous", w: 2 },
    { h: "Tolerant court shrugs at new sect", b: "{ruler} has declined to persecute the followers of {faith}. In {realm}, it seems, belief is a private matter.", req: "tolerant", w: 1.5 },
  ],
  titan_rampage: [
    { h: "{titan} rampages near {place}", b: "The titan {titan} has awoken and torn through the lands around {place}. Villages lie flattened in its wake." },
    { h: "The earth shakes: {titan} walks", b: "Farmers near {place} fled as {titan} strode across their fields. {count} homes were destroyed." },
    { h: "Titan attack devastates {place}", b: "Nothing could stand before {titan}. {place} has been reduced to rubble, and survivors speak of its terrible roar." },
    { h: "{titan} on the move", b: "Scouts report that {titan} is wandering toward {place}. The people of {realm} pray it will turn aside." },
    { h: "Ruin in the wake of {titan}", b: "Rivers diverted, forests crushed, towns shattered: {titan} has passed through {realm}, and thousands have lost their homes." },
    { h: "Faithful rejoice as {titan} walks", b: "While others flee, the titan-worshippers of {realm} follow in the footsteps of {titan}, singing its praises.", req: { any: ["faith:titan", "titan_touched"] }, w: 2 },
    { h: "Titan-slayers ride out", b: "The warriors of {realm}, heirs of those who once felled a titan, have ridden out to face {titan} near {place}.", req: "origin:titan_slayers", w: 2 },
  ],
  mystery_stirs: [
    { h: "Strange lights at {site}", b: "Villagers near {site} report lights and voices there at night. The scholars of {realm} are intrigued." },
    { h: "Trouble near {site}", b: "Animals have fled and wells have gone sour near {site}. Locals believe whatever lies there is waking up." },
    { h: "Omens over {site}", b: "A red moon hung over {site} for three nights. Travellers now give the place a wide berth." },
    { h: "Mystery deepens at {site}", b: "An expedition from {place} came back from {site} with half its members missing. The survivors cannot say clearly what happened." },
    { h: "Whispers from {site}", b: "Shepherds near {site} swear they heard singing from beneath the earth. The priests of {realm} are not amused." },
    { h: "Seers dream of {site}", b: "Every oracle in {realm} dreamed of {site} on the same night. None will say what they saw.", req: { any: ["seers", "faith:stars"] }, w: 2 },
    { h: "{users} flock to {site}", b: "The {users} of {realm} have sensed a surge of {power} at {site}. Several have already gone to investigate.", req: "arcane", w: 1.5 },
  ],

  /* ---------------- celebrations ---------------- */
  festival: [
    { h: "Great feast held in {place}", b: "Tables groaned under roast meat and wine as {ruler} hosted a great festival in {place}. Nobody went hungry, for once." },
    { h: "{place} celebrates", b: "Music, dancing and fireworks filled the streets of {place}. The people of {realm} needed something to cheer about." },
    { h: "Festival draws crowds to {place}", b: "Travellers from all corners of {realm} came to {place} for the festival. The inns are full and so are the purses." },
    { h: "Merriment across {short}", b: "By order of {ruler}, every town in {realm} held a day of feasting. Taverns stayed open until dawn." },
    { h: "Lanterns light the night in {place}", b: "Thousands of lanterns rose over {place} as the people of {realm} marked the festival. Even the guards joined the dancing." },
    { h: "Holy days observed in {place}", b: "Processions, prayers and feasts in honour of {faith} filled {place} for a week of devout celebration.", req: "pious", w: 1.5 },
    { h: "Horse races crown the festival", b: "The riders of {realm} gathered for great races and games. The winner was given a herd of the finest horses.", req: "horse_lords", w: 2 },
    { h: "Guests from afar feasted", b: "True to their reputation, the people of {realm} opened their doors to every traveller during the festival in {place}.", req: "hospitable", w: 1.5 },
  ],
};
