// Technology and learning: fields of knowledge, how cultures bend them, and the inventions,
// institutions and scholars a realm can produce.
//   FIELDS:       { id, n, d }  the twelve fields of knowledge.
//   FIELD_BIAS:   { tag, fields: { fieldId: +/-number } }  a realm with `tag` gets these level shifts.
//   INVENTIONS:   { id, n, field, level 1..5, d, req?, not?, mods?, w? }  level 1 = early bronze/iron age,
//                 3 = high medieval, 5 = early renaissance / gunpowder or equivalent high magic.
//                 req/not/mods use the rules.js condition format (tag, "!tag", [all], {any}, {not}).
//   INSTITUTIONS: { n, field, req?, d }  name templates; slots {capital} {short} {people} {deity} {ruler}
//                 (and the power words {power} {user} {users}).
//   SCHOLAR_ROLES / DISCOVERY_TEXT: flavour; DISCOVERY_TEXT slots {scholar} {capital} {invention} {field}.
//                 Roles are picked unconditionally, so they name no ley/rift trade.
//   Ley content that a magic:high/arcane route could reach also needs "default:power" (no premise
//   replaces the ley lines); rift content follows near:rift, which only exists under default:cosmos.

export const FIELDS = [
  { id: "agriculture", n: "Agriculture", d: "Fields, herds, irrigation and the slow craft of feeding more mouths from the same soil." },
  { id: "metallurgy", n: "Metallurgy", d: "Mining, smelting and smithing, from the first bronze to the finest tempered steel." },
  { id: "engineering", n: "Engineering", d: "Machines, mills, bridges and siegecraft: making wood, rope and water do work." },
  { id: "architecture", n: "Architecture", d: "Walls, vaults, towers and whole cities raised in stone, brick and timber." },
  { id: "navigation", n: "Navigation", d: "Ships, charts and the art of finding a way across open water and trackless land." },
  { id: "medicine", n: "Medicine", d: "Herbs, surgery and the long argument over what the body is and why it fails." },
  { id: "astronomy", n: "Astronomy", d: "Watching the sky, keeping calendars and reading fate or reason in the stars." },
  { id: "writing", n: "Letters", d: "Scripts, records, ledgers and libraries: the memory of a people kept outside their heads." },
  { id: "warfare", n: "Warfare", d: "Drill, arms, armour and the organisation of violence on a large scale." },
  { id: "arcana", n: "Arcana", d: "The study of magic as a discipline, with rules, schools and dangerous experiments." },
  { id: "alchemy", n: "Alchemy", d: "Distilling, refining and transmuting substances, halfway between the forge and the temple." },
  { id: "natural_philosophy", n: "Natural Philosophy", d: "Asking why things fall, burn and grow, and testing the answers against the world." },
];

export const FIELD_BIAS = [
  // culture traits
  { tag: "seafaring", fields: { navigation: 2, astronomy: 0.5, engineering: 0.5 } },
  { tag: "horse_lords", fields: { warfare: 1.5, agriculture: -0.5, architecture: -1 } },
  { tag: "mountain_folk", fields: { metallurgy: 2, architecture: 1, navigation: -1 } },
  { tag: "forest_folk", fields: { medicine: 1, agriculture: -0.5, architecture: -0.5 } },
  { tag: "desert_wanderers", fields: { astronomy: 1.5, navigation: 1, agriculture: -1 } },
  { tag: "river_folk", fields: { agriculture: 1.5, engineering: 1 } },
  { tag: "nomadic", fields: { architecture: -1.5, agriculture: -1, writing: -0.5, warfare: 1 } },
  { tag: "urbane", fields: { architecture: 1, writing: 1, medicine: 0.5 } },
  { tag: "martial", fields: { warfare: 2, metallurgy: 0.5, natural_philosophy: -0.5 } },
  { tag: "mercantile", fields: { navigation: 1, writing: 1, engineering: 0.5 } },
  { tag: "scholarly", fields: { writing: 1.5, astronomy: 1, natural_philosophy: 1.5, medicine: 0.5 } },
  { tag: "pious", fields: { architecture: 1, writing: 0.5, natural_philosophy: -1 } },
  { tag: "artisans", fields: { metallurgy: 1, engineering: 1, alchemy: 0.5 } },
  { tag: "insular", fields: { navigation: -1, natural_philosophy: -0.5 } },
  { tag: "hospitable", fields: { medicine: 0.5, writing: 0.5 } },
  { tag: "hierarchical", fields: { architecture: 0.5, writing: 0.5, natural_philosophy: -0.5 } },
  { tag: "egalitarian", fields: { agriculture: 0.5, natural_philosophy: 0.5 } },
  { tag: "ancestor_bound", fields: { writing: 1, natural_philosophy: -0.5 } },
  { tag: "beast_tamers", fields: { warfare: 1, medicine: 0.5, agriculture: 0.5 } },
  { tag: "titan_touched", fields: { metallurgy: 0.5, alchemy: 1, medicine: 0.5 } },
  { tag: "arcane", fields: { arcana: 2.5, alchemy: 1 } },
  { tag: "seers", fields: { astronomy: 1.5, arcana: 1 } },
  // faiths and doctrines
  { tag: "faith:stars", fields: { astronomy: 2, navigation: 0.5 } },
  { tag: "faith:sun", fields: { astronomy: 1, architecture: 0.5 } },
  { tag: "faith:sea", fields: { navigation: 1.5 } },
  { tag: "faith:ley", fields: { arcana: 2 } },
  { tag: "faith:philosophy", fields: { natural_philosophy: 2, writing: 1, medicine: 0.5 } },
  { tag: "faith:ancestors", fields: { writing: 0.5, architecture: 0.5 } },
  { tag: "faith:titan", fields: { alchemy: 0.5, natural_philosophy: -0.5 } },
  { tag: "faith:void", fields: { arcana: 1, medicine: -0.5 } },
  { tag: "zealous", fields: { natural_philosophy: -1, arcana: -0.5 } },
  { tag: "tolerant", fields: { natural_philosophy: 0.5, medicine: 0.5 } },
  { tag: "ascetic", fields: { medicine: 0.5, architecture: -0.5 } },
  { tag: "lavish", fields: { architecture: 1.5 } },
  { tag: "mystic", fields: { arcana: 1, alchemy: 0.5 } },
  // governments and ideals
  { tag: "gov:magocracy", fields: { arcana: 2, alchemy: 1 } },
  { tag: "gov:stratocracy", fields: { warfare: 2, engineering: 0.5 } },
  { tag: "gov:merchant", fields: { navigation: 1, writing: 1 } },
  { tag: "gov:empire", fields: { architecture: 1, engineering: 1, writing: 0.5 } },
  { tag: "gov:tribal", fields: { writing: -1, architecture: -0.5 } },
  { tag: "academies", fields: { natural_philosophy: 1, writing: 1, medicine: 0.5 } },
  { tag: "guilds", fields: { metallurgy: 1, engineering: 0.5 } },
  { tag: "navy", fields: { navigation: 1.5, engineering: 0.5 } },
  { tag: "standing_army", fields: { warfare: 1.5 } },
  { tag: "arcane_council", fields: { arcana: 1.5 } },
  { tag: "great_roads", fields: { engineering: 1, architecture: 0.5 } },
  { tag: "frontier_forts", fields: { architecture: 1, warfare: 0.5 } },
  { tag: "isolation", fields: { navigation: -1, natural_philosophy: -0.5 } },
  // land and surroundings
  { tag: "island", fields: { navigation: 1.5, agriculture: -0.5 } },
  { tag: "river", fields: { agriculture: 1 } },
  { tag: "desert", fields: { astronomy: 0.5, agriculture: -1 } },
  { tag: "magic:high", fields: { arcana: 1.5, alchemy: 0.5 } },
  { tag: "magic:low", fields: { arcana: -1.5, natural_philosophy: 1, engineering: 0.5 } },
  { tag: "near:ley", fields: { arcana: 1 } },
  { tag: "near:ruins", fields: { writing: 0.5, architecture: 0.5 } },
  { tag: "atwar", fields: { warfare: 1, medicine: 0.5 } },
];

export const INVENTIONS = [
  // --- agriculture ---
  { id: "irrigation_canals", n: "Irrigation canals", field: "agriculture", level: 1, d: "Ditches and sluices lead river water into the fields, turning a flood-plain into a granary that feeds towns.", w: 1.5, mods: [["river", 3]] },
  { id: "ox_plough", n: "Ox-drawn plough", field: "agriculture", level: 1, d: "A heavy wooden plough behind a yoke of oxen breaks soil that hoes could only scratch." },
  { id: "terrace_farming", n: "Terrace farming", field: "agriculture", level: 2, d: "Hillsides are stepped into stone-walled terraces, holding soil and water where only goats once grazed.", req: { any: ["mountain", "hills", "mountain_folk"] } },
  { id: "crop_rotation", n: "Three-field rotation", field: "agriculture", level: 2, d: "Fields rest in turn and beans follow wheat, so the land gives more each year instead of less." },
  { id: "horse_collar", n: "Padded horse collar", field: "agriculture", level: 3, d: "A collar that does not choke the horse lets it pull a plough twice as fast as any ox.", mods: [["horse_lords", 2]] },
  { id: "water_wheel_mill", n: "Water-driven gristmill", field: "agriculture", level: 3, d: "River-turned millstones grind a village's grain in a day, freeing hands that once worked the quern." },
  { id: "floating_gardens", n: "Floating gardens", field: "agriculture", level: 3, d: "Rafts of reed and silt anchored in lakes and marshes grow vegetables year-round above the water.", req: { any: ["marsh", "river_folk"] } },
  { id: "selective_breeding", n: "Stud books", field: "agriculture", level: 4, d: "Careful records of sires and dams produce heavier cattle, woollier sheep and faster horses within a few generations." },
  { id: "beast_ploughs", n: "Beast-drawn ploughs", field: "agriculture", level: 3, d: "Tamed monsters drag ploughs through roots and rock that would break a team of oxen.", req: { any: ["beast_tamers", "origin:beast_bond"] } },
  { id: "ley_blessed_fields", n: "Ley-furrowed fields", field: "agriculture", level: 4, d: "Furrows cut along ley lines yield two harvests a year, though the grain tastes faintly of copper.", req: { any: ["near:ley", "faith:ley"] } },
  { id: "polder_dykes", n: "Polders and dykes", field: "agriculture", level: 5, d: "Wind-pumped dykes reclaim farmland from the sea and marsh, one grey field at a time.", req: { any: ["coastal", "marsh"] } },
  { id: "seed_drill", n: "Seed drill", field: "agriculture", level: 5, d: "A wheeled drill sows seed in straight, even rows, wasting little and doubling the harvest of careful farmers." },

  // --- metallurgy ---
  { id: "bronze_casting", n: "Bronze casting", field: "metallurgy", level: 1, d: "Copper and tin melted together and poured into clay moulds make blades, cauldrons and temple bells." },
  { id: "bloomery_iron", n: "Bloomery iron", field: "metallurgy", level: 1, d: "Charcoal fires coax spongy iron from bog ore, cheaper than bronze and hammered into tools for everyone." },
  { id: "pattern_welding", n: "Pattern welding", field: "metallurgy", level: 2, d: "Twisted rods of iron and steel forged together give blades a serpent-skin sheen and a springy edge." },
  { id: "deep_shaft_mining", n: "Deep shaft mining", field: "metallurgy", level: 2, d: "Timbered shafts and bucket-chains reach veins far beneath the hills, and miners become a caste of their own.", req: { any: ["mountain", "hills", "mountain_folk"] } },
  { id: "crucible_steel", n: "Crucible steel", field: "metallurgy", level: 3, d: "Sealed clay crucibles yield watered steel so fine that foreign princes pay its weight in silver.", mods: [["desert", 2], ["artisans", 2]] },
  { id: "blast_furnace", n: "Water-powered bellows", field: "metallurgy", level: 4, d: "Waterwheels drive great bellows, and furnaces roar hot enough to pour liquid iron like soup." },
  { id: "titanbone_alloy", n: "Titan-bone alloy", field: "metallurgy", level: 3, d: "Powdered titan bone folded into the steel makes blades that never quite cool and never quite dull.", req: { any: ["near:titan", "titan_touched", "origin:titan_slayers"] } },
  { id: "skyiron_forging", n: "Star-iron forging", field: "metallurgy", level: 3, d: "Iron from fallen stars is worked cold under chant, and holds an edge that cuts ordinary steel.", req: { any: ["near:mystery", "faith:stars"] } },
  { id: "rune_quenching", n: "Rune quenching", field: "metallurgy", level: 4, d: "Blades quenched in water drawn from a ley spring keep the runes cut into them glowing for a lifetime.", req: [{ any: ["near:ley", "arcane", "magic:high"] }, "default:power"] },
  { id: "cast_cannon", n: "Bronze cannon founding", field: "metallurgy", level: 5, d: "Bell-founders learn to cast great bronze tubes that can take the kick of a powder charge without bursting." },
  { id: "rolling_mill", n: "Rolling mill", field: "metallurgy", level: 5, d: "Heavy rollers press metal into even sheets and rods, making armour plate and wire cheap and plentiful." },

  // --- engineering ---
  { id: "lever_and_pulley", n: "Block and tackle", field: "engineering", level: 1, d: "Ropes run through pulleys let a dozen labourers raise stones that once needed a hundred." },
  { id: "shaduf", n: "Well sweeps", field: "engineering", level: 1, d: "A counterweighted pole lifts water from wells and rivers, one bucket at a time, from dawn until dusk." },
  { id: "arched_bridge", n: "Stone arch bridges", field: "engineering", level: 2, d: "Keystone arches span rivers that were once crossed only by ferry, and trade routes bend to meet them." },
  { id: "torsion_catapult", n: "Torsion engines", field: "engineering", level: 2, d: "Twisted skeins of sinew hurl stones and bolts farther than any bow, and walls no longer guarantee safety." },
  { id: "aqueducts", n: "Aqueducts", field: "engineering", level: 3, d: "Channels carried on arches and through tunnels bring clean mountain water into the heart of the capital.", mods: [["gov:empire", 2], ["urbane", 1.5]] },
  { id: "trebuchet", n: "Counterweight trebuchet", field: "engineering", level: 3, d: "A swinging arm with a box of earth throws boulders that crack curtain walls within a week of siege." },
  { id: "windmill", n: "Windmills", field: "engineering", level: 3, d: "Canvas sails on a turning cap grind grain and pump water where no river runs fast enough." },
  { id: "mechanical_clock", n: "Escapement clock", field: "engineering", level: 4, d: "A weight-driven clock in the town tower strikes the hours, and merchants begin to reckon time as money." },
  { id: "canal_locks", n: "Pound locks", field: "engineering", level: 4, d: "Gated chambers raise and lower barges between levels, turning rivers and canals into one great road.", req: { any: ["river", "river_folk", "great_roads"] } },
  { id: "titan_harness", n: "Titan harness", field: "engineering", level: 4, d: "Chains and cranes the size of towers bind a sleeping titan, and engineers study how to make it walk where they want.", req: { any: ["origin:titan_heralds", "faith:titan", "titan_touched"] } },
  { id: "ley_engine", n: "Ley engine", field: "engineering", level: 5, d: "A brass mechanism draws current from a ley line and turns wheels without wind, water or muscle.", req: [{ any: ["near:ley", "faith:ley", "gov:magocracy"] }, "default:power"] },
  { id: "printing_press", n: "Printing press", field: "engineering", level: 5, d: "Movable metal type and a screw press turn out a hundred pages an hour, and pamphlets outrun preachers." },

  // --- architecture ---
  { id: "mudbrick", n: "Fired brick", field: "architecture", level: 1, d: "Kiln-fired bricks outlast sun-dried mud, and the first walls of lasting towns rise from them." },
  { id: "palisade_forts", n: "Earth-and-timber forts", field: "architecture", level: 1, d: "Ditches, ramparts and sharpened stakes turn a hilltop into a refuge no raiding band can take quickly." },
  { id: "ashlar_masonry", n: "Ashlar masonry", field: "architecture", level: 2, d: "Stones cut square and fitted without mortar make temples and walls that shrug off centuries." },
  { id: "concrete", n: "Lime concrete", field: "architecture", level: 2, d: "Lime, volcanic ash and rubble set into stone underwater, making harbours, domes and foundations possible.", mods: [["near:volcano", 3]] },
  { id: "curtain_walls", n: "Curtain walls and towers", field: "architecture", level: 3, d: "Tall stone walls between round towers give defenders crossing fire on anyone who reaches the ditch." },
  { id: "rib_vault", n: "Rib vaults and buttresses", field: "architecture", level: 3, d: "Pointed arches and flying buttresses lift cathedral roofs into the sky and fill walls with coloured glass.", mods: [["pious", 2], ["lavish", 2]] },
  { id: "cliff_cities", n: "Cliff-carved halls", field: "architecture", level: 3, d: "Whole towns carved into living rock, cool in summer and all but impossible to besiege.", req: { any: ["mountain", "mountain_folk", "origin:mountain_hold"] } },
  { id: "stilt_towns", n: "Stilt towns", field: "architecture", level: 2, d: "Houses and walkways raised on piles over water keep towns dry through flood and tide.", req: { any: ["marsh", "river_folk", "jungle", "coastal"] } },
  { id: "great_dome", n: "Great domes", field: "architecture", level: 4, d: "Masons master the dome on pendentives, and the capital gains a roof that seems to float on light." },
  { id: "star_fort", n: "Star forts", field: "architecture", level: 5, d: "Low, angled bastions of packed earth and brick deflect cannonballs and leave attackers no blind spot." },
  { id: "titanbone_halls", n: "Titan-bone halls", field: "architecture", level: 3, d: "Ribs of a dead titan serve as the rafters of a longhall big enough to hold a whole clan.", req: { any: ["near:titan", "origin:titan_slayers"] } },
  { id: "floating_foundations", n: "Floating foundations", field: "architecture", level: 5, d: "Stones cut from the drifting isles are set into towers that hang a hand's breadth above the ground.", req: { any: ["near:floating_isles", "premise:strewn_sky", ["magic:high", "default:power"]] }, w: 0.5 },

  // --- navigation ---
  { id: "dugout_coasting", n: "Plank-built coasters", field: "navigation", level: 1, d: "Sewn-plank boats hug the shore from headland to headland, carrying trade and raiders alike.", req: { any: ["coastal", "river"] } },
  { id: "square_sail", n: "Square sails", field: "navigation", level: 1, d: "A single woollen sail carries ships before the wind, letting crews rest their oars on long crossings.", req: { any: ["coastal", "river"] } },
  { id: "star_path_chants", n: "Star-path chants", field: "navigation", level: 2, d: "Navigators memorise songs listing which stars rise over which islands, and open ocean becomes a map.", req: { any: ["seafaring", "island", "faith:stars"] } },
  { id: "caravan_stars", n: "Desert star-reckoning", field: "navigation", level: 2, d: "Caravan masters steer across sand seas by the stars and the lie of the dunes, never losing a well.", req: { any: ["desert", "desert_wanderers"] } },
  { id: "stern_rudder", n: "Stern rudder", field: "navigation", level: 3, d: "A hinged rudder on the sternpost steers larger, taller hulls than a steering oar ever could.", req: "coastal" },
  { id: "lodestone_compass", n: "Lodestone compass", field: "navigation", level: 3, d: "A magnetised needle floating in a bowl points north through fog and overcast, and winter sailing begins." },
  { id: "astrolabe", n: "Mariner's astrolabe", field: "navigation", level: 4, d: "A brass ring sighted on the sun or pole star gives a ship its latitude to within a day's sail.", req: { any: ["seafaring", "faith:stars", "desert_wanderers", "scholarly"] } },
  { id: "portolan_charts", n: "Portolan charts", field: "navigation", level: 4, d: "Charts criss-crossed with compass lines let pilots plot a course between any two harbours they have never seen.", req: { any: ["coastal", "mercantile"] } },
  { id: "lateen_carrack", n: "Ocean carracks", field: "navigation", level: 5, d: "Tall three-masted ships mixing square and lateen sails can beat against the wind and cross unknown seas.", req: "coastal" },
  { id: "storm_glass", n: "Storm glass", field: "navigation", level: 4, d: "A sealed vial of storm-water clouds a day before a storm, and captains who carry one lose fewer ships.", req: { any: ["near:rift", "faith:sea", "arcane"] } },
  { id: "sky_whale_lines", n: "Sky-whale towlines", field: "navigation", level: 5, d: "Harnessed sky whales tow gondolas above the clouds, carrying mail and nobles across mountains in days.", req: { any: ["beast_tamers", "origin:beast_bond"] }, w: 0.4 },
  { id: "ley_lodestone", n: "Ley lodestone", field: "navigation", level: 4, d: "A needle cut from ley-crystal points along the nearest ley line, guiding travellers from nexus to nexus.", req: { any: ["near:ley", "faith:ley"] } },

  // --- medicine ---
  { id: "herbals", n: "Herbals", field: "medicine", level: 1, d: "Wise women and temple healers record which roots stop fevers and which leaves close wounds." },
  { id: "bone_setting", n: "Splints and bone-setting", field: "medicine", level: 1, d: "Broken limbs set straight and bound in splints heal clean, and cripples become rarer in every village." },
  { id: "wine_wound_washing", n: "Washing wounds in wine", field: "medicine", level: 2, d: "Army surgeons find that wounds washed in strong wine and bound clean fester far less often.", mods: [["martial", 2]] },
  { id: "quarantine", n: "Quarantine", field: "medicine", level: 3, d: "Ships and caravans from plague ports wait forty days at anchor, and the next great sickness is kept outside the walls.", mods: [["has:port", 2]] },
  { id: "hospitals", n: "Public infirmaries", field: "medicine", level: 3, d: "Temple wards take in the sick poor, and physicians learn from seeing a hundred cases instead of one." },
  { id: "anatomy_theatres", n: "Anatomical dissection", field: "medicine", level: 4, d: "Physicians open the bodies of hanged criminals before students, and old errors about the body die quickly.", not: "zealous" },
  { id: "inoculation", n: "Variolation", field: "medicine", level: 5, d: "Scratching pus from a mild case into healthy skin spares whole towns from the pox, to the horror of the priests." },
  { id: "spectacles", n: "Ground-glass spectacles", field: "medicine", level: 4, d: "Lenses in wire frames let ageing scribes and jewellers keep working for another twenty years." },
  { id: "beast_venom_cures", n: "Venom antidotes", field: "medicine", level: 3, d: "Healers milk captive monsters and learn to turn their venoms into cures for the stings of their wild kin.", req: { any: ["near:beasts", "beast_tamers"] } },
  { id: "titan_marrow_tonic", n: "Titan-marrow tonic", field: "medicine", level: 4, d: "A tonic of titan marrow knits bones in days, though those who drink it too often begin to dream of mountains.", req: { any: ["near:titan", "titan_touched", "faith:titan"] } },
  { id: "laying_on_hands", n: "Ordered healing rites", field: "medicine", level: 3, d: "Priests codify healing prayers into drilled rites that work more often than they fail.", req: { any: ["organised", "pious"] }, mods: [["magic:high", 2]] },
  { id: "ley_surgery", n: "Ley-sleep surgery", field: "medicine", level: 5, d: "Patients laid on a ley nexus fall into a painless sleep, letting surgeons attempt what was once certain death.", req: [{ any: ["near:ley", "faith:ley", "arcane"] }, "default:power"] },

  // --- astronomy ---
  { id: "lunar_calendar", n: "Lunar calendar", field: "astronomy", level: 1, d: "Priests count the moons to fix feast days and planting, and whoever keeps the calendar keeps power." },
  { id: "solar_alignments", n: "Solstice alignments", field: "astronomy", level: 1, d: "Stones and temple doors aligned to the solstice sunrise mark the turning of the year beyond doubt.", mods: [["faith:sun", 3]] },
  { id: "star_catalogue", n: "Star catalogue", field: "astronomy", level: 2, d: "A thousand stars listed by brightness and position, the fruit of generations of patient night-watchers." },
  { id: "eclipse_tables", n: "Eclipse tables", field: "astronomy", level: 3, d: "Astronomers predict eclipses to the hour, and a ruler who announces one in advance seems to command the sky." },
  { id: "armillary_sphere", n: "Armillary sphere", field: "astronomy", level: 3, d: "Nested bronze rings model the heavens, letting a scholar turn the sky by hand and see the planets wander." },
  { id: "great_observatory", n: "Walled quadrant", field: "astronomy", level: 4, d: "A quadrant carved into a wall three storeys high measures star positions more finely than any hand-held tool." },
  { id: "comet_reckoning", n: "Comet reckoning", field: "astronomy", level: 4, d: "Scholars show that certain comets return on schedule, and omens become arithmetic.", mods: [["faith:stars", 2], ["scholarly", 2]] },
  { id: "spyglass", n: "Spyglass", field: "astronomy", level: 5, d: "Two lenses in a tube reveal moons circling the wandering stars and mountains on the face of the moon." },
  { id: "seers_orrery", n: "Seer's orrery", field: "astronomy", level: 4, d: "A clockwork orrery that also moves one planet no one can see, which the seers insist is really there.", req: { any: ["seers", "faith:stars"] } },
  { id: "rift_star_charts", n: "Rift-sky charts", field: "astronomy", level: 5, d: "Astronomers map the strange stars glimpsed through the rift, and find that the other sky is slowly moving closer.", req: "near:rift" },

  // --- writing (letters) ---
  { id: "tally_knots", n: "Tally sticks and knot-cords", field: "writing", level: 1, d: "Notched sticks and knotted cords record debts, herds and tribute long before there is a script." },
  { id: "pictographs", n: "Temple script", field: "writing", level: 1, d: "Priests scratch pictures into clay to record offerings, and those pictures slowly become words." },
  { id: "alphabet", n: "Phonetic alphabet", field: "writing", level: 2, d: "Two dozen letters for sounds replace thousands of signs, and merchants learn to write for themselves.", mods: [["mercantile", 2]] },
  { id: "law_codes", n: "Written law code", field: "writing", level: 2, d: "The laws carved on a pillar in the marketplace, so that judge and accused read the same words.", mods: [["harsh_law", 2]] },
  { id: "parchment", n: "Parchment and codex", field: "writing", level: 3, d: "Books bound from scraped skins survive damp and fire far better than scrolls, and libraries grow." },
  { id: "double_entry", n: "Double-entry ledgers", field: "writing", level: 4, d: "Every debit matched by a credit, and trading houses can suddenly see exactly where their money went.", req: { any: ["mercantile", "gov:merchant", "free_trade", "guilds"] } },
  { id: "rag_paper", n: "Rag paper mills", field: "writing", level: 4, d: "Paper pulped from old linen is cheap enough for letters, contracts and schoolboys' exercises." },
  { id: "cipher_codes", n: "Substitution ciphers", field: "writing", level: 3, d: "Letters encoded with shifting alphabets let spymasters and generals send orders no captured courier can betray.", req: { any: ["spy_network", "autocracy", "gov:city_state"] } },
  { id: "genealogy_rolls", n: "Ancestral rolls", field: "writing", level: 2, d: "Every family's descent recorded back twenty generations, read aloud at feasts and fought over in court.", req: { any: ["ancestor_bound", "faith:ancestors", "dynastic"] } },
  { id: "speaking_stones", n: "Speaking stones", field: "writing", level: 5, d: "Paired ley-stones repeat whatever is said to their twin, and messages cross the realm in a heartbeat.", req: [{ any: ["near:ley", "faith:ley", "magic:high"] }, "default:power"], w: 0.5 },
  { id: "universal_grammar", n: "Comparative grammar", field: "writing", level: 5, d: "Scholars show that a dozen tongues descend from one lost language, and the old empire's inscriptions become readable.", req: { any: ["scholarly", "near:ruins", "origin:ruin_heirs"] } },

  // --- warfare ---
  { id: "chariots", n: "War chariots", field: "warfare", level: 1, d: "Light two-wheeled chariots carry archers across open ground faster than any footman can run.", req: { any: ["steppe", "horse_lords", "desert"] } },
  { id: "phalanx", n: "Shield wall", field: "warfare", level: 1, d: "Spearmen locked shield to shield learn that discipline can stop a charge that courage alone cannot." },
  { id: "composite_bow", n: "Composite bow", field: "warfare", level: 2, d: "Horn, wood and sinew glued into a short, recurved bow that a rider can draw at full gallop.", mods: [["horse_lords", 3], ["nomadic", 2]] },
  { id: "stirrup", n: "Stirrups", field: "warfare", level: 2, d: "Iron stirrups let a rider brace against a couched lance, and the armoured horseman rules the field.", mods: [["horse_lords", 2]] },
  { id: "chainmail", n: "Riveted mail", field: "warfare", level: 2, d: "Coats of thousands of riveted rings turn sword cuts and make a trained warrior very expensive to kill." },
  { id: "crossbow", n: "Crossbow", field: "warfare", level: 3, d: "A peasant with a week of training can now kill a knight at a hundred paces, and lords find it outrageous." },
  { id: "war_beasts", n: "Monster cavalry", field: "warfare", level: 3, d: "Tamed monsters bred for battle charge beside the lancers, and enemy horses bolt at their scent.", req: { any: ["beast_tamers", "beast_cavalry", "origin:beast_bond"] } },
  { id: "longbow_levies", n: "Longbow levies", field: "warfare", level: 3, d: "Village archers drilled every feast day loose volleys that darken the sky and empty saddles.", req: { any: ["levies", "forest_folk", "egalitarian"] } },
  { id: "plate_armour", n: "Plate armour", field: "warfare", level: 4, d: "Fitted steel plates cover a knight from crown to heel, and only a hammer or a lucky thrust will do." },
  { id: "drilled_pikes", n: "Drilled pike squares", field: "warfare", level: 4, d: "Dense squares of long pikes, moving on the beat of a drum, make heavy cavalry charges suicidal." },
  { id: "hand_cannon", n: "Arquebus", field: "warfare", level: 5, d: "A matchlock tube throws a lead ball through any armour, and the smoke of battle changes forever." },
  { id: "battle_mages", n: "Battle-mage cadres", field: "warfare", level: 5, d: "Mages trained to cast in formation, shielded by pikes, break enemy lines with drilled volleys of fire.", req: { any: ["arcane", "gov:magocracy", "arcane_council", "magic:high"] }, not: { any: ["slot:power-source", "slot:power-access"] } },
  { id: "titan_slayer_ballista", n: "Titan-slayer ballista", field: "warfare", level: 4, d: "A siege engine the size of a house throws harpoons barbed to catch in a titan's hide and hold.", req: { any: ["origin:titan_slayers", "near:titan"] } },

  // --- arcana ---
  { id: "hedge_charms", n: "Codified charms", field: "arcana", level: 1, d: "Village cunning-folk agree which words and knots keep milk from souring, and magic begins to be taught." },
  { id: "spirit_binding", n: "Spirit binding", field: "arcana", level: 2, d: "Shamans learn to bargain a spirit into a carved fetish, where it serves as guard, guide or weapon.", req: { any: ["faith:spirits", "tribal", "forest_folk"] } },
  { id: "ley_lamps", n: "Ley-lamps", field: "arcana", level: 2, d: "Crystal globes set on ley lines glow softly all night, and the streets of the capital are never dark.", req: { any: ["near:ley", "faith:ley"] } },
  { id: "warding_circles", n: "Warding circles", field: "arcana", level: 2, d: "Salt and silver circles, drawn to exact proportions, keep out what should not come in." },
  { id: "grimoire_schools", n: "Grimoire schools", field: "arcana", level: 3, d: "Spells written in a formal notation can be taught to anyone patient enough, and hedge-witches become magisters." },
  { id: "scrying_mirrors", n: "Scrying mirrors", field: "arcana", level: 3, d: "Obsidian mirrors show distant rooms to trained eyes, and no council chamber is quite private any more.", mods: [["seers", 3], ["spy_network", 2]] },
  { id: "rift_stitching", n: "Rift-stitching", field: "arcana", level: 4, d: "Mages learn to sew small tears in the world shut with thread spun from their own hair and blood.", req: { any: ["near:rift", "origin:rift_touched"] } },
  { id: "titan_speech", n: "Titan-speech", field: "arcana", level: 4, d: "Heralds learn the slow grinding language of titans, and one of them, once, answered.", req: { any: ["faith:titan", "origin:titan_heralds", "titan_touched"] } },
  { id: "golems", n: "Clay golems", field: "arcana", level: 4, d: "Clay figures animated by a written word labour without rest, until someone forgets to erase the word." },
  { id: "void_gates", n: "Void gates", field: "arcana", level: 5, d: "Archways that open onto the dark between worlds let a mage step from one city to another, if nothing notices.", req: { any: ["faith:void", "near:rift", "origin:rift_touched"] }, w: 0.6 },
  { id: "weather_working", n: "Weather-working", field: "arcana", level: 5, d: "Circles of mages call rain on dry fields and turn storms from harbours, for a price the treasury groans at." },
  { id: "ley_grid", n: "Ley grid", field: "arcana", level: 5, d: "Stone pylons redirect ley lines across the realm, powering lamps, wards and engines far from any natural nexus.", req: [{ any: ["faith:ley", "gov:magocracy", "arcane_council"] }, "default:power"] },

  // --- alchemy ---
  { id: "fermentation", n: "Brewing and fermentation", field: "alchemy", level: 1, d: "Grain and fruit turned into beer and wine, safer to drink than river water and sacred at every feast." },
  { id: "dye_mordants", n: "Mordant dyes", field: "alchemy", level: 1, d: "Alum and urine fix bright dyes into cloth, and purple becomes the colour of kings." },
  { id: "distillation", n: "Distillation", field: "alchemy", level: 2, d: "Alembics separate spirits, perfumes and essences, and 'the water of life' becomes a costly medicine." },
  { id: "glassblowing", n: "Glassblowing", field: "alchemy", level: 2, d: "Molten glass blown on a pipe into flasks, retorts and windows clear enough to read through.", mods: [["desert", 2], ["artisans", 2]] },
  { id: "greek_fire", n: "Liquid fire", field: "alchemy", level: 3, d: "A secret mixture pumped from siphons burns even on water, and its recipe is guarded by death.", mods: [["navy", 2], ["seafaring", 1.5]] },
  { id: "strong_acids", n: "Aqua fortis", field: "alchemy", level: 3, d: "Distilled acids part gold from silver and etch steel, and assayers can at last spot debased coin." },
  { id: "black_powder", n: "Black powder", field: "alchemy", level: 4, d: "Saltpetre, sulphur and charcoal in the right proportion explode, and the alchemists' fireworks become weapons.", mods: [["near:volcano", 2]] },
  { id: "philosophers_salts", n: "Philosopher's salts", field: "alchemy", level: 4, d: "Salts refined from mystery-site soil glow faintly and seem to preserve anything packed in them.", req: "near:mystery" },
  { id: "titan_ichor", n: "Titan-ichor refining", field: "alchemy", level: 4, d: "Ichor tapped from a sleeping titan is refined into a fuel that burns for a month on a thimbleful.", req: { any: ["near:titan", "faith:titan", "origin:titan_heralds"] } },
  { id: "beast_rendering", n: "Monster rendering", field: "alchemy", level: 3, d: "Rendering houses boil monster carcasses down into glues, poisons and oils prized across the continent.", req: "near:beasts" },
  { id: "transmutation", n: "True transmutation", field: "alchemy", level: 5, d: "Lead becomes gold on a ley nexus, in tiny, ruinously expensive quantities, and the coinage trembles.", req: [{ any: ["magic:high", "near:ley", "gov:magocracy"] }, "default:power"], w: 0.5 },
  { id: "porcelain", n: "Hard porcelain", field: "alchemy", level: 5, d: "A white clay fired impossibly hot yields porcelain thin as eggshell, and the kilns become state secrets." },

  // --- natural philosophy ---
  { id: "four_elements", n: "Theory of elements", field: "natural_philosophy", level: 1, d: "Thinkers argue that everything is made of a few basic elements, and the gods become optional in some debates." },
  { id: "geometry", n: "Geometry", field: "natural_philosophy", level: 1, d: "Surveyors re-marking flooded fields discover rules of angles and areas that are true everywhere." },
  { id: "place_value", n: "Place-value numbers", field: "natural_philosophy", level: 2, d: "A symbol for nothing and numbers written by position make long sums easy for any clerk.", mods: [["mercantile", 2]] },
  { id: "natural_histories", n: "Natural histories", field: "natural_philosophy", level: 2, d: "Encyclopaedias of every known beast, plant and stone, half careful observation and half travellers' tales." },
  { id: "optics", n: "Theory of optics", field: "natural_philosophy", level: 3, d: "A philosopher explains that sight is light entering the eye, and lens-grinders take note." },
  { id: "bestiary_taxonomy", n: "Monster taxonomy", field: "natural_philosophy", level: 3, d: "Scholars sort monsters by lineage rather than terror, and discover which ones can be driven off with smoke.", req: { any: ["near:beasts", "beast_tamers"] } },
  { id: "algebra", n: "Algebra", field: "natural_philosophy", level: 3, d: "Unknowns solved by balancing both sides of an equation, and inheritance disputes become simple arithmetic." },
  { id: "experimental_method", n: "Experimental method", field: "natural_philosophy", level: 4, d: "A school that insists every claim be tested and repeated before it is believed, to the fury of older masters.", not: "zealous" },
  { id: "titan_geology", n: "Titan geology", field: "natural_philosophy", level: 4, d: "Surveyors realise certain mountain ranges are titans that died long ago, and old maps are redrawn.", req: { any: ["near:titan", "titan_touched"] } },
  { id: "rift_physics", n: "Rift measurement", field: "natural_philosophy", level: 5, d: "Instruments measure how gravity and time bend near the rift, and the results terrify their makers.", req: { any: ["near:rift", "origin:rift_touched"] } },
  { id: "heliocentrism", n: "Heliocentric model", field: "natural_philosophy", level: 5, d: "A scholar proves the world circles the sun, and every temple that taught otherwise must decide what to do with her.", mods: [["faith:sun", 0.3], ["scholarly", 2]] },
  { id: "mechanical_philosophy", n: "Mechanical philosophy", field: "natural_philosophy", level: 5, d: "Philosophers describe the world as a vast clock, and magic as a part of it they do not yet understand.", mods: [["magic:low", 2]] },
];

export const INSTITUTIONS = [
  { n: "The Grand Library of {capital}", field: "writing", d: "Scrolls and codices from across the known world, copied by an army of scribes and guarded by an older one." },
  { n: "The Scriptorium of {deity}", field: "writing", req: { any: ["pious", "organised"] }, d: "Monks copy sacred texts and, quietly, a great many profane ones they are not supposed to keep." },
  { n: "The Hall of Records of {short}", field: "writing", req: { any: ["hierarchical", "gov:empire", "gov:absolute"] }, d: "Every tax roll, deed and census of the realm, filed in rooms that stretch farther than anyone has walked." },
  { n: "The House of Ancestral Names", field: "writing", req: { any: ["ancestor_bound", "faith:ancestors"] }, d: "Keepers recite the lineages of every family and settle inheritance disputes by memory alone." },
  { n: "The Academy of {capital}", field: "natural_philosophy", d: "A school where masters argue in colonnades and students pay for the privilege of arguing back." },
  { n: "The Free School of the {people}", field: "natural_philosophy", req: { any: ["egalitarian", "republic", "gov:commune"] }, d: "Open to anyone who can pass the entrance riddle, whatever their birth, and proud of it." },
  { n: "The Lyceum of {ruler}", field: "natural_philosophy", req: "monarchy", d: "Founded by royal decree to make the court look wise, it has since produced several genuinely dangerous ideas." },
  { n: "The Observatory of {capital}", field: "astronomy", d: "A tower of brass instruments above the rooftops, where night-watchers keep the calendar and the omens." },
  { n: "The Star Temple of {deity}", field: "astronomy", req: { any: ["faith:stars", "faith:sun"] }, d: "Priest-astronomers read the will of the heavens and correct the calendar with suspicious convenience." },
  { n: "The Seers' Tower", field: "astronomy", req: "seers", d: "A tall, windowless tower whose seers watch the sky through a single hole in the roof." },
  { n: "The Guildhall of Smiths", field: "metallurgy", req: { any: ["guilds", "artisans"] }, d: "Masters of the forge set prices, guard their secrets and hang the tools of expelled members on the gate." },
  { n: "The Deep Forges of {short}", field: "metallurgy", req: { any: ["mountain_folk", "origin:mountain_hold", "mountain"] }, d: "Furnaces cut into the roots of the mountain burn day and night, and the smoke rises from vents a mile away." },
  { n: "The Royal Arsenal", field: "metallurgy", req: { any: ["standing_army", "gov:stratocracy", "monarchy"] }, d: "Armourers, fletchers and gun-founders under one roof, turning out weapons for the realm's regiments." },
  { n: "The Masons' Lodge of {capital}", field: "architecture", d: "A brotherhood of builders with secret signs, whose masters alone know how the great vaults stand." },
  { n: "The Cathedral Works of {deity}", field: "architecture", req: { any: ["pious", "lavish"] }, d: "A workshop of hundreds that has been building the same cathedral for four generations." },
  { n: "The Office of Roads and Bridges", field: "engineering", req: { any: ["great_roads", "gov:empire"] }, d: "Surveyors and engineers who keep the highways straight and collect the tolls that pay for them." },
  { n: "The Engineers' Collegium", field: "engineering", d: "Millwrights, clockmakers and siege engineers trading drawings and quarrelling over patents." },
  { n: "The Royal Shipyards of {capital}", field: "navigation", req: "coastal", d: "Slipways, ropewalks and timber ponds along the harbour, launching a hull every month in good years." },
  { n: "The Pilots' Guild of {short}", field: "navigation", req: { any: ["seafaring", "mercantile"] }, d: "No ship may enter the harbour without a guild pilot, and the guild's charts are its most closely kept treasure." },
  { n: "The Admiralty School", field: "navigation", req: "navy", d: "Young officers learn gunnery, signals and the stars aboard old hulks moored in the roads." },
  { n: "The Caravan Masters' House", field: "navigation", req: { any: ["desert_wanderers", "nomadic", "open_roads"] }, d: "Where route-songs are taught, wells are recorded and caravans are insured against the sands." },
  { n: "The Infirmary of {deity}", field: "medicine", req: { any: ["pious", "organised"] }, d: "A temple hospital where nuns and physicians argue over whether prayer or bleeding comes first." },
  { n: "The Physicians' College of {capital}", field: "medicine", d: "Licenses every doctor in the realm and sues those it did not license, often with good reason." },
  { n: "The Beastwardens' Lodge", field: "medicine", req: { any: ["beast_tamers", "near:beasts"] }, d: "Healers of beasts and of those beasts have mauled, who know both kinds of wound better than anyone." },
  { n: "The War College of {short}", field: "warfare", req: { any: ["martial", "standing_army", "gov:stratocracy"] }, d: "Officers study old battles on sand tables and are failed for losing them the same way twice." },
  { n: "The Fencing Hall of {capital}", field: "warfare", d: "Masters of arms teach the sons and daughters of the rich to kill each other politely." },
  { n: "The Order of the Titan Hunt", field: "warfare", req: { any: ["origin:titan_slayers", "near:titan"] }, d: "A sworn order training hunters to bring down titans, whose halls are hung with teeth the size of men." },
  { n: "The Arcane Tower of {capital}", field: "arcana", req: { any: ["arcane", "magic:high", "arcane_council", "gov:magocracy"] }, d: "A spire of warped stone where {users} study, experiment and occasionally explode." },
  { n: "The Circle of the Ley", field: "arcana", req: [{ any: ["faith:ley", "near:ley"] }, "default:power"], d: "Mages who map and tend the ley lines, and who would very much like to own them." },
  { n: "The Riftwatch", field: "arcana", req: { any: ["near:rift", "origin:rift_touched"] }, d: "A fortress-college on the rift's edge that studies what comes through, preferably after killing it." },
  { n: "The College of Heralds of the Titan", field: "arcana", req: { any: ["faith:titan", "origin:titan_heralds"] }, d: "Scholars who listen to the titan's slow heartbeat and write down what they believe it is saying." },
  { n: "The Alchemists' Guild of {capital}", field: "alchemy", d: "Distillers, dyers and would-be gold-makers sharing a guildhall that smells of sulphur and ambition." },
  { n: "The Royal Powder Works", field: "alchemy", req: { any: ["standing_army", "autocracy"] }, d: "Saltpetre sheds and grinding mills behind high walls, far enough from town that explosions only break windows." },
  { n: "The Granary Council", field: "agriculture", req: { any: ["river_folk", "river", "gov:empire"] }, d: "Stewards who measure the flood, fix the grain tax and hold back reserves against the lean years." },
  { n: "The Stud of {ruler}", field: "agriculture", req: { any: ["horse_lords", "steppe"] }, d: "Royal horse farms whose bloodlines are recorded more carefully than the royal family's own." },
  { n: "The Seed Vault of the {people}", field: "agriculture", d: "A cool stone vault where every known strain of grain is kept against blight, war and famine." },
];

export const SCHOLAR_ROLES = [
  "astronomer", "physician", "alchemist", "master mason", "engineer", "cartographer", "archivist", "grammarian",
  "natural philosopher", "mathematician", "magister", "herbalist", "surgeon", "shipwright", "metallurgist", "gun-founder",
  "clockmaker", "lexicographer", "seer", "geomancer", "beastwarden", "military theorist", "agronomist", "glassblower",
  "historian", "translator", "occultist",
];

export const DISCOVERY_TEXT = [
  "The {scholar} of {capital} demonstrated {invention} before the court, and the doubters went quiet.",
  "After twenty years of failures, a {scholar} in {capital} perfected {invention}.",
  "{invention} came to {capital} with a foreign {scholar} who asked only for a workshop and a pension.",
  "A {scholar} working alone in a cellar in {capital} stumbled upon {invention} while looking for something else entirely.",
  "The guild tried to suppress {invention}, but a {scholar} published it openly, and {field} was never the same.",
  "{invention} was recovered from ruin-tablets translated by a {scholar} of {capital}.",
  "A {scholar} of {capital} was nearly burned for heresy before {invention} proved its worth.",
  "Rival {scholar}s in {capital} both claim {invention}, and their students still brawl over it in the taverns.",
  "{invention} was first used in anger, and only afterwards did the {scholar}s of {capital} explain why it worked.",
  "The crown paid a {scholar} a fortune to bring {invention} to {capital}, and it paid for itself within a decade.",
  "{invention} began as a toy made by a {scholar} for a child of the court and became the pride of {field} in {capital}.",
  "Stolen from a rival realm by a spy posing as a {scholar}, {invention} is now claimed as a native triumph in {capital}.",
  "A {scholar} of {capital} lost her sight, her fortune and her marriage to {invention}, and was honoured only after her death.",
  "Peasants had used a crude form of {invention} for generations before a {scholar} of {capital} wrote it down and took the credit.",
  "The masters of {field} in {capital} called {invention} impossible until a young {scholar} built one in the palace courtyard.",
  "{invention} was revealed in a dream to a {scholar} of {capital}, or so the {scholar} says.",
];
