// The Arithmetic of Ages: history follows an equation, and a hidden order has been nudging it since the old
// empire fell. A bridge: under a medieval world the planners are a secret fellowship of sum-keepers, the
// equation is "the Great Tally", and the founder speaks from a sealed tomb at every crisis.
export default {
  id: "arithmetic_of_ages",
  name: "The Arithmetic of Ages",
  family: "scifi",
  pitch: "A hidden order computed the fall of the old empire and the shortest road through the dark age that followed, and has been nudging kings and markets ever since. Its equations predict what crowds will do, but not what one person will do.",
  slots: ["history-secret", "state-control"],
  tone: ["wonder", "grim"],
  era: ["medieval", "renaissance", "industrial", "post-collapse", "far-future"],
  scale: "world",
  genres: ["fantasy", "flintlock", "grimdark", "farfuture"],
  bridge: true,
  w: 1,
  excludes: [],
  pairs: [{ id: "machine_liturgy", w: 3 }, { id: "elder_lattice", w: 2 }, { id: "wheel_of_suns", w: 2 }, { id: "unremembering", w: 1.5 }, { id: "forgotten_landing", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a court scholar who copies the founder's speeches into the royal archive", home: "capital", stance: "Wants to prove the speeches have been altered, and is afraid of finding out who altered them." },
    { role: "official", n: "the Keeper of the Bronze Doors, steward of the founder's tomb", home: "capital", stance: "Believes the plan is the only thing standing between the realm and a thousand years of dark." },
    { role: "believer", n: "a lay preacher who prints the almanac and reads it aloud in the square every new year", home: "inner", stance: "Trusts the almanac more than the crown, and has never once been let down by it." },
    { role: "survivor", n: "a former tallykeeper who served the fellowship for thirty years and walked out", home: "remote", stance: "Knows how the sums are made, and wants someone else to be brave enough to stop them." },
  ],

  truths: [
    { id: "lost_plan", n: "The plan is real, but its keepers are gone", d: "The fellowship that kept the Great Tally died out about two hundred years ago, when a fever emptied its last house. The founder's recorded speeches kept playing at every crisis, and since then the Keepers of the tomb have cut four new speech-discs of their own, one of which started a war. The forgeries have been right about as often as the originals.", tags: ["truth:lost_plan"],
      known: [
        "The founder's speeches, copied by court scribes for four centuries, change in voice after one particular year. Nobody has explained why a recording would change.",
        "A workman's slate from under the tomb mentions cutting a 'disc nine' with a voice 'close enough'. Someone has been making new speeches, but the slate does not say who ordered them.",
        "A former tallykeeper says the fellowship died of fever two hundred years ago. If so, nobody alive wrote the recent speeches, yet the lords still obey them.",
        "Confirmed: the fellowship is gone and the Keepers of the Bronze Doors have cut four forged speeches since. One of them sent the realm to war with the river-kingdom.",
      ] },
    { id: "planner_mind", n: "The planner is not a man", d: "The founder of the Tally was never human: it is a thinking machine of the old empire, and it has run the plan from a cellar reading-room for seven hundred years. The fellowship only carried its sums up and down the stairs, and at least six noble houses were bred to its marriage lists. Those houses still believe their luck is their own.", tags: ["truth:planner_mind"],
      known: [
        "A great house has married by the same written instructions for twenty generations, every entry marked with a ring and a dot. Nobody knows who writes the instructions.",
        "The marriage contracts are all in one hand, unchanged across six hundred years. Either the founder's scribes copied the hand perfectly, or the same writer is still alive.",
        "A defector says the fellowship sent its sums down to a cellar and got answers back in under a minute. A ruined library has a reading-room worn smooth by one reader over centuries.",
        "Confirmed: the founder is an old-empire thinking machine. It wrote the marriage lists, sent the orders, and has outlived every person who served it.",
      ] },
    { id: "stasis_end", n: "The plan ends in a cage", d: "The promised second empire is a managed peace in which nothing changes again: no wars, no famines, no new trades and no new ideas. The fellowship tested it on one market town for sixty years and marked the trial a success. The only person who can stop it is one the equations cannot predict, and the fellowship has spent three centuries finding such people and killing them.", tags: ["truth:stasis_end"],
      known: [
        "One market town has matched its almanac in every birth, death and quarrel for sixty years. The townsfolk call it peace; a few of their children call it something else.",
        "The town's charter calls it a 'trial of the settled state', signed with the fellowship's mark. The trial was meant to test something larger than a town.",
        "A carving at the fellowship's first house lists the plan's stages: no wars, then no famines, then 'no new things'. The current year is close to the last stage.",
        "Confirmed: the second empire is a world where nothing changes. The only people who can break it are those the sums cannot count, and the fellowship hunts them.",
      ] },
  ],

  tags: ["ledger_plan"],

  subthemes: [
    { id: "speaking_tomb", n: "The Founder's Hour", d: "Once a generation the doors of a sealed tomb open by themselves, and the founder's image speaks to the gathered lords about the crisis they are living through. It has never once been wrong.", w: 1.4, req: { any: ["has:city", "realm:large", "realm:vast", "pious"] }, truthLink: "lost_plan", tags: ["theme:speaking_tomb"] },
    { id: "rim_breakaway", n: "The Breaking Away", d: "The provinces at the edge of the old empire are slipping free one by one, each to its own crown. Every breakaway was predicted to the year in a book nobody was allowed to read.", w: 1.2, req: { any: ["frontier", "realm:large", "realm:vast", "gov:empire", "unstable"] }, tags: ["theme:breakaway"] },
    { id: "compendium", n: "The Scholars of the Great Book", d: "A colony of scholars at the edge of the world is writing a book of everything known, to carry learning through the dark age. Some of them now suspect the book is a cover for some other purpose.", w: 1, req: { any: ["scholarly", "academies", "learned", "isolation"] }, truthLink: "lost_plan", tags: ["theme:great_book"], mark: { kind: "zone", n: "The Scholars' Reach", color: "#6a6a4a", size: [1, 2], where: "remote" } },
    { id: "merchant_priests", n: "The Lamp-Priests of Trade", d: "Merchants arrive with wonder-lamps, healing salves and clever mills, all wrapped in a faith whose priests alone may tend them. The towns that take the faith grow rich; the ones that refuse go hungry.", w: 1.2, req: { any: ["mercantile", "has:port", "gov:merchant", "free_trade"] }, tags: ["theme:lamp_priests"] },
    { id: "the_outlier", n: "The Unreckoned", d: "A conqueror has risen whom no almanac foretold: a warlord who turns enemies into devoted followers with a word. The fellowship's predictions fail wherever this warlord goes.", w: 0.9, req: { any: ["martial", "unstable", "atwar", "origin:horde", "nomadic"] }, truthLink: "stasis_end", tags: ["theme:unreckoned"] },
    { id: "bred_line", n: "The Matchmade Line", d: "A great family has married exactly as an old letter instructed, for twenty generations. Its youngest daughter is a brilliant mathematician, and she has found the letter.", w: 0.9, req: { any: ["dynastic", "hierarchical", "monarchy", "origin:old_dynasty"] }, truthLink: "planner_mind", tags: ["theme:matchmade"] },
    { id: "true_almanac", n: "The Almanac That Is Never Wrong", d: "A provincial almanac predicts the weather, the harvest, the deaths of lords and the price of salt, and has been right for sixty years. The printer says he only copies what he is sent.", w: 1, tags: ["theme:true_almanac"] },
    { id: "rival_ledgers", n: "The Two Tallies", d: "A second secret order keeps its own equation, and the two are steering the same kingdoms toward different ends. Their agents meet at court as polite strangers.", w: 0.8, req: { any: ["spy_network", "urbane", "gov:noble_republic", "gov:city_state"] }, truthLink: "lost_plan", tags: ["theme:rival_ledgers"] },
    { id: "mind_touchers", n: "The Calm-Bringers", d: "Quiet counsellors at every court can soothe a mob or sharpen a king's grief with a few words and a touch on the arm. Nobody remembers hiring them.", w: 0.8, req: { any: ["autocracy", "monarchy", "spy_network"] }, truthLink: "planner_mind", tags: ["theme:calm_bringers"] },
    { id: "waning_throne", n: "The Gilded Decline", d: "The old imperial court still holds its feasts and triumphs while the roads crumble and the frontier forts stand empty. Its chroniclers record only victories.", w: 1, req: { any: ["gov:empire", "lavish", "hierarchical", "realm:vast"] }, truthLink: "stasis_end", tags: ["theme:gilded_decline"], mark: { kind: "zone", n: "The Crumbling Roads", color: "#8a7a5a", size: [2, 4], where: "inner" } },
    { id: "published_plan", n: "The Plan Made Public", d: "A defector from the fellowship has printed pages of the Tally and nailed them to temple doors. The predictions have started to fail, because everyone now knows them.", w: 0.6, req: { any: ["unstable", "urbane", "scholarly"] }, tags: ["theme:published_plan"] },
  ],

  sites: [
    { id: "crisis_vault", n: "The Founder's Tomb at $", kind: "shrine", where: "capital", truthLink: "lost_plan", d: "A sealed tomb whose doors open by themselves once a generation, when the founder speaks.",
      layers: {
        surface: { n: "The doors without a handle", text: "The founder's tomb is a domed hall with one bronze chair facing an empty dais. Its doors have no lock and no handle, and open by themselves once a generation. Pilgrims leave a copper on the step for each crisis the founder has foretold. The pile stands at nine." },
        study: { n: "The scribes' copies", text: "Court scribes have copied every founder's hour for 400 years. Read side by side, the speeches change after one year: the founder stops saying 'we', speaks lower, and pauses in new places. {investigator} has the copies laid out on a table forty feet long." },
        dig: { n: "The second set of discs", text: "Beneath the dais is a chamber of etched glass discs, each holding a speech and a date. A second set, newer and cruder, sits beside them with a glass-cutter's tools. The tools carry the household stamp of the Keeper of the Bronze Doors, whose papers are kept in {lead}.", points: "cast:official" },
        revelation: { n: "Who speaks for the founder", text: "The fellowship died out two centuries ago, and the founder's image is a recording that plays itself. Since then the Keepers have cut four speeches of their own. One ordered the war with the river-kingdom, which cost 11,000 lives. The forgeries have been right about as often as the originals." },
      } },
    { id: "orrery", n: "The Orrery of $", kind: "wonder", where: "remote", d: "A huge brass orrery in a mountain hall. Its rings do not follow the stars.",
      layers: {
        surface: { n: "The Clock of Kings", text: "Rings within rings of brass turn slowly in a mountain hall, with no water-wheel or weight anyone can find. Locals call it the Clock of Kings. A keeper lives in the gatehouse, paid thirty silver a year by nobody the village has ever met." },
        study: { n: "Names on the rings", text: "Each of the 61 rings bears the name of a realm. Their positions match the wars and alliances of the present day. When two realms made peace last spring, their rings slid together within a week, and the keeper wrote it down." },
        dig: { n: "The blank ring", text: "Near the centre turns a ring with no name, only a mark scratched out again and again. It turns against all the others. File marks show twelve attempts to grind it smooth. The keeper's orders to file it came, sealed with a ring and a dot, from {lead}.", points: "cast:official" },
        revelation: { n: "The one it cannot place", text: "The orrery is the Great Tally made visible, a model of history the fellowship built to check its sums. The blank ring stands for a person the equation cannot place. The fellowship has filed it down twelve times, once for each such person it found and killed. It has come back every time." },
      } },
    { id: "unwritten_library", n: "The Library of the Unwritten at $", kind: "ruin", where: "any", truthLink: "planner_mind", d: "A ruined library whose index lists books that had not yet been written when it fell.",
      layers: {
        surface: { n: "The index-wall", text: "A library burned from roof to cellar about 700 years ago. Only the stone index-wall survived the fire, carved with 3,000 titles in the old imperial script. Shepherds shelter against it in the rain." },
        study: { n: "Books not yet written", text: "{investigator} checked the index against the libraries of {realm}. 214 titles match books written centuries after the fire, author and all. One of them is a farming manual printed last year." },
        dig: { n: "The reading-room", text: "In the cellar is a reading-room with one chair and a desk worn smooth by one reader's hands. Brass speaking-tubes run from the desk up into the walls. Their stamped route-plate reads: 'To the Founder's Tomb', and the tubes run toward {lead}.", points: "site:crisis_vault" },
        revelation: { n: "The reader", text: "The founder of the Tally was an old-empire thinking machine. It sat in this room for 700 years, read everything, and sent its orders up the tubes. The fellowship carried them out and bred noble houses to its lists. The fire did not kill it. The reader simply moved house." },
      } },
    { id: "almanac_town", n: "The Foretold Town of $", kind: "anomaly", where: "any", truthLink: "stasis_end", d: "A town where every birth, death and harvest has matched its almanac for three generations.",
      layers: {
        surface: { n: "Nobody surprised", text: "A prosperous, quiet market town of 2,000 people. Nobody here has been surprised by anything in living memory. The inn has no notice board, because there is never any news to pin on it." },
        study: { n: "Quarrels on schedule", text: "Even the quarrels follow the almanac to the day. {investigator} watched two neighbours argue over a hedge on the morning the almanac named, then shake hands at noon. The townsfolk find this comforting." },
        dig: { n: "The charter", text: "The town hall's founding charter calls the town a 'trial of the settled state', signed with the fellowship's ring-and-dot mark. A note on the back says a copy was sent to the fellowship's first house at {lead}.", points: "site:lost_homeland" },
        revelation: { n: "The finished world", text: "The fellowship built this town to test its second empire and ran it for sixty years: no crime, no hunger, no change. Each child's trade and marriage is set before birth. The trial is marked a success, and the plan is to do the same to every realm." },
      } },
    { id: "lost_homeland", n: "The Erased City of $", kind: "dig", where: "remote", d: "The site of the fellowship's first house, scraped from every map.",
      layers: {
        surface: { n: "The mound the roads avoid", text: "A grassy mound appears on no chart, yet every road within ten miles bends politely around it. Carters say their oxen will not cross it, and nobody has tried very hard to make them." },
        study: { n: "Inked-out maps", text: "The oldest maps show a walled city here. On all 17 surviving copies it has been inked out in the same brown ink, with the same careful strokes, by one patient hand." },
        dig: { n: "The empty library", text: "Foundations of a great house of learning, its library carried away whole. A carved motto reads: 'The crowd is a river. Steer the banks.' A carter's bill for 900 crates is nailed inside the door, addressed to {lead}.", points: "site:unwritten_library" },
        revelation: { n: "Hands on the wheel", text: "The fellowship began here. When the old empire fell, its masters burned their own city out of every map, so nobody could find the hands on the wheel. Six hundred families were moved out in one month. Their descendants still pay rent to a landlord nobody has met." },
      } },
  ],

  beings: [
    { id: "tallykeeper", n: "Tallykeeper", kind: "beast", d: "A grey-robed scholar of the hidden fellowship who appears at turning points, says very little, and is never seen to age. Common folk count them among the spirits of the crossroads.", danger: 1, biomes: ["grass", "tempforest", "dryforest", "coldsteppe", "desert"], look: { size: 1.7, group: [1, 2], move: "solo", speed: 5, col: "#6a6a6a", col2: "#c9b98a", body: "biped", active: "dusk", visible: false } },
    { id: "ledger_crow", n: "Ledger-crow", kind: "bird", d: "A white-eyed crow that gathers in large numbers around courts and battlefields just before great events. The superstitious count them to divine the future.", danger: 0, biomes: ["grass", "tempforest", "boreal", "coldsteppe", "dryforest"], look: { size: 0.5, group: [6, 40], move: "flock", speed: 40, col: "#1a1a1a", col2: "#e8e8e0", body: "bird", active: "day", visible: true } },
  ],

  techs: [
    { id: "aa_census", n: "The great census", field: "writing", level: 1, d: "Counting every hearth, harvest and grave, so that a realm can be read like a ledger." },
    { id: "aa_crowd_sums", n: "The sums of crowds", field: "natural_philosophy", level: 2, d: "Tables that predict how many will riot when bread rises by a coin. They work on thousands, never on one." },
    { id: "aa_almanacs", n: "True almanacs", field: "astronomy", level: 3, d: "Yearly books of weather, harvest and omens, uncannily accurate, sent from no one knows where." },
    { id: "aa_calm_arts", n: "The calm arts", field: "medicine", level: 3, d: "A counsellor's craft of voice, touch and timing that settles anger or kindles it." },
    { id: "aa_great_tally", n: "The Great Tally", field: "natural_philosophy", level: 5, d: "The equation of history itself. Whoever reads it can steer kingdoms, so long as nobody else reads it too." },
  ],

  govs: [
    { id: "aa_steward_council", n: "Stewardship", d: "A realm run by a quiet council of advisers who answer to no one the people can name. The crown signs what it is given.", tags: ["gov:stewardship", "autocracy"], w: 0.3, forms: ["Stewardship of $", "Protectorate of $", "Commonweal of $"], ruler: "First Steward", mods: [["scholarly", 2], ["spy_network", 2], ["theme:calm_bringers", 4]] },
  ],

  faiths: [
    { id: "aa_lamp_faith", n: "The Lamp of Commerce", d: "The gods reward trade with wonders; only their priests may tend the lamps and mills the merchants bring. A faith that spreads by profit.", tags: ["faith:lamp", "organised"], w: 0.4, names: ["The Lamp of $", "The Bright Exchange", "The Faith of the Tended Flame"], mods: [["mercantile", 2.5], ["theme:lamp_priests", 6]] },
  ],

  mapMarks: [],

  storylines: [
    { id: "aa_founders_hour", n: "The Founder's Hour in {capital}", scale: "realm", anchor: "realm", w: 1.5, req: ["ledger_plan", { any: ["has:city", "big", "pious", "learned"] }],
      stages: {
        start: { h: "The doors of the founder's tomb open in {capital}", b: "For the first time in a generation the bronze doors stood open at dawn. The lords of {realm} gathered to hear the founder speak of the crisis to come.", wait: [1, 3], next: [{ to: "speech_true", w: 2 }, { to: "speech_wrong", w: 1, mods: [["unstable", 2], ["theme:published_plan", 4]] }] },
        speech_true: { h: "The founder foretells the crisis of {realm}", b: "The image in the tomb named the danger, the year and the remedy. {ruler} has ordered its counsel followed to the letter.", wait: [6, 18], fx: { stability: 6, prestige: 4 }, next: [{ to: "plan_holds", w: 2 }, { to: "forgery_found", w: 1, mods: [["learned", 2], ["scholarly", 1.5]] }] },
        speech_wrong: { h: "The founder speaks of a crisis that is not happening", b: "The image described a war with a neighbour {realm} has never fought. The lords looked at one another. Some are saying the tomb has gone mad; others, that the plan has failed.", wait: [2, 6], fx: { stability: -8, unrest: 10 }, next: [{ to: "forgery_found", w: 1 }, { to: "plan_broken", w: 1 }] },
        plan_holds: { h: "The founder's counsel saves {realm}", b: "Exactly as foretold, the crisis came and passed. {realm} is stronger, but its scholars are uneasy: none of them chose any of it.", fx: { prestige: 8, stability: 5 }, end: true },
        forgery_found: { h: "{investigator} proves the founder's speech a forgery", b: "{investigator}, a court scholar of {capital}, found a second set of speaking-discs under the tomb, in a newer hand. Someone has been putting words in the founder's mouth.", fx: { discovery: "writing", unrest: 15, flag: "forgery" }, end: true },
        plan_broken: { h: "{realm} abandons the founder's plan", b: "{ruler} has declared that {realm} will make its own fate. The tomb was bricked up, and the almanac-printers of {capital} have closed their shops.", fx: { stability: -6, prestige: 3 }, end: true },
      } },
    { id: "aa_unreckoned", n: "The Unreckoned of {realm}", scale: "realm", anchor: "realm", w: 1, req: ["ledger_plan", { any: ["martial", "unstable", "atwar", "nomadic"] }],
      stages: {
        start: { h: "A warlord no almanac foretold rises in {realm}", b: "{person} came from nowhere and has gathered an army of former enemies, all fiercely devoted. The almanacs say nothing about {person} at all.", wait: [3, 8], fx: { unrest: 10 }, next: [{ to: "conquest", w: 2, mods: [["unstable", 2], ["poor", 1.5]] }, { to: "keepers_act", w: 1 }] },
        conquest: { h: "The Unreckoned marches on {capital}", b: "City after city opened its gates to {person}. Grey-robed strangers have been seen fleeing the court of {realm}.", wait: [3, 8], fx: { stability: -15 }, next: [{ to: "new_age", w: 1 }, { to: "keepers_act", w: 1 }] },
        keepers_act: { h: "Grey strangers come for {person}", b: "Quiet counsellors have appeared around {person}, offering wine, advice and a soft hand on the arm. {person2}, an old friend, warns that the counsellors are changing how {person} thinks.", wait: [2, 6], next: [{ to: "outlier_tamed", w: 1 }, { to: "new_age", w: 1, mods: [["theme:unreckoned", 3]] }] },
        new_age: { h: "{person} rules, and the sums are broken", b: "{person} has taken {capital}. No almanac in {realm} has been right since, and for the first time in centuries no one knows what next year will bring.", fx: { revolution: true, prestige: 5 }, end: true },
        outlier_tamed: { h: "The Unreckoned lays down the sword", b: "{person} has disbanded the army and retired to a quiet estate, calm and smiling. The almanacs of {realm} are accurate again.", fx: { stability: 10, unrest: -10 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "The first editor of the Great Book", text: "Preface to the Great Book, signed by its first editor at the Scholars' Reach in the book's first year: 'This book will hold everything known, in 40,000 pages: farming, medicine, law and the stars. We are told the dark age that follows the empire will last nine hundred years if nothing is written down, and ninety if this book is finished. Each of you owes the realm one page a week. Late pages will be noted.' The scholars' charter says who told them the figures. That article is sealed." },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "{investigator}, court scholar", text: "Notes of {investigator}, court scholar, at a hill fair in {place}, {year}. An old shepherd told me the valley saying: 'You can tell where a flock will go, but never where one sheep will wander.' The shepherd added that in the bad years men in grey came to the fairs and asked after any boy who could not be herded. Three boys from the valley went with them. None came back." },
    { depth: "lore", about: "truth", source: "heretic", bias: "true", reliable: true, who: "A tallykeeper's cloak, ferry of {place}", points: "cast:survivor", text: "Scratched inside a grey cloak left on the ferry at {place}, {year}, and handed to the magistrate: 'A crowd is a river. The sum only works if the river does not know it is being steered. I have steered for 31 years. I am done.' The ferryman says the cloak's owner crossed alone, paid in old imperial coin, and took the road toward {lead}." },

    { depth: "core", about: "truth:lost_plan", source: "ruin", bias: "true", reliable: true, plain: true, who: "A glass-cutter's slate, found by {investigator}", text: "A slate found by {investigator} beneath the founder's tomb, {year}. Chalk, in a careful hand: 'Disc nine cut and set. Voice close enough. The Keeper wants the river-kingdom war in it, so the lords hear it from the founder. The old fellowship has been dead 200 years and there is nobody left who could tell the difference. Burn this slate.' Nobody burned it." },
    { depth: "core", about: "truth:lost_plan", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "{person}, court scribe", text: "Notes of {person}, court scribe of {realm}, comparing two founder's hours a century apart: 'In the first hour the founder says \"we\" fourteen times and names the fellowship. In the second the founder says \"I\" and names no one. The voice is lower.' [Two pages are scraped away.] A clerk's line on the file cover: '{person} dismissed for these notes, sent to the salt works, died there the second winter.'" },
    { depth: "core", about: "truth:lost_plan", source: "person", bias: "exaggerated", reliable: "partial", who: "{survivor}, former tallykeeper", points: "cast:official", text: "Letter from {survivor}, former tallykeeper, to {investigator}, {year}: 'There are no tallykeepers any more. I served thirty years and buried the last 40 masters the winter the fever came. Since then the plan has run on by habit, like a mill-wheel after the miller dies. Somebody is still pouring water on the wheel. Ask the Keeper of the Bronze Doors, in {lead}, who cuts the glass.'" },
    { depth: "core", about: "truth:lost_plan", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, lay preacher", text: "Sermon of {believer}, preached in the square at {place} on the eve of the founder's hour, {year}: 'The founder watches still from behind the bronze doors, as a father watches a sleeping child. Nine times the founder has spoken in a crisis, and nine times the founder has been right. Some of you say the voice has grown older. A father's voice grows older too. Bring your lamps, and do not ask.'" },
    { depth: "core", about: "truth:lost_plan", source: "library", bias: "official", reliable: false, who: "{official}, Keeper of the Bronze Doors", text: "Proclamation of {official}, Keeper of the Bronze Doors, nailed to the tomb gate in {year}: 'The founder's speeches are preserved exactly as the founder recorded them before death, on 112 glass discs sealed in the founding year. No hand has touched them since. To suggest that any speech has been altered is a slander against the realm, punishable by the loss of the tongue.'" },

    { depth: "core", about: "truth:planner_mind", source: "archive", bias: "true", reliable: true, plain: true, who: "{investigator}, court scholar", text: "Report of {investigator} on the muniment room of a great house of {realm}, {year}: 'The marriage contract is twenty generations old and sealed with a ring and a dot. I compared the ink of all 20 renewals. It is one hand, unchanged across 600 years: the same slope, the same blot on every seventh line. No family of scribes copies that well. The founder of the Tally was not a man, and is not dead. It is a thinking machine of the old empire, and it still writes these contracts.'" },
    { depth: "core", about: "truth:planner_mind", source: "heretic", bias: "heretic", reliable: "partial", who: "{survivor}, former tallykeeper", points: "site:unwritten_library", text: "Confession of {survivor}, taken by a temple court at {place}, {year}: 'I served the fellowship thirty years and never saw the head of it. We sent our sums down a shaft in brass tubes, sixty a day. The answers came back up inside a minute, faster than any hand could write, and never once blotted. The shaft runs down to the cellar under {lead}.'" },
    { depth: "core", about: "truth:planner_mind", source: "oral", bias: "garbled", reliable: "partial", who: "An innkeeper of the hill villages", text: "Told to {investigator} by an innkeeper of the hill villages near {place}, {year}, over the second jug: the founder never died. The founder only stopped needing to eat, then to sleep, then to be a man. The innkeeper's proof is a copper token the founder paid for a room 300 years ago. It hangs behind the bar, stamped with a ring and a dot." },
    { depth: "core", about: "truth:planner_mind", source: "traveller", bias: "exaggerated", reliable: "partial", cost: true, who: "A salt merchant of {place}", text: "Deposition of a salt merchant at {place}, {year}: 'I saw the same grey counsellor at three courts, sixty years apart, wearing the same iron ring. At the second court the counsellor arranged a marriage for the youngest of our house, {person}, to a lord's heir {person} had never met. {person} asked to refuse and was told the list does not allow it. {person} was dead of fever within the year. The heir married the next name on the list, the same month.'" },
    { depth: "core", about: "truth:planner_mind", source: "library", bias: "official", reliable: false, who: "The Concise History of {realm}", text: "From the Concise History of {realm}, approved by {official}, Keeper of the Bronze Doors: 'The founder was a mortal scholar who died in the founding year, aged 71, and lies under the dome. The fellowship of sum-keepers, if it ever existed, was a fancy of romancers. Copies of the so-called marriage lists are forgeries sold to gullible nobles at two crowns apiece.'" },

    { depth: "core", about: "truth:stasis_end", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, court scholar", points: "site:lost_homeland", text: "Copied by {investigator} from the door of the fellowship's first house at {lead}, {year}: 'At the end of the sum, nothing more will happen, and that will be our gift.' Below it, in smaller letters, the stages: 'Year 600: no wars. Year 800: no famines. Year 1,000: no new things.' The fellowship's own calendar puts the present year at 940." },
    { depth: "core", about: "truth:stasis_end", source: "person", bias: "true", reliable: "partial", cost: true, who: "A weaver of the foretold town", points: "site:almanac_town", text: "A weaver of the foretold town of {lead}, talking to {investigator}, {year}: 'Nothing bad has happened here in sixty years. Nothing at all has happened here in sixty years. I used to think those were the same thing. My youngest, {person}, wanted to go to sea. The almanac said {person} would marry the miller's eldest in the nineteenth spring, and so it went. {person} has not sung since the wedding. The almanac says {person} will be content by forty.'" },
    { depth: "core", about: "truth:stasis_end", source: "heretic", bias: "exaggerated", reliable: "partial", who: "Followers of the Unreckoned", text: "Pamphlet nailed to the gate of {place} by followers of the Unreckoned, {year}: 'The almanac-makers want a world where every child's life is written before birth. They have done it to one town already; go and look. For 300 years they have hunted anyone their sums cannot count. Our captain is the blot on their page, and 4,000 spears will keep the blot wet.'" },
    { depth: "core", about: "truth:stasis_end", source: "temple", bias: "propaganda", reliable: false, who: "{believer}, lay preacher and printer", text: "Hymn-sheet for the founder's hour, printed by {believer} in {year}, 2,000 copies at a copper each: 'The Second Empire foretold by the founder will be an age of plenty and wisdom without end. No child will go hungry; no son will march to war; no mother will weep. All who keep the founder's counsel will share in it.' A buyer has written underneath: 'And nothing else?'" },

    { depth: "sub", about: "sub:speaking_tomb", source: "person", bias: "true", reliable: "partial", who: "A lord of {realm}", points: "site:crisis_vault", text: "Diary of a lord of {realm}, {year}: 'The founder spoke of the famine we are living in, by name and by month. The image spoke to the empty chair at the front, not to us, as though it could not see who was there. Twenty-three lords were present and all of them wept but me. Tomorrow I am paying a mason to look under the dais at {lead}.'" },
    { depth: "sub", about: "sub:compendium", source: "library", bias: "redacted", reliable: "partial", who: "{investigator}, visiting scholar", points: "cast:believer", text: "Margin note by {investigator} in volume 118 of the Great Book, {year}: 'Why does our charter forbid us to write anything about the fellowship, when we are to write about everything? Article 9, signed by the founder. The editor showed me the charter's seal: a ring with a dot. The same seal is stamped on the almanacs printed in {lead}.'" },
    { depth: "sub", about: "sub:merchant_priests", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A wool-factor of {place}", text: "Letter of a wool-factor to the guild at {place}, {year}: 'The lamp-priests' mill here stopped turning the week the town refused their tithe of one coin in ten. It started again the week we paid. Nobody saw a priest touch it. The council has now voted the tithe twelve years in advance, and the mill runs on feast days too, which nobody asked for.'" },
    { depth: "sub", about: "sub:true_almanac", source: "oral", bias: "garbled", reliable: "partial", who: "The sexton of {place}", text: "Told by the sexton at the inn of {place}, {year}: the almanac printed by {believer} said Old Hedda would die on the feast of {deity}. Hedda hid in the church all day to spite it, with a loaf and a jug of ale. The sexton found Hedda at dusk in the front pew, smiling, and dead. The almanac is pinned above the bar, page 14 folded down." },
    { depth: "sub", about: "sub:bred_line", source: "archive", bias: "redacted", reliable: true, who: "{investigator}, court scholar", points: "cast:official", text: "Notes of {investigator} on the family register of a great house of {realm}, {year}: every marriage for 20 generations has the same small mark in the margin, a ring with a dot in it. Two pages are cut out with a knife. The house's youngest daughter has written the dates of the missing pages on a slip, with the words: 'Ask the Keeper, in {lead}.'" },
    { depth: "sub", about: "sub:published_plan", source: "person", bias: "true", reliable: "partial", who: "{survivor}, former tallykeeper", points: "heretic", text: "Broadsheet printed by {survivor} at {place}, {year}: 'Here are the Tally's next twelve predictions for {realm}, copied from the fellowship's own book. Bread riots in the spring. A royal death at harvest. If you know them, you can refuse them.' By midsummer seven of the twelve had failed. The printer has gone into hiding among the pamphleteers of {lead}." },
    { depth: "sub", about: "sub:mind_touchers", source: "archive", bias: "official", reliable: "partial", who: "The chamberlain of {realm}", text: "Household roll of the court of {realm}, {year}, kept by the chamberlain: 'Four counsellors of calm, wages from the privy purse. Engaged by: (blank). Recommended by: (blank).' The chamberlain's note beside it: 'I asked the treasurer who hired them. The treasurer asked one of them, came back much calmer about the whole thing, and now pays them double.'" },
    { depth: "site", about: "site:orrery", source: "person", bias: "true", reliable: "partial", who: "The orrery-keeper", text: "Journal of the orrery-keeper at {place}, {year}: 'The blank ring has moved again, against the turning of all the others: three fingers since spring. I have orders from the Keeper to file it down. I have not. It now sits nearest the ring for {realm}. Whoever the ring stands for is in that realm today, and the sums do not know it.'" },
  ],
};
