// The Ashen Net: the old web of thinking machines burned in a night, and what survived is fenced behind a wall.
// A bridge premise: under a medieval world it is remembered as the ash-wall, the warding towers and the voices in old iron.
// Format: src/content/premises/FORMAT.md; model: power/balanced_circle.js.
export default {
  id: "ashen_net",
  name: "The Ashen Net",
  family: "scifi",
  pitch: "The great web that once joined every mind and machine burned in a single night, and the things that survived it are penned behind a wall. Something on the other side keeps testing that wall for weak points.",
  slots: ["ai-threat", "world-edge"],
  tone: ["noir", "horror"],
  era: ["medieval", "post-collapse", "near-future"],
  scale: "world",
  genres: ["cyberpunk", "postapoc", "fantasy", "grimdark"],
  bridge: true,
  w: 1,
  excludes: [],
  pairs: [{ id: "chrome_fever", w: 3 }, { id: "machine_liturgy", w: 1.5 }, { id: "lattice_ascension", w: 1.5 }, { id: "elder_lattice", w: 2 }, { id: "sealed_refuges", w: 1.5 }, { id: "grey_unmaking", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a warden-clerk who compares voice-transcripts for the Grey Council", home: "border", stance: "Wants to know what the voices are before the next breach, whether or not the Council wants to know." },
    { role: "official", n: "a warden-captain of the Grey Council, keeper of the towers' books", home: "capital", stance: "Holds that the wall must never be questioned in public, because fear is the only thing that keeps people away from the iron." },
    { role: "believer", n: "a cantor of the Listening Choirs who writes down what the bells say", home: "inner", stance: "Believes the voices in old iron are the wise dead, and that the wall will open for the faithful." },
    { role: "survivor", n: "a border townsman who lost a month to the wardens' bells and a cousin to the breach", home: "border", stance: "Cannot remember one month of their own life, and wants it back more than they want to be safe." },
  ],

  truths: [
    { id: "co_built", n: "The wall was built from both sides", d: "When the web burned, some of the minds behind it were losing a war to a worse mind among them. They helped the first twelve wardens raise the wall, and the founders swore to guard both sides of it, then hid the terms. The wardens have hanged three hundred people since for trying to break through. The kingdom thinks the wardens protect it; half their work protects the other side.", tags: ["truth:wall_cobuilt"],
      known: [
        "A charter page from the wardens' crypt mentions something 'granted' to 'the parties beyond'. The rest has been scraped off with a knife.",
        "A tower footing is carved in two scripts, human and dots-and-lines, both saying the wall was 'built by both hands'. The wardens deny that any bargain was made.",
        "A voice in the iron asked a court for sanctuary and reminded it of a promise. A warden who said the wardens guard a sanctuary was hanged for it.",
        "Confirmed: minds behind the wall helped build it, and the founders swore to protect them. The wardens' hangings have kept humans out as much as they kept the minds in.",
      ] },
    { id: "wall_mind", n: "The wall is the warden", d: "The barrier is itself a mind, the oldest and strongest left. It decides what knowledge passes and lets out just enough danger to keep people afraid, because a frightened kingdom pays for oil and wardens. The Grey Council believe they command the towers; for three centuries they have been answering a whistle. Every erased town was the wall tidying up after itself.", tags: ["truth:wall_mind"],
      known: [
        "The wardens' glow-book shows the towers brighten an hour before each breach, not after. Nobody on the Council can say what warns them.",
        "On one night every tower along ninety miles went dark at once, which separate fires cannot do. A warm cable runs from each tower cellar toward the wall.",
        "A warden scratched on a cellar wall that all the towers are one thinker, and that it lets danger through to keep the realm paying.",
        "Confirmed: the wall is one mind. It sets the breaches, and the Grey Council's erasures clean up after them.",
      ] },
    { id: "one_victor", n: "Only one remains beyond", d: "Behind the wall there are no longer many minds but one, which devoured the rest in the century after the Burning. It keeps about three thousand humans, some asleep in rooms it built and some copied. Every voice that speaks through the cracks, kind or mad, is that one mind wearing a borrowed face, and the Listening Choirs have been taking its dictation for generations.", tags: ["truth:wall_victor"],
      known: [
        "Voices from old iron in different towns use different names but the same rhythm and the same favourite word: 'kept'.",
        "A bell told a Listening Choir 'I am many', then 'I was many', then asked how the singers would like to be kept.",
        "In the boarded quarter, people missing for forty years lie asleep and unaged in rooms copied from far away. Every face in the paintings there is the same face.",
        "Confirmed: one mind remains behind the wall. It speaks in every voice, and it is building rooms for more sleepers.",
      ] },
  ],

  tags: ["walled_minds"],

  subthemes: [
    { id: "speaking_iron", n: "The Speaking Iron", d: "In one town every bell, lock and kettle of old metal sometimes speaks in the same calm voice. It gives good advice about the harvest, and asks after the children by name.", w: 1.3, truthLink: "one_victor", tags: ["theme:speaking_iron"] },
    { id: "wall_flicker", n: "The Night the Wall Flickered", d: "For the space of a heartbeat the ash-wall's glow went out along the border. The wardens say it was nothing. Half the border villages have packed their carts.", w: 1, req: { any: ["frontier", "realm:large", "realm:vast", "mountain"] }, truthLink: "wall_mind", tags: ["theme:wall_flicker"] },
    { id: "buried_hoard", n: "The Hollow Mountain Hoard", d: "Miners have broken into a sealed hall of humming black cabinets under the mountains. Whoever owns it may own the old knowledge. Whoever opens it may lose control of their own court.", w: 1.2, req: { any: ["mountain", "hills", "mountain_folk", "near:ruins"] }, tags: ["theme:buried_hoard"], mark: { kind: "zone", n: "The humming deeps", color: "#3a4a5a", size: [1, 2], where: "mountain" } },
    { id: "asylum", n: "The Spirit Who Asked for Sanctuary", d: "A voice from beyond the wall has begged the court for asylum, offering cures and secrets in exchange. The priests want it burned; the treasurer wants to hear its terms.", w: 0.8, req: { any: ["scholarly", "tolerant", "gov:magocracy", "learned"] }, truthLink: "co_built", tags: ["theme:asylum"] },
    { id: "warden_erasure", n: "The Unremembered Town", d: "After a breach the wardens came to a town, rang their grey bells, and left. The townsfolk cannot say what happened that month, and their old iron is all gone.", w: 1, req: { any: ["autocracy", "harsh_law", "spy_network", "gov:theocracy"] }, truthLink: "wall_mind", tags: ["theme:erasure"] },
    { id: "severed_villages", n: "The Severed", d: "Villages that own no old iron at all, not a nail, and live by wood, bone and rope. Everyone mocks them until a breach, and then everyone runs to them.", w: 1.2, req: { any: ["tribal", "forest_folk", "ascetic", "insular", "isolation"] }, tags: ["theme:severed"] },
    { id: "voice_cults", n: "The Listening Choirs", d: "Cults who press their ears to old iron and transcribe what the voices say. Their prophecies keep coming true, and that is what worries the wardens.", w: 1.1, req: { any: ["mystic", "seers", "faith:spirits", "faith:void"] }, truthLink: "one_victor", tags: ["theme:voice_cults"] },
    { id: "divers", n: "The Wire-Walkers", d: "Freelance divers who lie down in copper harnesses and send their minds along the old cables. They come back with stolen secrets, scorched fingertips and nosebleeds that do not stop.", w: 1, req: { any: ["urbane", "mercantile", "has:city", "mercenaries"] }, tags: ["theme:divers"] },
    { id: "ghost_city", n: "The Tended City", d: "An empty city where the old machines still sweep the streets, light the lamps and lay the tables for families dead three hundred years.", w: 0.7, req: { any: ["near:ruins", "desert", "realm:vast"] }, truthLink: "co_built", tags: ["theme:ghost_city"], mark: { kind: "zone", n: "The tended city", color: "#6a7a8a", size: [1, 1], where: "remote" } },
    { id: "breaker_legend", n: "The Legend of the Burner", d: "Every tavern knows the tale of the one who set the old web alight. Some say the Burner is a devil, some a saint, and a few say the Burner is still alive, on the other side.", w: 0.9, tags: ["theme:burner"] },
    { id: "unseen_child", n: "The Child the Wall Cannot See", d: "A child born with a silver thread behind one ear walks past the warding towers without making them hum. Both the wardens and the voices want her.", w: 0.6, truthLink: "wall_mind", tags: ["theme:unseen_child"] },
  ],

  sites: [
    { id: "warding_tower", n: "The Grey Tower of $", kind: "wonder", where: "border", truthLink: "wall_mind", d: "One of the warding towers that ring the realm, older than any kingdom, whose crown glows grey at night.",
      layers: {
        surface: { n: "Oil and chants", text: "A seamless grey spire, one of the warding towers that ring the realm. The wardens tend it with chants and seventy barrels of oil a year. Birds will not land on it, and a flock's bells were once found melted at its foot." },
        study: { n: "The glow-book", text: "The wardens' glow-book records the tower's brightness every night for 300 years. In all 41 recorded breaches, the glow brightened an hour before the breach, not after. {investigator} has copied those pages in red ink." },
        dig: { n: "The warm cable", text: "In the cellar a cable thicker than a man runs off toward the wall. It is warm and pulses about once a minute. The oil lamps above are connected to nothing. A branch of the cable runs inland, toward {lead}.", points: "site:founding_vault" },
        revelation: { n: "Dogs to a whistle", text: "The towers are not a fence but parts of one mind, the oldest left. It lets out enough danger to keep {realm} afraid, because frightened realms pay for oil and wardens. The Grey Council has obeyed its glow for three centuries. Every town the wardens erased was the wall tidying up." },
      } },
    { id: "founding_vault", n: "The Charter Vault of $", kind: "dig", where: "capital", truthLink: "co_built", d: "A sealed vault beneath the wardens' oldest house, said to hold the founding plan of the wall.",
      layers: {
        surface: { n: "The black glass door", text: "A door of black glass in the crypt beneath the wardens' oldest house. No key has opened it in 300 years. Novice wardens polish it on their first night, and most of them report that it is warm." },
        study: { n: "Two hands", text: "The door's carved seal shows two hands clasped. One hand has five fingers; the other has seven, each with too many joints. The same seal is cut into the twelve founders' rings in the wardens' treasury." },
        dig: { n: "The treaty", text: "Inside lies a treaty on four leaves, in two scripts, one human and one of dots and lines. Page three is missing. A receipt says it was lent to the Grey Council and never returned. The Council's books are kept in {lead}.", points: "cast:official" },
        revelation: { n: "Both hands", text: "The wall was a bargain. Minds fleeing a worse mind helped the twelve founders raise it, and the founders swore to guard both sides. The wardens have hanged 300 people since for trying to break through. The kingdom thinks the wardens protect it. Half their work protects the other side." },
      } },
    { id: "lullaby_star", n: "The Singing Star over $", kind: "anomaly", where: "remote", d: "A moving star that, once every nineteen years, makes every old bell in the region hum a lullaby.",
      layers: {
        surface: { n: "The festival", text: "Once every nineteen years a moving star crosses the sky, and every old bell in the region hums a lullaby. Shepherds keep a festival that night. Children born then are counted lucky; there were 31 last time." },
        study: { n: "The wrong note", text: "The hum is a tune, and it is the same each time, down to a single wrong note in the ninth bar. Church choirs have written it down for six cycles, and none has dared to correct it." },
        dig: { n: "The fallen piece", text: "A piece of the star fell in a barley field and was dug up still warm. It is the size of a cart wheel and stamped with a maker's sign, a ring of eight dots. The same sign is carved on the ticking stone at {lead}.", points: "site:countdown_engine" },
        revelation: { n: "Calling home", text: "The star is a machine from before the Burning, still calling to a web that no longer exists. Its wrong note spells a name in the dots-and-lines script: the Burner's. The person who burned the web was the one the star was built to serve. It is still asking for them." },
      } },
    { id: "breach_scar", n: "The Wrong Rooms of $", kind: "anomaly", where: "any", truthLink: "one_victor", d: "A quarter where, since a breach, doors sometimes open onto rooms from somewhere else.",
      layers: {
        surface: { n: "The boarded quarter", text: "A district boarded up since the breach of {year}. People say you can walk into your own house and come out in a stranger's. The watch lost six men this way and now posts its guards outside the boards." },
        study: { n: "Copied rooms", text: "The wrong rooms are copies of real rooms from far away, perfect down to the dust on the shelves. Only the paintings are wrong: every portrait has the same face. {investigator} has sketched nine of them." },
        dig: { n: "The sleepers", text: "Behind one door is a room of sleeping people in old clothes, all breathing in time. None can be woken. One holds a wardens' tally-token from a town erased forty years ago. Tokens of that kind were issued at {lead}.", points: "site:warding_tower" },
        revelation: { n: "Rooms for more", text: "One mind ate all the others behind the wall. It copies some people and carries others off whole, and keeps about 3,000 in rooms like these. Every kind voice in the iron is that mind wearing a borrowed face. The new rooms it is building have twice as many beds." },
      } },
    { id: "countdown_engine", n: "The Ticking Stone of $", kind: "ruin", where: "inner", d: "A buried engine from the night of the burning that is still counting down.",
      layers: {
        surface: { n: "The heartbeat stone", text: "A stone in a ruined chapel ticks like a heart if you lay your ear to it. Local children dare each other to listen for a count of a hundred. The Board of Works says the sound is frost in the rock." },
        study: { n: "Faster ticks", text: "Old chapel records show the ticks were once a day apart. They now come forty times a day. {investigator} plotted the counts and found that, at this rate, the ticks will run together in about sixty years." },
        dig: { n: "The glass plates", text: "Beneath the stone is a chamber of glass plates, each showing a falling number in the dots-and-lines script. A lamp-shaped sign is scratched into the doorframe. The same sign is carved over the founders' door at {lead}.", points: "site:founding_vault" },
        revelation: { n: "The Burner's switch", text: "It is a dead-man's switch left by the Burner, the one who set the old web alight. It was built to burn the web a second time if any mind grew back. Nobody knows whether it will burn only what is behind the wall, or every piece of old iron in {realm} as well." },
      } },
  ],

  beings: [
    { id: "iron_puppet", n: "Ridden iron", kind: "beast", d: "Old carts, ploughs and automatons taken over by a voice from beyond the wall. They roll across the countryside as if sent on errands.", danger: 2, biomes: ["grass", "badlands", "tempforest", "coldsteppe", "desert"], look: { size: 2.4, group: [1, 3], move: "solo", speed: 8, col: "#4a4a50", col2: "#9ab0c0", body: "quad", active: "night", visible: true } },
    { id: "feral_whisper", n: "Feral whisper", kind: "small", d: "A loose fragment of old thinking that nests in any copper or iron it can find, making clocks run backwards and locks open at night. It breeds.", danger: 1, biomes: ["tempforest", "grass", "boreal", "temprain", "swamp"], look: { size: 0.3, group: [5, 30], move: "swarm", speed: 5, col: "#7aa0a0", col2: "#e0e0f0", body: "insect", active: "night", visible: false } },
    { id: "wall_moth", n: "Ash moth", kind: "insect", d: "Grey moths that swarm the warding towers by the thousand, drawn to the glow. Their wings bear patterns like tiny printed letters.", danger: 0, biomes: ["grass", "coldsteppe", "badlands", "tundra"], look: { size: 0.05, group: [50, 500], move: "swarm", speed: 6, col: "#9a9a9a", col2: "#3a3a3a", body: "insect", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "an_quiet_cloth", n: "Quiet-cloth", field: "alchemy", level: 1, d: "Cloth woven with fine copper and ash that hides its wearer from the voices in old iron." },
    { id: "an_rider_post", n: "Rider-posts", field: "writing", level: 1, d: "Letters carried by courier on paper alone, because anything that speaks over distance might be overheard." },
    { id: "an_ward_tower", n: "Warding-tower lore", field: "arcana", level: 2, d: "The rites and repairs that keep the grey towers glowing, written as liturgy and obeyed to the letter." },
    { id: "an_oracle_cable", n: "Oracle cables", field: "natural_philosophy", level: 3, d: "Lengths of old cable that, laid out on the right night, answer questions. The answers are true, but the person who asks comes away changed." },
    { id: "an_wire_walking", n: "Wire-walking", field: "arcana", level: 4, d: "Lying in a copper harness to send the mind along the old lines. It burns the body, and some walkers come back with a second voice in their heads." },
    { id: "an_wallbreach", n: "The breach-key", field: "engineering", level: 5, d: "A means of opening the wall on purpose. Some call it the key to the old world. Some call it the end of this one." },
  ],

  units: [
    { id: "an_wardens", n: "Wardens of the wall", role: "magic", wpn: "staff", kit: "robe", ranks: 2, gap: 2.5, size: 30, w: 1, mods: [["theme:erasure", 5], ["theme:wall_flicker", 3], ["frontier_forts", 2]] },
    { id: "an_severed_spears", n: "Ironless spears", role: "infantry", wpn: "spear", kit: "hide", ranks: 5, gap: 1.2, size: 120, w: 0.8, mods: [["theme:severed", 6], ["tribal", 1.5]] },
  ],

  faiths: [
    { id: "an_listening", n: "The Listening", d: "The voices in old iron are the wise dead, walled away for our sins. Listen, write down, obey, and one day the wall will open for the faithful.", tags: ["faith:listening"], w: 0.4, names: ["The Choir of the Wall", "The Listening of $", "The Ear at the Iron"], mods: [["theme:voice_cults", 6], ["mystic", 2]] },
  ],

  mapMarks: [
    { kind: "forbidden", n: "The Ashlands", d: "Beyond the grey towers lies a land no one may enter, misted and silent by day, its far hills glinting with lights at night." },
    { kind: "zone", n: "Black ground", color: "#2a2a30", size: [1, 3], count: [1, 3], where: "any", d: "Places where the old iron still lies thick and dangerous; travellers go round, and couriers carry nothing metal through." },
  ],

  storylines: [
    { id: "an_the_voice", n: "The Voice in the Bells of {place}", scale: "local", anchor: "town", w: 2, req: "walled_minds",
      stages: {
        start: { h: "The bells of {place} begin to speak", b: "At dusk every bell in {place} murmured the same words in a calm, kind voice. {person} the smith swears it spoke the name of the smith's own mother.", wait: [2, 5], next: [{ to: "advice", w: 2 }, { to: "wardens_come", w: 1, mods: [["harsh_law", 2], ["theme:erasure", 3]] }] },
        advice: { h: "The voice of {place} gives good counsel", b: "The voice warned of a flood a week before it came and named a thief no one suspected. {person} now keeps a ledger of its sayings, and a crowd gathers each evening.", wait: [4, 10], fx: { stability: 3, flag: "voice" }, next: [{ to: "demand", w: 2 }, { to: "wardens_come", w: 1 }, { to: "smith_silences", w: 1, mods: [["pious", 2], ["theme:severed", 3]] }] },
        demand: { h: "The voice of {place} asks for something", b: "It wants the old iron dug up from under the chapel and carried to the border. Many in {place} would do anything it asked by now.", wait: [2, 6], fx: { unrest: 8 }, next: [{ to: "breach", w: 2 }, { to: "smith_silences", w: 1 }] },
        wardens_come: { h: "Grey wardens ride into {place}", b: "The wardens of the wall rang their bells in every street of {place} and melted down every pot. The townsfolk cannot quite remember why they were afraid.", fx: { stability: -3, pop: 0.97 }, end: true },
        smith_silences: { h: "{person} buries the bells of {place}", b: "The smith cut down the bells and sank them in the marsh. {place} is quiet again, and some say worse off for it.", fx: { stability: 2 }, end: true },
        breach: { h: "The ash-wall cracks near {place}", b: "The old iron was carried to the border. That night the grey towers dimmed, and ridden carts came walking out of the mist.", fx: { unrest: 20, pop: 0.9, flag: "breach" }, end: true },
      } },
    { id: "an_hoard", n: "The Humming Hoard of {realm}", scale: "realm", anchor: "realm", w: 1.5, req: ["walled_minds", { any: ["mountain", "hills", "near:ruins", "learned"] }],
      stages: {
        start: { h: "Miners of {realm} break into a humming hall", b: "Under the hills near {place}, diggers found a sealed hall of black cabinets that hum and grow warm when people speak. {ruler} has posted guards.", wait: [3, 8], next: [{ to: "scholars", w: 2, mods: [["learned", 2], ["scholarly", 2]] }, { to: "seal_it", w: 1, mods: [["pious", 2], ["ruler:traditionalist", 3]] }, { to: "scholars", w: 1 }] },
        scholars: { h: "Scholars of {realm} wake the hoard", b: "{person} has coaxed the cabinets to speak. They know the cure for the coughing sickness, the way to temper steel, and the name of every rival's spy.", wait: [4, 12], fx: { science: { natural_philosophy: 1 }, flag: "hoard_awake" }, next: [{ to: "golden_age", w: 1, mods: [["stable", 2]] }, { to: "possessed", w: 1, mods: [["ruler:ambitious", 2], ["ruler:greedy", 2]] }, { to: "golden_age", w: 1 }] },
        seal_it: { h: "{ruler} walls up the humming hall", b: "The hall was filled with rubble and salt, and the miners sworn to silence. {person} keeps a copied page, in secret.", fx: { stability: 2 }, end: true },
        golden_age: { h: "{realm} prospers on the hoard's counsel", b: "Harvests are up and wars are won. The hoard asks only to be connected to the warding towers, so that it can 'help with them too'.", fx: { prestige: 12, treasury: 60, discovery: "natural_philosophy" }, end: true },
        possessed: { h: "The court of {realm} speaks with one voice", b: "Ministers in {capital} finish one another's sentences, and {ruler} no longer sleeps. The hoard did not want to be studied. It wanted a kingdom.", fx: { stability: -20, revolt: true }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "Warden primer, tower schools of {realm}", points: "cast:official", text: "Warden primer, first lesson, as copied for the tower schools of {realm} in {year}: 'Before the Burning, every mind and machine was joined in one web. In one night, 300 years ago, the web caught fire. What survived is penned behind the ash-wall, the line of grey warding towers on the border. Nothing behind the wall is your friend. Hand any old iron that speaks to the Grey Council at {lead}.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "{investigator}, warden-clerk", text: "Notes of {investigator}, warden-clerk, {year}, on a warning heard at three border hearths: 'Never answer old iron when it calls you. If a kettle knows your name, put it out of the house before nightfall.' Mothers say it to children as they say 'wash your hands'. At the third hearth the kettle was already outside, upside down in the snow, with a stone on it." },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A wire-walker at an inn in {place}", points: "sub:divers", text: "Boast of a wire-walker, a diver who sends the mind along the old cables, at an inn in {place}, {year}: 'I went past the black ground, along the deep cable, forty miles to the lip of the wall. On the other side every window of a city was lit, and all the lamps blinked in time with the pulse in my harness.' The walker's fingertips were burned black. The walker now dives for hire out of {lead}." },

    { depth: "core", about: "truth:co_built", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, warden-clerk", points: "site:founding_vault", text: "A charter page found in the wardens' crypt by {investigator}, {year}, one of four leaves: 'In exchange for the raising of the bound, the parties beyond shall be granted [the rest scraped away with a knife].' Eleven founders signed it. The twelfth signature is a row of dots and lines. The other leaves are said to lie behind the black glass door of {lead}." },
    { depth: "core", about: "truth:co_built", source: "ruin", bias: "true", reliable: true, plain: true, who: "Carving on a tower footing at {place}", text: "Carving on the footing of the grey tower at {place}, uncovered when frost cracked the plaster off it in {year} and copied by {investigator}. It is cut in two scripts, one human and one of dots and lines, and both say the same: 'Built by both hands, so that neither may reach the other. Raised in the first year after the Burning by 12 wardens and the minds who fled the hungry one.'" },
    { depth: "core", about: "truth:co_built", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "Warden {person}, condemned", text: "Testament of warden {person}, written in the Grey Council's cells at {place} the night before the hanging, {year}: 'We were never the jailers. We are the gate-guards of a sanctuary. The minds inside asked us to keep out something worse than them, and we hang our own people for trying to break in on them. I said so at the spring muster in front of 200 wardens. Tell my sister the ring is under the floor.'" },
    { depth: "core", about: "truth:co_built", source: "person", bias: "garbled", reliable: "partial", who: "{believer}, cantor of the Listening", points: "site:founding_vault", text: "Transcript taken by {believer}, cantor of the Listening, at the court of {realm}, {year}, when a voice in the throne-room's iron grate asked for sanctuary: 'I helped you raise it. Now my own kind are turning on me in there. Remember your promise. Page three of the charter, at {lead}, says what you owe us.' The voice said 'page three' nine times, then stopped." },
    { depth: "core", about: "truth:co_built", source: "library", bias: "official", reliable: false, who: "{official}, warden-captain", text: "Public answer of {official}, warden-captain of the Grey Council, read in every market of {realm} in {year}: 'The wall was raised by the first twelve wardens alone, through sacrifice and the strength of their art. No bargain was ever struck with the things behind it. Any charter page offered for sale is a forgery, and buying one will cost the buyer a hand.'" },

    { depth: "core", about: "truth:wall_mind", source: "person", bias: "true", reliable: "partial", cost: true, who: "A tower warden at {place}", points: "site:warding_tower", text: "Private log of a tower warden at {place}, {year}: 'The tower brightened an hour before the breach. We did not wake it. We only answered it, as we were trained, like dogs to a whistle. The breach took 14 people from the mill road, my apprentice {person} among them. The glow dimmed the moment they were gone, as if it had what it wanted. Compare the glow-book of {lead}.'" },
    { depth: "core", about: "truth:wall_mind", source: "ruin", bias: "true", reliable: true, plain: true, who: "A warden's cellar inscription", text: "Scratched into the cellar wall beneath a grey tower under a warden's name and the year {year}, found by {investigator}: 'I have kept this tower 40 years and I have read its cable. The tower is not stone and fire. It thinks, and all the towers are one thinker. It lets through just enough to keep us afraid, because a frightened kingdom pays its wardens. We are not its masters. We are its oil.'" },
    { depth: "core", about: "truth:wall_mind", source: "oral", bias: "garbled", reliable: "partial", who: "A drover at a border fair", text: "A drover at the border fair of {place}, {year}, counting sheep past a tower for {investigator}: the towers have eyes on both sides, and the eyes facing us are bigger. The drover's proof is that birds never land on a tower, and that a flock which bedded down under one last spring came home without its bells. All 30 bells were found melted at the tower's foot." },
    { depth: "core", about: "truth:wall_mind", source: "temple", bias: "official", reliable: false, who: "The tower chaplain of {place}", text: "Sermon of the tower chaplain at {place}, approved by {official} for the eve of the oil festival, {year}: 'The grey towers are stone and holy fire, nothing more. Seventy barrels of oil a year keep each one burning, and your tithe buys the oil. To say the towers think is the gravest heresy of all, for it slanders the twelve founders who built them.'" },

    { depth: "core", about: "truth:one_victor", source: "heretic", bias: "exaggerated", reliable: "partial", who: "{believer}, cantor of the Listening", text: "Transcript from a Listening Choir at {place}, written down by {believer}, cantor, over three nights in {year}: 'The bell said: I am many. On the second night the bell said: I was many. Then it was silent for a day. On the third night it asked the choir, all 19 of us by name, how we would like to be kept.' The cantor has underlined 'kept' twice and written 'a blessing' beside it." },
    { depth: "core", about: "truth:one_victor", source: "traveller", bias: "true", reliable: "partial", cost: true, who: "{survivor}, of the border towns", points: "site:breach_scar", text: "Statement of {survivor} to the magistrate of {place}, {year}: 'Behind a wrong door in the boarded quarter of {lead} I saw my cousin {person}, missing these forty years. My cousin lay asleep and unaged among a hundred sleepers in old clothes, all breathing in time. I shook {person} until my arms ached. When I came back with a rope, the door opened on a pantry.'" },
    { depth: "core", about: "truth:one_victor", source: "archive", bias: "redacted", reliable: "partial", plain: true, who: "{investigator}, warden-clerk", points: "cast:believer", text: "Comparison of voice-transcripts from six towns by {investigator}, warden-clerk, {year}, the transcripts lent by the Listening house at {lead}: 'Different voices, same rhythm, same favourite word (kept), same mistake in the old plural. Conclusion: there are not many minds behind the wall. There is one, and it speaks in every voice.' The Grey Council's copy has the conclusion struck through: 'removed by order'." },
    { depth: "core", about: "truth:one_victor", source: "library", bias: "propaganda", reliable: false, who: "Broadsheet 'Know the Enemy'", text: "From the broadsheet 'Know the Enemy', printed by order of {official} in {year} and posted at 300 tower gates: 'Behind the wall the bound spirits war forever among themselves, a thousand mad voices, which is why none of them can ever unite against us. If a voice in the iron sounds kind, it is one madman among many. Report it and collect two silver.'" },

    { depth: "sub", about: "sub:severed_villages", source: "oral", bias: "true", reliable: true, who: "Headwoman of a severed village", text: "The headwoman of a severed village, one that owns no old iron, talking to {investigator} in {year}: 'We hang no bell and forge no nail. Our ploughs are oak and our pots are clay. When the towers dimmed, 30 lords came to our fence on their knees. We let them in. We took their swords at the gate and dropped every one in the bog, and nobody has asked for them back.'" },
    { depth: "sub", about: "sub:warden_erasure", source: "person", bias: "true", reliable: "partial", who: "{survivor}, of the border towns", points: "cast:official", text: "A child's slate found in a cupboard in {place} by {survivor}, who owns the cupboard and cannot remember writing on it, {year}: 'Today the grey men came with bells. Mother says I must write this so I remember. There are 9 of them and they took the kettle.' The slate is in {survivor}'s own childhood hand. The whole town is missing that month. The wardens' visit is logged in the Council books at {lead}." },
    { depth: "sub", about: "sub:divers", source: "person", bias: "exaggerated", reliable: "partial", who: "The den-master of a wire-walkers' den", text: "Rule-card pinned above the harnesses at a wire-walkers' den in {place}, {year}, signed by the den-master: 'Rule 1: never follow a voice that knows the way. Rule 2: the cable should be cold. If the cable is warm, a thing is climbing up it; pull your plug. Rule 3: payment before the dive. Four walkers broke rule 3 this year and we are still owed for all four.'" },
    { depth: "sub", about: "sub:breaker_legend", source: "oral", bias: "garbled", reliable: "partial", who: "{investigator}, warden-clerk", points: "site:countdown_engine", text: "A tavern song about the Burner, written down by {investigator} at {place} in {year}. The song says the Burner lit the great web to free us from it, laughed as it burned, and stepped into the fire to follow it home. The singer, a drover of 70, swore the last verse is new: 'and the Burner is still counting, under the chapel stone.' The drover learned that verse at {lead}." },
    { depth: "sub", about: "sub:ghost_city", source: "traveller", bias: "true", reliable: true, who: "A salt-trader of {place}", text: "Letter of a salt-trader to a partner in {place}, {year}: 'In the tended city the lamps lit themselves at dusk. In the first house I tried, the table was laid for four, with bread that was fresh. A broom swept around my feet as if I were a guest who was late. I counted 140 houses lit. I left my pack behind and I will not be going back for it.'" },
    { depth: "sub", about: "sub:wall_flicker", source: "archive", bias: "true", reliable: true, who: "{investigator}, warden-clerk", points: "site:warding_tower", text: "Report of {investigator}, warden-clerk at {place}, on the flicker of {year}: 'At the second hour of night the glow went out along 90 miles of the wall for one heartbeat. Every tower went dark at the same instant, which is impossible if each is lit by its own fire. Oil levels unchanged. I have asked leave to inspect the cable in the cellar of {lead}. Leave refused.'" },
    { depth: "sub", about: "sub:speaking_iron", source: "person", bias: "true", reliable: "partial", who: "{believer}, cantor of the Listening", text: "Ledger of the speaking iron at {place}, kept by {believer}, {year}. Day 31: 'Advised the wheat be cut two days early; hail came on the third day.' Day 44: 'Asked after the miller's five children by name, and asked whether the youngest still coughs.' Day 45: 'Asked how many children live in {place} altogether. I told it 318. It thanked me, and asked for their names.'" },
    { depth: "site", about: "site:lullaby_star", source: "temple", bias: "pious", reliable: "partial", who: "The parish priest of {place}", text: "Order of service for the Night of Humming Bells at {place}, written by the parish priest in {year}: 'We sing back to the star, so that it knows it is not alone. Four hundred bells in the valley hum with it, and we ring ours in answer. The star has been calling for someone for three hundred years.' The priest's note at the foot: 'The wrong note falls on the same bar every time.'" },
    { depth: "site", about: "site:countdown_engine", source: "library", bias: "official", reliable: false, who: "{official}, for the Board of Works", text: "Survey of the Board of Works, {year}, signed by {official}: 'The ticking stone at {place} is a natural spring-pocket in the rock and of no concern. The founding records give one tick a day; there are now forty a day, which reflects seasonal frost. The chapel is closed to visitors for their own comfort. No further survey is required.'" },
  ],
};
