// The Forgotten Landing: everyone came from the sky and forgot. The gods of the old songs were the crew,
// the holy mountain is a lander, and the ship is still up there. Bridge premise: in a medieval world the ship
// is the wandering star, the crew's duties are liturgy, and the ship's keys are heirloom rings.
export default {
  id: "forgotten_landing",
  name: "The Forgotten Landing",
  family: "scifi",
  pitch: "Everyone's ancestors came down from the sky in a burning ship, then forgot it. The gods of the old songs were the crew, the holy mountain is the landing craft, and the main ship is still up there, waiting for an answer.",
  slots: ["history-secret", "world-edge", "bloodline"],
  tone: ["wonder", "melancholy"],
  era: ["stone", "bronze", "medieval", "renaissance", "post-collapse", "far-future"],
  scale: "world",
  genres: ["fantasy", "mythic", "postapoc", "farfuture"],
  bridge: true,
  w: 1,
  excludes: ["painted_sky", "rim", "strewn_sky", "inner_sun", "splinter_world"],
  pairs: [{ id: "gardener_engine", w: 3 }, { id: "kindled_lineages", w: 2.5 }, { id: "machine_liturgy", w: 2 }, { id: "nursery_sea", w: 1.5 }, { id: "elder_lattice", w: 1.5 }, { id: "sworn_kindred", w: 1.2 }],

  cast: [
    { role: "investigator", n: "a star-reader who keeps the tables of the wandering star", home: "capital", stance: "Believes the wandering star is a made thing losing height, and wants the temple relics opened to scholars before it falls." },
    { role: "official", n: "a Watch-priest of the Manifest office, keeper of the temple relics", home: "mountain", stance: "Keeps the crew's old duties as holy rites, and holds that the sky-script must be prayed, never read." },
    { role: "believer", n: "a sky-seeker who climbs the holy mountain against temple law", home: "mountain", stance: "Is sure the Captain's crew are still up there, and that the right words spoken from the summit will bring them back." },
    { role: "survivor", n: "a hedge-warden whose family farm was lost to the wrong lands", home: "border", stance: "Wants the silver grass stopped, and no longer believes anyone who says salt will do it." },
  ],

  truths: [
    { id: "colony_ship", n: "The ship still waits above", d: "The ancestors came down from a colony ship that still circles the world as the wandering star. The mutineers who seized the first settlements burned its records and turned its crew into gods, so that nobody would ask to go home. The ship's mind is still awake and alone, it loses height every year, and it is still waiting for its lander to come back.", tags: ["truth:landing_ship"],
      known: [
        "Star-readers in several realms track a star that crosses the sky the wrong way, keeps its own time and sinks a little lower every decade. Nobody has explained why a star should run down like a clock.",
        "Painted metal stamped with sky-script falls in fresh craters, and a hatch on the holy mountain reads 'Lander Two. Return to ship.' The ancestors seem to have come down in a made thing from something larger.",
        "A founding charter kept by the oathbreakers' house orders the ship's records destroyed and its name never spoken. The forgetting was deliberate, and the navigator who refused was walled up with the log.",
        "Confirmed: the wandering star is the colony ship. Its mind is awake, it is breaking up, and within living memory someone aboard was still alive and tried to come down. The temple filed the man's letter as a prayer.",
      ] },
    { id: "shaping_halted", n: "The shaping stopped halfway", d: "The founders' engines were remaking this world into farmland when they failed at forty-nine per cent. The settlers' leaders hid the failure instead of rationing, so the green lands were never finished. The 'wrong lands' of silver grass are the world as it was, they take a few rods of barley every year, and they belonged to a six-fingered people the founders planted over.", tags: ["truth:landing_shaping"],
      known: [
        "Hedge-wardens report that the line between the green lands and the silver grass moves a few rods into the farmland every year. Salt does not stop it. The temple says the wrong lands were poisoned by an old war.",
        "A cold tower in the wrong lands holds a slate that stopped at forty-nine per cent, and a ring of ordinary soil around it shrinks each year. The green lands look planted, and only half planted.",
        "Stone rings deep in the silver grass are cut for six-fingered hands and carved with the burning house falling from the sky. Someone was already here to watch the landing, and their graves are still being dug.",
        "Confirmed: the founders were remaking a living world and stopped halfway. Their survey called the natives 'non-competing fauna'. The native life is taking the rest back, and the plough is losing.",
      ] },
    { id: "vessel_world", n: "The world is the ship", d: "There was no landing, because there is no outside. The world is the inside of a vessel still on its voyage: the sky is a ceiling, the seasons are set by its machines, and the grey cliff at the world's edge is its hull. The crew who knew the destination died long ago, and the almanac-makers have worked out that the voyage ends within a century.", tags: ["truth:landing_vessel"],
      known: [
        "Almanac-makers note that midsummer has not come a single day early or late in three hundred years of records. Nothing in nature is that punctual. The observatories call it a blessing of {deity}.",
        "Sailors who pass the last isles describe a warm grey cliff with no top, and a sea beside it with no tide. Four of nine ships came back. Their logs agree on every point.",
        "A door in the foot of the cliff is marked in sky-script: 'Maintenance access. Hull section nine.' A plumb line beside the cliff hangs eleven degrees off true. The cliff is a wall, and it is made.",
        "Confirmed: the world is the inside of a vessel still travelling. The seasons are run by its machines, and the voyage is nearly over. Nobody alive knows where it was going or how to open the doors when it arrives.",
      ] },
  ],

  tags: ["sky_ancestry"],

  subthemes: [
    { id: "holy_peak", n: "The Mountain the Gods Rode Down", d: "The holy mountain of the realm is too smooth on one face and hums in thunderstorms. Climbing it is forbidden; a young sky-seeker has just come down from it with a key-shaped burn on her hand.", w: 1.4, mods: [["mountain", 2], ["pious", 1.3], ["near:ruins", 1.5]], tags: ["theme:holy_peak"], mark: { kind: "zone", n: "The Holy Mountain", color: "#b8a27a", size: [1, 1], where: "mountain" } },
    { id: "wandering_star", n: "The Wandering Star", d: "One star crosses the sky the wrong way every dusk, faster than the rest. Star-readers have charted it for centuries; lately it has been crossing a little lower.", w: 1.3, mods: [["faith:stars", 3], ["seers", 2], ["desert", 1.3], ["scholarly", 1.5]], truthLink: "colony_ship", tags: ["theme:wandering_star"] },
    { id: "watch_priests", n: "The Priests of the Watch", d: "The temple keeps the old offices as holy ranks: the Watch, the Manifest, the Captaincy. Their liturgy is a list of duties, and some of the old chants still open real doors.", w: 1.3, req: { any: ["pious", "organised", "gov:theocracy", "ancestor_bound"] }, tags: ["theme:watch_priests"] },
    { id: "speaking_box", n: "The Voice in the Bronze Box", d: "A sacred box of dull metal, kept in the oldest shrine, has begun to speak after centuries of silence. It asks for someone by a title nobody has held since the founding.", w: 0.8, truthLink: "colony_ship", tags: ["theme:speaking_box"] },
    { id: "wrong_lands", n: "The Wrong Lands", d: "Beyond a line as sharp as a hedge, the grass is silver, the water tastes of tin and the beasts have six legs. Each year the line moves a little further into the farmland.", w: 1.3, mods: [["frontier", 2], ["realm:large", 1.3], ["near:beasts", 1.5]], truthLink: "shaping_halted", tags: ["theme:wrong_lands"], mark: { kind: "zone", n: "The Wrong Lands", color: "#9fb2b8", size: [2, 5], where: "remote" } },
    { id: "two_lines", n: "The Officers and the Oathbreakers", d: "Two great houses have feuded since the founding over a crime neither can name. One keeps the rings that open the old doors; the other keeps the reason the doors were closed.", w: 1, req: { any: ["monarchy", "hierarchical", "dynastic"] }, truthLink: "colony_ship", tags: ["theme:two_lines"] },
    { id: "iron_falls", n: "The Falling Iron", d: "Burning stones fall from the sky more often each decade. The craters hold smooth, painted metal and, once, a sealed door with a handle on the inside.", w: 0.9, truthLink: "colony_ship", tags: ["theme:iron_falls"], mark: { kind: "zone", n: "The Iron Falls", color: "#7a6a5a", size: [1, 2], where: "any" } },
    { id: "seed_ark", n: "The Seed Ark", d: "A cold vault under a monastery holds jars of seed for crops no one has tasted and frozen eggs of beasts no one has seen. The abbots open one jar a generation.", w: 0.9, mods: [["scholarly", 1.5], ["pious", 1.3], ["river", 1.3]], tags: ["theme:seed_ark"] },
    { id: "unwoken", n: "The Unwoken", d: "The temple's oldest list of names ends with a column headed 'still sleeping'. The pilgrims who say those names aloud on the feast day do not know they are a roll-call.", w: 0.8, mods: [["ancestor_bound", 3], ["faith:ancestors", 3]], tags: ["theme:unwoken"] },
    { id: "changed_kin", n: "The Changed Kin", d: "The high-valley folk breathe thin air without tiring, the marsh folk see in the dark, and each says the other is no longer quite the same people. The founders' songs say there was once only one.", w: 1, mods: [["mountain", 1.5], ["cold", 1.5], ["marsh", 1.5], ["insular", 1.5]], tags: ["theme:changed_kin"] },
    { id: "sky_seam", n: "The Seam in the Sky", d: "On the clearest nights a thin straight line crosses the stars from horizon to horizon. The seasons arrive to the day, every year, and have never once been late.", w: 0.7, mods: [["seers", 2], ["scholarly", 1.5], ["faith:stars", 2]], truthLink: "vessel_world", tags: ["theme:sky_seam"] },
    { id: "dead_chimney", n: "The Dead Chimney of the Waste", d: "Deep in the wrong lands stands a tower that once breathed warm cloud into the sky. Shepherds say that while it breathed, the silver grass died back for a hundred miles.", w: 0.8, req: { any: ["desert", "cold", "badlands", "frontier", "steppe"] }, truthLink: "shaping_halted", tags: ["theme:dead_chimney"] },
  ],

  sites: [
    { id: "burning_house", n: "The Burning House of $", kind: "wonder", where: "mountain", d: "The holy mountain: half rock, half something smooth and scorched, where the songs say the gods came down in fire.",
      layers: {
        surface: { n: "The scorched face", text: "One face of the holy mountain is smooth, scorched black in long streaks, and hums in a thunderstorm. The temple forbids the climb. Eleven sky-seekers have tried since {year}; shepherds found the coats of three of them folded neatly on the lower slopes." },
        study: { n: "Letters under the moss", text: "{investigator} scraped the moss from a strip of the smooth face and found grey metal, cold and unrusted. Stamped into it is a line of the angular letters from the temple relics, each a hand high. The priests call the line a prayer. The rubbings went to the observatory." },
        dig: { n: "Four hundred seats", text: "A hatch near the summit opened to a ring from the Officers' house. Inside are four hundred seats in rows, all tilted to face upward, with straps at the shoulders. A painted plan on the wall shows the mountain beside a far larger shape. The Watch keeps its own copy of that plan at {lead}.", points: "temple" },
        revelation: { n: "Lander Two", text: "The mountain is a landing craft. Its crew brought four hundred settlers down and were meant to fly it back to the ship. The oathbreakers' house seized the settlement, burned the crew's logs and made the crew into gods, so no one would ask to go home. The temple still sweeps the seats every feast day." },
      } },
    { id: "sleeper_hall", n: "The Hall of Sleepers at $", kind: "dig", where: "remote", d: "A buried hall of glass coffins, each with a name lit softly above it.",
      layers: {
        surface: { n: "The glow in the hill", text: "Shepherds near {place} see a faint blue glow through a crack in a hillside on winter nights. The crack is a hand wide. Two boys went in after a lamb in {year} and came out saying the hill was full of beds made of glass." },
        study: { n: "The names", text: "{official} copied the names lit above the glass coffins and laid them beside the temple roll. Of the four hundred names in the 'still sleeping' column, three hundred and twelve are here, in the same order. The priest's report asks that the hill be consecrated and closed." },
        dig: { n: "The dark coffin", text: "The sleepers are alive and unaged, in plain grey clothes no tailor has made for a thousand years. One coffin's light is out, and the woman inside is dead. A plate on its foot refers to a 'wake schedule'. The founders' copy of that schedule was taken by the oathbreakers' house, whose archive is at {lead}.", points: "archive" },
        revelation: { n: "Revival pending", text: "The founders woke only as many settlers as the first fields could feed, and meant to wake the rest when harvests grew. The mutineers kept the hall secret, because the sleepers included the ship's officers. Three hundred and twelve people are still waiting for a harvest big enough, and the coffin lights go out one a generation." },
      } },
    { id: "silent_chimney", n: "The Silent Chimney of $", kind: "ruin", where: "desert", truthLink: "shaping_halted", d: "A cold tower in the wrong lands, its doors sealed, its vents choked with silver grass.",
      layers: {
        surface: { n: "The tower in the grass", text: "A tower taller than any keep stands alone in the silver grass, three days' ride past the hedge-line. No beast of ours will graze within a mile of it. The hedge-wardens use it as a landmark and do not go nearer." },
        study: { n: "The ring of earth", text: "Around the tower's foot is a ring of ordinary dark soil, where barley sown by {survivor} came up green. The oldest survey puts the ring at six hundred paces across. It is now one hundred and forty, and the silver grass closes in a few paces each year." },
        dig: { n: "The counting slate", text: "Inside are great cold engines and a glass slate of numbers that stopped at forty-nine per cent. Under the number is a warning in sky-script. The Watch priests refused to translate it. A copy was smuggled to the heretic readers who meet at {lead}.", points: "heretic" },
        revelation: { n: "Half a world", text: "The founders were remaking this world into farmland, chimney by chimney. The engines failed at forty-nine per cent, and the settlers' leaders hid it rather than ration the seed. The green lands are the finished half. The native life is taking back the rest at eight rods a year, and the temple still sells salt." },
      } },
    { id: "older_stones", n: "The Older Stones of $", kind: "ruin", where: "remote", truthLink: "shaping_halted", d: "Stone rings carved by hands that were not human, deep in the wrong lands.",
      layers: {
        surface: { n: "Rings in the silver grass", text: "Rings of standing stones stand deep in the wrong lands, weathered smooth. The handholds cut into them are spaced for hands with six fingers. {survivor} counted nineteen rings on one journey and saw no builders, only fresh tracks." },
        study: { n: "The carvings", text: "The inner faces show a burning house falling from the sky, seen from below, and small six-limbed figures running from it. One stone shows the house sitting on a mountain. The mountain is carved the same shape as the holy mountain of {realm}." },
        dig: { n: "The graves", text: "Beneath the rings are graves of a six-limbed people, laid with care, each with a reed bowl at its head. The newest was dug within the last ten years. A bowl of the same make sits in the relic room at {lead}, labelled as a gift of the gods.", points: "temple" },
        revelation: { n: "The first people", text: "This world had its own people. They watched the founders land and fled as the engines turned their grasslands to barley. The founders knew: their survey calls the natives 'non-competing fauna' and orders their towns ploughed. The six-fingered people are still in the silver grass, and they bury their dead facing the mountain." },
      } },
    { id: "curved_shore", n: "The Curved Shore at $", kind: "anomaly", where: "remote", truthLink: "vessel_world", d: "At the far edge of the world, behind a wall of mist, a grey shore that curves upward into the sky.",
      layers: {
        surface: { n: "The grey cliff", text: "Sailors who go past the last isles report a grey cliff with no top, lost in mist. Of nine ships known to have tried since {year}, four came back. Their logs agree that the cliff was warm and the sea beside it had no tide." },
        study: { n: "Seamless", text: "{investigator} sailed with the tenth ship and laid a hand on the cliff. It is not stone. It is smooth, seamless and warm as skin, and it curves up and over, out of sight. A plumb line dropped beside it hung eleven degrees off true." },
        dig: { n: "Hull section nine", text: "A door at the cliff's foot is marked in sky-script, with a word the priests translate as 'maintenance'. Beside it is a panel with a slot the shape of an Officers' ring. The only ring known to fit is held by the house at {lead}.", points: "sub:two_lines" },
        revelation: { n: "No outside", text: "There is no outside. The world is the inside of a vessel, and its seasons are set by its machines. The crew who ran it died long ago and let the passengers forget, because the voyage was longer than any life. The almanac puts the last season under a century away, and nobody knows what is meant to happen then." },
      } },
    { id: "iron_crater", n: "The Iron Fall at $", kind: "dig", where: "any", truthLink: "colony_ship", d: "A fresh crater around a twisted shell of painted metal, still warm.",
      layers: {
        surface: { n: "A fallen star", text: "A star fell near {place} within living memory and flattened an orchard. The crater is sixty paces wide and glitters with melted glass. Children sell the glass to pilgrims at a penny a piece and tell them it is a piece of heaven." },
        study: { n: "New paint", text: "The metal shell in the crater is painted with the angular letters of the temple relics. {investigator} noted that the paint is bright and unfaded, not centuries old. Whatever this fell from was painted within a lifetime, and someone up there was still painting." },
        dig: { n: "The man in the coat", text: "A sealed compartment held a dead man in a padded coat, with a letter folded inside his glove. The letter is in sky-script, which only the Watch priests half read. {official} took it to {lead} and has not released a translation.", points: "cast:official" },
        revelation: { n: "Someone came down", text: "The wandering star is the colony ship, and it is breaking up. Someone aboard was alive within living memory and tried to come down in a lifeboat. The landing killed him. His letter apologises for being late, and the temple of {faith} has filed it as a prayer." },
      } },
  ],

  beings: [
    { id: "ship_ghost", n: "Ship-ghost", kind: "beast", d: "A shining figure in an old-fashioned coat that appears near the holy mountain at night, speaks politely in a dead tongue, and walks through walls.", danger: 0, biomes: ["alpine", "peaks", "tempforest", "grass"], look: { size: 1.8, group: [1, 1], move: "solo", speed: 3, col: "#cfe3f0", col2: "#5a7a9a", body: "biped", active: "night", visible: true } },
    { id: "glass_grazer", n: "Silvergrass grazer", kind: "grazer", d: "A six-legged native beast with a shell like frosted glass, grazing the wrong lands in slow herds. Its meat is poison to people and its blood smells of tin.", danger: 1, biomes: ["grass", "coldsteppe", "colddesert", "badlands", "savanna"], look: { size: 1.8, group: [5, 25], move: "herd", speed: 5, col: "#c4d0d4", col2: "#7a8c94", body: "insect", active: "day", visible: true } },
    { id: "lantern_spirit", n: "Lantern-spirit", kind: "bird", d: "A small humming thing of metal and light that drifts through old shrines tidying, and is fed oil and honey as a household god.", danger: 0, biomes: ["tempforest", "grass", "alpine", "river"], look: { size: 0.3, group: [1, 3], move: "solo", speed: 6, col: "#e8d080", col2: "#8a8a8a", body: "bird", active: "night", visible: true } },
    { id: "plough_worm", n: "Plough-worm", kind: "beast", d: "A huge pale worm bred by the founders to turn the native soil into earth crops could grow in. Feral now, it surfaces at the edges of the wrong lands and swallows carts.", danger: 2, biomes: ["grass", "coldsteppe", "badlands", "savanna"], look: { size: 9, group: [1, 1], move: "solo", speed: 2, col: "#d8c8b0", col2: "#9a7a6a", body: "serpent", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "fl_sky_script", n: "The sky-script", field: "writing", level: 1, d: "The angular letters on temple relics are learned as a sacred alphabet; the first scholars notice they spell instructions." },
    { id: "fl_star_tables", n: "Tables of the wandering star", field: "astronomy", level: 2, d: "Exact tables of the star that crosses the wrong way, and the slow, worrying sum of how it is sinking." },
    { id: "fl_seed_waking", n: "Waking the ark seed", field: "agriculture", level: 3, d: "The art of thawing and sowing the founders' jars: crops that thrive where nothing native will." },
    { id: "fl_watch_rites", n: "The rites that open doors", field: "arcana", level: 3, d: "Priests learn which of the Watch's chants, rings and gestures make the old doors answer, and stop calling them miracles." },
    { id: "fl_ship_voice", n: "Speaking to the star", field: "natural_philosophy", level: 4, d: "A bronze box, a mountaintop and the right words, and the wandering star answers." },
    { id: "fl_return_road", n: "The road up", field: "astronomy", level: 5, d: "The founders' house is made to rise again. Someone must decide who goes." },
  ],

  faiths: [
    { id: "fl_watch", n: "The Watch", d: "The gods were the crew who brought the people down from the sky. The faithful keep their duties as holy offices and wait for the Captain's return.", tags: ["faith:fl_watch", "organised"], w: 0.7, mods: [["theme:watch_priests", 8], ["theme:holy_peak", 3], ["hierarchical", 1.5]],
      names: ["The Watch of $", "The Faith of the Manifest", "The Crew Eternal"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Native wilds", color: "#a8bcc0", size: [2, 4], count: [1, 2], where: "remote", d: "Land the founders never finished remaking: silver grass, tin-tasting water and six-legged beasts, behind an edge as sharp as a hedge." },
  ],

  storylines: [
    { id: "fl_hatch", n: "The Hatch on the Holy Mountain", scale: "realm", anchor: "realm", w: 1.5, req: "sky_ancestry",
      stages: {
        start: { h: "A sky-seeker climbs the holy mountain of {realm}", b: "Against every law of the temple, {person} has climbed the scorched face of the holy mountain. A light was seen at the summit for three nights.", wait: [2, 5], next: [{ to: "hatch_open", w: 2 }, { to: "seeker_lost", w: 1 }] },
        hatch_open: { h: "{person} returns with a ring and a story", b: "The seeker came down with a ring of the old Officers' house on one finger and a tale of rows of seats facing the sky. The temple of {faith} demands silence.", wait: [3, 8], fx: { unrest: 6, flag: "hatch" }, next: [{ to: "sealed_again", w: 1, mods: [["pious", 2], ["zealous", 2], ["theme:watch_priests", 2]] }, { to: "star_answers", w: 1.2, mods: [["learned", 2], ["scholarly", 1.5]] }, { to: "houses_feud", w: 1, mods: [["theme:two_lines", 4], ["monarchy", 1.3]] }] },
        seeker_lost: { h: "No word from the summit", b: "The light on the mountain went out. A ragged coat was found on the lower slopes, folded neatly, as if by someone else.", fx: { stability: 2 }, end: true },
        sealed_again: { h: "The temple seals the mountain of {realm}", b: "Masons of {faith} have bricked up the hatch and set a guard. {person} has been given a quiet cell and a great many visitors who ask questions.", fx: { stability: 4, prestige: -2 }, end: true },
        star_answers: { h: "The wandering star speaks to {realm}", b: "From the summit, a voice in an old tongue answered {person}. It asked how many had survived, and whether anyone was left who could take command.", fx: { discovery: "astronomy", prestige: 10, flag: "star_voice" }, end: true },
        houses_feud: { h: "The old feud of {realm} catches fire", b: "The heirs of the Officers' house claim the mountain by right of the ring. The oathbreakers' house says it knows why the door was shut, and will kill to keep it shut.", fx: { stability: -10, unrest: 12, revolt: true }, end: true },
      } },
    { id: "fl_bronze_voice", n: "The Voice in the Shrine of {place}", scale: "local", anchor: "town", w: 1.2, req: "sky_ancestry",
      stages: {
        start: { h: "The bronze box of {place} speaks", b: "The holy box in the old shrine of {place}, silent for centuries, spoke this morning. It asked, very politely, for the Captain.", wait: [1, 3], next: [{ to: "pilgrims", w: 1.5 }, { to: "ruler_claims", w: 1, mods: [["autocracy", 2], ["monarchy", 1.3]] }] },
        pilgrims: { h: "Pilgrims crowd the shrine of {place}", b: "Thousands come to hear the box. {person}, a shrine-keeper, has started writing down everything it says, and the priests of {faith} are uneasy.", wait: [3, 8], fx: { treasury: 15 }, next: [{ to: "knowledge", w: 1, mods: [["learned", 2], ["scholarly", 2]] }, { to: "silenced", w: 1, mods: [["zealous", 2]] }, { to: "falls_silent", w: 1 }] },
        ruler_claims: { h: "{ruler} answers the bronze box as Captain", b: "{ruler} has gone to {place} and declared to the box that the Captaincy is the crown's. The box asked for a code. Nobody knew it.", wait: [2, 6], next: [{ to: "knowledge", w: 1 }, { to: "falls_silent", w: 1.5 }] },
        knowledge: { h: "The book of the bronze voice is copied in {realm}", b: "{person}'s pages describe how to wake seed, set bones and read the stars, all from a voice that calls itself 'the ship' and sounds very tired.", fx: { discovery: "natural_philosophy", science: { medicine: 0.5 }, prestige: 6 }, end: true },
        silenced: { h: "Priests of {faith} smash the bronze box", b: "Declared a demon's mouth, the box was broken on the shrine steps. Its last words were a list of names, read very fast.", fx: { stability: 3, unrest: 6 }, end: true },
        falls_silent: { h: "The box of {place} falls silent again", b: "The voice faded mid-sentence. Those who heard it last say it was counting down, and did not reach the end.", fx: { stability: -2 }, end: true },
      } },
    { id: "fl_falling_star", n: "The Falling Star", scale: "world", anchor: "realm", w: 0.8, req: ["sky_ancestry", { any: ["theme:wandering_star", "theme:iron_falls", "learned"] }],
      stages: {
        start: { h: "The wandering star burns low over {realm}", b: "Star-readers of {capital} say the wandering star is lower than ever recorded, and that pieces of it are falling. {person2} has done the sum and will not say the answer.", wait: [6, 12], next: [{ to: "debris", w: 2 }, { to: "climbers", w: 1, mods: [["theme:holy_peak", 3], ["learned", 1.5]] }] },
        debris: { h: "Burning iron falls near {place}", b: "A fireball crossed the sky and struck the hills near {place}, flattening a village. The crater is full of painted metal.", wait: [3, 8], fx: { pop: 0.97, unrest: 8 }, next: [{ to: "star_falls", w: 1.5 }, { to: "climbers", w: 1 }] },
        climbers: { h: "{realm} sends seekers up the holy mountain", b: "Armed with {person2}'s tables, a band of seekers climbs the mountain with every ring and chant the temple keeps, hoping to speak to the star before it comes down.", wait: [4, 10], next: [{ to: "star_saved", w: 1, mods: [["learned", 2]] }, { to: "star_falls", w: 1 }] },
        star_falls: { h: "The wandering star falls", b: "For one night the sky burned from end to end. The wandering star is gone, and the old songs of the burning house have a new last verse.", fx: { stability: -8, prestige: -3, flag: "star_fallen" }, end: true },
        star_saved: { h: "The wandering star rises again", b: "The seekers spoke the right words, and the star climbed back up the sky. It crosses higher now, and some nights it seems to blink at {capital}.", fx: { prestige: 12, discovery: "astronomy", stability: 4 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "the founding hymn, as sung at {place}", text: "The founding hymn, as the children of {place} sing it at the spring feast, verse one of twelve: 'In the first days the gods came down / in a burning house from the sky; / the house sat down upon the mount / and never rose so high.' The temple teaches that the burning house is a picture of {deity}'s love. The children are given a honey cake for every verse." },
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", who: "{official}, Watch-priest", text: "From the liturgy of the Watch, as copied by {official} for the novices of {place}: 'Keep the watch. Keep the manifest. Keep faith with the Captain, who will return when the count is done.' The manifest is the temple's list of the first four hundred families. The count is not explained anywhere in the liturgy, and novices who ask what is being counted are given extra floors to sweep." },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "a temple primer, third edition", text: "From the temple primer on the sky-script, third edition, page 1: 'The sky-script is the holy alphabet of right angles, given to the first priests. It has forty-one letters. Its words are prayers and must not be read for meaning.' A marginal note in a student's hand says the letters spell 'pull' on one relic door and 'push' on another. The fuller grammar is shelved at {lead}.", points: "library" },

    { depth: "core", about: "truth:colony_ship", source: "ruin", bias: "true", reliable: true, plain: true, who: "{believer}, sky-seeker", text: "Statement of {believer}, sky-seeker, to the temple court of {place}, {year}: 'Painted over the inner door of the hatch, in letters a hand high: LANDER TWO. RETURN TO SHIP ON COMPLETION OF SURVEY. I can read the sky-script; the priests can too. We came down from a ship. The ship is the wandering star. It never got its lander back, and it is still up there, waiting.'" },
    { depth: "core", about: "truth:colony_ship", source: "person", bias: "true", reliable: "partial", who: "{investigator}, star-reader", points: "site:iron_crater", text: "Journal of {investigator}, star-reader, {year}: 'The wandering star does not keep the heavens' time. It keeps its own and loses a little every year, like a clock running down. Against the peak of the holy mountain it has sunk two finger-widths since my teacher drew these tables, forty years ago. Stars do not run down. Last spring a piece of it fell at {lead}, and the metal there is painted.'" },
    { depth: "core", about: "truth:colony_ship", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "the founding charter of the oathbreakers' house", points: "archive", text: "Founding charter, held by the oathbreakers' house, clause 9: 'The ship's records are to be destroyed and its name never spoken, that the people may belong to this world and not to [two lines scraped away]. The navigator {person}, who would not surrender the log, is to be walled up with it in the cellar of the first hall.' A copy of the charter with the two lines intact was lodged at {lead}." },
    { depth: "core", about: "truth:colony_ship", source: "oral", bias: "garbled", reliable: "partial", who: "{survivor}, hedge-warden", text: "Told by {survivor}, hedge-warden, to a temple clerk at {place} in {year}, while waiting to pay the salt tax: 'My grandmother said the wandering star is the gods' house still. She counted it crossing seven times a week and said they watch us from its windows, and that they are very lonely. She set a lamp in the attic window for them every night of her life. I still do.'" },
    { depth: "core", about: "truth:colony_ship", source: "temple", bias: "official", reliable: false, who: "{official}, for the Manifest office", text: "Ruling of the Manifest office, signed by {official}, {year}, in answer to the star-readers' petition: 'The wandering star is the soul of the first Captain, set in the sky by {deity} to watch over the faithful. It is not a thing that can fall, and metal found in craters is the work of smiths seeking to sell relics. The office has kept the names of the petition's 214 signatories, and will pray for each of them by name.'" },

    { depth: "core", about: "truth:shaping_halted", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, star-reader", text: "Transcribed by {investigator} from the glass slate in the silent chimney, {year}, with a stolen Watch key to the sky-script: 'ATMOSPHERE CONVERSION 49 PER CENT. ENGINES FAILING. NATIVE BIOSPHERE RESURGENT. ADVISE SETTLERS TO REMAIN IN THE GREEN ZONE.' The star-reader's covering letter to the observatory: 'The founders were remaking this world for us and stopped halfway. The silver grass is not a blight. It is what was here first, and it is winning.'" },
    { depth: "core", about: "truth:shaping_halted", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a wool-buyer of {realm}", points: "site:older_stones", text: "Letter of a wool-buyer of {realm} to a partner, {year}: 'Past the hedge-line the grass is silver and rings in the wind like a struck cup. On the fourth day I found a ring of standing stones with handholds too wide apart for any hand of ours. Something with six fingers watched me from them, I swear it. The ring is at {lead}. I will not go back for any price of wool.'" },
    { depth: "core", about: "truth:shaping_halted", source: "heretic", bias: "heretic", reliable: "partial", who: "{believer}, preaching unlicensed", text: "A forbidden sermon, preached by {believer} at a barn meeting outside {place}, {year}, and taken down by an informer for a fee of three pennies: 'The gods did not make this world for us. They were painting over someone else's, and the paint is peeling. Go and look at the stones past the hedge. Count the fingers on the handholds. Then ask the priests who our gods were painting over.'" },
    { depth: "core", about: "truth:shaping_halted", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, hedge-warden", text: "Petition of {survivor}, hedge-warden, to the crown at {year}: 'The silver line crossed my father's barley in the spring and took all forty acres by harvest. We salted it twice at our own cost. My son {person}, aged nine, ate the meat of a six-legged grazer that strayed in, because we were hungry. {person} died the same night with tin on the breath. I ask for land on the green side, and for someone to tell me the truth.'" },
    { depth: "core", about: "truth:shaping_halted", source: "library", bias: "official", reliable: false, who: "the crown's Office of Tillage", text: "Circular of the Office of Tillage, {year}, issued to the hedge-wardens: 'The wrong lands are a blighted country, poisoned by the wars of the first age. With diligent tillage and two cartloads of salt to the acre they will in time be restored to the plough. Wardens who report that the line is advancing are reminded that it is their duty to push it back.'" },

    { depth: "core", about: "truth:vessel_world", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, aboard the tenth ship", text: "Log of the tenth ship to the grey cliff, entry by {investigator}, {year}: 'Day 9 past the last isle. Calm, no tide, water warm as a bath. Read the door at the cliff foot: MAINTENANCE ACCESS. HULL SECTION NINE. VOYAGE YEAR, then a number worn away. Plumb line hangs eleven degrees off true. The edge of the world is a wall, and somebody built it. We are not on a world. We are inside a vessel that is still moving. Turning for home.'" },
    { depth: "core", about: "truth:vessel_world", source: "person", bias: "true", reliable: "partial", who: "an almanac-maker of {place}", points: "site:curved_shore", text: "Letter of an almanac-maker of {place} to {investigator}, {year}: 'In three hundred years of records, midsummer has never come a single day early or late. Nothing in nature is so punctual. Only things that are made. The sailors' cliff past the last isles is warm and has no tide beside it. If you want to see whether the sky has an edge, the place to begin is {lead}.'" },
    { depth: "core", about: "truth:vessel_world", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "a sailor of {place}, in the harbour tavern", text: "Told by a sailor of {place} in the harbour tavern, {year}, for the price of a jug: 'Sail nine days past the last isle and the edge of the world is a wall, and it's warm. My brother {person} climbed it with an iron hook, forty feet, laughing. Then the laughing stopped, because the wall leaned out overhead like a ceiling. {person} fell. We never found the body. I haven't been to sea since, and I won't sleep in a room with a low ceiling.'" },
    { depth: "core", about: "truth:vessel_world", source: "library", bias: "official", reliable: false, who: "the royal observatory's Answers to Common Questions", text: "From the royal observatory's Answers to Common Questions, number 17, {year}: 'The thin straight line seen across the stars on clear nights is a trick of cold air on the eye, well known to astronomers, and signifies nothing. Persons who see it on warm nights are advised to rest their eyes. The observatory regrets that it cannot answer further letters on this subject.'" },

    { depth: "sub", about: "sub:holy_peak", source: "person", bias: "true", reliable: true, who: "{believer}, sky-seeker", points: "site:burning_house", text: "Statement of {believer}, taken by a physician at {place} while the burn was dressed, {year}: 'The burn is the shape of a ring because I was wearing my uncle's ring when I put my hand on the door. The door opened. The inside smelled of dust and lamp oil, and there were seats, hundreds of them, facing up. I counted forty in one row before the light failed. The door is near the top of {lead}.'" },
    { depth: "sub", about: "sub:watch_priests", source: "temple", bias: "pious", reliable: "partial", who: "the Watch's rule of ordination", points: "cast:official", text: "Rule of ordination for a Watch-keeper, article 3: 'The candidate shall recite the duties of the night watch, check each of the fourteen temple doors twice, and record that all is well. Should any door open of its own accord, the candidate shall record that also, and not walk through it, and report it to the Manifest office at {lead}.' Article 4 sets the fine for walking through it: one year's stipend." },
    { depth: "sub", about: "sub:wrong_lands", source: "archive", bias: "official", reliable: "partial", who: "a crown surveyor of the hedge-line", points: "site:silent_chimney", text: "Survey of the hedge-line, {year}, crown surveyor's report: 'Advanced eight rods into the barley of {place} since last survey. Recommend salt. Salt has not worked. Recommend more salt.' Below, in a second hand: 'The wardens say the line bends back toward the old tower at {lead}, as if the tower once held it off. Not entered in the official copy.'" },
    { depth: "sub", about: "sub:two_lines", source: "oral", bias: "exaggerated", reliable: "partial", who: "an innkeeper of {place}", points: "archive", text: "An innkeeper of {place}, to a travelling scribe, {year}: 'The Officers' heirs say the oathbreakers murdered the gods. The oathbreakers say they saved us from them. I have served both houses at the same wedding, 120 guests, and both families stopped talking when the bread came in. If you want the quarrel in writing, the oathbreakers keep their papers at {lead}, and they bite.'" },
    { depth: "sub", about: "sub:unwoken", source: "temple", bias: "pious", reliable: "partial", who: "{official}, Watch-priest", points: "site:sleeper_hall", text: "Order of the feast of names, set out by {official} for the temple of {place}: 'On the feast we read the Still Sleeping, all four hundred names, so they will not be forgotten when they wake. The reading takes two hours. Readers must not skip names.' Added in {year}: 'A shepherd near {lead} claims some of these names are glowing in his hill. He is to be thanked and sent home.'" },
    { depth: "sub", about: "sub:seed_ark", source: "person", bias: "true", reliable: true, who: "the abbot of the seed vault", text: "Letter of the abbot of the seed vault to the mother house, spring of {year}: 'We opened jar 212 this spring, the first in thirty years. The seed grew into a green bush with red berries and a smell that made the old brothers weep, though none of them had ever smelled it before. Brother Cellarer says it tastes of something called a raspberry. We do not know how he knows the word.'" },
    { depth: "sub", about: "sub:changed_kin", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a lowland salt-trader", text: "Travel diary of a lowland salt-trader, crossing the high pass, {year}: 'The valley folk climbed the pass beside me singing, carrying 60 pounds each, while I crawled and gasped with nothing. Their old songs say we were one people once, who came down together from the mountain. I believe it less every mile. They breathe this air like it is soup.'" },
    { depth: "site", about: "site:sleeper_hall", source: "ruin", bias: "true", reliable: "partial", who: "{official}, Watch-priest", text: "Copied by {official} from the glass coffins under the hill, {year}: 'Above coffin 117, a name still lit, and under it in smaller sky-script: REVIVAL PENDING SUITABLE CONDITIONS. Above coffin 118, no light. The woman inside is dead, and her hands are folded over a small wooden horse.' The priest's note asks whether the temple should decide what conditions are suitable." },
    { depth: "site", about: "site:iron_crater", source: "person", bias: "true", reliable: true, who: "a farmer of {place}", text: "A farmer of {place}, who helped carry the body out of the iron fall, to {investigator}, {year}: 'The Watch priest read us the dead man's letter, slowly, before the others came and took it away. It said: If anyone is still down there, we are coming. We are sorry it took so long. There were six seats in that iron room, and only one man in them.'" },
  ],
};
