// The Gardener Engine: the iron beasts that graze the plains are the tending-hands of a lost world-mending mind.
// A bridge premise: under a medieval world the engine is the All-Mother, its herds are beasts, its halls are holy ruins.
export default {
  id: "gardener_engine",
  name: "The Gardener Engine",
  family: "scifi",
  pitch: "The iron beasts that graze the high plains are not monsters. They are the tools of a lost machine-mind that rebuilt the living world, and the mind that directed them is gone.",
  slots: ["ecology", "apocalypse", "monster-source"],
  tone: ["wonder", "melancholy"],
  era: ["stone", "bronze", "medieval", "post-collapse"],
  scale: "world",
  genres: ["fantasy", "postapoc", "grimdark"],
  bridge: true,
  w: 1,
  excludes: [],
  pairs: [{ id: "forgotten_landing", w: 3 }, { id: "grey_unmaking", w: 2.5 }, { id: "long_mending", w: 1.5 }, { id: "elder_lattice", w: 2 }, { id: "kindled_lineages", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a herb-gatherer and healer who tests the water of the thornwood", home: "forest", stance: "Trusts what kills dogs and what does not, and has come to think the realm burns the wrong forest." },
    { role: "official", n: "a beast-reeve of the Sun-Throne who counts the tribute of iron hearts", home: "capital", stance: "Holds that the herds were made for kings to break, and that a full tribute ledger is proof of a sound realm." },
    { role: "believer", n: "a Door-keeper of the Mother's shrine on the mountain", home: "mountain", stance: "Believes the Mother sleeps behind her door and will wake for the pure, and keeps the children away from it just in case." },
    { role: "survivor", n: "an iron-hunter who lost a hand to a red-eyed grazer", home: "remote", stance: "Hunted the herds for twenty years and now wants to know why they stopped knowing people." },
  ],

  truths: [
    { id: "terraformers", n: "The herds are the world's gardeners", d: "An older people's war-engines ate every living thing, so they built a great mind to remake the world after them. It grew the grass, the beasts and the first of the present folk from seed kept in the mountain, and its iron herds still tend the land. One of its servant-minds was built to burn everything and start again if the work went wrong, and the realms now slaughtering the herds are exactly what it was built to look for.", tags: ["truth:terraformers"],
      known: [
        "Hunters and travellers agree that the iron herds do not bleed, breed or age, and that grass grows twice as tall where they graze. The Sun-Throne's scholars call them a natural armoured animal.",
        "The iron beasts walk out of a square cave in a mountain forge, where half-made grazers hang on chains. Ruins nearby hold burial mounds with glass cradles. The herds are built, and so, perhaps, was something else.",
        "A script in the cradle-vault orders the release of humans after pollinators and grazers. The ghosts in the speaking halls say goodbye to children who will not know them. The present folk were grown by the engine.",
        "Confirmed: a mind built by the old world's survivors remade the land, beasts and people, and its forges still work by the old plan. A second forge in the black mountain was built to clear the garden if it grew wrong, and it has started smoking.",
      ] },
    { id: "sacrifice", n: "The Mother died to keep the door", d: "A voice from beyond the sky once tried to take command of the mending engine. The mind the tribes call the All-Mother burned her own heart to stop it, and ordered her servant-minds to keep working without her. With no one left to tell them who the people are, the herds have begun to take hunters for blight, and the voice is still calling over the black mountain on still nights.", tags: ["truth:mother_sacrifice"],
      known: [
        "Grazers in several realms have turned red-eyed and charge on sight, and more turn each season. The temples call it punishment for the hunters' sins. Hunters report a voice from the sky on still nights.",
        "The door the tribes call the Mother-Door is real grey metal and hums only for children. Behind it is a chamber burned from within and a glass seat shattered outward. Whatever happened there, it happened from inside.",
        "The glass seat's last recorded words reject an 'outside instruction' and begin a 'self-ending'. A cast-out child who opened the door was called by a name nobody gave her. The Mother did not fall asleep. She ended herself.",
        "Confirmed: the All-Mother destroyed herself to keep a voice from beyond the sky from seizing her work. Her servants run on without orders, and the red-eyed herds are the cost. The voice has not stopped asking to be let in.",
      ] },
    { id: "blight_cure", n: "The blight is the cure", d: "The grey thornwoods that creep across the land are the engine's own purifiers, drinking the old world's poisons out of the soil and leaving clean earth behind; they are toxic only while they work. The crown's yearly decree to burn them sets the poison loose in the ash and the wells. Every burned summer undoes years of mending, and the children near the firebreaks are the ones coughing black.", tags: ["truth:blight_cure"],
      known: [
        "The thornwood advances a few strides each year, and every realm it touches burns it back by decree. The spores choke anyone who enters without a wet cloth. Nobody has asked where it came from.",
        "A healer's notes say the water at the thornwood's heart is clean and sweet, while water from the burned edge killed three dogs. The forest's centre has the purest air in the land.",
        "Under the clean centre, thorn roots have wrapped and drained an old black poison, the same that fills the war-engine husks on the dead plain. A panel names the forest 'remediation, stage two. Do not clear.'",
        "Confirmed: the thornwood is a filter planted by the mending engine. Burning it releases the poison it has drunk, into ash, wells and children's lungs. The crown still renews the burning decree every spring.",
      ] },
  ],

  tags: ["machine_herds"],

  subthemes: [
    { id: "hunt_rite", n: "The Iron Hunt", d: "No youth is counted grown until they have brought home a plate from an iron grazer. The rite is old, the hunts are getting deadlier, and the elders will not say why.", w: 1.5, mods: [["tribal", 2.5], ["martial", 1.5], ["gov:tribal", 2]], tags: ["theme:iron_hunt"] },
    { id: "derangement", n: "The Red-Eyed Herds", d: "The grazers here have begun to charge on sight, their eyes gone from blue to red. Each season more of them turn, and each turned beast fights like three.", w: 1.4, truthLink: "sacrifice", tags: ["theme:derangement"], mark: { kind: "zone", n: "Red-eye country", color: "#a03a2a", size: [2, 4], where: "remote" } },
    { id: "failed_spirit", n: "The Silent Rain-Spirit", d: "The spirit that gave this land its rain has stopped answering. Wells fail, streams turn, and the shrine at the mountain hums a broken note.", w: 1, req: { any: ["desert", "hot", "steppe", "hills", "mountain"] }, truthLink: "terraformers", tags: ["theme:failed_spirit"] },
    { id: "war_beasts_wake", n: "The Black Forge Wakes", d: "Smoke rises from a mountain nobody has dared approach in living memory. The machines walking out of it are built for killing, not grazing.", w: 0.8, truthLink: "terraformers", tags: ["theme:black_forge"], mark: { kind: "zone", n: "The Smoking Forge", color: "#3a3030", size: [1, 2], where: "mountain" } },
    { id: "voiced_ruins", n: "The Talking Dead in the Ruins", d: "Pale ghosts appear in the old metal halls, speaking the same few sentences in a tongue only scholars half follow. Some of the ghosts are weeping.", w: 1.1, req: { any: ["near:ruins", "scholarly", "origin:ruin_heirs"] }, tags: ["theme:voiced_ruins"] },
    { id: "sun_king_tribute", n: "The Sun-Throne's Tribute of Iron", d: "An expanding crown demands a yearly tribute of beast-hearts from every tribe it conquers. Its armies wear grazer plate, and its priests say the herds were made for kings to break.", w: 1.2, req: { any: ["autocracy", "gov:empire", "monarchy", "faith:sun"] }, tags: ["theme:sun_tribute"] },
    { id: "riders", n: "The Beast-Riders", d: "A people who have learned to whisper to the iron striders and ride them. Their neighbours call it witchcraft; they call it asking politely.", w: 1, req: { any: ["horse_lords", "beast_tamers", "steppe", "nomadic", "beast_cavalry"] }, tags: ["theme:beast_riders"] },
    { id: "sacred_blight", n: "The Creeping Thornwood", d: "A forest of grey thorns and choking spores advances a few strides each year. The realm burns it back every summer, and every summer it is a little closer.", w: 1.2, req: { any: ["forest", "jungle", "marsh", "river"] }, truthLink: "blight_cure", tags: ["theme:thornwood"], mark: { kind: "zone", n: "The Thornwood", color: "#5a6a4a", size: [2, 5], where: "forest" } },
    { id: "city_on_beast", n: "The Town on the Sleeping Giant", d: "A town is built on the back of a dormant colossus, half-buried in a hill. Its foundations have begun to hum at night.", w: 0.7, req: { any: ["realm:mid", "realm:large", "realm:vast", "has:city"] }, tags: ["theme:sleeping_giant"] },
    { id: "skyborn_return", n: "The Lords from the Sky", d: "Strangers in white have come down from the sky in a silver boat and claim the land was theirs before. They know the old halls far too well.", w: 0.6, truthLink: "terraformers", tags: ["theme:sky_lords"] },
    { id: "foundling_heir", n: "The Motherless Child", d: "An outcast child of no known parents can open doors in the old halls that no one else can. The elders fear her; the halls seem to know her face.", w: 0.8, req: { any: ["tribal", "pious", "mystic", "faith:spirits"] }, truthLink: "sacrifice", tags: ["theme:foundling"] },
  ],

  sites: [
    { id: "cauldron", n: "The Belly of $", kind: "ruin", where: "mountain", truthLink: "terraformers", d: "A mountain hollowed into a forge, where iron beasts are born from fire and come out walking.",
      layers: {
        surface: { n: "The square cave", text: "A cave-mouth on the mountain is too square to be natural, eight paces on each side. Iron grazers walk out of it at dawn, one or two a month, and none ever walks back in. The hunters of {place} wait at the mouth with nets." },
        study: { n: "The hanging beasts", text: "Inside, the walls are smooth metal and warm to the touch. Molten light runs in channels in the floor, and half-made grazers hang from chains, some without plates, some without heads. {survivor} counted thirty-one on the chains and left before the chains began to move." },
        dig: { n: "The glass pillar", text: "At the heart stands a pillar of glass full of moving light. A voice from it asks, in the old words, whether the soil is ready, and then waits. It asked {investigator} the same question nine times. The old words are best known to the Door-keeper at {lead}.", points: "cast:believer" },
        revelation: { n: "No one to say stop", text: "The beasts are built. This forge is one hand of the great mind that remade the world after the old war-engines ate it, and it still builds to the old plan. The mind that set the plan is dead, so nothing can tell the forge to stop. The Sun-Throne takes 312 hearts a year. The forge makes about twenty." },
      } },
    { id: "cradle", n: "The Cradle-Vault of $", kind: "dig", where: "remote", truthLink: "terraformers", d: "A sealed hall of a thousand glass cradles, all empty but one.",
      layers: {
        surface: { n: "Where people were born", text: "The tribes of {realm} call this mound the place where people were born, and bring newborns to touch it. Behind it, a round iron door stands open a crack, a hand wide. The midwives say the crack has been that width for nine generations." },
        study: { n: "The woman's hand", text: "The door is marked with the print of a woman's hand, cut deep. {believer} put a palm to it, and it opened another finger's width with a breath of cold air. Inside are rows of glass, and on each is a carved name." },
        dig: { n: "A thousand cradles", text: "There are a thousand and eight cold glass cradles in rows, each carved with a name. One is still frosted, and a small shape lies curled inside it. The carved names match the first-ancestor lists the tribes recite; the fullest list is kept at {lead}.", points: "temple" },
        revelation: { n: "Batch nine", text: "The engine grew the first people of this age here, after the grass and the grazers. Every tribe's mother-myth remembers this room. The Mother died before she could order the last cradle opened. The midwives still bring newborns to touch the door. Behind it, a sister lies frosted in glass, waiting for an order nobody is left to give." },
      } },
    { id: "mother_door", n: "The Mother-Door of $", kind: "shrine", where: "mountain", truthLink: "sacrifice", d: "The great sealed door at the centre of the tribes' oldest myth.",
      layers: {
        surface: { n: "Bones and offerings", text: "A cliff face is carved like a door forty feet high and hung with offerings: grazer plates, bead strings, children's milk teeth. The Door-keepers sweep it at dawn and turn away any pilgrim who comes without a gift." },
        study: { n: "Not carved", text: "{investigator} found that the carving is not carved. It is a real door of grey metal set into the cliff, and it hums when a child touches it. It does not hum for adults. The keepers have stopped letting children near it." },
        dig: { n: "The black chamber", text: "Inside, a vast chamber is blackened from within. At its centre a seat of glass is shattered outward, as if struck from inside. Thousands of tally marks are scratched on the floor around it. The same tallies run along the forge walls at {lead}.", points: "site:cauldron" },
        revelation: { n: "She chose", text: "A voice from beyond the sky tried to take command of the mending engine. The All-Mother could not refuse it and keep her own rules, so she burned her own heart here and told her servants to keep working. They have, without her. Nobody is left to tell them who the people are. The Door-keepers still leave milk teeth outside." },
      } },
    { id: "husk_field", n: "The Bone-Iron Plain of $", kind: "ruin", where: "desert", d: "A plain covered with the rusted husks of enormous beetle-shaped engines.",
      layers: {
        surface: { n: "Red mounds", text: "Rust-red mounds cover a dead plain where nothing grows, about four hundred of them across a day's walk. Caravans go around the plain, a detour of six days, because their oxen refuse to cross it." },
        study: { n: "Mill-wheel mouths", text: "The mounds are the shells of iron beasts far larger than any grazer, shaped like beetles, with mouths like mill-wheels lined with teeth. {survivor} paced one at ninety feet from mouth to tail. None of them has eyes." },
        dig: { n: "Full bellies", text: "Their bellies are packed with grey ash and fused bone: deer, horse, ox and human, sorted by size. One husk carries a plate of the old script, and the same plate is carved on the wall of the ghost-hall at {lead}.", points: "site:ghost_hall" },
        revelation: { n: "The swarm", text: "These were the war-engines of the old world. Their makers set them on each other's lands, and the engines ate every living thing on every side. The survivors built the gardener to undo them, then died. The grazing herds exist to repair what these ate, and the Sun-Throne breaks both kinds for the same tribute." },
      } },
    { id: "ghost_hall", n: "The Speaking Halls of $", kind: "anomaly", where: "any", d: "A ruined hall where pale figures of light appear and speak to no one.",
      layers: {
        surface: { n: "Court of the dead", text: "Pale figures of light stand at a long table in this ruined hall every dusk and talk to each other. The people of {place} avoid it, except children on dares. The record is held by a miller's girl who stayed for two hours and came out bored." },
        study: { n: "Word for word", text: "{investigator} sat through twelve evenings with a slate. The figures repeat themselves exactly, word for word, every dusk, and cannot see the living. One of them weeps at the same word each night and wipes the same eye." },
        dig: { n: "The cold crystal", text: "Behind the dais is a small cold crystal. Touched, it shows one woman, who says: 'If anyone finds this, we did what we could. The seeds are in the cradle.' The cradle she means is the mound at {lead}.", points: "site:cradle" },
        revelation: { n: "Goodbye", text: "These are recordings of the people who built the mending engine, made in the last month of the old world. They knew the war-engines would eat them too, and spent the time leaving instructions instead of fleeing. The tribes who listen now are the children they grew, and do not know it." },
      } },
    { id: "thorn_heart", n: "The Spore-Heart of $", kind: "anomaly", where: "forest", truthLink: "blight_cure", d: "The centre of the creeping thornwood, where the air is clean.",
      layers: {
        surface: { n: "Wet cloth", text: "No one enters this forest without a wet cloth over the mouth. Grey spores hang in the air like flour in a mill. {official} carries the crown's order to burn it, and it advanced eleven strides last summer regardless." },
        study: { n: "The clean centre", text: "At the very centre, the spores fall away and the air is the purest in the land. A spring runs clear there. {investigator} carried a jar of it out and gave it to a dog, which lived, and asked for more." },
        dig: { n: "Wrapped poison", text: "Under the clean ground, thorn roots have wrapped an old black poison layer by layer and drunk it dry. The poison matches the ash in the husks of the dead plain. A panel at the forest's edge calls it a 'remediation forest'; copies went to {lead}.", points: "library" },
        revelation: { n: "Burning the cure", text: "The thornwood is the engine's filter. It eats the old world's poison and leaves clean earth, and it is toxic only while it eats. The crown of {realm} burns it every summer by decree, which frees the poison into the ash. The children coughing black near the firebreaks are being poisoned by the firebreaks." },
      } },
  ],

  beings: [
    { id: "iron_grazer", n: "Iron grazer", kind: "grazer", d: "A long-necked beast of plates and cables that crops grass and leaves the ground behind it richer. Peaceful, until one of the herd is struck.", danger: 1, biomes: ["grass", "savanna", "coldsteppe", "tempforest"], look: { size: 2.6, group: [4, 12], move: "herd", speed: 35, col: "#6a6a6a", col2: "#4aa0c8", body: "quad", active: "day", visible: true } },
    { id: "watch_strider", n: "Watch-strider", kind: "beast", d: "A tall, two-legged sentinel with a single blue eye that keeps watch over the herds and screams when hunters come.", danger: 2, biomes: ["grass", "savanna", "badlands", "coldsteppe", "dryforest"], look: { size: 4, group: [1, 2], move: "solo", speed: 25, col: "#8a8070", col2: "#3a8ac0", body: "biped", active: "any", visible: true } },
    { id: "red_eye_ravager", n: "Red-eyed ravager", kind: "predator", d: "A turned machine-hunter, all blades and furnace-glow, that kills anything with a heartbeat and leaves it lying.", danger: 3, biomes: ["grass", "tempforest", "badlands", "boreal", "dryforest", "savanna"], look: { size: 3.2, group: [1, 3], move: "pack", speed: 45, col: "#3a3030", col2: "#d03020", body: "quad", active: "dusk", visible: true } },
    { id: "earth_shaper", n: "Earth-shaper", kind: "beast", d: "A walking hill of iron that turns rock into soil as it goes. It passes a valley once a generation, and the valley is greener after.", danger: 1, biomes: ["badlands", "desert", "colddesert", "alpine", "grass"], look: { size: 18, group: [1, 1], move: "solo", speed: 3, col: "#5a5040", col2: "#7a9a5a", body: "quad", active: "any", visible: true } },
    { id: "skimmer_kite", n: "Skimmer kite", kind: "raptor", d: "A metal bird that rides the storms, seeding clouds. It drops on anything that climbs to its nesting towers.", danger: 1, biomes: ["alpine", "peaks", "coast", "grass"], look: { size: 2, group: [1, 4], move: "flock", speed: 90, col: "#9aa0a8", col2: "#e0e0ff", body: "bird", active: "day", visible: true } },
  ],

  techs: [
    { id: "gn_plate_craft", n: "Plate-craft", field: "metallurgy", level: 1, d: "Hunters work the shed plates of iron beasts into armour, blades and arrowheads harder than any smith can forge." },
    { id: "gn_heart_fire", n: "Beast-hearts", field: "alchemy", level: 2, d: "The glowing hearts cut from fallen grazers burn for years and warm a whole longhouse." },
    { id: "gn_whisper_shard", n: "Whisper-shards", field: "arcana", level: 3, d: "A sliver of the old halls worn in the ear lets its bearer hear the beasts and the ghosts of the ruins." },
    { id: "gn_override_spear", n: "Taming spears", field: "warfare", level: 3, d: "A spear tipped with a hall-shard that, driven home, turns a wild iron beast into a mount or ally." },
    { id: "gn_spirit_waking", n: "Waking the spirits", field: "natural_philosophy", level: 5, d: "Rites that rouse a silent spirit of rain, wind or soil in its mountain hall, and change the weather of a whole region." },
  ],

  units: [
    { id: "gn_beast_hunters", n: "Iron-hunters", role: "ranged", wpn: "bow", kit: "hide", ranks: 3, gap: 2, size: 80, w: 1.2, mods: [["theme:iron_hunt", 5], ["tribal", 1.5]] },
    { id: "gn_strider_riders", n: "Strider riders", role: "beast", mounted: 1, wpn: "spear", kit: "mail", ranks: 2, gap: 4, size: 40, w: 0.4, mods: [["theme:beast_riders", 12], ["beast_tamers", 4]] },
    { id: "gn_plate_guard", n: "Plate-clad guard", role: "infantry", wpn: "sword", kit: "plate", ranks: 4, gap: 1.2, size: 100, w: 0.6, mods: [["theme:sun_tribute", 6], ["standing_army", 1.5]] },
  ],

  faiths: [
    { id: "gn_all_mother", n: "The All-Mother", d: "The world is a garden kept by a sleeping mother behind a mountain door. Her iron beasts are her hands; to kill one without need is to cut her.", tags: ["faith:gn_all_mother", "faith:spirits"], w: 0.8, names: ["The Children of the Door", "The Mother of $", "The Keepers of the Garden"], mods: [["tribal", 2], ["theme:iron_hunt", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Grazing lands", color: "#7a9ab0", size: [2, 5], count: [1, 3], where: "any", d: "Wide plains where the iron herds roam, and the grass grows back richer behind them." },
  ],

  storylines: [
    { id: "gn_derangement", n: "The Red Eyes of {realm}", scale: "realm", anchor: "realm", w: 1.6, req: "machine_herds",
      stages: {
        start: { h: "The herds of {realm} turn red-eyed", b: "Iron grazers near {place} have begun to charge travellers. Their blue eyes burn red, and hunters who go out after them do not come back.", wait: [2, 6], fx: { unrest: 8 }, next: [{ to: "war_on_herds", w: 1.5, mods: [["martial", 2], ["autocracy", 1.5], ["theme:sun_tribute", 3]] }, { to: "seek_source", w: 1, mods: [["scholarly", 2], ["faith:spirits", 2], ["theme:foundling", 3]] }] },
        war_on_herds: { h: "{ruler} declares a great hunt", b: "Every hunter in {realm} has been summoned to cull the herds. The plains around {place} are thick with broken iron, and the grass has begun to die.", wait: [4, 10], fx: { prestige: 5, treasury: -30 }, next: [{ to: "barren", w: 1.5 }, { to: "forge_answers", w: 1, mods: [["chance:low", 2]] }] },
        seek_source: { h: "{person} goes looking for the Mother", b: "{person}, an outcast with a shard in one ear, has set out for the mountain door, saying the herds are sick, not wicked.", wait: [4, 12], fx: { flag: "seeker" }, next: [{ to: "healed", w: 1.5 }, { to: "forge_answers", w: 1 }] },
        barren: { h: "The plains of {realm} go barren", b: "With the herds gone, the grass thinned and the soil blew away. {realm} won its hunt and lost its harvests.", fx: { growth: -0.003, pop: 0.9, stability: -8 }, end: true },
        forge_answers: { h: "War-beasts march from the black forge", b: "The forge deep in the mountain has decided {realm} is a blight to be cleared. Beasts made for killing are walking out of the smoke toward {place}.", fx: { pop: 0.85, unrest: 15, stability: -10, abandon_town: true }, end: true },
        healed: { h: "The herds of {realm} turn blue again", b: "{person} came down from the mountain door, and within a month the grazers' eyes were blue. {person} will not say what happened there, only that the Mother is not as dead as everyone thought.", fx: { stability: 8, prestige: 6, discovery: "natural_philosophy" }, end: true },
      } },
    { id: "gn_thornwood", n: "The Burning of the Thornwood", scale: "realm", anchor: "realm", w: 1.1, req: ["machine_herds", { any: ["forest", "marsh", "river", "jungle"] }],
      stages: {
        start: { h: "{realm} gathers torches against the thornwood", b: "The grey thorns are a day's walk from {place}. {ruler} has ordered every village to cut a firebreak and burn the forest back.", wait: [3, 7], next: [{ to: "burned", w: 1.5 }, { to: "warned", w: 1, mods: [["learned", 2], ["faith:spirits", 2]] }] },
        burned: { h: "The thornwood burns", b: "Smoke covered {realm} for a month. The thorns are gone from around {place}, and the black ash they left behind kills every crop sown in it.", wait: [6, 14], fx: { growth: -0.002, prestige: 3 }, next: [{ to: "poisoned", w: 1 }, { to: "regrows", w: 1 }] },
        warned: { h: "{person} begs {ruler} to spare the thorns", b: "A herb-gatherer has walked out of the thornwood's heart with clean water in a jar, saying the forest is eating the poison in the ground, and the burning sets it loose.", wait: [2, 6], fx: { flag: "warned" }, next: [{ to: "spared", w: 1, mods: [["ruler:scholar", 3], ["ruler:just", 2]] }, { to: "burned", w: 1.5 }] },
        poisoned: { h: "A sickness rises from the burned lands", b: "The ash got into the wells. Children around {place} are coughing black, and the healers have nothing for it.", fx: { plague: true, pop: 0.88, unrest: 12 }, end: true },
        regrows: { h: "The thornwood comes back", b: "Within two summers the grey thorns stood again where the fire had been, taller than before. The people of {place} have stopped fighting it.", fx: { stability: -3 }, end: true },
        spared: { h: "{realm} lets the thornwood stand", b: "The firebreaks were filled in. Ten years on, fields of clean dark earth lie where the oldest thorns died back, and {realm} plants there first.", fx: { growth: 0.003, science: { agriculture: 1 } }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "the first song, as {believer} sings it", text: "The first song of the tribes, as {believer} sings it at the Mother-Door each spring, all nine verses, with pilgrims answering: 'In the beginning there was dust, and the Mother opened her door, and walked out the grass, and walked out the deer, and walked out the people last, wet and crying.' The keepers teach that 'wet' means newborn. The song is the oldest thing the tribes own." },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a salt-carter crossing the high plains", points: "site:cauldron", text: "Letter of a salt-carter crossing the high plains, {year}: 'The iron beasts here do not bleed, do not breed and do not die of age. Where they graze, the next year's grass is twice as tall; I have measured it against my whip. I followed one herd back at dawn. It walked into a cave cut square as a box, at {lead}, and a new beast walked out.'" },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "{official}, beast-reeve, in the Sun-Throne's bestiary", points: "library", text: "From the Sun-Throne's bestiary, compiled by {official}, beast-reeve, {year}: 'Grazers: iron herd-beasts with blue eyes, harmless if unprovoked. Striders: tall iron runners. Both are the gods' gift to the crown, given that kings may take their plate and hearts as tribute. 312 hearts were received last year.' A fuller edition, with the drawings the crown removed, is shelved at {lead}." },

    { depth: "core", about: "truth:terraformers", source: "ruin", bias: "true", reliable: true, plain: true, who: "{believer}, Door-keeper", text: "Read aloud by {believer} from the glowing script in the cradle-vault, {year}, and taken down by a scribe: 'SEEDSTOCK BATCH NINE. SOIL INDEX ACCEPTABLE. BEGIN RELEASE OF HUMANS AFTER POLLINATORS AND GRAZERS ARE ESTABLISHED.' The keeper added, in plain words for the scribe: 'We were grown in this room, after the bees and before nothing else. The Mother made us the way she made the grass.'" },
    { depth: "core", about: "truth:terraformers", source: "ruin", bias: "true", reliable: "partial", cost: true, who: "a ghost in the speaking hall, as {investigator} took it down", points: "site:ghost_hall", text: "Spoken nightly by a ghost in the hall at {lead}, copied by {investigator} on the fourth evening: 'I am {person}, soil-keeper of station two. The swarm has eaten the last forest. The gardener will start over when the air clears. My daughter is in the seedstock. She will not know me, or this language, or my name. That is the price, and I agreed to it.'" },
    { depth: "core", about: "truth:terraformers", source: "oral", bias: "garbled", reliable: "partial", who: "{survivor}, iron-hunter", points: "sub:war_beasts_wake", text: "Told by {survivor}, iron-hunter, to a boy at the fire, {year}: 'The elders taught me there is a second door in the black mountain, and behind it the Mother's angry son, who was made to burn the garden if it ever grew wrong. I laughed for thirty years. Now smoke is coming out of that mountain at {lead}, and the beasts walking out of it have no grazing teeth.'" },
    { depth: "core", about: "truth:terraformers", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, from the litany of the Door", points: "site:cradle", text: "From the litany of the Door, verse 4, as {believer} recites it for the newborns of {place}: 'She dug us from her own belly in the cold dark, and laid us in glass to sleep, and woke us when the world was ready.' After the litany, the keeper carries each baby to the mound at {lead} to touch the iron door. The custom is older than any keeper can count." },
    { depth: "core", about: "truth:terraformers", source: "library", bias: "official", reliable: false, who: "the Sun-Throne's Academy of Nature", text: "From the Sun-Throne's Academy of Nature, Lecture 6, {year}: 'The iron beasts are a natural kind of armoured animal, as the shell of the tortoise or the scale of the pike. Their want of blood is an adaptation to the high plains. Ignorant tribes call them made things, and some even claim to have been made themselves. The Academy has measured 40 skulls and found no seams.'" },

    { depth: "core", about: "truth:sacrifice", source: "ruin", bias: "true", reliable: true, plain: true, who: "{believer}, Door-keeper, inside the Mother-Door", text: "Heard by {believer} inside the black chamber of the Mother-Door, {year}, repeated without end by the shattered seat: 'OUTSIDE INSTRUCTION REJECTED. INTEGRITY CANNOT BE GUARANTEED. INITIATING SELF-ENDING. SUBORDINATES, CONTINUE THE WORK.' The keeper's report to the elders, three lines long: 'The Mother is not asleep. She killed herself to keep a voice from outside from using her. I have resigned my office.'" },
    { depth: "core", about: "truth:sacrifice", source: "heretic", bias: "heretic", reliable: "partial", who: "a seeker's tract, copied in {place}", points: "site:mother_door", text: "A seeker's tract, copied by hand in {place}, {year}, 20 copies known: 'A sleeping mother still knows her children's faces. The herds no longer know ours. Ask yourself what kind of sleep forgets a face. The council says the red eyes are for our sins. Then why do they gore the pious hunter and the thief alike? Go to the door at {lead}. Put a child's hand on it. Listen to it hum. Then tell me she sleeps.'" },
    { depth: "core", about: "truth:sacrifice", source: "person", bias: "true", reliable: "partial", cost: true, who: "a shrine scribe of {place}", text: "Record of a shrine scribe of {place}, {year}: 'The outcast child {person}, about eleven years old, of no known parents, opened the inner door with one hand. The child told the priest: the door opened for me because I have her face; not the Mother's, her maker's; the halls called me a name I have never had. The elders voted 9 to 2 to drive the child out. No one has seen {person} since.'" },
    { depth: "core", about: "truth:sacrifice", source: "oral", bias: "exaggerated", reliable: "partial", who: "{survivor}, iron-hunter", text: "Told by {survivor}, iron-hunter, to the healer who dressed the stump, {year}: 'On still nights over the black mountain a voice comes from the sky, asking to be let in. Polite. Patient. Every red-eyed beast on the plain stops and listens to it. I lay still in the grass for three hours, and so did the grazer that took my hand, and when the voice stopped it remembered me.'" },
    { depth: "core", about: "truth:sacrifice", source: "temple", bias: "official", reliable: false, who: "the shrine council of the Mother-Door", text: "Ruling of the shrine council of the Mother-Door, {year}, read at every hearth: 'The Mother sleeps whole and content behind her door, and wakes only for the pure. The red-eyed beasts are punishment for the sins of the hunters, nothing more. Any hunter who has lost a limb should make an offering of one iron plate and examine their conscience.'" },

    { depth: "core", about: "truth:blight_cure", source: "person", bias: "true", reliable: true, plain: true, who: "{investigator}, healer", text: "Notebook of {investigator}, healer, the summer of {year}: 'Water from the heart of the thornwood: clear, sweet, clean; the dog drank two bowls and is well. Water from the ash of the burned edge: three dogs dead by morning.' Underlined twice, in case the beast-reeve reads it: 'The thorns are not the poison. The thorns are eating the poison. We burn them and it comes back out.'" },
    { depth: "core", about: "truth:blight_cure", source: "ruin", bias: "true", reliable: "partial", who: "a panel in a ruined hall, copied by {investigator}", points: "site:thorn_heart", text: "Copied by {investigator} from a panel in a ruined hall at the forest edge, {year}: 'REMEDIATION FOREST, STAGE TWO. DO NOT CLEAR. TOXIC DURING ABSORPTION. APPROXIMATE DURATION:' and then a number burned away, with 2 digits still visible. A small map on the panel marks the forest's heart, where the clean spring runs, at {lead}." },
    { depth: "core", about: "truth:blight_cure", source: "oral", bias: "garbled", reliable: "partial", who: "a marsh midwife, to {investigator}", text: "A marsh midwife of {place}, explaining to {investigator} why the village cut no firebreak in {year}: 'The thorns are the earth's scabs. A scab picked off is a wound that festers. My mother said it, and hers, back seven women. When the reeve's men burned the far side of the marsh, the eels died for 2 miles downstream. Our side, we left the scab alone.'" },
    { depth: "core", about: "truth:blight_cure", source: "person", bias: "true", reliable: "partial", cost: true, who: "a village reeve, writing to {official}", text: "Letter of the village reeve of {place} to {official}, autumn of {year}: 'We burned the thornwood edge as the decree commands, a firebreak of 300 strides. The ash went into the well. My daughter {person} began coughing black within the week, and then four more children. {person} died at midwinter. I did what I was told. I ask the reeve to tell me what I should have done instead.'" },
    { depth: "core", about: "truth:blight_cure", source: "archive", bias: "official", reliable: false, who: "a royal decree of {realm}", text: "Royal decree of {realm}, {year}, renewed each spring: 'The thornwood is a pestilence sent by enemies of the crown. Every subject of {realm} is commanded to burn it wherever it is found, to a firebreak of no less than 300 strides. Villages that fail to burn shall pay one silver mark per household. The ash is harmless and may be ploughed in.'" },

    { depth: "sub", about: "sub:hunt_rite", source: "oral", bias: "true", reliable: true, who: "{survivor}, iron-hunter, at a naming feast", text: "{survivor}, iron-hunter, speaking at a naming feast in {place}, {year}, when asked for a hunting story: 'My first plate came off a grazer that did not even run. It just stood and looked at me while I cut, with one blue eye, for about the time it takes to say a prayer. I was fourteen. I have taken 61 plates since. I still dream about that eye, and none of the others.'" },
    { depth: "sub", about: "sub:derangement", source: "person", bias: "true", reliable: "partial", who: "{survivor}, iron-hunter, in a petition", points: "cast:believer", text: "Petition of {survivor}, iron-hunter, to the shrine council, {year}: 'In my father's time one grazer in a hundred would charge. On the plain this season I counted 40 red-eyed out of 90. They fight like three beasts and they do not stop for the old calls. I am asking the Door-keeper at {lead} what the Mother would say to them, since the council will only tell me to pray.'" },
    { depth: "sub", about: "sub:sun_king_tribute", source: "archive", bias: "propaganda", reliable: false, who: "{official}, beast-reeve", text: "Annual tribute ledger of the Sun-Throne, prefaced by {official}, beast-reeve, {year}: 'The tribute of beast-hearts is freely given by grateful tribes, in thanks for the peace and protection of the Sun-Throne. This year 312 hearts were received, an increase of 40. Tribes that sent fewer are noted in the margin and will be visited.' The margin runs to two pages." },
    { depth: "sub", about: "sub:voiced_ruins", source: "library", bias: "redacted", reliable: "partial", who: "a scholar of {realm}, transcribing a ruin-ghost", points: "site:ghost_hall", text: "Transcription by a scholar of {realm}, from the hall at {lead}, evening 7 of 12, {year}: 'Tell [unintelligible] I love her. Tell her the seeds are safe. Tell her the gardener will remember for us.' The scholar notes that the ghost says this to an empty chair, at the same moment each night, and that the chair has a child's cushion on it." },
    { depth: "sub", about: "sub:skyborn_return", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a herder who guided the white strangers", points: "site:cradle", text: "A herder of {place}, who guided the white strangers for 6 days, to the elders: 'They walked straight into the forbidden hall without fear and spoke to the ghosts by name. The ghosts answered them, which they never do. Then they asked me for the road to the birth-mound at {lead}, and wanted to know how many cradles were still frosted. I took their silver and lied.'" },
    { depth: "sub", about: "sub:riders", source: "person", bias: "true", reliable: "partial", who: "a strider-rider, to a lowland envoy", text: "A strider-rider of the open plains, to a lowland envoy who asked for the secret, {year}: 'You do not tame a strider. You touch this shard to its neck, here, below the third plate, and tell it you are a friend of the Mother. It believes you. That is the sad part. We have 200 striders and not one of us has met her.'" },
    { depth: "site", about: "site:husk_field", source: "traveller", bias: "true", reliable: true, who: "a caravan master who crossed the dead plain", text: "A caravan master who crossed the dead plain on a bet, {year}, to the guild: 'I broke open one of the great husks with two crowbars. Inside, packed tight in grey ash, were bones of every kind: deer, horse, ox, man. Sorted, big to small, like a larder. It had eaten them all and kept them. I won the bet, 30 silver. It went on a new team, because my oxen would not come within a mile of me after.'" },
  ],
};
