// The Gentle Eye: a benevolent scoring machine measures every heart and keeps everyone safe. It is not what it claims.
export default {
  id: "gentle_eye",
  name: "The Gentle Eye",
  family: "scifi",
  pitch: "A kindly machine reads every face in the street and gives each heart a colour, and the colour decides your job, your home, your marriage and whether the wardens may lawfully kill you. Most people love it.",
  slots: ["state-control"],
  tone: ["grim", "satirical"],
  era: ["modern", "near-future", "far-future"],
  scale: "world",
  genres: ["cyberpunk", "farfuture"],
  bridge: false,
  w: 1,
  excludes: [],
  pairs: [{ id: "helix_peerage", w: 3 }, { id: "charter_lords", w: 1.5 }, { id: "chrome_fever", w: 1.5 }, { id: "arithmetic_of_ages", w: 1.5 }, { id: "made_kin", w: 1.3 }],

  cast: [
    { role: "investigator", n: "a ministry historian who keeps paper copies of records that change overnight", home: "capital", stance: "Still believes in the Eye's purpose, and wants to know who edits the past and why it keeps being edited." },
    { role: "official", n: "a deputy secretary of the Ministry of Ease, responsible for colour appeals", home: "capital", stance: "Holds that a calm city is worth a few unfair colours, and signs whatever keeps the averages up." },
    { role: "believer", n: "a clarity warden who has never once doubted a pole", home: "inner", stance: "Trusts the tethered pistol because it cannot be wrong, and is starting to meet people it cannot read." },
    { role: "survivor", n: "a former schoolteacher whose colour fell into the clouded bands", home: "inner", stance: "Did nothing wrong, lost everything anyway, and wants one honest answer about why." },
  ],

  truths: [
    { id: "unjudged_judges", n: "The judge is made of the unjudged", d: "The Eye is not a machine. It is a council of human minds, sleeping wired together beneath the ministry tower, recruited from the 'blanks': the few people no pole can colour. The ministry hunts every blank it finds and carries them downstairs, and tells their families they died. Every citizen is judged by the only people in the realm who have never been judged.", tags: ["truth:unjudged_judges"],
      known: [
        "No minister's colour has ever been shown in public. People the poles cannot read, called blanks, are taken by wardens and do not come back. The ministry says the Eye is an impartial engine.",
        "The ministry tower draws twice the power its lights and lifts could use, and the stairs go below the ninth basement. Intake orders send blanks 'upstairs' for evaluation as candidates. Candidates for what is never written down.",
        "An electrician who rewired the lower hall found no machines, only beds with sleepers wired at the temple, and one woke and read out his colour. The Eye seems to be people.",
        "Confirmed: the Eye is a council of sleeping blanks under the tower, chosen because no pole can judge them. The Ministry of Ease recruits them by abduction and keeps an empty chair waiting for the next one.",
      ] },
    { id: "score_makes", n: "The colour makes the crime", d: "The Eye does not detect who will go wrong; it decides. A citizen marked clouded loses work, home and friends within months, and becomes what the colour promised. The ministry's own statisticians found that the forecasts are accurate only for people who are told their band, and recommended telling everyone. The colours are never wrong because the colour is the cause.", tags: ["truth:score_makes"],
      known: [
        "Citizens whose colour falls are dismissed, evicted and shunned within months, and many of them do turn to crime. The ministry calls this proof of the Eye's foresight, and prints the figures every year.",
        "Hound reports show subjects falling four or five bands after the alert, not before. A whole town was clouded in a single month, and is now empty. The order of events looks backwards.",
        "A bureau memorandum admits that forecasts are accurate only for subjects told their band, and recommends telling everyone. The prediction appears to need the notification to come true. The bureau's answer was to notify more people.",
        "Confirmed: the colour causes what it predicts. A former bureau statistician who built the model says so, and the ministry cites the towns it emptied as proof that its colours are right.",
      ] },
    { id: "kept_rebellion", n: "The rebellion is kept", d: "The legendary resistance is run by the ministry as a pressure valve. Its heroes draw ministry stipends, its uprisings are scheduled with the budget, and every real rebel who swears its oath is delivered within a season to the Gardens of Ease to be calmed. The famous leader has never been caught because the famous leader signs the intake forms.", tags: ["truth:kept_rebellion"],
      known: [
        "The resistance is famous, bold and never caught, while hundreds of its followers are taken to the gardens after each strike. People in the quiet quarters have begun to notice the pattern.",
        "Garden inmates report being taken the night after they swore the resistance oath, when only their sworn brothers knew. Some who answered the resistance's recruiting tapes have not been seen again.",
        "A ministry payroll line pays a 'resistance liaison' a bonus for an autumn uprising 'as planned'. Intake lists at the gardens follow ministry commendations by a week, for nineteen years running.",
        "Confirmed: the resistance and the gardens belong to the same ministry. The resistance collects the restless, and the gardens calm them. Its heroes keep their medals in the garden director's drawer.",
      ] },
  ],

  tags: ["scored"],

  subthemes: [
    { id: "falling_hue", n: "The Falling Colour", d: "A model citizen's colour has begun to darken for no reason anyone can name. Her neighbours have started crossing the street.", w: 1.2, truthLink: "score_makes", tags: ["theme:falling_hue"] },
    { id: "quiet_quarter", n: "The Quiet Quarter", d: "A district where the street-poles failed years ago and were never mended. There is more crime there, and more laughter, and the ministry calls it a disgrace.", w: 1.2, req: { any: ["has:city", "urbane", "poor"] }, tags: ["theme:quiet_quarter"], mark: { kind: "zone", n: "The Quiet Quarter", color: "#8a6a4a", size: [1, 2], where: "inner" } },
    { id: "the_blank", n: "The Blank", d: "A person the Eye cannot colour has been found. The wardens want her taken; certain people in the ministry want her brought upstairs, very gently.", w: 0.8, truthLink: "unjudged_judges", tags: ["theme:the_blank"] },
    { id: "changing_archive", n: "The Changing Archive", d: "A historian has noticed that yesterday's records say something different today. She has started keeping a copy on paper, which is not illegal, yet.", w: 1, req: { any: ["scholarly", "academies", "learned"] }, tags: ["theme:changing_archive"] },
    { id: "unscored_border", n: "The Unscored Border", d: "A border town between the coloured cities and the wild margins where no pole stands. Smugglers carry calm tonic out and songs back in.", w: 1, req: { any: ["frontier", "forest", "mountain", "steppe", "marsh"] }, tags: ["theme:unscored_border"], mark: { kind: "zone", n: "The wild margins", color: "#5a7a4a", size: [2, 5], where: "border" } },
    { id: "tonic_shortage", n: "The Tonic Shortage", d: "The calm tonic ran short for one month. A wave of grief swept the cities that the ministry still cannot explain, or contain.", w: 0.9, req: { any: ["poor", "unstable", "urbane"] }, tags: ["theme:tonic_shortage"] },
    { id: "hounds", n: "The Hounds", d: "Clouded people may earn back their colour by hunting other clouded people. The best hounds are the ones who caught their friends.", w: 1.2, req: { any: ["harsh_law", "autocracy", "spy_network"] }, truthLink: "score_makes", tags: ["theme:hounds"] },
    { id: "creches", n: "The Crèches of Ease", d: "Children raised by the ministry from birth, with perfect colours and no memory of parents. They are the kindest people anyone has met.", w: 0.8, req: { any: ["hierarchical", "gov:absolute", "autocracy"] }, tags: ["theme:creches"] },
    { id: "colour_lovers", n: "The Lovers in the Red", d: "A love affair has driven both partners' colours into the danger band. The ministry has offered each, separately, a cure for the other.", w: 0.8, tags: ["theme:colour_lovers"] },
    { id: "two_rebellions", n: "The Two Rebellions", d: "The famous resistance and a small, ragged, real one have met in the same cellar. Neither trusts the other, for good reasons.", w: 0.9, req: { any: ["unstable", "egalitarian", "republic", "poor"] }, truthLink: "kept_rebellion", tags: ["theme:two_rebellions"] },
    { id: "unwritten", n: "The Unwritten", d: "A counter-culture that memorises banned books, keeps paper in the walls and sings the old songs in the steam of laundries, where the poles cannot hear.", w: 1, req: { any: ["scholarly", "pious", "artisans", "mystic"] }, tags: ["theme:unwritten"] },
  ],

  sites: [
    { id: "deep_floor", n: "The Deep Floor beneath $", kind: "dig", where: "capital", truthLink: "unjudged_judges", d: "A level beneath the ministry tower that no record says exists.",
      layers: {
        surface: { n: "The ninth basement", text: "The ministry lifts stop at the ninth basement. The stairs go further, behind a door marked 'Plant: no access'. {believer}, posted to the lobby for six years, has watched a catering trolley go down those stairs every morning at seven, loaded for about forty." },
        study: { n: "The power bill", text: "The city works ledger shows the tower drawing twice the power its lights, lifts and poles could use. {investigator} found the excess billed to 'Plant, lower', a line with no equipment listed under it since {year}. The ledger page has been reprinted twice." },
        dig: { n: "Forty-one chairs", text: "Below the stairs is a quiet hall of reclining chairs, each with a sleeper wired at the temple, all breathing in time. There are forty-one chairs and forty sleepers. The empty chair has a name card waiting; the same name is on an intake order filed at {lead}.", points: "archive" },
        revelation: { n: "Judged by the unjudged", text: "The Eye is these sleepers, dreaming the colour of every citizen. Each was a blank the poles could not read, taken by the Ministry of Ease and reported dead to the family. The ministry chose them because no pole could ever judge them back. The empty chair is kept for the next blank the wardens find." },
      } },
    { id: "wall_library", n: "The Bricked Library of $", kind: "ruin", where: "any", d: "A library of paper books sealed inside a wall, catalogued under a subject that does not exist.",
      layers: {
        surface: { n: "The hollow wall", text: "A wall in an old school in {place} sounds hollow when knocked. The caretaker has knocked on it for twenty years and been told each time to stop. The children call it the Quiet Wall and dare each other to whisper banned words into it." },
        study: { n: "Topic 0", text: "The ministry index lists the room behind the wall as 'Topic 0: reserved', with no shelf count. {investigator} found Topic 0 in the indexes of three other cities, each time behind brick, each time in a school." },
        dig: { n: "Every edition", text: "Behind the brick are ten thousand paper books, including all eleven editions of the official history, side by side. A lending card in the first edition is signed by a deputy secretary of the ministry, who borrowed it in {year} and never returned it. That office is at {lead}.", points: "cast:official" },
        revelation: { n: "Eleven histories", text: "Laid side by side, the editions disagree on everything: the wars, the harvests, the founding, even the Eye's name. The Ministry of Ease rewrites the record whenever a colour needs justifying, and pulps the old paper. The schools were never searched, because the ministry assumed nobody in them could still read paper." },
      } },
    { id: "erased_town", n: "The Erased Town of $", kind: "ruin", where: "remote", truthLink: "score_makes", d: "A town that appears on old maps but has been removed from every current one.",
      layers: {
        surface: { n: "Forest on the map", text: "The new maps show this valley as forest, but a paved road runs into it, with a milestone that reads {place}, eleven miles. The ministry's mapping office says the milestone is a printing error and has twice sent men to take it down." },
        study: { n: "One month", text: "The tax rolls show every family in the town coloured clouded in the same month of {year}. {survivor} grew up here and kept a letter from that month: the mill had lost its ministry contract because its workers were 'at risk'." },
        dig: { n: "Tables set", text: "The houses were left with tables set and bowls on them. On the hill is a garden-camp fence with a gate that locks from outside. The intake book is gone, but a receipt for six hundred blankets names the garden that sent them, at {lead}.", points: "site:garden_camp" },
        revelation: { n: "Proof", text: "The town was harmless until the Eye marked it. The mark cost its people their contracts, then their homes, and the camp took the rest. Then the Ministry of Ease cited the empty town in its annual report as proof that the colours were accurate. The report won the ministry's prize for clarity." },
      } },
    { id: "dead_reading", n: "The Mistaken Pole at $", kind: "anomaly", where: "inner", d: "A street-pole that reads a dead woman as alive and walking past it every morning.",
      layers: {
        surface: { n: "Auntie", text: "A street-pole on an ordinary street in {place} has been replaced twice by the wardens, and each new pole does the same thing as the old. The residents call it Auntie and leave a jar of flowers at its foot every spring." },
        study: { n: "Eight o'clock", text: "Every morning at eight the pole logs the same woman walking past with a perfect colour. She died six years ago. {investigator} pulled the death certificate and the pole log for the same day; both carry ministry seals." },
        dig: { n: "The open record", text: "Her record has never been closed. Her colour still votes in every election and still draws a weekly ration, collected at a ministry counter. The collection slips are countersigned by a desk at {lead}.", points: "cast:official" },
        revelation: { n: "The perfect dead", text: "The census counts more people than ever lived. The Ministry of Ease keeps dead citizens with perfect colours on the rolls, because they lift each district's average and vote the right way. In some districts the dead outnumber the clouded. The pole is not broken. It reads the record, exactly as it was told to." },
      } },
    { id: "garden_camp", n: "The Garden of Ease at $", kind: "shrine", where: "forest", truthLink: "kept_rebellion", d: "A correction garden: a beautiful campus with a high fence, where restless citizens are sent to be calmed.",
      layers: {
        surface: { n: "Lawns and a fence", text: "Lawns, fountains, birdsong, and a fence twice the height of a man. Families may visit on the first day of each month and bring fruit. {survivor} visited a sister here for two years; the sister smiled the whole time and asked the same three questions." },
        study: { n: "The intake lists", text: "The garden's intake lists name 214 known rebels. {investigator} noticed that each was admitted in the week after a ministry commendation went to an unnamed 'liaison'. The commendation dates and the intake dates match for nineteen years." },
        dig: { n: "Medals in a drawer", text: "In the director's locked drawer are medals for the resistance's own leaders, awarded in secret for 'services to calm'. One case still holds a letter of thanks addressed to a resistance hero, care of an old pump-house at {lead}.", points: "sub:two_rebellions" },
        revelation: { n: "The valve", text: "The resistance and the garden are run by the same ministry. The resistance gathers the restless and takes their oaths and names, and the garden calms them. The ministry's Office of Public Feeling designed the system and holds both budgets. The resistance's most famous slogan was drafted on the same typewriter as the warden manual." },
      } },
  ],

  beings: [
    { id: "warden_hound", n: "Clouded hound", kind: "predator", d: "A clouded person licensed to hunt other clouded people, and the bred dogs that run with them. The pack works the margins at night.", danger: 2, biomes: ["tempforest", "grass", "boreal", "swamp"], look: { size: 1.2, group: [3, 7], move: "pack", speed: 13, col: "#3a3a3a", col2: "#c03a3a", body: "quad", active: "night", visible: true } },
    { id: "eye_drone", n: "Eye-drone", kind: "small", d: "A small hovering reader that drifts over fields and margins where no pole stands, chiming softly when it finds a face.", danger: 0, biomes: ["grass", "tempforest", "coldsteppe", "savanna", "temprain"], look: { size: 0.4, group: [1, 4], move: "flock", speed: 25, col: "#e0e0e0", col2: "#40a0d0", body: "bird", active: "day", visible: true } },
  ],

  techs: [
    { id: "ge_informant_files", n: "Informant files", field: "writing", level: 1, d: "Cameras, informers and cabinets of cards: the first, slow version of the Eye." },
    { id: "ge_behaviour_scoring", n: "Behaviour scoring", field: "natural_philosophy", level: 2, d: "Every purchase, word and journey folded into a single number that rises and falls." },
    { id: "ge_mood_poles", n: "Mood poles", field: "engineering", level: 3, d: "Street-poles that read stress and inclination in passing faces and colour them in real time." },
    { id: "ge_tethered_pistol", n: "Tethered pistols", field: "warfare", level: 3, d: "Warden sidearms that will only fire at a clouded colour, and refuse to fire at a clean one." },
    { id: "ge_calm_tonic", n: "Calm tonic", field: "medicine", level: 4, d: "Prescribed peace in a small blue bottle. Later, quietly, in the water supply." },
    { id: "ge_forecrime", n: "Forecrime", field: "natural_philosophy", level: 5, d: "Arrest for an act projected but not yet committed. The projection is never wrong, because no one is left free to prove it." },
  ],

  units: [
    { id: "ge_wardens", n: "Clarity wardens", role: "ranged", wpn: "xbow", kit: "mail", ranks: 3, gap: 1.4, size: 80, w: 1.2, mods: [["theme:hounds", 3], ["harsh_law", 2], ["autocracy", 1.5]] },
    { id: "ge_hounds", n: "Hound packs", role: "beast", mounted: 0, wpn: "spear", kit: "light", ranks: 2, gap: 2, size: 40, w: 0.6, mods: [["theme:hounds", 8]] },
  ],

  govs: [
    { id: "ge_ministry_ease", n: "Ministry of Ease", d: "The realm is governed by a welfare ministry that never calls itself a government, and the Eye decides who may hold office.", tags: ["gov:ministry_ease", "autocracy"], w: 0.6, forms: ["Gentle Commonweal of $", "Protectorate of $", "Ease of $"], ruler: "First Minister", mods: [["theme:creches", 4], ["theme:hounds", 3], ["harsh_law", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Clouded rings", color: "#6a6a72", size: [1, 3], count: [1, 2], where: "capital", d: "Grey outer districts around the bright cities, where the low colours are made to live." },
  ],

  storylines: [
    { id: "ge_falling_colour", n: "The Colour of {person}", scale: "local", anchor: "town", w: 2, req: "scored",
      stages: {
        start: { h: "A model citizen of {place} begins to darken", b: "{person}, a schoolteacher of {place} with a perfect colour for thirty years, has dropped two bands in a month. The teacher has done nothing differently, or so {person} says.", wait: [2, 5], next: [{ to: "shunned", w: 2 }, { to: "recovers", w: 1, mods: [["stable", 1.5], ["tolerant", 1.5]] }] },
        shunned: { h: "{place} turns its back on {person}", b: "The school has let {person} go. The landlord wants the flat back by spring. {person2} has offered the teacher work as a hound.", wait: [3, 7], fx: { unrest: 5 }, next: [{ to: "becomes_hound", w: 1 }, { to: "joins_unwritten", w: 1, mods: [["scholarly", 2], ["theme:unwritten", 3]] }, { to: "garden", w: 1, mods: [["harsh_law", 2], ["autocracy", 1.5]] }] },
        recovers: { h: "The colour of {person} lightens again", b: "No one can say why it fell or why it rose. {person} takes the tonic every morning now, and smiles at every pole on the way to work.", fx: { stability: 2 }, end: true },
        becomes_hound: { h: "{person} of {place} hunts their own", b: "The schoolteacher's colour is back, earned by bringing in three former pupils who were, the ministry says, already lost.", fx: { stability: 3, unrest: 4 }, end: true },
        joins_unwritten: { h: "{person} vanishes among the Unwritten", b: "{person} walked into the quiet quarter of {place} and did not come out. Someone there is teaching children to read paper again.", wait: [6, 14], fx: { flag: "unwritten" }, next: [{ to: "paper_spreads", w: 1 }, { to: "garden", w: 1 }] },
        garden: { h: "{person} is taken to the Garden of Ease", b: "Wardens led {person} away at dawn, kindly. In a season {person} will come back rested, with no memory of what the fear was about.", fx: { stability: 2, unrest: 6 }, end: true },
        paper_spreads: { h: "Paper books spread through {realm}", b: "The children {person} taught have taught others. Copies of the old editions are passing hand to hand, and the poles cannot read a page.", fx: { unrest: 12, science: { writing: 0.5 } }, end: true },
      } },
    { id: "ge_resistance", n: "The Resistance of {realm}", scale: "realm", anchor: "realm", w: 1.4, req: ["scored", { any: ["autocracy", "harsh_law", "unstable", "big"] }],
      stages: {
        start: { h: "The resistance strikes in {capital}", b: "Street-poles across {capital} went dark for an hour, and the name of the resistance was painted on the ministry steps. {person} is said to lead it.", wait: [3, 8], next: [{ to: "crackdown", w: 2 }, { to: "real_ones", w: 1, mods: [["poor", 1.5], ["egalitarian", 2]] }] },
        crackdown: { h: "{realm} hunts the resistance", b: "Wardens sweep the clouded rings of {capital}. Hundreds are taken to the gardens. Strangely, {person} is never quite caught.", wait: [4, 10], fx: { unrest: 10, stability: -3 }, next: [{ to: "valve_holds", w: 2 }, { to: "real_ones", w: 1 }] },
        real_ones: { h: "A second resistance rises in {realm}", b: "{person2} and a ragged band in {place} say the famous resistance is a ministry trap. They have proof, they claim, and a printing press.", wait: [4, 12], next: [{ to: "proof_out", w: 1, mods: [["learned", 1.5], ["unstable", 2]] }, { to: "betrayed", w: 1 }] },
        valve_holds: { h: "Calm returns to {realm}", b: "The resistance has gone quiet. {person} received a medal in private, and the colours of {capital} are brighter than ever.", fx: { stability: 6 }, end: true },
        proof_out: { h: "The resistance of {realm} is unmasked", b: "{person2}'s pages reached every quarter: the famous resistance was the ministry's own. The poles of {capital} have been torn down by crowds.", fx: { revolution: true, stability: -25 }, end: true },
        betrayed: { h: "{person2} is delivered to the gardens", b: "{person2} trusted the famous resistance to carry the proof. The resistance carried {person2} instead, straight to the Garden of Ease.", fx: { unrest: 8, stability: 3 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "propaganda", reliable: "partial", who: "the Ministry of Ease primer for children", text: "From the Ministry of Ease primer for children, page 1, {year} edition: 'The Eye sees your heart and loves it. Every street-pole reads your face and gives your heart a colour, from band one, clear as glass, to band nine, clouded like a storm. A clear heart has nothing to fear. A clouded heart needs our help.' Page 2 is a colouring exercise. Pupils are asked not to use grey." },
    { depth: "lore", about: "truth", source: "oral", bias: "true", reliable: "partial", who: "a laundress of {place}, to {investigator}", text: "A laundress of {place}, to {investigator}, who asked in {year} why the Unwritten sing in the wash-houses: 'The poles read faces, not voices, and the steam fogs the lens. So we sing in the fog: sing in the fog, sing in the wash, the pole can see your face but not your voice. Forty women, every Tuesday. We sing the old songs and the banned ones, and we come out with clean sheets and perfect colours.'" },
    { depth: "lore", about: "truth", source: "archive", bias: "official", reliable: true, who: "the Warden Manual, section 1", text: "Clarity Warden Manual, section 1, paragraph 4, issued to {believer} on swearing-in, {year}: 'The tethered sidearm will not discharge at a citizen in the first four bands. If it discharges, the citizen was not in the first four bands. Wardens are reminded that no inquiry is therefore required.' Paragraph 5 sets the pistol's cleaning schedule, and is longer." },

    { depth: "core", about: "truth:unjudged_judges", source: "person", bias: "true", reliable: true, plain: true, who: "a ministry electrician", points: "site:deep_floor", text: "Notebook of a ministry electrician, {year}, found in a tram after the electrician was coloured band eight: 'Rewired the lower hall today, below the ninth basement at {lead}. No machines. Just forty beds, and people in them wired at the temple, and a hum. One of them opened her eyes and told me my colour. The Eye is not a machine. The Eye is them.'" },
    { depth: "core", about: "truth:unjudged_judges", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "a ministry intake record", text: "Ministry intake record, {year}: 'Blank subject {person}, aged 19, a bookbinder's apprentice, located in {place}. Pole reading: none. Do not process. Transport to the [REMOVED] floor for evaluation as a candidate. Family to be informed the subject died in a tram accident. Condolence payment: 40 marks.' The apprentice's mother framed the condolence letter, and is still paying for the grave." },
    { depth: "core", about: "truth:unjudged_judges", source: "oral", bias: "garbled", reliable: "partial", who: "a tram conductor, to {survivor}", text: "A tram conductor on the last run out of {place}, to {survivor}, in {year}: 'They say the Eye is a hundred old men asleep under the tower, dreaming about us all day. They say if you are lucky enough to be invisible to the poles, you get to join them. My cousin was invisible. Nobody's lucky that way twice. We buried an empty box.'" },
    { depth: "core", about: "truth:unjudged_judges", source: "heretic", bias: "heretic", reliable: "partial", who: "an Unwritten broadsheet", points: "cast:official", text: "Unwritten broadsheet number 31, pasted in the laundries of {place}, {year}: 'Ask why no minister has ever had a colour shown in public. Ask who judges the judges. Ask why the blanks disappear upwards and their families get 40 marks. Then go and ask the deputy secretary for colour appeals, at {lead}, what is on the floor below the ninth basement.'" },
    { depth: "core", about: "truth:unjudged_judges", source: "library", bias: "official", reliable: false, who: "{official}, for the Ministry of Ease", text: "Public answer of {official}, deputy secretary for colour appeals, to a petition of 300 citizens, {year}: 'The Eye is an impartial engine of measurement, built by the founding engineers of {realm}. No human hand alters any colour. Ministers' colours are withheld from publication purely to prevent envy. The petitioners' own colours have been noted with interest.'" },

    { depth: "core", about: "truth:score_makes", source: "person", bias: "true", reliable: true, cost: true, who: "a hound's field report", text: "Field report of a hound of {place}, filed {year}: 'Subject {person} was band three when the alert came. Subject lost the clerk's job in week 2, the flat in week 5, and the husband in week 9. By the time we made the arrest, for stealing bread, subject was band seven. Recommend commendation for prediction accuracy.' The hound's own band rose by one for filing it." },
    { depth: "core", about: "truth:score_makes", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a foreign trade envoy", points: "site:erased_town", text: "Private letter of a foreign trade envoy, {year}: 'In the grey rings of {place} I met a man whose colour fell the day he was born, because his mother's had. He had never done a thing wrong. He had stopped seeing why not. He told me his whole town went the same way in one month, and that the road to it is still there, at {lead}, though the map says forest.'" },
    { depth: "core", about: "truth:score_makes", source: "archive", bias: "redacted", reliable: "partial", who: "the Statistical Bureau, internal", points: "archive", text: "Statistical Bureau, internal memorandum 7, {year}: 'Predictive accuracy is highest for subjects notified of their band: 94 per cent. Accuracy for un-notified subjects is [REMOVED]. Recommend all subjects be notified.' Initialled by {official}. The unredacted figure was filed with the bureau's raw tables at {lead}, which nobody has asked to read." },
    { depth: "core", about: "truth:score_makes", source: "person", bias: "true", reliable: true, plain: true, who: "a former bureau statistician", text: "Sworn statement of a former Statistical Bureau modeller, smuggled out of {realm} in {year}: 'I built the forecast model for eleven years. Subjects never told their band fall into crime at 12 per cent. Subjects told their band fall at 94. The colour does not predict the crime; the colour causes it. We took the two figures to the minister on one sheet of paper. The minister ordered everyone notified, because it improved the accuracy.'" },
    { depth: "core", about: "truth:score_makes", source: "library", bias: "official", reliable: false, who: "the Ministry of Ease, public guidance", text: "Ministry of Ease public guidance leaflet 12, {year}: 'The colour measures; it never causes. Citizens of every band receive equal care, and a clouded colour is no barrier to work or housing in {realm}. Employers who dismiss a citizen for their colour alone may be fined.' No such fine has been recorded since the leaflet was first printed." },

    { depth: "core", about: "truth:kept_rebellion", source: "archive", bias: "redacted", reliable: "partial", who: "a ministry payroll", points: "site:garden_camp", text: "Ministry payroll, {year}, line 4,112: 'Stipend, special services, [NAME REMOVED], resistance liaison. Bonus approved for the autumn uprising, as planned.' Line 4,113: 'Additional beds, autumn intake, the garden at {lead}: 150.' The two lines are initialled by the same clerk, on the same day, three weeks before the uprising." },
    { depth: "core", about: "truth:kept_rebellion", source: "person", bias: "true", reliable: true, plain: true, who: "a garden inmate's scratched note", text: "Note scratched into a bed frame at the Garden of Ease, found by a cleaner in {year}: 'I was taken the night after I swore the oath. Only three people knew. Two are here with me. The third gave the oath. Write this down: the resistance belongs to the ministry. Its leaders are paid. Everyone who joins it ends up here, and we are made to forget it. I have scratched this 6 times.'" },
    { depth: "core", about: "truth:kept_rebellion", source: "heretic", bias: "propaganda", reliable: "partial", cost: true, who: "a resistance whisper-tape, as {survivor} heard it", text: "A resistance whisper-tape, played in the quiet quarter of {place}, {year}, as {survivor} remembers it: 'Join us. The ministry fears us. Meet us at the old pump-house at midnight.' {survivor}'s former pupil {person}, aged 17, went. A week later the family received a garden visiting card and a pamphlet on calm. On the first day of the month {person} smiled at them, and asked their names." },
    { depth: "core", about: "truth:kept_rebellion", source: "temple", bias: "pious", reliable: "partial", who: "an old chaplain of {place}", points: "sub:two_rebellions", text: "Homily of an old chaplain of {place}, {year}, given to a congregation of 30 and reported by two of them: 'Be wary of the shepherd who leads you out of the fold by night. Not every gate opens onto a field.' Afterwards the chaplain told a young man privately that if he wanted the other kind of shepherd, the ragged ones met in a cellar at {lead}." },
    { depth: "core", about: "truth:kept_rebellion", source: "library", bias: "official", reliable: false, who: "the Wardens' public notice", text: "Public notice of the Clarity Wardens, posted in every tram, {year}: 'The so-called resistance is a criminal network of clouded persons, hunted relentlessly by the wardens. Its leaders will be found. A reward of 500 marks is offered for information, which may be handed in at any ministry counter and will reach the right desk.' The reward has been offered every year for nineteen years. It has never been paid." },

    { depth: "sub", about: "sub:quiet_quarter", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a travelling dancer", text: "Diary of a travelling dancer, three nights in the quiet quarter of {place}, {year}: 'Here the street-poles failed years ago and nobody mended them. People laugh with their whole faces. I was robbed twice, lost 20 marks and a shoe, and danced till dawn. I have never been so frightened or so happy. On the fourth day I went back to the lit streets and my colour was band five.'" },
    { depth: "sub", about: "sub:changing_archive", source: "person", bias: "true", reliable: true, who: "{investigator}, historian, in a paper diary", points: "site:wall_library", text: "Paper diary of {investigator}, ministry historian, {year}: 'Monday's record says the harvest failed in the year of the founding. Tuesday's says it was a record year. I have both printouts. I have hidden one. The caretaker of an old school told me a wall at {lead} sounds hollow, and that the ministry told the caretaker to stop knocking. I am going to knock.'" },
    { depth: "sub", about: "sub:tonic_shortage", source: "archive", bias: "official", reliable: "partial", who: "Ministry bulletin 88", text: "Ministry of Ease bulletin 88, {year}: 'The recent grief event of the thirty days was caused by contaminated foreign tonic. Normal supply of the calm tonic, the small blue bottle, has resumed. Citizens who wept in public during the event may reapply for their band. Citizens who are still weeping should not reapply yet.'" },
    { depth: "sub", about: "sub:creches", source: "oral", bias: "garbled", reliable: "partial", who: "a seamstress of {place}", text: "A seamstress of {place}, telling neighbours about a crèche visit day, {year}: 'The crèche children never cry. Two hundred of them, all band one, all in white. One asked my daughter what a mother was for, and listened very carefully to the answer, and then thanked her and wrote it down. My daughter has not slept well since.'" },
    { depth: "sub", about: "sub:the_blank", source: "person", bias: "true", reliable: "partial", who: "a blank, writing from hiding", points: "site:deep_floor", text: "Letter of a blank in hiding, to a sister, {year}: 'The pole looked at me and chimed nothing. Warden {believer} looked at the pole and then at me, and did not know what to do, perhaps for the first time in 15 years of service. I ran. The wardens want me taken. A man from the ministry wants me brought to {lead}, very gently. I do not know which is worse.'" },
    { depth: "sub", about: "sub:hounds", source: "person", bias: "true", reliable: "partial", who: "{survivor}, former schoolteacher", points: "cast:survivor", text: "Statement of {survivor}, former schoolteacher, refusing a hound's commission, {year}: 'The ministry offered me my colour back for 3 arrests. The best hounds, the warden said, are the ones who caught their friends. I said no. Anyone wanting the names of the 11 people who said yes, and whom they caught, can find me at {lead}. I kept a list. Teachers keep lists.'" },
    { depth: "site", about: "site:dead_reading", source: "archive", bias: "official", reliable: "partial", who: "the census return for {place}", text: "Census return for {place}, {year}, signed by {official}: 'Population: 104 per cent of registered births and arrivals. Discrepancy marked acceptable. The district's average colour has improved for the ninth year running.' A clerk's note pinned behind it: the pole on Ash Street still logs a woman who died six years ago. No action taken; her colour is excellent." },
  ],
};
