// The Grey Unmaking: the old world was not burned but eaten, by a devourer too small to see. It sleeps in the dust.
// Bridge premise: under a medieval world the devourer is "the Hunger", the grey wastes are cursed ground,
// and the machine that keeps it asleep is a holy bell-tower whose keepers no longer know what it sings.
export default {
  id: "grey_unmaking",
  name: "The Grey Unmaking",
  family: "scifi",
  pitch: "The world before ours was not burned or drowned but eaten, by a devouring dust too small to see that people call the Hunger. It is only asleep, in the grey wastes at the edges of every map.",
  slots: ["apocalypse", "history-secret", "monster-source"],
  tone: ["grim", "melancholy"],
  era: ["medieval", "renaissance", "post-collapse", "near-future"],
  scale: "world",
  genres: ["postapoc", "fantasy", "grimdark"],
  bridge: true,
  w: 1,
  excludes: ["long_mending"],
  pairs: [{ id: "sealed_refuges", w: 3 }, { id: "machine_liturgy", w: 2 }, { id: "unremembering", w: 2 }, { id: "elder_lattice", w: 1.5 }, { id: "blood_debt", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a healer of the grey-salve order who tests blood against the dust", home: "inner", stance: "Believes anything that can be measured can be stopped, and has started measuring the clean houses." },
    { role: "official", n: "a steward of a clean house who keeps the ledger of the bitter cup", home: "capital", stance: "Holds that the cup is charity, that charity has terms, and that villages which forget the terms must be reminded." },
    { role: "believer", n: "a keeper of the humming spire, sworn never to let the note fall", home: "mountain", stance: "Has kept the note for forty years on faith alone, and is frightened by the light that keeps blinking." },
    { role: "survivor", n: "an ash-digger who came back from the waste edge with grey fingertips", home: "border", stance: "Still digs because the metal pays, and wants someone to admit what the dust actually is." },
  ],

  truths: [
    { id: "dormant", n: "The Hunger is asleep, not dead", d: "The devourer that ate the old world never died. It went still when a signal told it to, and the humming spire on the mountain still sends that signal. The spire has run unrepaired for a thousand years and three of its twelve lights are failing; heat the dust, dig too deep or let the note lapse, and the grey wakes and eats again, as it ate a market town within living memory.", tags: ["truth:grey_dormant"],
      known: [
        "Ash-diggers report that grey dust near a fire starts to move against the wind. The libraries call the wastes dead ground, exhausted by ancient mining, and say the dust never moves.",
        "Border surveys show the wastes advancing by furlongs, and a market town crumbled in a single week within living memory. Wherever the spire's hum reaches, the grey stays still. Beyond it, the grey creeps.",
        "An inscription on the spire's inner stair reads 'Stop signal holds. Do not let it lapse. Do not heat the grey.' The hum is a command to the dust, and one of the lights below has blinked for a century.",
        "Confirmed: the Hunger is asleep, held by a signal from a failing machine that its keepers think is a hymn. Three of twelve lights are going out, and nobody alive knows how to mend them.",
      ] },
    { id: "released", n: "The end was a gift", d: "The unmaking was no accident and no judgment. One maker of the old world, tired of its wars, released the Hunger on purpose. First the maker bred a gentler people, who would never quarrel and never live past forty, and hid them in the valleys; the 'first folk' of every creation song are those replacements. The maker's name is carved on the oldest altars, and the realms pray to the one who ate the world.", tags: ["truth:grey_released"],
      known: [
        "The temples teach that the unmaking was heaven's judgment on a proud age. In a hidden valley lives a gentle people the grey has never touched, who die at forty and say a mother made them before the end.",
        "A white cellar in the waste, free of dust, holds glass cells labelled in old script. One label is a name, and the same name is carved on the oldest altars in the realm.",
        "A wall in the cellar sets out plans for a people who would not fight or want, and a date for 'release'. A copied scrap says the release was scheduled and no record was to survive.",
        "Confirmed: one maker ended the old world deliberately, after breeding the valley people to inherit it. The temples carve that maker's name above their altars, and the chronicler who said so was blinded for it.",
      ] },
    { id: "carried", n: "Everyone carries it", d: "Every living person carries a sleeping strain of the devourer in the blood, the clean houses included. Their bitter cup is the remedy that keeps the strain asleep, taken from sleepers in a barrow centuries ago, and they ration it to the obedient. A village that disputes its tithe can be left without the cup for a season, and the clean houses' own ledgers show they have done it.", tags: ["truth:grey_carried"],
      known: [
        "The clean houses claim their blood is proof against the grey, and walk barefoot in the dust each generation to prove it. Commoners must take the houses' bitter cup every season.",
        "A healer's test found that a lord's blood and a beggar's both go grey when dusted, and only the cup stops it. The clean houses may be no cleaner than anyone else.",
        "A clean house's accounts record a cup 'withheld' from a village after a tithe dispute, with the matter 'resolved'. The village is gone from the next tax roll, and its reeve died begging at the house gate.",
        "Confirmed: everyone carries the Hunger, and the cup is a remedy the clean houses took and kept for themselves. The cup is a collar, and the houses have pulled it tight before.",
      ] },
  ],

  tags: ["grey_devourer"],

  subthemes: [
    { id: "grey_wastes", n: "The Grey Wastes", d: "Plains of fine grey dust where nothing grows and no bird lands. Iron left there overnight is found pitted and half gone by morning.", w: 1.5, mods: [["desert", 2], ["badlands", 2], ["realm:large", 1.3]], tags: ["theme:grey_wastes"], mark: { kind: "zone", n: "The Grey", color: "#9a9a96", size: [2, 5], where: "remote" } },
    { id: "dust_town", n: "The Town That Turned to Dust", d: "Within living memory, a market town crumbled in a single week: walls, carts, people. The road to it is still blocked with thorn and salt.", w: 1, truthLink: "dormant", tags: ["theme:dust_town"], mark: { kind: "zone", n: "The Crumbled Town", color: "#7d7b74", size: [1, 1], where: "inner" } },
    { id: "stilling_bell", n: "The Bell That Must Not Stop", d: "A tower older than any kingdom hums day and night. Its keepers swear an oath that it will never fall silent, and none of them can say why.", w: 1.3, mods: [["pious", 1.5], ["organised", 1.5], ["ancestor_bound", 1.5]], truthLink: "dormant", tags: ["theme:stilling_bell"] },
    { id: "clean_blood", n: "The Clean Houses", d: "A nobility that claims its blood is proof against the grey-rot, and proves it every generation by walking barefoot in the dust. Commoners must take the houses' bitter cup each season.", w: 1.2, req: { any: ["hierarchical", "monarchy", "autocracy"] }, truthLink: "carried", tags: ["theme:clean_blood"] },
    { id: "grey_salve", n: "The Grey-Salve Healers", d: "A healers' order that mixes a pinch of tamed dust into its ointments. Wounds close overnight, bones knit in a week, and a few patients go quiet and grey at the fingertips.", w: 1, mods: [["scholarly", 2], ["learned", 1.5], ["urbane", 1.3]], truthLink: "carried", tags: ["theme:grey_salve"] },
    { id: "ash_wall", n: "The Ash Wall", d: "A great quarantine wall runs between the living lands and the grey. Who pays for it, who guards it, and who is left on the wrong side are the oldest quarrels in the realm.", w: 1.1, mods: [["autocracy", 1.5], ["frontier_forts", 2], ["standing_army", 1.5]], tags: ["theme:ash_wall"], mark: { kind: "zone", n: "The Ash March", color: "#6b5d52", size: [2, 3], where: "border" } },
    { id: "first_children", n: "The First Children", d: "In a hidden valley live a gentle, beautiful people who do not age past forty, never quarrel, and are untouched by the grey. The songs call them the world's first-born.", w: 0.7, req: { any: ["forest", "mountain", "jungle"] }, truthLink: "released", tags: ["theme:first_children"], mark: { kind: "zone", n: "The Gentle Valley", color: "#8fb88a", size: [1, 2], where: "remote" } },
    { id: "ash_diggers", n: "The Ash-Diggers", d: "Licensed scavengers in wet veils dig the grey's edge for old-world metal that never rusts. Every guild hall has a list of members who came back coughing grey.", w: 1.1, mods: [["mercantile", 1.5], ["poor", 1.5], ["near:ruins", 2]], tags: ["theme:ash_diggers"] },
    { id: "rot_cathedrals", n: "The Rot Cathedrals", d: "In a ruined city, mould has grown into vaults and spires taller than any temple. The figures standing inside them were people once, and sometimes they still walk.", w: 0.9, mods: [["marsh", 2], ["forest", 1.5], ["near:ruins", 2], ["jungle", 2]], tags: ["theme:rot_cathedrals"], mark: { kind: "zone", n: "Mould-city", color: "#5f6b4a", size: [1, 2], where: "forest" } },
    { id: "grey_penitents", n: "The Penitents of the Grey", d: "Ash-smeared preachers teach that the old world was eaten for its pride, and that every lamp, mill and printing press brings the Hunger nearer.", w: 1, req: { any: ["pious", "zealous", "ascetic", "gov:theocracy"] }, tags: ["theme:grey_penitents"] },
    { id: "unmaker_named", n: "The Scholar Who Named the Unmaker", d: "A chronicler claims to have traced the end of the old world to one name in one ruin, and the name is carved on the oldest altar in the realm.", w: 0.6, req: { any: ["scholarly", "learned", "academies"] }, truthLink: "released", tags: ["theme:unmaker_named"] },
  ],

  sites: [
    { id: "clean_room", n: "The White Cellar of $", kind: "ruin", where: "remote", truthLink: "released", d: "A buried hall of white stone where no dust lies at all, even after centuries.",
      layers: {
        surface: { n: "The white door", text: "A sunken white door lies in the grey, clean of the dust that covers everything for forty miles around. {survivor} found it by the glint and dug through six feet of grey to reach the lintel. Iron tools left beside it overnight were untouched in the morning." },
        study: { n: "The labels", text: "Inside are rows of empty glass cells, each labelled in a neat old script. {investigator} copied all 212 labels. One of them is a name, and it is the same name carved on the oldest altar of {faith} in {realm}." },
        dig: { n: "The chair and the wall", text: "A sealed inner room holds a single chair, a cup and a wall of writing: plans for a people who would never quarrel, bred to live forty years, and a date for 'release'. The plans name the valley where the people were to be hidden, at {lead}.", points: "sub:first_children" },
        revelation: { n: "The one who chose", text: "One person ended the old world on purpose. Tired of its wars, the maker in this room bred a gentler people, hid them in the valleys, then released the Hunger on everyone else, and sat in this chair to watch it work. The temples of {realm} still carve the maker's name above their altars." },
      } },
    { id: "grey_likeness", n: "The Grey Likeness of $", kind: "anomaly", where: "desert", d: "A whole city preserved in dust: every street, cart and sleeper shaped in fine grey powder that holds its form until touched.",
      layers: {
        surface: { n: "A city in fog", text: "From the ridge it looks like a city in fog. Up close it is a city made of grey powder, perfectly still: streets, carts, a well, people in doorways. Caravan guides charge a silver piece to show it and forbid anyone to cough." },
        study: { n: "Exact to the hair", text: "The shapes are exact to the hair. Bread on the tables kept its loaves and the marks of the knife. {investigator} counted three thousand figures in the market square alone, and noted that not one of them was running." },
        dig: { n: "Bare bedrock", text: "Beneath the dust is bare bedrock: no foundations, no bones, no iron, not a nail. The city was eaten down to the stone, and the dust kept its shape. The ash-diggers' guild keeps a tally of what was found here, at {lead}.", points: "sub:ash_diggers" },
        revelation: { n: "Eaten whole", text: "The old world was not smashed. The devourer ate it stone by stone and body by body, so fast that nobody ran, and left dust in the shape of everything it ate. The guides have shown the city for two hundred years, and the dust children are knocked down one by one by visitors' sleeves." },
      } },
    { id: "humming_spire", n: "The Humming Spire of $", kind: "wonder", where: "mountain", truthLink: "dormant", d: "A seamless tower that has hummed one low note for as long as anyone has kept records.",
      layers: {
        surface: { n: "The note", text: "A grey needle stands on a peak and rings one low note, felt in the teeth for a day's ride around. Its keepers swear never to let the note fall. {believer} has kept it for forty years and cannot say why it matters." },
        study: { n: "The reach of the hum", text: "{investigator} rode out along the hum with a cart of iron nails, leaving one each mile. Inside the hum's reach the nails stayed whole. Past it, the grey crept a few strides a season, and the nails were pitted within a week." },
        dig: { n: "The blinking light", text: "Inside, a stair runs down to a chamber of cold lights, twelve in a ring. One has flickered for a century; two are dark. The dark ones were first noted in a border report that was struck out by order, now held at {lead}.", points: "archive" },
        revelation: { n: "Stop signal", text: "The hum is a command, not a prayer. The old world's last engineers built the spire to tell the dust to sleep, and it has run a thousand years without repair. Three of its twelve lights are failing. The priests of {faith} taught the keepers that the note is a hymn, so none has ever learned how to mend it." },
      } },
    { id: "unopened_barrow", n: "The Unopened Barrow of $", kind: "dig", where: "any", truthLink: "carried", d: "A barrow mound with a door of grey metal, and behind it the sound of breathing.",
      layers: {
        surface: { n: "The green hill", text: "An old hill fort near {place} stands in pasture the shepherds will not graze. The grass on it is greener than any for ten miles and never browns in drought. Sheep that wander up come back fat, and are slaughtered at once." },
        study: { n: "The cup sign", text: "A door of grey metal is set into the barrow's side, marked with the same sign the clean houses stamp on the bitter cup. {official} has twice ordered the door bricked up. Both times the bricks were found stacked on the grass the next morning." },
        dig: { n: "Clean blood", text: "Inside are twenty sleepers in glass, alive and unaged. {investigator} drew blood from one through a seam in the glass. Dusted with a grain of grey, it stayed red. The healer's results were sent to the order's house at {lead}.", points: "sub:grey_salve" },
        revelation: { n: "The uncarried", text: "Everyone outside carries the Hunger in the blood, the clean houses too. The sleepers are the last people who never did. The clean houses found this barrow centuries ago, took the sleepers' remedy for themselves and named it the bitter cup. The sign on the door is the source of their crest." },
      } },
    { id: "mould_nave", n: "The Mould Nave of $", kind: "ruin", where: "forest", d: "A ruined city choked by a fungus that has grown into arches, buttresses and a spire.",
      layers: {
        surface: { n: "Pale vaults", text: "Spore-light hangs over a forest of pale vaults where a city once stood, some taller than any temple. Travellers on the old road hear singing from it on still nights. The road was moved two miles east in {year}." },
        study: { n: "The street plan", text: "The arches grow in the shape of the streets beneath them. {investigator} laid an old-world map over a sketch of the vaults; of forty crossroads, thirty-eight matched to within a stride. The mould is following a plan it found in the stone." },
        dig: { n: "The kneeling ring", text: "At the heart is a ring of kneeling figures fused to the central stalk, still warm. One wears a healer's ring of the grey-salve order, with a date inside it from within fifty years. The order's roll of missing healers is kept at {lead}.", points: "library" },
        revelation: { n: "Where it got into people", text: "The grey eats stone and iron. Where it got into living people, it grew this mould instead, and the mould is still growing. The healer in the ring was sent here to gather tamed dust for salve, as the order's masters have sent dozens. The order still sells the salve, and still sends collectors." },
      } },
  ],

  beings: [
    { id: "grey_drift", n: "Grey drift", kind: "insect", d: "A living haze of dust that wakes in heat or under a spade, flows uphill against the wind, and leaves iron pitted and flesh grey.", danger: 3, biomes: ["desert", "badlands", "colddesert", "grass", "coldsteppe"], look: { size: 0.001, group: [10000, 100000], move: "swarm", speed: 1, col: "#a3a29c", col2: "#d6d4cc", body: "insect", active: "day", visible: true } },
    { id: "rot_walker", n: "Rot-walker", kind: "beast", d: "A body taken by the mould-grey, crusted in pale growth, that wanders towards warmth and voices and sheds spores when struck.", danger: 2, biomes: ["swamp", "tempforest", "rainforest", "temprain", "mangrove"], look: { size: 1.7, group: [1, 6], move: "solo", speed: 2, col: "#8a8f78", col2: "#d8d8c0", body: "biped", active: "night", visible: true } },
    { id: "dust_hound", n: "Dust-hound", kind: "predator", d: "A lean grey dog of the waste margins, hairless and silent, said to be the only beast the grey does not eat. It follows ash-diggers home.", danger: 2, biomes: ["badlands", "desert", "coldsteppe", "grass"], look: { size: 1.1, group: [3, 9], move: "pack", speed: 13, col: "#8c8a84", col2: "#5a5650", body: "quad", active: "dusk", visible: true } },
    { id: "first_child", n: "The first children", kind: "beast", d: "A gentle, golden-eyed folk of the hidden valleys who eat only leaves, sing in rounds, and cannot be taught to lie or to fight.", danger: 0, biomes: ["tempforest", "rainforest", "alpine"], look: { size: 1.7, group: [4, 20], move: "herd", speed: 4, col: "#c9a87a", col2: "#e6d7a8", body: "biped", active: "day", visible: true } },
  ],

  techs: [
    { id: "gu_wet_veils", n: "Wet veils", field: "medicine", level: 1, d: "Vinegar-soaked veils and sealed collars that keep the grey out of the throat at the waste's edge." },
    { id: "gu_ash_walls", n: "Salt-and-lime walls", field: "architecture", level: 2, d: "Quarantine walls of lime, salt and cold stone, which the grey creeps over slowest." },
    { id: "gu_grey_salve", n: "Grey-salve", field: "medicine", level: 3, d: "A pinch of tamed dust that closes wounds and knits bone. Its makers count their patients' fingertips." },
    { id: "gu_hum_lore", n: "The stilling note", field: "natural_philosophy", level: 4, d: "Scholars learn to copy the hum of the old towers on bells and pipes, and find the dust lies still around them." },
    { id: "gu_tamed_grey", n: "Tamed grey", field: "alchemy", level: 4, d: "Dust coaxed to eat only rust, or only rot, or only stone in a line: a mason's dream and a terrible weapon." },
    { id: "gu_last_word", n: "The last word", field: "arcana", level: 5, d: "The full command the towers sing. Whoever holds it can put the hunger to sleep for good, or wake all of it at once." },
  ],

  units: [
    { id: "gu_ash_wardens", n: "Ash wardens", role: "infantry", wpn: "spear", kit: "robe", ranks: 4, gap: 1.4, size: 100, w: 0.8, mods: [["theme:ash_wall", 6], ["theme:grey_wastes", 2]] },
    { id: "gu_burners", n: "Burning companies", role: "siege", wpn: "siege", kit: "light", ranks: 1, gap: 8, size: 20, w: 0.3, mods: [["theme:dust_town", 6], ["theme:rot_cathedrals", 5]] },
  ],

  faiths: [
    { id: "gu_stilling", n: "The Stilling", d: "The world is asleep on a sleeping hunger. The holy duty is to keep everything quiet: the bells ringing, the dust undisturbed, ambition small.", tags: ["faith:gu_stilling"], w: 0.6, mods: [["theme:stilling_bell", 8], ["theme:grey_penitents", 4]],
      names: ["The Stilling of $", "The Keepers of the Note", "The Quiet Bell"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Grey waste", color: "#a6a5a0", size: [2, 5], count: [1, 3], where: "desert", d: "Dust plains where the old world was eaten; nothing grows, and iron does not last a night." },
  ],

  storylines: [
    { id: "gu_dust_town", n: "The Dust of {place}", scale: "local", anchor: "town", w: 1.5, req: "grey_devourer",
      stages: {
        start: { h: "Well-diggers of {place} strike grey ground", b: "Thirty feet down, the diggers at {place} broke into a bed of fine grey dust. By morning the well's iron chain was eaten through.", wait: [1, 3], next: [{ to: "spreading", w: 2 }, { to: "sealed", w: 1.5, mods: [["theme:ash_wall", 3], ["learned", 1.5], ["theme:stilling_bell", 2]] }] },
        sealed: { h: "{place} buries its well in salt and lime", b: "On the advice of {person}, an old ash-digger, the well was filled with salt and capped with stone. The town holds its breath.", wait: [3, 8], next: [{ to: "quiet", w: 2 }, { to: "spreading", w: 1, mods: [["hot", 2], ["chance:low", 2]] }] },
        spreading: { h: "Grey dust drifts through {place}", b: "Doors crumble at the hinges, cattle go grey at the hoof, and the dust moves against the wind. Folk are leaving {place} with what they can carry.", wait: [1, 4], fx: { unrest: 15, pop: 0.95, flag: "grey_waking" }, next: [{ to: "burned", w: 2, mods: [["autocracy", 2], ["harsh_law", 2]] }, { to: "salve", w: 1, mods: [["theme:grey_salve", 4], ["learned", 2]] }, { to: "eaten", w: 1 }] },
        quiet: { h: "The grey at {place} stays still", b: "A year on, the capped well is cold and the dust has not moved. {person} visits it each month with a bell, and nobody laughs.", fx: { stability: 3 }, end: true },
        burned: { h: "{realm} burns {place} to stop the grey", b: "Soldiers came with fire and lime and did not ask who was still inside. The grey went still under the ash. So did {place}.", fx: { abandon_town: true, stability: -6, unrest: 10 }, end: true },
        salve: { h: "Healers of {realm} still the grey at {place}", b: "{person2} and the grey-salve healers met the drift with bells and their own tamed dust, and it lay down. They will not say what it cost them.", fx: { discovery: "medicine", prestige: 6 }, end: true },
        eaten: { h: "{place} is gone", b: "Where {place} stood there is a grey shape of a town, perfect to the last shutter, that falls apart at a touch.", fx: { abandon_town: true, pop: 0.9, stability: -10 }, end: true },
      } },
    { id: "gu_silent_spire", n: "The Silent Spire of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["grey_devourer", { any: ["theme:stilling_bell", "pious", "near:ruins"] }],
      stages: {
        start: { h: "The great hum of {realm} falters", b: "For three nights the old spire's note has wavered. Its keeper, {person}, is dying, and swears the note must not stop.", wait: [2, 5], next: [{ to: "heir_found", w: 1.5, mods: [["learned", 1.5], ["pious", 1.3]] }, { to: "waking", w: 1 }, { to: "scholars", w: 1, mods: [["scholarly", 2], ["academies", 2]] }] },
        heir_found: { h: "A child of {capital} learns the keeper's song", b: "{person2}, a bell-ringer's apprentice, climbed the spire and came down knowing what to sing. The note is steady again.", fx: { stability: 5, prestige: 4 }, end: true },
        waking: { h: "The grey moves on the borders of {realm}", b: "The note is gone. The wastes have crept a mile in a month, and villages along the edge are emptying.", wait: [3, 8], fx: { unrest: 15, growth: -0.002, flag: "spire_silent" }, next: [{ to: "rot_years", w: 2 }, { to: "scholars", w: 1, mods: [["learned", 2]] }] },
        scholars: { h: "Scholars of {realm} climb the silent spire", b: "{person2} and a band of scholars have gone down the spire's inner stair to learn what the hum was and how to make it again.", wait: [4, 10], fx: { science: { natural_philosophy: 0.6 } }, next: [{ to: "word_found", w: 1, mods: [["learned", 2]] }, { to: "rot_years", w: 1 }] },
        rot_years: { h: "The Grey Years come to {realm}", b: "Fields turn to dust, iron rots in the barns, and the penitents say the old world's hunger has woken for {realm}'s pride.", fx: { plague: true, pop: 0.85, stability: -15 }, end: true },
        word_found: { h: "{realm} learns the word the spire sang", b: "Under the spire, {person2} found the note written out in an old hand, and more: a longer song the spire was never told to sing.", fx: { discovery: "natural_philosophy", prestige: 10, flag: "last_word" }, end: true },
      } },
    { id: "gu_bitter_cup", n: "The Bitter Cup of {realm}", scale: "realm", anchor: "realm", w: 1, req: ["grey_devourer", { any: ["theme:clean_blood", "hierarchical", "monarchy"] }],
      stages: {
        start: { h: "The clean houses of {realm} raise the price of the cup", b: "The seasonal draught that keeps the grey-rot away now costs a month's wage. Those who cannot pay are told their blood will hold.", wait: [3, 6], next: [{ to: "rot_poor", w: 2 }, { to: "secret_out", w: 1, mods: [["learned", 1.5], ["unstable", 1.5]] }] },
        rot_poor: { h: "Grey-rot in the poor quarters of {capital}", b: "Fingertips greying, then hands. Only those who missed the cup are sick, and the clean houses call it proof of their mercy.", wait: [2, 6], fx: { pop: 0.95, unrest: 15 }, next: [{ to: "secret_out", w: 1.5 }, { to: "cowed", w: 1, mods: [["harsh_law", 2], ["autocracy", 1.5]] }] },
        secret_out: { h: "A healer reveals the clean houses' secret", b: "{person}, a grey-salve healer, has shown the crowds that the clean are no cleaner than anyone: the cup keeps the hunger asleep, and they have always known it.", wait: [1, 4], fx: { stability: -10, flag: "cup_known" }, next: [{ to: "uprising", w: 2, mods: [["poor", 1.5]] }, { to: "cup_shared", w: 1, mods: [["ruler:just", 3], ["egalitarian", 2]] }] },
        cowed: { h: "{realm} pays for the cup in silence", b: "The rot passed. The price did not fall. Every family in {realm} now owes the clean houses a debt it will never finish paying.", fx: { treasury: 40, stability: 2, unrest: 5 }, end: true },
        uprising: { h: "The cup-houses of {capital} are stormed", b: "Mobs broke the clean houses' stillrooms and carried off the cup's makings. Nobody knows the true recipe, and the grey is patient.", fx: { revolt: true, stability: -15 }, end: true },
        cup_shared: { h: "{ruler} opens the stillrooms of {realm}", b: "By decree, the cup is free, its recipe read aloud in every market. The clean houses have lost their hold, and found out how many enemies they had.", fx: { stability: 8, prestige: 6, science: { medicine: 0.6 } }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "a ferryman of {place}, to a passenger", text: "A ferryman of {place}, telling a passenger the old story while they waited out a dust storm, {year}: 'Before the kings, the world was full of iron and light. Then the Hunger came, too small to see, and ate it all, cities and people both, in a single summer. Then it lay down to sleep in the grey. That's why we don't land on the grey bank, and why I charge double in a storm.'" },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "a primer of {realm}", points: "library", text: "From a children's primer of {realm}, lesson 3, {year} edition: 'The Grey is cursed ground: plains of fine dust where nothing grows. The Hunger is the old name for what made it. Do not dig there, do not camp there, and do not carry home anything that does not rust.' The primer's lesson 4, on why, was removed after the second edition; a first edition survives at {lead}." },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a wool merchant, writing home", points: "site:grey_likeness", text: "Letter of a wool merchant, writing home after a shortcut, {year}: 'I crossed one corner of the waste, nine miles, with a wet veil and an iron knife. I came out with a veil and a handle. The guide said I had been lucky and asked for double. On the ridge at {lead} he showed me a whole city made of dust, and would not let me go down.'" },
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: false, who: "a penitent preacher of {faith}", text: "Sermon of a penitent preacher of {faith}, at the market cross of {place}, {year}: 'The old world was eaten because it reached too high: towers of a hundred floors, lamps that never went out. The Hunger is the hand of {deity}, and it sleeps only while we keep small. Every new mill in this town is a finger poked in its eye.' The miller has asked the council to move the preacher on." },

    { depth: "core", about: "truth:dormant", source: "ruin", bias: "true", reliable: true, plain: true, who: "{believer}, keeper of the spire", text: "Report of {believer}, keeper of the humming spire, to the council of keepers, {year}: 'Cut into the inner stair, in an old hand, I found these words: STOP SIGNAL HOLDS. DO NOT LET IT LAPSE. DO NOT HEAT THE GREY. Brothers, we have sung the wrong thing for a thousand years. The note is not a hymn. It is an order to the dust to sleep. The dust is the Hunger, it is alive, and this spire is the only thing holding it down.'" },
    { depth: "core", about: "truth:dormant", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, ash-digger", text: "Account of {survivor}, ash-digger, to the guild's healer, {year}: 'Lit a fire to warm my hands at the waste edge, the first night of frost. The dust around it started to move. Not blown. Crawling, toward the heat. I put my hand down to push off and it went up my fingers like water up a rag. You cut off two of them yourself. Write that down in your book, and write the fire.'" },
    { depth: "core", about: "truth:dormant", source: "temple", bias: "pious", reliable: "partial", who: "the keepers' oath", points: "cast:believer", text: "The oath of the spire-keepers, sworn on the top step at midnight, {year} copy: 'While the note sounds, the sleeper sleeps. I will not let the note fall, though I do not know whose sleep I guard.' 31 keepers have sworn it since the order's records begin. The present keeper, at {lead}, is the first to ask what the oath means." },
    { depth: "core", about: "truth:dormant", source: "archive", bias: "redacted", reliable: "partial", who: "a border report", points: "site:humming_spire", text: "Border report of the Ash March, {year}: 'Wastes advanced eleven furlongs since last survey. The keeper of the spire at {lead} reports the low note weakening and two lights below gone dark. Request masons, and someone who can read the old hand. [Remainder struck out by order.]' The masons were sent. The reader was not." },
    { depth: "core", about: "truth:dormant", source: "library", bias: "official", reliable: false, who: "the royal Survey of Lands", text: "The royal Survey of Lands, volume 2, {year}: 'The grey wastes are dead ground, exhausted by the ancients' mining. They do not grow, they do not move, and the stories of creeping dust are travellers' fancies. The town of [name] was lost to a landslip. The surveyors walked the edge of the waste for 30 miles and saw nothing move.'" },

    { depth: "core", about: "truth:released", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, healer, copying a wall", text: "Copied by {investigator} from the wall of the white cellar, {year}: 'They will not fight. They will not want. They will inherit a world with nothing left to fight over. Forgive me, or do not; you will not be there to.' The healer's own note beneath: 'This is a confession. The person who wrote it released the Hunger on purpose, after making the valley people to replace us. The date is in the corner.'" },
    { depth: "core", about: "truth:released", source: "oral", bias: "garbled", reliable: "partial", who: "a valley woman, to a traveller", points: "sub:first_children", text: "A woman of the gentle valley, aged 38, to a traveller who asked about her people's song, {year}: 'We sing that a mother made us before the world ended, and sent the end so we would have room. We do not mind. We have room. You may visit the valley at {lead} if you are kind, but do not stay past spring; by then I will be gone.'" },
    { depth: "core", about: "truth:released", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "a forbidden chronicle by {person}", text: "From a forbidden chronicle by {person}, chronicler of {realm}, chapter 12, {year}: 'The name on our oldest altar is the name in the white cellar. I have matched all nine letters. We have been praying to the one who ate the world.' The chronicler was blinded by order of the temple court that spring. {person} dictated the last 4 chapters to a niece." },
    { depth: "core", about: "truth:released", source: "archive", bias: "redacted", reliable: "partial", who: "a scrap of old-world writing", points: "site:clean_room", text: "A scrap of old-world writing on plastic sheet, much copied, original held by a scholars' archive, {year} copy number 14: '...release is scheduled. The children are hidden in the valleys. No record of this decision is to survive...' The original was dug out of the waste beside a white door, at {lead}, by an ash-digger who sold it for a meal." },
    { depth: "core", about: "truth:released", source: "temple", bias: "official", reliable: false, who: "the synod of {faith}", text: "Ruling of the synod of {faith}, {year}, read in every temple of {realm}: 'The unmaking was a judgment on a wicked age, sent by heaven and by no hand of man. To say otherwise is to blaspheme against {deity}. The name above our altars is a holy name of 9 letters and is not to be compared with any other.' The ruling does not say who was comparing it." },

    { depth: "core", about: "truth:carried", source: "person", bias: "true", reliable: true, plain: true, who: "{investigator}, healer", text: "Notebook of {investigator}, healer, {year}: 'Drew blood from a lord of the clean house, during a bleeding for gout, and from a beggar. Dusted both with a grain of grey. Both went grey at the edges within the hour. The lord's stopped only when I added the bitter cup. There is no clean blood. Everyone carries it. The cup keeps it asleep, and the houses hold the cup.'" },
    { depth: "core", about: "truth:carried", source: "oral", bias: "garbled", reliable: "partial", who: "{survivor}, ash-digger, to a guild apprentice", points: "site:unopened_barrow", text: "{survivor}, ash-digger, to a new guild apprentice, {year}: 'My grandmother said everyone is born with a little grey in the heart, and you must drink your bitter cup every season or it grows. I never believed it till my fingers. There's a green hill at {lead} with the cup's sign on a door. Grandmother said the cup came out of that hill. The houses say it came from heaven.'" },
    { depth: "core", about: "truth:carried", source: "heretic", bias: "exaggerated", reliable: "partial", who: "chalked on a stillroom wall", points: "cast:official", text: "Chalked on the stillroom wall of a clean house in {place}, {year}, and copied by the steward before it was scrubbed off: 'THE CUP IS A COLLAR. MISS ONE SEASON AND SEE WHO STILL CALLS YOU KIN.' Under it, smaller: 'Ask the cup-steward at {lead} about the 40 days.' The steward's report blames a scullery maid, who was dismissed without a cup." },
    { depth: "core", about: "truth:carried", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "the household accounts of a clean house, kept by {official}", text: "Household accounts of a clean house, kept by {official}, {year}, entry 211: 'Cup withheld from the village of [name scraped away] following the tithe dispute. Day 40: reeve {person} came to the gate to beg, grey to the elbow. Not admitted. Day 52: matter resolved.' The village does not appear in the next tax roll. The reeve's name is on no grave." },
    { depth: "core", about: "truth:carried", source: "library", bias: "propaganda", reliable: false, who: "a genealogy of the clean houses", text: "From the Genealogy of the Clean Houses, preface, {year}, printed at the houses' expense in 600 copies: 'The clean houses descend from the few whose blood the Hunger could not touch. Their lords walk barefoot in the grey each generation to prove it. The cup they share each season is a gift of their charity, not a need of yours.'" },

    { depth: "sub", about: "sub:grey_wastes", source: "traveller", bias: "true", reliable: true, who: "a mapmaker crossing the Grey", text: "Field book of a mapmaker crossing the edge of the Grey, day 3, {year}: 'No tracks last a day here. I left an iron stake as a marker at dusk and found it pitted and half gone at dawn. But at mile 12 I saw a fox's skeleton, perfect, made of dust, and the wind did not touch it. I have drawn it. I did not measure it. I did not want to touch it.'" },
    { depth: "sub", about: "sub:dust_town", source: "oral", bias: "exaggerated", reliable: "partial", who: "an innkeeper on the salt road", points: "archive", text: "An innkeeper on the salt road, to a crown surveyor, {year}: 'My uncle's town fell to dust in one week, walls, carts, people. He was carting barley out on the sixth day. He said the church bell crumbled mid-ring and the sound kept going without it. The road there is blocked with thorn and salt. The crown's report of that week is at {lead}, if they let you read it.'" },
    { depth: "sub", about: "sub:ash_wall", source: "archive", bias: "official", reliable: "partial", who: "the levy roll for the Ash March", text: "Levy roll for the Ash March, {year}: 'Each village of {realm} to send two men and a cartload of lime yearly to the quarantine wall. Villages beyond the wall are exempt from the levy, being no longer counted.' A clerk has added in the margin that 14 villages moved beyond the wall last year to avoid the levy, and asks whether this was intended." },
    { depth: "sub", about: "sub:ash_diggers", source: "person", bias: "true", reliable: true, who: "the ash-diggers' guild rule book", points: "cast:survivor", text: "The ash-diggers' guild rule book, rule 9, as read aloud to {survivor} on joining, {year}: 'The digger who coughs grey does not come back into the hall. We leave the digger's share at the gate with a bell, and ring it once.' The book lists 63 shares left at the gate since the guild began. One digger who came back with grey fingers and no cough can be found at {lead}." },
    { depth: "sub", about: "sub:first_children", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a lost hunter of {place}", text: "A hunter of {place}, lost in the hills for a week in {year}, telling the tale at home: 'They fed me, set my broken leg and sang me to sleep. Nobody there argued, not once in 6 days. In the morning I asked their eldest how old she was. Thirty-nine, she said, and smiled, and said she would be gone by spring. I left them my knife. They did not know what it was for.'" },
    { depth: "sub", about: "sub:grey_penitents", source: "temple", bias: "pious", reliable: "partial", who: "a penitent's street sermon", text: "A penitent's street sermon, taken down by a magistrate's clerk in {place}, {year}, before the arrest: 'Smash the mill, unstring the loom, put out the forge. Every wheel you turn brings the Hunger closer to waking.' The clerk notes that the crowd of about 50 broke one loom, then went to the tavern, which has a fire, and nobody objected." },
    { depth: "sub", about: "sub:rot_cathedrals", source: "oral", bias: "garbled", reliable: "partial", who: "a charcoal-burner at the forest edge", points: "site:mould_nave", text: "A charcoal-burner at the forest edge, warning a pair of young healers in {year}: 'Do not go into the mould-city at night. The pale ones stand in the arches like a choir, forty at least, and if you sing, they turn their heads. Your order sent three of you last year to {lead}. One came back, and that one does not sing any more.'" },
    { depth: "site", about: "site:grey_likeness", source: "traveller", bias: "true", reliable: true, who: "a pilgrim who walked into the dust city", text: "A pilgrim who slipped the guide and walked into the dust city, writing to a sister, {year}: 'I touched a dust-child sitting on a dust-step, about 5 years old, with a cup in its hand. It fell into a little heap, cup and all. I wept the whole way home, and I do not know why. The guide made me pay a silver piece as a fine. I paid two.'" },
    { depth: "site", about: "site:humming_spire", source: "person", bias: "true", reliable: "partial", who: "{believer}, keeper of the spire", text: "Night book of the humming spire, in the hand of {believer}, keeper, {year}: 'Second bell. The cord on the great pipe snapped. The note fell silent for as long as it takes to say the creed twice, while I spliced it. No harm seen.' Entry for the following week, in the same hand: 'Border riders report the grey moved 300 strides on the night of the second bell, against the wind. I sleep beside the pipe now, with a spare cord in my hand.'" },
  ],
};
