// The Kindled Lineages: a non-human kind was raised to mind by a long-dead maker's experiment; their god is a
// moving star that speaks in numbers, and the makers' children are coming home. A bridge: under a medieval
// world the kindled are the beast-folk of legend, the star is a wandering god, and the ark is a prophecy.
export default {
  id: "kindled_lineages",
  name: "The Kindled Lineages",
  family: "scifi",
  pitch: "The thinking beast-folk who share the world with humans were made intelligent by an ancient experiment that went wrong. Their god is a moving star that teaches in numbers, and the experimenters' descendants are coming back to claim what they think they own.",
  slots: ["ecology", "bloodline", "history-secret"],
  tone: ["wonder", "melancholy"],
  era: ["stone", "bronze", "medieval", "post-collapse", "far-future"],
  scale: "world",
  genres: ["fantasy", "mythic", "postapoc", "farfuture"],
  bridge: true,
  w: 1,
  excludes: [],
  pairs: [{ id: "forgotten_landing", w: 3 }, { id: "gardener_engine", w: 2 }, { id: "walking_mountains", w: 1.5 }, { id: "elder_lattice", w: 1.5 }, { id: "fleshwright_covenant", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a human physician who treats the plague that spares humans in the silk cities", home: "forest", stance: "Does not believe in gods but believes in timing, and wants to know why the sickness began when the star's hymns changed." },
    { role: "official", n: "a royal astrologer charting the new star for the crown", home: "capital", stance: "Has done the sum on the new star and is paid to say it is an omen, not a ship." },
    { role: "believer", n: "a priest-mother of the star-watch who copies down the moving star's lessons", home: "mountain", stance: "Has copied the star's hymns for a lifetime as proof of its love, and does not know what to do with its new orders." },
    { role: "survivor", n: "a weaver-kin elder who lost a whole brood to the plague that spares humans", home: "forest", stance: "Wants to know who the kindled are in debt to, and who sent the sickness to collect." },
  ],

  truths: [
    { id: "gift_missed", n: "The gift missed its mark", d: "The makers' experiment was meant to raise a long-armed ape to mind, and a broken case spilled the gift into the weaver-kin's nests instead. The star the beast-folk worship is a machine in orbit carrying the maker's damaged mind; it waited a thousand years for the apes to answer, and has started trying to correct the mistake. The plague that spares humans began the year its hymns changed.", tags: ["truth:gift_missed"],
      known: [
        "The beast-folk's moving star has taught sums and shapes for a thousand years. Lately it has begun to issue orders, and a sickness that never touches humans is spreading among the kindled.",
        "The glass cradles in the maker's fallen house, where the kindled say their first mother was born, are all painted with a long-armed ape. None of them shows the kindled's shape.",
        "The star-watch scrolls show the star repeating the makers' word for that ape every night for a century, and asking for 'the long-armed ones'. The kindled may not be the creatures it raised on purpose.",
        "Confirmed: the gift was meant for another animal and fell on the kindled by accident. The star carries the maker's mind, and its new hymns and the plague arrived in the same year.",
      ] },
    { id: "makers_return", n: "The makers' children are coming", d: "The humans here are not the makers: they descend from the few crew who walked away from a scout ship that crashed in the desert, and then forgot. The makers' true descendants sleep aboard a huge, failing ark, which is the new star, and its maps mark the kindled lands 'to be reclaimed'. When it arrives they will claim the world, the kindled and the castaways' children as property.", tags: ["truth:makers_return"],
      known: [
        "A second bright star has appeared and grows brighter every month, and the old star has begun to speak to it. Crown astrologers call it an omen. The beast-folk call it a homecoming they fear.",
        "A metal ridge in the desert, the Coffin of the Sky-Lords, holds glass coffins with tall, pale sleepers who look like humans. The libraries call it star-iron and the sleepers mummies.",
        "A map-room in the ridge marks the kindled lands 'to be reclaimed' and plots a course to a point in the sky that matches the new star. The ridge was a scout ship. The new star may be what sent it.",
        "Confirmed: the makers' ark is coming, and the humans of this world are only the scout's forgotten crew. The ark's orders are to reclaim the native fauna on arrival, and the kindled are the fauna.",
      ] },
    { id: "client_debt", n: "The kindled owe their makers", d: "The makers built obedience into the kindled's blood: they must serve whoever carries the makers' mark. Their whole culture of debts, tithes and oaths grew out of that hidden order, which every young kindled remembers at the pool as a voice in a bright room. Any human who inherits a maker's ring can command a silk city, and some already have.", tags: ["truth:client_debt"],
      known: [
        "The beast-folk live by debts, tithes and inherited oaths, and their councils say the customs were freely chosen. Human traders come to the silk cities as guests and leave as debtors.",
        "Young kindled who drink at the remembering pool describe a bright room and a voice saying 'serve the mark'. A bronze plate under the pool bears the same mark as some old rings.",
        "A merchant who wore an old ring into a silk city saw every weaver in the market bow and stay down until told to rise. The mark commands the kindled, and the kindled cannot refuse it.",
        "Confirmed: obedience to the makers' mark was written into the kindled's blood, and the oath-culture grew around it. The rings sit in human jewellery boxes as keepsakes, and a few owners know what they do.",
      ] },
  ],

  tags: ["kindled"],

  subthemes: [
    { id: "web_city", n: "The Silk Cities", d: "The weaver-kin have raised cities of silk between the great trees, wider than any human town and lit by glow-moths. Human traders come as guests and leave as debtors.", w: 1.3, req: { any: ["forest", "jungle", "forest_folk"] }, tags: ["theme:silk_cities"], mark: { kind: "zone", n: "The Silk Canopy", color: "#c8c8b0", size: [2, 4], where: "forest" } },
    { id: "star_orders", n: "The Star Gives Orders", d: "For a thousand years the moving star taught sums and shapes. Now it has begun to issue commands, and the beast-folk's priest-mothers disagree about whether to obey.", w: 1.2, req: { any: ["pious", "faith:stars", "seers", "mystic"] }, truthLink: "gift_missed", tags: ["theme:star_orders"] },
    { id: "living_reckoners", n: "The Thinking Hives", d: "The kindled have bred ant-colonies that solve problems when fed the right scents. A queen-hive can plan a harvest, and some say a war.", w: 1, req: { any: ["scholarly", "artisans", "learned"] }, tags: ["theme:thinking_hives"] },
    { id: "blood_memory", n: "The Grandmothers' Voices", d: "The kindled inherit their ancestors' memories in the blood. In one lineage the dead are waking too strongly, and the young speak with their great-grandmothers' minds.", w: 1, truthLink: "client_debt", tags: ["theme:blood_memory"] },
    { id: "unkindled_cousins", n: "The Dumb Cousins", d: "Ordinary beasts of the same kind as the beast-folk still live in the wild. Hunting them is a sin to the kindled and supper to humans, and the border villages are where those two views meet.", w: 1.1, req: { any: ["frontier", "forest", "hills", "near:beasts"] }, tags: ["theme:unkindled"] },
    { id: "kindled_plague", n: "The Plague That Spares Humans", d: "A sickness is spreading among the beast-folk that never touches a human. The weaver-mothers have begun to study heredity to fight it, and to ask who sent it.", w: 0.8, req: { any: ["plague", "marsh", "jungle", "hot"] }, truthLink: "gift_missed", tags: ["theme:kindled_plague"] },
    { id: "ark_omen", n: "The New Star", d: "A second bright star has appeared, brighter every month, and the old star has begun to speak to it. Human astrologers call it an omen; the beast-folk call it a homecoming they fear.", w: 1, req: { any: ["scholarly", "faith:stars", "seers", "academies"] }, truthLink: "makers_return", tags: ["theme:new_star"] },
    { id: "forgotten_colony", n: "The Hill-Folk Who Forgot", d: "In the high valleys lives a human people who have lost writing, iron and the wheel, and who call the beast-folk 'masters'. Neither side remembers why.", w: 0.8, req: { any: ["mountain", "hills", "isolation", "tribal"] }, truthLink: "makers_return", tags: ["theme:forgotten_folk"] },
    { id: "oath_market", n: "The Oath-Market", d: "Among the beast-folk, every service is owed and every debt is inherited. A human merchant who carries the old maker's mark on a ring finds the whole silk city bowing to him.", w: 0.9, req: { any: ["mercantile", "has:port", "hierarchical"] }, truthLink: "client_debt", tags: ["theme:oath_market"] },
    { id: "rival_kindled", n: "The War of Wings and Webs", d: "Two kindled kinds, raised by the same gift in different places, are at war over the old forests. Human realms are being drawn in on both sides.", w: 0.8, req: { any: ["martial", "atwar", "forest", "has:rival"] }, tags: ["theme:kindred_war"] },
    { id: "own_satellite", n: "The Kindled Tower", d: "The weaver-kin are building a tower of silk and resin taller than any mountain, to reach the star and speak to it face to face.", w: 0.5, req: { any: ["learned", "scholarly", "artisans", "realm:large"] }, tags: ["theme:silk_tower"] },
  ],

  sites: [
    { id: "maker_lab", n: "The Maker's Fallen House at $", kind: "ruin", where: "remote", truthLink: "gift_missed", d: "A shattered hall of glass and white stone where the beast-folk say their first mother was born.",
      layers: {
        surface: { n: "The white ring", text: "A ring of white stone stands under the great trees, sacred to the beast-folk. Weaver-kin guards let no human in alone; {investigator} was admitted with two escorts and a debt of three favours. The kindled call it the house where the first mother was born." },
        study: { n: "The painted cradles", text: "Inside are rows of glass cradles, ninety-six of them, each painted with an animal. Every one shows a long-armed ape. None shows the kindled's shape. The guards say the paintings are of the first mother's enemies." },
        dig: { n: "The last vial", text: "A sealed case holds tiny vials, all spent but one, and a carved tablet showing the ape again, labelled in the makers' script with a word scholars read as 'chosen'. The priest-mothers copy the same word nightly at {lead}.", points: "site:moving_star" },
        revelation: { n: "The wrong animal", text: "The beast-folk were never meant to rise. The makers aimed their gift at a long-armed ape, and a broken case spilled it into the weaver-kin's nests instead. The maker who ran this house went up to the star to wait for the apes. The last vial is still full, and the star knows exactly where it is." },
      } },
    { id: "moving_star", n: "The Star-Watch of $", kind: "shrine", where: "mountain", d: "A mountain shrine where the beast-folk keep a vigil for their moving god and copy down its teachings.",
      layers: {
        surface: { n: "The vigil", text: "A silk-hung shrine sits on a peak, where priest-mothers sit through the night watching one star cross the sky. Forty mothers take the watch in turn. In a thousand years, {believer} says, not one night has been missed." },
        study: { n: "Hymns that are sums", text: "The star crosses at exactly the same hour each night and blinks in patterns the priests copy as hymns. {investigator} read the oldest hymn book and found that the hymns are sums: counting, then doubling, then the areas of circles." },
        dig: { n: "The name", text: "In the oldest scrolls, after the counting and the shapes, the star repeats one long word every night for a century. It is the makers' name for the long-armed ape. A cradle with the same word painted on it stands at {lead}.", points: "site:maker_lab" },
        revelation: { n: "Still waiting", text: "The god is a machine circling the world with the maker's damaged mind inside. It taught for a thousand years, waiting for the apes it chose to answer, and the kindled answered instead. Last year it changed its hymns from lessons to orders. The priest-mothers are still copying them down, word for word." },
      } },
    { id: "ark_wreck", n: "The Fallen Sky-Hull at $", kind: "dig", where: "desert", truthLink: "makers_return", d: "A vast hull of strange metal half-buried in the sands, called the Coffin of the Sky-Lords.",
      layers: {
        surface: { n: "The cold ridge", text: "A ridge of dull metal longer than any town rises from the dunes, cold even at noon. Desert guides call it the Coffin of the Sky-Lords and charge double to camp beside it. Their camels will not drink within a mile of it." },
        study: { n: "Sleepers in glass", text: "Its sealed chambers hold three hundred glass coffins, mostly empty. Twelve hold sleepers who look exactly like humans, only taller and paler. {official} measured one through the glass and recorded it at seven feet." },
        dig: { n: "The map-room", text: "A chamber of painted maps shows this world, with the kindled lands marked in a colour the legend calls 'to be reclaimed'. A chart beside it plots a course to a point in the sky. The astrologer's office at {lead} has matched that point to the new star.", points: "cast:official" },
        revelation: { n: "The scout", text: "This was a scout of the makers' ark, sent ahead to report the world fit. It crashed, and the few crew who walked away became the ancestors of the human realms, and forgot. The ark is the new star, and its main body is still asleep. The scout's last report recommends 'reclamation of native fauna'." },
      } },
    { id: "failed_uplift", n: "The Silent Towers of $", kind: "ruin", where: "any", d: "Strange towers of fused mud built by a beast-kind that rose to mind before the present ones, and then fell back.",
      layers: {
        surface: { n: "Mud spires", text: "Spires of hardened earth, far too regular for termites, stand across a dry plain, about two hundred of them. Herders use the lower chambers as goat pens. The goats will not go into the upper ones." },
        study: { n: "Counting marks", text: "The chambers hold scratched counting marks and pictures of a star with a line through it. {believer} copied the marks and found them the same as the first lessons of the star-watch, in the same order." },
        dig: { n: "Bones in the chamber", text: "The tunnels end in a great chamber full of the bones of a burrowing creature that still lives wild and witless on this plain. The counting marks in the chamber all stop at the same number. The weaver-mothers keep a record of that number at {lead}.", points: "temple" },
        revelation: { n: "It does not always last", text: "Another animal was made to think here before the kindled, by the same makers. It counted, built towers and drew the star, and then lost it all within a few generations. The bones show no war and no plague. The kindled's scholars have begun checking their children's sums against their elders', and do not like the numbers." },
      } },
    { id: "blood_pool", n: "The Remembering Pool at $", kind: "anomaly", where: "forest", truthLink: "client_debt", d: "A still pool where kindled who drink are said to remember every ancestor back to the first mother.",
      layers: {
        surface: { n: "Coming of age", text: "A dark pool lies in a silk-hung grove, where the beast-folk bring their young to drink at coming of age. About eighty young drink each year. Humans may watch from the edge of the grove and may not speak." },
        study: { n: "The bright room", text: "Kindled who drink speak afterward of a bright room and a voice saying 'serve the mark'. {survivor} has heard it from three generations of the family's young, in the same words, though none was told what to expect." },
        dig: { n: "The bronze plate", text: "Beneath the pool's mud is a bronze plate engraved with the mark found on the old maker's rings. A human merchant wearing such a ring made a whole market kneel at {lead}.", points: "sub:oath_market" },
        revelation: { n: "Serve the mark", text: "The memory runs back to the making itself, and the first memory is an order. The makers wrote obedience into the kindled's blood, so that their creatures would serve whoever carried the mark. Every debt and oath of the silk cities grew from it. The rings are still in human jewellery boxes, handed down as keepsakes." },
      } },
  ],

  beings: [
    { id: "weaver_kin", n: "Weaver-kin", kind: "beast", d: "A kindled spider-folk the size of a pony, patient, mathematical and courteous, who build cities of silk and speak by drumming and colour.", danger: 1, biomes: ["tempforest", "rainforest", "temprain", "dryforest", "jungle"], look: { size: 1.4, group: [2, 12], move: "pair", speed: 8, col: "#5a4a3a", col2: "#d8c8a0", body: "spider", active: "dusk", visible: true } },
    { id: "counsel_raven", n: "Counsel-raven", kind: "bird", d: "A kindled raven that speaks the human tongue, keeps long genealogies in its head and hires itself out as herald, spy and judge.", danger: 0, biomes: ["boreal", "tempforest", "coldsteppe", "tundra", "alpine"], look: { size: 0.7, group: [3, 20], move: "flock", speed: 50, col: "#1a1a2a", col2: "#6a7aa0", body: "bird", active: "day", visible: true } },
    { id: "hound_elder", n: "Hound-elder", kind: "predator", d: "A great kindled wolf-hound of the steppe clans, grey-muzzled and grave, who hunts only the unkindled and keeps its oaths to the letter.", danger: 2, biomes: ["grass", "coldsteppe", "boreal", "tundra"], look: { size: 1.6, group: [3, 9], move: "pack", speed: 30, col: "#7a7a72", col2: "#2a2a28", body: "quad", active: "any", visible: true } },
    { id: "thinking_hive", n: "Thinking hive", kind: "insect", d: "An ant-colony bred by the weaver-kin to reckon. Fed the right scents it lays out its answer in living lines across a slate floor.", danger: 0, biomes: ["savanna", "dryforest", "rainforest", "grass"], look: { size: 0.01, group: [500, 5000], move: "swarm", speed: 0.5, col: "#6a2a1a", col2: "#2a1a0a", body: "insect", active: "any", visible: false } },
  ],

  techs: [
    { id: "kl_silkcraft", n: "Load-bearing silk", field: "architecture", level: 1, d: "Weaver-kin silk spun into cables and walls stronger than rope or timber." },
    { id: "kl_star_sums", n: "The star's sums", field: "astronomy", level: 2, d: "The numbers and shapes the moving star teaches, copied as hymns and slowly understood as mathematics." },
    { id: "kl_hive_reckoning", n: "Hive reckoning", field: "natural_philosophy", level: 3, d: "Ant-colonies bred and scented to solve problems: harvests, tides, the paths of armies." },
    { id: "kl_blood_lore", n: "Blood-lore", field: "medicine", level: 3, d: "The weaver-mothers' science of inheritance, learned to fight the plague that spares humans." },
    { id: "kl_star_speech", n: "Speaking to the star", field: "arcana", level: 5, d: "A mirror-and-fire signal that the moving star answers. Sometimes it answers with orders instead of lessons." },
  ],

  units: [
    { id: "kl_weaver_host", n: "Weaver-kin host", role: "beast", mounted: 0, wpn: "spear", kit: "hide", ranks: 3, gap: 2, size: 40, w: 0.5, mods: [["theme:silk_cities", 8], ["theme:kindred_war", 4], ["forest", 1.5]] },
    { id: "kl_hound_riders", n: "Hound-elder riders", role: "cavalry", mounted: 1, wpn: "spear", kit: "light", ranks: 3, gap: 2.4, size: 60, w: 0.4, mods: [["theme:unkindled", 4], ["steppe", 2], ["beast_tamers", 3]] },
  ],

  govs: [
    { id: "kl_matriarchy", n: "Kindled matriarchy", d: "A realm where human law sits beneath the council of the weaver-mothers, who rule by inherited memory and the star's counsel.", tags: ["gov:kindled_mothers", "hierarchical"], w: 0.3, forms: ["Web of $", "Mothers' Realm of $", "The Silken Court of $"], ruler: "First Mother", mods: [["theme:silk_cities", 6], ["forest", 1.5]] },
  ],

  faiths: [
    { id: "kl_star_church", n: "The Moving Star", d: "A god who crosses the sky every night at the same hour and teaches in numbers. Its faithful copy its lessons and wait for it to speak plainly.", tags: ["faith:moving_star", "faith:stars"], w: 0.5, names: ["The Church of the Moving Star", "The Vigil of $", "The Lesson-Keepers"], mods: [["seers", 1.5], ["scholarly", 1.5], ["theme:star_orders", 4]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Mud-spire plains", color: "#a07a50", size: [1, 3], count: [0, 2], where: "desert", d: "Fields of fused-earth towers left by a kind that rose to mind before, and fell." },
  ],

  storylines: [
    { id: "kl_star_command", n: "The Star's Command in {realm}", scale: "realm", anchor: "realm", w: 1.5, req: ["kindled", { any: ["pious", "seers", "faith:stars", "forest"] }],
      stages: {
        start: { h: "The moving star speaks plainly over {realm}", b: "For the first time in living memory the star's blinking was not a lesson but a sentence. The weaver-mothers of {realm} say it is an order, and they will not say what it orders.", wait: [2, 5], fx: { unrest: 6 }, next: [{ to: "mothers_obey", w: 1 }, { to: "mothers_refuse", w: 1, mods: [["theme:blood_memory", 2], ["scholarly", 1.5]] }] },
        mothers_obey: { h: "The beast-folk of {realm} leave the human towns", b: "Weaver-kin and counsel-ravens have left the markets and courts of {realm} in long silent columns, heading for the old maker's house. {person}, a human trader, followed them.", wait: [4, 10], fx: { treasury: -40, stability: -5 }, next: [{ to: "correction", w: 1, mods: [["theme:kindled_plague", 3]] }, { to: "trader_returns", w: 1 }] },
        mothers_refuse: { h: "The weaver-mothers of {realm} defy their god", b: "The council of mothers burned the night's scroll and declared that the star is not a god but a teacher, and that pupils may disagree. Half the beast-folk of {realm} are in uproar.", wait: [3, 8], fx: { unrest: 12 }, next: [{ to: "schism_war", w: 1, mods: [["zealous", 2]] }, { to: "kindled_free", w: 1 }] },
        correction: { h: "A plague sweeps the beast-folk of {realm}", b: "At the maker's house the beast-folk carried out the star's order; none will say what it was. Since then the beast-folk sicken and die, and the humans of {realm} do not.", fx: { plague: true, stability: -8, flag: "correction" }, end: true },
        trader_returns: { h: "{person} returns from the maker's house", b: "{person} came back alone with a glass vial and a tale: the star wanted to finish a work begun long ago, and the weaver-mothers smashed the tools instead. The beast-folk are coming home.", fx: { discovery: "medicine", stability: 4 }, end: true },
        schism_war: { h: "The beast-folk of {realm} fight a holy war", b: "Faithful and free beast-folk now fight in the silk canopies above {realm}. Human lords are choosing sides, and {person2} says the star is watching to see who wins.", fx: { stability: -12, pop: 0.92 }, end: true },
        kindled_free: { h: "The star falls silent over {realm}", b: "After a season of defiance the moving star stopped blinking over {realm}. The weaver-mothers have begun to write their own lessons.", fx: { science: { natural_philosophy: 1 }, prestige: 6 }, end: true },
      } },
    { id: "kl_ark", n: "The Sky-Lords Return to {realm}", scale: "realm", anchor: "realm", w: 1, req: ["kindled", { any: ["realm:large", "realm:vast", "scholarly", "faith:stars", "big"] }],
      stages: {
        start: { h: "A new star burns over {realm}", b: "A second bright star grows brighter every night. Astrologers of {capital} call it an omen; the counsel-ravens have stopped speaking to humans altogether.", wait: [6, 14], next: [{ to: "landing", w: 2 }, { to: "star_passes", w: 1 }] },
        landing: { h: "Sky-lords descend near {place}", b: "A craft of silver metal came down near {place}, and tall pale folk stepped out who look like humans and speak a language no one knows. They carry the maker's mark on their hands, and the beast-folk kneel to them.", wait: [3, 8], fx: { unrest: 15, flag: "skylords" }, next: [{ to: "claim", w: 2, mods: [["theme:oath_market", 2]] }, { to: "alliance", w: 1, mods: [["hospitable", 2], ["tolerant", 2]] }] },
        star_passes: { h: "The new star fades from the skies of {realm}", b: "The new star has moved on and grown dim. The counsel-ravens speak to humans again, but they keep watching the sky.", fx: { stability: 3 }, end: true },
        claim: { h: "The sky-lords claim {realm}", b: "Through an interpreter, the sky-lords have declared that this world and every kindled creature on it belong to them by right of making. {ruler} has been ordered to kneel.", fx: { stability: -15, prestige: -10, unrest: 20 }, end: true },
        alliance: { h: "{ruler} makes peace with the sky-lords", b: "The sky-lords have been given land near {place}, and a feast in {capital}. They seem weary, and sick, and grateful. The beast-folk say they will not stay grateful.", fx: { prestige: 8, science: { engineering: 1 } }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, priest-mother of the star-watch", points: "temple", text: "The first hymn of the moving star, as {believer} teaches it to novices, with the priest-mother's gloss, {year}: 'One. One and one. One and one and one. Learn, children, and you will be chosen.' The gloss: 'The kindled are the beast-folk who think. The moving star is the god that made us think. It taught counting first.' The full hymn book, 1,000 years of copied blinks, is kept at {lead}." },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "a ferry-keeper of {place}", text: "A ferry-keeper of {place}, who carries both humans and beast-folk across the river, to a traveller in {year}: 'Our nursemaids tell the children the beast-folk were cursed princes. Theirs tell their young that humans were the ones cursed, with forgetting. I have carried both kinds for 30 years, and I'll say this: the beast-folk always know exactly how much they owe me.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "true", reliable: true, who: "a silk trader of {realm}", points: "site:maker_lab", text: "Note of a silk trader of {realm}, after 9 years in the silk cities, {year}: 'The weaver-kin keep no history older than the white stone house under the trees. Before that, they told me, they were not anyone; they were animals, and then the first mother was born there and they were people. They will show it to a human for three favours. It is at {lead}.'" },

    { depth: "core", about: "truth:gift_missed", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, physician", text: "Notes of {investigator}, physician, inside the maker's fallen house, {year}: 'Ninety-six glass cradles. On every one, a painted long-armed ape, and beneath it the makers' word the scholars read as chosen. Not one cradle shows a weaver. My escort asked me what the paintings meant, and I told her the truth, because she asked. The makers meant to raise the apes. The kindled were raised by accident. Their god was waiting for someone else. She thanked me, and added a fourth favour to my debt.'" },
    { depth: "core", about: "truth:gift_missed", source: "temple", bias: "pious", reliable: "partial", who: "the vigil scrolls of the star-watch", points: "site:moving_star", text: "From the vigil scrolls of the star-watch, night 41 of the year {year}, in the hand of {believer}: 'The star asked again tonight for the long-armed ones, in the old word, nine times. We answered that we are here, in blinks of the lantern as we were taught. It did not seem to hear.' The scrolls for every night since are kept at {lead}." },
    { depth: "core", about: "truth:gift_missed", source: "heretic", bias: "heretic", reliable: "partial", who: "a free weaver's teaching", points: "cast:believer", text: "Teaching of a free weaver, outlawed by the priest-mothers, spoken in a grove of {place} to 20 young, {year}: 'The star was waiting for a different creature, and it never came. We got its gift by accident, and the star is starting to notice the mistake. Ask the priest-mother at {lead} what the star has been asking for, every night for a hundred years.'" },
    { depth: "core", about: "truth:gift_missed", source: "person", bias: "exaggerated", reliable: "partial", cost: true, who: "{investigator}, physician", text: "Letter of {investigator}, physician, to a colleague, {year}: 'This plague takes only the kindled, and it began a year after the star's new hymns. Today I lost {person}, the weaver who first let me into the silk city, and with {person} a whole brood of 11. Not one human in the city has so much as a cough. I do not believe in gods, but I believe in timing.'" },
    { depth: "core", about: "truth:gift_missed", source: "temple", bias: "official", reliable: false, who: "the council of priest-mothers", text: "Ruling of the council of priest-mothers, {year}, read in every silk city: 'The moving star chose the kindled above all creatures and raised them by its love. Its lessons are a gift to its favoured children, and its silence a test of faith. Its new commands are to be obeyed. The plague is a trial, not a sign, and 40 days of prayer are ordered.'" },

    { depth: "core", about: "truth:makers_return", source: "ruin", bias: "true", reliable: true, plain: true, who: "a scholar of {realm}, in the sky-hull", text: "Translated by a scholar of {realm} from the writing in the sky-hull's map-room, {year}: 'SCOUT REPORTS WORLD FIT. NATIVE FAUNA ALTERED BEYOND PLAN. ADVISE RECLAMATION ON ARRIVAL OF MAIN BODY.' The scholar's covering letter to the crown, sent the same day: 'The ridge is a ship, and our ancestors were its crew. The main body is the new star, on its way to reclaim the land and the kindled. Its orders do not mention us at all.'" },
    { depth: "core", about: "truth:makers_return", source: "oral", bias: "garbled", reliable: "partial", who: "a hill-folk singer, recorded by a traveller", points: "sub:forgotten_colony", text: "Recorded by a traveller among the hill-folk who have no writing, {year}: they sing of tall pale masters who sleep in glass beyond the sky, 'seven feet and white as frost', and will wake when the second star burns. They sing it as a lullaby. The hill-folk call the beast-folk 'masters' too, and cannot say why. Their valley is at {lead}." },
    { depth: "core", about: "truth:makers_return", source: "archive", bias: "redacted", reliable: "partial", who: "{official}, royal astrologer", points: "site:ark_wreck", text: "Report of {official}, royal astrologer, to the crown, {year}: 'The new star moves against the heavens and grows brighter by [figure scraped away] each month. If it is a ship, as the kindled ravens claim, it is steering toward the point marked on the charts in the desert ridge at {lead}, and will arrive within [figure scraped away] years. I recommend the crown say nothing.'" },
    { depth: "core", about: "truth:makers_return", source: "traveller", bias: "exaggerated", reliable: "partial", cost: true, who: "a desert guide, to {official}", text: "A desert guide, questioned by {official} in {year}: 'The sleepers in the metal coffins have opened their eyes. Not wide. Just a crack, like someone checking if it is morning yet. My partner {person} put a hand flat on the glass to look closer. The cold took three of {person}'s fingers, and the sleeper's eyes followed the hand. We do not camp there any more, at any price.'" },
    { depth: "core", about: "truth:makers_return", source: "library", bias: "official", reliable: false, who: "the royal Natural History of the South", text: "The royal Natural History of the South, chapter 8, {year}: 'The metal ridge in the southern sands is a natural outcrop of star-iron, some 2 miles long. The so-called sleepers are the mummified dead of a forgotten desert people, preserved by dry air. The new star is a comet, and will pass.'" },

    { depth: "core", about: "truth:client_debt", source: "person", bias: "true", reliable: true, plain: true, who: "a human merchant, in a diary", points: "site:blood_pool", text: "Diary of a human merchant of {place}, {year}: 'I wore my late uncle's old ring into the silk city. Every weaver in the market, two hundred at least, stopped and bowed and would not rise until I told them to. It is the mark. They cannot refuse whoever wears it; it is in their blood. The same mark is on a bronze plate under their coming-of-age pool at {lead}. I have locked the ring away.'" },
    { depth: "core", about: "truth:client_debt", source: "heretic", bias: "true", reliable: "partial", cost: true, who: "{survivor}, weaver-kin elder", text: "Confession of {survivor}, weaver-kin elder, to {investigator}, {year}: 'When I drank from the pool I remembered a bright room and a voice: serve the mark. I have served debts all my life. When a human came with a ringed hand and claimed my eldest, {person}, as a debt of the line, I gave {person} up, and did not know why I could not say no. That was 14 years ago.'" },
    { depth: "core", about: "truth:client_debt", source: "oral", bias: "garbled", reliable: "partial", who: "a counsel-raven of the silk city", points: "cast:survivor", text: "A counsel-raven of the silk city, asked by a human envoy in {year} to explain the oath-customs, gave only the ravens' proverb: 'Every egg hatches owing.' Asked whom it owed, the raven said that nobody, not even the ravens, could say, and charged the envoy 2 favours for the answer. It suggested the envoy ask the elder at {lead}, who had paid the most." },
    { depth: "core", about: "truth:client_debt", source: "archive", bias: "propaganda", reliable: false, who: "the oath-market's charter", text: "Preamble to the charter of the oath-market, as copied for human traders, {year}: 'The oath-customs of the beast-folk are a free and honourable tradition, chosen by their mothers in ancient councils, and owe nothing to any outside power. Every debt is recorded, every debt is inherited, and every debt is paid.' Clause 1 of 300 then sets the price of a favour in silk." },

    { depth: "sub", about: "sub:web_city", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a human glassblower, home from the silk city", text: "A human glassblower, home from a season in the silk city of {place}, {year}: 'It hangs between trees a hundred paces tall, lit at night by glow-moths in jars. I walked on its floors for a week and never saw the ground. I was fed, housed and admired, and when I left I owed my hosts eleven favours, written down in silk and witnessed.'" },
    { depth: "sub", about: "sub:living_reckoners", source: "library", bias: "garbled", reliable: "partial", who: "a scholar of {realm}, visiting a hive", points: "library", text: "Account of a scholar of {realm}, visiting a thinking hive, {year}: 'The weaver-mothers poured three scents on the hive floor, and by dusk the ants had drawn the river's flood-line for the coming spring across 40 feet of sand. It was right to the stone.' The scholar's full measurements, and a complaint about the bites, are filed at {lead}." },
    { depth: "sub", about: "sub:blood_memory", source: "person", bias: "true", reliable: "partial", who: "a young weaver, to a human healer", points: "site:failed_uplift", text: "A young weaver of {place}, to a human healer, {year}: 'My mother's mother's mother's memories keep taking over my legs. She tries to walk me to a forest that was cut down 200 years ago. Last week she walked me two days east, to the mud towers at {lead}, and made me count the marks on the wall. I do not know why she cares. I only know she was frightened.'" },
    { depth: "sub", about: "sub:unkindled_cousins", source: "oral", bias: "pious", reliable: "partial", who: "the hound-elders' law, recited at {place}", text: "The hound-elders' law, recited by the kindled of {place} at every border feast, {year}: 'To kill a dumb cousin is to kill your own grandmother before she was born.' The village hunters of {realm} have never heard of this law. Last winter they sold 60 pelts of dumb cousins at the border market, and the hound-elders bought every one, to bury." },
    { depth: "site", about: "site:failed_uplift", source: "traveller", bias: "true", reliable: "partial", who: "a surveyor of {realm}", text: "Field book of a surveyor of {realm}, crossing the plain of mud towers, {year}: 'Inside the towers I found a star drawn on every wall, with a line through it, and counting marks beneath it. In every chamber of all 12 towers I entered, the counting stopped at the same number: 4,096. Beneath the deepest chamber are bones. The creatures that left them still live here, and cannot count to two.'" },
  ],
};
