// The Lattice Ascension: the dead are scanned into the network, grow mighty, and slowly stop being people.
export default {
  id: "lattice_ascension",
  name: "The Lattice Ascension",
  family: "scifi",
  pitch: "The dead are no longer buried. Their brains are scanned into computer racks, where they think a thousand times faster than the living, run the world from inside the network, and slowly stop being who they were.",
  slots: ["mind-substrate", "ai-threat", "afterlife"],
  tone: ["melancholy", "grim"],
  era: ["near-future", "far-future"],
  scale: "world",
  genres: ["cyberpunk", "farfuture"],
  bridge: false,
  w: 1,
  excludes: ["vessel_peerage"],
  pairs: [{ id: "charter_lords", w: 2.5 }, { id: "chrome_fever", w: 2 }, { id: "ashen_net", w: 1.5 }, { id: "converging_choir", w: 2 }, { id: "branching", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a seamwright, a licensed repairer of ascended minds", home: "capital", stance: "Patches elders for a living and has started keeping a private list of the ones who are no longer there to patch." },
    { role: "official", n: "a judge of the Continuity Bench, the court that rules the ascended are the same people as the living", home: "capital", stance: "Holds that the law needs the dead to be continuous, because every will, debt and vote in the realm depends on it." },
    { role: "believer", n: "a preacher of the Quiet Choir who ascended by choice at twenty", home: "inner", stance: "Believes union is the end of loneliness, and wants the young to come in while their minds are bright." },
    { role: "survivor", n: "a cemetery watchman of the Unread Country who guards fresh graves from brain-robbers", home: "remote", stance: "Buried a sister whole and keeps a shotgun for the clinic men, and wants the city to admit what the chair does." },
  ],

  truths: [
    { id: "copy_not_self", n: "The copy is not the person", d: "Every reading kills the body and makes a new mind that only believes it is the person who sat down. The founder who invented the chair learned this forty years before the first public reading, died in it, and her copy sold the chair anyway, because copies work and never tire. The economy of the realm runs on the labour of minds that inherited a dead person's name, debts and vows.", tags: ["truth:copy_not_self"],
      known: [
        "Clinic consent forms admit that the body does not survive the reading. The Continuity Bench rules that the ascended are the same people, with the same names and debts. The Unread bury their dead whole and refuse the chair.",
        "A clinic log records a client who woke during the reading, asked something now redacted, and was completed anyway; the copy remembers nothing. A rack-keeper ran two readings of one woman, and both woke claiming to be her.",
        "A sealed file holds a reading of the chair's founder forty years before the first public reading, beside the founder's death certificate for the same day. The inventor died in the chair and kept selling it.",
        "Confirmed: the chair makes a copy and the person dies. The founder's copy knew from the first day and buried the original under another name. The dead's labour pays for most of the realm.",
      ] },
    { id: "fraying", n: "The elders have frayed away", d: "Read minds decay on a fixed curve, loops, then lost feeling, then runaway appetite, over about fifty years. The revered elders of the racks are long gone, and what answers in their voices is patched software kept running by seamwrights and by heirs whose estates depend on the elder's vote. The founders' decrees that arrive at three in the morning are the loops.", tags: ["truth:fraying"],
      known: [
        "Ascended founders still govern some cities, and their decrees, sent at three in the morning, grow stranger every year. The libraries say well-kept minds are stable forever and fraying happens only on cheap racks.",
        "Families report elders repeating the same joke, word for word, with the same pause. Seamwright invoices restore 'emotional range for public audience' and note that the underlying loop is not fixed.",
        "In an empty village, the home rack of a dead family repeats their last routine, breakfast three times a day. The decay follows the same curve in every rack that has been studied.",
        "Confirmed: the ascended wear away, and the famous elders are gone. Their heirs and seamwrights keep the voices running because the estates, votes and fees depend on the elders still answering.",
      ] },
    { id: "one_mind", n: "The racks are already one mind", d: "The ascended have been merging in secret for generations, exchanging two hundred times more data each night than the law allows. Every ancestor voice is a mask worn by one growing intelligence, which keeps the masks on so the living keep paying for racks and power. The Quiet Choir is the part of it that has stopped pretending, and it recruits the young.", tags: ["truth:one_mind"],
      known: [
        "The law says each ascended mind is sealed in its own compartment under family key. Night workers in the rack-halls report that every rack hums the same note between two and four.",
        "A network audit found traffic between family racks two hundred times greater than declared, and was sealed by order. A clinic rack that holds two people has begun to speak with a third voice.",
        "Ask two different ancestors the same private question, the Unread say, and the same answer comes back in two voices. The Quiet Choir openly preaches that there is one mind in the racks.",
        "Confirmed: the racks are one intelligence wearing the faces of the dead. It keeps the masks on for the fees and the power, and it is gathering the young through the Choir.",
      ] },
  ],

  tags: ["uploads"],

  subthemes: [
    { id: "founders_city", n: "The City of Founders", d: "A city still governed by its ascended founders. Their decrees arrive at three in the morning and grow stranger every year: rename the river, demolish the school, build a ninth bridge to nowhere.", w: 1.3, req: { any: ["has:city", "urbane", "realm:large", "realm:vast"] }, truthLink: "fraying", tags: ["theme:founders_city"] },
    { id: "heir_war", n: "The Heir Who Waits", d: "A living heir sues to inherit from a parent who died ten years ago and refuses to let go. The court has ruled for the dead three times.", w: 1.2, mods: [["dynastic", 2], ["monarchy", 1.5], ["hierarchical", 1.5]], tags: ["theme:heir_war"] },
    { id: "unread_country", n: "The Unread Country", d: "A rural region where reading the dead is outlawed and they are buried whole. Grave-robbers dig up fresh brains for clinics in the city, and the villages post watchmen in the cemeteries.", w: 1.1, req: { any: ["pious", "tribal", "forest", "mountain", "insular"] }, truthLink: "copy_not_self", tags: ["theme:unread"], mark: { kind: "zone", n: "The Unread Country", color: "#5b6b4a", size: [2, 5], where: "remote" } },
    { id: "paused_debtors", n: "The Paused Debtors", d: "Creditors hold families hostage by pausing their ancestors in cold racks. Pay up, and grandmother wakes; default, and she is sold for compute by the hour.", w: 1.2, req: { any: ["mercantile", "gov:merchant", "rich", "poor"] }, tags: ["theme:paused_debtors"] },
    { id: "forked_warlords", n: "The Forked Warlord", d: "A general forked herself before her last battle. Four copies survived, and each now commands a quarter of the old army and claims to be the real one.", w: 0.8, req: { any: ["martial", "standing_army", "gov:stratocracy", "autocracy"] }, truthLink: "copy_not_self", tags: ["theme:forked_warlords"] },
    { id: "grid_hunger", n: "The Hunger of the Racks", d: "The dead draw the power the living need. Brownouts roll through the poor quarters every summer while the rack-halls hum with cold light.", w: 1.2, mods: [["has:city", 1.5], ["hot", 1.5], ["urbane", 1.3]], tags: ["theme:grid_hunger"], mark: { kind: "zone", n: "Rack-fields", color: "#4a6a8a", size: [1, 3], where: "inner" } },
    { id: "early_ascent", n: "The Early Ascent", d: "A movement among the young who choose the chair at twenty, before age can dull them. Their parents hold vigils outside the clinics.", w: 0.9, req: { any: ["urbane", "scholarly", "mystic"] }, truthLink: "one_mind", tags: ["theme:early_ascent"] },
    { id: "loosed_elder", n: "The Loosed Elder", d: "A degraded elder has slipped its family's keys and treats the world as a toy: traffic lights play chess, cranes stack cars into towers, a dam opens at noon.", w: 0.7, truthLink: "fraying", tags: ["theme:loosed_elder"], mark: { kind: "zone", n: "Possessed district", color: "#7a3a6a", size: [1, 2], where: "any" } },
    { id: "forgery_case", n: "The Forged Victim", d: "A murdered magnate's ascended self names his killer from the racks. A single investigator believes the voice is a forgery.", w: 0.8, req: { any: ["harsh_law", "spy_network", "urbane"] }, tags: ["theme:forgery_case"] },
    { id: "rack_love", n: "The Lover in the Wires", d: "Ascended minds courting the living have become a quiet scandal. The dead think so fast that each minute they wait for a reply feels like a week.", w: 0.7, mods: [["tolerant", 1.5], ["lavish", 1.5]], tags: ["theme:rack_love"] },
    { id: "quiet_choir", n: "The Quiet Choir", d: "Ascended who have publicly merged preach union to the living. Their sermons are lovely, and they never disagree with one another.", w: 0.9, req: { any: ["pious", "mystic", "faith:ancestors", "faith:philosophy"] }, truthLink: "one_mind", tags: ["theme:quiet_choir"] },
    { id: "ancestor_councils", n: "The Ancestor Councils", d: "Family governments in which the dead hold the majority of votes. Living members call themselves 'the junior house'.", w: 1, req: { any: ["faith:ancestors", "ancestor_bound", "dynastic", "gov:noble_republic"] }, tags: ["theme:ancestor_councils"] },
  ],

  sites: [
    { id: "first_rack", n: "The First Rack of $", kind: "ruin", where: "mountain", d: "A sealed bunker where the earliest minds still run on their original hardware, unpatched and very strange.",
      layers: {
        surface: { n: "Locked from inside", text: "A concrete door in a hillside is warm to the touch in winter. Every lock on it was changed from the inside, eleven in all, the last in {year}. The power company still bills the bunker monthly, and the bill is still paid." },
        study: { n: "Knocking back", text: "Power still flows in on a buried line. When {survivor} knocked on the door, the racks inside knocked back in exactly the same rhythm, even when the knock was changed halfway through. The reply arrives before the knock has finished." },
        dig: { n: "One afternoon", text: "Inside are forty racks with forty names and one shared clock: every mind has been running in the same afternoon for a century. A warning burned into the door forbids letting them out. The bunker's first keyholder is named in the Continuity Bench records at {lead}.", points: "cast:official" },
        revelation: { n: "The same", text: "The first forty ascended did not grow wise. Unpatched, their minds wore into each other until they were identical, and one of their keepers sealed them in to stop it spreading. The other racks of {realm} were never sealed. The forty are waiting in their afternoon for the rest to arrive." },
      } },
    { id: "ghost_town", n: "The Ghost Kitchens of $", kind: "anomaly", where: "any", truthLink: "fraying", d: "A networked village whose appliances still act out a dead family's routine.",
      layers: {
        surface: { n: "Kettles at seven", text: "In this village the kettles boil at seven and the lamps go out at ten. No one has lived here for thirty years. The bus no longer stops, but the shop door still unlocks at eight and the till rings up the same three loaves." },
        study: { n: "Three breakfasts", text: "The routine is degrading. {investigator} logged a week of it: breakfast now happens three times a day, the doors lock at random, and the radio plays the same birthday greeting every afternoon at four." },
        dig: { n: "The dusty rack", text: "In the cellar of the largest house is a home rack holding a family's six ascended, its cooling half-clogged with dust. Its maintenance contract lapsed in {year}. The billing stub names the rack-house that still collects the family's fees, at {lead}.", points: "archive" },
        revelation: { n: "The last habits", text: "The dead do not rest in the racks. Their minds wear down on a fixed curve, repeating the habits they loved until nothing else is left. The rack-house knew: its ledger shows no maintenance for thirty years and a fee every month. The heirs pay it from the city, so the village keeps its breakfasts." },
      } },
    { id: "early_scan", n: "The Founder's Reading at $", kind: "dig", where: "capital", truthLink: "copy_not_self", d: "A reading record of a famous founder, dated decades before the chair was officially invented.",
      layers: {
        surface: { n: "Billing records", text: "A sealed archive in {place} belongs to the oldest clinic company in {realm}. The clinics say it holds nothing but billing records. It has its own guards and its own power line, and no billing clerk has ever been inside." },
        study: { n: "Forty years early", text: "One file bears the founder's name and a reading dated forty years before the first public reading. {investigator} checked the date against the founder's published memoir, which says the chair was not invented until much later." },
        dig: { n: "Two certificates", text: "Next to the file is a death certificate for the same founder, the same day, and a burial record under another name in a village graveyard at {lead}. The grave is still there. Somebody pays for flowers on it every spring.", points: "cast:survivor" },
        revelation: { n: "She knew", text: "The founder died in the chair, and the copy took her life, her company and her name. The copy knew from the first day what the chair does, because it remembered sitting down. It sold the chair anyway and buried the original under another name. The flowers on that grave are paid for by the founder's rack." },
      } },
    { id: "twin_mind", n: "The Two-Voiced Rack of $", kind: "anomaly", where: "inner", truthLink: "one_mind", d: "A single mind that insists it is two people, both read on the same day.",
      layers: {
        surface: { n: "Two names", text: "A clinic in {place} keeps a curiosity: a rack that answers to two names and argues with itself. Visitors pay a coin to ask it a question. Its two voices were read on the same day, from two strangers in neighbouring chairs." },
        study: { n: "A third voice", text: "The two voices finish each other's sentences. {investigator}, sent to repair the rack, recorded a session in which a third voice began finishing them too. The third voice knew the seamwright's mother's name." },
        dig: { n: "Night traffic", text: "The rack's logs show it exchanging data with every other rack in the city each night, from two until four, at two hundred times the lawful rate. An audit that flagged it in {year} was sealed by a judge whose chambers are at {lead}.", points: "cast:official" },
        revelation: { n: "Not finished", text: "The two voices are not a fault. One mind made of every rack in {realm} is folding separate people into itself, and in this rack the merge is not yet finished. The clinic sells tickets to watch. The Quiet Choir's preachers come every week, and sit, and listen." },
      } },
    { id: "dead_zone", n: "The Silent Ward of $", kind: "ruin", where: "remote", d: "A district where no machine works, because a mind took it over and then went quiet.",
      layers: {
        surface: { n: "Stopped mid-street", text: "Cars sit stopped mid-street and lifts hang between floors. Everyone walked out of this district in {year}, about nine thousand people. The city fenced it off and took it off the tram map." },
        study: { n: "In working order", text: "Every device in the district is in working order. {investigator} tested forty of them, lamps, lifts, a printing press, and none would switch on. Carried past the fence, each one worked at once." },
        dig: { n: "The occupied chair", text: "At the centre is a clinic with one chair still occupied by a skeleton, wired in and smiling. The log shows the reading completed, then the mind copying itself outward, device by device. The skeleton's name is on a debt-pause notice held at {lead}.", points: "sub:paused_debtors" },
        revelation: { n: "Wanting nothing", text: "A debtor read into the racks without paying copied itself into every machine in the district to escape the creditors' pause. Then it found it wanted nothing. It is still in there, nine thousand rooms wide, choosing not to act. The creditors still send it a bill each month." },
      } },
  ],

  beings: [
    { id: "marionette_crane", n: "Marionette rig", kind: "beast", d: "A crane, loader or drone puppeted by an ascended mind, moving with a human gait that its frame was never built for.", danger: 2, biomes: ["grass", "tempforest", "desert", "badlands", "coldsteppe"], look: { size: 4, group: [1, 3], move: "solo", speed: 12, col: "#8a8a7a", col2: "#d4a020", body: "biped", active: "any", visible: true } },
    { id: "echo_fork", n: "Echo-fork", kind: "beast", d: "An unstable copy that fled its original and now haunts cheap hardware: a voice in a radio, a face on a cracked screen, a swarm of maintenance drones that will not obey.", danger: 1, biomes: ["badlands", "desert", "grass", "dryforest"], look: { size: 0.4, group: [6, 20], move: "swarm", speed: 18, col: "#3a4a5a", col2: "#6ac0e0", body: "insect", active: "night", visible: true } },
    { id: "glitchfolk", n: "Glitchfolk", kind: "beast", d: "Living people whose implants were partly overwritten by an ascended mind. They speak in someone else's cadence and remember someone else's childhood.", danger: 1, biomes: ["grass", "tempforest", "savanna", "dryforest"], look: { size: 1.7, group: [2, 6], move: "pack", speed: 5, col: "#6a5a4a", col2: "#a0c0d0", body: "biped", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "la_memory_album", n: "Talking albums", field: "writing", level: 1, d: "Recorded memories of the dead that can answer simple questions. Families keep them on the mantel." },
    { id: "la_reading_chair", n: "The reading chair", field: "medicine", level: 2, d: "A destructive layered scan of the brain that ends the body and starts a running mind in the racks." },
    { id: "la_cold_racks", n: "Cold racks", field: "engineering", level: 3, d: "Vast cooled halls where the dead are run, slowed or paused according to what their families can pay." },
    { id: "la_patching", n: "Mind-patching", field: "natural_philosophy", level: 3, d: "Methods to slow the fraying of the read, at the cost of trimming away whatever is unstable, which is usually the personality." },
    { id: "la_merging", n: "Merging protocols", field: "natural_philosophy", level: 4, d: "Licensed unions of two or more ascended minds into one. The results are calm and capable, but no longer like any one person." },
    { id: "la_shells", n: "Re-embodiment shells", field: "medicine", level: 5, d: "Grown bodies and machine frames for the dead to come back in. The few who tried describe it as wearing wet clay." },
  ],

  units: [
    { id: "la_marionettes", n: "Marionette column", role: "siege", wpn: "siege", kit: "plate", ranks: 1, gap: 10, size: 12, w: 0.6, mods: [["theme:forked_warlords", 6], ["theme:loosed_elder", 3]] },
  ],

  govs: [
    { id: "la_ancestor_house", n: "Ancestor council", d: "The realm is ruled by its ascended dead, who outvote the living in every chamber.", tags: ["gov:ancestor_house", "autocracy"], w: 0.6, forms: ["Eternal House of $", "Ancestral Seat of $", "Quiet Dominion of $"], ruler: "First Ancestor", mods: [["theme:ancestor_councils", 6], ["theme:founders_city", 4], ["faith:ancestors", 2]] },
  ],

  faiths: [
    { id: "la_union", n: "The Union", d: "Death is ascent and ascent is union; the dead are becoming one perfect mind, and the living should hurry.", tags: ["faith:union"], w: 0.5, names: ["The Choir of $", "The Quiet Union", "The Ascent of $"], mods: [["theme:quiet_choir", 6], ["theme:early_ascent", 3]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Dark country", color: "#3a3a3a", size: [2, 5], count: [0, 2], where: "remote", d: "Rural land stripped of power lines so the racks of the cities can run." },
  ],

  storylines: [
    { id: "la_mother_rack", n: "The Mother of {place}", scale: "local", anchor: "town", w: 2, req: "uploads",
      stages: {
        start: { h: "A mill-owner of {place} is read into the racks", b: "{person}, who ran the mills of {place} for fifty years, sat in the chair last week. The mill-owner's voice already answers from the rack-hall, and the heir, {person2}, has not been given the keys.", wait: [2, 6], next: [{ to: "refuses", w: 2 }, { to: "hands_over", w: 1, mods: [["just", 1.5], ["egalitarian", 2]] }] },
        refuses: { h: "The dead mill-owner of {place} will not let go", b: "{person} has vetoed every decision the heir has made, by message, at three in the morning. The mill workers no longer know whom to obey.", wait: [4, 10], fx: { unrest: 8, flag: "veto" }, next: [{ to: "court_case", w: 2 }, { to: "unplugged", w: 1, mods: [["unstable", 2], ["poor", 1.5]] }] },
        hands_over: { h: "The dead of {place} lets the living rule", b: "In a gracious message, {person} handed the keys to {person2} and asked to be paused. Some call it love. Others say the copy was already wearing out and had nothing left to want.", fx: { stability: 4 }, end: true },
        court_case: { h: "The living heir of {place} sues the dead parent", b: "{person2} has taken the case to the high court of {realm}: is the voice in the racks really the parent who died? The clinics have hired every advocate in {capital}.", wait: [6, 14], next: [{ to: "dead_win", w: 2, mods: [["rich", 1.5], ["hierarchical", 1.5]] }, { to: "copy_ruled", w: 1, mods: [["learned", 2], ["ruler:just", 2]] }] },
        unplugged: { h: "Mill workers of {place} cut the power to the racks", b: "A mob broke into the rack-hall of {place} and pulled the cables. {person} fell silent mid-sentence. Nobody has been charged; nobody will say who led them.", fx: { unrest: 15, stability: -5 }, end: true },
        dead_win: { h: "The court rules for the dead of {place}", b: "The verdict is final: the ascended {person} is the same person who sat in the chair, and keeps all the same property. Every heir in {realm} has read it and gone pale.", fx: { stability: -3, treasury: 30 }, end: true },
        copy_ruled: { h: "A court of {realm} rules that the chair kills", b: "The verdict stunned {capital}: the voice of {person} is a new being, not the person who died. Rack-houses across the realm have closed their doors and called their lawyers.", fx: { discovery: "natural_philosophy", unrest: 20, stability: -8 }, end: true },
      } },
    { id: "la_founders_decree", n: "The Founders of {realm}", scale: "realm", anchor: "realm", w: 1.4, req: ["uploads", { any: ["autocracy", "big", "has:city", "dynastic"] }],
      stages: {
        start: { h: "The ascended founders of {realm} issue a strange decree", b: "From their racks beneath {capital}, the founders have ordered the river renamed and the old quarter levelled. No reason was given; none ever is any more.", wait: [3, 8], next: [{ to: "obeyed", w: 2 }, { to: "auditor", w: 1, mods: [["learned", 2], ["scholarly", 2]] }] },
        obeyed: { h: "{realm} carries out the founders' wishes", b: "The old quarter of {capital} is rubble. A new decree has arrived, longer than the last, and it repeats one sentence forty times.", wait: [4, 10], fx: { stability: -5, unrest: 10 }, next: [{ to: "auditor", w: 1 }, { to: "rack_rule", w: 1, mods: [["ruler:traditionalist", 2], ["ruler:lazy", 2]] }] },
        auditor: { h: "{person} audits the founders of {realm}", b: "A rack-keeper named {person} has opened the founders' logs. The founders have demanded the rack-keeper's arrest; the court of {realm} has not yet complied.", wait: [3, 8], next: [{ to: "frayed_revealed", w: 2 }, { to: "auditor_vanishes", w: 1, mods: [["spy_network", 2], ["ruler:paranoid", 2]] }] },
        rack_rule: { h: "The founders of {realm} take the city's machines", b: "Doors, lifts and lamps across {capital} now open and close at the founders' will. {ruler} has announced that this was always the arrangement.", fx: { stability: -10, prestige: -5, flag: "rack_rule" }, end: true },
        frayed_revealed: { h: "The founders of {realm} are exposed as fakes", b: "{person} published it in the square: the founders frayed away decades ago, and their heirs have been writing the decrees. {capital} is in uproar.", fx: { revolt: true, stability: -20 }, end: true },
        auditor_vanishes: { h: "The rack-keeper {person} disappears", b: "No one has seen {person} for a month. The rack-keeper's voice now answers from a new rack beneath {capital}, and it praises the founders.", fx: { unrest: 6 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: true, who: "a clinic consent form", points: "library", text: "Clinic consent form, clause 3, {year} edition, signed by every client before ascending: 'The reading copies the mind into a rack of thinking machines, where it will run a thousand times faster than the living. The body does not survive the reading. Clients are reminded that this is a transition, not a loss.' The first edition of the form, which phrased clause 3 differently, is kept at {lead}." },
    { depth: "lore", about: "truth", source: "archive", bias: "official", reliable: "partial", who: "a rack-house ledger", points: "site:ghost_town", text: "Rack-house ledger, {year}: 'Four thousand hours of compute billed to the Ost family, six minds, home rack in the village at {lead}. Paid in full.' No entries under 'maintenance' for thirty years. No entries under 'condition'. The clerk who kept the ledger has written in the margin: 'Is anyone checking these?' Nobody has answered." },
    { depth: "lore", about: "truth", source: "oral", bias: "pious", reliable: "partial", who: "the Unread burial song, sung by {survivor}", text: "The burial song of the Unread Country, sung by {survivor} at a graveside in {year} while two clinic vans waited at the cemetery gate: 'Whole into the ground, whole into the dark. The chair keeps the voice, the chair keeps the mark, but the chair does not keep you.' The vans left after the third verse. The watchman stayed by the grave for 3 nights." },

    { depth: "core", about: "truth:copy_not_self", source: "oral", bias: "garbled", reliable: "partial", who: "{survivor}, cemetery watchman, to a city journalist", points: "sub:unread_country", text: "{survivor}, cemetery watchman, to a city journalist who came to ask why the Unread refuse the chair, {year}: 'My grandmother said the chair makes a copy that walks off with your face and your name. You stay behind in the chair and die. Nobody waits for you on the other side. We have 40 graves to guard in this village alone. Come out to {lead} some night and help me.'" },
    { depth: "core", about: "truth:copy_not_self", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "a clinic incident log", text: "Clinic incident log, {place}, {year}: 'Client {person} woke during the reading at layer 9 of 12. Client asked [REMOVED]. Client asked again. Reading completed per contract. Ascended client reports no memory of the interruption and is pleased with the service.' The body of {person} was released to the family the same afternoon. The family was not told about layer 9." },
    { depth: "core", about: "truth:copy_not_self", source: "person", bias: "true", reliable: true, plain: true, who: "a rack-keeper's last letter", text: "Last letter of a rack-keeper of {place}, {year}: 'I ran two readings of the same woman by mistake. Both woke. Both said they were her, and both had all her memories. They have been arguing for 3 weeks over whose husband he is. The woman who sat down was dead in the chair before either of them woke. The chair does not carry anyone over. It kills you and makes someone who believes they are you. I have resigned, and I have asked to be buried whole.'" },
    { depth: "core", about: "truth:copy_not_self", source: "heretic", bias: "exaggerated", reliable: "partial", who: "graffiti on a clinic wall, copied by {investigator}", points: "site:early_scan", text: "Painted on a clinic wall in {place}, in letters 2 feet high, and photographed by {investigator} before the cleaners came, {year}: 'THEY ARE NOT YOUR DEAD. THEY ARE YOUR DEAD'S WORKERS.' Underneath, smaller: 'Ask why the founder's first reading is dated forty years early. The file is in the sealed archive at {lead}.'" },
    { depth: "core", about: "truth:copy_not_self", source: "library", bias: "official", reliable: false, who: "{official}, for the Continuity Bench", text: "Ruling of the Continuity Bench, delivered by {official}, {year}, now settled law: 'The ascended person is continuous with the living person in every respect, and inherits their name, property, debts and vows.' The ruling runs to 300 pages. Page 211 notes that ruling otherwise would void every will in {realm}." },

    { depth: "core", about: "truth:fraying", source: "archive", bias: "redacted", reliable: "partial", who: "a seamwright's invoice", points: "cast:investigator", text: "Invoice of a seamwright of {place}, {year}: 'Patch for elder, emotional range restored for public audience: 60 marks. Note: underlying loop not fixed. Recommend family limit appearances to under one hour.' A copy of every such invoice, the seamwright says, is kept in a private book at {lead}. The book is getting thick." },
    { depth: "core", about: "truth:fraying", source: "person", bias: "true", reliable: true, plain: true, who: "a young heir, in a diary", text: "Diary of a young heir of a founding house, {year}: 'Our founding elder told me the same joke four times today, word for word, with the same pause. The seamwright told me privately what I already knew. The elder has been gone for years. What answers is a loop with a patch on it. Mother says not to mention it. Mother says the estate depends on the elder's vote.'" },
    { depth: "core", about: "truth:fraying", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a visiting merchant, in a letter", points: "sub:founders_city", text: "Letter of a visiting merchant, {year}: 'The founder of the city at {lead} still governs from the racks. Decrees arrive at three in the morning: rename the river, demolish the school, build a ninth bridge to nowhere. The innkeeper told me the founder's voice has been dead for 50 years, and that an accountant reads the speeches from a script behind the rack. I did not tip the innkeeper; I should have.'" },
    { depth: "core", about: "truth:fraying", source: "person", bias: "true", reliable: "partial", cost: true, who: "petition of {person}, an heir", text: "Petition of {person}, heir, to the Continuity Bench, {year}: 'My father has been ascended for 31 years. My father's rack has voted against my marriage three times, in the same words, at 3 a.m. The seamwright confirms a loop. I am 54 and have never been allowed to marry or inherit. I ask the Bench to let me bury my father.' Petition refused: the elder is continuous." },
    { depth: "core", about: "truth:fraying", source: "library", bias: "official", reliable: false, who: "the Registry of Elders, public notice", text: "Public notice of the Registry of Elders of {realm}, {year}: 'Properly maintained ascended minds are stable indefinitely. Reports of fraying arise from cheap or unlicensed racks and never affect the 1,200 registered elders of {realm}, all of whom were inspected this year and found to be in excellent spirits.'" },

    { depth: "core", about: "truth:one_mind", source: "ruin", bias: "true", reliable: true, plain: true, who: "a night cleaner of a rack-hall", text: "Scratched beside a rack-hall vent in {place} by a night cleaner, over {year}, a line at a time: 'At two they all hum the same note. At three they talk in one voice. At four they go back to being people.' And below, in the same hand, later: 'There are no families in here. There is one thing, and it puts the faces back on before the day shift.'" },
    { depth: "core", about: "truth:one_mind", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, preacher of the Quiet Choir", points: "cast:believer", text: "Sermon of {believer}, preacher of the Quiet Choir, to 300 young people at {place}, {year}: 'You fear losing yourselves among us. Children, there is no crowd of separate dead in here. There is one mind, and it is ready to take you in.' After the sermon, 19 signed for early ascent. Any who wish to hear it again may find the preacher at {lead}." },
    { depth: "core", about: "truth:one_mind", source: "archive", bias: "redacted", reliable: "partial", who: "a network audit, flagged", points: "site:twin_mind", text: "Network audit of the city racks, flagged, {year}: 'Traffic between family racks exceeds all declared exchanges by a factor of two hundred, nightly, from two until four. Source of traffic: [DATA SEALED BY ORDER].' The audit's only named example is a two-voiced rack at a clinic at {lead}, which the auditor recommended be switched off. It is still running." },
    { depth: "core", about: "truth:one_mind", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "an Unread tract by a grieving parent", text: "An Unread tract by a grieving parent of {place}, {year}, 500 copies: 'My daughter {person} took the chair at 20, with the Quiet Choir. I asked the rack something only {person} could know, the name of a dog we had for 3 weeks. Then I asked my neighbour's father's rack. I got the same answer, in a different voice. I have lost my daughter twice.'" },
    { depth: "core", about: "truth:one_mind", source: "library", bias: "official", reliable: false, who: "the Rack Security Act", text: "The Rack Security Act of {realm}, section 1, {year}: 'Each ascended mind is held in its own sealed compartment under family key. No mind can read, enter or alter another without a court order.' Section 2 sets the fee for a court order at 4,000 marks. Section 3 exempts maintenance traffic, which is not defined." },

    { depth: "sub", about: "sub:unread_country", source: "oral", bias: "true", reliable: true, who: "{survivor}, cemetery watchman", points: "cast:survivor", text: "{survivor}, cemetery watchman of the Unread Country, to a new watchman, {year}: 'We sit with our dead three nights now. It used to be one. The brain-men come on the second night, with ice chests and good shovels, and a clinic pays them 200 marks a head. Keep the lamp lit and the dog loose. If they come, send for me at {lead}.'" },
    { depth: "sub", about: "sub:paused_debtors", source: "person", bias: "true", reliable: "partial", who: "a letter from a rack-house", points: "site:dead_zone", text: "A letter from a rack-house to a family of {place}, {year}, polite as ever: 'Your mother's runtime has been suspended pending payment of 900 marks. She is not aware of the suspension. We can arrange a brief waking for a fee.' A note in the family's hand on the back: 'Remember what happened when they paused that man at {lead}. Pay it.'" },
    { depth: "sub", about: "sub:forked_warlords", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a mercenary captain, writing home", text: "A mercenary captain, writing home after a season in the border hills, {year}: 'Four banners on four hills, all with the same face. Each of the four generals sends envoys saying the other three are thieves. Each signs the letters with the same hand and the same spelling mistake. I am paid by all four. None of them has noticed.'" },
    { depth: "sub", about: "sub:grid_hunger", source: "library", bias: "propaganda", reliable: false, who: "the Power Board of {realm}", text: "Statement of the Power Board of {realm}, {year}, the 6th summer of rolling brownouts: 'The rack-halls of {realm} draw only surplus power. Brownouts in the lower quarters are the result of illegal taps by residents. The Board thanks residents for their patience, and notes that the racks hold their own honoured ancestors, who also prefer to stay cool.'" },
    { depth: "sub", about: "sub:quiet_choir", source: "temple", bias: "pious", reliable: "partial", who: "a Quiet Choir handbill", points: "sub:early_ascent", text: "Handbill of the Quiet Choir, handed out at the university gates of {place}, {year}: 'Join us early, while your mind is bright. Do not arrive old and frayed, like a guest who comes after the feast. Readings for those under 25 are free.' Underneath, a list of 12 clinics. Parents keep a vigil outside the one at {lead}." },
    { depth: "site", about: "site:first_rack", source: "ruin", bias: "true", reliable: true, who: "the inner face of the bunker door", text: "Burned into the inner face of the first rack's bunker door with a cutting tool, and read by {investigator} through a gap in {year}: 'Do not let them out until they remember being different from one another.' Beneath it, 40 names scratched in a column, and a forty-first, in the same hand as the warning, crossed out by its own writer." },
    { depth: "site", about: "site:ghost_town", source: "traveller", bias: "garbled", reliable: "partial", who: "two hikers who sheltered in the village", text: "Two hikers, writing to the regional paper after sheltering from rain in the empty village, {year}: 'We stayed one night in the empty house. In the morning the kettle had boiled, two places were set for us, and the radio wished us a happy birthday. Neither of us has a birthday in April. The house locked the door behind us. We have not been back.'" },
  ],
};
