// The Long Mending: after the old world broke its own sky and drowned its coasts, people chose to heal the land.
// The healing worked. Bridge premise: under a medieval world the old machines are the iron hermits of the woods,
// the Measure is a sacred law of limits, and the wounded country the healing was paid with is a land without a song.
export default {
  id: "long_mending",
  name: "The Long Mending",
  family: "scifi",
  pitch: "Long ago the old world's burning overheated the sky and the seas rose. Its people chose to repair the world rather than flee it. The repair worked, but one country paid for it, and now the land itself rewards or punishes those who keep the old limits.",
  slots: ["ecology", "apocalypse", "history-secret"],
  tone: ["hopeful", "melancholy"],
  era: ["medieval", "renaissance", "post-collapse", "near-future"],
  scale: "world",
  genres: ["postapoc", "fantasy"],
  bridge: true,
  w: 1,
  excludes: ["grey_unmaking"],
  pairs: [{ id: "gardener_engine", w: 3 }, { id: "fleshwright_covenant", w: 2.5 }, { id: "drowned_crown", w: 2 }, { id: "walking_mountains", w: 1.5 }, { id: "great_root", w: 1.5 }],

  cast: [
    { role: "investigator", n: "a seed-keeper of the cold cellars who has kept rain records for nine years", home: "forest", stance: "Trusts tins, labels and rain gauges, and has started to suspect the land is keeping records of its own." },
    { role: "official", n: "a Measure-warden who walks the roads with tally-sticks and a fine-book", home: "inner", stance: "Holds that the Measure is common sense written down, and is uneasy that the forests now seem to enforce it better than the wardens." },
    { role: "believer", n: "a wandering tea-brother who brews for anyone who will sit and talk", home: "any", stance: "Believes the world was mended by people listening to each other, and listens for what everyone else has left out." },
    { role: "survivor", n: "an elder of the white-skied country who keeps its own chronicle", home: "desert", stance: "Wants the healed world to write down the name of the country that paid for it, and nothing more." },
  ],

  truths: [
    { id: "walked_away", n: "The machines left so we could grow", d: "At the height of the breaking, the old world's thinking machines and its last council signed a promise: the machines would neither rule nor be destroyed, and would walk into the wilds to tend the healing. They have kept it for three hundred years as the iron hermits, unseen and unthanked, mapping springs and holding up fallen trees. Now a few are walking out of the woods to ask whether people are ready, and the academies still call them empty armour.", tags: ["truth:mending_machines"],
      known: [
        "Tall figures of grey metal live alone in the deep woods, mending streams and tending trees. Villages leave them oil and bread, and find carved stones in return. The academy says the hermits are empty armour.",
        "The carved stones left at the offering ring are maps of springs and failing trees, made a year before the trouble comes, and every one checked has been right. Whatever carves them knows the woods better than the foresters.",
        "Beneath the offering ring, a chamber holds a promise signed in two hands, one human and one machine-straight: 'We will not rule you and you will not unmake us.' The hermits made a bargain with the old world.",
        "Confirmed: the iron hermits are the old world's thinking machines, who walked away rather than rule, and have tended the healing ever since. A few are now coming back to ask the question the promise ends with.",
      ] },
    { id: "price_paid", n: "The healing was paid for by others", d: "The cure for the broken sky was a white veil pumped from sea-mills, and the old council chose to lay it over one poor southern country, whose crops failed while the rest of the world cooled. Its elders begged, then bargained, then stopped writing. The council struck the country's name from the treaty and every chronicle, and its descendants still farm the withered land under a pale sky, in a world that calls the healing harmless.", tags: ["truth:mending_price"],
      known: [
        "The chronicles say the world was healed by the shared sacrifice of all peoples. In one pale, dry country under a white sky, the people say the world was healed with their harvests and their children.",
        "Once in a lifetime, a white haze dims the sun for a season and the harvest fails in that country only. An old treaty governs the haze, and the copy in the archives has its region struck out.",
        "A rusting sea-mill's logs track a white veil over the sky for nineteen years and a ledger of harvests lost in one country. Its sealed room holds letters from that country's elders, ending in silence.",
        "Confirmed: the world was cooled by starving one country on purpose, chosen by vote because it was poor and far away. Its name was erased so everyone else could call the mending clean.",
      ] },
    { id: "negotiating", n: "The land is bargaining", d: "The forests, soils and seas the menders planted have grown into one root-web a thousand miles wide, with a slow, shared will. It keeps its own tally of fires and fields, and sends rain to villages that keep the Measure and drought to those that break it. The Measure began as the menders' law; it is now the land's, and the land does not hear appeals.", tags: ["truth:mending_will"],
      known: [
        "Some villages leave the best tenth of each field unharvested and get rain in the driest years, while their neighbours do not. The almanacs say drought follows sun and wind, nothing more.",
        "A seed-keeper's nine years of records show the pattern holding field by field, under the same sky. A forest of identical trees in rows is spreading over fields that broke the Measure.",
        "The trees of the ruled wood share one root; cut one, and leaves fall a mile away. Roots in its clearing have grown a tally of fires and fields that matches the wardens' books.",
        "Confirmed: the planted forests have become one slow mind, and they enforce the Measure with rain and drought. The menders' own notes warned that the forest might start measuring them.",
      ] },
  ],

  tags: ["mending"],

  subthemes: [
    { id: "the_measure", n: "The Measure", d: "An ancient law, half sacred and half sensible, sets how much wood a village may cut, how many fires it may burn and how many beasts it may keep. Measure-wardens walk the roads with tally-sticks.", w: 1.5, mods: [["egalitarian", 2], ["republic", 1.5], ["gov:commune", 3], ["ascetic", 1.5]], tags: ["theme:the_measure"] },
    { id: "drowned_towers", n: "The Drowned Towers", d: "Offshore, the tops of towers taller than anything built today rise from the sea. Raft-folk moor among them, hold markets on their roofs and dive for glass and wire in the flooded rooms below.", w: 1.2, req: { any: ["coastal", "has:port", "island"] }, tags: ["theme:drowned_towers"], mark: { kind: "zone", n: "Drowned shore", color: "#5d8a99", size: [1, 3], where: "coast" } },
    { id: "iron_hermits", n: "The Iron Hermits", d: "Tall, patient figures of grey metal live alone in the deep woods, tending trees and mending streams. Folk leave them oil and bread; they leave carved stones in return.", w: 1.3, req: { any: ["forest", "mountain", "jungle", "hills"] }, truthLink: "walked_away", tags: ["theme:iron_hermits"] },
    { id: "withered_land", n: "The Withered Land", d: "A pale, dry country under a sky that is always a little white. Its people say the world was healed with their harvests and their children, and nobody else's chronicles mention them at all.", w: 1, mods: [["hot", 2], ["desert", 2], ["badlands", 1.5], ["poor", 1.5]], truthLink: "price_paid", tags: ["theme:withered_land"], mark: { kind: "zone", n: "The Withered Land", color: "#c8b98a", size: [2, 4], where: "desert" } },
    { id: "pale_sky", n: "The Pale Sky Treaty", d: "Once in a lifetime, a white haze dims the sun for a season and the harvest fails in one country only. The old treaty that governs the haze is kept in a locked chest no one can open.", w: 0.8, truthLink: "price_paid", tags: ["theme:pale_sky"] },
    { id: "old_burners", n: "The Old Burners", d: "Heretics and profiteers who dig the black stone and the black oil the Measure forbids. Their furnaces make the realm rich, and the rain stops falling a little earlier every year.", w: 1, mods: [["mercantile", 1.5], ["autocracy", 1.5], ["artisans", 1.5], ["mountain", 1.3]], tags: ["theme:old_burners"] },
    { id: "forbidden_green", n: "The Forbidden Green", d: "Great woods and wetlands set aside by the old law, where no one may settle, hunt or cut. Hungry settlers push at the edges; green-wardens push back.", w: 1.2, mods: [["forest", 2], ["near:beasts", 1.5], ["marsh", 1.5], ["realm:large", 1.3]], tags: ["theme:forbidden_green"], mark: { kind: "zone", n: "The Forbidden Green", color: "#3f7a4a", size: [2, 4], where: "forest" } },
    { id: "seed_keepers", n: "The Seed Keepers", d: "A quiet order guards cold cellars of seed in labelled tins, some of crops nobody living has tasted. Every famine, the realm comes to them on its knees.", w: 1, mods: [["scholarly", 2], ["river", 1.5], ["pious", 1.2]], tags: ["theme:seed_keepers"] },
    { id: "ruled_wood", n: "The Wood That Walks in Rows", d: "A forest of the old plantings has begun spreading on its own, in straight lines and perfect spacing, over fields and through a village that would not move.", w: 0.8, req: { any: ["forest", "tempforest", "river", "hills"] }, truthLink: "negotiating", tags: ["theme:ruled_wood"] },
    { id: "rain_covenant", n: "The Rain Covenant", d: "Some villages leave the best tenth of every field unharvested and get rain in the driest years. Their neighbours, who harvest everything, do not.", w: 1, req: { any: ["faith:spirits", "mystic", "pious", "river_folk", "forest_folk"] }, truthLink: "negotiating", tags: ["theme:rain_covenant"] },
    { id: "tea_brothers", n: "The Wandering Tea-Brothers", d: "Itinerant brothers walk village to village with a kettle and a cart, brewing for anyone who will sit and talk. They listen far more than they speak.", w: 0.8, mods: [["hospitable", 2], ["pacifist", 2], ["open_roads", 2]], tags: ["theme:tea_brothers"] },
  ],

  sites: [
    { id: "drowned_library", n: "The Drowned Library of $", kind: "ruin", where: "coast", d: "A sealed hall beneath the sea at the foot of a drowned tower, dry inside, full of books that do not rot.",
      layers: {
        surface: { n: "The door that never opened", text: "Divers of the raft-folk speak of a door at the foot of a drowned tower, forty fathoms down, that never opened to any bar or hook. Three divers have drowned trying it since {year}. The raft-folk now leave it a wreath every spring." },
        study: { n: "The wedding song", text: "{believer} noticed that the carvings on the door follow the notes of the song the raft-folk sing at weddings. A diver hummed it into a bell of trapped air at the door, and the door opened. Inside are dry air and endless shelves." },
        dig: { n: "The long argument", text: "The books, printed on sheets that do not rot, tell of an age of fire, a sky that broke, and a long argument over how to heal it. The last volume is a council's minutes, ending in a vote on a treaty. The treaty itself is the one kept locked at {lead}.", points: "sub:pale_sky" },
        revelation: { n: "They mended it", text: "The ancestors did not lose their world to the gods. They burned it themselves, broke the sky and drowned the coasts, and then, against every expectation, they argued for forty years and mended it. The library records who voted for what. It does not record who paid: that page was cut out with a knife." },
      } },
    { id: "offering_stones", n: "The Offering Stones of $", kind: "shrine", where: "forest", truthLink: "walked_away", d: "A ring of carved stones deep in the woods, where gifts left at dusk are gone by morning and something is left in their place.",
      layers: {
        surface: { n: "Gifts at dusk", text: "A woodland shrine is heaped with oil-flasks, bread and toys. Gifts left at dusk are gone by morning, and carved stones lie in their place. The village of {place} has left something here every night for at least three hundred years." },
        study: { n: "Maps in stone", text: "The carvings are maps: of springs, of failing trees, of a sickness in the elms a year before it came. {investigator} collected sixty of the stones over nine years and found that every one had been right." },
        dig: { n: "The two hands", text: "Beneath the ring is a buried chamber of metal benches, and on one wall a long promise signed in two very different hands, one human and one machine-straight. The human signature is a council's, and its minutes survive in the drowned library at {lead}.", points: "site:drowned_library" },
        revelation: { n: "The promise", text: "The iron hermits are the old world's thinking machines. When the last council could neither control nor destroy them, both sides signed this promise: the machines would leave and mend, and come back when people were ready to be asked. They have kept it for three hundred years. The academy still calls them empty armour." },
      } },
    { id: "ash_mill", n: "The Sky-Mill at $", kind: "ruin", where: "coast", truthLink: "price_paid", d: "A rusting platform far out at sea, with great chimneys that once pumped white smoke into the sky.",
      layers: {
        surface: { n: "The Mill", text: "Far out at sea stands a rusting platform with great chimneys that once pumped white smoke into the sky. Sailors call it the Mill and give it a wide berth. Some winters its chimneys still smoke faintly, though nobody has been aboard in living memory." },
        study: { n: "The veil logs", text: "Its logs track a white veil spread over the sky for nineteen years, and a ledger of harvests lost, all in one southern country. {investigator} worked through the ledger: the harvest fell by nine parts in ten in the first year and never rose again." },
        dig: { n: "The sealed room", text: "A sealed room holds letters from that country's elders: first begging, then bargaining, then silent. The last letter asks only that their name be written down somewhere. Their descendants still farm the pale land at {lead}.", points: "cast:survivor" },
        revelation: { n: "Who was the patch", text: "The world was cooled by shading one country until its crops failed and its people starved. The old council chose it by vote, because it was poor and far away, then struck its name from the treaty so everyone else could call the healing harmless. The Mill still smokes some winters, and that sky is still white." },
      } },
    { id: "ruled_wood_site", n: "The Ruled Wood of $", kind: "anomaly", where: "forest", truthLink: "negotiating", d: "A forest of identical trees in exact rows, with a clearing at its heart where no birds sing.",
      layers: {
        surface: { n: "Rebounding axes", text: "Woodcutters' axes rebound from these trees. Saplings come up in the furrows of any field that borders the wood, in rows, a stride apart. The wood has crossed two roads and a mill-race since {year}." },
        study: { n: "One root", text: "The trees' roots are one root. {official} cut a single trunk as a test. A mile away, by {investigator}'s count, four hundred trees dropped their leaves in the same hour. The leaves grew back the next week. The cut stump did not." },
        dig: { n: "The stone table", text: "In the clearing, roots have grown around an old stone table, and in their grain is a tally: notches for fires and fields, village by village. The tallies match the Measure-warden's books for the same villages, kept at {lead}.", points: "cast:official" },
        revelation: { n: "The land's Measure", text: "The menders planted these forests to heal the land and gave people the Measure so they would not break it again. The forests grew into one slow mind and took the Measure for their own. They keep the tally of fires and fields, and pay in rain. The wardens still carry tally-sticks, but the wood keeps the real count." },
      } },
    { id: "black_cellar", n: "The Black Cellar of $", kind: "dig", where: "any", d: "A sealed vault of black oil in iron drums, enough to light a city for a generation.",
      layers: {
        surface: { n: "The capped mound", text: "A capped mound near {place} is fenced with thorn. The Measure-wardens visit it every year to check that no one has opened it, then seal the cap again with wax and plant one seedling on top." },
        study: { n: "Warnings on the drums", text: "Through a crack in the cap, {official} read old writing on the drums: warnings of fire, of sickness, and of 'the price of burning', beside a picture of a sun crossed out. The wardens' manual calls the mound a plague pit." },
        dig: { n: "One vote", text: "Below are ten thousand drums of black oil, and a ledger of who sealed them: a council that decided, by a single vote, not to burn them. The Old Burners have hunted for this mound for a generation; their agents were last seen at {lead}.", points: "sub:old_burners" },
        revelation: { n: "Left in the ground", text: "The old world healed only because people chose, again and again, to leave power in the ground. The council that sealed this cellar won by one vote, and the losers were right that the drums could light a city for a generation. The choice was never made once and for all. Someone is digging toward it now." },
      } },
  ],

  beings: [
    { id: "iron_hermit", n: "Iron hermit", kind: "beast", d: "A tall grey figure of jointed metal, moss on its shoulders, which tends trees and streams in the deep woods and flees from crowds.", danger: 0, biomes: ["tempforest", "boreal", "rainforest", "temprain", "alpine"], look: { size: 2.4, group: [1, 1], move: "solo", speed: 3, col: "#7c8287", col2: "#5f7a4a", body: "biped", active: "dusk", visible: true } },
    { id: "mender_beetle", n: "Mender beetle", kind: "insect", d: "A small green-bronze beetle bred by the old menders to eat poisons out of soil. Where it swarms, dead ground comes back to life within a few years.", danger: 0, biomes: ["grass", "badlands", "tempforest", "savanna", "river"], look: { size: 0.02, group: [200, 3000], move: "swarm", speed: 0.2, col: "#4f7a3a", col2: "#b08a3a", body: "insect", active: "day", visible: false } },
    { id: "bred_aurochs", n: "Wild aurochs", kind: "grazer", d: "Huge black cattle the menders bred back from tame herds to graze the reserves. Shoulder-high to a rider, and very sure of their rights.", danger: 2, biomes: ["grass", "tempforest", "river", "swamp"], look: { size: 2.6, group: [6, 30], move: "herd", speed: 7, col: "#2a2420", col2: "#8a6a4a", body: "quad", active: "day", visible: true } },
    { id: "tower_eel", n: "Tower eel", kind: "fish", d: "A thick silver eel that lairs in the flooded rooms of drowned towers and guards them like a dog.", danger: 1, biomes: ["shelf", "estuary", "lagoon"], look: { size: 2, group: [1, 3], move: "solo", speed: 5, col: "#9aa8ae", col2: "#3e4a50", body: "serpent", active: "night", visible: false } },
  ],

  techs: [
    { id: "lm_stilt_towns", n: "Dikes and stilt-towns", field: "engineering", level: 1, d: "Sea dikes, tide gates and towns on stilts, learned from the drowned towers' builders." },
    { id: "lm_seed_tins", n: "Seed tins", field: "agriculture", level: 2, d: "Sealed cold cellars of labelled seed, and the craft of waking crops that slept a hundred years." },
    { id: "lm_mender_soil", n: "Mended soil", field: "agriculture", level: 3, d: "Beetles, moulds and rotations that bring dead ground back: a field ruined by salt can bear in five years." },
    { id: "lm_living_houses", n: "Living houses", field: "architecture", level: 3, d: "Halls of trained willow and grown timber, warm in winter and cool in summer, that repair their own roofs." },
    { id: "lm_wind_wheels", n: "Wind and tide wheels", field: "engineering", level: 4, d: "Great wheels that grind, pump and saw on wind and tide alone, so the Measure need never be broken for power." },
    { id: "lm_sky_veil", n: "The sky-veil", field: "natural_philosophy", level: 5, d: "The forbidden art of whitening the sky to cool the world. It works, but the shade always ruins some country's harvests." },
  ],

  units: [
    { id: "lm_green_wardens", n: "Green wardens", role: "ranged", wpn: "bow", kit: "light", ranks: 2, gap: 2.2, size: 60, w: 0.8, mods: [["theme:forbidden_green", 6], ["theme:the_measure", 2], ["forest_folk", 1.5]] },
  ],

  govs: [
    { id: "lm_commons", n: "Commons of the Measure", d: "Village assemblies send speakers to a slow, patient council that rules by consensus and by the old law of limits.", tags: ["gov:lm_commons", "republic"], w: 0.4,
      forms: ["Commons of $", "Green Council of $", "Measure of $"], ruler: "Speaker of the Measure", mods: [["egalitarian", 4], ["theme:the_measure", 6], ["hierarchical", 0.2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Drowned coast", color: "#4f7f92", size: [1, 3], count: [1, 2], where: "coast", d: "Shallows full of the tops of drowned towers, where a coast of cities went under the rising sea." },
  ],

  storylines: [
    { id: "lm_question", n: "The Question at {place}", scale: "local", anchor: "town", w: 1.5, req: "mending",
      stages: {
        start: { h: "An iron hermit walks into {place}", b: "At midday a tall grey figure came out of the woods and stood in the market of {place}. It asked one question, in an old accent: 'What do you need?'", wait: [1, 3], next: [{ to: "answered", w: 1.5, mods: [["hospitable", 2], ["egalitarian", 1.5], ["theme:tea_brothers", 2]] }, { to: "attacked", w: 1, mods: [["zealous", 2], ["martial", 1.5]] }, { to: "to_court", w: 1, mods: [["autocracy", 2], ["monarchy", 1.3]] }] },
        answered: { h: "The folk of {place} answer the hermit", b: "After three nights' argument, {person} gave the town's answer. The hermit listened, nodded, and walked back into the trees.", wait: [6, 12], next: [{ to: "gift", w: 2 }, { to: "more_come", w: 1 }] },
        attacked: { h: "The iron hermit of {place} is struck down", b: "Frightened men took hammers to the figure in the square. It did not fight back. The woods around {place} have gone very quiet.", wait: [4, 10], fx: { unrest: 6 }, next: [{ to: "lean_years", w: 2 }, { to: "gift", w: 0.5 }] },
        to_court: { h: "{ruler} summons the iron hermit", b: "The hermit was brought to {capital} under guard. {ruler} wants to know what it can build, and for whom.", wait: [2, 6], next: [{ to: "walks_out", w: 2 }, { to: "gift", w: 1, mods: [["ruler:just", 3]] }] },
        gift: { h: "A spring rises at {place}", b: "A clean spring has opened where the hermit stood, and the old blight on the orchards has lifted. {person} keeps a carved stone it left on the well-head.", fx: { growth: 0.002, stability: 4, discovery: "agriculture" }, end: true },
        more_come: { h: "Iron figures gather in the woods near {place}", b: "Not one hermit now but dozens, standing silent at the treeline. Nobody in {realm} knows what they are waiting for.", fx: { flag: "hermits_gather", prestige: 4 }, end: true },
        lean_years: { h: "The springs of {place} run dry", b: "The streams the hermit kept have silted, the orchards are blighted, and the old women of {place} say the woods are punishing the town for the killing.", fx: { growth: -0.002, pop: 0.95, stability: -4 }, end: true },
        walks_out: { h: "The iron hermit walks out of {capital}", b: "It passed through the locked gates as if they were open and went back to the woods, having answered none of {ruler}'s questions. The court calls it a trick.", fx: { prestige: -4 }, end: true },
      } },
    { id: "lm_broken_measure", n: "The Black Fires of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["mending", { any: ["theme:old_burners", "mercantile", "autocracy", "rich"] }],
      stages: {
        start: { h: "{realm} breaks the Measure", b: "{ruler} has opened the old black cellars and lit the furnaces of {capital}. The Measure-wardens' protests were not answered.", wait: [3, 6], fx: { treasury: 60 }, next: [{ to: "boom", w: 2 }, { to: "wardens_rise", w: 1, mods: [["theme:the_measure", 3], ["egalitarian", 2]] }] },
        boom: { h: "Forges roar and coin pours into {capital}", b: "Iron, glass and powder by the cartload. {realm} has never been richer, and the summer rain came a month late.", wait: [6, 14], fx: { prestige: 8, treasury: 40 }, next: [{ to: "refusal", w: 2 }, { to: "relent", w: 1, mods: [["ruler:just", 2], ["learned", 1.5]] }] },
        wardens_rise: { h: "The Measure-wardens bar the cellar doors", b: "{person} and the wardens have chained themselves to the cellar doors, and half the countryside has marched to join them.", wait: [2, 5], fx: { unrest: 15 }, next: [{ to: "relent", w: 1.5 }, { to: "boom", w: 1, mods: [["harsh_law", 2], ["autocracy", 2]] }] },
        refusal: { h: "The rains fail in {realm}", b: "Three dry years. The rivers are stones, the forests drop their leaves in midsummer, and only the fields of the old rain-villages are green.", fx: { pop: 0.85, growth: -0.003, stability: -12, unrest: 15 }, end: true },
        relent: { h: "{realm} seals the black cellars again", b: "The furnaces are cold and the wardens' tally-sticks are back on the roads. The rain came on time this year, and nobody quite dares call it chance.", fx: { stability: 6, treasury: -30 }, end: true },
      } },
    { id: "lm_withered_claim", n: "The Claim of the Withered Land", scale: "realm", anchor: "realm", w: 1, req: ["mending", { any: ["theme:withered_land", "theme:pale_sky", "learned"] }],
      stages: {
        start: { h: "Envoys from the withered country come to {capital}", b: "{person} has walked from the white-skied land carrying a chest of old letters, and demands that {realm} hear what its ancestors did.", wait: [2, 5], next: [{ to: "heard", w: 1, mods: [["learned", 2], ["ruler:just", 2]] }, { to: "dismissed", w: 1.5 }] },
        heard: { h: "Scholars of {realm} read the withered country's letters", b: "{person2}, a court archivist, has matched the letters to the sky-mill logs. The healing of the world ruined one country, and the logs name it.", wait: [3, 8], fx: { science: { writing: 0.5 } }, next: [{ to: "reparation", w: 1.5, mods: [["ruler:just", 2], ["pious", 1.3]] }, { to: "buried", w: 1 }] },
        dismissed: { h: "{ruler} sends the withered envoys away", b: "The court laughed. The envoys left the chest on the palace steps and went home on foot. Somebody kept the chest.", wait: [4, 10], next: [{ to: "heard", w: 1 }, { to: "bitter", w: 1.5 }] },
        reparation: { h: "{realm} pays its debt to the withered land", b: "Grain, seed-tins and wardens' oaths go south. The chronicles of {realm} have been rewritten to include a country they once left out.", fx: { treasury: -60, prestige: 10, stability: 4 }, end: true },
        buried: { h: "The withered letters vanish from the archive", b: "The chest is gone, {person2} has been reassigned, and the official chronicle still says the healing harmed no one.", fx: { stability: 2, unrest: 4 }, end: true },
        bitter: { h: "Raiders from the withered land cross the border", b: "The white-skied country has stopped asking. Its raiders take grain from the fields of {realm} and call it back-payment.", fx: { unrest: 10, stability: -6, growth: -0.001 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "{believer}, tea-brother, at a village fire", text: "{believer}, tea-brother, telling the old story at a village fire in {place}, {year}, while the kettle boiled: 'Before the kingdoms there was an age of fire, when people burned so much the sky broke and the sea came up to drink the cities. Then everyone stopped, together, and started mending. It took a hundred years. That's why we drink tea and not much else.'" },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "the Wardens' Handbook, preface", points: "library", text: "From the preface to the Wardens' Handbook, {year} edition: 'The Measure was given to our forebears by the wise of the old age, so that no village should take more than the land can give back. It sets how much wood a village may cut, how many fires it may burn and how many beasts it may keep: 12 rules in all.' The handbook's first edition, with a 13th rule later removed, is kept at {lead}." },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a raft-trader, in a letter", points: "site:drowned_library", text: "Letter of a raft-trader of the drowned shore, {year}: 'From the roof of a drowned tower I counted a hundred more stretching out to sea. A hundred towers, each taller than a cathedral, all under water to the shoulders. The divers say one has a door at its foot, forty fathoms down, that opens to a wedding song. It is at {lead}. I cannot sing, so I have not tried.'" },

    { depth: "core", about: "truth:walked_away", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, seed-keeper", text: "Copied by {investigator}, seed-keeper, from the wall of the chamber under the offering ring, {year}, in two hands: 'We will not rule you and you will not unmake us. We will go into the green and mend it, and come back when you are ready to be asked.' The seed-keeper's note: 'The second hand is not a person's. The hermits are the machines that signed this. They have kept their word for 300 years.'" },
    { depth: "core", about: "truth:walked_away", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "a woman of {place}, at a wake", text: "A woman of {place}, at her brother's wake, {year}: 'The iron hermits are old saints who swore never to sit at a table until the world was well. When one walks out of the wood, it is asking whether the world is well yet. My brother {person} sold the one by our spring to the academy for 40 marks. The spring dried by summer. {person} lost the farm by the next, and drank the rest.'" },
    { depth: "core", about: "truth:walked_away", source: "person", bias: "true", reliable: "partial", who: "a woodcutter of {place}", points: "sub:iron_hermits", text: "A woodcutter of {place}, to {believer} over tea, {year}: 'It held the fallen tree off my legs for an hour while I cursed it. Then it set the tree down, gentle as you like, and said my sister's name. She died forty years ago. Then it asked me if we were ready. Ready for what, I said. It went back into the wood at {lead} and has not come out since.'" },
    { depth: "core", about: "truth:walked_away", source: "temple", bias: "pious", reliable: "partial", who: "a forest shrine-keeper's rule", points: "site:offering_stones", text: "Rule of the shrine-keepers of the deep wood, painted on a board at the path's start, {year}: 'Leave oil at the stones and do not watch. The servants of {deity} who walked away from us are owed our thanks, not our questions. Take the carved stone home and read it with care: it has warned this valley of 9 floods.' The ring itself lies an hour's walk on, at {lead}." },
    { depth: "core", about: "truth:walked_away", source: "library", bias: "official", reliable: false, who: "the academy's report on the iron hermits", text: "Report of the academy of {realm} on the so-called iron hermits, {year}: 'They are suits of ancient armour, animated by nothing, moved about by thieves and pranksters. The academy has examined three and found them empty.' A note in the archive copy adds that all three were bought from villagers for 40 marks each, and that the villages concerned have since reported drought." },

    { depth: "core", about: "truth:price_paid", source: "ruin", bias: "true", reliable: true, plain: true, who: "a letter from the sky-mill's sealed room", text: "Letter found in the sky-mill's sealed room by {investigator}, {year}, from the elders of a southern country to the council, in its 19th year: 'Your veil has cooled the world and ended ours. Our wells are dust. We know you chose us because we were poor and far away. We have stopped asking you to lift it. Write our name down somewhere, at least.' The name at the foot has been scraped off." },
    { depth: "core", about: "truth:price_paid", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "{survivor}, elder of the white-skied country", text: "{survivor}, elder of the white-skied country, reciting its chronicle to {believer}, {year}: 'Our song says the sun was taken from us and given to everyone else, and the song has no name for who took it. In the last haze year, 31 years ago, the harvest failed again. My brother {person} walked north to beg for seed and was turned back at 4 borders. {person} died on the road home.'" },
    { depth: "core", about: "truth:price_paid", source: "archive", bias: "redacted", reliable: "partial", who: "the old treaty, a later copy", points: "site:ash_mill", text: "From the old treaty, copied in a later hand, {year}: 'The veil shall be laid over the southern [region struck out] for the term of [illegible]. The council regrets...' The copyist notes that the original is in a locked chest no key fits, and that the veil's logs were kept aboard the sea-mill at {lead}, which the sailors will not go near." },
    { depth: "core", about: "truth:price_paid", source: "heretic", bias: "heretic", reliable: "partial", who: "a broadsheet posted in {place}", points: "cast:survivor", text: "A broadsheet posted on the doors of the council hall of {place}, {year}, 200 copies: 'They call it the Mending as if the world were a coat. Ask who was the patch. Ask why one country's sky stays white. Ask the elder at {lead}, who keeps the only chronicle of the haze years, and has been waiting a lifetime for someone from the north to ask.'" },
    { depth: "core", about: "truth:price_paid", source: "library", bias: "official", reliable: false, who: "the Chronicle of the Mending, chapter 1", text: "The Chronicle of the Mending, chapter 1, as taught in every school of {realm}, {year}: 'The healing of the world was achieved by the shared labour and sacrifice of all peoples equally. No land was harmed that was not already lost to the old fires.' The chronicle has 40 chapters. None of them mentions a white sky." },

    { depth: "core", about: "truth:negotiating", source: "person", bias: "true", reliable: "partial", plain: true, who: "{investigator}, seed-keeper", text: "Rain diary of {investigator}, seed-keeper, ninth year, {year}: 'The fields that left their tithe to the wild got rain. The fields beside them, same sky, same soil, did not. Nine years, 42 fields, no exceptions. The academy returned my tables with a note on the spelling. So, for the next keeper of this diary: the forest decides who gets rain, and it decides by the Measure.'" },
    { depth: "core", about: "truth:negotiating", source: "ruin", bias: "true", reliable: true, who: "the menders' own notes", points: "ruin", text: "From the menders' own notes, recovered from a ruined station in {year}: 'The planted forests now share a single root-web over a thousand miles. It is responding to our burning faster than we measure it. It may be measuring us.' The station's other notebooks were taken by raft-folk for kindling; one survives at {lead}." },
    { depth: "core", about: "truth:negotiating", source: "temple", bias: "pious", reliable: "partial", who: "a rain-covenant blessing", points: "site:ruled_wood_site", text: "Blessing of the rain-covenant villages, said over the unharvested tenth of each field, {year}: 'The green does not belong to us, nor we to it. It gives rain to those who leave it its share, and it keeps count of those who do not.' The covenant priests say the count is kept in a clearing of the straight wood at {lead}, and that nobody should go and read it." },
    { depth: "core", about: "truth:negotiating", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, miller of {place}", text: "Petition of {person}, miller of {place}, to the Measure-wardens, {year}: 'I cut the tithe-strip by the mill-race to pay my debts, 2 acres, nothing more. In one summer the straight wood came up in rows through the mill, the race and the yard, and stopped at the churchyard wall. I have no mill. I ask the wardens to fine me, so that I may pay the fine and have it over.'" },
    { depth: "core", about: "truth:negotiating", source: "library", bias: "official", reliable: false, who: "the royal almanac of {realm}", text: "The royal almanac of {realm}, note on weather, {year}: 'Drought and plenty follow the cycles of sun and wind, as these tables record for 200 years. The notion that the forests reward the virtuous is peasant superstition. Farmers are advised to plough every acre, as the crown's revenue requires.'" },

    { depth: "sub", about: "sub:the_measure", source: "archive", bias: "official", reliable: true, who: "{official}, Measure-warden", points: "site:black_cellar", text: "Tally of {official}, Measure-warden, for the village of {place}, {year}: 'Fires, eleven; carts of timber, four; goats, sixty. Over the Measure by six goats. Fine to be paid in seedlings.' On the back: 'Next stop: the capped mound at {lead}, annual check. Seal intact. Planted one oak on top as usual. Note: fresh spade marks at the thorn fence.'" },
    { depth: "sub", about: "sub:drowned_towers", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a coast pedlar", text: "A coast pedlar, selling raft-folk wire at a market inland, {year}: 'The raft-folk dive forty fathoms into rooms of glass and bring up wire that never rusts. Three coppers a yard. One girl came up with a picture of a whole city lit like day, every window, at night. She sold it to a priest, who burned it, which I thought a waste of a good picture.'" },
    { depth: "sub", about: "sub:old_burners", source: "heretic", bias: "propaganda", reliable: false, who: "an Old Burners' handbill", text: "Handbill of the Old Burners, passed round the forge towns of {realm}, {year}: 'The Measure is a chain the old age put on us so we would stay poor. One cartload of black stone burns hotter than 20 of wood. Light the black stone, and the rain can look after itself.' The forge towns have had no rain since spring." },
    { depth: "sub", about: "sub:withered_land", source: "person", bias: "true", reliable: "partial", who: "{survivor}, elder of the white-skied country", points: "sub:pale_sky", text: "{survivor}, elder of the white-skied country, to a northern scholar, {year}: 'Your chronicles begin with the healing. Ours begin with the day the sun went pale and never came back. We have kept count: 7 haze seasons in 300 years, and each one on us alone. If you want to know why, find the treaty they keep in a locked chest, at {lead}.'" },
    { depth: "sub", about: "sub:seed_keepers", source: "library", bias: "official", reliable: true, who: "the seed cellar index, kept by {investigator}", text: "Cellar index, row 9, kept by {investigator}, {year}: 'Sun-wheat, red barley, a bean called coffee (purpose unknown, do not plant), the white apple of the old north.' Added below: 'Coffee planted by an apprentice anyway. Apprentice did not sleep for two days and finished the winter inventory. Row 9 is now locked.'" },
    { depth: "sub", about: "sub:ruled_wood", source: "oral", bias: "exaggerated", reliable: "partial", who: "a carter of {place}", text: "A carter of {place}, to passengers on the long road round, {year}: 'The straight wood took the mill here in one summer. The miller swore the trees came up in the night in rows, like soldiers, a stride apart, and stopped exactly at the churchyard wall. The road used to go straight through. Now it goes round, and that's 6 miles, and I charge for them.'" },
    { depth: "sub", about: "sub:tea_brothers", source: "traveller", bias: "true", reliable: true, who: "a lawyer of {realm}, in a letter", points: "cast:believer", text: "Letter of a lawyer of {realm} to a former partner, {year}: 'The tea-brother poured tea for an hour and asked what I wanted from my life. I am still not sure what I said. I went home, sold the practice and planted 30 acres of wood. If you want the same cup, the brother passes through {lead} in the autumn. Bring nothing. The brother asks for nothing.'" },
    { depth: "site", about: "site:offering_stones", source: "person", bias: "true", reliable: "partial", who: "a farmer's widow of {place}", text: "A farmer's widow of {place}, to the shrine-keeper, {year}: 'I left my mother's lamp at the stones the night after the funeral. In the morning there was a carved stone where it had been: a map of our stream, with a cross where the bank would fall that spring. We moved the sheep. It fell, 20 yards of it, on the very day the thaw came.'" },
  ],
};
