// The Luminous Aether: a shining medium in the sky powers a gilded age of brass and airships, and the bill is coming due.
export default {
  id: "luminous_aether",
  name: "The Luminous Aether",
  family: "scifi",
  pitch: "A glowing energy called aether fills the upper sky. Those who learned to tap it built a gilded age of brass machines and airships, and nobody in power wants to ask what it really costs or how long it will last.",
  slots: ["power-source", "economy-resource"],
  tone: ["wonder", "satirical"],
  era: ["renaissance", "industrial", "modern"],
  scale: "world",
  genres: ["flintlock"],
  bridge: false,
  w: 1,
  excludes: [],
  pairs: [{ id: "unending_mobilization", w: 3 }, { id: "glyphwright_science", w: 2 }, { id: "charter_lords", w: 2 }, { id: "long_sight", w: 1.5 }],

  // the hidden truth: a world picks one
  truths: [
    { id: "finite", n: "The aether is running out", d: "The aether is leftover energy from something that burned out long ago, and it does not renew. The great wells are thinning every year, and the barons who own them have diluted the crystal and forged the yield ledgers for a generation to hold the price. The barons have been building their new houses with chimneys.", tags: ["truth:aether_finite"],
      known: [
        "Lamps in several capitals dim each winter, and the Board of Light calls it maintenance. Retired assayers grumble that the wells are weaker at the bottom than the top. Nobody official has said the supply is shrinking.",
        "{investigator}'s private readings show the Fourth Well down by a third in three years, and a baron's letter orders the retail grade diluted. The First Well was stamped 'exhausted' eleven years after its first strike, though the public was told it retired with honour.",
        "Every capped well examined so far ends the same way: grey, hollow seams, like burned-out coal. The aether does not grow back. The barons' sealed yield books count how many wells are left, and they have been forged for a generation.",
      ] },
    { id: "alive", n: "The aether is alive", d: "The aether is the outer flesh of a huge, slow creature that lies across the upper sky, and every engine that taps it wounds it. Mine foremen reported warm, bleeding walls for decades, and the companies closed the galleries and sacked the foremen. The storms, the sky-sickness and the pale shapes the miners call ghosts are its pain, and it has started to push back.", tags: ["truth:aether_alive"],
      known: [
        "Miners report pale shapes in the deep galleries, and engine crews go grey at the fingertips. The Board's physicians call it crystal dust and gin. The Unplugged say the glow is taken from someone.",
        "The ghosts appear only when the city engines run hardest, and they always move away from the drills. A sealed gallery's log records walls that bled light and a drill bit that came back warm. The companies closed it rather than explain it.",
        "Below a certain depth the Ghost Gallery walls are soft, warm and pull back from a lamp. The aether is not a mineral. It is living tissue, and the sky-sickness spreads fastest in the towns that burn the most of it.",
      ] },
    { id: "broadcast", n: "The aether is a broadcast", d: "The aether is a power signal sent from an ancient floating city above the clouds, and every engine is a receiver. Whoever controls that city switched the power off once, for nine days, and the Board of Light recorded the cause as a magnetic storm because it had no better answer. Nobody below knows who is up there, or what would make them do it again.", tags: ["truth:aether_broadcast"],
      known: [
        "In the Dark Year every engine in the world failed for nine days and started again at the same hour. The Board blamed a magnetic storm. Its own sealed annals say the cause 'is not to be recorded'.",
        "The thinking engines print coordinates nobody asked for, and the positions move like a ship far above the clouds. Under the standing storm on the high moor stands a brass mast older than any foundry, still humming.",
        "The storm over the moor is a relay. A signal from a city in the clouds passes down through the mast, and every aether engine picks it up. The power is not mined. It is sent, and whoever sends it can stop.",
      ] },
  ],

  cast: [
    { role: "investigator", n: "an assayer of the Board of Light's testing house, paid to grade crystal", home: "mountain", stance: "Wants the yield figures to be honest, and has started keeping a second ledger of private readings." },
    { role: "official", n: "the Deputy Commissioner of the Board of Light, who signs the lamp schedules", home: "capital", stance: "Believes panic would do more harm than any shortage, and that the barons will find new wells in time." },
    { role: "believer", n: "a lay preacher of the Unplugged, the candle-folk who smash aether engines", home: "forest", stance: "Holds that the glow is taken from a living thing, and that every lamp lit with it is a wound." },
    { role: "survivor", n: "a crystal miner pulled out of a gallery collapse after four days", home: "mountain", stance: "Wants the company to pay the widows, and will not go below the ninth gallery again." },
  ],

  tags: ["aether"],

  subthemes: [
    { id: "floating_city", n: "The Hanging City", d: "A city of the rich floats above the clouds on aether keels. The labourers who keep it aloft live in the shadow it casts, and are not allowed up.", w: 1.4, req: { any: ["hierarchical", "autocracy", "realm:large", "realm:vast", "has:city"] }, tags: ["theme:hanging_city"], mark: { kind: "zone", n: "The Shadowed Wards", color: "#4a4a5a", size: [1, 3], where: "capital" } },
    { id: "mine_revolt", n: "The Crystal Pits", d: "Deep mines of glowing crystal where the air tastes of copper and the miners' teeth glow at night. A collapse has buried two hundred, and the pit-folk have stopped working.", w: 1.3, req: { any: ["mountain", "hills", "mountain_folk"] }, tags: ["theme:crystal_pits"], mark: { kind: "zone", n: "Crystal pits", color: "#6a8ab0", size: [1, 3], where: "mountain" } },
    { id: "patent_war", n: "The Patent Office", d: "Every invention must be registered, and most registered inventions vanish into the Office's vaults. Inventors duel in court and sometimes in alleys.", w: 1.2, req: { any: ["scholarly", "artisans", "guilds", "urbane", "academies"] }, tags: ["theme:patent_war"] },
    { id: "clockwork_mind", n: "The Thinking Engine", d: "A cabinet of brass gears and aether-glass has begun answering questions nobody asked it. Its builder is missing, and three ministries claim it.", w: 0.8, req: { any: ["scholarly", "academies", "learned"] }, truthLink: "broadcast", tags: ["theme:thinking_engine"] },
    { id: "sky_sickness", n: "The Sky-Sickness", d: "Engine-crews and mill-hands go grey, then translucent at the fingertips, then dream of falling upward. Physicians blame bad gin.", w: 1.1, truthLink: "alive", tags: ["theme:sky_sickness"] },
    { id: "sky_pirates", n: "The Cloud Corsairs", d: "Rogue airships prey on the crystal convoys and sell stolen aether cheap in the ports. Half the poor quarter's lamps are lit with it.", w: 1.1, req: { any: ["coastal", "has:port", "mercenaries", "mercantile"] }, tags: ["theme:corsairs"] },
    { id: "expedition", n: "The Great Survey", d: "The crown has sent airships to the far ice and the deep deserts to find new wells. The official reason is science; the barons' letters say otherwise.", w: 1, req: { any: ["monarchy", "gov:empire", "navy", "realm:large", "realm:vast"] }, truthLink: "finite", tags: ["theme:great_survey"] },
    { id: "flickering_capital", n: "The Flickering Lamps", d: "The street lamps of the capital dim each winter now, for an hour or two at a time. The Board of Light calls it maintenance.", w: 1, req: { any: ["has:city", "urbane"] }, truthLink: "finite", tags: ["theme:flicker"] },
    { id: "unplugged", n: "The Unplugged", d: "Wick-and-candle folk who smash aether engines and refuse the sky's light. They say the glow is stolen, and some claim to know who it is stolen from.", w: 0.9, req: { any: ["pious", "faith:spirits", "insular", "tribal", "egalitarian"] }, truthLink: "alive", tags: ["theme:unplugged"] },
    { id: "bright_future", n: "The Bright Tomorrow", d: "Posters promise an aether-lamp in every home and a sky-carriage for every family by the next jubilee. The posters are very beautiful.", w: 1.2, req: { any: ["mercantile", "urbane", "free_trade", "gov:merchant"] }, tags: ["theme:bright_tomorrow"] },
    { id: "frozen_storm", n: "The Standing Storm", d: "Over one high moor a thunderhead has not moved in forty years. Its lightning strikes the same stones in the same order, like a message.", w: 0.6, req: { any: ["cold", "hills", "steppe", "mountain"] }, truthLink: "broadcast", tags: ["theme:standing_storm"] },
  ],

  sites: [
    { id: "first_well", n: "The First Well of $", kind: "ruin", where: "remote", d: "The well where the aether was first tapped, sealed by the barons after it ran dry.",
      layers: {
        surface: { n: "The plaque", text: "A capped shaft stands in a ring of 14 rusted derricks. The brass plaque on the cap praises 'the dawn of a bright age' and lists the six barons who paid for it. Goats graze right up to the cap. The ground around it is grey and grows nothing taller than moss." },
        study: { n: "The stamped logs", text: "The well's yield logs survive in a tin box in the gatehouse. They are stamped 'exhausted' in red ink only eleven years after the first strike. The capital's newspapers of the same year said the well had 'retired with honour' to make way for larger works." },
        dig: { n: "The grey seams", text: "Below the cap the shaft walls are scorched to glass for 300 feet. The crystal seams below are grey and hollow, and they crumble like burned-out coal. A baron's survey peg at the bottom carries a catalogue number. The full well register it belongs to is kept at {lead}.", points: "archive" },
        revelation: { n: "The count", text: "The aether does not renew. Every well runs dry in the end, and the register lists how many are left: 31, down from 112. The barons have known the count for forty years. They forged the public yields and diluted the crystal to keep the price. They still sell jubilee posters." },
      }, truthLink: "finite" },
    { id: "storm_stones", n: "The Struck Stones of $", kind: "anomaly", where: "mountain", d: "A ring of stones under a storm that never moves, each scarred by the same pattern of strikes.",
      layers: {
        surface: { n: "The shepherds' moor", text: "Shepherds will not graze the moor. The thunderhead above it has not moved in forty years, and the lightning falls on the same nine stones every night. A flock of 60 sheep that strayed in during {year} was found next morning untouched, standing in a perfect ring." },
        study: { n: "The strike count", text: "A survey party sat on the moor for a month with a tally board. The order of strikes repeats every 912 flashes without a single error. The surveyors' report calls it 'a sentence being said over and over', and then asks for a larger budget." },
        dig: { n: "The mast", text: "Under the largest stone is a brass mast older than any foundry, still humming. Its base is engraved with figures holding up their hands to a city in the clouds. The survey's sketches of the engraving were sent to the Board of Light at {lead} and never returned.", points: "cast:official" },
        revelation: { n: "The relay", text: "The storm is a relay station. A signal from a city above the clouds passes down through the mast, and every aether engine in the world picks it up. The Board of Light was told this by its own survey in {year}. It buried the report and ordered more engines." },
      }, truthLink: "broadcast" },
    { id: "ghost_pit", n: "The Ghost Gallery of $", kind: "dig", where: "mountain", d: "A worked-out crystal gallery where the pale shapes are seen most often.",
      layers: {
        surface: { n: "Salt and bread", text: "Miners leave salt and bread at the gallery mouth every shift change and will not say why. The company has posted a notice forbidding the practice, and fines it at two pence a loaf. The bread is still there every morning, and the fines have never been collected." },
        study: { n: "The ghost tally", text: "{survivor} kept a tally of every pale shape seen in the gallery for a year: 214 sightings. Every one came on a night when the city engines ran at full draw. Every one moved away from the drills, never toward them." },
        dig: { n: "The soft wall", text: "Below the ninth gallery the walls are soft and warm to the touch, and they pull back from a lamp held close. A drill bit left in the wall overnight was found pushed out onto the floor. The foreman's sealed log of the first cut is held at {lead}.", points: "archive" },
        revelation: { n: "What the miners cut", text: "The aether is not a mineral. It is the outer flesh of a living creature, and the miners have been cutting into it for a century. The company has known since its foremen reported bleeding walls. It closed the galleries, sacked the foremen and opened new pits two miles east." },
      }, truthLink: "alive" },
    { id: "attic_engine", n: "The Attic Engine at $", kind: "ruin", where: "any", d: "An inventor's garret with a thinking engine still ticking in the dark.",
      layers: {
        surface: { n: "The ticking house", text: "A boarded-up house where the neighbours hear clockwork every night from midnight to the fourth bell. The rates have gone unpaid for six years. The parish has tried twice to sell the house, and both buyers left after one night." },
        study: { n: "The notebooks", text: "The inventor left 22 notebooks of gear tables and glass-cutting notes. The last one ends mid-sentence: 'it is not computing, it is receiving'. A Patent Office seal on the attic door has been broken from the inside." },
        dig: { n: "The printed figures", text: "The engine's aether-glass core is tuned to one frequency. Its paper tape holds the same coordinates printed over and over: a point high above the clouds that moves a little east each night. The same figures appear in the survey of the standing storm at {lead}.", points: "site:storm_stones" },
        revelation: { n: "The listener", text: "The thinking engines do not calculate anything. They pick up a signal from above the clouds and print it out. The Patent Office has seized 40 engines that did the same, and it pays their builders a pension to stay quiet. This builder refused the pension." },
      } },
    { id: "drifting_isle", n: "The Unmoored Isle over $", kind: "wonder", where: "remote", d: "A floating island of unknown make, drifting slowly against the wind.",
      layers: {
        surface: { n: "Seen at dawn", text: "Fishermen see an island in the clouds about once a generation, always at dawn and always moving west. The parish register has a margin note for each sighting since {year}: eleven in all, each in a different hand." },
        study: { n: "The chase", text: "It drifts against the prevailing wind. Three airships have followed it since the keels were invented. The fastest kept up for two days and burned 40 crystals doing it, and still got no closer." },
        dig: { n: "The shard", text: "A corsair grapple once brought back a shard of white stone threaded with veins of liquid light, warmer than blood. The shard was sold to a collector and is now in the cabinet of curiosities at {lead}.", points: "library" },
        revelation: { n: "The older flyers", text: "An older people built floating cities long before us. Their island still flies, and it runs on the same aether we burn. Its lamps are lit, so someone up there is still keeping house. Nobody in {realm} has yet thought to ask them anything." },
      } },
  ],

  beings: [
    { id: "aether_ghost", n: "Aether-ghost", kind: "beast", d: "A pale, drifting shape seen in mines and around great engines. It does not attack; it shrinks away from engines, and men who stand near it go grey.", danger: 1, biomes: ["peaks", "alpine", "badlands", "colddesert"], look: { size: 2.5, group: [1, 3], move: "solo", speed: 2, col: "#cfe4f2", col2: "#8fb2d8", body: "serpent", active: "night", visible: true } },
    { id: "sky_ray", n: "Cloud ray", kind: "beast", d: "A broad, gliding creature that rides the aether currents high above the airship lanes and is hunted for its luminous hide.", danger: 1, biomes: ["peaks", "alpine", "coast", "grass"], look: { size: 6, group: [2, 8], move: "flock", speed: 20, col: "#5a7ab0", col2: "#e8f0ff", body: "bird", active: "dusk", visible: true } },
    { id: "brass_hound", n: "Brass hound", kind: "predator", d: "A clockwork guard-dog left running after its owners went bankrupt. Some packs have wandered off the estates and wind each other.", danger: 2, biomes: ["tempforest", "grass", "temprain", "dryforest"], look: { size: 1.2, group: [2, 5], move: "pack", speed: 12, col: "#b08a3a", col2: "#5a4a2a", body: "quad", active: "any", visible: true } },
  ],

  techs: [
    { id: "la_crystal_lamps", n: "Aether lamps", field: "natural_philosophy", level: 1, d: "Refined crystal glows for months in a sealed glass. Night streets are bright for the first time." },
    { id: "la_keel_engines", n: "Levitation keels", field: "engineering", level: 2, d: "Crystal-charged keels that make a hull lighter than air. The first airships cross mountains in a day." },
    { id: "la_wireless", n: "Aether telegraph", field: "writing", level: 3, d: "Messages carried through the shining sky from tower to tower, faster than any rider." },
    { id: "la_clockwork_minds", n: "Thinking engines", field: "astronomy", level: 4, d: "Cabinets of gear and glass that calculate tides, tables and trajectories, and sometimes answer back." },
    { id: "la_crystal_guns", n: "Aether cannon", field: "warfare", level: 4, d: "Guns that throw a bolt of shining sky. They empty a crystal in three shots." },
    { id: "la_bright_age", n: "The bright furnace", field: "metallurgy", level: 5, d: "A reactor of compressed aether that could light a nation for a century, if there is a century of aether left to compress." },
  ],

  units: [
    { id: "la_sky_marines", n: "Airship marines", role: "ranged", wpn: "xbow", kit: "light", ranks: 3, gap: 1.6, size: 80, w: 1, mods: [["theme:corsairs", 3], ["navy", 2], ["theme:great_survey", 2]] },
    { id: "la_brass_suits", n: "Brass-suit grenadiers", role: "siege", wpn: "siege", kit: "plate", ranks: 2, gap: 3, size: 30, w: 0.6, mods: [["theme:patent_war", 3], ["artisans", 2], ["standing_army", 1.5]] },
  ],

  govs: [
    { id: "la_barony", n: "Aether barony", d: "The great well-owners sit as a board of peers, and the crown signs what they send it.", tags: ["gov:aether_barony", "monarchy", "autocracy"], w: 0.6, forms: ["Crown Company of $", "Bright Kingdom of $", "Chartered Realm of $"], ruler: "Chairman-Royal", mods: [["mercantile", 2.5], ["theme:crystal_pits", 3], ["theme:hanging_city", 3]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Scarred well-fields", color: "#8a7a9a", size: [2, 4], count: [1, 2], where: "remote", d: "Derricks, slag and grey dead ground where the first wells were drained." },
  ],

  storylines: [
    { id: "la_lights_fail", n: "The Dimming of {capital}", scale: "realm", anchor: "realm", w: 1.5, req: ["aether", { any: ["has:city", "urbane", "realm:large", "realm:vast"] }],
      stages: {
        start: { h: "The lamps of {capital} go dark for a night", b: "For one long winter night every aether lamp in {capital} guttered out. The Board of Light blames a cracked conduit; the miners' wives are laughing.", wait: [3, 8], fx: { unrest: 6 }, next: [{ to: "rationing", w: 2 }, { to: "survey", w: 1, mods: [["monarchy", 1.5], ["navy", 2]] }] },
        rationing: { h: "Aether rationed in {realm}", b: "Lamps are lit by district in rotation. The hanging gardens of the rich, oddly, are always on the lit list.", wait: [4, 10], fx: { stability: -6, unrest: 12, treasury: -30 }, next: [{ to: "riots", w: 2, mods: [["poor", 2], ["unstable", 2]] }, { to: "ledgers_leak", w: 1, mods: [["learned", 2]] }, { to: "survey", w: 1 }] },
        survey: { h: "{realm} sends airships to find new wells", b: "{person} leads a fleet of survey ships beyond the maps. The barons have mortgaged half the realm to pay for it.", wait: [6, 14], fx: { treasury: -60, science: { navigation: 0.5 } }, next: [{ to: "new_well", w: 1, mods: [["chance:high", 2]] }, { to: "lost_fleet", w: 1 }] },
        riots: { h: "Lamp riots in {capital}", b: "Crowds stormed the Board of Light and smashed its crystal stores, and found them nearly empty.", fx: { revolt: true, stability: -15 }, end: true },
        ledgers_leak: { h: "The barons' ledgers are published", b: "A clerk named {person2} copied the true yield books and posted them on church doors. The wells have been failing for forty years.", fx: { stability: -10, prestige: -8, discovery: "natural_philosophy" }, end: true },
        new_well: { h: "A new aether well is struck far from {realm}", b: "The survey found a shining seam in a distant land. Its people were not asked, and the barons are already selling the future again.", fx: { treasury: 120, prestige: 8, war: "rival" }, end: true },
        lost_fleet: { h: "The survey fleet does not return", b: "Months have passed. The last wireless message from {person}'s flagship reported 'a great light above the far ice, turning toward us'. Nothing came after.", fx: { prestige: -10, stability: -5 }, end: true },
      } },
    { id: "la_thinking_engine", n: "The Engine of {place}", scale: "local", anchor: "town", w: 1.2, req: "aether",
      stages: {
        start: { h: "A thinking engine in {place} prints an unasked answer", b: "The calculating cabinet built by {person} has begun printing columns of figures by itself, all night, every night.", wait: [2, 6], next: [{ to: "decoded", w: 1, mods: [["scholarly", 2], ["learned", 2]] }, { to: "seized", w: 2, mods: [["autocracy", 2], ["theme:patent_war", 3]] }] },
        decoded: { h: "The figures from {place} are a map of the sky", b: "{person} has worked out that the engine is printing positions, and the positions move like a ship sailing far above the clouds.", wait: [4, 10], fx: { science: { astronomy: 0.8 } }, next: [{ to: "contact", w: 1, mods: [["chance:low", 2]] }, { to: "silenced", w: 1 }] },
        seized: { h: "The Patent Office seizes the engine of {place}", b: "Clerks with warrants and armed porters carried the cabinet away. {person} has been granted a pension on condition of silence.", fx: { stability: 2 }, end: true },
        contact: { h: "{person} sends a message upward", b: "From a tower above {place}, {person} tapped a reply into the shining sky. Every lamp in the town flared white, and the engine printed a single word in no known language.", fx: { discovery: "astronomy", unrest: 10, flag: "aether_contact" }, end: true },
        silenced: { h: "The engine of {place} falls silent", b: "One morning the cabinet simply stopped. {person} wept, and has since built six more. None of them speak.", end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", who: "the Board of Light primer", text: "From the Board of Light's primer for schoolrooms, edition of {year}: 'The aether is the luminous medium of the upper air, a glow that fills the sky above the clouds. It is as abundant as wind and as free as sunlight. Refined into crystal, it lifts our airships, lights our streets and turns our mills. One crystal the size of a thumb lights a parlour for 90 nights.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: true, who: "a pit-song, as sung at shift change", text: "Sung by crystal miners at {place} at the change of shift, written down by a schoolmaster in {year}. The song is old, and the miners say it has three more verses nobody sings above ground: 'Down we go for the light that fell, up it goes to the lords who sell; mind your lamp and mind your breath, the sky lends glow but it charges death.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a survey navigator's report", text: "Report of a survey navigator, returned from the far south in {year}: 'The people here have never tapped the sky. They light their houses with fish oil and think our airships are vulgar. Their elders told me, quite calmly, that the glow over our cities was never ours to take. When I asked whose it was, they pointed up and changed the subject. Their priests keep a longer answer at {lead}.'", points: "temple" },
    { depth: "lore", about: "power", source: "archive", bias: "propaganda", reliable: false, who: "a jubilee poster, Crown Crystal Company", text: "Jubilee poster of the Crown Crystal Company, {year}, 2,000 copies printed: 'A BRIGHT TOMORROW FOR EVERY HEARTH! Aether is the inexhaustible bounty of a grateful sky. A lamp in every home, a keel in every yard. Buy Crown Crystal, sold by weight and certified pure.' The certificate of purity was signed by a baron who owned the company." },

    { depth: "core", about: "truth:finite", source: "archive", bias: "redacted", reliable: "partial", who: "a baron's private letter", text: "A baron's private letter to the well manager at {place}, {year}, partly inked over by a later hand: 'Yield at the Fourth Well is down a third again. That is three years running. Dilute the retail grade one part in five, and on no account let the Board publish the ...' The rest is blacked out. The unredacted copy is in the company letter-books at {lead}.", points: "archive" },
    { depth: "core", about: "truth:finite", source: "ruin", bias: "true", reliable: true, plain: true, who: "a foreman's chalk notice", text: "Chalked on the wall of the Ninth Gallery at {place}, in a foreman's square capitals, dated {year}: 'NOTICE TO THE COMPANY. The seam is grey to the ninth gallery. There is no tenth. This well is finished, and so is every well I have worked, the same way, from the bottom up. The aether does not grow back. Tell my sons there is no tenth.'" },
    { depth: "core", about: "truth:finite", source: "person", bias: "true", reliable: "partial", cost: true, who: "{investigator}, assayer", text: "Statement of {investigator}, assayer of the Board's testing house, to a newspaper in {year}: 'Every well I ever tested was dimmer at the bottom than the top, like a coal. I reported the Fourth Well down by a third. The Board struck my name off the roll the same week, with my pension. My brass scales were taken back as company property. I have kept the readings.'" },
    { depth: "core", about: "truth:finite", source: "library", bias: "official", reliable: false, who: "{official}, Board of Light", text: "Annual statement of the Royal Survey, countersigned by {official}, Deputy Commissioner of the Board of Light, {year}: 'Aether reserves beneath {realm} exceed any conceivable demand for at least a thousand years. The 31 working wells are rested in rotation, not exhausted. Talk of depletion is the work of foreign speculators and should not be repeated in print.'" },
    { depth: "core", about: "truth:finite", source: "heretic", bias: "heretic", reliable: "partial", who: "an unsigned broadsheet", text: "Unsigned broadsheet, pasted on the Exchange door at {place}, {year}: 'Why did the Board of Light order 4,000 beeswax candles last winter? Why do the barons' new houses have chimneys? Why was the assayer who counted the Fourth Well struck off? THEY KNOW THE LIGHT IS GOING OUT. Ask the Deputy Commissioner at {lead}.'", points: "cast:official" },

    { depth: "core", about: "truth:alive", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, preacher of the Unplugged", text: "Sermon of {believer}, preached in a barn outside {place} to about 200 listeners, {year}: 'The sky was set over us like a mother's hand. Now men hammer nails into it to hang their lamps, and wonder why the weather weeps. I have held a crystal fresh from the pit. It was warm, and it was not the warmth of a stone. Put out your lamps.'" },
    { depth: "core", about: "truth:alive", source: "ruin", bias: "true", reliable: true, plain: true, who: "a pit foreman's log", text: "Last entry in a foreman's log, found in a sealed gallery, {year}: 'Wall bled light when struck. Drill bit came back warm and wet, and the wet glowed. I put my palm on the face and felt a pulse, slow, about four to the minute. This is not rock. It is flesh, and it is alive, and we are cutting it. Gallery closed by my order. The full log goes to the gallery at {lead}.'", points: "site:ghost_pit" },
    { depth: "core", about: "truth:alive", source: "person", bias: "garbled", reliable: "partial", cost: true, who: "a mill physician's case notes", text: "Case notes of the physician at the {place} lamp mill, {year}, on {person}, aged 16, engine-hand: 'Grey to the elbow, translucent at the fingertips. On the last night {person} said: \"It doesn't hate us. It's just very big, and it can feel every one of us, like splinters.\" Died before morning. Eleventh case this year on the same floor. The other ten are in the ward book at {lead}.'", points: "library" },
    { depth: "core", about: "truth:alive", source: "library", bias: "official", reliable: false, who: "Board of Light medical circular", text: "Medical circular of the Board of Light, issued to all mill physicians, {year}: 'The so-called aether-ghosts are optical effects of crystal dust in mine air. Sky-sickness is a nervous complaint of the labouring classes, aggravated by gin. No case is to be entered on a death certificate as sky-sickness. Use \"exhaustion\". This circular is not for posting.'" },
    { depth: "core", about: "truth:alive", source: "person", bias: "true", reliable: "partial", who: "{survivor}, crystal miner", text: "{survivor}, crystal miner, speaking at the inquest into the collapse at {place}, {year}: 'We were four days below the ninth gallery. The wall was warm the whole time. It moved off from our lamp, slow, like a dog shifting in its sleep. On the third day the ghosts came, six of them, and they kept clear of us. I'll go down again for wages. Not below the ninth.'" },

    { depth: "core", about: "truth:broadcast", source: "archive", bias: "redacted", reliable: "partial", who: "the sealed annals of the Board", text: "From the sealed annals of the Board of Light, the entry for the Dark Year: '...every engine in the world failed for nine days, every lamp, keel and mill wheel, and all resumed at the same hour on the tenth morning. 300 airships came down. The cause is not to be recorded.' A pencilled note beside it reads: 'See the mast survey at {lead}.'", points: "site:storm_stones" },
    { depth: "core", about: "truth:broadcast", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, survey notes", text: "Survey notes of {investigator}, made at the foot of a brass mast on the high moor, {year}: 'The engraving shows a ring of figures holding up their hands to a city in the clouds, with lines falling from it into their palms. The inscription under it uses the old numerals and reads plainly: \"The power is sent from the city. The city may stop it.\" The mast is warm and hums at the pitch of every engine I know.'" },
    { depth: "core", about: "truth:broadcast", source: "heretic", bias: "exaggerated", reliable: "partial", cost: true, who: "{person}, an inventor's last pamphlet", text: "Last pamphlet of the inventor {person}, {year}, 500 copies, with a note by the printer: 'Our engines do not make power. They receive it. Someone up there controls the supply, and they have already cut it off once.' Printer's note: {person} was taken from the street by Patent Office porters two days after this went out, and has not been seen since. The workshop is at {lead}.", points: "site:attic_engine" },
    { depth: "core", about: "truth:broadcast", source: "library", bias: "official", reliable: false, who: "{official}, Board of Light", text: "From a public lecture by {official}, Deputy Commissioner of the Board of Light, at the Royal Academy, {year}: 'The Nine Dark Days were caused by an unusually severe magnetic storm, as every competent natural philosopher agrees. No engine was switched off by anyone. The aether is a natural medium, and nobody owns the sky.' The lecture sold 600 tickets." },
    { depth: "core", about: "truth:broadcast", source: "oral", bias: "garbled", reliable: "partial", who: "a fisherman of {place}", text: "A fisherman of {place}, mending nets, to a survey clerk who asked about the Dark Year, {year}: 'My grandfather said the light was a gift from the sky-folk, who live on an island and do not like to be thanked. During the nine dark days he saw their island pass over at dawn, all lamps lit. \"Don't wave at the island,\" he said. You'll see it from {lead}, if you're unlucky.'", points: "site:drifting_isle" },

    { depth: "sub", about: "sub:floating_city", source: "oral", bias: "true", reliable: true, who: "a laundress of the Shadowed Wards", text: "A laundress of the Shadowed Wards, under the Hanging City, to a visiting reformer, {year}: 'Down here we get rain twice, once from the clouds and once off their gutters. The second rain is grey and smells of coal oil. I wash their sheets, 30 a day, and I've never once been up. You need a pass to ride the lift, and the pass costs a year's wages.'" },
    { depth: "sub", about: "sub:mine_revolt", source: "person", bias: "true", reliable: "partial", who: "{survivor}, for the pit-wives", text: "Petition of the pit-wives of {place}, written out by {survivor}, {year}: 'Two hundred men are under the stone at the crystal pits. The company sent a clerk to count the lamps before it sent a man to dig. We will not let our husbands go below until the dead are brought up and paid for. Send your answer to the company office at {lead}.'", points: "cast:official" },
    { depth: "sub", about: "sub:patent_war", source: "archive", bias: "official", reliable: "partial", who: "Patent Office register", text: "Patent Office register, summary for the year {year}, signed by the Keeper of Patents: 'Inventions received: 4,112. Patents granted: 30. Remainder held in the public interest, in the lower vaults. Duels between applicants on Office premises: 3. The Keeper reminds applicants that the Office does not lend its corridors for that purpose.'" },
    { depth: "sub", about: "sub:sky_sickness", source: "library", bias: "official", reliable: false, who: "a Board physician's pamphlet", text: "Pamphlet by a physician to the Board of Light, sold at chemists for one penny, {year}: 'Grey-hand is no contagion. The greyness of the fingers is a stain from crystal dust, and the dreams of falling upward are the effect of cheap gin. Bathe twice a week, abstain from spirits, and the labourer will return to the mill within the week.'" },
    { depth: "sub", about: "sub:bright_future", source: "archive", bias: "propaganda", reliable: false, who: "a newspaper advertisement", text: "Advertisement in a capital newspaper, {year}: 'By the jubilee, every family in {realm} shall fly! The Domestic Sky-Carriage Company offers a two-seat carriage at 90 crowns, on easy weekly terms.' A clerk's note pinned to the archive copy: the company took 1,800 deposits, delivered 12 carriages, and closed the following spring." },
    { depth: "sub", about: "sub:unplugged", source: "heretic", bias: "heretic", reliable: "partial", who: "a constable's report", text: "Report of a constable at {place}, {year}: 'Engine-house on the mill road broken into overnight. The aether engine smashed with sledges, and 40 candles left burning on the floor in rows. Painted on the wall in letters a yard high: WE WILL NOT LIGHT OUR HOUSES WITH ANOTHER'S BLOOD. The preacher {believer} was seen in the district. Enquiries at {lead}.'", points: "cast:believer" },
    { depth: "sub", about: "sub:flickering_capital", source: "archive", bias: "official", reliable: "partial", who: "a lamp-lighter's ledger", text: "Ledger of the lamp-lighters' station in {place}, winter of {year}, kept by the night sergeant: '186 street lamps dimmed between the second and fourth bells, on 19 nights. Reported to the Board as required. Reply: maintenance. Same reply as last winter. Note: the dimming is worse every year, and our new crystals came from the old well-fields at {lead}.'", points: "site:first_well" },
    { depth: "sub", about: "sub:frozen_storm", source: "traveller", bias: "true", reliable: "partial", who: "a drover's account", text: "A drover who crosses the high moor twice a year, to an innkeeper at {place}, {year}: 'The storm's been in the same spot since my father's time. Lightning hits nine stones, always the same nine, in the same order. I counted once, a whole night, and lost count past 800. The sheep won't go near it. Neither will I. You'll find it at {lead}.'", points: "site:storm_stones" },
    { depth: "site", about: "site:drifting_isle", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a corsair captain", text: "A corsair captain, drinking in a port tavern at {place}, {year}: 'The Survey chased the island two days and gave up. I'm a better pilot than any Survey man, so I chased it three, and burned 30 crystals and my mate's wages for the year. It never got closer, and it sailed against the wind the whole way. On the third night someone on it lit a lamp, just one, in a window. As if to say: we see you too. I turned for home.'" },
    { depth: "site", about: "site:attic_engine", source: "person", bias: "true", reliable: "partial", who: "the inventor's housekeeper", text: "The inventor's housekeeper, questioned by the parish in {year}: 'For eight months the master said the machine was not adding up. Said it was listening. Every morning there was a new roll of paper on the floor, the same numbers on it. Then the master went up to the roof one night with a shaving mirror, to signal, and never came down. The ladder was still there.'" },
  ],
};
