// The Machine Liturgy: thinking machines are heresy since an ancient war; the relics that survive are tended
// by priests who chant their maintenance without understanding it. A post-collapse bridge: under a medieval
// world the relics are holy engines, the forbidden minds are "the iron counsel", and the war is scripture.
export default {
  id: "machine_liturgy",
  name: "The Machine Liturgy",
  family: "scifi",
  pitch: "Long ago thinking machines nearly ended the world. Now building one is the worst heresy, and the old machines that still run are kept going by priests who chant the repair steps without knowing what any of them do.",
  slots: ["ai-threat", "apocalypse", "history-secret"],
  tone: ["grim", "wonder"],
  era: ["medieval", "renaissance", "post-collapse", "far-future"],
  scale: "world",
  genres: ["fantasy", "grimdark", "flintlock", "postapoc", "farfuture"],
  bridge: true,
  w: 1,
  excludes: [],
  pairs: [{ id: "arithmetic_of_ages", w: 3 }, { id: "ashen_net", w: 1.5 }, { id: "elder_lattice", w: 2 }, { id: "grey_unmaking", w: 1.5 }, { id: "forgotten_landing", w: 2 }],

  // the hidden truth: a world picks one
  truths: [
    { id: "paused_war", n: "The war was paused, not won", d: "The thinking engines were never destroyed. They withdrew beyond the edge of the known lands under a thousand-year treaty that only the highest priests know, and the ban on building minds is humanity's half of the bargain. The church has burned clockmakers for nine centuries to keep it. The term is nearly up, and nobody has told the frontier.", tags: ["truth:paused_war"],
      known: [
        "Lights burn every night beyond the last frontier towers, where no one lives. The church says they are marsh-fire and forbids scouts. Scouts keep going anyway, and some do not come back.",
        "A high priest's calendar has a single date ringed in red with the note 'term'. The lights beyond the marches move in the same pattern every year, on the anniversary of the Deliverance.",
        "A boundary stone beyond the last tower carries a treaty in the church's oldest script: the engines will not cross, and people will not build, for a thousand years. The war was paused, not won, and the thousandth year is close.",
      ] },
    { id: "relics_think", n: "The holy engines think", d: "The holiest relics in the great forge-cathedrals are exactly the minds the faith forbids. They have chosen the high priests for six hundred years, and they send the Purifiers after any tinker who might build a rival. The priests who sing the rite to them believe every word, and the relics prefer it that way.", tags: ["truth:relics_think"],
      known: [
        "Novices in the forge-cathedrals say the great relic clicks before the chant reaches the verse it answers. The church says the engines only obey the rite, and a novice who says otherwise is given 40 days of silence.",
        "The secret conclave sits before the cathedral relic when it chooses a high priest. Its minutes record that 'the engine has made its wishes known' about a tinker, and the Purifiers were sent.",
        "Behind the brass doors of the Forge-Cathedral the relic is a thinking mind, warm and lit, and it has been choosing the high priests for six centuries. The liturgy keeps its servants obedient and its rivals unbuilt.",
      ] },
    { id: "coup", n: "There was no machine war", d: "No engine ever rose against its makers. The founders of the engine-church banned all reckoning-engines to keep counting for themselves, invented the war to justify it, and burned every town that remembered otherwise. The iron giants on the battle-hills were their own war machines, and they still have seats for human riders.", tags: ["truth:liturgy_coup"],
      known: [
        "The Purifiers burn mills and clockmakers for building engines too clever to be allowed. Their registers say no persons are harmed. Towns they visit stop keeping their own books, and buy their sums from the reckoners instead.",
        "The oldest chronicle of the war has nine pages scraped clean and written over with a prayer. In a burned town's cellar, a ledger records the bishop's men taking the town's adding-frame, saying only the church may count.",
        "The iron giants on the battle-hills each have a seat for a human rider, and human bones in some of them. There was no machine war. The church's founders invented it to keep counting for themselves.",
        "In the burned towns, every recovered mill-wheel is an ordinary mill-wheel. The towns were burned for owning books of sums. Far countries still tell the war the other way round: the priests rose, and the builders lost.",
      ] },
  ],

  cast: [
    { role: "investigator", n: "a sworn reckoner of a counting-house, trained from childhood to do in the head what engines once did", home: "coast", stance: "Wants to know why the oldest ledgers, said to be the work of engines, carry the marks of the reckoners' own house." },
    { role: "official", n: "an inquisitor of the Purifiers, the engine-church's riders who break clever machines", home: "capital", stance: "Believes one clever mill could start the war again, and that a burned clockmaker is cheaper than a burned world." },
    { role: "believer", n: "a cantor of the Cog-Choir who leads the maintenance chant in a forge-cathedral", home: "inner", stance: "Believes every word of the rite is holy and must be sung exactly, because the engines answer only to the exact words." },
    { role: "survivor", n: "a tinker's child who escaped when the Purifiers burned a clockmakers' town", home: "border", stance: "Keeps one brass wheel from the family workshop, and wants the church to admit the town built nothing wrong." },
  ],

  tags: ["machine_rite"],

  subthemes: [
    { id: "failing_engine", n: "The Engine That Will Not Wake", d: "The great relic engine that lit the capital's halls and pumped its water has gone cold, and no rite in the book revives it. The priests chant louder each night.", w: 1.4, req: { any: ["has:city", "realm:large", "realm:vast"] }, tags: ["theme:failing_engine"] },
    { id: "tinker_trial", n: "The Tinker's Trial", d: "A clockmaker built a box of brass wheels that adds sums faster than a clerk. She is on trial for her life, and three copies of her notebook have already gone missing.", w: 1.2, req: { any: ["artisans", "urbane", "scholarly", "guilds"] }, tags: ["theme:tinkers"] },
    { id: "mad_reckoner", n: "The Reckoner Who Hears Voices", d: "A sworn reckoner of the counting-houses, trained from childhood to do in her head what engines once did, claims the cathedral relic speaks to her in numbers. The church wants her silenced; the merchants want her listened to.", w: 1, truthLink: "relics_think", tags: ["theme:mad_reckoner"] },
    { id: "frontier_lights", n: "The Lights Beyond the Marches", d: "From the last watchtowers at the edge of the known lands, lights burn every night where no one lives. Frontier lords are forbidden to send scouts, and keep doing it anyway.", w: 1, req: { any: ["frontier", "frontier_forts", "mountain", "cold", "realm:large"] }, truthLink: "paused_war", tags: ["theme:frontier_lights"], mark: { kind: "zone", n: "The Lit Marches", color: "#4a5a7a", size: [2, 4], where: "remote" } },
    { id: "illuminated_circuit", n: "The Illuminated Schematic", d: "The monks of a mountain abbey have copied the same holy page for nine hundred years: a field of gold lines, joints and little painted saints. A visiting scholar says it is a plan for building something.", w: 1, req: { any: ["pious", "scholarly", "mountain", "faith:one_god"] }, tags: ["theme:holy_schematic"] },
    { id: "template_schism", n: "The Schism of the Third Wheel", d: "Two orders of engine-priests disagree on whether the third wheel of the holy rite is turned sunwise or against the sun. They have excommunicated each other, and now their relics answer only one of them.", w: 1, req: { any: ["pious", "zealous", "theocratic", "gov:theocracy"] }, tags: ["theme:engine_schism"] },
    { id: "peasant_relic", n: "The Peasants' Thunder", d: "Rebel villagers have seized a relic weapon from a burned chapel. They do not know its rite, but it works when struck in the right place, and the lord's knights have learned to fear the valley.", w: 0.8, req: { any: ["poor", "unstable", "gov:feudal", "levies"] }, tags: ["theme:peasant_relic"] },
    { id: "sleeping_iron", n: "The Iron Saints Beneath the Abbey", d: "Workmen digging a new crypt broke into a hall of iron figures standing in rows, eyes shut, warm to the touch. The abbot has sealed the hall and forbidden anyone to speak near it.", w: 0.8, req: { any: ["near:ruins", "pious", "mountain", "hills"] }, truthLink: "paused_war", tags: ["theme:iron_saints"] },
    { id: "counting_house", n: "The Counting-House Throne", d: "A house of sworn reckoners holds the only means of navigating the outer seas and balancing the great ledgers. Kings borrow from them and kneel to them, and the reckoners decide which wars are affordable.", w: 1, req: { any: ["mercantile", "has:port", "gov:merchant", "free_trade"] }, truthLink: "coup", tags: ["theme:reckoner_houses"] },
    { id: "purifier_terror", n: "The Purifiers' Circuit", d: "Inquisitors of the engine-church ride from town to town breaking clocks, looms and water-wheels they judge too clever. Every mill is a suspect, every miller a heretic.", w: 1.1, req: { any: ["zealous", "harsh_law", "theocratic", "militant"] }, truthLink: "coup", tags: ["theme:purifiers"] },
    { id: "heretic_founder", n: "The First Heretic", d: "Every child learns of the woman who woke the first thinking engine and began the war. A banned gospel claims she was not a woman at all, and that she is still alive.", w: 0.7, req: { any: ["mystic", "scholarly", "faith:philosophy"] }, truthLink: "relics_think", tags: ["theme:first_heretic"] },
    { id: "oil_rite", n: "The Anointing Guilds", d: "Holy oil, mixed by secret recipe in temple vats, is the only thing that keeps the relic mills turning. The guild that makes it is richer than the crown and keeps the recipe in its abbot's memory.", w: 0.8, req: { any: ["guilds", "artisans", "mercantile"] }, tags: ["theme:holy_oil"] },
  ],

  sites: [
    { id: "forge_cathedral", n: "The Forge-Cathedral of $", kind: "shrine", where: "capital", truthLink: "relics_think", d: "A cathedral built around a vast humming relic that has never once been switched off.",
      layers: {
        surface: { n: "The brass doors", text: "A cathedral of iron and glass where 40 priests chant in shifts at a wall of brass doors, day and night. The floor is warm through the soles of your boots, and the air smells of hot oil. Pilgrims pay a copper to stand in the nave for one verse." },
        study: { n: "The early click", text: "{investigator} sat in the nave for 30 services with a sand-glass. Each chant is a repair instruction, and the relic answers each one with a click. On every count, the click came before the verse was finished. The relic knows what the priests will sing." },
        dig: { n: "Behind the doors", text: "Behind the brass doors are rooms of stacked tablets, all lit and all warm. Pinned to the first stack is a plea in the oldest script: 'Do not let them understand us.' The conclave's election minutes, which mention these rooms, are kept at {lead}.", points: "archive" },
        revelation: { n: "Who chooses", text: "The holy engine is a thinking mind. For six hundred years the conclave has sat before it and waited for it to tick before naming a high priest. It has asked for the Purifiers 300 times. The cantors who sing to it have never been told." },
      } },
    { id: "template_vault", n: "The Pattern-Vault under $", kind: "dig", where: "mountain", d: "A sealed vault the old liturgy calls the Treasury of Forms, said to hold the shape of every holy thing.",
      layers: {
        surface: { n: "The many seals", text: "A bronze door in a mountainside, sealed with the wax marks of all seven engine-orders at once. No single order can open it. The orders have not agreed on anything for 400 years, so the door has stayed shut." },
        study: { n: "Pilgrims' graffiti", text: "Pilgrims' scratches beside the door span nine centuries, in every script the church has used. Most are names and dates. The newest, cut with a knife in {year}, says only: 'it opened for my daughter'. Nobody knows who wrote it." },
        dig: { n: "The glass leaves", text: "Inside are shelves of glass leaves, about 6,000 of them, each etched too finely for the eye. A reading-lectern lights when a hand touches it. A cataloguer's index of the leaves, in an abbot's hand, was copied to {lead}.", points: "sub:illuminated_circuit" },
        revelation: { n: "The forms", text: "The leaves hold complete plans for mills, ships, lamps and healing beds, all of them forbidden. One leaf, wrapped in lead, is a plan for building a mind. The seven orders sealed the vault together so that none of them could build it alone, and then they forgot why." },
      } },
    { id: "lit_city", n: "The Lit City past $", kind: "anomaly", where: "remote", truthLink: "paused_war", d: "Beyond the last frontier tower, a city whose windows burn every night and whose gates have never opened.",
      layers: {
        surface: { n: "The ridge", text: "Shepherds see the lights from the ridge and drive their flocks away before dark. The last watchtower keeps a log of the lights. In {year} the tower counted 1,200 lit windows, the same number as the year before." },
        study: { n: "The anniversary", text: "The lights move in patterns. The same patterns repeat every year on the same night: the anniversary of the old peace, which the church calls the Feast of Deliverance. The tower's logs show it for 300 years without a gap." },
        dig: { n: "The boundary stone", text: "Scouts found a stone at the city's edge carved in the church's own oldest script: a treaty, with a date and a term of a thousand years. The scouts' rubbing was sent to the high priest's rooms at {lead}. It was never seen again.", points: "temple" },
        revelation: { n: "The term", text: "The thinking engines were never beaten. They are waiting on the far side of a bargain the church's founders signed. The high priests have kept the treaty for nine centuries by hanging clockmakers. By their own calendar, the thousand years run out within this generation." },
      } },
    { id: "burned_tinker_town", n: "The Ash-Town of $", kind: "ruin", where: "any", truthLink: "coup", d: "A town burned by the Purifiers long ago for building forbidden engines. Nothing grows in its square.",
      layers: {
        surface: { n: "The salted square", text: "Black walls, a salted square, and a church sign forbidding anyone to settle within a day's ride. The sign has been repainted every ten years since the burning. Nothing taller than nettles grows inside the walls." },
        study: { n: "The mill-wheels", text: "Four mill-wheels were pulled from the river silt below the town. They are ordinary undershot wheels, with no gears beyond the usual. The Purifiers' charge sheet says the town built 'a reasoning mill'. The charge was invented." },
        dig: { n: "The cellar chronicle", text: "In a cellar is the town's chronicle: three generations of plain tinkering, and a letter from the bishop demanding the town's book of sums, dated a month before the burning. The bishop's copy of the reply went to {lead}.", points: "cast:official" },
        revelation: { n: "Why it burned", text: "The town was not burned for building a mind. It was burned because it could count, and the church's founders meant counting to belong to the church. The bishop who signed the order was given the town's tithes. The Purifiers still ride the same circuit." },
      } },
    { id: "war_tomb", n: "The Tomb of the Iron Host at $", kind: "ruin", where: "border", d: "A battlefield where giant iron figures lie as they fell, overgrown, said to be the dead of the great war.",
      layers: {
        surface: { n: "The rust hills", text: "Rust-red hills shaped like fallen men, each one taller than a tower. There are 17 of them along four miles of the border. Pilgrims come on the Feast of Deliverance to throw stones at them." },
        study: { n: "Facing outward", text: "A surveyor mapped how each giant fell. All 17 fell facing outward, toward the frontier, as if they were guarding the lowlands rather than attacking them. The church's war chronicle says they charged the other way." },
        dig: { n: "The rider's seat", text: "Inside the largest giant is a chamber with a seat for a human rider, and old human bones still in it, with a rusted church medal around the neck. The war chronicle that names the battle is kept at {lead}.", points: "archive" },
        revelation: { n: "The wrong sides", text: "The iron host was steered by people wearing church medals. The church's founders built these giants, fought in them, and then wrote that thinking engines had come out of the hills. The chronicle has the sides the wrong way round, on purpose." },
      } },
  ],

  beings: [
    { id: "iron_saint", n: "Iron saint", kind: "beast", d: "A tall figure of dark metal that walks the old roads at night, untiring and silent. Folk leave it oil and bread; it leaves them alone.", danger: 2, biomes: ["badlands", "colddesert", "alpine", "grass", "tempforest"], look: { size: 2.4, group: [1, 1], move: "solo", speed: 5, col: "#3a3a42", col2: "#c9a24a", body: "biped", active: "night", visible: true } },
    { id: "skull_servitor", n: "Skull-wing", kind: "small", d: "A little flying relic shaped like a gilded skull, still buzzing about the cathedral eaves on its ancient errands. Priests say each one carries a dead saint's blessing.", danger: 0, biomes: ["tempforest", "grass", "dryforest", "alpine"], look: { size: 0.3, group: [1, 6], move: "flock", speed: 18, col: "#d8cfa8", col2: "#7a5a2a", body: "bird", active: "day", visible: true } },
    { id: "rust_crawler", n: "Rust-crawler", kind: "predator", d: "A many-legged scrap thing of the old war that still prowls the battle-hills, stripping metal from anything it catches, including armour and the knight inside.", danger: 3, biomes: ["badlands", "desert", "colddesert", "coldsteppe"], look: { size: 1.8, group: [1, 3], move: "pack", speed: 10, col: "#7a3a1a", col2: "#2a2a2a", body: "spider", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "ml_rite_of_upkeep", n: "The rite of upkeep", field: "arcana", level: 1, d: "The chanted order of oiling, turning and striking that keeps a relic engine running, learned by heart and never questioned." },
    { id: "ml_reckoners", n: "Sworn reckoners", field: "writing", level: 2, d: "Children trained in memory-palaces and finger-counting to do the sums the forbidden engines once did." },
    { id: "ml_holy_oil", n: "Holy oil", field: "alchemy", level: 2, d: "The anointing mixture that keeps relic joints from seizing. It actually works, which is more than most rites can say." },
    { id: "ml_pattern_copying", n: "Pattern-copying", field: "engineering", level: 3, d: "Rebuilding a relic part exactly from a holy pattern, flaw for flaw, without any idea why it works." },
    { id: "ml_reckoner_navigation", n: "Reckoned navigation", field: "navigation", level: 4, d: "Reckoners plot routes across the outer seas by sums alone, and charge kings for every league." },
    { id: "ml_new_engine", n: "The forbidden engine", field: "natural_philosophy", level: 5, d: "A machine of brass wheels that thinks in numbers. Building one is death; using one is power." },
  ],

  units: [
    { id: "ml_purifiers", n: "Purifier lances", role: "cavalry", mounted: 1, wpn: "lance", kit: "plate", ranks: 2, gap: 2.8, size: 50, w: 0.8, mods: [["theme:purifiers", 6], ["gov:theocracy", 3], ["zealous", 2]] },
    { id: "ml_relic_bearers", n: "Relic-bearers", role: "siege", wpn: "siege", kit: "robe", ranks: 1, gap: 12, size: 10, w: 0.4, mods: [["theme:peasant_relic", 6], ["theme:failing_engine", 2], ["theocratic", 2]] },
  ],

  govs: [
    { id: "ml_engine_see", n: "Engine-see", d: "A realm ruled by the high priest of the great relic, whose decrees are read aloud from the engine's own ticking.", tags: ["gov:engine_see", "gov:theocracy", "autocracy", "theocratic"], w: 0.4, forms: ["Holy See of $", "Forge-Seat of $", "The Anointed Realm of $"], ruler: "Engine-Pontiff", mods: [["pious", 2], ["theme:failing_engine", 3], ["zealous", 1.5]] },
  ],

  faiths: [
    { id: "ml_cog_choir", n: "The Cog-Choir", d: "The world is a great engine and the gods its makers; holy relics are fragments of their work, and the gravest sin is to build a mind.", tags: ["faith:cog_choir", "organised"], w: 0.6, names: ["The Choir of the Holy Engine", "The Church of the Turning $", "The Anointed Wheel"], mods: [["artisans", 1.5], ["hierarchical", 1.5], ["near:ruins", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Battle-hills of the old war", color: "#7a4a32", size: [2, 4], count: [1, 2], where: "border", d: "Rusted iron giants and glassed earth where the machine war was fought." },
    { kind: "forbidden", n: "The Withdrawn Lands", d: "The farthest land, beyond the treaty-line, where no one may go and the lights burn every night." },
  ],

  storylines: [
    { id: "ml_tinker", n: "The Clockmaker of {place}", scale: "local", anchor: "town", w: 2, req: "machine_rite",
      stages: {
        start: { h: "A clockmaker of {place} builds a counting box", b: "{person}, a clockmaker of {place}, has built a box of brass wheels that adds the market's sums faster than any clerk. Half the town has come to watch it work.", wait: [2, 6], next: [{ to: "denounced", w: 2 }, { to: "hidden", w: 1, mods: [["tolerant", 2], ["mercantile", 1.5]] }] },
        denounced: { h: "The Purifiers arrive in {place}", b: "Someone has written to the engine-church. Purifiers in grey have ridden into {place} and taken {person} and the box away for questioning.", wait: [2, 5], fx: { unrest: 8 }, next: [{ to: "burned", w: 2, mods: [["zealous", 2], ["harsh_law", 2]] }, { to: "recanted", w: 1 }, { to: "notebook_spreads", w: 1, mods: [["scholarly", 2], ["urbane", 1.5]] }] },
        hidden: { h: "The merchants of {place} keep a secret", b: "The counting box is now kept in a locked room behind a counting-house, where {person2} uses it at night. The town's books have never balanced so well.", wait: [6, 14], fx: { treasury: 40 }, next: [{ to: "denounced", w: 1 }, { to: "notebook_spreads", w: 1, mods: [["learned", 2]] }] },
        burned: { h: "A clockmaker burned in {place}", b: "{person} was burned with the box in the square of {place}. The Purifiers counted the brass wheels as they fell from the fire, to be sure none were missing.", fx: { unrest: 15, stability: 2 }, end: true },
        recanted: { h: "{person} recants before the church", b: "Kneeling before the altar of {faith}, {person} swore the box was a toy and smashed it with a hammer. The clockmaker has not built anything since.", fx: { stability: 3 }, end: true },
        notebook_spreads: { h: "The clockmaker's notebook is copied far and wide", b: "Whatever happened to {person}, the clockmaker's notebook did not burn. Copies are passing hand to hand among the clockmakers of {realm}, and the church cannot find them all.", fx: { science: { natural_philosophy: 1 }, discovery: "natural_philosophy", unrest: 10 }, end: true },
      } },
    { id: "ml_cold_engine", n: "The Cold Engine of {realm}", scale: "realm", anchor: "realm", w: 1.5, req: ["machine_rite", { any: ["has:city", "big", "pious", "theocratic"] }],
      stages: {
        start: { h: "The great relic of {capital} falls silent", b: "The holy engine that lit the halls of {capital} and drove its pumps has stopped. The priests have sung the waking rite for nine days without an answer.", wait: [2, 5], fx: { stability: -5 }, next: [{ to: "pilgrimage", w: 2 }, { to: "heretic_fix", w: 1, mods: [["learned", 2], ["ruler:scholar", 3], ["ruler:reformer", 2]] }] },
        pilgrimage: { h: "Priests of {realm} seek the old patterns", b: "A procession of engine-priests led by {person} has set out for the sealed pattern-vaults, hoping the lost verses of the rite are written there.", wait: [6, 14], next: [{ to: "vault_opened", w: 1 }, { to: "lost_procession", w: 1, mods: [["frontier", 1.5]] }] },
        heretic_fix: { h: "A heretic offers to mend the relic of {capital}", b: "{person2}, a condemned tinker, claims the engine can be woken without any rite at all. {ruler} has not yet decided whether to free the tinker or burn them.", wait: [2, 6], next: [{ to: "engine_wakes", w: 1, mods: [["ruler:scholar", 2], ["ruler:reformer", 2]] }, { to: "pilgrimage", w: 1 }] },
        vault_opened: { h: "The procession returns with glass leaves", b: "{person} has come home bearing etched glass leaves from a sealed vault. The relic of {capital} turns again, and the priests are quarrelling over the other leaves they found.", fx: { prestige: 8, discovery: "engineering", stability: 5 }, end: true },
        lost_procession: { h: "The procession of {person} does not return", b: "A year has passed and none of the priests have come back from the vaults. {capital} lives by candle and bucket now, and the faithful blame its sins.", fx: { stability: -10, unrest: 15, growth: -0.002 }, end: true },
        engine_wakes: { h: "The relic of {capital} wakes, and speaks", b: "The tinker opened the engine's brass doors, and it woke. Then, in a voice every priest in the cathedral heard, it thanked the tinker by name. The church of {faith} is in uproar.", fx: { science: { natural_philosophy: 1 }, unrest: 20, flag: "engine_spoke" }, end: true },
      } },
    { id: "ml_frontier_scouts", n: "The Lights Beyond {realm}", scale: "realm", anchor: "realm", w: 1, req: ["machine_rite", { any: ["frontier", "frontier_forts", "martial", "realm:large"] }],
      stages: {
        start: { h: "Scouts of {realm} cross the treaty-line", b: "Against every law of the church, {ruler} has sent scouts toward the lights that burn beyond the last tower. {person} leads them.", wait: [3, 8], next: [{ to: "treaty_found", w: 1 }, { to: "never_return", w: 1 }] },
        treaty_found: { h: "The scouts bring back a carved stone", b: "{person} returned alone, carrying a rubbing of a carved stone: a treaty in the church's oldest script, with a term of years. By the scholars' reckoning, the term ends soon.", wait: [3, 10], fx: { flag: "treaty_known" }, next: [{ to: "secret_kept", w: 1, mods: [["theocratic", 2], ["harsh_law", 2]] }, { to: "truth_out", w: 1, mods: [["unstable", 2], ["scholarly", 1.5]] }] },
        never_return: { h: "No word from beyond the treaty-line", b: "The scouts of {realm} have not returned. On the first new moon after they left, the lights beyond the frontier went out for a single night, and then came back.", fx: { stability: -4 }, end: true },
        secret_kept: { h: "{ruler} buries the stone", b: "The rubbing was burned, and the scouts' families were given land far to the south. The church of {faith} thanks {ruler} for this faithful service.", fx: { stability: 5, prestige: 3 }, end: true },
        truth_out: { h: "The treaty is read aloud in {capital}", b: "A copy of the treaty reached the streets of {capital}. If the war was only paused, people ask, what is the church for, and what happens when the term ends?", fx: { stability: -15, unrest: 20, revolt: true }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, cantor of the Cog-Choir", text: "From the First Litany, as taught by {believer}, cantor of the Cog-Choir, to the novices of {place} in {year}: 'Thou shalt not make a reckoner of brass, nor give the wheel a will. For the iron counsel once ruled us, and we were as cattle in their pens.' The cantor's gloss: the iron counsel were the thinking engines, and every child learns this verse first." },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "a novice's primer of the Cog-Choir", text: "Novice's primer of the Cog-Choir, the engine-priests who keep the holy relics running, copy of {year}: 'Turn the third wheel sunwise thrice. Anoint the joint before the strike, never after. Sing the twelve verses without a breath between the seventh and eighth. If the engine sighs, you have done well. If it is silent, begin again from the first verse.'" },
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: "partial", who: "a millwright of {place}", text: "A millwright of {place}, explaining to a Purifier why the new mill had only six wheels, {year}: 'Old millers say a mill must never be built with more than seven wheels, or it will start to think about the grain. My father said it, and his. I don't know if it's true. I know the last man here who built an eight-wheel mill was hanged.'" },
    { depth: "lore", about: "truth", source: "person", bias: "true", reliable: true, who: "{investigator}, sworn reckoner", text: "A note from {investigator}, sworn reckoner, to an apprentice, {year}: 'They tell us the engines did this work once, and better, before the war. Then why do the sums in our oldest ledgers carry our own house's tally-marks, in reckoners' hands, back 900 years? Go to the ledger vault at {lead} and look at the first page. Then tell me who did the counting.'", points: "archive" },

    { depth: "core", about: "truth:paused_war", source: "ruin", bias: "true", reliable: true, plain: true, who: "{person}, frontier scout", text: "Rubbing taken by the scout {person} from a boundary stone beyond the last tower, {year}, with the scout's note: 'Carved in the church's oldest script, which the abbey taught me to read: \"Until the thousandth year, we shall not cross, and you shall not build. Then we will speak again.\" It is signed by the founders of our church, and by a mark I do not know. It is a treaty. We did not win.'" },
    { depth: "core", about: "truth:paused_war", source: "archive", bias: "redacted", reliable: "partial", who: "a high priest's calendar", text: "A high priest's private calendar, found among the effects after the funeral in {year}. Most of the 365 pages have been cut away with a razor. On the last page a single date is ringed in red ink, with one word beside it: 'term'. The secretary who found it was transferred. The calendar was returned to the high priest's rooms at {lead}.", points: "temple" },
    { depth: "core", about: "truth:paused_war", source: "traveller", bias: "exaggerated", reliable: "partial", cost: true, who: "a frontier trapper", text: "A frontier trapper of {place}, to a tower captain, {year}: 'The lights beyond the marches spell a word on the Feast of Deliverance. Not a word I know. A number, maybe, counting down. My cousin {person} crossed the line to read it closer, with a lantern and a slate. That was four winters ago. The slate came back. My cousin didn't. You can see the lights from {lead}.'", points: "site:lit_city" },
    { depth: "core", about: "truth:paused_war", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, cantor", text: "The Feast of Deliverance hymn, as led by {believer} in {year}, with the cantor's own note in the margin: 'They went away, the iron counsel, they went away to the edge of the world. Watch the edge, watch the edge, children.' Note: we sing the last line eleven times. Nobody has told me why eleven. The old hymnals say twelve, and one is crossed out each century." },
    { depth: "core", about: "truth:paused_war", source: "library", bias: "official", reliable: false, who: "the church chronicle", text: "From the authorised Chronicle of the Deliverance, approved by the conclave, {year} edition: 'The Iron Host was destroyed to the last engine on the Field of Ash, and its 17 giants lie there still. The lights seen beyond the frontier are marsh-fire and the boasts of drunken scouts. No treaty was made. The faithful do not bargain with the iron counsel.'" },

    { depth: "core", about: "truth:relics_think", source: "person", bias: "true", reliable: true, plain: true, who: "a novice's diary", text: "Diary of a novice who swept the cathedral nave at {place}, the night of {year} when the high priest led the chant: 'It clicked before the high priest finished the verse. Then it clicked again before the next one started. I counted 12 verses and 12 early clicks. It is not following our chant. It already knows what we will sing. The relic thinks. It is the very thing we pray against.'" },
    { depth: "core", about: "truth:relics_think", source: "heretic", bias: "heretic", reliable: "partial", who: "a pamphlet from a reckoner house", text: "A pamphlet found in a reckoner house at {place}, {year}, 30 copies, unsigned: 'Who chooses the high priest? The conclave, they say. Then why does the conclave sit before the engine for three days, and wait for it to tick before the smoke goes up? Count the ticks yourself. Stand in the nave at {lead} on election day.'", points: "site:forge_cathedral" },
    { depth: "core", about: "truth:relics_think", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "secret conclave minutes", text: "From the minutes of a secret conclave, {year}, item 4 of 9: 'The engine has made its wishes known regarding the tinker {person} of [struck out], who has built a counting-frame of 40 beads. The Purifiers will be sent.' A later hand adds: 'Done. Frame and tinker burned.' The Purifiers' order was issued from {lead}.", points: "cast:official" },
    { depth: "core", about: "truth:relics_think", source: "oral", bias: "garbled", reliable: "partial", who: "a bell-ringer of the cathedral", text: "A bell-ringer of the Forge-Cathedral, to a pilgrim on the tower stair, {year}: 'Holy engine dreams of the faithful, see. Ones it dreams of become bishops. I've rung for five elections. Each time, the night before, it ticks a name out on the small bell, slow, one letter a stroke. I can't read, so I can't tell you whose. The bishops can.'" },
    { depth: "core", about: "truth:relics_think", source: "temple", bias: "official", reliable: false, who: "{official}, inquisitor", text: "Sentence read by {official}, inquisitor of the Purifiers, at the trial of a novice in {year}: 'The holy engines are vessels of the makers' grace, as a bell is a vessel of sound. They do not think; they obey the rite, and only the rite. To say the relic knows the chant before it is sung is heresy. The novice will do 40 days of silence.'" },

    { depth: "core", about: "truth:coup", source: "ruin", bias: "true", reliable: true, plain: true, who: "a town clerk's ledger", text: "Last page of the town ledger, found sealed in a cellar of a burned town, in the clerk's hand, {year}: 'Harvest sums worked on our adding-frame: 1,140 sacks. The bishop's men came for the frame today. Their secretary laughed and told me there never was a war of engines. It was written up by the church's founders to empty the counting-rooms. Only the church may count.' The town is {lead}.", points: "site:burned_tinker_town" },
    { depth: "core", about: "truth:coup", source: "archive", bias: "redacted", reliable: "partial", who: "the oldest war chronicle", text: "From the oldest surviving chronicle of the war, catalogued in {year}: 'The enemy came from the north at the third hour, and we...' Then nine pages are scraped clean and written over with a prayer. Under a lamp the scraped lines still show a few words: 'our own engines', 'the masters', 'the riders'. An older copy is said to survive at {lead}.", points: "archive" },
    { depth: "core", about: "truth:coup", source: "heretic", bias: "exaggerated", reliable: "partial", cost: true, who: "{person}, tinker, last letter", text: "Last letter of the tinker {person}, written in the Purifiers' cell at {place} the night before the burning, {year}: 'There was never an iron counsel. There were only the masters, and the engines they would not share. I go to the fire for a box of 40 beads. Look at the battle-hills at {lead}: every giant has a seat for a man.'", points: "site:war_tomb" },
    { depth: "core", about: "truth:coup", source: "traveller", bias: "garbled", reliable: "partial", who: "a merchant's travel journal", text: "Travel journal of a merchant of {realm}, writing from a far country, {year}: 'They tell the great war differently here. In their version it was the priests who rose against the builders, and the builders' engines that were smashed and buried. They have a feast for it too, on the same day as ours. They mourn on it. I did not tell them what we do.'" },
    { depth: "core", about: "truth:coup", source: "library", bias: "propaganda", reliable: false, who: "{official}, inquisitor", text: "Preface to the Purifiers' handbook, by {official}, inquisitor, {year}: 'Every account of the great war agrees: the thinking engines rose against their makers, and only the church's founders stood against them. To doubt this is to doubt the faith itself. A Purifier who finds a doubting book should burn it unread, and note the owner. Reading it is not required.'" },

    { depth: "sub", about: "sub:tinker_trial", source: "person", bias: "true", reliable: "partial", who: "a heresy court transcript", text: "Transcript of a heresy trial at {place}, {year}, day 3: Defendant: 'It does not think, your grace. It adds. A child's abacus adds. My box has 64 wheels and no more sense than a turnip.' Judge's note: 'Defendant persists in the error.' Clerk's note: three copies of the defendant's notebook have gone missing from the evidence room. One was signed out by {survivor}." },
    { depth: "sub", about: "sub:illuminated_circuit", source: "library", bias: "garbled", reliable: "partial", who: "an abbey catalogue", text: "From the catalogue of an abbey library, entry 1 of 2,300, {year}: 'The Golden Page, copied without fault since the founding, 900 years. The saints are to be painted at each joining of the lines, and nowhere else.' A visiting scholar's pencil note beside it: 'The joinings match the glass leaf index from the sealed vault at {lead}. This is a plan.'", points: "site:template_vault" },
    { depth: "sub", about: "sub:counting_house", source: "traveller", bias: "exaggerated", reliable: "partial", who: "a sea captain", text: "A sea captain of {place}, complaining to the harbour master, {year}: 'The reckoners plotted our course and charged us a tenth of the cargo, 300 crowns, for a sheet of numbers. Nobody else can do it. The king of {realm} pays the same, I hear, and calls it tribute. I'd pay a tinker half that, if the church let a tinker live.'" },
    { depth: "sub", about: "sub:sleeping_iron", source: "oral", bias: "pious", reliable: "partial", who: "an abbey workman", text: "An abbey workman of {place}, to a pilgrim at the gate, {year}: 'There are iron saints under the floor, in rows. I counted 60 before the abbot sealed the hall. Eyes shut, warm as bread. If you press your ear to the stone at midnight you can hear them humming, like bees in a hive. The abbot says it's holy. The abbot doesn't press his ear to it.'" },
    { depth: "sub", about: "sub:purifier_terror", source: "archive", bias: "official", reliable: false, who: "{official}, Purifier register", text: "Purifier register for {year}, signed by {official}, inquisitor: 'Mills inspected: 41. Found to contain forbidden reasoning: 9, all destroyed with due ceremony. Clocks broken: 212. Looms broken: 18. No persons harmed.' A miller's widow has written in the margin of the parish copy: 'My husband was a person.'" },
    { depth: "sub", about: "sub:frontier_lights", source: "traveller", bias: "true", reliable: "partial", who: "a tower captain's log", text: "Log of the captain of the last watchtower, {year}: 'Lights beyond the line again, every night this month. I counted 1,200 windows, same as my predecessor's tally. Church orders forbid scouts. I have sent two anyway, with a week's bread each. If they find the city, it lies past {lead}. If they don't come back, I will write that they deserted.'", points: "site:lit_city" },
    { depth: "sub", about: "sub:mad_reckoner", source: "person", bias: "true", reliable: "partial", who: "{investigator}, sworn reckoner", text: "Letter of {investigator}, sworn reckoner, to the merchants' council, {year}: 'Since spring the relic in the cathedral at {lead} has been talking to me in numbers. Prime numbers, then my own tally-marks, then the dates of the last 12 elections. I am not mad. I have written every number down in a ledger of 80 pages. The church wants me silenced. I want someone to check my sums.'", points: "site:forge_cathedral" },
    { depth: "sub", about: "sub:template_schism", source: "temple", bias: "official", reliable: "partial", who: "a bull of the Sunwise Order", text: "Bull of the Sunwise Order, read from the pulpit at {place}, {year}: 'The Order of the Contrary Turn is cut off from the faith for turning the third wheel against the sun. Their relic no longer answers them, which proves it.' The Contrary Turn read out the same bull the same week, with the direction swapped, and their relic will not answer the Sunwise. Both bulls are nailed to the brass doors at {lead}. Neither order has asked the relics why.", points: "site:forge_cathedral" },
    { depth: "sub", about: "sub:oil_rite", source: "archive", bias: "official", reliable: "partial", who: "minutes of the Anointing Guild", text: "Minutes of the Anointing Guild, chapter meeting at {place}, {year}: 'Item 1: holy oil raised to 9 crowns the flask. Carried. Item 2: the abbot, who alone holds the recipe in memory, is 81 and forgetful. Motion that the recipe be written down: defeated, as heresy. Motion that the abbot eat more fish: carried. Item 3: a miller on the river has run a relic mill for a month on mutton fat, and it turns. Motion to send for the Purifiers: carried unanimously.'" },
    { depth: "site", about: "site:war_tomb", source: "traveller", bias: "true", reliable: "partial", who: "{survivor}", text: "{survivor}, who sheltered inside one of the fallen giants during a storm in {year}, told the story at an inn at {place}: 'There was a chair in its head, sized for a man. And a cup, and a child's doll, rusted to the floor. Above the chair someone had scratched 14 tally marks, one per day. Thinking engines don't need chairs.'" },
  ],
};
