// The Watchers in the Dark: the sky is silent because something listens, and every few thousand years it comes
// to reap whatever has grown tall. Bridge premise: under a medieval world the relic gates are the gods' waystones,
// the reapings are the ends of past ages, and the hidden watchers are the curse that spoils every scholar's sums.
export default {
  id: "watchers_in_the_dark",
  name: "The Watchers in the Dark",
  family: "scifi",
  pitch: "The night sky is silent because every people that ever signalled to it was found and destroyed. The ancient relics that help each new age grow great were left by the destroyers, so they know where to strike next.",
  slots: ["apocalypse", "history-secret"],
  tone: ["horror", "grim"],
  era: ["medieval", "renaissance", "post-collapse", "far-future"],
  scale: "world",
  genres: ["farfuture", "fantasy", "grimdark"],
  bridge: true,
  w: 0.9,
  excludes: ["wheel_of_suns"],
  pairs: [{ id: "seed_engine", w: 3 }, { id: "elder_lattice", w: 2.5 }, { id: "arithmetic_of_ages", w: 2 }, { id: "unremembering", w: 2 }, { id: "machine_liturgy", w: 1.5 }],

  truths: [
    { id: "cycle", n: "The relics are bait", d: "Every few thousand years an outside power, the harvesters, sweeps the world and destroys every people that has grown great. The harvesters left the waystones, towers and other relics on purpose: each age builds its capitals around the rings and lights them, and a lit ring tells the harvesters where to strike and when. Seven ages have fallen this way, and this one has lit more rings than any.", tags: ["truth:watchers_cycle"],
      known: [
        "The oldest relic of {realm} carries a column of dates, thousands of years apart, each followed by the glyph for 'again'. Old cities lie buried beneath the modern capitals. Nobody has yet explained why each one ended, or what the dates count.",
        "Digs under the unnamed city found three cities stacked on the same plan, each built around a waystone ring, each ending on a single day. The academy blacked out the date and calls it ordinary decline, war and plague.",
        "A woman sealed in a tomb from the last age says her people lit every ring before they fell, and begs us not to light ours. The oldest reading of the weeping pillar says the same. The academy has ordered 12 new rings.",
        "Confirmed: the relics were left by the harvesters who end each age. Every age builds its capitals around the rings, and the harvesters come when the rings are all lit. {official} keeps the ring register, and the count is nearly full.",
      ] },
    { id: "hush", n: "We were heard", d: "Long ago a learned society built a tower to signal the stars, and the harvesters answered by sending watchers too small to see. The watchers spoil weighings, sums and experiments so that learning can never advance far enough to fight back, and every academy has lost lifetimes of work to them. They will keep at it until their masters arrive, and the beacon-kindlers are signalling again.", tags: ["truth:watchers_hush"],
      known: [
        "For a generation, scales and astrolabes in the academies of {realm} have given a different answer each time they are used. Some fellows blame worn brass and tired eyes. Others have burned their tables. Nobody can show why it happens.",
        "The followers of the Hush keep their towns dark and quiet, because they say the sky is listening. Their catechism names a burned tower on a mountain peak, built long ago to flash signals at one star.",
        "The tower's log ends with a reply: a cloud of specks came down the signal beam, and the next entry says 'they are here, and they are small.' Reckoners in counting-houses now report sparks at the edge of sight.",
        "Confirmed: this world was heard. The watchers sent in answer are already here, too small to see, and they spoil every measurement so learning stalls. They will keep at it until their masters arrive, and {believer} has 200 kindlers polishing a mirror wider than a barn.",
      ] },
    { id: "mind_toll", n: "The roads run on minds", d: "The waystones are fed by the minds of those who use them: every crossing takes some memory from the traveller, and the rings pass it on to a power far away. The crown's courier corps has known for generations and simply recruits from the provinces to replace the hollowed. The busier the roads, the better fed the collector.", tags: ["truth:watchers_toll"],
      known: [
        "Royal couriers who cross by waystone often retire young, confused and forgetful. The crown says it is the ordinary fatigue of long service. In the corps' own register of retirements, the cause has been struck out.",
        "{investigator}, physician to the courier corps, tested couriers with lists of words before and after a crossing. Every one lost words, and none got them back with rest. The crown has the report and has not answered it.",
        "One ring on a remote moor has no twin in any register. Couriers sent through it came back years older and empty. Someone keeps chalking on the rings: 'every step a memory'. The chalk is scrubbed off within a day.",
        "Confirmed: the waystones run on travellers' memory, and the stolen memory feeds a power far away. {survivor} paid with most of a life. The crown pays the fare in provincial recruits, 200 a year, and keeps the roads open.",
      ] },
  ],

  cast: [
    { role: "investigator", n: "a physician-philosopher of the royal academy, physician to the courier corps", home: "capital", stance: "Measures everything twice and wants the crown to read what the numbers say, even if it costs the post." },
    { role: "official", n: "the crown's chancellor of relics, who governs the waystone register, the courier corps and the academy's charters", home: "capital", stance: "Believes the rings hold the realm together, and that a panic would cost more lives than the fare." },
    { role: "believer", n: "a beacon-kindler preacher who builds signal mirrors on hilltops", home: "mountain", stance: "Is sure the silent stars are only lonely, and that answering them will end all our fear." },
    { role: "survivor", n: "a retired royal courier who crossed by waystone for eleven years", home: "inner", stance: "Wants back the names the rings took, and wants the young couriers stopped before they lose theirs." },
  ],

  tags: ["harvest_cycle"],

  subthemes: [
    { id: "lying_instruments", n: "The Lying Instruments", d: "For a generation, every astrolabe, balance and alembic in the great academies has given a different answer each time it is used. Some scholars have burned their books; two have hanged themselves.", w: 1.1, req: { any: ["scholarly", "learned", "academies", "faith:philosophy"] }, truthLink: "hush", tags: ["theme:lying_instruments"] },
    { id: "beacon_kindlers", n: "The Beacon-Kindlers", d: "A joyful cult builds great fires and polished mirrors on the hilltops to signal the sky. They say the silent stars are only lonely, and that someone is coming to save us.", w: 1, mods: [["mystic", 2], ["seers", 2], ["zealous", 1.5], ["faith:stars", 2]], tags: ["theme:beacon_kindlers"] },
    { id: "late_warning", n: "The Warning in the Stone", d: "Scholars have at last read the long inscription on the oldest relic of the realm. It is a list of seven dates, thousands of years apart, and a word repeated after each: 'again'.", w: 1, mods: [["near:ruins", 2], ["scholarly", 1.5]], truthLink: "cycle", tags: ["theme:late_warning"] },
    { id: "glassed_country", n: "The Glassed Country", d: "A whole country lies fused to green glass, smooth as a lake, with the outlines of towers still standing in it like flies in amber. No chronicle records a war there.", w: 1.2, mods: [["desert", 2], ["badlands", 2], ["realm:large", 1.3]], tags: ["theme:glassed_country"], mark: { kind: "zone", n: "The Glassed Country", color: "#7fa89a", size: [2, 4], where: "desert" } },
    { id: "last_age_sleeper", n: "The Sleeper of the Last Age", d: "A woman has climbed out of a sealed tomb speaking a tongue no one knows, and wept when she saw the waystones lit. She is learning ours quickly.", w: 0.7, mods: [["near:ruins", 2], ["ancestor_bound", 1.5]], tags: ["theme:last_age_sleeper"] },
    { id: "waystone_lords", n: "The Waystone Lords", d: "The lords who keep court beside the great relics grow serene, distant and strangely united. Their counsel always favours more relics, more roads, more reaching.", w: 1, req: { any: ["autocracy", "monarchy", "gov:empire", "near:ruins"] }, truthLink: "cycle", tags: ["theme:waystone_lords"] },
    { id: "sealed_counsellors", n: "The Sealed Counsellors", d: "Fearing the watchers hear every council, the crown has named a few counsellors with absolute power and no duty to explain. No one, not even the crown, knows what they are planning.", w: 0.8, req: { any: ["autocracy", "spy_network", "gov:absolute", "gov:empire"] }, truthLink: "hush", tags: ["theme:sealed_counsellors"] },
    { id: "unlit_cities", n: "The Unlit Cities", d: "By law, no lamp may burn after dark, no tower may rise above the trees, and no bell may ring at night. The people say it keeps the sky from noticing them.", w: 1, mods: [["pious", 1.5], ["insular", 2], ["isolation", 2], ["harsh_law", 1.5]], truthLink: "hush", tags: ["theme:unlit_cities"], mark: { kind: "zone", n: "The Darkened Reach", color: "#2e3240", size: [1, 3], where: "inner" } },
    { id: "waystones", n: "The Waystone Roads", d: "Rings of black stone let a traveller step from one end of the realm to the other in a breath. Empires are built around them, and nobody alive knows who raised them.", w: 1.3, mods: [["gov:empire", 2.5], ["great_roads", 2], ["mercantile", 1.5], ["near:ruins", 1.5]], truthLink: "mind_toll", tags: ["theme:waystones"], mark: { kind: "zone", n: "Waystone ring", color: "#4a4058", size: [1, 1], where: "capital" } },
    { id: "hollow_couriers", n: "The Hollow Couriers", d: "Royal couriers who cross by waystone ten times a month are the fastest in the world. After a few years they forget their children's names, then their own, then how to want anything.", w: 0.9, truthLink: "mind_toll", tags: ["theme:hollow_couriers"] },
    { id: "exodus_ships", n: "The Secret Exodus", d: "A great house has been quietly building ships and buying charts of the empty ocean. Its rivals say it is fleeing something it will not name.", w: 0.7, req: { any: ["coastal", "has:port", "seafaring"] }, tags: ["theme:exodus_ships"] },
    { id: "pale_envoy", n: "The Pale Envoy", d: "A courteous stranger with no shadow has come to the court offering peace, plenty and an end to all fear, on one condition no one will repeat aloud.", w: 0.6, tags: ["theme:pale_envoy"] },
  ],

  sites: [
    { id: "unnamed_city", n: "The Unnamed City of $", kind: "ruin", where: "remote", truthLink: "cycle", d: "A city larger than any living capital, abandoned whole, its every name and face chiselled away.",
      layers: {
        surface: { n: "Thrown towers", text: "The towers of the unnamed city are pale stone. All 40 that survey parties have counted lie in neat rows, every one fallen east to west, as if knocked down by a single blow from above. Every carved name and face has been chiselled off. Herders shelter in the fallen towers and leave a copper on the threshold." },
        study: { n: "The street plan", text: "{investigator} paced out the streets over one summer and drew them on six sheets. They spread from a central square around a waystone ring, the same plan as every capital in {realm}. The ring is cracked across and cold to the touch. Nobody has stepped through it in living memory." },
        dig: { n: "The second city", points: "archive", text: "Under the central square, at 40 feet, lies a second city on the same plan, and under that a third. Each has an archive of clay tablets. All 300 tablets in the third city stop mid-sentence on the same date. The academy carted the best of them to {lead} and sealed the crates." },
        revelation: { n: "Three ages, one road", text: "This people built on the same rings we use, grew great, and were wiped out from above in a day; so were the two cities beneath. The tablets name the ring-masters who lit the last rings and asked the council for more. The register of {realm} lists 12 new rings for this decade." },
      } },
    { id: "weeping_pillar", n: "The Weeping Pillar of $", kind: "wonder", where: "mountain", truthLink: "cycle", d: "A pillar of dark glass that sings one phrase over and over, in what sounds like a crowd speaking at once.",
      layers: {
        surface: { n: "The pilgrims", text: "Pilgrims climb to hear the pillar of dark glass sing one phrase, over and over, like a crowd speaking at once. The song makes children cry and dogs howl. The shrine-keepers sell two kinds of wax earplugs at the gate, and the dearer kind works." },
        study: { n: "Slowed speech", text: "A scholar caught the song on a turning wax drum and played it back a thousand times faster. It is speech: many voices saying one short sentence together. The shrine keeps a book of each age's translation. There are five entries, and no two agree." },
        dig: { n: "The builders", points: "site:unnamed_city", text: "In the pillar's root lie 140 skeletons in rows, every skull turned to the same patch of sky. Each pair of hands holds a small black ring, cut from waystone, the size of a bracelet. The rows are laid out in the street plan of the dead city at {lead}." },
        revelation: { n: "The last warning", text: "The last people to be reaped built the pillar while they waited for the end. Its sentence is: do not use the gifts, do not grow tall, they are coming back. Our age translated it as 'Welcome', and {official} had that word carved over the shrine gate in gold." },
      } },
    { id: "orphan_gate", n: "The Gate Without a Road at $", kind: "anomaly", where: "remote", truthLink: "mind_toll", d: "A waystone ring that leads to no ring in any register.",
      layers: {
        surface: { n: "Warm stones on the moor", text: "A waystone ring stands alone on a moor: twelve black stones in a circle, warm to the hand even in snow. Its centre hums at the pitch of a held note. Sheep will not graze within 30 paces, and the shepherds have marked the line with cairns." },
        study: { n: "No twin", text: "Every other ring in the register has a twin, and stepping through one brings you out at the other. The office of {official} searched its ledgers for a year and found no twin for this one. Its page in the register is blank except for a pencilled question mark." },
        dig: { n: "Couriers on a rope", points: "cast:investigator", text: "Three volunteer couriers stepped through on a rope. Each came back within minutes, a decade older, unable to say where they had been or to name their own mothers. One held a scrap of cloth woven in no known pattern. The physician's notes on all three went to {lead}." },
        revelation: { n: "Where the fare goes", text: "The waystones carry no one for free. Every crossing takes some memory, every ring sends what it takes here, and this gate passes it on to the far power that collects it. The courier corps has known for 80 years. {official} pays the fare in provincial recruits, 200 a year." },
      } },
    { id: "pressed_land", n: "The Pressed Land of $", kind: "anomaly", where: "desert", d: "A plain where everything, stones, trees, a whole village, has been pressed flat as a painting on the ground.",
      layers: {
        surface: { n: "Pictures on the ground", text: "Across four miles of plain, houses, trees and people lie flat on the earth, thin as paint and perfectly detailed. A woman is drawing water; a dog is caught mid-leap. Caravans go around the plain rather than across it, which adds two days to the salt road." },
        study: { n: "No depth", text: "Surveyors pushed a knife into a pressed doorway. The blade passed through as through a shadow and came out clean. No gauge can find any thickness in the shapes, and rain does not wash them away. Local children dare each other to stand on the pressed faces." },
        dig: { n: "The cut well", points: "site:answering_tower", text: "At the plain's edge the flattening stops in a straight line. The line cuts a stone well exactly in half: one side round and deep, the other a picture. Surveyors chained the edge for nine miles. It runs dead straight, aimed at {lead}." },
        revelation: { n: "A warning shot", text: "In the tower's sixth year of signalling, a weapon from the sky flattened this village of 400, who had nothing to do with the tower. The cut points straight at it. It was a warning. The keeper on the peak still wrote 'no reply'. The society in the city voted it a greeting and paid for a larger mirror." },
      } },
    { id: "answering_tower", n: "The Answering Tower of $", kind: "ruin", where: "mountain", truthLink: "hush", d: "A burned tower on a peak, built to call to the stars, whose builders vanished.",
      layers: {
        surface: { n: "The burned tower", text: "A blackened tower stands on the peak, crowned by a broken mirror twenty feet across, still aimed at a single star. Lightning does not explain the fire: the stair is burned from the top down. Goats shelter in the lower rooms, and the kindlers leave candles at the door." },
        study: { n: "The signal log", text: "The builders kept a log of their signals for nine years, in fourteen bound volumes. Each entry gives the star, the pattern flashed and the weather. Every entry ends 'no reply', in the same patient hand, until the last volume." },
        dig: { n: "The last page", points: "archive", text: "The last page records a reply: a cloud of specks that came down the beam. The next entry, in another hand, says only: 'they are here, and they are small.' A note inside the cover names the learned society that paid for the tower. Its minutes are kept at {lead}." },
        revelation: { n: "Who called", text: "A learned society built this tower to greet the stars, and the harvesters answered by sending watchers too small to see. Since then every scale, astrolabe and sum in the world has been quietly spoiled, so learning cannot pass a certain point. The society's founder signed the first signal. {believer} is building a new mirror." },
      } },
  ],

  beings: [
    { id: "hollowed", n: "The hollowed", kind: "beast", d: "People who lingered too long beside the great relics: calm, smiling, utterly obedient to something no one else can hear. They wander towards waystones and wait there.", danger: 2, biomes: ["grass", "tempforest", "badlands", "desert", "coldsteppe"], look: { size: 1.7, group: [1, 8], move: "herd", speed: 3, col: "#b8b4b0", col2: "#3a3448", body: "biped", active: "any", visible: true } },
    { id: "motes", n: "Watcher-motes", kind: "insect", d: "Specks of light seen only in the corner of the eye, gathering around scholars, instruments and anyone who stares at the sky too long.", danger: 0, biomes: ["grass", "tempforest", "alpine", "desert", "tundra", "river"], look: { size: 0.001, group: [10, 200], move: "swarm", speed: 20, col: "#e8e8ff", col2: "#8a8aff", body: "insect", active: "night", visible: false } },
    { id: "ring_keeper", n: "Ring-keeper", kind: "beast", d: "A tall, faceless figure of black stone that tends the waystone rings, mending cracks and turning away those who would deface them. It has never been seen to speak or to hurry.", danger: 1, biomes: ["grass", "badlands", "alpine", "desert", "tempforest"], look: { size: 2.8, group: [1, 1], move: "solo", speed: 2, col: "#1e1c24", col2: "#5a4a7a", body: "biped", active: "night", visible: true } },
  ],

  techs: [
    { id: "wd_waystone_lore", n: "Waystone lore", field: "navigation", level: 1, d: "The rites and tables for stepping between the black rings, learned from the ancients' marks." },
    { id: "wd_glyph_reading", n: "Reading the last age", field: "writing", level: 2, d: "Scholars decode the warning glyphs of the previous age, and learn to fear what they say." },
    { id: "wd_dimming", n: "The dimming", field: "architecture", level: 3, d: "Shuttered towns, smoke-veils and low roofs: the craft of making a realm invisible from above." },
    { id: "wd_blind_sums", n: "Blind experiments", field: "natural_philosophy", level: 4, d: "Trials run in sealed lead rooms by lot and dice, so that whatever spoils the sums cannot know which sum to spoil." },
    { id: "wd_stoneless_roads", n: "Roads without stones", field: "engineering", level: 4, d: "A deliberate return to canals, post-horses and ships, so the realm need not pay the waystones' toll." },
    { id: "wd_cycle_breaker", n: "The breaking of the cycle", field: "warfare", level: 5, d: "Weapons and plans made in total secret by people who trust no one, meant to meet the harvesters when they come." },
  ],

  units: [
    { id: "wd_ring_guard", n: "Ring guard", role: "infantry", wpn: "pike", kit: "plate", ranks: 4, gap: 1.1, size: 100, w: 0.6, mods: [["theme:waystones", 6], ["theme:waystone_lords", 3]] },
  ],

  faiths: [
    { id: "wd_hush", n: "The Hush", d: "The sky is full of listening, and the holy life is a quiet one: small towns, low roofs, dark nights and no calling out.", tags: ["faith:wd_hush", "organised"], w: 0.5, mods: [["theme:unlit_cities", 8], ["ascetic", 2], ["insular", 2]],
      names: ["The Hush of $", "The Quiet Covenant", "The Lightless Way"] },
  ],

  mapMarks: [
    { kind: "zone", n: "Glassed waste", color: "#86ad9e", size: [1, 3], count: [1, 2], where: "desert", d: "Land fused to green glass by a blow from the sky that no chronicle remembers." },
  ],

  storylines: [
    { id: "wd_beacon", n: "The Beacon of {place}", scale: "local", anchor: "town", w: 1.2, req: "harvest_cycle",
      stages: {
        start: { h: "Beacon-kindlers raise a great mirror at {place}", b: "On the hill above {place}, {believer} and the kindlers are building a mirror wider than a barn, to flash a greeting at the silent stars.", wait: [3, 8], next: [{ to: "lit", w: 2 }, { to: "torn_down", w: 1, mods: [["theme:unlit_cities", 4], ["harsh_law", 2], ["zealous", 1.5]] }] },
        lit: { h: "The mirror of {place} flashes at the sky", b: "Every clear night, the great mirror blinks its pattern at one star. Crowds come from far away to watch, and the kindlers sing.", wait: [6, 14], next: [{ to: "answered", w: 1 }, { to: "nothing", w: 1.5 }, { to: "torn_down", w: 0.7 }] },
        torn_down: { h: "The mirror of {place} is smashed", b: "Men with hammers came in the night. {believer} was found the next morning sitting in the broken glass, saying over and over that it was too late anyway.", fx: { stability: 2, unrest: 4 }, end: true },
        nothing: { h: "The kindlers of {place} give up", b: "Years of signalling and not one answer. The mirror is dull with bird-droppings, and {believer} has gone back to farming.", fx: { stability: 1 }, end: true },
        answered: { h: "Something answers the mirror of {place}", b: "The star the kindlers signalled has moved. {believer} ran through the streets of {place} weeping for joy. The old women barred their doors.", fx: { unrest: 12, stability: -6, flag: "answered" }, end: true },
      } },
    { id: "wd_closing_ways", n: "The Closing of the Ways", scale: "realm", anchor: "realm", w: 1, req: ["harvest_cycle", { any: ["theme:waystones", "theme:hollow_couriers", "gov:empire", "great_roads"] }],
      stages: {
        start: { h: "The couriers of {realm} are forgetting", b: "A court physician, {investigator}, has shown that every royal courier who crosses by waystone loses a little memory each time. The court does not want to hear it.", wait: [2, 6], next: [{ to: "ways_closed", w: 1, mods: [["ruler:just", 2], ["learned", 2]] }, { to: "ways_kept", w: 1.5, mods: [["gov:empire", 2], ["mercantile", 1.5]] }] },
        ways_closed: { h: "{ruler} closes the waystones of {realm}", b: "By decree, the rings are walled up. Messages that took a breath now take a month, and distant provinces have begun to rule themselves.", wait: [6, 14], fx: { stability: -8, treasury: -40 }, next: [{ to: "fragment", w: 1.5, mods: [["realm:vast", 2], ["realm:large", 1.5]] }, { to: "slow_peace", w: 1 }] },
        ways_kept: { h: "{realm} keeps the waystones open", b: "{investigator} has been dismissed and the couriers ride on. In the palace, the hollow ones are given quiet rooms and kind nurses.", wait: [6, 18], fx: { treasury: 30 }, next: [{ to: "hollow_court", w: 1.5 }, { to: "ways_closed", w: 0.6 }] },
        fragment: { h: "The far provinces of {realm} break away", b: "Without the rings to bind them, the outer provinces have stopped sending taxes and started crowning their own lords.", fx: { revolt: true, stability: -12 }, end: true },
        slow_peace: { h: "{realm} learns to live without the ways", b: "Canals, post-horses and ships carry the realm's business now. The hollow couriers are healing, slowly; one remembered her son's name this spring.", fx: { stability: 5, discovery: "engineering" }, end: true },
        hollow_court: { h: "The court of {realm} grows very calm", b: "Half the ministers now cross by waystone daily. They agree on everything, smile often, and have ordered a new ring built in every town.", fx: { stability: 6, unrest: 8, flag: "hollow_court" }, end: true },
      } },
    { id: "wd_warning", n: "The Warning in the Stone", scale: "realm", anchor: "realm", w: 1, req: ["harvest_cycle", { any: ["theme:late_warning", "learned", "scholarly", "near:ruins"] }],
      stages: {
        start: { h: "Scholars of {realm} begin to read the oldest stone", b: "{person2} and a circle of scholars in {capital} believe they can finally read the inscription on the realm's oldest relic.", wait: [6, 14], fx: { science: { writing: 0.5 } }, next: [{ to: "read", w: 2 }, { to: "scholars_die", w: 0.8 }] },
        read: { h: "The inscription of {realm} is read", b: "It is a list of dates, each thousands of years apart, and after each one the same word: 'again'. The next date in the sequence is not far off.", wait: [2, 6], fx: { unrest: 8 }, next: [{ to: "prepare", w: 1, mods: [["ruler:just", 1.5], ["learned", 2], ["stable", 1.5]] }, { to: "suppressed", w: 1.5 }] },
        scholars_die: { h: "The scholars of the stone are found dead", b: "{person2} and the others were found in the reading room, unmarked, their notes burned to fine ash in a cold grate.", fx: { stability: -4, flag: "silenced_scholars" }, end: true },
        prepare: { h: "{ruler} orders {realm} to prepare", b: "Granaries in caves, books copied onto stone, a secret council of planners answerable to no one. Nobody knows quite what they are preparing for.", fx: { treasury: -50, stability: -3, discovery: "writing", flag: "preparing" }, end: true },
        suppressed: { h: "The reading of the stone is declared false", b: "The academy has disowned {person2}'s translation as a fevered error, and the stone has been curtained. The dates are still on it.", fx: { stability: 3, prestige: -2 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "truth", source: "oral", bias: "garbled", reliable: true, who: "the ferrymen of {place}", text: "An old saying of the ferrymen of {place}, told to children who ask about the stars: 'Every great age ends the same way. A long night, strange lights crowding the sky, and in the morning nobody left to say what happened.' The ferrymen add that the weeping pillar has counted seven such nights. Nobody on the river can say who first told them so." },
    { depth: "lore", about: "truth", source: "library", bias: "official", reliable: "partial", who: "academy primer, {year}", points: "site:orphan_gate", text: "From the academy primer for first-year students, {year}: 'The waystones are rings of black stone, twelve paces across. Stepping into one brings a traveller out at its twin ring in a single breath. They and the weeping pillars were raised by the ancients for the good of all who came after. 214 rings are registered, and every one has a twin.' A later hand has written in the margin: 'Not the one at {lead}.'" },
    { depth: "lore", about: "truth", source: "traveller", bias: "exaggerated", reliable: "partial", who: "{person}, salt-trader", text: "Travel journal of {person}, a salt-trader on the desert road south of {place}, {year}: 'Lay on my back by the fire and counted stars until dawn. I gave up past four thousand. The academy says there must be peoples out there by the thousand, and not one has ever sent a word. The guide, who has crossed this sand forty times, said the silence was the point. Then the guide put out our fire, and would not light another all the way to the coast.'" },

    { depth: "core", about: "truth:cycle", source: "ruin", bias: "true", reliable: true, plain: true, who: "{person}, keeper of old scripts", points: "site:weeping_pillar", text: "Translation filed by {person}, keeper of old scripts at the academy of {realm}, {year}: 'The oldest relic carries a column of seven dates, each about four thousand years apart. After every date is the glyph for again. Under the column is one plain line: The rings were given to us by the ones who came, and they came when every ring was lit. The same sentence is cut into the root of the pillar at {lead}. I have checked the count three times.'" },
    { depth: "core", about: "truth:cycle", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, dig report", points: "site:unnamed_city", text: "Dig report of {investigator} to the academy of {realm}, season of {year}, from the dead city at {lead}: 'Beneath the unnamed city, a second city at 40 feet. Beneath that, a third. Each is laid out around a waystone ring, in the same place as ours. We lifted 300 clay tablets from the third city's archive. Every one breaks off mid-line on the same day, which is [the rest of the page is blacked out by the academy censor].'" },
    { depth: "core", about: "truth:cycle", source: "heretic", bias: "heretic", reliable: "partial", who: "unsigned broadsheet, {place}", points: "cast:official", text: "Broadsheet nailed to the ring-house door in {place}, {year}, unsigned; 500 copies seized by the watch: 'The gifts of the ancients are bait. We build our capitals around the rings just as their makers planned, and the makers know to the day when we will be big enough to harvest. Fifty years ago {realm} had 30 lit rings. Now it has 90. Ask {official} at {lead} who ordered the rest.'" },
    { depth: "core", about: "truth:cycle", source: "person", bias: "true", reliable: "partial", cost: true, who: "Hesra, the tomb-sleeper, to {investigator}", text: "Words of the woman from the sealed tomb, called Hesra by the dig crew, taken down by {investigator}, {year}. Her first full sentence in our tongue: 'You have lit the stones. All of them. Why?' Later: 'My city had 90 rings. I was master of roads, and I lit the last one myself. Forty of us were sealed in the vault to warn whoever came next. I am the only one who woke. My two daughters were too young for the vault.'" },
    { depth: "core", about: "truth:cycle", source: "library", bias: "official", reliable: false, who: "academy council minutes, {official} presiding", text: "Minutes of the academy council of {realm}, {year}, {official} presiding. Item 4, the buried cities: of 31 sites surveyed, the council finds ordinary decline, war and plague, and no common date. Motion to publish the date on the third-city tablets: withdrawn. Item 5, the 12 new rings: approved, the relics being a proven blessing. Item 6: the censor's ink for the dig report, 14 silver, to be charged to the dig." },

    { depth: "core", about: "truth:hush", source: "ruin", bias: "true", reliable: true, plain: true, who: "last keeper of the signal tower", text: "Log of the signal tower on the peak, in the last keeper's hand, night 3,212: 'Reply received. Not light. A cloud of specks, finer than flour, came down our beam and into the tower. They went for the instruments first. The brass scale gives a new weight every time, and the star-glass a new sky. They harm our sums, not us. I believe they were sent to stop us learning until the rest of them arrive.' Next morning, in another hand: 'they are here, and they are small.'" },
    { depth: "core", about: "truth:hush", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, academician", text: "Letter of {person}, academician of {place}, to {investigator}, {year}: 'I have weighed the same brass stone two hundred times and had two hundred weights. It is not the scale; I have used six, from three makers. Someone, or some thing, is changing the result as I read it. Thirty-one years of my tables are worthless. I burned them this morning in the courtyard. Do not come to the funeral.'" },
    { depth: "core", about: "truth:hush", source: "temple", bias: "pious", reliable: "partial", who: "catechism of the Hush", points: "site:answering_tower", text: "From the catechism of the Hush, the faith of low roofs and dark nights, as taught to children in {place}, {year}: 'Why do we light no lamp after dark? Because the sky is not empty; it is listening. Who listens? Those who answered the tower. What keeps us safe? A small light in a quiet house is never noticed.' Question nine of forty names the tower: the burned ruin at {lead}." },
    { depth: "core", about: "truth:hush", source: "oral", bias: "garbled", reliable: "partial", who: "head reckoner, counting-house of {place}", text: "Card pinned above the desks of the counting-house of {place} by the head reckoner, {year}: 'If you see small sparks at the edge of your eye while reckoning, put down the pen and go outside for an hour. The sparks spoil the numbers. If you keep going, they spoil you. Clerk {person} kept going for three nights in spring and has not added a column since. The house is paying the clerk's rent.'" },
    { depth: "core", about: "truth:hush", source: "library", bias: "propaganda", reliable: false, who: "academy circular, issued by {official}", text: "Circular of the academy of {realm}, issued by {official}, {year}: 'The inconsistent results reported by certain academies arise from poor instruments and poorer method. Of 88 complaints received this year, all were traced to worn brass or tired eyes. Natural philosophy in {realm} has never been healthier. Fellows who publish further complaints will lose their stipend.'" },

    { depth: "core", about: "truth:mind_toll", source: "person", bias: "true", reliable: true, cost: true, who: "{survivor}, royal courier", text: "Journal of {survivor}, royal courier, found in a saddlebag at a ring-house, {year}: 'Crossed four times today, 41 this month. There is a name I used to say every night before sleeping. I have written it on the inside of this cover, so I will know whose it was. The physicians say rest will bring it back. It has not brought back the other six.'" },
    { depth: "core", about: "truth:mind_toll", source: "archive", bias: "redacted", reliable: "partial", who: "register of the courier corps", points: "cast:investigator", text: "Register of the royal courier corps, kept by the office of {official}, entry for {year}: 'Nineteen couriers retired this year for [condition struck out]. All nineteen were under thirty. Recommend raising recruitment from the provinces to 200 a year.' A loose sheet in the register, unsigned: 'Ask the corps physician at {lead} for the word-lists. The crown has a copy and will not read it.'" },
    { depth: "core", about: "truth:mind_toll", source: "heretic", bias: "exaggerated", reliable: "partial", who: "chalk on the ring at {place}", text: "Chalked on the black stones of the ring at {place}, {year}, and scrubbed off twice since: 'EVERY STEP A MEMORY. EVERY MEMORY A MEAL. WHO IS EATING?'" },
    { depth: "core", about: "truth:mind_toll", source: "library", bias: "official", reliable: false, who: "notice by order of {official}", text: "Notice posted in every ring-house of {realm} by order of {official}, {year}: 'Waystone travel is wholly safe. More than two million crossings are made each year without harm. The confusion seen in a few couriers is the ordinary fatigue of long service, and passes with rest. Spreading rumours to the contrary is an offence, fined at five silver a word.'" },
    { depth: "core", about: "truth:mind_toll", source: "archive", bias: "true", reliable: true, plain: true, who: "{investigator}, physician to the courier corps", points: "site:orphan_gate", text: "Report of {investigator}, physician to the courier corps, to the crown, {year}: 'I gave 60 couriers a list of 100 words, before one crossing and after it. Every one lost between two and five words, and rest did not return them. The rings take memory as their fare. Where it goes I cannot say. But the one ring with no twin, at {lead}, takes ten years at a step.'" },

    { depth: "sub", about: "sub:lying_instruments", source: "person", bias: "true", reliable: "partial", who: "{person}, astronomer's apprentice", points: "cast:investigator", text: "Diary of {person}, apprentice to an astronomer of {place}, {year}: 'The master smashed the astrolabe tonight. It put the moon in three places in one night, and the 400-year almanac put it where we could see it with our own eyes. Our brass came from three different workshops, and all of it lies. The master has written to {investigator} at {lead} to ask whether the academy's instruments are sick too. I am to sweep up the glass.'" },
    { depth: "sub", about: "sub:beacon_kindlers", source: "temple", bias: "heretic", reliable: false, who: "{believer}, beacon-kindler", points: "cast:believer", text: "Hymn sheet of the beacon-kindlers, handed out by {believer} at the hilltop fire above {place}, {year}, 200 copies. The hymn: 'Shine for the ones who are coming, / shine for the friends in the dark. / They are lonely, as we are lonely; / let us be the first to call.' On the back, in plain print: all are welcome at the great mirror of {lead}, polishing every seventh day, bring rags." },
    { depth: "sub", about: "sub:glassed_country", source: "traveller", bias: "true", reliable: true, who: "{person}, caravan master", points: "site:pressed_land", text: "Road notes of {person}, caravan master, after crossing the glassed country, {year}: 'Three days on green glass, flat as pond ice; the camels hated it. Under the glass I could see the tops of towers, and once a market with its awnings still up and fruit on the stalls. No chronicle records a war here. The glass ends at a straight edge, and past it the land at {lead} is pressed flat as a painting.'" },
    { depth: "sub", about: "sub:waystone_lords", source: "oral", bias: "garbled", reliable: "partial", who: "{person}, retired steward", points: "sub:hollow_couriers", text: "Told by {person}, a retired steward, to guests at an inn in {place}, {year}: 'I served the ring-court for 22 years. The lords who sit by the black rings stop arguing with each other after a year or two. They smile the same smile and vote the same vote, always for more rings. That was the most frightening thing I saw at court, and I saw two poisonings. They cross every morning, like the couriers of {lead}.'" },
    { depth: "sub", about: "sub:sealed_counsellors", source: "archive", bias: "redacted", reliable: "partial", who: "warrant of the crown of {realm}", points: "archive", text: "Warrant of the crown of {realm}, copy four of seven, sealed in black wax, {year}: 'The bearer is answerable to no court, council or person, the crown included, until [date withheld]. The bearer may take any ship, granary or ledger. Obey.' A clerk's note on the file: 'Bearer took the waystone register and the dig tablets from the archives of {lead}. No receipt given.'" },
    { depth: "sub", about: "sub:unlit_cities", source: "traveller", bias: "exaggerated", reliable: "partial", who: "{person}, wool-buyer", points: "temple", text: "Letter of {person}, a wool-buyer, home from {place}, {year}: 'A city of a hundred thousand souls and not one candle after dusk. The fine is ten silver a lamp. They whisper in the streets at night and look up before they cross a square. I struck a match in my room and the innkeeper took the box. The priests of the Hush run the night watch from {lead}.'" },
    { depth: "sub", about: "sub:pale_envoy", source: "person", bias: "redacted", reliable: "partial", who: "{person}, under-clerk to the council", points: "archive", text: "Statement of {person}, under-clerk to the council of {realm}, taken {year}: 'The envoy was courteous, very tall, and cast no shadow under six lamps. The terms, as best I recall: peace, plenty and an end to fear. You need only stop [the clerk refused to say it]. The envoy left a sealed copy, and {official} ordered it locked in the archives of {lead}.'" },
    { depth: "sub", about: "sub:exodus_ships", source: "archive", bias: "true", reliable: "partial", who: "{person}, port-reeve of {place}", text: "Harbour ledger of {place}, kept by {person}, port-reeve, {year}: 'A great house of the coast has bought eleven hulls this year, and every chart of the empty ocean we had, at triple price. Its master shipwright asked me how long salt pork keeps at sea. I said three years. The shipwright asked about ten. The house's steward paid in gold and asked me not to write any of this down.'" },
    { depth: "sub", about: "sub:hollow_couriers", source: "archive", bias: "true", reliable: true, who: "assize court of {place}", points: "cast:survivor", text: "Record of the assize court of {place}, {year}, {person} against the royal courier corps. The plaintiff's spouse made 1,100 crossings in nine years and can no longer name their three children. The plaintiff asked for the courier back as before, or a pension. Counsel for {official} replied that the corps' contract covers lost horses, not lost memories. Judgment for the corps; costs of 12 silver. Clerk's note: the courier smiled throughout, asking twice whose case it was. A retired courier at {lead} offered to testify and was not called." },
    { depth: "site", about: "site:weeping_pillar", source: "ruin", bias: "garbled", reliable: "partial", who: "{person}, keeper of the pillar shrine", points: "site:unnamed_city", text: "Shrine-book of the weeping pillar, copied by {person}, keeper of the shrine, {year}. Each age wrote its own reading of the pillar's song. Ours, entered 90 years ago: 'Welcome'. The one before: 'Hide'. The oldest page, in a script few can read: 'Do not.' The oldest page also names the city whose people built the pillar. It lies at {lead}." },
    { depth: "site", about: "site:pressed_land", source: "traveller", bias: "true", reliable: true, who: "{investigator}, survey note", text: "Survey note of {investigator}, from the desert road, {year}: 'Two days at the pressed village. Sixty-three people lie flat in the street, thin as paint. A child's kite is pressed in mid-flight, string and all. I chained the cut edge: nine miles, dead straight. A cut that straight was aimed. I have asked for the old tower logs from the mountains, to see who was signalling that year.'" },
  ],
};
