// The Ascending Path: cultivation of an inner core towards immortality, and the truth about the heaven at the top.
export default {
  id: "ascending_path",
  name: "The Ascending Path",
  family: "power",
  pitch: "Cultivators use breathing, pills and decades of seclusion to refine the world's essence into a core inside the body. Each realm they climb brings them closer to immortality, but heaven sends lightning to strike down anyone who climbs too high.",
  slots: ["cosmology", "power-access", "economy-resource"],
  tone: ["heroic", "grim"],
  era: ["bronze", "medieval", "renaissance"],
  scale: "world",
  genres: ["fantasy", "shonen", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "strewn_sky", w: 2.5 }, { id: "body_of_the_world", w: 2 }, { id: "elder_lattice", w: 1.5 }, { id: "walking_mountains", w: 1.5 }],

  power: {
    name: "the ascending path", user: "cultivator", users: "cultivators",
    taught: "The world's essence can be drawn in through breath, pills and long seclusion and refined into a core inside the body. Each realm climbed lengthens life, and at every threshold heaven sends lightning to test the climber.",
    rules: ["The realms are climbed in order: Kindling, Bedrock, Pearl, Infant-Self, Severance, Crossing.", "Every great breakthrough brings a tribulation of heavenly lightning.", "Innate roots set the speed of the climb; poor roots may never form a core.", "A careless breakthrough cripples the meridians or the mind."],
    forbidden: "Devouring another cultivator's core.",
  },

  cast: [
    { role: "investigator", n: "a vein-reader who surveys the spirit veins for the court", home: "mountain", stance: "Wants the crown to ration essence before the last veins die; trusts a measurement over a scripture." },
    { role: "official", n: "the record-elder of the great sect on the mountain", home: "mountain", stance: "Holds that the path has no end, and that doubt is a symptom of poor roots." },
    { role: "believer", n: "keeper of the lowland shrine to the ascended immortals", home: "inner", stance: "Believes the ascended live in bliss and remember the families who leave them rice." },
    { role: "survivor", n: "a former disciple who watched their master taken in a tribulation", home: "remote", stance: "Left the sect, and wants someone in authority to admit what came out of the clouds." },
  ],

  truths: [
    { id: "harvester", n: "Heaven is a harvester", d: "The tribulations are not tests but culls. The being that calls itself heaven takes the strongest cultivators whole and eats them; the world is a farm kept to grow strong souls. The sects send it their best elders every season and call it ascension.", tags: ["truth:heaven_harvest"],
      known: [
        "Families light lamps for relatives who ascended, and none has ever had word back. {believer}, keeper of the shrine of the ascended, has started asking the sect why. The sect says heaven is far away.",
        "Tribulation craters hold no bodies. {survivor}, a disciple who watched their master's crossing, swears a hand came down out of the clouds. The sect wrote 'ascended' in its register and expelled the disciple.",
        "The bones of the Rib Ranges carry the same ninefold pattern of strikes as a tribulation, struck again and again on one huge beast. Heaven's lightning has killed great climbers before, and their bodies were taken.",
        "Confirmed: the tribulations are a harvest. The being that calls itself heaven takes the strongest cultivators whole and eats them. The sects have sent it their best elders for centuries and called it ascension.",
      ] },
    { id: "finite", n: "Essence is finite", d: "Every breakthrough drains the world, and the spirit veins are running dry. The ancient age of immortals ended because they exhausted their world, and the sects of this golden age, racing each other for breakthroughs, are repeating the mistake faster.", tags: ["truth:finite_essence"],
      known: [
        "Breakthrough pills cost three times what they did a decade ago. The pill-masters blame the herbs; the herb-sellers blame the spirit stones. Nobody in the guilds will say where the stones have gone.",
        "{investigator}, the court's vein-reader, reports that the southern vein is dry and the eastern vein halved. The sect's own survey has a page torn out, and its record-elder says the veins will recover.",
        "A jade slip from the grey valley says the immortals of the last age drained their veins until children were born without roots. The grey valley looks exactly like what the slip describes.",
        "Confirmed: essence is finite. Every breakthrough spends a little of a supply that does not come back. The last age ended when its veins ran out, and the sects of this age are draining them faster.",
      ] },
    { id: "ceiling_seal", n: "The ceiling is a seal", d: "The world is a pocket realm, sealed long ago by an immortal who is now dead, either to shelter its people or to imprison them. The limit on the climb is the seal itself. Each elder who presses on it cracks it a little, and breaking through will let in whatever is outside.", tags: ["truth:ceiling_seal"],
      known: [
        "Watch disciples on the eastern peaks have logged a hair-thin crack in the night sky, two finger-widths long on the brass rule and growing each year. They were told to stop recording it, and their logs were moved.",
        "An elder of the Crossing realm came back blind and said the path ends at a wall with a lock written on it. The sect council sealed the elder's notes and still teaches that the path has no end.",
        "The vanished Chain Sect climbed the chains of the hanging mountains and found a warm stone ceiling covered in lock-script. Their last record says that knocking on it is answered from the other side.",
        "Confirmed: the world is a sealed pocket, closed by an immortal dead 3,000 years. The limit on the climb is the seal itself. Every elder who presses on it weakens it, and nobody knows what is outside.",
      ] },
  ],

  tags: ["cultivation"],

  subthemes: [
    { id: "fallen_prodigy", n: "The Fallen Prodigy", d: "The sect's brightest disciple had his core shattered in a duel and his engagement broken in public. Now there is a voice in a cracked ring teaching him at night.", w: 1.2, mods: [["martial", 1.5], ["hierarchical", 1.5]], tags: ["theme:fallen_prodigy"] },
    { id: "sect_tournament", n: "The Grand Tournament", d: "Once a generation the sects meet to rank their disciples. The ranking decides who gets the spirit stones, the pills and the veins for the next thirty years.", w: 1.2, req: { any: ["martial", "warrior_code", "mountain_folk", "mountain"] }, tags: ["theme:sect_tournament"] },
    { id: "hidden_realm", n: "The Hidden Realm", d: "Once a century a pocket world opens in the mountains. Young cultivators go in by the hundred; a handful come out, changed and rich.", w: 0.9, mods: [["mountain", 1.5], ["near:rift", 2]], truthLink: "ceiling_seal", tags: ["theme:hidden_realm"] },
    { id: "devouring_sects", n: "The Devouring Sects", d: "Sects of the demonic path grow fast by eating other cultivators' cores. They are crueller than the orthodox, and far more honest about what they want.", w: 1, mods: [["faith:void", 2], ["near:beasts", 1.5]], tags: ["theme:devouring_sects"] },
    { id: "tribulation_season", n: "Tribulation Season", d: "Black clouds circle the sect mountain for nine days at a time. Every year more elders attempt the crossing, and the valley folk sleep in cellars.", w: 1, mods: [["mountain", 2]], truthLink: "harvester", tags: ["theme:tribulation_season"], mark: { kind: "zone", n: "Scorched peaks", color: "#3a3a5a", size: [1, 2], where: "mountain" } },
    { id: "pill_wars", n: "The Pill Wars", d: "The pill-masters' guilds hoard the breakthrough pills and set prices that ruin whole sects. Their price lists show the shortage years before anyone admits it.", w: 1, req: { any: ["mercantile", "guilds", "artisans"] }, truthLink: "finite", tags: ["theme:pill_wars"] },
    { id: "vein_wars", n: "The Vein Wars", d: "Sects fight over land where the world's essence runs thick. Mortal kingdoms are trampled in passing, and nobody counts them.", w: 1.2, truthLink: "finite", tags: ["theme:vein_wars"], mark: { kind: "zone", n: "Dried veins", color: "#8a8a7a", size: [1, 3], where: "remote" } },
    { id: "mortal_farms", n: "The Talent Levy", d: "The sect's scouts tour the mortal kingdom every spring testing children's roots. Those with good roots are taken; the king's armies cannot stop them and do not try.", w: 1, req: { any: ["monarchy", "autocracy", "tribal"] }, mods: [["realm:small", 1.5], ["realm:tiny", 1.5]], tags: ["theme:mortal_farms"] },
    { id: "face_and_vengeance", n: "Face and Vengeance", d: "A young master was insulted at a tea-house. Three clans have since been wiped out, and the feud is still climbing.", w: 0.9, mods: [["hierarchical", 2], ["dynastic", 2]], tags: ["theme:face_and_vengeance"] },
    { id: "gate_above", n: "The Gate Above", d: "A sect's elders have made contact with an upper realm. What came back through the gate was polite, condescending, and called this world 'the bottom rung'.", w: 0.7, req: { any: ["seers", "faith:stars", "mystic", "scholarly"] }, truthLink: "ceiling_seal", tags: ["theme:gate_above"] },
    { id: "hated_body", n: "The Body Heaven Hates", d: "A lowland girl was born with a body that heaven's lightning hunts. Storms follow her from village to village, and no village will keep her.", w: 0.6, truthLink: "harvester", tags: ["theme:hated_body"] },
  ],

  sites: [
    { id: "sealed_abode", n: "The Sealed Abode of $", kind: "ruin", where: "mountain", d: "An immortal's cave behind nine layered arrays and riddles.",
      layers: {
        surface: { n: "The door that pushes back", text: "A door is cut into the cliff above the sect's lower terraces, glowing faintly green at night. Hands that reach for it are pushed gently away. The sect has logged 212 attempts since {year}, and the shepherds' children try it for dares." },
        study: { n: "Nine riddles", text: "Nine arrays guard the door, one behind another, each a riddle cut into a bronze plate. Sect scholars solved eight of them over two centuries. The ninth asks the solver what they would give up. Every disciple who answered 'anything' was turned away." },
        dig: { n: "The patient one's cave", points: "cast:survivor", text: "One disciple answered 'my rank' and was let in. Inside sit an immortal's bones in meditation, beside a jade slip addressed 'to whoever was patient'. The disciple copied the slip, left the sect the same week, and took the copy to {lead}." },
        revelation: { n: "How to stop", text: "The immortal reached the Severance realm 900 years ago, watched the tribulation clouds take three friends, and chose to stop climbing. They sat here until the world forgot them. The slip teaches a safe way to stop. The sect elders have known of it for a century and keep it from their disciples." },
      } },
    { id: "rib_ranges", n: "The Rib Ranges of $", kind: "wonder", where: "mountain", truthLink: "harvester", d: "A mountain range made of the ribcage of a huge creature that died in an ancient age.",
      layers: {
        surface: { n: "White ridges", text: "Eleven curved white ridges cross the range about a mile apart, like ribs. Herders call them the Ribs and graze goats between them. Lightning strikes the ridges more often than any peak in {realm}, and the herders build no huts on the tops." },
        study: { n: "Bone, not stone", text: "{investigator}, the court's vein-reader, cut a sample from the third ridge in {year}. It is bone, laid down in rings like a tree. Every ridge is scored with forked scorch marks, some of them as wide as a road." },
        dig: { n: "The ninefold pattern", points: "site:glass_crater", text: "Charted from the high pass, the scorches fall in groups of nine, struck again and again: 81 strikes, the count of a full tribulation. The same ring of scorches is burned around the crater at {lead}, where an elder vanished." },
        revelation: { n: "What heaven eats", text: "Before the sects, a beast climbed as high as any cultivator since. The tribulation struck it down here, and its core and flesh were taken; only the ribs were left. Heaven's lightning is not a test of virtue. It is a harvest, and the sect elders still send their best up the mountain to meet it." },
      } },
    { id: "grey_valley", n: "The Grey Valley of $", kind: "anomaly", where: "remote", truthLink: "finite", d: "A valley on a dead spirit vein, where nothing grows.",
      layers: {
        surface: { n: "Ash stones", text: "Nothing grows in the valley: no grass, no lichen, and the stones are pale as ash. Herb gatherers have walked around it for 300 years. The one well at its mouth gives water that tastes of chalk, and the mules will not drink it." },
        study: { n: "An empty vein", text: "Every old map in {realm} shows a spirit vein under the valley. {investigator} sat on it for seven days in {year} and felt no essence at all. Cultivators who meditate here wake with nosebleeds and lose a month of progress." },
        dig: { n: "The dry channel", points: "archive", text: "Under the bedrock runs a dry channel lined with crumbled spirit stones, and boundary markers bearing the crest of a sect no record names. The court's vein survey, which called this valley 'healthy' until 40 years ago, is kept in {lead}." },
        revelation: { n: "The last age's mistake", text: "The immortals of the last age drained this vein, then the next, until no child in their world could form a core. Their age ended in valleys like this one. The vein survey shows today's sects draining veins three times faster than the old maps, and the pill guilds have priced it in." },
      } },
    { id: "chained_peaks", n: "The Chained Peaks of $", kind: "wonder", where: "mountain", truthLink: "ceiling_seal", d: "Floating mountains held by great chains, abandoned by a vanished sect.",
      layers: {
        surface: { n: "Hanging mountains", text: "Three mountains hang in the air above the valley, held by chains thicker than watchtowers. A vanished sect once lived on them. Pilgrims climb the lowest chain to its first link, 400 feet up, and tie prayer ribbons there." },
        study: { n: "Chains going up", text: "A sect surveyor with a brass sighting tube noted in {year} that the chains run up as well as down. The upper chains rise into the empty sky and end at nothing visible. Cranes that fly above them come back down within the hour, exhausted." },
        dig: { n: "The bell on the summit", points: "cast:official", text: "On the highest peak, under a fallen hall, hangs a bronze bell cut with the vanished sect's last record. A rubbing of it was sent to the sect's record-elder at {lead} in {year}. The rubbing was filed, and the summit was closed to disciples." },
        revelation: { n: "The roof of the world", text: "The mountains hang on chains from a solid lid over the sky, built by an immortal who sealed this world away 3,000 years ago. The Chain Sect climbed up to cut through it and never came down. The record-elder filed their bell-rubbing and closed the summit. Every elder who reaches the Crossing still presses on that lid." },
      } },
    { id: "glass_crater", n: "The Glass Crater of $", kind: "anomaly", where: "any", truthLink: "harvester", d: "A tribulation crater of green glass with a cultivator's shadow burned into it.",
      layers: {
        surface: { n: "Green glass", text: "A crater of green glass, 60 paces across, crowns a hill above {place}. It formed in a single night of tribulation in {year}. Children slide down it on boards, and pedlars chip off pieces to sell as luck charms." },
        study: { n: "The shadow", text: "In the glass at the centre is the shadow of a seated cultivator: crossed legs, hands on knees, head tipped back to look up. {survivor}, the elder's last disciple, identified the posture as their master's from 30 paces away." },
        dig: { n: "Nothing underneath", points: "temple", text: "Miners cut through the glass in a week. Beneath it there is no body: no bone, no ash, not even the iron storage ring every elder wears. The mourning register for the elder, marked 'ascended', is kept at the shrine in {lead}." },
        revelation: { n: "Picked like fruit", text: "The lightning did not burn the elder. It cleared a path, and a hand came down it and lifted the body out whole, iron ring and all. The sect wrote 'ascended' in its register and held a feast. Its record-elder has written that word 40 times this century, and sends the next elder up each spring." },
      } },
    { id: "sword_stele", n: "The Sword Stele of $", kind: "shrine", where: "any", d: "A stele carved with sword-strokes in which every viewer sees a different technique.",
      layers: {
        surface: { n: "Sword strokes", text: "A stone stele twice a man's height stands by the old road, scored with 64 sword-strokes. Travelling swordsmen stop to stare at it. The innkeeper across the road charges a copper extra for a room with a view of it." },
        study: { n: "A different form for every viewer", text: "Each viewer sees a different technique in the strokes. The sect's register lists 31 sword-forms taken from it. Three disciples tried to see all of them at once and had to be fed by hand for the rest of their lives." },
        dig: { n: "The back of the stone", points: "library", text: "Masons who reset the stele in {year} found one line carved on its back, facing the cliff: 'Do not climb past the sixth.' The carver's other writings, four bamboo books, are catalogued in the library at {lead}." },
        revelation: { n: "The turning stroke", text: "The master who carved the stele reached the sixth realm, saw what waits above it, and came back down to warn others. The 64 strokes teach one technique: turning back from a breakthrough without crippling the meridians. The sects copy the stele and teach every form on it but that one." },
      } },
  ],

  beings: [
    { id: "spirit_tiger", n: "Core-bearing tiger", kind: "beast", d: "A white tiger that has cultivated for three centuries and grown a beast-core in its chest. Sects send whole expeditions to hunt one.", danger: 3, biomes: ["tempforest", "rainforest", "alpine"], look: { size: 3, group: [1, 1], move: "solo", speed: 40, col: "#e0d8c0", col2: "#2a2a2a", body: "quad", active: "night", visible: true } },
    { id: "thousand_crane", n: "Thousand-year crane", kind: "bird", d: "A crane that has drunk spirit-dew for a thousand years. Its feathers are worth a village; killing one is said to cost a decade of life.", danger: 0, biomes: ["river", "swamp", "alpine"], look: { size: 1.8, group: [1, 2], move: "pair", speed: 60, col: "#f4f4f0", col2: "#c02020", body: "bird", active: "day", visible: true } },
    { id: "lightning_remnant", n: "Lightning remnant", kind: "predator", d: "What is left of a cultivator who failed the tribulation: a crackling shape that wanders the high peaks, hungry for the essence it lost.", danger: 2, biomes: ["peaks", "alpine"], look: { size: 2, group: [1, 1], move: "solo", speed: 30, col: "#a0a0ff", col2: "#ffffff", body: "biped", active: "any", visible: true } },
    { id: "root_serpent", n: "Root-serpent", kind: "reptile", d: "A great serpent coiled around a thousand-year spirit herb. It has guarded the herb so long that the two share a pulse.", danger: 2, biomes: ["rainforest", "tempforest", "alpine"], look: { size: 6, group: [1, 1], move: "solo", speed: 10, col: "#3a6a2a", col2: "#c0a040", body: "serpent", active: "night", visible: true } },
  ],

  techs: [
    { id: "ap_breathwork", n: "Breathwork", field: "medicine", level: 1, d: "Longevity exercises and martial breathing: the first step on the path, taught in every village square." },
    { id: "ap_core_forming", n: "Core-forming", field: "arcana", level: 2, d: "The realms written down and the first cores formed. Sects are founded on the mountains." },
    { id: "ap_pill_refining", n: "Pill refining", field: "alchemy", level: 3, d: "Spirit herbs and beast-cores refined into pills that force a breakthrough, at a price." },
    { id: "ap_arrays", n: "Array formations", field: "engineering", level: 3, d: "Patterns of stones and flags that raise protective domes and killing mazes." },
    { id: "ap_flying_swords", n: "Flying swords", field: "warfare", level: 4, d: "Blades bound to a cultivator's will that fly, strike and carry their master over mountains." },
    { id: "ap_vein_reading", n: "Vein-reading", field: "natural_philosophy", level: 5, d: "The spirit veins measured and mapped, and with the maps, the first proof that they are running dry." },
  ],

  units: [
    { id: "ap_sword_disciples", n: "Sect sword-disciples", role: "magic", wpn: "sword", kit: "robe", ranks: 2, gap: 3, size: 20, w: 0.5, mods: [["theme:sect_tournament", 5], ["theme:vein_wars", 3], ["mountain", 1.5]] },
    { id: "ap_array_masters", n: "Array-masters", role: "siege", wpn: "siege", kit: "robe", ranks: 1, gap: 8, size: 8, w: 0.3, mods: [["theme:vein_wars", 4], ["gov:ap_sect_rule", 4]] },
  ],

  govs: [
    { id: "ap_sect_rule", n: "Sect dominion", d: "A mountain sect rules the lowlands. The mortal king is its steward, and the patriarch has not left seclusion in two hundred years.", tags: ["gov:ap_sect_rule", "autocracy", "arcane_rule"], w: 0.5, forms: ["Sect of $", "Mountain Gate of $", "Sword Sect of $"], ruler: "Patriarch", mods: [["mountain", 2], ["martial", 1.5], ["hierarchical", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Spirit veins", color: "#7ab0a0", size: [1, 3], count: [1, 3], where: "mountain", d: "Lands where the world's essence runs thick. Every sect wants them." },
  ],

  storylines: [
    { id: "ap_prodigy", n: "The Cripple of {place}", scale: "local", anchor: "town", w: 1.5, req: "cultivation",
      stages: {
        start: { h: "A sect prodigy of {place} is crippled", b: "{person}, once the pride of the sect above {place}, had their core shattered in a duel. Then their betrothed's family broke the engagement in the public square.", wait: [2, 5], next: [{ to: "ring", w: 2 }, { to: "leaves_path", w: 1 }] },
        ring: { h: "{person} finds a cracked ring", b: "In a pawnshop in {place}, {person} spent their last coin on a cracked ring. At night, a voice in the ring has begun to teach them.", wait: [6, 18], next: [{ to: "returns", w: 2 }, { to: "devoured", w: 1, mods: [["theme:devouring_sects", 3]] }] },
        leaves_path: { h: "{person} leaves the path", b: "The fallen prodigy has become a scribe in {place}. The scribe will live an ordinary lifespan, and seems happier than anyone at the sect.", fx: { stability: 1 }, end: true },
        returns: { h: "{person} returns to the tournament", b: "The cripple of {place} walked into the sect tournament and defeated every disciple who had mocked them, then the elder who broke their core. Nobody laughs now.", fx: { prestige: 8 }, end: true },
        devoured: { h: "The voice in the ring takes {person}", b: "The voice was a devouring elder waiting for a body. {person} came back with new eyes, and the sect above {place} burned within the month.", fx: { unrest: 12, pop: 0.95 }, end: true },
      } },
    { id: "ap_tribulation", n: "The Tribulation above {place}", scale: "local", anchor: "town", w: 1.2, req: "cultivation",
      stages: {
        start: { h: "Storm clouds circle the peak above {place}", b: "For nine days black clouds have circled the sect mountain above {place}. The elder {person} is attempting the crossing.", wait: [1, 2], next: [{ to: "strikes", w: 2 }, { to: "abandons", w: 0.5, mods: [["theme:hated_body", 2]] }] },
        abandons: { h: "{person} abandons the crossing", b: "On the ninth day the elder came down the mountain, pale, and would not say what was in the clouds.", fx: { stability: 1 }, end: true },
        strikes: { h: "Lightning falls on the mountain above {place}", b: "Eighty-one bolts struck the peak in one night. The people of {place} hid in their cellars; the disciples watched from the walls.", wait: [1, 2], fx: { unrest: 4 }, next: [{ to: "ascends", w: 1 }, { to: "fails", w: 1 }, { to: "taken", w: 0.6, mods: [["theme:tribulation_season", 2]] }] },
        ascends: { h: "{person} ascends", b: "At dawn a pillar of light rose from the peak, and {person} was gone. The sect is celebrating; nobody has ever had a letter back from heaven.", fx: { prestige: 8 }, end: true },
        fails: { h: "{person} falls in the tribulation", b: "The elder's body was found in a crater of green glass. The sect is in mourning, and its rivals are already sharpening their swords.", fx: { stability: -4 }, end: true },
        taken: { h: "A shadow is burned into the glass above {place}", b: "Where the elder sat there is only a shadow in the glass, and no body at all. {survivor}, a disciple, says a huge hand reached down out of the clouds.", fx: { unrest: 8, flag: "harvest_seen" }, end: true },
      } },
    { id: "ap_vein_war", n: "The Vein War of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: "cultivation",
      stages: {
        start: { h: "A spirit vein is found in {realm}", b: "Prospectors of {realm} have found a rich spirit vein under the hills. Within a week, three sects sent elders to claim it.", wait: [2, 5], next: [{ to: "sects_fight", w: 2 }, { to: "crown_claims", w: 1, mods: [["autocracy", 2], ["standing_army", 1.5]] }] },
        crown_claims: { h: "{ruler} claims the vein for the crown", b: "{ruler} has declared the vein the property of {realm} and set soldiers around it. The sects find this very funny.", wait: [2, 6], next: [{ to: "sects_fight", w: 1 }, { to: "crown_keeps", w: 1, mods: [["ruler:cunning", 2]] }] },
        sects_fight: { h: "Sects fight over the vein in {realm}", b: "Sect disciples fight with flying swords over the hills of {realm}. A stray array flattened three villages. The crown's soldiers can only watch.", wait: [3, 8], fx: { pop: 0.95, unrest: 10 }, next: [{ to: "vein_dry", w: 1 }, { to: "sect_rules", w: 1 }] },
        vein_dry: { h: "The vein of {realm} runs dry", b: "Before the war was settled, the vein ran dry. {investigator}, the court's old vein-reader, says it is the third this century, and each one dies faster.", fx: { stability: -4, science: { natural_philosophy: 0.5 } }, end: true },
        sect_rules: { h: "A sect rules {realm}", b: "The victorious sect has made {ruler} its steward. Taxes are now paid in children with good roots.", fx: { stability: -8, prestige: -5 }, end: true },
        crown_keeps: { h: "{realm} keeps its vein", b: "By playing the sects against each other, {ruler} kept the vein for the crown, and now sells its essence by the ounce.", fx: { treasury: 80, prestige: 6 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", who: "Outer-disciple scripture of the sect", text: "Outer-disciple scripture of the sect above {place}, copied in {year}, chapter one: 'Gather the breath at dawn, refine it at noon, store it at dusk. Six realms are climbed in order: Kindling, Bedrock, Pearl, Infant-Self, Severance, Crossing.' The breath meant is the world's essence, drawn in and pressed into a core below the navel. The four stanzas on Severance are left blank and marked 'taught to core disciples only'." },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: false, who: "A rice farmer of {place}, to a travelling scribe", text: "Told by a rice farmer of {place} to a travelling scribe, {year}: 'The immortals on the mountain are kind gods who keep the rain falling. My grandmother left them a bowl of rice every new moon, six hundred bowls in her life, and our field has never flooded. When the sect took my boy for his roots, I told him to give the gods our family name.'" },
    { depth: "lore", about: "power", source: "archive", bias: "official", reliable: true, points: "sub:pill_wars", who: "A merchant's daybook, {place}", text: "Price board of the pill-masters' guild at {place}, copied into a merchant's daybook, {year}: 'Bedrock-building pill, forty spirit stones. Last year, twenty. The year before, twelve.' The merchant adds: 'Spirit stones are crystals of the world's essence, mined from the veins. The guild blames the herbs. The herb-sellers say the herbs are fine and the stones are short. The guild's own minutes are kept in {lead}.'" },
    { depth: "core", about: "truth:harvester", source: "person", bias: "true", reliable: true, plain: true, who: "An elder of the devouring path, diary", text: "Diary of an elder of the devouring path, the night before a crossing, {year}: 'I have eaten fourteen cores, and I know the taste of a ripe one. Tonight I felt the clouds taste me back. What sits above the clouds is not a court of immortals. It eats cultivators who have ripened, as I eat them, and the sects send it their best. I will not go up. Let it come down for me.'" },
    { depth: "core", about: "truth:harvester", source: "ruin", bias: "true", reliable: "partial", cost: true, who: "{survivor}, cut into the crater glass", text: "Cut into the glass at the crater's rim with a sword-point, signed {survivor}, disciple, {year}: 'My master was not burned. I sat 30 paces off holding the incense bowl. On the 81st bolt a hand came down out of the cloud, wider than this hill, and took my master like fruit. I have left the sect for saying so. If you read this, do not let them write ascended.'" },
    { depth: "core", about: "truth:harvester", source: "heretic", bias: "heretic", reliable: "partial", points: "site:rib_ranges", who: "Unsigned pamphlet, tournament gate of {place}", text: "Pamphlet nailed to the tournament gate at {place}, {year}, unsigned: 'Heaven strikes only the strongest. In 300 years of sect registers, no tribulation has fallen on a cultivator below the Pearl realm. A shepherd does not kill the weak lambs; he eats the fat ones. If you doubt it, go and count the scorch marks on the bones at {lead}, and ask what was eaten there.'" },
    { depth: "core", about: "truth:harvester", source: "oral", bias: "garbled", reliable: "partial", who: "{believer}, keeper of the shrine of the ascended", text: "Letter of complaint from {believer}, keeper of the shrine of the ascended in {place}, to the sect, {year}: 'Forty-one families light lamps here for relatives who ascended. Not one has had a letter, a dream or a sign. The families ask me why. I tell them heaven's post is slow. I would be grateful for a better answer, and for twelve more jars of lamp oil.'" },
    { depth: "core", about: "truth:harvester", source: "temple", bias: "official", reliable: false, who: "Festival sermon, shrine of the ascended", text: "Festival sermon of the {faith}, read at the shrine of the ascended in {place}, {year}: 'The tribulation is heaven's test of virtue. Nine times nine bolts fall, and the impure is burned away. Those who pass are welcomed into the upper court as honoured immortals, where they dwell forever in bliss. Bring rice and lamp oil for the ascended. They see you, and they remember your family.'" },
    { depth: "core", about: "truth:finite", source: "ruin", bias: "true", reliable: true, plain: true, who: "A jade slip of the last age", text: "Jade slip found in a dry channel of the grey valley, written by a cultivator of the last age, about 2,000 years ago by the sect's reckoning: 'We drank the last vein in my master's time. The sky went pale. The children were born without roots, and none of them could form a core. The essence of the world is not a river. It is a jar, and we emptied it. Do not do as we did.'" },
    { depth: "core", about: "truth:finite", source: "archive", bias: "redacted", reliable: "partial", points: "cast:investigator", who: "Sect survey of spirit veins, {year}", text: "Survey of spirit veins kept by the sect above {place}, {year}: 'Eastern vein, flow halved since the survey 30 years ago. Southern vein, dry; the sect there has moved. Northern vein...' The page is torn out. A clerk's note pinned in its place says the court's vein-reader, {investigator}, made a fair copy before the page was removed, and still lives in {lead}." },
    { depth: "core", about: "truth:finite", source: "person", bias: "true", reliable: "partial", cost: true, who: "{investigator}, vein-reader to the court", text: "Testimony of {investigator}, vein-reader to the court of {realm}, {year}: 'When I was young I could feel the essence from the valley floor. Now I must climb to the peak, and even there it is thin. My home village sat on the southern vein. Its rice failed four years running after the vein went dry, and 300 of my neighbours walked to the city. I measured it going. Nobody paid me to stop it.'" },
    { depth: "core", about: "truth:finite", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:grey_valley", who: "A caravan master, at an inn in {place}", text: "Account of a caravan master back from the far east, told at an inn in {place}, {year}: 'There is a land 40 days' ride east where the sky is grey and the herbs taste of dust. The people there die at sixty and have no cultivators at all, though their old sect halls are bigger than our palaces. They told me their country looked like your valley at {lead} in their great-grandparents' time.'" },
    { depth: "core", about: "truth:finite", source: "library", bias: "official", reliable: false, who: "{official}, Treatise on Veins", text: "From the Treatise on Veins by {official}, record-elder of the sect, {year} edition: 'Spirit veins renew themselves as rivers renew from rain. The present weakness of the eastern and southern veins is a passing season, like the dry years of the 9th dynasty, and will reverse within the century. Rumours of dead valleys are spread by vein-readers seeking larger stipends.'" },
    { depth: "core", about: "truth:ceiling_seal", source: "ruin", bias: "true", reliable: true, plain: true, who: "Last record of the Chain Sect, the summit bell", text: "Final entry in the day-book of the vanished Chain Sect, cut into the bronze bell on the highest hanging peak, {year}: 'Nine of us climbed the upper chain for eleven days. At the top is a ceiling of stone, warm to the hand, with lock-script written across it. This world is sealed in a box, and the chains hang from its lid. We will cut through. When we knock, the knocking is answered from the other side.'" },
    { depth: "core", about: "truth:ceiling_seal", source: "person", bias: "true", reliable: "partial", cost: true, points: "archive", who: "The elder {person}, to the sect council", text: "Statement of the elder {person}, Crossing realm, to the sect council, {year}, written down by {official}: 'I rose nine days past the last tribulation. There is no further. There is only a wall, and writing on the wall, and the writing is a lock. I tried to read it.' {person} lost both eyes and 200 years of cultivation that afternoon. The council sealed the notes in {lead}." },
    { depth: "core", about: "truth:ceiling_seal", source: "heretic", bias: "exaggerated", reliable: "partial", who: "A heretic teacher's lecture, taken down by a student", text: "Lecture by a heretic teacher in the lowlands below {place}, taken down by a student, {year}: 'The founder did not make this world. The founder hid it, the way a man hides his family in a cellar during a war. The founder has been dead 3,000 years, and nobody upstairs remembers the cellar. Now our elders want to open the door and see if the war is over.'" },
    { depth: "core", about: "truth:ceiling_seal", source: "oral", bias: "garbled", reliable: "partial", points: "library", who: "Night-watch log of the eastern star-tower", text: "Night-watch log of the star-tower on the eastern peaks, kept by duty disciples, {year}: 'Clear sky. The crack visible again over the third peak, thin as a hair. Measured against the brass rule: two finger-widths long. Last year, one and a half.' The next line, in another hand, orders the watch to stop recording it. The tower's older logs were sent to {lead}." },
    { depth: "core", about: "truth:ceiling_seal", source: "library", bias: "official", reliable: false, who: "{official}, Lesser Catechism of the sect", text: "Lesser Catechism of the sect, answer 18, set by {official}, record-elder: 'Q: Is there a ceiling to the path? A: No. The heavens are boundless, and the path rises without end. The so-called ceiling is a story told by cultivators too weak to climb further. A disciple who repeats it is to copy this answer 100 times.'" },
    { depth: "sub", about: "sub:mortal_farms", source: "person", bias: "true", reliable: true, who: "A weaver's petition to the king", text: "Petition of a weaver of {place} to the king of {realm}, {year}, left in the box at the palace gate: 'In spring the sect scouts tested 60 children in our street by laying a spirit stone in their palms. My son's stone glowed. They took him for his good roots, and your soldiers held the door for them. I ask only to know if he is alive. His name is sewn inside his collar.'" },
    { depth: "sub", about: "sub:face_and_vengeance", source: "oral", bias: "exaggerated", reliable: "partial", who: "Owner of the Willow tea-house, {place}", text: "Told by the owner of the Willow tea-house in {place} to a magistrate's clerk, {year}: 'It began with one spilled cup of tea on a young master's sleeve, at the window table. Three clans are gone now, 140 people by your count. The young master's family paid for my waiter's funeral, which was decent of them. We are still open. Nobody sits by the window.'" },
    { depth: "sub", about: "sub:pill_wars", source: "archive", bias: "redacted", reliable: "partial", points: "sub:vein_wars", who: "Minutes of the pill-masters' guild", text: "Minutes of the pill-masters' guild, closed session, {year}: 'Resolved that the spirit-stone shortage shall not be mentioned outside this room. Prices to rise by a fifth, citing herb blight. Resolved further to buy every stone mined from the disputed vein at {lead} before the sects settle who owns it. Motion to warn the sects that the vein is failing: withdrawn, as bad for business.'" },
    { depth: "sub", about: "sub:sect_tournament", source: "library", bias: "propaganda", reliable: false, who: "Heralds of the Grand Tournament", text: "Proclamation of the heralds of the Grand Tournament, read in the square of {place}, {year}: 'The Grand Tournament is a festival of friendship between the sects. Every 30 years the young of every mountain meet in honour. The losers are always treated with respect, and receive a jade token and a hot meal. Injuries are rare and always accidental. At the last tournament there were 17, all accidental.'" },
    { depth: "sub", about: "sub:devouring_sects", source: "person", bias: "heretic", reliable: "partial", who: "A devouring elder, to an orthodox patriarch", text: "Letter from an elder of the devouring path to the patriarch of an orthodox sect, {year}, delivered with a severed sword-hand: 'You take essence from the earth until the valleys go grey. I take it from men like you, one core at a time. Your sect has drained three veins in my lifetime. Which of us is the parasite? Answer before spring, or I come for yours.'" },
    { depth: "sub", about: "sub:gate_above", source: "archive", bias: "official", reliable: "partial", points: "site:chained_peaks", who: "{official}, record of the envoy from above", text: "Record of the envoy from the upper realm, written by {official}, record-elder, {year}: 'It came through the gate at the third bell and stayed one hour. It was courteous. It asked our ages and laughed. It called this world the bottom rung. It asked whether any of us were ripe, and whether the chains at {lead} still held. We did not understand either question.'" },
    { depth: "site", about: "site:sword_stele", source: "traveller", bias: "true", reliable: "partial", who: "A travelling swordsman's journal", text: "Journal of a travelling swordsman, the inn opposite the stele, {year}: 'I looked at the stele for an hour and saw a sword-form, the 12th I have taken from it. The old master beside me has looked at it for a year. Today the master saw a door, and wept, and paid the bill, and went home to a family not seen in forty years. I was left the master's sword. I do not know what to do with it.'" },
    { depth: "site", about: "site:sealed_abode", source: "oral", bias: "garbled", reliable: "partial", points: "cast:survivor", who: "{survivor}, letter to a younger disciple", text: "Letter from {survivor}, a former disciple, to a younger one still at the sect, {year}: 'The cave on the cliff asks what you would give up to enter. I watched 30 disciples answer anything, and the door stayed shut for all 30. I answered my rank, and it opened. I will tell you what was inside if you come to me at {lead}. Do not ask the elders. They know.'" },
    { depth: "site", about: "site:glass_crater", source: "archive", bias: "official", reliable: "partial", points: "site:glass_crater", who: "{official}, register of the sect", text: "Register of the sect above {place}, in the hand of {official}, record-elder, {year}: 'Elder of the Severance realm attempted the crossing. 81 bolts. The elder ascended at dawn, to great honour. A crater of green glass remains at {lead}; disciples are forbidden to dig in it. Item, one iron storage ring: not recovered. Item, one disciple: left the sect without leave.'" },
  ],
};
