// Borrowed Grace: gods who lend power and live on belief, and what the faithful are slowly realising about who needs whom.
export default {
  id: "borrowed_grace",
  name: "Borrowed Grace",
  family: "power",
  pitch: "Priests work miracles with power lent by their gods. But gods are made of worship, a starving god grows desperate, and the faithful are slowly realising that the gods need them more than they need the gods.",
  slots: ["power-source", "divine-order", "power-access"],
  tone: ["mythic", "grim"],
  era: ["stone", "bronze", "medieval", "renaissance"],
  scale: "world",
  genres: ["fantasy", "mythic", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "body_of_the_world", w: 2.5 }, { id: "unremembering", w: 2 }, { id: "unquiet_gate", w: 1.5 }, { id: "walking_mountains", w: 1 }],

  power: {
    name: "grace", user: "grace-bearer", users: "grace-bearers",
    taught: "The gods lend their power to those who serve them. Prayer, vows and rites open the way, and each god grants only within its own domain.",
    rules: ["Each god grants only within its domain: harvest, war, sea, death, the road.", "A miracle needs the god's symbol, the right rite and the god's attention.", "Grace can be withdrawn at the god's whim, and apostates lose it at once.", "Great miracles burn out the vessel who carries them."],
    forbidden: "Consecrating a new god, or killing a god's last believer.",
  },

  cast: [
    { role: "investigator", n: "an auditor of the great temple's treasury who keeps the tallies of belief", home: "capital", stance: "Counts prayers like grain for the church, and has begun to wonder who the yield is delivered to." },
    { role: "official", n: "a high chaplain of the great church, keeper of the sanctum keys", home: "capital", stance: "Believes the church must keep the bells ringing, whatever is or is not on the throne." },
    { role: "believer", n: "the novice-mistress of the convent of saints", home: "inner", stance: "Believes a saint's self-emptying is the highest gift a soul can give, and has trained forty saints." },
    { role: "survivor", n: "the grown child of a saint who was perfected and no longer knows them", home: "any", stance: "Wants their parent back, and wants the church to say aloud what a miracle costs." },
  ],

  truths: [
    { id: "empty_throne", n: "The throne is empty", d: "Gods are made and kept alive by worship. The great church's highest god died centuries ago, and the high chaplains work its miracles with a splinter of bone taken from its body. The faithful pray to an empty throne, and their prayers are feeding some other power that answers through the cathedral echo.", tags: ["truth:empty_throne"],
      known: [
        "A priest who climbed into the sanctum on a feast night wrote that the throne of the highest god was covered in dust, and that its voice came from a pipe in the wall. The church stripped the priest of office.",
        "Prayers in the Echoing Cathedral come back a heartbeat late, in another voice, answering things nobody said aloud. {official}, keeper of the sanctum keys, has forbidden prayer there after midnight.",
        "A reliquary behind the cathedral altar holds a glowing splinter of bone wired to the bells, inscribed 'taken from the body of the Highest on the day it fell silent'. Six high chaplains have signed beneath it.",
        "Confirmed: the highest god is dead. The high chaplains have worked its miracles for centuries with a splinter of its body, and kept the bells ringing so nobody heard the quiet. The prayers go to some other power.",
      ] },
    { id: "willing_doors", n: "Gods need willing doors", d: "Gods can act in the world only through mortals who freely let them in. Every miracle uses up part of that mortal's soul. The church trains children to say yes, counts what is left of each saint in a ledger, and calls a saint with nothing left 'perfected'.", tags: ["truth:willing_doors"],
      known: [
        "Saints who work many miracles grow quiet, stop laughing and stop dreaming. {survivor} says their parent, a saint, no longer knows their name. The church calls this holiness, and refuses the families' requests to visit.",
        "A saint's confessor wrote down the saint's last words: the god cannot heal unless the saint lets it in, and each time less of the saint is left. The church's doctrine says the vessel suffers no loss.",
        "The tally vault under the temple treasury holds a ledger of saints. Each has a count of miracles and a final column that falls from 100 to zero. The word 'perfected' sits beside every zero.",
        "Confirmed: every miracle spends part of the soul it passes through. Gods need willing mortals to act at all, and the church trains children to be willing. Its greatest saints have nothing of themselves left.",
      ] },
    { id: "god_farm", n: "The pantheon is a farm", d: "The gods did not make the world; they herd it. They eat mortal devotion, and the halls of the blessed are where they store the dead to eat later. The temples collect the 'yield' for them every season, and a heretic sect has learned how to starve a god by forgetting it.", tags: ["truth:god_farm"],
      known: [
        "Temple tallies count devotion by province, and the totals in the margins are headed 'yield'. {investigator}, the treasury auditor, asked who receives it and was told it was not their concern.",
        "A traveller who followed a dead wife down the road of the dead says the halls of the blessed are shelves of silent dead, taken down one at a time. The church calls the traveller mad.",
        "A sealed cave holds ten thousand idols, all with open mouths facing one wall. Behind it is a granary for worship, with chutes and a floor of grey dust where the stores were eaten.",
        "Confirmed: the gods farm mortals. They eat devotion while people live and store the dead to eat later, and the temples deliver the yield. The starvers have found the one defence: forget a god entirely, and it dies.",
      ] },
  ],

  tags: ["lent_grace"],

  subthemes: [
    { id: "forgotten_god", n: "The Forgotten God", d: "A god that once ruled the whole sea now fits in a basket, and travels the roads with the last old woman who believes in it. It still gets seasick.", w: 0.8, mods: [["near:ruins", 1.5], ["hospitable", 1.5]], tags: ["theme:forgotten_god"] },
    { id: "market_crusade", n: "The Crusade for Souls", d: "The great temple's holy wars are recruitment drives. Every conquered city is a new congregation, and every congregation makes the god stronger.", w: 1.2, req: { any: ["militant", "zealous", "gov:theocracy", "organised"] }, tags: ["theme:market_crusade"] },
    { id: "fallen_season", n: "The Season of Fallen Gods", d: "For one season the gods walked as mortals, and whoever killed one inherited its domain. The killers still rule, and they are afraid of each other.", w: 0.6, mods: [["near:ruins", 1.5]], tags: ["theme:fallen_season"] },
    { id: "made_saints", n: "The Made Saints", d: "A convent turns grieving children into saints by ordeal and isolation. Its saints work great miracles, and none of them smile.", w: 1, req: { any: ["organised", "faith:one_god", "gov:theocracy", "pious"] }, truthLink: "willing_doors", tags: ["theme:made_saints"] },
    { id: "priest_who_looked", n: "The Priest Who Looked", d: "A priest climbed into the sanctum on a feast night and found the throne of the highest god covered in dust. He has not stopped talking about it, yet.", w: 0.9, req: { any: ["organised", "faith:one_god", "pious"] }, truthLink: "empty_throne", tags: ["theme:priest_who_looked"] },
    { id: "godborn", n: "The Godborn", d: "Children of gods and mortals are raised in the palace as political pawns. Each is a claim on a domain, and their parents are jealous.", w: 0.9, req: { any: ["monarchy", "dynastic", "divine_right"] }, tags: ["theme:godborn"] },
    { id: "new_god", n: "The New God", d: "A city's belief in a fad, a champion, a lucky coin, is giving birth to a god. The old temples are not pleased.", w: 0.9, req: { any: ["has:city", "urbane", "mercantile"] }, truthLink: "empty_throne", tags: ["theme:new_god"] },
    { id: "iconoclasts", n: "The Iconoclasts", d: "A sect smashes idols and refuses to pray, not out of unbelief but to starve a god they say is a tyrant. The god has noticed.", w: 0.9, mods: [["egalitarian", 2], ["faith:philosophy", 2]], truthLink: "god_farm", tags: ["theme:iconoclasts"] },
    { id: "shrine_towns", n: "The Shrine Towns", d: "Pilgrim towns live on relics and pardons. The saint's fingers on sale number two hundred and six.", w: 1, req: { any: ["pilgrims", "lavish", "mercantile"] }, tags: ["theme:shrine_towns"], mark: { kind: "zone", n: "The pilgrim road", color: "#d0b070", size: [2, 4], where: "inner" } },
    { id: "afterlife_audit", n: "The Afterlife Audit", d: "A traveller came back from the road of the dead with a story: the halls of the blessed are storage shelves, and the blessed are being taken off them one at a time.", w: 0.6, truthLink: "god_farm", tags: ["theme:afterlife_audit"] },
    { id: "little_gods", n: "The Little Gods", d: "Every well, bridge and crossroads has its own tiny god, fed on a crust a day. The crusts are getting smaller, and the little gods are getting hungry.", w: 1.1, mods: [["faith:spirits", 2.5], ["faith:pantheon", 1.5], ["forest_folk", 1.5]], tags: ["theme:little_gods"] },
  ],

  sites: [
    { id: "echo_cathedral", n: "The Echoing Cathedral of $", kind: "anomaly", where: "capital", truthLink: "empty_throne", d: "A cathedral where prayers echo back a moment late, in another voice.",
      layers: {
        surface: { n: "The late echo", text: "In the great cathedral of {place}, every prayer echoes back a heartbeat late. The vergers time it with a sand-glass: half a breath, never more. Pilgrims pay a copper to pray in the north aisle, where the echo is loudest." },
        study: { n: "Another voice", text: "{investigator} sat in the north aisle for 40 nights in {year} and wrote down what the echo said. It speaks in a voice deeper than any priest's. On nine of those nights it answered prayers that nobody had spoken aloud." },
        dig: { n: "Wired to the bells", points: "cast:official", text: "Behind the altar, a reliquary holds a splinter of bone that glows the colour of candle-flame. Copper wires run from it up into the bell tower. The reliquary's key, and the record of who installed it, are held by the high chaplain at {lead}." },
        revelation: { n: "Keep the bells ringing", text: "The highest god died in the cathedral's first year. The high chaplains cut a splinter from its body and wired it to the bells so the miracles would go on. For 600 years they have hidden the silence. The prayers now go to a power nobody in the church has named, and it answers through the echo." },
      } },
    { id: "god_corpse", n: "The Sleeping Isle of $", kind: "wonder", where: "coast", d: "An island the islanders say is a god, lying face down in the sea.",
      layers: {
        surface: { n: "The face-down island", text: "An island three miles long lies off the coast in the shape of a sleeping figure, face down. The islanders say it is a god. Once a year, on the sighing day, the whole shore breathes out, and nobody puts out a boat." },
        study: { n: "Ribs and wounds", text: "{investigator} measured the cliffs in {year}. They are bone, curved like ribs, 22 of them. The hot springs below run red-brown and never cool. The islanders bathe their sick there and call the springs the wounds that never closed." },
        dig: { n: "The mouth", points: "library", text: "In the heart of the island is a cavern shaped like a mouth, with teeth as tall as doors. A last prayer is carved along the teeth in an alphabet older than the church. A rubbing was taken, and its translation was filed in {lead}." },
        revelation: { n: "Worshipping a body", text: "The island is the body of a sea-god that died before the church was founded. The prayer on its teeth asks for one believer to stay. That century the great church's missionaries baptised the whole coast, and the god starved. The islanders still leave it a fish every morning, out of habit. The church taxes the catch." },
      } },
    { id: "idol_cave", n: "The Cave of Idols at $", kind: "ruin", where: "remote", truthLink: "god_farm", d: "A sealed cave packed with ten thousand clay idols of a nameless god.",
      layers: {
        surface: { n: "Ten thousand idols", text: "A cave in the hills was found sealed with river clay in {year}. Inside stand ten thousand clay idols of a god with no name, packed so tight a child cannot walk between them. Shepherds sell them in the valley as doorstops." },
        study: { n: "Open mouths", text: "Every idol has its mouth open, and every one faces the same wall at the back of the cave. {investigator} counted 104 rows. The back wall is brick, newer than the cave, and warm to the touch like a bread oven." },
        dig: { n: "The granary", points: "archive", text: "Behind the wall is a chamber built like a granary, with three chutes from the cave above and an ankle-deep floor of fine grey dust. A tally board on the wall, headed 'yield', uses the same columns as the temple tallies kept in {lead}." },
        revelation: { n: "Stored like grain", text: "Worship was collected here like grain: the idols drew it in, the chutes carried it down, and the gods came to eat. The dust is what they left. The temple treasury still keeps the same columns and sends the yield up every season. The gods do not love people. They farm them." },
      } },
    { id: "hermit_shrine", n: "The Hermit's Shrine at $", kind: "shrine", where: "forest", d: "A moss-roofed shrine whose god is at home, because one hermit still prays.",
      layers: {
        surface: { n: "The fire that never goes out", text: "A moss-roofed shrine stands in the forest, a day's walk from any road. Its fire has not gone out in living memory. Woodcutters leave a log by the door each autumn, and the log is always gone by spring." },
        study: { n: "A god at home", text: "Here the shrine's god can be seen: warm, small, about the size of a cat, sitting by the fire. {investigator} visited in {year} and reported that it bowed. The hermit says it is grateful for every visitor, all three of them this decade." },
        dig: { n: "A hundred hermits", points: "temple", text: "Under the floor lie the bones of 100 hermits, each buried by the next, each with a name scratched on a slate. The first slate names a novice of the great convent. The convent's register at {lead} records that novice as 'run away'." },
        revelation: { n: "One soul is enough", text: "A god lives as long as one soul keeps it. When the great church let this little god's congregation die, one novice walked out of the convent to keep it alive. A hundred hermits have done the same since, one at a time, for a thousand years. The church has never sent anyone to help." },
      } },
    { id: "tally_vault", n: "The Tally Vault of $", kind: "ruin", where: "capital", truthLink: "willing_doors", d: "A vault beneath a temple treasury, full of ledgers of the faithful.",
      layers: {
        surface: { n: "Under the treasury", text: "A locked vault lies beneath the temple treasury of {place}. Three keys open it, and the treasury clerks hold only one. The door is oak bound with iron, and the floor in front of it is worn into a groove by feet." },
        study: { n: "Given and taken", text: "{investigator}, the treasury auditor, got all three keys in {year}. The ledgers count believers by province like grain, in two columns marked 'given' and 'taken'. There are 340 ledgers, the oldest from the founding of the church." },
        dig: { n: "The ledger of saints", points: "cast:survivor", text: "The last ledger is of saints: each name, each miracle, and a final column of numbers falling to zero. Beside one zero is a note: 'Family asks to visit. Refused.' The family's address, in {lead}, is written underneath." },
        revelation: { n: "Used up", text: "Every miracle spends part of the soul it passes through, and the ledger measures what is left. The convents train children to let the god in, count them down to zero, and call them perfected. The high chaplains have signed every page. There are 60 empty lines left in the book." },
      } },
  ],

  beings: [
    { id: "grace_stag", n: "Grace-stag", kind: "grazer", d: "A white stag sacred to a harvest god. It glows faintly when prayed to, and hunters who kill one lose their luck for life.", danger: 0, biomes: ["tempforest", "boreal", "alpine"], look: { size: 2, group: [1, 3], move: "herd", speed: 50, col: "#e8e0c8", col2: "#d0a040", body: "quad", active: "day", visible: true } },
    { id: "hungry_hearthgod", n: "Hungry hearth-god", kind: "small", d: "The tiny god of a forgotten well or bridge, starving. It steals bread from sills and, lately, the breath of sleeping children.", danger: 1, biomes: ["tempforest", "grass", "river", "swamp"], look: { size: 0.4, group: [1, 1], move: "solo", speed: 3, col: "#8a6a4a", col2: "#e0c080", body: "biped", active: "night", visible: false } },
    { id: "winged_herald", n: "Winged herald", kind: "bird", d: "A many-winged servant of a great god, seen above battlefields and coronations. It does not land unless the god is very hungry.", danger: 2, biomes: ["peaks", "alpine", "grass"], look: { size: 3, group: [1, 1], move: "solo", speed: 60, col: "#f0f0e0", col2: "#e0b040", body: "bird", active: "day", visible: true } },
  ],

  techs: [
    { id: "bg_offerings", n: "Offering-rites", field: "agriculture", level: 1, d: "The little gods of field and well are fed with bread and beer, and the harvest comes in." },
    { id: "bg_temple_rites", n: "Temple rites", field: "architecture", level: 2, d: "Great temples built to collect prayer, with every arch shaped to gather it." },
    { id: "bg_laying_on", n: "Laying on of hands", field: "medicine", level: 2, d: "Healing grace channelled through a priest's palms, at a price nobody counts." },
    { id: "bg_relics", n: "Relic-keeping", field: "arcana", level: 3, d: "Bones, blood and belongings of the holy, kept so that a god's attention lingers." },
    { id: "bg_tallies", n: "Tallies of belief", field: "writing", level: 4, d: "The faithful counted like grain, province by province, and the god's strength reckoned from the sum." },
    { id: "bg_divine_engineering", n: "Divine engineering", field: "natural_philosophy", level: 5, d: "The deliberate making, feeding and starving of gods." },
  ],

  units: [
    { id: "bg_oath_knights", n: "Oath-knights", role: "cavalry", mounted: 1, wpn: "lance", kit: "plate", ranks: 2, gap: 2.8, size: 50, w: 0.5, mods: [["pious", 2], ["militant", 3], ["theme:market_crusade", 4]] },
    { id: "bg_saints", n: "Saint's host", role: "magic", wpn: "staff", kit: "robe", ranks: 2, gap: 3, size: 15, w: 0.3, mods: [["theme:made_saints", 8], ["gov:theocracy", 2]] },
  ],

  faiths: [
    { id: "bg_little_gods", n: "The Small Shrines", d: "Every well, bridge and crossroads has its own small god, fed daily with bread and a kind word.", tags: ["faith:bg_little_gods"], w: 1, names: ["The Small Shrines of $", "The Hundred Little Gods", "The Hearth and Well"], mods: [["forest_folk", 1.5], ["insular", 1.5], ["egalitarian", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Divine battlefields", color: "#e0d8a0", size: [1, 2], count: [0, 2], where: "any", d: "Glassed ground and holy springs where gods once fought each other." },
  ],

  storylines: [
    { id: "bg_iconoclasts", n: "The Iconoclasts of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: "lent_grace",
      stages: {
        start: { h: "Iconoclasts smash the idols of {capital}", b: "A sect in {capital} preaches that the gods eat prayer, and that the only freedom is to stop feeding them. Last night they broke every statue in the great temple.", wait: [2, 5], fx: { unrest: 10 }, next: [{ to: "crackdown", w: 2 }, { to: "spreads", w: 1, mods: [["egalitarian", 2], ["faith:philosophy", 2]] }] },
        crackdown: { h: "The priests of {faith} hunt the iconoclasts", b: "Temple guards have dragged the sect's preachers from their beds. {person}, their leader, was burned in the square of {capital}, and did not pray.", wait: [2, 6], next: [{ to: "crushed", w: 1 }, { to: "martyrs", w: 1 }] },
        martyrs: { h: "The iconoclasts of {realm} have martyrs", b: "{person} died on the pyre without a word of prayer, and that convinced more people than any sermon. In every town of {realm}, people are leaving the temples empty.", wait: [2, 6], next: [{ to: "spreads", w: 1 }] },
        spreads: { h: "Prayers cease across {realm}", b: "Whole villages have stopped praying. The priests' miracles fail, the holy springs run cold, and the harvest-rites bring no rain.", wait: [4, 10], fx: { stability: -6 }, next: [{ to: "god_starves", w: 1 }, { to: "god_bargains", w: 1 }] },
        crushed: { h: "The iconoclasts of {realm} are crushed", b: "The sect is broken and the statues are being recarved. The priests of {faith} preach a little more carefully now.", fx: { stability: 3, unrest: 4 }, end: true },
        god_starves: { h: "A god dies in {realm}", b: "On a still morning every temple bell in {realm} cracked at once. The priests of {faith} have no miracles left, and some of them look relieved.", fx: { stability: -10, flag: "godless", science: { natural_philosophy: 0.5 } }, end: true },
        god_bargains: { h: "The god of {realm} comes to terms", b: "The god appeared in {capital} as a thin old man and begged. It offered to work for its food: rain on time, no plague, fair harvests. The iconoclasts are negotiating.", fx: { stability: 6, prestige: 8 }, end: true },
      } },
    { id: "bg_saint", n: "The Saint of {place}", scale: "local", anchor: "town", w: 1.5, req: "lent_grace",
      stages: {
        start: { h: "A miracle at {place}", b: "{person}, who takes in washing in {place}, laid hands on a drowned boy, and the boy coughed up the river. The pilgrims are already coming.", wait: [2, 5], fx: { prestige: 2 }, next: [{ to: "miracles", w: 2 }, { to: "church_takes", w: 1, mods: [["organised", 2], ["theme:made_saints", 3]] }] },
        miracles: { h: "{person} heals the sick of {place}", b: "{person} heals every day now, and talks less each day. {survivor}, the healer's child, says the healer no longer laughs, or dreams.", wait: [3, 8], next: [{ to: "hollow", w: 1 }, { to: "refuses", w: 1 }] },
        church_takes: { h: "The church takes {person} away", b: "Priests in fine carriages came for the saint of {place}. The saint heals in the great temple now, behind a screen, three times a day.", wait: [3, 8], next: [{ to: "hollow", w: 2 }, { to: "refuses", w: 1 }] },
        hollow: { h: "The saint of {place} is hollowed out", b: "{person} still works miracles, but no longer knows family or friends, or answers to a name. The church has declared the saint perfected.", fx: { stability: 4, unrest: 4 }, end: true },
        refuses: { h: "{person} closes the door", b: "{person} told the god no. The miracles stopped that day, and so did the pilgrims. The saint went back to the washing and laughed for the first time in a year.", fx: { prestige: -2, stability: 2 }, end: true },
      } },
    { id: "bg_new_god", n: "The Champion of {place}", scale: "local", anchor: "town", w: 1, req: ["lent_grace", { any: ["has:city", "urbane", "mercantile"] }],
      stages: {
        start: { h: "Strange luck in {place}", b: "Everyone in {place} talks about {person}, a prize-fighter who has never lost. People touch the fighter's statue for luck now, and it works.", wait: [3, 8], next: [{ to: "cult", w: 2 }, { to: "fades", w: 1 }] },
        cult: { h: "A new god is worshipped in {place}", b: "There is a shrine to the champion in every tavern of {place}, and its priests are bookmakers. The temples of {faith} are half empty.", wait: [3, 8], fx: { unrest: 6 }, next: [{ to: "war_of_gods", w: 1, mods: [["zealous", 2], ["organised", 2]] }, { to: "accepted", w: 1, mods: [["tolerant", 2]] }, { to: "fades", w: 1 }] },
        fades: { h: "The luck of {place} runs out", b: "{person} lost a fight, and the little god faded away within a week. Folk in {place} are embarrassed about it now.", fx: { stability: 2 }, end: true },
        war_of_gods: { h: "The old temple burns the new shrines", b: "Priests of {faith} led a mob through {place}, smashing the champion's shrines. That night the old temple's roof fell in.", fx: { unrest: 12, stability: -5 }, end: true },
        accepted: { h: "{place} has a new god", b: "The champion's god has been given a niche in the temple of {faith}. It answers prayers about wagers and nothing else, and it is very good at them.", fx: { prestige: 3, discovery: "natural_philosophy" }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "temple", bias: "official", reliable: true, who: "Priests' catechism, chapter three", text: "Catechism of the priests of the {faith}, chapter three, on asking, {year} edition: 'Ask within the god's domain: the harvest god for rain, the road god for a safe journey. Ask humbly. Ask once. A god asked twice may answer the second time with the opposite. Grace is lent, not given. A priest who breaks a vow will find that the next miracle does not come.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: true, who: "A ferry-keeper of {place}, to a traveller", text: "A ferry-keeper of {place}, explaining to a traveller why there is bread on the bridge, {year}: 'My grandmother put a crust on the bridge-god's ledge every morning for 50 years, and the bridge never shifted. The year she died, nobody did it. By spring the planks had sprouted green shoots. Leave the bridge-god a crust every morning, or the bridge will remember it was once a tree.'" },
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: "partial", who: "A letter in a shrine's offering box", text: "Letter found in the offering box of a roadside shrine near {place}, {year}, written on bark in a shaking hand the parish priest could not identify: 'You used to bring me honey, every feast day for 30 years. I am not angry. I would only like to know that you are well. The well is still sweet. I have kept it sweet for you.'" },
    { depth: "core", about: "truth:empty_throne", source: "ruin", bias: "true", reliable: true, plain: true, who: "Reliquary inscription, copied by {investigator}", text: "Inscription inside the reliquary behind the cathedral altar, copied by {investigator} in {year}: 'Taken from the body of the Highest on the day it fell silent, in the first year of the cathedral. The Highest is dead. This splinter carries what is left of its grace. Wire it to the bells and keep the bells ringing. Never let the faithful hear the quiet.' Six high chaplains have signed beneath it." },
    { depth: "core", about: "truth:empty_throne", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, priest of the cathedral, diary", text: "Diary of {person}, priest of the cathedral of {place}, feast night, {year}: 'I climbed into the sanctum with a candle while the choir sang. The throne was dust, an inch deep. The voice that blesses us came out of a brass pipe in the wall.' Two days later {person} was stripped of the priesthood and sent to a hill parish of 12 souls, where this diary was found after the priest's death." },
    { depth: "core", about: "truth:empty_throne", source: "heretic", bias: "heretic", reliable: "partial", points: "site:echo_cathedral", who: "A hedge-preacher, taken down by a temple informer", text: "Sermon of a hedge-preacher outside the cathedral gates in {place}, {year}, taken down by a temple informer: 'Your prayers are letters to a dead god. Someone else has been opening the post. Go and pray in the north aisle of {lead} at midnight, and count the heartbeats before the reply. It is one, every time. A living god would not need to stop and think.'" },
    { depth: "core", about: "truth:empty_throne", source: "oral", bias: "garbled", reliable: "partial", who: "An old verger of the cathedral, to a new one", text: "Told by an old verger of the cathedral to a new one, {year}: 'Lock the north aisle at the midnight bell, and don't stay to pray. I prayed there once in my first year, for my brother. The echo answered in a voice like a cellar. It said things the god never would, and it knew my brother's debts to the penny: 14 silver. Lock up and go home.'" },
    { depth: "core", about: "truth:empty_throne", source: "temple", bias: "official", reliable: false, who: "{official}, high chaplain, feast-day proclamation", text: "Proclamation of {official}, high chaplain of the great church, read in every temple on the feast of {year}: '{deity} reigns eternal on the high throne, and every miracle of the church is the proof of it. This year the church recorded 3,000 healings. Rumours that the sanctum stands empty are the work of apostates, and repeating them will cost the speaker their grace.'" },
    { depth: "core", about: "truth:willing_doors", source: "archive", bias: "redacted", reliable: true, points: "site:tally_vault", who: "Ledger of saints, copied by an auditor", text: "Entry from the ledger of saints, copied out of the vault under the treasury at {lead} by a temple auditor, {year}: 'Sister of the well. Entered the convent aged 9. Miracles worked: four hundred and twelve. Remainder: none. Perfected.' The remainder column for her first year reads 100. It falls by about one for every four miracles." },
    { depth: "core", about: "truth:willing_doors", source: "person", bias: "true", reliable: true, plain: true, who: "A saint's last words, written by her confessor", text: "Last words of a saint of the convent, written down by her confessor at {place}, {year}: 'Every time the god asks, I let it in. It cannot heal anyone unless I do; it has no hands but mine. I have healed 300 people, and each time less of me is left. I have forgotten my mother's face, and then her name. Soon there will be nothing of me left, and the god will need another girl.'" },
    { depth: "core", about: "truth:willing_doors", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, novice-mistress, to new novices", text: "Address of {believer}, novice-mistress of the convent of saints, to 30 new novices, {year}: 'The saint empties herself so that the god may fill her. There is no higher gift a soul can give. You will forget things: your village, your games, your family's faces. Do not grieve for them; each one makes room for a miracle. I have trained 40 saints, and not one has asked for her old life back.'" },
    { depth: "core", about: "truth:willing_doors", source: "library", bias: "official", reliable: false, who: "Doctrine of Grace, approved by {official}", text: "From the Doctrine of Grace, the church's teaching text, approved by {official}, {year}: 'Miracles are the free gift of the gods, who act as and when they will. The mortal vessel is incidental, as a cup is to the wine, and suffers no loss. Saints who grow quiet in later years do so from contemplation. Eight in ten report great contentment.'" },
    { depth: "core", about: "truth:willing_doors", source: "person", bias: "true", reliable: true, cost: true, points: "archive", who: "{survivor}, petition to the high chaplain", text: "Petition of {survivor} to the high chaplain, {year}: 'My mother laid hands on a drowned boy in our town, and he lived. Your priests took her to the great temple to heal behind a screen, three times a day. I visited after two years. She looked at me kindly and asked my name. The ledger in {lead} says she has 6 left of 100. I ask you to stop before she reaches none.'" },
    { depth: "core", about: "truth:god_farm", source: "ruin", bias: "true", reliable: true, plain: true, who: "Builders' note on the granary wall, dated by {investigator}", text: "Painted on the granary wall behind the idols, dated by {investigator} to about 1,200 years ago: a shepherd with too many arms, and a flock of people walking into its mouth. Beneath it the builders wrote in red ochre: 'We built this store for the gods. They eat our prayers while we live and our souls when we die, and keep the dead on shelves until they are hungry. We were paid in rain.'" },
    { depth: "core", about: "truth:god_farm", source: "traveller", bias: "exaggerated", reliable: "partial", cost: true, points: "sub:afterlife_audit", who: "{person}, who walked the road of the dead", text: "Account of {person}, who walked the road of the dead and came back, told to an abbot in {year}: 'I followed my wife down the road for 40 days to the halls of the blessed. They were shelves, and the blessed were stacked on them, silent. My wife was on the third shelf. They were being taken down one at a time, and I could not see by whom. In {lead} they called me mad for saying so.'" },
    { depth: "core", about: "truth:god_farm", source: "heretic", bias: "heretic", reliable: true, points: "sub:iconoclasts", who: "An iconoclast, before the magistrate of {place}", text: "The first rule of the starvers, recited by an iconoclast before the magistrate of {place}, {year}: 'Do not hate the god. Hatred is a kind of worship. Do not curse it; do not smash its statue twice. Forget it. Being forgotten is the one thing a god cannot survive.' Asked to name the sect's teachers, the iconoclast named the 3 villages in {lead} where the temples already stand empty." },
    { depth: "core", about: "truth:god_farm", source: "archive", bias: "redacted", reliable: "partial", who: "Treasury tally, audited by {investigator}", text: "Annual tally of the temple treasury, {year}, audited by {investigator}: 'Devotion received this year, by province: northern, 41,000 prayers; river, 38,000...' The totals in the margin are headed, oddly, 'yield'. The auditor's query, pinned to the page, asks who the yield is delivered to. The reply from the high chaplain's office reads: 'Not your concern.'" },
    { depth: "core", about: "truth:god_farm", source: "temple", bias: "official", reliable: false, who: "Hymn-book preface by {official}", text: "Preface to the hymn-book of the {faith}, by {official}, high chaplain, {year} edition: 'The gods made the world and all within it out of love. The halls of the blessed are a paradise of rest, where the faithful dead sit at the gods' own table forever. Twelve thousand copies of this book have been printed. Pray from it daily, and be glad.'" },
    { depth: "sub", about: "sub:forgotten_god", source: "oral", bias: "true", reliable: "partial", points: "sub:forgotten_god", who: "A carter on the south road, to a temple scribe", text: "Told by a carter on the south road to a temple scribe in {place}, {year}: 'There's an old woman on the road with a little god in a basket, no bigger than a hen. It used to be the god of the whole sea, she says. She feeds it salt and sings to it. At the ford it was sick over the side. She is 80, she has nobody to leave it to, and she was heading for {lead}.'" },
    { depth: "sub", about: "sub:market_crusade", source: "archive", bias: "official", reliable: "partial", points: "sub:market_crusade", who: "A crusade commander, dispatch to the high chaplain", text: "Dispatch of a crusade commander to the high chaplain after the fall of a city, {year}: 'The city is taken. Converts, eleven thousand; refusers, sent to the mines. Temple raised in the square within 9 days. The god's strength in the region is expected to rise by a third. Request permission to march on {lead}, which has twice the people and a weaker god.'" },
    { depth: "sub", about: "sub:made_saints", source: "person", bias: "true", reliable: true, points: "cast:believer", who: "A farmer's daughter, letter to the convent", text: "Letter of a farmer's daughter of {place} to the convent of saints at {lead}, {year}, returned unopened: 'You took my sister at nine. You told her every day that her family was dead, until for her it was true. I have written 22 letters. This one has a lock of our mother's hair in it, so she will know who sent it. Please give it to her.'" },
    { depth: "sub", about: "sub:new_god", source: "traveller", bias: "garbled", reliable: "partial", who: "A wool merchant's travel notes, {place}", text: "Travel notes of a wool merchant passing through {place}, {year}: 'Here they pray to a prize-fighter, 27 fights unbeaten. People touch the fighter's statue before a wager, and the strangest thing is that it works: my own bet came in at five to one. The priests of the {faith} stand outside the taverns looking sour.'" },
    { depth: "sub", about: "sub:shrine_towns", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A pilgrim's letter home from {place}", text: "Letter of a pilgrim in the shrine town of {place} to family at home, {year}: 'I counted the saint's fingers on sale here: two hundred and six, at prices from a copper to a gold crown. She must have been a remarkable woman. I bought one of the cheaper ones. The seller gave me a written guarantee, which I enclose.'" },
    { depth: "sub", about: "sub:little_gods", source: "temple", bias: "pious", reliable: "partial", who: "A village priest's sermon notes, {place}", text: "A village priest's notes for the spring sermon at {place}, {year}: 'The little gods keep the little things. Feed them, and the bridge holds, the well runs sweet and the bread rises. Remind the parish: one crust a day per shrine. We have 31 shrines, and last month the crusts got smaller. Two wells have gone sour, and the mill-bridge creaks.'" },
    { depth: "site", about: "site:hermit_shrine", source: "person", bias: "true", reliable: "partial", points: "site:hermit_shrine", who: "The hermit of the forest shrine", text: "Letter of the hermit of the forest shrine, left in the woodcutters' box, {year}: 'I am the 101st hermit of this shrine, and I am 71. The god sits by the fire with me in the evenings and warms my hands. When I die the fire goes out, and so does the god. I hope someone comes. The path to {lead} is marked with white stones.'" },
    { depth: "site", about: "site:god_corpse", source: "oral", bias: "garbled", reliable: "partial", points: "site:god_corpse", who: "An island fisherwoman, to {investigator}", text: "Told by an island fisherwoman to {investigator}, {year}: 'Once a year the island sighs. The whole shore breathes out, warm, and the gulls go up. On that day nobody fishes; my uncle went out once and came home without his boat. We leave a fish on the rocks each morning, 365 a year. If you go to {lead}, go on any other day.'" },
    { depth: "site", about: "site:idol_cave", source: "traveller", bias: "true", reliable: "partial", points: "site:idol_cave", who: "A shepherd's report to the magistrate of {place}", text: "Report of a shepherd to the magistrate of {place}, {year}, about a cave in the hills: 'The clay seal cracked after the rains. Inside are clay idols, more than I could count, every mouth open, every face turned to the back wall. I took 6 to sell. The back wall of the cave at {lead} is warm enough to dry socks on, and the flock will not graze near it.'" },
  ],
};
