// The Bound Nine: colossal beasts of the world's life-force, sealed into human hosts and owned by nations.
export default {
  id: "bound_nine",
  name: "The Bound Nine",
  family: "power",
  pitch: "Nine colossal beasts made of the world's own life-force are sealed inside human hosts: living weapons owned by nations, and hated by the villages they protect.",
  slots: ["power-access", "bloodline", "state-control", "monster-source"],
  tone: ["heroic", "grim"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "shonen", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "great_root", w: 2.5 }, { id: "walking_mountains", w: 2 }, { id: "elder_lattice", w: 1.5 }, { id: "pale_visitor", w: 1.5 }, { id: "blood_debt", w: 1.5 }],

  power: {
    name: "the inner current", user: "current-adept", users: "current-adepts",
    taught: "Every body carries a current of mixed breath and will along hidden channels. Adepts mould it with hand-signs into workings of earth, wind, fire, water or lightning. The Nine are vast pools of that same current given beast-shape, and a sealed beast lends its host a sea of it.",
    rules: ["Everyone has channels; training opens them.", "Each person leans to one of five elements.", "Hand-signs shape a working; masters need fewer.", "A host can draw on their beast only so far as the beast allows."],
    forbidden: "Extracting a beast from its host, raising the dead, and taking another's eyes.",
  },

  cast: [
    { role: "investigator", n: "an archivist of the village academy who catalogues the sealing scrolls", home: "inner", stance: "Wants to know why the harvest records are filed beside the hosts' names." },
    { role: "official", n: "an elder of the village council, which decides what is done with its beast", home: "forest", stance: "Holds that the beast must stay sealed and the host kept apart, for everyone's safety." },
    { role: "believer", n: "a heron-hermit of the sage mountain", home: "mountain", stance: "Teaches that the current is borrowed from the world and must one day be paid back." },
    { role: "survivor", n: "a former host whose beast was torn out by the Collectors", home: "remote", stance: "Lived alone for twenty years for the village's sake, and wants to know what it was for." },
  ],

  truths: [
    { id: "one_beast", n: "The Nine are one", d: "The Nine were cut by the first sage from a single beast, the guardian of a world-tree, so that no one hand could hold it. If the Nine are brought together they will become that beast again. The Collectors are working towards it, and so, quietly, are the beasts themselves.", tags: ["truth:one_beast"],
      known: [
        "Hosts in different villages, who have never met, report the same dream from their beasts: eight others, which the beast calls its 'other hands'. The academies record it as a fever of the seal.",
        "The Collectors pull beasts out of their hosts and into a stone statue, and seven are already gone. {survivor}, whose beast was taken, says it went willingly. The Collectors' creed calls the first sage a butcher.",
        "A crater of nine rings holds nine cracked beast statues and a tenth plinth, empty, sized for all nine together. The first sage's own inscription on the plinth asks forgiveness.",
        "Confirmed: the Nine are one beast, cut apart by the first sage. Brought together they become the world-tree's guardian again. The Collectors hold seven, and the villages are still counting theirs.",
      ] },
    { id: "stolen_current", n: "The current was stolen", d: "Every human channel descends from a stranger from the sky who ate the fruit of the world-tree. The beasts are what remains of the tree's fury at the theft. Her vessel still waits under the stump, and her kin are coming back to harvest what she planted.", tags: ["truth:stolen_current"],
      known: [
        "Heron-hermits teach that the current is borrowed from the world and that the lender will come for it. Students who draw too much of the world's own current turn to stone where they sit.",
        "Inside the oldest of the stone students is a heart of living green wood, with growth rings. {believer}, a heron-hermit, says the current in a body and the sap of the tree are one thing.",
        "Under the roots of the Great Stump lies a vessel of unknown metal with one empty chair, and a line of signs that every adept's hands half-know: 'Planted. Return at ripening.'",
        "Confirmed: the human current was stolen. A stranger from the sky ate the world-tree's fruit, and everyone with channels descends from her. Her vessel was built to carry the harvest home, and the harvest is her children.",
      ] },
    { id: "suffering_subsidy", n: "The hosts pay for the harvest", d: "A host's misery feeds the land: the worse the host's year, the richer the village harvest. The councils know it, and keep their hosts lonely and hated on purpose. A host who befriends their beast breaks the seal and ends the extra harvest, and the councils call that treason.", tags: ["truth:suffering_subsidy"],
      known: [
        "Host villages bring in better harvests than their neighbours, and the councils credit fine soil. The host in each village eats alone, and nobody can say who first told the children to keep away.",
        "Council minutes cut the harvest forecast when a host makes a friend, and order the friend's family moved. {investigator}, the academy archivist, found the minutes filed with the grain accounts.",
        "In the sealed archive of a dead village, harvest records sit beside the host's name for a hundred years. Every good harvest follows the host's worst year, and the village starved the winter its host was loved.",
        "Confirmed: the hosts pay for the harvest. Their misery feeds the land, and the councils keep them lonely on purpose. When a host is loved, the seal thins and the fields fail.",
      ] },
  ],

  tags: ["sealed_beasts"],

  subthemes: [
    { id: "orphan_host", n: "The Orphan Host", d: "A child with the marks of a beast burned into their palms is raised by nobody in particular. The village knows what is in them and treats them accordingly; the child does not know why.", w: 1.4, truthLink: "suffering_subsidy", tags: ["theme:orphan_host"] },
    { id: "hidden_villages", n: "The Hidden Villages", d: "The land is held by fortified villages in cliffs and forests, each a state with an academy and a beast. Their carved stone faces watch over the passes.", w: 1.3, req: { any: ["forest", "mountain", "hills", "forest_folk", "mountain_folk"] }, mods: [["martial", 1.5]], tags: ["theme:hidden_villages"], mark: { kind: "zone", n: "Carved cliffs", color: "#8a7050", size: [1, 2], where: "forest" } },
    { id: "eye_massacre", n: "The Eye-Clan Massacre", d: "A clan whose eyes see through lies was wiped out in a single night. The one survivor has learned that the order came from his own village's council.", w: 1, req: { any: ["autocracy", "harsh_law", "spy_network", "hierarchical"] }, tags: ["theme:eye_massacre"] },
    { id: "beast_cult", n: "The Collectors", d: "A league of cloaked killers is hunting hosts one by one, extracting their beasts into a stone statue. Seven are already gone.", w: 1.1, truthLink: "one_beast", tags: ["theme:collectors"] },
    { id: "beast_race", n: "The Beast Count", d: "Villages measure power by how many beasts they hold. Two have signed a treaty limiting hosts; both are cheating.", w: 1, req: { any: ["has:rival", "martial", "standing_army", "realm:mid", "realm:large"] }, truthLink: "suffering_subsidy", tags: ["theme:beast_count"] },
    { id: "sage_hermits", n: "The Heron Mountain", d: "On a mountain of talking herons, hermits teach the slow art of drawing on the world's own current. Students who rush it turn to stone and stay as they fell.", w: 0.9, req: { any: ["mountain", "mystic", "ascetic", "faith:spirits"] }, truthLink: "stolen_current", tags: ["theme:heron_mountain"] },
    { id: "failed_hosts", n: "The Marsh of Failed Hosts", d: "The sealing experiments of an old war left a marsh full of people whose sealing went wrong halfway. Beast-flesh has grown over them, and they are barely human now.", w: 0.7, req: { any: ["marsh", "swamp", "river"] }, tags: ["theme:failed_hosts"], mark: { kind: "zone", n: "The Unsealed Marsh", color: "#4a5a3a", size: [1, 3], where: "remote" } },
    { id: "beasts_rights", n: "The Host Who Made Friends", d: "A host has talked to their beast for ten years and the beast has started answering. The seal is thinning. The council is terrified, and the fields are failing.", w: 0.8, req: { any: ["egalitarian", "hospitable", "faith:spirits", "tolerant"] }, truthLink: "suffering_subsidy", tags: ["theme:beast_friend"] },
    { id: "tree_rising", n: "The Tree in the Desert", d: "A green shoot has broken out of the giant stump in the central waste. Wells for a hundred miles are drying up.", w: 0.7, req: { any: ["desert", "badlands", "hot", "steppe"] }, truthLink: "one_beast", tags: ["theme:tree_rising"] },
    { id: "moon_prison", n: "The Sealed Mountain", d: "Herders say a mountain in the north is hollow and someone is inside. The priests seal its passes every spring; lately the seals have been found broken from within.", w: 0.7, req: { any: ["mountain", "cold", "seers", "faith:stars"] }, truthLink: "stolen_current", tags: ["theme:sealed_mountain"] },
    { id: "proxy_war", n: "The Proxy War", d: "Small realms between the great villages have become their battlefields. Adepts in borrowed colours burn fields that are not theirs.", w: 1, req: { any: ["realm:tiny", "realm:small", "unstable", "frontier"] }, tags: ["theme:proxy_war"] },
  ],

  sites: [
    { id: "nine_crater", n: "The Nine Rings of $", kind: "ruin", where: "remote", truthLink: "one_beast", d: "A crater of nine rings, with nine broken statues in a cave beneath.",
      layers: {
        surface: { n: "Nine rings", text: "A crater of nine overlapping rings lies in the waste, two miles across, as if a huge animal had circled nine times before lying down. Nothing grows on the ring walls. Caravans go round the long way, which adds four days." },
        study: { n: "Nine statues", text: "A cave under the crater floor holds nine stone beasts: fox, crab, ox, hound, horse, bird, serpent, cat and one with a dozen tails. {investigator} found every seal cracked. Seven of the cracks are fresh, and the stone dust still lies on the floor." },
        dig: { n: "The tenth plinth", points: "sub:beast_cult", text: "Behind the statues stands a tenth plinth, empty, big enough for a beast made of all nine together. Grey wool fibres with stitched eyes are caught on its edge. The Collectors who wear such cloaks were last reported in {lead}." },
        revelation: { n: "Cut from one body", text: "The first sage cut the Nine from one body here: the guardian of the world-tree, split so that no single realm could hold it. The tenth plinth was carved for the day it is made whole. The sage left the villages to decide when. They spent 900 years counting beasts instead, and the Collectors hold seven." },
      } },
    { id: "eye_tablet", n: "The Eye-Tablet of $", kind: "shrine", where: "any", d: "A stone tablet that shows different words to eyes of different strength.",
      layers: {
        surface: { n: "A blank slab", text: "A slab of black stone in the eye-clan's shrine looks blank to ordinary eyes. Visitors pay the shrine-keeper a copper to stare at it. The shrine-keeper, who has clan eyes, reads it aloud to them for two coppers." },
        study: { n: "Two histories", text: "The clan's eyes read a history on it: the first sage's account of the Nine. Stronger eyes, opened by grief, read a second history beneath it. Only four living members of the clan could read the second layer in {year}." },
        dig: { n: "Cut lines", points: "sub:eye_massacre", text: "At the deepest level the words change again, and a later hand has cut away certain lines with a chisel. The chisel marks are newer than the stone. The last clan member who could read this deep fled after the massacre, to {lead}." },
        revelation: { n: "The edited tablet", text: "The first sage wrote that the clans should share the Nine. Over 200 years, the council's archivists chiselled that line out and carved 'Trust no brother' in its place, to keep the clans at each other's throats and the council in charge. The eye-clan was massacred the year after it noticed." },
      } },
    { id: "stone_forest", n: "The Stone Students of $", kind: "anomaly", where: "mountain", truthLink: "stolen_current", d: "A petrified forest of people.",
      layers: {
        surface: { n: "Stone students", text: "On a high slope stand 60 human-shaped stones, all facing the dawn. Goatherds leave them hats in winter. Heron-hermits sweep the snow off them each morning and will not say why." },
        study: { n: "Cross-legged", text: "Each statue sits cross-legged, palms up. {believer}, a heron-hermit, names each one from the mountain's roll: students who drew too much of the world's own current and stopped mid-breath. The oldest name on the roll is 900 years old." },
        dig: { n: "Green heartwood", points: "site:great_stump", text: "A rockfall split the oldest stone in {year}. Inside is a heart of green wood, still alive, with growth rings. The grain matches a cutting taken from the stump in the desert at {lead}." },
        revelation: { n: "The tree takes it back", text: "The current in human bodies was taken from the world-tree, not given. Draw too much of the world's own current, and the tree takes its part back: the body turns to its wood and stone. The heron-hermits have known this for 900 years, and still accept students who are in a hurry." },
      } },
    { id: "great_stump", n: "The Great Stump at $", kind: "wonder", where: "desert", truthLink: "stolen_current", d: "A tree-stump of impossible size in a central waste.",
      layers: {
        surface: { n: "A bark cliff", text: "A grey cliff stands in the desert, 30 miles round. Travellers learn it is bark when they try to climb it. The oasis at its foot is the only water for a week's ride in any direction." },
        study: { n: "Bitten rings", text: "The stump's rings are a day's walk across. {investigator} counted 11,000 of them before the light failed. The innermost rings are scorched in a crescent, like a bite taken out of an apple." },
        dig: { n: "One chair", points: "cast:believer", text: "Under the roots is a vessel of no metal anyone can name, with one chair, empty, and a line of signs on the wall. Every adept who sees the signs moves their hands without meaning to. The heron-hermit at {lead} can read three of them." },
        revelation: { n: "Planted", text: "A stranger from the sky landed here, ate the world-tree's fruit, and took its current into her body. Everyone with channels descends from her, and the tree's fury became the Nine. The signs read: 'Planted. Return at ripening.' Her vessel was built to carry the harvest home. It still has fuel." },
      } },
    { id: "seal_archive", n: "The Sealed Archive of $", kind: "dig", where: "inner", truthLink: "suffering_subsidy", d: "A dead village's archive of sealing scrolls, locked by its last elder.",
      layers: {
        surface: { n: "A paper door", text: "A vault cut into the cliff of a dead village has a door of paper seals, 300 of them, every one still holding. The village emptied in a single bad winter 80 years ago. Scavengers took the roofs and left the door alone." },
        study: { n: "Harvests beside names", text: "{investigator}, an academy archivist, opened the seals one by one over a month. The scrolls are harvest records, kept year by year beside the host's name, in the council's hand. Nothing else in the vault concerns farming." },
        dig: { n: "The worst years", points: "archive", text: "Every good harvest in a hundred years follows the host's worst year: a beating, a shunning, a lonely winter, each noted in the margin. The council's other villages kept the same ledgers, and their copies went to the academy archive at {lead}." },
        revelation: { n: "Fed on misery", text: "This village's council kept its host lonely on purpose, because a host's misery fattens the fields. In the last year a farmer's daughter befriended the host. The seal thinned, the harvest failed, and the village starved that winter. The council's final entry blames the girl." },
      } },
  ],

  beings: [
    { id: "great_beast", n: "Unbound great beast", kind: "beast", d: "One of the Nine, free: a fox or ox or crab the size of a hill, made of raw current, furious at everything.", danger: 3, biomes: ["tempforest", "grass", "alpine", "swamp", "dryforest"], look: { size: 40, group: [1, 1], move: "solo", speed: 25, col: "#c05020", col2: "#f0b040", body: "quad", active: "any", visible: true } },
    { id: "talking_heron", n: "Mountain heron", kind: "bird", d: "A grey heron of the sage mountain, as tall as a man, who teaches, scolds and gossips.", danger: 0, biomes: ["alpine", "river", "temprain"], look: { size: 1.8, group: [1, 6], move: "flock", speed: 30, col: "#8a90a0", col2: "#e0e0d0", body: "bird", active: "day", visible: true } },
    { id: "marsh_halfling", n: "Half-sealed", kind: "beast", d: "A failed host of the old war, half-covered in the hide and bone of a beast that never sealed properly. They live in the marsh and remember being people.", danger: 2, biomes: ["swamp", "mangrove"], look: { size: 2, group: [1, 5], move: "solo", speed: 7, col: "#5a6a3a", col2: "#a04030", body: "biped", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "b9_hand_signs", n: "Hand-signs", field: "arcana", level: 1, d: "A shared grammar of gestures for shaping the inner current." },
    { id: "b9_academies", n: "Village academies", field: "warfare", level: 2, d: "Ranked schools that turn children into adepts, and adepts into soldiers." },
    { id: "b9_seal_tags", n: "Seal-paper", field: "writing", level: 2, d: "Brushed paper tags that bind, burst or track: the workhorse of every adept." },
    { id: "b9_sealing", n: "Host sealing", field: "arcana", level: 3, d: "The method for binding a great beast into a newborn. It kills one sealer in three." },
    { id: "b9_world_current", n: "The world's current", field: "natural_philosophy", level: 4, d: "Drawing on the current of the land itself, at the risk of turning to stone." },
    { id: "b9_eye_grafts", n: "Eye-grafting", field: "medicine", level: 5, d: "Clan eyes transplanted into strangers. Forbidden, and practised by every council." },
  ],

  units: [
    { id: "b9_adepts", n: "Village adepts", role: "infantry", wpn: "javelin", kit: "light", ranks: 2, gap: 2.4, size: 60, w: 1.5, mods: [["theme:hidden_villages", 5], ["theme:proxy_war", 2]] },
    { id: "b9_host", n: "Host and escort", role: "magic", wpn: "staff", kit: "light", ranks: 1, gap: 4, size: 8, w: 0.3, mods: [["theme:beast_count", 6], ["theme:orphan_host", 3]] },
  ],

  govs: [
    { id: "b9_village_state", n: "Hidden village", d: "A fortified village of adepts that is also a state, ruled by its strongest adept and a council of elders who decide what is done with its beast.", tags: ["gov:hidden_village", "autocracy"], w: 0.5, forms: ["Hidden Village of $", "$ in the Leaves", "Cliff of $"], ruler: "Village Head", mods: [["theme:hidden_villages", 8], ["martial", 1.5], ["realm:tiny", 2], ["realm:small", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Beast-scar", color: "#a06040", size: [1, 3], count: [1, 2], where: "any", d: "A valley gouged by a loose beast's fury, or a lake the shape of a paw." },
  ],

  storylines: [
    { id: "b9_orphan", n: "The Marked Child of {place}", scale: "local", anchor: "town", w: 2, req: "sealed_beasts",
      stages: {
        start: { h: "The marked child of {place} fails the academy", b: "{person}, the orphan with the ember-marks on both hands, failed the academy test of {place} for the third time and painted the village elders' faces in the night. Nobody laughed.", wait: [2, 6], next: [{ to: "teacher", w: 2 }, { to: "lured", w: 1, mods: [["harsh_law", 1.5], ["unstable", 1.5]] }] },
        teacher: { h: "A teacher takes on the child of {place}", b: "{person2}, a tired teacher, has taken {person} as a student, and told the child the truth about the beast inside. The village is furious.", wait: [6, 18], fx: { flag: "taught" }, next: [{ to: "friend_beast", w: 1, mods: [["egalitarian", 2], ["theme:beast_friend", 3]] }, { to: "hero", w: 2 }] },
        lured: { h: "Cloaked strangers visit {place}", b: "The Collectors have come for the host of {place}. They told {person} the village would be better off without them, and {person} believed it.", wait: [1, 3], next: [{ to: "taken", w: 1 }, { to: "hero", w: 1 }] },
        hero: { h: "The beast of {place} turns the battle", b: "When raiders came over the wall, {person} let the beast out just far enough. {place} stands. The elders bow now, and nobody quite looks the child in the eye.", fx: { prestige: 6, stability: 4 }, end: true },
        friend_beast: { h: "The host of {place} and the beast make peace", b: "{person} and the beast have made a compact. The seal is gone, and so is the fat harvest of {place}. The council calls it treason.", fx: { growth: -0.002, unrest: 8, discovery: "arcana" }, end: true },
        taken: { h: "The host of {place} is taken", b: "{person} was found in the forest, alive, with the beast torn out. Far away, in the Collectors' statue, an eighth pair of eyes opened.", fx: { stability: -6, unrest: 10 }, end: true },
      } },
    { id: "b9_collectors", n: "The Ninth Host of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["sealed_beasts", { any: ["big", "martial", "has:rival", "atwar"] }],
      stages: {
        start: { h: "{realm} hides its last host", b: "Word has come that the Collectors hold eight beasts. {realm} has the ninth, in a host named {person}, and {ruler} has ordered the host moved in secret.", wait: [2, 5], next: [{ to: "ambush", w: 2 }, { to: "alliance", w: 1, mods: [["has:ally", 2], ["ruler:charismatic", 2]] }] },
        ambush: { h: "The host's escort is ambushed", b: "The escort was cut down in a mountain pass. {person} escaped on foot with {person2}, a disgraced eye-clan survivor nobody trusts.", wait: [2, 6], fx: { stability: -4 }, next: [{ to: "nine_together", w: 1, mods: [["chance:low", 2], ["unstable", 1.5]] }, { to: "turned_back", w: 2 }] },
        alliance: { h: "Old enemies unite to guard the last host", b: "For the first time in a hundred years the villages have sent their adepts to fight under one banner, around one frightened host.", wait: [3, 8], fx: { prestige: 5 }, next: [{ to: "turned_back", w: 2 }, { to: "nine_together", w: 1 }] },
        turned_back: { h: "The Collectors are broken", b: "The cult's last stand failed in a burning valley. Eight beasts walked out of the shattered statue and went their own ways, and the hosts of {realm} are counting the cost.", fx: { stability: 5, prestige: 8, unrest: 6 }, end: true },
        nine_together: { h: "The Nine are one", b: "The ninth beast was torn out of {person} at midnight. By dawn a giant tree had grown up into the sky over {realm}, and nobody in the land could cast a working.", fx: { stability: -20, pop: 0.85, titan: true }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "Academy first-year scroll, {place}", text: "First-year scroll of the village academy of {place}, {year} copy: 'The inner current is breath and will mixed together, running along channels in the body. Heron, kiln, root, lantern: each hand-sign is a valve on the current. A clumsy hand opens the wrong valve, and you will learn that lesson only once. Of last year's 40 first-years, 3 learned it.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "A woman of {place}, to {investigator}", text: "A grown woman of {place}, remembering her childhood to {investigator}, academy archivist, {year}: 'My mother said, don't play with the ember-handed child. There is a fox in him, and the fox remembers who was cruel. So for six years none of us did. He used to sit on the wall and watch us play. I think now the fox remembers that too.'" },
    { depth: "lore", about: "power", source: "archive", bias: "propaganda", reliable: false, who: "History of the Village of {place}, academy copy", text: "From the official History of the Village of {place}, chapter 9, held in the academy library: 'Our hosts are honoured as heroes and volunteers, cherished by the whole village, and lack for nothing.' The archivist's copy has a slip of paper tucked into this page, in the hand of {official}, elder of the council: 'Do not show to the host.'" },
    { depth: "core", about: "truth:one_beast", source: "ruin", bias: "true", reliable: true, plain: true, who: "The first sage, on the tenth plinth", text: "Inscription on the empty tenth plinth in the nine-ring crater, in the first sage's script, read by {investigator} in {year}: 'I cut the guardian of the tree into nine so that no one hand could hold it. Nine for now. Forgive me. Put together, they are one beast again, and this plinth is for that day. May it come when the world has learned to share.'" },
    { depth: "core", about: "truth:one_beast", source: "person", bias: "true", reliable: "partial", cost: true, points: "site:nine_crater", who: "{survivor}, former host, to the council", text: "Account of {survivor}, a former host, to the village council, {year}: 'For 22 years my beast dreamed of eight brothers. It did not call them brothers. It called them its other hands. In spring two grey cloaks pulled it out of me like a thread from a hem. I am alive, but I cannot feel heat or cold, and my village has stopped needing me. The beast went gladly, toward {lead}.'" },
    { depth: "core", about: "truth:one_beast", source: "heretic", bias: "heretic", reliable: "partial", points: "site:nine_crater", who: "Collectors' creed, sewn into a grey cloak", text: "Creed of the Collectors, sewn into the lining of a grey cloak taken from a corpse at {place}, {year}: 'The sage was a butcher. We are surgeons, sewing the body back together. Seven stitches are made; two remain. The plinth waits at {lead}. When the ninth is in, the guardian will stand again, and the villages will have nothing left to count.'" },
    { depth: "core", about: "truth:one_beast", source: "library", bias: "official", reliable: false, who: "Bestiary of the Nine, approved by {official}", text: "From the academy's Bestiary of the Nine, approved by {official}, elder of the council, {year}: 'The nine great beasts arose separately, each from a different calamity of the old age, and share nothing but their size. Stories that they were once one creature are a Collector lie. Students who repeat them will be held back one year.'" },
    { depth: "core", about: "truth:stolen_current", source: "ruin", bias: "true", reliable: true, plain: true, who: "Vessel signs, translated by {believer}", text: "Signs on the wall of the vessel under the Great Stump, translated by {believer}, heron-hermit, after three years of study: 'I ate the fruit of the tree and took its current into me. My children will carry it in their channels, and their children after them. Planted. Return at ripening.' The hermit adds: 'Every adept is her child. The current was stolen, and the owners will collect.'" },
    { depth: "core", about: "truth:stolen_current", source: "temple", bias: "pious", reliable: "partial", points: "site:stone_forest", who: "{believer}, heron-hermit, to a new student", text: "Teaching of {believer}, heron-hermit of the sage mountain, to a new student, {year}: 'Your current is borrowed from the world. Breathe it back when you can, little one, for the lender will come. If you doubt me, go to the slope at {lead} and count the stone students. There are 60. Each of them took more than they gave back.'" },
    { depth: "core", about: "truth:stolen_current", source: "traveller", bias: "exaggerated", reliable: "partial", points: "sub:moon_prison", who: "A fur trader, report to the priests of the passes", text: "Report of a fur trader to the priests of the north passes, {year}: 'The herders swear the hollow mountain has a woman in it, sitting in a chair of grey metal, waiting for her children to grow. I laughed at them. Then I saw the spring seals on the pass above {lead}: 12 paper seals, all broken, and all broken from the inside.'" },
    { depth: "core", about: "truth:stolen_current", source: "library", bias: "official", reliable: false, who: "{official}, Treatise on Channels", text: "From the academy's Treatise on Channels, by {official}, {year}: 'The channels are an organ of the human body, like the veins, given by the gods at the dawn of the world to all peoples alike. They owe nothing to any tree. The 60 so-called stone students on the sage mountain died of cold, and their shape is a trick of the weather.'" },
    { depth: "core", about: "truth:stolen_current", source: "person", bias: "true", reliable: true, cost: true, who: "{believer}, letter to a student's family", text: "Letter of {believer}, heron-hermit, to the family of the student {person}, {year}: 'Your child sat for nine days drawing on the mountain's own current. On the tenth morning the fingers were stone. By noon, all of {person} was. We carried the stone to the slope with the others. Inside the stone there is wood. I am sorry. I never told the students whose current it is.'" },
    { depth: "core", about: "truth:suffering_subsidy", source: "archive", bias: "redacted", reliable: "partial", points: "cast:investigator", who: "Minutes of the elders of {place}", text: "Minutes of the elders of {place}, {year}, filed with the grain accounts: 'The host is reported to have made a friend, a weaver's son. Harvest forecast cut by a quarter. The friend's family to be moved to...' The rest is blotted out. The academy archivist {investigator} copied the page before the blotting and keeps the copy at {lead}." },
    { depth: "core", about: "truth:suffering_subsidy", source: "person", bias: "true", reliable: true, plain: true, who: "A dying elder of {place}, confession", text: "Confession of a dying elder of {place}, taken down by a heron-hermit, {year}: 'We never let the boy be happy. The host's misery feeds the fields: a bad year for the boy, a good year for the rice. Every elder on the council knew it. We told the village it was for safety. It was for the rice. In 30 years we never had a famine.'" },
    { depth: "core", about: "truth:suffering_subsidy", source: "oral", bias: "garbled", reliable: "partial", who: "Threshing rhyme of {place}, noted by {investigator}", text: "Rhyme sung by the children of {place} at threshing time, noted by {investigator} in {year}; nobody could say where it came from: 'Fat year, sad year; sad host, good harvest; cry, little fox, and we eat.' The children clap twice on 'cry'. The host of {place} is 12 years old and does not come to the threshing." },
    { depth: "core", about: "truth:suffering_subsidy", source: "library", bias: "official", reliable: false, who: "Council harvest office, signed by {official}", text: "Report of the council's harvest office, signed by {official}, {year}: 'Harvests in host villages are no better than elsewhere. Any apparent difference, which the office puts at about a third, is due to the fine soils on which the hidden villages were founded. The office recommends no further study, and no further questions from the academy archive.'" },
    { depth: "core", about: "truth:suffering_subsidy", source: "person", bias: "true", reliable: true, cost: true, who: "A weaver of {place}, letter to a sister", text: "Letter of a weaver of {place} to a sister, {year}: 'My son {person} played with the host every day for one summer. That autumn the rice failed on 40 acres. The council moved us to the border, where the raids are, and gave no reason. {person} is ten, and asks every day whether the host has anyone to play with now. I do not know what to answer.'" },
    { depth: "sub", about: "sub:orphan_host", source: "person", bias: "true", reliable: true, who: "Scratched under an academy bench, {place}", text: "Scratched under a bench in the back row of the academy of {place}, found by a carpenter mending it in {year}: 'Nobody sits next to me. I counted. Four years, three terms a year, 12 terms. The teacher moved my bench to the back so the others would not be afraid.' The carpenter asked who had sat there. The academy said the bench had always been empty." },
    { depth: "sub", about: "sub:eye_massacre", source: "archive", bias: "redacted", reliable: "partial", points: "site:eye_tablet", who: "A council order, half-burned", text: "Council order, half-burned, found in the eye-clan's quarter after the massacre, {year}: '...the clan to be removed in one night, all 140, by the night watch under seal. Any child found hiding in the well-houses is to be spared, sent to the academy, and watched. The tablet at {lead} is to be guarded until the clan's readers are dead.' The seal is the council's own." },
    { depth: "sub", about: "sub:beast_cult", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A pedlar's statement to the watch at {place}", text: "Statement of a pedlar to the watch at {place}, {year}: 'Grey cloaks with nine eyes stitched on the back. Only ever two at a time. I saw one of them draw a beast out of a girl, hand over hand, like a bucket up a well. It took about as long as boiling an egg. The girl lived. The cloaks paid me a silver piece not to have seen it, and I spent it.'" },
    { depth: "sub", about: "sub:sage_hermits", source: "temple", bias: "pious", reliable: "partial", who: "A mountain heron, as written down by {believer}", text: "Instruction given by a mountain heron to a new student, written down by {believer}, {year}: 'Sit still until the frogs forget you are there. Then you will hear the mountain breathe. Breathe with it, not against it. You will want to hurry. The 60 on the lower slope hurried.' The heron then complained about the food for an hour, which the hermit did not write down." },
    { depth: "sub", about: "sub:failed_hosts", source: "oral", bias: "true", reliable: true, who: "A ferryman at the edge of the marsh", text: "Told by a ferryman at the edge of the Unsealed Marsh to a travelling scholar, {year}: 'My uncle went into the marsh to bring his brother home from the old war. Found him after nine days. Half of him had turned to beast, hide and bone, with a tusk through the cheek. He knew my uncle's name. He would not come. He said the marsh was the only place nobody counted him.'" },
    { depth: "sub", about: "sub:beast_race", source: "archive", bias: "official", reliable: "partial", points: "sub:beast_race", who: "Treaty of the Leaves, with sealed annex", text: "Treaty of the Leaves between two hidden villages, {year}, article four: 'Neither party shall hold more than two hosts.' Sealed annex, signed by {official}: 'Hosts not yet weaned are not counted. Hosts in training are not counted. Hosts on loan to an ally are not counted.' A clerk's pencil tally pinned to the copy in {lead} gives each side five." },
    { depth: "sub", about: "sub:proxy_war", source: "person", bias: "true", reliable: true, who: "A borderland farmer, letter to the lord of {realm}", text: "Letter of a borderland farmer to the lord of {realm}, {year}: 'They were not our adepts and it was not our war. Two villages' adepts fought in our valley for one afternoon. It was our wheat they burned, 200 acres, and our barn. Neither village will pay; each says the other started the fire. I enclose the ash.'" },
    { depth: "site", about: "site:eye_tablet", source: "person", bias: "true", reliable: "partial", points: "site:eye_tablet", who: "An eye-clan scholar, letter to a cousin", text: "Letter of an eye-clan scholar to a cousin, {year}, the year before the massacre: 'At the third depth the stone at {lead} says: Trust no brother. The chisel marks around it are newer than the stone, maybe 200 years newer. Something else was written there first. I have asked the council archive for the sage's original copy. They say there is none.'" },
    { depth: "site", about: "site:great_stump", source: "traveller", bias: "true", reliable: "partial", points: "site:great_stump", who: "A desert guide's journal", text: "Journal of a desert guide, {year}: 'Took four adepts to the stump at {lead}. At the roots their hands started making signs on their own, the same five signs over and over, and none of them knew what the signs meant. They wanted to go back at once and would not say why. I charge double for adepts now.'" },
    { depth: "site", about: "site:seal_archive", source: "archive", bias: "redacted", reliable: "partial", points: "site:seal_archive", who: "{investigator}, academy archive register", text: "Register of the academy archive, entry for {year}, in the hand of {investigator}: 'Received: one vault key, from the last elder of a dead village, on the elder's deathbed, with the words: open it and tell them. The vault is at {lead}, sealed with 300 paper tags. Request leave of one month to open it.' A second line reads: 'Leave refused. Taken anyway.'" },
  ],
};
