// Elemental Kinship: four peoples, four elemental arts first taught by beasts, and one soul reborn to hold all four.
export default {
  id: "elemental_kinship",
  name: "Elemental Kinship",
  family: "power",
  pitch: "Each people can move one element (stone, tide, flame or wind) through martial forms first learned from great beasts. Once a generation, one person is reborn who can move all four and walk among the spirits.",
  slots: ["cosmology", "divine-order", "power-access", "bloodline"],
  tone: ["heroic", "mythic"],
  era: ["bronze", "medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "shonen", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "walking_mountains", w: 2.5 }, { id: "strewn_sky", w: 2 }, { id: "wheel_of_suns", w: 2 }, { id: "elder_lattice", w: 1.5 }],

  power: {
    name: "the kin-forms", user: "form-master", users: "form-masters",
    taught: "Breath drawn through the martial forms moves the element around you. Each people moves its own element, as its ancestors did, and the spirits watch to keep the balance.",
    rules: ["One element to each soul, by birth; only the Bridge moves all four.", "The element must be near: no stone-master moves stone in a ship.", "The heart shapes the art: drive feeds flame, patience feeds tide, stubbornness feeds stone, letting go feeds wind.", "A troubled mind warps the art, and a master at war with herself can lose it."],
    forbidden: "Moving the blood inside a living body.",
  },

  cast: [
    { role: "investigator", n: "a scholar of the sinking library who collects the oldest forms", home: "desert", stance: "Wants to rebuild the first teaching from what each people has kept, and suspects the peoples kept it apart on purpose." },
    { role: "official", n: "a minister of forms in the stone capital, who certifies masters and approves the histories", home: "capital", stance: "Holds that four separate arts keep the peace, and that the Bridge belongs to whichever state finds it." },
    { role: "believer", n: "a custodian of the Bridge, who tests children with the box of old toys", home: "mountain", stance: "Believes the Bridge is reborn to keep the balance, and has started to fear what the custodians are not told." },
    { role: "survivor", n: "a hidden descendant of the wind-folk, raised in a stone village", home: "mountain", stance: "Can move the wind and has hidden it for thirty years; wants the wind-folk's killing called what it was." },
  ],

  truths: [
    { id: "fused_spirit", n: "The Bridge is half a spirit", d: "The Bridge, who is reborn each generation, is a mortal fused ten thousand years ago with a spirit of order. Its twin, a spirit of disorder, is sealed in the roots of the great tree, and the two must meet when the sky aligns. The arts were only lent by the spirit-titans, and the custodians have never told a Bridge that the loan can be called in.", tags: ["truth:fused_bridge"],
      known: [
        "Past Bridges wrote in their diaries of someone else inside them, very old and afraid of nothing but the great tree. The custodians call these entries the strain of rebirth and keep the diaries locked.",
        "A spirit at the twin pools told a traveller that the elements were lent so mortals would not starve, and that a loan is not a gift. The roots of the great tree are clenched around a hollow that smells of thunderstorms.",
        "Carvings in the tree's hollow show two spirits, one light and one dark, and the light one stepping into a human body. {believer}, a custodian, saw them and has asked twice for the hollow to be sealed.",
        "Confirmed: the Bridge is half a spirit, the order-half of a pair. The disorder-half is sealed under the great tree. When the sky aligns they will meet, and the spirits who lent the arts will decide whether to take them back.",
      ] },
    { id: "one_art", n: "The four were one art", d: "The four disciplines were once a single teaching, split by force so that no people could hold all of it, and the nations were built along the cracks. The three peoples then marched together, the one time in history, to massacre the wind-folk who kept the whole teaching, hoping to end the Bridge's cycle forever.", tags: ["truth:sundered_art"],
      known: [
        "Old masters of every art open with the same bow, palms up then palms down, and none can say why. The minister of forms teaches that the four arts were given separately to four peoples, and that the bow means nothing.",
        "The wind-folk were wiped out a century ago. The 212 monks in their temple died back to back, killed by flame, stone and tide fighting side by side. The official histories blame a fever.",
        "A defaced treaty of the three peoples orders the wind-folk who 'refuse to divide the teaching' destroyed, and the cycle 'thereby ended'. {investigator} found it in the sinking library, filed under weather.",
        "Confirmed: the four arts were one. The three peoples split it to keep each other weak, then united once, to kill the wind-folk and burn the last whole copy. The Bridge was reborn anyway.",
      ] },
    { id: "beast_teachers", n: "The beasts were the teachers", d: "Each art was taught to the first people by a lineage of thinking beasts: burrow-bears, tide-eels, sun-drakes and sky-oxen. As each line dies out, its art decays into empty technique. The last sun-drakes are being hunted for trophies, and every horn sold makes every flame-master in the world a little weaker.", tags: ["truth:beast_teachers"],
      known: [
        "The burrow-bears no longer come to the stone-masters' caves. The forms are taught perfectly, and each generation of students moves a little less stone than the last. The minister of forms blames lazy teachers.",
        "Cave paintings show the first people copying the stances of bears, eels, drakes and great oxen, step by step. Their bones lie curled beside beast bones, wrapped in the same red cloth, like kin.",
        "The season a sun-drake's horn was hung in an inn, the flame-masters of the region found their fires smaller. {survivor} says the wind went slack the year the last sky-ox herd was seen.",
        "Confirmed: the beasts were the teachers. Each art lives only while its teaching beasts live. The sun-drakes are down to two, and every horn sold makes every flame-master in the world a little weaker.",
      ] },
  ],

  tags: ["elemental_arts"],

  subthemes: [
    { id: "flame_conquest", n: "The Comet War", d: "The flame-folk began a war of conquest under a comet that multiplied their fire a hundredfold. The comet is gone; the war has not ended.", w: 1.4, req: { any: ["autocracy", "gov:empire", "martial", "standing_army"] }, mods: [["hot", 1.5], ["warrior_code", 2]], truthLink: "one_art", tags: ["theme:flame_conquest"], mark: { kind: "zone", n: "The scorched march", color: "#8a3a1a", size: [2, 4], where: "border" } },
    { id: "last_wind_monk", n: "The Last of the Wind-Folk", d: "A boy found frozen in a mountain glacier has woken a century after his people were wiped out. He keeps asking for them by name.", w: 0.8, mods: [["mountain", 2], ["cold", 2], ["pious", 1.3]], truthLink: "one_art", tags: ["theme:wind_monk"] },
    { id: "levellers", n: "The Levellers", d: "The ungifted are nine in ten and pay all the taxes. In the factory city a masked movement fights the gifted with machines and nerve-strikes that stop the breath.", w: 1.1, req: { any: ["urbane", "has:city", "egalitarian", "artisans"] }, mods: [["hierarchical", 1.5], ["poor", 1.5]], tags: ["theme:levellers"] },
    { id: "spirit_wilds", n: "The Spirit Wilds", d: "The spirits have come back into the mortal world. Glowing vines split the streets of a city overnight, and spirits with mask-like faces walk the markets.", w: 1, mods: [["forest", 1.5], ["faith:spirits", 2], ["mystic", 1.5]], truthLink: "fused_spirit", tags: ["theme:spirit_wilds"], mark: { kind: "zone", n: "Spirit wilds", color: "#5ac08a", size: [1, 3], where: "forest" } },
    { id: "metal_wardens", n: "The Metal-Wardens", d: "Stone-masters who learned to move refined metal patrol the city on cables. They answer to the city council, and lately to no one.", w: 1, req: { any: ["has:city", "urbane", "harsh_law"] }, mods: [["mountain_folk", 1.5]], tags: ["theme:metal_wardens"] },
    { id: "blood_moon", n: "The Full-Moon Art", d: "Under the full moon a tide-master can move the blood inside a living body. The art is forbidden, hunted, and passed from mother to daughter in one coastal village.", w: 0.7, mods: [["coastal", 1.5], ["cold", 1.5], ["faith:void", 2.5]], tags: ["theme:blood_moon"] },
    { id: "sinking_library", n: "The Sinking Library", d: "A library of everything ever known sinks slowly into the desert, guarded by an owl the size of a tower who wants nothing from mortals but their curiosity.", w: 0.7, req: { any: ["desert", "hot", "badlands"] }, mods: [["scholarly", 2]], tags: ["theme:sinking_library"] },
    { id: "walled_calm", n: "The Walled Calm", d: "Inside the great rings of the stone capital no one speaks of the war. Those who do are quietly taken aside and taught to be calm again.", w: 1, req: { any: ["realm:large", "realm:vast", "gov:empire", "autocracy"] }, mods: [["harsh_law", 2], ["spy_network", 2]], tags: ["theme:walled_calm"] },
    { id: "last_drakes", n: "The Last Sun-Drakes", d: "Two sun-drakes hide in a ruined fire temple. They could reteach flame as it was first danced; trophy-hunters want their horns.", w: 0.9, mods: [["mountain", 2], ["hot", 1.5]], truthLink: "beast_teachers", tags: ["theme:last_drakes"] },
    { id: "silent_bears", n: "The Silent Bears", d: "The burrow-bears no longer come to the stone-masters' caves. The forms are taught perfectly, and the stone moves a little less each generation.", w: 0.9, mods: [["mountain_folk", 2], ["hills", 1.5], ["mountain", 1.5]], truthLink: "beast_teachers", tags: ["theme:silent_bears"] },
    { id: "bridge_search", n: "The Search for the Bridge", d: "The custodians test every child born in the year the last Bridge died with a box of old toys. This time two children chose rightly.", w: 1, req: { any: ["pious", "faith:spirits", "mystic", "ancestor_bound"] }, tags: ["theme:bridge_search"] },
  ],

  sites: [
    { id: "painted_caves", n: "The Painted Caves of $", kind: "ruin", where: "mountain", truthLink: "beast_teachers", d: "A cave of ochre paintings showing the first masters learning from beasts.",
      layers: {
        surface: { n: "Handprints", text: "A cave mouth on the mountain is daubed with red handprints, 300 of them by a herder's count. Some are human; some have claws. Stone-masters come here before their final test and press their palms beside the oldest." },
        study: { n: "Copying the stances", text: "Deeper in, 48 panels show people copying the stances of bears, eels, drakes and great oxen, step by step. {investigator} matched 12 panels to forms still taught today. The rest are lost to every school." },
        dig: { n: "Kin", points: "sub:silent_bears", text: "Under the floor lie beast bones laid in honour beside human bones, curled together like kin and wrapped in the same red cloth. The stone-masters of {lead} say no burrow-bear has come to their caves in 40 years." },
        revelation: { n: "Taught, not found", text: "The arts were not discovered. The beasts taught them, one student at a time, for thousands of years. When the peoples founded temple schools and wrote the forms down, they stopped going back to the teachers. The beasts are dying, and the arts are dying with them, one perfect form at a time." },
      } },
    { id: "wind_temple", n: "The Empty Wind Temple of $", kind: "ruin", where: "mountain", truthLink: "one_art", d: "A mountain temple of the wind-folk, full of skeletons in monks' robes.",
      layers: {
        surface: { n: "The bell", text: "Windswept terraces climb to a temple 9,000 feet up. A bell in the gate rings when no wind blows. Herders leave it alone. Nobody has lived here for a hundred years." },
        study: { n: "Back to back", text: "The monks died back to back in the courtyard, 212 of them. {investigator} examined the remains: burns, crushed bones, lungs full of water. Their killers wore every colour. Flame, stone and tide fought side by side, the only time in history." },
        dig: { n: "The abbot's scroll", points: "library", text: "In the abbot's cell is a scroll that draws the forms of all four arts as one dance, titled 'The first teaching, before the quarrel'. A partial copy, made by a stone officer who took part in the killing, is held in {lead}." },
        revelation: { n: "Why they burned it", text: "The four arts were once one. The wind-folk kept the last whole copy and refused to split it. The three peoples signed a treaty, marched together, and killed every monk, hoping to end the Bridge's cycle with them. The Bridge was reborn anyway, among the children of the killers." },
      } },
    { id: "great_tree", n: "The Great Tree of $", kind: "anomaly", where: "forest", truthLink: "fused_spirit", d: "A colossal tree with a sealed chamber in its roots.",
      layers: {
        surface: { n: "Fist roots", text: "A tree wider than a town stands in the forest, its roots knotted like fists. The custodians have ringed it with four shrines, one for each art. Pilgrims touch the bark and swear it is warm in winter." },
        study: { n: "The warm hollow", text: "The roots are clenched around a hollow that is warm and smells of thunderstorms. {believer}, a custodian, spent one night inside in {year} and came out with singed hair and a stammer that lasted a week." },
        dig: { n: "Two spirits", points: "cast:believer", text: "Carvings in the hollow show two spirits, one light and one dark, and the light one stepping into a human body. A tally of sky-alignments is cut beside them, and the next falls soon. The custodians' copy of the tally is kept at {lead}." },
        revelation: { n: "The jailer's half", text: "The Bridge is half a spirit. Ten thousand years ago the custodians' founders fused the spirit of order into a mortal and sealed its twin here, under four shrines facing inward. When the sky aligns, the two will meet. The custodians have known for a thousand years, and told no Bridge." },
      } },
    { id: "comet_scar", n: "The Comet Scar of $", kind: "anomaly", where: "any", d: "A crater lake ringed with black glass, sacred to the flame-folk.",
      layers: {
        surface: { n: "Black glass", text: "A round lake sits in a ring of black glass, warm in winter. Flame-folk pilgrims walk the ring barefoot. The glass is sharp, and the shrine sells bandages at the gate for a copper." },
        study: { n: "Hotter fire", text: "Fire burns hotter here. {investigator} lit the same lamp here and at home: by the lake it burned three times as bright, and the wick lasted a third as long. Flame-masters train here and leave with blistered hands." },
        dig: { n: "The hot heart", points: "archive", text: "Divers found the comet's heart under the lake, still hot after centuries; the water over it boils in winter. The flame-folk war calendar, which lists seven campaigns on the same span of years, is kept in {lead}." },
        revelation: { n: "A calendar of war", text: "The comet returns every 112 years, and its heart answers it from under the lake. Every flame-folk conquest began in a comet year. The flame generals have planned their wars around it for 800 years and called it destiny. The next return is due within a generation." },
      } },
    { id: "twin_pools", n: "The Twin Pools of $", kind: "shrine", where: "coast", d: "A shrine garden where two fish circle in two pools, one pale, one dark.",
      layers: {
        surface: { n: "Two fish", text: "Two pools lie in a shrine garden on the coast. In each a fish circles, one pale and one dark. Fishing families pay the shrine a basket of catch a month to feed them, and children are told not to put their hands in." },
        study: { n: "The tides follow", text: "The tides of the whole coast follow the fish. The shrine's tide-book, kept for 300 years, records high water each time the pale fish reaches the north end of its pool. The harbour-masters of four ports set their sailing days by the book, not by the sky." },
        dig: { n: "The tide-master's bones", points: "sub:blood_moon", text: "Under the pools lie the bones of a tide-master, with a note sealed in a jar: she gave her life to take the place of a slain fish. Her family came from the coastal village at {lead}, where the forbidden full-moon art is still taught." },
        revelation: { n: "Spirits need mortals", text: "A raider once killed the pale fish for its scales. The tides stopped for three days and every harbour on the coast dried out. A tide-master gave her own life to take the fish's place, and the tides came back. The raider's family still owns the coast's largest fleet." },
      } },
  ],

  beings: [
    { id: "sky_ox", n: "Sky-ox", kind: "grazer", d: "A shaggy six-legged ox that swims through the air. It taught the wind-folk to move the wind, and it has not been seen in herds since they died.", danger: 0, biomes: ["alpine", "peaks", "grass"], look: { size: 6, group: [1, 4], move: "herd", speed: 40, col: "#e8e2d0", col2: "#a07a40", body: "quad", active: "day", visible: true } },
    { id: "sun_drake", n: "Sun-drake", kind: "beast", d: "A crested drake whose fire-breath moves in coloured patterns. Proud, rare and hunted; flame-masters who have seen one never fight the same way again.", danger: 2, biomes: ["badlands", "peaks", "desert", "dryforest"], look: { size: 8, group: [1, 2], move: "pair", speed: 50, col: "#c0401a", col2: "#e8b030", body: "reptile", active: "day", visible: true } },
    { id: "burrow_bear", n: "Burrow-bear", kind: "beast", d: "A blind bear that hears through its paws and tunnels through rock as if it were snow. The first stone-masters learned from them.", danger: 2, biomes: ["boreal", "alpine", "tempforest", "badlands"], look: { size: 3, group: [1, 2], move: "solo", speed: 12, col: "#5a4a3a", col2: "#8a7a5a", body: "quad", active: "dusk", visible: true } },
    { id: "tide_eel", n: "Tide-eel", kind: "beast", d: "A sea-eel the length of a galley that rides the moon-tides. Fishers say the tide-masters' first forms are its swimming.", danger: 2, biomes: ["shelf", "polar", "open"], look: { size: 9, group: [1, 3], move: "pod", speed: 20, col: "#2a5a7a", col2: "#a0d0e0", body: "serpent", active: "night", visible: true } },
  ],

  techs: [
    { id: "ek_beast_forms", n: "The beast-forms", field: "warfare", level: 1, d: "The first masters copy the stances of the teaching beasts and find the element answers." },
    { id: "ek_temple_schools", n: "The temple schools", field: "writing", level: 2, d: "Each people writes down its forms and founds temples to teach them, and the forms begin to drift from the beasts." },
    { id: "ek_metal_moving", n: "Metal-moving", field: "metallurgy", level: 3, d: "A blind stone-master learns to feel the earth left in refined metal, and moves it." },
    { id: "ek_wind_ships", n: "Wind-ships", field: "navigation", level: 4, d: "Hulls lifted and driven by wind-masters, and later by hot air when the wind-masters run short." },
    { id: "ek_lightning_mills", n: "Lightning mills", field: "engineering", level: 4, d: "Flame-masters throw lightning into copper and turn the mills of a whole city." },
    { id: "ek_spirit_crossing", n: "Spirit-crossing", field: "natural_philosophy", level: 5, d: "A discipline of meditation that lets a master walk, for an hour, among the spirits." },
  ],

  units: [
    { id: "ek_flame_legion", n: "Flame legion", role: "magic", wpn: "staff", kit: "mail", ranks: 3, gap: 2, size: 60, w: 1, mods: [["theme:flame_conquest", 5], ["martial", 2], ["hot", 1.5]] },
    { id: "ek_stone_shapers", n: "Stone-shapers", role: "siege", wpn: "siege", kit: "mail", ranks: 2, gap: 3, size: 30, w: 0.8, mods: [["mountain_folk", 3], ["theme:walled_calm", 3]] },
    { id: "ek_metal_wardens", n: "Metal-wardens", role: "infantry", wpn: "spear", kit: "plate", ranks: 3, gap: 1.6, size: 60, w: 0.4, mods: [["theme:metal_wardens", 10]] },
  ],

  faiths: [
    { id: "ek_bridge", n: "The Way of the Bridge", d: "The custodians of the reincarnating Bridge, who preach balance between the four arts and the spirit world.", tags: ["faith:ek_bridge"], w: 1, names: ["The Way of the Bridge", "The Custodians of $", "The Fourfold Path"], mods: [["mystic", 2], ["faith:spirits", 1.5], ["pacifist", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Comet scars", color: "#3a2a2a", size: [1, 2], count: [0, 2], where: "any", d: "Black-glass craters where the comet fell, sacred to the flame-masters." },
  ],

  storylines: [
    { id: "ek_bridge_child", n: "The Child of {place}", scale: "local", anchor: "town", w: 1.5, req: "elemental_arts",
      stages: {
        start: { h: "Custodians come to {place} with a box of old toys", b: "{believer} and the custodians of the Bridge have tested every child born in the year the last Bridge died. In {place}, {person}, a fisher's child, reached past a hundred toys and chose the four that once belonged to the last Bridge.", wait: [2, 5], next: [{ to: "trained", w: 2 }, { to: "hidden", w: 1, mods: [["atwar", 2], ["unstable", 1.5]] }] },
        hidden: { h: "The child of {place} vanishes", b: "With war on the roads, the custodians have hidden {person} away. {survivor}, of the hidden wind-folk, has taken the child into the mountains.", wait: [6, 18], next: [{ to: "trained", w: 2 }, { to: "killed", w: 0.5 }] },
        trained: { h: "{person} masters a second element", b: "The child of {place} has moved both tide and stone, which no one living has done. Envoys from four peoples have begun to arrive.", wait: [6, 14], fx: { prestige: 4 }, next: [{ to: "awakened", w: 1 }, { to: "killed", w: 0.5, mods: [["atwar", 2], ["ruler:cruel", 2]] }, { to: "refuses", w: 1, mods: [["egalitarian", 1.5], ["theme:levellers", 2]] }] },
        awakened: { h: "The Bridge walks again", b: "{person} stood in the square of {place} and moved stone, tide, flame and wind in one breath. The spirits of the wild came out of the trees to watch.", fx: { prestige: 12, stability: 8, discovery: "natural_philosophy" }, end: true },
        killed: { h: "The child of {place} is murdered", b: "Assassins found {person} before the arts were whole. The custodians say the cycle of rebirth is broken, and the spirits have stopped showing themselves to anyone.", fx: { stability: -10, unrest: 15 }, end: true },
        refuses: { h: "{person} refuses to be the Bridge", b: "The child of {place} has walked away from the custodians, saying the world must learn to keep its own balance. Some call it betrayal; some call it the first wise thing a Bridge ever did.", fx: { unrest: 6, stability: -2 }, end: true },
      } },
    { id: "ek_comet", n: "The Comet over {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["elemental_arts", { any: ["martial", "autocracy", "gov:empire", "standing_army"] }],
      stages: {
        start: { h: "The astronomers of {realm} foretell the comet", b: "The court astronomers report that the comet of the old war will return within the year, and with it a fire no wall can stand against.", wait: [3, 8], next: [{ to: "muster", w: 2 }, { to: "restrain", w: 1, mods: [["ruler:peaceful", 3], ["ruler:just", 2]] }] },
        muster: { h: "{ruler} musters the flame legions", b: "Every flame-master in {realm} has been called to the colours. The forges of {capital} glow day and night under the coming comet.", wait: [3, 8], fx: { treasury: -40 }, next: [{ to: "comet_war", w: 2, req: "has:rival" }, { to: "comet_passes", w: 1 }, { to: "capital_burns", w: 0.5, mods: [["chance:low", 2]] }] },
        restrain: { h: "{ruler} forbids a war of the comet", b: "Against the generals, {ruler} has sworn that {realm} will not march under the comet. The flame legions mutter in their barracks.", wait: [3, 6], fx: { stability: 2 }, next: [{ to: "comet_passes", w: 2 }, { to: "legions_rise", w: 1, mods: [["martial", 2], ["theme:flame_conquest", 3]] }] },
        comet_war: { h: "{realm} marches under the comet", b: "With the comet burning overhead, the flame legions of {realm} crossed the border into {rival}. Their fire turned walls to glass.", fx: { war: "rival", prestige: 10 }, end: true },
        comet_passes: { h: "The comet passes over {realm}", b: "The fire rose and fell with the comet, and no war came of it. The flame-masters of {realm} say they will be ready next time.", fx: { stability: 3 }, end: true },
        capital_burns: { h: "Fire runs wild in {capital}", b: "Drunk on comet-fire, a young flame-master lost control in the training yards. Half of {capital} burned before the comet set.", fx: { pop: 0.9, stability: -10, unrest: 15 }, end: true },
        legions_rise: { h: "The flame legions turn on {ruler}", b: "Officers who would not miss the comet stormed the palace of {capital}. {ruler} did not survive the night.", fx: { ruler_dies: true, stability: -12, unrest: 10 }, end: true },
      } },
    { id: "ek_drakes", n: "The Drakes above {place}", scale: "local", anchor: "town", w: 1, req: ["elemental_arts", { any: ["mountain", "hills", "hot", "badlands"] }],
      stages: {
        start: { h: "Trophy-hunters come to {place}", b: "Hunters with chains and harpoons have taken rooms in {place}, asking the way to the old fire temple. They say the last sun-drakes nest there.", wait: [2, 5], next: [{ to: "hunt", w: 2 }, { to: "warned", w: 1, mods: [["hospitable", 1.5], ["pious", 1.5]] }] },
        warned: { h: "{person2} rides ahead to warn the drakes", b: "A flame-master of {place}, {person2}, left in the night to reach the fire temple before the hunters.", wait: [2, 5], next: [{ to: "taught", w: 2 }, { to: "hunt", w: 1 }] },
        hunt: { h: "The hunt for the sun-drakes begins", b: "{person} leads the hunters up the mountain with a cart of chains. Smoke has been seen rising from the old temple.", wait: [2, 6], next: [{ to: "drake_slain", w: 1 }, { to: "taught", w: 1, mods: [["theme:last_drakes", 3]] }] },
        drake_slain: { h: "A sun-drake's horn hangs in {place}", b: "The hunters came back with one horn and a burned arm. The flame-masters of the region say their fires have been smaller ever since.", fx: { prestige: 2, unrest: 4 }, end: true },
        taught: { h: "The sun-drakes dance for {person2}", b: "Instead of prey, the hunters found {person2} dancing with two drakes in a ring of coloured fire. The flame-masters of {place} have begun relearning their art from the beginning.", fx: { discovery: "warfare", prestige: 6 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "Temple-school primer, {place}", text: "First-year primer of the temple school of {place}, {year} edition: 'The kin-forms are martial forms; breath drawn through them moves your people's element. Stone is moved by the one who will not be moved. Tide by the one who yields. Flame by the one who wants. Wind by the one who lets go. Practise each form 1,000 times before you ask the element to answer.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "A net-mender of {place}, to a grandchild", text: "A net-mender of {place} to a grandchild who could not move water, overheard by a temple scribe, {year}: 'Your grandmother's art is in your blood, child. If she moved the tide, so will you. If she moved nothing, be content and mend the nets. Nine in ten of us move nothing at all, and the nets still need mending.'" },
    { depth: "lore", about: "power", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, custodian of the Bridge", text: "Sermon of {believer}, custodian of the Bridge, at the four-shrine ring, {year}: 'The Bridge is reborn so the four peoples will remember they are one. About every 70 years a child of one people moves all four elements, stone, tide, flame and wind, and the wars stop for a while.' The custodian did not say what the Bridge must do when the peoples forget." },
    { depth: "core", about: "truth:fused_spirit", source: "ruin", bias: "true", reliable: true, plain: true, who: "Founders' carving in the great tree, read by {investigator}", text: "Carved in the hollow of the great tree, read by {investigator} by lamplight in {year}: 'We put the spirit of light into the man, and the spirit of dark into the roots. The man will be born again and again, and we call him the Bridge. When the sky stands in a straight line, they will look each other in the face.' Fourteen founders' names are carved below." },
    { depth: "core", about: "truth:fused_spirit", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, the Bridge of 300 years ago, diary", text: "From the diary of {person}, the Bridge of 300 years ago, in a hand the present Bridge knows as their own: 'There is someone else in here. It is very old, and afraid of nothing but the tree. It wants me to go down to the roots.' The last entry is dated the year of the last alignment. {person} walked into the great tree that night and did not come out." },
    { depth: "core", about: "truth:fused_spirit", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:twin_pools", who: "A salt merchant's journal", text: "Journal of a salt merchant who stayed a night at the shrine at {lead}, {year}: 'A spirit came up out of the pale pool, with a face like a mask and no notion of nations at all. It said: we lent you the elements so you would not starve in our world. A loan is not a gift. Then it asked me the date, twice, and counted on its fingers. It had 7 of them, and needed all 7.'" },
    { depth: "core", about: "truth:fused_spirit", source: "heretic", bias: "heretic", reliable: "partial", points: "site:great_tree", who: "An expelled custodian's broadsheet", text: "Broadsheet of a custodian expelled from the four-shrine ring, {year}: 'The Bridge is no saviour. It is a jailer reborn, 140 times so far, and every war it ends is a war that kept us from asking what it guards. Ask the custodians why the four shrines around the tree at {lead} face inward, and none face out.'" },
    { depth: "core", about: "truth:fused_spirit", source: "temple", bias: "official", reliable: false, who: "The custodians' answer to the court of {realm}", text: "Official answer of the custodians of the Bridge to a question from the court of {realm}, {year}: 'The Bridge is a mortal soul of perfect balance, reborn by the grace of the spirits. Nothing is sealed in the great tree but its own roots. The four shrines were placed for the convenience of pilgrims. The custodians thank the court for its gift of 300 silver.'" },
    { depth: "core", about: "truth:one_art", source: "ruin", bias: "true", reliable: true, plain: true, who: "The abbot's scroll, copied by {investigator}", text: "Scroll found in the abbot's cell of the wind temple, copied by {investigator} in {year}: all four arts drawn as one dance in 64 figures, titled 'The first teaching, before the quarrel.' In the margin, in the abbot's hand: 'The four arts are one art, cut in four by the three peoples so that none could hold it whole. We keep the whole. They will come for it.'" },
    { depth: "core", about: "truth:one_art", source: "archive", bias: "redacted", reliable: "partial", points: "sub:sinking_library", who: "A defaced treaty of the three peoples", text: "A treaty of the three peoples, much defaced, found by {investigator} in the sinking library at {lead}, {year}: '...the wind-folk who refuse to divide the teaching shall be... by the three armies together, before the next comet, and the cycle thereby ended for...' It bears the seals of flame, stone and tide. The space for a fourth seal is empty." },
    { depth: "core", about: "truth:one_art", source: "heretic", bias: "exaggerated", reliable: "partial", points: "sub:levellers", who: "Leveller pamphlet on the mill gates of {lead}", text: "Leveller pamphlet, pasted on the mill gates of {lead}, {year}: 'THE GIFTED SPLIT THEIR OWN ART SO NO ONE COULD HOLD IT ALL. Then they killed the wind-folk, 212 monks, for refusing. WHAT ELSE HAVE THEY SPLIT TO KEEP YOU SMALL? Nine in ten of us are ungifted. Count the council.'" },
    { depth: "core", about: "truth:one_art", source: "library", bias: "official", reliable: false, who: "{official}, Concordance of the Four Arts", text: "From the Concordance of the Four Arts, certified by {official}, minister of forms, {year}: 'The four arts were given to four peoples, each according to its nature. No master has ever moved two elements, and none ever will, save the Bridge alone. The wind-folk perished of a mountain fever in the year of the comet, as the 3 national histories agree.'" },
    { depth: "core", about: "truth:one_art", source: "person", bias: "true", reliable: true, cost: true, points: "cast:survivor", who: "{survivor}, letter to {investigator}", text: "Letter of {survivor} to {investigator}, {year}: 'My mother's mother's mother was a girl of the wind-folk, carried out of the temple in a laundry basket by a stone soldier who could not finish the order. 212 died. She lived in a stone village and never moved the wind again, out of fear. I can move it. I have hidden it for 30 years. Write to me at {lead} and tell me what the scroll says.'" },
    { depth: "core", about: "truth:beast_teachers", source: "ruin", bias: "true", reliable: true, plain: true, who: "Ochre writing in the painted caves, copied by {investigator}", text: "Ochre painting in the painted caves, copied by {investigator} in {year}: a girl copying a burrow-bear's stance, and beneath it the oldest writing in the cave: 'She asked. He answered. That is all the art is. The bear taught us stone; the eel, tide; the drake, flame; the ox, wind. When the teachers are gone, the art goes with them.'" },
    { depth: "core", about: "truth:beast_teachers", source: "person", bias: "true", reliable: "partial", cost: true, points: "site:painted_caves", who: "{person}, stone-master, letter to the minister of forms", text: "Letter of {person}, stone-master of the hill school, to the minister of forms, {year}: 'The bears no longer come to the caves at {lead}. My 30 students learn the forms perfectly and move nothing but dust. I was the last of my school to train beside a bear. When I die, my school will be a dance class. Please send a bear, or tell me where one is.'" },
    { depth: "core", about: "truth:beast_teachers", source: "traveller", bias: "exaggerated", reliable: "partial", points: "sub:last_drakes", who: "A herbalist's travel journal, {place}", text: "Travel journal of a herbalist passing through {place}, {year}: 'The hunters at the inn showed me a sun-drake's horn as long as my arm, priced at 500 gold, and said there was one more pair in the old temple above {lead}. The flame-master travelling with me wept, and could not say why. That night the inn's fire would not light for anyone.'" },
    { depth: "core", about: "truth:beast_teachers", source: "oral", bias: "garbled", reliable: "partial", who: "A flame-folk cook of {place}, to a traveller", text: "A flame-folk cook of {place}, asked by a traveller why the kitchen would not serve lizard, {year}: 'Fire was danced to the first people by the sun-drakes. Lizards are their little cousins. We have not eaten one in 600 years, and I will not start for you. Have the goat.'" },
    { depth: "core", about: "truth:beast_teachers", source: "library", bias: "official", reliable: false, who: "{official}, preface to the Book of Flame", text: "From the preface to the Book of Flame, signed by {official}, minister of forms, {year}: 'The so-called teaching beasts are a children's allegory. The arts were developed by human masters through centuries of disciplined study, and are recorded complete in the 4 canonical books. The hunting of drakes is a matter for the game wardens.'" },
    { depth: "sub", about: "sub:flame_conquest", source: "library", bias: "propaganda", reliable: false, who: "Victory column of the flame-folk", text: "Inscription on the victory column in the flame-folk capital, {year}: 'Under the comet the flame-folk carried the light of order to every shore, and the conquered peoples gave thanks for it. Forty cities opened their gates in a single year.' Beneath it, a stone-folk visitor has scratched: 'Opened, or melted?'" },
    { depth: "sub", about: "sub:levellers", source: "heretic", bias: "exaggerated", reliable: "partial", who: "A masked Leveller, as reported by a constable", text: "Speech of a masked Leveller in the factory square of {place}, {year}, reported by a constable: 'Nine in ten are born ungifted. Nine in ten pay the taxes. One in ten sits on the council. Count again, and then count us.' The constable notes that 2,000 people cheered, and that no arrest was attempted." },
    { depth: "sub", about: "sub:blood_moon", source: "person", bias: "true", reliable: true, points: "sub:blood_moon", who: "A former tide-student, to the magistrate", text: "Statement of a former tide-student to the magistrate of {place}, {year}: 'My teacher could move the river. On the full moon, she could move me: my arms, my legs, the pace of my heart. I left that night and have not touched water since, 11 years now. She still lives in the coastal village at {lead}, and still takes students.'" },
    { depth: "sub", about: "sub:spirit_wilds", source: "oral", bias: "true", reliable: "partial", who: "A tram driver of {place}, to a city clerk", text: "Told by a tram driver of {place} to a city clerk, {year}: 'The vines came up through the tramlines in a single night, glowing green, and split three streets. In the morning spirits walked down the high street with faces like masks, as if they had never left. One bought an apple and paid with a feather. The stallholder kept it.'" },
    { depth: "sub", about: "sub:walled_calm", source: "traveller", bias: "true", reliable: "partial", who: "A foreign trader, letter from the ringed city", text: "Letter of a foreign trader from the ringed city of {place}, {year}: 'Nobody here says the word war. When I asked about the fighting 20 miles outside the walls, a guide took my arm and smiled, and I was at the gate by evening with my goods and a free meal. My partner asked the same question in the inner ring. I have not heard from my partner in a month.'" },
    { depth: "sub", about: "sub:last_wind_monk", source: "oral", bias: "garbled", reliable: "partial", points: "site:wind_temple", who: "A glacier herder, to {believer}", text: "Told by a glacier herder to {believer}, custodian, {year}: 'The boy from the ice asked for his people by name, one by one, 30 names. We had to tell him they had been gone a hundred years. He asked who did it. We said a fever. He looked at us the way you look at a liar, and asked for the road to {lead}.'" },
    { depth: "site", about: "site:comet_scar", source: "temple", bias: "pious", reliable: "partial", points: "site:comet_scar", who: "Flame-hymnal of {place}", text: "Flame-hymn sung at the black-glass lake at {lead}, from the temple hymnal of {place}, {year} edition: 'From the sky it came and to the sky it returns, and on that day the fire will remember its strength.' The hymnal's margin lists the comet's last two returns, 112 years apart, and the war fought in each." },
    { depth: "site", about: "site:twin_pools", source: "oral", bias: "true", reliable: "partial", who: "Tide-book of the twin-pool shrine", text: "Entry in the tide-book of the twin-pool shrine, {year}, by the shrine-keeper: 'The pale fish stopped circling at noon. The tide did not come in for three days, and 40 boats sat on the mud. On the fourth day it swam again, slower. Nobody in the village will say what the keeper before me did that night.'" },
  ],
};
