// The First Tongue: true names in the speech that made the world, and what the namers are not telling.
export default {
  id: "first_tongue",
  name: "The First Tongue",
  family: "power",
  pitch: "Everything has a true name in the language the world was made in, and whoever knows a thing's name can command it. The wise hide their own true names. The dragons still speak this language as their mother tongue.",
  slots: ["power-source", "cosmology", "power-access"],
  tone: ["mythic", "melancholy"],
  era: ["bronze", "medieval"],
  scale: "world",
  genres: ["fantasy", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "unremembering", w: 3 }, { id: "drowned_crown", w: 2 }, { id: "unquiet_gate", w: 1.5 }, { id: "elder_lattice", w: 1.5 }],

  power: {
    name: "naming", user: "namer", users: "namers",
    taught: "Every thing has a true name in the First Tongue, the speech the world was made in. Speak a thing's name rightly and it listens.",
    rules: ["You must know the exact name of the exact thing: the name of a wave will not still the sea.", "Names change as things grow; the name that bound the child will not bind the woman.", "No lie can be spoken in the First Tongue, and what is promised in it binds the speaker.", "Every change is paid for somewhere else; the world keeps its balance."],
    forbidden: "Calling up the dead, or binding a living soul by its name.",
  },

  cast: [
    { role: "investigator", n: "a lexicon-keeper of the namers' school who tests which names still answer", home: "inner", stance: "Wants an honest count of the names that still work, whatever the council says." },
    { role: "official", n: "a master of the namers' school with a seat on its council", home: "coast", stance: "Holds that the lexicon is complete, and that admitting otherwise would end the school." },
    { role: "believer", n: "a hearth-witch who keeps the village names in a charm-book", home: "forest", stance: "Believes the long names the grandmothers keep are the true ones, and the school's short names are failing." },
    { role: "survivor", n: "a client of the death-binders, who traded words of their own speech to hear a dead child", home: "border", stance: "Wants to know where the traded words went, and what the dead are kept for." },
  ],

  truths: [
    { id: "fading", n: "The names are being forgotten", d: "Every name that falls out of living memory weakens the thing it named. Grey, soundless places spread where the names are gone. The great library's own keepers burned it to hide how many were already lost, and the school still teaches from a lexicon in which most names no longer answer.", tags: ["truth:fading_names"],
      known: [
        "In the border hills crops, cloth and birds are turning grey, and bells are going quiet. The council of namers calls it a blight of the soil. The namers who walk the grey say the old names no longer answer.",
        "Hearth-witches find that the long names their grandmothers used still work while the school's short names fail. {believer}, a hearth-witch, keeps count of which names in the village still answer.",
        "The inventory of the burned library, made the year before the fire, marks most of its forty thousand names 'no longer answering'. The fire destroyed exactly the scrolls that had stopped working.",
        "Confirmed: forgotten names weaken the things they named. The library's keepers burned it to hide how many were gone, and the school has taught from a dying lexicon ever since. The grey follows the forgetting.",
      ] },
    { id: "stolen", n: "The tongue was stolen", d: "The First Tongue belongs to the dragons. The first people traded wings and long life for hands, houses and graves, signed for the speech, then broke the deal and carried it away without paying the rest. The dragons have never stopped wanting it back, and they fly closer to the treaty line every year.", tags: ["truth:stolen_tongue"],
      known: [
        "Sailors who have heard a dragon speak say they understood every word without learning any. The school teaches that dragons only parrot words our ancestors taught them, and that students should never answer one.",
        "The hymn of the first people says they came down from the high air and chose hands over wings. The dragon-born girl of the coast writes that the people took the tongue, and have feared its owners ever since.",
        "The verse cut into the dragon skeleton on the sea cliff reads two ways: as a lament and as a contract with a date of payment. Human tools older than any human town lie in its skull.",
        "Confirmed: the tongue was stolen. The first people bought it from the dragons with their wings and long lives, then broke the bargain and never paid the rest. The dragons have started to collect.",
      ] },
    { id: "dry_wall", n: "The wall of the dead is a spell", d: "Ancient namers tried to name death away and made instead a dry grey country where the dead are kept, loveless and thirsty. The working has never stopped. It feeds on every word spoken in the First Tongue, which is why the art grows weaker each age, and the council of namers calls the loss 'the tithe'.", tags: ["truth:dry_wall"],
      known: [
        "Families leave cups of water on graves and cannot say why. Death-binders sell the words of the dead and take payment in words from the client's own speech; {survivor} paid one and still cannot say the word for sweet.",
        "On a hill where it is always evening, a wall of low stones is cut with the names of the dead. Travellers hear voices on the far side asking, politely, for water.",
        "Under the low wall runs a second wall, carrying a binding written as one sentence that has never been finished. New words are still being added to it, and the namers' marks on it are older than the school.",
        "Confirmed: the wall of the dead is a spell. Ancient namers spoke it to end death and made a dry country instead. It is still being spoken, and every word of the First Tongue feeds it.",
      ] },
  ],

  tags: ["true_names"],

  subthemes: [
    { id: "loosed_shadow", n: "The Shadow Loosed by Pride", d: "A prodigy of the namers' school called up the dead to win an argument. A shadow with no name came through instead, and it is hunting him from island to island.", w: 1.2, mods: [["scholarly", 1.5], ["academies", 2], ["arcane", 1.5]], tags: ["theme:loosed_shadow"] },
    { id: "name_wardens", n: "The Name-Wardens", d: "A hereditary order keeps the ruler's true name. Each warden carries it to the grave, and a warden who flees the court is hunted like a plague.", w: 1.2, req: { any: ["monarchy", "autocracy", "dynastic"] }, tags: ["theme:name_wardens"] },
    { id: "hearth_namers", n: "The Hearth-Witches", d: "The school calls village charm-craft weak magic. The grandmothers who practise it quietly hold more living names than the whole school, and they are tired of being polite about it.", w: 1.2, mods: [["egalitarian", 2], ["forest_folk", 1.5], ["faith:spirits", 1.5], ["hierarchical", 0.6]], truthLink: "fading", tags: ["theme:hearth_namers"] },
    { id: "name_market", n: "The Name Market", d: "In a certain harbour no one gives a true name. Thieves trade stolen names like keys, and the richest house in town deals in nothing else.", w: 1, req: { any: ["has:port", "mercantile"] }, tags: ["theme:name_market"] },
    { id: "dragon_peace", n: "The Peace of Wings", d: "An old treaty split the sea between dragons and people. The dragons are flying closer to the line each year, and nobody living can read the treaty's terms.", w: 1, req: { any: ["coastal", "island"] }, mods: [["near:beasts", 2]], truthLink: "stolen", tags: ["theme:dragon_peace"], mark: { kind: "zone", n: "Dragon reaches", color: "#8a5a3a", size: [2, 4], where: "remote" } },
    { id: "grey_creep", n: "The Grey Creep", d: "In the border hills, crops, cloth and birds are turning grey, and bells and voices are going quiet. The namers walk the grey with their lexicons and find that the old names no longer answer.", w: 0.9, truthLink: "fading", tags: ["theme:grey_creep"], mark: { kind: "zone", n: "The Grey", color: "#9c9c9c", size: [1, 3], where: "border" } },
    { id: "nameless_tombs", n: "The Tombs of the Nameless", d: "In a desert labyrinth a child-priestess, chosen at birth, serves powers older than names. She has begun to ask what they are.", w: 0.9, req: { any: ["desert", "hot", "badlands"] }, mods: [["pious", 1.5]], tags: ["theme:nameless_tombs"] },
    { id: "undying_mage", n: "The Undying Archmage", d: "The art is weakening across the realm, spell by spell, while one archmage grows no older. Students whisper that he is draining the art to keep himself alive.", w: 0.8, req: { any: ["arcane_council", "gov:magocracy", "arcane", "scholarly"] }, truthLink: "dry_wall", tags: ["theme:undying_mage"] },
    { id: "death_binders", n: "The Death-Binders", d: "Outlawed summoners trade with the dry country for the words of the dead. Clients pay with words from their own speech, and go home unable to say them ever again.", w: 0.9, mods: [["faith:ancestors", 2], ["faith:void", 2.5], ["sacrifice", 1.5]], truthLink: "dry_wall", tags: ["theme:death_binders"] },
    { id: "island_dialects", n: "The Island Dialects", d: "Each island speaks a broken dialect of the First Tongue, partial namings that only work at home. The fire-name of one isle is a curse on the next.", w: 1, req: { any: ["island", "coastal"] }, mods: [["island", 3], ["insular", 1.5]], tags: ["theme:island_dialects"] },
    { id: "dragon_born", n: "The Dragon-Born Girl", d: "A girl of the coast turns into a dragon on certain nights. Both the school and the dragons want her, and neither will say why.", w: 0.5, mods: [["near:beasts", 2], ["coastal", 1.5]], truthLink: "stolen", tags: ["theme:dragon_born"] },
  ],

  sites: [
    { id: "death_wall", n: "The Low Wall of $", kind: "anomaly", where: "remote", truthLink: "dry_wall", d: "A line of knee-high stones on a hill where the light is always evening. Nothing living will step over it.",
      layers: {
        surface: { n: "Always evening", text: "A line of knee-high stones runs along a hilltop where it is always dusk, whatever the hour in the valley. No animal will step over the stones. A dog dragged across in {year} died the same night, and the shepherds now drive their flocks the long way round." },
        study: { n: "Names of the dead", text: "Every stone is cut with a single name in the First Tongue. {investigator} matched 40 of them to burial registers: all belong to people who have died, some only last year. Names have appeared on stones that were blank the season before." },
        dig: { n: "The unfinished sentence", points: "cast:survivor", text: "Under the wall runs a second wall, and along it a binding written as one sentence that has never been finished. New words are still being added. One of the newest is the word for sweet, traded away by a death-binder's client who lives in {lead}." },
        revelation: { n: "Spoken into being", text: "Namers of the first school spoke this wall into being to stop dying, and made a dry country where the dead are kept instead. It is still being spoken: every word of the First Tongue, from any namer, adds to it. The council of namers has known for 300 years, and calls it 'the tithe'." },
      } },
    { id: "lettered_maze", n: "The Lettered Maze of $", kind: "ruin", where: "desert", truthLink: "fading", d: "A temple half-buried in sand whose corridors are carved floor to ceiling with tiny script.",
      layers: {
        surface: { n: "Tiny writing", text: "Sand-choked corridors run under a half-buried temple, every wall covered in writing too small to read by torchlight. Caravans shelter here in sandstorms. The guides claim nine miles of corridor, and charge by the mile." },
        study: { n: "Ordered by fear", text: "The writing is a lexicon of the First Tongue, ordered not by sound but by what each thing fears. {investigator} copied 2,000 entries in one season. Salt is listed beside rain. Fire is listed beside its own name." },
        dig: { n: "The dropped chisel", points: "site:ash_library", text: "The deepest corridors are bare. The carving stops halfway through a word, and the chisel lies where it fell. A tag on the chisel's handle names the carver's employer: the great library at {lead}." },
        revelation: { n: "A race lost", text: "The library's keepers sent carvers out to cut every name into stone before it was forgotten. The carvers lost. The things that should be named on the blank walls have faded half out of the world: dim, quiet and hard to find. The keepers burned their library that same year and blamed a lamp." },
      } },
    { id: "rib_poem", n: "The Rib-Poem of $", kind: "dig", where: "coast", truthLink: "stolen", d: "A dragon skeleton on a sea cliff whose every bone is inscribed with verse.",
      layers: {
        surface: { n: "Ribs on the cliff", text: "Ribs like a ship's frame stand on a cliff top, white and scored with lines, 80 feet from skull to tail. Fishermen tie their boats' names to the ribs for luck. Dragons fly over it once a year and do not land." },
        study: { n: "Two readings", text: "Each line of the verse means two things at once. {investigator} translated it both ways in {year}. Read one way it is a lament. Read the other it is a contract, with a price and a date of payment." },
        dig: { n: "Tools in the skull", points: "sub:dragon_peace", text: "In the skull lies a cache of human tools older than any human town: a knife, a spindle, a door-key. The contract's last clause sets the same sea line the Peace of Wings follows. The only copy of that treaty is held at {lead}." },
        revelation: { n: "The bill of sale", text: "The verse is a bill of sale. The first people gave up wings and long lives for the dragons' language, and left the knife, the spindle and the key as a deposit. They signed, then broke the deal and never paid the rest. The date of payment in the contract fell last century." },
      } },
    { id: "drifting_isle", n: "The Unmoored Isle of $", kind: "anomaly", where: "coast", d: "An island marked on every chart and rarely where the chart puts it.",
      layers: {
        surface: { n: "Seen and gone", text: "A green island is seen from the deck one week and gone the next. Every chart marks it, and no two put it in the same place. The admiralty pays five silver to any captain who lands on it and comes back." },
        study: { n: "Eleven spellings", text: "Its name is spelled eleven ways in eleven charts. {investigator} laid the charts out in order of date. Each time the spelling changed, the island moved, and it moved the way the new spelling sounded." },
        dig: { n: "The staff in the rock", points: "library", text: "On its shore a namer's staff is driven into the rock like a tent peg, the grip worn smooth, with no owner anywhere on the island. The school's register of lost staffs, held in {lead}, lists one taken out by a master who never came back." },
        revelation: { n: "The place that cannot be found", text: "A master of the school named the island 'the place that cannot be found', to hide a copy of the old lexicon from the council, then died with the name unspoken. The island has obeyed ever since. The council struck the master from the register, and the island from the charts." },
      } },
    { id: "ash_library", n: "The Burned Library of $", kind: "ruin", where: "inner", truthLink: "fading", d: "A gutted library whose ash, centuries old, has never blown away.",
      layers: {
        surface: { n: "Ash that stays", text: "Black walls stand around a floor of ash that the wind will not move. The ash is ankle-deep and centuries old. Families of {place} bring their children to blow on it and watch it stay still." },
        study: { n: "Whispering ash", text: "Held close to the ear, a pinch of the ash whispers a single word. {believer}, a hearth-witch, listened to 100 pinches in {year}. The witch knew seven of the words from the charm-book, and none from the school's lexicon." },
        dig: { n: "The inventory", points: "archive", text: "In the cellar is an inventory of the scrolls made before the fire: forty thousand names, most marked in red as 'no longer answering', signed by the keepers' council. A second copy was sent to the school archive at {lead}." },
        revelation: { n: "The fire was the cover", text: "The keepers burned their own library to hide how many names were already lost. They saved the 206 scrolls that still answered and called the rest a tragedy. The fire was the cover, not the crime. The school rebuilt its lexicon from the 206, and it grows shorter every year." },
      } },
  ],

  beings: [
    { id: "tongue_dragon", n: "Old-tongue dragon", kind: "beast", d: "A vast, speaking dragon that uses the First Tongue as its mother speech. It cannot lie, but it can tell the exact truth in the most hurtful way.", danger: 3, biomes: ["peaks", "alpine", "coast", "badlands"], look: { size: 14, group: [1, 1], move: "solo", speed: 60, col: "#7a3a2a", col2: "#d0a040", body: "reptile", active: "day", visible: true } },
    { id: "nameless_shade", n: "Nameless shade", kind: "predator", d: "A shadow with no name, loosed by a careless summoning. It cannot be bound, because there is nothing to call it.", danger: 2, biomes: ["badlands", "colddesert", "tundra", "swamp", "boreal"], look: { size: 1.8, group: [1, 1], move: "solo", speed: 8, col: "#24242c", col2: "#56566a", body: "biped", active: "night", visible: false } },
    { id: "hollow_heron", n: "Hollow heron", kind: "bird", d: "A heron that has lost its name: colourless, soundless, and slowly forgetting how to fish.", danger: 0, biomes: ["river", "swamp", "coast"], look: { size: 1, group: [1, 6], move: "flock", speed: 30, col: "#b4b4b4", col2: "#dadada", body: "bird", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "ft_name_songs", n: "Name-songs", field: "writing", level: 1, d: "Shamans keep the true names of the herd, the river and the weather in long songs passed from mouth to mouth." },
    { id: "ft_lexicon", n: "The written lexicon", field: "writing", level: 2, d: "True names written down and taught in schools. What is written can be learned by anyone, and stolen by anyone." },
    { id: "ft_weather_naming", n: "Weather-naming", field: "navigation", level: 3, d: "Ship-namers call a wind by its name and set it in the sails, and the fleets stop waiting on the weather." },
    { id: "ft_name_stones", n: "Name-stones", field: "arcana", level: 3, d: "Stones that speak a thing's true name aloud when it is pressed against them. Courts use them; so do thieves." },
    { id: "ft_pattern_arts", n: "The pattern-arts", field: "arcana", level: 4, d: "Great workings that name a storm, a tide or a plague and turn it aside, paid for by a drought or a flood somewhere else." },
    { id: "ft_grammar", n: "The grammar of making", field: "natural_philosophy", level: 5, d: "A study of how names themselves are made, and therefore of how a new one might be spoken." },
  ],

  units: [
    { id: "ft_wind_namers", n: "Wind-namers", role: "magic", wpn: "staff", kit: "robe", ranks: 2, gap: 3, size: 20, w: 1, mods: [["theme:island_dialects", 3], ["seafaring", 2], ["arcane", 2]] },
    { id: "ft_warden_guard", n: "Name-warden guard", role: "infantry", wpn: "sword", kit: "plate", ranks: 4, gap: 1.2, size: 80, w: 0.5, mods: [["theme:name_wardens", 8]] },
  ],

  govs: [
    { id: "ft_namers_council", n: "Council of Namers", d: "The masters of the namers' school rule, because nobody else can be sure their own name is safe.", tags: ["gov:ft_namers_council", "arcane_rule"], w: 0.5, forms: ["Isle of $", "Wise Council of $", "Namers' Seat of $"], ruler: "Archnamer", mods: [["arcane", 3], ["island", 2], ["scholarly", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "The Grey", color: "#a0a0a0", size: [1, 3], count: [0, 2], where: "border", d: "Lands where colour has faded from everything and no bird sings." },
  ],

  storylines: [
    { id: "ft_shadow", n: "The Shadow of {place}", scale: "local", anchor: "town", w: 1.5, req: "true_names",
      stages: {
        start: { h: "A student of {place} breaks the namers' law", b: "{person}, the quickest pupil the namers have seen in a generation, tried to call a dead hero to win an argument. A shadow came through instead, and it had no name.", wait: [2, 5], next: [{ to: "hunted", w: 2 }, { to: "masters_seal", w: 1, mods: [["scholarly", 2], ["academies", 2]] }] },
        masters_seal: { h: "The masters of {place} close the breach", b: "The old namers worked through the night. The breach is shut and {person} is scarred across the face, but the shadow is loose in the world now.", wait: [2, 6], next: [{ to: "hunted", w: 1 }, { to: "faded", w: 1 }] },
        hunted: { h: "A nameless shadow hunts {person}", b: "The shadow loosed in {place} follows {person} from town to town. Where it passes, dogs fall silent and lamps gutter.", wait: [3, 8], fx: { unrest: 6 }, next: [{ to: "turns_hunt", w: 1 }, { to: "consumed", w: 1, mods: [["chance:low", 2]] }] },
        turns_hunt: { h: "{person} turns to hunt the shadow", b: "Instead of running, {person} has sailed after the shadow towards the edge of the charts, with {person2}, a hearth-witch, at the tiller.", wait: [6, 14], next: [{ to: "named", w: 1 }, { to: "lost_at_sea", w: 1 }] },
        named: { h: "The shadow of {place} is named at last", b: "At the world's edge {person} spoke the shadow's name, and it was {person}'s own. The two became one, and {person} came home quieter and stronger.", fx: { stability: 4, prestige: 6, discovery: "arcana" }, end: true },
        consumed: { h: "{person} is found without a shadow", b: "{person} was found on the road out of {place}, alive and smiling, answering to no name at all.", fx: { unrest: 8 }, end: true },
        lost_at_sea: { h: "No word of the boat from {place}", b: "The little boat that sailed after the shadow has not come back. On the quay, {person2}'s sister still leaves a lamp lit.", end: true },
        faded: { h: "The shadow of {place} passes into rumour", b: "Months pass with no sign of the shadow. {person} keeps a lamp burning every night all the same.", fx: { stability: 2 }, end: true },
      } },
    { id: "ft_kings_name", n: "The True Name of {ruler}", scale: "realm", anchor: "realm", w: 1.2, req: ["true_names", { any: ["monarchy", "autocracy", "dynastic"] }],
      stages: {
        start: { h: "The true name of {ruler} is stolen", b: "A name-warden of {realm} has fled the court with a sealed tablet. Whoever reads it can command {ruler} like a hound.", wait: [2, 6], fx: { stability: -4 }, next: [{ to: "ransom", w: 2 }, { to: "hunt", w: 1, mods: [["spy_network", 3]] }] },
        hunt: { h: "The court's hounds ride after the warden", b: "{person}, master of the court's spies, rides out of {capital} with orders to burn the tablet and anyone who has read it.", wait: [2, 5], next: [{ to: "recovered", w: 2 }, { to: "ransom", w: 1 }] },
        ransom: { h: "A price is named for the name of {ruler}", b: "Letters reach {capital}: the name will be sold abroad unless {realm} pays in gold and in pardons.", wait: [2, 5], fx: { stability: -6 }, next: [{ to: "paid", w: 1, mods: [["rich", 2]] }, { to: "sold", w: 1, req: "has:rival" }, { to: "renamed", w: 1, mods: [["arcane", 2], ["arcane_council", 2]] }] },
        recovered: { h: "The warden is taken and the tablet burned", b: "The tablet was found sewn into a saddle. {person} burned it unread, and the warden was given to the river.", fx: { stability: 4 }, end: true },
        paid: { h: "{realm} buys back the name of its ruler", b: "The ransom was paid in a back room in {capital}. Nobody believes the thieves kept no copy.", fx: { treasury: -80, stability: -2 }, end: true },
        sold: { h: "{rival} holds the name of {ruler}", b: "The tablet crossed the border. {ruler} now flinches at the sound of foreign voices, and the court of {realm} knows its master has a master.", fx: { stability: -15, prestige: -10, relation: { rival: -30 } }, end: true },
        renamed: { h: "{ruler} is named anew", b: "The namers of {realm} worked their riskiest rite and gave the ruler a new true name. {ruler} woke a stranger to old friends, but no stolen tablet can bind them now.", fx: { stability: -3, prestige: 5, ruler_trait: "paranoid" }, end: true },
      } },
    { id: "ft_greying", n: "The Greying of {place}", scale: "local", anchor: "town", w: 1, req: "true_names",
      stages: {
        start: { h: "Colour drains from {place}", b: "The wheat of {place} came up grey and the bells there have lost their ring. The elders cannot remember what the river used to be called.", wait: [3, 8], fx: { unrest: 5 }, next: [{ to: "namers_come", w: 2 }, { to: "spreads", w: 1 }] },
        namers_come: { h: "Namers come to read the grey at {place}", b: "{investigator} of the school walks the grey fields with a lexicon, trying names that no longer answer.", wait: [3, 8], next: [{ to: "restored", w: 1, mods: [["theme:hearth_namers", 3], ["egalitarian", 1.5]] }, { to: "spreads", w: 1 }, { to: "bad_count", w: 1, mods: [["learned", 1.5]] }] },
        spreads: { h: "The grey spreads beyond {place}", b: "Three more villages have faded. Folk who leave {place} forget their own names within a month.", wait: [4, 10], fx: { pop: 0.9, unrest: 12 }, next: [{ to: "abandoned", w: 2 }, { to: "restored", w: 0.5 }] },
        restored: { h: "A grandmother restores the names of {place}", b: "It was not the school but {believer}, an old hearth-witch with a charm-book, who remembered the river's name. The colour came back with it.", fx: { stability: 6, discovery: "writing" }, end: true },
        abandoned: { h: "{place} is left to the grey", b: "The last families have gone. {place} stands silent and colourless, and the maps have stopped naming it.", fx: { abandon_town: true, unrest: 10 }, end: true },
        bad_count: { h: "{investigator} returns with a terrible count", b: "The namer came home and burned the lexicon. 'Half the words in it no longer answer,' the namer told the school. 'We have been teaching the names of ghosts.'", fx: { science: { writing: 0.5 }, unrest: 6 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "The school's first lexicon, foreword", text: "Foreword to the school's first lexicon, by the founding masters, copied in {year}: 'Every thing has a true name in the First Tongue, the speech the world was made in. Learn the name of the sea and you know nothing. Learn the name of this wave and you may still it. Ours is the art of the particular. A student who knows 300 names well is worth ten who know 3,000 badly.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: true, who: "A ferryman of {place}, to his passengers", text: "Told by a ferryman of {place} to any passenger who asks his name, {year}: 'Never tell your name to a stranger, a crow or a king. Give them your use-name and keep the true one under your tongue. My use-name is Ferry. I have had it 40 years, and nobody has ever commanded me to do anything but row.'" },
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", points: "library", who: "{official}, Rules of Prudence", text: "From the Rules of Prudence by {official}, master of the school, {year}: 'Every change is paid for somewhere else. Rain called here is drought somewhere else; a storm turned from one harbour lands on the next. The prudent namer does as little as possible, and does it well. Last year 3 masters were fined for calling rain without a licence.' The full rules are chained in the library at {lead}." },
    { depth: "core", about: "truth:fading", source: "ruin", bias: "true", reliable: true, cost: true, who: "{person}, carver, below the last word in the maze", text: "Scratched below the last carved word in the maze, signed {person}, carver for the great library, {year}: 'The names go faster than I can cut them. I wrote salt yesterday, and today I cannot taste it. I wrote my sister's name last week, and I cannot remember her face. Four of us came; I am the last. I am going home, if I can still name the road.'" },
    { depth: "core", about: "truth:fading", source: "archive", bias: "redacted", reliable: "partial", points: "site:ash_library", who: "Library inventory, copy found by {investigator}", text: "Inventory of the great library, made the year before the fire; a copy found by {investigator} in the school archive: '...scrolls of the rivers, nine hundred; marked as answering, thirty-one; the remainder to be...' The page is cut off. The original was kept in the library cellar at {lead}." },
    { depth: "core", about: "truth:fading", source: "person", bias: "true", reliable: "partial", who: "{believer}, hearth-witch, charm-book margin", text: "In the margin of the charm-book of {believer}, hearth-witch, beside the entry for feverwort, {year}: 'Grandmother called this herb by a long name, eleven syllables. The school calls it by a short one, three. I tried both on the miller's fever. Only Grandmother's works. Asked the school's master why. Was told I had the accent wrong.'" },
    { depth: "core", about: "truth:fading", source: "library", bias: "official", reliable: false, who: "Circular of the council of namers, signed by {official}", text: "Circular of the council of namers, signed by {official}, {year}: 'The Grey is a blight of the soil, well known to farmers, and has nothing to do with the art. The lexicon is complete, and all of its 4,000 names answer. Namers who report otherwise are to be retested on their pronunciation.'" },
    { depth: "core", about: "truth:fading", source: "person", bias: "true", reliable: true, plain: true, points: "site:lettered_maze", who: "A former keeper of the great library, to {investigator}", text: "Confession of a former keeper of the great library, aged 90, to {investigator}, {year}: 'I was an apprentice the night we burned it. The masters told us most of the names no longer answered, and every name forgotten takes part of its thing out of the world. If people learned how many were gone, the school was finished. We saved 206 scrolls and lit the rest. The carvers sent to {lead} never finished either. I carried the lamp.'" },
    { depth: "core", about: "truth:stolen", source: "ruin", bias: "true", reliable: true, points: "site:rib_poem", who: "Claw-cut line on a dragon rib, translated by {investigator}", text: "Cut into a rib of the skeleton at {lead}, translated by {investigator} in {year}: 'We gave you the word for give. You have never once used it back.' The cut is about 500 years newer than the other verses on the bones, and was made with a claw, not a chisel. Fishermen report that a dragon lands on the cliff once a year, alone, at night." },
    { depth: "core", about: "truth:stolen", source: "temple", bias: "pious", reliable: "partial", who: "Spring hymn of the first people, {place}", text: "Hymn of the first people, sung at the {faith} temple of {place} on the first day of spring, from the {year} hymnal: 'We came down out of the high air and chose the hand over the wing, the house over the sky, the grave over the long years.' The choir-master notes that two lines after these are always skipped by custom, and nobody remembers them." },
    { depth: "core", about: "truth:stolen", source: "heretic", bias: "heretic", reliable: true, plain: true, who: "The dragon-born girl, letter to the council of namers", text: "Letter from the dragon-born girl of the coast to the council of namers, {year}, delivered by a gull: 'You did not learn the tongue. Your ancestors bought it from my mother's people with their wings and their long lives, then ran without paying the rest. You took it, the way you take everything, and you have been afraid of its owners ever since. They have not forgotten the price.'" },
    { depth: "core", about: "truth:stolen", source: "library", bias: "official", reliable: false, who: "School Bestiary, approved by {official}", text: "From the school's Bestiary, approved by {official}, {year}: 'Dragons are beasts with a gift for mimicry. Their so-called speech is a parroting of words our ancestors taught them in the age of taming, as a starling learns 20 words from a farmer. Students should not answer a dragon that speaks to them.'" },
    { depth: "core", about: "truth:stolen", source: "person", bias: "true", reliable: true, cost: true, who: "The harbour-master of {place}, report", text: "Report of the harbour-master of {place}, {year}: 'The fishing boat of {person} crossed the treaty line by two miles, chasing herring. A dragon came down and said one word to {person} in the First Tongue. {person} has not spoken since, in any language, and cannot write either. The crew say the dragon told them it was collecting on account.'" },
    { depth: "core", about: "truth:dry_wall", source: "ruin", bias: "true", reliable: true, plain: true, who: "A first-school namer, on a stone of the low wall", text: "Cut on a stone of the low wall beside a namer's mark of the first school, read by {investigator} in {year}: 'Here we ended death. Here we ended rain, and love, and the sea, for those beyond. We spoke the wall to keep the dead from going on; we did not know they would stay thirsty. Every word of the tongue spoken after us adds a stone.'" },
    { depth: "core", about: "truth:dry_wall", source: "person", bias: "true", reliable: "partial", cost: true, points: "cast:survivor", who: "A death-binder's ledger, seized by the watch", text: "Ledger of a death-binder of {place}, {year}, seized by the watch: 'Client: {survivor}, of {lead}. Called up the shade of the client's daughter, aged 6. The shade would not speak, and only asked for water. Paid: the word for sweet, for one year.' The year is long past. {survivor} still cannot say the word." },
    { depth: "core", about: "truth:dry_wall", source: "heretic", bias: "exaggerated", reliable: "partial", points: "sub:undying_mage", who: "A death-binder on trial at {place}", text: "Speech of a death-binder on trial at {place}, {year}: 'Every word you speak in the First Tongue is a cup of water poured over the wall. The dead drink it. That is why the art grows weaker every age. Ask why the Archmage at {lead} grows no older while no student has passed the trial in 100 years. He drinks from the same cup.'" },
    { depth: "core", about: "truth:dry_wall", source: "oral", bias: "garbled", reliable: "partial", who: "A gravedigger of {place}, to {investigator}", text: "Told by a gravedigger of {place} to {investigator}, {year}: 'We leave cups of water on the graves, two a week, and empty the old ones. The dead go to a dry country, my father said, and his father said it before him. Nobody knows what good the water does. The cups are always dry by morning, even when it rains.'" },
    { depth: "core", about: "truth:dry_wall", source: "temple", bias: "official", reliable: false, who: "Funeral rite of the {faith}, revised edition", text: "Funeral rite of the {faith}, as revised by the high temple, {year}: 'The dead pass whole and rejoicing into the light of {deity}. Tales of a dry country are invented by death-binders, who profit by fear. The faithful need leave no water on graves; the 3 coppers saved each month should go to the temple instead.'" },
    { depth: "sub", about: "sub:loosed_shadow", source: "oral", bias: "true", reliable: "partial", points: "sub:loosed_shadow", who: "An innkeeper of an outer isle, to a namer", text: "Told by the innkeeper of an outer isle to a namer of the school, {year}: 'The young master who called the shadow came through here last spring. Scar across the face, four lines. Would not walk anywhere with the sun behind, so the shadow fell in front where it could be watched. Paid in silver, asked for the next boat to {lead}, and slept on deck.'" },
    { depth: "sub", about: "sub:name_wardens", source: "archive", bias: "redacted", reliable: true, who: "Warden-roll of the court of {realm}", text: "The oath of the name-wardens, as sworn at the court of {realm}, from the warden-roll, {year}: 'I will carry the name to my grave, and if I am taken, I will carry it there a little sooner.' The roll lists 31 wardens since the founding. Nine of the entries end with the word 'sooner'." },
    { depth: "sub", about: "sub:name_market", source: "traveller", bias: "exaggerated", reliable: "partial", points: "sub:name_market", who: "A wool trader, letter from the harbour", text: "Letter of a wool trader from the harbour at {lead}, {year}: 'Every soul here goes by a dockside name; mine is Grey Coat. A true name sells for more than a ship, 400 gold for a merchant's, and the buyer never says what it is for. The richest house in town deals in nothing else. I have kept my mouth shut for a month.'" },
    { depth: "sub", about: "sub:dragon_peace", source: "library", bias: "propaganda", reliable: false, who: "Admiralty History of the Peace of Wings", text: "From the Admiralty's History of the Peace of Wings, {year} edition: 'The Peace of Wings was won by the courage of our admirals, and the dragons have kept to their reaches ever since out of fear of our fleets. The treaty line lies 40 miles offshore.' A reader has noted in the margin that the dragons now fly at 30." },
    { depth: "sub", about: "sub:undying_mage", source: "heretic", bias: "heretic", reliable: "partial", who: "Pamphlet in the students' hall", text: "Pamphlet left in the students' hall of the namers' school, {year}: 'The Archmage of {realm} has not aged in 100 years. In the same 100 years, no new namer has passed the trial of the staff, and the spells in the lexicon work a little less each spring. Do the arithmetic, and then do it again in the First Tongue, where it cannot lie.'" },
    { depth: "sub", about: "sub:island_dialects", source: "traveller", bias: "garbled", reliable: "partial", points: "sub:island_dialects", who: "A ship-namer's journal, eastern isles", text: "Journal of a ship-namer of the school in the eastern isles of {lead}, {year}: 'Here they call fire by a word that only lights wet wood. I lit our galley stove with our fire-word and the islanders ran. They think our fire-word is a curse. Their harbour burned two years ago, the week a school ship called, and maybe it is.'" },
    { depth: "sub", about: "sub:hearth_namers", source: "person", bias: "true", reliable: true, who: "{believer}, hearth-witch, to a master of the school", text: "Said by {believer}, hearth-witch, to a master of the school who came to {place} in {year}, as the master wrote it down: 'You came here to teach us the name of the well. The well has been answering to me for forty years. Say yours to it, and see if it answers you.' The master did. The bucket came up empty." },
    { depth: "site", about: "site:death_wall", source: "traveller", bias: "true", reliable: "partial", points: "site:death_wall", who: "A salt-carrier's day-book", text: "Day-book of a salt-carrier on the hill road, {year}: 'I crossed the hill at {lead} at evening, though the sun had stood at noon over the ford an hour before. On the far side of the low wall someone was asking for water, very politely, in my mother's voice. My mother has been dead nine years. I left my water-skin on the stones and did not look back.'" },
    { depth: "site", about: "site:drifting_isle", source: "archive", bias: "official", reliable: "partial", points: "site:drifting_isle", who: "Admiralty chart office, order", text: "Order of the Admiralty chart office, {year}: 'The isle known as {lead} is struck from the charts. It is to be struck from the charts again next year, wherever it is. Captains who land on it are to report the spelling of its name as given by any inhabitants. Reward: 5 silver. No captain has yet claimed it.'" },
  ],
};
