// The Grudgewell: power pooled from human dread, the curses it breeds, and the sorcerers who fight poison with poison.
export default {
  id: "grudgewell",
  name: "The Grudgewell",
  family: "power",
  pitch: "Fear, hatred and grief leak from every person and collect into living curses. Sorcerers fight curses with the same dark feelings, and the best can turn the space around them into a pocket world shaped by their own mind.",
  slots: ["power-source", "monster-source", "bloodline"],
  tone: ["grim", "horror"],
  era: ["medieval", "renaissance", "industrial", "modern"],
  scale: "regional",
  genres: ["fantasy", "shonen", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "thinning", w: 2 }, { id: "ward_walls", w: 2 }, { id: "unquiet_gate", w: 1.5 }, { id: "unremembering", w: 2 }, { id: "sleeper", w: 1.2 }],

  power: {
    name: "grudgecraft", user: "grudge-sorcerer", users: "grudge-sorcerers",
    taught: "Every person leaks a little dread, spite and grief, the way a body leaks heat. It pools in dark places and, given time, wakes as a curse. A sorcerer is someone who holds the leak inside and refines it into a weapon instead.",
    rules: ["Ordinary people cannot see curses, only suffer them.", "Each sorcerer is born with one inborn working, often their family's.", "The greatest can spread their inner world around them as a sealed ground where their working cannot miss.", "Turning the dread back into healing is possible, and very rare."],
    forbidden: "Eating curses, sealing with human lives, or binding a curse into an unborn child.",
  },

  cast: [
    { role: "investigator", n: "a grader of the schools' curse register, sent out to measure pools", home: "inner", stance: "Counts everything and believes the numbers will shame the masters into honesty." },
    { role: "official", n: "a warden of the capital's ward-posts, sworn to the three houses", home: "capital", stance: "Keeps the succession roll and believes one life a generation is a fair price for a city." },
    { role: "believer", n: "a night nurse at the House of Grief who has joined the fear-cult", home: "remote", stance: "Thinks curses are people's grief made solid, to be soothed and fed, never killed." },
    { role: "survivor", n: "the giftless younger child of a great house, whose sister was taken for the ward", home: "capital", stance: "Wants to know where the sister went, and will burn the roll to find out." },
  ],

  truths: [
    { id: "barrier_man", n: "The ward is a man", d: "A sorcerer called the Keeper has lived under the capital for a thousand years, holding up its ward against curses with his own body. Each generation the three houses give him a gifted young successor, who is merged into him; the posts carry 41 names. He is slowly turning into a monster, and each successor now lasts half as long as the last.", tags: ["truth:barrier_man"],
      known: [
        "The stone posts around the capital carry 41 names, one a generation, and lately they sweat black water. The official guide says the ward needs no keeper. No mason in the city has ever been paid to carve a name.",
        "The three houses keep a succession roll. Each generation a gifted young sorcerer is 'presented to the Keeper' on the longest night, and the family is paid as for a death in service. The names on the roll match the names on the posts.",
        "Someone lives under the central post. A successor scratched a message on the warm door below: they were pressed into an old sorcerer who holds the ward up, and they are one voice among many inside him.",
        "Confirmed: the Keeper, a thousand-year-old sorcerer, holds the capital's ward with his body, and the houses feed him a successor each generation. He is turning into a curse, and the successors are being used up faster every century.",
      ] },
    { id: "fear_gods", n: "Shared fear makes gods", d: "The strongest curses are born from the fear a whole people shares of one thing: a colour, the dark, an animal, the sea. When a school kills such a curse, the thing goes with it, out of the world and out of every memory. The schools have done this for pay many times and entered each as a clean kill; the language has holes where those fears were killed.", tags: ["truth:fear_gods"],
      known: [
        "Some towns and trades have blanks in their words: a hymn line that does not scan, a colour nobody can name, a hunter's bounty book with the animal scraped out. The schools call it folk confusion.",
        "Each blank follows the slaying of a great curse nearby. The fear-cult teaches that great curses are made of what a whole people fears, and that killing one kills a part of their minds.",
        "A great curse was killed under the grey town's dye-works in the same year the town lost a colour. The school's register calls it a clean kill and records the fee.",
        "Confirmed: a curse made of a people's shared fear carries the feared thing in it. Kill the curse and the thing leaves the world and every memory. The schools have done it many times, and were paid each time.",
      ] },
    { id: "sorcerers_source", n: "The sorcerers are the source", d: "Curses breed thickest where sorcerers gather, because the refined dread that sorcerers carry seeds the pools around them. The schools that protect people are farming the problem: near one school the pools are nine times the provincial mean. The eldest of the three houses has known for a century and kept the figures out of every yearly report.", tags: ["truth:sorcerers_source"],
      known: [
        "Curses are thickest around the schools. The schools say they were built where the danger already was. The towns beside them have almost stopped having children: one parish recorded two births this year against thirty-one twenty years ago.",
        "A grader's internal survey found nine times the normal pool density near one school, thirty times beside the masters' dormitory, and half that while the students were away. The figure was struck from the yearly report.",
        "The curse-burners say the pools grow where sorcerers live, and their street counts back them up. A private letter from the head of the eldest house says the same thing to her heir, and calls the school a farm.",
        "Confirmed: the refined dread that sorcerers carry seeds the pools around them. The schools are breeding the very curses they are paid to kill, and the eldest of the three houses has known for a century and kept the figures out of every report.",
      ] },
  ],

  tags: ["curses"],

  subthemes: [
    { id: "tyrant_relics", n: "The Tyrant's Relics", d: "The body of an ancient curse-king was cut into twenty pieces and sealed in shrines across the land. Someone is collecting them, and each one taken makes the others whisper louder.", w: 1.4, req: { any: ["near:ruins", "ancestor_bound", "pious", "faith:ancestors"] }, tags: ["theme:tyrant_relics"] },
    { id: "great_houses", n: "The Three Houses", d: "Three ancient bloodlines pass down their inborn workings and control the schools. A child born without power to any of them is a family shame, and is treated as one.", w: 1.4, req: { any: ["hierarchical", "monarchy", "origin:old_dynasty", "dynastic"] }, tags: ["theme:great_houses"] },
    { id: "disaster_curses", n: "The Disaster Curses", d: "Curses born of the fear of earthquakes, forests and the sea have learned to speak. They hold councils, and they talk about the world after humans.", w: 1, mods: [["mountain", 1.5], ["coastal", 1.5], ["forest", 1.5]], truthLink: "fear_gods", tags: ["theme:disaster_curses"], mark: { kind: "zone", n: "Living land", color: "#3a2a4a", size: [2, 4], where: "remote" } },
    { id: "forgotten_word", n: "The Forgotten Word", d: "A province has lost a word. Nobody can say what it was, only that sentences end oddly and an old festival has no reason any more.", w: 0.7, truthLink: "fear_gods", tags: ["theme:forgotten_word"] },
    { id: "grief_hospital", n: "The House of Grief", d: "An asylum on a hill where the curses that crawl the corridors wear the faces of the patients' dead.", w: 0.9, req: { any: ["urbane", "has:city", "scholarly"] }, tags: ["theme:grief_hospital"], mark: { kind: "zone", n: "Black ground", color: "#2a2030", size: [1, 1], where: "inner" } },
    { id: "seeing_glass", n: "The Seeing-Glasses", d: "A lens-grinder has made cheap spectacles that let anyone see curses. The streets are full of panic, vigilantes and people who will never sleep again.", w: 0.8, req: { any: ["artisans", "urbane", "guilds", "mercantile"] }, tags: ["theme:seeing_glass"] },
    { id: "school_rot", n: "The Rot Under the Schools", d: "The two great schools of sorcery sit on the worst curse-pools in the land. The masters call it the natural result of training; the townsfolk around them have stopped having children.", w: 1, req: { any: ["academies", "scholarly", "learned", "organised"] }, truthLink: "sorcerers_source", tags: ["theme:school_rot"] },
    { id: "fear_cults", n: "The Fear-Cults", d: "Cults that worship a curse as a child of humanity, feed it, name it, and sing it to sleep. In some places, the curse really does listen.", w: 1, req: { any: ["faith:void", "sacrifice", "mystic", "sinister", "faith:spirits"] }, tags: ["theme:fear_cults"] },
    { id: "capital_ward", n: "The Ward of the Capital", d: "A ring of stone posts circles the capital, and every post carries a dead sorcerer's name. Lately the posts have begun to sweat.", w: 1.1, req: { any: ["autocracy", "gov:empire", "realm:large", "realm:vast", "big"] }, truthLink: "barrier_man", tags: ["theme:capital_ward"] },
    { id: "lottery", n: "The Harrowing Lottery", d: "Every soul in a province has been forced into a killing game by an old sorcerer playing a long hand. The rules arrive by dream, and refusing is not one of the options.", w: 0.6, req: { any: ["unstable", "autocracy", "realm:mid", "realm:large"] }, truthLink: "barrier_man", tags: ["theme:lottery"] },
    { id: "state_contracts", n: "The Bound Curses of State", d: "The crown has learned to bind tame curses by vow and use them as spies, executioners and border dogs. It has not told anyone how.", w: 0.9, req: { any: ["autocracy", "spy_network", "harsh_law", "standing_army"] }, truthLink: "sorcerers_source", tags: ["theme:state_curses"] },
  ],

  sites: [
    { id: "reliquary", n: "The Finger-Shrine of $", kind: "shrine", where: "remote", d: "A sealed reliquary holding a mummified finger that talks.",
      layers: {
        surface: { n: "Nine locks", text: "A mountain shrine above {place} with nine iron locks on one small door. Four monks keep it and refused even a crown warrant in {year}. Pilgrims leave salt on the doorstep. The salt turns grey within a day, and the monks sweep it into the gorge." },
        study: { n: "The waiting curses", text: "A grader's survey counted 140 curses within fifty miles of the shrine, all drifting toward it. Each one stops at the outer wall and stays there, facing the door. The monks sweep a path through them every morning with a broom of white birch." },
        dig: { n: "The finger", text: "Behind the ninth lock is a blackened finger on a silk cushion, longer than any man's. Those who sleep inside the walls dream of a man in red laughing at a feast. The shrine's founding charter names nineteen sister shrines; a copy is kept in {lead}.", points: "archive" },
        revelation: { n: "A beacon, not a prison", text: "The finger is one of twenty pieces of the curse-king, cut up by the first three houses and sealed apart. The houses meant the shrines as prisons. They work as beacons: every curse is drawn to a piece and waits there for its master. Two shrines are already empty, and the curses outside them have moved on." },
      } },
    { id: "colourless_town", n: "The Grey Town of $", kind: "anomaly", where: "any", truthLink: "fear_gods", d: "A town where no one remembers a colour.",
      layers: {
        surface: { n: "A drab town", text: "Travellers find {place} drab and cannot say why. Its 40 houses, market awnings and chapel doors are all grey or brown. The dyers' guild hall stands empty, with a sign over the door scraped down to bare wood." },
        study: { n: "Grey, but loud", text: "Shown a dyed cloth, townsfolk call it 'grey, but loud' and look away. The schoolmaster's word-list has 11 blank lines where a colour's names should be. Children here paint with ash. Their grandparents' wedding clothes lie folded in chests that nobody opens." },
        dig: { n: "Under the dye-works", text: "Under the old dye-works lies the husk of a vast curse curled around six vats, its mouths sewn shut with sorcerer's thread. The vats are crusted with a dye nobody can name. The school's kill register for that year is kept in {lead}.", points: "archive" },
        revelation: { n: "The colour that was killed", text: "The town once feared one colour as the colour of the plague that killed half of it. That shared fear woke as a great curse, and a school master killed it for a fee of 200 crowns. The colour went with it, from the world and from every memory. The register calls it a clean kill." },
      } },
    { id: "realm_shell", n: "The Empty School of $", kind: "ruin", where: "inner", d: "An abandoned school whose hall is still a sealed inner world.",
      layers: {
        surface: { n: "The wrong sky", text: "A boarded-up schoolhouse at {place}, closed since {year}. Through gaps in the boards, the hall windows show night and a red moon at any hour. Carters take the long road round. The school still pays the building's rates every year, on time." },
        study: { n: "The lake in the hall", text: "Step through the hall door and the room is a lake under a red moon: a sorcerer's inner world, still standing without its maker. A rope let out from the door ran 300 paces before going slack. An hour inside is four minutes outside." },
        dig: { n: "The diver's find", text: "Divers found the maker at the bottom of the lake in a master's robe, perfectly kept, eyes open. A brass school badge on the robe gives a name and the year {year}. The school says this master died abroad; the master's file is held in {lead}.", points: "archive" },
        revelation: { n: "Still dreaming", text: "A self-world can outlast its maker only if the maker never truly leaves it. This master never did. The master is alive at the bottom of the lake and still dreaming it. The school knew within a month, sealed the building, and has paid its rates for sixty years rather than open the door." },
      } },
    { id: "name_posts", n: "The Named Posts of $", kind: "wonder", where: "capital", truthLink: "barrier_man", d: "A ring of carved posts around a capital, one for each dead sorcerer.",
      layers: {
        surface: { n: "Grey posts", text: "Grey stone posts stand at every road into {place}, 41 in all, each carved with a name and a date. Lately they sweat black water, which the wardens wipe off at dawn with linen cloths. The cloths are burned afterwards, never washed." },
        study: { n: "One death a generation", text: "The dates run back a thousand years, one death about every 25 years, never two at once. The masons' guild of {place} has no record of carving any of them. Every name belongs to one of the most gifted young sorcerers of the houses." },
        dig: { n: "The warm door", text: "Under the central post is a stair of 88 steps. At its foot is a warm door of something like hide that swells and shrinks every few seconds, scratched all over on its inner face. The succession roll that matches names to posts is kept in {lead}.", points: "archive" },
        revelation: { n: "The Keeper", text: "Every name on the posts was a young sorcerer the three houses handed to the Keeper, a man who has held the ward up with his body for a thousand years. Each was merged into him. He has taken 41 people. The last three lasted half as long as the ones before, and the houses have no candidate left." },
      } },
    { id: "fear_map", n: "The Cult Map at $", kind: "dig", where: "any", truthLink: "fear_gods", d: "A cult's map of the land, marking every disaster before it happened.",
      layers: {
        surface: { n: "The burned house", text: "A cult house outside {place}, burned by the townsfolk in {year} with nine members inside. In the cellar a map of the land is painted across one whole wall. The council left it there because nobody would go down with a brush." },
        study: { n: "Thirty-one marks", text: "The map has 31 red marks, each a landslide, a flood or a fire. Nine happened before the cult was burned. Four happened after, at exactly the marked spots. The rest have not happened yet, and one of them sits over the capital." },
        dig: { n: "The words beside the marks", text: "Beside each mark is one word in the cult's hand: 'drowning', 'the dark', 'the high pass'. A ledger behind a loose brick lists the offerings made at each place: bread, hair, songs. The cult's survivors still keep the other half of that ledger at {lead}.", points: "heretic" },
        revelation: { n: "Choosing what to feed", text: "The cult was not predicting disasters. It recorded what each district feared most and fed the strongest fears until they woke as calamity curses, and so chose which towns would fall. The townsfolk burned the members but left the map. Two new marks have been painted on it since." },
      } },
  ],

  beings: [
    { id: "pool_curse", n: "Pool-curse", kind: "beast", d: "A curse woken from an old pool of dread: a dark body covered in mouths, which only the gifted can see.", danger: 2, biomes: ["swamp", "tempforest", "temprain", "boreal", "badlands"], look: { size: 2, group: [1, 3], move: "solo", speed: 8, col: "#2a1a2a", col2: "#8a3a6a", body: "spider", active: "night", visible: false } },
    { id: "dread_vermin", n: "Dread-vermin", kind: "small", d: "Fourth-grade curses: little, numerous, harmless one at a time, and found wherever people are miserable.", danger: 1, biomes: ["grass", "tempforest", "swamp", "dryforest", "river"], look: { size: 0.3, group: [5, 30], move: "swarm", speed: 6, col: "#3a3040", col2: "#6a5a7a", body: "insect", active: "night", visible: false } },
    { id: "calamity_curse", n: "Calamity curse", kind: "beast", d: "A curse born of a whole people's fear of a disaster. It thinks, it speaks, and it wants the world.", danger: 3, biomes: ["peaks", "rainforest", "mangrove", "alpine", "desert"], look: { size: 6, group: [1, 1], move: "solo", speed: 12, col: "#4a1a1a", col2: "#e06030", body: "biped", active: "any", visible: false } },
  ],

  techs: [
    { id: "gw_charms", n: "Crossroad charms", field: "arcana", level: 1, d: "Paper wards and shrine-posts that keep small curses from pooling where people pass." },
    { id: "gw_grading", n: "Curse grading", field: "natural_philosophy", level: 2, d: "A register of curses by grade, from vermin to calamity, and of sorcerers to match." },
    { id: "gw_cursed_tools", n: "Cursed tools", field: "metallurgy", level: 3, d: "Blades that cut spirits and chains that have no end, forged around a captive curse." },
    { id: "gw_barriers", n: "Curtain barriers", field: "architecture", level: 3, d: "Black curtains of dread dropped over a district to hide a fight from the unseeing." },
    { id: "gw_seeing_glass", n: "Seeing-glasses", field: "medicine", level: 4, d: "Lenses ground with a sorcerer's blood that let anyone see curses." },
    { id: "gw_inner_world", n: "The inner world", field: "arcana", level: 5, d: "The sorcerer turns the space around them into a pocket world shaped by their own mind, where their working cannot miss." },
  ],

  units: [
    { id: "gw_sorcerers", n: "Grudge-sorcerers", role: "magic", wpn: "sword", kit: "robe", ranks: 2, gap: 3, size: 20, w: 1, mods: [["theme:great_houses", 3], ["theme:school_rot", 2]] },
    { id: "gw_curse_hounds", n: "Bound curses", role: "beast", mounted: 0, wpn: "axe", kit: "hide", ranks: 2, gap: 2, size: 30, w: 0.4, mods: [["theme:state_curses", 10]] },
  ],

  faiths: [
    { id: "gw_fear_cult", n: "Fear-cult", d: "The curses are humanity's children, and the faithful feed and soothe them so they do not grow hungry.", tags: ["faith:fear_cult", "sinister"], w: 0.4, names: ["The Nursery of $", "The Kindly Dread", "The Hymn of the Pools"], mods: [["theme:fear_cults", 6], ["sacrifice", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Black zone", color: "#2a2030", size: [1, 2], count: [1, 3], where: "any", d: "Ground thick with pooled dread: old battlefields, plague pits, prisons." },
  ],

  storylines: [
    { id: "gw_relic", n: "The Finger of {place}", scale: "local", anchor: "town", w: 2, req: "curses",
      stages: {
        start: { h: "A shrine is robbed near {place}", b: "The nine locks of the hill shrine above {place} were found open and the cushion bare. Curses have been seen walking the lanes in daylight, all going the same way.", wait: [1, 4], fx: { unrest: 6 }, next: [{ to: "boy_eats", w: 2 }, { to: "school_sends", w: 1, mods: [["learned", 2], ["theme:great_houses", 2]] }] },
        boy_eats: { h: "A youth of {place} swallows the relic", b: "Cornered by a curse in the schoolyard, {person} swallowed the blackened finger to keep it from the curse. {person} lived, but the dead tyrant now shares the body, and sometimes laughs with {person}'s mouth.", wait: [2, 6], fx: { flag: "vessel" }, next: [{ to: "execution", w: 1, mods: [["harsh_law", 2], ["theme:great_houses", 2]] }, { to: "vessel_trained", w: 2 }] },
        school_sends: { h: "Sorcerers arrive in {place}", b: "{person2}, a master of the school, has come for the relic with three students. The townsfolk are told it is a gas leak.", wait: [2, 5], next: [{ to: "boy_eats", w: 1 }, { to: "recovered", w: 1 }] },
        execution: { h: "The vessel of {place} is condemned", b: "The houses have ruled that {person} must die. {person2} has refused to carry out the sentence, and has vanished with the youth.", fx: { unrest: 8, stability: -3 }, end: true },
        vessel_trained: { h: "The school takes in the vessel of {place}", b: "{person} has been enrolled at the school, under a suspended sentence of death, to eat the other nineteen pieces before anyone else can. Once the last piece is eaten, {person} will be executed, and everyone involved knows it.", fx: { science: { arcana: 0.5 } }, end: true },
        recovered: { h: "The relic of {place} is sealed again", b: "{person2} cornered the thief in a flooded cellar and sealed the finger in salt. Two students did not come home.", fx: { stability: 3 }, end: true },
      } },
    { id: "gw_glasses", n: "The Glasses of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["curses", { any: ["urbane", "artisans", "learned", "mercantile"] }],
      stages: {
        start: { h: "Seeing-glasses on sale in {capital}", b: "{person}, a lens-grinder of {capital}, is selling spectacles that let the wearer see curses. Several of the first buyers have been taken to the asylum.", wait: [2, 5], next: [{ to: "panic", w: 2 }, { to: "banned", w: 1, mods: [["harsh_law", 2], ["autocracy", 1.5]] }] },
        panic: { h: "Panic spreads through {realm}", b: "Everyone can see the curses now: on the stairs, in the wells, at the foot of every sickbed. Mobs have burned three houses where curses were pooling, and the families inside.", wait: [3, 8], fx: { unrest: 15, stability: -6 }, next: [{ to: "vigilantes", w: 1 }, { to: "public_sorcery", w: 1, mods: [["learned", 2], ["ruler:reformer", 3]] }] },
        banned: { h: "{ruler} bans the glasses", b: "The lens-grinder {person} has been arrested and the glasses broken in the square. Some were kept back, and they sell for their weight in silver.", fx: { stability: 2, unrest: 4 }, end: true },
        vigilantes: { h: "The curse-burners of {realm}", b: "Gangs with glasses and torches now rule the night streets of {capital}. They say the pools only grow where sorcerers live. They are not entirely wrong.", fx: { unrest: 12, revolt: true }, end: true },
        public_sorcery: { h: "Sorcery comes into the open in {realm}", b: "{ruler} has made the schools public institutions and handed out glasses to every watch-house. For the first time, ordinary people help hunt the curses.", fx: { stability: 6, discovery: "medicine", prestige: 5 }, end: true },
      } },
    { id: "gw_ward_keeper", n: "The Keeper Beneath {capital}", scale: "realm", anchor: "realm", w: 1, req: ["curses", { any: ["big", "autocracy", "gov:empire"] }],
      stages: {
        start: { h: "The ward-posts of {capital} weep", b: "The named stone posts around {capital} have begun sweating black water. Curses have been seen inside the walls for the first time in living memory.", wait: [3, 6], fx: { unrest: 8 }, next: [{ to: "successor_sought", w: 2 }, { to: "ward_fails", w: 1, mods: [["unstable", 2], ["chance:low", 2]] }] },
        successor_sought: { h: "A successor is sought for the ward", b: "Masked emissaries have come to {person}'s door: the youngest sorcerer of the houses to test so high. Nobody tells {person} what the honour involves.", wait: [3, 8], next: [{ to: "merged", w: 1 }, { to: "refuses", w: 1, mods: [["egalitarian", 2], ["ruler:just", 2]] }] },
        merged: { h: "A new name is carved at {capital}", b: "A new post stands at the north gate, carved with {person}'s name. The black water has stopped. The emissaries say {person} is at peace.", fx: { stability: 8 }, end: true },
        refuses: { h: "The chosen one of {capital} runs", b: "{person} learned what the successor becomes and fled with the truth. Pamphlets on every wall of {capital} ask who the ward-keeper is, and how many he has eaten.", fx: { stability: -10, unrest: 15 }, end: true },
        ward_fails: { h: "The ward over {capital} breaks", b: "On the longest night the posts cracked one after another. A thousand years of held-back curses poured into {capital} at once.", fx: { pop: 0.85, stability: -20, plague: true }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "School grading manual", text: "From the grading manual of the school at {place}, {year} edition, issued to every first-year: 'A curse is dread that has pooled in a dark place and woken. Grade Four: vermin, a broom will do. Grade Three: dangerous to the untrained. Grade Two: a sorcerer's work. Grade One: a master's. Above Grade One, report and withdraw. Do not count the mouths aloud. A lost manual costs two silver to replace.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "{survivor}, of a great house", text: "{survivor}, giftless child of a great house, recalling the nursery in {place}: 'Don't sulk in the dark, our old nurse said, or the dark will learn your face. She meant it as a joke. Nobody in our house laughed. Every winter a grade-four curse grew in the cellar, and it was always shaped a little like whoever had cried most that year. One year it looked like me.'" },
    { depth: "lore", about: "power", source: "archive", bias: "propaganda", reliable: false, who: "Watch-house statement, filed by the school", text: "Watch-house statement, {place}, night of the 9th, filed by the school's liaison: 'The witness, a baker, reports a beast with many mouths on the bakery stair. Investigation found a leaking gas pipe under the stair. The pipe has been mended. The witness was given a sedative and two days' wages for the trouble. Further reports from this street go to the school office in {lead}.'", points: "archive" },
    { depth: "core", about: "truth:barrier_man", source: "ruin", bias: "true", reliable: true, plain: true, who: "A successor, scratched on the warm door", text: "Scratched with a nail on the inside of the warm door under the central ward-post of {place}, by the successor of {year}: 'I am the forty-first. The houses told me I would be a hero. They carried me down 88 steps and pressed me into the Keeper, the old sorcerer who holds the ward up with his own body. Now I am one more voice inside him. He uses us up faster each time. Someone tell my sister.'" },
    { depth: "core", about: "truth:barrier_man", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "{official}, warden of the ward-posts", text: "From the three houses' succession roll, entry for {year}, in the hand of {official}, warden of the ward-posts: 'Candidate: elder daughter of the second house, aged nineteen, graded One. To be presented to the Keeper on the longest night. Family compensated as for death in service: 400 crowns and a post in her name. The younger sibling, {survivor}, ungifted, objected at table and is confined to the east wing until spring.'" },
    { depth: "core", about: "truth:barrier_man", source: "oral", bias: "garbled", reliable: "partial", points: "site:name_posts", who: "A skipping rhyme, noted by {investigator}", text: "A skipping rhyme from the gate streets of {place}, written down by {investigator} in {year}: 'Old man under the palace floor, holds the bad things from the door. Every hundred years or so, someone has to hold him. Go!' The child who says 'Go!' is out. All six children pointed at the same ward-post when they said it, the central post of {lead}." },
    { depth: "core", about: "truth:barrier_man", source: "person", bias: "exaggerated", reliable: "partial", who: "A retired master, overheard by {investigator}", text: "Overheard by {investigator} at an inn in {place}, {year}, from a retired master of the school after six cups: 'Who do you think carves the posts? Not us, boy. Forty-one names in a ring and not one mason ever paid. They carve themselves, the night after. I saw the last one come up out of the stone like frost on a window.' The master left without paying." },
    { depth: "core", about: "truth:barrier_man", source: "library", bias: "official", reliable: false, who: "Official guide to the capital", text: "From 'The Capital and Its Defences', the official guide sold at the gates of {place}, {year}, price one silver: 'The ward of the capital is a stone circle of great age, renewed each generation by the joint working of the three houses. It requires no keeper and has no weakness. The names on the posts honour masters who died in service. Visitors are asked not to touch the posts, which are cleaned weekly.'" },
    { depth: "core", about: "truth:fear_gods", source: "ruin", bias: "true", reliable: true, plain: true, who: "A sorcerer's last words, on a lair wall", text: "Written in charcoal on the wall of a calamity curse's lair near {place}, in the hand of a master listed among the school's dead for {year}: 'We killed it at noon, four of us. It was made of what the whole valley feared together, and when it died the feared thing went with it, out of the world and out of every head but ours. It is going from mine. I have written the word here so that someone' The wall below is blank." },
    { depth: "core", about: "truth:fear_gods", source: "heretic", bias: "heretic", reliable: "partial", points: "heretic", who: "{believer}, of the fear-cult", text: "Catechism of the fear-cult, as taught by {believer} to new members at {place} in {year}, question seven: 'What are the great curses? Our children, made of what we dread together. What happens when a school kills one? A part of our minds dies with it, and the thing we feared is gone from the world. Why do we feed them? Because a people with nothing left to fear has nothing left to name.' Copies are given out at {lead}." },
    { depth: "core", about: "truth:fear_gods", source: "library", bias: "garbled", reliable: "partial", points: "site:colourless_town", who: "{investigator}, marginal note", text: "Marginal note by {investigator} in the library of {place}, {year}: 'The old harvest hymn has a line that does not scan: \"We feared the ___ and the ___ feared us.\" All 23 copies I have checked have the same gap, in hands two centuries apart. The dyers of {lead} sing the same hymn and stop at the same place. I mean to go there and ask them what is missing.'" },
    { depth: "core", about: "truth:fear_gods", source: "library", bias: "official", reliable: false, who: "School council circular", text: "Circular of the school council to provincial wardens, {year}, item 3: 'The calamity curses are large and unusually dangerous, but they are curses like any other. Slaying one has no effect beyond relief to the district. Reports of words or colours lost after a slaying are folk confusion and are not to be entered in the register. Wardens who file them will pay the copying fee themselves.'" },
    { depth: "core", about: "truth:fear_gods", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a hunter's daughter", text: "Letter from {person}, a hunter's daughter of {place}, to the school council, {year}: 'My father hunted for the bounty office for thirty years. Since your masters killed the great curse in the hills, there is nothing left to hunt, and he cannot say what he used to hunt. His bounty book has 212 entries with the animal's name scraped blank. The office has stopped his pension because the bounty no longer exists. What did you kill?'" },
    { depth: "core", about: "truth:sorcerers_source", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "{investigator}, grader", text: "Internal survey of the school at {place}, {year}, by grader {investigator}, page 4: 'Pool density within five miles of the school: nine times the provincial mean. Within one mile of the masters' dormitory: thirty times. Density falls by half each summer the students are away.' Below, in a different hand: 'Recommend this figure not be included in the yearly report.' The full survey was filed in {lead}." },
    { depth: "core", about: "truth:sorcerers_source", source: "heretic", bias: "exaggerated", reliable: "partial", who: "Curse-burners' pamphlet", text: "Pamphlet of the curse-burners, nailed to doors in {place} in {year}: 'WHERE DO THE CURSES GROW? NEXT TO THE PEOPLE WHO SAY THEY KILL THEM. Put on a pair of glasses and walk from the school gate to the river: we counted 64 pools. Walk the same distance the other way: 7. ASK WHO PROFITS. ASK WHO PAYS. ASK WHY THE MASTERS NEVER MOVE HOUSE.'" },
    { depth: "core", about: "truth:sorcerers_source", source: "person", bias: "true", reliable: true, plain: true, who: "Head of the eldest house, to her heir", text: "Letter from the head of the eldest house to her heir, {year}, found among the papers of {official}: 'You are old enough to be told. Our dread feeds the pools. Every sorcerer we train leaks refined spite, and curses grow from it like mould on bread. The school is a farm, and we are the crop and the farmers both. Either the schools go or the people do. The other two houses know, and say nothing.'" },
    { depth: "core", about: "truth:sorcerers_source", source: "temple", bias: "official", reliable: false, who: "{official}, founders' day sermon", text: "Sermon preached by {official} in the school chapel of {place} on founders' day, {year}: 'Why do the schools stand where the curses are worst? Because they were built to defend the people there. Curses gather near sorcerers as wolves gather near a fold. Pray for the masters, who sleep beside the danger so that you need not. Today's collection goes to the dormitory roof, which leaks.'" },
    { depth: "core", about: "truth:sorcerers_source", source: "archive", bias: "redacted", reliable: "partial", cost: true, who: "Parish register beside the school wall", text: "Parish register of {place}, the parish beside the school wall, {year}, kept by the sexton: 'Births this year: two. Twenty years ago: thirty-one. The midwife has moved to the coast. The school bought the empty houses on Tanner Row at half price. Today I buried the child of {person}, the miller's wife, carried for eight months after nine years of trying. The school physician said it was the damp.'" },
    { depth: "sub", about: "sub:tyrant_relics", source: "traveller", bias: "garbled", reliable: "partial", points: "site:reliquary", who: "A mule-driver, to {investigator}", text: "A mule-driver's account, taken down by {investigator} on the pass road near {place}, {year}: 'The monks say there are twenty pieces of the old king, sealed in twenty shrines. That is a lot of king, I said. Nobody laughed. Two shrines down the valley were robbed this spring, both with all nine locks opened clean. If you want monks who still keep a piece, go up to {lead}.'" },
    { depth: "sub", about: "sub:great_houses", source: "archive", bias: "official", reliable: "partial", points: "cast:survivor", who: "Herald's copy of a house genealogy", text: "Genealogy of the second house, copied for the herald's office of {place} in {year}: twelve generations, with one name in each written in smaller letters and marked 'without gift: provided for'. The last small name is {survivor}'s. A clerk's note: 'The provided-for receive 30 crowns a year and a house in the country. Several asked to stay at court. None were allowed.' {survivor} now lives at {lead}." },
    { depth: "sub", about: "sub:disaster_curses", source: "person", bias: "true", reliable: true, who: "{person}, forester, to the warden's court", text: "Deposition of {person}, forester, to the warden's court at {place}, {year}: 'It stood up out of the beeches, taller than the fire-tower, and spoke to me in my own voice. It said the forest was patient and we were not. It said there would be a council at the first frost, and that people would be the business. Then it went back into the trees.' The forester's axe was found 200 paces away, rusted through." },
    { depth: "sub", about: "sub:grief_hospital", source: "person", bias: "true", reliable: "partial", who: "{believer}, night nurse", text: "Diary of {believer}, night nurse at the House of Grief above {place}, {year}: 'Room nine's husband came again tonight, the fourth visit this month. He has been dead four years. He stands at the foot of her bed with his drowned face, and she smiles at him. The board gave us glasses, so I see him too. I have stopped trying to send him away. When he comes, she eats.'" },
    { depth: "sub", about: "sub:seeing_glass", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A wool-buyer, to the firm", text: "Letter from a wool-buyer passing through {place}, {year}, to the firm: 'The whole street wears spectacles now. A pair costs three silver and the lens-grinder cannot keep up. Nobody sits on the third stair of the old courthouse, and nobody will say why. I sat there to eat my lunch and a woman knocked the bread out of my hand. I shall buy a pair before I sleep in this town again.'" },
    { depth: "sub", about: "sub:fear_cults", source: "temple", bias: "pious", reliable: "partial", points: "temple", who: "{investigator}, on a fear-cult meeting", text: "Notes of {investigator} on a fear-cult meeting behind the tannery at {place}, {year}. Eleven singers sat round a pool of dread and sang: 'Hush now, little dread, we made you, we fed you, we will not leave you alone in the dark.' The pool shrank by a third while they sang. By morning it had grown back. The cult borrows the side chapel at {lead} on every new moon." },
    { depth: "sub", about: "sub:lottery", source: "person", bias: "true", reliable: true, who: "{person}, a carter, to the magistrate", text: "Statement of {person}, a carter of {place}, to the magistrate, {year}: 'The rules came in my sleep, written on the inside of my eyes. Five points for every gifted life. One for the ungifted. A hundred points buys a city. I woke with blood on my hands and the number six in my head. I have not left the house since. My wife has hidden the knives. Please lock me up.'" },
    { depth: "sub", about: "sub:state_contracts", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "Treasury ledger, border accounts", text: "Treasury ledger of {realm}, border accounts, third quarter of {year}, page 112: 'Upkeep of the eastern border dogs: forty grieving widows per quarter, to be found. Paid to each widow: 2 crowns. Contractor for finding: [name cut out]. Note: the dogs went hungry in the second quarter and the post at the ford was lost.' The binding vows themselves are filed in {lead}." },
    { depth: "site", about: "site:colourless_town", source: "traveller", bias: "true", reliable: true, who: "A cloth merchant's journal", text: "Journal of a cloth merchant at the inn of the grey town near {place}, {year}: 'I gave the innkeeper's girl a ribbon from my sample case, the madder one. She held it a long time and asked what it was for. Her mother called it grey, but loud. Then the girl cried and could not say why. Of the 40 houses here, not one door is painted anything but grey.'" },
    { depth: "site", about: "site:realm_shell", source: "person", bias: "true", reliable: true, points: "archive", who: "The school bursar, to the rates office", text: "Letter from the bursar of the school to the rates office of {place}, {year}: 'Enclosed, 14 crowns for the closed hall on the north road, as every year for sixty years. Your new assessor asks why we pay rates on an empty building rather than sell it. The school is not selling. The windows show night because the glass is old. Please do not send the assessor again; we understand he has not slept since. Queries about the hall's last occupant go to {lead}.'" },
    { depth: "site", about: "site:fear_map", source: "ruin", bias: "true", reliable: "partial", points: "archive", who: "Town council minutes", text: "Minutes of the town council of {place}, {year}, item 6, the cellar of the burned cult house: 'The painted map in the cellar is still there. The flood at the mill came where the cult marked it. Motion to paint over the map: carried, nine to two. Volunteers to go down with the brush: none. Motion to brick up the cellar: deferred. The clerk notes that two new red marks have appeared since spring. The cult's own records were seized and sent to {lead}.'" },
  ],
};
