// Hungerfruit: powers you eat, the sea that refuses those who have eaten, and the century nobody may read about.
export default {
  id: "hungerfruit",
  name: "Hungerfruit",
  family: "power",
  pitch: "Rare fruits give one impossible gift to whoever eats one. The sea once belonged to the people who made the fruits, and it drowns any eater who falls into it.",
  slots: ["world-edge", "power-access", "economy-resource", "state-control"],
  tone: ["heroic", "whimsical"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "shonen", "flintlock"],
  w: 1,
  excludes: [],
  pairs: [{ id: "nursery_sea", w: 3 }, { id: "drowned_crown", w: 2.5 }, { id: "vowfire", w: 1.5 }, { id: "elder_lattice", w: 1.5 }, { id: "unremembering", w: 1.5 }],

  power: {
    name: "the eaten gift", user: "fruit-eater", users: "fruit-eaters",
    taught: "A hungerfruit is a swirl-skinned fruit that tastes of rot and ash. Whoever eats it gains a single impossible gift: a body of smoke, a body of rubber, a beast-shape, a door in the air. The gift is theirs until death, and then the fruit grows again somewhere nearby.",
    rules: ["One fruit to a body; a second kills the eater.", "No eater can swim again: the sea takes their strength and drowns them.", "Seastone, the grey stone of the ocean floor, drains any eater it touches.", "A gift is fixed in kind, but mastery stretches it until it reshapes the land around the eater."],
    forbidden: "Eating a second fruit, or killing an eater to catch the fruit when it regrows.",
  },

  cast: [
    { role: "investigator", n: "a cataloguer of the navy's fruit catalogue who reads the forbidden script in secret", home: "capital", stance: "Wants every gift written down truly, including where it came from, and is running out of safe places to keep notes." },
    { role: "official", n: "a commodore of the Admiralty who keeps the fruit vault and its ledgers", home: "coast", stance: "Believes the world is safe only while a single navy holds the fruit, the stone and the records." },
    { role: "believer", n: "a deepfolk singer of the reefs who keeps the old 'stolen songs'", home: "coast", stance: "Holds that every fruit is a stolen voice that should be given back to the sea." },
    { role: "survivor", n: "a freed slave of the seastone pits, missing three fingers", home: "remote", stance: "Wants the pits closed and wants to know where the fine stone dust was taken." },
  ],

  truths: [
    { id: "dreamers", n: "The fruits are wishes", d: "Each fruit is the hardened wish of a person who longed to become something else; the first grew on a dying god's wishing-tree, and every wisher since has given the wish up with their death. An eater slowly takes on part of the wisher's mind along with the gift. Old eaters start to remember a life that was not theirs, and some stop remembering their own.", tags: ["truth:fruit_dreamers"],
      known: [
        "Some old eaters report memories that are not theirs: a hill, a girl, a name they never knew. The Admiralty's natural history calls this a well-understood dotage and recommends retiring the eater at half pay.",
        "Island catechisms say every fruit is a wish that fell from a god's wishing-tree, and a stone tree full of fossil fruit lies under a mountain quarry. The borrowed memories of different eaters of the same gift match each other.",
        "Words carved round the fossil tree say its wishers came there to become something else, and that each wish hardened into a fruit when the wisher died. The Rot-Orchard bears only empty fruit, as if a wish can be used up.",
        "Confirmed: each fruit is a dead person's hardened wish. With the gift the eater takes on part of the wisher's mind, and the oldest eaters begin to forget their own lives and live the wisher's instead.",
      ] },
    { id: "vanquished", n: "The fruits are the vanquished", d: "Three centuries ago the twenty families who now sit on the world council destroyed a sea-kingdom and wiped it out of history. They had its people's gifts rendered into fruit and shared them out as spoils. The sea drowns eaters because it was that kingdom's sea and it refuses its killers' weapons. The council still hangs anyone who reads the kingdom's script.", tags: ["truth:fruit_vanquished"],
      known: [
        "The council says its history is complete, yet reading the black tablets on certain beaches is a hanging offence. The deepfolk of the reefs call the fruits 'stolen songs' and have 300 songs about one day.",
        "The council's founding record says the twenty families divided something among themselves in the year of the Settlement, and that the sea-lanes were closed for one season. The details are in a sealed annex nobody may read.",
        "A translation of the tablets says the twenty families burned a sea-kingdom, pressed its people's gifts into fruit and ate them, and that the sea would not hold them up afterwards. Scholars who read the tablets are hanged.",
        "Confirmed: the families who rule the world council destroyed a sea-kingdom three centuries ago, rendered its people's gifts into fruit and erased it from history. The sea drowns every eater because it was that kingdom's sea.",
      ] },
    { id: "leash", n: "The fruits are a leash", d: "Seastone and hungerfruit are the same mineral in two states. The Admiralty, the armed hand of the world's ruling power, presses fruit from seastone and seeds about fourteen a year, so that every great power in the world depends on the one thing only it can mine. It sells the gift, the chain for the gift and the cure, and slaves dig the stone for all three.", tags: ["truth:fruit_leash"],
      known: [
        "The Admiralty keeps a vault of uneaten fruit, sells seastone to every crown, and pays 50 crowns for the name of anyone who says it makes fruit. Pirates say there is only one shop in the world.",
        "An overseer at the seastone pits says ground seastone wet with blood goes soft like fruit-flesh. Every sixth week the finest stone dust leaves the pits under seal, for the navy and not for the smiths.",
        "The drowned hall off the coast has press-cellars full of half-stone fruit husks, and its vats carry the Admiralty anchor. An Admiralty ledger counts the fruits 'seeded' each year beside the ones recovered.",
        "Confirmed: fruit and seastone are one mineral. The Admiralty presses fruit from seastone and seeds about fourteen a year, so every great power needs both the gift and the stone that chains it, and both come from one shop.",
      ] },
  ],

  tags: ["fruit_gifts"],

  subthemes: [
    { id: "grand_course", n: "The Grand Course", d: "A sea-road of islands, each with its own weather and its own laws of nature. Every captain who wants to be anyone must sail it, and most of them sink.", w: 1.4, req: { any: ["seafaring", "has:port", "island", "coastal"] }, mods: [["navy", 1.5]], tags: ["theme:grand_course"], mark: { kind: "zone", n: "The Course", color: "#3a7a9a", size: [2, 5], where: "coast" } },
    { id: "admiralty", n: "The Admiralty Hoard", d: "The great navy keeps a vault of uneaten fruit and hands them out to its officers like medals. Mutiny now means a captain with a gift and nothing to lose.", w: 1.3, req: { any: ["navy", "standing_army", "autocracy", "gov:empire"] }, truthLink: "leash", tags: ["theme:admiralty"] },
    { id: "false_fruit", n: "The False-Fruit Works", d: "A warlord is pressing fruit from animal blood and seastone dust. One in ten works. The rest leave their eaters with a fixed smile they can never stop, and little mind left.", w: 1, req: { any: ["autocracy", "artisans", "harsh_law", "mercenaries"] }, tags: ["theme:false_fruit"], mark: { kind: "zone", n: "The Smiling Yards", color: "#8a6a2a", size: [1, 2], where: "remote" } },
    { id: "erased_century", n: "The Erased Century", d: "Unbreakable stone tablets record a lost century, in a script that it is a hanging offence to read. Archaeologists who try are hunted down, and so are their towns.", w: 1.1, req: { any: ["scholarly", "near:ruins", "academies", "origin:ruin_heirs"] }, truthLink: "vanquished", tags: ["theme:erased_century"] },
    { id: "stone_mines", n: "The Seastone Pits", d: "Slave gangs dig grey seastone out of drained tidal flats, the one stuff in the world that chains an eater. Every crown wants it. Every slave is an islander nobody will miss.", w: 1.1, req: { any: ["coastal", "harsh_law", "hierarchical", "mercantile"] }, truthLink: "leash", tags: ["theme:seastone_pits"] },
    { id: "beast_herd", n: "The Herd-Kingdom", d: "An island ruled by eaters of beast-fruits: a court of half-wolves, half-oxen and one half-dragon, who regard the rest of the world as livestock.", w: 0.8, req: { any: ["island", "near:beasts", "beast_tamers", "tribal"] }, tags: ["theme:beast_herd"] },
    { id: "nearest_heir", n: "Succession by Proximity", d: "A noble house's fruit regrows near wherever its eater dies. Every death-bed is crowded with relatives, and every relative has a knife.", w: 1, req: { any: ["monarchy", "dynastic", "hierarchical", "origin:old_dynasty"] }, truthLink: "dreamers", tags: ["theme:nearest_heir"] },
    { id: "deepfolk", n: "The Deepfolk Question", d: "The sea-peoples of the reefs swim where no eater can follow, and the land powers hate them for it. Their old songs call the fruits 'stolen songs'.", w: 1, req: { any: ["coastal", "island", "faith:sea", "seafaring"] }, truthLink: "vanquished", tags: ["theme:deepfolk"] },
    { id: "treasure_hunt", n: "The Dead King's Hoard", d: "A sea-king, hanged at sixty, laughed on the scaffold and told the crowd his treasure was still out there. Half the young of the coast have taken to the sea.", w: 1.2, req: { any: ["seafaring", "has:port", "mercenaries", "free_trade"] }, tags: ["theme:dead_kings_hoard"] },
    { id: "awakened", n: "The Awakened", d: "A handful of old eaters have learned to make the world around them obey their gift: a harbour turned to rubber, a valley turned to smoke. The crown calls them living disasters.", w: 0.7, truthLink: "dreamers", tags: ["theme:awakened"] },
    { id: "still_belt", n: "The Windless Belt", d: "A band of dead-calm sea, full of leviathans, separates two halves of the world. Only seastone-hulled ships slip through unnoticed, and only the crown builds them.", w: 0.9, req: { any: ["has:port", "seafaring", "navy"] }, truthLink: "leash", tags: ["theme:still_belt"] },
  ],

  sites: [
    { id: "tablet_isle", n: "The Unbreakable Stones of $", kind: "ruin", where: "coast", truthLink: "vanquished", d: "Tablets of a stone no tool can mark, carved in a forbidden script.",
      layers: {
        surface: { n: "Black stones", text: "Eleven black blocks lie on the beach at {place}, polished by the tide and covered in square letters. Fishermen use them as windbreaks. A harbour-court notice nailed to the nearest one says that copying the letters is a hanging offence." },
        study: { n: "Nothing marks them", text: "Nothing scratches the blocks: not steel, not fire, not an eater's gift. A smoke-eater tried in {year} and coughed for a week. The script matches no living language, though the deepfolk on the reef sing words that fit its rhythm." },
        dig: { n: "The wall under the sand", text: "Under the sand is a whole wall of blocks, 90 paces long, carved with a map of a coast that is no longer there. Twenty family crests run along the bottom. The council's sealed annex, which may explain them, is stored in {lead}.", points: "archive" },
        revelation: { n: "The kingdom that was sunk", text: "The tablets are the record of a sea-kingdom destroyed three centuries ago by the twenty families who now sit on the world council. They pressed its people's gifts into fruit, shared them as spoils, sank its coast and outlawed its script. The crests on the wall match the council's twenty seats." },
      } },
    { id: "rot_orchard", n: "The Rot-Orchard of $", kind: "anomaly", where: "remote", truthLink: "dreamers", d: "An island whose trees bear swirl-marked fruit that rots the instant it is picked.",
      layers: {
        surface: { n: "The ash grove", text: "A grove of 30 grey trees on an island off {place}. They fruit once a year and stink of ash. Fruit-hunters land every season and leave with nothing. Sailors call it the Liar's Orchard and will not anchor there overnight." },
        study: { n: "Fruit without a gift", text: "The fruit carries the swirl of a true hungerfruit, but no gift. Picked, it falls to grey pulp within a breath. A cataloguer who ate the pulp in {year} gained nothing but a fever, and dreamed for a week of a woman sitting under a tree." },
        dig: { n: "The seated bones", text: "Among the roots of the largest tree sits a skeleton with its hands clasped, ringed by the bones of hundreds of birds that ate the windfalls. A copper ring on one finger bears a crest listed in the navy's catalogue at {lead}.", points: "library" },
        revelation: { n: "A used-up wish", text: "Each true fruit is a hardened wish. This orchard grew from one dying woman's wish to bring her drowned children home, made as she sat down under the first tree. The navy harvested it for 160 years, one true fruit a year, until nothing of her wish was left. The navy still logs each failed harvest." },
      } },
    { id: "stone_throne", n: "The Drowned Hall of $", kind: "dig", where: "coast", truthLink: "leash", d: "A sunken palace with a throne carved from seastone.",
      layers: {
        surface: { n: "Columns at low tide", text: "At low spring tides the tops of 16 columns show above the waves off {place}. Fishermen tie up to them. Admiralty cutters chase off anyone who stays longer than one tide, and the fishermen have never been told why." },
        study: { n: "The seastone throne", text: "Divers find a throne room. The throne is cut from one block of seastone, the oldest piece ever seen. A diver who was also an eater touched it in {year} and had to be hauled up by the rope, limp as wet cloth." },
        dig: { n: "The press-cellars", text: "In the cellars are vats, pipes, millstones and the pressed husks of thousands of fruit, half turned back into grey stone. A brass plate on the largest vat carries the Admiralty anchor. The works' current ledgers are kept at {lead}.", points: "archive" },
        revelation: { n: "Where the fruits are made", text: "Fruit and seastone are one mineral in two states. The first kings of the present world pressed fruit here from ground stone and blood, and seeded it across the world so every power would need what only they could mine. The Admiralty inherited the works. Someone cleaned the vats last spring." },
      } },
    { id: "fruit_fossils", n: "The Fossil Bed of $", kind: "dig", where: "mountain", d: "Fruit-shaped fossils older than any human town.",
      layers: {
        surface: { n: "Spiral stones", text: "Quarrymen at {place} keep turning up round stones with a spiral pattern, about the size of a fist. They sell them to travellers for a copper each. The quarry-master keeps a basket of 200 by the gate for the tourist season." },
        study: { n: "The swirl in the grain", text: "Cut open, each stone shows the faint swirl of a hungerfruit in the grain of the rock. A navy cataloguer measured the rock beds in {year} and judged them many times older than any human town. The report was never published." },
        dig: { n: "The stone tree", text: "A whole fossil tree lies under the quarry floor, its trunk hollow and as wide as a house, its branches heavy with stone fruit. Words are carved round the trunk in an old script. A rubbing was sent to the library at {lead} for translation.", points: "library" },
        revelation: { n: "The first wishers", text: "The fruits are older than people. Creatures that lived here long before humans came to this tree to wish to be something else, and each wish hardened into fruit when the wisher died. The tree kept bearing after they were gone. Every fruit eaten today may carry a piece of a mind nobody alive has met." },
      } },
    { id: "census", n: "The Living Census of $", kind: "shrine", where: "capital", d: "A book listing every known gift, whose blank pages fill in by themselves.",
      layers: {
        surface: { n: "Under guard", text: "The navy's great catalogue of fruits sits under guard in the library at {place}: 6 volumes, 4,400 pages, two marines at the door. Visiting scholars may read it for one hour, in gloves, with a cataloguer watching over their shoulder." },
        study: { n: "Entries nobody wrote", text: "New entries appear overnight in a hand no librarian recognises, sometimes before the fruit is found. In {year} an entry described a smoke-gift eaten by a child of eleven in a town the navy did not know existed. The child ate the fruit two days later." },
        dig: { n: "The oldest pages", text: "The oldest pages list gifts the navy has never seen, with the eaters' names in the forbidden script of the black tablets. The binding is older than the navy itself. The library's record of how it acquired the first volume is filed in {lead}.", points: "archive" },
        revelation: { n: "Not the navy's book", text: "The navy did not make the census. It was taken from the drowned kingdom's archive in the year of the Settlement, and it never stopped writing. It lists every gift, including the ones the twenty families stole. Who writes the new entries is unknown. The navy guards the book because it is a list of what they owe." },
      } },
  ],

  beings: [
    { id: "belt_leviathan", n: "Belt leviathan", kind: "marine", d: "A sea-beast as long as a fleet, sleeping in the windless belt and waking for any keel it can smell.", danger: 3, biomes: ["open", "abyss"], look: { size: 60, group: [1, 2], move: "solo", speed: 20, col: "#2a4a5a", col2: "#8ab0a0", body: "whale", active: "any", visible: true } },
    { id: "deepfolk", n: "Deepfolk", kind: "marine", d: "Fish-skinned people of the reefs, proud, quick-tempered, and the only people who swim where eaters drown.", danger: 1, biomes: ["reef", "lagoon", "kelp", "shelf"], look: { size: 1.8, group: [2, 10], move: "school", speed: 14, col: "#3a7a8a", col2: "#d0c0a0", body: "biped", active: "day", visible: true } },
    { id: "smiler", n: "Smiler", kind: "beast", d: "A failed false-fruit eater: an animal gift without a mind behind it, and a face that cannot stop smiling.", danger: 2, biomes: ["savanna", "dryforest", "grass", "badlands"], look: { size: 1.7, group: [1, 4], move: "pack", speed: 10, col: "#9a7a4a", col2: "#d0b080", body: "quad", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "hf_catalogue", n: "The fruit catalogue", field: "writing", level: 1, d: "Every known fruit drawn and named, so a found fruit can be valued and an eater known." },
    { id: "hf_seastone", n: "Seastone working", field: "metallurgy", level: 2, d: "Manacles, nets and bullet-tips of grey stone that make an eater as weak as a child." },
    { id: "hf_island_needle", n: "Island-needles", field: "navigation", level: 2, d: "Compasses that lock onto the next island of the Course rather than the north." },
    { id: "hf_bounties", n: "The bounty register", field: "writing", level: 3, d: "Printed posters with a price on every outlaw eater: the first fame that crosses oceans." },
    { id: "hf_stone_hulls", n: "Seastone hulls", field: "navigation", level: 4, d: "Keels plated with seastone that slip through the windless belt unnoticed by its beasts." },
    { id: "hf_false_fruit", n: "Pressed fruit", field: "alchemy", level: 5, d: "Fruit made by hand from blood and stone. Most of them work badly; all of them cost." },
  ],

  units: [
    { id: "hf_marines", n: "Fruit-officers", role: "magic", wpn: "sword", kit: "light", ranks: 2, gap: 3, size: 20, w: 0.8, req: "has:port", mods: [["theme:admiralty", 6], ["navy", 2]] },
    { id: "hf_stone_shot", n: "Seastone musketeers", role: "ranged", wpn: "xbow", kit: "mail", ranks: 3, gap: 1.3, size: 100, w: 0.6, mods: [["theme:seastone_pits", 4], ["theme:admiralty", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Impossible weather", color: "#a0c0d0", size: [1, 3], count: [1, 2], where: "coast", d: "Islands where a fruit war left one corner in endless summer and another in endless snow." },
    { kind: "zone", n: "Seastone flats", color: "#7a8080", size: [1, 2], count: [1, 2], where: "coast", d: "Drained tidal flats where seastone is quarried by chained gangs." },
  ],

  storylines: [
    { id: "hf_found_fruit", n: "The Fruit of {place}", scale: "local", anchor: "coast", w: 2, req: "fruit_gifts",
      stages: {
        start: { h: "A hungerfruit washes ashore at {place}", b: "A fisher of {place} found a swirl-skinned fruit in the nets this morning. By noon three captains, a navy cutter and a fence from the capital were in the harbour.", wait: [1, 3], next: [{ to: "eaten", w: 2 }, { to: "auction", w: 1, mods: [["mercantile", 2], ["free_trade", 1.5]] }] },
        eaten: { h: "A child of {place} eats the fruit", b: "Before anyone could sell it, {person}, the fisher's youngest, ate it on a dare. {person} can now stretch like warm tar and will never swim again.", wait: [3, 10], fx: { flag: "eater" }, next: [{ to: "goes_to_sea", w: 2 }, { to: "navy_takes", w: 1, mods: [["navy", 2], ["harsh_law", 2]] }] },
        auction: { h: "The fruit of {place} goes to auction", b: "The fruit was sold to {person2} for the price of a town. {place} has new roofs, new boats, and new enemies.", fx: { treasury: 80, unrest: 5 }, end: true },
        goes_to_sea: { h: "{person} of {place} sails for the Course", b: "With a borrowed boat and a crew of three, {person} has gone after the dead king's hoard. The poster went up all over {realm} within the year.", fx: { prestige: 3 }, end: true },
        navy_takes: { h: "The navy pressgangs the eater of {place}", b: "An eater is a weapon, and weapons belong to the crown. {person} was taken aboard in seastone cuffs, and the fisher's boat was burned.", fx: { unrest: 10, stability: -2 }, end: true },
      } },
    { id: "hf_tablets", n: "The Forbidden Script of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["fruit_gifts", { any: ["scholarly", "learned", "academies", "near:ruins"] }],
      stages: {
        start: { h: "Scholars of {realm} read a forbidden stone", b: "{person}, a scholar at {capital}, claims to have read a line of the unbreakable tablets. The navy has sent an envoy to ask, politely, what it said.", wait: [2, 5], next: [{ to: "burned_isle", w: 2 }, { to: "copied", w: 1, mods: [["learned", 2], ["isolation", 2]] }] },
        burned_isle: { h: "The navy burns the scholars' island", b: "Warships shelled the library of {person} for a day and a night. The navy reports a rebel nest destroyed. Survivors say it was the books they aimed at.", wait: [2, 6], fx: { pop: 0.95, unrest: 15 }, next: [{ to: "one_escapes", w: 2 }, { to: "silence", w: 1 }] },
        copied: { h: "{realm} quietly copies the tablets", b: "{ruler} has refused the envoy and hidden {person} in the mountains. Copies of the script are being made in a cellar under {capital}.", fx: { science: { writing: 0.8 }, flag: "script" }, end: true },
        one_escapes: { h: "A child escapes the burning library", b: "{person2}, a child of eight who can read the script, was carried out by a giant from the navy who changed his mind. Both are now the most wanted people in the world.", fx: { discovery: "writing", prestige: 2 }, end: true },
        silence: { h: "No one speaks of the burned library", b: "The island is a black stub on the charts. In {capital} the scholars have found other things to study.", fx: { stability: 2, prestige: -4 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", points: "library", who: "The navy's fruit catalogue", text: "From the navy's fruit catalogue, {year} edition, page 1: 'Fruits are of three kinds: those that change the body, those that make the body a thing of nature, and those that give a beast's shape. The third kind is lesser, and fetches a third of the price. 412 gifts are known.' In one copy someone has underlined 'lesser' twice and written 'liars' in the margin. That copy is in {lead}." },
    { depth: "lore", about: "power", source: "oral", bias: "exaggerated", reliable: "partial", who: "A sailors' song, noted by a purser", text: "A drinking song, heard by a ship's purser at the Gull and Anchor in {place} in {year}, sung by thirty sailors on pay night: 'He ate the fruit and he lost the sea, and he won the world, so they say; but drink to the man who swims home free, for the sea won't have him today.' The eater at the corner table bought the next round and did not sing." },
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: true, who: "{person}, ferry-hand, to a sister", text: "Letter from {person}, a ferry-hand of {place}, to a sister inland, {year}: 'You asked what it was like. A hungerfruit, which is what they call these swirl-skinned things, tastes of rot and ash. Then for one moment it tastes of something else, like a name you nearly remember. I ate it a week ago. I can make my arm into smoke up to the elbow. I can't work the ferry now. The captain says the river counts as sea.'" },
    { depth: "core", about: "truth:dreamers", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, an eater of seventy, to a priest", text: "Confession of {person}, an eater of seventy, to the priest of {place}, {year}, written down at the eater's request: 'I dream of a girl on a hill who wanted to be a cloud. I ate her fruit at thirty and have been a cloud for forty years. Last month I called my own daughter by a name I have never known, and my daughter cried. I am dreaming as the girl now. I cannot remember my mother's face.'" },
    { depth: "core", about: "truth:dreamers", source: "temple", bias: "pious", reliable: "partial", points: "site:fruit_fossils", who: "Reef chapel catechism, copied by {investigator}", text: "Island catechism, taught at the reef chapel of {place} and copied by {investigator} in {year}: 'Where did the first fruit grow? In the first garden stood the tree that granted wishes, and the god who planted it died wishing. What is a fruit? A wish that fell. Where is the tree now? Turned to stone, at {lead}.' The chapel keeps one stone fruit on its altar, the size of a fist." },
    { depth: "core", about: "truth:dreamers", source: "ruin", bias: "true", reliable: true, plain: true, who: "The fossil tree, translated by {investigator}", text: "Carved round the trunk of the fossil tree, translated by {investigator} in {year}, oldest lines first: 'Here we came to wish to be other than we were: a cloud, a hawk, a door. When we die, each wish hardens into a fruit. Whoever eats it becomes what we wished, and carries a little of us with them. Let what we wished be eaten by someone who needs it more.' Below are 38 names." },
    { depth: "core", about: "truth:dreamers", source: "library", bias: "official", reliable: false, who: "Admiralty natural history", text: "From 'A Natural History of the Fruit', printed by the Admiralty press at {place} in {year}, chapter 2: 'A hungerfruit is a natural organism of rare occurrence, like a pearl. The memories some aged eaters report are a well-understood dotage and carry no meaning. Eaters who suffer from them should be retired at half pay and discouraged from discussing them. See appendix 4 for pension rates.'" },
    { depth: "core", about: "truth:vanquished", source: "oral", bias: "garbled", reliable: "partial", points: "cast:believer", who: "{believer}, a deepfolk singer", text: "Told by {believer}, a deepfolk singer, to a ship's boy who swam out to the reef at {place} in {year}: 'Your people call them fruit. We call them stolen songs. There was a kingdom that sang, and the sea held it up. People from the land took its voice, pressed it into fruit and ate it. We have 300 songs, and every one is about that day. Come to {lead} and hear one.'" },
    { depth: "core", about: "truth:vanquished", source: "ruin", bias: "true", reliable: true, plain: true, who: "The black tablets, translated by {investigator}", text: "From the black tablets on the beach at {place}, lines 14 to 19, in {investigator}'s hurried translation of {year}: 'The twenty families came in their ships and burned our cities. They took our singers and pressed our gifts into fruit, gave them out as spoils, and ate them. The sea that was ours would not hold them up. So they wrote that we never were. Remember us.' The translator's note: 'Plain as that. I checked it twice.'" },
    { depth: "core", about: "truth:vanquished", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "World council founding record, held by {official}", text: "From the founding records of the world council, copy held by {official}, entry for the year of the Settlement: 'The twenty families divided ______ among themselves, in shares as recorded in the sealed annex. The sea-lanes were closed for one season while the matter was concluded. Compensation to fishermen: none.' The sealed annex is not bound in this copy. The index lists it as stored at {lead}." },
    { depth: "core", about: "truth:vanquished", source: "library", bias: "official", reliable: false, who: "Council history for schools", text: "From the council's 'Short History for Schools', {year} edition, issued free to every harbour school in {realm}: 'There is no lost century. The historical record of the world council is complete and continuous from the founding to the present day. The black stones on some beaches are natural and carry no writing. Children who claim to read them are to be reported to the harbourmaster.'" },
    { depth: "core", about: "truth:vanquished", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a scholar's widow", text: "Petition of {person}, widow of a scholar of {place}, to the council's harbour court, {year}: 'My husband read 40 lines of the black stones and copied them into a school exercise book. Your officers hanged him in the square on market day and burned the book and our house. I ask only for his body, and the 12 crowns the school still owed him. I never read the book. I cannot read at all.'" },
    { depth: "core", about: "truth:leash", source: "person", bias: "true", reliable: "partial", points: "site:stone_throne", who: "A pit overseer, to {investigator}", text: "Said to {investigator} by an overseer of the seastone pits at {place}, {year}, after a third bottle: 'Grind seastone fine enough, wet it with blood, and it goes soft, like fruit-flesh. Swirls come up in it. I saw them press a barrel of it in the old drowned hall at {lead}, under guard, an Admiralty seal on the door. I wish I had not seen it. I have worked nights ever since.'" },
    { depth: "core", about: "truth:leash", source: "heretic", bias: "heretic", reliable: "partial", points: "heretic", who: "A pirate broadside", text: "Pirate broadside, pasted on the harbour wall at {place} in {year}: 'Who sells the fruit? Who sells the stone? Who sells the cuffs for the gift they sold you? Who sells the cure? There is ONE shop in this world, brothers, and its flag flies over every harbour. Count the Admiralty cutters in port today. We counted 9. Copies of this sheet at {lead}.'" },
    { depth: "core", about: "truth:leash", source: "archive", bias: "redacted", reliable: true, plain: true, who: "Admiralty fruit office ledger, signed {official}", text: "Admiralty ledger, fruit office, {year}, signed by {official}: 'Fruits pressed from seastone at the works: 14. Seeded this year on beaches and in markets: 14. Recovered: 9. Eaters registered: 11. At large: 3 (see warrants). Seastone sold to crowns for cuffs and hulls: 2,600 tons.' The column headed 'pressed from seastone' has been inked over in a later hand. The figures show through." },
    { depth: "core", about: "truth:leash", source: "library", bias: "propaganda", reliable: false, who: "Admiralty notice", text: "Notice of the Admiralty, posted in every port of {realm}, {year}: 'The Admiralty holds uneaten fruits only to keep them from pirates and tyrants. Seastone is mined only for the safety of decent people, and is sold at cost. Rumours that the Admiralty makes or sows fruit are pirate lies. A reward of 50 crowns is paid for the name of anyone who repeats them.'" },
    { depth: "core", about: "truth:leash", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, freed from the pits", text: "Statement of {survivor}, freed from the seastone pits at {place} in {year}, to a harbour clerk: 'Eleven years I cut the grey stone with my hands, and lost three fingers to it. Every sixth week a wagon took the finest dust away under seal, to the navy, not to the smiths. My brother went with one wagon to load it and did not come back. The pit clerk said he had been made useful.'" },
    { depth: "sub", about: "sub:grand_course", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A brig's mate, on the Grand Course", text: "Log of a merchant brig on the Grand Course, the island road out of {place}, {year}, kept by the mate: 'Third island: it snowed upward for two days. Fourth: the sea was hot enough to cook in, so we did. Fifth: the cook ate something on the beach that he should not have. Now he can turn into fog, and now he is the captain. 23 crew left of 40.'" },
    { depth: "sub", about: "sub:false_fruit", source: "person", bias: "true", reliable: true, points: "sub:false_fruit", who: "{person}, to the magistrate", text: "Letter from {person} of {place} to the magistrate, {year}: 'My brother came home from the Smiling Yards with the strength of a bull and a smile on his face. He smiled while he cried. He smiled while he broke our father's arm, not meaning to. He smiled in his open coffin. The Yards paid us 30 crowns. I want to know who else they bought. The Yards are at {lead}.'" },
    { depth: "sub", about: "sub:erased_century", source: "archive", bias: "official", reliable: false, points: "site:tablet_isle", who: "Harbour court notice", text: "Notice of the harbour court of {place}, nailed to the customs house, {year}: 'The so-called black tablets are a hoax of pirates and seditionists. Possession of a rubbing, a copy or a translation is punishable by death. Possession of a scholar's notes: ten years in the pits. Informers receive one tenth of the guilty party's goods. The beach at {lead} is closed to all boats.'" },
    { depth: "sub", about: "sub:stone_mines", source: "oral", bias: "true", reliable: true, points: "sub:stone_mines", who: "Pit company price list, annotated by {survivor}", text: "Price list of the Grey Flats Company, pinned in the hiring shed at {place}, {year}: 'Island labour, sound, per head: 18 crowns. With fingers missing: 11. Overseers: ordinary men only, since a gifted man goes weak as a kitten beside the stone. Whips supplied; replacement whips charged to wages. The Company is not responsible for workers lost to the tide.' Pencilled under it by {survivor}: '200 of us to a flat. Go to {lead} and count the graves.'" },
    { depth: "sub", about: "sub:nearest_heir", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "A noble household book", text: "Household book of a noble house of {place}, {year}, kept by the steward: 'Present at the death of the Lady: her three sons, her sister, two physicians and a cook (since dismissed). Candles: 40. Knives taken from guests at the door: 11. The fruit regrew in the kitchen, in the onion basket. Its eater is not named in this book.' The book was sold at auction to {lead}." },
    { depth: "sub", about: "sub:deepfolk", source: "traveller", bias: "garbled", reliable: "partial", who: "A ship's surgeon, anchored off the reef", text: "Journal of a ship's surgeon, anchored off the reef at {place}, {year}: 'The fish-people sang to us from the reef for an hour at dusk. Our eater, a gunner of twenty years' service, wept and would not say why. Afterwards the gunner told me the song was known by heart, every word, though nobody aboard had ever heard it. The gunner has asked to be put ashore and left there.'" },
    { depth: "sub", about: "sub:treasure_hunt", source: "oral", bias: "exaggerated", reliable: "partial", who: "A fishwife of {place}, at the hanging", text: "Told by a fishwife of {place} who stood in the front row at the hanging in {year}: 'Sixty years old and laughing on the scaffold. Someone shouted, where is the gold? He said the gold was the easy part, and called out a page number in the navy's fruit catalogue. Then the rope went. The navy burned that page the same week. By the next spring 300 of our young ones had gone to sea, my two among them. One came back.'" },
    { depth: "sub", about: "sub:awakened", source: "archive", bias: "official", reliable: "partial", who: "Admiralty standing order 88, signed {official}", text: "Standing order of the Admiralty, number 88, {year}, signed by {official}: 'Awakened eaters, meaning those whose gift has spread into the land around them, are to be treated as natural disasters. No arrest is to be attempted. Evacuate to a distance of five miles and report. The harbour at {place} is to stay closed until it is no longer made of rubber.'" },
    { depth: "site", about: "site:census", source: "library", bias: "true", reliable: true, who: "Library notice, signed by {investigator}", text: "Rules for readers of the Living Census, posted at the library door in {place}, {year}, signed by {investigator}, duty cataloguer: '1. One hour, gloves, a cataloguer present. 2. No ink within ten paces. 3. Do not read ahead of the last filled page. 4. A reader who finds their own name on a new page is to close the book and report to the duty officer, not to the harbour. 5. Readers are asked to stop asking who writes the new pages. We do not know either.'" },
    { depth: "site", about: "site:rot_orchard", source: "traveller", bias: "true", reliable: "partial", who: "Navy harvest book, grey island station", text: "Harvest book of the navy station on the grey island 60 miles out of {place}, kept by the station sergeant, {year}: 'Liar's Orchard, 30 trees, yearly count. True fruit taken: 0. Pulp: about 900, burned. Birds dead under the trees: not counted.' The first page of the book, two hundred years older, reads: 'True fruit taken: 1. Sent to the vault.' The entries between show one true fruit a year for 160 years, then none." },
  ],
};
