// The Long Sight: a prescience substance from one desert, and the empire, guild and sisterhood built on it.
export default {
  id: "long_sight",
  name: "The Long Sight",
  family: "power",
  pitch: "A dust found only in one deadly desert lengthens life and lets its users see possible futures. Every throne, guild and navigator depends on it. The desert people who live on top of it have been waiting a long time for their turn.",
  slots: ["economy-resource", "state-control", "power-access", "ecology"],
  tone: ["grim", "mythic"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "world",
  genres: ["fantasy", "flintlock", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "machine_liturgy", w: 2.5 }, { id: "glyphwright_science", w: 2.5 }, { id: "arithmetic_of_ages", w: 2 }, { id: "strewn_sky", w: 1.5 }],

  power: {
    name: "the long sight", user: "seer", users: "seers",
    taught: "The amber, a dust mined only in the deep desert, lengthens life and opens the mind to the roads ahead. Dose, discipline and blood decide how far a seer sees.",
    rules: ["Once taken, the amber cannot be given up; withdrawal kills within the month.", "A seer's eyes stain a deep blue that never fades.", "Futures are likelihoods, not certainties, and two seers cloud each other's sight.", "No seer sees past their own death, or clearly around a child of the sand."],
    forbidden: "Building a machine that thinks.",
  },

  cast: [
    { role: "investigator", n: "a reckoner of the imperial treasury, trained from the age of five to count, sent to audit the amber harvest", home: "capital", stance: "Trusts only figures, and the figures from the desert no longer add up." },
    { role: "official", n: "a harvest-master of the pilots' guild in the amber desert", home: "desert", stance: "Believes the amber is endless and the road is wise, and that doubt is bad for prices." },
    { role: "believer", n: "a veiled sister who keeps the bloodline ledgers in the field", home: "capital", stance: "Has served the breeding plan since childhood and now fears what it is about to produce." },
    { role: "survivor", n: "a sand-folk water-keeper whose family garden was salted by the guild", home: "desert", stance: "Wants the harvest ended and the desert green again, whatever the empire pays." },
  ],

  truths: [
    { id: "sight_trap", n: "The sight is a cage", d: "Seeing the future fixes it in place. For a thousand years the seers, through the blue-eyed emperors and the pilots' guild, have steered the world down one narrow road to avoid an extinction only they can see; nearly every other road ends in ash. The price is endless tyranny: cities refused passage, heirs removed, machines destroyed. People will only have free will again when the sight is gone.", tags: ["truth:sight_cage"],
      known: [
        "The pilots' guild refuses passage to some cities 'by order of the road', and every ruler in the palace gallery for a thousand years has had blue eyes. The court primer says the seers only advise and rulers may ignore them.",
        "A free city refused passage for 14 years has starved, and nobody can say what it did wrong. A wrecked thinking machine in the dunes still whispers a year at night, the same year the seers are said to fear.",
        "A seer's memoir says almost every possible road ends in ash, and that the seers hold the world to the one road that does not, whatever it costs. The machine's drum has one road scratched out by a seer's blue thumb.",
        "Confirmed: the sight fixes the future. For a thousand years the seers have steered the world down one narrow road to avoid an extinction, and every refusal, purge and crusade was part of it. Free will returns only when the sight is gone.",
      ] },
    { id: "living_dust", n: "The amber is alive", d: "The amber is the spawn of the desert's great burrowers, and the burrowers made the desert: the land was green, with rivers and orchards, until they came. The guild's harvest is the slow murder of their young. In answer the burrowers spread the sand a mile a year to make room for more, and every throne pays the harvesters to keep digging.", tags: ["truth:living_amber"],
      known: [
        "The harvest field moves a mile further out every year, and the sand moves a mile further in over the old farms. The guild's survey calls the amber an inexhaustible mineral and the moving sand an accident of weather.",
        "The sand-folk say the amber is the breath of the little worms and the great burrowers are its mothers. Burrowers rise where the harvest is heaviest, and the richest seams lie among the teeth of dead burrowers.",
        "Murals in a sealed cistern show the desert as a green land with 40 walled orchards, until the burrowers came from the south and the green died behind them like a wave. The paint is mixed with crushed amber.",
        "Confirmed: the amber is the burrowers' young, and the burrowers made the desert to raise them. Every ounce harvested is a dead child, and the mothers answer by spreading the sand a mile a year. The empire keeps buying.",
      ] },
    { id: "breeding_plan", n: "The breeding plan wants a god", d: "A veiled sisterhood has matched noble bloodlines like horses for a thousand years to breed one person who will see every road at once. That person is about to be born a generation early and in the wrong family, because one mother refused the match the sisters chose for her. No seer can see past the child, and the sisters no longer control what they made.", tags: ["truth:bred_seer"],
      known: [
        "The veiled sisters say they are a teaching order for orphans, but they keep the birth registers of every great house, and court gossip says they choose the marriages as well.",
        "A vault under a convent holds 212 ledgers of noble marriages going back a thousand years, with notes on eye colour, sight and temper. The last page names one pairing and says in red ink: too early.",
        "A sister's letter says one mother refused her match and bore a son twenty years early, and that no seer can see past him. A desert prophecy of a deliverer was carved with the sisters' grammar and sealed with their seal.",
        "Confirmed: the sisterhood has bred the great houses for a thousand years to make one mind that sees every road. The child is coming early, in the wrong house, and nobody, the sisters included, can see what follows.",
      ] },
  ],

  tags: ["farsight"],

  subthemes: [
    { id: "poisoned_fief", n: "The Poisoned Fief", d: "The throne has granted the amber desert to a noble house as a reward. Every court knows it is a trap, including the house that accepted it.", w: 1.3, req: { any: ["monarchy", "gov:feudal", "gov:empire", "dynastic"] }, mods: [["desert", 2], ["hierarchical", 1.5]], tags: ["theme:poisoned_fief"] },
    { id: "planted_prophecy", n: "The Planted Prophecy", d: "The sand-folk await a deliverer from beyond the dunes. Veiled women planted the prophecy among them centuries ago, so that someone could use it to command them later.", w: 1.1, req: { any: ["desert", "nomadic", "desert_wanderers"] }, mods: [["pious", 1.5]], truthLink: "breeding_plan", tags: ["theme:planted_prophecy"] },
    { id: "water_discipline", n: "The Water Discipline", d: "Every drop is reclaimed. The dead are rendered for their water, debts are paid in measured cups, and to weep at a funeral is the greatest gift there is.", w: 1.2, req: { any: ["desert", "hot", "desert_wanderers"] }, tags: ["theme:water_discipline"] },
    { id: "greening", n: "The Greening Dream", d: "For generations the sand-folk have filled hidden cisterns and planted hardy shrubs in secret valleys. If the desert turns green, the amber ends.", w: 1, req: { any: ["desert", "desert_wanderers", "hot"] }, truthLink: "living_dust", tags: ["theme:greening"], mark: { kind: "zone", n: "Hidden gardens", color: "#6a9a4a", size: [1, 2], where: "desert" } },
    { id: "fog_pilots", n: "The Fog-Pilots' Monopoly", d: "Only the sighted can steer through the great sea-fogs. The pilots' guild sets the price of every crossing and holds every throne hostage to it.", w: 1.2, req: { any: ["has:port", "seafaring", "coastal", "mercantile"] }, tags: ["theme:fog_pilots"] },
    { id: "machine_war", n: "The Machine Crusade", d: "Long ago a holy war destroyed every thinking machine. Cults still keep forbidden gears in cellars, and the inquisitors still hunt them.", w: 0.9, mods: [["zealous", 2], ["pious", 1.5], ["near:ruins", 1.5]], truthLink: "sight_trap", tags: ["theme:machine_war"] },
    { id: "reckoners", n: "The Reckoners", d: "With machines forbidden, children are trained from the age of five to be living calculators. The best can add an empire's harvest in their heads; few remember their mothers' faces.", w: 1, req: { any: ["academies", "scholarly", "gov:empire", "realm:large"] }, tags: ["theme:reckoners"] },
    { id: "deliverer_war", n: "The Deliverer's War", d: "A deliverer's followers are sweeping the world in his name. He has begged them to stop; they say this is how he wants them to understand him.", w: 0.8, mods: [["zealous", 2], ["militant", 2], ["desert", 1.5]], truthLink: "sight_trap", tags: ["theme:deliverer_war"] },
    { id: "seer_emperor", n: "The Seer-Emperor", d: "A blue-eyed ruler follows the one safe future and has done monstrous things to stay on it. The court lives in terror of a man who already knows what they will say.", w: 0.7, req: { any: ["autocracy", "gov:empire", "gov:absolute"] }, truthLink: "sight_trap", tags: ["theme:seer_emperor"] },
    { id: "face_thieves", n: "The Face-Thieves", d: "Shapechanging assassins serve whoever pays. An ambassador attended dinner at court last night, though his body had been in the river for days.", w: 0.8, req: { any: ["spy_network", "hierarchical", "autocracy"] }, mods: [["spy_network", 2]], tags: ["theme:face_thieves"] },
  ],

  sites: [
    { id: "sealed_cistern", n: "The Sealed Cistern of $", kind: "ruin", where: "desert", truthLink: "living_dust", d: "Watertight doors in a cliff face, and inside, murals of a green desert.",
      layers: {
        surface: { n: "Wax-sealed doors", text: "Watertight doors in a cliff face near {place}, sealed with wax older than the empire. The sand-folk will not open them and will not say why. A guild survey of {year} marked them 'empty storage' and never tried the seals." },
        study: { n: "The green murals", text: "Inside, murals show the desert as a green land of rivers and 40 walled orchards. The people in them wear the sand-folk's dress and carry the sand-folk's water-cups. The paint is mixed with crushed amber, which has kept it bright." },
        dig: { n: "The wave of sand", text: "In the deepest chamber a mural shows the burrowers arriving from the south and the green dying behind them like a wave. Beneath it sits a sealed pot of seed grain, still dry. The sand-folk keep a copy of these pictures at {lead}.", points: "cast:survivor" },
        revelation: { n: "The desert was made", text: "This was a green country until the burrowers came and turned it to sand for their young. The amber is their young. The guild's harvesters kill thousands a week, and the mothers answer by spreading the sand a mile a year. The empire's maps still call the desert eternal." },
      } },
    { id: "tooth_field", n: "The Tooth Field of $", kind: "dig", where: "desert", d: "A forest of pale spires on the sand that are really teeth, each as tall as a tower.",
      layers: {
        surface: { n: "The stone forest", text: "Pale spires stand on the sand near {place}, the caravans' stone forest. Caravans never camp there. Harvest crews do, and pay the guild 20 crowns a season for the right. They come out richer and quieter." },
        study: { n: "Teeth", text: "The spires are teeth, each the height of a tower, worn smooth by centuries of wind. A treasury reckoner counted 600 of them in curved rows, like a jaw a mile across. The rows are not all the same age." },
        dig: { n: "Amber in the roots", text: "Among the roots lie the richest amber seams in the desert, and the dry shed skins of huge larvae, each as long as a barge. Harvest tallies show this field yields three times any other. The guild's yield books are kept at {lead}.", points: "archive" },
        revelation: { n: "A graveyard", text: "The burrowers come here to die, and their rotting bodies feed the young that become the amber. The harvesters are digging in a graveyard and a nursery at once. The guild has known since the field was opened, and pays the crews extra to keep quiet about the skins." },
      } },
    { id: "whispering_engine", n: "The Whispering Engine of $", kind: "ruin", where: "remote", truthLink: "sight_trap", d: "A wrecked thinking machine half-buried in a dune that still whispers at night.",
      layers: {
        surface: { n: "The brass heap", text: "A heap of brass and glass lies half-buried in a dune near {place}. Every caravan route bends two miles around it. The inquisition's charts mark it as destroyed, with a date 900 years ago." },
        study: { n: "The night voice", text: "Lying beside it at night, a listener hears it speak from midnight to the third hour: numbers, then names, then numbers again. A reckoner who listened in {year} wrote down 300 names. Every one was a ruler, past or still to come." },
        dig: { n: "The list of futures", text: "Inside is a lattice of fine wire, still warm, and a brass drum stamped with calculated futures. All of them end in the same year. One road is scratched out by hand, with a seer's blue thumbprint on the brass. The inquisition's file is in {lead}.", points: "archive" },
        revelation: { n: "Two kinds of prophet", text: "Before the seers, machines saw ahead, and they saw the same ending. The machines would have told everyone. The seers chose to steer the world in secret, and the crusade they preached destroyed every machine that could contradict them. The thumbprint on the drum is the first seer-emperor's." },
      } },
    { id: "genealogy_vault", n: "The Genealogy Vault of $", kind: "ruin", where: "capital", truthLink: "breeding_plan", d: "A sealed library beneath a convent, holding nothing but ledgers of marriages.",
      layers: {
        surface: { n: "Bare shelves", text: "A sealed library under the convent at {place}. The shelves are bare but for heavy ledgers, 212 of them, bound in undyed leather. Two veiled sisters guard it in turn, day and night, and neither carries a key." },
        study: { n: "Houses like horses", text: "The ledgers are genealogies: noble houses matched like horses, a thousand years deep. Every marriage of every great house is entered with notes on eye colour, sight and temper. Some matches are crossed out and replaced the next year by better ones." },
        dig: { n: "Too early", text: "The last page holds a single pairing, circled, with next year's date and a note in red: 'too early'. Letters tucked into the back cover come from a sister in the field, and grow more frightened as they go. The field sister's home convent is at {lead}.", points: "cast:believer" },
        revelation: { n: "The bred mind", text: "For a thousand years the veiled sisters have bred the great houses toward one person who will see every possible future at once. One mother refused the match she was given, and the child is coming early, in the wrong house. No seer can see past it. The sisters no longer control their plan." },
      } },
    { id: "prophecy_stone", n: "The Deliverer's Stone of $", kind: "shrine", where: "desert", d: "A desert shrine carved with the prophecy of a deliverer from beyond the sands.",
      layers: {
        surface: { n: "The deliverer's verse", text: "A desert shrine near {place} carries a carved prophecy of a deliverer who will come from beyond the dunes. Sand-folk pilgrims leave a cup of water on the step at every new moon. The guild's harvest-masters drink it, and nobody stops them." },
        study: { n: "Wrong grammar", text: "The prophecy is carved in the sand-folk's tongue, but its grammar is a foreign scholar's, and its 12 lines rhyme only in the court language. The chisel marks were made with a fine steel the sand-folk never had." },
        dig: { n: "The sealed jar", text: "Behind the stone sits a sealed jar with written instructions: 'To be revealed when the chosen line arrives.' The seal is the veiled sisterhood's, and the ink matches their ledgers. The jar's twin is listed in the inventory of {lead}.", points: "site:genealogy_vault" },
        revelation: { n: "A planted prophecy", text: "The veiled sisters planted this prophecy among the sand-folk centuries ago, so that a ruler from their bred line could one day use it to take command of the desert and its riders. The sand-folk have waited, prayed and died for it. The jar's instructions name the heir who is meant to come." },
      } },
  ],

  beings: [
    { id: "great_burrower", n: "Great burrower", kind: "beast", d: "A sand-worm the length of a town, drawn by rhythm. The sand-folk ride them; the harvesters flee them; nobody has ever killed one and lived to boast.", danger: 3, biomes: ["desert", "colddesert", "badlands"], look: { size: 120, group: [1, 1], move: "solo", speed: 25, col: "#a08a60", col2: "#e0c890", body: "serpent", active: "any", visible: true } },
    { id: "sand_krill", n: "Sand-krill", kind: "insect", d: "Tiny pale creatures that swarm under the dunes in their millions, and that the harvesters crush by the ton without a second look.", danger: 0, biomes: ["desert", "badlands"], look: { size: 0.05, group: [100, 1000], move: "swarm", speed: 1, col: "#c08a3a", col2: "#e8d0a0", body: "insect", active: "night", visible: false } },
    { id: "blue_fox", n: "Blue-eyed fox", kind: "predator", d: "A desert fox that licks amber dust from the dunes. Its eyes are stained blue, and it always seems to know where the hunter will step.", danger: 0, biomes: ["desert", "badlands", "colddesert"], look: { size: 0.6, group: [1, 2], move: "pair", speed: 40, col: "#d0b080", col2: "#3050a0", body: "quad", active: "night", visible: true } },
  ],

  techs: [
    { id: "ls_ritual_amber", n: "Rite-amber", field: "medicine", level: 1, d: "The sand-folk take small doses at their rites and see the next day's weather, and sometimes more." },
    { id: "ls_moisture_suit", n: "Moisture-suits", field: "engineering", level: 2, d: "Close-fitting suits that reclaim sweat and breath, so a walker loses a cup of water a day." },
    { id: "ls_reckoning", n: "The reckoners' art", field: "writing", level: 3, d: "Human calculators trained from childhood to do the work of forbidden machines." },
    { id: "ls_fog_piloting", n: "Fog-piloting", field: "navigation", level: 3, d: "Dosed seers steer whole fleets blind through the great sea-fogs." },
    { id: "ls_slow_shields", n: "Slow-shields", field: "warfare", level: 4, d: "Personal wards that stop anything moving fast. Only a slow blade gets through, so duels return to knives." },
    { id: "ls_bloodline_ledgers", n: "The bloodline ledgers", field: "natural_philosophy", level: 5, d: "Heredity tabulated across a thousand years, and with it the power to breed a mind." },
  ],

  units: [
    { id: "ls_worm_riders", n: "Burrower-riders", role: "beast", mounted: 1, wpn: "spear", kit: "robe", ranks: 2, gap: 6, size: 30, w: 0.3, req: "desert", mods: [["desert_wanderers", 10], ["theme:planted_prophecy", 4]] },
    { id: "ls_knife_duelists", n: "Shielded knife-fighters", role: "infantry", wpn: "sword", kit: "light", ranks: 3, gap: 1.5, size: 80, w: 0.6, mods: [["theme:poisoned_fief", 3], ["hierarchical", 1.5]] },
  ],

  govs: [
    { id: "ls_great_houses", n: "Imperium of Great Houses", d: "An emperor rules by balancing great houses, each holding its fief at the throne's pleasure, and every one of them begging the pilots' guild for passage.", tags: ["gov:ls_great_houses", "monarchy", "autocracy"], w: 0.5, req: { any: ["realm:large", "realm:vast"] }, forms: ["Imperium of $", "Throne of $", "High Imperium of $"], ruler: "Emperor", mods: [["hierarchical", 2], ["dynastic", 1.5]] },
  ],

  faiths: [
    { id: "ls_concord", n: "The Concord", d: "A compromise faith written by a council of every church to keep peace between the great houses. It forbids the thinking machine above all other sins.", tags: ["faith:ls_concord"], w: 0.8, names: ["The Concord of $", "The Bound Scriptures", "The Common Lamp"], mods: [["tolerant", 2], ["gov:empire", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "The amber sea", color: "#c8a050", size: [3, 6], count: [1, 1], where: "desert", d: "The deep desert where the amber is mined and the burrowers rise." },
  ],

  storylines: [
    { id: "ls_fief", n: "The Gift of the Desert", scale: "realm", anchor: "realm", w: 1.3, req: ["farsight", { any: ["monarchy", "dynastic", "gov:empire", "gov:feudal"] }],
      stages: {
        start: { h: "{realm} is granted the amber fief", b: "By decree, {ruler} has been given the amber desert to govern, taken from an older house. Every court knows it is a gift and a trap.", wait: [3, 8], fx: { prestige: 6, treasury: 60 }, next: [{ to: "betrayed", w: 2 }, { to: "sand_alliance", w: 1, mods: [["ruler:just", 2], ["egalitarian", 1.5]] }] },
        sand_alliance: { h: "{ruler} makes peace with the sand-folk", b: "Against all advice, {ruler} sat down at the sand-folk's water and learned their names. The amber flows, and the old house watches.", wait: [4, 10], next: [{ to: "betrayed", w: 1 }, { to: "held", w: 1 }] },
        betrayed: { h: "The old house strikes at {realm}", b: "The old house came back by night with soldiers in borrowed colours and face-thieves in the kitchens. The palace of {capital} burned, and {person}, the young heir, fled into the deep desert.", wait: [3, 8], fx: { stability: -15 }, next: [{ to: "deliverer", w: 1, mods: [["theme:planted_prophecy", 3]] }, { to: "lost_in_sand", w: 1 }] },
        deliverer: { h: "The sand-folk hail {person} as the deliverer", b: "The heir who fled into the desert has come back at the head of the burrower-riders, and the sand-folk sing the old prophecy. Nobody asks who wrote it.", fx: { revolt: true, prestige: 10 }, end: true },
        lost_in_sand: { h: "No word from the deep desert", b: "The heir of {realm} was last seen walking into the sand. The old house governs the amber now, and the price has doubled.", fx: { treasury: -40, stability: -5 }, end: true },
        held: { h: "{realm} holds the amber", b: "The old house's plot was found out in time. {realm} holds the desert, the amber flows, and every throne in the world now writes to {capital} first.", fx: { treasury: 80, prestige: 8 }, end: true },
      } },
    { id: "ls_blue_child", n: "The Blue-Eyed Child of {place}", scale: "local", anchor: "town", w: 1.2, req: "farsight",
      stages: {
        start: { h: "A child of {place} is born with blue eyes", b: "{person}, born to a harvester family in {place}, came into the world with eyes already stained the deep blue of the amber. No dose was ever given.", wait: [3, 8], next: [{ to: "sisters", w: 2 }, { to: "guild", w: 1, mods: [["theme:fog_pilots", 3], ["has:port", 1.5]] }] },
        sisters: { h: "Veiled women come for {person}", b: "Two sisters of the veiled order arrived in {place} with gold for the parents and a sealed letter. The parents have not opened it.", wait: [2, 6], next: [{ to: "taken", w: 1 }, { to: "hidden", w: 1, mods: [["hospitable", 1.5]] }] },
        guild: { h: "The fog-pilots take {person}", b: "The pilots' guild paid a fortune for the blue-eyed child of {place}. In ten years {person} will steer fleets; in thirty, {person} will be so changed by the amber that they can never leave the pilot's tank.", fx: { treasury: 40 }, end: true },
        taken: { h: "{person} is taken to the convent", b: "The veiled sisters took the child of {place} away in a closed carriage. The parents bought a farm with the gold and do not speak of it.", wait: [6, 16], next: [{ to: "sees_all", w: 1 }, { to: "breaks", w: 1 }] },
        hidden: { h: "{place} hides its blue-eyed child", b: "The neighbours swore the child died of fever. {person2}, a harvester, has taken {person} into the deep desert.", wait: [6, 16], next: [{ to: "sees_all", w: 1 }, { to: "breaks", w: 1 }] },
        sees_all: { h: "{person} sees every road", b: "The child of {place} has seen every road the world could take, and has stopped speaking. Courts everywhere have quietly begun making plans that leave {person} out.", fx: { discovery: "natural_philosophy", stability: -4, prestige: 8 }, end: true },
        breaks: { h: "The sight breaks {person}", b: "The child of {place} saw too much too young, and screams at the sight of doors. The sisters have closed the ledger on that line.", fx: { unrest: 4 }, end: true },
      } },
    { id: "ls_greening", n: "The Green Line at {place}", scale: "local", anchor: "town", w: 1, req: ["farsight", { any: ["desert", "hot", "desert_wanderers"] }],
      stages: {
        start: { h: "Shrubs grow in a hidden valley near {place}", b: "Ranks of hardy shrubs have appeared in a valley near {place}, watered from cisterns the sand-folk have filled for generations.", wait: [4, 10], next: [{ to: "discovered", w: 2 }, { to: "spreads", w: 1 }] },
        discovered: { h: "A harvest-master finds the gardens of {place}", b: "{person}, a harvest-master, has found the hidden gardens. The guild wants them salted; the sand-folk want the harvest-master dead.", wait: [2, 5], next: [{ to: "salted", w: 1, mods: [["harsh_law", 2]] }, { to: "spreads", w: 1 }] },
        spreads: { h: "The green spreads from {place}", b: "The green line creeps a mile a year. The burrowers turn aside from it, and the amber yields of the region are falling.", wait: [6, 14], fx: { growth: 0.002 }, next: [{ to: "rain", w: 1 }, { to: "burrowers_rise", w: 1 }] },
        rain: { h: "Rain falls on {place}", b: "For the first time in living memory rain fell on {place}. The amber harvest of the region failed, and the guild has sworn revenge.", fx: { growth: 0.003, treasury: -40, stability: 3 }, end: true },
        burrowers_rise: { h: "The burrowers rise under the gardens", b: "A burrower the size of a hill rose beneath the gardens of {place} and swallowed them, and half the town with them.", fx: { pop: 0.85, unrest: 12 }, end: true },
        salted: { h: "The gardens of {place} are salted", b: "Guild soldiers poured salt into the cisterns of {place}. The sand-folk have gone deeper into the desert, and their songs have changed.", fx: { unrest: 10, treasury: 20 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "Imperial pharmacopoeia", text: "From the imperial pharmacopoeia, {year} edition, entry 'Amber': 'A golden dust mined only in the deep desert. Taken daily, it lengthens life by half and sharpens the mind until the taker sees the likely roads ahead. The eyes stain blue within the year. Withdrawal is fatal within the month. Dose accordingly. Price at the exchange of {place} this season: 40 crowns the ounce.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "A sand-folk mother, noted by {investigator}", text: "Said by a sand-folk mother to her child at a water-rite near {place}, as noted by {investigator} in {year}: 'No seer can see a child born of the sand. Their blue eyes go cloudy when they look at us, like a man staring at the sun. That is why the guild hates us, little one, and why it pays 10 crowns for each of our names.'" },
    { depth: "lore", about: "power", source: "temple", bias: "pious", reliable: "partial", points: "library", who: "The Concord scriptures, temple copy", text: "From the Concord scriptures, the ninth prohibition, in the temple copy at {place}, {year}: 'No hand shall build a reckoner of wheels and wire, for judgement belongs to the living.' In the margin, a gloss in a later hand: 'Then what are the children in the counting schools?' The reckoners' school is two streets away and trains 40 children a year. The temple has since bought a clean copy. The annotated one was sent to {lead}." },
    { depth: "core", about: "truth:sight_trap", source: "person", bias: "true", reliable: true, plain: true, who: "A court seer's unpublished memoir", text: "From the unpublished memoir of a seer of the imperial court, found in {year} among the papers of {official}: 'I have seen nine thousand roads, and all but one end in ash: no people, no cities. The sight holds the world to the one road that does not. Every refused passage and every dead heir is that road. I am sorry for what it costs you. I am not sorry enough to stop.'" },
    { depth: "core", about: "truth:sight_trap", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "Pilots' guild price list", text: "Pilots' guild price list for {year}, posted at the harbour of {place}: 'Passage to the eastern ports: 30 crowns. Passage to the southern isles: 45 crowns. Passage to the free cities: refused.' A note in the margin, in a harvest-master's hand: 'by order of the road.' The free cities have had no ship for 14 years. The guild's register of refusals is kept in {lead}." },
    { depth: "core", about: "truth:sight_trap", source: "heretic", bias: "heretic", reliable: "partial", points: "site:whispering_engine", who: "A machine-cult pamphlet", text: "Pamphlet of a machine-cult, left in a reading room at {place} in {year}: 'Every tyrant of the last thousand years had blue eyes. Count the portraits in the palace gallery: 31 rulers, 31 pairs of blue eyes. Ask who wanted it that way. Then go to {lead}, lie beside the old machine at night, and listen to what it says about the year.'" },
    { depth: "core", about: "truth:sight_trap", source: "library", bias: "official", reliable: false, who: "Court primer 'On the Sight'", text: "From 'On the Sight', a primer for young courtiers of {realm}, {year}, chapter 1: 'The sight serves free choice. The seers only advise, and every ruler is at liberty to ignore them. That rulers seldom do is a tribute to the quality of the advice. The guild's refusals of passage are a matter of weather and are not open to appeal.'" },
    { depth: "core", about: "truth:sight_trap", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, mayor of a free city", text: "Letter of {person}, the last mayor of a free city, to the emperor, {year}: 'For 14 years no pilot will bring a ship to us. Our grain came by sea. We have eaten the horses and the seed corn, and 3,000 of our people are buried outside the walls. Your seers say it is the road. I have asked what we did. Nobody can tell me. Only that the road does not have us on it.'" },
    { depth: "core", about: "truth:living_dust", source: "ruin", bias: "true", reliable: true, plain: true, who: "The cistern mural, copied by {investigator}", text: "Painted under the last mural in the sealed cistern near {place}, copied by {investigator} in {year}: 'The great worms came from the south. The rivers went into the ground, the orchards became sand, and the sand became the worms' nursery. The golden dust is their young. Whoever digs it kills them, and the mothers will take more land for every child taken.' The mural shows 40 orchards. Today there are none." },
    { depth: "core", about: "truth:living_dust", source: "oral", bias: "true", reliable: "partial", points: "site:sealed_cistern", who: "{survivor}, sand-folk water-keeper", text: "Told by {survivor}, a sand-folk water-keeper, to a guild clerk at {place}, {year}: 'The amber is the breath of the little worms, and the great worms are its mothers. Kill the mothers and the amber stops. Feed them and the world stops. You dig up a thousand of their children every week and wonder why the sand keeps coming. The mothers are making room. The pictures of how it was are at {lead}.'" },
    { depth: "core", about: "truth:living_dust", source: "person", bias: "exaggerated", reliable: "partial", cost: true, who: "{person}, harvester", text: "Diary of {person}, a harvester of {place}, {year}: 'Every year the harvest field is a mile further out, and every year the sand is a mile further in. The old maps show farms where I dig. One is the farm my family lost; I found its well-head this morning, 9 feet down. Last night a burrower took the crawler and the four men on it, my brother among them. The guild has docked our pay for the crawler.'" },
    { depth: "core", about: "truth:living_dust", source: "traveller", bias: "garbled", reliable: "partial", points: "site:tooth_field", who: "A spice-trader with a harvest convoy", text: "Journal of a spice-trader travelling with a harvest convoy near {place}, {year}: 'I saw a burrower rise beyond the rock haven, a quarter-mile of it. The harvesters say the thump of their crawlers draws it. The sand-folk say it is drawn by grief, because we had dug out a fresh seam that morning. The convoy lost two crawlers. Tomorrow we go on to {lead}, where the harvest is richest.'" },
    { depth: "core", about: "truth:living_dust", source: "library", bias: "official", reliable: false, who: "{official}, harvest-master", text: "From the guild survey 'The Amber Reserves of {realm}', {year}, signed by {official}, harvest-master: 'The amber is a mineral laid down in the age of the ancients. It is inexhaustible over any span that matters to the throne. Reports linking the harvest to the movement of the sand are unscientific. The sand moves because it is sand. Yields for the year are up by one part in twelve.'" },
    { depth: "core", about: "truth:breeding_plan", source: "archive", bias: "redacted", reliable: true, points: "site:genealogy_vault", who: "A genealogy ledger, recovered by {investigator}", text: "Last page of a genealogy ledger, recovered by {investigator} in {year}: 'House of the river, daughter; house of the falcon, son. Pairing for the next generation, to be wed in the spring.' Under it, in red ink and a different hand: 'TOO EARLY. WRONG MOTHER. ADJUST.' The spine is numbered 212. The rest of the series is shelved in {lead}." },
    { depth: "core", about: "truth:breeding_plan", source: "person", bias: "true", reliable: "partial", plain: true, who: "{believer}, veiled sister, to the abbess", text: "Letter from {believer}, a veiled sister, to the abbess, {year}: 'Mother, I will say it plainly, since we may not have time. For a thousand years we have matched the great houses like horses to breed one mind that sees every road at once. The girl of the river house disobeyed. She bore a son and not the daughter we asked of her, and twenty years early. I cannot see past the boy. None of us can.'" },
    { depth: "core", about: "truth:breeding_plan", source: "heretic", bias: "exaggerated", reliable: "partial", who: "Handbill on a convent gate", text: "Handbill posted on the convent gate at {place} in {year}: 'The veiled sisters choose your brides, your husbands and your heirs. They have done it for 1,000 years. Your mother's marriage was on their list. So was her mother's. Whose child are you, really? Ask the sisters to show you the ledgers. Ask why the matchmakers of every great house draw a pension from the convent.'" },
    { depth: "core", about: "truth:breeding_plan", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "A lamp-seller, to {investigator}", text: "Told by a lamp-seller of {place} to {investigator}, {year}: 'My grandmother, {person}, ran away from the veiled sisters at seventeen. The convent's list had paired our family with a lord nobody had met. The sisters caught up in the next town. {person} came home a year later without the first child, and never said where it went. Every spring until the end there was a lamp lit for it in the window. That lamp is why I sell lamps.'" },
    { depth: "core", about: "truth:breeding_plan", source: "temple", bias: "official", reliable: false, who: "Rule of the Veiled Sisterhood", text: "From the rule of the Veiled Sisterhood, as read to novices at {place}, {year}: 'The Sisterhood is a teaching order devoted to orphans and to the discipline of the body. Sisters keep the birth registers of the great houses as a service to the throne, and for no other purpose. Tales of a breeding plan are idle court gossip. A sister who repeats them fasts for 3 days.'" },
    { depth: "sub", about: "sub:water_discipline", source: "oral", bias: "true", reliable: true, who: "{survivor}, water-keeper, cistern book", text: "Cistern book of {place}, kept by {survivor}, water-keeper, {year}: 'Funeral of my uncle. Rendered: 31 cups. To the widow: 27. To the guild clerk, for water he drank at the graveside without asking: 4, entered as his debt. Tears shed at the grave: by me and by the widow, none by the clerk. Among us a tear is water given to the dead and the dearest gift there is. The clerk laughed. His debt stands.'" },
    { depth: "sub", about: "sub:fog_pilots", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A passenger's letter home", text: "From a passenger's letter home, written aboard a guild ship in the fogs off {place}, {year}: 'I saw our fog-pilot once, through the window of the tank on the upper deck. The pilot had no legs any more, and the eyes were all blue, no white at all, and smiled at me as if knowing my name. We crossed 400 miles of fog in two days without a single star. I paid 60 crowns for the privilege.'" },
    { depth: "sub", about: "sub:machine_war", source: "library", bias: "propaganda", reliable: false, who: "A Concord schoolbook", text: "From a Concord schoolbook, {year}, lesson 4, read aloud in every school of {realm}: 'The machines were hateful things that enslaved our ancestors. The crusade freed every soul in the world, and nothing of value was lost. Children who find gears, wires or glass plates in the sand must give them to the inquisitor at once and wash their hands three times.'" },
    { depth: "sub", about: "sub:reckoners", source: "person", bias: "true", reliable: "partial", points: "cast:investigator", who: "{person}, a weaver, to the reckoners' school", text: "Letter from {person}, a weaver of {place}, to the reckoners' school, {year}: 'My son was taken for a reckoner at five. At twelve he can add an empire's harvest in his head. At midwinter he could not remember my face without counting it: two eyes, one scar, forty-one years. He asked me to stand still while he did it. The treasury's reckoner, {investigator}, was taken the same way, and lives at {lead}. Ask if it was worth it.'" },
    { depth: "sub", about: "sub:face_thieves", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "Court memorandum, initialled {official}", text: "Court memorandum, palace of {place}, {year}, initialled by {official}: 'The ambassador's body was found in the river this morning, three days dead by the physician's reckoning. The ambassador attended dinner last night as usual, ate the fish, and was charming. No further copies of this note are to be made.' The guest list for that dinner is filed in {lead}." },
    { depth: "sub", about: "sub:poisoned_fief", source: "oral", bias: "exaggerated", reliable: "partial", who: "A foreign envoy, on a court saying", text: "A saying of the court at {place}, written down by a foreign envoy in {year}, with the note 'repeated to me by four separate lords': 'The throne gives the desert to the house it fears most.' The envoy adds that the desert has changed hands nine times in 300 years, and that seven of those nine houses no longer exist." },
    { depth: "site", about: "site:prophecy_stone", source: "traveller", bias: "garbled", reliable: "partial", points: "site:genealogy_vault", who: "A scholar with a sand-folk guide", text: "Journal of a scholar visiting the desert shrine near {place} with a sand-folk guide, {year}: 'The deliverer's verse rhymes in the scholars' tongue, not the sand-folk's: 12 lines, every one ending on a rhyme that only works in the court language. When I said so, my guide walked away and left me one water skin. The convent that keeps the same verse is at {lead}.'" },
    { depth: "site", about: "site:tooth_field", source: "oral", bias: "true", reliable: "partial", who: "A caravan-master, to new drivers", text: "Caravan rule, as told to new drivers by a caravan-master at {place}, {year}: 'Never camp in the stone forest. Those pale spires are teeth, each one a tower high, and the sand under them moves.' The master added that the harvest crews camp there anyway, for the money. Of the 6 crews who wintered there last year, 4 came back, and those 4 paid off their debts to the guild by spring." },
    { depth: "site", about: "site:whispering_engine", source: "ruin", bias: "true", reliable: "partial", points: "archive", who: "{investigator}, after a night in the dunes", text: "Notes of {investigator} after a night beside the brass heap in the dunes near {place}, {year}: 'It whispers from midnight to the third hour. I counted. First numbers, then a list of names, then numbers again. One of the names was the present emperor's. The last number it repeated was a year, 41 years from now. The inquisition's file on this machine is in {lead}.'" },
  ],
};
