// Ore-Burning: swallowed metals burned for power, noble blood, an ash sky and an emperor who never dies.
export default {
  id: "ore_burning",
  name: "Ore-Burning",
  family: "power",
  pitch: "Swallow a flake of the right metal and burn it inside you for strength, sight or the push and pull of iron: a gift that runs in noble blood, under a sky of ash ruled by an emperor who never dies.",
  slots: ["power-access", "economy-resource", "bloodline", "state-control", "apocalypse"],
  tone: ["grim", "heroic"],
  era: ["medieval", "renaissance", "industrial"],
  scale: "regional",
  genres: ["fantasy", "grimdark", "flintlock"],
  w: 1,
  excludes: [],
  pairs: [{ id: "sworn_kindred", w: 2 }, { id: "long_dark", w: 2.5 }, { id: "body_of_the_world", w: 1.5 }, { id: "unremembering", w: 1.5 }],

  power: {
    name: "oreburning", user: "burner", users: "burners",
    taught: "Those born to the gift can swallow a pinch of filed metal and burn it in the belly like a lamp burns oil. Each metal gives one thing: iron pulls, steel pushes, tin sharpens the senses, pewter the body, copper hides, bronze listens, zinc stirs the heart, brass calms it. A second art stores strength in worn metal bands; a third, forbidden, steals a gift with a spike.",
    rules: ["Most burners burn a single metal; a rare few burn them all.", "A burner without metal in the belly is only a person.", "Pushes and pulls run in straight lines, and the heavier side wins.", "The gift wakes only after a brush with death."],
    forbidden: "A noble bedding a serf, which spreads the gift; and driving a spike through a living burner to take theirs.",
  },

  cast: [
    { role: "investigator", n: "a bracelet-archivist, one of the hunted people who store knowledge in metal bands", home: "mountain", stance: "Wants the true record kept and checked, because metal can lie if someone changes it." },
    { role: "official", n: "an ash-priest of the Undying Lord's church, keeper of the metal tables", home: "capital", stance: "Believes the Lord's order is the only thing between the serfs and chaos, and that the old sky is a dangerous fantasy." },
    { role: "believer", n: "a hedge-preacher of the fog lowlands who preaches against the spike", home: "inner", stance: "Holds that the fog and the spike belong to an enemy power, and that no one should ever accept a spike." },
    { role: "survivor", n: "a half-blood serf whose gift woke after a beating, now running a thieves' crew", home: "inner", stance: "Wants the emperor dead and the serfs free, and has not thought much about what comes after." },
  ],

  truths: [
    { id: "two_halves", n: "Two halves of a broken god", d: "The three metal arts come from two powers locked in stalemate: one that keeps and one that unmakes. The spike-art belongs to the unmaker, and it can speak into the mind of anyone who has been spiked; the emperor's wardens carry a dozen spikes each. The ash, the killing fog and the undying emperor are all side effects of the long deadlock, and the unmaker tells its wardens it is winning.", tags: ["truth:ore_two_halves"],
      known: [
        "Spiked wardens sometimes report a voice through their spikes. The church says the spike is only a surgical tool and prescribes ten days' rest. A night fog kills some people in the lowlands and wakes the gift in others.",
        "The bracelet-archivists recite an old teaching: there are two powers, one that keeps and one that unmakes, bound together, and the world is the knot. One steel plate of prophecy, the one everybody follows, has been secretly recut.",
        "A dying warden wrote that the voice in the spike says the other power is losing. The spike-art and the fog both seem to belong to the second power, and it can reach anyone who has been spiked.",
        "Confirmed: the metal arts come from two deadlocked powers. The spike belongs to the unmaker, which speaks through every spike and has edited the empire's prophecy. The ash, the fog and the undying emperor all come from the deadlock.",
      ] },
    { id: "wrong_saviour", n: "The tyrant saved the world badly", d: "A thousand years ago a porter seized a world-shaping power at the brink of the end and mended the world clumsily: he moved it, made the sun red and the plants brown, and buried the thing that was coming under ash. He has ruled as a tyrant ever since and hangs anyone who remembers the old sky. But his power still holds the buried threat down, and whoever kills him sets it free.", tags: ["truth:ore_wrong_saviour"],
      known: [
        "The church says the sky has always been red and brown, yet people are hanged for saying the sun was once gold. A remote valley of stone flowers keeps colours nobody has names for.",
        "A buried city's murals show a yellow sun, a blue sky and a dark mass coming from the north, with a man in a porter's apron standing in its way. Its star-charts put the world much farther from the sun than it is now.",
        "Rumour says an unlisted metal in the capital's deepest vault can kill the emperor. The wardens hang everyone who repeats it. The emperor's own journal, a thousand years old, says that if he dies, what he buried comes back up.",
        "Confirmed: the emperor is a porter who seized a god's power a thousand years ago, moved the world and buried a coming catastrophe under ash. He is a tyrant, and he is also the lid. Whoever kills him opens it.",
      ] },
    { id: "god_corpse", n: "The seams are a body", d: "Every seam of burnable metal is a vein of a fallen god's corpse, which lies under the land with its arms flung out. Mining it means cutting up the body, and burning it means eating it. The noblest houses are the ones whose ancestors burned the most for thirty generations, and their children are slowly turning back into the god.", tags: ["truth:ore_god_corpse"],
      known: [
        "Foremen in the deep seams report that the metal bleeds when it is cut, a cupful at a time. The church's mining primer says the red seep is rust and that rust is no reason to stop work.",
        "Mapped together, the deep seams make the shape of a man lying on his back with his arms flung out, 300 miles long. A pool of liquid light in a mountain cave lies over a metal hand, palm up.",
        "The oldest noble house has burned more metal than any other for 30 generations. Its own physician writes that its children dream of a great body under the land, and two have grown metal under their nails.",
        "Confirmed: the seams are the veins of a fallen god. Mining cuts up its body and burning eats it. The houses that burned most are turning back into it, and the pool of its blood is filling again.",
      ] },
  ],

  tags: ["metal_burning"],

  subthemes: [
    { id: "god_heist", n: "The Heist on a God", d: "A crew of half-blood thieves plans to topple the undying emperor with his own treasury and an army of serfs. Their leader escaped the emperor's deepest pit and laughs too much.", w: 1.2, req: { any: ["autocracy", "gov:empire", "harsh_law", "unstable"] }, truthLink: "wrong_saviour", tags: ["theme:god_heist"] },
    { id: "ash_farms", n: "Ash-Farming", d: "Brown crops grow under a red sun in fields that must be swept of ash every morning. Starvation is a tool of policy, and every serf knows it.", w: 1.4, req: { any: ["hierarchical", "levies", "gov:feudal", "river", "grass"] }, mods: [["poor", 2]], tags: ["theme:ash_farms"], mark: { kind: "zone", n: "Ash plantations", color: "#6a5a4a", size: [2, 5], where: "inner" } },
  { id: "ballroom_war", n: "The Ballroom War", d: "The great houses fight at balls: spies with tin-sharp ears, duels by flung coin over the rooftops at midnight, marriages arranged for metals.", w: 1.2, req: { any: ["urbane", "hierarchical", "dynastic", "spy_network"] }, tags: ["theme:ballroom_war"] },
    { id: "metal_memory", n: "The Bracelet-Archivists", d: "A hunted people store the whole of human knowledge in metal bands, copying it from memory into metal and back, while they search for a religion that told the truth.", w: 1, req: { any: ["scholarly", "mountain_folk", "insular", "ancestor_bound"] }, truthLink: "two_halves", tags: ["theme:archivists"] },
    { id: "missing_metal", n: "The Unlisted Metal", d: "Rumour says one more metal exists, unlisted in any table, that can kill the emperor. The emperor's wardens are killing everyone who repeats the rumour, which suggests it is true.", w: 0.9, truthLink: "wrong_saviour", tags: ["theme:unlisted_metal"] },
    { id: "spike_giants", n: "The Spike-Made Clans", d: "Huge blue-grey warriors and wolf-men, made by spiking, have escaped their masters and live in the badlands. They grow bigger as they age and stop being able to speak.", w: 1, req: { any: ["badlands", "frontier", "mountain", "hills"] }, truthLink: "two_halves", tags: ["theme:spike_clans"], mark: { kind: "zone", n: "Spike-giant country", color: "#4a5a7a", size: [2, 4], where: "remote" } },
    { id: "light_well", n: "The Pool Beneath the Mountain", d: "In a cave beneath a mountain a pool of liquid light fills once in a thousand years. Whoever drinks it can remake the world. It is filling.", w: 0.6, req: { any: ["mountain", "seers", "mystic", "near:ley"] }, truthLink: "god_corpse", tags: ["theme:light_well"] },
    { id: "bastard_rights", n: "The Half-Blood Question", d: "Half-blood burners, the children of nobles and serfs, now outnumber the pure houses. They are illegal by birth and indispensable by trade.", w: 1.1, req: { any: ["egalitarian", "urbane", "unstable", "origin:rebellion"] }, tags: ["theme:half_bloods"] },
    { id: "killing_fog", n: "The Killing Fog", d: "Every night a fog fills the lowlands. Most nights it harms nobody. Some nights it picks someone, and they shake until they die.", w: 1.1, req: { any: ["river", "marsh", "forest", "coastal"] }, truthLink: "two_halves", tags: ["theme:killing_fog"] },
    { id: "seam_mines", n: "The Deep Seams", d: "Serf gangs dig the burnable metals from the deepest seams in the world. The seams bleed when cut, the foremen say, though only a little.", w: 1.1, req: { any: ["mountain", "hills", "artisans", "mountain_folk"] }, truthLink: "god_corpse", tags: ["theme:deep_seams"] },
    { id: "rail_frontier", n: "The Rail Frontier", d: "Centuries on, railways push into the wild and lawmen who burn steel ride the rails, flinging themselves from car to car. The frontier towns have their own metals now, and their own gods.", w: 0.6, req: { any: ["frontier", "steppe", "desert", "badlands"] }, tags: ["theme:rail_frontier"] },
  ],

  sites: [
    { id: "light_cave", n: "The Pool of $", kind: "wonder", where: "mountain", truthLink: "god_corpse", d: "A cave pool of liquid light, ringed by the bones of those who came for it.",
      layers: {
        surface: { n: "The glow", text: "A cave high in the mountains above {place} where the rock at the back glows faintly, enough to read by. Shepherds will not shelter in it. The ash-church has kept a warden at its mouth since {year}, with orders to let nobody pass." },
        study: { n: "Rings of bones", text: "A pool of liquid light fills a hollow at the back, rising a hair's breadth each year. The bones around it lie in rings, one ring for each time it filled. The newest ring has 14 skeletons. Most of them wear noble rings." },
        dig: { n: "The open hand", text: "Under the pool is a cast of metal shaped like a vast hand, open and palm up, its fingers seamed with every burnable metal. Laid together, the empire's seam maps put this hand at the end of an arm. The church's maps are kept in {lead}.", points: "archive" },
        revelation: { n: "Blood in the palm", text: "The pool is the dead god's blood, collecting in its palm. Those who drink it are not given power; they are taken back into the god. The noble houses have sent their strongest burners here each time it filled, believing it a crown. It is filling again, and the oldest house has already chosen." },
      } },
    { id: "steel_plate", n: "The Uncorrupted Plate of $", kind: "ruin", where: "any", truthLink: "two_halves", d: "A steel plate whose text has been altered, though nothing should be able to change words written in metal.",
      layers: {
        surface: { n: "Words in steel", text: "A sealed archive under an old monastery at {place}, its records cut into 1,140 steel plates. The archivists believed nothing could change words written in metal, so they cut only what they meant to keep forever." },
        study: { n: "One plate disagrees", text: "Every plate agrees with every other but one. That one holds the prophecy of the Lord's return, which the ash-church has read aloud each new year for nine centuries. Its wording differs from the older copies in eleven places." },
        dig: { n: "The recut paragraph", text: "On that plate a whole paragraph has been smoothed and recut in the original hand, so finely it took a tin-burner's eye to see it. The archivists carried off a rubbing made before the change; one is said to survive at {lead}.", points: "cast:investigator" },
        revelation: { n: "The editor", text: "The unmaker can change even words cut in steel, working through the hands of the spiked. The archivists trusted metal and never checked it. The prophecy the empire has acted on for 900 years was edited, and the wars fought to fulfil it served the unmaker. The church still reads it every new year." },
      } },
    { id: "buried_city", n: "The Ash-Buried City of $", kind: "dig", where: "remote", truthLink: "wrong_saviour", d: "A city buried under ash from before the sun turned red.",
      layers: {
        surface: { n: "Towers in the ash", text: "A rise in the ash plain near {place}, with the tops of 9 towers sticking out of it. Ash-crows nest in the windows. The church calls it a natural formation of the plain and has never sent anyone to dig." },
        study: { n: "The old sky", text: "The murals inside show a yellow sun, a blue sky and green fields. A dark mass comes down over them from the north like a flood. A man in a porter's apron stands between the mass and the fields with his arms spread wide." },
        dig: { n: "The star-charts", text: "In the deepest vault are star-charts that put the world much farther from the sun than it is now, and a note in a hurried hand: 'He says he can fix it.' It is signed by a court astronomer whose later papers are kept in {lead}.", points: "archive" },
        revelation: { n: "Moved, not made", text: "The emperor did not make the ash out of cruelty. A thousand years ago the porter who seized a god's power moved the world to bury the threat from the north, and moved it too close to the sun. The ash keeps it from burning. He has hanged everyone who remembered the old sky ever since." },
      } },
    { id: "spike_map", n: "The Pierced Dead of $", kind: "dig", where: "any", truthLink: "two_halves", d: "A mass grave where every body was spiked at an exact point.",
      layers: {
        surface: { n: "The plague pit", text: "A pit outside an old garrison near {place}, marked on the county map as a plague burial of {year}. Nobody in the village remembers a plague. The garrison's wardens visit once a year and leave without a word." },
        study: { n: "One hole each", text: "Every one of the 140 skeletons has a single hole through the bone, each in a different place: shoulder, rib, eye, hip. None shows any sign of disease. The holes are round and clean, as if made with a long iron spike." },
        dig: { n: "The garrison ledger", text: "A garrison ledger buried with the bodies matches each hole to a gift, and each gift to the warden who received it. Some wardens appear 20 times. The garrison's later ledgers were sent to {lead}.", points: "archive" },
        revelation: { n: "Wardens built of the dead", text: "The emperor's wardens are built from stolen gifts, one spike and one dead burner at a time, and every spike lets the unmaker a little further into the warden's mind. The church knows: its own ash-priests signed the ledger. The most-spiked warden in the book now commands the capital's guard." },
      } },
    { id: "iron_canyon", n: "The Hanging Canyon of $", kind: "anomaly", where: "desert", d: "A canyon where iron debris hangs in the air.",
      layers: {
        surface: { n: "Floating iron", text: "Rusted blades, nails and horseshoes, about 3,000 pieces, float motionless above a dry gorge near {place}. Caravans stop to stare and leave quickly. The rail company has rerouted its line 14 miles to avoid the place." },
        study: { n: "Perfect balance", text: "Every piece is held in a perfect balance of push and pull, as though two burners had stopped in mid-duel. A steel-burner who pushed one nail felt it push back hard, from both ends of the canyon at once." },
        dig: { n: "Two skeletons", text: "At each end of the canyon lies a skeleton with a pouch of metal flakes still full. One wore a noble's signet ring, the other a serf's iron collar. The noble's house is still listed in the heralds' rolls at {lead}.", points: "library" },
        revelation: { n: "The duel that never ended", text: "Three hundred years ago a noble and a half-blood serf met here to settle who had the right to burn. They burned so hard against each other that their pushes outlived them. Neither family admits the duel. The noble house still sends someone every year to check that the serf has not won." },
      } },
    { id: "colour_field", n: "The Stone Flowers of $", kind: "anomaly", where: "remote", d: "A field of mineral flowers in colours the world has forgotten.",
      layers: {
        surface: { n: "Stone blossoms", text: "Brilliant stone blossoms cover a valley near {place} where everything else is brown. Serfs who see them weep and cannot say why. The wardens have twice tried to smash them, and 300 hammers have not chipped a petal." },
        study: { n: "Nameless colours", text: "The colours have no names in the modern tongue. The oldest songs of the bracelet-archivists have words for them, and the archivists will sing those songs only inside this valley. Children brought here learn the words in a day." },
        dig: { n: "Seeds of stone", text: "Under the flowers lie ordinary seeds, turned to stone in the instant the sky changed. Some are wheat. Some are fruits no one has eaten for a thousand years. A sample was sent to the ash-church at {lead} and never returned.", points: "temple" },
        revelation: { n: "What the saving cost", text: "Before the ash, the whole world looked like this. When the emperor saved the world he took its colours along with the danger, and then made it a crime to remember them. The flowers are the only proof left. The church has ordered the valley buried in ash, and the ash will not settle on it." },
      } },
  ],

  beings: [
    { id: "spike_giant", n: "Spike-giant", kind: "beast", d: "A towering grey-blue warrior made by spiking, skin splitting as it grows, mind going as it ages.", danger: 3, biomes: ["badlands", "desert", "coldsteppe", "alpine"], look: { size: 3.5, group: [2, 10], move: "pack", speed: 9, col: "#4a5a7a", col2: "#c0c0c8", body: "biped", active: "day", visible: true } },
    { id: "bone_mimic", n: "Bone-mimic", kind: "beast", d: "A jelly-bodied shapeshifter that wears the bones of the dead and their faces. Most serve a contract; a few have gone free.", danger: 2, biomes: ["tempforest", "grass", "river", "temprain"], look: { size: 1.7, group: [1, 1], move: "solo", speed: 6, col: "#b0a090", col2: "#e0d8c8", body: "biped", active: "night", visible: false } },
    { id: "ash_crow", n: "Ash-crow", kind: "bird", d: "A grey crow of the ashlands that nests in dead chimneys and can find a burner by the smell of hot metal.", danger: 0, biomes: ["badlands", "grass", "coldsteppe", "dryforest"], look: { size: 0.5, group: [5, 40], move: "flock", speed: 45, col: "#5a5550", col2: "#8a3a20", body: "bird", active: "day", visible: true } },
  ],

  techs: [
    { id: "ob_metal_tables", n: "The metal tables", field: "alchemy", level: 1, d: "The burnable metals listed in pairs, with exactly what each gives." },
    { id: "ob_fuel_vials", n: "Fuel vials", field: "alchemy", level: 2, d: "Flakes of metal suspended in spirit, carried in a burner's belt like cartridges." },
    { id: "ob_storing_bands", n: "Storing bands", field: "arcana", level: 3, d: "Metal bands that hold weight, health or memory spent now, to be tapped later." },
    { id: "ob_glass_arms", n: "Glass and wood", field: "warfare", level: 3, d: "Glass blades, wooden armour and stone-tipped arrows that no iron-burner can push." },
    { id: "ob_alloys", n: "New alloys", field: "metallurgy", level: 4, d: "Metallurgists alloy new burnables with effects nobody has felt before." },
    { id: "ob_rail_lawmen", n: "Steel-rail engines", field: "engineering", level: 5, d: "Railways and engines, and the burners who ride them faster than any horse." },
  ],

  units: [
    { id: "ob_coinriders", n: "Coin-riders", role: "magic", wpn: "javelin", kit: "light", ranks: 1, gap: 4, size: 15, w: 0.8, mods: [["theme:ballroom_war", 3], ["theme:half_bloods", 3]] },
    { id: "ob_spike_giants", n: "Spike-giant warband", role: "beast", mounted: 0, wpn: "axe", kit: "hide", ranks: 3, gap: 2.2, size: 60, w: 0.4, mods: [["theme:spike_clans", 12]] },
    { id: "ob_wardens", n: "Spiked wardens", role: "magic", wpn: "axe", kit: "robe", ranks: 1, gap: 4, size: 6, w: 0.3, mods: [["gov:empire", 3], ["harsh_law", 3], ["theme:god_heist", 4]] },
  ],

  govs: [
    { id: "ob_undying_throne", n: "Undying throne", d: "A single immortal emperor rules as god, through a church of ash-priests and spiked wardens. Noble houses keep the gift by breeding laws.", tags: ["gov:undying_throne", "monarchy", "autocracy", "theocratic"], w: 0.4, forms: ["Ashen Dominion of $", "Ash Throne of $"], ruler: "Undying Lord", mods: [["realm:vast", 4], ["realm:large", 2], ["theme:god_heist", 6], ["harsh_law", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Ashfall", color: "#5a5048", size: [2, 5], count: [1, 2], where: "any", d: "Land under a constant fall of ash from the ashmounts, brown and grey, swept every morning." },
    { kind: "zone", n: "Fog lowland", color: "#8a8a90", size: [1, 3], count: [0, 2], where: "inner", d: "Valleys where the killing fog pools every night, and every house is shuttered at dusk." },
  ],

  storylines: [
    { id: "ob_snapped", n: "The Waking of {place}", scale: "local", anchor: "town", w: 2, req: "metal_burning",
      stages: {
        start: { h: "A serf of {place} survives a beating", b: "{person}, a young serf of {place}, was beaten nearly to death by a lord's steward and woke the next day able to hear a pin drop across the plantation.", wait: [1, 3], next: [{ to: "crew_finds", w: 2 }, { to: "warden_finds", w: 1, mods: [["harsh_law", 2], ["autocracy", 1.5]] }] },
        crew_finds: { h: "A thieves' crew comes to {place}", b: "{person2}, a scarred thief who laughs too much, has taken {person} into a crew of half-blood thieves. {person2} says the crew is going to rob a god.", wait: [6, 14], fx: { flag: "crew" }, next: [{ to: "rising", w: 1, mods: [["unstable", 2], ["poor", 1.5]] }, { to: "crew_caught", w: 1 }] },
        warden_finds: { h: "A spiked warden visits {place}", b: "A warden with spikes for eyes came to {place} asking which young serf had begun to flinch at whispers. Nobody answered. The warden began to count the houses.", wait: [1, 2], next: [{ to: "crew_finds", w: 1 }, { to: "spiked", w: 1 }] },
        rising: { h: "The serfs of {place} rise", b: "The crew's plan worked, in part. The serfs of {place} burned the steward's house and the plantation ledgers. {person} was on the roof, throwing coins like knives.", fx: { revolt: true, unrest: 15 }, end: true },
        crew_caught: { h: "The crew is taken in {place}", b: "The wardens took the crew in a warehouse. {person2} died laughing. {person} was not among the bodies.", fx: { stability: 2, unrest: 6 }, end: true },
        spiked: { h: "A new warden rides out of {place}", b: "{person} is gone. A new warden rode out of {place} with a fresh spike in the shoulder, and very good ears.", fx: { stability: 3, unrest: 8 }, end: true },
      } },
    { id: "ob_emperor", n: "The Undying Lord of {realm}", scale: "realm", anchor: "realm", w: 1, req: ["metal_burning", { any: ["autocracy", "big", "gov:empire", "gov:undying_throne"] }],
      stages: {
        start: { h: "The serfs of {realm} whisper of an unlisted metal", b: "A rumour runs through the plantations of {realm}: there is a metal in the deepest vault of {capital} that can kill the emperor. The wardens have begun hanging people for repeating it.", wait: [3, 8], fx: { unrest: 10 }, next: [{ to: "heist", w: 2 }, { to: "crushed", w: 1, mods: [["stable", 2], ["harsh_law", 1.5]] }] },
        heist: { h: "Thieves break into the vault of {capital}", b: "{person}'s crew broke into the deepest vault of {capital}. They found a bead of metal, an old journal, and a sealed door. Behind it they could hear slow, heavy breathing.", wait: [2, 6], next: [{ to: "emperor_dies", w: 1, mods: [["unstable", 2], ["chance:low", 1.5]] }, { to: "journal", w: 1 }] },
        crushed: { h: "The rumour of {realm} is drowned in blood", b: "The wardens burned three villages and the rumour went quiet. The ash fell as it always does.", fx: { stability: 4, unrest: 5, pop: 0.97 }, end: true },
        emperor_dies: { h: "The Undying Lord is dead", b: "The emperor of {realm} died on the steps of his temple with a serf's spear through him. Within the week, the ashmounts erupted, the fog came at noon, and the sun looked larger.", fx: { ruler_dies: true, revolution: true, stability: -20, pop: 0.9 }, end: true },
        journal: { h: "The emperor's journal is read aloud in {capital}", b: "It was the journal of a porter who took the emperor's place a thousand years ago, and it describes the threat he has held back ever since. Half of {realm} now wants him dead. The other half wants him to live forever.", fx: { discovery: "writing", stability: -8, unrest: 10 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "{official}, ash-priest, the noble metal tables", text: "From the noble metal tables, copied for every house school by {official}, ash-priest of {place}, {year}: 'Iron, pull. Steel, push. Tin, sharpen. Pewter, strengthen. Copper, hide. Bronze, seek. Zinc, stir. Brass, calm. Eight, and no more, by the Lord's grace. A child of a house who shows the gift is to be registered within 30 days. A serf who shows it is to be reported to the wardens at once.'" },
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: true, points: "cast:survivor", who: "{survivor}, rules for a thieves' crew", text: "Rules for a thieves' crew of {place}, written out by {survivor} for new members, {year}: 'Carry three vials of metal flakes in spirit. Drink one before the job, keep one for the run, keep one for when you are wrong about the run. Never carry iron you cannot drop. Never fight a warden. If a warden finds you, run toward the fog; they hate it more than we do. New members ask for me at {lead}.'" },
    { depth: "lore", about: "power", source: "temple", bias: "propaganda", reliable: false, who: "The emperor's catechism", text: "From the emperor's catechism, recited each morning by serf children at the ash-church of {place}, {year}, lesson 1: 'Who made the ash? The Lord, in mercy. Why does the ash fall? To sift the unworthy from the worthy. What do we say when we sweep? Bless the ash, which keeps us humble.' Children who recite it without a mistake receive one cup of brown meal." },
    { depth: "core", about: "truth:two_halves", source: "ruin", bias: "true", reliable: true, cost: true, points: "site:spike_map", who: "{person}, a spiked warden, on a cell wall", text: "Scratched on the cell wall of {person}, a spiked warden held in the garrison at {place} in {year}, before the warden died: 'It talks to me through the spike. It says the other one is losing. It says I can help. I have eleven spikes. I hear it most through the one in my eye. I asked them to pull it. They said I would die. I am dying anyway.' The garrison buries its dead at {lead}." },
    { depth: "core", about: "truth:two_halves", source: "person", bias: "true", reliable: "partial", plain: true, points: "site:steel_plate", who: "{investigator}, bracelet-archivist", text: "Recited by {investigator}, a bracelet-archivist, from a band 400 years old, to a magistrate of {place}, {year}: 'There are two powers. The first keeps; the second unmakes. They fought, they bound each other, and our world is the knot. The burning belongs to the keeper. The spike belongs to the unmaker, and it speaks to anyone who carries one. The ash and the fog are what the knot leaks.' The archivist adds that the plates at {lead} were changed to hide this." },
    { depth: "core", about: "truth:two_halves", source: "heretic", bias: "heretic", reliable: "partial", who: "{believer}, hedge-preacher", text: "Sermon of {believer}, hedge-preacher, to forty serfs in a barn near {place}, {year}: 'The fog is not weather. It is the unmaker reaching for us, and most nights it misses. When it takes someone, they shake for three days, and some stand up burning metal, because the other power is fighting for them. Never take a spike. A spike is a door, and the unmaker comes in through doors.'" },
    { depth: "core", about: "truth:two_halves", source: "library", bias: "official", reliable: false, who: "Ash-church manual", text: "From 'The Arts Lawfully Explained', issued by the ash-church of {realm} in {year}, page 3: 'The metal arts are the gift of the Lord alone. There is no other power. The spike is merely a surgical tool of the faithful wardens, and causes no voices. Wardens who report voices are suffering from fatigue and will be given 10 days' rest at the garrison's expense.'" },
    { depth: "core", about: "truth:wrong_saviour", source: "archive", bias: "true", reliable: true, plain: true, who: "The emperor's own journal", text: "From the emperor's own journal, a thousand years old, page 61, kept in the deepest vault of {place}: 'I am not the hero they wanted. I am a porter. But I am the one who got here, and I took the power. I moved the world and buried what was coming under ash. The sun is red now and the fields are brown. If I die, it comes back up. I will fix it properly one day, whatever it costs.'" },
    { depth: "core", about: "truth:wrong_saviour", source: "ruin", bias: "true", reliable: "partial", points: "site:buried_city", who: "{investigator}, on a mural under the ash", text: "Notes of {investigator} on a mural in a tower sticking out of the ash plain near {place}, {year}: 'A yellow sun, a blue sky, green fields, and a dark mass coming down from the north, painted like a flood wave over the fields. Below it, 12 figures kneel to a man in a porter's apron. The tower belongs to a buried city, {lead}. Nobody lives within 30 miles of it.'" },
    { depth: "core", about: "truth:wrong_saviour", source: "oral", bias: "garbled", reliable: "partial", cost: true, points: "site:colour_field", who: "A serf, to {believer}", text: "Told by a serf of {place} to {believer} at the crossroads gibbet, {year}: 'This is where they hanged {person}, who raised me. Seventy years old. {person} told the children at the well that the sun was gold once, and that the Lord stole its colour to make a crown. A wardens' informer was drawing water that morning. They left the body a week, and fined us two cups of meal for asking for it. The stone flowers at {lead} are gold, and nobody hangs them.'" },
    { depth: "core", about: "truth:wrong_saviour", source: "temple", bias: "official", reliable: false, who: "Ash-church sermon, by order of {official}", text: "From a sermon read in every ash-church of {realm} on the Lord's day, {year}, by order of {official}: 'The Lord has ruled since the dawn of the world, and the sky has always been as it is. The so-called old sky is a serf fantasy. Anyone who speaks of a yellow sun, a blue sky or a green field is to be reported. Reports are rewarded with one week's meal.'" },
    { depth: "core", about: "truth:god_corpse", source: "person", bias: "true", reliable: "partial", cost: true, points: "archive", who: "Foreman of the deep seam", text: "Report of the foreman of the deep seam at {place} to the house steward, {year}: 'The seam bled again on the fourth level, a cupful, dark and warm. The men refuse to cut. {person}, who cut it anyway, has not stopped shaking and calls out in a voice not their own. I have doubled the drink ration. Please send a physician and 20 new men.' The house's seam ledgers are kept at {lead}." },
    { depth: "core", about: "truth:god_corpse", source: "archive", bias: "redacted", reliable: "partial", plain: true, who: "A noble house's breeding register", text: "Last page of the breeding register of the oldest noble house of {place}, {year}, in the house physician's hand: 'Plainly: the seams are the veins of the fallen god, and to burn them is to eat it. Our line has burned more than any other for 30 generations. Our children now dream of a great body lying under the land, and of being its hand. Two have grown metal under the nails.' The rest of the page is cut away." },
    { depth: "core", about: "truth:god_corpse", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:light_cave", who: "A surveyor, to {investigator}", text: "Told by a mine surveyor to {investigator} at an inn in {place}, {year}: 'The deep seams run in the shape of a man, if you map them all. A man lying on his back with his arms flung out, 300 miles from head to foot. I have seen the whole map. The miners have not. The right hand lies under the mountain at {lead}, palm up, and there is a light in it.'" },
    { depth: "core", about: "truth:god_corpse", source: "library", bias: "official", reliable: false, who: "Ash-church mining primer", text: "From 'Ores of the Empire', a mining primer issued by the ash-church in {year}, chapter 1: 'The burnable metals are ores like any other, laid down by the ordinary workings of fire and water in the deep earth. Seams that seep red do so because of rust. Foremen are reminded that rust is not a reason to stop work, and that idle crews lose their meal.'" },
    { depth: "sub", about: "sub:ash_farms", source: "oral", bias: "true", reliable: true, who: "A sweeping-song, noted by {believer}", text: "A sweeping-song of the ash plantations, sung at dawn in the fields outside {place} and written down by {believer} in {year}: 'Sweep the field at dawn, sweep it at noon, sweep it at dusk, and the brown wheat still tastes of ash.' The steward pays by the sheaf. This year the fields gave 4 sheaves to the acre. The serfs' share was half of one." },
    { depth: "sub", about: "sub:ballroom_war", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A foreign envoy, after a ball", text: "Letter from a foreign envoy after a ball at the great house of {place}, {year}: 'Every lady burned tin to hear the others whisper, and every gentleman burned copper so as not to be heard. The music was very loud. At midnight two guests left by the roof, and in the morning one came back. Our host said the evening had cost 900 crowns in metal alone.'" },
    { depth: "sub", about: "sub:metal_memory", source: "person", bias: "true", reliable: "partial", points: "cast:investigator", who: "{investigator}, to an innkeeper", text: "Said by {investigator}, bracelet-archivist, to the innkeeper who hid the archivist from the wardens at {place}, {year}: 'I carry the songs of four hundred peoples in this band of copper. When I die, give it to my daughter. If you cannot find her, melt it. Do not wear it, or your head will fill with strangers. Our people still meet at {lead}.'" },
    { depth: "sub", about: "sub:missing_metal", source: "oral", bias: "garbled", reliable: "partial", points: "archive", who: "A wardens' informer, reporting", text: "Overheard in a plantation tavern near {place} by an informer for the wardens, {year}, and reported word for word: 'There is an unlisted metal. There always was. The noble tables list eight. The church's own tables, the ones kept in {lead}, stop at ten. Why would the Lord keep two more than he gives us?' The informer was paid 5 crowns. The speaker has not been found." },
    { depth: "sub", about: "sub:spike_giants", source: "traveller", bias: "true", reliable: true, who: "A rail surveyor in the badlands", text: "Journal of a rail surveyor in the badlands east of {place}, {year}: 'The giant was twice my height, grey-blue, the skin split along both arms. It spoke to me in a child's sentences: \"I am big now. When I am bigger I will not talk. That is how it goes.\" It had seven spike-scars. It shared its water with my crew of 12 and walked away.'" },
    { depth: "sub", about: "sub:bastard_rights", source: "heretic", bias: "heretic", reliable: true, points: "heretic", who: "The half-bloods' petition", text: "Petition of the half-bloods of {place}, nailed to the door of the noble court in {year} with 600 marks and signatures: 'Your lordships made us. Your lordships use us in your mines, your ballrooms and your wars. Your lordships hang us for being born. Choose one.' The court tore it down the same morning. New copies are printed at {lead} every week." },
    { depth: "sub", about: "sub:killing_fog", source: "person", bias: "true", reliable: "partial", who: "{person}, of the fog lowlands", text: "Statement of {person}, a ferry-keeper of the fog lowlands near {place}, to the ash-priest, {year}: 'The fog took my husband on a clear night. He shook for three days. When he stood up again he could burn pewter, and has not been sick a day since. The wardens came for him on the fourth day. I am asking where he was taken. Your register says only: claimed.'" },
    { depth: "site", about: "site:steel_plate", source: "archive", bias: "true", reliable: true, who: "{investigator}, archive inventory", text: "Inventory of the steel archive under the monastery at {place}, {year}, checked by {investigator}, bracelet-archivist: 'Plates held: 1,140. Plates checked against older rubbings this year: 1,140. Plates that agree: 1,139. Plates that disagree: 1, number 812, the prophecy of the Lord's return, in eleven places. Our order never checked a metal record before, because metal does not lie. This is the first check in nine centuries. There will be more.'" },
    { depth: "site", about: "site:iron_canyon", source: "traveller", bias: "true", reliable: true, who: "Rail company board, to its surveyors", text: "Reply of the rail company board to its survey party at {place}, {year}: 'The board has read your report of iron hanging in the air over the gorge. The board does not accept that 3,000 nails can float, and has deducted the cost of your 14-mile detour from your bonus. The board's own inspector went out in spring, pushed a horseshoe as a test, and was pushed back 40 feet into the river. The detour is approved. The bonus is not restored.'" },
  ],
};
