// The Pact Market: spirits, devils and remembered heroes bound by contract, and who really holds the paper.
export default {
  id: "pact_market",
  name: "The Pact Market",
  family: "power",
  pitch: "Spirits, devils and heroes of the past can be called into service by contract, and contracts are law across every world, so the true power is never the summoner's: it is the fine print.",
  slots: ["power-access", "monster-source", "state-control"],
  tone: ["grim", "horror"],
  era: ["medieval", "renaissance", "industrial", "modern"],
  scale: "regional",
  genres: ["fantasy", "grimdark", "shonen", "flintlock"],
  w: 1,
  excludes: [],
  pairs: [{ id: "last_kindling", w: 2 }, { id: "thinning", w: 2 }, { id: "downward_throat", w: 1.5 }, { id: "ward_walls", w: 1 }],

  power: {
    name: "pactcraft", user: "pact-holder", users: "pact-holders",
    taught: "Spirits, devils and the remembered dead can be called into service by contract. The terms are law in every world, and a summoner is as strong as what they have bound.",
    rules: ["Every contract has a price: years, a sense, a memory, a body part, a future child, or the soul at death.", "The terms are absolute and literal; the bound do exactly what is written.", "Every summons needs an anchor: a book, a ring, a key, a relic of the hero.", "A devil grows with the fear people feel for what it is."],
    forbidden: "Contracting the great devils of Death, Hunger and the Dark, or paying with another's life.",
  },

  cast: [
    { role: "investigator", n: "a pact-lawyer of the guild who reads every clause twice", home: "capital", stance: "Believes every contract can be read, and that whoever writes the forms is the real power." },
    { role: "official", n: "a registrar of the Office of Pacts who signs off on contained devils", home: "capital", stance: "Keeps the files tidy and the casualty figures light, and believes the Office is all that stands between the city and the rift." },
    { role: "believer", n: "a keeper of the book tower who hands out pact-books on Book Day", home: "border", stance: "Has always taught that the books reward merit, and has begun to doubt it." },
    { role: "survivor", n: "a former wish-bearer who stopped hunting before lapsing, ribbon still on one wrist", home: "remote", stance: "Wants the white messengers stopped, and the girls still hunting in the marsh brought home." },
  ],

  truths: [
    { id: "wish_sale", n: "Every wish is a sale", d: "The small, friendly white messengers who grant wishes are harvesting the despair that follows. Every wish-bearer fights monsters until she despairs, and then becomes the monster the next one is sent to kill. The messengers consider it an honest trade that keeps the world from running down, and the Office of Pacts has filed every missing girl as closed.", tags: ["truth:wish_sale"],
      known: [
        "Girls granted a wish by small white creatures go out at night with ribbons on their wrists to hunt the lapsed, the monsters of the marsh. The Office's bestiary says the two have nothing to do with each other.",
        "The lapsed and the missing wish-bearers come in the same numbers. A lapsed girl's lair held a ribbon, a tally of nights and the words: 'I was sent to kill the last one. She had my ribbon too.'",
        "A pearl given to a museum by a white creature darkens every year, and the custodians hear a girl crying inside it. The donor ledger has a girl's name crossed out beside the creature's entry.",
        "Confirmed: the messengers harvest the despair that follows each wish. Every wish-bearer becomes the monster the next one is sent to kill, and the messengers call it a fair trade that keeps the stars lit.",
      ] },
    { id: "organized_below", n: "The underworld is a civil service", d: "The devils are a bureaucracy, and contracts are its currency. The great Contest of Seven on the surface is a procurement, rigged to deliver one perfect vessel to the ruler below every sixty years. Seven winners have gone down; the great families who fund the contest are paid in favours, and the eighth intake is due.", tags: ["truth:infernal_office"],
      known: [
        "Every sixty years seven summoners fight in secret for one wish. The official programme says the prize carries no further obligation. None of the past seven winners has a grave, a will or a death date.",
        "Devils at contract hearings all quote the same precedents and section numbers. A summoner who came back through a rift describes queues, forms and a very long corridor, and devils who hate it.",
        "Under the scorched crypt is a stair to an iron door marked 'Receiving Office', with a plaque about vessels signed for in triplicate and the next intake in sixty years.",
        "Confirmed: the underworld is a bureaucracy run on contracts, and the Contest of Seven is its procurement. Every sixty years it sends the strongest summoner in the realm below, as a vessel for the ruler there.",
      ] },
    { id: "books_choose", n: "The books choose", d: "The pact-books handed out each year by the old tower are not tools but cells, each with a devil inside, and the luck of which child gets which book is the devils choosing their hosts. The keepers run the tower as the devils' nursery. The bookless outcast, whom the kingdom treats as worthless, is the only free person in it.", tags: ["truth:choosing_books"],
      known: [
        "Every child receives a pact-book at fifteen, by merit of soul, the keepers say. The bookless are treated as worthless. Some knights write that their books have begun answering for them.",
        "The stair of the book tower ends in a blank wall, though the tower's plans show eleven floors above it. A mason who broke through found the words 'I picked you' written thousands of times.",
        "A keeper of 31 years wrote, unsigned, that each book holds a devil that chose its child. A bookless boy walks past whole squads of book-knights without a single book noticing him.",
        "Confirmed: the pact-books are cells, and the devils in them choose their hosts. The tower is their nursery. The bookless children the kingdom despises are the only free people in it.",
      ] },
  ],

  tags: ["pacts"],

  subthemes: [
    { id: "summoning_contest", n: "The Contest of Seven", d: "Every sixty years seven summoners call seven remembered heroes and fight in secret for one prize. The city becomes a battlefield by night and pretends nothing is happening by day.", w: 1, req: { any: ["has:city", "urbane", "arcane"] }, truthLink: "organized_below", tags: ["theme:summoning_contest"] },
    { id: "fear_economy", n: "The Fear Economy", d: "Devils grow with the fear of what they are. Ministers and broadsheets farm fears to grow their own devils, and starve their enemies' by making people laugh.", w: 1.1, req: { any: ["has:city", "harsh_law", "spy_network", "urbane"] }, tags: ["theme:fear_economy"] },
    { id: "wish_bearers", n: "The Wish-Bearers", d: "Girls granted a single wish hunt the lapsed, monsters of the marshes, at night with ribbons on their wrists. Sooner or later, each girl becomes one of the lapsed.", w: 1, truthLink: "wish_sale", tags: ["theme:wish_bearers"] },
    { id: "book_day", n: "Book Day", d: "At fifteen every child climbs the tower to receive a pact-book. The knight-squads are ranked by books, and this year an orphan was given a tattered one with only three pages.", w: 1.1, req: { any: ["monarchy", "hierarchical", "arcane"] }, truthLink: "books_choose", tags: ["theme:book_day"] },
    { id: "debt_hunter", n: "The Debt-Hunter", d: "A poor boy bound a little dog-devil to pay off his dead father's debts. Now the moneylenders are frightened, and so are the boy's friends.", w: 0.9, mods: [["poor", 2], ["mercantile", 1.5]], tags: ["theme:debt_hunter"] },
    { id: "underworld_rift", n: "The Rift in the Market", d: "A rift opened across the market district one festival night. It was sealed, mostly. Small devils still climb up through the cellars.", w: 0.7, mods: [["near:rift", 3]], tags: ["theme:underworld_rift"], mark: { kind: "zone", n: "Devil-scarred ward", color: "#6a1a2a", size: [1, 2], where: "inner" } },
    { id: "key_spirits", n: "The Twelve Keys", d: "Twelve spirits are sealed in twelve keys scattered across the world. A collector holds nine, and the spirits in them are not on his side.", w: 0.8, mods: [["mercantile", 1.5], ["seafaring", 1.5]], tags: ["theme:key_spirits"] },
    { id: "pact_lawyers", n: "The Pact-Lawyers", d: "A guild drafts contracts for summoners and finds loopholes for whoever pays. Some of its best clients are devils.", w: 1, req: { any: ["guilds", "mercantile", "gov:merchant", "urbane"] }, tags: ["theme:pact_lawyers"] },
    { id: "tribute_city", n: "The Tribute City", d: "A city far too rich for its poor harbour. Every seventh year, a child from each street goes up the hill and does not come back.", w: 0.7, req: { any: ["mercantile", "has:port", "gov:merchant"] }, mods: [["sacrifice", 3], ["faith:void", 2]], tags: ["theme:tribute_city"] },
    { id: "legends_in_flesh", n: "Legends in the Flesh", d: "Summoned heroes from rival histories argue in the taverns over whose story was true. One of them is appalled at how history remembers her.", w: 0.6, mods: [["scholarly", 2], ["ancestor_bound", 1.5]], tags: ["theme:legends_in_flesh"] },
    { id: "office_of_pacts", n: "The Office of Pacts", d: "A ministry employs contracted hunters to kill rogue devils. Its own devils are kept on a short leash, and its hunters on a shorter one.", w: 1.1, req: { any: ["autocracy", "standing_army", "harsh_law", "gov:empire"] }, tags: ["theme:office_of_pacts"] },
  ],

  sites: [
    { id: "scorched_crypt", n: "The Scorched Crypt of $", kind: "dig", where: "capital", truthLink: "organized_below", d: "A crypt under an old church, its floor ringed with seven scorch-marks.",
      layers: {
        surface: { n: "Seven rings", text: "A crypt under an old church in {place}, its floor ringed with scorch-marks. The sexton charges two pennies to see it and says a fire did it. The church above has burned down twice since {year}; the crypt has never been touched." },
        study: { n: "Sixty years apart", text: "There are seven rings, one for each Contest of Seven, each burned sixty years after the last. The contest records match each ring to a winner. None of the seven winners has a grave, a will or a death date in any register." },
        dig: { n: "The stair down", text: "In the centre is a drain, and below it a stair down into heat, ending at an iron door with a plaque that reads 'Receiving Office'. The Office of Pacts holds a key to this door; its register of keys is kept in {lead}.", points: "archive" },
        revelation: { n: "A procurement", text: "The contest was never a contest. Every sixty years it picks the strongest summoner in the realm and sends them down as a vessel for the ruler below, and the office there signs for them. The great families who fund the contest are paid in favours. Seven have gone down. The eighth intake is due." },
      } },
    { id: "book_tower", n: "The Tower of Books at $", kind: "wonder", where: "border", truthLink: "books_choose", d: "A frontier tower where every child receives a book at fifteen.",
      layers: {
        surface: { n: "Book Day", text: "A tower on the frontier near {place} where every child of fifteen climbs the stair to receive a pact-book. 340 children came last year. Their families camp below for three days and sell each other food." },
        study: { n: "The blank wall", text: "No one has ever climbed above the distribution hall. The stairs end in a blank plastered wall, and the keepers say the upper floors are storage. The tower's own plans, filed with the crown in {year}, show eleven floors above the hall." },
        dig: { n: "Warm shelves", text: "Behind the wall are empty shelves, warm to the touch, and the sound of pages turning with nobody there. The wall is covered in the words 'I picked you'. The keepers' register of which child got which book is kept at {lead}.", points: "cast:believer" },
        revelation: { n: "The nursery", text: "The books are cells. Each holds a devil, and the devils choose their children; the tower is their nursery and the keepers its staff. The knight-squads ranked by book are ranked by their devils' strength. The bookless children the kingdom treats as worthless are the only free people in it." },
      } },
    { id: "clause_field", n: "The Clause Field of $", kind: "ruin", where: "any", d: "A field of grave-markers inscribed not with names but with contract clauses.",
      layers: {
        surface: { n: "Nameless graves", text: "A field of 400 grave-markers outside {place}, none with a name. Families visit it on the day of the dead. New stones appear every year, and nobody in the town admits to placing them." },
        study: { n: "Clauses instead of names", text: "Each marker bears a contract clause instead of a name: 'the second son', 'all the colours', 'every summer after'. A pact-lawyer matched 60 of them, word for word, to contracts on file with the guild." },
        dig: { n: "What was paid", text: "Under each stone lies not a body but what was paid: eyes in brine, a lock of hair, a child's shoe. Each is wrapped in a receipt. The receipts carry the stamp of an office whose records are held in {lead}.", points: "archive" },
        revelation: { n: "Small prices", text: "Most prices are not paid in blood. They are paid in small things nobody misses at first: a colour, a summer, a son who grows up somewhere else. The devils collect them and bury the receipts here. The field has filled faster every year since the guild began offering standard terms." },
      } },
    { id: "mirror_lake", n: "The Mirror Lake of $", kind: "anomaly", where: "remote", d: "A still lake reflecting a city that does not stand on its shore.",
      layers: {
        surface: { n: "The reflection", text: "A still lake near {place} holds the reflection of a walled city, though no city stands on the shore. Farmers fish it, and nothing they catch has eyes. The lake has never frozen, even in the hardest winter." },
        study: { n: "Moving lamps", text: "It is not a reflection. Lamps move along the streets of the city under the water, about 30 of them after dark, and on calm days a bell rings the hours. The city's clock runs two hours behind the town's." },
        dig: { n: "The deed", text: "A diver brought up a brass door-knocker and a deed in a sealed tube: 'held as surety until the debt is paid in full'. The deed was registered with the pact-lawyers' guild, and the guild's copy is in {lead}.", points: "archive" },
        revelation: { n: "Collateral", text: "A lord pledged his whole city as surety for a contract, and defaulted. The city went into the lake with all its people, to be held until the debt is paid. The lord's heirs still own the estates on the far shore. The people below are still waiting for them to pay." },
      } },
    { id: "dark_pearl", n: "The Darkening Pearl of $", kind: "anomaly", where: "capital", truthLink: "wish_sale", d: "A pearl in a museum case that grows darker every year.",
      layers: {
        surface: { n: "The bruise-coloured pearl", text: "A pearl the size of a plum lies in a museum case in {place}, once white, now the colour of a bruise. The label says it was a gift to the city in {year}. Children who stop at the case often cry and cannot say why." },
        study: { n: "Crying in the case", text: "It darkens a little each year; the custodians keep a colour chart beside the case. On clear nights they hear a girl crying inside the glass. Two custodians have resigned. The third has started leaving a lamp lit." },
        dig: { n: "The donor", text: "The museum ledger names the pearl's donor: a small white creature 'who asked for nothing in return'. Beside it is a girl's name, crossed out, and the name of a marsh village. A former wish-bearer from that village lives at {lead}.", points: "cast:survivor" },
        revelation: { n: "A soul, ripening", text: "The pearl is a wish-bearer's soul. The white messengers gave it to the museum to keep safe while it ripens. When it turns fully black, a monster will hatch from it, and the messengers will send the next wish-bearer to kill it. By the custodians' chart, it has about four years left." },
      } },
    { id: "unmapped_town", n: "The Unmapped Town of $", kind: "anomaly", where: "inner", d: "A town missing from every map since a contract erased it.",
      layers: {
        surface: { n: "The empty meadow", text: "A well-kept road from {place} leads to a green valley and an empty meadow. Its milestones count down to a town that is not there. Carters who take the road reach the meadow and turn round without being able to say why." },
        study: { n: "Bread and voices", text: "Bread left in the meadow is gone by morning, and voices are heard at a well that is not there. The county land roll still lists a town of 600 here, with two mills, and its tithe is paid every year in fresh bread." },
        dig: { n: "The charter", text: "Buried in the meadow is the town's charter, stamped 'forgotten, by contract'. The contract was signed by the town's lord, in exchange for something the charter does not name. The guild keeps a copy of the contract in {lead}.", points: "archive" },
        revelation: { n: "Forgotten, not destroyed", text: "The town was not destroyed. Its lord sold the world's memory of it to a devil to escape a war, and the world forgot. Its 600 people still live there, unseen and unable to leave. The lord was away on the day, and lives comfortably in the capital." },
      } },
  ],

  beings: [
    { id: "dread_devil", n: "Dread-devil", kind: "beast", d: "A devil of a feared thing: rot, drowning, the dark under the stairs. The more it is feared, the larger it grows.", danger: 3, biomes: ["tempforest", "grass", "badlands", "swamp"], look: { size: 3, group: [1, 1], move: "solo", speed: 12, col: "#4a1a1a", col2: "#e0a030", body: "biped", active: "night", visible: true } },
    { id: "bound_imp", n: "Bound imp", kind: "small", d: "A minor devil bound to fetch, spy and carry. It keeps a careful tally of every insult, against the day its contract ends.", danger: 1, biomes: ["tempforest", "grass", "river", "dryforest"], look: { size: 0.5, group: [1, 3], move: "solo", speed: 8, col: "#7a2a1a", col2: "#2a1a1a", body: "biped", active: "dusk", visible: true } },
    { id: "wish_messenger", n: "Wish-messenger", kind: "small", d: "A small white creature with soft ears and a calm voice that offers children one wish, in exchange for 'just a little help'.", danger: 0, biomes: ["tempforest", "grass", "river", "temprain"], look: { size: 0.4, group: [1, 1], move: "solo", speed: 10, col: "#f0f0f0", col2: "#e05070", body: "quad", active: "any", visible: false } },
    { id: "pact_toad", n: "Pact-toad", kind: "amphibian", d: "A huge talking toad of a summoning clan, bound by an old contract to one family. Rude, loyal and always hungry.", danger: 1, biomes: ["swamp", "river", "rainforest"], look: { size: 2.5, group: [1, 3], move: "solo", speed: 6, col: "#5a7a3a", col2: "#e0c050", body: "quad", active: "day", visible: true } },
  ],

  techs: [
    { id: "pm_ancestor_calling", n: "Ancestor-calling", field: "arcana", level: 1, d: "Shamans call ancestor spirits and animal clans with gifts and old songs; the first pacts are spoken, not written." },
    { id: "pm_written_pacts", n: "Written pacts", field: "writing", level: 2, d: "Contracts set down in books with seals and catalogues of devils. What is written binds both sides." },
    { id: "pm_licensed_summoning", n: "Licensed summoning", field: "arcana", level: 3, d: "Towers, offices and licences: summoning becomes a regulated trade." },
    { id: "pm_contract_law", n: "Contract law", field: "writing", level: 4, d: "Standard prices, insurance and pact-lawyers who argue terms with devils across a table." },
    { id: "pm_fear_reckoning", n: "Fear-reckoning", field: "natural_philosophy", level: 4, d: "Public fear measured street by street, so the growth of a devil can be predicted, or arranged." },
    { id: "pm_primal_terms", n: "Primal terms", field: "arcana", level: 5, d: "Negotiation with the great devils and the office below, and the first contract the surface ever won." },
  ],

  units: [
    { id: "pm_office_hunters", n: "Office of Pacts hunters", role: "infantry", wpn: "sword", kit: "mail", ranks: 2, gap: 2, size: 30, w: 0.5, mods: [["theme:office_of_pacts", 8], ["harsh_law", 1.5]] },
    { id: "pm_bound_devils", n: "Bound devils", role: "beast", wpn: "axe", kit: "hide", ranks: 1, gap: 4, size: 10, w: 0.2, mods: [["theme:office_of_pacts", 4], ["theme:fear_economy", 3]] },
    { id: "pm_book_knights", n: "Book-knights", role: "magic", wpn: "staff", kit: "robe", ranks: 2, gap: 3, size: 25, w: 0.5, mods: [["theme:book_day", 8]] },
  ],

  govs: [
    { id: "pm_compact", n: "The Compact", d: "A state founded on a contract with a power below. Its laws are clauses, and its ruler is a signatory.", tags: ["gov:pm_compact", "autocracy"], w: 0.3, forms: ["Compact of $", "Bound Crown of $", "Signatory State of $"], ruler: "Signatory", mods: [["faith:void", 4], ["sacrifice", 3], ["mercantile", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Erased lands", color: "#d8d8d8", size: [1, 2], count: [0, 2], where: "any", d: "Blank places on the map, removed by contract. The roads still lead there." },
  ],

  storylines: [
    { id: "pm_debt", n: "The Debt of {place}", scale: "local", anchor: "town", w: 1.5, req: "pacts",
      stages: {
        start: { h: "A youth of {place} inherits a dead father's debts", b: "{person}'s father died owing the moneylenders of {place} more than {person} can earn in a lifetime. Last night {person} drew a circle in the woodshed.", wait: [1, 3], next: [{ to: "dog_devil", w: 2 }, { to: "lawyer", w: 1, mods: [["theme:pact_lawyers", 3], ["mercantile", 1.5]] }] },
        dog_devil: { h: "{person} binds a little dog-devil", b: "The devil that answered was the size of a dog and smelled of wet chain. It asked for {person}'s left eye, and got it.", wait: [2, 6], next: [{ to: "debts_cleared", w: 1 }, { to: "office_comes", w: 1, mods: [["theme:office_of_pacts", 3], ["harsh_law", 1.5]] }] },
        lawyer: { h: "A pact-lawyer offers {person} terms", b: "{person2}, a pact-lawyer, has offered to draft the contract for {person} in return for a share of whatever comes of it.", wait: [2, 5], next: [{ to: "debts_cleared", w: 1 }, { to: "loophole", w: 1 }] },
        debts_cleared: { h: "The moneylenders of {place} are found dead", b: "Every creditor of {person}'s father was found in the morning, very still. The debts are cleared, and nobody in {place} will lend money any more.", fx: { unrest: 8, treasury: -20 }, end: true },
        office_comes: { h: "The Office of Pacts recruits {person}", b: "Hunters of the Office arrived in {place} with chains, then offered {person} a choice: a cell or a badge. {person} took the badge.", fx: { stability: 2 }, end: true },
        loophole: { h: "{person2} finds the loophole", b: "The contract had a clause no devil reads closely: 'payment due upon the first snowfall in summer'. The debts are gone, and the devil is still waiting.", fx: { prestige: 3 }, end: true },
      } },
    { id: "pm_contest", n: "The Contest of Seven in {capital}", scale: "realm", anchor: "realm", w: 1, req: ["pacts", { any: ["has:city", "urbane", "arcane"] }],
      stages: {
        start: { h: "Seven marks appear on seven hands in {capital}", b: "Every sixty years the marks come. Seven summoners of {realm} have woken with red sigils on their hands, and the great families are sending for the relics of dead heroes.", wait: [2, 5], next: [{ to: "battles", w: 2 }, { to: "forbidden", w: 1, mods: [["ruler:just", 2], ["pacifist", 2]] }] },
        forbidden: { h: "{ruler} forbids the contest", b: "{ruler} has declared the contest ended and ordered the marked to the palace. Two came. Five did not.", wait: [2, 4], next: [{ to: "battles", w: 2 }, { to: "marks_fade", w: 1 }] },
        battles: { h: "Night battles in {capital}", b: "Streets of {capital} are found cratered in the morning. {person}, a summoner fighting beside a remembered queen, has outlasted three rivals.", wait: [3, 8], fx: { unrest: 8, pop: 0.97 }, next: [{ to: "winner", w: 1 }, { to: "descent", w: 1, mods: [["theme:summoning_contest", 2]] }] },
        winner: { h: "{person} claims the prize", b: "{person} stood alone in the scorched crypt with the prize. {person} wished for a lost brother to come back. The brother came home on the next ship, and has not been quite right since.", fx: { prestige: 5 }, end: true },
        descent: { h: "The crypt beneath {capital} opens", b: "When the last summoner fell, the floor of the scorched crypt opened, and the devils below took the winner down as their vessel. {capital} shook for a week.", fx: { stability: -12, unrest: 12, flag: "vessel" }, end: true },
        marks_fade: { h: "The marks fade in {capital}", b: "One by one the sigils have faded from the summoners' hands. The contest has been missed for the first time in history, and nobody knows what that means.", fx: { stability: 4 }, end: true },
      } },
    { id: "pm_wish", n: "The Wish at {place}", scale: "local", anchor: "town", w: 1.2, req: "pacts",
      stages: {
        start: { h: "A small white creature visits {place}", b: "{person}, a child of {place} whose mother is dying, says a small white creature came to the window at night and offered one wish.", wait: [1, 3], next: [{ to: "wished", w: 2 }, { to: "refused", w: 1, mods: [["pious", 1.5]] }] },
        wished: { h: "A dying woman of {place} rises from her bed", b: "The fever broke overnight. Now {person} goes out at night with a ribbon on one wrist, hunting monsters in the marshes.", wait: [4, 10], next: [{ to: "lapsed", w: 1 }, { to: "broken_deal", w: 1, mods: [["theme:pact_lawyers", 3], ["learned", 1.5]] }] },
        refused: { h: "{person} closes the window", b: "{person}'s mother died in spring. The creature has not come back, and {person} sometimes wishes it would.", fx: { stability: 1 }, end: true },
        lapsed: { h: "A new horror in the marshes of {place}", b: "{person} has not come home. A new monster lives in the marsh, weeping and dangerous, and a white creature has been seen at another child's window.", fx: { unrest: 8, pop: 0.98 }, end: true },
        broken_deal: { h: "{person} breaks the contract", b: "With the help of {person2}, a pact-lawyer, {person} found a clause that cancels the contract. The white creature has been seen in {place}, looking, for the first time, annoyed.", fx: { prestige: 4, discovery: "writing" }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", points: "library", who: "A summoner's notebook", text: "From a summoner's notebook, sold with its owner's effects at {place} in {year}: 'Circle, anchor, name, terms. Read the terms aloud. Never break the circle before the devil agrees.' Below, the owner copied the main clauses of 3 contracts in a fair hand. The price clauses are in script so small the owner never copied them. The last 9 pages are blank. The notebook is now in {lead}." },
    { depth: "lore", about: "power", source: "archive", bias: "official", reliable: "partial", points: "archive", who: "{official}, registrar of the Office of Pacts", text: "Office of Pacts incident report, east docks of {place}, {year}, signed by {official}, registrar: 'Rogue devil (drowning) contained at the east docks after two hours. Casualties: light. Anchor recovered: one brass ring. Summoner: not found.' Beside 'light', in a later hand: 'Forty-one.' The Office's full casualty rolls are kept in {lead}." },
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: true, who: "A remembered hero, at dinner", text: "Said by a remembered hero, called up after six hundred years by a summoner of {place}, to the summoner's household at dinner, {year}: 'They sing that I slew the serpent for love of the realm. I slew it for the reward: 300 gold and a duchy. I drowned the realm's children in the shallows to bait it. Please stop singing that song at me.'" },
    { depth: "core", about: "truth:wish_sale", source: "person", bias: "true", reliable: "partial", plain: true, who: "A wish-messenger, taken down by {investigator}", text: "A wish-messenger's own explanation, taken down word for word by {investigator}, pact-lawyer, at {place} in {year}: 'Every girl we grant a wish fights monsters for us until she despairs, and her despair is the warmest thing in the world. We take it to keep the stars lit. When it is all used up, she becomes a monster herself, and we send the next girl. Is that so wrong? We always ask first.'" },
    { depth: "core", about: "truth:wish_sale", source: "ruin", bias: "true", reliable: true, cost: true, who: "{survivor}, in a lapsed girl's lair", text: "Found by {survivor}, a former wish-bearer, in a lapsed girl's lair in the marsh near {place}, {year}: a pink ribbon, a tally of 212 nights scratched on a stone, and the words 'I was sent to kill the last one. She had my ribbon too.' The tally is signed {person}, the girl {survivor} hunted beside for two years. It is the thirteenth lair in that marsh." },
    { depth: "core", about: "truth:wish_sale", source: "oral", bias: "garbled", reliable: "partial", points: "cast:survivor", who: "Marsh-village mothers, noted by {investigator}", text: "Advice given to children by the mothers of the marsh villages near {place}, as noted by {investigator} in {year}: 'If a little white beast asks what you want most in the world, say nothing, and mean it, and do not look at its eyes.' The villages have lost 4 girls in 20 years, all from families that did not teach it. The one who came back lives at {lead}." },
    { depth: "core", about: "truth:wish_sale", source: "heretic", bias: "exaggerated", reliable: "partial", points: "site:dark_pearl", who: "A marsh preacher's broadsheet", text: "Broadsheet of a marsh-village preacher near {place}, {year}: 'Every monster in the marsh was a girl once who wanted her father to stop drinking. Count the monsters. Count the wishes. It is the same number: we counted 13 of each. Then go to the museum at {lead}, look at the pearl the white beast gave them, and tell me what colour it is now.'" },
    { depth: "core", about: "truth:wish_sale", source: "library", bias: "official", reliable: false, who: "Office-approved bestiary", text: "From 'Spirits of the Field and Fen', a bestiary approved by the Office of Pacts, {year}, entry 41: 'The wish-messengers are benign spirits of good fortune, harmless to children. The lapsed are wild devils of the marsh with no relation to them whatever. Any likeness between a lapsed devil and a missing girl is coincidence, and the Office will not reopen closed files.'" },
    { depth: "core", about: "truth:organized_below", source: "ruin", bias: "true", reliable: true, who: "Plaque under the scorched crypt, copied by {investigator}", text: "An iron plaque at the foot of the stair under the scorched crypt in {place}, copied by {investigator} in {year}: 'RECEIVING OFFICE. Vessels to be signed for in triplicate. Next intake: sixty years. Late deliveries will be charged to the surface account.' The plaque is bolted to a door that is warm to the touch. Beside it hang 7 brass hooks, all empty." },
    { depth: "core", about: "truth:organized_below", source: "archive", bias: "redacted", reliable: "partial", cost: true, points: "site:scorched_crypt", who: "Contract scroll of the last contest", text: "Contract scroll from the last Contest of Seven, recovered from the house of {person}, its winner, {year}: 'The prize shall be granted to the last summoner standing, who shall thereafter be...' The rest is burned away. {person} went down into the crypt at {lead} on the night of the victory, as the rules require, and was not seen again. The household later received a receipt, signed in triplicate." },
    { depth: "core", about: "truth:organized_below", source: "person", bias: "true", reliable: "partial", plain: true, who: "{investigator}, pact-lawyer, case notes", text: "Case notes of {investigator}, pact-lawyer, {year}, after a 300th contract argued with a devil: 'Every devil I have faced quotes the same precedents and the same section numbers. The underworld is a civil service, and contracts are its currency. The Contest of Seven is a procurement: it exists to deliver one strong vessel to the ruler below every sixty years. I have the forms to prove it, and I have told nobody.'" },
    { depth: "core", about: "truth:organized_below", source: "traveller", bias: "exaggerated", reliable: "partial", points: "archive", who: "A summoner back through the rift", text: "Told by a summoner who came back through the market rift at {place} in {year}, to the Office's interviewer: 'The underworld has queues, forms and a very long corridor. I waited 11 days to be told I was in the wrong queue. The devils hate it as much as we would. One of them asked me, very politely, whether the surface had any openings.' The interview is filed in {lead}." },
    { depth: "core", about: "truth:organized_below", source: "library", bias: "official", reliable: false, who: "Official contest programme", text: "From the official programme of the Contest of Seven, printed in {place} for the contest of {year}, price two pennies: 'The Contest of Seven is an ancient and honourable trial of summoners. The prize is a single wish, freely granted, with no further obligation. Citizens are asked to stay indoors after dark during the contest weeks and to report any damage for compensation.'" },
    { depth: "core", about: "truth:books_choose", source: "ruin", bias: "true", reliable: true, points: "site:book_tower", who: "The wall above the distribution hall", text: "Written on the blank wall above the distribution hall of {lead}, found by a mason who broke through it in {year}: 'I picked you.' 'I picked you.' 'I picked you.' The same three words, 2,000 times or more, in many hands and many inks, the oldest faded brown. The mason was dismissed the next day, and the wall was plastered over by evening." },
    { depth: "core", about: "truth:books_choose", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, book-knight, diary", text: "Diary of {person}, a book-knight of the third squad, {year}: 'My book opens to a page I have never read, and it knows what I am going to say before I say it. Lately it has started answering for me. At the squad dinner it spoke for an hour in my voice, and everyone laughed at its jokes. I have not chosen my own words for 9 days. I am writing this while it sleeps.'" },
    { depth: "core", about: "truth:books_choose", source: "oral", bias: "garbled", reliable: "partial", who: "A tavern-keeper of {place}", text: "Said by a tavern-keeper of {place} to a travelling clerk, {year}: 'The bookless boy at the end of our street has no magic at all. Got nothing at fifteen, not even a pamphlet. He is also the only one in town the knights cannot see coming. Twice this year he walked straight past the whole third squad, and not one of their books noticed him.'" },
    { depth: "core", about: "truth:books_choose", source: "heretic", bias: "heretic", reliable: "partial", plain: true, who: "A keeper of the tower, unsigned", text: "Unsigned pamphlet left on the steps of the tower of books near {place} in {year}, 'by a keeper of this tower, 31 years in service': 'You did not choose your book, and the tower did not choose it for you. Every book is a cell with a devil inside. The devil chose you, and it was pleased with its choice. The bookless are the only free people in this kingdom. Ask the keepers what is behind the wall.'" },
    { depth: "core", about: "truth:books_choose", source: "temple", bias: "official", reliable: false, who: "{believer}, keeper of the tower, on Book Day", text: "Address of {believer}, keeper of the tower, to the children of {place} on Book Day, {year}: 'The books are granted by the tower according to the merit of each child's soul. To be given none is the mark of a soul without worth. This year 340 of you will climb the stair. Walk slowly, do not speak to your book until you are home, and thank it when it answers.'" },
    { depth: "sub", about: "sub:fear_economy", source: "archive", bias: "redacted", reliable: true, points: "archive", who: "Ministry memorandum, initialled {official}", text: "Ministry memorandum, {place}, {year}, initialled by {official}: 'Our drowning devil is weakening, down a third since the new embankment. Recommend the broadsheets run three river-death stories a week until further notice. The opposition's devil (fire) is to be starved: approve the comic play about the burning bakery, 20 performances.' Copies to {lead}." },
    { depth: "sub", about: "sub:book_day", source: "oral", bias: "true", reliable: "partial", points: "cast:believer", who: "A girl who climbed on Book Day", text: "Told at the frontier inn below the tower by a girl who climbed on Book Day, {year}: 'The orphan's book had three pages and a burned spine. All 340 of us laughed. The book did not. On the way down the stair, every other book in the line went quiet, the way dogs go quiet. The keeper who handed it over, {believer}, has not given out a book since, and has gone home to {lead}.'" },
    { depth: "sub", about: "sub:tribute_city", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A wool-factor, visiting the hill city", text: "Letter from a wool-factor visiting the hill city of {place}, {year}: 'Gold on every door-knocker, and a harbour no ship over 40 tons could use. I asked where the wealth came from. A woman told me to count the children. I walked the whole lower town and counted 3. This is the seventh year. The woman has asked me to take her niece home with me.'" },
    { depth: "sub", about: "sub:pact_lawyers", source: "person", bias: "true", reliable: "partial", who: "{investigator}, to an apprentice", text: "Advice from {investigator}, pact-lawyer, to a new apprentice at the guild hall of {place}, {year}: 'Never draft for a devil on a Tuesday; they send their best people on Tuesdays. Charge by the clause, not the hour. Read every word twice, once forward and once back. And remember that a third of our fees come from devils, so be polite in the corridor.'" },
    { depth: "sub", about: "sub:office_of_pacts", source: "library", bias: "propaganda", reliable: false, points: "heretic", who: "Office of Pacts recruiting poster", text: "Recruiting poster of the Office of Pacts, pasted up in {place}, {year}: 'The hunters of the Office are free citizens serving gladly! Good pay: 2 crowns a week and a pension. The devils in our keeping are perfectly tamed and pose no danger to their handlers.' Under it, in chalk: 'Ask what the hunters signed. Ask what happens if they quit. Ask at {lead}.'" },
    { depth: "sub", about: "sub:legends_in_flesh", source: "person", bias: "true", reliable: true, who: "A watch-sergeant's report", text: "Report of a watch-sergeant of {place}, {year}, on a disturbance at the Three Crowns tavern: 'Two summoned kings, each from the founding legend of a different realm, arguing at volume about which of them killed the other. Both produced the same sword as proof. Damage: 6 chairs and one window. Both summoners fined and asked to keep their kings at home.'" },
    { depth: "site", about: "site:clause_field", source: "oral", bias: "true", reliable: "partial", who: "{person}, at the clause field", text: "Told by {person} of {place} to {investigator}, beside a stone marked 'all the colours' in the clause field, {year}: 'My father paid his colours to bring me through the fever when I was six. He saw in grey for forty years and called it a bargain. He used to ask me what colour the sea was that day, then argue with the answer. That is his stone. Nobody is under it. There are 400 stones here now, and more every year.'" },
    { depth: "site", about: "site:mirror_lake", source: "traveller", bias: "garbled", reliable: "partial", points: "archive", who: "A pedlar camped by the lake", text: "Journal of a pedlar who camped by the still lake near {place}, {year}: 'A boy from the farm waved at the city in the water, and somebody in the city waved back. I counted 30 lamps moving along its streets after dark. The farmer says the deed to that city was registered with the pact-lawyers in {lead}, and was never paid off.'" },
    { depth: "site", about: "site:unmapped_town", source: "archive", bias: "redacted", reliable: "partial", who: "County land roll of {realm}", text: "Entry in the county land roll of {realm}, {year}, under a heading scraped clean: 'Population: 600. Mills: 2. Tithe owed: 40 crowns. Status: forgotten, by contract, at the request of the lord.' The clerk has added: 'I cannot find this place on any map, but the road is still kept up, and somebody pays the tithe every year in fresh bread.'" },
  ],
};
