// The Quickening: most people are now born gifted, society is rebuilt around licensed champions, and the gifts grow stranger each generation.
export default {
  id: "quickening",
  name: "The Quickening",
  family: "power",
  pitch: "Some generations ago children began to be born with gifts; now four in five are gifted, society has been rebuilt around licensed champions, and every generation the gifts grow stronger and stranger.",
  slots: ["power-access", "bloodline", "state-control", "apocalypse"],
  tone: ["heroic", "grim"],
  era: ["medieval", "renaissance", "industrial", "modern"],
  scale: "world",
  genres: ["fantasy", "shonen", "flintlock"],
  w: 1,
  excludes: [],
  pairs: [{ id: "pale_visitor", w: 2 }, { id: "visited_ground", w: 2 }, { id: "ward_walls", w: 1.5 }, { id: "wheel_of_suns", w: 1.2 }],

  power: {
    name: "the quickening", user: "quickened", users: "the quickened",
    taught: "A gift shows itself by the fourth year of life: fire from the palms, a second pair of arms, a voice that commands dogs. It follows the blood, mixing the parents' gifts or turning out something new. Using it in public without a guild licence is a crime.",
    rules: ["Most people have a single gift, fixed at birth.", "A gift's drawback grows with its strength.", "Gifts mix in children: two parents' gifts make a third.", "A few gifts wake late, only under terror or grief."],
    forbidden: "Unlicensed use of a gift in public; taking or giving a gift; experiments on children.",
  },

  cast: [
    { role: "investigator", n: "a physician of the college who measures children's gifts for the register", home: "capital", stance: "Believes the numbers should be published, and is watching them climb." },
    { role: "official", n: "a licensing officer of the champions' guild", home: "inner", stance: "Thinks order depends on the rankings and the licences, and that rumours of stolen gifts are bad for business." },
    { role: "believer", n: "a mother of an Ordeal House who brings initiates to the edge to wake their gifts", home: "remote", stance: "Holds that pain is the door to the gift and that the gods are testing what people can carry." },
    { role: "survivor", n: "a giftless child who was handed the relay gift by a dying champion", home: "inner", stance: "Wants to live up to the gift, and has not yet understood who will come looking for it." },
  ],

  truths: [
    { id: "singularity", n: "The gifts are compounding", d: "Each generation's gifts are stronger and more tangled than their parents', on a curve the physicians' college has measured for thirty years. Within four more generations children will be born with gifts their bodies cannot hold, and the quickening will end humankind as its children die of their own gifts. The college stopped publishing its tables rather than say so.", tags: ["truth:gift_singularity"],
      known: [
        "Babies are being born with gifts too strong for them; one burned down a lying-in house with its first cry. The college says gift strength varies like height and has no tendency to rise.",
        "The college stopped publishing its birth tables in the year of the first too-bright child. Midwives report several such births a month, and some have stopped answering calls at night.",
        "A sealed annex in the physicians' hall holds a signed projection: at the present rate gift strength passes survivable limits in the fourth generation. The recommendation beneath it is inked over.",
        "Confirmed: gifts compound with every generation. Within four generations children will die of their own gifts at birth. The college has known for thirty years, and the champion houses are pushing the curve higher with lift serum.",
      ] },
    { id: "visitor_shards", n: "The gifts are a visitor's shards", d: "The gifts are splinters of a vast being that crossed the sky the year before the first quickened baby, and seeded humanity in order to study it. Trauma wakes gifts because the visitor is studying how people fight, which is why the Ordeal Houses get results. When the study is complete, it will return to collect what it learned.", tags: ["truth:visitor_shards"],
      known: [
        "Late gifts wake under terror or grief. The college says fear quickens the blood. The Ordeal Houses drown and starve their initiates to wake them, and many come out shining.",
        "Old star-tables record a light that crossed the sky the year before the first quickened baby, called 'the guest'. One town, where a glassy splinter lies under the well, has no working gifts at all.",
        "A late bloomer says that when the gift woke, something as wide as the sky looked at them like a fisherman at a net. Lines scored into a blast-bowl show the world with a ring around it, and a tick.",
        "Confirmed: the gifts are splinters of a vast visitor that seeded humanity to study how it fights. Pain wakes gifts because pain is the experiment. When the study is complete, the visitor will come back for its pieces.",
      ] },
    { id: "first_thief", n: "The first gift was a thief", d: "The very first quickened child had a twin who could take gifts and give them, and took his brother's on the first night. Every great line is descended from gifts he handed out, and he is still alive, wearing a dozen of them. A secret relay of a single passed-down gift has fought him for three hundred years; eight holders have died, and the ninth is a giftless child.", tags: ["truth:first_thief"],
      known: [
        "Every great house traces its gift to the same town and the same year. The guild rules that no gift can pass from one person to another, and fines anyone who claims otherwise.",
        "The first city's birth register lists twin boys on the first night, both names scraped out. A burned estate in the hills held cages and ledgers of gifts marked 'taken, handshake, no complaint'.",
        "A dying champion told a nurse that the gift was a relay, handed on for three hundred years to fight a man who takes gifts, and that the ninth holder must be found before he finds them.",
        "Confirmed: the first quickened child's twin takes and gives gifts. He founded the great houses with the gifts he handed out, still lives, and wears a dozen. Eight relay holders have died fighting him; the ninth is a giftless child.",
      ] },
  ],

  tags: ["gifted"],

  subthemes: [
    { id: "champion_guilds", n: "The Licensed Champions", d: "Champions are ranked, sponsored and painted on tavern signs. The yearly rankings decide whose shops sell and whose children are admired, and the rankings are bought.", w: 1.5, req: { any: ["urbane", "guilds", "mercantile", "has:city"] }, tags: ["theme:champion_guilds"] },
    { id: "giftless", n: "The Giftless Fifth", d: "One in five has no gift at all. They cannot hold most offices or marry into most families, and their children are not expected to be anything.", w: 1.3, req: { any: ["hierarchical", "harsh_law", "autocracy", "origin:old_dynasty"] }, truthLink: "first_thief", tags: ["theme:giftless"] },
    { id: "villain_league", n: "The League of the Burned", d: "Children orphaned by champions' collateral damage have formed a league. They are angry, partly right, and very well armed.", w: 1, req: { any: ["unstable", "poor", "urbane", "egalitarian"] }, truthLink: "first_thief", tags: ["theme:league_burned"] },
    { id: "erasing_draught", n: "The Erasing Draught", d: "A draught that strips a gift for a day, or forever, has appeared on the black market. It is made from a child's blood, and the child is missing.", w: 0.9, req: { any: ["mercantile", "has:port", "urbane", "spy_network"] }, tags: ["theme:erasing_draught"] },
    { id: "lift_serum", n: "The Lift Serum", d: "The great champion houses dose their stars with a serum that sharpens gifts. The stars burn bright and short, and the houses keep a cemetery.", w: 0.9, req: { any: ["mercantile", "gov:merchant", "free_trade", "guilds"] }, truthLink: "singularity", tags: ["theme:lift_serum"] },
    { id: "mutant_reserve", n: "The Changed Marches", d: "Those whose gifts changed their bodies past hiding have been moved to a march on the border, where they govern themselves and are not allowed to leave.", w: 0.9, req: { any: ["frontier", "harsh_law", "realm:large", "realm:vast", "isolation"] }, tags: ["theme:changed_marches"], mark: { kind: "zone", n: "The Changed Marches", color: "#7a6aa0", size: [2, 4], where: "border" } },
    { id: "trigger_cults", n: "The Ordeal Houses", d: "Cults that half-drown, starve and terrify their initiates until a late gift wakes. Some initiates come out mighty. Others are pulled dead out of the river.", w: 0.8, req: { any: ["mystic", "zealous", "sacrifice", "ascetic"] }, truthLink: "visitor_shards", tags: ["theme:ordeal_houses"] },
    { id: "first_baby", n: "The First Too-Bright Child", d: "A baby was born last spring whose gift burned down the lying-in house. Physicians have been sent from every court to watch the child, and to wait for the next.", w: 0.7, truthLink: "singularity", tags: ["theme:bright_child"] },
    { id: "champion_academy", n: "The Champions' Academy", d: "An elite school takes the best gifted children of the realm and trains them for licences. Its entrance trial is cried in every square and printed in every gossip sheet.", w: 1.2, req: { any: ["academies", "scholarly", "standing_army", "urbane"] }, tags: ["theme:champion_academy"] },
    { id: "gift_witch_hunts", n: "The Old Fear", d: "In the hill country the quickening came late, and the old fear never left. Gifted babies are still left on hillsides, and gifted adults keep their hands in their pockets.", w: 0.9, req: { any: ["zealous", "insular", "tribal", "mountain_folk", "backward"] }, tags: ["theme:old_fear"] },
    { id: "deep_prison", n: "The Pit", d: "The worst of the gifted are kept in a prison sunk deep in a mountain, each in a cell built against their gift. The cells are getting harder to design.", w: 0.8, req: { any: ["mountain", "harsh_law", "autocracy"] }, truthLink: "singularity", tags: ["theme:deep_prison"] },
  ],

  sites: [
    { id: "first_city", n: "The Lantern Birthplace at $", kind: "shrine", where: "inner", truthLink: "first_thief", d: "The town where the first glowing baby was born.",
      layers: {
        surface: { n: "Here the light first came", text: "A modest house in {place} kept as a shrine, with a painted sign: 'Here the light first came'. Pilgrims leave about 3,000 candles a year by the keeper's count. The guild pays for the roof, and its crest hangs over the door." },
        study: { n: "Two births", text: "The birth records of that week list two quickened babies, not one: twins born to the cooper's wife. The second name has been scraped away more deeply than the first. No later record mentions a second child at all." },
        dig: { n: "The cradle", text: "In the cellar is a cradle with two sets of tiny hand-marks burned into the wood, one hand reaching for the other. The cooper's own account of that night was sold to a collector, and is now held at {lead}.", points: "library" },
        revelation: { n: "The twin who takes", text: "The first gifted child was not alone. His twin took his gift on the first night and has been taking ever since: he handed out gifts to found the great houses, and wears a dozen himself. The guild was founded the year he turned forty. The crest over the shrine door is his." },
      } },
    { id: "chimera_lab", n: "The Stitch-House of $", kind: "ruin", where: "remote", truthLink: "first_thief", d: "A secret laboratory where brutes were built from many stolen gifts.",
      layers: {
        surface: { n: "Thudding in the hills", text: "A burned estate in the hills above {place} where shepherds hear thudding at night. It was sold in {year} to a buyer who paid in gold and never moved in. The fire came the following winter." },
        study: { n: "Cages", text: "In the cellars stand 14 cages too large for any animal, each with its own lock built against a different gift: salt for one, copper for another, one with no door at all. Some of the bars are bent outward." },
        dig: { n: "The donor ledgers", text: "Ledgers list gifts by donor: a strong arm here, regrowth there, a scream that shatters stone. Beside each name is written 'taken, handshake, no complaint'. The paper carries the watermark of a mill whose order books are kept at {lead}.", points: "archive" },
        revelation: { n: "Bodies built to hold more", text: "Gifts can be taken and stacked. The first thief took them from ordinary people with a handshake, and built bodies here to hold more of them than any human could: the stitched brutes. The donors lost their gifts and often their lives. The gold for the estate came from a great house's account." },
      } },
    { id: "null_town", n: "The Quiet Town of $", kind: "anomaly", where: "any", truthLink: "visitor_shards", d: "A town where no gift works.",
      layers: {
        surface: { n: "The town the gifted avoid", text: "A sleepy market town near {place} that the gifted avoid without knowing why. The guild has posted no champion here for 80 years. Rents are a third of the capital's, and the giftless have been moving in." },
        study: { n: "Gifts stop", text: "Inside its boundary stones, gifts simply stop. The gifted feel cold and very small. A physician measured 40 gifted visitors in {year}: every reading fell to nothing at the stones and came back a pace outside them." },
        dig: { n: "The splinter in the well", text: "Under the well lies a fragment of glassy stuff, the size of a fist, that hums at the edge of hearing. Its edges match the glass of the blast-bowls. The physicians' college took a chip of it to {lead} and has not reported back.", points: "site:birth_records" },
        revelation: { n: "Nothing is watched", text: "The gifts are splinters of the visitor, and it watches through every one. This splinter is dead, so inside the town no gift works and nothing is watched. People here sleep better, quarrel less and have more children. The college has left the town off its gift maps." },
      } },
    { id: "birth_records", n: "The Physicians' Hall of $", kind: "dig", where: "capital", truthLink: "singularity", d: "Hospital records that show gifts growing stronger every generation.",
      layers: {
        surface: { n: "The records hall", text: "A dusty records hall of the physicians' college in {place}, holding the measured gift of every child registered at four years old since the guild began: 2 million cards. Scholars may apply for access. Few are approved." },
        study: { n: "The curve", text: "Generation by generation, measured gift strength rises along a smooth and steepening curve. A clerk plotted it on the wall in chalk in {year} and was moved to another department the next day. The chalk was never washed off." },
        dig: { n: "The sealed annex", text: "A sealed annex holds a physician's projection and the year the curve goes off the page. The projection is signed. Its author left the college soon after and now lives at {lead}.", points: "cast:investigator" },
        revelation: { n: "Four generations", text: "Within four generations no child will survive its own gift at birth. The college has known for thirty years and stopped publishing its tables rather than say so. The champion houses that fund the college dose their stars with lift serum, which steepens the curve further." },
      } },
    { id: "trigger_crater", n: "The Blast-Bowl of $", kind: "anomaly", where: "remote", truthLink: "visitor_shards", d: "A crater the size of a town, made by a single gift waking.",
      layers: {
        surface: { n: "The fused bowl", text: "A perfect bowl of fused earth, a mile across, where a village of 300 stood near {place}. Nothing grows on the glass. Carters cross it at noon because it is flat and fast, and avoid it after dark." },
        study: { n: "The beaten girl", text: "Survivors from the edge say the steward was beating the miller's girl in the yard when it happened. She screamed, and the light came. The edge of the bowl stops 50 paces from where the nearest survivor stood." },
        dig: { n: "Lines in the glass", text: "At the centre is the girl's shape burned into the glass, and above it, scored into the fused ground, a pattern of lines no person drew. They make sense only from the air. A stargazer's sketch of them was sent to {lead}.", points: "library" },
        revelation: { n: "The visitor's notes", text: "When a gift wakes in agony, the visitor in the sky records it. The lines are its notes: the world with a ring around it, and a tick. It made gifts wake through pain because it is studying how people fight. The Ordeal Houses have been helping it with its work." },
      } },
  ],

  beings: [
    { id: "stitched_brute", n: "Stitched brute", kind: "beast", d: "A hulking body built to hold a dozen stolen gifts, and a mind that was never asked.", danger: 3, biomes: ["badlands", "tempforest", "grass", "dryforest"], look: { size: 3.2, group: [1, 1], move: "solo", speed: 12, col: "#3a3a3a", col2: "#a0a0a0", body: "biped", active: "night", visible: true } },
    { id: "changed_folk", n: "Changed folk", kind: "beast", d: "People of the marches whose gifts reshaped them: winged, scaled, three-armed, too tall. Wary, proud, and mostly just farming.", danger: 1, biomes: ["coldsteppe", "badlands", "alpine", "grass"], look: { size: 2.1, group: [2, 8], move: "herd", speed: 7, col: "#7a6aa0", col2: "#c0a080", body: "biped", active: "day", visible: true } },
  ],

  techs: [
    { id: "qk_birth_registry", n: "The birth registry", field: "writing", level: 1, d: "Every child's gift recorded at four years old, with its parents', in the parish books." },
    { id: "qk_licences", n: "Gift licences", field: "writing", level: 2, d: "Guild licences that allow a gift to be used in public, with ranks and duties." },
    { id: "qk_containment", n: "Gift-proof cells", field: "architecture", level: 3, d: "Prisons built against particular gifts: rubber floors, salt walls, no windows, no water." },
    { id: "qk_lineage_science", n: "Lineage science", field: "medicine", level: 3, d: "Tables that predict a child's gift from its parents', used by matchmakers and kings." },
    { id: "qk_erasing", n: "The erasing draught", field: "alchemy", level: 4, d: "A draught that strips a gift. Its making is a crime, and its source a scandal." },
    { id: "qk_lift", n: "Lift serum", field: "medicine", level: 5, d: "A serum that sharpens a gift beyond its natural limit, at a cost to the years." },
  ],

  units: [
    { id: "qk_champions", n: "Licensed champions", role: "magic", wpn: "sword", kit: "light", ranks: 1, gap: 3.5, size: 15, w: 1.2, mods: [["theme:champion_guilds", 5], ["theme:champion_academy", 3]] },
    { id: "qk_changed", n: "Changed march levy", role: "beast", mounted: 0, wpn: "axe", kit: "hide", ranks: 3, gap: 1.8, size: 60, w: 0.4, mods: [["theme:changed_marches", 10]] },
  ],

  govs: [
    { id: "qk_gift_aristocracy", n: "Gift aristocracy", d: "Rank follows the strength of one's gift, measured at four and written down forever. The strongest line rules.", tags: ["gov:gift_aristocracy", "monarchy", "autocracy"], w: 0.4, forms: ["Gifted Crown of $", "Bright Realm of $"], ruler: "First of the Bright", mods: [["theme:giftless", 6], ["hierarchical", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Trigger crater", color: "#b0a080", size: [1, 1], count: [0, 2], where: "any", d: "A bowl of fused ground where a gift woke in agony." },
  ],

  storylines: [
    { id: "qk_giftless_hero", n: "The Giftless Child of {place}", scale: "local", anchor: "town", w: 2, req: "gifted",
      stages: {
        start: { h: "A giftless child of {place} saves a stranger", b: "{person}, a giftless child of {place}, ran into a collapsing granary to drag out a stranger. Every gifted bystander had stood and watched.", wait: [1, 4], next: [{ to: "gift_given", w: 2 }, { to: "ignored", w: 1, mods: [["hierarchical", 1.5], ["harsh_law", 1.5]] }] },
        gift_given: { h: "A dying champion passes on a gift in {place}", b: "The stranger was {person2}, the greatest champion of {realm}, dying in secret. Before leaving {place}, the champion took {person}'s hand and passed on the champion's own gift. Since then, {person} has been breaking bones in every training bout.", wait: [6, 18], fx: { flag: "relay" }, next: [{ to: "academy", w: 2 }, { to: "thief_comes", w: 1, mods: [["unstable", 1.5], ["chance:low", 2]] }] },
        ignored: { h: "The brave child of {place} is forgotten", b: "No guild came for {person}. The gifted children of {place} still laugh, and {person} still runs into burning buildings.", fx: { stability: 1 }, end: true },
        academy: { h: "The child of {place} enters the Academy", b: "{person} passed the Academy trial by a margin nobody can explain and broke both arms doing it. The gossip sheets of {realm} are calling it the year of the late bloomer.", fx: { prestige: 4, science: { medicine: 0.3 } }, end: true },
        thief_comes: { h: "A smiling man visits {place}", b: "A well-dressed stranger came to {place} asking for {person} by name. He wore a dozen gifts like rings. {person} met him in the square, alone, and the square is a crater now.", fx: { pop: 0.95, unrest: 12, abandon_town: true }, end: true },
      } },
    { id: "qk_bright_child", n: "The Bright Child of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["gifted", { any: ["learned", "big", "academies", "scholarly"] }],
      stages: {
        start: { h: "A baby's gift burns a lying-in house in {capital}", b: "A newborn's first cry set a lying-in house in {capital} alight. The child lived, and burns everything she touches. Physicians are arriving from every court.", wait: [2, 5], fx: { unrest: 5 }, next: [{ to: "more_born", w: 2 }, { to: "child_saved", w: 1, mods: [["learned", 2], ["ruler:scholar", 2]] }] },
        more_born: { h: "More bright children are born in {realm}", b: "There have been six more this year. The physicians of {realm} have published nothing, and the midwives have stopped answering calls at night.", wait: [4, 10], fx: { stability: -6, flag: "bright" }, next: [{ to: "registry_law", w: 1, mods: [["autocracy", 2], ["harsh_law", 2]] }, { to: "curve_published", w: 1 }] },
        child_saved: { h: "Physicians of {capital} save the bright child", b: "{person}, a physician of {capital}, has built the child a room of wet stone and taught the baby to breathe slowly. The baby has not burned anything in a month.", fx: { discovery: "medicine", prestige: 6 }, end: true },
        registry_law: { h: "{ruler} decrees a marriage registry", b: "No two strong gifts may now marry in {realm} without a licence. The great houses are furious, and the poor say it was always so for them.", fx: { stability: -4, unrest: 10, science: { medicine: 0.5 } }, end: true },
        curve_published: { h: "The physicians' curve is published", b: "{person2} has published the college's secret projection: in four generations, no child will survive birth. The temples of {realm} are full, and some of the champion houses have stopped having children.", fx: { stability: -10, growth: -0.002, unrest: 12 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "propaganda", reliable: false, points: "archive", who: "Champions' ranking sheet", text: "From the champions' ranking sheet printed in {place} for the spring of {year}, price one penny: 'The First Champion has never lost a bout and never will! A smile for the children, a fist for the wicked! Ranking unchanged for the 11th year!' The sheet is paid for by the First Champion's house. The First Champion has lost three bouts, all in private; the guild's file on them is in {lead}." },
    { depth: "lore", about: "power", source: "archive", bias: "official", reliable: true, who: "{official}, licensing officer, guild statute 14", text: "Guild statute 14, read aloud by {official}, licensing officer, to new applicants at {place}, {year}: 'No gift shall be used in a public way, street or market except by a licensed holder in the course of duty, or in the saving of life, which shall be proved.' The fine for a first offence is 20 crowns. Proving that a life was saved costs 30 crowns in witness fees." },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "An old weaver, to {investigator}", text: "Told by an old weaver of {place} to the physician {investigator} in {year}, while the weaver's gift was measured for the register: 'My great-grandmother remembered when nobody had gifts. She said people were kinder then, because nobody could ever be sure who was strongest. My own gift is that I never drop a thread. Write that down. Sixty-one years in the trade.'" },
    { depth: "core", about: "truth:singularity", source: "archive", bias: "redacted", reliable: "partial", plain: true, points: "site:birth_records", who: "The physicians' sealed annex", text: "From the physicians' sealed annex at {lead}, a projection signed and dated {year}: 'Plainly stated: gift strength rises with every generation. At the present rate it exceeds survivable limits in the fourth generation from now, and children will die of their own gifts at birth. First-day survival is already down 1 in 40 since the last count. Recommendation: ...' The recommendation is inked over. The annex lock was changed that week." },
    { depth: "core", about: "truth:singularity", source: "person", bias: "true", reliable: true, cost: true, who: "A midwife of {place}, to {investigator}", text: "Letter from a midwife of {place} to {investigator}, {year}: 'Third this month. The mother, {person}, has a gift of warm hands. The baby's gift was the sun. I wrapped the baby in wet sheets and they steamed dry, and then the cradle caught. We lost the child at dawn, and {person} has burned hands for life from holding on. I have delivered 400 children. I am not doing this any more.'" },
    { depth: "core", about: "truth:singularity", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, Ordeal House mother, in the square", text: "Sermon of {believer}, mother of an Ordeal House, preached in the square at {place} in {year} to about 200 people: 'The gods give a little more each time, to see if we can carry it. Your grandparents lit candles. Your children will light houses. One day we will not be able to carry it, and that will be the Judgement. Bring your children to the edge now, while they are strong enough to come back.'" },
    { depth: "core", about: "truth:singularity", source: "heretic", bias: "exaggerated", reliable: "partial", who: "Leaflet thrown over a parade", text: "Leaflet thrown from a roof over the champions' parade in {place}, {year}, about 3,000 copies: 'IN A HUNDRED YEARS YOUR GRANDCHILDREN WILL BE GODS OR ASH. ASK THE COLLEGE WHICH. ASK WHY THE COLLEGE STOPPED PUBLISHING ITS BIRTH TABLES IN THE YEAR OF THE FIRST TOO-BRIGHT CHILD. ASK WHERE THE PHYSICIANS SEND THEIR OWN CHILDREN.' The route was swept clean by noon." },
    { depth: "core", about: "truth:singularity", source: "library", bias: "official", reliable: false, who: "College yearly bulletin", text: "From the physicians' college yearly bulletin, {year}, signed by its president: 'Gift strength varies from child to child as height does, and has no tendency to rise. Alarmist curves are the work of untrained pamphleteers. The college's birth tables are withheld this year, as last year, to protect the privacy of families, and will resume in due course.'" },
    { depth: "core", about: "truth:visitor_shards", source: "ruin", bias: "true", reliable: true, points: "site:trigger_crater", who: "Lines in the blast-bowl, sketched by a stargazer", text: "Sketched from a hilltop by a stargazer of {place} in {year}: the lines scored into the glass of the blast-bowl at {lead}, which make sense only from above. They show a picture of the world, with a little ring around it and a mark like a tick. Along one edge run 1,140 short strokes in rows of ten. The stargazer notes that nobody living could have drawn them." },
    { depth: "core", about: "truth:visitor_shards", source: "person", bias: "true", reliable: "partial", plain: true, who: "A late bloomer, to {investigator}", text: "Account of {person}, a late bloomer of {place}, given to {investigator} in {year}: 'When my gift woke, I felt someone look at me. Not kindly. The way a fisherman looks at a net. For one moment I saw what was looking: a thing as wide as the sky, that broke itself into pieces and put a piece in each of us to watch how we fight. When it has seen enough, it is coming back for the pieces.'" },
    { depth: "core", about: "truth:visitor_shards", source: "traveller", bias: "garbled", reliable: "partial", points: "library", who: "An almanac-seller at the fair", text: "Patter of an almanac-seller at the fair of {place}, {year}, taken down by a bored constable: 'Old star-tables, friends! They show a light that crossed the sky the year before the first quickened baby, and in no other year. It took 40 nights to cross and shed sparks over the land, and the stargazers of the day called it the guest. Coincidence? Two pennies says not. The only full copy is in {lead}. Page one, fair copy, two pennies.' The constable bought one." },
    { depth: "core", about: "truth:visitor_shards", source: "library", bias: "official", reliable: false, who: "College handbook for parents", text: "From the college's handbook for parents, {year} edition, page 9: 'Late gifts wake under stress because fear quickens the blood. There is nothing in them that could not be explained by any competent physician. Parents are warned against the Ordeal Houses, which are unlicensed, and against stargazers, who are unqualified.'" },
    { depth: "core", about: "truth:visitor_shards", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, at the edge of the blast-bowl", text: "Statement of {person}, who was carting hay at the edge of the village when the blast-bowl was made, {year}: 'The steward was beating the miller's girl in the yard. She screamed and the light came. My house, my wife and both my boys were inside the line, with 300 others. I was 50 paces outside it. The physicians say her gift was waiting for pain to wake it. Whose idea was it to make gifts that way?'" },
    { depth: "core", about: "truth:first_thief", source: "archive", bias: "redacted", reliable: "partial", points: "site:first_city", who: "The first city's lying-in register", text: "The lying-in register of {lead}, the town of the first quickened child, entry for the first night: 'Born this night, to the cooper's wife, twin boys; the first, glowing, named ...; the second, named ...' Both names are scraped out, the second more deeply. The register's keeper reports in {year} that the page has been cut out and pasted back twice in living memory." },
    { depth: "core", about: "truth:first_thief", source: "person", bias: "true", reliable: true, plain: true, points: "cast:survivor", who: "A dying champion, taken down by a nurse", text: "Last words of a dying champion, written down by a nurse at {place} in {year}: 'Listen. The first quickened child had a twin who takes gifts and gives them, and he is still alive, wearing a dozen. Every great house got its gift from him. We are a relay: one gift, handed on, to fight him. I am the eighth. I have given it to a giftless child at {lead}. Find the ninth before he does.'" },
    { depth: "core", about: "truth:first_thief", source: "heretic", bias: "heretic", reliable: "partial", who: "Manifesto of the League of the Burned", text: "Manifesto of the League of the Burned, printed in {place} in {year}, 500 copies: 'The great houses did not earn their gifts. They were given them, by a man who is still collecting. Look at the lineage tables: 9 great houses, and every one traces its gift to the same year and the same town. Ask the houses who their godfather was.'" },
    { depth: "core", about: "truth:first_thief", source: "library", bias: "official", reliable: false, who: "{official}, guild ruling", text: "Ruling of the champions' guild, {year}, signed by {official}: 'No gift can be passed from one person to another. All such tales are fables. The Guild has examined every claim since its founding, 212 in all, and found none true. Persons claiming to have received a gift from another are to be re-measured and fined 5 crowns for the inconvenience.'" },
    { depth: "core", about: "truth:first_thief", source: "person", bias: "true", reliable: "partial", cost: true, points: "site:chimera_lab", who: "{person}, a quarry-hand, to the watch", text: "Statement of {person}, a quarry-hand of {place}, to the watch, {year}: 'A well-dressed man came to our door asking for my sister by name. Her gift was regrowth, nothing grand: a cut finger healed in a day. He shook her hand, smiling, and left. In spring she cut her hand at the quarry and bled to death like anyone. His carriage was seen going up to {lead}.'" },
    { depth: "sub", about: "sub:champion_guilds", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A cloth merchant's letter", text: "Letter from a cloth merchant in {place}, {year}: 'Every tavern sign in this city bears a champion's face; I counted 140 of them. The Seventh-ranked owns half the breweries. The First-ranked owns the Seventh. A pint of the First's own ale is two pennies dearer, and you are booed if you order anything else.'" },
    { depth: "sub", about: "sub:giftless", source: "person", bias: "true", reliable: true, who: "{person}, a giftless clerk", text: "Diary of {person}, a giftless clerk of {place}, {year}: 'I was the best scholar in the school, first in 6 subjects of 6. They gave the post to a boy who can light candles with a look. The registrar did not read my papers. He read the line that says GIFT: NONE and set them down. My mother has asked me to stop applying.'" },
    { depth: "sub", about: "sub:villain_league", source: "heretic", bias: "heretic", reliable: "partial", points: "heretic", who: "A League organiser, at a funeral", text: "Speech of a League of the Burned organiser at a funeral in {place}, {year}: 'They call the falling tower collateral. My mother was the collateral, and 30 others. The champion who knocked it down got a medal the next week. Ask them how much the tower was insured for. We did: 9,000 crowns. Ask them what our mothers were worth.' The League meets at {lead}." },
    { depth: "sub", about: "sub:erasing_draught", source: "archive", bias: "redacted", reliable: true, points: "archive", who: "Watch-house report, harbour of {place}", text: "Watch-house report, harbour of {place}, {year}, signed by the duty sergeant: 'Seized: twelve vials, blue glass, in a fish crate. Base substance: blood, a child's, gifted. Source: unknown. Matter closed by order.' The order is signed by the guild's licensing office. The vials were sent on to {lead} and have not been seen since." },
    { depth: "sub", about: "sub:mutant_reserve", source: "traveller", bias: "true", reliable: true, who: "A seed merchant in the Changed Marches", text: "Journal of a seed merchant who travelled into the Changed Marches near {place} with a permit, {year}: 'I met a woman with wings who ran the best orchard I have ever seen, 300 trees. She asked me what the capital was like. She had never been allowed to go. I said it was crowded. She said she had thought it would be.'" },
    { depth: "sub", about: "sub:trigger_cults", source: "temple", bias: "pious", reliable: "partial", points: "temple", who: "{believer}, the Ordeal House rule", text: "The rule of the Ordeal House at {place}, read to initiates by {believer}, {year}: 'You will be brought to the edge, child, for the gift waits at the edge. You will be held under water, kept from bread and left in the dark. Not all of you will come back. Those who do will shine.' Of 30 initiates that year, 19 woke a gift and 4 were pulled from the river. The house register is kept at {lead}." },
    { depth: "sub", about: "sub:deep_prison", source: "person", bias: "true", reliable: "partial", who: "A warder of the Pit", text: "Said by a warder of the Pit, the prison sunk in the mountain near {place}, to a visiting physician, {year}: 'We built a cell for a man who could pass through stone: iron walls, a copper cage inside. Took 4 years. Then his son was born, and the son can pass through anything. We have no cell for the boy. We are keeping him calm with stories.'" },
    { depth: "site", about: "site:null_town", source: "traveller", bias: "true", reliable: true, who: "A fire-champion, to the guild", text: "Letter from a licensed fire-champion passing through the quiet town of {place}, {year}, to the guild: 'Inside the boundary stones my gift was gone. I could not light a pipe. I stayed 3 nights and have never slept so well. The innkeeper says the gifted always leave within the day. I would like to apply for leave.'" },
  ],
};
