// The Shadeself: the soul stepping out as a visible guardian with one strange ability, and what the guardian really is.
export default {
  id: "shadeself",
  name: "The Shadeself",
  family: "power",
  pitch: "In a moment of crisis a person's soul steps out of them as a visible guardian with a single strange ability, and whatever hurts the guardian hurts them.",
  slots: ["mind-substrate", "power-access", "bloodline"],
  tone: ["heroic", "noir"],
  era: ["medieval", "renaissance", "industrial", "modern"],
  scale: "personal",
  genres: ["fantasy", "shonen", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "hush_below", w: 2 }, { id: "visited_ground", w: 2 }, { id: "blood_debt", w: 1.5 }, { id: "thinning", w: 1.5 }],

  power: {
    name: "the shade", user: "shade-bearer", users: "shade-bearers",
    taught: "Some people carry a second self that only steps out in need: a figure of armour, smoke, clockwork or bird-bone that stands at their shoulder. Each shade has a single gift, often absurd, always exact. Most bearers are born to it; some are woken by a wound from an old arrowhead.",
    rules: ["A shade has one gift, and only one.", "A shade cannot stray far from its bearer.", "Whatever wounds the shade wounds the bearer in the same place.", "Only another bearer can see a shade."],
    forbidden: "Taking a second wound from the arrows, and prising a shade out of its bearer.",
  },

  cast: [
    { role: "investigator", n: "a registrar of the shade register who scores and records bearers", home: "capital", stance: "Believes every shade can be measured and filed, and keeps finding entries that will not fit." },
    { role: "official", n: "a commissioner of the crown's arrow commission who licenses star-arrows", home: "capital", stance: "Holds that the arrows are too dangerous for anyone but the crown, and keeps every sale record." },
    { role: "believer", n: "the chaplain of the tide prison, writing a way to heaven in fourteen steps", home: "coast", stance: "Believes that if every soul knew its fate the world would be at peace, and that a few bones are a fair price." },
    { role: "survivor", n: "the present heir of the star-marked house, whose shade has begun to wear a white mask", home: "mountain", stance: "Wants to finish the family's enemy for good, and is afraid the enemy is already inside." },
  ],

  truths: [
    { id: "sky_arrows", n: "The arrows came from the sky", d: "Shades were very rare, three in the whole land and all of them priests, until a star fell and a smith forged seven arrowheads from its slag. The metal carries a sickness that either wakes a shade or kills; it took the smith's apprentices first. Whoever holds the arrows decides who will be powerful in the next generation, and the crown and the crime families are buying.", tags: ["truth:sky_arrows"],
      known: [
        "The crown says shades are as old as humanity and as common as they ever were. Old shepherds in the hills say there were three bearers in the whole land before a star fell, and many after it.",
        "Arrow-houses offer the poor a wound from a star-arrow: three in four die and the rest wake shades. The crown's own arrow commission keeps sale records of arrowheads sold to great houses.",
        "A forge on the bed of the star-lake held a mould for seven arrowheads, and the smith's confession cut into the anvil: the fever in the star's metal wakes a shade or kills.",
        "Confirmed: shades are woken by a sickness in fallen-star iron. Whoever holds the arrows decides who will be powerful in the next generation, and the crown and the crime families are buying them.",
      ] },
    { id: "tenant", n: "The soul has a tenant", d: "Every shade is a piece of a dead or imprisoned being that has moved into a living soul. The dark mirror-shade that sometimes turns on its bearer is not madness: it is that being waking up and taking over. The creature chained in the sunless crypt has lodged in a hundred bearers of the star-marked house, and the houses that breed bearers are breeding it.", tags: ["truth:shade_tenant"],
      known: [
        "Some bearers' shades turn on them in the middle of a fight, wearing white masks and laughing in other voices. The physicians call it a malady of overwork and prescribe three weeks' rest.",
        "Bearers of the star-marked house write of shades that speak while they sleep, say they were there first, and give thanks for the use of the house. One woke to a page written in an unknown script.",
        "In a sunless crypt, a coffin under nine chains holds the house's first enemy. Its body carries a hundred tiny scars, one for each bearer it has lodged in, and its lid is scratched from inside.",
        "Confirmed: every shade is a piece of a dead or imprisoned being living in a human soul. The mirror-shade is that being taking over, and the houses that breed bearers have been breeding it.",
      ] },
    { id: "dead_court", n: "The dead keep a court", d: "Shades are what souls become after death. To the dead, a living bearer is a clerical error, and a vast court of the dead, with thirteen companies of wardens, regulates them. The court has quietly rigged the balance between the living and the dead in its own favour: its twelfth company sells souls and keeps the valuable ones back to serve.", tags: ["truth:dead_court"],
      known: [
        "The temples teach that the dead pass freely and at once to the halls of the gods. Children in the old quarter skip a rhyme about black robes and a price the dead pay twice.",
        "Bearers see the city's dead rising single file through a dark crack in the sky over the old quarter, about forty a night, and black-robed wardens holding some of them back.",
        "A warden's ledger dropped on a rooftop lists souls held back, sent on or sold, with their prices. An apostate warden says the twelfth of the court's thirteen companies sells souls.",
        "Confirmed: shades are what souls become after death, and a court of the dead regulates the living bearers. Its wardens sell souls and keep the best back to serve, tilting the balance toward the dead.",
      ] },
  ],

  tags: ["shades"],

  subthemes: [
    { id: "star_mark", n: "The Star-Marked House", d: "A family whose bearers all carry a star-shaped birthmark has fought the same undying enemy for five generations, one heir at a time.", w: 1.2, req: { any: ["monarchy", "origin:old_dynasty", "ancestor_bound", "dynastic"] }, truthLink: "tenant", tags: ["theme:star_mark"] },
    { id: "quiet_killer", n: "The Quiet Killer", d: "A respectable clerk in a quiet town has a shade that kills without leaving a trace, and has used it thirty times. The town is pretty and peaceful, and nobody suspects a thing.", w: 1, req: { any: ["urbane", "has:city", "stable", "realm:small", "realm:mid"] }, tags: ["theme:quiet_killer"] },
    { id: "arrow_trade", n: "The Arrow-Trade", d: "A crime family offers the poor a chance: take an arrow-wound and maybe rise. Most die. The ones who live owe the family for life.", w: 1.2, req: { any: ["urbane", "mercantile", "poor", "mercenaries", "has:port"] }, truthLink: "sky_arrows", tags: ["theme:arrow_trade"] },
    { id: "shade_prison", n: "The Tide Prison", d: "A sea-fortress holds the most dangerous bearers in the realm. Its chaplain has been visiting a certain prisoner every night, and taking notes on 'the way to heaven'.", w: 0.9, req: { any: ["coastal", "harsh_law", "autocracy"] }, tags: ["theme:tide_prison"], mark: { kind: "zone", n: "The Tide Prison", color: "#4a5a6a", size: [1, 1], where: "coast" } },
    { id: "warden_rot", n: "The Wardens' Rot", d: "The black-robed wardens who send lost souls onward are being bribed. Some souls are being sent nowhere at all.", w: 0.9, req: { any: ["faith:ancestors", "pious", "organised", "ancestor_bound"] }, truthLink: "dead_court", tags: ["theme:warden_rot"] },
    { id: "mirror_rising", n: "The Mirror Rising", d: "A celebrated bearer is losing fights to their own shade, which has begun to wear a white mask and laugh in a voice that is not theirs.", w: 1, truthLink: "tenant", tags: ["theme:mirror_rising"] },
    { id: "blade_names", n: "The Blade-Naming", d: "Here, shades live in swords. Coming of age means learning your blade's true name, and some blades refuse to give it.", w: 1.1, req: { any: ["martial", "warrior_code", "hierarchical", "gov:feudal"] }, tags: ["theme:blade_naming"] },
    { id: "star_names", n: "The Constellation Register", d: "The old court astrologers named the first bearers after constellations. The register is still kept, and there are exactly as many entries as stars in those constellations.", w: 0.8, req: { any: ["faith:stars", "seers", "scholarly", "academies"] }, truthLink: "sky_arrows", tags: ["theme:star_register"] },
    { id: "mask_eaters", n: "The Masked Hungry", d: "Masked spirits roam the outskirts and eat the dead before the wardens can reach them. Lately they have started eating the living.", w: 1, req: { any: ["near:ruins", "badlands", "near:rift", "frontier"] }, truthLink: "dead_court", tags: ["theme:masked_hungry"], mark: { kind: "zone", n: "Hungry ground", color: "#3a3a4a", size: [1, 3], where: "border" } },
    { id: "bearer_quarter", n: "The Odd Quarter", d: "A district where, for no reason anyone will explain, half the residents are bearers: the baker who stops time for seven seconds, the girl who folds doors into paper. It is the strangest and safest street in the realm.", w: 1, req: { any: ["urbane", "has:city", "tolerant"] }, tags: ["theme:odd_quarter"] },
  ],

  sites: [
    { id: "arrow_crater", n: "The Star-Pit of $", kind: "dig", where: "remote", truthLink: "sky_arrows", d: "A meteor crater with arrowheads still in the slag.",
      layers: {
        surface: { n: "The star-lake", text: "A round lake in the hills above {place}, a quarter-mile across, which the locals say a star made. Nothing lives in it. Shepherds water their flocks elsewhere, and the crown's arrow commission keeps a locked hut on the shore." },
        study: { n: "Buzzing slag", text: "The shore is littered with blackened slag that buzzes faintly when held. Two of the commission's men carried pieces in their pockets in {year} and fell into a fever. One died. The other woke a shade that hears through walls." },
        dig: { n: "The forge on the lake bed", text: "On the lake bed stands an old forge and a mould for arrowheads with seven cavities, six of them crusted with slag. A confession is cut into the anvil. The commission's sale records for the seven heads are kept in {lead}.", points: "archive" },
        revelation: { n: "The sickness called a gift", text: "The arrows were made from the star, and the star carried a sickness: what people call a gift is that fever, which wakes a shade or kills. Before it fell there were three bearers in the land. The smith sold six arrows, and now the crown and the crime families decide who becomes powerful." },
      } },
    { id: "frozen_pose", n: "The Still Square of $", kind: "anomaly", where: "any", d: "Corpses frozen in identical poses in a market square.",
      layers: {
        surface: { n: "Twenty standing dead", text: "A square in the dead town of {place} where twenty people died standing in {year}. The bodies were never moved, because the first two men who tried fell asleep on the spot for a week. Crows will not land in the square." },
        study: { n: "One raised hand", text: "Every body faces the same way, with the right hand raised, as if all of them had reached for one thing at once. None shows a wound. A registrar who is also a bearer saw a faint ring of light on each raised palm." },
        dig: { n: "Shoes and slag", text: "At the spot they all face lie a pair of child's shoes and a ring of slag-iron from the star-lake. A name is scratched inside the ring. The shade register kept by a registrar at {lead} lists a bearer of that name.", points: "cast:investigator" },
        revelation: { n: "One gift, one child", text: "A single shade did this with a single gift: a child woken by an arrow-scratch, whose shade made everyone near it want what the child held. The whole square reached at once, and died reaching. The child walked away barefoot. The register scores the gift as 'unscored'." },
      } },
    { id: "sealed_crypt", n: "The Sunless Crypt of $", kind: "ruin", where: "mountain", truthLink: "tenant", d: "A manor crypt sealed against sunlight.",
      layers: {
        surface: { n: "The mirrored roof", text: "A shuttered manor near {place} whose crypt is roofed with mirrors angled to keep daylight out. The star-marked house pays two servants double wages to polish them every morning. The servants have never been told why." },
        study: { n: "The chained coffin", text: "The coffin inside is chained shut with 9 chains, each added by a different generation. Its occupant was the first enemy of the star-marked house, killed by the first heir and, the house chronicle says, killed again by every heir since." },
        dig: { n: "A hundred scars", text: "Inside the coffin is a dry body with a hundred tiny scars, one for each bearer it has lodged in. The lid is scratched from the inside. The house's chronicle, listing every heir and every cost, is kept at {lead}.", points: "cast:survivor" },
        revelation: { n: "The tenant in the line", text: "The creature in the coffin has been living in the house's children all along, a small piece in every bearer. Each heir who killed it only woke more of it. The mirror-shade that turns on a bearer is the creature taking over. The house still breeds bearers, and the present heir's shade has begun to wear a mask." },
      } },
    { id: "seminary", n: "The Fourteen Steps of $", kind: "ruin", where: "inner", d: "An abandoned seminary whose diaries describe a way to heaven in fourteen steps.",
      layers: {
        surface: { n: "Fourteen stones", text: "A roofless chapel near {place}, with a garden of fourteen paving stones laid in a spiral. The seminary closed in {year}. Pilgrims walk the spiral at night without knowing what it is for, and leave candles on the last stone." },
        study: { n: "The fourteen steps", text: "The seminary's diaries list fourteen steps: a salt-moth, a cracked bell, a lantern under water, forty bones, a quiet king and nine others. Thirteen seminarians are marked 'gone to the chaplain' in the same week." },
        dig: { n: "The unfinished diary", text: "Under the fourteenth stone is a diary in the chaplain's neat hand, ending mid-sentence on a date that has not yet come. The chaplain now serves at the tide prison, whose records are kept at {lead}.", points: "archive" },
        revelation: { n: "The way to heaven", text: "The chaplain planned to remake the world so that every living soul would know its own fate, believing it would bring peace. Each step needs a bearer's shade. The thirteen seminarians were the first steps. The chaplain needs only a few more bones, and the tide prison is full of bearers." },
      } },
    { id: "sky_crack", n: "The Upward Rain of $", kind: "anomaly", where: "capital", truthLink: "dead_court", d: "A crack in the sky over a city where souls fall upward.",
      layers: {
        surface: { n: "The dark line", text: "A thin dark line hangs over the old quarter of {place}, about the length of a street. On still nights the sick beneath it say they feel light. The physicians report that deaths there come quicker and quieter than elsewhere." },
        study: { n: "Rising single file", text: "Bearers see grey figures rising through the crack in single file from every deathbed in the city, about 40 on an ordinary night. Some stop halfway while a black-robed figure writes something down, and then they wait." },
        dig: { n: "The dropped ledger", text: "On the highest roof lies a black-robed warden's ledger, dropped or thrown away, listing each soul and the price paid for it, 600 in a month. The quarter's temple keeps the burial lists that match it, at {lead}.", points: "temple" },
        revelation: { n: "Bought and kept", text: "The dead are not sent on freely. The court's twelfth company sells them, and keeps the valuable ones back to serve, quietly tilting the balance between the living and the dead in the court's favour. The temples promise free passage, and have never once checked." },
      } },
  ],

  beings: [
    { id: "masked_hungry", n: "Masked hungry", kind: "beast", d: "A ghost that ate too many other ghosts and grew a white bone mask to hide what it became.", danger: 3, biomes: ["badlands", "grass", "tempforest", "colddesert", "desert"], look: { size: 3.5, group: [1, 3], move: "solo", speed: 14, col: "#e8e8e0", col2: "#1a1a1a", body: "biped", active: "night", visible: false } },
    { id: "stray_shade", n: "Stray shade", kind: "small", d: "A shade whose bearer died and that has not yet understood. It drifts about its old house doing the one thing it can do.", danger: 1, biomes: ["grass", "tempforest", "river", "coldsteppe"], look: { size: 1.2, group: [1, 1], move: "solo", speed: 4, col: "#8a8aa0", col2: "#d0d0f0", body: "biped", active: "dusk", visible: false } },
  ],

  techs: [
    { id: "ss_guardian_rites", n: "Guardian rites", field: "arcana", level: 1, d: "Ancestor-spirits and spirit animals called on by shamans: the first shades, half understood." },
    { id: "ss_named_blades", n: "Named blades", field: "metallurgy", level: 2, d: "Swords forged to house a shade, which wakes when its true name is spoken." },
    { id: "ss_arrows", n: "The star-arrows", field: "metallurgy", level: 3, d: "Arrowheads of fallen-star iron that wake a shade or kill the one they wound." },
    { id: "ss_shade_ranking", n: "Shade measures", field: "natural_philosophy", level: 4, d: "Shades scored for strength, speed, reach and precision, and registered like weapons." },
    { id: "ss_soul_discs", n: "Soul-discs", field: "arcana", level: 5, d: "Thin discs of bone that can hold a shade lifted out of its bearer, and slot it into another." },
  ],

  units: [
    { id: "ss_bearers", n: "Shade-bearer cadre", role: "magic", wpn: "sword", kit: "light", ranks: 1, gap: 4, size: 12, w: 0.8, mods: [["theme:blade_naming", 4], ["theme:arrow_trade", 2], ["theme:odd_quarter", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Thin district", color: "#6a6a8a", size: [1, 2], count: [0, 2], where: "inner", d: "Quarters where the dead and their wardens can be glimpsed by anyone, at dusk, if they stand still." },
  ],

  storylines: [
    { id: "ss_quiet_town", n: "The Quiet Killer of {place}", scale: "local", anchor: "town", w: 2, req: "shades",
      stages: {
        start: { h: "Another disappearance in {place}", b: "A young woman of {place} went out for bread and never came home. It is the fourth this year. The watch has no body, no blood, and no idea.", wait: [2, 5], fx: { unrest: 4 }, next: [{ to: "bearer_notices", w: 2 }, { to: "wrong_man", w: 1, mods: [["harsh_law", 2], ["ruler:paranoid", 1.5]] }] },
        bearer_notices: { h: "A young bearer of {place} sees a killer's shade", b: "{person2}, a bearer of fifteen, saw a shade with cat's ears at a clerk's window and followed it home. Now someone has followed {person2} home.", wait: [1, 4], next: [{ to: "showdown", w: 2 }, { to: "rewind", w: 1, mods: [["chance:low", 2]] }] },
        wrong_man: { h: "A drifter is hanged in {place}", b: "The watch hanged a drifter for the killings. A week later, a fifth woman vanished from the same street.", wait: [1, 3], fx: { unrest: 8, stability: -3 }, next: [{ to: "bearer_notices", w: 1 }] },
        showdown: { h: "The killer of {place} is unmasked", b: "In a rain-soaked alley the odd folk of {place} cornered {person}, the polite clerk from the tax office. The clerk's shade went down first. Then {person} died under the wheels of a cart.", fx: { stability: 6 }, end: true },
        rewind: { h: "{place} lives the same morning twice", b: "Half of {place} swears that yesterday happened twice. {person2} was dead in the first one. In the second, {person} has moved away, and nobody can remember the clerk's face.", fx: { unrest: 6, flag: "rewound" }, end: true },
      } },
    { id: "ss_arrow_house", n: "The Arrows of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["shades", { any: ["urbane", "poor", "unstable", "mercantile"] }],
      stages: {
        start: { h: "An arrow-house opens in {capital}", b: "In a back street of {capital}, {person} is offering the poor a wound from a star-arrow. Three in four die. The queue goes round the block.", wait: [2, 6], fx: { pop: 0.98, unrest: 5 }, next: [{ to: "gang_war", w: 2 }, { to: "crown_buys", w: 1, mods: [["autocracy", 2], ["ruler:ambitious", 2]] }] },
        gang_war: { h: "Shade-gangs fight for {capital}", b: "The survivors of the arrow-house are the most frightening gang in {realm}. {person2}, a newly woken dockhand, has decided to take the house down from inside.", wait: [3, 8], fx: { unrest: 12, stability: -5 }, next: [{ to: "arrows_lost", w: 1 }, { to: "new_boss", w: 1 }] },
        crown_buys: { h: "{ruler} buys the arrows", b: "The arrows of {person} are now the property of the crown, and the queue outside the palace barracks is made of soldiers.", fx: { prestige: 5, unrest: 6, science: { warfare: 0.5 } }, end: true },
        arrows_lost: { h: "The star-arrows sink in the harbour", b: "{person2} threw the arrows into the sea from the end of the pier. The gang is leaderless, and the queue has gone home.", fx: { stability: 8 }, end: true },
        new_boss: { h: "A new boss rules the arrow-house", b: "{person2} won. The house is open again, and the price has gone up.", fx: { unrest: 6, treasury: -20 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: true, who: "{person}, a carter, diary", text: "Diary of {person}, a carter of {place}, {year}: 'It came out of me when the cart overturned: a tall thing like a clock with arms. It caught the wheel before the wheel hit the child. My wrist broke when it did, in the same place as the shade's. The physician set it for 2 silver. Nobody else saw the clock. The child's mother thinks I lifted the cart.'" },
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", who: "{investigator}, preface to the shade register", text: "From the preface to the shade register at {place}, {year} edition, by its registrar {investigator}: 'A shade is the soul's will given shape: a second self that steps out of the bearer in need. It is scored from A to E for power, speed, reach, precision, endurance and growth. Shades scoring E in growth are fully formed and will not change. Shades registered to date: 1,412.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "An old ferry-woman, to a young bearer", text: "Said by an old ferry-woman of {place} to a young bearer who came asking for work, {year}, as the bearer later wrote it down: 'Bearers can always find each other. They are drawn together like iron to iron, until one of them is dead. That is why I keep to the river. I have met 6 in my life, and buried 5.'" },
    { depth: "core", about: "truth:sky_arrows", source: "ruin", bias: "true", reliable: true, plain: true, who: "The smith's confession, cut into the anvil", text: "Cut into the anvil of the slag-forge on the bed of the star-lake near {place}, found by divers in {year}: 'Seven heads from the stone that fell. The fever is in the metal. It took all my apprentices but two, and those two can do things I cannot write down, with shapes standing beside them. A wound from these heads wakes a shade or kills. God forgive me, I have sold six.'" },
    { depth: "core", about: "truth:sky_arrows", source: "archive", bias: "redacted", reliable: "partial", points: "archive", who: "Arrow commission sale record, countersigned {official}", text: "A sale record of the crown's arrow commission, {year}, countersigned by {official}: 'One arrowhead, star-iron, sold to the house of ... for the sum of ... The buyer asks that no record be kept.' The record was kept, and filed with 6 others in {lead}. Where the sums on the others can be read, each would buy a small town." },
    { depth: "core", about: "truth:sky_arrows", source: "traveller", bias: "exaggerated", reliable: "partial", points: "site:arrow_crater", who: "A shepherd of ninety, to a travelling registrar", text: "A shepherd of the hills above {place}, aged 90, to a travelling registrar in {year}: 'Before the star fell there were three bearers in the whole land, and all of them priests. After, my own grandson had one, from a scratch off an arrowhead he found by the lake. He was the only one of 4 boys who lived through the fever. The lake is up at {lead}. Nobody swims in it.'" },
    { depth: "core", about: "truth:sky_arrows", source: "library", bias: "official", reliable: false, who: "Crown notes for magistrates", text: "From the crown's 'Notes on the Shade', issued to magistrates in {year}: 'Shades are as old as humanity, and their frequency has not changed since the earliest records. The arrow tales are criminal myths spread by those who sell fakes. Magistrates should treat any claim of an arrow-woken shade as fraud, punishable by a fine of 40 crowns.'" },
    { depth: "core", about: "truth:sky_arrows", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a widow, to the arrow commission", text: "Petition of {person}, a widow of {place}, to the arrow commission, {year}: 'Your commission bought the arrow-house on Salt Lane and kept it open. My son queued for two days and took the wound for 50 crowns. The fever lasted 6 days. He did not wake a shade. Your clerk paid the 50 crowns to me and asked me to sign that he had volunteered. I signed. I want the paper back.'" },
    { depth: "core", about: "truth:tenant", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a bearer of the star-marked house", text: "Last letter of {person}, a bearer of the star-marked house, to the family, {year}: 'It speaks now when I sleep. It says it was here before me. It says it is grateful for the use of the house. This morning my hands wrote a page in a script I do not know. I have asked to be locked in the east tower. Give my sword to {survivor}, and do not let anyone open my coffin.'" },
    { depth: "core", about: "truth:tenant", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, chaplain, noted by a guard", text: "Sermon of {believer}, chaplain of the tide prison, to 30 prisoners, {year}, as noted by a guard: 'Ask your shade where it came from. If it does not answer, give thanks. If it answers, pray. If it answers in the voice of someone long dead, run, for it is not yours, and it has been waiting.' The guard notes that two prisoners wept and one laughed for an hour." },
    { depth: "core", about: "truth:tenant", source: "ruin", bias: "true", reliable: true, plain: true, points: "site:sealed_crypt", who: "Inside the chained coffin's lid", text: "Scratched inside the lid of the chained coffin in the sunless crypt of {lead}, found by {investigator} in {year}: 'They chained me, so I went into their children. Every bearer of their line carries a little of me. I count a hundred so far. When enough of me is awake in one of them, I will walk out in that body. I can wait. I am good at waiting.'" },
    { depth: "core", about: "truth:tenant", source: "library", bias: "official", reliable: false, who: "Physicians' handbook on bearers", text: "From a physicians' handbook on bearers, {place}, {year}, page 31: 'The so-called mirror-shade is a malady of the bearer's mind, brought on by overwork. It is treated with rest, herbal tinctures and the removal of mirrors from the sickroom. Three weeks' rest suffices in most cases. Reports of shades speaking in strange voices may be safely ignored.'" },
    { depth: "core", about: "truth:dead_court", source: "heretic", bias: "heretic", reliable: "partial", plain: true, points: "heretic", who: "An apostate warden's broadsheet", text: "Broadsheet of an apostate warden, nailed up in {place} in {year}: 'Hear it plainly from one who wore the black robe. Shades are what souls become when they die. A living bearer is a clerical error to the court of the dead, and the court regulates you. It has thirteen companies of wardens. The twelfth sells souls and keeps the best back to serve. I know. I was the twelfth. Find me at {lead}.'" },
    { depth: "core", about: "truth:dead_court", source: "ruin", bias: "true", reliable: true, points: "site:sky_crack", who: "A warden's dropped ledger", text: "From a warden's ledger found on the highest roof beneath the dark crack over {lead}, {year}: 'Soul of the blacksmith's wife: held back, value high, see court order 112. Family's prayers: noted. Soul of the miller: sent on, value low. Soul of the child at Bell Street: sold, 3 marks.' The ledger holds 600 entries for a single month." },
    { depth: "core", about: "truth:dead_court", source: "oral", bias: "garbled", reliable: "partial", who: "A skipping rhyme, noted by {investigator}", text: "A skipping rhyme of the old quarter of {place}, written down by {investigator} in {year}: 'Black robe, black robe, what is my price? Once for the living, and the dead pay twice.' The children skip it at dusk under the dark line in the sky. The girl who taught it said her grandmother used to sing it, and that her grandmother was kept back." },
    { depth: "core", about: "truth:dead_court", source: "temple", bias: "official", reliable: false, who: "Funeral rite of the temple", text: "Funeral rite of the temple of {deity} at {place}, {year}, as read over every grave: 'The dead pass freely and at once to the halls of {deity}. There is no court between, no ledger and no price. Weep, but pay nobody who offers to speed the soul along. The temple has received 14 complaints of such fraud this year.'" },
    { depth: "core", about: "truth:dead_court", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a blacksmith, to the temple", text: "Letter of {person}, a blacksmith of {place}, to the temple, {year}: 'My wife died in spring. Every bearer on our street says she has not gone on. They see her standing in a queue under the dark line in the sky, with a black robe beside her writing something down. I paid your priest 10 crowns for prayers. Who do I pay to get her let through?'" },
    { depth: "sub", about: "sub:star_mark", source: "archive", bias: "official", reliable: "partial", points: "cast:survivor", who: "Chronicle of the star-marked house", text: "Chronicle of the star-marked house, kept at its manor near {place}, entry for {year}: 'Each heir has borne the star. Each heir has fought the Enemy. Each heir has won, at cost.' The cost is listed in the margins in smaller letters and many hands: an eye, a wife, a voice, five years. The present heir is {survivor}, who lives at {lead}. That margin is still blank." },
    { depth: "sub", about: "sub:quiet_killer", source: "person", bias: "true", reliable: true, who: "A neighbour, to the watch", text: "Statement of a neighbour to the watch of {place}, {year}, about the clerk at number 30: 'A quiet man. Kept his hands very clean. Always asked to see my wife's hands, oddly, and said he admired them. Paid his rent on the first of every month for 12 years. I cannot believe it of him. My wife can, and she has gone to stay with her sister.'" },
    { depth: "sub", about: "sub:arrow_trade", source: "oral", bias: "true", reliable: true, points: "archive", who: "A dock-hand, to {investigator}", text: "Said by a dock-hand of {place} to {investigator}, who was registering new bearers in {year}: 'My sister took the arrow for a hundred crowns. The family that runs the arrow-house paid the crowns to me, after. She lasted four days. I am not here to register. I am here to ask whose arrow it was.' The registrar notes that the arrow-house pays its licence fee to {lead}." },
    { depth: "sub", about: "sub:shade_prison", source: "person", bias: "exaggerated", reliable: "partial", points: "site:seminary", who: "A guard of the tide prison", text: "Report of a guard of the tide prison off {place}, {year}, to the governor: 'The chaplain, {believer}, keeps a lamp burning all night in cell 14 and talks about a salt-moth and a cracked bell. The prisoners love the chaplain. That is what frightens me. The chaplain's old seminary is at {lead}. I would like someone to go and look at it.'" },
    { depth: "sub", about: "sub:mirror_rising", source: "traveller", bias: "true", reliable: "partial", who: "A spectator at the arena", text: "Letter of a spectator at the arena of {place}, {year}: 'In the third bout the champion's shade turned and struck the champion. I saw a white mask on it, and heard it laugh in a voice that was not the champion's own. The bout was stopped. Two thousand people saw it. The broadsheets the next day said the champion had slipped.'" },
    { depth: "sub", about: "sub:blade_names", source: "library", bias: "pious", reliable: "partial", who: "A sword-school primer", text: "From a sword-school primer, {place}, {year}, lesson 3: 'Sit with your blade until it speaks. If it gives you a name, you are a bearer. If it gives you a different name each night, give it back to the smith. If it gives you your own name, give it back to the smith and do not come to lessons for a week.' The school has 80 pupils and 12 named blades." },
    { depth: "sub", about: "sub:mask_eaters", source: "traveller", bias: "exaggerated", reliable: "partial", points: "archive", who: "A post-rider on the frontier road", text: "Journal of a post-rider on the frontier road near {place}, {year}: 'At the third milestone I saw a white face in the dark with nothing behind it, and heard my dead father's voice ask me to come closer. I rode the next 12 miles at a gallop and killed the horse.' The garrison's list of travellers missing on that stretch is kept at {lead}." },
    { depth: "sub", about: "sub:bearer_quarter", source: "traveller", bias: "true", reliable: true, who: "A visitor to the odd quarter", text: "Letter of a visitor to the odd quarter of {place}, {year}: 'The baker stopped time for seven seconds to catch my dropped loaf, and then apologised. Everyone on that street apologises. Of 60 houses, the landlady says 31 hold a bearer. No house there has been robbed in 20 years. Rents are double those of the next street.'" },
    { depth: "site", about: "site:seminary", source: "library", bias: "garbled", reliable: "partial", who: "A seminarian's notebook", text: "A seminarian's notebook from the fourteen-step seminary near {place}, {year}, the ink run: '...the salt-moth, the cracked bell, the lantern under water, the forty bones... the quiet king... and on the fourteenth step everyone will know their fate, and be at peace.' A boy fishing for frogs found it in the chapel well, wrapped in oilcloth. The owner's name is torn off the cover. The last page lists 13 names with a tick beside each, and a fourteenth, unticked: the chaplain's own." },
    { depth: "site", about: "site:frozen_pose", source: "traveller", bias: "true", reliable: "partial", points: "archive", who: "A tax assessor, on the dead town", text: "Report of a tax assessor sent to the dead town of {place}, {year}: 'Twenty people died standing in the market square, all facing one way, each with the right hand raised as if to take something offered. No wounds. At the spot they faced: a pair of child's shoes and a ring of dark slag-iron, which I sent to {lead}. Tax for the year: written off.'" },
  ],
};
