// The Sundered Wellspring: one source of power in two halves, one half poisoned, and the madness that unmade the last age.
export default {
  id: "sundered_wellspring",
  name: "The Sundered Wellspring",
  family: "power",
  pitch: "The source of all magic has two halves, worked differently by men and by women, and one half was poisoned in the war that sealed the dark: every man who touches it goes mad, and the last time they did, the world broke.",
  slots: ["power-source", "cosmology", "state-control", "apocalypse"],
  tone: ["mythic", "grim"],
  era: ["bronze", "medieval", "renaissance"],
  scale: "world",
  genres: ["fantasy", "mythic", "grimdark"],
  w: 1,
  excludes: ["underchord"],
  pairs: [{ id: "wheel_of_suns", w: 2.5 }, { id: "elder_lattice", w: 2 }, { id: "long_dark", w: 1.2 }, { id: "unremembering", w: 1.2 }],

  power: {
    name: "the Wellspring", user: "drawer", users: "drawers",
    taught: "All power flows from a single Wellspring with two halves. Women draw on the Yielded Half by surrendering to it; men draw on the Seized Half by wrestling it. Five threads, earth, air, fire, water and spirit, are woven into workings. Since the age of the Sundering, the Seized Half has been poisoned, and men who draw from it go mad and rot.",
    rules: ["A drawer is born with the spark or with the slow talent; neither can be taught to those without it.", "Five threads, woven together, make every working.", "Drawers linked in a circle multiply their strength; old relics multiply it further.", "Drawing too much burns the ability out forever."],
    forbidden: "A man drawing on the Seized Half; compelling another's mind; the rootflame, which unmakes a thing backwards through time.",
  },

  cast: [
    { role: "investigator", n: "an archivist of the river tower who catalogues relics of the last age", home: "inner", stance: "Wants the tower's oldest records read in full, and is beginning to suspect why they were sealed." },
    { role: "official", n: "a warden-captain of the Severers, the order that hunts men who draw", home: "capital", stance: "Believes severing is mercy and that doubt gets people killed." },
    { role: "believer", n: "a dreamwalker mother of the desert clans", home: "desert", stance: "Believes the Sisterhood stole the Wellspring and wants the clans' memory of it heard." },
    { role: "survivor", n: "a severed man from a hill village", home: "mountain", stance: "Lost the Wellspring and a son to it; wants someone to admit what was done." },
  ],

  truths: [
    { id: "seal_price", n: "The poison is the seal's price", d: "The heroes of the last age locked the dark in the prison-mountain using the Seized Half as the lock, knowing the dark's dying stroke would poison it. They voted to let every man who drew afterwards go mad. The poison and the seal are one working: whoever cleanses the Half unlocks the prison.", tags: ["truth:well_seal_price"],
      known: [
        "Every copy of the prophecy says the man who cleanses the Seized Half will both save the world and break it. Nobody in the towers has explained why curing a poison should be dangerous, and novices who ask are told it is a mystery.",
        "A mad drawer in the tower cells repeated 'clean it and you open it' four hundred times and drew a circle with two names in it. {investigator} found the same design carved at a sealed vault from the last age.",
        "Notes in the Sleeping Vault show the seal and the poison drawn as one design. The heroes of the last age expected the poison before they cast the seal, and voted seven to two to accept it.",
        "Confirmed: the poison is the lock. Half the world's drawers were driven mad on purpose to keep the dark shut in, and anyone who cleanses the Seized Half, at the colossi or anywhere, opens the prison.",
      ] },
    { id: "prison_leaking", n: "The prison is leaking", d: "The poison in the Seized Half is the dark itself, seeping out through cracks in the prison-mountain. Every man it drives mad gives it more room, and the river tower has hidden the cracks' growth for forty years. When mad drawers rave now, it is often the dark talking.", tags: ["truth:well_leaking"],
      known: [
        "Fort-lords on the Rotwood border report the rotting forest moving south a mile a year, against a mile a lifetime in their old maps. The river tower says it is wet summers and poor soil.",
        "Chained drawers at the border forts speak in a voice that is not theirs and know things they could not know, such as the hours of the watch. {official}, warden-captain of the Severers, has had the hours changed twice and left it out of every report.",
        "{investigator} climbed two hundred feet into the vent of the prison-mountain and found the rock clawed from the inside. The black smoke there matches the residue the tower scrapes from the tongues of mad drawers in its cells.",
        "Confirmed: the poison is the dark leaking through the prison wall. The tower's own survey found the vent doubling in width and filed it as weather. Every mad drawer widens the crack a little more, and the Severers cannot sever fast enough.",
      ] },
    { id: "split_on_purpose", n: "The halves were split on purpose", d: "The Wellspring was once one current that anyone could draw in full. The first council of the river tower voted nine to three to split it, keep the stronger half under its own control, and poison that half so that men who drew it could be hunted as madmen. Every severed man since has paid for that vote.", tags: ["truth:well_split"],
      known: [
        "The desert clans say their ancestors drew both halves of the Wellspring at once, men and women alike, without harm, and that the Sisterhood took that away from them. The river towers call this wilder talk and do not answer it.",
        "The oldest charter of the river tower survives only as a burned sheet. Its legible lines speak of dividing a current and preparing a justification. {investigator}, the tower archivist who transcribed it, notes that the burns were cut with a hot blade, on purpose.",
        "At the oldest column of the Glass Forest, visitors see men and women weaving together, then a council in white raising hands. {believer} says the hands belonged to clan mothers as well as sisters.",
        "Confirmed: the minutes of the first tower council record a vote to split the Wellspring, taint the greater half, and call the hunting of its drawers mercy. The madness of men who draw was manufactured, and every severing since has enforced a three-thousand-year-old vote.",
      ] },
  ],

  tags: ["wellspring"],

  subthemes: [
    { id: "white_sisterhood", n: "The Sisterhood's Counsel", d: "Oath-bound women drawers stand at every throne as advisers. They cannot lie, they cannot make weapons, and kings have learned to listen very carefully to exactly what they say.", w: 1.5, req: { any: ["monarchy", "organised", "academies", "hierarchical"] }, tags: ["theme:sisterhood"] },
    { id: "prophesied_madman", n: "The Promised Madman", d: "The prophecies say one man must draw the poisoned half to save the world, and will break it again in doing so. Three men have claimed to be him this year.", w: 1, req: { any: ["seers", "pious", "faith:stars", "mystic"] }, truthLink: "seal_price", tags: ["theme:promised_madman"] },
    { id: "leash_empire", n: "The Leash Empire", d: "Across the sea, an empire collars its drawers like hounds and sends them to war on leashes. Its ships have been seen off the coast.", w: 0.9, req: { any: ["coastal", "has:port", "autocracy", "harsh_law"] }, tags: ["theme:leash_empire"] },
    { id: "severers", n: "The Severers", d: "An order hunts men who draw and cuts them off from the Wellspring forever. Most severed men die of despair within a year. The order says it is mercy.", w: 1.3, req: { any: ["zealous", "harsh_law", "militant", "organised"] }, truthLink: "split_on_purpose", tags: ["theme:severers"] },
    { id: "schism", n: "The Two Towers", d: "The Sisterhood has split over what to do about the madman, and now two towers, two councils and two heads each call the other false.", w: 0.8, req: { any: ["unstable", "realm:large", "realm:vast", "scholarly"] }, tags: ["theme:two_towers"] },
    { id: "hidden_channelers", n: "The Sheltering Villages", d: "Hill villages quietly hide men and women who draw without a licence. Their crops are excellent, and every few years one of the men stops talking.", w: 1, req: { any: ["mountain_folk", "insular", "egalitarian", "hills"] }, truthLink: "split_on_purpose", tags: ["theme:sheltering_villages"] },
    { id: "traitors_within", n: "The Hollow Sisters", d: "Inside the Sisterhood is a hidden sisterhood sworn to the dark. Their oaths are layered underneath the true ones, and nobody knows how many there are.", w: 0.8, req: { any: ["spy_network", "organised", "urbane"] }, truthLink: "prison_leaking", tags: ["theme:hollow_sisters"] },
    { id: "rotwood", n: "The Rotwood", d: "In the far north a land of rotting forest surrounds the prison-mountain, and its border creeps south every year. Fortress-kings hold the line.", w: 1, req: { any: ["cold", "mountain", "frontier", "frontier_forts"] }, truthLink: "prison_leaking", tags: ["theme:rotwood"], mark: { kind: "zone", n: "The Rotwood", color: "#3a4a2a", size: [3, 6], where: "remote" } },
    { id: "rootflame_wars", n: "The Rootflame Wars", d: "In the last age whole cities were unmade backwards from history with the rootflame. Their names survive only in curses, and some people dream of streets that are on no map.", w: 0.7, req: { any: ["near:ruins", "scholarly", "ancestor_bound"] }, tags: ["theme:rootflame_wars"] },
    { id: "wolf_dreamers", n: "The Wolf-Dreamers", d: "A few men and women can speak to wolves in a shared dream. The Sisterhood does not know what they are and does not like it.", w: 0.8, req: { any: ["forest", "forest_folk", "cold", "nomadic"] }, tags: ["theme:wolf_dreamers"] },
    { id: "dreamwalker_mothers", n: "The Dreamwalker Mothers", d: "Among the desert clans, wise women walk in dreams and work the Wellspring their own way. The Sisterhood calls them wilders. The mothers call the Sisterhood children.", w: 0.9, req: { any: ["desert", "desert_wanderers", "nomadic", "hot"] }, truthLink: "split_on_purpose", tags: ["theme:dreamwalkers"] },
  ],

  sites: [
    { id: "glass_canyon", n: "The Glass Canyon of $", kind: "anomaly", where: "remote", d: "A glass-smooth canyon where a city was unmade.",
      layers: {
        surface: { n: "Black walls", text: "The canyon of {place} runs for six miles between walls of black glass, too smooth for any river to have cut. Herders will not water flocks on its floor. A surveyor's iron chain left there overnight in {year} was found next morning fused into the wall." },
        study: { n: "Streets in the glass", text: "Held up to noon light, the walls show faint shapes pressed flat inside them: kerbs, doorframes, a well-head, a market cross. {investigator} counted 340 doorways along the north wall and copied a shop sign whose letters no archive can read." },
        dig: { n: "No rubble", points: "archive", text: "Diggers went forty feet below the canyon floor and found no rubble, no bones and no ash. The city here was not destroyed. Seven old roads end at the canyon rim, and their milestones count down to a blank. The old road tolls are kept in {lead}." },
        revelation: { n: "The city with no name", text: "In the Rootflame Wars a mad drawer of the Seized Half burned this city backwards out of time with the rootflame, and its people never existed. The toll rolls still show a town here paying every year, with the name left blank. Later tower clerks scraped out the blank line too, to keep the ledger tidy." },
      } },
    { id: "memory_pillars", n: "The Glass Forest of $", kind: "wonder", where: "desert", truthLink: "split_on_purpose", d: "A forest of glass columns that show the memories of one's ancestors to those who walk among them.",
      layers: {
        surface: { n: "Clan ground", text: "A grove of 212 glass columns stands in the desert of {place}. Only the desert clans may walk there, and a dreamwalker mother keeps watch at its edge. The mothers leave a clay cup of water at the foot of every column. Outsiders who slip in come out weeping." },
        study: { n: "Backwards through the blood", text: "Walking between the columns, a visitor sees through a parent's eyes, then a grandparent's, one generation per column. {believer} has walked the grove thirty times and keeps a knotted cord, one knot for each ancestor seen. The longest cord in the clan has 96 knots." },
        dig: { n: "The oldest column", points: "archive", text: "At the farthest column the visions show men and women weaving together, both halves at once, and nobody going mad. Then a council in white sits at a long table and votes with raised hands. The tower's minutes of that council are said to survive in {lead}." },
        revelation: { n: "The vote", text: "The Wellspring was once one current. The first council of the river tower voted to split it and poison the stronger half, so men who drew it could be hunted as mad. Three of the nine hands raised for the motion belonged to clan mothers. The clans call the Sisterhood children, and never say who taught them." },
      } },
    { id: "twisted_ruin", n: "The Crooked Ruin of $", kind: "ruin", where: "any", d: "Ruins whose weight and direction were twisted by a madman's drawing.",
      layers: {
        surface: { n: "Sideways rain", text: "The towers of {place} lean further than stone can stand. Rain falls at a slant on still days, and a dropped coin rolls uphill toward the old palace. Carters on the salt road go the long way round, which costs them two days each way." },
        study: { n: "Down is not down", text: "{investigator} hung a plumb line at twenty points across the ruin. Each line pointed a little further toward the palace than the one before. Water in the gutters runs uphill to its gate. A child's leather ball has sat tilted on a wall-top for a century." },
        dig: { n: "The folded throne room", points: "library", text: "The throne room is folded like paper, floor meeting ceiling. A skeleton sits in the fold on a cushioned chair, beside a second chair laid with a woman's bone comb. A diary lay on the cushion. It was sent to {lead} for copying." },
        revelation: { n: "A good afternoon", text: "A drawer of the Seized Half went mad here in the last age and bent his own city in one afternoon. He lived eleven more years in it, eating from the palace stores and talking to his dead wife at the second chair. His diary is cheerful throughout. Nobody else in the city lived past that afternoon." },
      } },
    { id: "colossi", n: "The Buried Colossus of $", kind: "dig", where: "any", d: "A colossal statue, half-buried, that magnifies a drawer's power beyond reason.",
      layers: {
        surface: { n: "The head on the hill", text: "A stone head the size of a house juts from the hillside at {place}. Shepherds shelter from rain in its mouth and carve initials on its teeth; the oldest carving is 600 years old. Sheep will not graze within fifty paces of the chin." },
        study: { n: "Too much at once", text: "Drawers who touch the stone feel the Wellspring rush at them faster than anyone can hold it. A sister of the river tower burned out her ability for good in {year} after one touch to the cheek. Her report calls the head 'an amplifier, ungoverned'." },
        dig: { n: "The twin", points: "site:stasis_box", text: "Under the chin, diggers found a bronze plate engraved with a map. It marks a second head buried in another land, and says that linked, the two would reach every drawer alive. The same head is sketched in a scholar's notes at {lead}." },
        revelation: { n: "Cure or key", text: "The colossi were built by the heroes who cast the seal on the dark. In the builders' notes one hand calls them the cure for the poison; a second hand in the margin calls them the key to the prison. Both agree on the mechanism. The Sisterhood has buried this head twice, and lost the second one entirely." },
      } },
    { id: "mountain_crack", n: "The Vent of $", kind: "anomaly", where: "mountain", truthLink: "prison_leaking", d: "A crack in the prison-mountain's face, venting black smoke.",
      layers: {
        surface: { n: "Black smoke", text: "A fissure splits the face of the prison-mountain above {place}, venting black smoke in still air. The border forts light a beacon whenever the smoke thickens. They lit it nine times last year. The fort's oldest logbook records two lightings in a whole decade." },
        study: { n: "Birds that crawl", text: "The smoke smells of hot iron. Birds that fly through it drop, crawl, and do not die. The fort keeps forty of them in a wicker cage, still crawling after two winters. {official} ordered the cage burned. The garrison has not burned it." },
        dig: { n: "Claw marks", points: "archive", text: "Inside the crack the rock is scored from within, like claw marks on a door, and the edges are fresh. Beside them someone cut a tally of days, thousands of strokes long. The tower's survey of the vent, made forty years ago, is filed in {lead}." },
        revelation: { n: "Filed as weather", text: "The poison in the Seized Half is the dark itself, seeping through cracks like this one, and every mad drawer gives it room. Forty years ago the river tower measured the vent at twice its recorded width and filed the survey as weather. The council voted to tell no one. The vent is now four times as wide." },
      } },
    { id: "stasis_box", n: "The Sleeping Vault of $", kind: "dig", where: "inner", truthLink: "seal_price", d: "A vault from the old age where time stands still, full of working relics.",
      layers: {
        surface: { n: "The cube", text: "A cube of grey stone thirty feet on a side sits in the hillside at {place}. No chisel, fire or working leaves a mark on it. Villagers thresh grain on its flat top. In {year} a boy found a door in the downhill face that had not been there the day before." },
        study: { n: "Fresh bread", text: "Inside, lamps of the last age still burn, and the bread on the table is still soft. Time does not pass in the vault. {investigator} carried one loaf out for the tower; it went stale within the hour. The baker's stamp names a city nobody has heard of." },
        dig: { n: "The scholar's table", points: "site:colossi", text: "On the table lie a scholar's last notes: the seal and the poison drawn as one design, a single circle with two names. In the margin is a sketch of a giant stone head and a note that it 'must never be linked to its twin'. The head is the one at {lead}." },
        revelation: { n: "They knew", text: "The heroes of the last age sealed the dark with the Seized Half, knowing the dark's last stroke would poison it. They voted to accept that every man who drew it afterwards would go mad. The vote was seven to two. The scholar's notes end, on the next line, with a list of groceries." },
      } },
  ],

  beings: [
    { id: "beast_soldier", n: "Beast-soldier", kind: "beast", d: "A huge half-man, half-beast warrior bred by the dark in the last age. They come out of the Rotwood in war-bands every winter.", danger: 3, biomes: ["boreal", "tundra", "alpine", "tempforest"], look: { size: 2.6, group: [5, 30], move: "pack", speed: 10, col: "#3a3a2a", col2: "#8a5a3a", body: "biped", active: "night", visible: true } },
    { id: "eyeless_hunter", n: "Eyeless hunter", kind: "predator", d: "A tall, pale, eyeless shape in black that walks out of shadows and commands the beast-soldiers. Its gaze freezes the brave.", danger: 3, biomes: ["boreal", "tempforest", "tundra"], look: { size: 2, group: [1, 1], move: "solo", speed: 30, col: "#1a1a1a", col2: "#d0d0d0", body: "biped", active: "night", visible: true } },
    { id: "dream_wolf", n: "Dream-wolf", kind: "predator", d: "A grey wolf that runs in two worlds, the waking and the dreamed, and speaks to those who can hear.", danger: 1, biomes: ["boreal", "tempforest", "coldsteppe", "tundra"], look: { size: 1.3, group: [3, 9], move: "pack", speed: 50, col: "#6a6a6a", col2: "#c0c0b0", body: "quad", active: "night", visible: true } },
  ],

  techs: [
    { id: "sw_five_threads", n: "The five threads", field: "arcana", level: 1, d: "Earth, air, fire, water and spirit named, and the first workings taught." },
    { id: "sw_circles", n: "Linked circles", field: "arcana", level: 2, d: "Drawers linked in a circle, one guiding, to work far beyond any single strength." },
    { id: "sw_oath_staff", n: "The oath-staff", field: "arcana", level: 3, d: "A white staff that makes any oath sworn on it binding on the body." },
    { id: "sw_healing", n: "Woven healing", field: "medicine", level: 3, d: "Wounds closed and fevers broken by a weave, at a cost to the patient's strength." },
    { id: "sw_leash", n: "The leash", field: "metallurgy", level: 4, d: "A silver collar and bracelet that make a drawer the slave of whoever wears the bracelet." },
    { id: "sw_cleansing", n: "The cleansing", field: "natural_philosophy", level: 5, d: "A working, through the twin colossi, to purge the poison from the Seized Half." },
  ],

  units: [
    { id: "sw_sisters", n: "Sisterhood and wardens", role: "magic", wpn: "staff", kit: "robe", ranks: 2, gap: 3, size: 20, w: 0.8, mods: [["theme:sisterhood", 4], ["theme:two_towers", 2]] },
    { id: "sw_leashed", n: "Leashed drawers", role: "magic", wpn: "staff", kit: "robe", ranks: 1, gap: 4, size: 12, w: 0.3, mods: [["theme:leash_empire", 15]] },
    { id: "sw_borderguard", n: "Rotwood-border lancers", role: "cavalry", mounted: 1, wpn: "lance", kit: "plate", ranks: 2, gap: 2.8, size: 60, w: 0.6, mods: [["theme:rotwood", 8], ["frontier_forts", 2]] },
  ],

  govs: [
    { id: "sw_tower_rule", n: "Tower-rule", d: "A council of oath-bound women drawers rules from a river tower on an island in a river, and every throne sends it tribute.", tags: ["gov:tower_rule", "arcane_rule"], w: 0.3, forms: ["Tower of $", "Isle of $"], ruler: "Tower-Mother", mods: [["theme:sisterhood", 6], ["river", 2], ["arcane", 2]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Sundering scar", color: "#7a6a6a", size: [2, 4], count: [1, 2], where: "any", d: "Land torn by the last age's mad drawers: glassy chasms, mountains pushed up overnight, a sea where a plain was." },
  ],

  storylines: [
    { id: "sw_madman", n: "The Drawer of {place}", scale: "local", anchor: "town", w: 2, req: "wellspring",
      stages: {
        start: { h: "Lightning strikes a clear sky over {place}", b: "Lightning fell from a clear sky over {place} three times this week, each time near {person}, a young shepherd. {person} denies doing it, but sparks keep jumping from the shepherd's fingers.", wait: [1, 3], next: [{ to: "severers_come", w: 2 }, { to: "sister_comes", w: 1, mods: [["theme:sisterhood", 2], ["tolerant", 2]] }] },
        severers_come: { h: "The Severers ride to {place}", b: "A company of Severers under {official}, their warden-captain, has come to {place} for the shepherd. The village has hidden the shepherd in the mill, though nobody can say why they are risking it.", wait: [1, 3], next: [{ to: "severed", w: 1 }, { to: "flees", w: 2 }] },
        sister_comes: { h: "A woman of the Sisterhood visits {place}", b: "{person2}, a sister of the river tower, has come to {place}. The sister will not say who sent word. The sister wants the shepherd, and the Severers are a day behind.", wait: [1, 3], next: [{ to: "flees", w: 1 }, { to: "severed", w: 1 }] },
        severed: { h: "The shepherd of {place} is severed", b: "{person} was cut off from the Wellspring in the square of {place}. The shepherd has not spoken since, and goes out each night to stare at the sky.", fx: { stability: 3, unrest: 4 }, end: true },
        flees: { h: "The shepherd of {place} is gone", b: "{person} and {person2} left {place} in the night. The mill is a ring of fused stone. The prophets of {realm} are very interested.", fx: { unrest: 6, flag: "drawer_loose" }, end: true },
      } },
    { id: "sw_colossi", n: "The Cleansing of {realm}", scale: "world", anchor: "realm", w: 0.8, req: ["wellspring", { any: ["learned", "big", "prestigious", "arcane"] }],
      stages: {
        start: { h: "The colossi of {realm} are uncovered", b: "Diggers in {realm} have found both buried colossi. {person}, a drawer of the Seized Half who has not gone mad yet, says the colossi can be used to cleanse the poison.", wait: [3, 8], next: [{ to: "attempt", w: 2 }, { to: "towers_forbid", w: 1, mods: [["theme:sisterhood", 2], ["zealous", 2]] }] },
        towers_forbid: { h: "The Sisterhood forbids the cleansing", b: "The towers have declared the colossi forbidden and put a guard on each. {person} has vanished, and so has a sister of high rank.", wait: [2, 6], fx: { stability: -3 }, next: [{ to: "attempt", w: 1 }, { to: "buried_again", w: 1 }] },
        attempt: { h: "Light pours out of the colossi of {realm}", b: "For a day and a night a pillar of light stood over {realm}, and every drawer in the world felt it. The armies of the Rotwood attacked the colossi from the north.", wait: [1, 2], fx: { unrest: 10 }, next: [{ to: "cleansed", w: 1 }, { to: "seal_breaks", w: 1, mods: [["chance:low", 2], ["unstable", 1.5]] }] },
        cleansed: { h: "The Seized Half is clean", b: "The poison is gone. Men may draw without going mad for the first time in three thousand years. The Severers have no purpose, and the Sisterhood has rivals.", fx: { discovery: "arcana", prestige: 15, stability: -5 }, end: true },
        seal_breaks: { h: "The prison-mountain splits", b: "The poison came out of the Wellspring and the seal came with it. In the north, the prison-mountain broke open, and the dark it had held stepped out into the snow.", fx: { stability: -20, pop: 0.85, plague: true }, end: true },
        buried_again: { h: "The colossi of {realm} are buried again", b: "The towers' wardens filled in the digs with earth and spells. The prophecies are unchanged. The Rotwood is a mile closer.", fx: { stability: 3 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "Novices' primer of the river tower", text: "From the novices' primer of the river tower, page one, copied for every girl who shows the spark: 'Surrender, child. You cannot fight a river. Float, let it carry you, then steer. The Yielded Half is the half of the Wellspring that women draw on by giving way to it. Five threads, earth, air, fire, water and spirit, make every working. Pull too hard and you burn out for life. Of every hundred novices, twelve do.'" },
    { depth: "lore", about: "power", source: "archive", bias: "official", reliable: "partial", who: "A crown clerk's copy of the oaths", text: "The three oaths of the Sisterhood, as sworn on the white oath-staff, which binds an oath to the body; copied for the crown archive of {realm} in {year}: 'I will say nothing false. I will forge nothing with the Wellspring that cuts or burns. I will raise no working against a living soul, except the dark's.' The clerk's note beneath: 'Read these three times. A sister may stay silent. A sister may hand a smith the fire and leave before he starts work.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "A ferryman of {place}", text: "A ferryman of {place}, to passengers crossing below the Sundering scar, {year}: 'In the age of wonders, my grandmother said, ships flew and cities sang. Then the men went mad and pulled the mountains up by the roots. That ridge was a plain once, with two hundred villages on it. That is why we don't let our boys play with lightning, sir. Fare's two coppers.'" },
    { depth: "core", about: "truth:seal_price", source: "ruin", bias: "true", reliable: true, plain: true, who: "A scholar of the last age, in the Sleeping Vault", text: "Notes left on the table of the Sleeping Vault by a scholar of the last age, dated the night before the sealing: 'The seal requires the Seized Half as its lock. The enemy's counterstroke will taint that Half, and every man who draws on it afterwards will go mad. We accept this. The poison and the seal are one working. Undo one and you undo the other. Seven voted yes, two no. There is no other way.'" },
    { depth: "core", about: "truth:seal_price", source: "heretic", bias: "heretic", reliable: "partial", who: "{investigator}, archivist of the river tower", points: "site:stasis_box", text: "Written down by {investigator}, archivist of the river tower, at the bedside of a mad drawer in the tower cells, {year}: 'Clean it and you open it. Clean it and you open it.' The patient said this 412 times by my tally, then drew a circle on the sheet with two names inside it. I had not seen the design before. A mason tells me the same circle is cut over a door at {lead}." },
    { depth: "core", about: "truth:seal_price", source: "temple", bias: "pious", reliable: "partial", who: "Reader's note in the vigil book of {place}", points: "library", text: "The prophecy as read at the winter vigil in the temple of {place}, verse 41, with the reader's note in the margin: 'He shall wash the water and break the lock; he shall save the world and slay it.' Every year a novice asks how one man can do both, and every year the priest says it is a mystery. The older copy in {lead} reads differently: 'by washing the water he shall break the lock.'" },
    { depth: "core", about: "truth:seal_price", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, a severed man of the hill villages", text: "Letter of {survivor}, a severed man of the hill villages, to the river tower, {year}: 'My son drew lightning at fourteen and was raving by seventeen. Your sisters told me the poison was the dark's spite and nothing more. Now your own archivist says the poison is the lock on the prison, and that you have known for three thousand years. You took my son's mind to keep a door shut. I would have said yes if asked. Nobody asked.'" },
    { depth: "core", about: "truth:seal_price", source: "library", bias: "official", reliable: false, who: "Secretary to the Tower-Mother", text: "Public reply of the river tower on the cleansing question, signed by the Tower-Mother's secretary, {year}: 'The poison in the Seized Half is the dark's last spite and nothing more. Its cleansing would be a pure blessing, with no consequence but the end of the madness. The council has studied the matter for 300 years. Rumours that the colossi are dangerous are spread by Severers who fear for their pay.'" },
    { depth: "core", about: "truth:prison_leaking", source: "person", bias: "true", reliable: "partial", who: "The lord of a Rotwood border fort", points: "archive", text: "Letter from the lord of a border fort on the Rotwood, the rotting forest that rings the prison-mountain, to {official}, {year}: 'The Rotwood moved a mile south this year. Our family maps from eighty years back show a mile in a whole lifetime. We lost the third watchtower in spring; the timbers went soft as bread. Send men, or send priests. The tower's surveyor came and left in a day and filed a report in {lead} that I am not allowed to read.'" },
    { depth: "core", about: "truth:prison_leaking", source: "heretic", bias: "exaggerated", reliable: "partial", who: "{official}, warden-captain of the Severers", text: "Statement taken by {official}, warden-captain of the Severers, from a chained drawer at the fort of {place}, {year}: 'It is not my voice. It has not been my voice for a year. It says thank you for the room.' The prisoner then named the fort's three sentries and the hours they changed, which the prisoner had no way of knowing. I have changed the hours. I have not put this in the report." },
    { depth: "core", about: "truth:prison_leaking", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, archivist of the river tower", text: "Survey notes of {investigator}, roped 200 feet inside the vent of the prison-mountain, {year}: 'The rock is scored from inside, like a door clawed at. The black smoke is the same residue I have scraped from the tongues of mad drawers in our cells. The poison in the Seized Half is not left over from the old war. It is the dark itself, getting out here, and it is getting out faster each year.'" },
    { depth: "core", about: "truth:prison_leaking", source: "person", bias: "true", reliable: "partial", cost: true, who: "Register of the fort of {place}", text: "Register of the border fort of {place}, {year}: 'Entered: the death of {person}, aged nineteen, a drawer of the Yielded Half lent to us by the tower to burn back the Rotwood. {person} worked the fire-thread for six days. On the seventh the voice that came out was a man's, asking the garrison to open the gate. We bound the drawer to a cot. By morning {person} was dead and the trees were forty paces closer.'" },
    { depth: "core", about: "truth:prison_leaking", source: "archive", bias: "official", reliable: false, who: "Survey office of the river tower", text: "Report of the river tower's survey office to the crowns, {year}: 'The prison of the dark is whole and stable. Our surveyor inspected the vent in person and found it unchanged since the survey of forty years ago. The Rotwood's advance is a matter of wet summers and poor soil. Fort-lords who ask for more men should first drain their ditches. No further survey is needed.'" },
    { depth: "core", about: "truth:split_on_purpose", source: "traveller", bias: "true", reliable: "partial", who: "{believer}, dreamwalker mother of the desert clans", points: "site:memory_pillars", text: "Told by {believer}, a dreamwalker mother of the desert clans, to a tower envoy at {place}, {year}: 'In the glass forest I walked back 96 generations. I saw my mother's mother's mother weave with a man, both halves at once, and nobody went mad. Then I saw a long table and women in white raising their hands. Your sisters call us wilders. Walk to the oldest column at {lead}, and see whose hands they were.'" },
    { depth: "core", about: "truth:split_on_purpose", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, archivist of the river tower", points: "archive", text: "The oldest charter of the river tower, a burned sheet kept under glass, as transcribed by {investigator} in {year}: '...that the current be divided, the greater half be placed under ... and that a justification be ... to be read to the people as ... [twelve lines burned] ... signed by twelve.' Archivist's note: the burn edges are straight. This was cut with a hot blade. The copying ledger for that year should be in {lead}." },
    { depth: "core", about: "truth:split_on_purpose", source: "heretic", bias: "heretic", reliable: "partial", cost: true, who: "{survivor}, a severed man of the hill villages", text: "Last letter of {survivor}, a severed man of the hill villages, to a sister of the tower, {year}: 'They did not cut me off to save me. Before the Severers came I could lift a millstone with one thread, and I was as sane as you. Their captain told me so, laughing. It is eight months now and I wake every night reaching for a river that is not there. They cut me off because I could do what you could not.'" },
    { depth: "core", about: "truth:split_on_purpose", source: "archive", bias: "true", reliable: true, plain: true, who: "Minutes of the first tower council", text: "Minutes of the first council of the river tower, sheet three, found by {investigator} in a sealed lead box in {year}: 'Resolved, nine to three: that the Wellspring be divided; that the greater half be kept under the tower's hand; that a taint be laid on it so that men who draw it sicken; and that this be told to the people as the enemy's work. The hunting of such men shall be called mercy.'" },
    { depth: "core", about: "truth:split_on_purpose", source: "library", bias: "official", reliable: false, who: "Tower Primer of Histories", text: "From the Tower Primer of Histories, chapter one, taught in every licensed school of {realm}, {year} edition: 'The Wellspring has always had two halves, as the world has day and night. No power of man could divide it. The taint on the Seized Half was laid by the dark in the last war, and the Severers hunt only to spare the tainted ten years of suffering.'" },
    { depth: "sub", about: "sub:white_sisterhood", source: "person", bias: "true", reliable: true, who: "A king of {realm}, to the heir", points: "archive", text: "A king of {realm} to the heir, in a letter kept with the crown papers, {year}: 'The sister did not lie. She said the harvest would not fail in the east, and it did not. She said nothing about the west, where 3,000 people starved. The sisters cannot lie; the oath-staff binds them. They choose which half of a truth to give. Ask every question twice. The oaths themselves are copied in {lead}; read the gaps.'" },
    { depth: "sub", about: "sub:leash_empire", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A salt trader at {place}", text: "A salt trader's account, given at the harbour office of {place}, {year}: 'The foreign ships carried twelve women on silver leashes, collar to bracelet. The soldiers patted them like dogs. When an officer twisted a bracelet, one of the women threw lightning at a fishing boat and sank it with four men aboard. Her face did not change. The officer gave her a sugared plum, as you would a dog. I sold my cargo at a loss and sailed home that night.'" },
    { depth: "sub", about: "sub:severers", source: "temple", bias: "propaganda", reliable: false, who: "{official}, warden-captain of the Severers", text: "Notice nailed to the temple door of {place} by order of {official}, warden-captain of the Severers, {year}: 'The Severers bring mercy to the afflicted. A man who draws on the Seized Half is mad within three years. Severing ends that fate. No severed man has ever regretted it. Twenty silver is paid for the name of any man who draws. To hide one is a crime against the man's own family.'" },
    { depth: "sub", about: "sub:hidden_channelers", source: "oral", bias: "true", reliable: true, who: "A hill farmer of {place}, to a tax assessor", text: "A hill farmer of {place} to a crown tax assessor, {year}, as the assessor wrote it down: 'Our village has the best wheat for a hundred miles. Forty bushels an acre. Nobody asks why. When old Bren started talking to the walls, nobody asked about that either. We fed Bren for six years and buried Bren under the threshing floor. If the Severers ask, Bren was a weaver.'" },
    { depth: "sub", about: "sub:traitors_within", source: "person", bias: "true", reliable: "partial", who: "A novice of the river tower", points: "cast:investigator", text: "Diary of a novice of the river tower, {year}, day 112: 'Sister Ama swore the three oaths on the staff in front of all forty of us, and the staff glowed for her as for everyone. Then in the corridor she told me the Tower-Mother was sick. The Tower-Mother is not sick; I saw her at supper. Sisters cannot lie. Sister Ama did. I have written to the archivist, {lead}, to ask who else swore with her.'" },
    { depth: "sub", about: "sub:rotwood", source: "traveller", bias: "true", reliable: true, who: "A carter at the customs house of {place}", text: "A carter's statement at the customs house of {place}, on the Rotwood road, {year}: 'In the Rotwood the trees lean toward the road as you pass. They were straight on the way in. The flies are as big as sparrows. The soldiers of the border forts sing all night in two shifts. When I asked why, the sergeant said singing men are still men. I will not take that road again at any price.'" },
    { depth: "sub", about: "sub:wolf_dreamers", source: "oral", bias: "garbled", reliable: "partial", who: "Parish book of {place}", text: "Entry in the parish book of {place}, in the priest's hand, {year}: 'Buried this day, the woodcutter Tamas, aged 51. Eleven grey wolves came to the edge of the trees during the service and stood there until the grave was filled. The widow says Tamas ran with them in sleep for twenty years. I have written to the tower, as I must. I have not mentioned the wolves.'" },
    { depth: "sub", about: "sub:rootflame_wars", source: "library", bias: "true", reliable: "partial", who: "{investigator}, archivist of the river tower", points: "site:twisted_ruin", text: "From {investigator}'s catalogue of the last age, entry on the rootflame, {year}: 'The rootflame is a forbidden working that burns a thing backwards out of time, so that it never was. In the Rootflame Wars at least fourteen cities were unmade; their names survive only in curses. Not every mad drawer of that age used it. Some only bent things. The best surviving example of a bent city is the ruin at {lead}.'" },
    { depth: "sub", about: "sub:prophesied_madman", source: "heretic", bias: "heretic", reliable: "partial", who: "A street preacher's handbill, {place}", points: "site:colossi", text: "Handbill of a street preacher in {place}, {year}: 'The prophecy says one man must draw the poisoned half to save the world. Three men have claimed to be him this year. Two were severed in the square. The third, a tanner, has gone north with thirty followers to find the stone head the verses call the washing-bowl. It sits on a hill at {lead}. Join him before the Severers do.'" },
    { depth: "sub", about: "sub:schism", source: "archive", bias: "official", reliable: "partial", who: "Minutes of the western council", points: "site:mountain_crack", text: "Minutes of the western council of the river tower, one of the Two Towers, {year}: 'Item 4. The eastern council claims the vent on the prison-mountain is widening. Their surveyor measured it at 600 feet; ours, at 300. Motion to send a joint survey to {lead}: defeated, seven to six, on the ground that a joint survey would imply the eastern council exists. Item 5: the price of candles.'" },
    { depth: "site", about: "site:glass_canyon", source: "library", bias: "garbled", reliable: "partial", who: "A clerk of the crown toll office", points: "archive", text: "Query of a clerk of the crown toll office at {place} to the chief auditor, {year}: 'The old road roll shows a town on the glass canyon paying 40 silver every year for 300 years, the name left blank. Nobody collects it and nobody pays it, yet the sum is carried forward each spring as owing. Do I write it off, or do I send a collector to a town that is not there? The original roll is in {lead}.'" },
  ],
};
