// The Sworn Kindred: spirit partners bound by spoken oaths, and the day every knight broke theirs.
export default {
  id: "sworn_kindred",
  name: "The Sworn Kindred",
  family: "power",
  pitch: "Fragments of the world's spirit choose humans and bond with them through spoken oaths, each sworn word unlocking more power; and long ago, on a single day, every knight of the bonded orders broke their oaths and killed their partners.",
  slots: ["divine-order", "power-access", "apocalypse"],
  tone: ["mythic", "heroic"],
  era: ["bronze", "medieval", "renaissance"],
  scale: "world",
  genres: ["fantasy", "mythic", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "ore_burning", w: 2 }, { id: "forgotten_landing", w: 2 }, { id: "elder_lattice", w: 1.5 }, { id: "long_dark", w: 1.2 }],

  power: {
    name: "the bond", user: "sworn knight", users: "sworn knights",
    taught: "Small spirits of wind, honour, truth and growth drift through the world. Rarely, one chooses a person who has survived a terrible loss and been changed by it. If that person speaks the first oath of an order, the two are bonded, and the knight can breathe in storm-charge from gems and spend it on the forces their order commands.",
    rules: ["Each order commands two of the ten forces: the pull of ground, cling, glow, change, passage, joining, strain, cleaving, wearing and growth.", "Power comes by oaths, spoken aloud, each harder to keep than the last.", "Storm-charge, caught in gems during the great storms, must be breathed in and burns away.", "Breaking an oath maims or kills the spirit and severs the bond."],
    forbidden: "Breaking a sworn oath; carrying a dead partner's blade; bonding a spirit of the enemy.",
  },

  cast: [
    { role: "investigator", n: "a storm-reader and scholar who copies the records of the old orders", home: "inner", stance: "Wants to know why every knight quit on one day, and distrusts the Devoted's answer." },
    { role: "official", n: "an archivist-priest of the Devoted, the church that keeps the histories", home: "capital", stance: "Holds that the knights were traitors and that some records are better burned." },
    { role: "believer", n: "a rhythm-folk song-keeper on a field estate", home: "border", stance: "Keeps the old songs whole and believes the storm is coming home." },
    { role: "survivor", n: "a branded former soldier who leads a slave bridge crew", home: "remote", stance: "Has lost everything once already and wants the bond to mean something this time." },
  ],

  truths: [
    { id: "mercy", n: "The abandonment was mercy", d: "The first knights were refugees who had burned their old world with these powers. On the Day of Swords they learned the same burning had begun here, and every knight broke their oaths, killing their partners, to stop it. The relic blades the princes carry now are those partners' bodies, and they are still awake.", tags: ["truth:kindred_mercy"],
      known: [
        "The Devoted teach that the knights betrayed mankind out of pride on the Day of Swords. Yet some 1,200 swords were laid down in a single hour, and nobody has explained why every order in the world agreed at once.",
        "Princes who carry relic blades say the blades scream or weep when drawn. {official} of the Devoted calls it nerves. In the Day of Swords archive, the page with the orders' resolution has been cut out with a knife.",
        "A stone box under the central blade of the sword field holds a letter from every knight. They speak of a world their ancestors burned with these powers before they came here, and of the same burning beginning again.",
        "Confirmed: the knights killed their own partners to keep their powers from burning a second world. The relic blades are those partners, still conscious. The Devoted read the letters centuries ago and preached treason anyway.",
      ] },
    { id: "enemy_is_us", n: "The enemy is us", d: "The knights' ancestors came ashore as refugees and took this land from the rhythm-folk, its first people. The 'returning darkness' of the legends was the rhythm-folk defending their homes, and the heroes of the old orders were the invaders who enslaved them. Their work-songs still hold the true history, and the new westward storm is on their side.", tags: ["truth:kindred_invaders"],
      known: [
        "The rhythm-folk, the enslaved field workers of the estates, sing work-songs no overseer bothers to learn. One verse, half-translated by {believer}, tells of strangers who came off the sea with fire in their hands and were given water.",
        "A new storm blows from the west, against every storm before it, and rhythm-folk slaves stand outside to face it. On one coast, harbour books have recorded western storms for two hundred years as routine.",
        "{investigator} paced out a work-song to a buried rhythm-folk city, centuries older than any human town. Its walls show a fleet landing, a crowd offering bowls of water, and then the same shore burning.",
        "Confirmed: the humans were the invaders. The 'returning darkness' was the rhythm-folk defending their land, and the heroes of the old orders enslaved them. The westward storm is theirs, kept alive at shrines on the coast.",
      ] },
    { id: "belief_spirits", n: "The spirits are what we think", d: "Spirits are shaped by what people believe: gods are spirits grown huge on worship, and an idea held by enough people becomes a creature. Every oath a knight speaks feeds the partner. After the Day of Swords people stopped believing in kept words, and the god of honour starved to death, helped along by the Devoted's sermons.", tags: ["truth:kindred_belief"],
      known: [
        "Sworn knights report that their spirit partners change with what the knight expects of them, and villages report fears that take on bodies. The Devoted say the gods made the spirits and no thought of man can change them.",
        "A sick-house wall at {place} carries the dying-vision of the god of honour, carved by seven patients. It says the god faded because people stopped believing in keeping their word.",
        "A cellar of old gem-engines holds spirits caught from shared feelings: fear from a plague town, pain from a battlefield. {investigator} found the craftsman's ledger listing where each one was taken.",
        "Confirmed: spirits are made of belief. Gods are spirits fed by worship, oaths feed a knight's partner, and the god of honour starved after the Day of Swords. Every sermon the Devoted preach against the spirits changes them.",
      ] },
  ],

  tags: ["spirit_bonds"],

  subthemes: [
    { id: "chasm_war", n: "The Chasm War", d: "Princes race across a shattered plain to cut gem-hearts from great chasm-beasts. The war has lasted six years; the gems pay for everything, and nobody remembers what started it.", w: 1.3, req: { any: ["martial", "warrior_code", "badlands", "steppe", "gov:feudal"] }, tags: ["theme:chasm_war"], mark: { kind: "zone", n: "The Rent Plain", color: "#7a6a5a", size: [2, 5], where: "remote" } },
    { id: "wrong_storm", n: "The Wrong-Way Storm", d: "A new storm has begun to blow from the west, against every storm that came before. Wherever it passes, the enslaved rhythm-folk stop working and begin to sing.", w: 0.9, truthLink: "enemy_is_us", tags: ["theme:wrong_storm"] },
    { id: "broken_soldier", n: "The Fourth Oath", d: "A soldier who has lost everything is said to be close to speaking an oath that no knight has spoken since the abandonment. Every faction wants to be in the room when he does.", w: 1, req: { any: ["martial", "standing_army", "levies", "warrior_code"] }, tags: ["theme:fourth_oath"] },
    { id: "rhythm_folk", n: "The Rhythm-Folk", d: "A marbled-skinned people work the fields as slaves, dull and obedient, without their old rhythms. Some have begun to hum again.", w: 1.3, req: { any: ["hierarchical", "harsh_law", "autocracy", "levies"] }, truthLink: "enemy_is_us", tags: ["theme:rhythm_folk"] },
    { id: "tower_city", n: "The Tower in the Clouds", d: "A lost mountain citadel of the old orders has been found, dead and dark, its crystal veins empty. Whoever lights it again commands the gateways it once held.", w: 0.8, req: { any: ["mountain", "near:ruins", "scholarly", "origin:ruin_heirs"] }, truthLink: "mercy", tags: ["theme:tower_city"], mark: { kind: "zone", n: "The Dark Tower-Valley", color: "#8a9aa0", size: [1, 2], where: "mountain" } },
    { id: "bridge_crews", n: "The Bridge Crews", d: "Slaves are sent to carry bridges across the chasms under arrow-fire. One crew has stopped dying, and its leader glows faintly at night.", w: 1, req: { any: ["harsh_law", "hierarchical", "martial"] }, tags: ["theme:bridge_crews"] },
    { id: "abandonment_archive", n: "The Day of Swords", d: "Scholars fight over the archives of the day the knights laid down their blades. Somebody has been destroying them, one library at a time, very carefully.", w: 1, req: { any: ["scholarly", "academies", "learned", "pious"] }, truthLink: "mercy", tags: ["theme:day_of_swords"] },
    { id: "dead_god", n: "The Last Words of Honour", d: "The god of honour is dead. Its last messages still come as visions to the sick and dying, who carve them down. The messages are grim.", w: 0.8, req: { any: ["pious", "seers", "mystic", "faith:one_god"] }, truthLink: "belief_spirits", tags: ["theme:last_words"] },
    { id: "gem_coin", n: "The Gem Coinage", d: "Money is gems caught full of storm-charge. When storms are late, the coins dim and prices rise, and when a prince hoards light, a whole city goes dark.", w: 1.2, req: { any: ["mercantile", "urbane", "free_trade", "guilds"] }, tags: ["theme:gem_coin"] },
    { id: "secret_order", n: "The Order of Quiet", d: "One order swore to keep truths hidden for the greater good. It is still keeping them, and it has decided the world is not ready.", w: 0.9, req: { any: ["spy_network", "insular", "organised", "autocracy"] }, truthLink: "belief_spirits", tags: ["theme:order_of_quiet"] },
    { id: "storm_coast", n: "The Storm Coast", d: "On the windward coast everything hides from the great storms: grass that pulls into the ground, trees that fold, crabs as big as houses. People live in the lee of rocks and pray eastward.", w: 1, req: { any: ["coastal", "hills", "seafaring"] }, tags: ["theme:storm_coast"] },
  ],

  sites: [
    { id: "blade_field", n: "The Field of Laid Swords at $", kind: "wonder", where: "remote", truthLink: "mercy", d: "A thousand blades thrust into the stone, all abandoned on the same day.",
      layers: {
        surface: { n: "A plain of swords", text: "Some 1,200 swords stand driven into the bare rock at {place}, in rows. After centuries, none has rusted. In {year} a prince's men tried to pull one out with oxen and broke two chains. Moss will not grow within a yard of any blade." },
        study: { n: "The same hour", text: "{investigator} catalogued 300 of the blades. Each bears the mark of a different order chapter, and the wax seals on the hilts carry the same date and bell-hour. The knights who owned them walked off this field together, within one hour." },
        dig: { n: "The letter box", points: "archive", text: "Under the central blade is a stone box of folded letters, one from each knight, all saying a version of the same thing. A Devoted seal on the lid shows it was opened once before and closed again. The Devoted's register of that opening is in {lead}." },
        revelation: { n: "We will not do it again", text: "The first knights were refugees who had burned their old world with these powers. On the Day of Swords they learned the burning had begun here, and broke their oaths, killing their partners, rather than repeat it. The Devoted read these letters three hundred years ago, resealed the box, and preached that the knights were traitors." },
      } },
    { id: "dark_tower", n: "The Lightless Spire of $", kind: "ruin", where: "mountain", truthLink: "mercy", d: "A mountain tower-city whose crystal veins hold no light.",
      layers: {
        surface: { n: "Dark windows", text: "A tower the height of a mountain is cut into the peak above {place}. Its four thousand windows are dark. Goatherds use the lower halls as winter pens. A brass gate-ring wide enough for a cart stands in the great court, cold." },
        study: { n: "Dead veins", text: "Crystal runs through every wall like veins. A charged gem held against the crystal goes dull in one breath; {investigator} lost a purse of twenty gem-coins learning this. Every vein runs downward, toward the tower's heart." },
        dig: { n: "The shape in the stone", points: "site:blade_field", text: "At the heart of the tower a huge spirit-shape winds through the stone, traced in dark crystal. It has not moved since the Day of Swords. Over its chamber door is a list of the knights who served here, and a note that their blades lie at {lead}." },
        revelation: { n: "Still waiting", text: "The tower was itself a great spirit, partner to a whole order. It went dark in the hour its knights broke their oaths at the sword field to keep a second world from burning. Nobody told the tower why. The last line carved over its door, six hundred years old, is in the tower's own script: 'Which of you will come back first?'" },
      } },
    { id: "chiselled_murals", n: "The Defaced Murals of $", kind: "ruin", where: "any", d: "Murals of the abandonment with every face chiselled away.",
      layers: {
        surface: { n: "Scraped faces", text: "A gallery in an old order-house at {place} shows the Day of Swords in fourteen painted panels. Every face of every figure has been chiselled off. The order-house is a grain store now, and the miller hangs sacks over the worst of the damage." },
        study: { n: "The weepers", text: "The panels show knights laying down their swords while faceless figures around them weep. {investigator} measured the weepers: a head taller than the knights, with four-fingered hands. The chisel marks are one width throughout, one tool." },
        dig: { n: "Flecks of paint", points: "temple", text: "The plaster scrapings were never swept away. Sifted, they hold flecks of marbled red and black, the skin of the rhythm-folk. The chisel was left in a wall niche, stamped with the mark of a Devoted workshop listed in {lead}." },
        revelation: { n: "Not all human", text: "The first knights were not all human: rhythm-folk swore oaths and carried blades beside them. After the Day of Swords the Devoted sent masons to scrape every rhythm-folk face from every mural, so the field slaves would have no heroes. The bill for the chisels was paid from the crown treasury." },
      } },
    { id: "song_map", n: "The Singing Ruin of $", kind: "dig", where: "any", truthLink: "enemy_is_us", d: "A rhythm-folk song that encodes the way to a buried city.",
      layers: {
        surface: { n: "Nine beats east", text: "Field slaves near {place} sing a work-song nobody else can follow, about walking 'nine beats east and the stone sings back'. Overseers allow it because it keeps the hoes in time. {believer} knows all 31 verses and will not sing them for strangers." },
        study: { n: "Paced out", text: "Paced at a slow walk from the estate well, the song's directions lead two miles to a bare hillside. The ground there hums underfoot whenever anyone sings. A plough that struck it in {year} rang for an hour, and the ploughman sold the ox." },
        dig: { n: "The buried city", points: "site:wrong_coast", text: "Under the hill lies a rhythm-folk city older than any human town, its walls cut with songs. One wall shows a fleet landing and a crowd on the shore holding out bowls of water. Another shows shrines on a western shore, matching those at {lead}." },
        revelation: { n: "Welcome", text: "This land belonged to the rhythm-folk. The humans came ashore fleeing a world they had burned, were given water, and then took the land. The 'returning darkness' the old orders fought was the rhythm-folk defending their homes. The knights' descendants now own theirs, and set the pace of their songs." },
      } },
    { id: "gem_engine", n: "The Caged Spirits of $", kind: "dig", where: "inner", truthLink: "belief_spirits", d: "Old gem-engines with spirits trapped inside.",
      layers: {
        surface: { n: "Brass boxes", text: "Workmen clearing a cellar at {place} found 64 brass boxes, each with a glowing gem at its heart. The boxes still warm, ring or shine when spoken to. The landlord sold eight before the craft guild of {realm} seized the rest." },
        study: { n: "A spirit in each gem", text: "Under a lens, each gem holds a tiny spirit, moving. The alarm boxes hold spirits that flinch at noise; the heaters hold ones that curl like cats. {investigator} notes that spirits in the same kind of box look alike, though caught decades apart." },
        dig: { n: "The ledger", points: "library", text: "A strongbox held the craftsman's ledger: 'Fear-spirit, for alarms. Flame-spirit, for heat. Pain-spirit, best for nothing.' Each entry notes where the spirit was caught: a plague ward, a winter market, a battlefield. The guild kept copies in {lead}." },
        revelation: { n: "Made from feelings", text: "Spirits are made from what people feel and believe together. The craftsman caught fear where a town was afraid and warmth where a crowd was warm, caged them, and sold them by the dozen. Every pain-spirit came from one battlefield of the Chasm War. The guild's engines still run on them." },
      } },
    { id: "wrong_coast", n: "The Backward Shore of $", kind: "anomaly", where: "coast", truthLink: "enemy_is_us", d: "A coastline where the storms always come from the wrong side.",
      layers: {
        surface: { n: "Bent trees", text: "On the shore at {place} every tree grows bent toward the east, the wrong way for a world where the great storms blow from the east. Fishermen moor on the far side of the headland, which costs them an hour's rowing every day." },
        study: { n: "The storm book", text: "{investigator} read the harbour's storm book back 200 years. Every storm on this one shore came from the west. Elsewhere the westward storm is called new and blamed on the rhythm-folk. Here it is entered as routine, between tide tables and fish prices." },
        dig: { n: "Kept shrines", points: "cast:believer", text: "In the cliffs are rhythm-folk shrines facing west, swept clean, with fresh bowls of water in them. Overseers on the nearby estates swear no slave leaves at night. One bowl carries a song-keeper's mark: that of {lead}." },
        revelation: { n: "Called in", text: "The westward storm is not new. The rhythm-folk have called it at these shrines for centuries, keeping it alive with song until enough of them sang to send it inland. The coast's overseers saw the shrines and wrote them up as quaint. The storm is inland now, and it is on the rhythm-folk's side." },
      } },
  ],

  beings: [
    { id: "chasm_beast", n: "Chasm-beast", kind: "beast", d: "A shelled giant of the shattered plains that climbs from the chasms to cocoon in the sun, with a gem the size of a cart in its chest.", danger: 3, biomes: ["badlands", "coldsteppe", "desert"], look: { size: 12, group: [1, 1], move: "solo", speed: 6, col: "#6a5a4a", col2: "#d0a060", body: "crab", active: "day", visible: true } },
    { id: "wind_flicker", n: "Wind-flicker", kind: "small", d: "A playful ribbon of light that rides the wind and copies faces. One in a thousand is the start of a bond.", danger: 0, biomes: ["grass", "coldsteppe", "alpine", "savanna"], look: { size: 0.3, group: [1, 6], move: "swarm", speed: 40, col: "#e0f0ff", col2: "#a0c0f0", body: "bird", active: "day", visible: true } },
    { id: "rhythm_folk", n: "Rhythm-folk", kind: "beast", d: "A marbled-skinned people who change form with the season and think in rhythms, enslaved for centuries and beginning to remember.", danger: 1, biomes: ["grass", "badlands", "savanna", "coldsteppe"], look: { size: 1.9, group: [3, 15], move: "herd", speed: 6, col: "#8a4a3a", col2: "#2a2a2a", body: "biped", active: "day", visible: true } },
    { id: "shell_grazer", n: "Shell-grazer", kind: "grazer", d: "A house-sized crustacean that grazes storm-coast grass and pulls into its shell when the wind rises.", danger: 1, biomes: ["grass", "coldsteppe", "temprain"], look: { size: 4, group: [2, 6], move: "herd", speed: 3, col: "#7a6a5a", col2: "#b09070", body: "crab", active: "day", visible: true } },
  ],

  techs: [
    { id: "sk_storm_gems", n: "Storm-gems", field: "natural_philosophy", level: 1, d: "Gems left out in the great storms come back full of charge and glow for weeks." },
    { id: "sk_gem_coin", n: "Gem coinage", field: "writing", level: 2, d: "Charged gems in glass beads as money, worth more lit than dim." },
    { id: "sk_storm_plate", n: "Storm-plate", field: "metallurgy", level: 3, d: "Ancient armour that drinks charge and turns a soldier into a walking fortress." },
    { id: "sk_gem_engines", n: "Gem-engines", field: "engineering", level: 4, d: "Brass devices built around a caged spirit: heat, alarms, far-speaking pens." },
    { id: "sk_oath_record", n: "The oath-books", field: "writing", level: 4, d: "The oaths of every order found and written down again, for the first time in centuries." },
    { id: "sk_gate_rings", n: "Tower-gates", field: "arcana", level: 5, d: "The old rings that carried knights from tower-city to tower-city in a flash, relit." },
  ],

  units: [
    { id: "sk_knights", n: "Sworn knights", role: "magic", wpn: "sword", kit: "plate", ranks: 1, gap: 3.5, size: 10, w: 0.5, mods: [["theme:fourth_oath", 5], ["theme:bridge_crews", 4], ["theme:tower_city", 3]] },
    { id: "sk_bridgemen", n: "Bridge crew", role: "infantry", wpn: "spear", kit: "light", ranks: 4, gap: 1.2, size: 40, w: 0.8, mods: [["theme:bridge_crews", 8], ["theme:chasm_war", 3]] },
  ],

  faiths: [
    { id: "sk_devoted", n: "The Devoted", d: "A scholar-church of shaven priests, legally owned by the nobility, who keep the histories and teach that the knights were traitors.", tags: ["faith:devoted", "organised"], w: 0.5, names: ["The Devoted of $", "The Owned Church", "The Scribes Above"], mods: [["hierarchical", 2], ["theme:day_of_swords", 3]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Storm-scoured coast", color: "#8a8a7a", size: [2, 4], count: [1, 1], where: "coast", d: "The windward coast where the great storms make landfall and everything lives in shells." },
    { kind: "zone", n: "Blade field", color: "#b0b0c0", size: [1, 1], count: [0, 1], where: "remote", d: "A plain of abandoned swords, untouched by rust." },
  ],

  storylines: [
    { id: "sk_bridge", n: "The Bridge Crew of {realm}", scale: "realm", anchor: "realm", w: 2, req: ["spirit_bonds", { any: ["atwar", "martial", "harsh_law"] }],
      stages: {
        start: { h: "A slave bridge-crew in {realm} stops dying", b: "Bridge crews in {realm}'s war die in weeks. Crew Nine, led by a branded former soldier named {person}, has lost nobody for a month.", wait: [2, 5], next: [{ to: "glow", w: 2 }, { to: "massacred", w: 1, mods: [["ruler:cruel", 2], ["harsh_law", 1.5]] }] },
        glow: { h: "A slave glows in the camp of {realm}", b: "{person} was seen at night breathing light out of a gem. A wind-flicker follows {person} everywhere, and it has started to speak.", wait: [3, 8], fx: { flag: "bonded" }, next: [{ to: "oath", w: 2 }, { to: "princes_claim", w: 1, mods: [["hierarchical", 2], ["autocracy", 1.5]] }] },
        massacred: { h: "Crew Nine is thrown at the chasm", b: "Their officer, jealous of their luck, sent Crew Nine at the chasm without shields. No light saved them. The war goes on.", fx: { unrest: 5 }, end: true },
        oath: { h: "An oath is spoken over the chasm", b: "With Crew Nine about to be overrun, {person} spoke the words aloud. The chasm-beasts fell back from a light none of them had seen in centuries. {realm} has its first sworn knight since the Day of Swords.", fx: { prestige: 12, discovery: "arcana", stability: 4 }, end: true },
        princes_claim: { h: "The princes of {realm} claim the glowing slave", b: "{ruler} has ordered {person} brought to court in chains as a curiosity. The wind-flicker is gone. Nobody has seen it since.", fx: { stability: -2, unrest: 6 }, end: true },
      } },
    { id: "sk_song", n: "The Song of {place}", scale: "local", anchor: "town", w: 1.5, req: ["spirit_bonds", { any: ["hierarchical", "harsh_law", "levies", "theme:rhythm_folk"] }],
      stages: {
        start: { h: "The field slaves of {place} start humming", b: "The rhythm-folk of {place}, silent for generations, have begun to hum while they work. Overseers say it is harmless. The dogs will not go near them.", wait: [2, 6], next: [{ to: "storm", w: 1 }, { to: "scholar_listens", w: 1, mods: [["scholarly", 2], ["learned", 2]] }] },
        storm: { h: "A storm from the west strikes {place}", b: "A red storm blew in against the wind. When it passed, the rhythm-folk of {place} stood up straighter, their eyes glowing, and walked out of the fields together.", wait: [1, 3], fx: { unrest: 10, pop: 0.95 }, next: [{ to: "uprising", w: 1 }, { to: "exodus", w: 1 }] },
        scholar_listens: { h: "A scholar transcribes the songs of {place}", b: "{investigator}, a storm-reader and scholar, has spent a season writing down the songs, and found in them a city, a war, and the moment humans first came ashore.", fx: { discovery: "writing", stability: -3 }, end: true },
        uprising: { h: "The rhythm-folk of {place} take up arms", b: "They came back with spears and old songs. {place} is theirs, they say, as it always was.", fx: { revolt: true, unrest: 15 }, end: true },
        exodus: { h: "The rhythm-folk leave {place}", b: "They walked west, singing, and nobody dared stop them. The fields of {place} lie untended.", fx: { growth: -0.002, treasury: -30 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", who: "A court primer of {realm}", points: "temple", text: "From a court primer of {realm}, taught to princes' children, {year} copy: 'The knights of old swore oaths to small spirits, the wind-flickers and their kind, and for this were given command of two of the ten forces each. Then on one day they broke their oaths, and for this were cursed. Trust no spirit, and no one who speaks to one. Report any person seen glowing to the Devoted at {lead}.'" },
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: true, who: "{survivor}, bridge-crew leader", text: "Account of {survivor}, a branded bridge-crew leader of the Chasm War, as taken down by a Devoted scribe in {year}: 'I said the words of the first oath, and it was like breathing in the sky. The storm-gem in my fist went dark in one breath. All thirty of my crew saw me glow. Then the little light on my shoulder told me, very seriously, that now I had to mean it. I asked what happens if I don't. It did not answer.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: "partial", who: "{investigator}, storm-reader", points: "archive", text: "A skipping rhyme of the storm-coast children, noted by {investigator} at {place} in {year}: 'The storm brings light, the light brings oaths, the oaths bring sorrow, one two three.' The children jump on 'sorrow'. Their parents say it is about drink. The same three lines appear in the margin of a 600-year-old order roll kept in {lead}." },
    { depth: "core", about: "truth:mercy", source: "ruin", bias: "true", reliable: true, plain: true, who: "A knight of the wind order, Day of Swords", text: "One of the 1,200 letters in the stone box under the central blade, signed by a knight of the wind order on the Day of Swords: 'Our grandparents came here fleeing a world they burned with these powers. Today the order of truth showed us that the same burning has begun here. We will not do it twice. The only way to stop it is to break our oaths, and our oaths are our partners. Forgive us, little ones.'" },
    { depth: "core", about: "truth:mercy", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a prince of {realm}", text: "Confession of {person}, a prince of {realm}, to a priest of the Devoted, {year}: 'My relic blade screams when I draw it, and only I can hear it. It came to me at twelve, from my father, who drowned himself at thirty. Last week it said its own name and asked for its knight. I cut a man down at the chasm and it wept for an hour. The court smith says I imagine it. Forty nights without sleep, and now I know why my father went into the river.'" },
    { depth: "core", about: "truth:mercy", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, storm-reader", points: "library", text: "From the Day of Swords archive, folio 7, copied by {investigator} in {year}: 'The orders met at ... and heard testimony from the order of truth concerning the old world. Unanimous resolution: ...' The rest of the page is cut out with a knife. The folio before it has been replaced by a blank sheet of newer paper. The Devoted signed this folio out twice in one year; the lending book is in {lead}." },
    { depth: "core", about: "truth:mercy", source: "temple", bias: "official", reliable: false, who: "The Devoted's coronation chronicle", text: "The Devoted's chronicle of the Day of Swords, read aloud at every coronation in {realm}, {year} text: 'On that day the knights betrayed mankind out of pride, and abandoned us to the darkness for their own gain. They threw down 1,200 swords and walked away. The relic blades they dropped were saved by the princes, who alone kept faith. Let no one speak an oath again.'" },
    { depth: "core", about: "truth:enemy_is_us", source: "oral", bias: "true", reliable: "partial", who: "{believer}, rhythm-folk song-keeper", points: "site:song_map", text: "A rhythm-folk work-song from the estate at {place}, half-translated by {believer}, a song-keeper, in {year}: 'They came off the sea with fire in their hands. We sang them welcome. We gave them water in bowls. They did not stop.' The overseer allows it because it keeps the hoes at four beats to a row. The whole song, the song-keeper says, is cut into a wall at {lead}." },
    { depth: "core", about: "truth:enemy_is_us", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, in the buried city", text: "Survey notes of {investigator} in the buried city under the singing hill, {year}: 'By the depth of its foundations, this city is at least 800 years older than any human town. Its carvings show a fleet arriving, a crowd on the shore holding out bowls of water, then the same shore burning. The rhythm-folk lived here first. The darkness our old orders fought was them, defending their homes. We were the invaders.'" },
    { depth: "core", about: "truth:enemy_is_us", source: "heretic", bias: "heretic", reliable: "partial", who: "A runaway Devoted scholar", points: "site:chiselled_murals", text: "Pamphlet of a runaway Devoted scholar, nailed to the gates of {place}, {year}: 'The darkness of the legends had faces. I have seen them in the old order-houses, where the masons missed a few. They are the faces in our fields. Sixty thousand rhythm-folk work the estates of {realm}. Go and look at the scraped murals at {lead}, and ask why a church needs a chisel.'" },
    { depth: "core", about: "truth:enemy_is_us", source: "archive", bias: "true", reliable: "partial", cost: true, who: "Bill of sale, estate of {place}", text: "Bill of sale from the estate of {place}, {year}, in the overseer's hand: 'Sold to the mines for 40 silver, one rhythm-folk song-keeper named {person}, on the overseer's word that {person} taught the field hands the coast-song and the hands stopped work to sing it. The three children of {person} retained on the estate. Note added in autumn: the children have been heard singing it.'" },
    { depth: "core", about: "truth:enemy_is_us", source: "library", bias: "official", reliable: false, who: "Royal Bestiary of {realm}", text: "From the Royal Bestiary of {realm}, entry 'Rhythm-folk', {year} edition: 'The returning darkness was a race of monsters from beyond the world, driven out by the orders in twelve years of war. The rhythm-folk who now work our fields are a dull and docile people with no history of their own. Their songs have no words, only rhythm. They are content.'" },
    { depth: "core", about: "truth:belief_spirits", source: "person", bias: "true", reliable: "partial", who: "A sworn knight of the bridge crews", text: "Written down by a sworn knight of the bridge crews, at the spirit's own request, {year}: 'You want me to be honourable, so I am. Before you swore, I was a flicker that copied faces. If all of you wanted me cruel, I think I would be cruel instead. If nobody wanted me at all, I would be wind.' The knight adds: since then I have kept every oath on purpose, all three." },
    { depth: "core", about: "truth:belief_spirits", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A pedlar at an inn of {place}", text: "A pedlar's tale at an inn of {place}, {year}: 'In one hill village they have feared a giant black hound for a hundred years. Nobody had ever seen it; mothers used it to keep children in after dark. Last spring they saw it. It took nine sheep and a dog. The village has stopped telling the story, and the hound has stopped coming. Nobody can tell me which happened first.'" },
    { depth: "core", about: "truth:belief_spirits", source: "ruin", bias: "true", reliable: true, plain: true, who: "Seven patients of the sick-house at {place}", text: "The dying-vision of the god of honour, carved on the wall of the sick-house at {place} by the seven patients who saw it in {year}, one line each: 'I am fading because you stopped holding me. I was made of what you believed about keeping your word. When the knights broke their oaths you stopped believing it, and I starved. Every spirit is made this way. I am sorry. Hold each other instead.'" },
    { depth: "core", about: "truth:belief_spirits", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, sworn knight", text: "Letter of {survivor}, sworn knight of the bridge crews, to the Devoted of {realm}, {year}: 'You preach that my partner is a demon. Two thousand people heard your sermon in the square. Since that sermon my partner has grown teeth. Last night it bit my hand to the bone, then wept. I have lost two fingers to your doctrine. Every time you preach it gets worse. Stop.'" },
    { depth: "core", about: "truth:belief_spirits", source: "temple", bias: "pious", reliable: false, who: "{official}, priest of the Devoted", text: "Sermon of {official}, archivist-priest of the Devoted, at the high temple of {realm}, {year}: 'The gods made the spirits, not men. The One Above lives and reigns, and no thought of man can raise or lower the One Above. Those who say the god of honour died because men stopped believing are fools of six kinds, and the Devoted keep a list of their names.'" },
    { depth: "sub", about: "sub:chasm_war", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A mercenary on the Rent Plain", text: "A mercenary's letter home from the Rent Plain, {year}: 'The princes race to the chasm like boys after a ball. The gem-heart was as big as a cart wheel, and it went to the prince with the fastest bridge crew. I counted that crew afterwards: four left out of forty. The prince had the gem set in a crown by evening. Nobody here remembers why the war started. The pay is good.'" },
    { depth: "sub", about: "sub:wrong_storm", source: "person", bias: "true", reliable: true, who: "{investigator}, storm-reader", points: "site:wrong_coast", text: "Log of {investigator}, storm-reader on the estate at {place}, {year}: 'Westward storm, red lightning, nine hours, against every storm in my thirty years of records. Every rhythm-folk slave on the estate was found standing outside, facing it, smiling. I hear of one shore whose harbour books treat western storms as routine. I have written to the harbourmaster at {lead}.'" },
    { depth: "sub", about: "sub:rhythm_folk", source: "archive", bias: "propaganda", reliable: false, who: "Estate handbook of {realm}", text: "Estate handbook of {realm}, issued to overseers, section 4, {year}: 'The rhythm-folk are content in their labour and feel no hardship. Give each two bowls of meal a day. They do not sing. Should any begin to hum, separate the hummers and report it to the estate clerk. Humming is not singing, and is not to be entered in the books as singing.'" },
    { depth: "sub", about: "sub:tower_city", source: "traveller", bias: "true", reliable: "partial", who: "A climbing party of {realm}", points: "site:dark_tower", text: "Journal of a climbing party sent by the crown of {realm}, {year}: 'We climbed three days inside the tower and found a garden of stone, dry fountains, and a hundred empty chairs all facing a door with no handle. The crystal in the walls drank our lamp-gems dry by the second night. Our guide would go no further. For the record, the tower is the Lightless Spire at {lead}.'" },
    { depth: "sub", about: "sub:gem_coin", source: "oral", bias: "true", reliable: true, who: "A baker of {place}", text: "A baker of {place} to a customer's child, as overheard by a tax clerk in {year}: 'Keep your coins in the window, or the light goes out of them and I'll laugh at you. A dim coin buys half a loaf. The storms came three weeks late this year and the whole street is paying double. Meanwhile the prince's vault has had its shutters open since spring.'" },
    { depth: "sub", about: "sub:secret_order", source: "heretic", bias: "redacted", reliable: "partial", who: "A lapsed member of the Order of Quiet", points: "temple", text: "Statement of a lapsed member of the Order of Quiet, taken by {investigator} the week before the member died, {year}: 'Our oath runs: I will hide what must be hidden, for ... I may not say the rest. We number forty. We keep three truths in a vault under {lead}, and we have decided the world is not ready for any of them. Two people who asked me the end of the oath were found drowned.'" },
    { depth: "sub", about: "sub:storm_coast", source: "traveller", bias: "true", reliable: true, who: "A traveller on the storm coast", text: "A traveller's letter from the storm coast to a sister in {realm}, {year}: 'Here the grass pulls itself into the ground when you step on it. The children think it is very funny, and so did I. Every house is built in the lee of a rock, and every door faces east, to pray at the storms. A crab the size of a cart sat on the inn roof for two days. The landlord charged us extra for the view.'" },
    { depth: "sub", about: "sub:abandonment_archive", source: "archive", bias: "official", reliable: "partial", who: "{official}, archivist-priest of the Devoted", points: "site:blade_field", text: "Report of {official}, archivist-priest of the Devoted, {year}: 'Third library burned this year, at {place}; 400 volumes lost, every one on the Day of Swords. The arsonist took care to save the cookbooks. Whoever it is reads well. I suspect the Order of Quiet. I recommend we move the knights' letters out of the stone box at {lead} before they are next.'" },
    { depth: "sub", about: "sub:broken_soldier", source: "oral", bias: "exaggerated", reliable: "partial", who: "A Devoted spy in the war camp", points: "cast:survivor", text: "Camp talk on the Rent Plain, written down by a Devoted spy for {official}, {year}: 'The men say a branded soldier of the bridge crews is one word away from the fourth oath, the one no knight has spoken since the Day of Swords. Three princes have sent offers. The soldier answered none of them. The men say that if the oath is spoken, it will be by {lead}.'" },
    { depth: "site", about: "site:gem_engine", source: "person", bias: "true", reliable: "partial", who: "A craftsman's ledger, cellar of {place}", text: "A note in the margin of a craftsman's ledger, found in the cellar at {place}, dated {year}: 'The fear-spirit in alarm box 12 has been crying for a week. I did not know they could. It started the day the town heard the plague had reached the next valley. The whole street is frightened, and the box is louder each night. I will sell this box quickly.'" },
  ],
};
