// The Tally: a cold voice that ranks everyone, gates that open onto dungeons, and what the counting is for.
export default {
  id: "tally",
  name: "The Tally",
  family: "power",
  pitch: "One day the sky cracked into gates and a cold voice began giving every person a rank, and the world rearranged itself around who can clear the dungeons beyond.",
  slots: ["power-source", "world-edge", "monster-source", "economy-resource"],
  tone: ["heroic", "grim"],
  era: ["medieval", "renaissance", "industrial", "modern"],
  scale: "world",
  genres: ["fantasy", "shonen"],
  w: 0.9,
  excludes: ["kindled_age"],
  pairs: [{ id: "downward_throat", w: 2 }, { id: "elder_lattice", w: 1.5 }, { id: "watchers_dark", w: 1.5 }, { id: "unremembering", w: 1.2 }],

  power: {
    name: "the tally", user: "ranked delver", users: "ranked delvers",
    taught: "Since the Cracking, a voice that nobody can locate speaks to those it wakes, giving them a rank from the lowest letter to the highest, a calling, and a ledger of skills. The awakened enter the gates, kill what lives inside, and bring out glowing stones that now light and heat the world.",
    rules: ["A rank is given once at waking and almost never changes.", "A gate left uncleared too long breaks, and its monsters walk out.", "A calling closes some paths and opens others.", "The voice answers no questions."],
    forbidden: "Hiding a gate, killing other delvers for their spoils, and waking a second time.",
  },

  cast: [
    { role: "investigator", n: "a rank-tester of the Guild, who certifies delvers' ranks and measures gates", home: "inner", stance: "Trusts measurements over the Guild's primers, and has started to measure the wrong things." },
    { role: "official", n: "chief clerk to a gate broker, who buys and writes off gates", home: "capital", stance: "Believes every gate has a price and a village is a line in a ledger." },
    { role: "believer", n: "a Listener priest who keeps vigil at every new gate", home: "remote", stance: "Believes the voice is making the world clear, and wants everyone ranked." },
    { role: "survivor", n: "a low-ranked porter who walked out of a gate that killed the party", home: "border", stance: "Wants to know who is watching, and why the rank keeps going up." },
  ],

  truths: [
    { id: "recruitment", n: "It is a draft", d: "The voice is a recruiting sergeant for a war between powers outside the world. Each gate is a drill ground, each rank a place on a muster roll, and every lesson a gate teaches is a lesson in fighting in line. When the last gate is cleared, the real front opens, and the voice will march the world to it.", tags: ["truth:tally_draft"],
      known: [
        "Every gate teaches its delvers the same lessons: hold a line, hold a wall, fight at night, hold out for thirty days. Old delvers have begun to ask why a voice would drill farmers in formation. The Guild says the gates are a natural calamity.",
        "Beyond the gate that has stood open for forty years is a grey plain worn with drill lines, and an empty army camp sized for people. A banner over the command tent shows this world beside a number.",
        "{investigator} matched the banner's number to the Guild's register of uncleared gates. They are the same, and the banner drops by one each time word of a clearance arrives. A top-ranked delver has been ordered by the voice to report there.",
        "Confirmed: the voice is recruiting for a war outside the world. The gates are drill grounds and the ranks are a muster roll. When the last gate is cleared the front opens, and every guild clearance brings that day closer.",
      ] },
    { id: "spectacle", n: "It is a show", d: "Beings outside the world are watching the delvers and betting on them. The voice's rules are written to entertain them, its 'flaws' are crowd favourites, and its titles are applause. Every delver who dies in a gate dies for an audience, and the lowest-ranked delver who keeps climbing is the most popular act they have ever had.", tags: ["truth:tally_show"],
      known: [
        "Delvers report hearing applause or laughter in gates when someone falls, and the voice hands out titles for reckless acts. The Guild calls this gate-fever, moves the reporters to porter duty, and keeps it out of the records.",
        "A cleared gate-temple has tiers of stone seats behind its throne, enough for an audience of thousands, and a carving in the voice's own letters: 'Season one. Thank you for watching.'",
        "{investigator} found a carved token under a temple seat with odds marked on it, and nine notches matching the nine delvers who died there, in the order they died. The Guild has asked for the token back.",
        "Confirmed: beings outside the world watch the delvers and bet on them, and the voice's rules are written to entertain them. A porter of the lowest rank who keeps rising, {survivor}, is the show's favourite act.",
      ] },
    { id: "reformatting", n: "It is a rewriting", d: "The world is being turned into a dungeon. Each cleared gate writes a little more of the voice's rules over the world's old laws, so the guilds that clear gates for glowstone are paying for the rewrite. Near the oldest gates, fire already burns at numbered levels, and children are born with ranks.", tags: ["truth:tally_rewriting"],
      known: [
        "Smiths near cleared gates complain that their forges now burn at numbered levels, whatever the coal. The Guild says the laws of nature are unchanged since the Cracking, and that the smiths should buy better coal.",
        "Midwives in the town by the oldest gate report babies born with ranks. Meanwhile one hill village that has never had a gate keeps the old fire and the old weight inside its boundary stones.",
        "{investigator} measured fire and falling weight near twelve cleared and twelve uncleared gates. Near cleared ones the world follows the voice's numbers; near uncleared ones the old laws still hold.",
        "Confirmed: each cleared gate writes the voice's rules over the world's laws. The guilds that clear gates for glowstone are paying for the rewrite, and the last village with the old laws is on a broker's list for a gate licence.",
      ] },
  ],

  tags: ["tally", "gates"],

  subthemes: [
    { id: "weakest_delver", n: "The Weakest Delver", d: "A porter of the lowest rank came back from a gate that killed his whole party, and now he is the only person in the world whose rank goes up.", w: 1.2, truthLink: "spectacle", tags: ["theme:weakest_delver"] },
    { id: "rule_temple", n: "The Temple of Commandments", d: "A gate opened on a temple whose stone statues kill anyone who breaks its carved laws. One party got out. They will not talk about the laws they broke.", w: 0.9, req: { any: ["pious", "zealous", "near:ruins", "organised"] }, truthLink: "recruitment", tags: ["theme:rule_temple"] },
    { id: "red_gates", n: "The Crimson Gates", d: "Some gates close behind the party and do not reopen until the boss is dead. Time inside runs differently; delvers come out years older, or years later.", w: 1, truthLink: "reformatting", tags: ["theme:crimson_gates"] },
    { id: "broken_isle", n: "The Brood Isle", d: "A gate broke on an island and nobody cleared it. The island is a monster nation now, and the brood-queen has begun to send envoys.", w: 0.8, req: { any: ["island", "coastal", "unstable", "has:port"] }, tags: ["theme:brood_isle"], mark: { kind: "zone", n: "The Brood Isle", color: "#6a2a2a", size: [2, 4], where: "coast" } },
    { id: "stone_economy", n: "The Glowstone Economy", d: "Glowstones from the gates now light the streets and drive the mills. The guild houses that clear the gates are richer than the kings who license them.", w: 1.5, req: { any: ["mercantile", "guilds", "urbane", "free_trade"] }, tags: ["theme:glowstone"] },
    { id: "rank_race", n: "The Rank Race", d: "Realms count their high-ranked delvers the way they once counted knights. Poaching another realm's top rank is now a cause for war.", w: 1, req: { any: ["has:rival", "martial", "standing_army", "autocracy"] }, truthLink: "recruitment", tags: ["theme:rank_race"] },
    { id: "risen_lord", n: "The Lord of the Risen", d: "A delver whose calling lets him raise what he kills now walks with an army of shadow soldiers. They are obedient, silent and growing.", w: 0.6, req: { any: ["near:ruins", "faith:ancestors", "sinister", "autocracy"] }, tags: ["theme:risen_lord"] },
    { id: "endless_tower", n: "The Endless Tower", d: "A gate opened upward: a tower with no top. Those who reach the highest floor are promised a wish, and its climbers have formed a nation of their own.", w: 0.8, req: { any: ["mountain", "academies", "warrior_code", "martial"] }, truthLink: "spectacle", tags: ["theme:endless_tower"], mark: { kind: "zone", n: "The Tower's Shadow", color: "#5a5a7a", size: [1, 2], where: "inner" } },
    { id: "dungeon_cooks", n: "The Gate Cooks", d: "Delvers who must eat what they kill have turned it into a craft and a cult. The best gate-kitchens are booked a year in advance.", w: 0.9, req: { any: ["hospitable", "artisans", "urbane", "nomadic"] }, tags: ["theme:gate_cooks"] },
    { id: "voice_cults", n: "The Listeners", d: "A faith has grown up around the voice. Its priests are the unawakened, who pray to be ranked and keep a vigil at every new gate.", w: 1, req: { any: ["pious", "mystic", "zealous", "seers"] }, truthLink: "reformatting", tags: ["theme:listeners"] },
    { id: "gate_brokers", n: "The Gate Brokers", d: "Brokers buy the right to clear a gate from the crown and sell it on to guilds. A gate that nobody bids for is left to break, and the villages near it know their price.", w: 1, req: { any: ["mercantile", "gov:merchant", "republic", "has:port"] }, tags: ["theme:gate_brokers"] },
  ],

  sites: [
    { id: "empty_gate", n: "The Open Gate of $", kind: "anomaly", where: "remote", truthLink: "recruitment", d: "A gate that never closes but has nothing inside.",
      layers: {
        surface: { n: "Forty years open", text: "A gate has hung open in a field at {place} for forty years. The Guild has sent 26 parties through it. Every one found it empty and came out bored. The farmer who owns the field charges a copper to look." },
        study: { n: "The worn plain", text: "Inside is a plain under a grey sky. {investigator} walked it for two days and found paths worn into the dust in straight parallel lines, too many to count, as if an army had drilled there for years. There are no footprints, only the lines." },
        dig: { n: "The camp", points: "archive", text: "Far across the plain stands a camp: tents, banners, weapon racks, all empty, all sized for people. One banner shows this world and a number beside it, which drops by one whenever a gate is cleared. The Guild's clearance tally is kept in {lead}." },
        revelation: { n: "Muster ground", text: "This is not a dungeon. It is a mustering ground for a war outside the world, waiting for this world to finish its training. The banner's number matches the count of uncleared gates exactly. The guild houses advertise every clearance as a victory, and are paid by the crown for each one." },
      } },
    { id: "statue_temple", n: "The Smiling Statue of $", kind: "ruin", where: "any", truthLink: "spectacle", d: "A temple whose great statue smiles when someone dies.",
      layers: {
        surface: { n: "The stone giant", text: "A cleared gate-temple at {place} is a ruin now, with a stone giant on a throne at its heart. Listener pilgrims leave rank-cards at its feet. Its face is carved in a broad smile. Locals say the smile was not there before the gate was cleared." },
        study: { n: "Rules of a game", text: "The laws carved on the walls are the rules of a game: bow, pray, sing, and do not move when it looks. Of the twelve delvers who first cleared the temple, nine died breaking them. {survivor} was one of the three who walked out." },
        dig: { n: "The seats", points: "cast:survivor", text: "Behind the throne are tiers of stone seats for thousands, and the floor before them is worn smooth. Under one seat lay a carved token, like a betting slip, with nine notches. The surviving porter, {lead}, recognised the order of the notches." },
        revelation: { n: "Thank you for watching", text: "The temple was a stage and the statue was the host. The seats were built for an audience from outside the world, which bet on who would break the rules first. The nine notches on the token are the nine dead, in order. The voice gave the three survivors a title for it: Crowd Pleasers." },
      } },
    { id: "floating_ledger", n: "The Still Ledger of $", kind: "anomaly", where: "any", d: "A dead top-ranked delver whose ledger still floats above the body.",
      layers: {
        surface: { n: "Blue letters", text: "On a roadside cairn at {place}, travellers see blue letters hanging in the air at head height. Carters stop to read them. A pedlar sells chalk copies of the letters at two coppers each, and updates the copies every week." },
        study: { n: "Still counting", text: "It is a dead delver's ledger, with rank, calling and skills, still updating. {investigator} copied it daily for a month. 'Status: deceased' repeats on every line, but the experience count keeps rising, by about forty points a week, with no fighting anywhere near." },
        dig: { n: "Rank: rising", points: "library", text: "Under the cairn lies the delver, a top-ranked woman, untouched by decay after eleven years. A new line has appeared in her ledger: 'Rank: rising.' The Guild's record of her last gate, the one that killed her, is in {lead}." },
        revelation: { n: "The dead still count", text: "The voice keeps ranking people after they die, and their points keep climbing, so the count is not only for what they do here. When the Guild learned this it quietly stopped burying top-ranked delvers. It now keeps 14 of them in a guarded cellar and copies their ledgers daily." },
      } },
    { id: "silent_village", n: "The Silent Village of $", kind: "shrine", where: "remote", truthLink: "reformatting", d: "A village where the voice has never spoken.",
      layers: {
        surface: { n: "No gate", text: "A hill village at {place} has never had a gate, and none of its 300 people has ever woken. The Listeners call it cursed. Delvers come to rest here, and most leave within a week, complaining that they feel slow." },
        study: { n: "Old fire", text: "Inside the old boundary stones a delver's skills stop working, and fire burns as it did before the Cracking, hot or cold with the wood. {investigator} carried a level-three forge-stone across the line. It became an ordinary stone, and stayed one." },
        dig: { n: "The hymn stone", points: "temple", text: "Under the shrine is a stone carved with the world's old laws as hymns: how heat moves, how weight falls, how time passes. Every temple once sang them. The Listeners struck them from their books; the last copy outside this village is said to be in {lead}." },
        revelation: { n: "Written over", text: "The old laws hold here because no gate was ever cleared nearby. Everywhere else, each clearance writes the voice's rules over the world, and the guilds clear gates for profit. A day's walk away, forges already burn at numbered levels. The village is now on a broker's list for a gate licence." },
      } },
    { id: "named_monster", n: "The Named Beast of $", kind: "dig", where: "any", truthLink: "reformatting", d: "A monster with a human name in its ledger.",
      layers: {
        surface: { n: "The trophy", text: "A gate-boss killed near {place} was dragged out and displayed on the green: a horned thing the size of a hay cart. The guild that killed it charged a copper a look and took in four hundred coppers in a week." },
        study: { n: "A local name", text: "Delvers who look at the beast see its ledger, as with any monster. Where a monster's kind should be is a name: Oren Tallow, a common name in the district. {investigator} asked around. A family of Tallows farms three miles off." },
        dig: { n: "The parish book", points: "archive", text: "The parish book lists Oren Tallow as vanished in the spring the gate opened, last seen walking a dog toward it. The guild's kill-record for the beast, with its full ledger copied out, was sent to {lead}." },
        revelation: { n: "Rewritten", text: "The gates do not only make monsters; they rewrite whatever walks in. Oren Tallow went into the gate after his dog and came out as its boss. The Iron Lantern guild collected a bounty of 200 silver for him. His widow was sent the bill for the display." },
      } },
  ],

  beings: [
    { id: "gnasher", n: "Gnasher", kind: "beast", d: "The lowest gate-beast: a grey-green biped of teeth and spite, a nuisance alone and a disaster by the hundred.", danger: 1, biomes: ["tempforest", "grass", "badlands", "boreal", "dryforest"], look: { size: 1.1, group: [4, 20], move: "pack", speed: 9, col: "#5a6a3a", col2: "#a0a060", body: "biped", active: "any", visible: true } },
    { id: "broodant", n: "Broodant", kind: "beast", d: "A man-sized ant from a broken gate, organised under a queen and capable of learning.", danger: 3, biomes: ["savanna", "grass", "dryforest", "rainforest"], look: { size: 2, group: [10, 40], move: "swarm", speed: 14, col: "#3a2020", col2: "#8a3a2a", body: "insect", active: "any", visible: true } },
    { id: "tuskman", n: "Tuskman", kind: "beast", d: "A heavy, tusked gate-beast that fights in companies and carries iron it did not forge.", danger: 2, biomes: ["coldsteppe", "boreal", "alpine", "tempforest"], look: { size: 2.3, group: [3, 12], move: "pack", speed: 8, col: "#4a4a3a", col2: "#c0b090", body: "biped", active: "dusk", visible: true } },
  ],

  techs: [
    { id: "ty_rank_testing", n: "Rank testing", field: "natural_philosophy", level: 1, d: "Crystals from the gates that show a person's rank to anyone, not only to them." },
    { id: "ty_gate_charts", n: "Gate charts", field: "navigation", level: 2, d: "Maps of gates by colour and size, with the days left before each one breaks." },
    { id: "ty_monster_gear", n: "Beast-gear", field: "metallurgy", level: 2, d: "Blades and armour made from gate-beast hide, bone and fang." },
    { id: "ty_glowstone", n: "Glowstone lamps", field: "engineering", level: 3, d: "The glowing stones of the gates put to work: street lamps, kilns, mill engines." },
    { id: "ty_gate_seals", n: "Gate-seals", field: "arcana", level: 4, d: "Rings of stone that hold a gate shut a little past its breaking day." },
    { id: "ty_glowstone_works", n: "Glowstone works", field: "engineering", level: 5, d: "Great furnaces that burn crushed glowstone to drive whole cities." },
  ],

  units: [
    { id: "ty_delvers", n: "Ranked delvers", role: "magic", wpn: "sword", kit: "mail", ranks: 2, gap: 2.5, size: 25, w: 1.5, mods: [["theme:glowstone", 3], ["theme:rank_race", 4], ["theme:gate_brokers", 2]] },
    { id: "ty_risen", n: "Risen host", role: "infantry", wpn: "spear", kit: "light", ranks: 6, gap: 1.1, size: 200, w: 0.2, mods: [["theme:risen_lord", 20]] },
  ],

  faiths: [
    { id: "ty_listeners", n: "The Listeners", d: "The voice is the first honest god: it tells everyone exactly what they are worth. The faithful pray to be counted.", tags: ["faith:listeners", "organised"], w: 0.4, names: ["The Listeners of $", "The Counted", "The Ledger of Heaven"], mods: [["theme:listeners", 6]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Broken land", color: "#5a3a3a", size: [2, 4], count: [1, 2], where: "remote", d: "Country overrun when a gate broke and nobody came. Monsters rule it now." },
    { kind: "zone", n: "Gate field", color: "#4a6a9a", size: [1, 2], count: [1, 3], where: "any", d: "Ground where gates open thickest, fenced and quarantined." },
  ],

  storylines: [
    { id: "ty_gate_break", n: "The Gate at {place}", scale: "local", anchor: "town", w: 2, req: "gates",
      stages: {
        start: { h: "A red gate opens outside {place}", b: "A gate the colour of a wound has opened in the barley outside {place}. The broker's notice gives it thirty days. No guild has bid.", wait: [1, 2], next: [{ to: "guild_comes", w: 1, mods: [["rich", 2], ["theme:glowstone", 2]] }, { to: "porters_go", w: 2 }] },
        guild_comes: { h: "A guild clears the gate at {place}", b: "A guild of {realm} arrived on the twenty-ninth day and cleared it by dusk. {place} has been sent the bill.", fx: { treasury: -20, stability: 2 }, end: true },
        porters_go: { h: "The low-ranked of {place} go in", b: "With no guild coming, {person}, the lowest-ranked porter in {place}, has led a band of farmers and failed delvers into the gate.", wait: [1, 2], next: [{ to: "porter_rises", w: 1, mods: [["chance:low", 2], ["theme:weakest_delver", 3]] }, { to: "break", w: 1 }, { to: "cleared_cost", w: 1 }] },
        porter_rises: { h: "The porter of {place} comes back changed", b: "{person} came out alone, dragging the boss's head. The voice gave {person} a new rank this morning. That is not supposed to happen.", fx: { prestige: 4, flag: "riser" }, end: true },
        cleared_cost: { h: "The gate at {place} is cleared, at a price", b: "The farmers cleared it. Half of them did not come out. {place} will have glowstone lamps this winter and empty chairs.", fx: { pop: 0.95, treasury: 30 }, end: true },
        break: { h: "The gate at {place} breaks", b: "On the thirtieth day the gate split and the gnashers came out by the thousand. {place} is a broken land now.", fx: { pop: 0.8, unrest: 15, abandon_town: true }, end: true },
      } },
    { id: "ty_rank_war", n: "The Ranked War of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["tally", "has:rival"],
      stages: {
        start: { h: "{rival} poaches a top delver from {realm}", b: "{person}, one of the three highest-ranked delvers of {realm}, has taken service with {rival}. {ruler} calls it theft.", wait: [2, 5], fx: { relation: { rival: -20 } }, next: [{ to: "war", w: 1, mods: [["ruler:warlike", 2], ["atwar", 2]] }, { to: "bidding", w: 2 }] },
        bidding: { h: "{realm} bids for delvers abroad", b: "{realm} is offering titles and estates to any high-ranked delver who will come. Rival houses are doing the same. Gates in the poor provinces are being left to break.", wait: [3, 8], fx: { treasury: -60 }, next: [{ to: "war", w: 1 }, { to: "home_grown", w: 1, mods: [["academies", 2], ["learned", 2]] }] },
        war: { h: "{realm} goes to war over delvers", b: "The delvers of {realm} and {rival} meet in the field. The voice gives the same points for a person as for a beast.", fx: { war: "rival", unrest: 8 }, end: true },
        home_grown: { h: "{realm} trains its own", b: "{person2}, an old delver, has opened a school in {capital} for the low-ranked, teaching them to fight beyond their numbers. The rankings are starting to look wrong.", fx: { science: { warfare: 0.8 }, prestige: 5 }, end: true },
      } },
    { id: "ty_last_gate", n: "The Last Gate", scale: "world", anchor: "realm", w: 0.7, req: ["tally", { any: ["big", "prestigious", "learned"] }],
      stages: {
        start: { h: "No new gates open in {realm}", b: "For a full season no new gate has opened anywhere in {realm}. The guilds are delighted. The Listeners are terrified.", wait: [3, 6], next: [{ to: "voice_speaks", w: 2 }, { to: "quiet_age", w: 1 }] },
        voice_speaks: { h: "The voice speaks to everyone at once", b: "At dawn every person in {realm}, awakened or not, heard the voice say the same thing: 'Training complete.' {believer}, a Listener priest, has been preaching ever since.", wait: [2, 6], fx: { unrest: 15, stability: -8 }, next: [{ to: "great_gate", w: 2 }, { to: "refusal", w: 1, mods: [["ruler:brave", 2], ["chance:low", 1.5]] }] },
        quiet_age: { h: "The gates fade from {realm}", b: "The old gates are closing one by one. Glowstone prices have tripled and the guild houses are selling their towers.", fx: { treasury: -40, stability: 3 }, end: true },
        great_gate: { h: "A gate opens over {capital} the size of the sky", b: "Through it people can see a plain and an army, and hear the voice calling out ranks by name.", fx: { stability: -15, pop: 0.9, unrest: 20 }, end: true },
        refusal: { h: "{ruler} refuses the voice", b: "{ruler} and every delver of {realm} stood in the square of {capital} and refused, aloud, together. The voice has not spoken since. Nobody knows if that was a victory.", fx: { prestige: 12, stability: 6, discovery: "natural_philosophy" }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: true, who: "{survivor}, porter", text: "From the journal of {survivor}, a porter, copied word for word by a Guild tester in {year}: '[You have slain: Gnasher. Experience gained: 12. Rank: F. Calling: Porter. Remaining days of gate: 3.]' Below it, in the porter's own hand: 'It took four of us and a door to kill it. F is the lowest letter there is. The voice that says this has no mouth, and nobody can tell where it comes from.'" },
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: "partial", who: "Registrar of the Guild", text: "Preface to the Guild's Register of Ranks, {year} edition, signed by the registrar: 'A rank is a fact, like height. It is given once, at waking, by the voice, on a scale of letters from F upward. It cannot be changed by effort. Effort should therefore go into choosing the right party. Of 9,000 delvers registered, six have changed rank, all by clerical error.'" },
    { depth: "lore", about: "power", source: "archive", bias: "propaganda", reliable: false, who: "Handbill of the Silver Banner guild", points: "archive", text: "Handbill of the Silver Banner guild, posted in {place}, {year}: 'Glory, gold and glowstone! Not one delver of the Silver Banner lost this year! Apply at the guildhall, ranks D and above.' Beneath it, in pencil, unsigned: 'Count the new stones in their burial ground. I made it forty. The burial register is in {lead}.'" },
    { depth: "core", about: "truth:recruitment", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, Guild rank-tester", text: "Report of {investigator}, Guild rank-tester, from the camp beyond the open gate, {year}: 'The camp is a barracks: 4,000 cots, all sized for us. The banner over the command tent shows our world, and a number beside it. The number is 312. The Guild lists 312 uncleared gates. I watched it drop by one when word came of a clearance. The voice is drilling us for a war, and the number is how long we have left.'" },
    { depth: "core", about: "truth:recruitment", source: "person", bias: "true", reliable: "partial", who: "An old delver, to a nephew", points: "site:empty_gate", text: "Letter of an old delver to a nephew who has just woken, {year}: 'Every gate is a lesson. Fight in a line. Fight in a wall. Fight at night. Hold for thirty days. Who teaches a farmer to fight in a wall unless they mean to put the farmer in one? Before you sign with any guild, walk through the open gate at {lead} and look at the camp on the far side.'" },
    { depth: "core", about: "truth:recruitment", source: "heretic", bias: "exaggerated", reliable: "partial", who: "{believer}, Listener priest", points: "temple", text: "Sermon of {believer}, a Listener priest, at the gate-vigil of {place}, {year}, for which the preacher was later expelled: 'We are not being blessed. We are being mustered. Your rank is your place in the line. F ranks carry, E ranks hold, A ranks lead. Why would a god need porters? I have kept vigil at seventy new gates, and at every one the voice's first word was: Report. The vigil books are at {lead}.'" },
    { depth: "core", about: "truth:recruitment", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, A-rank delver", text: "Note found pinned inside the open gate, {year}, in the hand of {person}, a delver of rank A: 'The voice woke me at the third hour with an order: Assemble at the camp. Rank A. Calling: Captain. Bring your party of six. I have told nobody. I have left my ring and my house to my sister. If I am wrong, I will be home by supper.' Neither {person} nor the six came back." },
    { depth: "core", about: "truth:recruitment", source: "library", bias: "official", reliable: false, who: "Guild Primer of Gates", text: "From the Guild Primer of Gates, chapter one, {year}: 'The gates are a natural calamity, like floods, and the voice is no more than the world's own way of preparing us for them. Nothing lies beyond the last gate. Delvers who speak of camps, banners or musters are to be sent to the Guild physicians for a rest of not less than thirty days.'" },
    { depth: "core", about: "truth:spectacle", source: "person", bias: "true", reliable: "partial", who: "{survivor}, porter", text: "Statement of {survivor}, a porter, to the Guild rank office, {year}: 'When I did something stupid and brave, jumping the gnasher pit with a lamp in my teeth, the voice gave me a title for it: Daredevil. Who gives titles for stupidity? An audience does. I heard three things after: the title, my new rank, and a noise like a crowd drawing breath.'" },
    { depth: "core", about: "truth:spectacle", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, Guild rank-tester", points: "site:statue_temple", text: "Report of {investigator}, Guild rank-tester, {year}: 'Carved on the base of the smiling statue at {lead}, in the voice's own blue letters: Season one. Thank you for watching. Behind the throne are seats for ten thousand. We are being watched, for pleasure, by beings outside the world, and they bet on us. The token I found under seat 40 has odds carved on it.'" },
    { depth: "core", about: "truth:spectacle", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "A tanner of {place}, at a wake", text: "A tanner of {place} at the wake of {person}, a delver, {year}, as the priest wrote it down: 'I heard laughter in the gate when {person} fell. Not cruel laughter. The kind you hear at a play, when the clown trips. Then clapping, two or three hands, then a lot. Fourteen years in the gates, rank C. The voice gave the rest of us a title that night: Survivor's Guilt.'" },
    { depth: "core", about: "truth:spectacle", source: "archive", bias: "official", reliable: false, who: "{official}, chief clerk", text: "Guild finding, rank office of {realm}, {year}, countersigned by {official}: 'Reports of voices, applause and audiences within gates are symptoms of gate-fever and are not to be entered in official records. Of 140 such reports this year, all came from delvers inside a gate more than three days. Delvers who persist in reporting applause will be moved to porter duty.'" },
    { depth: "core", about: "truth:reformatting", source: "person", bias: "true", reliable: "partial", who: "A smith of {place}", points: "archive", text: "Complaint of a smith of {place} to the town council, {year}: 'My forge used to burn hot or cold depending on the coal. Since the gate by the mill was cleared, it burns at exactly level three, every time, whatever I feed it. Level three will not weld. I have lost two orders and an apprentice. I never asked for levels. The guild that cleared it should pay; its licence is filed in {lead}.'" },
    { depth: "core", about: "truth:reformatting", source: "traveller", bias: "exaggerated", reliable: "partial", cost: true, who: "A midwife of {place}", text: "A midwife of the town by the oldest gate, {place}, to a visiting physician, {year}: 'The babies are born with ranks now, seven of the last ten. I check the ledger before I check the breathing, because the mothers ask for the letter first. Last month {person} was born rank F, and the father was gone before the cord was cut. The mother wanted it written that the child is well.'" },
    { depth: "core", about: "truth:reformatting", source: "temple", bias: "pious", reliable: "partial", who: "{investigator}, Guild rank-tester", points: "temple", text: "A Listener hymn sung at the dawn vigil by the gate of {place}, copied by {investigator} in {year}: 'The old world was a blur. The new world has numbers. Praise the voice that makes all things clear.' The priest asked the faithful to pray for three clearances a week. The first hymnal, printed in year two of the Cracking and kept at {lead}, has a verse since dropped: 'Mourn the fire that was hot or cold with the wood.'" },
    { depth: "core", about: "truth:reformatting", source: "library", bias: "true", reliable: true, plain: true, who: "{investigator}, Guild rank-tester", text: "Paper read to the academy of {realm} by {investigator}, Guild rank-tester, {year}: 'I measured fire, weight and falling water within ten miles of twelve cleared gates and twelve uncleared ones. Near cleared gates, heat comes in numbered levels and a dropped stone falls at the same speed whatever its size. Near uncleared ones the old laws hold. Each clearance writes the voice's rules over the world's. We pay guilds to do it.'" },
    { depth: "core", about: "truth:reformatting", source: "library", bias: "official", reliable: false, who: "Guild Primer of Gates", text: "From the Guild Primer of Gates, chapter two, {year}: 'The laws of nature are unchanged since the Cracking. The voice affects the awakened and the gates, and nothing else. The Guild's own forges have shown no change in 40 years of records. Smiths who complain of levels should buy better coal, which the Guild sells at fair rates.'" },
    { depth: "sub", about: "sub:weakest_delver", source: "traveller", bias: "garbled", reliable: "partial", who: "The innkeeper of {place}", points: "cast:survivor", text: "Carters' gossip at the inn of {place}, {year}, as the innkeeper repeated it to a Guild clerk: 'They say the porter's rank went up. Then up again. F to C in one year, which never happens. The Guild sent three testers. The testers have resigned. The porter, {lead}, lives quietly and tells the story to anyone, for nothing.'" },
    { depth: "sub", about: "sub:red_gates", source: "person", bias: "true", reliable: true, who: "A delver, to the Guild pension office", text: "Letter of a delver to the Guild pension office, {year}: 'We were inside the red gate for a week by our count: seven days, six nights, one boss. When we came out, nine years had passed outside. My daughter was married. My wife had remarried. I am owed nine years of guild pay, and your office tells me the claim form only has room for one.'" },
    { depth: "sub", about: "sub:broken_isle", source: "traveller", bias: "true", reliable: "partial", who: "A harbour officer of {place}", points: "archive", text: "Report of a harbour officer of {place} to the crown, {year}: 'The brood-queen's envoy came ashore in a fishing boat with three attendants. It spoke our language badly and our customs perfectly, and bowed to the right people in the right order. It asked for a trade treaty. Under goods wanted it listed grain, iron and people, 200 a year, with a price for each. Its list is filed in {lead}.'" },
    { depth: "sub", about: "sub:stone_economy", source: "archive", bias: "official", reliable: true, who: "Treasury ledger of {realm}", text: "Treasury ledger of {realm}, {year}, with the treasurer's note in the margin: 'Revenue from gate licences now exceeds the land tax, 31,000 crowns against 28,000. Recommend the land tax be abolished. Recommend the gates be encouraged. Recommend nobody ask what encouraging a gate would involve, or where the nearest one is to this office.'" },
    { depth: "sub", about: "sub:risen_lord", source: "oral", bias: "exaggerated", reliable: "partial", who: "A goatherd of {place}", text: "A goatherd of {place}, describing the Lord of the Risen's army on the road, {year}: 'Shadow soldiers, four hundred at least, black as soot. They never speak and make no sound walking. But they still salute the way they did when they were alive. I knew one of them: Cobb, the blacksmith's boy. He still salutes left-handed, and he still can't keep in step.'" },
    { depth: "sub", about: "sub:dungeon_cooks", source: "traveller", bias: "true", reliable: true, who: "A traveller at a gate-kitchen in {place}", text: "A traveller's note on a gate-kitchen in {place}, {year}: 'Gnasher stew is better than it sounds, if you remove the glands. The cook insisted I remove the glands myself, at the table, with a spoon. Booked a year ahead; eight silver a head. My companion swallowed a gland by mistake and spoke only in numbers until morning.'" },
    { depth: "sub", about: "sub:gate_brokers", source: "person", bias: "true", reliable: true, who: "{official}, broker's clerk", points: "archive", text: "{official}, chief clerk to a gate broker, to a colleague, {year}: 'Nobody bid for the gate at the mill village: thirty days, 400 souls. We wrote it off. That is the word we use, written off. The village sent a petition with 112 marks on it. I filed it under Closed. The full write-off list for the year is kept at {lead}, if anyone wants to know where not to buy land.'" },
    { depth: "sub", about: "sub:voice_cults", source: "temple", bias: "pious", reliable: "partial", who: "{believer}, Listener priest", points: "site:silent_village", text: "Circular of the Listeners to all vigil-keepers, signed by {believer}, {year}: 'The voice has never spoken in one hill village, at {lead}. Its 300 people are unwoken and unranked, and say they are content. Send two priests to pray at its boundary stones until a gate opens there. A world that is not yet clear is a world not yet loved.'" },
    { depth: "site", about: "site:named_monster", source: "archive", bias: "redacted", reliable: "partial", who: "Kill-record of the Iron Lantern guild", points: "cast:investigator", text: "Kill-record of the Iron Lantern guild, {year}, entry 214: 'Boss, horned, cart-sized, at the gate near {place}. Bounty paid: 200 silver. Ledger name: [struck out].' Note from the guild master beneath: 'Do not copy monster ledger names into the record. Families read them.' A rank-tester has asked for the struck name; the request came from {lead}." },
    { depth: "site", about: "site:floating_ledger", source: "traveller", bias: "true", reliable: "partial", who: "A traveller on the road past {place}", text: "A traveller's letter from the road past {place}, {year}: 'The blue letters above the cairn changed while I watched. The rank went up by one, from A to a letter above A that the Guild's register has no column for. The dead woman under the stones did not move; she has been dead eleven years. The pedlar there sells chalk copies of her ledger at two coppers. I bought one. It is already out of date.'" },
  ],
};
