// The Underchord: the world is a song still being sung, and a counter-theme has been sung against it since the start.
export default {
  id: "underchord",
  name: "The Underchord",
  family: "power",
  pitch: "The world was sung into being and the song has never stopped; those who can hear it can join in to heal, build and unmake, and somewhere a discordant voice has been singing against the theme since the beginning.",
  slots: ["power-source", "cosmology", "power-access"],
  tone: ["mythic", "melancholy"],
  era: ["stone", "bronze", "medieval", "renaissance"],
  scale: "world",
  genres: ["fantasy", "mythic"],
  w: 1,
  excludes: [],
  pairs: [{ id: "unremembering", w: 2 }, { id: "walking_mountains", w: 1.5 }, { id: "drowned_crown", w: 1.5 }, { id: "long_dark", w: 1.5 }],

  power: {
    name: "songcraft", user: "songsmith", users: "songsmiths",
    taught: "The world was sung into being and the song has never stopped. Every thing has its own note and rhythm, and whoever can hear it can join in, to heal, to build or to unmake.",
    rules: ["You must match the thing's own note.", "A choir is a hundred times stronger than one voice; a solo singer is subtle, not strong.", "Overuse ruins the throat and the ear, and too much listening ruins the mind.", "A song once sung cannot be unsung."],
    forbidden: "Singing the counter-theme, or silencing a thing's note entirely.",
  },

  cast: [
    { role: "investigator", n: "a choirmaster-scholar of the conservatory who measures old notes", home: "inner", stance: "Trusts a tuning fork over a hymnal, and has begun to find the hymnals wrong." },
    { role: "official", n: "a cantor of the Choir's council, which keeps the hymnals", home: "capital", stance: "Holds that the song is eternal and that doubt is a wrong note to be sung over." },
    { role: "believer", n: "a copyist of a discord-cult who writes the struck verses back in", home: "remote", stance: "Believes the counter-theme must be sung again before the world shakes apart." },
    { role: "survivor", n: "a crystal-cutter of the ringing mountains, going deaf", home: "mountain", stance: "Sang the mountain hollow for the choirs' towers and wants to know what it cost." },
  ],

  truths: [
    { id: "discord_belongs", n: "The discord belongs in the song", d: "The great enemy's counter-theme was written into the song from the start, as its bass line. The Choir's founding council bound its singer under a grey valley, cut its verses from every hymnal, and has sung over it ever since. That left the world brittle and turned a partner into a monster. The world will only be stable once the counter-theme is let back in.", tags: ["truth:needed_discord"],
      known: [
        "Earthquakes in the lands of the Choir follow its great festivals, and the Choir answers each quake with louder singing. The Choir teaches that the counter-theme is pure malice and has no place in the song.",
        "Old hymnals have whole verses scraped out, marked in one margin as 'where the second voice was, before the council'. Discord-cult copyists such as {believer}, who write those verses back in, are punished with the loss of a hand.",
        "In a grey valley where nothing echoes, forty choir-stones face inward over a pit. {investigator} found the singer of the counter-theme bound in it, alive, under a carving signed by the Choir's founding council.",
        "Confirmed: the counter-theme was the song's bass line. The Choir's founding council bound its singer and cut it from every hymn, and the world has been brittle since. Each festival sung over the valley sets off the next quake.",
      ] },
    { id: "song_ending", n: "The song is ending", d: "The first voices that sang the world are falling silent one by one, and each that stops takes something with it: a species, a colour, a wind. Every great choir working draws on those voices, and since the great choirs were founded the fall has run three times faster. When the last one stops, the world ends, and the choirs are still recruiting.", tags: ["truth:song_ending"],
      known: [
        "Old bestiaries list beasts nobody can find, and old songsmiths remember a colour nobody can describe. The Choir teaches that the song is eternal and that silent places are the work of discord-cults and wraiths.",
        "In the humming cave, choirmasters' marks going back eleven hundred years show its note falling a little each century. {investigator} reads the most recent marks as falling three times faster than the old ones.",
        "The old hymnals list twelve humming caves, each beside a beast, a wind or a dye. Nine of those caves are silent now, and the things listed beside them are gone from the world.",
        "Confirmed: the first voices that sang the world are running down, and each that stops takes something with it. Every great choir working draws on them, and the fall has run three times faster since the great choirs were founded.",
      ] },
    { id: "we_are_notes", n: "We are notes, not singers", d: "Every mortal life is already written into the song, like a line in a score, and songsmiths only think they choose their notes. One mortal, a blind singer, has learned to read ahead in the score and change it. Every life the singer saves is paid for by someone else's line, rewritten to fill the bar.", tags: ["truth:sung_lives"],
      known: [
        "A blind singer sings dirges for people a week before they die. The priests call it murder by song. The Choir teaches that each soul is a free singer and no life is written before it is lived.",
        "Midwives say every newborn hums a tune of its own. A speaking stone, struck by {investigator}, describes the present year in a tongue ten thousand years dead, down to the price of rye.",
        "The blind singer's notebook says every life is written in the song like a line in a score, and that the singer can bend a bar. When the singer spared a child, a farmer's son died on the coast road in the same hour.",
        "Confirmed: lives are written in advance, and people sing the parts given to them. One blind singer has learned to read ahead and rewrite, and every life saved is paid for by a stranger's line.",
      ] },
  ],

  tags: ["worldsong"],

  subthemes: [
    { id: "song_paths", n: "The Song-Paths", d: "Some roads can only be walked by singing them, and the maps of the wanderers are melodies. Forget a bar and you are lost in a land you have crossed a hundred times.", w: 1.2, mods: [["nomadic", 2], ["steppe", 1.5], ["desert", 1.5]], tags: ["theme:song_paths"] },
    { id: "silent_city", n: "The Silent City", d: "In an old capital no sound carries: bells swing without ringing, and merchants trade in sign. The city's own note has stopped, and nobody knows why.", w: 0.6, truthLink: "song_ending", tags: ["theme:silent_city"], mark: { kind: "zone", n: "The hushed city", color: "#8a8aa0", size: [1, 1], where: "capital" } },
    { id: "discordant_heir", n: "The Discordant Heir", d: "A royal child can sing only the counter-theme. Glass cracks when she hums, and an old choirmaster weeps every time, and will not say whether from horror or relief.", w: 0.8, req: { any: ["monarchy", "dynastic"] }, truthLink: "discord_belongs", tags: ["theme:discordant_heir"] },
    { id: "ballad_carriers", n: "The Ballad-Carriers", d: "News travels in ballads. The bards are spies, propagandists and the only record of half the realm's battles, and the censors have begun banning tunes.", w: 1.1, req: { any: ["has:city", "urbane", "open_roads", "great_roads"] }, tags: ["theme:ballad_carriers"] },
    { id: "crystal_mines", n: "The Crystal Mines", d: "Singers cut resonant crystal free from the mountain with their voices. The rich buy it for their towers; the cutters go deaf by thirty and mad by forty.", w: 1, req: { any: ["mountain", "mountain_folk", "hills"] }, tags: ["theme:crystal_mines"], mark: { kind: "zone", n: "Ringing mountains", color: "#b0c8e0", size: [1, 2], where: "mountain" } },
    { id: "interval_heresy", n: "The Interval Heresy", d: "Two great choirs have split over a single interval in the creation hymn. Each calls the other's note blasphemy, and both have started recruiting soldiers.", w: 1, req: { any: ["organised", "zealous", "pious", "faith:one_god"] }, truthLink: "discord_belongs", tags: ["theme:interval_heresy"] },
    { id: "lost_verse", n: "The Lost Verse", d: "A missing stanza of the creation song survives in a children's skipping rhyme. Scholars have been following children around for a year.", w: 0.8, mods: [["scholarly", 1.5], ["learned", 1.5]], tags: ["theme:lost_verse"] },
    { id: "lullaby_wards", n: "The Lullaby Wards", d: "Mothers' songs are the oldest protective magic. In one valley the mothers have stopped singing, and night creatures have begun to come to the cradles.", w: 1, mods: [["hospitable", 1.5], ["forest_folk", 1.5], ["egalitarian", 1.3]], truthLink: "song_ending", tags: ["theme:lullaby_wards"] },
    { id: "dirge_singers", n: "The Dirge-Singers", d: "The dead are sung to rest by a guild of dirge-singers. A few have learned to sing the verse backwards, and the dead they sing for do not stay at rest.", w: 0.9, mods: [["faith:ancestors", 2.5], ["ancestor_bound", 2]], tags: ["theme:dirge_singers"] },
    { id: "drum_clans", n: "The Drum-Clans", d: "The steppe clans sing in rhythm, not melody, and their magic is all war: drums that stop a charging horse's heart, chants that keep a rider awake for a week.", w: 1, req: { any: ["steppe", "horse_lords", "nomadic", "tribal"] }, tags: ["theme:drum_clans"] },
    { id: "score_reader", n: "The Reader of the Score", d: "A blind singer sings dirges for people a week before they die. Lately she has started changing the words.", w: 0.7, req: { any: ["seers", "scholarly", "mystic"] }, truthLink: "we_are_notes", tags: ["theme:score_reader"] },
  ],

  sites: [
    { id: "humming_cave", n: "The Humming Cave of $", kind: "anomaly", where: "mountain", truthLink: "song_ending", d: "A cave that has hummed a single note for ten thousand years.",
      layers: {
        surface: { n: "One note", text: "A cave mouth on the mountain above {place} hums one low note, day and night. Goatherds tune their pipes to it. The oldest pipe found in the scree below, a bone flute, is about 900 years old and is tuned to a slightly higher note." },
        study: { n: "The Mother-note", text: "{investigator} matched the hum to the oldest note in the creation hymn, which the choirs call the Mother. The conservatory's bronze fork for the Mother, cast 400 years ago, now rings a hair higher than the cave. The fork has not changed. The cave has." },
        dig: { n: "The choirmasters' marks", points: "library", text: "On the wall are choirmasters' marks going back 1,140 years, one per generation. Side by side they show the note falling a little each century, and three times faster since the great choirs were founded. The old hymnals that list caves like this are kept in {lead}." },
        revelation: { n: "Running down", text: "This is one of the first voices that sang the world, still singing and slowly running down. Every working of the great choirs borrows from it. The hymnals list twelve such caves; nine are silent, and the beasts, winds and dyes listed beside them are gone. The choirs sing four services a day, and are recruiting." },
      } },
    { id: "sleepers_stage", n: "The Sleeper's Stage at $", kind: "wonder", where: "any", d: "An amphitheatre whose acoustics heal anyone who sleeps on its stage.",
      layers: {
        surface: { n: "The sick on the stage", text: "An old amphitheatre at {place} seats two thousand, and every night the sick come to sleep on its stage. A warden charges a copper a night and lays out straw. The queue for the stage begins at noon." },
        study: { n: "Waking in tune", text: "Sleepers wake healed of small hurts, cuts, sprains and coughs, and humming. {investigator} kept a ledger of 300 sleepers: 271 woke mended, and all 300 hummed the same long note for an hour. Broken bones do not mend." },
        dig: { n: "The tuning-stone", points: "site:humming_cave", text: "Beneath the boards is a single tuning-stone carved with one sustained note of the creation hymn, the Mother-note. It was cut to match a living note somewhere else. An arrow carved on its base points toward the cave at {lead}." },
        revelation: { n: "Back in tune", text: "The stone holds the Mother-note, and a sleeping body falls back into tune with it, so small hurts mend. The builders meant it for a theatre and never knew. A drunk actor found the cure 300 years ago by sleeping off a bad night on the stage. The warden's family has charged a copper ever since." },
      } },
    { id: "drowned_bell", n: "The Drowned Bell of $", kind: "anomaly", where: "any", d: "A bell under a lake that tolls when the realm is in danger.",
      layers: {
        surface: { n: "Tolling under water", text: "A bell is heard tolling from under a cold lake near {place}, some years and not others. Fishermen pull in their nets when it rings. The lake is 200 feet deep at the centre, and no bell tower has ever stood on its shore." },
        study: { n: "Before every disaster", text: "{investigator} set the tolling years from the village register beside the realm's chronicle. The bell rang before every invasion and every plague in 300 years: fourteen tollings, fourteen disasters. It rang three nights before the last plague, and nobody listened." },
        dig: { n: "Names on the rim", points: "archive", text: "Divers found the bell hanging from nothing at sixty feet. Cast into its rim are 31 names, a full choir, with the choirmaster's name first. The choir's roll for that year should be in {lead}." },
        revelation: { n: "Still singing", text: "A whole choir sang themselves into the bell, by their own vote, so that the realm would always be warned. All 31 voices are still singing inside it. The council called the tolling superstition until the last plague. It has now voted the choir a pension, payable to nobody." },
      } },
    { id: "unechoing_valley", n: "The Unechoing Valley of $", kind: "anomaly", where: "remote", truthLink: "discord_belongs", d: "A valley where birds do not sing and echoes do not return.",
      layers: {
        surface: { n: "No echo", text: "In a grey valley beyond {place} no bird sings and no shout comes back. Shepherds drive their flocks through it at a run. A horn blown at the valley mouth in {year} made no sound at all, though the player's cheeks were full." },
        study: { n: "The choir-stones", text: "Forty choir-stones ring the valley, all facing inward, all carved with the same hymn. {investigator} copied it: the creation hymn with every counter-theme verse struck out. The stones are a choir in rock, singing it without end." },
        dig: { n: "The pit", points: "archive", text: "Under the central stone is a pit where no sound carries at all. In it lies the singer of the counter-theme, bound in bronze and gagged with choir linen, alive. The names of the council who voted to bind it are cut into the lip; their minutes are in {lead}." },
        revelation: { n: "Gagged, not beaten", text: "The choirs never defeated the counter-theme. The Choir's founding council bound its singer here because its part sounded wrong to them, and cut its verses from every hymnal. The world has been brittle since: every great quake in the chronicle follows a choir festival. The minutes call it 'tidying the score'." },
      } },
    { id: "speaking_stones", n: "The Speaking Stones of $", kind: "dig", where: "any", truthLink: "we_are_notes", d: "Fossil stones that replay ancient voices when struck.",
      layers: {
        surface: { n: "The ringing bank", text: "A bank of pale stones near {place} rings like voices when struck. Children dare each other to hit them. A quarry opened here in {year} closed within a month, because the stones in the carts kept talking on the road." },
        study: { n: "Dead tongues", text: "Each stone, struck, replays a scrap of speech in a tongue ten thousand years dead. {investigator} recorded 80 scraps with a scribe and a tutor of old languages. Most are ordinary: weather, prices, a name called across a field." },
        dig: { n: "This year", points: "library", text: "One stone, struck, describes this very year in the old tongue: the harvest, a war, the reeve of {place} by name, and the price of rye to the penny. It also names a blind singer. The tutor's full translation was sent to {lead}." },
        revelation: { n: "Already written", text: "The song was written in full before anyone lived it. People do not choose their notes; they sing the parts written for them, and the stones are scraps of the score. A blind singer has learned to read ahead and change a bar. The same stone lists, in order, the strangers whose lines were changed to pay for it." },
      } },
    { id: "deep_organ", n: "The Deep Organ of $", kind: "ruin", where: "inner", d: "A broken organ in a ruined cathedral whose pipes reach underground.",
      layers: {
        surface: { n: "The broken organ", text: "A ruined cathedral at {place} holds a vast broken organ of 900 pipes. Rooks nest in the largest. The bellows rotted long ago, but on still nights the pipes give a low sound with nobody at the keys." },
        study: { n: "Pipes into rock", text: "The pipes do not stop at the floor. They run down into the bedrock; {investigator} lowered a lead weight 600 feet and did not touch bottom. Air moves up the pipes, warm, and smelling of ink." },
        dig: { n: "The scriptorium", points: "archive", text: "At the bottom of the deepest pipe, down a stair cut for the purpose, is a scriptorium: twelve desks, ink dried in the wells, and stacks of music in no hand anyone recognises. The cathedral's copying accounts are in {lead}." },
        revelation: { n: "Copied, not composed", text: "The pipes were built to listen, not to play. For three centuries the old choirs copied down music sent up from deep underground and published it as their own. A third of the Choir's hymnal came up these pipes, credited to the cathedral's choirmasters by name. Nobody has asked who sings at the bottom, or what it is owed." },
      } },
  ],

  beings: [
    { id: "spell_lark", n: "Spell-lark", kind: "bird", d: "A songbird that learns a sung working by ear and carries it for miles. Farmers set them loose with rain-songs in dry years.", danger: 0, biomes: ["grass", "tempforest", "coldsteppe"], look: { size: 0.2, group: [1, 6], move: "flock", speed: 40, col: "#a08a60", col2: "#e0d0a0", body: "bird", active: "day", visible: true } },
    { id: "echo_hound", n: "Echo-hound", kind: "predator", d: "A hound made of returned sound. It answers your call in your own voice, from behind you.", danger: 1, biomes: ["alpine", "badlands", "colddesert"], look: { size: 1.2, group: [2, 5], move: "pack", speed: 20, col: "#7a7a8a", col2: "#c0c0d0", body: "quad", active: "dusk", visible: false } },
    { id: "silence_wraith", n: "Silence-wraith", kind: "predator", d: "A being of no note. Where it passes, sound stops, and the things it touches forget how they were meant to sound.", danger: 2, biomes: ["tundra", "boreal", "badlands", "swamp"], look: { size: 2, group: [1, 1], move: "solo", speed: 6, col: "#e8e8f0", col2: "#b0b0c0", body: "biped", active: "night", visible: false } },
    { id: "wrong_note", n: "Wrong-note", kind: "beast", d: "A discord given flesh: too many joints, colours that make the eyes water, a body that seems to be in two places at once.", danger: 3, biomes: ["badlands", "peaks", "colddesert"], look: { size: 3, group: [1, 2], move: "solo", speed: 15, col: "#5a2a6a", col2: "#c0e040", body: "spider", active: "any", visible: true } },
  ],

  techs: [
    { id: "uc_work_chants", n: "Work-chants", field: "agriculture", level: 1, d: "Planting songs, drum-rhythms and lullabies: the first songcraft, sung by everyone." },
    { id: "uc_sacred_modes", n: "The sacred modes", field: "writing", level: 2, d: "Scales and modes set down as holy law, taught in temple choirs." },
    { id: "uc_notation", n: "Notation", field: "writing", level: 3, d: "Music written down as spell-scrolls, so that anyone who can read can perform a working." },
    { id: "uc_crystal_cutting", n: "Crystal-cutting", field: "metallurgy", level: 3, d: "Resonant crystal sung free of the rock and tuned for towers, ships and weapons." },
    { id: "uc_organs", n: "Mechanical organs", field: "engineering", level: 4, d: "Music boxes and great organs that play workings by themselves, with no singer at all." },
    { id: "uc_captured_song", n: "Captured song", field: "natural_philosophy", level: 5, d: "Song-power stored in wax and crystal, and resonance engines that run on it." },
  ],

  units: [
    { id: "uc_war_choir", n: "War choir", role: "magic", wpn: "staff", kit: "robe", ranks: 3, gap: 1.5, size: 60, w: 0.6, mods: [["theme:interval_heresy", 4], ["pious", 1.5]] },
    { id: "uc_drum_riders", n: "Drum-clan riders", role: "cavalry", mounted: 1, wpn: "spear", kit: "light", ranks: 3, gap: 2.5, size: 80, w: 0.3, mods: [["theme:drum_clans", 10]] },
  ],

  faiths: [
    { id: "uc_choir", n: "The Choir", d: "A faith of temple choirs that keep walls, harvests and weather in tune, and that cut the counter-theme verses from every hymnal.", tags: ["faith:uc_choir", "organised"], w: 1, names: ["The Choir of $", "The Harmonious Church", "The Great Chorus"], mods: [["pious", 1.5], ["urbane", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Silent zones", color: "#9a9aa8", size: [1, 2], count: [0, 2], where: "remote", d: "Grey, birdless lands where nothing echoes." },
  ],

  storylines: [
    { id: "uc_heir", n: "The Discordant Heir of {realm}", scale: "realm", anchor: "realm", w: 1.2, req: ["worldsong", { any: ["monarchy", "dynastic"] }],
      stages: {
        start: { h: "A royal child of {realm} sings a wrong note", b: "At the feast of naming, {person}, the youngest royal child of {realm}, sang the blessing back in the counter-theme. Glasses broke, and an old choirmaster wept.", wait: [2, 6], fx: { unrest: 6 }, next: [{ to: "hidden_away", w: 2 }, { to: "exiled", w: 1, mods: [["zealous", 2], ["theme:interval_heresy", 2]] }] },
        hidden_away: { h: "{person} is sent to the silent monks", b: "The child has been sent to a monastery of monks who never speak, to learn silence. Letters from the abbot are short and worried.", wait: [6, 14], next: [{ to: "harmony", w: 1, mods: [["tolerant", 2], ["mystic", 1.5]] }, { to: "discord_host", w: 1 }] },
        exiled: { h: "{person} is cast out of {realm}", b: "The choirs of {capital} declared the child a vessel of discord. {person} was put across the border with a horse and a servant, and not a word of farewell.", wait: [6, 14], next: [{ to: "discord_host", w: 2 }, { to: "harmony", w: 1 }] },
        harmony: { h: "{person} sings both themes at once", b: "On the solstice {person} stood before the choirs of {capital} and sang the theme and the counter-theme together. The cracks in the city walls closed, and the ground under the mountains gave a long, low rumble, like a sigh.", fx: { stability: 8, prestige: 10, discovery: "natural_philosophy" }, end: true },
        discord_host: { h: "The heir returns with a discordant host", b: "{person} has come back to {realm} at the head of an army of the outcast, singing a song that splits stone. The choirs of {capital} are singing against it day and night.", fx: { revolt: true, unrest: 15 }, end: true },
      } },
    { id: "uc_quiet", n: "The Quiet of {place}", scale: "local", anchor: "town", w: 1.3, req: "worldsong",
      stages: {
        start: { h: "Silence falls on the market of {place}", b: "At the third bell on market day, sound stopped across four streets of {place} and the river bridge. Inside the line, people shout and hear nothing. Traders have fled with half their stock. The edge has moved forty paces since morning, and the magistrate has sent for a choir.", wait: [1, 3], fx: { unrest: 10 }, next: [{ to: "choir_comes", w: 2 }, { to: "wraith", w: 1, mods: [["chance:low", 1.5]] }] },
        wraith: { h: "A pale thing is seen in the streets of {place}", b: "Folk of {place} have seen a tall white figure walking the streets at night. Wherever it goes, the silence spreads.", wait: [1, 3], next: [{ to: "choir_comes", w: 1 }, { to: "abandoned", w: 1 }] },
        choir_comes: { h: "A choir comes to sing {place} back", b: "{person}, a choirmaster, has brought forty singers to {place}. They sing from dawn to dusk at the edge of the silence.", wait: [2, 6], next: [{ to: "restored", w: 1 }, { to: "choir_lost", w: 1 }] },
        restored: { h: "Birdsong returns to {place}", b: "On the ninth day a blackbird sang in the square of {place}, and then the bells, and then everyone at once. {person}'s choir has been given the freedom of the town.", fx: { stability: 4 }, end: true },
        choir_lost: { h: "The choir at {place} falls silent", b: "One by one the singers' voices failed at the edge of the silence. {person} came back alone and has not spoken since. The silence grows a street a month.", fx: { unrest: 8, flag: "silence" }, end: true },
        abandoned: { h: "{place} is left to the silence", b: "The last families have walked out of {place} with their hands over their ears, though there is nothing to hear.", fx: { abandon_town: true, unrest: 6 }, end: true },
      } },
    { id: "uc_score", n: "The Score-Reader of {place}", scale: "local", anchor: "town", w: 1, req: "worldsong",
      stages: {
        start: { h: "A singer of {place} foretells a death", b: "{person}, a blind singer of {place}, sang a dirge for the miller a week before the mill-wheel caught the miller. Then for the baker. Then for the priest.", wait: [2, 5], fx: { unrest: 4 }, next: [{ to: "rewrites", w: 1 }, { to: "accused", w: 1, mods: [["zealous", 2], ["harsh_law", 1.5]] }] },
        accused: { h: "{person} is accused of murder by song", b: "The priests of {place} say the blind singer does not foretell the deaths but causes them. The singer has been taken to the cells.", wait: [2, 4], next: [{ to: "burned", w: 1 }, { to: "rewrites", w: 1 }] },
        rewrites: { h: "{person} changes a song", b: "{person} sang a dirge for a child of {place}, then stopped mid-verse and sang it differently. The child lived. The next morning a stranger died in the child's place.", wait: [3, 8], next: [{ to: "composer", w: 1 }, { to: "stops", w: 1 }] },
        composer: { h: "{person} vanishes with the score", b: "The blind singer of {place} has gone, leaving a note: 'Someone has to finish it.' Since then, the deaths in {realm} have come at regular intervals, like beats in a song.", fx: { stability: -6, flag: "composer" }, end: true },
        stops: { h: "{person} stops singing", b: "The blind singer of {place} has sworn never to sing again. The singer sits by the river in the evenings and listens instead, and sometimes smiles.", fx: { stability: 3 }, end: true },
        burned: { h: "{person} is burned in {place}", b: "The singer was burned in the square. In the smoke, people swear, they heard the singer finish the verse.", fx: { unrest: 8 }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "Conservatory primer of {realm}", text: "From the conservatory primer of {realm}, lesson one, {year} edition: 'The world was sung into being, and the song has never stopped. Every stone, river and body has its own note. Songcraft is joining in: match a thing's note and you can heal it, build with it or unmake it. Before you sing to a stone, listen to it for a year. It has been singing longer than you. Of forty students a year, three finish.'" },
    { depth: "lore", about: "power", source: "person", bias: "true", reliable: "partial", who: "A monk of the silent house", points: "library", text: "Wax tablet handed to {investigator} by a monk of the silent house above {place}, {year}, in answer to a question: 'We do not speak because every word is a note, and a note once sung cannot be unsung. We have heard enough of the song to be afraid of adding to it. We are 31. The last of us who spoke did so in the founder's time. The founder's journal is kept at {lead}.'" },
    { depth: "lore", about: "power", source: "oral", bias: "garbled", reliable: true, who: "A baker of {place}", text: "A baker of {place} to an apprentice, as noted by a travelling choir's scribe in {year}: 'Hum to the bread while it rises and it rises better. Everyone knows that. Low note for rye, a higher one for white. My mother hummed and her loaves were the best in three streets. The bakers' guild says it is superstition. The guild's bread is flat.'" },
    { depth: "core", about: "truth:discord_belongs", source: "heretic", bias: "heretic", reliable: true, who: "{believer}, discord-cult copyist", text: "From a score copied by {believer}, a discord-cult copyist, seized at {place} in {year}, with the copyist's note: 'The counter-singer was never the enemy. That voice was the bass line. You cut it out and wonder why the world sounds thin.' Below are 64 bars of the creation hymn with the counter-theme written back in. The arresting officers sang it through once; the crack in the cell wall closed." },
    { depth: "core", about: "truth:discord_belongs", source: "ruin", bias: "true", reliable: true, plain: true, who: "The Choir's founding council, carved in stone", text: "Carved on the inward face of a choir-stone in the unechoing valley, copied by {investigator} in {year}: 'We, the founding council of the Choir, bound the singer of the counter-theme under this stone to save the harmony. We were wrong. The counter-theme was in the song from the start; it is the bass line. The ground has shaken since the day we bound it. Forgive us. We did not know the harmony needed it.' Twelve names follow." },
    { depth: "core", about: "truth:discord_belongs", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, choirmaster-scholar", points: "library", text: "An old hymnal in the Choir's archive, examined by {investigator} in {year}: nineteen verses have been scraped from the vellum. In the margin, in a later choirmaster's hand: 'Where the second voice was, before the council.' The archive's register lists an unscraped copy as lent out that same year and never returned. The lending slip names {lead}." },
    { depth: "core", about: "truth:discord_belongs", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, mason of {place}", text: "Letter of {person}, a mason of {place}, to the Choir's council, {year}: 'My house fell in the quake after your solstice festival, as the house before it fell after the last one. My wife and our two girls were inside. Your cantor says the quakes are the enemy's malice. My father was a choir mason, and told me the valley stones were cut to hold the counter-singer down. Every festival you sing them louder. You are not fighting the shaking. You are causing it.'" },
    { depth: "core", about: "truth:discord_belongs", source: "temple", bias: "official", reliable: false, who: "{official}, cantor of the Choir", text: "Ruling of the Choir's council, read in every temple of {realm} by order of {official}, cantor, {year}: 'The counter-theme is pure malice, the voice of the enemy of all creation. It has no place in the song and never had. Earthquakes are its spite, and are answered by louder singing. Those who sing it are damned. Those who copy it lose one hand, and on a second offence the other.'" },
    { depth: "core", about: "truth:song_ending", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, choirmaster-scholar", text: "Choirmaster's mark cut in the humming cave beside eleven older ones, signed by {investigator}, {year}: 'The Mother-note has dropped again. In the oldest marks it shook the floor; now I must press my ear to the stone. This is one of the first voices that sang the world, and it is running down. By the marks it has fallen three times faster since the great choirs began. Every working we sing is drawn from it.'" },
    { depth: "core", about: "truth:song_ending", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, crystal-cutter", text: "Letter of {survivor}, a crystal-cutter going deaf, to a niece, {year}: 'There was a colour when I was young, between green and blue. The cutters called it vein-light. I cannot describe it now, and nobody can; I have asked forty people. Its singer stopped. I spent thirty years singing crystal out of the mountain for the choirs' towers, and I think I helped it stop.'" },
    { depth: "core", about: "truth:song_ending", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A fur trader at {place}", points: "temple", text: "A fur trader's account, told at {place} in {year}: 'In the far north there is a country where the wind has stopped for good. Nineteen years now. The air lies on the land like still water. The windmills stand idle, the ships sit in harbour, and the people there do not laugh much. Their old choir book named the wind and gave it a hymn. The hymn is kept at {lead}, and nobody sings it.'" },
    { depth: "core", about: "truth:song_ending", source: "heretic", bias: "exaggerated", reliable: "partial", who: "A pamphlet on the conservatory door", points: "site:humming_cave", text: "Pamphlet nailed to the conservatory door at {place}, {year}: 'Count the beasts in the old bestiaries: 212. Count the ones you can find today: 160. Each missing one was a voice in the choir, and nobody is replacing them. The old hymnals list twelve humming caves. Go and listen at the one at {lead}, then tell me the choirs should sing four services a day.'" },
    { depth: "core", about: "truth:song_ending", source: "library", bias: "official", reliable: false, who: "Book of Common Song", text: "From the Choir's Book of Common Song, preface, {year} edition, approved by {official}: 'The song is eternal and will be sung forever. Silent places are the work of discord-cults and wraiths, and our choirs will restore them all. A choir of forty can restore a silent street in nine days. Donations toward new choirs are welcome at every temple.'" },
    { depth: "core", about: "truth:we_are_notes", source: "ruin", bias: "true", reliable: "partial", who: "{investigator}, choirmaster-scholar", text: "Speaking stone 61, struck by {investigator} in {year}, translated from a tongue ten thousand years dead: 'And in the year of the long frost a blind singer in {place} will learn to read ahead, and will change a bar, and will be sorry.' The long frost came two winters ago. The scribe who took this down asked to be released from the survey and went home." },
    { depth: "core", about: "truth:we_are_notes", source: "person", bias: "true", reliable: true, plain: true, who: "The blind score-reader of {place}", text: "From the notebook of the blind score-reader of {place}, dictated to a niece in {year}: 'I do not sing the dirges. I only hear them early, because every life is already written into the song like a line in a score. We do not choose our notes. I have found that if I hum a different bar, the music bends. Last week I bent it for a child. A stranger on the coast road died that hour. The bar has to be filled.'" },
    { depth: "core", about: "truth:we_are_notes", source: "oral", bias: "garbled", reliable: "partial", who: "A midwife of {place}", points: "library", text: "A midwife of {place} to a conservatory student collecting songs, {year}: 'Every baby is born humming a tune nobody taught it. I have delivered six hundred and heard every one. Midwives say it is the tune of the child's whole life, if you know how to listen. The short tunes, we don't tell the mother about. My teacher wrote the tunes down for forty years, and her book is at {lead}.'" },
    { depth: "core", about: "truth:we_are_notes", source: "person", bias: "true", reliable: "partial", cost: true, who: "{person}, a farmer of {place}", text: "Petition of {person}, a farmer of {place}, to the magistrate, {year}: 'On the morning the blind singer changed the dirge for the reeve's child, my son was on the coast road with a cart of rye. The reeve's child lived. My son was found under the cart at noon, fourteen years old, and the oxen standing calm. The singer came to me weeping and said the bar had to be filled. I want the singer tried.'" },
    { depth: "core", about: "truth:we_are_notes", source: "temple", bias: "official", reliable: false, who: "{official}, cantor of the Choir", text: "Sermon of {official}, cantor of the Choir, at the high temple of {realm}, {year}: 'Each soul is a free singer, gifted by {deity} with its own voice and its own choice of song. No life is written before it is lived. The so-called score-readers are frauds or murderers, and the Choir has hanged three this year to prove it.'" },
    { depth: "sub", about: "sub:ballad_carriers", source: "traveller", bias: "propaganda", reliable: false, who: "A tavern ballad of {realm}", points: "archive", text: "A ballad sung in every tavern of {realm} in {year}, two coppers a printed sheet: 'And the king rode out at the head of his men, and not one coward among them.' The muster roll for that battle, in {lead}, shows the king forty miles away at a wedding, and lists 300 men who ran. The ballad-sellers are paid by the palace." },
    { depth: "sub", about: "sub:crystal_mines", source: "person", bias: "true", reliable: true, who: "{survivor}, crystal-cutter", text: "Pay docket of the ringing-mountain cut, {year}, made out to {survivor}, crystal-cutter: 'Three carts of tower crystal, at six silver the cart. Buyer: the Choir of {realm}, for its new bell-tower. Paid in advance.' On the back, in the cutter's hand: 'Left ear gone last month. The cutters say deaf by thirty, mad by forty. I am twenty-nine. The vein rang so sweet today I cried.'" },
    { depth: "sub", about: "sub:lost_verse", source: "oral", bias: "garbled", reliable: "partial", who: "{investigator}, choirmaster-scholar", points: "library", text: "Children's skipping rhyme of {place}, written down by {investigator}, who has followed the town's children for a year, {year}: 'Low note, high note, one note under; sing it backwards, break in thunder.' The rhyme's tune matches a stanza missing from every hymnal. The children say a girl taught it to them, and no girl in town knows it. The conservatory's file on the rhyme is in {lead}." },
    { depth: "sub", about: "sub:interval_heresy", source: "temple", bias: "pious", reliable: "partial", who: "Rule of the Eastern Choir", text: "From the Rule of the Eastern Choir, chapter four, read at every ordination, {year}: 'The fourth is holy, and the tritone is the ladder of the damned. Whoever sings the other interval sings the world's undoing.' The Western Choir's rule says the same thing word for word, with the two intervals swapped. Both choirs have hired two thousand soldiers since spring." },
    { depth: "sub", about: "sub:song_paths", source: "traveller", bias: "true", reliable: "partial", who: "A salt merchant crossing the flats", text: "A salt merchant's travel journal, crossing the flats east of {place}, {year}: 'My guide sang the whole way across, nine days. When she stopped to drink, the path stopped too: the ground ahead was only white, and we could not tell east from west. We waited until she could sing again. I paid thirty silver for the crossing. I would pay double.'" },
    { depth: "sub", about: "sub:dirge_singers", source: "archive", bias: "official", reliable: "partial", who: "Clerk of the Guild of Dirge-Singers", points: "archive", text: "By-laws of the Guild of Dirge-Singers, {year} copy: 'By-law nine. No member shall sing a dirge in reverse, nor teach it, nor hum it in jest.' The clerk's note: added after the funeral at {place}, where the deceased sat up at verse four and asked for soup. The minutes of the meeting that followed are in {lead}." },
    { depth: "sub", about: "sub:score_reader", source: "traveller", bias: "true", reliable: "partial", who: "A carter at the inn of {place}", points: "site:speaking_stones", text: "A carter to the room at the inn of {place}, {year}: 'The blind singer sang a dirge for the miller a week before the wheel took him. Then one for the baker. Now the singer won't sing at all. Every morning the singer walks out to the ringing stones at {lead} and strikes them one by one, listening. I asked why. The singer said: checking the score.'" },
    { depth: "sub", about: "sub:discordant_heir", source: "person", bias: "true", reliable: "partial", who: "An old choirmaster at court", points: "site:unechoing_valley", text: "Letter of an old choirmaster at the court of {realm} to {investigator}, {year}: 'When the princess hums, glass cracks; we have lost forty goblets this year. Yet when the princess hums, the crack in the palace wall closes by a finger's width. I wept the first time, and I will not write down why. Find out what the founding council buried in the valley at {lead}.'" },
    { depth: "site", about: "site:sleepers_stage", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A pilgrim at the amphitheatre of {place}", points: "site:humming_cave", text: "A pilgrim's letter from the amphitheatre at {place}, {year}: 'I slept on the stage three nights for my bad knee, at a copper a night. I woke mended, and humming one long note I cannot get out of my head. The warden says the note is cut into a stone under the boards, and that the same note comes out of a cave at {lead}. My wife says I hum in my sleep now.'" },
    { depth: "site", about: "site:drowned_bell", source: "oral", bias: "true", reliable: "partial", who: "A fisherman of {place}", text: "A fisherman of {place} to {investigator}, {year}: 'The bell under the lake rang three nights before the plague came. Nobody listened, and two hundred died in the town. Now we listen every night, in turns. My uncle dived for the bell once, sixty feet down, and came up with his palm cut on its rim and a name pressed into the cut. Not a family name. The priest looked it up: the choirmaster of the year the bell was cast.'" },
    { depth: "site", about: "site:deep_organ", source: "ruin", bias: "garbled", reliable: "partial", who: "The organist of the ruined cathedral", text: "Pinned to the organ bench in the ruined cathedral at {place}: a page of music in an unknown hand, dated {year}, and beneath it, in the organist's: 'I did not write this. I only copied what came up the pipe. That is the 47th page this year. The cantor publishes them in the hymnal under the cathedral choir's name, and pays me a candle a page.'" },
  ],
};
