// Vowfire: a trained life-aura sharpened by binding vows, and what the oldest vows have become.
export default {
  id: "vowfire",
  name: "Vowfire",
  family: "power",
  pitch: "Everyone carries a life-aura and a trained few can shape it; the deadliest are those who bind themselves with vows that would kill them if broken.",
  slots: ["power-access", "state-control"],
  tone: ["heroic", "grim"],
  era: ["medieval", "renaissance", "industrial", "modern"],
  scale: "personal",
  genres: ["fantasy", "shonen", "grimdark"],
  w: 1,
  excludes: [],
  pairs: [{ id: "nursery_sea", w: 3 }, { id: "hungerfruit", w: 1.5 }, { id: "downward_throat", w: 1.5 }, { id: "ward_walls", w: 1.5 }, { id: "unquiet_gate", w: 1.5 }],

  power: {
    name: "vowfire", user: "kindler", users: "kindlers",
    taught: "Every living body gives off a steady warmth of will. A trained kindler can hold it in, harden it, send it out or shape it into a working that fits their temperament. A vow, freely sworn, narrows the fire and makes it burn hotter.",
    rules: ["Each person is born to one of six temperaments and works poorly outside it.", "The narrower and harsher the vow, the stronger the fire it feeds.", "A broken vow takes its forfeit: the power, a limb or a life.", "Overuse burns the years: old kindlers look older than they are."],
    forbidden: "Forcing another's fire open by violence, or feeding one's own fire with the lives of others.",
  },

  cast: [
    { role: "investigator", n: "an unbinder who clears old vows from houses and fields for a fee", home: "border", stance: "Has seen too many oaths that will not end, and wants to know where they all start." },
    { role: "official", n: "a senior monk of the founding monastery who keeps the bowl-test registers", home: "inner", stance: "Believes the six temperaments keep order, and is under vow not to doubt them." },
    { role: "believer", n: "a captain of the edge expeditions", home: "coast", stance: "Believes there is a fire past the last coast, and that the shoals are a door, not a wall." },
    { role: "survivor", n: "the last of the Eye-Clan, sworn to a killing vow", home: "remote", stance: "Wants every buyer of the clan's eyes dead, and the monastery that started it with them." },
  ],

  truths: [
    { id: "vows_outlive", n: "Vows outlive their makers", d: "A kindler who dies with a vow unfulfilled does not let it go: the vow keeps burning without a body, stronger for having nothing else to spend itself on. Much of what people call haunting is old oaths still trying to finish. The present war was sworn by a dead queen two hundred years ago, and every soldier who dies in it is paying her debt.", tags: ["truth:vows_outlive"],
      known: [
        "Unbinders, who clear old vows from houses and fields for a fee, report hauntings that behave like unfinished oaths: soldiers holding a vanished bridge, doors that will not stay shut. The monasteries' books say a vow dies with the body that swore it.",
        "A royal council forbade any reading of a dead queen's death-oath, at the same session that declared war on the old enemy. Every war with that enemy since has begun within a year of the queen's death-day.",
        "{investigator} found the queen's oath cut into a lintel in a sealed vault, still warm after two hundred years, and a dead master's tomb where the master's vow still fights and maims trespassers.",
        "Confirmed: vows outlive the people who swear them and burn on until they are fulfilled. The present war is a dead queen's oath, still driving two realms to fight, and every soldier who dies in it pays her debt.",
      ] },
    { id: "seventh_temperament", n: "The six were imposed", d: "The founding monastery designed the six temperaments and the bowl-test that sorts every child, to rank and govern. A seventh temperament exists, born only among a people the monastery has hunted for centuries, and its fire can unmake a vow. The monks enter every seventh child as Fourth and take it away, and they swear a vow to keep doing it.", tags: ["truth:seventh_temperament"],
      known: [
        "Every child is sorted at seven by the bowl-test into one of six temperaments, and the result decides their schooling, trade and marriage. A leaflet asks why the old monastery walls have brackets for seven bowls.",
        "A village shrine keeps a black bowl no child may touch. Over it, certain hands turn the salt black, as no known temperament does. {investigator} found four such hands in one hill family.",
        "Under the shrine lies a register of 212 struck names and a monastery order: children 'of the seventh reading' are to be entered as Fourth and taken to the House. The countersigning monk still keeps the registers.",
        "Confirmed: there were always seven temperaments. The founding monastery struck out the seventh, whose fire unmakes vows, and hunted its people, the Eye-Clan among them. Its monks enter seventh children falsely, under vow.",
      ] },
    { id: "world_vow", n: "The land is under a vow", d: "The first people of the continent swore that they and their children would never leave its shores, and that restriction is what makes the land's fire so strong. The edge of the known map is the edge of the vow, and the shoals are full of ships whose crews tried to cross it. Whoever crosses it for good breaks the oath for everyone, and every kindler's fire with it.", tags: ["truth:world_vow"],
      known: [
        "Edge expeditions sail past the last charted coast, and few come back. Survivors say their fire went cold beyond the shoals, and some say a crewmate's went out entirely. The academies blame seamanship and supply.",
        "The Promise Shoals hold hundreds of wrecks at the end of every chart, and the recovered logs all end with the same line, in different hands and languages: 'We shall not go back.'",
        "Under the oldest wrecks stand markers older than any kingdom, carved with a vow. {believer}'s rubbing, translated at the academy, is an oath by a whole people never to cross the water again.",
        "Confirmed: the first people swore that they and their children would never leave, and that oath feeds every kindler's fire. The edge of the map is the edge of the vow, and whoever crosses it for good breaks it for everyone.",
      ] },
  ],

  tags: ["aura", "vows"],

  subthemes: [
    { id: "climbing_tower", n: "The Climbing Tower", d: "A city has grown around a fight-tower two hundred floors high. Commoners climb for purses and learn the fire the hard way; the top floors are owned, and the fights there are fixed.", w: 1.4, req: { any: ["urbane", "has:city", "mercantile"] }, mods: [["martial", 1.5], ["gov:merchant", 1.5]], tags: ["theme:fight_tower"] },
    { id: "seeker_trial", n: "The Seekers' Trial", d: "Each year the Licensed Seekers hold an open trial: four hundred enter, a dozen leave with a licence. This year's class is already being spoken of as the one that will define the age.", w: 1.3, mods: [["martial", 1.5], ["open_roads", 1.5], ["warrior_code", 1.5]], tags: ["theme:seeker_trial"] },
    { id: "grudge_blades", n: "The Grudge-Blade Trade", d: "Weapons that hold the fire of their murdered makers fetch fortunes. They are cursed, they are hungry, and the smiths who make the most of them have been dying young.", w: 1, req: { any: ["artisans", "mercantile", "guilds"] }, truthLink: "vows_outlive", tags: ["theme:grudge_blades"] },
    { id: "eye_clan", n: "The Last of the Eye-Clan", d: "A small people whose eyes burn crimson under strong feeling were massacred for them. Their eyes are sold in jars to collectors; one survivor has sworn a vow that will kill everyone who bought one, and then him.", w: 0.9, truthLink: "seventh_temperament", tags: ["theme:eye_clan"], mark: { kind: "zone", n: "The Emptied Hills", color: "#7a3030", size: [1, 2], where: "remote" } },
    { id: "unarmed_city", n: "The City That Swore Off Steel", d: "A town once vowed, all together, never to bear arms. Within its walls no blade cuts and no arrow flies straight, and every warlord nearby wants to know how to break it.", w: 0.8, req: { any: ["pacifist", "egalitarian", "gov:commune", "pious"] }, truthLink: "world_vow", tags: ["theme:unarmed_city"], mark: { kind: "zone", n: "The Unarmed Ward", color: "#c8b878", size: [1, 1], where: "inner" } },
    { id: "vow_exorcists", n: "The Unbinders", d: "Haunted fields, cursed heirlooms and houses where doors will not stay shut: unbinding old vows has become a trade, and a dangerous one.", w: 1.2, req: { any: ["ancestor_bound", "faith:ancestors", "near:ruins", "seers"] }, truthLink: "vows_outlive", tags: ["theme:unbinders"] },
    { id: "bowl_test", n: "The Bowl-Test Registry", d: "Every child is tested at seven with a bowl of salt, a feather and a flame. The result is written in the parish book and decides their schooling, their trade and whom they may marry.", w: 1.2, req: { any: ["hierarchical", "autocracy", "organised", "harsh_law"] }, truthLink: "seventh_temperament", tags: ["theme:bowl_registry"] },
    { id: "vow_lawyers", n: "The Vow-Notaries", d: "Merchants seal deals with witnessed vows, and so do kings. A guild of notaries drafts them, and the notary always knows the clause the parties hid from each other.", w: 1, req: { any: ["mercantile", "urbane", "gov:merchant", "republic"] }, tags: ["theme:vow_notaries"] },
    { id: "hive_kin", n: "The Hive That Learned", d: "A new insect-kin people has learned the fire by instinct, faster than any monastery could teach it. Their queen has begun keeping humans in pens.", w: 0.6, req: { any: ["jungle", "marsh", "hot", "forest"] }, tags: ["theme:hive_kin"], mark: { kind: "zone", n: "The Brood-Country", color: "#5a6a2a", size: [2, 4], where: "remote" } },
    { id: "edge_expeditions", n: "The Edge Expeditions", d: "Ships and caravans set out past the last charted coast, financed by houses who want what is out there. Few return, and those that do speak of a fire that is not like ours.", w: 1, req: { any: ["seafaring", "has:port", "coastal", "frontier"] }, truthLink: "world_vow", tags: ["theme:edge_expeditions"] },
    { id: "oath_guard", n: "The Oath-Guard", d: "The ruler's guard have all sworn the same vow: never to lie to the throne. It makes them perfect witnesses and terrible friends, and a usurper's first act is always to kill them.", w: 1, req: { any: ["monarchy", "autocracy"] }, mods: [["divine_right", 1.5], ["hierarchical", 1.5]], tags: ["theme:oath_guard"] },
  ],

  sites: [
    { id: "master_tomb", n: "The Duelling Tomb of $", kind: "ruin", where: "mountain", truthLink: "vows_outlive", d: "A hill tomb where every trespasser is forced to fight a dead master.",
      layers: {
        surface: { n: "Practice swords", text: "A barrow in the hills above {place} is sealed with a bronze door. Locals leave wooden practice swords at the threshold, three hundred or more, stacked like firewood. Young kindlers come to bow at the door, and do not go in." },
        study: { n: "Undefeated", text: "The parish book records the master's vow: never to lose a duel. The master died undefeated, of a fever, in {year}, with three challengers still waiting at the inn. {investigator} traced the three challengers. All three later went into the tomb." },
        dig: { n: "The seated bones", points: "archive", text: "The master's bones sit cross-legged facing the door. The air around them is warm, and anyone who steps within reach is struck before they see a movement. {investigator} lost two fingers proving it. The notary's copy of the master's vow is in {lead}." },
        revelation: { n: "Undefeated still", text: "The vow has no body and needs none. The master swore never to lose, died before anyone could test it, and the vow has fought every trespasser since: 41 by the parish count, all dead or maimed. It learns from every bout. The village makes a good living selling practice swords." },
      } },
    { id: "vow_stands", n: "The Oath-Stands of $", kind: "ruin", where: "any", d: "A ruined arena whose stands are carved with thousands of vows.",
      layers: {
        surface: { n: "Carved seats", text: "Tiers of overgrown stone seating near {place} ring an old arena, and every block is cut with small letters. Goats graze the upper tiers. The local mason quarries a seat now and then and sells it as a doorstep, carvings and all." },
        study: { n: "Witnessed vows", text: "Each carving is a spectator's vow, witnessed by the crowd: to win, to avenge, to protect a name. {investigator} copied two thousand of them. About one in ten has a tick beside it, as if the arena kept score of which were kept." },
        dig: { n: "The ring under the sand", points: "library", text: "Beneath the arena floor lies a second ring of vows, older, all in one hand, binding the arena itself to hold every vow sworn in it. The handwriting matches the founders' charter of the monastery, held at {lead}." },
        revelation: { n: "A machine for oaths", text: "The arena was built to gather witnessed oaths and draw fire from them, ten thousand promises a season. The founding monastery built it and fed its masters from it for a century. When the crowds stopped coming the masters' fire faded, and the order closed the arena and called it a pagan ruin." },
      } },
    { id: "unknown_bowl", n: "The Seventh Bowl at $", kind: "anomaly", where: "remote", truthLink: "seventh_temperament", d: "A testing-bowl that reacts to no known temperament.",
      layers: {
        surface: { n: "The black bowl", text: "A village shrine at {place} keeps an old testing bowl of black clay that the monks will not let children touch. Every other testing bowl in the realm is white. The shrine-keeper dusts it weekly and has never been told why." },
        study: { n: "Black salt", text: "Over a white bowl, a child's hand makes the salt dissolve, grow or move, as the six temperaments do. Over this one, certain hands make it do none of these: the salt simply goes black. {investigator} found four such hands in one hill family." },
        dig: { n: "The struck register", points: "cast:official", text: "Under the shrine floor is a register of 212 names, every one struck through, and a burned order of the founding monastery: such children are 'to be entered as Fourth and brought to the House'. The countersignature is that of {lead}, who still keeps the registers." },
        revelation: { n: "Seven from the start", text: "There were seven temperaments from the beginning. The founding monastery struck the seventh from the books because its fire unmakes vows, and the monastery rules by vows. Its children were entered as Fourth and taken to the House. None of the 212 names appears in any register again." },
      } },
    { id: "edge_wrecks", n: "The Promise Shoals of $", kind: "dig", where: "coast", truthLink: "world_vow", d: "A graveyard of ships at the edge of charted water.",
      layers: {
        surface: { n: "The reef of hulls", text: "Hulls lie stacked on a reef off {place}, at the end of every chart: 340 by the harbourmaster's count, and more under the water. Salvagers strip them for timber. No salvager will sail past the reef." },
        study: { n: "The same last line", text: "{investigator} read sixty recovered logs. Every one ends with the same line, in different hands and languages: 'We shall not go back.' The entries before it describe the crew's fires going cold, one by one, aboard ship." },
        dig: { n: "Older than ships", points: "cast:believer", text: "Under the oldest wrecks stand stone markers older than any ship, carved with a vow in a script no living scholar reads. A rubbing was taken by an expedition captain, {lead}, now fitting out a ship." },
        revelation: { n: "Where the oath catches", text: "The first people swore that they and their children would never leave this land, and the land's fire comes from that oath. The shoals are where it catches those who try: crews whose fire goes out a mile past the reef. The houses that fund the expeditions write the losses off as weather." },
      } },
    { id: "rule_isle", n: "The Game-Island of $", kind: "wonder", where: "coast", d: "An island where a dead master's working still makes everyone follow the rules of a game.",
      layers: {
        surface: { n: "Permission to eat", text: "Sailors from {place} avoid an island where, they say, you cannot so much as eat without permission. Fishermen leave its bay to the seals. A customs boat went in, in {year}, and came back a week later with the crew still arguing about the rules." },
        study: { n: "Cards in pockets", text: "Visitors find printed cards in their pockets. Each card is a power, each power has a rule, and breaking a rule costs the card. {investigator} came back with nine cards and a tenth, in plain print: 'Penalty: one year.' The unbinder was on the island for a week and came home a year greyer." },
        dig: { n: "Nine chairs", points: "library", text: "At the island's heart is a hall of nine chairs around a table. Eight hold very old people, still playing. The ninth is empty and warm. A rulebook on the table names the founder, a master kindler whose papers are kept in {lead}." },
        revelation: { n: "The game goes on", text: "A master kindler swore to build a game no one could cheat at, and the vow built an island with its own laws. The master died sixty years ago in the ninth chair. The vow keeps the game running and the eight players alive, and none may leave until somebody wins." },
      } },
  ],

  beings: [
    { id: "hive_kin", n: "Hive-kin", kind: "beast", d: "Man-sized insect-folk who learned the fire by instinct. Clever, organised, and very hungry.", danger: 3, biomes: ["rainforest", "swamp", "savanna", "dryforest"], look: { size: 1.9, group: [3, 12], move: "swarm", speed: 11, col: "#4a5a2a", col2: "#b8a040", body: "insect", active: "any", visible: true } },
    { id: "vow_wraith", n: "Vow-wraith", kind: "beast", d: "An unfinished oath with no body left, a warm wind that still tries to do what it swore.", danger: 2, biomes: ["grass", "tempforest", "badlands", "coldsteppe", "alpine"], look: { size: 1.7, group: [1, 1], move: "solo", speed: 6, col: "#c86a3a", col2: "#f0d0a0", body: "biped", active: "night", visible: false } },
    { id: "sworn_hound", n: "Sworn hound", kind: "predator", d: "A tracking dog bound by its handler's vow to one quarry. It does not tire until that quarry is dead.", danger: 2, biomes: ["grass", "tempforest", "boreal", "coldsteppe"], look: { size: 1.1, group: [1, 3], move: "pack", speed: 15, col: "#3a3028", col2: "#c87830", body: "quad", active: "any", visible: true } },
  ],

  techs: [
    { id: "vf_opening", n: "The slow opening", field: "medicine", level: 1, d: "Monastic breathing that opens a novice's fire over years without killing them." },
    { id: "vf_bowl_test", n: "The bowl-test", field: "natural_philosophy", level: 2, d: "Salt, feather and flame: a standard test that sorts every child into a temperament." },
    { id: "vf_hardened_skin", n: "Hardened fire", field: "warfare", level: 2, d: "Drilled kindlers wrap themselves in fire that turns a sword cut into a bruise." },
    { id: "vf_vow_law", n: "Vow law", field: "writing", level: 3, d: "Witnessed vows written up like contracts; treaties and trade deals bound with fire." },
    { id: "vf_grudge_forging", n: "Grudge-forging", field: "metallurgy", level: 4, d: "Weapons quenched in a dying smith's fire. They strike harder, and they remember." },
    { id: "vf_rule_spaces", n: "Rule-spaces", field: "arcana", level: 5, d: "A master's vow made into a place: a room, a ship, an island with laws of its own." },
  ],

  units: [
    { id: "vf_kindlers", n: "Sworn kindlers", role: "magic", wpn: "sword", kit: "light", ranks: 2, gap: 2.5, size: 30, w: 1.5, mods: [["theme:seeker_trial", 3], ["theme:fight_tower", 2], ["warrior_code", 2]] },
    { id: "vf_oath_guard", n: "Oath-guard", role: "infantry", wpn: "spear", kit: "plate", ranks: 3, gap: 1.2, size: 60, w: 0.5, mods: [["theme:oath_guard", 8], ["monarchy", 1.5]] },
  ],

  govs: [
    { id: "vf_sworn_crown", n: "Sworn crown", d: "The ruler and every minister rule under witnessed vows of office, and those who break them burn.", tags: ["gov:sworn_crown", "monarchy"], w: 0.4, forms: ["Sworn Crown of $", "Oathbound Realm of $"], ruler: "Oath-King", mods: [["theme:oath_guard", 4], ["theme:vow_notaries", 3], ["divine_right", 1.5]] },
  ],

  mapMarks: [
    { kind: "zone", n: "Vow-ground", color: "#b07040", size: [1, 3], count: [1, 3], where: "any", d: "Land where an old oath still holds: no fire burns, no metal rusts, or no lie can be spoken." },
    { kind: "zone", n: "Haunted field", color: "#5a4a5a", size: [1, 2], count: [0, 2], where: "border", d: "An old battlefield where the vows of the fallen never let go." },
  ],

  storylines: [
    { id: "vf_rookie_class", n: "The Rookie Class of {place}", scale: "local", anchor: "town", w: 2, req: "aura",
      stages: {
        start: { h: "The Seekers' trial opens at {place}", b: "Four hundred hopefuls crowd into {place} for the trial. The talk of the inns is {person}, a farm child who swears they have never had a lesson in their life.", wait: [1, 3], next: [{ to: "trial_deaths", w: 2 }, { to: "rival_vow", w: 1, mods: [["martial", 1.5], ["warrior_code", 2]] }] },
        trial_deaths: { h: "The trial at {place} turns lethal", b: "A third of the entrants did not come back from the second stage. The examiners call it regrettable and expected. {person} came back carrying {person2}, a rival, on their back.", wait: [2, 4], fx: { unrest: 5 }, next: [{ to: "licensed", w: 2 }, { to: "rival_vow", w: 1 }] },
        rival_vow: { h: "Two rookies swear against each other in {place}", b: "{person} and {person2} have sworn a witnessed vow: neither will take a licence until the other is beaten. The notaries say it is the hottest young fire they have ever seen.", wait: [3, 8], fx: { flag: "rival_vow" }, next: [{ to: "licensed", w: 1 }, { to: "vow_breaks", w: 1, mods: [["chance:low", 2], ["unstable", 1.5]] }] },
        licensed: { h: "A licence for the farm child of {place}", b: "{person} walked out of the last stage with a Seeker's licence and a vow nobody else has heard. The houses of {realm} are already bidding for their service.", fx: { prestige: 4, science: { warfare: 0.4 } }, end: true },
        vow_breaks: { h: "A vow breaks in {place}", b: "{person2} struck from behind in the final bout. The vow took its forfeit on the spot: {person2} will never kindle again, and {person} has left {place} without a word.", fx: { unrest: 6, stability: -2 }, end: true },
      } },
    { id: "vf_dead_oath", n: "The Old Oath of {realm}", scale: "realm", anchor: "realm", w: 1.5, req: ["aura", { any: ["atwar", "has:rival", "unstable"] }],
      stages: {
        start: { h: "Unbinders find a living vow in {capital}", b: "Workmen opening an old vault in {capital} found the air hot and the walls carved with one sentence, sworn by a forgotten queen of {realm}: that her enemies' line would end.", wait: [2, 6], next: [{ to: "war_explained", w: 2 }, { to: "sealed_again", w: 1, mods: [["pious", 1.5], ["ruler:traditionalist", 2]] }] },
        war_explained: { h: "The scholars of {realm} trace the war to a dead queen", b: "{investigator}, an unbinder, claims every war with the old enemy has broken out within a year of the queen's death-day. The vow is unfulfilled, and it keeps driving the two realms to fight.", wait: [4, 10], fx: { stability: -4, flag: "dead_oath" }, next: [{ to: "fulfil", w: 1, mods: [["ruler:cruel", 3], ["ruler:warlike", 2], ["atwar", 2]] }, { to: "unbind", w: 1, mods: [["learned", 2], ["ruler:just", 2], ["ruler:scholar", 2]] }, { to: "unbinder_dies", w: 1 }] },
        sealed_again: { h: "The vault in {capital} is bricked up", b: "{ruler} has ordered the vault closed and its workmen paid for their silence. The air in the street above is still warm in winter.", fx: { stability: 2 }, end: true },
        fulfil: { h: "{ruler} vows to finish the queen's oath", b: "Rather than fight the dead, {ruler} has chosen to finish what she swore. The armies of {realm} march, and every kindler in them feels the old fire at their backs.", fx: { war: "rival", prestige: 6, unrest: 10 }, end: true },
        unbind: { h: "The queen's vow is unbound", b: "{investigator} spent a winter in the vault and came out grey-haired and silent. For the first time in two centuries, the warm wind in {capital} has stopped.", fx: { stability: 10, prestige: 5, discovery: "arcana" }, end: true },
        unbinder_dies: { h: "The unbinder of {capital} is found burned", b: "{investigator} was found dead in the vault, burned from the inside with no mark of flame on the skin. The vow will not let anyone end it except by killing its enemies.", fx: { unrest: 8, stability: -5 }, end: true },
      } },
    { id: "vf_black_bowl", n: "The Black Bowl of {place}", scale: "local", anchor: "town", w: 1, req: ["aura", { any: ["hierarchical", "organised", "harsh_law", "autocracy"] }],
      stages: {
        start: { h: "A bowl turns black at the testing in {place}", b: "At the yearly testing in {place}, the salt in the bowl went black under a child's hand. The monk tore the page out of the book, and {person}'s family left that night.", wait: [1, 4], next: [{ to: "hunted", w: 2 }, { to: "hidden", w: 1, mods: [["hospitable", 2], ["egalitarian", 2]] }] },
        hunted: { h: "Monks hunt a child through {realm}", b: "Riders of the founding monastery are searching the roads for {person}. They carry an order older than {realm} itself.", wait: [3, 8], fx: { unrest: 6 }, next: [{ to: "taken", w: 1 }, { to: "unmakes", w: 1, mods: [["chance:low", 2], ["unstable", 1.5]] }] },
        hidden: { h: "{place} hides a child from the monks", b: "The village of {place} swears, together, that there was never a child named {person}. The monks cannot break a vow that many people share.", fx: { stability: 3, flag: "seventh_hidden" }, end: true },
        taken: { h: "The black-bowl child is taken", b: "{person} was caught at a ferry and taken to the monastery. The testing books of {realm} have been quietly reprinted.", fx: { stability: 2, unrest: 4 }, end: true },
        unmakes: { h: "Vows break all across {realm}", b: "Cornered, {person} reached out with a fire nobody had seen before. Every vow within a mile came undone: guards forgot their oaths, notaries' contracts went blank, and two lords died of forfeits they had not earned.", fx: { stability: -12, unrest: 15, discovery: "natural_philosophy" }, end: true },
      } },
  ],

  fragments: [
    { depth: "lore", about: "power", source: "library", bias: "official", reliable: true, who: "Handbook of the Licensed Seekers", text: "From the Licensed Seekers' handbook, first page, {year} edition: 'Every living body gives off a warmth of will. We call it vowfire, and a trained kindler can shape it. Fire held in is armour. Fire sent out is a fist. Fire narrowed by a vow is a blade, and a blade cuts both ways. Of four hundred entrants to the trial, twelve pass. Of those twelve, the ones who swear vows fight best and die first.'" },
    { depth: "lore", about: "power", source: "temple", bias: "pious", reliable: "partial", who: "A monastery primer, annotated", text: "A monastery primer, page nine, in the copy held at the House library, {year}: 'The vow is the vanity of the impatient. The patient student needs no oath to burn brightly.' Beneath it, in another hand: 'Then why do all six masters of this House swear them?' Beneath that, in a third: 'Ask {official}.' The lending card shows the primer was taken out forty times in one year." },
    { depth: "lore", about: "power", source: "oral", bias: "exaggerated", reliable: "partial", who: "Broadsheet of the fight-tower of {place}", text: "Broadsheet sold outside the fight-tower of {place}, {year}, one copper: 'THE BUTCHER OF THE NINETIETH FLOOR swore a vow to fight only with the left hand! Since then: 63 bouts, no losses! Bets are open on the day the Butcher forgets! Odds at the tower bookmaker, ground floor. The tower accepts no liability for forfeits.'" },
    { depth: "core", about: "truth:vows_outlive", source: "ruin", bias: "true", reliable: true, plain: true, who: "{investigator}, unbinder", text: "Report of {investigator}, unbinder, on the sealed vault under {place}, {year}: 'Cut into the lintel: I will not rest until the last of them is in the ground. The letters are warm to the touch after two hundred years. A queen swore it on her deathbed and never finished it. A vow does not die with the body that swore it. It keeps burning, stronger for having nothing else to spend itself on. This one is why we are at war.'" },
    { depth: "core", about: "truth:vows_outlive", source: "person", bias: "true", reliable: "partial", who: "{investigator}, unbinder", points: "archive", text: "Notebook of {investigator}, unbinder, {year}: 'Third haunting this month on the old frontier. All three the same: a soldier's vow to hold a bridge. The bridge went in a flood eighty years ago. They are holding the air where it was, and carts that try the ford are turned back. Fee: twelve silver each. I could not unbind them; I could not find the end of the oath. The muster roll with their names is in {lead}.'" },
    { depth: "core", about: "truth:vows_outlive", source: "archive", bias: "redacted", reliable: "partial", who: "Minutes of the royal council of {realm}", points: "archive", text: "Minutes of a royal council of {realm}, {year}, item three: '...the Queen's death-oath, as recorded by the notaries, is not to be read aloud in this chamber, nor copied, nor...' The rest of the item is blacked out. The same session declared war on the old enemy, by nine votes to none. The notaries' register of royal oaths is in {lead}." },
    { depth: "core", about: "truth:vows_outlive", source: "oral", bias: "garbled", reliable: "partial", cost: true, who: "A nurse at a deathbed in {place}", text: "A nurse at the deathbed of {person}, an old kindler of {place}, to the family, {year}: 'Don't let the old one swear anything now. Whatever you swear on your deathbed, you'll be doing forever.' {person} swore anyway, that the farm would stay in the family. It has. Three tenants in nine years, none past a month; no buyer will stay a night. The family lives in town now, paying tax on 60 acres it cannot enter." },
    { depth: "core", about: "truth:vows_outlive", source: "library", bias: "official", reliable: false, who: "Monastery treatise on vows", text: "From the founding monastery's Treatise on Vows, chapter six, {year} copy: 'A vow lives in the body that swore it, and dies with that body. So-called vow-hauntings are a matter for physicians of the mind, not for unbinders, whose trade preys on the grieving. In 300 years the House has recorded no vow outliving its maker.'" },
    { depth: "core", about: "truth:seventh_temperament", source: "archive", bias: "redacted", reliable: "partial", who: "{investigator}, unbinder", points: "archive", text: "An order of the founding monastery, its seal cut away, found by {investigator} under a shrine in {year}: 'Children of the seventh reading are to be entered as Fourth and brought to the House. Their parents are to be told the child has gone to study. The monk who makes the entry is to swear on it.' 212 names follow, all struck through. The House's intake ledger is kept in {lead}." },
    { depth: "core", about: "truth:seventh_temperament", source: "heretic", bias: "heretic", reliable: true, who: "A leaflet in the testing hall of {place}", points: "site:unknown_bowl", text: "A leaflet left in the testing hall of {place}, {year}: 'Six bowls, they tell you. Count the brackets in the old monastery walls: there are seven. Count the names struck from the registers. Then ask why a black bowl sits in the shrine at {lead}, and why no child may touch it.'" },
    { depth: "core", about: "truth:seventh_temperament", source: "person", bias: "true", reliable: true, plain: true, who: "A monk of the founding monastery, dying", text: "Deathbed statement of a monk of the founding monastery, taken by {investigator}, {year}: 'For 31 years I tested children at the bowls. There are seven temperaments, not six. The founders made the six to rank people, and struck the seventh because its fire unmakes vows, and our order rules by vows. I entered forty seventh children as Fourth and sent them to the House. I swore to do it. I am breaking that vow now, and I know the forfeit.'" },
    { depth: "core", about: "truth:seventh_temperament", source: "person", bias: "true", reliable: "partial", cost: true, who: "{survivor}, last of the Eye-Clan", text: "Letter of {survivor}, last of the Eye-Clan, to the founding monastery, {year}: 'My sister's bowl went black at the testing when she was seven. Your monk wrote her down as Fourth and took her to the House. That same year your riders burned our hills. You told the realm it was for our eyes. It was for the seventh fire, which runs in our blood. I have sworn a vow that ends with you. Every monk who wrote a false entry is on my list.'" },
    { depth: "core", about: "truth:seventh_temperament", source: "library", bias: "official", reliable: false, who: "Monastery treatise on temperaments", text: "From the founding monastery's Treatise on Temperaments, preface, {year}: 'The six temperaments are a natural division, as fixed as the four winds, observed independently by every school in the known world. No seventh has ever been recorded. Rumours of black salt are spread by salt merchants selling cheap stock.'" },
    { depth: "core", about: "truth:world_vow", source: "ruin", bias: "true", reliable: true, plain: true, who: "{believer}, expedition captain", text: "Rubbing taken by {believer}, expedition captain, from a marker stone at the end of the shoals, {year}, with the academy's translation: 'We and our children will not go back across the water. Let the land keep us, and keep us strong.' The academy's note: the script is a thousand years older than any kingdom. This is a vow sworn by a whole people, it feeds the fire of every kindler alive, and the shoals are its edge." },
    { depth: "core", about: "truth:world_vow", source: "traveller", bias: "exaggerated", reliable: "partial", cost: true, who: "{believer}, expedition captain", text: "Log of {believer}, captain of an edge expedition, {year}, day 19: 'A mile beyond the shoals my fire went cold. Old Barek's went cold and then went out, and Barek with it, at the rail, at noon. We were 32; we are 27. The sea was not hostile. It was simply not ours. I have turned back. The house that paid for this voyage will want its 4,000 crowns.'" },
    { depth: "core", about: "truth:world_vow", source: "temple", bias: "pious", reliable: "partial", who: "{investigator}, unbinder", points: "temple", text: "The founders' hymn, sung at the shore festival of {place} every spring, as written down by {investigator} in {year}: 'Here we swore and here we stay; the land remembers what we say.' At the end of the festival every child of seven throws a stone into the sea and steps back from the water. Nobody can say why. The second verse, sung only in the oldest hymnal at {lead}, runs: 'Whoever sails and does not turn, unmakes the oath, and all fires burn out.'" },
    { depth: "core", about: "truth:world_vow", source: "library", bias: "official", reliable: false, who: "Academy report on the edge expeditions", text: "Report of the academy of {realm} on the edge expeditions, {year}: 'The failure of the edge expeditions is a matter of seamanship and supply. Of nine voyages, seven were badly provisioned. There is nothing past the known coasts that a well-found ship and a disciplined crew cannot master. The academy will advise any house that pays its fee.'" },
    { depth: "sub", about: "sub:climbing_tower", source: "person", bias: "true", reliable: true, who: "A fighter of the tower, to a sister", text: "Letter of a fighter of the fight-tower at {place} to a sister at home, {year}: 'Floor 140. The man I fought today had been told to lose. I could see it in his face; he kept looking at the box where the owners sit. I won anyway. They have stopped my winnings, eighty silver, for breach of form. The top sixty floors are owned, and every bout up there is fixed.'" },
    { depth: "sub", about: "sub:seeker_trial", source: "library", bias: "propaganda", reliable: false, who: "Notice of the Licensed Seekers", text: "Notice of the Licensed Seekers, posted at {place} before the trial, {year}: 'The Seekers' trial is demanding but fair, and every entrant is under the eye of an examiner at all times. Of last year's 400 entrants, twelve earned a licence. The Seekers regret the 131 who did not return from the second stage, and remind entrants to settle their debts beforehand.'" },
    { depth: "sub", about: "sub:grudge_blades", source: "traveller", bias: "exaggerated", reliable: "partial", who: "A buyer's agent at the auction in {place}", points: "archive", text: "A buyer's agent writing from the blade auction at {place}, {year}: 'The sword screamed when the hammer fell. Everyone in the room heard it. The buyer paid double, 900 crowns, and smiled. The smith who forged it died at 34, like the last three smiths of that forge, and the blade holds the smith's fire. Its maker's dying vow is filed with the notaries at {lead}.'" },
    { depth: "sub", about: "sub:eye_clan", source: "oral", bias: "true", reliable: true, who: "A woman of {place}, overheard", points: "cast:survivor", text: "A woman of {place} to a neighbour, overheard by a magistrate's clerk, {year}: 'My cousin keeps two red eyes in a jar on the mantel, bought for 300 crowns. They glow when my cousin quarrels with the household. I have stopped visiting. They say the last of the Eye-Clan has sworn to kill every buyer, and the name going round is {lead}. My cousin laughs at that, and has hired two guards.'" },
    { depth: "sub", about: "sub:unarmed_city", source: "archive", bias: "official", reliable: "partial", who: "Report to the war council of {realm}", points: "archive", text: "Report to the war council of {realm}, {year}: 'The siege of the unarmed town failed. Two thousand arrows were loosed; they turned in the air and fell into the moat. The townsfolk swore together, 300 years ago, never to bear arms, and no blade cuts inside the walls. We recommend a negotiated toll. The town's founding vow is copied in {lead}.'" },
    { depth: "sub", about: "sub:bowl_test", source: "person", bias: "true", reliable: "partial", who: "{official}, monk of the founding monastery", text: "From the diary of {official}, a monk of the founding monastery, {year}: 'Today I wrote a child down as Second. The child's salt did not move as Second salt moves; it went black at the rim. I wrote what I was told to write. That is the ninth this year. I sleep well, because the vow I swore at ordination lets me.'" },
    { depth: "sub", about: "sub:vow_lawyers", source: "archive", bias: "redacted", reliable: true, who: "A notarised trade vow of {place}", text: "A notarised trade vow between two houses of {place}, {year}, sworn for twenty years on 4,000 crowns of grain. In the middle of the page is a blank space a hand wide, where a clause has been burned out, neatly, by fire. Only the notary who drafted it knows what it said. The notary's fee for the draft was double the usual." },
    { depth: "sub", about: "sub:hive_kin", source: "traveller", bias: "true", reliable: true, who: "A border captain in the brood-country", text: "A border captain's report from the brood-country, {year}: 'They do not fight like animals. They fight like a monastery's best class, all at once, and they learned it in one season. We lost forty men in an hour. Prisoners we got back say the queen keeps humans in pens and watches them train.'" },
    { depth: "sub", about: "sub:oath_guard", source: "person", bias: "true", reliable: true, who: "A guardsman's widow of {place}", text: "A guardsman's widow of {place}, to the magistrate, {year}: 'My husband swore the oath-guard's vow, never to lie to the throne. So in eleven years he never told the king anything at all, and that is what got him killed. The usurper had all sixty of the guard hanged in the first hour, and asked them nothing.'" },
    { depth: "sub", about: "sub:vow_exorcists", source: "person", bias: "true", reliable: "partial", who: "{investigator}, unbinder", points: "site:master_tomb", text: "Price list of {investigator}, unbinder, pinned up in an inn at {place}, {year}: 'Doors that will not shut: 4 silver. Cursed heirloom: 10 silver. Haunted field: 12. Battlefield: by arrangement. Dead master's tomb: not taken, on any terms. Two of my guild went into the tomb at {lead}. I keep what came back of them in a small box.'" },
    { depth: "sub", about: "sub:edge_expeditions", source: "traveller", bias: "exaggerated", reliable: "partial", who: "Prospectus of a house of {place}", points: "site:edge_wrecks", text: "Prospectus of a trading house of {place} for an edge expedition, {year}, captained by {believer}: 'Shares at 50 crowns. Beyond the last coast lies a fire not like ours. Our captain has seen the markers on the shoals at {lead} and believes they mark a door, not a wall. Previous voyages: 9. Returned: 2. Past losses are no guide to future returns.'" },
    { depth: "site", about: "site:vow_stands", source: "library", bias: "garbled", reliable: "partial", who: "A gazetteer of {realm}", text: "Entry in a gazetteer of {realm}, {year}: 'Old arena, ruinous, near {place}. Seats for some ten thousand. Every block is carved with promises; the mason's lads sell them as doorsteps at three coppers. The founding monastery calls it pagan and forbids its novices to visit. The novices visit.'" },
    { depth: "site", about: "site:rule_isle", source: "traveller", bias: "garbled", reliable: "partial", who: "A sailor of {place}", points: "library", text: "A sailor's letter from the harbour at {place}, {year}: 'On that island I was handed a card that said I could not speak until I had eaten. There was no food. I went two days hungry and silent. I have never been so frightened by a piece of paper. The cards are still in my sea-chest. The captain says the island's rulebook is copied in {lead}.'" },
  ],
};
